allocators.h
typedef std::basic_string<char, std::char_traits<char>, secure_allocator<char> > SecureString
static size_t GetSystemPageSize()
Determine system page size in bytes
void LockObject(const T &t)
References LockedPageManager::instance, LockedPageManagerBase< Locker >::LockRange.
Referenced by CKey::Derive, CExtKey::SetMaster, ECC_Start, CKey::CKey.
void UnlockObject(const T &t)
References memory_cleanse, LockedPageManager::instance, LockedPageManagerBase< Locker >::UnlockRange.
Referenced by CKey::Derive, CExtKey::SetMaster, ECC_Start, CKey::~CKey.