amount.h
typedef int64_t CAmount
const CAmount COIN
const CAmount CENT
const CAmount MAX_MONEY
No amount larger than this (in DRKSLK) is valid.
bool MoneyRange(const CAmount &nValue)
Referenced by GetMinFee, CTransactionPoS::GetValueOut, CTransactionPoS::ConnectInputs, CTransaction::CheckTransaction, CTransaction::GetValueOut, AmountFromValue, CWallet::GetChange, CWallet::GetDebit, CWallet::GetCredit, CWalletTx::GetAvailableCredit, CWalletTx::GetAnonymizableCredit, CWalletTx::GetDenominatedCredit, CWalletTx::GetAvailableWatchOnlyCredit.