argon2.h
ARGON2_MIN_LANES
Referenced by validate_inputs.
ARGON2_MAX_LANES
Referenced by main.
ARGON2_MIN_THREADS
Referenced by validate_inputs.
ARGON2_MAX_THREADS
Referenced by main.
ARGON2_SYNC_POINTS
Referenced by argon2_core, index_alpha, fill_memory_blocks.
ARGON2_MIN_OUTLEN
Referenced by validate_inputs.
ARGON2_MAX_OUTLEN
ARGON2_MIN_MEMORY
Referenced by validate_inputs.
ARGON2_MIN
Referenced by main.
ARGON2_MAX_MEMORY_BITS
Referenced by main.
ARGON2_MAX_MEMORY
Referenced by main.
ARGON2_MIN_TIME
Referenced by validate_inputs.
ARGON2_MAX_TIME
Referenced by main.
ARGON2_MIN_PWD_LENGTH
Referenced by validate_inputs.
ARGON2_MAX_PWD_LENGTH
ARGON2_MIN_AD_LENGTH
Referenced by validate_inputs.
ARGON2_MAX_AD_LENGTH
ARGON2_MIN_SALT_LENGTH
Referenced by validate_inputs.
ARGON2_MAX_SALT_LENGTH
ARGON2_MIN_SECRET
Referenced by validate_inputs.
ARGON2_MAX_SECRET
ARGON2_FLAG_CLEAR_PASSWORD
Referenced by finalize, initial_hash, initial_kat.
ARGON2_FLAG_CLEAR_SECRET
Referenced by initial_hash, initial_kat.
ARGON2_FLAG_CLEAR_MEMORY
ARGON2_DEFAULT_FLAGS
Referenced by argon2_hash, Argon2d_Hash.
Argon2_ErrorCodes
Argon2_type
typedef enum Argon2_ErrorCodes argon2_error_codes
typedef int(* allocate_fptr) (uint8_t **memory, size_t bytes_to_allocate))(uint8_t **memory, size_t bytes_to_allocate)
typedef void(* deallocate_fptr) (uint8_t *memory, size_t bytes_to_allocate))(uint8_t *memory, size_t bytes_to_allocate)
typedef struct Argon2_Context argon2_context
typedef enum Argon2_type argon2_type
int argon2_core(argon2_context *context, argon2_type type)
References validate_inputs, ARGON2_OK, Argon2_d, Argon2_i, ARGON2_INCORRECT_TYPE, Argon2_Context::m_cost, ARGON2_SYNC_POINTS, Argon2_Context::lanes, Argon2_instance_t::memory, Argon2_instance_t::passes, Argon2_Context::t_cost, Argon2_instance_t::memory_blocks, Argon2_instance_t::segment_length, Argon2_instance_t::lane_length, Argon2_instance_t::lanes, Argon2_instance_t::threads, Argon2_Context::threads, Argon2_instance_t::type, initialize, fill_memory_blocks, finalize.
Referenced by argon2_hash, argon2d, argon2i, verify_d, verify_i, Argon2d_Hash.
int argon2i_hash_encoded(const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void *pwd, const size_t pwdlen, const void *salt, const size_t saltlen, const size_t hashlen, char *encoded, const size_t encodedlen)
Hashes a password with Argon2i, producing an encoded hash t_cost Number of iterations m_cost Sets memory usage to m_cost kibibytes parallelism Number of threads and compute lanes pwd Pointer to password pwdlen Password size in bytes salt Pointer to salt saltlen Salt size in bytes hashlen Desired length of the hash in bytes encoded Buffer where to write the encoded hash encodedlen Size of the buffer (thus max size of the encoded hash) Different parallelism levels will give different results Returns ARGON2_OK if successful
References argon2_hash, Argon2_i.
int argon2i_hash_raw(const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void *pwd, const size_t pwdlen, const void *salt, const size_t saltlen, void *hash, const size_t hashlen)
Hashes a password with Argon2i, producing a raw hash t_cost Number of iterations m_cost Sets memory usage to m_cost kibibytes parallelism Number of threads and compute lanes pwd Pointer to password pwdlen Password size in bytes salt Pointer to salt saltlen Salt size in bytes hash Buffer where to write the raw hash hashlen Desired length of the hash in bytes Different parallelism levels will give different results Returns ARGON2_OK if successful
References argon2_hash, Argon2_i.
int argon2d_hash_encoded(const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void *pwd, const size_t pwdlen, const void *salt, const size_t saltlen, const size_t hashlen, char *encoded, const size_t encodedlen)
References argon2_hash, Argon2_d.
int argon2d_hash_raw(const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void *pwd, const size_t pwdlen, const void *salt, const size_t saltlen, void *hash, const size_t hashlen)
References argon2_hash, Argon2_d.
int argon2_hash(const uint32_t t_cost, const uint32_t m_cost, const uint32_t parallelism, const void *pwd, const size_t pwdlen, const void *salt, const size_t saltlen, void *hash, const size_t hashlen, char *encoded, const size_t encodedlen, argon2_type type)
References ARGON2_PWD_TOO_LONG, ARGON2_OUTPUT_TOO_LONG, ARGON2_SALT_TOO_LONG, ARGON2_MEMORY_ALLOCATION_ERROR, Argon2_Context::out, Argon2_Context::outlen, Argon2_Context::pwd, CONST_CAST, Argon2_Context::pwdlen, Argon2_Context::salt, Argon2_Context::saltlen, Argon2_Context::secret, Argon2_Context::secretlen, Argon2_Context::ad, Argon2_Context::adlen, Argon2_Context::t_cost, Argon2_Context::m_cost, Argon2_Context::lanes, Argon2_Context::threads, Argon2_Context::allocate_cbk, Argon2_Context::free_cbk, Argon2_Context::flags, ARGON2_DEFAULT_FLAGS, argon2_core, ARGON2_OK, encode_string, ARGON2_ENCODING_FAIL.
Referenced by argon2i_hash_encoded, argon2i_hash_raw, argon2d_hash_encoded, argon2d_hash_raw, argon2_verify.
int argon2i_verify(const char *encoded, const void *pwd, const size_t pwdlen)
Verifies a password against an encoded string encoded String encoding parameters, salt, hash pwd Pointer to password Returns ARGON2_OK if successful
References argon2_verify, Argon2_i.
int argon2d_verify(const char *encoded, const void *pwd, const size_t pwdlen)
References argon2_verify, Argon2_d.
int argon2_verify(const char *encoded, const void *pwd, const size_t pwdlen, argon2_type type)
References Argon2_Context::adlen, Argon2_Context::saltlen, Argon2_Context::outlen, Argon2_Context::ad, Argon2_Context::salt, Argon2_Context::out, ARGON2_MEMORY_ALLOCATION_ERROR, decode_string, ARGON2_DECODING_FAIL, argon2_hash, Argon2_Context::t_cost, Argon2_Context::m_cost, Argon2_Context::threads, ARGON2_OK.
Referenced by argon2i_verify, argon2d_verify.
int argon2d(argon2_context *context)
References argon2_core, Argon2_d.
int argon2i(argon2_context *context)
References argon2_core, Argon2_i.
int argon2di(argon2_context *context)
int argon2ds(argon2_context *context)
int argon2id(argon2_context *context)
int verify_d(argon2_context *context, const char *hash)
References Argon2_Context::outlen, ARGON2_OUT_PTR_MISMATCH, argon2_core, Argon2_d, ARGON2_OK, Argon2_Context::out.
int verify_i(argon2_context *context, const char *hash)
References Argon2_Context::outlen, ARGON2_OUT_PTR_MISMATCH, argon2_core, Argon2_i, ARGON2_OK, Argon2_Context::out.
const char* error_message(int error_code)
References ARGON2_ERROR_CODES_LENGTH.