base58.h
typedef CDarkSilkExtKeyBase<CExtKey, 74, CChainParams::EXT_SECRET_KEY> CDarkSilkExtKey
typedef CDarkSilkExtKeyBase<CExtPubKey, 74, CChainParams::EXT_PUBLIC_KEY> CDarkSilkExtPubKey
std::string EncodeBase58(const unsigned char *pbegin, const unsigned char *pend)
Encode a byte sequence as a base58-encoded string. pbegin and pend cannot be NULL, unless both are.
Referenced by EncodeBase58, EncodeBase58Check, MessageModel::getAddressOrPubkey, StartRPCThreads, smsglocalkeys, smsggetpubkey, SecureMsgGetLocalPublicKey, CStealthAddress::Encoded, BOOST_AUTO_TEST_CASE.
std::string EncodeBase58(const std::vector< unsigned char > &vch)
Encode a byte vector as a base58-encoded string
References EncodeBase58.
bool DecodeBase58(const char *psz, std::vector< unsigned char > &vch)
Decode a base58-encoded string (psz) into a byte vector (vchRet). return true if decoding is successful. psz cannot be NULL.
Referenced by DecodeBase58, DecodeBase58Check, importstealthaddress, SecureMsgAddAddress, CStealthAddress::SetEncoded, IsStealthAddress, BOOST_AUTO_TEST_CASE.
bool DecodeBase58(const std::string &str, std::vector< unsigned char > &vchRet)
Decode a base58-encoded string (str) into a byte vector (vchRet). return true if decoding is successful.
References DecodeBase58.
std::string EncodeBase58Check(const std::vector< unsigned char > &vchIn)
Encode a byte vector into a base58-encoded string, including checksum
References hash, Hash, EncodeBase58.
Referenced by CBase58Data::ToString.
bool DecodeBase58Check(const char *psz, std::vector< unsigned char > &vchRet)
Decode a base58-encoded string (psz) that includes a checksum into a byte vector (vchRet), return true if decoding is successful
References DecodeBase58, hash, Hash, base_uint< BITS >::end.
Referenced by DecodeBase58Check, CBase58Data::SetString.
bool DecodeBase58Check(const std::string &str, std::vector< unsigned char > &vchRet)
Decode a base58-encoded string (str) that includes a checksum into a byte vector (vchRet), return true if decoding is successful
References DecodeBase58Check.