blake2b.c
G
ROUND
TRY
Referenced by blake2b_long.
const uint64_t blake2b_IV[8][8]
const unsigned int blake2b_sigma[12][16][12][16]
static BLAKE2_INLINE void blake2b_set_lastnode(blake2b_state *S)
static BLAKE2_INLINE void blake2b_set_lastblock(blake2b_state *S)
static BLAKE2_INLINE void blake2b_increment_counter(blake2b_state *S, uint64_t inc)
static BLAKE2_INLINE void blake2b_invalidate_state(blake2b_state *S)
static BLAKE2_INLINE void blake2b_init0(blake2b_state *S)
int blake2b_init_param(blake2b_state *S, const blake2b_param *P)
References __blake2b_state::h, __blake2b_state::outlen, __blake2b_param::digest_length.
Referenced by blake2b_init, blake2b_init_key.
int blake2b_init(blake2b_state *S, size_t outlen)
References BLAKE2B_OUTBYTES, __blake2b_param::digest_length, __blake2b_param::key_length, __blake2b_param::fanout, __blake2b_param::depth, __blake2b_param::leaf_length, __blake2b_param::node_offset, __blake2b_param::node_depth, __blake2b_param::inner_length, __blake2b_param::reserved, __blake2b_param::salt, __blake2b_param::personal, blake2b_init_param.
Referenced by blake2b, blake2b_long, initial_hash, HashBlake2b.
int blake2b_init_key(blake2b_state *S, size_t outlen, const void *key, size_t keylen)
References BLAKE2B_OUTBYTES, BLAKE2B_KEYBYTES, __blake2b_param::digest_length, __blake2b_param::key_length, __blake2b_param::fanout, __blake2b_param::depth, __blake2b_param::leaf_length, __blake2b_param::node_offset, __blake2b_param::node_depth, __blake2b_param::inner_length, __blake2b_param::reserved, __blake2b_param::salt, __blake2b_param::personal, blake2b_init_param, BLAKE2B_BLOCKBYTES, blake2b_update.
Referenced by blake2b.
static void blake2b_compress(blake2b_state *S, const uint8_t *block)
int blake2b_update(blake2b_state *S, const void *in, size_t inlen)
References __blake2b_state::f, __blake2b_state::buflen, BLAKE2B_BLOCKBYTES, __blake2b_state::buf.
Referenced by blake2b_init_key, blake2b, blake2b_long, initial_hash, HashBlake2b.
int blake2b_final(blake2b_state *S, void *out, size_t outlen)
References BLAKE2B_OUTBYTES, __blake2b_state::f, __blake2b_state::buflen, __blake2b_state::buf, BLAKE2B_BLOCKBYTES, __blake2b_state::h, __blake2b_state::outlen.
Referenced by blake2b, blake2b_long, initial_hash, HashBlake2b.
int blake2b(void *out, size_t outlen, const void *in, size_t inlen, const void *key, size_t keylen)
References BLAKE2B_OUTBYTES, BLAKE2B_KEYBYTES, blake2b_init_key, blake2b_init, blake2b_update, blake2b_final.
Referenced by blake2b_long.
int blake2b_long(void *pout, size_t outlen, const void *in, size_t inlen)
References BLAKE2B_OUTBYTES, TRY, blake2b_init, blake2b_update, blake2b_final, blake2b.
Referenced by finalize, fill_first_blocks.