blockbrowser.cpp
double getBlockHardness(int height)
References getBlockIndex, CBlockIndex::nBits.
Referenced by getBlockHashrate, BlockBrowser::updateExplorer.
int getBlockHashrate(int height)
References getBlockTime, getBlockHardness.
Referenced by BlockBrowser::updateExplorer.
const CBlockIndex* getBlockIndex(int height)
References getBlockHash, hash, mapBlockIndex.
Referenced by getBlockHardness.
std::string getBlockHash(int Height)
References pindexBest, CBlockIndex::nHeight, nBestHeight, mapBlockIndex, hashBestChain, CBlockIndex::pprev, CBlockIndex::phashBlock, base_uint< BITS >::GetHex.
Referenced by getBlockIndex, getBlockTime, getBlockMerkle, getBlocknBits, getBlockNonce, getBlockDebug, BlockBrowser::updateExplorer.
int getBlockTime(int Height)
References getBlockHash, hash, mapBlockIndex, CBlockIndex::nTime.
Referenced by getBlockHashrate, blocksInPastHours, BlockBrowser::updateExplorer.
std::string getBlockMerkle(int Height)
References getBlockHash, hash, mapBlockIndex, CBlockIndex::hashMerkleRoot, base_uint< BITS >::ToString.
Referenced by BlockBrowser::updateExplorer.
int getBlocknBits(int Height)
References getBlockHash, hash, mapBlockIndex, CBlockIndex::nBits.
Referenced by BlockBrowser::updateExplorer.
int getBlockNonce(int Height)
References getBlockHash, hash, mapBlockIndex, CBlockIndex::nNonce.
Referenced by BlockBrowser::updateExplorer.
std::string getBlockDebug(int Height)
References getBlockHash, hash, mapBlockIndex, CBlockIndex::ToString.
int blocksInPastHours(int hours)
References pindexBest, CBlockIndex::nHeight, getBlockTime.
double getTxTotalValue(std::string txid)
References hash, base_uint< BITS >::SetHex, GetTransaction, SER_NETWORK, value, convertCoins, CTxOut::nValue.
Referenced by BlockBrowser::updateExplorer.
double convertCoins(CAmount amount)
Referenced by getTxTotalValue, getOutputs, getInputs, getTxFees.
std::string getOutputs(std::string txid)
References hash, base_uint< BITS >::SetHex, GetTransaction, SER_NETWORK, source, ExtractDestination, CTxOut::scriptPubKey, CBase58Data::ToString, convertCoins, CTxOut::nValue.
Referenced by BlockBrowser::updateExplorer.
std::string getInputs(std::string txid)
References hash, base_uint< BITS >::SetHex, GetTransaction, SER_NETWORK, CTxIn::prevout, COutPoint::hash, base_uint< BITS >::ToString, source, ExtractDestination, COutPoint::n, CBase58Data::ToString, convertCoins, getInputValue.
Referenced by BlockBrowser::updateExplorer.
int64_t getInputValue(CTransaction tx, CScript target)
References CTransaction::vin, CTransaction::vout, CTxOut::scriptPubKey, CTxOut::nValue.
Referenced by getInputs, getTxFees.
double getTxFees(std::string txid)
References hash, base_uint< BITS >::SetHex, GetTransaction, SER_NETWORK, value, convertCoins, CTxOut::nValue, CTxIn::prevout, COutPoint::hash, base_uint< BITS >::ToString, COutPoint::n, getInputValue.
Referenced by BlockBrowser::updateExplorer.