block.cpp
bool CheckProofOfWork(uint256 hash, unsigned int nBits)
References CBigNum::SetCompact, Params, CBigNum::getuint256.
Referenced by CBlock::CheckBlock, CBlock::ReadFromDisk, CBlockTreeDB::LoadBlockIndexGuts.