blockbrowser.h
double getBlockHardness(int)
References getBlockIndex, CBlockIndex::nBits.
Referenced by getBlockHashrate, BlockBrowser::updateExplorer.
double getTxTotalValue(std::string)
References hash, base_uint< BITS >::SetHex, GetTransaction, SER_NETWORK, value, convertCoins, CTxOut::nValue.
Referenced by BlockBrowser::updateExplorer.
double convertCoins(int64_t)
Referenced by getTxTotalValue, getOutputs, getInputs, getTxFees.
double getTxFees(std::string)
References hash, base_uint< BITS >::SetHex, GetTransaction, SER_NETWORK, value, convertCoins, CTxOut::nValue, CTxIn::prevout, COutPoint::hash, base_uint< BITS >::ToString, COutPoint::n, getInputValue.
Referenced by BlockBrowser::updateExplorer.
int getBlockTime(int)
References getBlockHash, hash, mapBlockIndex, CBlockIndex::nTime.
Referenced by getBlockHashrate, blocksInPastHours, BlockBrowser::updateExplorer.
int getBlocknBits(int)
References getBlockHash, hash, mapBlockIndex, CBlockIndex::nBits.
Referenced by BlockBrowser::updateExplorer.
int getBlockNonce(int)
References getBlockHash, hash, mapBlockIndex, CBlockIndex::nNonce.
Referenced by BlockBrowser::updateExplorer.
int blocksInPastHours(int)
References pindexBest, CBlockIndex::nHeight, getBlockTime.
int getBlockHashrate(int)
References getBlockTime, getBlockHardness.
Referenced by BlockBrowser::updateExplorer.
std::string getInputs(std::string)
References hash, base_uint< BITS >::SetHex, GetTransaction, SER_NETWORK, CTxIn::prevout, COutPoint::hash, base_uint< BITS >::ToString, source, ExtractDestination, COutPoint::n, CBase58Data::ToString, convertCoins, getInputValue.
Referenced by BlockBrowser::updateExplorer.
std::string getOutputs(std::string)
References hash, base_uint< BITS >::SetHex, GetTransaction, SER_NETWORK, source, ExtractDestination, CTxOut::scriptPubKey, CBase58Data::ToString, convertCoins, CTxOut::nValue.
Referenced by BlockBrowser::updateExplorer.
std::string getBlockHash(int)
References pindexBest, CBlockIndex::nHeight, nBestHeight, mapBlockIndex, hashBestChain, CBlockIndex::pprev, CBlockIndex::phashBlock, base_uint< BITS >::GetHex.
Referenced by getBlockIndex, getBlockTime, getBlockMerkle, getBlocknBits, getBlockNonce, getBlockDebug, BlockBrowser::updateExplorer.
std::string getBlockMerkle(int)
References getBlockHash, hash, mapBlockIndex, CBlockIndex::hashMerkleRoot, base_uint< BITS >::ToString.
Referenced by BlockBrowser::updateExplorer.
bool addnode(std::string)
const CBlockIndex* getBlockIndex(int)
References getBlockHash, hash, mapBlockIndex.
Referenced by getBlockHardness.
int64_t getInputValue(CTransaction, CScript)
References CTransaction::vin, CTransaction::vout, CTxOut::scriptPubKey, CTxOut::nValue.
Referenced by getInputs, getTxFees.