c.h
@6
typedef struct leveldb_t leveldb_t
typedef struct leveldb_cache_t leveldb_cache_t
typedef struct leveldb_comparator_t leveldb_comparator_t
typedef struct leveldb_env_t leveldb_env_t
typedef struct leveldb_filelock_t leveldb_filelock_t
typedef struct leveldb_filterpolicy_t leveldb_filterpolicy_t
typedef struct leveldb_iterator_t leveldb_iterator_t
typedef struct leveldb_logger_t leveldb_logger_t
typedef struct leveldb_options_t leveldb_options_t
typedef struct leveldb_randomfile_t leveldb_randomfile_t
typedef struct leveldb_readoptions_t leveldb_readoptions_t
typedef struct leveldb_seqfile_t leveldb_seqfile_t
typedef struct leveldb_snapshot_t leveldb_snapshot_t
typedef struct leveldb_writablefile_t leveldb_writablefile_t
typedef struct leveldb_writebatch_t leveldb_writebatch_t
typedef struct leveldb_writeoptions_t leveldb_writeoptions_t
leveldb_t* leveldb_open(const leveldb_options_t *options, const char *name, char **errptr)
References leveldb_options_t::rep, leveldb_t::rep.
Referenced by main.
void leveldb_close(leveldb_t *db)
References leveldb_t::rep.
Referenced by main.
void leveldb_put(leveldb_t *db, const leveldb_writeoptions_t *options, const char *key, size_t keylen, const char *val, size_t vallen, char **errptr)
References leveldb_t::rep, leveldb::DB::Put, leveldb_writeoptions_t::rep.
Referenced by main.
void leveldb_delete(leveldb_t *db, const leveldb_writeoptions_t *options, const char *key, size_t keylen, char **errptr)
References leveldb_t::rep, leveldb::DB::Delete, leveldb_writeoptions_t::rep.
Referenced by main.
void leveldb_write(leveldb_t *db, const leveldb_writeoptions_t *options, leveldb_writebatch_t *batch, char **errptr)
References leveldb_t::rep, leveldb::DB::Write, leveldb_writeoptions_t::rep, leveldb_writebatch_t::rep.
Referenced by main.
char* leveldb_get(leveldb_t *db, const leveldb_readoptions_t *options, const char *key, size_t keylen, size_t *vallen, char **errptr)
References leveldb_t::rep, leveldb::DB::Get, leveldb_readoptions_t::rep, leveldb::Status::ok, leveldb::Status::IsNotFound.
leveldb_iterator_t* leveldb_create_iterator(leveldb_t *db, const leveldb_readoptions_t *options)
References leveldb_iterator_t::rep, leveldb_t::rep, leveldb::DB::NewIterator, leveldb_readoptions_t::rep.
Referenced by main.
const leveldb_snapshot_t* leveldb_create_snapshot(leveldb_t *db)
References leveldb_snapshot_t::rep, leveldb_t::rep, leveldb::DB::GetSnapshot.
Referenced by main.
void leveldb_release_snapshot(leveldb_t *db, const leveldb_snapshot_t *snapshot)
References leveldb_t::rep, leveldb::DB::ReleaseSnapshot, leveldb_snapshot_t::rep.
Referenced by main.
char* leveldb_property_value(leveldb_t *db, const char *propname)
References leveldb_t::rep, leveldb::DB::GetProperty.
Referenced by main.
void leveldb_approximate_sizes(leveldb_t *db, int num_ranges, const char *const *range_start_key, const size_t *range_start_key_len, const char *const *range_limit_key, const size_t *range_limit_key_len, uint64_t *sizes)
References leveldb::Range::start, leveldb::Range::limit, leveldb_t::rep, leveldb::DB::GetApproximateSizes.
Referenced by main.
void leveldb_compact_range(leveldb_t *db, const char *start_key, size_t start_key_len, const char *limit_key, size_t limit_key_len)
References leveldb_t::rep, leveldb::DB::CompactRange.
Referenced by main.
void leveldb_destroy_db(const leveldb_options_t *options, const char *name, char **errptr)
References leveldb::DestroyDB, leveldb_options_t::rep.
Referenced by main.
void leveldb_repair_db(const leveldb_options_t *options, const char *name, char **errptr)
References leveldb::RepairDB, leveldb_options_t::rep.
Referenced by main.
void leveldb_iter_destroy(leveldb_iterator_t *)
References leveldb_iterator_t::rep.
Referenced by main.
unsigned char leveldb_iter_valid(const leveldb_iterator_t *)
References leveldb_iterator_t::rep, leveldb::Iterator::Valid.
Referenced by main.
void leveldb_iter_seek_to_first(leveldb_iterator_t *)
References leveldb_iterator_t::rep, leveldb::Iterator::SeekToFirst.
Referenced by main.
void leveldb_iter_seek_to_last(leveldb_iterator_t *)
References leveldb_iterator_t::rep, leveldb::Iterator::SeekToLast.
Referenced by main.
void leveldb_iter_seek(leveldb_iterator_t *, const char *k, size_t klen)
References leveldb_iterator_t::rep, leveldb::Iterator::Seek.
Referenced by main.
void leveldb_iter_next(leveldb_iterator_t *)
References leveldb_iterator_t::rep, leveldb::Iterator::Next.
Referenced by main.
void leveldb_iter_prev(leveldb_iterator_t *)
References leveldb_iterator_t::rep, leveldb::Iterator::Prev.
Referenced by main.
const char* leveldb_iter_key(const leveldb_iterator_t *, size_t *klen)
References leveldb_iterator_t::rep, leveldb::Iterator::key, leveldb::Slice::size, leveldb::Slice::data.
const char* leveldb_iter_value(const leveldb_iterator_t *, size_t *vlen)
References leveldb_iterator_t::rep, leveldb::Iterator::value, leveldb::Slice::size, leveldb::Slice::data.
void leveldb_iter_get_error(const leveldb_iterator_t *, char **errptr)
References leveldb_iterator_t::rep, leveldb::Iterator::status.
Referenced by main.
leveldb_writebatch_t* leveldb_writebatch_create()
Referenced by main.
void leveldb_writebatch_destroy(leveldb_writebatch_t *)
Referenced by main.
void leveldb_writebatch_clear(leveldb_writebatch_t *)
References leveldb_writebatch_t::rep, leveldb::WriteBatch::Clear.
Referenced by main.
void leveldb_writebatch_put(leveldb_writebatch_t *, const char *key, size_t klen, const char *val, size_t vlen)
References leveldb_writebatch_t::rep, leveldb::WriteBatch::Put.
Referenced by main.
void leveldb_writebatch_delete(leveldb_writebatch_t *, const char *key, size_t klen)
References leveldb_writebatch_t::rep, leveldb::WriteBatch::Delete.
Referenced by main.
void leveldb_writebatch_iterate(leveldb_writebatch_t *, void *state, void(*put)(void *, const char *k, size_t klen, const char *v, size_t vlen), void(*deleted)(void *, const char *k, size_t klen))
References value, leveldb::Slice::data, leveldb::Slice::size, state, leveldb_writebatch_t::rep, leveldb::WriteBatch::Iterate.
Referenced by main.
leveldb_options_t* leveldb_options_create()
Referenced by main.
void leveldb_options_destroy(leveldb_options_t *)
Referenced by main.
void leveldb_options_set_comparator(leveldb_options_t *, leveldb_comparator_t *)
References leveldb_options_t::rep, leveldb::Options::comparator, cmp.
Referenced by main.
void leveldb_options_set_filter_policy(leveldb_options_t *, leveldb_filterpolicy_t *)
References leveldb_options_t::rep, leveldb::Options::filter_policy.
Referenced by main.
void leveldb_options_set_create_if_missing(leveldb_options_t *, unsigned char)
References leveldb_options_t::rep, leveldb::Options::create_if_missing.
Referenced by main.
void leveldb_options_set_error_if_exists(leveldb_options_t *, unsigned char)
References leveldb_options_t::rep, leveldb::Options::error_if_exists.
Referenced by main.
void leveldb_options_set_paranoid_checks(leveldb_options_t *, unsigned char)
References leveldb_options_t::rep, leveldb::Options::paranoid_checks.
Referenced by main.
void leveldb_options_set_env(leveldb_options_t *, leveldb_env_t *)
References leveldb_options_t::rep, leveldb::Options::env, leveldb_env_t::rep.
Referenced by main.
void leveldb_options_set_info_log(leveldb_options_t *, leveldb_logger_t *)
References leveldb_options_t::rep, leveldb::Options::info_log, leveldb_logger_t::rep.
Referenced by main.
void leveldb_options_set_write_buffer_size(leveldb_options_t *, size_t)
References leveldb_options_t::rep, leveldb::Options::write_buffer_size.
Referenced by main.
void leveldb_options_set_max_open_files(leveldb_options_t *, int)
References leveldb_options_t::rep, leveldb::Options::max_open_files.
Referenced by main.
void leveldb_options_set_cache(leveldb_options_t *, leveldb_cache_t *)
References leveldb_options_t::rep, leveldb::Options::block_cache, leveldb_cache_t::rep.
Referenced by main.
void leveldb_options_set_block_size(leveldb_options_t *, size_t)
References leveldb_options_t::rep, leveldb::Options::block_size.
Referenced by main.
void leveldb_options_set_block_restart_interval(leveldb_options_t *, int)
References leveldb_options_t::rep, leveldb::Options::block_restart_interval.
Referenced by main.
void leveldb_options_set_compression(leveldb_options_t *, int)
References leveldb_options_t::rep, leveldb::Options::compression.
Referenced by main.
leveldb_comparator_t* leveldb_comparator_create(void *state, void(*destructor)(void *), int(*compare)(void *, const char *a, size_t alen, const char *b, size_t blen), const char *(*name)(void *))
References leveldb_comparator_t::state_, state, leveldb_comparator_t::destructor_, leveldb_comparator_t::compare_, leveldb_comparator_t::name_, name.
Referenced by main.
void leveldb_comparator_destroy(leveldb_comparator_t *)
References cmp.
Referenced by main.
leveldb_filterpolicy_t* leveldb_filterpolicy_create(void *state, void(*destructor)(void *), char *(*create_filter)(void *, const char *const *key_array, const size_t *key_length_array, int num_keys, size_t *filter_length), unsigned char(*key_may_match)(void *, const char *key, size_t length, const char *filter, size_t filter_length), const char *(*name)(void *))
References leveldb_filterpolicy_t::state_, state, leveldb_filterpolicy_t::destructor_, leveldb_filterpolicy_t::create_, leveldb_filterpolicy_t::key_match_, leveldb_filterpolicy_t::name_, name.
Referenced by main.
void leveldb_filterpolicy_destroy(leveldb_filterpolicy_t *)
Referenced by main.
leveldb_filterpolicy_t* leveldb_filterpolicy_create_bloom(int bits_per_key)
References leveldb_filterpolicy_t::Name, leveldb::FilterPolicy::Name, leveldb_filterpolicy_t::CreateFilter, leveldb::FilterPolicy::CreateFilter, leveldb_filterpolicy_t::KeyMayMatch, leveldb::FilterPolicy::KeyMayMatch, leveldb::NewBloomFilterPolicy.
Referenced by main.
leveldb_readoptions_t* leveldb_readoptions_create()
Referenced by main.
void leveldb_readoptions_destroy(leveldb_readoptions_t *)
Referenced by main.
void leveldb_readoptions_set_verify_checksums(leveldb_readoptions_t *, unsigned char)
References leveldb_readoptions_t::rep, leveldb::ReadOptions::verify_checksums.
Referenced by main.
void leveldb_readoptions_set_fill_cache(leveldb_readoptions_t *, unsigned char)
References leveldb_readoptions_t::rep, leveldb::ReadOptions::fill_cache.
Referenced by main.
void leveldb_readoptions_set_snapshot(leveldb_readoptions_t *, const leveldb_snapshot_t *)
References leveldb_readoptions_t::rep, leveldb::ReadOptions::snapshot, leveldb_snapshot_t::rep.
Referenced by main.
leveldb_writeoptions_t* leveldb_writeoptions_create()
Referenced by main.
void leveldb_writeoptions_destroy(leveldb_writeoptions_t *)
Referenced by main.
void leveldb_writeoptions_set_sync(leveldb_writeoptions_t *, unsigned char)
References leveldb_writeoptions_t::rep, leveldb::WriteOptions::sync.
Referenced by main.
leveldb_cache_t* leveldb_cache_create_lru(size_t capacity)
References leveldb_cache_t::rep, leveldb::NewLRUCache.
Referenced by main.
void leveldb_cache_destroy(leveldb_cache_t *cache)
References leveldb_cache_t::rep.
Referenced by main.
leveldb_env_t* leveldb_create_default_env()
References leveldb_env_t::rep, leveldb_env_t::is_default.
Referenced by main.
void leveldb_env_destroy(leveldb_env_t *)
References leveldb_env_t::is_default, leveldb_env_t::rep.
Referenced by main.
void leveldb_free(void *ptr)
Referenced by main.
int leveldb_major_version()
Referenced by main.
int leveldb_minor_version()
Referenced by main.