chain.h
BlockStatus
Unused.
std::map<uint256, CBlockIndex*> mapBlockIndex
Referenced by CBlock::AcceptBlock, CBlockLocator::CBlockLocator, CBlockLocator::GetDistanceBack, CBlockLocator::GetBlockIndex, CBlockLocator::GetBlockHash, CCoinsViewDB::GetStats, AppInit2, CheckStake, getBlockIndex, getBlockHash, getBlockTime, getBlockMerkle, getBlocknBits, getBlockNonce, getBlockDebug, TransactionRecord::updateStatus, getblock, getblockbynumber, TxToJSON, WalletTxToJSON, gettransaction, scanforalltxns, scanforstealthtxns, IsBudgetCollateralValid, InsertBlockIndex, CTxDB::LoadBlockIndex, CWallet::AddToWallet, CWallet::GetKeyBirthTimes.
CBlockIndex* pindexBest
Referenced by InvalidChainFound, Reorganize, IsInitialBlockDownload, CBlock::CheckBlock, Checkpoints::AutoSelectSyncCheckpoint, Shutdown, AppInit2, CreateNewLock, CleanTransactionLocksList, CreateNewBlock, ThreadStakeMiner, getBlockHash, blocksInPastHours, BlockBrowser::updateExplorer, ClientModel::getLastBlockDate, OverviewPage::sandStormStatus, StatisticsPage::updateStatistics, GetDifficulty, GetPoSKernelPS, getdifficulty, importwallet, dumpwallet, getmininginfo, getstakinginfo, checkkernel, getworkex, getwork, getblocktemplate, getinfo, snbudget, stormnode, stormnodelist, listsinceblock, CSandstormPool::GetStatus, CSandstormPool::CompletedTransaction, CSandstormPool::DoAutomaticDenominating, CSandstormPool::MakeCollateralAmounts, CSandstormPool::CreateDenominated, ProcessSpork, CBudgetManager::SubmitFinalBudget, CBudgetManager::CheckAndRemove, CBudgetManager::FillBlockPayee, CBudgetManager::HasNextFinalizedBudget, CBudgetManager::GetBudget, CBudgetManager::GetTotalBudget, CBudgetProposal::IsValid, CBudgetProposal::GetBlockCurrentCycle, CFinalizedBudget::AutoCheck, CFinalizedBudget::IsValid, IsBlockValueValid, FillBlockPayee, CStormnodePayments::FillBlockPayee, CStormnodePayments::ProcessMessageStormnodePayments, CStormnodePayments::IsScheduled, CStormnodePayments::CleanPaymentList, CStormnodePayments::Sync, CStormnodeSync::IsBlockchainSynced, CStormnodeSync::Process, GetBlockHash, CStormnode::CalculateScore, CStormnode::GetLastPaid, CStormnode::GetStormnodeInputAge, CTxDB::LoadBlockIndex, CWallet::CreateCoinStake.
bool fUseFastIndex
Referenced by CDiskBlockIndex::GetBlockHash.
CBlockIndex* pindexGenesisBlock
Referenced by CBlockLocator::GetBlockIndex, AppInit2, GetPoWMHashPS, importprivkey, importaddress, scanforalltxns, scanforstealthtxns, SecureMsgScanBlockChain, CTxDB::LoadBlockIndex, CWallet::ReacceptWalletTransactions.
CBlockIndex* pblockindexFBBHLast
Referenced by CBlock::SetBestChain.
bool IsInitialBlockDownload()
References LOCK, cs_main, pindexBest, nBestHeight, Checkpoints::GetTotalBlocksEstimate, GetTime, CBlockIndex::GetBlockTime.
Referenced by CBlock::WriteToDisk, ProcessBlock, SendMessages, CBlock::SetBestChain, ThreadStakeMiner, ClientModel::inInitialBlockDownload, OverviewPage::updateSandstormProgress, OverviewPage::sandStormStatus, checkkernel, getworkex, getwork, getblocktemplate.
CBlockIndex* FindBlockByHeight(int nHeight)
Referenced by getblockhash, CWallet::GetKeyBirthTimes.
bool Reorganize(CTxDB &txdb, CBlockIndex *pindexNew)
References LogPrintf, pindexBest, CBlockIndex::nHeight, CBlockIndex::pprev, CBlockIndex::GetBlockHash, base_uint< BITS >::ToString, CBlock::ReadFromDisk, CBlock::DisconnectBlock, CBlock::vtx, CTransaction::IsCoinBase, CTransaction::IsCoinStake, Checkpoints::GetTotalBlocksEstimate, state, CBlock::ConnectBlock, CTxDB::WriteHashBestChain, CTxDB::TxnCommit, CBlockIndex::pnext, AcceptToMemoryPool, mempool, CTxMemPool::remove, CTxMemPool::removeConflicts.
Referenced by CBlock::SetBestChain.
void InvalidChainFound(CBlockIndex *pindexNew)
References CBlockIndex::nChainTrust, nBestInvalidTrust, CTxDB::WriteBestInvalidTrust, CBlockIndex::pprev, pindexBest, CBlockIndex::nHeight, LogPrintf, CBlockIndex::GetBlockHash, base_uint< BITS >::ToString, CBigNum::ToString, base_uint< BITS >::Get64, DateTimeStrFormat, CBlockIndex::GetBlockTime, hashBestChain, nBestHeight.
Referenced by CBlock::SetBestChain.