chainparams.h
MESSAGE_START_SIZE
Referenced by LoadExternalBlockFile, ProcessMessages, CMessageHeader::CMessageHeader, CMessageHeader::IsValid.
typedef unsigned char MessageStartChars[MESSAGE_START_SIZE][MESSAGE_START_SIZE]
const CChainParams& Params()
Return the currently selected parameters. This won't change after app startup outside of the unit tests.
Referenced by CActiveStormnode::ManageStatus, CActiveStormnode::Register, CAlert::CheckSignature, CDarkSilkAddress::Set, CDarkSilkAddress::IsValid, CDarkSilkAddress::Get, CDarkSilkAddress::GetKeyID, CDarkSilkAddress::IsScript, CDarkSilkSecret::SetKey, CDarkSilkSecret::IsValid, CDarkSilkExtKeyBase< K, Size, Type >::SetKey, CBlock::AcceptBlock, CBlock::WriteToDisk, CBlockLocator::Set, CBlockLocator::GetBlockHash, TestNet, AppInit2, GetNextTargetRequired, LoadBlockIndex, LoadExternalBlockFile, ProcessMessages, CBlock::SetBestChain, GetListenPort, ConnectNode, ThreadDNSAddressSeed, ThreadOpenConnections, ThreadOpenAddedConnections, CAddrDB::Write, CAddrDB::Read, CheckProofOfWork, CMessageHeader::CMessageHeader, CMessageHeader::IsValid, ClientModel::getLastBlockDate, DarkSilkGUI::setNumBlocks, CallRPC, getblocktemplate, getaddednodeinfo, StartRPCThreads, CSandstormPool::ChargeFees, CSandstormPool::InitCollateralAddress, CSandstormPool::GetMaxPoolTransactions, GetBudgetPaymentCycleBlocks, CBudgetDB::Write, CBudgetDB::Read, CBudgetManager::ProcessMessage, CFinalizedBudget::AutoCheck, CBudgetProposal::IsEstablished, CStormnodePaymentDB::Write, CStormnodePaymentDB::Read, CStormnodePayments::ProcessMessageStormnodePayments, CStormnodeSync::Process, CStormnodeBroadcast::CheckAndUpdate, CStormnodeDB::Write, CStormnodeDB::Read, CStormnodeMan::SsegUpdate, CStormnodeMan::ProcessMessage, CTxDB::LoadBlockIndex, GetDataDir, CWallet::CreateCoinStake.
void SelectParams(CChainParams::Network network)
Sets the params returned by Params() to those for the given network.
References CChainParams::MAIN, CChainParams::TESTNET.
Referenced by SelectParamsFromCommandLine, BOOST_AUTO_TEST_CASE.
bool SelectParamsFromCommandLine()
Looks for -testnet and then calls SelectParams as appropriate. Returns false if an invalid combination is given.
References GetBoolArg, SelectParams, CChainParams::TESTNET, CChainParams::MAIN.
Referenced by AppInit, AppInit2.
bool TestNet()
References Params, CChainParams::NetworkID, CChainParams::TESTNET.
Referenced by Checkpoints::CheckHardened, Checkpoints::GetTotalBlocksEstimate, Checkpoints::GetLastCheckpoint, AcceptToMemoryPool, LoadBlockIndex, ClientModel::isTestNet, getmininginfo, getinfo.