CCoins
bool CCoins::fCoinBase
whether transaction is a coinbase
Referenced by Spend, swap, IsCoinBase.
std::vector<CTxOut> CCoins::vout
unspent transaction outputs; spent outputs are .IsNull(); spent outputs at the end of the array are dropped
Referenced by CalcMaskSize, Spend, CCoinsViewCache::GetOutputFor, CCoinsViewCache::GetPriority, swap.
int CCoins::nHeight
at which height this transaction was included in the active block chain
Referenced by Spend, CCoinsViewCache::GetPriority, swap.
int CCoins::nVersion
version of the CTransaction; accesses to this value should probably check for nHeight as well, as new tx version will probably only be introduced at certain heights
Referenced by Spend, swap, GetSerializeSize, Serialize.
void CCoins::FromTx(const CTransaction &tx, int nHeightIn)
References CTransaction::IsCoinBase, CTransaction::vout, CTransaction::nVersion, ClearUnspendable.
Referenced by CCoins.
CCoins::CCoins(const CTransaction &tx, int nHeightIn)
construct a CCoins from a CTransaction, at a given height
References FromTx.
void CCoins::Clear()
References swap.
CCoins::CCoins()
empty constructor
void CCoins::Cleanup()
remove spent outputs at the end of vout
Referenced by Spend, ClearUnspendable, Unserialize.
void CCoins::ClearUnspendable()
References CTxOut::scriptPubKey, CScript::IsUnspendable, CTxOut::SetNull, Cleanup.
Referenced by FromTx.
void CCoins::swap(CCoins &to)
References fCoinBase, vout, nHeight, nVersion.
Referenced by CCoinsViewCache::BatchWrite, Clear.
void CCoins::CalcMaskSize(unsigned int &nBytes, unsigned int &nNonzeroBytes) const
calculate number of bytes for the bitmask, and its number of non-zero bytes each bit in the bitmask represents the availability of one output, but the availabilities of the first two outputs are encoded separately
References vout.
Referenced by GetSerializeSize, Serialize.
bool CCoins::IsCoinBase() const
References fCoinBase.
unsigned int CCoins::GetSerializeSize(int nType, int nVersion) const
References CalcMaskSize, VARINT, REF, nVersion.
void CCoins::Serialize(Stream &s, int nType, int nVersion) const
References CalcMaskSize, VARINT, REF, nVersion.
void CCoins::Unserialize(Stream &s, int nType, int nVersion)
References VARINT, REF, Cleanup.
bool CCoins::Spend(const COutPoint &out, CTxInUndo &undo)
mark an outpoint spent, and construct undo information
References COutPoint::n, vout, Cleanup, CTxInUndo::nHeight, nHeight, CTxInUndo::fCoinBase, fCoinBase, CTxInUndo::nVersion, nVersion.
Referenced by Spend.
bool CCoins::Spend(int nPos)
mark a vout spent
References Spend.
bool CCoins::IsAvailable(unsigned int nPos) const
check whether a particular output is still available
Referenced by CCoinsViewCache::GetOutputFor, CCoinsViewCache::HaveInputs, CCoinsViewCache::GetPriority.
bool CCoins::IsPruned() const
check whether the entire CCoins is spent note that only !IsPruned() CCoins can be serialized
References CTxOut::IsNull.
Referenced by CCoinsViewMemPool::GetCoins, BatchWriteCoins.
bool operator==(const CCoins &a, const CCoins &b)
equality test
bool operator!=(const CCoins &a, const CCoins &b)