CTxDB
leveldb::DB* CTxDB::pdb
leveldb::WriteBatch* CTxDB::activeBatch
leveldb::Options CTxDB::options
bool CTxDB::fReadOnly
int CTxDB::nVersion
CTxDB::CTxDB(const char *pszMode="r+")
References txdb, leveldb::Options::create_if_missing, leveldb::Options::filter_policy, leveldb::NewBloomFilterPolicy, LogPrintf.
CTxDB::~CTxDB()
void CTxDB::Close()
References txdb, leveldb::Options::filter_policy, leveldb::Options::block_cache.
bool CTxDB::TxnBegin()
Referenced by CBlock::SetBestChain, CBlock::AddToBlockIndex.
bool CTxDB::TxnCommit()
References leveldb::Status::ok, LogPrintf, leveldb::Status::ToString.
Referenced by Reorganize, CBlock::SetBestChain, CBlock::AddToBlockIndex.
bool CTxDB::TxnAbort()
Referenced by CBlock::SetBestChain.
bool CTxDB::ReadVersion(int &nVersion)
References Read.
bool CTxDB::WriteVersion(int nVersion)
References Write.
bool CTxDB::ReadAddrIndex(uint160 addrHash, std::vector< uint256 > &txHashes)
Referenced by FindTransactionsByDestination.
bool CTxDB::WriteAddrIndex(uint160 addrHash, uint256 txHash)
Referenced by CBlock::RebuildAddressIndex, CBlock::ConnectBlock.
bool CTxDB::ReadTxIndex(uint256 hash, CTxIndex &txindex)
References CTxIndex::SetNull.
Referenced by CTransactionPoS::ReadFromDisk, CTransactionPoS::DisconnectInputs, CTransactionPoS::FetchInputs, CWallet::ReacceptWalletTransactions, CWallet::FixSpentCoins.
bool CTxDB::UpdateTxIndex(uint256 hash, const CTxIndex &txindex)
Referenced by CBlock::ConnectBlock, CTransactionPoS::DisconnectInputs.
bool CTxDB::AddTxIndex(const CTransaction &tx, const CDiskTxPos &pos, int nHeight)
References hash, CTransaction::GetHash, CTransaction::vout.
bool CTxDB::EraseTxIndex(const CTransaction &tx)
References hash, CTransaction::GetHash.
Referenced by CTransactionPoS::DisconnectInputs.
bool CTxDB::ContainsTx(uint256 hash)
Referenced by AcceptToMemoryPool, AcceptableInputs, CWalletTx::AcceptWalletTransaction.
bool CTxDB::ReadDiskTx(uint256 hash, CTransaction &tx, CTxIndex &txindex)
References CTransaction::SetNull, CTransactionPoS::ReadFromDisk, CTxIndex::pos.
Referenced by CWalletTx::AddSupportingTransactions.
bool CTxDB::ReadDiskTx(uint256 hash, CTransaction &tx)
bool CTxDB::ReadDiskTx(COutPoint outpoint, CTransaction &tx, CTxIndex &txindex)
References COutPoint::hash.
bool CTxDB::ReadDiskTx(COutPoint outpoint, CTransaction &tx)
References COutPoint::hash.
bool CTxDB::WriteBlockIndex(const CDiskBlockIndex &blockindex)
References CDiskBlockIndex::GetBlockHash.
Referenced by CBlock::DisconnectBlock, CBlock::ConnectBlock, CBlock::AddToBlockIndex.
bool CTxDB::ReadHashBestChain(uint256 &hashBestChain)
bool CTxDB::WriteHashBestChain(uint256 hashBestChain)
Referenced by Reorganize, CBlock::SetBestChain.
bool CTxDB::ReadBestInvalidTrust(CBigNum &bnBestInvalidTrust)
bool CTxDB::WriteBestInvalidTrust(CBigNum bnBestInvalidTrust)
Referenced by InvalidChainFound.
bool CTxDB::LoadBlockIndex()
References mapBlockIndex, SER_DISK, leveldb::Iterator::Seek, CDataStream::str, leveldb::Iterator::Valid, CDataStream::write, leveldb::Iterator::key, leveldb::Slice::data, leveldb::Slice::size, leveldb::Iterator::value, InsertBlockIndex, CBlockIndex::pprev, CBlockIndex::pnext, CBlockIndex::nFile, CBlockIndex::nBlockPos, CBlockIndex::nHeight, CBlockIndex::nMint, CBlockIndex::nMoneySupply, CBlockIndex::nFlags, CBlockIndex::nStakeModifier, CBlockIndex::bnStakeModifierV2, CBlockIndex::prevoutStake, CBlockIndex::nStakeTime, CBlockIndex::hashProof, CBlockIndex::nVersion, CBlockIndex::hashMerkleRoot, CBlockIndex::nTime, CBlockIndex::nBits, CBlockIndex::nNonce, pindexGenesisBlock, Params, CBlockIndex::CheckIndex, CBlockIndex::IsProofOfStake, setStakeSeen, leveldb::Iterator::Next, PAIRTYPE, CBlockIndex::nChainTrust, CBlockIndex::GetBlockTrust, hashBestChain, pindexBest, nBestHeight, nBestChainTrust, LogPrintf, base_uint< BITS >::ToString, CBigNum::ToString, DateTimeStrFormat, CBlockIndex::GetBlockTime, nBestInvalidTrust, CBigNum::getuint256, GetArg, state, CBlock::ReadFromDisk, CBlock::CheckBlock, CBlock::vtx, CTransaction::GetHash, CTxIndex::pos, CDiskTxPos::nFile, CDiskTxPos::nBlockPos, CTransactionPoS::ReadFromDisk, CTxIndex::vSpent, CDiskTxPos::IsNull, CTransaction::CheckTransaction, CTransaction::vin, CTxIn::prevout, COutPoint::hash, COutPoint::n, txdb, CBlock::SetBestChain.
Referenced by AppInit2, LoadBlockIndex.
bool CTxDB::ScanBatch(const CDataStream &key, std::string *value, bool *deleted) const
References CBatchScanner::needle, CDataStream::str, CBatchScanner::deleted, CBatchScanner::foundValue, value, leveldb::Status::ok, leveldb::Status::ToString, CBatchScanner::foundEntry.
Referenced by Read, Exists.
bool CTxDB::Read(const K &key, T &value)
References SER_DISK, CDataStream::reserve, ScanBatch, leveldb::DB::Get, CDataStream::str, leveldb::Status::ok, leveldb::Status::IsNotFound, LogPrintf, leveldb::Status::ToString, value.
Referenced by ReadVersion.
bool CTxDB::Write(const K &key, const T &value)
References SER_DISK, CDataStream::reserve, value, leveldb::WriteBatch::Put, CDataStream::str, leveldb::DB::Put, leveldb::Status::ok, LogPrintf, leveldb::Status::ToString.
Referenced by WriteVersion.
bool CTxDB::Erase(const K &key)
References SER_DISK, CDataStream::reserve, leveldb::WriteBatch::Delete, CDataStream::str, leveldb::DB::Delete, leveldb::Status::ok, leveldb::Status::IsNotFound.
bool CTxDB::Exists(const K &key)
References SER_DISK, CDataStream::reserve, ScanBatch, leveldb::DB::Get, CDataStream::str, leveldb::Status::IsNotFound.
bool CTxDB::LoadBlockIndexGuts()