CAlert
std::vector<unsigned char> CAlert::vchMsg
Referenced by sendalert.
std::vector<unsigned char> CAlert::vchSig
Referenced by sendalert.
CAlert::ADD_SERIALIZE_METHODS
CAlert::CAlert()
References SetNull.
void CAlert::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE.
void CAlert::SetNull()
References CUnsignedAlert::SetNull.
Referenced by CAlert.
bool CAlert::IsNull() const
Referenced by ClientModel::updateAlert.
uint256 CAlert::GetHash() const
References Hash.
bool CAlert::IsInEffect() const
References GetAdjustedTime.
Referenced by ProcessAlert.
bool CAlert::Cancels(const CAlert &alert) const
References CUnsignedAlert::nID.
Referenced by ProcessAlert.
bool CAlert::AppliesTo(int nVersion, std::string strSubVerIn) const
bool CAlert::AppliesToMe() const
References FormatSubVersion, CLIENT_NAME.
Referenced by GetWarnings.
bool CAlert::RelayTo(CNode *pnode) const
References CNode::nVersion, CNode::setKnown, CNode::strSubVer, GetAdjustedTime, CNode::PushMessage.
Referenced by sendalert.
bool CAlert::CheckSignature() const
References Params, CPubKey::Verify, Hash, SER_NETWORK.
bool CAlert::ProcessAlert(bool fThread=true)
References LOCK, mapAlerts, CUnsignedAlert::nID, uiInterface, CClientUIInterface::NotifyAlertChanged, CT_DELETED, IsInEffect, PAIRTYPE, Cancels, CT_NEW, GetArg, SanitizeString, runCommand.
Referenced by sendalert.
CAlert CAlert::getAlertByHash(const uint256 &hash)
References LOCK, mapAlerts.
Referenced by ClientModel::updateAlert.