json_spirit::Value_impl
typedef Config json_spirit::Value_impl< Config >::Config_type
typedef Config::String_type json_spirit::Value_impl< Config >::String_type
typedef Config::Object_type json_spirit::Value_impl< Config >::Object
typedef Config::Array_type json_spirit::Value_impl< Config >::Array
typedef String_type::const_pointer json_spirit::Value_impl< Config >::Const_str_ptr
typedef boost::variant< String_type, boost::recursive_wrapper< Object >, boost::recursive_wrapper< Array >, bool, int64_t, double > json_spirit::Value_impl< Config >::Variant
const Value_impl< Config > json_spirit::Value_impl< Config >::null
Referenced by importprivkey, importaddress, importwallet, dumpwallet, submitblock, ping, addnode, snbudget, snfinalbudget, stormnode.
Value_type json_spirit::Value_impl< Config >::type_
Variant json_spirit::Value_impl< Config >::v_
bool json_spirit::Value_impl< Config >::is_uint64_
json_spirit::Value_impl< Config >::Value_impl()
json_spirit::Value_impl< Config >::Value_impl(Const_str_ptr value)
json_spirit::Value_impl< Config >::Value_impl(const String_type &value)
json_spirit::Value_impl< Config >::Value_impl(const Object &value)
json_spirit::Value_impl< Config >::Value_impl(const Array &value)
json_spirit::Value_impl< Config >::Value_impl(bool value)
json_spirit::Value_impl< Config >::Value_impl(int value)
json_spirit::Value_impl< Config >::Value_impl(int64_t value)
json_spirit::Value_impl< Config >::Value_impl(uint64_t value)
json_spirit::Value_impl< Config >::Value_impl(double value)
json_spirit::Value_impl< Config >::Value_impl(const Value_impl &other)
bool json_spirit::Value_impl< Config >::operator==(const Value_impl &lhs) const
References json_spirit::Value_impl< Config >::type.
Value_impl< Config > & json_spirit::Value_impl< Config >::operator=(const Value_impl &lhs)
Value_type json_spirit::Value_impl< Config >::type() const
Referenced by json_spirit::Value_impl< Config >::operator==, RPCExecutor::request, CommandLineRPC, checkkernel, getblocktemplate, JSONRPCReplyObj, createrawtransaction, signrawtransaction, RPCTypeCheck, ParseHashV, ParseHexV, JSONRequest::parse, ServiceConnection.
bool json_spirit::Value_impl< Config >::is_uint64() const
bool json_spirit::Value_impl< Config >::is_null() const
References json_spirit::null_type.
const Config::String_type & json_spirit::Value_impl< Config >::get_str() const
References json_spirit::str_type.
Referenced by json_spirit::internal_::get_value, RPCExecutor::request, getblock, CommandLineRPC, importprivkey, checkkernel, getblocktemplate, verifymessage, createrawtransaction, signrawtransaction, ParseHashV, ParseHexV, JSONRequest::parse, smsgoptions, AccountFromValue, backupwallet, liststealthaddresses, importstealthaddress.
const Value_impl< Config >::Object & json_spirit::Value_impl< Config >::get_obj() const
References json_spirit::obj_type.
Referenced by json_spirit::internal_::get_value, CallRPC, CommandLineRPC, checkkernel, getblocktemplate, createrawtransaction, signrawtransaction, JSONRequest::parse.
const Value_impl< Config >::Array & json_spirit::Value_impl< Config >::get_array() const
References json_spirit::array_type.
Referenced by json_spirit::internal_::get_value, JSONRequest::parse, ServiceConnection, BOOST_AUTO_TEST_CASE.
bool json_spirit::Value_impl< Config >::get_bool() const
References json_spirit::bool_type.
Referenced by json_spirit::internal_::get_value, getaddednodeinfo, reservebalance.
int json_spirit::Value_impl< Config >::get_int() const
References json_spirit::int_type.
Referenced by json_spirit::internal_::get_value, getblockhash, getblockbynumber, checkkernel, createrawtransaction.
int64_t json_spirit::Value_impl< Config >::get_int64() const
References json_spirit::int_type.
Referenced by json_spirit::internal_::get_value.
uint64_t json_spirit::Value_impl< Config >::get_uint64() const
References json_spirit::int_type.
Referenced by json_spirit::internal_::get_value.
double json_spirit::Value_impl< Config >::get_real() const
References json_spirit::int_type, json_spirit::real_type.
Referenced by json_spirit::internal_::get_value, AmountFromValue.
Value_impl< Config >::Object & json_spirit::Value_impl< Config >::get_obj()
References json_spirit::obj_type.
Value_impl< Config >::Array & json_spirit::Value_impl< Config >::get_array()
References json_spirit::array_type.
T json_spirit::Value_impl< Config >::get_value() const
References json_spirit::internal_::get_value.
void json_spirit::Value_impl< Config >::check_type(const Value_type vtype) const