leveldb::VersionEdit
typedef std::set< std::pair<int, uint64_t> > leveldb::VersionEdit::DeletedFileSet
friend class VersionSet
std::string leveldb::VersionEdit::comparator_
uint64_t leveldb::VersionEdit::log_number_
uint64_t leveldb::VersionEdit::prev_log_number_
uint64_t leveldb::VersionEdit::next_file_number_
SequenceNumber leveldb::VersionEdit::last_sequence_
bool leveldb::VersionEdit::has_comparator_
bool leveldb::VersionEdit::has_log_number_
bool leveldb::VersionEdit::has_prev_log_number_
bool leveldb::VersionEdit::has_next_file_number_
bool leveldb::VersionEdit::has_last_sequence_
std::vector< std::pair<int, InternalKey> > leveldb::VersionEdit::compact_pointers_
DeletedFileSet leveldb::VersionEdit::deleted_files_
std::vector< std::pair<int, FileMetaData> > leveldb::VersionEdit::new_files_
leveldb::VersionEdit::VersionEdit()
References Clear.
leveldb::VersionEdit::~VersionEdit()
void leveldb::VersionEdit::Clear()
Referenced by DecodeFrom, VersionEdit.
void leveldb::VersionEdit::SetComparatorName(const Slice &name)
References leveldb::Slice::ToString.
Referenced by leveldb::TEST.
void leveldb::VersionEdit::SetLogNumber(uint64_t num)
Referenced by leveldb::DB::Open, leveldb::TEST, leveldb::VersionSet::LogAndApply.
void leveldb::VersionEdit::SetPrevLogNumber(uint64_t num)
Referenced by leveldb::VersionSet::LogAndApply.
void leveldb::VersionEdit::SetNextFile(uint64_t num)
Referenced by leveldb::TEST, leveldb::VersionSet::LogAndApply.
void leveldb::VersionEdit::SetLastSequence(SequenceNumber seq)
Referenced by leveldb::TEST, leveldb::VersionSet::LogAndApply.
void leveldb::VersionEdit::SetCompactPointer(int level, const InternalKey &key)
Referenced by leveldb::TEST.
void leveldb::VersionEdit::AddFile(int level, uint64_t file, uint64_t file_size, const InternalKey &smallest, const InternalKey &largest)
References leveldb::FileMetaData::number, leveldb::FileMetaData::file_size, leveldb::FileMetaData::smallest, leveldb::FileMetaData::largest.
Referenced by leveldb::BM_LogAndApply, leveldb::TEST.
void leveldb::VersionEdit::DeleteFile(int level, uint64_t file)
Referenced by leveldb::BM_LogAndApply, leveldb::TEST, leveldb::Compaction::AddInputDeletions.
void leveldb::VersionEdit::EncodeTo(std::string *dst) const
References leveldb::PutVarint32, leveldb::kComparator, leveldb::PutLengthPrefixedSlice, leveldb::kLogNumber, leveldb::PutVarint64, leveldb::kPrevLogNumber, leveldb::kNextFileNumber, leveldb::kLastSequence, leveldb::kCompactPointer, leveldb::kDeletedFile, leveldb::kNewFile, leveldb::FileMetaData::number, leveldb::FileMetaData::file_size, leveldb::FileMetaData::smallest, leveldb::InternalKey::Encode, leveldb::FileMetaData::largest.
Referenced by leveldb::VersionSet::LogAndApply.
Status leveldb::VersionEdit::DecodeFrom(const Slice &src)
References Clear, leveldb::GetVarint32, leveldb::kComparator, leveldb::GetLengthPrefixedSlice, leveldb::Slice::ToString, leveldb::kLogNumber, leveldb::GetVarint64, leveldb::kPrevLogNumber, leveldb::kNextFileNumber, leveldb::kLastSequence, leveldb::kCompactPointer, leveldb::kDeletedFile, leveldb::kNewFile, leveldb::FileMetaData::number, leveldb::FileMetaData::file_size, leveldb::FileMetaData::smallest, leveldb::FileMetaData::largest, leveldb::Slice::empty, leveldb::Status::Corruption.
Referenced by leveldb::VersionSet::Recover.
std::string leveldb::VersionEdit::DebugString() const
References leveldb::AppendNumberTo, leveldb::FileMetaData::number, leveldb::FileMetaData::file_size, leveldb::FileMetaData::smallest, leveldb::InternalKey::DebugString, leveldb::FileMetaData::largest.