CBigNum
CBigNum::CBigNum()
Referenced by pow.
CBigNum::CBigNum(const CBigNum &b)
CBigNum& CBigNum::operator=(const CBigNum &b)
CBigNum::~CBigNum()
CBigNum::CBigNum(signed char n)
References setulong, setint64.
CBigNum::CBigNum(short n)
References setulong, setint64.
CBigNum::CBigNum(int n)
References setulong, setint64.
CBigNum::CBigNum(long n)
References setulong, setint64.
CBigNum::CBigNum(long long n)
References setint64.
CBigNum::CBigNum(unsigned char n)
References setulong.
CBigNum::CBigNum(unsigned short n)
References setulong.
CBigNum::CBigNum(unsigned int n)
References setulong.
CBigNum::CBigNum(unsigned long n)
References setulong.
CBigNum::CBigNum(unsigned long long n)
References setuint64.
CBigNum::CBigNum(uint256 n)
References setuint256.
CBigNum::CBigNum(const std::vector< unsigned char > &vch)
References setvch.
int CBigNum::bitSize() const
Returns the size in bits of the underlying bignum.the size
void CBigNum::setulong(unsigned long n)
Referenced by CBigNum, BOOST_AUTO_TEST_CASE.
unsigned long CBigNum::getulong() const
Referenced by ToString, EvalScript.
unsigned int CBigNum::getuint() const
int CBigNum::getint() const
Referenced by EvalScript, ValueString.
void CBigNum::setint64(int64_t sn)
Referenced by CBigNum, mysetint64.
uint64_t CBigNum::getuint64()
void CBigNum::setuint64(uint64_t n)
Referenced by CBigNum.
void CBigNum::setuint256(uint256 n)
Referenced by CBigNum.
uint256 CBigNum::getuint256() const
Referenced by CBlockIndex::GetBlockTrust, CheckStakeKernelHash, CheckWork, CheckProofOfWork, getworkex, getwork, getblocktemplate, CTxDB::LoadBlockIndex.
void CBigNum::setvch(const std::vector< unsigned char > &vch)
Referenced by CBigNum, Unserialize.
std::vector<unsigned char> CBigNum::getvch() const
Referenced by GetSerializeSize, Serialize, EvalScript, CScript::push_int64, CScript::push_uint64, CScript::operator<<.
CBigNum& CBigNum::SetCompact(unsigned int nCompact)
Referenced by CBlockIndex::GetBlockTrust, CheckStakeKernelHash, GetNextTargetRequired, CheckWork, CheckProofOfWork, getworkex, getwork, getblocktemplate, CWallet::CreateCoinStake.
unsigned int CBigNum::GetCompact() const
Referenced by GetNextTargetRequired.
void CBigNum::SetHex(const std::string &str)
References HexDigit.
Referenced by BOOST_AUTO_TEST_CASE.
std::string CBigNum::ToString(int nBase=10) const
References getulong.
Referenced by GetHex, operator<<, InvalidChainFound, CBlock::SetBestChain, BOOST_AUTO_TEST_CASE, CTxDB::LoadBlockIndex.
std::string CBigNum::GetHex() const
References ToString.
Referenced by BOOST_AUTO_TEST_CASE.
unsigned int CBigNum::GetSerializeSize(int nType=0, int nVersion=PROTOCOL_VERSION) const
References GetSerializeSize, getvch.
void CBigNum::Serialize(Stream &s, int nType=0, int nVersion=PROTOCOL_VERSION) const
References getvch.
void CBigNum::Unserialize(Stream &s, int nType=0, int nVersion=PROTOCOL_VERSION)
References setvch.
CBigNum CBigNum::pow(const int e) const
exponentiation with an int. this^e e the exponent as an int
References CBigNum.
CBigNum CBigNum::pow(const CBigNum &e) const
exponentiation this^e e the exponent
CBigNum CBigNum::mul_mod(const CBigNum &b, const CBigNum &m) const
modular multiplication: (this * b) mod m b operand m modulus
CBigNum CBigNum::pow_mod(const CBigNum &e, const CBigNum &m) const
modular exponentiation: this^e mod n e exponent m modulus
References inverse.
CBigNum CBigNum::inverse(const CBigNum &m) const
Calculates the inverse of this element mod m. i.e. i such this*i = 1 mod m m the modu the inverse
Referenced by pow_mod.
CBigNum CBigNum::gcd(const CBigNum &b) const
Calculates the greatest common divisor (GCD) of two numbers. m the second element the GCD
bool CBigNum::isPrime(const int checks=BN_prime_checks) const
Miller-Rabin primality test on this element checks optional, the number of Miller-Rabin tests to run default causes error rate of 2^-80. true if prime
bool CBigNum::isOne() const
bool CBigNum::operator!() const
CBigNum& CBigNum::operator+=(const CBigNum &b)
CBigNum& CBigNum::operator-=(const CBigNum &b)
CBigNum& CBigNum::operator*=(const CBigNum &b)
CBigNum& CBigNum::operator/=(const CBigNum &b)
CBigNum& CBigNum::operator%=(const CBigNum &b)
CBigNum& CBigNum::operator<<=(unsigned int shift)
CBigNum& CBigNum::operator>>=(unsigned int shift)
CBigNum& CBigNum::operator++()
const CBigNum CBigNum::operator++(int)
CBigNum& CBigNum::operator--()
const CBigNum CBigNum::operator--(int)
static CBigNum CBigNum::randBignum(const CBigNum &range)
Generates a cryptographically secure random number between zero and range exclusive i.e. 0 < returned number < range range The upper bound on the number.
static CBigNum CBigNum::RandKBitBigum(const uint32_t k)
Generates a cryptographically secure random k-bit number k The bit length of the number.
static CBigNum CBigNum::generatePrime(const unsigned int numBits, bool safe=false)
Generates a random (safe) prime of numBits bits numBits the number of bits safe true for a safe prime the prime
const CBigNum operator-(const CBigNum &a, const CBigNum &b)
const CBigNum operator/(const CBigNum &a, const CBigNum &b)
const CBigNum operator%(const CBigNum &a, const CBigNum &b)
const CBigNum operator*(const CBigNum &a, const CBigNum &b)
bool operator<(const CBigNum &a, const CBigNum &b)