leveldb::Table
Rep* leveldb::Table::rep_
friend class TableCache
Status leveldb::Table::Open(const Options &options, RandomAccessFile *file, uint64_t file_size, Table **table)
References leveldb::Footer::kEncodedLength, leveldb::Status::Corruption, leveldb::RandomAccessFile::Read, leveldb::Status::ok, leveldb::Footer::DecodeFrom, leveldb::Options::paranoid_checks, leveldb::ReadOptions::verify_checksums, leveldb::ReadBlock, leveldb::Footer::index_handle, leveldb::Table::Rep::options, leveldb::Table::Rep::file, leveldb::Table::Rep::metaindex_handle, leveldb::Footer::metaindex_handle, leveldb::Table::Rep::index_block, leveldb::Table::Rep::cache_id, leveldb::Options::block_cache, leveldb::Cache::NewId, leveldb::Table::Rep::filter_data, leveldb::Table::Rep::filter.
Referenced by leveldb::TableConstructor::FinishImpl.
leveldb::Table::~Table()
Iterator * leveldb::Table::NewIterator(const ReadOptions &) const
References leveldb::NewTwoLevelIterator, leveldb::Table::Rep::index_block, leveldb::Block::NewIterator, leveldb::Table::Rep::options, leveldb::Options::comparator.
Referenced by leveldb::TableCache::NewIterator, leveldb::TableConstructor::NewIterator.
uint64_t leveldb::Table::ApproximateOffsetOf(const Slice &key) const
References leveldb::Table::Rep::index_block, leveldb::Block::NewIterator, leveldb::Table::Rep::options, leveldb::Options::comparator, leveldb::Iterator::Seek, leveldb::Iterator::Valid, leveldb::Iterator::value, leveldb::BlockHandle::DecodeFrom, leveldb::Status::ok, leveldb::BlockHandle::offset, leveldb::Table::Rep::metaindex_handle.
Referenced by leveldb::VersionSet::ApproximateOffsetOf, leveldb::TableConstructor::ApproximateOffsetOf.
leveldb::Table::Table(Rep *rep)
Status leveldb::Table::InternalGet(const ReadOptions &, const Slice &key, void *arg, void(*handle_result)(void *arg, const Slice &k, const Slice &v))
void leveldb::Table::ReadMeta(const Footer &footer)
void leveldb::Table::ReadFilter(const Slice &filter_handle_value)
leveldb::Table::Table(const Table &)
void leveldb::Table::operator=(const Table &)
Iterator * leveldb::Table::BlockReader(void *, const ReadOptions &, const Slice &)