PeerTableModel
int PeerTableModel::rowCount(const QModelIndex &parent) const
References PeerTablePriv::size.
int PeerTableModel::columnCount(const QModelIndex &parent) const
QVariant PeerTableModel::data(const QModelIndex &index, int role) const
References Address, CNodeCombinedStats::nodeStats, CNodeStats::addrName, Subversion, CNodeStats::cleanSubVer, Ping, GUIUtil::formatPingTime, CNodeStats::dPingTime.
Referenced by index.
QVariant PeerTableModel::headerData(int section, Qt::Orientation orientation, int role) const
QModelIndex PeerTableModel::index(int row, int column, const QModelIndex &parent) const
References data, PeerTablePriv::index.
Qt::ItemFlags PeerTableModel::flags(const QModelIndex &index) const
void PeerTableModel::sort(int column, Qt::SortOrder order)
References PeerTablePriv::sortColumn, PeerTablePriv::sortOrder, refresh.
ColumnIndex
ClientModel* PeerTableModel::clientModel
QStringList PeerTableModel::columns
PeerTablePriv* PeerTableModel::priv
QTimer* PeerTableModel::timer
PeerTableModel::PeerTableModel(ClientModel *parent=0)
References PeerTablePriv::sortColumn, refresh.
const CNodeCombinedStats * PeerTableModel::getNodeStats(int idx)
References PeerTablePriv::index.
Referenced by DEBUGConsole::peerSelected, DEBUGConsole::peerLayoutChanged.
int PeerTableModel::getRowByNodeId(NodeId nodeid)
References PeerTablePriv::mapNodeRows.
Referenced by DEBUGConsole::peerLayoutChanged.
void PeerTableModel::startAutoRefresh()
void PeerTableModel::stopAutoRefresh()
void PeerTableModel::refresh()
References PeerTablePriv::refreshPeers.
Referenced by PeerTableModel, sort.