CStealthAddress
uint8_t CStealthAddress::options
Referenced by SetEncoded, Encoded, CStealthAddress.
ec_point CStealthAddress::scan_pubkey
Referenced by WalletModel::sendCoins, importstealthaddress, SetEncoded, Encoded, operator<, CWallet::Lock, CWallet::NewStealthAddress, CWallet::UnlockStealthAddresses, CWallet::SendStealthMoneyToDestination, CWalletDB::WriteStealthAddress, CWalletDB::ReadStealthAddress.
ec_point CStealthAddress::spend_pubkey
Referenced by WalletModel::sendCoins, importstealthaddress, SetEncoded, Encoded, CWallet::EncryptWallet, CWallet::NewStealthAddress, CWallet::AddStealthAddress, CWallet::UnlockStealthAddresses, CWallet::SendStealthMoneyToDestination.
size_t CStealthAddress::number_signatures
stealth_prefix CStealthAddress::prefix
std::string CStealthAddress::label
Referenced by AddressTableModel::addRow, liststealthaddresses, importstealthaddress, CWallet::NewStealthAddress, CWallet::AddStealthAddress, CWallet::UpdateStealthAddress.
data_chunk CStealthAddress::scan_secret
Referenced by liststealthaddresses, importstealthaddress, CKeyStoreIsMineVisitor::operator(), CWallet::NewStealthAddress, CWallet::AddStealthAddress, CWallet::UpdateStealthAddress.
data_chunk CStealthAddress::spend_secret
Referenced by liststealthaddresses, importstealthaddress, CWallet::Lock, CWallet::EncryptWallet, CWallet::NewStealthAddress, CWallet::AddStealthAddress, CWallet::UnlockStealthAddresses.
CStealthAddress::ADD_SERIALIZE_METHODS
CStealthAddress::CStealthAddress()
References options.
bool CStealthAddress::SetEncoded(const std::string &encodedAddress)
References DecodeBase58, fDebug, VerifyChecksum, version, stealth_version_byte, options, scan_pubkey, spend_pubkey.
Referenced by AddressTableModel::addRow, AddressTableModel::labelForAddress, WalletModel::sendCoins, sendtostealthaddress.
std::string CStealthAddress::Encoded() const
References stealth_version_byte, options, scan_pubkey, spend_pubkey, AppendChecksum, EncodeBase58.
Referenced by AddressTableModel::addRow, getnewstealthaddress, liststealthaddresses, importstealthaddress, operator==, CWallet::Lock, CWallet::EncryptWallet, CWallet::AddStealthAddress, CWallet::UnlockStealthAddresses.
bool CStealthAddress::operator<(const CStealthAddress &y) const
References scan_pubkey, ec_compressed_size.
bool CStealthAddress::operator==(const CStealthAddress &y) const
References Encoded.
void CStealthAddress::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE.