CStormnodeSync
std::map<uint256, int> CStormnodeSync::mapSeenSyncSNB
Referenced by Reset, AddedStormnodeList, CStormnodeBroadcast::CheckInputsAndAdd, CStormnodeMan::CheckAndRemove.
std::map<uint256, int> CStormnodeSync::mapSeenSyncSNW
Referenced by CStormnodePayments::CleanPaymentList, Reset, AddedStormnodeWinner.
std::map<uint256, int> CStormnodeSync::mapSeenSyncBudget
Referenced by Reset, AddedBudgetItem.
int64_t CStormnodeSync::lastStormnodeList
Referenced by Reset, AddedStormnodeList, Process.
int64_t CStormnodeSync::lastStormnodeWinner
Referenced by Reset, AddedStormnodeWinner, Process.
int64_t CStormnodeSync::lastBudgetItem
Referenced by Reset, AddedBudgetItem, Process.
int64_t CStormnodeSync::lastFailure
Referenced by Reset, Process.
int CStormnodeSync::nCountFailures
Referenced by Reset, Process.
int CStormnodeSync::sumStormnodeList
Referenced by Reset, ProcessMessage.
int CStormnodeSync::sumStormnodeWinner
Referenced by Reset, ProcessMessage.
int CStormnodeSync::sumBudgetItemProp
Referenced by Reset, IsBudgetPropEmpty, ProcessMessage.
int CStormnodeSync::sumBudgetItemFin
Referenced by Reset, IsBudgetFinEmpty, ProcessMessage.
int CStormnodeSync::countStormnodeList
Referenced by Reset, ProcessMessage.
int CStormnodeSync::countStormnodeWinner
Referenced by Reset, ProcessMessage.
int CStormnodeSync::countBudgetItemProp
Referenced by Reset, IsBudgetPropEmpty, ProcessMessage.
int CStormnodeSync::countBudgetItemFin
Referenced by Reset, IsBudgetFinEmpty, ProcessMessage.
int CStormnodeSync::RequestedStormnodeAssets
Referenced by stormnode, CBudgetManager::NewBlock, IsSynced, Reset, GetNextAsset, GetSyncStatus, ProcessMessage, Process.
int CStormnodeSync::RequestedStormnodeAttempt
Referenced by Reset, GetNextAsset, Process.
int64_t CStormnodeSync::nAssetSyncStarted
Referenced by Reset, GetNextAsset, Process.
CStormnodeSync::CStormnodeSync()
References Reset.
void CStormnodeSync::AddedStormnodeList(uint256 hash)
References snodeman, CStormnodeMan::mapSeenStormnodeBroadcast, mapSeenSyncSNB, lastStormnodeList, GetTime, hash.
Referenced by CStormnodeBroadcast::CheckAndUpdate, CStormnodeMan::ProcessMessage.
void CStormnodeSync::AddedStormnodeWinner(uint256 hash)
References stormnodePayments, CStormnodePayments::mapStormnodePayeeVotes, mapSeenSyncSNW, lastStormnodeWinner, GetTime, hash.
Referenced by CStormnodePayments::ProcessMessageStormnodePayments.
void CStormnodeSync::AddedBudgetItem(uint256 hash)
References budget, CBudgetManager::mapSeenStormnodeBudgetProposals, CBudgetManager::mapSeenStormnodeBudgetVotes, CBudgetManager::mapSeenFinalizedBudgets, CBudgetManager::mapSeenFinalizedBudgetVotes, mapSeenSyncBudget, lastBudgetItem, GetTime, hash.
Referenced by CBudgetManager::ProcessMessage.
void CStormnodeSync::GetNextAsset()
References RequestedStormnodeAssets, ClearFulfilledRequest, LogPrintf, RequestedStormnodeAttempt, nAssetSyncStarted, GetTime.
Referenced by Process.
std::string CStormnodeSync::GetSyncStatus()
References RequestedStormnodeAssets, _.
void CStormnodeSync::ProcessMessage(CNode *pfrom, std::string &strCommand, CDataStream &vRecv)
References RequestedStormnodeAssets, sumStormnodeList, countStormnodeList, sumStormnodeWinner, countStormnodeWinner, sumBudgetItemProp, countBudgetItemProp, sumBudgetItemFin, countBudgetItemFin, LogPrintf.
bool CStormnodeSync::IsBudgetFinEmpty()
References sumBudgetItemFin, countBudgetItemFin.
Referenced by CBudgetManager::HasNextFinalizedBudget.
bool CStormnodeSync::IsBudgetPropEmpty()
References sumBudgetItemProp, countBudgetItemProp.
void CStormnodeSync::Reset()
References lastStormnodeList, lastStormnodeWinner, lastBudgetItem, mapSeenSyncSNB, mapSeenSyncSNW, mapSeenSyncBudget, lastFailure, nCountFailures, sumStormnodeList, sumStormnodeWinner, sumBudgetItemProp, sumBudgetItemFin, countStormnodeList, countStormnodeWinner, countBudgetItemProp, countBudgetItemFin, RequestedStormnodeAssets, RequestedStormnodeAttempt, nAssetSyncStarted, GetTime.
Referenced by CStormnodeSync, IsBlockchainSynced, Process.
void CStormnodeSync::Process()
References IsSynced, snodeman, CStormnodeMan::CountEnabled, Reset, RequestedStormnodeAssets, lastFailure, GetTime, fDebug, LogPrintf, GetNextAsset, Params, CChainParams::TESTNET, IsBlockchainSynced, TRY_LOCK, cs_vNodes, vNodes, RequestedStormnodeAttempt, CNode::PushMessage, CStormnodeMan::SsegUpdate, CNode::HasFulfilledRequest, CNode::FulfilledRequest, CNode::nVersion, stormnodePayments, CStormnodePayments::GetMinStormnodePaymentsProto, lastStormnodeList, nAssetSyncStarted, IsSporkActive, nCountFailures, lastStormnodeWinner, pindexBest, lastBudgetItem, activeStormnode, CActiveStormnode::ManageStatus.
Referenced by ThreadCheckSandStormPool.
bool CStormnodeSync::IsSynced()
References RequestedStormnodeAssets.
Referenced by stormnode, CBudgetManager::NewBlock, CBudgetManager::ProcessMessage, CBudgetManager::UpdateProposal, CBudgetManager::UpdateFinalizedBudget, IsBlockValueValid, IsBlockPayeeValid, CStormnodePayments::ProcessMessageStormnodePayments, CStormnodePaymentWinner::IsValid, Process.
bool CStormnodeSync::IsBlockchainSynced()
References GetTime, Reset, fImporting, fReindex, TRY_LOCK, cs_main, pindexBest, CBlockIndex::nTime.
Referenced by CActiveStormnode::ManageStatus, CActiveStormnode::Register, ProcessMessageInstantX, snbudget, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::GetStatus, CSandstormPool::DoAutomaticDenominating, ThreadCheckSandStormPool, CBudgetManager::ProcessMessage, CStormnodePayments::ProcessMessageStormnodePayments, Process, CStormnodeMan::ProcessMessage.
void CStormnodeSync::ClearFulfilledRequest()
References TRY_LOCK, cs_vNodes, vNodes, CNode::ClearFulfilledRequest.
Referenced by GetNextAsset.