CStormnodeMan
CCriticalSection CStormnodeMan::cs
CCriticalSection CStormnodeMan::cs_process_message
std::vector<CStormnode> CStormnodeMan::vStormnodes
std::map<CNetAddr, int64_t> CStormnodeMan::mAskedUsForStormnodeList
std::map<CNetAddr, int64_t> CStormnodeMan::mWeAskedForStormnodeList
std::map<COutPoint, int64_t> CStormnodeMan::mWeAskedForStormnodeListEntry
map<uint256, CStormnodeBroadcast> CStormnodeMan::mapSeenStormnodeBroadcast
Referenced by CStormnodeSync::AddedStormnodeList, CStormnodeBroadcast::CheckInputsAndAdd, CStormnodePing::CheckAndUpdate, CheckAndRemove, Clear, ProcessMessage.
map<uint256, CStormnodePing> CStormnodeMan::mapSeenStormnodePing
Referenced by CStormnode::UpdateFromNewBroadcast, CheckAndRemove, Clear, ProcessMessage.
int64_t CStormnodeMan::nSsqCount
Referenced by CSandstormPool::ProcessMessageSandstorm, CSandstormPool::DoAutomaticDenominating, CStormnodeMan, Clear, ToString.
CStormnodeMan::ADD_SERIALIZE_METHODS
void CStormnodeMan::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References LOCK, READWRITE.
CStormnodeMan::CStormnodeMan()
References nSsqCount.
CStormnodeMan::CStormnodeMan(CStormnodeMan &other)
bool CStormnodeMan::Add(CStormnode &sn)
Add an entry.
References LOCK, CStormnode::IsEnabled, CStormnode::IsPreEnabled, Find, CStormnode::vin, CStormnode::addr, CService::ToString, size.
Referenced by CStormnodeBroadcast::CheckInputsAndAdd.
void CStormnodeMan::AskForSN(CNode *pnode, CTxIn &vin)
Ask (source) node for snb.
References CTxIn::prevout, GetTime, LogPrintf, CTxIn::ToString, CNode::PushMessage.
Referenced by ProcessConsensusVote, CBudgetManager::ProcessMessage, CStormnodePayments::ProcessMessageStormnodePayments, CStormnodePaymentWinner::IsValid, ProcessMessage.
void CStormnodeMan::Check()
Check all Stormnodes.
References LOCK, CStormnode::Check.
Referenced by CheckAndRemove.
void CStormnodeMan::CheckAndRemove(bool forceExpiredRemoval=false)
Check all Stormnodes and remove inactive.
References Check, LOCK, CStormnode::STORMNODE_REMOVE, CStormnode::STORMNODE_VIN_SPENT, CStormnode::STORMNODE_EXPIRED, stormnodePayments, CStormnodePayments::GetMinStormnodePaymentsProto, size, mapSeenStormnodeBroadcast, stormnodeSync, CStormnodeSync::mapSeenSyncSNB, GetTime, mapSeenStormnodePing.
Referenced by AppInit2, ThreadCheckSandStormPool, CStormnodeDB::Read.
void CStormnodeMan::Clear()
Clear Stormnode vector.
References LOCK, mapSeenStormnodeBroadcast, mapSeenStormnodePing, nSsqCount.
Referenced by CStormnodeDB::Read.
int CStormnodeMan::CountEnabled(int protocolVersion=-1)
References stormnodePayments, CStormnodePayments::GetMinStormnodePaymentsProto, CStormnode::Check, CStormnode::protocolVersion, CStormnode::IsEnabled.
Referenced by ClientModel::getStormnodeCountString, stormnode, CSandStormRelay::Relay, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::DoAutomaticDenominating, CBudgetManager::IsBudgetPaymentBlock, CBudgetManager::IsTransactionValid, CBudgetManager::GetBudget, CBudgetProposal::IsValid, CStormnodePayments::ProcessMessageStormnodePayments, CStormnodePayments::Sync, CStormnodeSync::Process, CStormnode::GetLastPaid, GetNextStormnodeInQueueForPayment, FindRandomNotInVec.
void CStormnodeMan::SsegUpdate(CNode *pnode)
References LOCK, Params, CChainParams::MAIN, CNode::addr, CNetAddr::IsRFC1918, CNetAddr::IsLocal, GetTime, LogPrintf, CService::ToString, CNode::PushMessage.
Referenced by CStormnodeSync::Process.
CStormnode * CStormnodeMan::Find(const CScript &payee)
Find an entry.
References LOCK, GetScriptForDestination, CStormnode::pubkey, CPubKey::GetID.
Referenced by CActiveStormnode::ManageStatus, ProcessConsensusVote, CConsensusVote::SignatureValid, snbudget, snbudgetvoteraw, snfinalbudget, stormnode, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::DoAutomaticDenominating, CSandstormQueue::CheckSignature, CSandstormQueue::GetAddress, CSandstormQueue::GetProtocolVersion, CBudgetManager::ProcessMessage, CBudgetVote::SignatureValid, CFinalizedBudgetVote::SignatureValid, CStormnodePaymentWinner::IsValid, CStormnodePaymentWinner::SignatureValid, CStormnodeBroadcast::CheckAndUpdate, CStormnodeBroadcast::CheckInputsAndAdd, CStormnodePing::CheckAndUpdate, Add, GetNextStormnodeInQueueForPayment, GetStormnodeByRank, ProcessMessage.
CStormnode * CStormnodeMan::Find(const CTxIn &vin)
References LOCK, CStormnode::vin, CTxIn::prevout.
CStormnode * CStormnodeMan::Find(const CPubKey &pubKeyStormnode)
References LOCK, CStormnode::pubkey2.
CStormnode * CStormnodeMan::GetNextStormnodeInQueueForPayment(int nBlockHeight, bool fFilterSigTime, int &nCount)
Find an entry in the stormnode list that is next to be paid.
References LOCK, CountEnabled, CStormnode::Check, CStormnode::IsEnabled, CStormnode::protocolVersion, stormnodePayments, CStormnodePayments::GetMinStormnodePaymentsProto, CStormnodePayments::IsScheduled, CStormnode::sigTime, GetAdjustedTime, CStormnode::GetStormnodeInputAge, CStormnode::SecondsSincePayment, CStormnode::vin, PAIRTYPE, Find, CStormnode::CalculateScore.
Referenced by stormnode, CStormnodePayments::ProcessBlock.
CStormnode * CStormnodeMan::FindRandomNotInVec(std::vector< CTxIn > &vecToExclude, int protocolVersion=-1)
Find a random entry.
References LOCK, stormnodePayments, CStormnodePayments::GetMinStormnodePaymentsProto, CountEnabled, LogPrintf, rand, GetRandInt, CStormnode::protocolVersion, CStormnode::IsEnabled, CStormnode::vin, CTxIn::prevout.
Referenced by CSandstormPool::DoAutomaticDenominating.
CStormnode * CStormnodeMan::GetCurrentStormNode(int mod=1, int64_t nBlockHeight=0, int minProtocol=0)
Get the current winner for this block.
References CStormnode::Check, CStormnode::protocolVersion, CStormnode::IsEnabled, CStormnode::CalculateScore, uint256::GetCompact.
Referenced by getpoolinfo, stormnode, CStormnodePayments::FillBlockPayee, CWallet::CreateCoinStake.
std::vector<CStormnode> CStormnodeMan::GetFullStormnodeVector()
Referenced by StormnodeManager::on_UpdateButton_clicked, stormnode, stormnodelist.
std::vector< pair< int, CStormnode > > CStormnodeMan::GetStormnodeRanks(int64_t nBlockHeight, int minProtocol=0)
References hash, GetBlockHash, CStormnode::Check, CStormnode::protocolVersion, CStormnode::IsEnabled, CStormnode::CalculateScore, uint256::GetCompact, PAIRTYPE.
Referenced by stormnodelist.
int CStormnodeMan::GetStormnodeRank(const CTxIn &vin, int64_t nBlockHeight, int minProtocol=0, bool fOnlyActive=true)
References hash, GetBlockHash, CStormnode::protocolVersion, CStormnode::Check, CStormnode::IsEnabled, CStormnode::CalculateScore, uint256::GetCompact, CStormnode::vin, PAIRTYPE, CTxIn::prevout.
Referenced by DoConsensusVote, ProcessConsensusVote, CTransactionLock::SignaturesValid, CStormnodePaymentWinner::IsValid, CStormnodePayments::ProcessBlock.
CStormnode * CStormnodeMan::GetStormnodeByRank(int nRank, int64_t nBlockHeight, int minProtocol=0, bool fOnlyActive=true)
References CStormnode::protocolVersion, CStormnode::Check, CStormnode::IsEnabled, CStormnode::CalculateScore, uint256::GetCompact, CStormnode::vin, PAIRTYPE, Find.
Referenced by CSandStormRelay::RelayThroughNode.
void CStormnodeMan::ProcessStormnodeConnections()
References LOCK, cs_vNodes, vNodes, CNode::fSandStorm, sandStormPool, CSandstormPool::pSubmittedToStormnode, CNode::addr, CStormnode::addr, LogPrintf, CService::ToString, CNode::fDisconnect.
Referenced by ThreadCheckSandStormPool.
void CStormnodeMan::ProcessMessage(CNode *pfrom, std::string &strCommand, CDataStream &vRecv)
References fLiteMode, stormnodeSync, CStormnodeSync::IsBlockchainSynced, LOCK, mapSeenStormnodeBroadcast, CStormnodeSync::AddedStormnodeList, Misbehaving, CNode::GetId, sandStormSigner, CSandStormSigner::IsVinAssociatedWithPubkey, LogPrintf, addrman, CAddrMan::Add, CNode::addr, mapSeenStormnodePing, Find, AskForSN, CNetAddr::IsRFC1918, CNetAddr::IsLocal, Params, CChainParams::NetworkID, CChainParams::MAIN, GetTime, CStormnode::addr, CStormnode::IsEnabled, CService::ToString, CStormnode::vin, hash, CStormnodeBroadcast::GetHash, CNode::PushInventory, MSG_STORMNODE_ANNOUNCE, CNode::PushMessage.
int CStormnodeMan::size()
Return the number of (unique) Stormnodes.
Referenced by ClientModel::getStormnodeCountString, stormnode, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::DoAutomaticDenominating, CStormnodePayments::CleanPaymentList, Add, CheckAndRemove, Remove.
std::string CStormnodeMan::ToString() const
References nSsqCount.
Referenced by AppInit2, CStormnodeDB::Read.
void CStormnodeMan::Remove(CTxIn vin)
References LOCK, size.
Referenced by CStormnodeBroadcast::CheckInputsAndAdd.