leveldb::Random
uint32_t leveldb::Random::seed_
leveldb::Random::Random(uint32_t s)
uint32_t leveldb::Random::Next()
Referenced by leveldb::TEST, leveldb::ConcurrentTest::WriteStep, leveldb::ConcurrentTest::ReadStep, Uniform, OneIn.
uint32_t leveldb::Random::Uniform(int n)
References Next.
Referenced by leveldb::TEST, leveldb::Harness::TestRandomAccess, leveldb::Harness::PickRandomKey, Skewed, leveldb::test::RandomString, leveldb::test::RandomKey.
bool leveldb::Random::OneIn(int n)
References Next.
Referenced by leveldb::TEST.
uint32_t leveldb::Random::Skewed(int max_log)
References Uniform.
Referenced by leveldb::TEST.