BlockBrowser
Ui::BlockBrowser* BlockBrowser::ui
ClientModel* BlockBrowser::model
BlockBrowser::BlockBrowser(QWidget *parent=0)
References blockClicked, txClicked.
BlockBrowser::~BlockBrowser()
void BlockBrowser::setModel(ClientModel *model)
void BlockBrowser::blockClicked()
References updateExplorer.
Referenced by BlockBrowser.
void BlockBrowser::txClicked()
References updateExplorer.
Referenced by BlockBrowser.
void BlockBrowser::updateExplorer(bool)
References pindexBest, CBlockIndex::nHeight, getBlockHashrate, hash, getBlockHash, getBlockMerkle, getBlocknBits, getBlockNonce, getBlockTime, getBlockHardness, value, getTxTotalValue, getTxFees, getOutputs, getInputs.
Referenced by txClicked, blockClicked.