CECKey
EC_KEY* CECKey::pkey
CECKey::CECKey()
CECKey::~CECKey()
EC_KEY* CECKey::GetECKey()
Referenced by SecureMsgEncrypt, SecureMsgDecrypt.
void CECKey::GetSecretBytes(unsigned char vch[32]) const
void CECKey::SetSecretBytes(const unsigned char vch[32])
Referenced by SecureMsgEncrypt, SecureMsgDecrypt.
int CECKey::GetPrivKeySize(bool fCompressed)
int CECKey::GetPrivKey(unsigned char *privkey, bool fCompressed)
bool CECKey::SetPrivKey(const unsigned char *privkey, size_t size, bool fSkipCheck=false)
void CECKey::GetPubKey(std::vector< unsigned char > &pubkey, bool fCompressed)
References begin_ptr.
Referenced by SignCompact.
bool CECKey::SetPubKey(const unsigned char *pubkey, size_t size)
Referenced by SecureMsgEncrypt, SecureMsgDecrypt.
bool CECKey::Sign(const uint256 &hash, std::vector< unsigned char > &vchSig)
bool CECKey::Verify(const uint256 &hash, const std::vector< unsigned char > &vchSig)
References base_uint< BITS >::size.
bool CECKey::SignCompact(const uint256 &hash, unsigned char *p64, int &rec)
References GetPubKey.
bool CECKey::Recover(const uint256 &hash, const unsigned char *p64, int rec)
bool CECKey::TweakPublic(const unsigned char vchTweak[32])
bool CECKey::TweakSecret(unsigned char vchSecretOut[32], const unsigned char vchSecretIn[32], const unsigned char vchTweak[32])
bool CECKey::SanityCheck()