MRichTextEdit
ParagraphItems
QStringList MRichTextEdit::m_paragraphItems
Referenced by MRichTextEdit.
int MRichTextEdit::m_fontsize_h1
Referenced by MRichTextEdit, textStyle, fontChanged.
int MRichTextEdit::m_fontsize_h2
Referenced by MRichTextEdit, textStyle, fontChanged.
int MRichTextEdit::m_fontsize_h3
Referenced by MRichTextEdit, textStyle, fontChanged.
int MRichTextEdit::m_fontsize_h4
Referenced by MRichTextEdit, textStyle, fontChanged.
QPointer<QTextList> MRichTextEdit::m_lastBlockList
Referenced by MRichTextEdit, slotCursorPositionChanged.
MRichTextEdit::MRichTextEdit(QWidget *parent=0)
References m_lastBlockList, slotCurrentCharFormatChanged, slotCursorPositionChanged, m_fontsize_h1, m_fontsize_h2, m_fontsize_h3, m_fontsize_h4, fontChanged, bgColorChanged, m_paragraphItems, textStyle, slotClipboardDataChanged, textLink, textBold, textItalic, textUnderline, textStrikeout, listBullet, listOrdered, increaseIndentation, decreaseIndentation, textSize, textBgColor.
QString MRichTextEdit::toPlainText() const
QString MRichTextEdit::toHtml() const
QTextDocument* MRichTextEdit::document()
QTextCursor MRichTextEdit::textCursor() const
void MRichTextEdit::setTextCursor(const QTextCursor &cursor)
void MRichTextEdit::setText(const QString &text)
References setPlainText, setHtml.
void MRichTextEdit::clear()
void MRichTextEdit::setPlainText(const QString &text)
Referenced by setText.
void MRichTextEdit::setHtml(const QString &text)
Referenced by setText.
void MRichTextEdit::textBold()
References mergeFormatOnWordOrSelection.
Referenced by MRichTextEdit.
void MRichTextEdit::textUnderline()
References mergeFormatOnWordOrSelection.
Referenced by MRichTextEdit.
void MRichTextEdit::textStrikeout()
References mergeFormatOnWordOrSelection.
Referenced by MRichTextEdit.
void MRichTextEdit::textItalic()
References mergeFormatOnWordOrSelection.
Referenced by MRichTextEdit.
void MRichTextEdit::textSize(const QString &p)
References mergeFormatOnWordOrSelection.
Referenced by MRichTextEdit.
void MRichTextEdit::textLink(bool checked)
References url, mergeFormatOnWordOrSelection.
Referenced by MRichTextEdit.
void MRichTextEdit::textStyle(int index)
References ParagraphHeading1, ParagraphHeading2, ParagraphHeading3, ParagraphHeading4, m_fontsize_h1, m_fontsize_h2, m_fontsize_h3, m_fontsize_h4, ParagraphMonospace.
Referenced by MRichTextEdit.
void MRichTextEdit::textBgColor()
References bgColorChanged.
Referenced by MRichTextEdit.
void MRichTextEdit::listBullet(bool checked)
References list.
Referenced by MRichTextEdit.
void MRichTextEdit::listOrdered(bool checked)
References list.
Referenced by MRichTextEdit.
void MRichTextEdit::slotCurrentCharFormatChanged(const QTextCharFormat &format)
References fontChanged, bgColorChanged.
Referenced by MRichTextEdit.
void MRichTextEdit::slotCursorPositionChanged()
References m_lastBlockList.
Referenced by MRichTextEdit.
void MRichTextEdit::slotClipboardDataChanged()
Referenced by MRichTextEdit.
void MRichTextEdit::increaseIndentation()
References indent.
Referenced by MRichTextEdit.
void MRichTextEdit::decreaseIndentation()
References indent.
Referenced by MRichTextEdit.
void MRichTextEdit::mergeFormatOnWordOrSelection(const QTextCharFormat &format)
Referenced by textBold, textUnderline, textItalic, textStrikeout, textSize, textLink.
void MRichTextEdit::fontChanged(const QFont &f)
References m_fontsize_h1, ParagraphHeading1, m_fontsize_h2, ParagraphHeading2, m_fontsize_h3, ParagraphHeading3, m_fontsize_h4, ParagraphHeading4, ParagraphMonospace, ParagraphStandard.
Referenced by MRichTextEdit, slotCurrentCharFormatChanged.
void MRichTextEdit::bgColorChanged(const QColor &c)
Referenced by MRichTextEdit, textBgColor, slotCurrentCharFormatChanged.
void MRichTextEdit::list(bool checked, QTextListFormat::Style style)
Referenced by listBullet, listOrdered.
void MRichTextEdit::indent(int delta)
Referenced by increaseIndentation, decreaseIndentation.
void MRichTextEdit::focusInEvent(QFocusEvent *event)