LockedPageManagerBase
typedef std::map<size_t,int> LockedPageManagerBase< Locker >::Histogram
Locker LockedPageManagerBase< Locker >::locker
boost::mutex LockedPageManagerBase< Locker >::mutex
size_t LockedPageManagerBase< Locker >::page_size
size_t LockedPageManagerBase< Locker >::page_mask
Histogram LockedPageManagerBase< Locker >::histogram
LockedPageManagerBase< Locker >::LockedPageManagerBase(size_t page_size)
void LockedPageManagerBase< Locker >::LockRange(void *p, size_t size)
Referenced by LockObject, secure_allocator< T >::allocate, CCrypter::CCrypter, SecMsgCrypter::SecMsgCrypter, SecMsgCrypter::~SecMsgCrypter, BOOST_AUTO_TEST_CASE.
void LockedPageManagerBase< Locker >::UnlockRange(void *p, size_t size)
Referenced by UnlockObject, secure_allocator< T >::deallocate, CCrypter::~CCrypter, BOOST_AUTO_TEST_CASE.
int LockedPageManagerBase< Locker >::GetLockedPageCount()
Referenced by BOOST_AUTO_TEST_CASE.