Notificator
Class
Informational message
Mode
Ignore informational notifications, and show a modal pop-up dialog for Critical notifications.
QWidget* Notificator::parent
QString Notificator::programName
Mode Notificator::mode
QSystemTrayIcon* Notificator::trayIcon
Notificator::Notificator(const QString &programName=QString(), QSystemTrayIcon *trayIcon=0, QWidget *parent=0)
Create a new notificator. Ownership of trayIcon is not transferred to this object.
References MacNotificationHandler::instance, MacNotificationHandler::hasUserNotificationCenterSupport.
Notificator::~Notificator()
void Notificator::notify(Class cls, const QString &title, const QString &text, const QIcon &icon=QIcon(), int millisTimeout=10000)
Show notification message. cls general message class title title shown with message text message content icon optional icon to show with message millisTimeout notification timeout in milliseconds (defaults to 10 seconds) Platform implementations are free to ignore any of the provided fields except for text.
References Critical.
Referenced by DarkSilkGUI::message, DarkSilkGUI::dropEvent, DarkSilkGUI::handleURI.
void Notificator::notifySystray(Class cls, const QString &title, const QString &text, const QIcon &icon, int millisTimeout)