CAddrInfo
CNetAddr CAddrInfo::source
int64_t CAddrInfo::nLastSuccess
int CAddrInfo::nAttempts
int CAddrInfo::nRefCount
bool CAddrInfo::fInTried
int CAddrInfo::nRandomPos
friend class CAddrMan
CAddrInfo::ADD_SERIALIZE_METHODS
void CAddrInfo::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE.
void CAddrInfo::Init()
References CAddress::nLastTry.
Referenced by CAddrInfo.
CAddrInfo::CAddrInfo(const CAddress &addrIn, const CNetAddr &addrSource)
References Init.
CAddrInfo::CAddrInfo()
References Init.
int CAddrInfo::GetTriedBucket(const std::vector< unsigned char > &nKey) const
References SER_GETHASH, Hash, CDataStream::begin, CDataStream::end, ADDRMAN_TRIED_BUCKETS_PER_GROUP, ADDRMAN_TRIED_BUCKET_COUNT.
Referenced by CAddrMan::MakeTried.
int CAddrInfo::GetNewBucket(const std::vector< unsigned char > &nKey, const CNetAddr &src) const
References SER_GETHASH, CNetAddr::GetGroup, Hash, CDataStream::begin, CDataStream::end, ADDRMAN_NEW_BUCKETS_PER_SOURCE_GROUP, ADDRMAN_NEW_BUCKET_COUNT.
Referenced by CAddrMan::Add_, GetNewBucket.
int CAddrInfo::GetNewBucket(const std::vector< unsigned char > &nKey) const
References GetNewBucket.
bool CAddrInfo::IsTerrible(int64_t nNow=GetAdjustedTime()) const
References ADDRMAN_HORIZON_DAYS, ADDRMAN_RETRIES, ADDRMAN_MIN_FAIL_DAYS, ADDRMAN_MAX_FAILURES.
double CAddrInfo::GetChance(int64_t nNow=GetAdjustedTime()) const