CDarkSilkSecret
void CDarkSilkSecret::SetKey(const CKey &vchSecret)
References CKey::IsValid, CBase58Data::SetData, Params, CChainParams::SECRET_KEY, CKey::begin, CKey::size, CKey::IsCompressed, CBase58Data::vchData.
Referenced by CDarkSilkSecret, BOOST_AUTO_TEST_CASE.
CKey CDarkSilkSecret::GetKey()
References CBase58Data::vchData, CKey::Set.
Referenced by importprivkey, importwallet, signrawtransaction, CSandStormSigner::SetKey, BOOST_AUTO_TEST_CASE.
bool CDarkSilkSecret::IsValid() const
References CBase58Data::vchData, CBase58Data::vchVersion, Params, CChainParams::Base58Prefix, CChainParams::SECRET_KEY.
Referenced by SetString, BOOST_AUTO_TEST_CASE.
bool CDarkSilkSecret::SetString(const char *pszSecret)
References CBase58Data::SetString, IsValid.
Referenced by SetString, importprivkey, importwallet, signrawtransaction, CSandStormSigner::SetKey, BOOST_AUTO_TEST_CASE.
bool CDarkSilkSecret::SetString(const std::string &strSecret)
References SetString.
CDarkSilkSecret::CDarkSilkSecret(const CKey &vchSecret)
References SetKey.
CDarkSilkSecret::CDarkSilkSecret()