uint256
uint256::uint256()
uint256::uint256(const base_uint< 256 > &b)
uint256::uint256(uint64_t b)
uint256::uint256(const std::string &str)
uint256::uint256(const std::vector< unsigned char > &vch)
uint256 & uint256::SetCompact(uint32_t nCompact, bool *pfNegative=NULL, bool *pfOverflow=NULL)
The "compact" format is a representation of a whole number N using an unsigned 32bit number similar to a floating point format. The most significant 8 bits are the unsigned exponent of base 256. This exponent can be thought of as "number of bytes of N". The lower 23 bits are the mantissa. Bit number 24 (0x800000) represents the sign of N. N = (-1^sign) * mantissa * 256^(exponent-3)Satoshi's original implementation used BN_bn2mpi() and BN_mpi2bn(). MPI uses the most significant bit of the first byte as sign. Thus 0x1234560000 is compact (0x05123456) and 0xc0de000000 is compact (0x0600c0de)Bitcoin only uses this "compact" format for encoding difficulty targets, which are unsigned 256bit quantities. Thus, all the complexities of the sign bit and using base 256 are probably an implementation accident.
uint32_t uint256::GetCompact(bool fNegative=false) const
References base_uint< 256 >::bits, base_uint< 256 >::GetLow64, base_uint< BITS >::GetLow64.
Referenced by CStormnode::SecondsSincePayment, CStormnode::GetLastPaid, CStormnodeMan::GetCurrentStormNode, CStormnodeMan::GetStormnodeRank, CStormnodeMan::GetStormnodeRanks, CStormnodeMan::GetStormnodeByRank.
uint64_t uint256::GetHash(const uint256 &salt) const
References base_uint< 256 >::WIDTH, base_uint< 256 >::pn, base_uint< BITS >::pn.
Referenced by CCoinsKeyHasher::operator(), CBlock::AddToBlockIndex, CBudgetManager::SubmitFinalBudget.