leveldb::Harness
Options leveldb::Harness::options_
Constructor* leveldb::Harness::constructor_
leveldb::Harness::Harness()
void leveldb::Harness::Init(const TestArgs &args)
References leveldb::Options::block_restart_interval, leveldb::TestArgs::restart_interval, leveldb::Options::block_size, leveldb::TestArgs::reverse_compare, leveldb::Options::comparator, leveldb::TestArgs::type, leveldb::TABLE_TEST, leveldb::BLOCK_TEST, leveldb::MEMTABLE_TEST, leveldb::DB_TEST.
leveldb::Harness::~Harness()
void leveldb::Harness::Add(const std::string &key, const std::string &value)
References leveldb::Constructor::Add.
void leveldb::Harness::Test(Random *rnd)
References leveldb::Constructor::Finish, TestForwardScan, TestBackwardScan, TestRandomAccess.
void leveldb::Harness::TestForwardScan(const std::vector< std::string > &keys, const KVMap &data)
References leveldb::Constructor::NewIterator, ASSERT_TRUE, leveldb::Iterator::Valid, leveldb::Iterator::SeekToFirst, ASSERT_EQ, ToString, leveldb::Iterator::Next.
Referenced by Test.
void leveldb::Harness::TestBackwardScan(const std::vector< std::string > &keys, const KVMap &data)
References leveldb::Constructor::NewIterator, ASSERT_TRUE, leveldb::Iterator::Valid, leveldb::Iterator::SeekToLast, ASSERT_EQ, ToString, leveldb::Iterator::Prev.
Referenced by Test.
void leveldb::Harness::TestRandomAccess(Random *rnd, const std::vector< std::string > &keys, const KVMap &data)
References leveldb::Constructor::NewIterator, ASSERT_TRUE, leveldb::Iterator::Valid, leveldb::Random::Uniform, leveldb::Iterator::Next, ASSERT_EQ, ToString, leveldb::Iterator::SeekToFirst, PickRandomKey, leveldb::EscapeString, leveldb::Iterator::Seek, leveldb::Iterator::Prev, leveldb::Iterator::SeekToLast.
Referenced by Test.
std::string leveldb::Harness::ToString(const KVMap &data, const KVMap::const_iterator &it)
Referenced by TestForwardScan, TestBackwardScan, TestRandomAccess.
std::string leveldb::Harness::ToString(const KVMap &data, const KVMap::const_reverse_iterator &it)
std::string leveldb::Harness::ToString(const Iterator *it)
References leveldb::Iterator::Valid, leveldb::Iterator::key, leveldb::Slice::ToString, leveldb::Iterator::value.
std::string leveldb::Harness::PickRandomKey(Random *rnd, const std::vector< std::string > &keys)
References leveldb::Random::Uniform, leveldb::Options::comparator.
Referenced by TestRandomAccess.
DB* leveldb::Harness::db() const
References leveldb::Constructor::db.