CWalletTx
const CWallet* CWalletTx::pwallet
std::vector<CMerkleTx> CWalletTx::vtxPrev
mapValue_t CWalletTx::mapValue
Referenced by TransactionDesc::toHTML, TransactionRecord::decomposeTransaction, WalletModel::sendCoins, WalletTxToJSON, sendtoaddress, sendfrom, sendmany, ListTransactions, sendtostealthaddress, BOOST_AUTO_TEST_CASE, CWallet::AddToWalletIfInvolvingMe, CWallet::CreateStealthTransaction, CWallet::CommitTransaction, SerializationOp.
std::vector<std::pair<std::string, std::string> > CWalletTx::vOrderForm
unsigned int CWalletTx::fTimeReceivedIsTxTime
unsigned int CWalletTx::nTimeReceived
Referenced by TransactionRecord::updateStatus, WalletTxToJSON, CWallet::AddToWallet, CWallet::ResendWalletTransactions, CWalletDB::ReorderTransactions.
unsigned int CWalletTx::nTimeSmart
Referenced by CWallet::AddToWallet, SerializationOp.
char CWalletTx::fFromMe
Referenced by CWallet::AddToWallet.
std::string CWalletTx::strFromAccount
Referenced by sendfrom, sendmany, SerializationOp.
std::vector<char> CWalletTx::vfSpent
Referenced by CWallet::AddToWallet, SerializationOp.
int64_t CWalletTx::nOrderPos
Referenced by CWallet::OrderedTxItems, CWallet::AddToWallet, SerializationOp, CWalletDB::ReorderTransactions.
bool CWalletTx::fDebitCached
bool CWalletTx::fCreditCached
bool CWalletTx::fImmatureCreditCached
bool CWalletTx::fDenomUnconfCreditCached
bool CWalletTx::fDenomConfCreditCached
bool CWalletTx::fAnonymizedCreditCached
bool CWalletTx::fAnonymizableCreditCached
bool CWalletTx::fAvailableWatchCreditCached
bool CWalletTx::fImmatureWatchCreditCached
bool CWalletTx::fAvailableCreditCached
bool CWalletTx::fChangeCached
bool CWalletTx::fWatchDebitCached
bool CWalletTx::fWatchCreditCached
CAmount CWalletTx::nWatchDebitCached
Referenced by GetDebit.
CAmount CWalletTx::nWatchCreditCached
Referenced by GetCredit.
CAmount CWalletTx::nImmatureCreditCached
Referenced by GetImmatureCredit.
CAmount CWalletTx::nDebitCached
Referenced by GetDebit.
CAmount CWalletTx::nCreditCached
Referenced by GetCredit.
CAmount CWalletTx::nAvailableCreditCached
Referenced by GetAvailableCredit.
CAmount CWalletTx::nChangeCached
Referenced by GetChange.
CAmount CWalletTx::nImmatureWatchCreditCached
Referenced by GetImmatureWatchOnlyCredit.
CAmount CWalletTx::nAvailableWatchCreditCached
Referenced by GetAvailableWatchOnlyCredit.
CAmount CWalletTx::nAnonymizableCreditCached
Referenced by GetAnonymizableCredit.
CAmount CWalletTx::nAnonymizedCreditCached
CAmount CWalletTx::nDenomUnconfCreditCached
Referenced by GetDenominatedCredit.
CAmount CWalletTx::nDenomConfCreditCached
Referenced by GetDenominatedCredit.
CWalletTx::ADD_SERIALIZE_METHODS
CWalletTx::CWalletTx()
References CMerkleTx::Init.
CWalletTx::CWalletTx(const CWallet *pwalletIn)
References CMerkleTx::Init.
CWalletTx::CWalletTx(const CWallet *pwalletIn, const CMerkleTx &txIn)
References CMerkleTx::Init.
CWalletTx::CWalletTx(const CWallet *pwalletIn, const CTransaction &txIn)
References CMerkleTx::Init.
void CWalletTx::Init(const CWallet *pwalletIn)
Referenced by SerializationOp.
void CWalletTx::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References Init, mapValue, strFromAccount, nOrderPos, strprintf, READWRITE, vfSpent, CTransaction::vout, nTimeSmart, atoi64.
bool CWalletTx::UpdateSpent(const std::vector< char > &vfNewSpent)
Referenced by CWallet::AddToWallet.
void CWalletTx::MarkDirty()
Referenced by CWallet::MarkDirty, CWallet::AddToWallet, CWallet::ReacceptWalletTransactions, BindWallet.
void CWalletTx::BindWallet(CWallet *pwalletIn)
References MarkDirty.
Referenced by CWallet::AddToWallet, CWallet::CommitTransaction.
void CWalletTx::MarkSpent(unsigned int nOut)
References CTransaction::vout.
Referenced by CWallet::ReacceptWalletTransactions, CWallet::CommitTransaction, CWallet::FixSpentCoins.
void CWalletTx::MarkUnspent(unsigned int nOut)
References CTransaction::vout.
Referenced by CWallet::FixSpentCoins, CWallet::DisableTransaction.
bool CWalletTx::IsSpent(unsigned int nOut) const
References CTransaction::vout.
Referenced by CWallet::ReacceptWalletTransactions, CWallet::GetAnonymizedBalance, CWallet::GetAverageAnonymizedRounds, CWallet::GetNormalizedAnonymizedBalance, CWallet::AvailableCoins, CWallet::AvailableCoinsForStaking, CWallet::CountInputsWithAmount, CWallet::GetAddressBalances, CWallet::FixSpentCoins, GetAvailableCredit.
int64_t CWalletTx::IsDenominated() const
References CTransaction::vin, CWallet::IsDenominated.
CAmount CWalletTx::GetCredit(const isminefilter &filter) const
References CTransaction::IsCoinBase, CTransaction::IsCoinStake, CMerkleTx::GetBlocksToMaturity, ISMINE_SPENDABLE, nCreditCached, CWallet::GetCredit, ISMINE_WATCH_ONLY, nWatchCreditCached.
Referenced by TransactionDesc::toHTML, TransactionRecord::decomposeTransaction, gettransaction, CWallet::ReacceptWalletTransactions.
CAmount CWalletTx::GetDebit(const isminefilter &filter) const
References CTransaction::vin, ISMINE_SPENDABLE, nDebitCached, CWallet::GetDebit, ISMINE_WATCH_ONLY, nWatchDebitCached.
Referenced by TransactionDesc::toHTML, TransactionRecord::decomposeTransaction, gettransaction, IsFromMe.
CAmount CWalletTx::GetImmatureCredit(bool fUseCache=true) const
References CTransaction::IsCoinBase, CMerkleTx::GetBlocksToMaturity, CMerkleTx::IsInMainChain, nImmatureCreditCached, CWallet::GetCredit, ISMINE_SPENDABLE.
Referenced by CWallet::GetImmatureBalance.
CAmount CWalletTx::GetAvailableCredit(bool fUseCache=true) const
References CTransaction::IsCoinBase, CTransaction::IsCoinStake, CMerkleTx::GetBlocksToMaturity, nAvailableCreditCached, CTransaction::vout, IsSpent, CWallet::GetCredit, ISMINE_SPENDABLE, MoneyRange.
Referenced by CWallet::GetBalance, CWallet::GetUnconfirmedBalance.
CAmount CWalletTx::GetAnonymizableCredit(bool fUseCache=false) const
References CTransaction::IsCoinBase, CTransaction::IsCoinStake, CMerkleTx::GetBlocksToMaturity, nAnonymizableCreditCached, CTransaction::GetHash, CTransaction::vout, CTransaction::vin, CWallet::IsSpent, CWallet::IsLockedCoin, fStormNode, sandStormDenominations, CWallet::GetInputSandstormRounds, nSandstormRounds, CWallet::GetCredit, ISMINE_SPENDABLE, MoneyRange.
CAmount CWalletTx::GetDenominatedCredit(bool unconfirmed, bool fUseCache=false) const
References CTransaction::IsCoinBase, CTransaction::IsCoinStake, CMerkleTx::GetBlocksToMaturity, CMerkleTx::GetDepthInMainChain, IsFinalTx, IsTrusted, nDenomUnconfCreditCached, nDenomConfCreditCached, CTransaction::GetHash, CTransaction::vout, CWallet::IsSpent, CWallet::IsDenominatedAmount, CWallet::GetCredit, ISMINE_SPENDABLE, MoneyRange.
CAmount CWalletTx::GetImmatureWatchOnlyCredit(const bool &fUseCache=true) const
References CTransaction::IsCoinBase, CTransaction::IsCoinStake, CMerkleTx::GetBlocksToMaturity, CMerkleTx::IsInMainChain, nImmatureWatchCreditCached, CWallet::GetCredit, ISMINE_WATCH_ONLY.
Referenced by CWallet::GetImmatureWatchOnlyBalance.
CAmount CWalletTx::GetAvailableWatchOnlyCredit(const bool &fUseCache=true) const
References CTransaction::IsCoinBase, CTransaction::IsCoinStake, CMerkleTx::GetBlocksToMaturity, nAvailableWatchCreditCached, CTransaction::vout, CWallet::IsSpent, CTransaction::GetHash, CWallet::GetCredit, ISMINE_WATCH_ONLY, MoneyRange.
Referenced by CWallet::GetWatchOnlyBalance, CWallet::GetUnconfirmedWatchOnlyBalance.
CAmount CWalletTx::GetChange() const
References nChangeCached, CWallet::GetChange.
Referenced by TransactionDesc::toHTML, TransactionRecord::decomposeTransaction.
void CWalletTx::GetAmounts(std::list< std::pair< CTxDestination, CAmount > > &listReceived, std::list< std::pair< CTxDestination, CAmount > > &listSent, CAmount &nFee, std::string &strSentAccount, const isminefilter &filter) const
References ExtractDestination, CTxOut::scriptPubKey, LogPrintf, CTxOut::nValue.
Referenced by getbalance, ListTransactions, listaccounts.
void CWalletTx::GetAccountAmounts(const std::string &strAccount, CAmount &nReceived, CAmount &nSent, CAmount &nFee, const isminefilter &filter) const
References PAIRTYPE, LOCK.
Referenced by GetAccountBalance.
bool CWalletTx::IsFromMe(const isminefilter &filter) const
References GetDebit.
Referenced by ListTransactions, gettransaction, CWallet::SelectCoinsMinConfByCoinAge, CWallet::SelectCoinsMinConf, CWallet::GetAddressBalances, IsTrusted.
bool CWalletTx::IsTrusted() const
References IsFinalTx, CMerkleTx::GetDepthInMainChain, fConfChange, IsFromMe, ISMINE_ALL, CTransaction::vin, CWallet::GetWalletTx, CTxIn::prevout, COutPoint::hash, CTransaction::vout, COutPoint::n, CWallet::IsMine, ISMINE_SPENDABLE.
Referenced by TransactionRecord::updateStatus, CWallet::GetBalance, CWallet::GetAnonymizableBalance, CWallet::GetAnonymizedBalance, CWallet::GetAverageAnonymizedRounds, CWallet::GetNormalizedAnonymizedBalance, CWallet::GetDenominatedBalance, CWallet::GetUnconfirmedBalance, CWallet::GetWatchOnlyBalance, CWallet::GetUnconfirmedWatchOnlyBalance, CWallet::AvailableCoins, CWallet::CountInputsWithAmount, CWallet::GetAddressBalances, GetDenominatedCredit.
bool CWalletTx::WriteToDisk()
References CWalletDB::WriteTx.
Referenced by CWallet::AddToWallet, CWallet::ReacceptWalletTransactions, CWallet::CommitTransaction, CWallet::FixSpentCoins, CWallet::DisableTransaction.
int64_t CWalletTx::GetTxTime() const
Referenced by TransactionDesc::toHTML, TransactionRecord::decomposeTransaction, WalletTxToJSON.
int CWalletTx::GetRequestCount() const
References LOCK.
Referenced by TransactionDesc::toHTML, TransactionRecord::updateStatus.
void CWalletTx::AddSupportingTransactions(CTxDB &txdb)
References CTxIn::prevout, COutPoint::hash, LOCK, CTransaction::GetHash, hash, CTxDB::ReadDiskTx, LogPrintf, CMerkleTx::SetMerkleBranch, CTransaction::vin.
bool CWalletTx::AcceptWalletTransaction(CTxDB &txdb)
References CTransaction::IsCoinBase, CTransaction::IsCoinStake, CTransaction::GetHash, mempool, CTxMemPool::exists, CTxDB::ContainsTx, CMerkleTx::AcceptToMemoryPool, AcceptToMemoryPool.
Referenced by CWallet::ReacceptWalletTransactions.
bool CWalletTx::AcceptWalletTransaction()
References txdb.
void CWalletTx::RelayWalletTransaction(CTxDB &txdb, std::string strCommand="tx")
References LogPrintf, base_uint< BITS >::ToString, mapTxLockReq, CreateNewLock, RelayTransactionLockReq, RelayTransaction.
Referenced by CSandstormPool::ChargeFees, CSandstormPool::ChargeRandomFees, CWallet::ResendWalletTransactions, CWallet::CommitTransaction.
void CWalletTx::RelayWalletTransaction(std::string strCommand="tx")
References txdb.
set< uint256 > CWalletTx::GetConflicts() const
Referenced by WalletTxToJSON.