leveldb::InternalKey
std::string leveldb::InternalKey::rep_
leveldb::InternalKey::InternalKey()
leveldb::InternalKey::InternalKey(const Slice &user_key, SequenceNumber s, ValueType t)
References leveldb::AppendInternalKey.
void leveldb::InternalKey::DecodeFrom(const Slice &s)
References leveldb::Slice::data, leveldb::Slice::size.
Referenced by leveldb::BuildTable.
Slice leveldb::InternalKey::Encode() const
Referenced by leveldb::DBTest::AllEntriesFor, leveldb::InternalKeyComparator::Compare, leveldb::VersionEdit::EncodeTo, leveldb::FindFile, leveldb::SomeFileOverlapsRange, leveldb::VersionSet::ApproximateOffsetOf, leveldb::VersionSet::PickCompaction, leveldb::Compaction::ShouldStopBefore, leveldb::FindFileTest::Find.
Slice leveldb::InternalKey::user_key() const
References leveldb::ExtractUserKey.
Referenced by leveldb::Version::Get, leveldb::Version::GetOverlappingInputs, leveldb::Compaction::IsBaseLevelForKey.
void leveldb::InternalKey::SetFrom(const ParsedInternalKey &p)
References leveldb::AppendInternalKey.
void leveldb::InternalKey::Clear()
std::string leveldb::InternalKey::DebugString() const
References leveldb::ParseInternalKey, leveldb::ParsedInternalKey::DebugString, leveldb::EscapeString.
Referenced by leveldb::VersionEdit::DebugString, leveldb::VersionSet::Builder::SaveTo.