CSporkManager
std::vector<unsigned char> CSporkManager::vchSig
std::string CSporkManager::strMasterPrivKey
std::string CSporkManager::strMainPubKey
CSporkManager::CSporkManager()
std::string CSporkManager::GetSporkNameByID(int id)
Referenced by spork.
int CSporkManager::GetSporkIDByName(std::string strName)
Referenced by spork.
bool CSporkManager::UpdateSpork(int nSporkID, int64_t nValue)
References CSporkMessage::nSporkID, CSporkMessage::nValue, CSporkMessage::nTimeSigned, GetTime, Sign, Relay, mapSporks, CSporkMessage::GetHash, mapSporksActive.
Referenced by spork.
bool CSporkManager::SetPrivKey(std::string strPrivKey)
References Sign, CheckSignature, LogPrintf.
Referenced by AppInit2.
bool CSporkManager::CheckSignature(CSporkMessage &spork)
References CSporkMessage::nSporkID, CSporkMessage::nValue, CSporkMessage::nTimeSigned, ParseHex, sandStormSigner, CSandStormSigner::VerifyMessage, CSporkMessage::vchSig.
Referenced by ProcessSpork, SetPrivKey.
bool CSporkManager::Sign(CSporkMessage &spork)
References CSporkMessage::nSporkID, CSporkMessage::nValue, CSporkMessage::nTimeSigned, sandStormSigner, CSandStormSigner::SetKey, LogPrintf, CSandStormSigner::SignMessage, CSporkMessage::vchSig, CSandStormSigner::VerifyMessage.
Referenced by UpdateSpork, SetPrivKey.
void CSporkManager::Relay(CSporkMessage &msg)
References MSG_SPORK, CSporkMessage::GetHash, LOCK, cs_vNodes, vNodes, CNode::PushMessage.
Referenced by ProcessSpork, UpdateSpork.