CScript
CScript& CScript::push_int64(int64_t n)
References OP_1, CBigNum::getvch.
Referenced by operator<<.
CScript& CScript::push_uint64(uint64_t n)
References OP_1, CBigNum::getvch.
Referenced by operator<<.
CScript::CScript()
CScript::CScript(const CScript &b)
CScript::CScript(const_iterator pbegin, const_iterator pend)
CScript::CScript(const unsigned char *pbegin, const unsigned char *pend)
CScript& CScript::operator+=(const CScript &b)
CScript::CScript(signed char b)
References operator<<.
CScript::CScript(short b)
References operator<<.
CScript::CScript(int b)
References operator<<.
CScript::CScript(long b)
References operator<<.
CScript::CScript(long long b)
References operator<<.
CScript::CScript(unsigned char b)
References operator<<.
CScript::CScript(unsigned int b)
References operator<<.
CScript::CScript(unsigned short b)
References operator<<.
CScript::CScript(unsigned long b)
References operator<<.
CScript::CScript(unsigned long long b)
References operator<<.
CScript::CScript(opcodetype b)
References operator<<.
CScript::CScript(const uint256 &b)
References operator<<.
CScript::CScript(const CBigNum &b)
References operator<<.
CScript::CScript(const std::vector< unsigned char > &b)
References operator<<.
CScript& CScript::operator<<(signed char b)
References push_int64.
Referenced by CScript.
CScript& CScript::operator<<(short b)
References push_int64.
CScript& CScript::operator<<(int b)
References push_int64.
CScript& CScript::operator<<(long b)
References push_int64.
CScript& CScript::operator<<(long long b)
References push_int64.
CScript& CScript::operator<<(unsigned char b)
References push_uint64.
CScript& CScript::operator<<(unsigned int b)
References push_uint64.
CScript& CScript::operator<<(unsigned short b)
References push_uint64.
CScript& CScript::operator<<(unsigned long b)
References push_uint64.
CScript& CScript::operator<<(unsigned long long b)
References push_uint64.
CScript& CScript::operator<<(opcodetype opcode)
CScript& CScript::operator<<(const uint160 &b)
CScript& CScript::operator<<(const uint256 &b)
CScript& CScript::operator<<(const CPubKey &key)
References CPubKey::size, OP_PUSHDATA1, CPubKey::begin, CPubKey::end.
CScript& CScript::operator<<(const CBigNum &b)
References CBigNum::getvch.
CScript& CScript::operator<<(const std::vector< unsigned char > &b)
References OP_PUSHDATA1, OP_PUSHDATA2, OP_PUSHDATA4.
CScript& CScript::operator<<(const CScript &b)
bool CScript::GetOp(iterator &pc, opcodetype &opcodeRet, std::vector< unsigned char > &vchRet)
References GetOp2.
Referenced by CBlock::CheckBlockSignature, EvalScript, Solver, GetSigOpCount, FindAndDelete, Find, IsPushOnly, ToString, CWallet::FindStealthTransactions.
bool CScript::GetOp(iterator &pc, opcodetype &opcodeRet)
References GetOp2.
bool CScript::GetOp(const_iterator &pc, opcodetype &opcodeRet, std::vector< unsigned char > &vchRet) const
References GetOp2.
bool CScript::GetOp(const_iterator &pc, opcodetype &opcodeRet) const
References GetOp2.
bool CScript::GetOp2(const_iterator &pc, opcodetype &opcodeRet, std::vector< unsigned char > *pvchRet) const
References OP_INVALIDOPCODE, OP_PUSHDATA4, OP_PUSHDATA1, OP_PUSHDATA2.
Referenced by GetOp.
int CScript::FindAndDelete(const CScript &b)
References GetOp.
Referenced by EvalScript, SignatureHash.
int CScript::Find(opcodetype op) const
References GetOp.
unsigned int CScript::GetSigOpCount(bool fAccurate) const
References OP_INVALIDOPCODE, OP_CHECKSIG, OP_CHECKSIGVERIFY, OP_CHECKMULTISIG, OP_CHECKMULTISIGVERIFY, OP_1, OP_16.
Referenced by GetLegacySigOpCount, GetP2SHSigOpCount, GetSigOpCount, BOOST_AUTO_TEST_CASE.
unsigned int CScript::GetSigOpCount(const CScript &scriptSig) const
References GetOp, OP_16, GetSigOpCount.
bool CScript::IsNormalPaymentScript() const
References OP_DUP, OP_HASH160, OP_EQUALVERIFY, OP_CHECKSIG.
Referenced by ProcessMessageInstantX, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::IsCollateralValid, IsBudgetCollateralValid.
bool CScript::IsPayToScriptHash() const
References OP_HASH160, OP_EQUAL.
Referenced by GetP2SHSigOpCount, Solver, VerifyScript, CBudgetProposal::IsValid.
bool CScript::IsPushOnly() const
References GetOp, OP_16.
Referenced by IsStandardTx, VerifyScript.
bool CScript::IsUnspendable() const
Returns whether the script is guaranteed to fail at execution, regardless of the initial stack. This allows outputs to be pruned instantly when entering the UTXO set.
References OP_RETURN.
Referenced by CCoins::ClearUnspendable, ProcessMessageInstantX, IsBudgetCollateralValid.
bool CScript::HasCanonicalPushes() const
References OP_16, OP_PUSHDATA1, OP_PUSHDATA2, OP_PUSHDATA4.
Referenced by IsStandardTx.
void CScript::SetDestination(const CTxDestination &address)
Referenced by WalletModel::sendCoins, createrawtransaction, GetAccountAddress, getreceivedbyaddress, sendmany, IsMine, BOOST_AUTO_TEST_CASE, CWallet::SendStealthMoneyToDestination, CWallet::SendMoneyToDestination.
void CScript::SetMultisig(int nRequired, const std::vector< CPubKey > &keys)
References OP_CHECKMULTISIG.
Referenced by _createmultisig, addmultisigaddress, BOOST_AUTO_TEST_CASE.
std::string CScript::ToString(bool fShort=false) const
References GetOp, OP_PUSHDATA4, ValueString, GetOpName.
Referenced by CTxIn::ToString, CTxOut::ToString, ScriptPubKeyToJSON, TxToJSON, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::SignatureValid, CSandstormPool::AddScriptSig, CStormnodePaymentWinner::Sign, CStormnodePaymentWinner::SignatureValid, CStormnodePaymentWinner::ToString.
CScriptID CScript::GetID() const
References Hash160.
Referenced by CBasicKeyStore::AddCScript, decodescript, createmultisig, addmultisigaddress, BOOST_AUTO_TEST_CASE, CWallet::LoadCScript.
void CScript::clear()
Referenced by CTxOut::SetNull, CTxOut::SetEmpty, signrawtransaction, Solver, CScriptVisitor::operator(), CWallet::CreateCoinStake.
CScript operator+(const CScript &a, const CScript &b)
static int CScript::DecodeOP_N(opcodetype opcode)
References OP_0, OP_1, OP_16.
Referenced by Solver.
static opcodetype CScript::EncodeOP_N(int n)
References OP_0, OP_1.
Referenced by GetScriptForMultisig.