CTxMemPool
unsigned int CTxMemPool::nTransactionsUpdated
CFeeRate CTxMemPool::minRelayFee
CCriticalSection CTxMemPool::cs
Passed to constructor to avoid dependency on main.
Referenced by AcceptToMemoryPool, AcceptableInputs, CreateNewBlock, GetTransactionsUpdated, AddTransactionsUpdated, addUnchecked, remove, removeConflicts, clear, queryHashes, lookup, WriteFeeEstimates, ReadFeeEstimates, CWallet::ReacceptWalletTransactions.
std::map<uint256, CTransaction> CTxMemPool::mapTx
Referenced by AcceptToMemoryPool, CreateNewBlock, addUnchecked, remove, clear, queryHashes, lookup.
std::map<COutPoint, CInPoint> CTxMemPool::mapNextTx
Referenced by AcceptToMemoryPool, AcceptableInputs, addUnchecked, remove, removeConflicts, clear.
CMinerPolicyEstimator* CTxMemPool::minerPolicyEstimator
Referenced by CTxMemPool, ~CTxMemPool, WriteFeeEstimates, ReadFeeEstimates.
bool CTxMemPool::fSanityCheck
Referenced by CTxMemPool.
CTxMemPool::CTxMemPool(const CFeeRate &_minRelayFee)
References fSanityCheck, minerPolicyEstimator.
CTxMemPool::~CTxMemPool()
References minerPolicyEstimator.
bool CTxMemPool::addUnchecked(const uint256 &hash, CTransaction &tx)
References LOCK, cs, mapTx, hash, CTransaction::vin, mapNextTx.
Referenced by AcceptToMemoryPool.
bool CTxMemPool::remove(const CTransaction &tx, bool fRecursive=false)
References LOCK, cs, hash, CTransaction::GetHash, mapTx, CTransaction::vout, mapNextTx, CTransaction::vin, CTxIn::prevout.
Referenced by Reorganize.
bool CTxMemPool::removeConflicts(const CTransaction &tx)
References LOCK, cs, CTransaction::vin, mapNextTx, CTxIn::prevout.
Referenced by Reorganize.
void CTxMemPool::clear()
References LOCK, cs, mapTx, mapNextTx.
void CTxMemPool::queryHashes(std::vector< uint256 > &vtxid)
References LOCK, cs, mapTx.
Referenced by getrawmempool.
unsigned int CTxMemPool::GetTransactionsUpdated() const
References LOCK, cs.
Referenced by getworkex, getwork, getblocktemplate.
void CTxMemPool::AddTransactionsUpdated(unsigned int n)
References LOCK, cs.
Referenced by Shutdown, StopNode.
bool CTxMemPool::ReadFeeEstimates(CAutoFile &filein)
References LOCK, cs, minerPolicyEstimator, CMinerPolicyEstimator::Read, LogPrintf.
Referenced by AppInit2.
bool CTxMemPool::WriteFeeEstimates(CAutoFile &fileout) const
References LOCK, cs, minerPolicyEstimator, CMinerPolicyEstimator::Write, LogPrintf.
Referenced by Shutdown.
unsigned long CTxMemPool::size() const
References LOCK.
Referenced by getmininginfo, getstakinginfo.
bool CTxMemPool::exists(uint256 hash) const
References LOCK.
Referenced by CCoinsViewMemPool::HaveCoins, AcceptToMemoryPool, AcceptableInputs, CMerkleTx::GetDepthInMainChain, CWalletTx::AcceptWalletTransaction.
bool CTxMemPool::lookup(uint256 hash, CTransaction &result) const
References LOCK, cs, mapTx.
Referenced by CCoinsViewMemPool::GetCoins, GetTransaction.