leveldb::WriteBatch
friend class WriteBatchInternal
std::string leveldb::WriteBatch::rep_
leveldb::WriteBatch::WriteBatch()
References Clear.
leveldb::WriteBatch::~WriteBatch()
void leveldb::WriteBatch::Put(const Slice &key, const Slice &value)
References leveldb::WriteBatchInternal::SetCount, leveldb::WriteBatchInternal::Count, leveldb::kTypeValue, leveldb::PutLengthPrefixedSlice.
Referenced by leveldb_writebatch_put, leveldb::CorruptionTest::Build, leveldb::TEST, leveldb::DB::Put, leveldb::DBConstructor::FinishImpl, CLevelDBBatch::Write, SecMsgDB::WritePK, SecMsgDB::WriteSmesg, CTxDB::Write.
void leveldb::WriteBatch::Delete(const Slice &key)
References leveldb::WriteBatchInternal::SetCount, leveldb::WriteBatchInternal::Count, leveldb::kTypeDeletion, leveldb::PutLengthPrefixedSlice.
Referenced by leveldb_writebatch_delete, leveldb::DB::Delete, leveldb::TEST, CLevelDBBatch::Erase, SecMsgDB::EraseSmesg, CTxDB::Erase.
void leveldb::WriteBatch::Clear()
Referenced by leveldb_writebatch_clear, leveldb::CorruptionTest::Build, leveldb::DBImpl::Write, WriteBatch, leveldb::TEST.
Status leveldb::WriteBatch::Iterate(Handler *handler) const
References leveldb::Slice::size, leveldb::Status::Corruption, leveldb::Slice::remove_prefix, value, leveldb::Slice::empty, leveldb::kTypeValue, leveldb::GetLengthPrefixedSlice, leveldb::WriteBatch::Handler::Put, leveldb::kTypeDeletion, leveldb::WriteBatch::Handler::Delete, leveldb::WriteBatchInternal::Count, leveldb::Status::OK.
Referenced by leveldb_writebatch_iterate, leveldb::ModelDB::Write, leveldb::WriteBatchInternal::InsertInto, SecMsgDB::ScanBatch.