CBlockHeader
const int32_t CBlockHeader::CURRENT_VERSION
Referenced by CBlock::AcceptBlock, CBlockHeader, CBlock::SetNull, CBlock::SetBestChain.
int32_t CBlockHeader::nVersion
Referenced by CBlock::AcceptBlock, CBlockIndex::CBlockIndex, CBlockIndex::GetBlockHeader, CDiskBlockIndex::GetBlockHash, SerializationOp, CBlock::SetNull, FormatHashBuffers, CBlock::ToString, blockToJSON, getblocktemplate.
uint256 CBlockHeader::hashPrevBlock
Referenced by CBlock::AcceptBlock, CBlockIndex::GetBlockHeader, CDiskBlockIndex::GetBlockHash, CBlock::SetNull, ProcessBlock, IncrementExtraNonce, FormatHashBuffers, CheckWork, CheckStake, CBlock::ToString, getblocktemplate, IsBlockValueValid.
uint256 CBlockHeader::hashMerkleRoot
Referenced by CBlock::CheckBlock, CBlockIndex::CBlockIndex, CBlockIndex::GetBlockHeader, CDiskBlockIndex::GetBlockHash, CBlock::SetNull, IncrementExtraNonce, FormatHashBuffers, CBlock::ToString, blockToJSON, getworkex, getwork.
uint32_t CBlockHeader::nTime
Referenced by CBlock::AcceptBlock, CBlockIndex::CBlockIndex, CBlockIndex::GetBlockHeader, CDiskBlockIndex::GetBlockHash, GetBlockTime, CBlock::SetNull, CBlock::GetProofOfStake, FormatHashBuffers, CBlock::UpdateTime, CBlock::ToString, getworkex, getwork, getblocktemplate.
uint32_t CBlockHeader::nBits
Referenced by CBlock::AcceptBlock, CBlock::CheckBlock, CBlock::ReadFromDisk, CBlockIndex::CBlockIndex, CBlockIndex::GetBlockHeader, CDiskBlockIndex::GetBlockHash, CBlock::SetNull, PrintBlockTree, FormatHashBuffers, CheckWork, CheckStake, CBlock::ToString, blockToJSON, getworkex, getwork, getblocktemplate.
uint32_t CBlockHeader::nNonce
Referenced by CBlockIndex::CBlockIndex, CBlockIndex::GetBlockHeader, CDiskBlockIndex::GetBlockHash, CBlock::SetNull, FormatHashBuffers, CBlock::ToString, blockToJSON, getworkex, getwork, getblocktemplate.
int CBlockHeader::nDoS
Referenced by CBlock::SetNull.
CBlockHeader::ADD_SERIALIZE_METHODS
bool CBlockHeader::DoS(int nDoSIn, bool fIn) const
Referenced by CBlock::AcceptBlock, CBlock::ConnectBlock, CBlock::CheckBlock.
CBlockHeader::CBlockHeader()
References CURRENT_VERSION.
void CBlockHeader::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE, nVersion.
bool CBlockHeader::IsNull() const
uint256 CBlockHeader::GetHash() const
References Hash, BEGIN, END, GetPoWHash.
Referenced by CBlock::AcceptBlock, CBlock::ReadFromDisk, CDiskBlockIndex::GetBlockHash, CBlock::GetStakeEntropyBit, CMerkleTx::SetMerkleBranch, CTxIndex::GetDepthInMainChain, GetTransaction, ProcessBlock, PrintBlockTree, CheckWork, CheckStake, CBlock::CheckBlockSignature, CBlock::ToString, blockToJSON.
uint256 CBlockHeader::GetPoWHash() const
References scrypt_blockhash, CVOIDBEGIN.
Referenced by CBlock::AcceptBlock, CBlock::CheckBlock, CBlock::ReadFromDisk, GetHash, CheckWork.
uint256 CBlockHeader::GetPoWArgonHash() const
References hashArgon2d, BEGIN, END.
int64_t CBlockHeader::GetBlockTime() const
References nTime.
Referenced by CBlock::AcceptBlock, CBlock::CheckBlock, CheckProofOfStake, CheckKernel, ProcessBlock, PrintBlockTree, CBlock::UpdateTime, DarkSilkGUI::setNumBlocks, blockToJSON.