CAddrMan
CCriticalSection CAddrMan::cs
std::vector<unsigned char> CAddrMan::nKey
int CAddrMan::nIdCount
std::map<int, CAddrInfo> CAddrMan::mapInfo
std::map<CNetAddr, int> CAddrMan::mapAddr
std::vector<int> CAddrMan::vRandom
int CAddrMan::nTried
std::vector<std::vector<int> > CAddrMan::vvTried
int CAddrMan::nNew
std::vector<std::set<int> > CAddrMan::vvNew
CAddrInfo * CAddrMan::Find(const CNetAddr &addr, int *pnId=NULL)
CAddrInfo * CAddrMan::Create(const CAddress &addr, const CNetAddr &addrSource, int *pnId=NULL)
void CAddrMan::SwapRandom(unsigned int nRandomPos1, unsigned int nRandomPos2)
int CAddrMan::SelectTried(int nKBucket)
References ADDRMAN_TRIED_ENTRIES_INSPECT_ON_EVICT, GetRandInt.
int CAddrMan::ShrinkNew(int nUBucket)
References GetRandInt.
void CAddrMan::MakeTried(CAddrInfo &info, int nId, int nOrigin)
References CAddrInfo::GetTriedBucket, ADDRMAN_TRIED_BUCKET_SIZE, ADDRMAN_NEW_BUCKET_SIZE.
void CAddrMan::Good_(const CService &addr, int64_t nTime)
References CAddress::nLastTry, CAddress::nTime, GetRandInt, CService::ToString.
Referenced by Good.
bool CAddrMan::Add_(const CAddress &addr, const CNetAddr &source, int64_t nTimePenalty)
References CNetAddr::IsRoutable, GetAdjustedTime, CAddress::nTime, CAddress::nServices, ADDRMAN_NEW_BUCKETS_PER_ADDRESS, GetRandInt, CAddrInfo::GetNewBucket, ADDRMAN_NEW_BUCKET_SIZE.
Referenced by Add.
void CAddrMan::Attempt_(const CService &addr, int64_t nTime)
References CAddress::nLastTry.
Referenced by Attempt.
CAddress CAddrMan::Select_(int nUnkBias)
References GetRandInt.
Referenced by Select.
void CAddrMan::GetAddr_(std::vector< CAddress > &vAddr)
References ADDRMAN_GETADDR_MAX_PCT, ADDRMAN_GETADDR_MAX, GetRandInt.
Referenced by GetAddr.
void CAddrMan::Connected_(const CService &addr, int64_t nTime)
References CAddress::nTime.
Referenced by Connected.
void CAddrMan::Serialize(Stream &s, int nType, int nVersionDummy) const
References LOCK, ADDRMAN_NEW_BUCKET_COUNT.
void CAddrMan::Unserialize(Stream &s, int nType, int nVersionDummy)
References LOCK, ADDRMAN_TRIED_BUCKET_COUNT, ADDRMAN_NEW_BUCKET_COUNT, ADDRMAN_TRIED_BUCKET_SIZE, ADDRMAN_NEW_BUCKETS_PER_ADDRESS.
unsigned int CAddrMan::GetSerializeSize(int nType, int nVersion) const
CAddrMan::CAddrMan()
References GetRandBytes.
int CAddrMan::size()
Referenced by ThreadDNSAddressSeed, DumpAddresses, ThreadOpenConnections.
void CAddrMan::Check()
References LOCK, LogPrintf.
Referenced by Add, Good, Attempt, Select, GetAddr, Connected.
bool CAddrMan::Add(const CAddress &addr, const CNetAddr &source, int64_t nTimePenalty=0)
References LOCK, Check, Add_, CService::ToStringIPPort, CNetAddr::ToString.
Referenced by CActiveStormnode::Register, ThreadDNSAddressSeed, ThreadOpenConnections, CStormnodeMan::ProcessMessage.
bool CAddrMan::Add(const std::vector< CAddress > &vAddr, const CNetAddr &source, int64_t nTimePenalty=0)
References LOCK, Check, Add_, CNetAddr::ToString.
void CAddrMan::Good(const CService &addr, int64_t nTime=GetAdjustedTime())
References LOCK, Check, Good_.
void CAddrMan::Attempt(const CService &addr, int64_t nTime=GetAdjustedTime())
References LOCK, Check, Attempt_.
Referenced by ConnectNode.
CAddress CAddrMan::Select(int nUnkBias=50)
References LOCK, Check, Select_.
Referenced by ThreadOpenConnections.
std::vector<CAddress> CAddrMan::GetAddr()
References Check, LOCK, GetAddr_.
void CAddrMan::Connected(const CService &addr, int64_t nTime=GetAdjustedTime())
References LOCK, Check, Connected_.
Referenced by AddressCurrentlyConnected.