CFeeRate
CAmount CFeeRate::nSatoshisPerK
CFeeRate::ADD_SERIALIZE_METHODS
CFeeRate::CFeeRate()
CFeeRate::CFeeRate(const CAmount &_nSatoshisPerK)
CFeeRate::CFeeRate(const CAmount &nFeePaid, size_t nSize)
CFeeRate::CFeeRate(const CFeeRate &other)
CAmount CFeeRate::GetFee(size_t size) const
Referenced by GetFeePerK, CTxOut::IsDust.
CAmount CFeeRate::GetFeePerK() const
References GetFee.
Referenced by CBlockAverage::AreSane.
std::string CFeeRate::ToString() const
References strprintf.
Referenced by CMinerPolicyEstimator::seenBlock.
void CFeeRate::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE.
bool operator<(const CFeeRate &a, const CFeeRate &b)
bool operator>(const CFeeRate &a, const CFeeRate &b)
bool operator==(const CFeeRate &a, const CFeeRate &b)
bool operator<=(const CFeeRate &a, const CFeeRate &b)
bool operator>=(const CFeeRate &a, const CFeeRate &b)