CRPCTable
std::map<std::string, const CRPCCommand*> CRPCTable::mapCommands
CRPCTable::CRPCTable()
References CRPCCommand::name.
const CRPCCommand * CRPCTable::operator[](std::string name) const
string CRPCTable::help(std::string name) const
Note: This interface may still be subject to change.
References CRPCCommand::reqWallet, pwalletMain, CRPCCommand::actor, strprintf.
Referenced by help.
json_spirit::Value CRPCTable::execute(const std::string &method, const json_spirit::Array &params) const
Execute a method. method Method to execute params Array of arguments (JSON objects) Result of the call. an exception (json_spirit::Value) when an error happens.
References tableRPC, JSONRPCError, RPC_METHOD_NOT_FOUND, CRPCCommand::reqWallet, pwalletMain, GetWarnings, GetBoolArg, CRPCCommand::okSafeMode, RPC_FORBIDDEN_BY_SAFE_MODE, CRPCCommand::threadSafe, CRPCCommand::actor, LOCK, cs_main, LOCK2, CWallet::cs_wallet, RPC_MISC_ERROR.
Referenced by RPCExecutor::request, ServiceConnection.