leveldb::MemTable
typedef SkipList<const char*, KeyComparator> leveldb::MemTable::Table
friend class MemTableIterator
Referenced by NewIterator.
friend class MemTableBackwardIterator
KeyComparator leveldb::MemTable::comparator_
int leveldb::MemTable::refs_
Arena leveldb::MemTable::arena_
Table leveldb::MemTable::table_
leveldb::MemTable::MemTable(const InternalKeyComparator &comparator)
void leveldb::MemTable::Ref()
Referenced by leveldb::DBImpl::DBImpl, leveldb::DBImpl::Get, leveldb::MemTableConstructor::MemTableConstructor, leveldb::MemTableConstructor::FinishImpl, leveldb::TEST.
void leveldb::MemTable::Unref()
Referenced by leveldb::DBImpl::~DBImpl, leveldb::DBImpl::Get, leveldb::MemTableConstructor::~MemTableConstructor, leveldb::MemTableConstructor::FinishImpl, leveldb::TEST.
size_t leveldb::MemTable::ApproximateMemoryUsage()
References leveldb::Arena::MemoryUsage.
Iterator * leveldb::MemTable::NewIterator()
References MemTableIterator.
Referenced by leveldb::MemTableConstructor::NewIterator, leveldb::TEST.
void leveldb::MemTable::Add(SequenceNumber seq, ValueType type, const Slice &key, const Slice &value)
References leveldb::Slice::size, leveldb::VarintLength, leveldb::Arena::Allocate, leveldb::EncodeVarint32, leveldb::Slice::data, leveldb::EncodeFixed64, leveldb::SkipList< Key, Comparator >::Insert.
Referenced by leveldb::MemTableConstructor::FinishImpl.
bool leveldb::MemTable::Get(const LookupKey &key, std::string *value, Status *s)
References leveldb::LookupKey::memtable_key, leveldb::Slice::data, key_length, leveldb::GetVarint32Ptr, leveldb::LookupKey::user_key, leveldb::DecodeFixed64, leveldb::kTypeValue, leveldb::Slice::size, leveldb::kTypeDeletion, leveldb::Status::NotFound.
Referenced by leveldb::DBImpl::Get.
leveldb::MemTable::~MemTable()
leveldb::MemTable::MemTable(const MemTable &)
void leveldb::MemTable::operator=(const MemTable &)