CDiskTxPos
unsigned int CDiskTxPos::nFile
Referenced by CheckProofOfStake, CheckKernel, CMerkleTx::SetMerkleBranch, GetTransaction, IsConfirmedInNPrevBlocks, CTransactionPoS::ReadFromDisk, CTxDB::LoadBlockIndex.
unsigned int CDiskTxPos::nBlockPos
Referenced by CheckProofOfStake, CheckKernel, CMerkleTx::SetMerkleBranch, GetTransaction, IsConfirmedInNPrevBlocks, CTxDB::LoadBlockIndex.
unsigned int CDiskTxPos::nTxPos
Referenced by CTransactionPoS::ReadFromDisk.
CDiskTxPos::ADD_SERIALIZE_METHODS
CDiskTxPos::CDiskTxPos()
References SetNull.
CDiskTxPos::CDiskTxPos(unsigned int nFileIn, unsigned int nBlockPosIn, unsigned int nTxPosIn)
void CDiskTxPos::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE, FLATDATA.
void CDiskTxPos::SetNull()
Referenced by CDiskTxPos, CTxIndex::SetNull.
bool CDiskTxPos::IsNull() const
Referenced by ToString, CTxIndex::IsNull, CTxDB::LoadBlockIndex.
std::string CDiskTxPos::ToString() const
References IsNull, strprintf.
bool operator==(const CDiskTxPos &a, const CDiskTxPos &b)
bool operator!=(const CDiskTxPos &a, const CDiskTxPos &b)