leveldb::Iterator
typedef void(* leveldb::Iterator::CleanupFunction) (void *arg1, void *arg2))(void *arg1, void *arg2)
Cleanup leveldb::Iterator::cleanup_
leveldb::Iterator::Iterator()
leveldb::Iterator::~Iterator()
References next.
virtual bool leveldb::Iterator::Valid() const =0
Referenced by leveldb::AutoCompactTest::DoReads, leveldb::BuildTable, leveldb_iter_valid, leveldb::CorruptionTest::Check, leveldb::DBTest::Contents, leveldb::DBTest::AllEntriesFor, leveldb::DBTest::IterStatus, leveldb::TEST, leveldb::Table::ApproximateOffsetOf, leveldb::KeyConvertingIterator::Valid, leveldb::Harness::TestForwardScan, leveldb::Harness::TestBackwardScan, leveldb::Harness::TestRandomAccess, leveldb::Harness::ToString, SecMsgDB::NextSmesg, SecMsgDB::NextSmesgKey, CTxDB::LoadBlockIndex.
virtual void leveldb::Iterator::SeekToFirst()=0
Referenced by leveldb::AutoCompactTest::DoReads, leveldb::BuildTable, leveldb_iter_seek_to_first, leveldb::CorruptionTest::Check, leveldb::DBTest::Contents, leveldb::TEST, leveldb::IteratorWrapper::SeekToFirst, leveldb::KeyConvertingIterator::SeekToFirst, leveldb::Harness::TestForwardScan, leveldb::Harness::TestRandomAccess.
virtual void leveldb::Iterator::SeekToLast()=0
Referenced by leveldb_iter_seek_to_last, leveldb::DBTest::Contents, leveldb::TEST, leveldb::IteratorWrapper::SeekToLast, leveldb::KeyConvertingIterator::SeekToLast, leveldb::Harness::TestBackwardScan, leveldb::Harness::TestRandomAccess.
virtual void leveldb::Iterator::Seek(const Slice &target)=0
Referenced by leveldb_iter_seek, leveldb::DBTest::AllEntriesFor, leveldb::TEST, leveldb::IteratorWrapper::Seek, leveldb::Table::ApproximateOffsetOf, leveldb::KeyConvertingIterator::Seek, leveldb::Harness::TestRandomAccess, SecMsgDB::NextSmesg, SecMsgDB::NextSmesgKey, CTxDB::LoadBlockIndex.
virtual void leveldb::Iterator::Next()=0
Referenced by leveldb::AutoCompactTest::DoReads, leveldb::BuildTable, leveldb_iter_next, leveldb::CorruptionTest::Check, leveldb::DBTest::Contents, leveldb::DBTest::AllEntriesFor, leveldb::TEST, leveldb::IteratorWrapper::Next, leveldb::KeyConvertingIterator::Next, leveldb::Harness::TestForwardScan, leveldb::Harness::TestRandomAccess, SecMsgDB::NextSmesg, SecMsgDB::NextSmesgKey, CTxDB::LoadBlockIndex.
virtual void leveldb::Iterator::Prev()=0
Referenced by leveldb_iter_prev, leveldb::DBTest::Contents, leveldb::TEST, leveldb::IteratorWrapper::Prev, leveldb::KeyConvertingIterator::Prev, leveldb::Harness::TestBackwardScan, leveldb::Harness::TestRandomAccess.
virtual Slice leveldb::Iterator::key() const =0
Referenced by leveldb::AutoCompactTest::DoReads, leveldb::BuildTable, leveldb_iter_key, leveldb::CorruptionTest::Check, leveldb::DBTest::AllEntriesFor, leveldb::DBTest::IterStatus, leveldb::TEST, leveldb::KeyConvertingIterator::key, leveldb::Harness::ToString, SecMsgDB::NextSmesg, SecMsgDB::NextSmesgKey, CTxDB::LoadBlockIndex.
virtual Slice leveldb::Iterator::value() const =0
Referenced by leveldb::BuildTable, leveldb_iter_value, leveldb::CorruptionTest::Check, leveldb::DBTest::AllEntriesFor, leveldb::DBTest::IterStatus, leveldb::TEST, leveldb::IteratorWrapper::value, leveldb::Table::ApproximateOffsetOf, leveldb::KeyConvertingIterator::value, leveldb::Harness::ToString, SecMsgDB::NextSmesg, CTxDB::LoadBlockIndex.
virtual Status leveldb::Iterator::status() const =0
Referenced by leveldb::BuildTable, leveldb_iter_get_error, leveldb::DBTest::AllEntriesFor, leveldb::IteratorWrapper::status, leveldb::KeyConvertingIterator::status.
void leveldb::Iterator::RegisterCleanup(CleanupFunction function, void *arg1, void *arg2)
References func.
Referenced by leveldb::TableCache::NewIterator.
leveldb::Iterator::Iterator(const Iterator &)
void leveldb::Iterator::operator=(const Iterator &)