MessageTablePriv
QList<MessageTableEntry> MessageTablePriv::cachedMessageTable
Referenced by MessageModel::rowCount, MessageModel::removeRows.
MessageModel* MessageTablePriv::parent
MessageTablePriv::MessageTablePriv(MessageModel *parent)
void MessageTablePriv::refreshMessageTable()
References MessageModel::getWalletModel, WalletModel::getEncryptionStatus, WalletModel::Locked, LOCK, cs_smsgDB, SecMsgDB::Open, SecMsgDB::pdb, leveldb::DB::NewIterator, SecMsgDB::NextSmesg, SecMsgStored::vchMessage, SMSG_HDR_LEN, SecureMsgDecrypt, SecMsgStored::sAddrTo, WalletModel::getAddressTableModel, AddressTableModel::labelForAddress, MessageData::sFromAddress, MessageData::timestamp, SecMsgStored::timeReceived, MessageTableEntry::Received, MessageData::vchMessage, SecMsgStored::sAddrOutbox, MessageTableEntry::Sent.
Referenced by walletUnlocked, MessageModel::MessageModel.
void MessageTablePriv::newMessage(const SecMsgStored &inboxHdr)
References SecMsgStored::vchMessage, SMSG_HDR_LEN, SecureMsgDecrypt, SecMsgStored::sAddrTo, MessageModel::getWalletModel, WalletModel::getAddressTableModel, AddressTableModel::labelForAddress, MessageData::sFromAddress, MessageData::timestamp, SecMsgStored::timeReceived, SecureMessage::timestamp, MessageTableEntry::Received, MessageData::vchMessage.
Referenced by MessageModel::newMessage.
void MessageTablePriv::newOutboxMessage(const SecMsgStored &outboxHdr)
References SecMsgStored::vchMessage, SMSG_HDR_LEN, SecureMsgDecrypt, SecMsgStored::sAddrOutbox, MessageModel::getWalletModel, WalletModel::getAddressTableModel, AddressTableModel::labelForAddress, SecMsgStored::sAddrTo, MessageData::timestamp, SecMsgStored::timeReceived, SecureMessage::timestamp, MessageTableEntry::Sent, MessageData::sFromAddress, MessageData::vchMessage.
Referenced by MessageModel::newOutboxMessage.
void MessageTablePriv::walletUnlocked()
References refreshMessageTable, MessageModel::proxyModel, MessageModel::resetFilter, MessageModel::Ambiguous.
Referenced by MessageModel::walletUnlocked.
void MessageTablePriv::setEncryptionStatus(int status)
References WalletModel::Locked.
Referenced by MessageModel::setEncryptionStatus.
MessageTableEntry* MessageTablePriv::index(int idx)
Referenced by MessageModel::index, MessageModel::removeRows.
const json_spirit::mValue& MessageTablePriv::find_value(json_spirit::mObject &obj, const char *key)
const std::string MessageTablePriv::get_value(json_spirit::mObject &obj, const char *key)
void MessageTablePriv::handleMessageEntry(const MessageTableEntry &message, const bool append)
void MessageTablePriv::addMessageEntry(const MessageTableEntry &message, const bool &append)