CStormnodePing
CTxIn CStormnodePing::vin
Referenced by CStormnodePing, Sign, CheckAndUpdate, swap.
uint256 CStormnodePing::blockHash
Referenced by CStormnodePing, Sign, CheckAndUpdate, swap.
int64_t CStormnodePing::sigTime
Referenced by stormnode, stormnodelist, CStormnode::Check, CStormnodePing, Sign, CheckAndUpdate, swap, CStormnode::IsPingedWithin.
std::vector<unsigned char> CStormnodePing::vchSig
Referenced by CStormnodePing, Sign, CheckAndUpdate, swap.
CStormnodePing::ADD_SERIALIZE_METHODS
CStormnodePing::CStormnodePing()
References vin, blockHash, sigTime, vchSig.
CStormnodePing::CStormnodePing(CTxIn &newVin)
References vin, sigTime, GetAdjustedTime, vchSig.
void CStormnodePing::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE.
bool CStormnodePing::CheckAndUpdate(int &nDos, bool fRequireEnabled=true)
References sigTime, GetAdjustedTime, LogPrintf, vin, CTxIn::ToString, GetHash, blockHash, base_uint< BITS >::ToString, snodeman, CStormnodeMan::Find, stormnodePayments, CStormnodePayments::GetMinStormnodePaymentsProto, sandStormSigner, CSandStormSigner::VerifyMessage, vchSig, hash, CStormnodeBroadcast::GetHash, CStormnodeMan::mapSeenStormnodeBroadcast, Relay.
Referenced by CStormnode::UpdateFromNewBroadcast.
bool CStormnodePing::Sign(CKey &keyStormnode, CPubKey &pubKeyStormnode)
References sigTime, GetAdjustedTime, vin, CTxIn::ToString, blockHash, base_uint< BITS >::ToString, sandStormSigner, CSandStormSigner::SignMessage, vchSig, LogPrintf, CSandStormSigner::VerifyMessage.
void CStormnodePing::Relay()
References MSG_STORMNODE_PING, GetHash, RelayInv.
Referenced by CheckAndUpdate.
uint256 CStormnodePing::GetHash()
References SER_GETHASH, CHashWriter::GetHash.
Referenced by CStormnode::UpdateFromNewBroadcast, CheckAndUpdate, Relay.
void CStormnodePing::swap(CStormnodePing &first, CStormnodePing &second)
References vin, blockHash, sigTime, vchSig.
CStormnodePing& CStormnodePing::operator=(CStormnodePing from)
bool operator==(const CStormnodePing &a, const CStormnodePing &b)
bool operator!=(const CStormnodePing &a, const CStormnodePing &b)