CBudgetDB
ReadResult
boost::filesystem::path CBudgetDB::pathDB
std::string CBudgetDB::strMagicMessage
CBudgetDB::CBudgetDB()
References GetDataDir.
bool CBudgetDB::Write(const CBudgetManager &objToSave)
References LOCK, CBudgetManager::cs, GetTimeMillis, SER_DISK, FLATDATA, Params, hash, Hash, CDataStream::begin, CDataStream::end, LogPrintf.
Referenced by DumpBudgets.
CBudgetDB::ReadResult CBudgetDB::Read(CBudgetManager &objToLoad, bool fDryRun=false)
References LOCK, CBudgetManager::cs, GetTimeMillis, SER_DISK, FileError, HashReadError, Hash, CDataStream::begin, CDataStream::end, IncorrectHash, IncorrectMagicMessage, FLATDATA, Params, IncorrectMagicNumber, CBudgetManager::Clear, IncorrectFormat, LogPrintf, CBudgetManager::ToString, CBudgetManager::CheckAndRemove, Ok.
Referenced by AppInit2, DumpBudgets.