CNode
uint64_t CNode::nServices
SOCKET CNode::hSocket
Referenced by SocketSendData, ThreadSocketHandler, CNetCleanup::~CNetCleanup.
CDataStream CNode::ssSend
Referenced by ThreadSocketHandler.
size_t CNode::nSendSize
Referenced by ProcessMessages, SocketSendData, ThreadSocketHandler, ThreadMessageHandler.
size_t CNode::nSendOffset
Referenced by SocketSendData.
uint64_t CNode::nSendBytes
Referenced by SocketSendData.
std::deque<CSerializeData> CNode::vSendMsg
Referenced by SocketSendData, ThreadSocketHandler.
CCriticalSection CNode::cs_vSend
Referenced by ThreadSocketHandler, ThreadMessageHandler, ThreadSecureMsg, SecureMsgDisable.
std::deque<CInv> CNode::vRecvGetData
Referenced by ProcessMessages, ThreadMessageHandler.
std::deque<CNetMessage> CNode::vRecvMsg
Referenced by ProcessMessages, ThreadSocketHandler, ThreadMessageHandler.
CCriticalSection CNode::cs_vRecvMsg
Referenced by ThreadSocketHandler, ThreadMessageHandler.
uint64_t CNode::nRecvBytes
Referenced by ThreadSocketHandler.
int CNode::nRecvVersion
int64_t CNode::nLastSend
Referenced by SocketSendData, ThreadSocketHandler.
int64_t CNode::nLastRecv
Referenced by ThreadSocketHandler.
int64_t CNode::nTimeConnected
Referenced by ConnectNode, ThreadSocketHandler.
int64_t CNode::nTimeOffset
CAddress CNode::addr
Referenced by ProcessMessageInstantX, SendMessages, IsPeerAddrLocalGood, FindNode, ThreadSocketHandler, ThreadOpenConnections, ThreadOpenAddedConnections, getaddednodeinfo, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::DoAutomaticDenominating, CSandstormPool::RelayIn, CBudgetManager::ProcessMessage, CStormnodePayments::ProcessMessageStormnodePayments, CStormnodeMan::SsegUpdate, CStormnodeMan::ProcessStormnodeConnections, CStormnodeMan::ProcessMessage.
std::string CNode::addrName
Referenced by Misbehaving, FindNode, SecureMsgReceiveData, SecureMsgSendData.
CService CNode::addrLocal
Referenced by IsPeerAddrLocalGood.
int CNode::nVersion
Referenced by CAlert::RelayTo, ProcessBlock, SendMessages, RelayInv, CSandstormPool::ProcessMessageSandstorm, CBudgetManager::NewBlock, CStormnodePayments::ProcessMessageStormnodePayments, CStormnodeSync::Process.
std::string CNode::strSubVer
Referenced by CAlert::RelayTo.
std::string CNode::cleanSubVer
Referenced by ProcessMessageInstantX.
bool CNode::fOneShot
Referenced by OpenNetworkConnection.
bool CNode::fClient
bool CNode::fInbound
Referenced by ThreadSocketHandler, ThreadOpenConnections, getaddednodeinfo.
bool CNode::fNetworkNode
Referenced by ThreadSocketHandler, OpenNetworkConnection.
bool CNode::fSuccessfullyConnected
bool CNode::fDisconnect
Referenced by ProcessMessages, SendMessages, ThreadSocketHandler, ThreadMessageHandler, CStormnodeMan::ProcessStormnodeConnections.
bool CNode::fRelayTxes
Referenced by RelayTransactionLockReq.
bool CNode::fSandStorm
Referenced by ConnectNode, CStormnodeMan::ProcessStormnodeConnections.
CSemaphoreGrant CNode::grantOutbound
Referenced by ThreadSocketHandler, OpenNetworkConnection.
int CNode::nRefCount
Referenced by GetRefCount.
NodeId CNode::id
Referenced by GetId, ThreadSecureMsg, SecureMsgReceiveData, SecureMsgSendData.
int CNode::nMisbehavior
Referenced by Misbehaving.
uint256 CNode::hashContinue
CBlockIndex* CNode::pindexLastGetBlocksBegin
Referenced by PushGetBlocks.
uint256 CNode::hashLastGetBlocksEnd
Referenced by PushGetBlocks.
int CNode::nStartingHeight
Referenced by CBlock::AcceptBlock.
bool CNode::fStartSync
Referenced by SendMessages.
std::vector<CAddress> CNode::vAddrToSend
Referenced by SendMessages.
mruset<CAddress> CNode::setAddrKnown
Referenced by SendMessages.
bool CNode::fGetAddr
std::set<uint256> CNode::setKnown
Referenced by CAlert::RelayTo.
uint256 CNode::hashCheckpointKnown
mruset<CInv> CNode::setInventoryKnown
Referenced by SendMessages.
std::vector<CInv> CNode::vInventoryToSend
Referenced by SendMessages.
CCriticalSection CNode::cs_inventory
Referenced by SendMessages, ThreadSocketHandler.
std::multimap<int64_t, CInv> CNode::mapAskFor
Referenced by SendMessages.
SecMsgNode CNode::smsgData
Referenced by ThreadSecureMsg, SecureMsgDisable, SecureMsgReceiveData, SecureMsgSendData.
uint64_t CNode::nPingNonceSent
Referenced by SendMessages, ThreadSocketHandler.
int64_t CNode::nPingUsecStart
Referenced by SendMessages, ThreadSocketHandler.
int64_t CNode::nPingUsecTime
bool CNode::fPingQueued
Referenced by SendMessages, ping.
std::map< CNetAddr, int64_t > CNode::setBanned
CCriticalSection CNode::cs_setBanned
std::vector<std::string> CNode::vecRequestsFulfilled
CCriticalSection CNode::cs_totalBytesRecv
CCriticalSection CNode::cs_totalBytesSent
uint64_t CNode::nTotalBytesRecv
uint64_t CNode::nTotalBytesSent
CNode::CNode(SOCKET hSocketIn, CAddress addrIn, std::string addrNameIn="", bool fInboundIn=false)
References CDataStream::SetType, GetTime, CService::ToStringIPPort, mruset< T >::max_size, SendBufferSize, LOCK, INVALID_SOCKET, PushVersion, GetNodeSignals, CNodeSignals::InitializeNode, GetId.
CNode::~CNode()
References INVALID_SOCKET, closesocket, GetNodeSignals, CNodeSignals::FinalizeNode, GetId.
NodeId CNode::GetId() const
References id.
Referenced by Misbehaving, SendMessages, CNode, ~CNode, ProcessSpork, CBudgetManager::ProcessMessage, CStormnodePayments::ProcessMessageStormnodePayments, CStormnodePaymentWinner::IsValid, CStormnodeMan::ProcessMessage.
int CNode::GetRefCount()
References nRefCount.
Referenced by ThreadSocketHandler.
unsigned int CNode::GetTotalRecvSize()
References total, CNetMessage::vRecv, CDataStream::size.
Referenced by ThreadSocketHandler.
bool CNode::ReceiveMsgBytes(const char *pch, unsigned int nBytes)
References SER_NETWORK, CNetMessage::in_data, CNetMessage::readHeader, CNetMessage::readData, CNetMessage::complete, CNetMessage::nTime, GetTimeMicros.
Referenced by ThreadSocketHandler.
void CNode::SetRecvVersion(int nVersionIn)
References CNetMessage::SetVersion.
CNode* CNode::AddRef()
Referenced by ConnectNode, ThreadSocketHandler, ThreadMessageHandler.
void CNode::Release()
Referenced by ThreadSocketHandler, ThreadMessageHandler.
void CNode::AddAddressKnown(const CAddress &addr)
References mruset< T >::insert.
void CNode::PushAddress(const CAddress &addr)
References CNetAddr::IsValid, mruset< T >::count.
Referenced by SendMessages.
void CNode::AddInventoryKnown(const CInv &inv)
References LOCK, mruset< T >::insert.
Referenced by ProcessMessageInstantX.
void CNode::PushInventory(const CInv &inv)
References LOCK, mruset< T >::count.
Referenced by CBlock::AcceptBlock, RelayInv, RelayInventory, CBudgetManager::Sync, CStormnodePayments::Sync, CStormnodeMan::ProcessMessage.
void CNode::AskFor(const CInv &inv)
References CInv::ToString, DateTimeStrFormat, GetTime.
Referenced by ProcessBlock.
void CNode::BeginMessage(const char *pszCommand) EXCLUSIVE_LOCK_FUNCTION(cs_vSend)
References ENTER_CRITICAL_SECTION, CDataStream::size.
Referenced by PushMessage.
void CNode::AbortMessage() UNLOCK_FUNCTION(cs_vSend)
References CDataStream::clear, LEAVE_CRITICAL_SECTION.
Referenced by EndMessage, PushMessage.
void CNode::EndMessage() UNLOCK_FUNCTION(cs_vSend)
References mapArgs, GetRand, atoi, AbortMessage, CDataStream::size, CMessageHeader::HEADER_SIZE, CMessageHeader::MESSAGE_SIZE_OFFSET, hash, Hash, CDataStream::begin, CDataStream::end, CMessageHeader::CHECKSUM_OFFSET, CDataStream::GetAndClear, SocketSendData, LEAVE_CRITICAL_SECTION.
Referenced by PushMessage.
void CNode::PushVersion()
References GetAdjustedTime, GetTime, IsProxy, GetLocalAddress, GetRandBytes, nLocalHostNonce, nBestHeight, CService::ToString, nLocalServices, FormatSubVersion, CLIENT_NAME.
Referenced by CNode.
void CNode::PushMessage(const char *pszCommand)
References BeginMessage, EndMessage, AbortMessage.
Referenced by CAlert::RelayTo, PushGetBlocks, SendMessages, RelayTransactionLockReq, CSandStormRelay::RelayThroughNode, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::SignFinalTransaction, CSandstormPool::DoAutomaticDenominating, CSandstormQueue::Relay, CSandstormPool::RelayFinalTransaction, CSandstormPool::RelayIn, CSandstormPool::RelayStatus, CSandstormPool::RelayCompletedTransaction, ThreadSecureMsg, SecureMsgEnable, SecureMsgDisable, SecureMsgReceiveData, SecureMsgSendData, ProcessSpork, CSporkManager::Relay, CBudgetManager::Sync, CBudgetManager::UpdateProposal, CBudgetManager::UpdateFinalizedBudget, CStormnodePayments::Sync, CStormnodeSync::Process, CStormnodeMan::AskForSN, CStormnodeMan::SsegUpdate, CStormnodeMan::ProcessMessage.
void CNode::PushMessage(const char *pszCommand, const T1 &a1)
References BeginMessage, EndMessage, AbortMessage.
void CNode::PushMessage(const char *pszCommand, const T1 &a1, const T2 &a2)
References BeginMessage, EndMessage, AbortMessage.
void CNode::PushMessage(const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3)
References BeginMessage, EndMessage, AbortMessage.
void CNode::PushMessage(const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3, const T4 &a4)
References BeginMessage, EndMessage, AbortMessage.
void CNode::PushMessage(const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3, const T4 &a4, const T5 &a5)
References BeginMessage, EndMessage, AbortMessage.
void CNode::PushMessage(const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3, const T4 &a4, const T5 &a5, const T6 &a6)
References BeginMessage, EndMessage, AbortMessage.
void CNode::PushMessage(const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3, const T4 &a4, const T5 &a5, const T6 &a6, const T7 &a7)
References BeginMessage, EndMessage, AbortMessage.
void CNode::PushMessage(const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3, const T4 &a4, const T5 &a5, const T6 &a6, const T7 &a7, const T8 &a8)
References BeginMessage, EndMessage, AbortMessage.
void CNode::PushMessage(const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3, const T4 &a4, const T5 &a5, const T6 &a6, const T7 &a7, const T8 &a8, const T9 &a9)
References BeginMessage, EndMessage, AbortMessage.
void CNode::PushMessage(const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3, const T4 &a4, const T5 &a5, const T6 &a6, const T7 &a7, const T8 &a8, const T9 &a9, const T10 &a10)
References BeginMessage, EndMessage, AbortMessage.
void CNode::PushMessage(const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3, const T4 &a4, const T5 &a5, const T6 &a6, const T7 &a7, const T8 &a8, const T9 &a9, const T10 &a10, const T11 &a11)
References BeginMessage, EndMessage, AbortMessage.
void CNode::PushMessage(const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3, const T4 &a4, const T5 &a5, const T6 &a6, const T7 &a7, const T8 &a8, const T9 &a9, const T10 &a10, const T11 &a11, const T12 &a12)
References BeginMessage, EndMessage, AbortMessage.
void CNode::ClearFulfilledRequest(std::string strRequest)
Referenced by CStormnodeSync::ClearFulfilledRequest.
bool CNode::HasFulfilledRequest(std::string strRequest)
Referenced by FulfilledRequest, CBudgetManager::ProcessMessage, CStormnodePayments::ProcessMessageStormnodePayments, CStormnodeSync::Process.
void CNode::FulfilledRequest(std::string strRequest)
References HasFulfilledRequest.
Referenced by CBudgetManager::ProcessMessage, CStormnodePayments::ProcessMessageStormnodePayments, CStormnodeSync::Process.
bool CNode::IsSubscribed(unsigned int nChannel)
void CNode::Subscribe(unsigned int nChannel, unsigned int nHops=0)
void CNode::CancelSubscribe(unsigned int nChannel)
void CNode::CloseSocketDisconnect()
References INVALID_SOCKET, closesocket, TRY_LOCK.
Referenced by SocketSendData, ThreadSocketHandler, ThreadMessageHandler.
bool CNode::Misbehaving(int howmuch)
References LogPrintf, GetArg, GetTime, LOCK.
Referenced by ProcessBlock, SecureMsgReceiveData, SecureMsgReceive.
void CNode::copyStats(CNodeStats &stats)
References CNodeStats::nodeid, X, CNodeStats::fSyncNode, GetTimeMicros, CNodeStats::dPingTime, CNodeStats::dPingWait, CNodeStats::addrLocal, CNetAddr::IsValid, CService::ToString.
Referenced by PeerTablePriv::refreshPeers.
CNode::CNode(const CNode &)
void CNode::operator=(const CNode &)
void CNode::ClearBanned()
bool CNode::IsBanned(CNetAddr ip)
References LOCK, GetTime.
Referenced by ThreadSocketHandler, OpenNetworkConnection.
void CNode::RecordBytesRecv(uint64_t bytes)
References LOCK.
Referenced by ThreadSocketHandler.
void CNode::RecordBytesSent(uint64_t bytes)
References LOCK.
Referenced by SocketSendData.
uint64_t CNode::GetTotalBytesRecv()
References LOCK.
Referenced by ClientModel::getTotalBytesRecv, getnettotals.
uint64_t CNode::GetTotalBytesSent()
References LOCK.
Referenced by ClientModel::getTotalBytesSent, getnettotals.