CConsensusVote
CTxIn CConsensusVote::vinStormnode
Referenced by DoConsensusVote, ProcessConsensusVote, CTransactionLock::SignaturesValid.
uint256 CConsensusVote::txHash
Referenced by DoConsensusVote, ProcessConsensusVote.
int CConsensusVote::nBlockHeight
Referenced by DoConsensusVote, ProcessConsensusVote, CTransactionLock::SignaturesValid, CTransactionLock::CountSignatures.
std::vector<unsigned char> CConsensusVote::vchStormNodeSignature
CConsensusVote::ADD_SERIALIZE_METHODS
uint256 CConsensusVote::GetHash() const
Referenced by DoConsensusVote, ProcessConsensusVote, CleanTransactionLocksList.
bool CConsensusVote::SignatureValid()
References snodeman, CStormnodeMan::Find, LogPrintf, sandStormSigner, CSandStormSigner::VerifyMessage.
Referenced by DoConsensusVote, ProcessConsensusVote, CTransactionLock::SignaturesValid.
bool CConsensusVote::Sign()
References sandStormSigner, CSandStormSigner::SetKey, strStormNodePrivKey, LogPrintf, CSandStormSigner::SignMessage, CSandStormSigner::VerifyMessage.
Referenced by DoConsensusVote.
void CConsensusVote::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE.