leveldb::SequentialFile
leveldb::SequentialFile::SequentialFile()
leveldb::SequentialFile::~SequentialFile()
virtual Status leveldb::SequentialFile::Read(size_t n, Slice *result, char *scratch)=0
Referenced by leveldb::TEST, leveldb::ReadFileToString.
virtual Status leveldb::SequentialFile::Skip(uint64_t n)=0
Referenced by leveldb::TEST.
leveldb::SequentialFile::SequentialFile(const SequentialFile &)
void leveldb::SequentialFile::operator=(const SequentialFile &)