leveldb::Cache
Rep* leveldb::Cache::rep_
leveldb::Cache::Cache()
leveldb::Cache::~Cache()
virtual Handle* leveldb::Cache::Insert(const Slice &key, void *value, size_t charge, void(*deleter)(const Slice &key, void *value))=0
Referenced by leveldb::CacheTest::Insert.
virtual Handle* leveldb::Cache::Lookup(const Slice &key)=0
Referenced by leveldb::CacheTest::Lookup.
virtual void leveldb::Cache::Release(Handle *handle)=0
Referenced by leveldb::TableCache::Get, leveldb::CacheTest::Lookup, leveldb::CacheTest::Insert.
virtual void* leveldb::Cache::Value(Handle *handle)=0
Referenced by leveldb::TableCache::NewIterator, leveldb::TableCache::Get, leveldb::CacheTest::Lookup.
virtual void leveldb::Cache::Erase(const Slice &key)=0
Referenced by leveldb::TableCache::Evict, leveldb::CacheTest::Erase.
virtual uint64_t leveldb::Cache::NewId()=0
Referenced by leveldb::Table::Open.
void leveldb::Cache::LRU_Remove(Handle *e)
void leveldb::Cache::LRU_Append(Handle *e)
void leveldb::Cache::Unref(Handle *e)
leveldb::Cache::Cache(const Cache &)
void leveldb::Cache::operator=(const Cache &)