MacNotificationHandler
void MacNotificationHandler::showNotification(const QString &title, const QString &text)
shows a 10.8+ UserNotification in the UserNotificationCenter
References hasUserNotificationCenterSupport.
void MacNotificationHandler::sendAppleScript(const QString &script)
executes AppleScript
bool MacNotificationHandler::hasUserNotificationCenterSupport(void)
check if OS can handle UserNotifications
Referenced by showNotification, Notificator::Notificator.
MacNotificationHandler * MacNotificationHandler::instance()
Referenced by Notificator::Notificator.