CCoinControl
CTxDestination CCoinControl::destChange
bool CCoinControl::useSandStorm
Referenced by CoinControlDialog::updateLabels, SendCoinsDialog::SendCoinsDialog.
bool CCoinControl::useInstantX
Referenced by CoinControlDialog::updateLabels, SendCoinsDialog::SendCoinsDialog.
std::set<COutPoint> CCoinControl::setSelected
CCoinControl::CCoinControl()
References SetNull.
void CCoinControl::SetNull()
Referenced by CCoinControl.
bool CCoinControl::HasSelected() const
Referenced by CWallet::AvailableCoins.
bool CCoinControl::IsSelected(const uint256 &hash, unsigned int n) const
Referenced by CWallet::AvailableCoins.
void CCoinControl::Select(COutPoint &output)
void CCoinControl::UnSelect(COutPoint &output)
void CCoinControl::UnSelectAll()
void CCoinControl::ListSelected(std::vector< COutPoint > &vOutpoints)
Referenced by CoinControlDialog::updateLabels.