CBlockIndex
@0
@1
const uint256* CBlockIndex::phashBlock
Referenced by GetBlockHash, CBlock::AddToBlockIndex, getBlockHash, getblockhash, getblockbynumber.
CBlockIndex* CBlockIndex::pprev
Referenced by CBlock::DisconnectBlock, CBlock::ConnectBlock, InvalidChainFound, Reorganize, CChain::SetTip, GetMedianTimePast, CBlockLocator::Set, Checkpoints::AutoSelectSyncCheckpoint, AppInit2, ComputeNextStakeModifier, GetLastBlockIndex, GetNextTargetRequired, IsConfirmedInNPrevBlocks, PrintBlockTree, CBlock::SetBestChain, CBlock::AddToBlockIndex, getBlockHash, GetPoSKernelPS, blockToJSON, getblockbynumber, importwallet, listsinceblock, scanforalltxns, scanforstealthtxns, GetBlockHash, CStormnode::GetLastPaid, CTxDB::LoadBlockIndex, CBlockTreeDB::LoadBlockIndexGuts.
CBlockIndex* CBlockIndex::pnext
Referenced by Reorganize, GetTransaction, GetPoWMHashPS, blockToJSON, scanforstealthtxns, ScanChainForPublicKeys, CTxDB::LoadBlockIndex, CWallet::ScanForWalletTransactions.
unsigned int CBlockIndex::nFile
Referenced by CBlock::ConnectBlock, IsConfirmedInNPrevBlocks, PrintBlockTree, CTxDB::LoadBlockIndex, CBlockTreeDB::LoadBlockIndexGuts.
unsigned int CBlockIndex::nBlockPos
Referenced by CBlock::ConnectBlock, IsConfirmedInNPrevBlocks, PrintBlockTree, CTxDB::LoadBlockIndex.
uint256 CBlockIndex::nChainTrust
Referenced by InvalidChainFound, CBlock::SetBestChain, CBlock::AddToBlockIndex, blockToJSON, CTxDB::LoadBlockIndex.
int CBlockIndex::nHeight
Referenced by CBlock::AcceptBlock, InvalidChainFound, Reorganize, CChain::SetTip, CBlockLocator::GetHeight, CChain::operator[], CChain::Contains, CChain::Next, Checkpoints::AutoSelectSyncCheckpoint, AppInit2, CreateNewLock, ComputeNextStakeModifier, CheckStakeKernelHash, CMerkleTx::SetMerkleBranch, GetInputAge, CTxIndex::GetDepthInMainChain, GetProofOfWorkReward, GetNextTargetRequired, IsConfirmedInNPrevBlocks, PrintBlockTree, CBlock::SetBestChain, CBlock::AddToBlockIndex, CreateNewBlock, IncrementExtraNonce, getBlockHash, blocksInPastHours, BlockBrowser::updateExplorer, OverviewPage::sandStormStatus, StatisticsPage::updateStatistics, TransactionRecord::updateStatus, blockToJSON, getblockbynumber, getcheckpoint, importwallet, getblocktemplate, TxToJSON, snbudget, stormnode, stormnodelist, listsinceblock, gettransaction, scanforalltxns, scanforstealthtxns, CSandstormPool::GetStatus, CSandstormPool::CompletedTransaction, CSandstormPool::DoAutomaticDenominating, CSandstormPool::MakeCollateralAmounts, CSandstormPool::CreateDenominated, ScanChainForPublicKeys, ProcessSpork, IsBudgetCollateralValid, CBudgetManager::SubmitFinalBudget, CBudgetManager::CheckAndRemove, CBudgetManager::FillBlockPayee, CBudgetManager::HasNextFinalizedBudget, CBudgetManager::GetBudget, CBudgetProposal::IsValid, CBudgetProposal::GetBlockCurrentCycle, CFinalizedBudget::AutoCheck, IsBlockValueValid, FillBlockPayee, CStormnodePayments::FillBlockPayee, CStormnodePayments::ProcessMessageStormnodePayments, CStormnodePayments::IsScheduled, CStormnodePayments::CleanPaymentList, CStormnodePayments::Sync, GetBlockHash, CStormnode::GetLastPaid, CStormnode::GetStormnodeInputAge, CTxDB::LoadBlockIndex, CBlockTreeDB::LoadBlockIndexGuts, CWallet::CreateCoinStake.
int64_t CBlockIndex::nMint
Referenced by CBlock::ConnectBlock, PrintBlockTree, blockToJSON, CTxDB::LoadBlockIndex.
int64_t CBlockIndex::nMoneySupply
Referenced by CBlock::ConnectBlock, StatisticsPage::updateStatistics, getinfo, CTxDB::LoadBlockIndex.
unsigned int CBlockIndex::nFlags
Referenced by CTxDB::LoadBlockIndex.
uint64_t CBlockIndex::nStakeModifier
Referenced by CDiskBlockIndex::SerializationOp, CheckStakeKernelHash, blockToJSON, CTxDB::LoadBlockIndex.
uint256 CBlockIndex::bnStakeModifierV2
Referenced by CDiskBlockIndex::SerializationOp, ComputeStakeModifierV2, CheckStakeKernelHash, CBlock::AddToBlockIndex, blockToJSON, CTxDB::LoadBlockIndex.
COutPoint CBlockIndex::prevoutStake
Referenced by CDiskBlockIndex::SerializationOp, CBlock::AddToBlockIndex, CTxDB::LoadBlockIndex.
unsigned int CBlockIndex::nStakeTime
Referenced by ToString, CDiskBlockIndex::SerializationOp, CBlock::AddToBlockIndex, CTxDB::LoadBlockIndex.
uint256 CBlockIndex::hashProof
Referenced by CDiskBlockIndex::SerializationOp, CBlock::AddToBlockIndex, blockToJSON, CTxDB::LoadBlockIndex.
int CBlockIndex::nVersion
Referenced by GetBlockHeader, CDiskBlockIndex::GetBlockHash, CBlock::SetBestChain, CTxDB::LoadBlockIndex, CBlockTreeDB::LoadBlockIndexGuts.
uint256 CBlockIndex::hashMerkleRoot
Referenced by GetBlockHeader, CDiskBlockIndex::SerializationOp, CDiskBlockIndex::GetBlockHash, getBlockMerkle, CTxDB::LoadBlockIndex, CBlockTreeDB::LoadBlockIndexGuts.
unsigned int CBlockIndex::nTime
Referenced by GetBlockHeader, GetBlockTime, CDiskBlockIndex::SerializationOp, CDiskBlockIndex::GetBlockHash, CheckStakeKernelHash, ProcessBlock, getBlockTime, GetPoSKernelPS, importwallet, dumpwallet, TxToJSON, IsBudgetCollateralValid, CStormnodeSync::IsBlockchainSynced, CStormnode::GetLastPaid, CTxDB::LoadBlockIndex, CBlockTreeDB::LoadBlockIndexGuts, CWallet::ScanForWalletTransactions.
unsigned int CBlockIndex::nBits
Referenced by GetBlockTrust, GetBlockHeader, CDiskBlockIndex::SerializationOp, CDiskBlockIndex::GetBlockHash, GetNextTargetRequired, CreateNewBlock, getBlockHardness, getBlocknBits, GetDifficulty, CBudgetManager::FillBlockPayee, CStormnodePayments::FillBlockPayee, CTxDB::LoadBlockIndex, CBlockTreeDB::LoadBlockIndexGuts.
unsigned int CBlockIndex::nNonce
Referenced by GetBlockHeader, CDiskBlockIndex::SerializationOp, CDiskBlockIndex::GetBlockHash, getBlockNonce, CTxDB::LoadBlockIndex, CBlockTreeDB::LoadBlockIndexGuts.
unsigned int CBlockIndex::nDataPos
Byte offset within blk?????.dat where this block's data is stored.
Referenced by CBlockTreeDB::LoadBlockIndexGuts.
unsigned int CBlockIndex::nUndoPos
Byte offset within rev?????.dat where this block's undo data is stored.
Referenced by CBlockTreeDB::LoadBlockIndexGuts.
uint256 CBlockIndex::nChainWork
(memory only) Total amount of work (expected number of hashes) in the chain up to and including this block
uint32_t CBlockIndex::nSequenceId
(memory only) Sequential id assigned to distinguish order in which blocks are received.
unsigned int CBlockIndex::nStatus
Verification status of this block. See enum BlockStatus.
Referenced by CBlockTreeDB::LoadBlockIndexGuts.
unsigned int CBlockIndex::nTx
Number of transactions in this block. Note: in a potential headers-first mode, this number cannot be relied upon
Referenced by CBlockTreeDB::LoadBlockIndexGuts.
CBlockIndex::CBlockIndex()
References COutPoint::SetNull.
CBlockIndex::CBlockIndex(unsigned int nFileIn, unsigned int nBlockPosIn, CBlock &block)
References CBlock::IsProofOfStake, SetProofOfStake, CBlock::vtx, COutPoint::SetNull, CBlockHeader::nVersion, CBlockHeader::hashMerkleRoot, CBlockHeader::nTime, CBlockHeader::nBits, CBlockHeader::nNonce.
CBlock CBlockIndex::GetBlockHeader() const
References CBlockHeader::nVersion, nVersion, CBlockHeader::hashPrevBlock, GetBlockHash, CBlockHeader::hashMerkleRoot, hashMerkleRoot, CBlockHeader::nTime, nTime, CBlockHeader::nBits, nBits, CBlockHeader::nNonce, nNonce.
uint256 CBlockIndex::GetBlockHash() const
References phashBlock.
Referenced by CBlock::ConnectBlock, InvalidChainFound, Reorganize, GetBlockHeader, ToString, CDiskBlockIndex::CDiskBlockIndex, CDiskBlockIndex::ToString, CBlockLocator::Set, ComputeNextStakeModifier, CreateNewBlock, blockToJSON, getcheckpoint, listsinceblock, IsBlockValueValid, GetBlockHash, CBlockTreeDB::LoadBlockIndexGuts.
int64_t CBlockIndex::GetBlockTime() const
References nTime.
Referenced by CBlock::AcceptBlock, InvalidChainFound, IsInitialBlockDownload, GetPastTimeLimit, GetMedianTimePast, ComputeNextStakeModifier, GetNextTargetRequired, CBlock::SetBestChain, ThreadStakeMiner, ClientModel::getLastBlockDate, GetPoWMHashPS, getcheckpoint, CTxDB::LoadBlockIndex.
uint256 CBlockIndex::GetBlockTrust() const
References CBigNum::SetCompact, nBits, CBigNum::getuint256.
Referenced by CBlock::AddToBlockIndex, blockToJSON, CTxDB::LoadBlockIndex.
bool CBlockIndex::IsInMainChain() const
Referenced by CBlockLocator::GetDistanceBack, CBlockLocator::GetBlockIndex, CBlockLocator::GetBlockHash, CMerkleTx::SetMerkleBranch, CTxIndex::GetDepthInMainChain, blockToJSON, TxToJSON, gettransaction, IsBudgetCollateralValid.
bool CBlockIndex::CheckIndex() const
Referenced by CTxDB::LoadBlockIndex.
int64_t CBlockIndex::GetPastTimeLimit() const
References GetBlockTime.
Referenced by CBlock::AcceptBlock, CreateNewBlock, getworkex, getblocktemplate.
int64_t CBlockIndex::GetMedianTimePast() const
References nMedianTimeSpan, pprev, GetBlockTime.
bool CBlockIndex::IsProofOfWork() const
References BLOCK_PROOF_OF_STAKE.
Referenced by GetPoWMHashPS.
bool CBlockIndex::IsProofOfStake() const
References BLOCK_PROOF_OF_STAKE.
Referenced by ToString, CDiskBlockIndex::SerializationOp, ComputeNextStakeModifier, GetLastBlockIndex, CBlock::AddToBlockIndex, GetPoSKernelPS, blockToJSON, CTxDB::LoadBlockIndex.
void CBlockIndex::SetProofOfStake()
References BLOCK_PROOF_OF_STAKE.
Referenced by CBlockIndex.
unsigned int CBlockIndex::GetStakeEntropyBit() const
References BLOCK_STAKE_ENTROPY.
Referenced by ToString, ComputeNextStakeModifier, blockToJSON.
bool CBlockIndex::SetStakeEntropyBit(unsigned int nEntropyBit)
References BLOCK_STAKE_ENTROPY.
Referenced by CBlock::AddToBlockIndex.
bool CBlockIndex::GeneratedStakeModifier() const
References BLOCK_STAKE_MODIFIER.
Referenced by ToString, blockToJSON.
void CBlockIndex::SetStakeModifier(uint64_t nModifier, bool fGeneratedStakeModifier)
References BLOCK_STAKE_MODIFIER.
Referenced by CBlock::AddToBlockIndex.
std::string CBlockIndex::ToString() const
References strprintf, FormatMoney, GeneratedStakeModifier, GetStakeEntropyBit, IsProofOfStake, base_uint< BITS >::ToString, COutPoint::ToString, nStakeTime, GetBlockHash.
Referenced by CDiskBlockIndex::ToString, getBlockDebug, CBlockTreeDB::LoadBlockIndexGuts.