leveldb::Status
Code
const char* leveldb::Status::state_
leveldb::Status::Status()
Referenced by OK, NotFound, Corruption, NotSupported, InvalidArgument, IOError.
leveldb::Status::~Status()
leveldb::Status::Status(const Status &s)
void leveldb::Status::operator=(const Status &s)
bool leveldb::Status::ok() const
Referenced by leveldb::BuildTable, leveldb_get, leveldb::CorruptionTest::Corrupt, leveldb::TEST, leveldb::SanitizeOptions, leveldb::DBImpl::TEST_CompactRange, leveldb::DBImpl::TEST_CompactMemTable, leveldb::DBImpl::Write, leveldb::DB::Open, leveldb::DestroyDB, leveldb::SpecialEnv::NewWritableFile, leveldb::SpecialEnv::NewRandomAccessFile, leveldb::DBTest::Get, leveldb::DBTest::AllEntriesFor, leveldb::SetCurrentFile, leveldb::log::Writer::AddRecord, leveldb::TableCache::NewIterator, leveldb::TableCache::Get, leveldb::Version::Get, leveldb::VersionSet::LogAndApply, leveldb::VersionSet::Recover, leveldb::Footer::DecodeFrom, leveldb::ReadBlock, leveldb::Table::Open, leveldb::Table::ApproximateOffsetOf, leveldb::TableBuilder::Finish, leveldb::Constructor::Finish, leveldb::TableConstructor::FinishImpl, leveldb::KeyConvertingIterator::status, leveldb::DBConstructor::FinishImpl, leveldb::ReadFileToString, leveldb::test::TmpDir, leveldb::test::Tester::IsOk, CLevelDBWrapper::Read, CLevelDBWrapper::Exists, SecMsgDB::Open, SecMsgDB::ScanBatch, SecMsgDB::TxnCommit, SecMsgDB::ReadPK, SecMsgDB::WritePK, SecMsgDB::ReadSmesg, SecMsgDB::WriteSmesg, SecMsgDB::EraseSmesg, CTxDB::TxnCommit, CTxDB::ScanBatch, CTxDB::Read, CTxDB::Write, CTxDB::Erase.
bool leveldb::Status::IsNotFound() const
Referenced by leveldb_get, leveldb::DBTest::Get, CLevelDBWrapper::Read, CLevelDBWrapper::Exists, SecMsgDB::ReadPK, SecMsgDB::ExistsPK, SecMsgDB::ReadSmesg, SecMsgDB::ExistsSmesg, SecMsgDB::EraseSmesg, CTxDB::Read, CTxDB::Erase, CTxDB::Exists.
bool leveldb::Status::IsCorruption() const
bool leveldb::Status::IsIOError() const
std::string leveldb::Status::ToString() const
Referenced by leveldb::CorruptionTest::Corrupt, leveldb::DBTest::Get, leveldb::DBTest::AllEntriesFor, leveldb::TEST, leveldb::VersionSet::LogAndApply, leveldb::Constructor::Finish, leveldb::TableConstructor::FinishImpl, leveldb::test::TmpDir, leveldb::test::Tester::IsOk, CLevelDBWrapper::Read, CLevelDBWrapper::Exists, SecMsgDB::Open, SecMsgDB::ScanBatch, SecMsgDB::TxnCommit, SecMsgDB::ReadPK, SecMsgDB::WritePK, SecMsgDB::ReadSmesg, SecMsgDB::WriteSmesg, SecMsgDB::EraseSmesg, CTxDB::TxnCommit, CTxDB::ScanBatch, CTxDB::Read, CTxDB::Write.
static Status leveldb::Status::OK()
References Status.
Referenced by leveldb::DestroyDB, leveldb::SpecialEnv::NewWritableFile, leveldb::MemTableIterator::status, leveldb::Version::LevelFileNumIterator::status, leveldb::WriteBatch::Iterate, leveldb::BlockHandle::DecodeFrom, leveldb::ReadBlock, leveldb::NewEmptyIterator, leveldb::TableBuilder::ChangeOptions, leveldb::StringSink::Close, leveldb::StringSink::Flush, leveldb::StringSink::Sync, leveldb::StringSink::Append, leveldb::StringSource::Read, leveldb::BlockConstructor::FinishImpl, leveldb::MemTableConstructor::FinishImpl, leveldb::DBConstructor::FinishImpl.
static Status leveldb::Status::NotFound(const Slice &msg, const Slice &msg2=Slice())
References Status.
Referenced by leveldb::ModelDB::Get, leveldb::MemTable::Get, leveldb::Version::Get.
static Status leveldb::Status::Corruption(const Slice &msg, const Slice &msg2=Slice())
References Status.
Referenced by leveldb::VersionEdit::DecodeFrom, leveldb::Version::Get, leveldb::VersionSet::Recover, leveldb::WriteBatch::Iterate, leveldb::Block::NewIterator, leveldb::BlockHandle::DecodeFrom, leveldb::Footer::DecodeFrom, leveldb::ReadBlock, leveldb::Table::Open, leveldb::KeyConvertingIterator::key.
static Status leveldb::Status::NotSupported(const Slice &msg, const Slice &msg2=Slice())
References Status.
static Status leveldb::Status::InvalidArgument(const Slice &msg, const Slice &msg2=Slice())
References Status.
Referenced by leveldb::DumpFile, leveldb::VersionSet::Recover, leveldb::TableBuilder::ChangeOptions, leveldb::StringSource::Read.
static Status leveldb::Status::IOError(const Slice &msg, const Slice &msg2=Slice())
References Status.
Referenced by leveldb::SpecialEnv::NewWritableFile, leveldb::test::ErrorEnv::NewWritableFile.
Code leveldb::Status::code() const
leveldb::Status::Status(Code code, const Slice &msg, const Slice &msg2)
const char * leveldb::Status::CopyState(const char *s)