leveldb::Slice
const char* leveldb::Slice::data_
size_t leveldb::Slice::size_
leveldb::Slice::Slice()
leveldb::Slice::Slice(const char *d, size_t n)
leveldb::Slice::Slice(const std::string &s)
leveldb::Slice::Slice(const char *s)
const char* leveldb::Slice::data() const
Referenced by CCoinsViewDB::GetStats, leveldb_comparator_t::Compare, leveldb_filterpolicy_t::CreateFilter, leveldb_filterpolicy_t::KeyMayMatch, leveldb_iter_key, leveldb_iter_value, leveldb_writebatch_iterate, leveldb::AppendInternalKey, leveldb::InternalKeyComparator::Compare, leveldb::InternalKeyComparator::FindShortestSeparator, leveldb::InternalKeyComparator::FindShortSuccessor, leveldb::LookupKey::LookupKey, leveldb::ExtractUserKey, leveldb::ExtractValueType, leveldb::InternalKey::DecodeFrom, leveldb::ParseInternalKey, leveldb::log::Reader::ReadRecord, leveldb::log::LogTest::CheckInitialOffsetRecord, leveldb::log::Writer::AddRecord, leveldb::MemTableIterator::value, leveldb::MemTable::Add, leveldb::MemTable::Get, leveldb::WriteBatchInternal::SetContents, leveldb::TEST, leveldb::operator==, leveldb::BlockBuilder::Add, leveldb::FilterBlockBuilder::AddKey, leveldb::FilterBlockReader::FilterBlockReader, leveldb::TestHashFilter::KeyMayMatch, leveldb::Footer::DecodeFrom, leveldb::TableBuilder::Add, leveldb::StringSink::Append, leveldb::PutLengthPrefixedSlice, leveldb::GetVarint32, leveldb::GetVarint64, leveldb::GetLengthPrefixedSlice, leveldb::ReadFileToString, SecMsgDB::NextSmesg, SecMsgDB::NextSmesgKey, CTxDB::LoadBlockIndex, CBlockTreeDB::LoadBlockIndexGuts.
size_t leveldb::Slice::size() const
Referenced by CCoinsViewDB::GetStats, leveldb_comparator_t::Compare, leveldb_filterpolicy_t::CreateFilter, leveldb_filterpolicy_t::KeyMayMatch, leveldb_iter_key, leveldb_iter_value, leveldb_writebatch_iterate, leveldb::DBImpl::GetProperty, leveldb::TEST, leveldb::AppendInternalKey, leveldb::InternalKeyComparator::Compare, leveldb::InternalKeyComparator::FindShortestSeparator, leveldb::InternalKeyComparator::FindShortSuccessor, leveldb::LookupKey::LookupKey, leveldb::InternalKeyEncodingLength, leveldb::ExtractUserKey, leveldb::ExtractValueType, leveldb::InternalKey::DecodeFrom, leveldb::ParseInternalKey, leveldb::log::Reader::ReadRecord, leveldb::log::LogTest::CheckInitialOffsetRecord, leveldb::log::Writer::AddRecord, leveldb::MemTableIterator::value, leveldb::MemTable::Add, leveldb::MemTable::Get, leveldb::WriteBatch::Iterate, leveldb::WriteBatchInternal::SetContents, operator[], remove_prefix, leveldb::operator==, leveldb::BlockBuilder::Add, leveldb::FilterBlockBuilder::AddKey, leveldb::FilterBlockReader::FilterBlockReader, leveldb::TestHashFilter::KeyMayMatch, leveldb::Footer::DecodeFrom, leveldb::TableBuilder::Add, leveldb::StringSink::Append, leveldb::PutLengthPrefixedSlice, leveldb::GetVarint32, leveldb::GetVarint64, leveldb::GetLengthPrefixedSlice, leveldb::ReadFileToString, leveldb::AppendEscapedStringTo, SecMsgDB::NextSmesg, SecMsgDB::NextSmesgKey, CTxDB::LoadBlockIndex, CBlockTreeDB::LoadBlockIndexGuts.
bool leveldb::Slice::empty() const
Referenced by leveldb::DBImpl::GetProperty, leveldb::ParseFileName, leveldb::VersionEdit::DecodeFrom, leveldb::WriteBatch::Iterate, leveldb::ReadFileToString, leveldb::ConsumeDecimalNumber.
char leveldb::Slice::operator[](size_t n) const
References size.
void leveldb::Slice::clear()
Referenced by leveldb::log::Reader::ReadRecord, leveldb::Version::GetOverlappingInputs.
void leveldb::Slice::remove_prefix(size_t n)
References size.
Referenced by leveldb::DBImpl::GetProperty, leveldb::ParseFileName, leveldb::SetCurrentFile, leveldb::WriteBatch::Iterate, leveldb::GetLengthPrefixedSlice, leveldb::ConsumeDecimalNumber.
std::string leveldb::Slice::ToString() const
Referenced by leveldb::AutoCompactTest::DoReads, leveldb::Benchmark::Run, leveldb::DBTest::AllEntriesFor, leveldb::DBTest::IterStatus, leveldb::TEST, leveldb::ModelDB::Write, leveldb::ParsedInternalKey::DebugString, leveldb::SetCurrentFile, leveldb::log::LogTest::Read, leveldb::VersionEdit::DecodeFrom, leveldb::VersionEdit::SetComparatorName, leveldb::Constructor::Add, leveldb::BlockConstructor::FinishImpl, leveldb::Harness::ToString, leveldb::BloomTest::Add, SecMsgBatchScanner::Put, SecMsgBatchScanner::Delete, CBatchScanner::Put, CBatchScanner::Delete.
int leveldb::Slice::compare(const Slice &b) const
Referenced by leveldb::TEST.
bool leveldb::Slice::starts_with(const Slice &x) const
Referenced by leveldb::Benchmark::Benchmark, leveldb::DBImpl::GetProperty, leveldb::ParseFileName, leveldb::SetCurrentFile.