CNetAddr
unsigned char CNetAddr::ip[16][16]
Referenced by SetIP, operator==, operator!=, operator<, CService::CService, CService::GetKey, CService::SerializationOp.
CNetAddr::ADD_SERIALIZE_METHODS
CNetAddr::CNetAddr()
CNetAddr::CNetAddr(const struct in_addr &ipv4Addr)
CNetAddr::CNetAddr(const char *pszIp, bool fAllowLookup=false)
References LookupHost.
CNetAddr::CNetAddr(const std::string &strIp, bool fAllowLookup=false)
References LookupHost.
void CNetAddr::Init()
void CNetAddr::SetIP(const CNetAddr &ip)
References ip.
Referenced by OptionsModel::setData.
bool CNetAddr::SetSpecial(const std::string &strName)
References I2PSession::Instance, SAM::StreamSessionAdapter::namingLookup, DecodeBase32.
Referenced by ThreadSocketHandler.
bool CNetAddr::IsIPv4() const
Referenced by CService::GetSockAddr, CService::ToStringIPPort.
bool CNetAddr::IsIPv6() const
Referenced by BindListenPort, CService::GetSockAddr.
bool CNetAddr::IsRFC1918() const
Referenced by CStormnodeBroadcast::CheckInputsAndAdd, CStormnodeMan::SsegUpdate, CStormnodeMan::ProcessMessage.
bool CNetAddr::IsRFC3849() const
bool CNetAddr::IsRFC3927() const
bool CNetAddr::IsRFC3964() const
bool CNetAddr::IsRFC4193() const
bool CNetAddr::IsRFC4380() const
bool CNetAddr::IsRFC4843() const
bool CNetAddr::IsRFC4862() const
bool CNetAddr::IsRFC6052() const
bool CNetAddr::IsRFC6145() const
bool CNetAddr::IsTor() const
Referenced by CService::ToStringIPPort, BOOST_AUTO_TEST_CASE.
bool CNetAddr::IsI2P() const
Referenced by CService::ToStringIPPort.
bool CNetAddr::IsLocal() const
Referenced by CStormnodeBroadcast::CheckInputsAndAdd, CStormnodeMan::SsegUpdate, CStormnodeMan::ProcessMessage.
bool CNetAddr::IsRoutable() const
References IsLocal.
Referenced by CAddrMan::Add_, SendMessages, IsPeerAddrLocalGood, AddLocal, BindListenPort, BOOST_AUTO_TEST_CASE.
bool CNetAddr::IsValid() const
Referenced by AppInit2, CNode::copyStats, ThreadOpenConnections, CNode::PushAddress, SetProxy, SetNameProxy, GetNameProxy, HaveNameProxy, ConnectSocketByName, getinfo.
bool CNetAddr::IsMulticast() const
enum Network CNetAddr::GetNetwork() const
References NET_UNROUTABLE, NET_IPV4, NET_TOR, NET_I2P, NET_IPV6.
Referenced by IsPeerAddrLocalGood, AddLocal, IsLimited, IsReachable, ConnectSocket.
std::string CNetAddr::ToString() const
Referenced by CAddrMan::Add, CSandstormPool::ProcessMessageSandstorm.
std::string CNetAddr::ToStringIP() const
References EncodeBase32, CService::GetSockAddr, name, strprintf.
Referenced by ConnectSocket, CService::ToStringIPPort, OptionsModel::data, BOOST_AUTO_TEST_CASE.
unsigned int CNetAddr::GetByte(int n) const
uint64_t CNetAddr::GetHash() const
References hash, Hash.
bool CNetAddr::GetInAddr(struct in_addr *pipv4Addr) const
Referenced by CService::GetSockAddr.
std::vector< unsigned char > CNetAddr::GetGroup() const
References NET_IPV6, IsLocal, NET_UNROUTABLE, NET_IPV4, NET_TOR, NET_I2P.
Referenced by CAddrInfo::GetNewBucket, ThreadOpenConnections.
int CNetAddr::GetReachabilityFrom(const CNetAddr *paddrPartner=NULL) const
Calculates a metric for how reachable (*this) is from a given partner
References NET_IPV4, NET_IPV6, NET_TOR, NET_I2P, NET_UNROUTABLE.
CNetAddr::CNetAddr(const struct in6_addr &pipv6Addr)
bool CNetAddr::GetIn6Addr(struct in6_addr *pipv6Addr) const
Referenced by CService::GetSockAddr.
void CNetAddr::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE, FLATDATA.
bool operator==(const CNetAddr &a, const CNetAddr &b)
bool operator!=(const CNetAddr &a, const CNetAddr &b)
bool operator<(const CNetAddr &a, const CNetAddr &b)