leveldb::VersionSet::Builder
typedef std::set<FileMetaData*, BySmallestKey> leveldb::VersionSet::Builder::FileSet
VersionSet* leveldb::VersionSet::Builder::vset_
Version* leveldb::VersionSet::Builder::base_
LevelState leveldb::VersionSet::Builder::levels_[config::kNumLevels][config::kNumLevels]
leveldb::VersionSet::Builder::Builder(VersionSet *vset, Version *base)
References leveldb::Version::Ref, cmp.
leveldb::VersionSet::Builder::~Builder()
References leveldb::FileMetaData::refs, leveldb::Version::Unref.
void leveldb::VersionSet::Builder::Apply(VersionEdit *edit)
References leveldb::FileMetaData::refs, leveldb::FileMetaData::allowed_seeks, leveldb::FileMetaData::file_size, leveldb::FileMetaData::number.
Referenced by leveldb::VersionSet::LogAndApply, leveldb::VersionSet::Recover.
void leveldb::VersionSet::Builder::SaveTo(Version *v)
References cmp, MaybeAddFile, leveldb::InternalKeyComparator::Compare, leveldb::InternalKey::DebugString.
Referenced by leveldb::VersionSet::LogAndApply, leveldb::VersionSet::Recover.
void leveldb::VersionSet::Builder::MaybeAddFile(Version *v, int level, FileMetaData *f)
References leveldb::FileMetaData::number, leveldb::InternalKeyComparator::Compare, leveldb::FileMetaData::smallest, leveldb::FileMetaData::refs.
Referenced by SaveTo.