SecMsgDB
leveldb::DB* SecMsgDB::pdb
Referenced by MessageTablePriv::refreshMessageTable, smsginbox, smsgoutbox, Open, TxnCommit, ReadPK, WritePK, ExistsPK, NextSmesg, NextSmesgKey, ReadSmesg, WriteSmesg, ExistsSmesg, EraseSmesg, ThreadSecureMsgPow.
leveldb::WriteBatch* SecMsgDB::activeBatch
Referenced by ScanBatch, TxnBegin, TxnCommit, TxnAbort, ReadPK, WritePK, ExistsPK, ReadSmesg, WriteSmesg, ExistsSmesg, EraseSmesg, SecMsgDB, ~SecMsgDB.
SecMsgDB::SecMsgDB()
References activeBatch.
SecMsgDB::~SecMsgDB()
References activeBatch.
bool SecMsgDB::Open(const char *pszMode="r+")
References pdb, smsgDB, GetDataDir, LogPrintf, leveldb::Options::create_if_missing, leveldb::DB::Open, leveldb::Status::ok, leveldb::Status::ToString.
Referenced by MessageTablePriv::refreshMessageTable, MessageModel::removeRows, smsginbox, smsgoutbox, ThreadSecureMsgPow, SecureMsgInsertAddress, SecureMsgScanBlock, ScanChainForPublicKeys, SecureMsgScanMessage, SecureMsgGetStoredKey, SecureMsgSend.
bool SecMsgDB::ScanBatch(const CDataStream &key, std::string *value, bool *deleted) const
References activeBatch, SecMsgBatchScanner::needle, CDataStream::str, SecMsgBatchScanner::deleted, SecMsgBatchScanner::foundValue, value, leveldb::WriteBatch::Iterate, leveldb::Status::ok, LogPrintf, leveldb::Status::ToString, SecMsgBatchScanner::foundEntry.
Referenced by ReadPK, ExistsPK, ReadSmesg, ExistsSmesg.
bool SecMsgDB::TxnBegin()
References activeBatch.
Referenced by smsginbox, smsgoutbox, SecureMsgScanBlock, ScanChainForPublicKeys.
bool SecMsgDB::TxnCommit()
References activeBatch, leveldb::WriteOptions::sync, pdb, leveldb::DB::Write, leveldb::Status::ok, LogPrintf, leveldb::Status::ToString.
Referenced by smsginbox, smsgoutbox, SecureMsgScanBlock, ScanChainForPublicKeys.
bool SecMsgDB::TxnAbort()
References activeBatch.
bool SecMsgDB::ReadPK(CKeyID &addr, CPubKey &pubkey)
References pdb, SER_DISK, CDataStream::reserve, activeBatch, ScanBatch, leveldb::DB::Get, CDataStream::str, leveldb::Status::ok, leveldb::Status::IsNotFound, LogPrintf, leveldb::Status::ToString.
Referenced by SecureMsgGetStoredKey.
bool SecMsgDB::WritePK(CKeyID &addr, CPubKey &pubkey)
References pdb, SER_DISK, CDataStream::reserve, activeBatch, leveldb::WriteBatch::Put, CDataStream::str, leveldb::WriteOptions::sync, leveldb::DB::Put, leveldb::Status::ok, LogPrintf, leveldb::Status::ToString.
bool SecMsgDB::ExistsPK(CKeyID &addr)
References pdb, SER_DISK, CDataStream::reserve, activeBatch, ScanBatch, leveldb::DB::Get, CDataStream::str, leveldb::Status::IsNotFound.
bool SecMsgDB::NextSmesg(leveldb::Iterator *it, std::string &prefix, uint8_t *vchKey, SecMsgStored &smsgStored)
References pdb, leveldb::Iterator::Valid, leveldb::Iterator::Seek, leveldb::Iterator::Next, leveldb::Iterator::key, leveldb::Slice::size, leveldb::Slice::data, leveldb::Iterator::value, SER_DISK, LogPrintf.
Referenced by MessageTablePriv::refreshMessageTable, smsginbox, smsgoutbox, ThreadSecureMsgPow.
bool SecMsgDB::NextSmesgKey(leveldb::Iterator *it, std::string &prefix, uint8_t *vchKey)
References pdb, leveldb::Iterator::Valid, leveldb::Iterator::Seek, leveldb::Iterator::Next, leveldb::Iterator::key, leveldb::Slice::size, leveldb::Slice::data.
Referenced by smsginbox, smsgoutbox.
bool SecMsgDB::ReadSmesg(uint8_t *chKey, SecMsgStored &smsgStored)
References pdb, SER_DISK, CDataStream::write, activeBatch, ScanBatch, leveldb::DB::Get, CDataStream::str, leveldb::Status::ok, leveldb::Status::IsNotFound, LogPrintf, leveldb::Status::ToString.
bool SecMsgDB::WriteSmesg(uint8_t *chKey, SecMsgStored &smsgStored)
References pdb, SER_DISK, CDataStream::write, activeBatch, leveldb::WriteBatch::Put, CDataStream::str, leveldb::WriteOptions::sync, leveldb::DB::Put, leveldb::Status::ok, LogPrintf, leveldb::Status::ToString.
Referenced by smsginbox, SecureMsgScanMessage, SecureMsgSend.
bool SecMsgDB::ExistsSmesg(uint8_t *chKey)
References pdb, SER_DISK, CDataStream::write, activeBatch, ScanBatch, leveldb::DB::Get, CDataStream::str, leveldb::Status::IsNotFound.
Referenced by SecureMsgScanMessage.
bool SecMsgDB::EraseSmesg(uint8_t *chKey)
References SER_DISK, CDataStream::write, activeBatch, leveldb::WriteBatch::Delete, CDataStream::str, leveldb::WriteOptions::sync, pdb, leveldb::DB::Delete, leveldb::Status::ok, leveldb::Status::IsNotFound, LogPrintf, leveldb::Status::ToString.
Referenced by MessageModel::removeRows, smsginbox, smsgoutbox, ThreadSecureMsgPow.