OptionsModel
OptionID
int OptionsModel::nDisplayUnit
bool OptionsModel::fMinimizeToTray
bool OptionsModel::fMinimizeOnClose
bool OptionsModel::fCoinControlFeatures
QString OptionsModel::language
OptionsModel::OptionsModel(QObject *parent=0)
References Init.
void OptionsModel::Init()
References DarkSilkUnits::DRKSLK, nTransactionFee, nReserveBalance, nSandstormRounds, nAnonymizeDarkSilkAmount, SoftSetBoolArg, SoftSetArg, mapArgs, mapMultiArgs, I2P_SAM_HOST_PARAM, I2P_SAM_PORT_PARAM, I2P_SESSION_NAME_PARAM, SAM_NAME_INBOUND_QUANTITY, SAM_DEFAULT_INBOUND_QUANTITY, SAM_NAME_INBOUND_LENGTH, SAM_DEFAULT_INBOUND_LENGTH, SAM_NAME_INBOUND_LENGTHVARIANCE, SAM_DEFAULT_INBOUND_LENGTHVARIANCE, SAM_NAME_INBOUND_BACKUPQUANTITY, SAM_DEFAULT_INBOUND_BACKUPQUANTITY, SAM_NAME_INBOUND_ALLOWZEROHOP, SAM_DEFAULT_INBOUND_ALLOWZEROHOP, SAM_NAME_INBOUND_IPRESTRICTION, SAM_DEFAULT_INBOUND_IPRESTRICTION, SAM_NAME_OUTBOUND_QUANTITY, SAM_DEFAULT_OUTBOUND_QUANTITY, SAM_NAME_OUTBOUND_LENGTH, SAM_DEFAULT_OUTBOUND_LENGTH, SAM_NAME_OUTBOUND_LENGTHVARIANCE, SAM_DEFAULT_OUTBOUND_LENGTHVARIANCE, SAM_NAME_OUTBOUND_BACKUPQUANTITY, SAM_DEFAULT_OUTBOUND_BACKUPQUANTITY, SAM_NAME_OUTBOUND_ALLOWZEROHOP, SAM_DEFAULT_OUTBOUND_ALLOWZEROHOP, SAM_NAME_OUTBOUND_IPRESTRICTION, SAM_DEFAULT_OUTBOUND_IPRESTRICTION, SAM_NAME_OUTBOUND_PRIORITY, SAM_DEFAULT_OUTBOUND_PRIORITY, I2P_SAM_I2P_OPTIONS_PARAM.
Referenced by OptionsModel.
int OptionsModel::rowCount(const QModelIndex &parent=QModelIndex()) const
References OptionIDRowCount.
QVariant OptionsModel::data(const QModelIndex &index, int role=Qt::DisplayRole) const
References StartAtStartup, GUIUtil::GetStartOnSystemStartup, MinimizeToTray, MapPortUPnP, GetBoolArg, MinimizeOnClose, ProxyUse, ProxyIP, GetProxy, NET_IPV4, CNetAddr::ToStringIP, ProxyPort, CService::GetPort, Fee, nTransactionFee, ReserveBalance, nReserveBalance, DisplayUnit, Language, CoinControlFeatures, SandstormRounds, nSandstormRounds, AnonymizeDarkSilkAmount, nAnonymizeDarkSilkAmount, UseBlackTheme, mapArgs, mapMultiArgs, GetArg, I2P_SAM_HOST_PARAM, I2P_SAM_HOST_DEFAULT, I2P_SAM_PORT_PARAM, I2P_SAM_PORT_DEFAULT, I2P_SESSION_NAME_PARAM, I2P_SESSION_NAME_DEFAULT.
bool OptionsModel::setData(const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
References StartAtStartup, GUIUtil::SetStartOnSystemStartup, MinimizeToTray, MapPortUPnP, MapPort, MinimizeOnClose, ProxyUse, ProxyIP, GetProxy, NET_IPV4, CNetAddr::SetIP, CService::ToStringIPPort, ProxyPort, CService::SetPort, Fee, nTransactionFee, transactionFeeChanged, ReserveBalance, nReserveBalance, reserveBalanceChanged, DisplayUnit, displayUnitChanged, Language, CoinControlFeatures, coinControlFeaturesChanged, UseBlackTheme, SandstormRounds, nSandstormRounds, sandstormRoundsChanged, AnonymizeDarkSilkAmount, nAnonymizeDarkSilkAmount, AnonymizeDarkSilkAmountChanged, SAM_NAME_INBOUND_QUANTITY, SAM_NAME_INBOUND_LENGTH, SAM_NAME_INBOUND_LENGTHVARIANCE, SAM_NAME_INBOUND_BACKUPQUANTITY, SAM_NAME_INBOUND_ALLOWZEROHOP, SAM_NAME_INBOUND_IPRESTRICTION, SAM_NAME_OUTBOUND_QUANTITY, SAM_NAME_OUTBOUND_LENGTH, SAM_NAME_OUTBOUND_LENGTHVARIANCE, SAM_NAME_OUTBOUND_BACKUPQUANTITY, SAM_NAME_OUTBOUND_ALLOWZEROHOP, SAM_NAME_OUTBOUND_IPRESTRICTION, SAM_NAME_OUTBOUND_PRIORITY.
qint64 OptionsModel::getTransactionFee()
References nTransactionFee.
qint64 OptionsModel::getReserveBalance()
References nReserveBalance.
bool OptionsModel::getMinimizeToTray()
Referenced by DarkSilkGUI::changeEvent.
bool OptionsModel::getMinimizeOnClose()
Referenced by DarkSilkGUI::closeEvent.
int OptionsModel::getDisplayUnit()
Referenced by CoinControlDialog::updateLabels, DarkSilkGUI::askFee, OverviewPage::setBalance, OverviewPage::updateSandstormProgress, SendCoinsDialog::setBalance, TransactionTableModel::data, TransactionView::changedAmount.
bool OptionsModel::getCoinControlFeatures()
Referenced by SendCoinsDialog::setModel.
QString OptionsModel::getLanguage()
void OptionsModel::displayUnitChanged(int unit)
Referenced by setData.
void OptionsModel::transactionFeeChanged(qint64)
Referenced by setData.
void OptionsModel::reserveBalanceChanged(qint64)
Referenced by setData.
void OptionsModel::coinControlFeaturesChanged(bool)
Referenced by setData.
void OptionsModel::sandstormRoundsChanged(int)
Referenced by setData.
void OptionsModel::AnonymizeDarkSilkAmountChanged(int)
Referenced by setData.