CFinalizedBudget
CCriticalSection CFinalizedBudget::cs
bool CFinalizedBudget::fAutoChecked
bool CFinalizedBudget::fValid
Referenced by CBudgetManager::CheckAndRemove, CBudgetManager::ResetSync, CBudgetManager::MarkSynced, CBudgetManager::Sync, CFinalizedBudget.
std::string CFinalizedBudget::strBudgetName
Referenced by CFinalizedBudget, IsValid, CFinalizedBudgetBroadcast::CFinalizedBudgetBroadcast, CFinalizedBudgetBroadcast::swap.
int CFinalizedBudget::nBlockStart
Referenced by CBudgetManager::CheckAndRemove, CFinalizedBudget, IsValid, CFinalizedBudgetBroadcast::CFinalizedBudgetBroadcast, CFinalizedBudgetBroadcast::swap.
std::vector<CTxBudgetPayment> CFinalizedBudget::vecBudgetPayments
Referenced by CFinalizedBudget, AutoCheck, GetTotalPayout, GetProposals, IsValid, IsTransactionValid, CFinalizedBudgetBroadcast::CFinalizedBudgetBroadcast, CFinalizedBudgetBroadcast::swap.
map<uint256, CFinalizedBudgetVote> CFinalizedBudget::mapVotes
Referenced by snfinalbudget, CBudgetManager::ResetSync, CBudgetManager::MarkSynced, CBudgetManager::Sync, CFinalizedBudget, AddOrUpdateVote, CleanAndRemove, CFinalizedBudgetBroadcast::CFinalizedBudgetBroadcast, CFinalizedBudgetBroadcast::swap.
uint256 CFinalizedBudget::nFeeTXHash
Referenced by snfinalbudget, CFinalizedBudget, IsValid, CFinalizedBudgetBroadcast::CFinalizedBudgetBroadcast, CFinalizedBudgetBroadcast::swap.
int64_t CFinalizedBudget::nTime
Referenced by CFinalizedBudget, AddOrUpdateVote, IsValid, CFinalizedBudgetBroadcast::swap.
CFinalizedBudget::ADD_SERIALIZE_METHODS
CFinalizedBudget::CFinalizedBudget()
References strBudgetName, nBlockStart, vecBudgetPayments, mapVotes, nFeeTXHash, nTime, fValid.
CFinalizedBudget::CFinalizedBudget(const CFinalizedBudget &other)
References strBudgetName, nBlockStart, vecBudgetPayments, mapVotes, nFeeTXHash, nTime, fValid.
void CFinalizedBudget::CleanAndRemove(bool fSignatureCheck)
References mapVotes.
bool CFinalizedBudget::AddOrUpdateVote(CFinalizedBudgetVote &vote, std::string &strError)
References LOCK, hash, CFinalizedBudgetVote::vin, CTxIn::prevout, COutPoint::GetHash, mapVotes, nTime, CFinalizedBudgetVote::nTime, strprintf, CFinalizedBudgetVote::GetHash, base_uint< BITS >::ToString, GetTime.
double CFinalizedBudget::GetScore()
bool CFinalizedBudget::HasMinimumRequiredSupport()
bool CFinalizedBudget::IsValid(std::string &strError, bool fCheckCollateral=true)
References nBlockStart, GetBudgetPaymentCycleBlocks, GetBlockEnd, vecBudgetPayments, strBudgetName, nFeeTXHash, GetTotalPayout, CBudgetManager::GetTotalBudget, IsBudgetCollateralValid, GetHash, nTime, pindexBest.
Referenced by snfinalbudget, CBudgetManager::AddFinalizedBudget, CBudgetManager::CheckAndRemove.
std::string CFinalizedBudget::GetName()
Referenced by snfinalbudget.
std::string CFinalizedBudget::GetProposals()
References LOCK, vecBudgetPayments, CBudgetManager::FindProposal, CTxBudgetPayment::nProposalHash, base_uint< BITS >::ToString, CBudgetProposal::GetName.
Referenced by snfinalbudget.
int CFinalizedBudget::GetBlockStart()
Referenced by snfinalbudget, CBudgetManager::FillBlockPayee, CBudgetManager::IsBudgetPaymentBlock, CBudgetManager::IsTransactionValid, CBudgetManager::GetRequiredPaymentsString, GetStatus, IsTransactionValid.
int CFinalizedBudget::GetBlockEnd()
Referenced by snfinalbudget, CBudgetManager::FillBlockPayee, CBudgetManager::IsBudgetPaymentBlock, CBudgetManager::IsTransactionValid, CBudgetManager::GetRequiredPaymentsString, GetStatus, IsValid.
int CFinalizedBudget::GetVoteCount()
Referenced by snfinalbudget, CBudgetManager::FillBlockPayee, CBudgetManager::IsBudgetPaymentBlock, CBudgetManager::IsTransactionValid, CBudgetManager::GetFinalizedBudgets.
bool CFinalizedBudget::IsTransactionValid(const CTransaction &txNew, int nBlockHeight)
References GetBlockStart, LogPrintf, vecBudgetPayments, CTransaction::vout, CTxOut::scriptPubKey, CTxOut::nValue, ExtractDestination, CBase58Data::ToString.
Referenced by CBudgetManager::IsTransactionValid.
bool CFinalizedBudget::GetBudgetPaymentByBlock(int64_t nBlockHeight, CTxBudgetPayment &payment)
References LOCK.
Referenced by CBudgetManager::GetRequiredPaymentsString, GetStatus.
bool CFinalizedBudget::GetPayeeAndAmount(int64_t nBlockHeight, CScript &payee, CAmount &nAmount)
References LOCK.
Referenced by CBudgetManager::FillBlockPayee.
void CFinalizedBudget::AutoCheck()
References LOCK, pindexBest, LogPrintf, CBlockIndex::nHeight, fStormNode, Params, CChainParams::MAIN, rand, strBudgetMode, CBudgetManager::GetBudget, vecBudgetPayments, GetHash, SubmitVote.
Referenced by CBudgetManager::CheckAndRemove.
CAmount CFinalizedBudget::GetTotalPayout()
References vecBudgetPayments.
Referenced by IsValid.
void CFinalizedBudget::SubmitVote()
References sandStormSigner, CSandStormSigner::SetKey, strStormNodePrivKey, LogPrintf, activeStormnode, CActiveStormnode::vin, GetHash, CFinalizedBudgetVote::Sign, CBudgetManager::UpdateFinalizedBudget, CFinalizedBudgetVote::GetHash, base_uint< BITS >::ToString, CBudgetManager::mapSeenFinalizedBudgetVotes, CFinalizedBudgetVote::Relay.
Referenced by AutoCheck.
std::string CFinalizedBudget::GetStatus()
References GetBlockStart, GetBlockEnd, GetBudgetPaymentByBlock, LogPrintf, CBudgetManager::FindProposal, CTxBudgetPayment::nProposalHash, base_uint< BITS >::ToString, CBudgetProposal::GetPayee, CTxBudgetPayment::payee, CBudgetProposal::GetAmount, CTxBudgetPayment::nAmount.
Referenced by snfinalbudget.
uint256 CFinalizedBudget::GetHash()
References SER_GETHASH, CHashWriter::GetHash.
Referenced by snfinalbudget, CBudgetManager::SubmitFinalBudget, CBudgetManager::AddFinalizedBudget, CBudgetManager::CheckAndRemove, AutoCheck, IsValid, SubmitVote, CFinalizedBudgetBroadcast::Relay.
void CFinalizedBudget::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE, LIMITED_STRING.