CWalletDB
CWalletDB::CWalletDB(const std::string &strFilename, const char *pszMode="r+")
bool CWalletDB::WriteName(const std::string &strAddress, const std::string &strName)
References nWalletDBUpdated.
Referenced by CWallet::SetAddressBookName.
bool CWalletDB::EraseName(const std::string &strAddress)
References nWalletDBUpdated.
Referenced by CWallet::DelAddressBookName.
bool CWalletDB::WriteTx(uint256 hash, const CWalletTx &wtx)
References nWalletDBUpdated.
Referenced by CWalletTx::WriteToDisk.
bool CWalletDB::EraseTx(uint256 hash)
References nWalletDBUpdated.
Referenced by CWallet::EraseFromWallet.
bool CWalletDB::WriteStealthKeyMeta(const CKeyID &keyId, const CStealthKeyMetadata &sxKeyMeta)
References nWalletDBUpdated.
bool CWalletDB::EraseStealthKeyMeta(const CKeyID &keyId)
References nWalletDBUpdated.
bool CWalletDB::WriteStealthAddress(const CStealthAddress &sxAddr)
References nWalletDBUpdated, CStealthAddress::scan_pubkey.
Referenced by CWallet::AddStealthAddress.
bool CWalletDB::ReadStealthAddress(CStealthAddress &sxAddr)
References CStealthAddress::scan_pubkey.
Referenced by CWallet::Lock.
bool CWalletDB::WriteKey(const CPubKey &vchPubKey, const CPrivKey &vchPrivKey, const CKeyMetadata &keyMeta)
References nWalletDBUpdated, CPubKey::size, CPubKey::begin, CPubKey::end, Hash.
Referenced by CWallet::AddKeyPubKey.
bool CWalletDB::WriteCryptedKey(const CPubKey &vchPubKey, const std::vector< unsigned char > &vchCryptedSecret, const CKeyMetadata &keyMeta)
References nWalletDBUpdated.
Referenced by CWallet::AddCryptedKey.
bool CWalletDB::WriteMasterKey(unsigned int nID, const CMasterKey &kMasterKey)
References nWalletDBUpdated.
Referenced by CWallet::ChangeWalletPassphrase.
bool CWalletDB::WriteCScript(const uint160 &hash, const CScript &redeemScript)
References nWalletDBUpdated.
Referenced by CWallet::AddCScript.
bool CWalletDB::WriteWatchOnly(const CScript &script)
References nWalletDBUpdated.
Referenced by CWallet::AddWatchOnly.
bool CWalletDB::EraseWatchOnly(const CScript &script)
References nWalletDBUpdated.
bool CWalletDB::WriteBestBlock(const CBlockLocator &locator)
References nWalletDBUpdated.
Referenced by CWallet::SetBestChain.
bool CWalletDB::ReadBestBlock(CBlockLocator &locator)
Referenced by AppInit2.
bool CWalletDB::WriteOrderPosNext(int64_t nOrderPosNext)
References nWalletDBUpdated.
Referenced by CWallet::IncOrderPosNext.
bool CWalletDB::WriteDefaultKey(const CPubKey &vchPubKey)
References nWalletDBUpdated.
bool CWalletDB::ReadPool(int64_t nPool, CKeyPool &keypool)
Referenced by CWallet::ReserveKeyFromKeyPool, CWallet::GetAllReserveKeys.
bool CWalletDB::WritePool(int64_t nPool, const CKeyPool &keypool)
References nWalletDBUpdated.
Referenced by CWallet::NewKeyPool, CWallet::TopUpKeyPool, CWallet::AddReserveKey.
bool CWalletDB::ErasePool(int64_t nPool)
References nWalletDBUpdated.
Referenced by CWallet::NewKeyPool, CWallet::KeepKey.
bool CWalletDB::WriteMinVersion(int nVersion)
Referenced by CWallet::SetMinVersion.
bool CWalletDB::ReadAccount(const std::string &strAccount, CAccount &account)
References CAccount::SetNull.
Referenced by GetAccountAddress.
bool CWalletDB::WriteAccount(const std::string &strAccount, const CAccount &account)
Referenced by GetAccountAddress.
bool CWalletDB::WriteAccountingEntry(const CAccountingEntry &acentry)
CAmount CWalletDB::GetAccountCreditDebit(const std::string &strAccount)
References CAccountingEntry::nCreditDebit.
Referenced by GetAccountBalance.
void CWalletDB::ListAccountCreditDebit(const std::string &strAccount, std::list< CAccountingEntry > &acentries)
References SER_DISK, CAccountingEntry::strAccount.
Referenced by listaccounts, CWallet::OrderedTxItems.
DBErrors CWalletDB::ReorderTransactions(CWallet *)
References LOCK, CWallet::cs_wallet, CWallet::mapWallet, CWalletTx::nTimeReceived, CAccountingEntry::nTime, CWallet::nOrderPosNext, CWalletTx::nOrderPos, CAccountingEntry::nOrderPos, CTransaction::GetHash, DB_LOAD_FAIL, CAccountingEntry::nEntryNo, DB_LOAD_OK.
DBErrors CWalletDB::LoadWallet(CWallet *pwallet)
References CWallet::vchDefaultKey, DB_LOAD_OK, LOCK, CWallet::cs_wallet, DB_TOO_NEW, CWallet::LoadMinVersion, LogPrintf, DB_CORRUPT, SER_DISK, ReadKeyValue, SoftSetBoolArg, DB_NONCRITICAL_ERROR, CWalletScanState::nFileVersion, CWalletScanState::nKeys, CWalletScanState::nCKeys, CWalletScanState::nKeyMeta, CWallet::nTimeFirstKey, hash, CWalletScanState::vWalletUpgrade, CWallet::mapWallet, CWalletScanState::fIsEncrypted, DB_NEED_REWRITE, CWalletScanState::fAnyUnordered.
Referenced by CWallet::LoadWallet.
CWalletDB::CWalletDB(const CWalletDB &)
void CWalletDB::operator=(const CWalletDB &)
bool CWalletDB::WriteAccountingEntry(const uint64_t nAccEntryNum, const CAccountingEntry &acentry)
bool CWalletDB::Recover(CDBEnv &dbenv, std::string filename, bool fOnlyKeys)
References GetTime, strprintf, CDBEnv::dbenv, LogPrintf, CDBEnv::Salvage, CDBEnv::TxnBegin, SER_DISK, ReadKeyValue.
Referenced by AppInit2, Recover.
bool CWalletDB::Recover(CDBEnv &dbenv, std::string filename)
References Recover.