CTxIndex
CDiskTxPos CTxIndex::pos
Referenced by CheckProofOfStake, CheckKernel, CMerkleTx::SetMerkleBranch, GetTransaction, IsConfirmedInNPrevBlocks, CTransactionPoS::ReadFromDisk, CTransactionPoS::FetchInputs, CTxDB::ReadDiskTx, CTxDB::LoadBlockIndex.
std::vector<CDiskTxPos> CTxIndex::vSpent
Referenced by CTransactionPoS::DisconnectInputs, CTransactionPoS::FetchInputs, CTxDB::LoadBlockIndex, CWallet::ReacceptWalletTransactions, CWallet::FixSpentCoins.
CTxIndex::ADD_SERIALIZE_METHODS
CTxIndex::CTxIndex()
References SetNull.
CTxIndex::CTxIndex(const CDiskTxPos &posIn, unsigned int nOutputs)
void CTxIndex::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References SER_GETHASH, READWRITE.
void CTxIndex::SetNull()
References CDiskTxPos::SetNull.
Referenced by CTxIndex, CTxDB::ReadTxIndex.
bool CTxIndex::IsNull()
References CDiskTxPos::IsNull.
int CTxIndex::GetDepthInMainChain() const
References CBlock::ReadFromDisk, CBlockHeader::GetHash, CBlockIndex::IsInMainChain, CBlockIndex::nHeight.
Referenced by CreateNewBlock.
bool operator==(const CTxIndex &a, const CTxIndex &b)
bool operator!=(const CTxIndex &a, const CTxIndex &b)