leveldb::WriteBatchInternal
int leveldb::WriteBatchInternal::Count(const WriteBatch *batch)
References leveldb::DecodeFixed32.
Referenced by leveldb::DBImpl::Write, leveldb::WriteBatch::Iterate, leveldb::WriteBatch::Put, leveldb::WriteBatch::Delete, leveldb::TEST.
void leveldb::WriteBatchInternal::SetCount(WriteBatch *batch, int n)
References leveldb::EncodeFixed32.
Referenced by leveldb::WriteBatch::Put, leveldb::WriteBatch::Delete.
SequenceNumber leveldb::WriteBatchInternal::Sequence(const WriteBatch *batch)
References leveldb::DecodeFixed64.
Referenced by InsertInto, leveldb::TEST.
void leveldb::WriteBatchInternal::SetSequence(WriteBatch *batch, SequenceNumber seq)
References leveldb::EncodeFixed64.
Referenced by leveldb::DBImpl::Write, leveldb::TEST.
static Slice leveldb::WriteBatchInternal::Contents(const WriteBatch *batch)
Referenced by leveldb::DBImpl::Write, leveldb::TEST.
static size_t leveldb::WriteBatchInternal::ByteSize(const WriteBatch *batch)
void leveldb::WriteBatchInternal::SetContents(WriteBatch *batch, const Slice &contents)
References leveldb::Slice::size, leveldb::Slice::data.
Referenced by leveldb::TEST.
Status leveldb::WriteBatchInternal::InsertInto(const WriteBatch *batch, MemTable *memtable)
References Sequence, leveldb::WriteBatch::Iterate.
Referenced by leveldb::DBImpl::Write, leveldb::TEST.
void leveldb::WriteBatchInternal::Append(WriteBatch *dst, const WriteBatch *src)
Referenced by leveldb::TEST.