CSandstormPool
messages
CCriticalSection CSandstormPool::cs_sandstorm
std::vector<CSandStormEntry> CSandstormPool::entries
CMutableTransaction CSandstormPool::finalTransaction
int64_t CSandstormPool::lastTimeChanged
unsigned int CSandstormPool::state
unsigned int CSandstormPool::entriesCount
unsigned int CSandstormPool::countEntriesAccepted
std::vector<CTxIn> CSandstormPool::lockedCoins
bool CSandstormPool::unitTest
int CSandstormPool::sessionID
int CSandstormPool::sessionUsers
bool CSandstormPool::sessionFoundStormnode
std::vector<CTransaction> CSandstormPool::vecSessionCollateral
CMutableTransaction CSandstormPool::txCollateral
int64_t CSandstormPool::lastNewBlock
std::vector<int64_t> CSandstormPool::sandStormDenominationsSkipped
std::string CSandstormPool::lastMessage
Referenced by OverviewPage::sandStormStatus.
unsigned int CSandstormPool::lastEntryAccepted
Referenced by OverviewPage::sandStormStatus, GetLastEntryAccepted.
int CSandstormPool::cachedLastSuccess
Referenced by OverviewPage::sandStormStatus.
int CSandstormPool::minBlockSpacing
Referenced by OverviewPage::sandStormStatus.
std::string CSandstormPool::strAutoDenomResult
Referenced by OverviewPage::sandStormStatus.
CScript CSandstormPool::collateralPubKey
Referenced by CStormnodeBroadcast::CheckInputsAndAdd.
CStormnode* CSandstormPool::pSubmittedToStormnode
Referenced by CStormnodeMan::ProcessStormnodeConnections.
int CSandstormPool::sessionDenom
Referenced by OverviewPage::sandStormStatus, CWallet::PrepareSandstormDenominate.
int CSandstormPool::cachedNumBlocks
Referenced by OverviewPage::sandStormStatus.
CSandstormPool::CSandstormPool()
References SetNull.
void CSandstormPool::ProcessMessageSandstorm(CNode *pfrom, std::string &strCommand, CDataStream &vRecv)
Process a Sandstorm message using the Sandstorm protocol pfrom strCommand lower case command string; valid values are: Command Description ssa Sandstorm Acceptable ssc Sandstorm Complete ssf Sandstorm Final tx ssi Sandstorm vIn ssq Sandstorm Queue sss Sandstorm Signal Final Tx sssu Sandstorm status update sssub Sandstorm Subscribe To vRecv
References fLiteMode, stormnodeSync, CStormnodeSync::IsBlockchainSynced, CNode::nVersion, LogPrintf, CNode::PushMessage, STORMNODE_REJECTED, fStormNode, snodeman, CStormnodeMan::Find, CActiveStormnode::vin, CStormnode::nLastSsq, CStormnodeMan::CountEnabled, CStormnodeMan::nSsqCount, CNode::addr, CService::ToString, STORMNODE_ACCEPTED, TRY_LOCK, CNetAddr::ToString, state, POOL_STATUS_QUEUE, vecSandstormQueue, CSandstormQueue::vin, CStormnodeMan::size, CStormnode::addr, CStormnode::allowFreeTx, GetTime, CTxOut::nValue, CTransaction::vout, CTxOut::scriptPubKey, CScript::ToString, CScript::IsNormalPaymentScript, CTransaction::vin, CTxIn::ToString, hash, GetTransaction, CTxIn::prevout, COutPoint::hash, COutPoint::n, CTransaction::ToString, LOCK, cs_main, AcceptableInputs, mempool, STORMNODE_RESET, Check, GetState, GetEntriesCount, CompletedTransaction.
void CSandstormPool::InitCollateralAddress()
References SetCollateralAddress, Params.
Referenced by AppInit2.
void CSandstormPool::ClearSkippedDenominations()
bool CSandstormPool::IsDenomSkipped(int64_t denom)
void CSandstormPool::InitDenominations()
References sandStormDenominations.
Referenced by AppInit2.
void CSandstormPool::SetMinBlockSpacing(int minBlockSpacingIn)
Referenced by AppInit2.
bool CSandstormPool::SetCollateralAddress(std::string strAddress)
References CBase58Data::SetString, LogPrintf, GetScriptForDestination, CDarkSilkAddress::Get.
Referenced by InitCollateralAddress.
void CSandstormPool::Reset()
References vecStormnodesUsed.
Referenced by sandstorm.
void CSandstormPool::SetNull()
References state, POOL_STATUS_IDLE, GetTimeMillis.
Referenced by CSandstormPool.
void CSandstormPool::UnlockCoins()
References TRY_LOCK, pwalletMain, CWallet::cs_wallet, MilliSleep, CWallet::UnlockCoin, CTxIn::prevout.
bool CSandstormPool::IsNull() const
References POOL_STATUS_ACCEPTING_ENTRIES.
int CSandstormPool::GetState() const
Referenced by OverviewPage::sandStormStatus, getpoolinfo, ProcessMessageSandstorm, ThreadCheckSandStormPool, UpdateState, CWallet::PrepareSandstormDenominate.
std::string CSandstormPool::GetStatus()
References pindexBest, CBlockIndex::nHeight, stormnodeSync, CStormnodeSync::IsBlockchainSynced, state, POOL_STATUS_IDLE, _, POOL_STATUS_ACCEPTING_ENTRIES, strprintf, POOL_STATUS_SIGNING, POOL_STATUS_TRANSMISSION, POOL_STATUS_FINALIZE_TRANSACTION, POOL_STATUS_ERROR, POOL_STATUS_SUCCESS, POOL_STATUS_QUEUE.
Referenced by sandstorm.
int CSandstormPool::GetEntriesCount() const
Referenced by OverviewPage::sandStormStatus, getpoolinfo, ProcessMessageSandstorm, UpdateState, CWallet::PrepareSandstormDenominate.
int CSandstormPool::GetLastEntryAccepted() const
Get the time the last entry was accepted (time in UTC milliseconds)
References lastEntryAccepted.
Referenced by OverviewPage::sandStormStatus.
int CSandstormPool::GetCountEntriesAccepted() const
Get the count of the accepted entries.
Referenced by getpoolinfo.
void CSandstormPool::UpdateState(unsigned int newState)
References fStormNode, POOL_STATUS_ERROR, POOL_STATUS_SUCCESS, LogPrintf, GetTimeMillis, RelayStatus, GetState, GetEntriesCount, STORMNODE_RESET.
int CSandstormPool::GetMaxPoolTransactions()
Get the maximum number of transactions for the pool.
References Params, CChainParams::PoolMaxTransactions.
Referenced by OverviewPage::sandStormStatus, IsSessionReady.
bool CSandstormPool::IsSessionReady()
Do we have enough users to take entries?
References GetMaxPoolTransactions.
bool CSandstormPool::IsCompatibleWithEntries(std::vector< CTxOut > &vout)
Are these outputs compatible with other client in the pool?
References LogPrintf, CSandStormEntry::vout.
bool CSandstormPool::IsCompatibleWithSession(CAmount nAmount, CTransaction txCollateral, int &errorID)
Is this amount compatible with other client in the pool?
References LogPrintf, rand, GetTimeMillis, CSandstormQueue::nDenom, CSandstormQueue::vin, CActiveStormnode::vin, CSandstormQueue::time, GetTime, CSandstormQueue::Sign, CSandstormQueue::Relay, POOL_STATUS_QUEUE, state, POOL_STATUS_ACCEPTING_ENTRIES.
bool CSandstormPool::DoAutomaticDenominating(bool fDryRun=false)
Passively run Sandstorm in the background according to the configuration in settings (only for QT)
References fEnableSandstorm, fStormNode, state, POOL_STATUS_ERROR, POOL_STATUS_SUCCESS, _, TRY_LOCK, stormnodeSync, CStormnodeSync::IsBlockchainSynced, pwalletMain, CCryptoKeyStore::IsLocked, fSandstormMultiSession, pindexBest, CBlockIndex::nHeight, LogPrintf, snodeman, CStormnodeMan::size, sandStormDenominations, CWallet::HasCollateralInputs, nAnonymizeDarkSilkAmount, CWallet::GetAnonymizedBalance, CWallet::GetAnonymizableBalance, CWallet::SelectCoinsDark, nSandstormRounds, CWallet::GetDenominatedBalance, rand, POOL_STATUS_ACCEPTING_ENTRIES, CWallet::CreateCollateralTransaction, CStormnodeMan::CountEnabled, vecStormnodesUsed, nLiquidityProvider, vecSandstormQueue, CSandstormQueue::time, CSandstormQueue::GetAddress, CSandstormQueue::IsExpired, CSandstormQueue::GetProtocolVersion, CSandstormQueue::nDenom, CSandstormQueue::vin, CWallet::SelectCoinsByDenominations, ConnectNode, CStormnodeMan::Find, CTxIn::ToString, CNode::PushMessage, CNode::addr, CService::ToString, CStormnodeMan::FindRandomNotInVec, CStormnode::nLastSsq, CStormnodeMan::nSsqCount, GetTimeMillis, CStormnode::addr, CStormnode::vin, CWallet::ConvertList.
Referenced by sandstorm, ThreadCheckSandStormPool.
bool CSandstormPool::PrepareSandstormDenominate()
References nSandstormRounds, pwalletMain, CWallet::PrepareSandstormDenominate, LogPrintf.
void CSandstormPool::Check()
Check for process in Sandstorm.
References fStormNode, state, POOL_STATUS_ACCEPTING_ENTRIES, POOL_STATUS_FINALIZE_TRANSACTION, POOL_STATUS_SIGNING, CMutableTransaction::vout, CMutableTransaction::vin, CMutableTransaction::ToString, POOL_STATUS_TRANSMISSION, POOL_STATUS_ERROR, POOL_STATUS_SUCCESS, GetTimeMillis, STORMNODE_RESET.
Referenced by OverviewPage::sandStormStatus, ProcessMessageSandstorm.
void CSandstormPool::CheckFinalTransaction()
References fStormNode, pwalletMain, LOCK2, cs_main, CWallet::cs_wallet, CTransaction::ToString, CMerkleTx::AcceptToMemoryPool, LogPrintf, POOL_STATUS_ACCEPTING_ENTRIES, GetAdjustedTime, CTransaction::GetHash, base_uint< BITS >::ToString, CSandStormSigner::SetKey, strStormNodePrivKey, CSandStormSigner::SignMessage, CSandStormSigner::VerifyMessage, mapSandstormBroadcastTxes, CSandstormBroadcastTx::tx, CSandstormBroadcastTx::vin, CActiveStormnode::vin, CSandstormBroadcastTx::vchSig, CSandstormBroadcastTx::sigTime, MSG_SSTX, RelayInv, STORMNODE_RESET.
void CSandstormPool::ChargeFees()
Charge fees to bad actors (Charge clients a fee if they're abusive)
References fStormNode, rand, state, POOL_STATUS_ACCEPTING_ENTRIES, CSandStormEntry::collateral, LogPrintf, POOL_STATUS_SIGNING, CSandStormEntry::sev, CTxSSIn::fHasSig, Params, pwalletMain, CMerkleTx::AcceptToMemoryPool, CWalletTx::RelayWalletTransaction.
void CSandstormPool::ChargeRandomFees()
Rarely charge fees to pay miners.
References fStormNode, rand, LogPrintf, pwalletMain, CMerkleTx::AcceptToMemoryPool, CWalletTx::RelayWalletTransaction.
void CSandstormPool::CheckTimeout()
References fEnableSandstorm, fStormNode, state, POOL_STATUS_TRANSMISSION, POOL_STATUS_ERROR, POOL_STATUS_SUCCESS, vecSandstormQueue, POOL_STATUS_ACCEPTING_ENTRIES, POOL_STATUS_QUEUE, STORMNODE_RESET, GetTimeMillis, SANDSTORM_QUEUE_TIMEOUT, _, POOL_STATUS_SIGNING, SANDSTORM_SIGNING_TIMEOUT.
Referenced by NewBlock, ThreadCheckSandStormPool.
void CSandstormPool::CheckForCompleteQueue()
References fEnableSandstorm, fStormNode, state, POOL_STATUS_QUEUE, POOL_STATUS_ACCEPTING_ENTRIES, CSandstormQueue::nDenom, CSandstormQueue::vin, CActiveStormnode::vin, CSandstormQueue::time, GetTime, CSandstormQueue::ready, CSandstormQueue::Sign, CSandstormQueue::Relay.
Referenced by ThreadCheckSandStormPool.
bool CSandstormPool::SignatureValid(const CScript &newSig, const CTxIn &newVin)
Check to make sure a signature matches an input in the pool.
References CMutableTransaction::vin, CMutableTransaction::vout, CSandStormEntry::vout, CSandStormEntry::sev, CTxIn::prevPubKey, CScript::ToString, VerifyScript, SCRIPT_VERIFY_P2SH, SCRIPT_VERIFY_STRICTENC.
bool CSandstormPool::IsCollateralValid(const CTransaction &txCollateral)
If the collateral is valid given by a client.
References CTransaction::vout, CTransaction::nLockTime, CTxOut::nValue, CTxOut::scriptPubKey, CScript::IsNormalPaymentScript, LogPrintf, CTransaction::ToString, CTransaction::vin, hash, GetTransaction, CTxIn::prevout, COutPoint::hash, COutPoint::n, LOCK, cs_main, state.
bool CSandstormPool::AddEntry(const std::vector< CTxIn > &newInput, const CAmount &nAmount, const CTransaction &txCollateral, const std::vector< CTxOut > &newOutput, int &errorID)
Add a clients entry to the pool.
References fStormNode, CTxIn::prevout, COutPoint::IsNull, CTxIn::ToString, CSandStormEntry::sev, CSandStormEntry::Add.
bool CSandstormPool::AddScriptSig(const CTxIn &newVin)
Add signature to a vin.
References CTxIn::scriptSig, CScript::ToString, CSandStormEntry::sev, CTxIn::ToString, CTxIn::prevout, CTxIn::nSequence, CTxIn::prevPubKey, LogPrintf.
bool CSandstormPool::SignaturesComplete()
Check that all inputs are signed. (Are all inputs signed?)
References CSandStormEntry::sev, CTxSSIn::fHasSig.
void CSandstormPool::SendSandstormDenominate(std::vector< CTxIn > &vin, std::vector< CTxOut > &vout, CAmount amount)
As a client, send a transaction to a Stormnode to start the denomination process.
References fStormNode, LogPrintf, CheckDiskSpace, fEnableSandstorm, POOL_STATUS_ACCEPTING_ENTRIES, state, CTxOut::nValue, CTransaction::vout, CTransaction::vin, CTxIn::ToString, CTransaction::ToString, TRY_LOCK, cs_main, MilliSleep, AcceptableInputs, mempool, CSandStormEntry::Add.
Referenced by CWallet::PrepareSandstormDenominate.
bool CSandstormPool::StatusUpdate(int newState, int newEntriesCount, int newAccepted, int &errorID, int newSessionID=0)
Get Stormnode updates about the progress of Sandstorm.
References fStormNode, state, POOL_STATUS_ERROR, POOL_STATUS_SUCCESS, _, LogPrintf, POOL_STATUS_ACCEPTING_ENTRIES, POOL_STATUS_QUEUE.
bool CSandstormPool::SignFinalTransaction(CTransaction &finalTransactionNew, CNode *node)
As a client, check and sign the final transaction.
References fStormNode, LogPrintf, CSandStormEntry::sev, CTxIn::prevPubKey, CSandStormEntry::vout, CTxOut::nValue, pwalletMain, SignSignature, SIGHASH_ALL, SIGHASH_ANYONECANPAY, CNode::PushMessage.
bool CSandstormPool::GetLastValidBlockHash(uint256 &hash, int mod=1, int nBlockHeight=0)
Get the last valid block hash for a given modulus.
void CSandstormPool::NewBlock()
Process a new block.
References GetTime, CheckTimeout.
void CSandstormPool::CompletedTransaction(bool error, int errorID)
References fStormNode, LogPrintf, POOL_STATUS_ERROR, POOL_STATUS_SUCCESS, pindexBest, CBlockIndex::nHeight.
Referenced by ProcessMessageSandstorm.
void CSandstormPool::ClearLastMessage()
bool CSandstormPool::MakeCollateralAmounts()
Split up large inputs or make fee sized inputs.
References pwalletMain, CReserveKey::GetReservedKey, GetScriptForDestination, CPubKey::GetID, CWallet::CreateTransaction, ALL_COINS, LogPrintf, CReserveKey::ReturnKey, CReserveKey::KeepKey, CTransaction::GetHash, base_uint< BITS >::GetHex, CWallet::CommitTransaction, pindexBest, CBlockIndex::nHeight.
bool CSandstormPool::CreateDenominated(CAmount nTotalValue)
References pwalletMain, CReserveKey::GetReservedKey, GetScriptForDestination, CPubKey::GetID, CWallet::HasCollateralInputs, sandStormDenominations, CWallet::CountInputsWithAmount, strprintf, _, LogPrintf, CReserveKey::KeepKey, CWallet::CreateTransaction, ALL_COINS, CReserveKey::ReturnKey, CWallet::CommitTransaction, pindexBest, CBlockIndex::nHeight, CTransaction::GetHash, base_uint< BITS >::GetHex.
int CSandstormPool::GetDenominations(const std::vector< CTxOut > &vout, bool fSingleRandomDenom=false)
Get the denominations for a list of outputs (returns a bitshifted integer)
References sandStormDenominations, PAIRTYPE, CTxOut::nValue, rand.
Referenced by CWallet::PrepareSandstormDenominate.
int CSandstormPool::GetDenominations(const std::vector< CTxSSOut > &vout)
void CSandstormPool::GetDenominationsToString(int nDenom, std::string &strDenom)
Referenced by OverviewPage::sandStormStatus.
int CSandstormPool::GetDenominationsByAmount(CAmount nAmount, int nDenomTarget=0)
Get the denominations for a specific amount of dash.
References sandStormDenominations, LogPrintf.
int CSandstormPool::GetDenominationsByAmounts(std::vector< CAmount > &vecAmount)
std::string CSandstormPool::GetMessageByID(int messageID)
References _.
void CSandstormPool::RelayFinalTransaction(const int sessionID, const CTransaction &txNew)
References LOCK, cs_vNodes, vNodes, CNode::PushMessage.
void CSandstormPool::RelaySignaturesAnon(std::vector< CTxIn > &vin)
void CSandstormPool::RelayInAnon(std::vector< CTxIn > &vin, std::vector< CTxOut > &vout)
void CSandstormPool::RelayIn(const std::vector< CTxSSIn > &vin, const CAmount &nAmount, const CTransaction &txCollateral, const std::vector< CTxSSOut > &vout)
References FindNode, LogPrintf, CNode::addr, CService::ToString, CNode::PushMessage.
void CSandstormPool::RelayStatus(const int sessionID, const int newState, const int newEntriesCount, const int newAccepted, const int errorID=MSG_NOERR)
References LOCK, cs_vNodes, vNodes, CNode::PushMessage.
Referenced by UpdateState.
void CSandstormPool::RelayCompletedTransaction(const int sessionID, const bool error, const int errorID)
References LOCK, cs_vNodes, vNodes, CNode::PushMessage.