CChainParams
Network
Base58Type
uint256 CChainParams::hashGenesisBlock
MessageStartChars CChainParams::pchMessageStart
vector<unsigned char> CChainParams::vAlertPubKey
int CChainParams::nDefaultPort
int CChainParams::nRPCPort
CBigNum CChainParams::bnProofOfWorkLimit
int CChainParams::nSubsidyHalvingInterval
string CChainParams::strDataDir
vector<CDNSSeedData> CChainParams::vSeeds
std::vector<unsigned char> CChainParams::base58Prefixes[MAX_BASE58_TYPES][MAX_BASE58_TYPES]
std::string CChainParams::strStormnodePaymentsPubKey
int64_t CChainParams::nStartStormnodePayments
int CChainParams::nFirstPOSBlock
int CChainParams::nPoolMaxTransactions
std::string CChainParams::strSandstormPoolDummyAddress
const uint256& CChainParams::HashGenesisBlock() const
Referenced by CBlockLocator::GetBlockHash, CBlock::SetBestChain.
const MessageStartChars& CChainParams::MessageStart() const
const vector<unsigned char>& CChainParams::AlertKey() const
int CChainParams::GetDefaultPort() const
Referenced by ThreadOpenConnections, ThreadOpenAddedConnections, getaddednodeinfo.
const CBigNum& CChainParams::ProofOfWorkLimit() const
Referenced by GetNextTargetRequired.
int CChainParams::SubsidyHalvingInterval() const
virtual const CBlock& CChainParams::GenesisBlock() const =0
Referenced by LoadBlockIndex, DarkSilkGUI::setNumBlocks.
virtual bool CChainParams::RequireRPCPassword() const
const string& CChainParams::DataDir() const
Referenced by GetDataDir.
virtual Network CChainParams::NetworkID() const =0
Referenced by CActiveStormnode::ManageStatus, TestNet, CStormnodePayments::ProcessMessageStormnodePayments, CStormnodeMan::ProcessMessage, GetDataDir.
const vector<CDNSSeedData>& CChainParams::DNSSeeds() const
Referenced by ThreadDNSAddressSeed.
const std::vector<unsigned char>& CChainParams::Base58Prefix(Base58Type type) const
Referenced by CDarkSilkAddress::IsValid, CDarkSilkAddress::IsScript, CDarkSilkSecret::IsValid.
virtual const vector<CAddress>& CChainParams::FixedSeeds() const =0
int CChainParams::RPCPort() const
int CChainParams::FirstPOSBlock() const
Referenced by CBlock::AcceptBlock.
std::string CChainParams::StormnodePaymentPubKey() const
int64_t CChainParams::StartStormnodePayments() const
int CChainParams::PoolMaxTransactions() const
Referenced by CSandstormPool::GetMaxPoolTransactions.
std::string CChainParams::SandstormPoolDummyAddress() const
CChainParams::CChainParams()