leveldb::TableCache
Env* const leveldb::TableCache::env_
const std::string leveldb::TableCache::dbname_
const Options* leveldb::TableCache::options_
Cache* leveldb::TableCache::cache_
leveldb::TableCache::TableCache(const std::string &dbname, const Options *options, int entries)
leveldb::TableCache::~TableCache()
Iterator * leveldb::TableCache::NewIterator(const ReadOptions &options, uint64_t file_number, uint64_t file_size, Table **tableptr=NULL)
References leveldb::Status::ok, leveldb::NewErrorIterator, leveldb::Cache::Value, leveldb::Table::NewIterator, leveldb::Iterator::RegisterCleanup.
Referenced by leveldb::BuildTable, leveldb::Version::AddIterators, leveldb::VersionSet::ApproximateOffsetOf, leveldb::VersionSet::MakeInputIterator.
Status leveldb::TableCache::Get(const ReadOptions &options, uint64_t file_number, uint64_t file_size, const Slice &k, void *arg, void(*handle_result)(void *, const Slice &, const Slice &))
References leveldb::Status::ok, leveldb::Cache::Value, leveldb::Cache::Release.
Referenced by leveldb::Version::Get.
void leveldb::TableCache::Evict(uint64_t file_number)
References leveldb::EncodeFixed64, leveldb::Cache::Erase.
Status leveldb::TableCache::FindTable(uint64_t file_number, uint64_t file_size, Cache::Handle **)