leveldb::SkipList::Iterator
const SkipList* leveldb::SkipList< Key, Comparator >::Iterator::list_
Node* leveldb::SkipList< Key, Comparator >::Iterator::node_
leveldb::SkipList< Key, Comparator >::Iterator::Iterator(const SkipList *list)
bool leveldb::SkipList< Key, Comparator >::Iterator::Valid() const
Referenced by leveldb::TEST, leveldb::ConcurrentTest::ReadStep.
const Key & leveldb::SkipList< Key, Comparator >::Iterator::key() const
Referenced by leveldb::TEST, leveldb::ConcurrentTest::ReadStep.
void leveldb::SkipList< Key, Comparator >::Iterator::Next()
Referenced by leveldb::TEST, leveldb::ConcurrentTest::ReadStep.
void leveldb::SkipList< Key, Comparator >::Iterator::Prev()
References list_.
Referenced by leveldb::TEST.
void leveldb::SkipList< Key, Comparator >::Iterator::Seek(const Key &target)
References list_.
Referenced by leveldb::TEST, leveldb::ConcurrentTest::ReadStep.
void leveldb::SkipList< Key, Comparator >::Iterator::SeekToFirst()
References list_.
Referenced by leveldb::TEST.
void leveldb::SkipList< Key, Comparator >::Iterator::SeekToLast()
References list_.
Referenced by leveldb::TEST.