CInv
CInv::ADD_SERIALIZE_METHODS
int CInv::type
Referenced by SendMessages, CInv, operator<, IsKnownType, GetCommand, SerializationOp.
uint256 CInv::hash
Referenced by SendMessages, CInv, operator<, ToString, SerializationOp.
CInv::CInv()
References type, hash.
CInv::CInv(int typeIn, const uint256 &hashIn)
References type, hash.
CInv::CInv(const std::string &strType, const uint256 &hashIn)
References ARRAYLEN, type, strprintf, hash.
void CInv::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE, type, hash.
bool CInv::IsKnownType() const
References type, ARRAYLEN.
Referenced by GetCommand.
const char * CInv::GetCommand() const
References IsKnownType, strprintf, type.
Referenced by ToString.
std::string CInv::ToString() const
References strprintf, GetCommand, hash, base_uint< BITS >::ToString.
Referenced by SendMessages, CNode::AskFor, print.
void CInv::print() const
References LogPrintf, ToString.
bool operator<(const CInv &a, const CInv &b)