CBudgetVote
bool CBudgetVote::fValid
Referenced by CBudgetManager::ProcessMessage, CBudgetVote.
bool CBudgetVote::fSynced
Referenced by CBudgetVote.
CTxIn CBudgetVote::vin
Referenced by CBudgetProposal::AddOrUpdateVote, CBudgetVote, Sign, SignatureValid.
uint256 CBudgetVote::nProposalHash
Referenced by CBudgetManager::UpdateProposal, CBudgetVote, Sign, SignatureValid.
int CBudgetVote::nVote
Referenced by CBudgetVote, Sign, SignatureValid.
int64_t CBudgetVote::nTime
Referenced by snbudgetvoteraw, CBudgetProposal::AddOrUpdateVote, CBudgetVote, Sign, SignatureValid.
std::vector<unsigned char> CBudgetVote::vchSig
Referenced by snbudgetvoteraw, Sign, SignatureValid.
CBudgetVote::ADD_SERIALIZE_METHODS
CBudgetVote::CBudgetVote()
References vin, nProposalHash, nVote, nTime, fValid, fSynced.
CBudgetVote::CBudgetVote(CTxIn vin, uint256 nProposalHash, int nVoteIn)
References vin, nProposalHash, nVote, nTime, GetAdjustedTime, fValid, fSynced.
bool CBudgetVote::Sign(CKey &keyStormnode, CPubKey &pubKeyStormnode)
References vin, CTxIn::prevout, COutPoint::ToStringShort, nProposalHash, base_uint< BITS >::ToString, nVote, nTime, sandStormSigner, CSandStormSigner::SignMessage, vchSig, LogPrintf, CSandStormSigner::VerifyMessage.
Referenced by snbudget.
bool CBudgetVote::SignatureValid(bool fSignatureCheck)
References vin, CTxIn::prevout, COutPoint::ToStringShort, nProposalHash, base_uint< BITS >::ToString, nVote, nTime, snodeman, CStormnodeMan::Find, LogPrintf, CTxIn::ToString, sandStormSigner, CSandStormSigner::VerifyMessage, CStormnode::pubkey2, vchSig.
Referenced by snbudgetvoteraw.
void CBudgetVote::Relay()
References MSG_BUDGET_VOTE, GetHash, RelayInv.
Referenced by snbudget, snbudgetvoteraw.
std::string CBudgetVote::GetVoteString()
uint256 CBudgetVote::GetHash()
References SER_GETHASH, CHashWriter::GetHash.
Referenced by snbudget, snbudgetvoteraw, CBudgetProposal::AddOrUpdateVote, Relay.
void CBudgetVote::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE.