CMerkleTx
uint256 CMerkleTx::hashBlock
Referenced by TransactionRecord::updateStatus, WalletTxToJSON, CWallet::AddToWallet, CWallet::GetKeyBirthTimes.
std::vector<uint256> CMerkleTx::vMerkleBranch
Referenced by CWallet::AddToWallet.
int CMerkleTx::nIndex
Referenced by WalletTxToJSON, CWallet::AddToWallet.
bool CMerkleTx::fMerkleVerified
CMerkleTx::ADD_SERIALIZE_METHODS
int CMerkleTx::GetDepthInMainChainINTERNAL(CBlockIndex *&pindexRet) const
CMerkleTx::CMerkleTx()
References Init.
CMerkleTx::CMerkleTx(const CTransaction &txIn)
References Init.
void CMerkleTx::Init()
Referenced by CMerkleTx, CWalletTx::CWalletTx.
void CMerkleTx::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE, CTransaction::nVersion.
int CMerkleTx::SetMerkleBranch(const CBlock *pblock=NULL)
References AssertLockHeld, CBlock::ReadFromDisk, CTxIndex::pos, CDiskTxPos::nFile, CDiskTxPos::nBlockPos, CBlockHeader::GetHash, CBlock::vtx, LogPrintf, CBlock::GetMerkleBranch, CBlockIndex::IsInMainChain, CBlockIndex::nHeight.
Referenced by CWallet::AddToWalletIfInvolvingMe, CWalletTx::AddSupportingTransactions.
int CMerkleTx::GetDepthInMainChain(CBlockIndex *&pindexRet, bool enableIX=true) const
References AssertLockHeld, mempool, CTxMemPool::exists, INSTANTX_SIGNATURES_REQUIRED, nInstantXDepth.
Referenced by TransactionRecord::updateStatus, WalletTxToJSON, getreceivedbyaddress, getreceivedbyaccount, GetAccountBalance, getbalance, ListReceived, ListTransactions, listaccounts, listsinceblock, CWallet::ReacceptWalletTransactions, CWallet::GetAnonymizedBalance, CWallet::GetAverageAnonymizedRounds, CWallet::GetNormalizedAnonymizedBalance, CWallet::GetDenominatedBalance, CWallet::GetUnconfirmedBalance, CWallet::GetWatchOnlyStake, CWallet::GetUnconfirmedWatchOnlyBalance, CWallet::AvailableCoins, CWallet::AvailableCoinsForStaking, CWallet::GetStake, CWallet::GetNewMint, CWallet::CountInputsWithAmount, CWallet::GetAddressBalances, CWalletTx::GetDenominatedCredit, CWalletTx::IsTrusted.
int CMerkleTx::GetDepthInMainChain(bool enableIX=true) const
References GetDepthInMainChain.
Referenced by GetDepthInMainChain.
bool CMerkleTx::IsInMainChain() const
Referenced by TransactionDesc::toHTML, TransactionRecord::showTransaction, TransactionRecord::updateStatus, CWalletTx::GetImmatureCredit, CWalletTx::GetImmatureWatchOnlyCredit.
int CMerkleTx::GetBlocksToMaturity() const
Referenced by TransactionDesc::toHTML, TransactionRecord::updateStatus, GetAccountBalance, getbalance, ListTransactions, listaccounts, CWallet::GetAnonymizableBalance, CWallet::GetWatchOnlyStake, CWallet::AvailableCoins, CWallet::AvailableCoinsForStaking, CWallet::GetStake, CWallet::GetNewMint, CWallet::GetAddressBalances, CWalletTx::GetCredit, CWalletTx::GetImmatureCredit, CWalletTx::GetAvailableCredit, CWalletTx::GetAnonymizableCredit, CWalletTx::GetDenominatedCredit, CWalletTx::GetImmatureWatchOnlyCredit, CWalletTx::GetAvailableWatchOnlyCredit.
bool CMerkleTx::AcceptToMemoryPool(bool fLimitFree=true, bool fRejectInsaneFee=true, bool ignoreFees=false)
References state, AcceptToMemoryPool, mempool.
Referenced by CWalletTx::AcceptWalletTransaction, CSandstormPool::CheckFinalTransaction, CSandstormPool::ChargeFees, CSandstormPool::ChargeRandomFees, CWallet::ReacceptWalletTransactions, CWallet::CommitTransaction.
int CMerkleTx::GetTransactionLockSignatures() const
References IsSporkActive, fEnableInstantX, mapTxLocks.
bool CMerkleTx::IsTransactionLockTimedOut() const
References fEnableInstantX, mapTxLocks, GetTime.