leveldb::Version
friend class Compaction
friend class VersionSet
VersionSet* leveldb::Version::vset_
Version* leveldb::Version::next_
Version* leveldb::Version::prev_
int leveldb::Version::refs_
std::vector<FileMetaData*> leveldb::Version::files_[config::kNumLevels][config::kNumLevels]
FileMetaData* leveldb::Version::file_to_compact_
int leveldb::Version::file_to_compact_level_
double leveldb::Version::compaction_score_
int leveldb::Version::compaction_level_
void leveldb::Version::AddIterators(const ReadOptions &, std::vector< Iterator * > *iters)
References leveldb::TableCache::NewIterator.
Status leveldb::Version::Get(const ReadOptions &, const LookupKey &key, std::string *val, GetStats *stats)
References leveldb::LookupKey::internal_key, leveldb::LookupKey::user_key, leveldb::InternalKeyComparator::user_comparator, leveldb::Version::GetStats::seek_file, leveldb::Version::GetStats::seek_file_level, leveldb::Comparator::Compare, leveldb::FileMetaData::smallest, leveldb::InternalKey::user_key, leveldb::FileMetaData::largest, leveldb::FindFile, ucmp, user_key, value, leveldb::TableCache::Get, leveldb::FileMetaData::number, leveldb::FileMetaData::file_size, leveldb::Status::ok, leveldb::Status::NotFound, leveldb::Status::Corruption.
Referenced by leveldb::DBImpl::Get.
bool leveldb::Version::UpdateStats(const GetStats &stats)
References leveldb::Version::GetStats::seek_file, leveldb::FileMetaData::allowed_seeks, leveldb::Version::GetStats::seek_file_level.
Referenced by leveldb::DBImpl::Get, RecordReadSample.
bool leveldb::Version::RecordReadSample(Slice key)
References leveldb::ParseInternalKey, stats, state, arg, leveldb::ParsedInternalKey::user_key, UpdateStats.
Referenced by leveldb::DBImpl::RecordReadSample.
void leveldb::Version::Ref()
Referenced by leveldb::DBImpl::Get, leveldb::DBImpl::GetApproximateSizes, leveldb::VersionSet::Builder::Builder, leveldb::VersionSet::PickCompaction, leveldb::VersionSet::CompactRange.
void leveldb::Version::Unref()
Referenced by leveldb::DBImpl::Get, leveldb::DBImpl::GetApproximateSizes, leveldb::VersionSet::Builder::~Builder, leveldb::VersionSet::~VersionSet, leveldb::Compaction::~Compaction, leveldb::Compaction::ReleaseInputs.
void leveldb::Version::GetOverlappingInputs(int level, const InternalKey *begin, const InternalKey *end, std::vector< FileMetaData * > *inputs)
References leveldb::InternalKey::user_key, leveldb::InternalKeyComparator::user_comparator, leveldb::FileMetaData::smallest, leveldb::FileMetaData::largest, leveldb::Comparator::Compare, leveldb::Slice::clear.
Referenced by PickLevelForMemTableOutput, leveldb::VersionSet::MaxNextLevelOverlappingBytes, leveldb::VersionSet::PickCompaction, leveldb::VersionSet::CompactRange.
bool leveldb::Version::OverlapInLevel(int level, const Slice *smallest_user_key, const Slice *largest_user_key)
References leveldb::SomeFileOverlapsRange.
Referenced by leveldb::DBImpl::CompactRange, PickLevelForMemTableOutput.
int leveldb::Version::PickLevelForMemTableOutput(const Slice &smallest_user_key, const Slice &largest_user_key)
References OverlapInLevel, start, GetOverlappingInputs.
int leveldb::Version::NumFiles(int level) const
std::string leveldb::Version::DebugString() const
References leveldb::AppendNumberTo.
Referenced by leveldb::DBImpl::GetProperty.
Iterator * leveldb::Version::NewConcatenatingIterator(const ReadOptions &, int level) const
void leveldb::Version::ForEachOverlapping(Slice user_key, Slice internal_key, void *arg, bool(*func)(void *, int, FileMetaData *))
leveldb::Version::Version(VersionSet *vset)
leveldb::Version::~Version()
leveldb::Version::Version(const Version &)
void leveldb::Version::operator=(const Version &)