SSLIOStreamDevice
bool SSLIOStreamDevice< Protocol >::fNeedHandshake
bool SSLIOStreamDevice< Protocol >::fUseSSL
boost::asio::ssl::stream<typename Protocol::socket>& SSLIOStreamDevice< Protocol >::stream
SSLIOStreamDevice< Protocol >::SSLIOStreamDevice(boost::asio::ssl::stream< typename Protocol::socket > &streamIn, bool fUseSSLIn)
void SSLIOStreamDevice< Protocol >::handshake(boost::asio::ssl::stream_base::handshake_type role)
Referenced by SSLIOStreamDevice< Protocol >::read, SSLIOStreamDevice< Protocol >::write.
std::streamsize SSLIOStreamDevice< Protocol >::read(char *s, std::streamsize n)
References SSLIOStreamDevice< Protocol >::handshake.
std::streamsize SSLIOStreamDevice< Protocol >::write(const char *s, std::streamsize n)
References SSLIOStreamDevice< Protocol >::handshake, json_spirit::write.
bool SSLIOStreamDevice< Protocol >::connect(const std::string &server, const std::string &port)
Referenced by CallRPC.