CCrypter
unsigned char CCrypter::chKey[WALLET_CRYPTO_KEY_SIZE][WALLET_CRYPTO_KEY_SIZE]
unsigned char CCrypter::chIV[WALLET_CRYPTO_KEY_SIZE][WALLET_CRYPTO_KEY_SIZE]
bool CCrypter::fKeySet
bool CCrypter::SetKeyFromPassphrase(const SecureString &strKeyData, const std::vector< unsigned char > &chSalt, const unsigned int nRounds, const unsigned int nDerivationMethod)
References WALLET_CRYPTO_SALT_SIZE, scrypt_salted_multiround_hash, memory_cleanse, WALLET_CRYPTO_KEY_SIZE.
Referenced by CWallet::Unlock, CWallet::ChangeWalletPassphrase, CWallet::EncryptWallet.
bool CCrypter::Encrypt(const CKeyingMaterial &vchPlaintext, std::vector< unsigned char > &vchCiphertext)
Referenced by EncryptSecret, CWallet::ChangeWalletPassphrase, CWallet::EncryptWallet.
bool CCrypter::Decrypt(const std::vector< unsigned char > &vchCiphertext, CKeyingMaterial &vchPlaintext)
Referenced by DecryptSecret, CWallet::Unlock, CWallet::ChangeWalletPassphrase.
bool CCrypter::SetKey(const CKeyingMaterial &chNewKey, const std::vector< unsigned char > &chNewIV)
References WALLET_CRYPTO_KEY_SIZE.
Referenced by EncryptSecret, DecryptSecret.
void CCrypter::CleanKey()
Referenced by ~CCrypter.
CCrypter::CCrypter()
References LockedPageManager::instance, LockedPageManagerBase< Locker >::LockRange.
CCrypter::~CCrypter()
References CleanKey, LockedPageManager::instance, LockedPageManagerBase< Locker >::UnlockRange.