CStormnodeConfig
std::vector<CStormnodeEntry> CStormnodeConfig::entries
CStormnodeConfig::CStormnodeConfig()
void CStormnodeConfig::clear()
bool CStormnodeConfig::read(std::string &strErr)
References GetStormnodeConfigFile, CDarkSilkAddress::IsValid, add.
void CStormnodeConfig::add(std::string alias, std::string ip, std::string privKey, std::string txHash, std::string outputIndex, std::string donationAddress, std::string donationPercent)
Referenced by read.
std::vector<CStormnodeEntry>& CStormnodeConfig::getEntries()
Referenced by CActiveStormnode::SelectCoinsStormnode, AppInit2, StormnodeManager::on_UpdateButton_clicked, snbudget, snfinalbudget, stormnode.