CSVModelWriter
QString CSVModelWriter::filename
const QAbstractItemModel* CSVModelWriter::model
QList<Column> CSVModelWriter::columns
CSVModelWriter::CSVModelWriter(const QString &filename, QObject *parent=0)
void CSVModelWriter::setModel(const QAbstractItemModel *model)
Referenced by AddressBookPage::exportClicked, MessagePage::exportClicked, TransactionView::exportClicked.
void CSVModelWriter::addColumn(const QString &title, int column, int role=Qt::EditRole)
Referenced by AddressBookPage::exportClicked, MessagePage::exportClicked, TransactionView::exportClicked.
bool CSVModelWriter::write()
Perform export of the model to CSV. true on success, false otherwise
Referenced by AddressBookPage::exportClicked, MessagePage::exportClicked, TransactionView::exportClicked.