AskPassphraseDialog
Mode
Ask passphrase twice and encrypt
Ui::AskPassphraseDialog* AskPassphraseDialog::ui
Mode AskPassphraseDialog::mode
WalletModel* AskPassphraseDialog::model
bool AskPassphraseDialog::fCapsLock
AskPassphraseDialog::AskPassphraseDialog(Mode mode, QWidget *parent=0)
References fWalletUnlockStakingOnly, Encrypt, UnlockStaking, Unlock, Decrypt, ChangePass.
AskPassphraseDialog::~AskPassphraseDialog()
References secureClearPassFields.
void AskPassphraseDialog::accept()
References secureClearPassFields, Encrypt, WalletModel::setWalletEncrypted, UnlockStaking, Unlock, WalletModel::setWalletLocked, fWalletUnlockStakingOnly, Decrypt, ChangePass, WalletModel::changePassphrase.
void AskPassphraseDialog::setModel(WalletModel *model)
void AskPassphraseDialog::textChanged()
bool AskPassphraseDialog::event(QEvent *event)
Referenced by eventFilter.
bool AskPassphraseDialog::eventFilter(QObject *, QEvent *event)
References event.
void AskPassphraseDialog::secureClearPassFields()
Referenced by ~AskPassphraseDialog, accept.