CSandStormSigner
bool CSandStormSigner::IsVinAssociatedWithPubkey(CTxIn &vin, CPubKey &pubkey)
Is the inputs associated with this public key? (and there is 1000 DASH - checking if valid stormnode)
References GetScriptForDestination, CPubKey::GetID, hash, GetTransaction, CTxIn::prevout, COutPoint::hash, CTxOut::nValue, CTxOut::scriptPubKey.
Referenced by CStormnodeMan::ProcessMessage.
bool CSandStormSigner::SetKey(std::string strSecret, std::string &errorMessage, CKey &key, CPubKey &pubkey)
Set the private/public key values, returns true if successful.
References CDarkSilkSecret::SetString, _, CDarkSilkSecret::GetKey, CKey::GetPubKey.
Referenced by CActiveStormnode::ManageStatus, CActiveStormnode::Register, AppInit2, CConsensusVote::Sign, snbudget, snfinalbudget, CSandStormRelay::Sign, CSandStormRelay::VerifyMessage, CSandstormPool::CheckFinalTransaction, CSandstormQueue::Sign, CSporkManager::Sign, CFinalizedBudget::SubmitVote, CStormnodePayments::ProcessBlock.
bool CSandStormSigner::SignMessage(std::string strMessage, std::string &errorMessage, std::vector< unsigned char > &vchSig, CKey key)
Sign the message, returns true if successful.
References SER_GETHASH, strMessageMagic, CKey::SignCompact, CHashWriter::GetHash, _.
Referenced by CConsensusVote::Sign, CSandStormRelay::Sign, CSandstormPool::CheckFinalTransaction, CSandstormQueue::Sign, CSporkManager::Sign, CBudgetVote::Sign, CFinalizedBudgetVote::Sign, CStormnodePaymentWinner::Sign, CStormnodeBroadcast::Sign, CStormnodePing::Sign.
bool CSandStormSigner::VerifyMessage(CPubKey pubkey, std::vector< unsigned char > &vchSig, std::string strMessage, std::string &errorMessage)
Verify the message, returns true if succcessful.
References SER_GETHASH, strMessageMagic, CPubKey::RecoverCompact, CHashWriter::GetHash, _, fDebug, CPubKey::GetID, LogPrintf, base_uint< BITS >::ToString.
Referenced by CConsensusVote::SignatureValid, CConsensusVote::Sign, CSandStormRelay::Sign, CSandStormRelay::VerifyMessage, CSandstormPool::CheckFinalTransaction, CSandstormQueue::Sign, CSandstormQueue::CheckSignature, CSporkManager::CheckSignature, CSporkManager::Sign, CBudgetVote::Sign, CBudgetVote::SignatureValid, CFinalizedBudgetVote::Sign, CFinalizedBudgetVote::SignatureValid, CStormnodePaymentWinner::Sign, CStormnodePaymentWinner::SignatureValid, CStormnodeBroadcast::CheckAndUpdate, CStormnodeBroadcast::Sign, CStormnodePing::Sign, CStormnodePing::CheckAndUpdate.