CLevelDBWrapper
leveldb::Env* CLevelDBWrapper::penv
custom environment this database is using (may be NULL in case of default environment)
leveldb::Options CLevelDBWrapper::options
database options used
leveldb::ReadOptions CLevelDBWrapper::readoptions
options used when reading from the database
leveldb::ReadOptions CLevelDBWrapper::iteroptions
options used when iterating over values of the database
leveldb::WriteOptions CLevelDBWrapper::writeoptions
options used when writing to the database
leveldb::WriteOptions CLevelDBWrapper::syncoptions
options used when sync writing to the database
leveldb::DB* CLevelDBWrapper::pdb
the database itself
CLevelDBWrapper::CLevelDBWrapper(const boost::filesystem::path &path, size_t nCacheSize, bool fMemory=false, bool fWipe=false)
References leveldb::ReadOptions::verify_checksums, leveldb::ReadOptions::fill_cache, leveldb::WriteOptions::sync, leveldb::Options::create_if_missing, leveldb::NewMemEnv, leveldb::Env::Default, leveldb::Options::env, LogPrintf, leveldb::DestroyDB, TryCreateDirectory, leveldb::DB::Open, HandleError.
CLevelDBWrapper::~CLevelDBWrapper()
References leveldb::Options::filter_policy, leveldb::Options::block_cache, leveldb::Options::env.
bool CLevelDBWrapper::Read(const K &key, V &value) const
References SER_DISK, CDataStream::reserve, CDataStream::GetSerializeSize, CDataStream::size, leveldb::DB::Get, leveldb::Status::ok, leveldb::Status::IsNotFound, LogPrintf, leveldb::Status::ToString, HandleError, value.
Referenced by CCoinsViewDB::GetCoins, CCoinsViewDB::GetBestBlock, CBlockTreeDB::ReadBlockFileInfo, CBlockTreeDB::ReadLastBlockFile, CBlockTreeDB::ReadTxIndex, CBlockTreeDB::ReadFlag.
bool CLevelDBWrapper::Write(const K &key, const V &value, bool fSync=false)
References CLevelDBBatch::Write, WriteBatch.
Referenced by CBlockTreeDB::WriteBlockIndex, CBlockTreeDB::WriteBlockFileInfo, CBlockTreeDB::WriteLastBlockFile, CBlockTreeDB::WriteReindexing, CBlockTreeDB::WriteFlag.
bool CLevelDBWrapper::Exists(const K &key) const
References SER_DISK, CDataStream::reserve, CDataStream::GetSerializeSize, CDataStream::size, leveldb::DB::Get, leveldb::Status::ok, leveldb::Status::IsNotFound, LogPrintf, leveldb::Status::ToString, HandleError.
Referenced by CCoinsViewDB::HaveCoins, CBlockTreeDB::ReadReindexing.
bool CLevelDBWrapper::Erase(const K &key, bool fSync=false)
References CLevelDBBatch::Erase, WriteBatch.
Referenced by CBlockTreeDB::WriteReindexing.
bool CLevelDBWrapper::WriteBatch(CLevelDBBatch &batch, bool fSync=false)
References HandleError.
Referenced by CCoinsViewDB::BatchWrite, Write, Erase, Sync, CBlockTreeDB::WriteTxIndex.
bool CLevelDBWrapper::Flush()
bool CLevelDBWrapper::Sync()
References WriteBatch.
leveldb::Iterator* CLevelDBWrapper::NewIterator()
References leveldb::DB::NewIterator.
Referenced by CBlockTreeDB::LoadBlockIndexGuts.