CHashWriter
SHA256_CTX CHashWriter::ctx
int CHashWriter::nType
int CHashWriter::nVersion
void CHashWriter::Init()
Referenced by CHashWriter.
CHashWriter::CHashWriter(int nTypeIn, int nVersionIn)
References Init.
CHashWriter& CHashWriter::write(const char *pch, size_t size)
uint256 CHashWriter::GetHash()
Referenced by CCoinsViewDB::GetStats, SerializeHash, verifymessage, signmessage, CSandStormSigner::SignMessage, CSandStormSigner::VerifyMessage, SignatureHash, CFinalizedBudget::GetHash, CFinalizedBudgetVote::GetHash, CBudgetProposal::GetHash, CBudgetVote::GetHash, CStormnodePaymentWinner::GetHash, CStormnode::CalculateScore, CStormnode::SecondsSincePayment, CStormnodePing::GetHash, CStormnodeBroadcast::GetHash.
CHashWriter& CHashWriter::operator<<(const T &obj)
References Serialize.