CTransactionPoS
const int CTransactionPoS::CURRENT_VERSION
Referenced by CTransactionPoS.
int CTransactionPoS::nVersion
Referenced by SerializationOp.
CTransactionPoS::ADD_SERIALIZE_METHODS
CTransactionPoS::CTransactionPoS()
References CURRENT_VERSION.
void CTransactionPoS::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE, nVersion.
CAmount CTransactionPoS::GetValueOut(CTransaction &tx) const
References CTransaction::vout, CTxOut::nValue, MoneyRange.
Referenced by CBlock::ConnectBlock, AcceptToMemoryPool, AcceptableInputs, ConnectInputs, CreateNewBlock, CheckStake, TransactionDesc::toHTML, TransactionRecord::decomposeTransaction, getblocktemplate, gettransaction.
CAmount CTransactionPoS::GetValueIn(CTransaction &tx, const MapPrevTx &mapInputs) const
Amount of darksilks coming in to this transaction Note that lightweight clients may not know anything besides the hash of previous transactions, so may not be able to calculate this.
References CTransaction::IsCoinBase, CTransaction::vin.
Referenced by CBlock::ConnectBlock, AcceptToMemoryPool, AcceptableInputs, CreateNewBlock, getblocktemplate.
bool CTransactionPoS::ReadFromDisk(CTransaction &tx, CDiskTxPos pos, FILE **pfileRet=NULL)
References OpenBlockFile, CDiskTxPos::nFile, SER_DISK, CDiskTxPos::nTxPos, CAutoFile::release.
Referenced by CheckProofOfStake, CheckKernel, GetTransaction, ReadFromDisk, FetchInputs, CreateNewBlock, CTxDB::ReadDiskTx, CTxDB::LoadBlockIndex.
bool CTransactionPoS::ReadFromDisk(CTransaction &tx, CTxDB &txdb, const uint256 &hash, CTxIndex &txindexRet)
References CTransaction::SetNull, CTxDB::ReadTxIndex, ReadFromDisk, CTxIndex::pos.
bool CTransactionPoS::ReadFromDisk(CTransaction &tx, CTxDB &txdb, COutPoint prevout, CTxIndex &txindexRet)
References COutPoint::hash, COutPoint::n, CTransaction::vout, CTransaction::SetNull.
bool CTransactionPoS::ReadFromDisk(CTransaction &tx, CTxDB &txdb, COutPoint prevout)
bool CTransactionPoS::ReadFromDisk(CTransaction &tx, COutPoint prevout)
References txdb.
bool CTransactionPoS::DisconnectInputs(CTransaction &tx, CTxDB &txdb)
References CTransaction::IsCoinBase, CTransaction::vin, CTxIn::prevout, CTxDB::ReadTxIndex, COutPoint::hash, COutPoint::n, CTxIndex::vSpent, CTxDB::UpdateTxIndex, CTxDB::EraseTxIndex.
Referenced by CBlock::DisconnectBlock.
bool CTransactionPoS::FetchInputs(CTransaction &tx, CTxDB &txdb, const std::map< uint256, CTxIndex > &mapTestPool, bool fBlock, bool fMiner, MapPrevTx &inputsRet, bool &fInvalid)
Fetch from memory and/or disk. inputsRet keys are transaction hashes.
References CTransaction::IsCoinBase, CTransaction::vin, COutPoint::hash, CTxDB::ReadTxIndex, CTransaction::GetHash, base_uint< BITS >::ToString, CTxIndex::pos, CTxIndex::vSpent, ReadFromDisk, COutPoint::n, CTransaction::vout, CTransaction::DoS, CTransaction::ToString.
Referenced by CBlock::RebuildAddressIndex, CBlock::ConnectBlock, AcceptToMemoryPool, AcceptableInputs, CreateNewBlock, getblocktemplate, signrawtransaction.
bool CTransactionPoS::ConnectInputs(CTransaction &tx, CTxDB &txdb, MapPrevTx inputs, std::map< uint256, CTxIndex > &mapTestPool, const CDiskTxPos &posThisTx, const CBlockIndex *pindexBlock, bool fBlock, bool fMiner, unsigned int flags=STANDARD_SCRIPT_VERIFY_FLAGS, bool fValidateSig=true)
Sanity check previous transactions, then, if all checks succeed, mark them as spent by this transaction.
References CTransaction::IsCoinBase, CTransaction::vin, COutPoint::hash, COutPoint::n, CTransaction::vout, CTransaction::DoS, CTransaction::GetHash, base_uint< BITS >::ToString, CTransaction::ToString, CTransaction::IsCoinStake, IsConfirmedInNPrevBlocks, CTransaction::nTime, MoneyRange, Checkpoints::GetTotalBlocksEstimate, VerifySignature, GetValueOut.
Referenced by CBlock::ConnectBlock, AcceptToMemoryPool, AcceptableInputs, CreateNewBlock.
bool CTransactionPoS::GetCoinAge(CTransaction &tx, CTxDB &txdb, const CBlockIndex *pindexPrev, uint64_t &nCoinAge) const
const CTxOut & CTransactionPoS::GetOutputFor(const CTxIn &input, const MapPrevTx &inputs) const
References CTxIn::prevout, COutPoint::hash, COutPoint::n, CTransaction::vout.
Referenced by AreInputsStandard, GetP2SHSigOpCount.