leveldb::SnapshotList
SnapshotImpl leveldb::SnapshotList::list_
leveldb::SnapshotList::SnapshotList()
bool leveldb::SnapshotList::empty() const
Referenced by oldest, newest.
SnapshotImpl* leveldb::SnapshotList::oldest() const
References empty.
SnapshotImpl* leveldb::SnapshotList::newest() const
References empty.
const SnapshotImpl* leveldb::SnapshotList::New(SequenceNumber seq)
References leveldb::SnapshotImpl::number_.
Referenced by leveldb::DBImpl::GetSnapshot.
void leveldb::SnapshotList::Delete(const SnapshotImpl *s)
Referenced by leveldb::DBImpl::ReleaseSnapshot.