AddressTableModel
int AddressTableModel::rowCount(const QModelIndex &parent) const
References AddressTablePriv::size.
int AddressTableModel::columnCount(const QModelIndex &parent) const
QVariant AddressTableModel::data(const QModelIndex &index, int role) const
References Label, AddressTableEntry::label, Address, AddressTableEntry::address, GUIUtil::darksilkAddressFont, TypeRole, AddressTableEntry::type, AddressTableEntry::Sending, Send, AddressTableEntry::Receiving, Receive.
Referenced by index.
bool AddressTableModel::setData(const QModelIndex &index, const QVariant &value, int role)
References OK, Label, AddressTableEntry::label, NO_CHANGES, AddressTableEntry::address, IsStealthAddress, CWallet::UpdateStealthAddress, CWallet::SetAddressBookName, Address, INVALID_ADDRESS, WalletModel::validateAddress, CWallet::mapAddressBook, DUPLICATE_ADDRESS, AddressTableEntry::type, AddressTableEntry::Sending, LOCK, CWallet::cs_wallet, CWallet::DelAddressBookName.
QVariant AddressTableModel::headerData(int section, Qt::Orientation orientation, int role) const
QModelIndex AddressTableModel::index(int row, int column, const QModelIndex &parent) const
References data, AddressTablePriv::index.
Referenced by lookupAddress.
bool AddressTableModel::removeRows(int row, int count, const QModelIndex &parent=QModelIndex())
References AddressTablePriv::index, AddressTableEntry::type, AddressTableEntry::Receiving, LOCK, CWallet::cs_wallet, CWallet::DelAddressBookName, AddressTableEntry::address.
Qt::ItemFlags AddressTableModel::flags(const QModelIndex &index) const
References AddressTableEntry::type, AddressTableEntry::Sending, AddressTableEntry::Receiving, Label.
AddressType
User specified label
ColumnIndex
User specified label
RoleIndex
Type of address (Send or Receive)
EditStatus
Everything ok
const QString AddressTableModel::Send
Specifies send address
Referenced by AddressBookPage::setModel, data, addRow.
const QString AddressTableModel::Receive
Specifies receive address
Referenced by AddressBookPage::setModel, data, addRow.
WalletModel* AddressTableModel::walletModel
CWallet* AddressTableModel::wallet
AddressTablePriv* AddressTableModel::priv
QStringList AddressTableModel::columns
EditStatus AddressTableModel::editStatus
friend class AddressTablePriv
Referenced by AddressTableModel.
AddressTableModel::AddressTableModel(CWallet *wallet, WalletModel *parent=0)
References AddressTablePriv, AddressTablePriv::refreshAddressTable.
AddressTableModel::~AddressTableModel()
QString AddressTableModel::addRow(const QString &type, const QString &label, const QString &address, int addressType)
References OK, Send, CStealthAddress::SetEncoded, INVALID_ADDRESS, LOCK, CWallet::cs_wallet, CWallet::stealthAddresses, DUPLICATE_ADDRESS, CStealthAddress::label, CWallet::AddStealthAddress, WalletModel::validateAddress, CWallet::mapAddressBook, CWallet::SetAddressBookName, Receive, WalletModel::requestUnlock, WALLET_UNLOCK_FAILURE, AT_Stealth, CWallet::NewStealthAddress, KEY_GENERATION_FAILURE, CStealthAddress::Encoded, CWallet::GetKeyFromPool, CPubKey::GetID.
QString AddressTableModel::labelForAddress(const QString &address) const
References LOCK, CWallet::cs_wallet, CStealthAddress::SetEncoded, CWallet::stealthAddresses, CWallet::mapAddressBook, CDarkSilkAddress::Get.
Referenced by MessageTablePriv::refreshMessageTable, MessageTablePriv::newMessage, MessageTablePriv::newOutboxMessage, TransactionTableModel::data.
int AddressTableModel::lookupAddress(const QString &address) const
References index, Address.
EditStatus AddressTableModel::getEditStatus() const
Referenced by EditAddressDialog::accept.
void AddressTableModel::emitDataChanged(int index)
Notify listeners that data changed.
void AddressTableModel::updateEntry(const QString &address, const QString &label, bool isMine, int status)
References AddressTablePriv::updateEntry.
Referenced by WalletModel::updateAddressBook.