leveldb::port::AtomicPointer
intptr_t leveldb::port::AtomicPointer::rep_
void* leveldb::port::AtomicPointer::rep_
leveldb::port::AtomicPointer::AtomicPointer()
leveldb::port::AtomicPointer::AtomicPointer(void *v)
void * leveldb::port::AtomicPointer::Acquire_Load() const
Referenced by leveldb::DBImpl::TEST_CompactRange, leveldb::SpecialEnv::NewWritableFile, leveldb::TEST.
void leveldb::port::AtomicPointer::Release_Store(void *v)
Referenced by leveldb::DBImpl::DBImpl, leveldb::DBImpl::~DBImpl, leveldb::SpecialEnv::SpecialEnv, leveldb::TEST.
void * leveldb::port::AtomicPointer::NoBarrier_Load() const
Referenced by leveldb::TEST.
void leveldb::port::AtomicPointer::NoBarrier_Store(void *v)
Referenced by leveldb::SkipList< Key, Comparator >::Insert.
leveldb::port::AtomicPointer::AtomicPointer()
leveldb::port::AtomicPointer::AtomicPointer(void *v)
void* leveldb::port::AtomicPointer::Acquire_Load() const
void leveldb::port::AtomicPointer::Release_Store(void *v)
void* leveldb::port::AtomicPointer::NoBarrier_Load() const
void leveldb::port::AtomicPointer::NoBarrier_Store(void *v)