I2PSession
static SAM::StreamSessionAdapter& I2PSession::Instance()
Referenced by AppInit2, ConnectSocket, CNetAddr::SetSpecial.
std::string I2PSession::GenerateB32AddressFromDestination(const std::string &destination)
References DecodeBase64, hash, EncodeBase32, base_uint< BITS >::begin, base_uint< BITS >::end.
Referenced by AppInit2.
I2PSession::I2PSession()
I2PSession::~I2PSession()
I2PSession::I2PSession(const I2PSession &)
I2PSession& I2PSession::operator=(const I2PSession &)