base_uint
@19
uint32_t base_uint< BITS >::pn[WIDTH][WIDTH]
Referenced by base_uint< BITS >::operator<<=, base_uint< BITS >::operator>>=, base_uint< BITS >::operator*=, base_uint< BITS >::CompareTo, uint256::GetHash, base_uint< 512 >::base_uint, base_uint< 512 >::operator=, base_uint< 512 >::operator~, base_uint< 512 >::operator-, base_uint< 512 >::operator^=, base_uint< 512 >::operator&=, base_uint< 512 >::operator|=, base_uint< 512 >::operator+=, base_uint< 512 >::size, base_uint< 512 >::GetSerializeSize, uint512::trim256.
friend class uint160
friend class uint256
friend class uint512
const base_uint operator+(const base_uint &a, const base_uint &b)
const base_uint operator-(const base_uint &a, const base_uint &b)
const base_uint operator*(const base_uint &a, const base_uint &b)
const base_uint operator/(const base_uint &a, const base_uint &b)
const base_uint operator|(const base_uint &a, const base_uint &b)
const base_uint operator&(const base_uint &a, const base_uint &b)
const base_uint operator^(const base_uint &a, const base_uint &b)
const base_uint operator>>(const base_uint &a, int shift)
const base_uint operator<<(const base_uint &a, int shift)
const base_uint operator*(const base_uint &a, uint32_t b)
bool operator==(const base_uint &a, const base_uint &b)
bool operator!=(const base_uint &a, const base_uint &b)
bool operator>(const base_uint &a, const base_uint &b)
bool operator<(const base_uint &a, const base_uint &b)
bool operator>=(const base_uint &a, const base_uint &b)
bool operator<=(const base_uint &a, const base_uint &b)
bool operator==(const base_uint &a, uint64_t b)
bool operator!=(const base_uint &a, uint64_t b)
base_uint< BITS >::base_uint()
base_uint< BITS >::base_uint(const base_uint &b)
base_uint& base_uint< BITS >::operator=(const base_uint &b)
base_uint< BITS >::base_uint(uint64_t b)
base_uint< BITS >::base_uint(const std::string &str)
base_uint< BITS >::base_uint(const std::vector< unsigned char > &vch)
bool base_uint< BITS >::operator!() const
const base_uint base_uint< BITS >::operator~() const
const base_uint base_uint< BITS >::operator-() const
double base_uint< BITS >::getdouble() const
base_uint& base_uint< BITS >::operator=(uint64_t b)
base_uint& base_uint< BITS >::operator^=(const base_uint &b)
base_uint& base_uint< BITS >::operator&=(const base_uint &b)
base_uint& base_uint< BITS >::operator|=(const base_uint &b)
base_uint& base_uint< BITS >::operator^=(uint64_t b)
base_uint& base_uint< BITS >::operator|=(uint64_t b)
base_uint< BITS > & base_uint< BITS >::operator<<=(unsigned int shift)
References base_uint< BITS >::pn.
base_uint< BITS > & base_uint< BITS >::operator>>=(unsigned int shift)
References base_uint< BITS >::pn.
base_uint& base_uint< BITS >::operator+=(const base_uint &b)
base_uint& base_uint< BITS >::operator-=(const base_uint &b)
base_uint& base_uint< BITS >::operator+=(uint64_t b64)
base_uint& base_uint< BITS >::operator-=(uint64_t b64)
base_uint< BITS > & base_uint< BITS >::operator*=(uint32_t b32)
base_uint< BITS > & base_uint< BITS >::operator*=(const base_uint &b)
References base_uint< BITS >::pn.
base_uint< BITS > & base_uint< BITS >::operator/=(const base_uint &b)
References base_uint< BITS >::bits.
base_uint& base_uint< BITS >::operator++()
const base_uint base_uint< BITS >::operator++(int)
base_uint& base_uint< BITS >::operator--()
const base_uint base_uint< BITS >::operator--(int)
int base_uint< BITS >::CompareTo(const base_uint &b) const
References base_uint< BITS >::pn.
bool base_uint< BITS >::EqualTo(uint64_t b) const
std::string base_uint< BITS >::GetHex() const
Referenced by CBlock::SetBestChain, CheckWork, CheckStake, getBlockHash, WalletModel::sendCoins, blockToJSON, getbestblockhash, getblockhash, checkkernel, getblocktemplate, TxToJSON, sendrawtransaction, WalletTxToJSON, sendfrom, sendmany, ListReceived, listsinceblock, gettransaction, sendtostealthaddress, CSandstormPool::MakeCollateralAmounts, CSandstormPool::CreateDenominated, BOOST_AUTO_TEST_CASE, CWallet::AddToWallet, CWallet::FindStealthTransactions.
void base_uint< BITS >::SetHex(const char *psz)
References HexDigit.
Referenced by CActiveStormnode::SelectCoinsStormnode, AppInit2, getTxTotalValue, getOutputs, getInputs, getTxFees, ClientModel::updateAlert, TransactionTableModel::updateTransaction, getrawtransaction, signrawtransaction, ParseHashV, listsinceblock, gettransaction, BOOST_AUTO_TEST_CASE.
void base_uint< BITS >::SetHex(const std::string &str)
std::string base_uint< BITS >::ToString() const
Referenced by CBlock::AcceptBlock, CBlock::RebuildAddressIndex, CBlock::ConnectBlock, InvalidChainFound, Reorganize, CBlock::CheckBlock, CBlockIndex::ToString, CDiskBlockIndex::ToString, AppInit2, CreateNewLock, ProcessConsensusVote, CheckForConflictingLocks, CheckStakeKernelHash, CheckProofOfStake, AddOrphanTx, AcceptToMemoryPool, AcceptableInputs, ProcessBlock, PrintBlockTree, SendMessages, CTransactionPoS::FetchInputs, CTransactionPoS::ConnectInputs, CBlock::SetBestChain, CBlock::AddToBlockIndex, CreateNewBlock, CBlock::ToString, COutPoint::ToString, COutPoint::ToStringShort, CInv::ToString, getBlockMerkle, getInputs, getTxFees, MessageModel::getAddressOrPubkey, TransactionRecord::formatSubTxId, TransactionTablePriv::updateWallet, getrawmempool, getcheckpoint, dumpwallet, snbudget, snfinalbudget, stormnode, stormnodelist, CSandstormPool::CheckFinalTransaction, CSandStormSigner::VerifyMessage, ProcessSpork, IsBudgetCollateralValid, CBudgetManager::SubmitFinalBudget, CBudgetManager::CheckAndRemove, CBudgetManager::GetRequiredPaymentsString, CBudgetManager::UpdateProposal, CBudgetManager::UpdateFinalizedBudget, CBudgetProposal::AddOrUpdateVote, CBudgetVote::Sign, CBudgetVote::SignatureValid, CFinalizedBudget::AddOrUpdateVote, CFinalizedBudget::GetProposals, CFinalizedBudget::GetStatus, CFinalizedBudget::SubmitVote, CFinalizedBudgetVote::Sign, CFinalizedBudgetVote::SignatureValid, CStormnodePing::Sign, CStormnodePing::CheckAndUpdate, CTxDB::LoadBlockIndex, CWallet::AddToWallet, CWallet::ReacceptWalletTransactions, CWalletTx::RelayWalletTransaction, CWallet::FixSpentCoins, COutput::ToString.
unsigned char* base_uint< BITS >::begin()
Referenced by I2PSession::GenerateB32AddressFromDestination, CKey::Sign, CKey::VerifyPubKey, CKey::SignCompact, CPubKey::Verify, CPubKey::RecoverCompact, GenerateRandomSecret.
unsigned char* base_uint< BITS >::end()
Referenced by DecodeBase58Check, I2PSession::GenerateB32AddressFromDestination.
const unsigned char* base_uint< BITS >::begin() const
const unsigned char* base_uint< BITS >::end() const
unsigned int base_uint< BITS >::size() const
Referenced by CECKey::Verify, ProcessBlock.
uint64_t base_uint< BITS >::Get64(int n=0) const
Referenced by InvalidChainFound, CBlock::GetStakeEntropyBit, CBlock::SetBestChain.
unsigned int base_uint< BITS >::bits() const
Returns the position of the highest bit set plus one, or zero if the value is zero.
Referenced by base_uint< BITS >::operator/=.
uint64_t base_uint< BITS >::GetLow64() const
Referenced by BlockHasher::operator(), uint256::GetCompact.
unsigned int base_uint< BITS >::GetSerializeSize(int nType, int nVersion) const
void base_uint< BITS >::Serialize(Stream &s, int nType, int nVersion) const
void base_uint< BITS >::Unserialize(Stream &s, int nType, int nVersion)