leveldb::Env
leveldb::Env::Env()
leveldb::Env::~Env()
virtual Status leveldb::Env::NewSequentialFile(const std::string &fname, SequentialFile **result)=0
Referenced by leveldb::VersionSet::Recover, leveldb::TEST, leveldb::EnvWrapper::NewSequentialFile, leveldb::ReadFileToString.
virtual Status leveldb::Env::NewRandomAccessFile(const std::string &fname, RandomAccessFile **result)=0
Referenced by leveldb::SpecialEnv::NewRandomAccessFile, leveldb::TEST, leveldb::EnvWrapper::NewRandomAccessFile.
virtual Status leveldb::Env::NewWritableFile(const std::string &fname, WritableFile **result)=0
Referenced by leveldb::BuildTable, leveldb::DB::Open, leveldb::SpecialEnv::NewWritableFile, leveldb::VersionSet::LogAndApply, leveldb::TEST, leveldb::EnvWrapper::NewWritableFile, leveldb::test::ErrorEnv::NewWritableFile.
virtual bool leveldb::Env::FileExists(const std::string &fname)=0
Referenced by leveldb::TEST, leveldb::EnvWrapper::FileExists.
virtual Status leveldb::Env::GetChildren(const std::string &dir, std::vector< std::string > *result)=0
Referenced by leveldb::Benchmark::Benchmark, leveldb::DestroyDB, leveldb::TEST, leveldb::EnvWrapper::GetChildren.
virtual Status leveldb::Env::DeleteFile(const std::string &fname)=0
Referenced by leveldb::BuildTable, leveldb::Benchmark::Benchmark, leveldb::DestroyDB, leveldb::SetCurrentFile, leveldb::VersionSet::LogAndApply, leveldb::TEST, leveldb::EnvWrapper::DeleteFile.
virtual Status leveldb::Env::CreateDir(const std::string &dirname)=0
Referenced by leveldb::SanitizeOptions, leveldb::TEST, leveldb::EnvWrapper::CreateDir.
virtual Status leveldb::Env::DeleteDir(const std::string &dirname)=0
Referenced by leveldb::DestroyDB, leveldb::TEST, leveldb::EnvWrapper::DeleteDir.
virtual Status leveldb::Env::GetFileSize(const std::string &fname, uint64_t *file_size)=0
Referenced by leveldb::TEST, leveldb::EnvWrapper::GetFileSize.
virtual Status leveldb::Env::RenameFile(const std::string &src, const std::string &target)=0
Referenced by leveldb::SanitizeOptions, leveldb::SetCurrentFile, leveldb::TEST, leveldb::EnvWrapper::RenameFile.
virtual Status leveldb::Env::LockFile(const std::string &fname, FileLock **lock)=0
Referenced by leveldb::DestroyDB, leveldb::TEST, leveldb::EnvWrapper::LockFile.
virtual Status leveldb::Env::UnlockFile(FileLock *lock)=0
Referenced by leveldb::DBImpl::~DBImpl, leveldb::DestroyDB, leveldb::TEST, leveldb::EnvWrapper::UnlockFile.
virtual void leveldb::Env::Schedule(void(*function)(void *arg), void *arg)=0
Referenced by leveldb::EnvWrapper::Schedule, leveldb::TEST.
virtual void leveldb::Env::StartThread(void(*function)(void *arg), void *arg)=0
Referenced by leveldb::TEST, leveldb::EnvWrapper::StartThread.
virtual Status leveldb::Env::GetTestDirectory(std::string *path)=0
Referenced by main, leveldb::Benchmark::Benchmark, leveldb::Benchmark::Open, leveldb::TEST, leveldb::EnvWrapper::GetTestDirectory, leveldb::test::TmpDir.
virtual Status leveldb::Env::NewLogger(const std::string &fname, Logger **result)=0
Referenced by leveldb::SanitizeOptions, leveldb::EnvWrapper::NewLogger.
virtual uint64_t leveldb::Env::NowMicros()=0
Referenced by leveldb::BM_LogAndApply, leveldb::EnvWrapper::NowMicros.
virtual void leveldb::Env::SleepForMicroseconds(int micros)=0
Referenced by leveldb::AutoCompactTest::DoReads, leveldb::TEST, leveldb::EnvWrapper::SleepForMicroseconds.
Env * leveldb::Env::Default()
Referenced by leveldb::AutoCompactTest::DoReads, leveldb::CorruptionTest::Corrupt, leveldb::Benchmark::Benchmark, main, leveldb::BM_LogAndApply, leveldb::Benchmark::Open, leveldb::TEST, leveldb::test::TmpDir, CLevelDBWrapper::CLevelDBWrapper.
leveldb::Env::Env(const Env &)
void leveldb::Env::operator=(const Env &)