leveldb::VersionSet
friend class Compaction
Referenced by PickCompaction, CompactRange.
friend class Version
Referenced by VersionSet, LogAndApply, Recover.
Env* const leveldb::VersionSet::env_
const std::string leveldb::VersionSet::dbname_
const Options* const leveldb::VersionSet::options_
TableCache* const leveldb::VersionSet::table_cache_
const InternalKeyComparator leveldb::VersionSet::icmp_
uint64_t leveldb::VersionSet::next_file_number_
uint64_t leveldb::VersionSet::manifest_file_number_
uint64_t leveldb::VersionSet::last_sequence_
uint64_t leveldb::VersionSet::log_number_
uint64_t leveldb::VersionSet::prev_log_number_
WritableFile* leveldb::VersionSet::descriptor_file_
log::Writer* leveldb::VersionSet::descriptor_log_
Version leveldb::VersionSet::dummy_versions_
Version* leveldb::VersionSet::current_
std::string leveldb::VersionSet::compact_pointer_[config::kNumLevels][config::kNumLevels]
leveldb::VersionSet::VersionSet(const std::string &dbname, const Options *options, TableCache *table_cache, const InternalKeyComparator *)
References Version.
leveldb::VersionSet::~VersionSet()
References leveldb::Version::Unref.
Status leveldb::VersionSet::LogAndApply(VersionEdit *edit, port::Mutex *mu) EXCLUSIVE_LOCKS_REQUIRED(mu)
References leveldb::VersionEdit::SetLogNumber, leveldb::VersionEdit::SetPrevLogNumber, leveldb::VersionEdit::SetNextFile, leveldb::VersionEdit::SetLastSequence, Version, leveldb::VersionSet::Builder::Apply, leveldb::VersionSet::Builder::SaveTo, leveldb::DescriptorFileName, leveldb::Env::NewWritableFile, leveldb::Status::ok, leveldb::port::Mutex::Unlock, leveldb::VersionEdit::EncodeTo, leveldb::log::Writer::AddRecord, leveldb::WritableFile::Sync, leveldb::Log, leveldb::Options::info_log, leveldb::Status::ToString, leveldb::SetCurrentFile, leveldb::port::Mutex::Lock, leveldb::Env::DeleteFile.
Referenced by leveldb::DB::Open, leveldb::BM_LogAndApply.
Status leveldb::VersionSet::Recover()
References leveldb::Status::ok, current, leveldb::ReadFileToString, leveldb::CurrentFileName, leveldb::Status::Corruption, leveldb::Env::NewSequentialFile, leveldb::log::Reader::ReadRecord, leveldb::VersionEdit::DecodeFrom, leveldb::InternalKeyComparator::user_comparator, leveldb::Comparator::Name, leveldb::Status::InvalidArgument, leveldb::VersionSet::Builder::Apply, MarkFileNumberUsed, Version, leveldb::VersionSet::Builder::SaveTo.
Referenced by leveldb::BM_LogAndApply.
Version* leveldb::VersionSet::current() const
Referenced by leveldb::DBImpl::CompactRange, leveldb::DBImpl::Get, leveldb::DBImpl::RecordReadSample, leveldb::DBImpl::GetProperty, leveldb::DBImpl::GetApproximateSizes, Recover.
uint64_t leveldb::VersionSet::ManifestFileNumber() const
uint64_t leveldb::VersionSet::NewFileNumber()
Referenced by leveldb::DB::Open.
void leveldb::VersionSet::ReuseFileNumber(uint64_t file_number)
int leveldb::VersionSet::NumLevelFiles(int level) const
Referenced by leveldb::DBImpl::GetProperty.
int64_t leveldb::VersionSet::NumLevelBytes(int level) const
Referenced by leveldb::DBImpl::GetProperty.
uint64_t leveldb::VersionSet::LastSequence() const
Referenced by leveldb::DBImpl::Get, leveldb::DBImpl::GetSnapshot, leveldb::DBImpl::Write.
void leveldb::VersionSet::SetLastSequence(uint64_t s)
Referenced by leveldb::DBImpl::Write.
void leveldb::VersionSet::MarkFileNumberUsed(uint64_t number)
Referenced by Recover.
uint64_t leveldb::VersionSet::LogNumber() const
uint64_t leveldb::VersionSet::PrevLogNumber() const
Compaction * leveldb::VersionSet::PickCompaction()
References Compaction, leveldb::InternalKeyComparator::Compare, leveldb::FileMetaData::largest, leveldb::InternalKey::Encode, leveldb::Version::Ref, leveldb::Version::GetOverlappingInputs.
Compaction * leveldb::VersionSet::CompactRange(int level, const InternalKey *begin, const InternalKey *end)
References leveldb::Version::GetOverlappingInputs, total, Compaction, leveldb::Version::Ref.
int64_t leveldb::VersionSet::MaxNextLevelOverlappingBytes()
References leveldb::Version::GetOverlappingInputs, leveldb::FileMetaData::smallest, leveldb::FileMetaData::largest.
Referenced by leveldb::DBImpl::TEST_MaxNextLevelOverlappingBytes.
Iterator * leveldb::VersionSet::MakeInputIterator(Compaction *c)
References leveldb::ReadOptions::verify_checksums, leveldb::Options::paranoid_checks, leveldb::ReadOptions::fill_cache, leveldb::Compaction::level, leveldb::TableCache::NewIterator, leveldb::NewTwoLevelIterator, leveldb::NewMergingIterator.
bool leveldb::VersionSet::NeedsCompaction() const
void leveldb::VersionSet::AddLiveFiles(std::set< uint64_t > *live)
uint64_t leveldb::VersionSet::ApproximateOffsetOf(Version *v, const InternalKey &key)
References leveldb::InternalKeyComparator::Compare, leveldb::TableCache::NewIterator, leveldb::Table::ApproximateOffsetOf, leveldb::InternalKey::Encode.
Referenced by leveldb::DBImpl::GetApproximateSizes.
const char * leveldb::VersionSet::LevelSummary(LevelSummaryStorage *scratch) const
References leveldb::VersionSet::LevelSummaryStorage::buffer.
void leveldb::VersionSet::Finalize(Version *v)
void leveldb::VersionSet::GetRange(const std::vector< FileMetaData * > &inputs, InternalKey *smallest, InternalKey *largest)
void leveldb::VersionSet::GetRange2(const std::vector< FileMetaData * > &inputs1, const std::vector< FileMetaData * > &inputs2, InternalKey *smallest, InternalKey *largest)
void leveldb::VersionSet::SetupOtherInputs(Compaction *c)
Status leveldb::VersionSet::WriteSnapshot(log::Writer *log)
void leveldb::VersionSet::AppendVersion(Version *v)
leveldb::VersionSet::VersionSet(const VersionSet &)
void leveldb::VersionSet::operator=(const VersionSet &)