CCoinsView
bool CCoinsView::GetCoins(const uint256 &txid, CCoins &coins) const
Retrieve the CCoins (unspent transaction outputs) for a given txid.
Referenced by CCoinsViewBacked::GetCoins, CCoinsViewCache::ModifyCoins, CCoinsViewMemPool::GetCoins.
bool CCoinsView::HaveCoins(const uint256 &txid) const
Just check whether we have data for a given txid. This may (but cannot always) return true for fully spent transactions
Referenced by CCoinsViewBacked::HaveCoins, CCoinsViewMemPool::HaveCoins.
uint256 CCoinsView::GetBestBlock() const
Retrieve the block hash whose state this CCoinsView currently represents.
Referenced by CCoinsViewBacked::GetBestBlock, CCoinsViewCache::GetBestBlock.
bool CCoinsView::BatchWrite(CCoinsMap &mapCoins, const uint256 &hashBlock)
Do a bulk modification (multiple CCoins changes + BestBlock change). The passed mapCoins can be modified.
Referenced by CCoinsViewBacked::BatchWrite, CCoinsViewCache::Flush.
bool CCoinsView::GetStats(CCoinsStats &stats) const
Calculate statistics about the unspent transaction output set.
Referenced by CCoinsViewBacked::GetStats.
virtual CCoinsView::~CCoinsView()
As we use CCoinsViews polymorphically, have a virtual destructor.