CTransaction
const int CTransaction::CURRENT_VERSION
Referenced by AddOrphanTx, IsStandardTx, SetNull.
int CTransaction::nVersion
Referenced by CCoins::FromTx, IsStandardTx, CMerkleTx::SerializationOp, ToString, TxToJSON.
unsigned int CTransaction::nTime
Referenced by CBlock::CheckBlock, CheckStakeKernelHash, CheckProofOfStake, CBlock::GetMaxTransactionTime, IsStandardTx, CTransactionPoS::ConnectInputs, CreateNewBlock, ToString, TxToJSON, CWallet::AvailableCoinsForStaking, CWallet::SelectCoinsMinConfByCoinAge, CWallet::CreateCoinStake.
std::vector<CTxIn> CTransaction::vin
Referenced by CBlock::ConnectBlock, CBlock::CheckBlock, CCoinsViewCache::GetValueIn, CCoinsViewCache::HaveInputs, CCoinsViewCache::GetPriority, IsIXTXValid, CreateNewLock, CheckForConflictingLocks, CleanTransactionLocksList, CheckProofOfStake, AddOrphanTx, IsStandardTx, IsFinalTx, AreInputsStandard, GetLegacySigOpCount, GetP2SHSigOpCount, AcceptToMemoryPool, AcceptableInputs, CTransactionPoS::DisconnectInputs, CTransactionPoS::FetchInputs, CTransactionPoS::GetValueIn, CTransactionPoS::ConnectInputs, CreateNewBlock, ToString, ComputePriority, CheckTransaction, SignatureHash, getInputValue, TransactionDesc::toHTML, TransactionRecord::decomposeTransaction, WalletModel::listCoins, TxToJSON, signrawtransaction, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::IsCollateralValid, CSandstormPool::SendSandstormDenominate, SignSignature, VerifySignature, CStormnodeBroadcast::CheckInputsAndAdd, CTxDB::LoadBlockIndex, CTxMemPool::addUnchecked, CTxMemPool::remove, CTxMemPool::removeConflicts, CWallet::GetConflicts, CWallet::SyncTransaction, CWallet::IsDenominated, CWalletTx::AddSupportingTransactions, CWallet::CreateCoinStake, CWallet::CommitTransaction, CWallet::GetAddressGroupings, CWallet::DisableTransaction, CWallet::GetDebit, CWalletTx::IsDenominated, CWalletTx::GetDebit, CWalletTx::GetAnonymizableCredit, CWalletTx::IsTrusted.
std::vector<CTxOut> CTransaction::vout
Referenced by CActiveStormnode::SelectCoinsStormnode, CBlock::RebuildAddressIndex, CBlock::ConnectBlock, CCoins::FromTx, IsIXTXValid, CheckStakeKernelHash, IsStandardTx, GetLegacySigOpCount, GetMinFee, CTransactionPoS::GetValueOut, CTransactionPoS::ReadFromDisk, CTransactionPoS::FetchInputs, CTransactionPoS::GetOutputFor, CTransactionPoS::ConnectInputs, CreateNewBlock, ToString, CheckTransaction, GetValueOut, SignatureHash, getInputValue, CoinControlDialog::updateLabels, TransactionDesc::toHTML, TransactionRecord::decomposeTransaction, WalletModel::getBalance, WalletModel::listCoins, TxToJSON, GetAccountAddress, getreceivedbyaddress, getreceivedbyaccount, ListReceived, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::IsCollateralValid, CSandstormPool::SendSandstormDenominate, SignSignature, VerifySignature, IsBudgetCollateralValid, CBudgetManager::FillBlockPayee, CFinalizedBudget::IsTransactionValid, CStormnodePayments::FillBlockPayee, CStormnodeBlockPayees::IsTransactionValid, CStormnodeBroadcast::CheckInputsAndAdd, CTxDB::AddTxIndex, CTxMemPool::remove, CWallet::IsMine, CWallet::GetDebit, CWallet::IsDenominated, CWallet::ReacceptWalletTransactions, CWallet::GetAnonymizableBalance, CWallet::GetAnonymizedBalance, CWallet::GetAverageAnonymizedRounds, CWallet::GetNormalizedAnonymizedBalance, CWallet::GetDenominatedBalance, CWallet::AvailableCoins, CWallet::AvailableCoinsForStaking, CWallet::SelectCoinsMinConfByCoinAge, less_then_denom, CWallet::SelectCoinsMinConf, CWallet::SelectCoinsByDenominations, CWallet::SelectCoinsDark, CWallet::SelectCoinsCollateral, CWallet::CountInputsWithAmount, CWallet::HasCollateralInputs, CWallet::SelectCoinsWithoutDenomination, CWallet::ConvertList, CWallet::CreateStealthTransaction, CWallet::FindStealthTransactions, CWallet::CreateCoinStake, CWallet::GetTotalValue, CWallet::GetAddressBalances, CWallet::GetAddressGroupings, CWallet::FixSpentCoins, CWallet::DisableTransaction, CWallet::GetKeyBirthTimes, CWallet::GetCredit, CWallet::GetChange, CWalletTx::SerializationOp, CWalletTx::MarkSpent, CWalletTx::MarkUnspent, CWalletTx::IsSpent, CWalletTx::GetAvailableCredit, CWalletTx::GetAnonymizableCredit, CWalletTx::GetDenominatedCredit, CWalletTx::GetAvailableWatchOnlyCredit, CWalletTx::IsTrusted, COutput::ToString, COutput::Priority.
unsigned int CTransaction::nLockTime
Referenced by IsIXTXValid, IsFinalTx, ToString, TransactionRecord::updateStatus, TxToJSON, CSandstormPool::IsCollateralValid, IsBudgetCollateralValid, BOOST_AUTO_TEST_CASE.
int CTransaction::nDoS
Referenced by CBlock::CheckBlock.
CTransaction::ADD_SERIALIZE_METHODS
bool CTransaction::DoS(int nDoSIn, bool fIn) const
Referenced by CheckProofOfStake, AcceptToMemoryPool, AcceptableInputs, CTransactionPoS::FetchInputs, CTransactionPoS::ConnectInputs, CheckTransaction.
CTransaction::CTransaction()
CTransaction::CTransaction(int nVersion, unsigned int nTime, const std::vector< CTxIn > &vin, const std::vector< CTxOut > &vout, unsigned int nLockTime)
CTransaction::CTransaction(const CMutableTransaction &tx)
Convert a CMutableTransaction into a CTransaction.
void CTransaction::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE.
void CTransaction::SetNull()
References CURRENT_VERSION, GetAdjustedTime.
Referenced by CTransactionPoS::ReadFromDisk, CTxDB::ReadDiskTx.
bool CTransaction::IsNull() const
uint256 CTransaction::GetHash() const
References SerializeHash.
Referenced by CBlock::RebuildAddressIndex, CBlock::ConnectBlock, CBlock::CheckBlock, CreateNewLock, DoConsensusVote, CheckForConflictingLocks, CheckProofOfStake, CBlock::BuildMerkleTree, AddOrphanTx, AcceptToMemoryPool, AcceptableInputs, CWalletTx::AcceptWalletTransaction, GetTransaction, CTransactionPoS::FetchInputs, CTransactionPoS::ConnectInputs, CreateNewBlock, RelayTransactionLockReq, ToString, TransactionDesc::toHTML, TransactionRecord::decomposeTransaction, WalletModel::sendCoins, blockToJSON, getblocktemplate, TxToJSON, sendrawtransaction, snbudget, stormnode, WalletTxToJSON, sendfrom, sendmany, ListReceived, sendtostealthaddress, CSandstormPool::CheckFinalTransaction, CSandstormPool::MakeCollateralAmounts, CSandstormPool::CreateDenominated, VerifySignature, CBudgetManager::SubmitFinalBudget, BOOST_AUTO_TEST_CASE, CTxDB::AddTxIndex, CTxDB::EraseTxIndex, CTxDB::LoadBlockIndex, CTxMemPool::remove, CWallet::AddToWallet, CWallet::AddToWalletIfInvolvingMe, CWalletTx::AddSupportingTransactions, CWallet::ReacceptWalletTransactions, CWallet::GetAnonymizedBalance, CWallet::GetAverageAnonymizedRounds, CWallet::GetNormalizedAnonymizedBalance, CWallet::SelectCoinsByDenominations, CWallet::SelectCoinsDark, CWallet::SelectCoinsCollateral, CWallet::CountInputsWithAmount, CWallet::FindStealthTransactions, CWallet::CommitTransaction, CWallet::FixSpentCoins, CWalletTx::GetAnonymizableCredit, CWalletTx::GetDenominatedCredit, CWalletTx::GetAvailableWatchOnlyCredit, COutput::ToString, CWalletDB::ReorderTransactions.
bool CTransaction::IsCoinBase() const
Referenced by CBlock::RebuildAddressIndex, CBlock::ConnectBlock, Reorganize, CBlock::CheckBlock, CCoinsViewCache::GetValueIn, CCoinsViewCache::HaveInputs, CCoinsViewCache::GetPriority, CCoins::FromTx, AreInputsStandard, GetP2SHSigOpCount, AcceptToMemoryPool, AcceptableInputs, CWalletTx::AcceptWalletTransaction, CTransactionPoS::DisconnectInputs, CTransactionPoS::FetchInputs, CTransactionPoS::GetValueIn, CTransactionPoS::ConnectInputs, CreateNewBlock, ToString, CheckTransaction, TransactionDesc::toHTML, TransactionRecord::showTransaction, TransactionRecord::decomposeTransaction, TransactionRecord::updateStatus, getblocktemplate, TxToJSON, WalletTxToJSON, getreceivedbyaddress, getreceivedbyaccount, ListReceived, ListTransactions, CWallet::ReacceptWalletTransactions, CWallet::GetAnonymizableBalance, CWallet::AvailableCoins, CWallet::GetNewMint, CWallet::GetAddressBalances, CWalletTx::GetCredit, CWalletTx::GetImmatureCredit, CWalletTx::GetAvailableCredit, CWalletTx::GetAnonymizableCredit, CWalletTx::GetDenominatedCredit, CWalletTx::GetImmatureWatchOnlyCredit, CWalletTx::GetAvailableWatchOnlyCredit.
bool CTransaction::IsCoinStake() const
Referenced by CBlock::ConnectBlock, Reorganize, CheckProofOfStake, AcceptToMemoryPool, AcceptableInputs, CWalletTx::AcceptWalletTransaction, CTransactionPoS::ConnectInputs, CreateNewBlock, ToString, CheckTransaction, TransactionDesc::toHTML, TransactionRecord::decomposeTransaction, getblocktemplate, WalletTxToJSON, getreceivedbyaddress, getreceivedbyaccount, ListReceived, ListTransactions, CWallet::SyncTransaction, CWallet::ReacceptWalletTransactions, CWallet::GetWatchOnlyStake, CWallet::AvailableCoins, CWallet::GetStake, CWallet::GetAddressBalances, CWallet::DisableTransaction, CWalletTx::GetCredit, CWalletTx::GetAvailableCredit, CWalletTx::GetAnonymizableCredit, CWalletTx::GetDenominatedCredit, CWalletTx::GetImmatureWatchOnlyCredit, CWalletTx::GetAvailableWatchOnlyCredit.
CAmount CTransaction::GetValueOut() const
References vout, MoneyRange.
Referenced by CStormnodeBlockPayees::IsTransactionValid.
double CTransaction::ComputePriority(double dPriorityInputs, unsigned int nTxSize=0) const
References GetSerializeSize, SER_NETWORK, vin, CTxIn::scriptSig.
Referenced by CCoinsViewCache::GetPriority.
bool CTransaction::CheckTransaction(CValidationState &state)
References vin, DoS, vout, GetSerializeSize, SER_NETWORK, CTxOut::IsEmpty, IsCoinBase, IsCoinStake, CTxOut::nValue, MoneyRange, CTxIn::prevout, COutPoint::IsNull.
Referenced by CBlock::CheckBlock, AcceptToMemoryPool, AcceptableInputs, CTxDB::LoadBlockIndex.
std::string CTransaction::ToString() const
References IsCoinBase, IsCoinStake, strprintf, GetHash, nTime, nVersion, vin, vout, nLockTime.
Referenced by IsIXTXValid, CTransactionPoS::FetchInputs, CTransactionPoS::ConnectInputs, TransactionDesc::toHTML, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::CheckFinalTransaction, CSandstormPool::IsCollateralValid, CSandstormPool::SendSandstormDenominate, IsBudgetCollateralValid, IsBlockPayeeValid, CWallet::CommitTransaction.
bool operator==(const CTransaction &a, const CTransaction &b)
bool operator!=(const CTransaction &a, const CTransaction &b)