StatisticsPage
int StatisticsPage::heightPrevious
Referenced by updateStatistics, updatePrevious.
int StatisticsPage::connectionPrevious
Referenced by updateStatistics, updatePrevious.
int StatisticsPage::volumePrevious
Referenced by updateStatistics, updatePrevious.
double StatisticsPage::rewardPrevious
Referenced by updatePrevious.
double StatisticsPage::netPawratePrevious
Referenced by updatePrevious.
QString StatisticsPage::pawratePrevious
Referenced by updateStatistics, updatePrevious.
double StatisticsPage::hardnessPrevious
Referenced by updatePrevious.
double StatisticsPage::hardnessPrevious2
Referenced by updateStatistics, updatePrevious.
Ui::StatisticsPage* StatisticsPage::ui
ClientModel* StatisticsPage::model
StatisticsPage::StatisticsPage(QWidget *parent=0)
References updateStatistics.
StatisticsPage::~StatisticsPage()
void StatisticsPage::setModel(ClientModel *model)
References updateStatistics.
void StatisticsPage::updateStatistics()
References GetDifficulty, GetLastBlockIndex, pindexBest, GetPoWMHashPS, CBlockIndex::nHeight, CBlockIndex::nMoneySupply, ClientModel::getNumConnections, phase, ClientModel::getLastBlockDate, heightPrevious, stakecPrevious, hardnessPrevious2, pawratePrevious, connectionPrevious, volumePrevious, updatePrevious.
Referenced by StatisticsPage, setModel.
void StatisticsPage::updatePrevious(int, QString, double, double, double, double, QString, int, int)
References heightPrevious, stakecPrevious, phase, rewardPrevious, hardnessPrevious, hardnessPrevious2, netPawratePrevious, pawratePrevious, connectionPrevious, volumePrevious.
Referenced by updateStatistics.