MessageModel
int MessageModel::rowCount(const QModelIndex &parent) const
References MessageTablePriv::cachedMessageTable.
int MessageModel::columnCount(const QModelIndex &parent) const
QVariant MessageModel::data(const QModelIndex &index, int role) const
References Label, MessageTableEntry::label, ToAddress, MessageTableEntry::to_address, FromAddress, MessageTableEntry::from_address, SentDateTime, MessageTableEntry::sent_datetime, ReceivedDateTime, MessageTableEntry::received_datetime, Message, MessageTableEntry::message, TypeInt, MessageTableEntry::type, HTML, Type, MessageTableEntry::Sent, Sent, MessageTableEntry::Received, Received, Key, MessageTableEntry::chKey, KeyRole, TypeRole, SentDateRole, ReceivedDateRole, FromAddressRole, ToAddressRole, FilterAddressRole, LabelRole, MessageRole, ShortMessageRole, HTMLRole, Ambiguous, ambiguous.
Referenced by index, SendMessagesDialog::loadRow, SendMessagesEntry::loadRow.
QVariant MessageModel::headerData(int section, Qt::Orientation orientation, int role) const
QModelIndex MessageModel::index(int row, int column, const QModelIndex &parent) const
References data, MessageTablePriv::index.
Referenced by SendMessagesDialog::loadRow, SendMessagesEntry::loadRow.
bool MessageModel::removeRows(int row, int count, const QModelIndex &parent=QModelIndex())
References MessageTablePriv::index, LOCK, cs_smsgDB, SecMsgDB::Open, SecMsgDB::EraseSmesg, MessageTableEntry::chKey, MessageTablePriv::cachedMessageTable.
Qt::ItemFlags MessageModel::flags(const QModelIndex &index) const
StatusCode
ColumnIndex
Sent/Received
RoleIndex
Type of message
const QString MessageModel::Sent
Specifies sent message
Referenced by data.
const QString MessageModel::Received
Specifies sent message
Referenced by data, SendMessagesDialog::loadRow, SendMessagesEntry::loadRow.
QSortFilterProxyModel* MessageModel::proxyModel
Referenced by MessageTablePriv::walletUnlocked, MessageModel, ~MessageModel, MessagePage::setModel, MessagePage::exportClicked.
CWallet* MessageModel::wallet
WalletModel* MessageModel::walletModel
OptionsModel* MessageModel::optionsModel
MessageTablePriv* MessageModel::priv
QStringList MessageModel::columns
friend class MessageTablePriv
Referenced by MessageModel.
MessageModel::MessageModel(CWallet *wallet, WalletModel *walletModel, QObject *parent=0)
References proxyModel, WalletModel::getOptionsModel, MessageTablePriv, MessageTablePriv::refreshMessageTable.
MessageModel::~MessageModel()
References proxyModel.
int MessageModel::lookupMessage(const QString &message) const
WalletModel * MessageModel::getWalletModel()
Referenced by MessageTablePriv::refreshMessageTable, MessageTablePriv::newMessage, MessageTablePriv::newOutboxMessage, SendMessagesEntry::validate.
OptionsModel * MessageModel::getOptionsModel()
void MessageModel::resetFilter()
References ambiguous.
Referenced by MessageTablePriv::walletUnlocked.
bool MessageModel::getAddressOrPubkey(QString &Address, QString &Pubkey) const
References SecureMsgGetStoredKey, SecureMsgGetLocalKey, base_uint< BITS >::ToString, EncodeBase58, CPubKey::Raw.
MessageModel::StatusCode MessageModel::sendMessages(const QList< SendMessagesRecipient > &recipients)
MessageModel::StatusCode MessageModel::sendMessages(const QList< SendMessagesRecipient > &recipients, const QString &addressFrom)
References OK, WalletModel::validateAddress, SendMessagesRecipient::address, InvalidAddress, SendMessagesRecipient::message, MessageCreationFailed, SendMessagesRecipient::pubkey, SecureMsgAddAddress, SecureMsgSend, arg, FailedErrorShown, CDarkSilkAddress::Get, SendMessagesRecipient::label, LOCK, CWallet::cs_wallet, CWallet::mapAddressBook, CWallet::SetAddressBookName, DuplicateAddress.
void MessageModel::subscribeToCoreSignals()
void MessageModel::unsubscribeFromCoreSignals()
void MessageModel::newMessage(const SecMsgStored &smsg)
References MessageTablePriv::newMessage.
void MessageModel::newOutboxMessage(const SecMsgStored &smsg)
References MessageTablePriv::newOutboxMessage.
void MessageModel::walletUnlocked()
References MessageTablePriv::walletUnlocked.
void MessageModel::setEncryptionStatus(int status)
References MessageTablePriv::setEncryptionStatus.
void MessageModel::error(const QString &title, const QString &message, bool modal)