CFinalizedBudgetVote
bool CFinalizedBudgetVote::fValid
Referenced by CBudgetManager::ProcessMessage, CFinalizedBudgetVote.
bool CFinalizedBudgetVote::fSynced
Referenced by CFinalizedBudgetVote.
CTxIn CFinalizedBudgetVote::vin
Referenced by CFinalizedBudget::AddOrUpdateVote, CFinalizedBudgetVote, Sign, SignatureValid.
uint256 CFinalizedBudgetVote::nBudgetHash
Referenced by CBudgetManager::UpdateFinalizedBudget, CFinalizedBudgetVote, Sign, SignatureValid.
int64_t CFinalizedBudgetVote::nTime
Referenced by CFinalizedBudget::AddOrUpdateVote, CFinalizedBudgetVote, Sign, SignatureValid.
std::vector<unsigned char> CFinalizedBudgetVote::vchSig
Referenced by CFinalizedBudgetVote, Sign, SignatureValid.
CFinalizedBudgetVote::ADD_SERIALIZE_METHODS
CFinalizedBudgetVote::CFinalizedBudgetVote()
References vin, nBudgetHash, nTime, vchSig, fValid, fSynced.
CFinalizedBudgetVote::CFinalizedBudgetVote(CTxIn vinIn, uint256 nBudgetHashIn)
References vin, nBudgetHash, nTime, GetAdjustedTime, vchSig, fValid, fSynced.
bool CFinalizedBudgetVote::Sign(CKey &keyStormnode, CPubKey &pubKeyStormnode)
References vin, CTxIn::prevout, COutPoint::ToStringShort, nBudgetHash, base_uint< BITS >::ToString, nTime, sandStormSigner, CSandStormSigner::SignMessage, vchSig, LogPrintf, CSandStormSigner::VerifyMessage.
Referenced by snfinalbudget, CFinalizedBudget::SubmitVote.
bool CFinalizedBudgetVote::SignatureValid(bool fSignatureCheck)
References vin, CTxIn::prevout, COutPoint::ToStringShort, nBudgetHash, base_uint< BITS >::ToString, nTime, snodeman, CStormnodeMan::Find, LogPrintf, sandStormSigner, CSandStormSigner::VerifyMessage, vchSig.
void CFinalizedBudgetVote::Relay()
References MSG_BUDGET_FINALIZED_VOTE, GetHash, RelayInv.
Referenced by snfinalbudget, CFinalizedBudget::SubmitVote.
uint256 CFinalizedBudgetVote::GetHash()
References SER_GETHASH, CHashWriter::GetHash.
Referenced by snfinalbudget, CFinalizedBudget::AddOrUpdateVote, CFinalizedBudget::SubmitVote, Relay.
void CFinalizedBudgetVote::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE.