leveldb::log::LogTest
StringDest leveldb::log::LogTest::dest_
StringSource leveldb::log::LogTest::source_
ReportCollector leveldb::log::LogTest::report_
bool leveldb::log::LogTest::reading_
Writer leveldb::log::LogTest::writer_
Reader leveldb::log::LogTest::reader_
size_t leveldb::log::LogTest::initial_offset_record_sizes_[]
uint64_t leveldb::log::LogTest::initial_offset_last_record_offsets_[]
leveldb::log::LogTest::LogTest()
void leveldb::log::LogTest::Write(const std::string &msg)
References ASSERT_TRUE, leveldb::log::Writer::AddRecord.
Referenced by WriteInitialOffsetLog.
size_t leveldb::log::LogTest::WrittenBytes() const
Referenced by CheckOffsetPastEndReturnsNoRecords.
std::string leveldb::log::LogTest::Read()
References leveldb::log::Reader::ReadRecord, leveldb::Slice::ToString.
void leveldb::log::LogTest::IncrementByte(int offset, int delta)
void leveldb::log::LogTest::SetByte(int offset, char new_byte)
void leveldb::log::LogTest::ShrinkSize(int bytes)
void leveldb::log::LogTest::FixChecksum(int header_offset, int len)
References leveldb::crc32c::Value, leveldb::crc32c::Mask, leveldb::EncodeFixed32.
void leveldb::log::LogTest::ForceError()
size_t leveldb::log::LogTest::DroppedBytes() const
std::string leveldb::log::LogTest::ReportMessage() const
std::string leveldb::log::LogTest::MatchError(const std::string &msg) const
void leveldb::log::LogTest::WriteInitialOffsetLog()
References Write.
Referenced by CheckOffsetPastEndReturnsNoRecords, CheckInitialOffsetRecord.
void leveldb::log::LogTest::CheckOffsetPastEndReturnsNoRecords(uint64_t offset_past_end)
References WriteInitialOffsetLog, WrittenBytes, ASSERT_TRUE, leveldb::log::Reader::ReadRecord.
void leveldb::log::LogTest::CheckInitialOffsetRecord(uint64_t initial_offset, int expected_record_offset)
References WriteInitialOffsetLog, ASSERT_TRUE, leveldb::log::Reader::ReadRecord, ASSERT_EQ, leveldb::Slice::size, leveldb::log::Reader::LastRecordOffset, leveldb::Slice::data.