leveldb::ModelDB
const Options leveldb::ModelDB::options_
KVMap leveldb::ModelDB::map_
leveldb::ModelDB::ModelDB(const Options &options)
leveldb::ModelDB::~ModelDB()
virtual Status leveldb::ModelDB::Put(const WriteOptions &o, const Slice &k, const Slice &v)
References leveldb::DB::Put.
Referenced by Write, leveldb::TEST.
virtual Status leveldb::ModelDB::Delete(const WriteOptions &o, const Slice &key)
References leveldb::DB::Delete.
Referenced by Write, leveldb::TEST.
virtual Status leveldb::ModelDB::Get(const ReadOptions &options, const Slice &key, std::string *value)
References leveldb::Status::NotFound.
virtual Iterator* leveldb::ModelDB::NewIterator(const ReadOptions &options)
References leveldb::ReadOptions::snapshot.
virtual const Snapshot* leveldb::ModelDB::GetSnapshot()
References leveldb::ModelDB::ModelSnapshot::map_.
Referenced by leveldb::TEST.
virtual void leveldb::ModelDB::ReleaseSnapshot(const Snapshot *snapshot)
Referenced by leveldb::TEST.
virtual Status leveldb::ModelDB::Write(const WriteOptions &options, WriteBatch *batch)
References Put, leveldb::Slice::ToString, Delete, leveldb::WriteBatch::Iterate.
Referenced by leveldb::TEST.
virtual bool leveldb::ModelDB::GetProperty(const Slice &property, std::string *value)
virtual void leveldb::ModelDB::GetApproximateSizes(const Range *r, int n, uint64_t *sizes)
virtual void leveldb::ModelDB::CompactRange(const Slice *start, const Slice *end)