DarkSilkUnits
QList< DarkSilkUnits::Unit > DarkSilkUnits::availableUnits()
Get list of units, for drop-down box.
References DRKSLK, mDRKSLK, uDRKSLK.
bool DarkSilkUnits::valid(int unit)
Is unit ID valid?
References DRKSLK, mDRKSLK, uDRKSLK.
Referenced by format, parse.
QString DarkSilkUnits::name(int unit)
Short name.
References DRKSLK, mDRKSLK, uDRKSLK.
Referenced by formatWithUnit, floorWithUnit, data.
QString DarkSilkUnits::description(int unit)
Longer description.
References DRKSLK, mDRKSLK, uDRKSLK.
Referenced by data.
qint64 DarkSilkUnits::factor(int unit)
Number of Satoshis (1e-8) per unit.
References DRKSLK, mDRKSLK, uDRKSLK.
Referenced by format.
int DarkSilkUnits::amountDigits(int unit)
Number of amount digits (to represent max number of coins)
References DRKSLK, mDRKSLK, uDRKSLK.
int DarkSilkUnits::decimals(int unit)
Number of decimals left.
References DRKSLK, mDRKSLK, uDRKSLK.
Referenced by format, floorWithUnit, parse.
QString DarkSilkUnits::format(int unit, const CAmount &nIn, bool plussign=false)
Format as string.
References valid, factor, decimals.
Referenced by DarkSilkAmountField::setValue, formatWithUnit, floorWithUnit.
QString DarkSilkUnits::formatWithUnit(int unit, const CAmount &amount, bool plussign=false)
Format as string (with unit)
References format, name.
Referenced by CoinControlDialog::updateLabels, DarkSilkGUI::askFee, TxViewDelegate::paint, OverviewPage::setBalance, OverviewPage::updateSandstormProgress, SendCoinsDialog::setBalance, TransactionDesc::toHTML.
bool DarkSilkUnits::parse(int unit, const QString &value, CAmount *val_out)
Parse string to coin amount.
References valid, decimals.
Referenced by DarkSilkAmountField::validate, DarkSilkAmountField::value, GUIUtil::parseDarkSilkURI, TransactionView::changedAmount.
QString DarkSilkUnits::floorWithUnit(int unit, const CAmount &amount, bool plussign=false, SeparatorStyle separators=separatorStandard)
Format as string (with unit) but floor value up to "digits" settings.
References format, decimals, name.
Referenced by floorHtmlWithUnit, OverviewPage::setBalance.
QString DarkSilkUnits::floorHtmlWithUnit(int unit, const CAmount &amount, bool plussign=false, SeparatorStyle separators=separatorStandard)
References floorWithUnit, THIN_SP_CP, THIN_SP_HTML.
QString DarkSilkUnits::format(int unit, const CAmount &nIn, bool fPlus, SeparatorStyle separators)
References valid, factor, decimals.
RoleIndex
Unit identifier
int DarkSilkUnits::rowCount(const QModelIndex &parent) const
QVariant DarkSilkUnits::data(const QModelIndex &index, int role) const
References name, description, UnitRole.
Unit
SeparatorStyle
QList<DarkSilkUnits::Unit> DarkSilkUnits::unitlist
DarkSilkUnits::DarkSilkUnits(QObject *parent)
CAmount DarkSilkUnits::maxMoney()
Return maximum number of base units (Satoshis)