leveldb::InternalKeyComparator
const Comparator* leveldb::InternalKeyComparator::user_comparator_
leveldb::InternalKeyComparator::InternalKeyComparator(const Comparator *c)
const char * leveldb::InternalKeyComparator::Name() const
int leveldb::InternalKeyComparator::Compare(const Slice &a, const Slice &b) const
References leveldb::Comparator::Compare, leveldb::ExtractUserKey, leveldb::DecodeFixed64, leveldb::Slice::data, leveldb::Slice::size.
Referenced by FindShortestSeparator, FindShortSuccessor, Compare, leveldb::VersionSet::Builder::SaveTo, leveldb::VersionSet::Builder::MaybeAddFile, leveldb::VersionSet::ApproximateOffsetOf, leveldb::VersionSet::PickCompaction, leveldb::Compaction::ShouldStopBefore.
void leveldb::InternalKeyComparator::FindShortestSeparator(std::string *start, const Slice &limit) const
References leveldb::ExtractUserKey, leveldb::Slice::data, leveldb::Slice::size, leveldb::Comparator::FindShortestSeparator, leveldb::Comparator::Compare, leveldb::PutFixed64, Compare.
void leveldb::InternalKeyComparator::FindShortSuccessor(std::string *key) const
References user_key, leveldb::ExtractUserKey, leveldb::Slice::data, leveldb::Slice::size, leveldb::Comparator::FindShortSuccessor, leveldb::Comparator::Compare, leveldb::PutFixed64, Compare.
const Comparator* leveldb::InternalKeyComparator::user_comparator() const
Referenced by leveldb::SomeFileOverlapsRange, leveldb::Version::Get, leveldb::Version::GetOverlappingInputs, leveldb::VersionSet::Recover, leveldb::Compaction::IsBaseLevelForKey.
int leveldb::InternalKeyComparator::Compare(const InternalKey &a, const InternalKey &b) const
References Compare, leveldb::InternalKey::Encode.