CSandstormQueue
CTxIn CSandstormQueue::vin
Referenced by CSandstormPool::ProcessMessageSandstorm, CSandstormPool::CheckForCompleteQueue, CSandstormPool::DoAutomaticDenominating, CSandstormPool::IsCompatibleWithSession.
int64_t CSandstormQueue::time
Referenced by CSandstormPool::CheckForCompleteQueue, CSandstormPool::DoAutomaticDenominating, CSandstormPool::IsCompatibleWithSession.
int CSandstormQueue::nDenom
Referenced by CSandstormPool::CheckForCompleteQueue, CSandstormPool::DoAutomaticDenominating, CSandstormPool::IsCompatibleWithSession.
bool CSandstormQueue::ready
Referenced by CSandstormPool::CheckForCompleteQueue.
std::vector<unsigned char> CSandstormQueue::vchSig
CSandstormQueue::ADD_SERIALIZE_METHODS
CSandstormQueue::CSandstormQueue()
void CSandstormQueue::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE.
bool CSandstormQueue::GetAddress(CService &addr)
References snodeman, CStormnodeMan::Find, CStormnode::addr.
Referenced by CSandstormPool::DoAutomaticDenominating.
bool CSandstormQueue::GetProtocolVersion(int &protocolVersion)
Get the protocol version.
References snodeman, CStormnodeMan::Find, CStormnode::protocolVersion.
Referenced by CSandstormPool::DoAutomaticDenominating.
bool CSandstormQueue::Sign()
Sign this Sandstorm transaction true if all conditions are met: 1) we have an active Stormnode, 2) we have a valid Stormnode private key, 3) we signed the message successfully, and 4) we verified the message successfully
References fStormNode, CSandStormSigner::SetKey, strStormNodePrivKey, LogPrintf, CSandStormSigner::SignMessage, CSandStormSigner::VerifyMessage.
Referenced by CSandstormPool::CheckForCompleteQueue, CSandstormPool::IsCompatibleWithSession.
bool CSandstormQueue::Relay()
References LOCK, cs_vNodes, vNodes, CNode::PushMessage.
Referenced by CSandstormPool::CheckForCompleteQueue, CSandstormPool::IsCompatibleWithSession.
bool CSandstormQueue::IsExpired()
Is this Sandstorm expired?
References GetTime, SANDSTORM_QUEUE_TIMEOUT.
Referenced by CSandstormPool::DoAutomaticDenominating.
bool CSandstormQueue::CheckSignature()
Check if we have a valid Stormnode address.
References snodeman, CStormnodeMan::Find, CSandStormSigner::VerifyMessage, CStormnode::pubkey2.