SendMessagesDialog
Mode
Type
Ui::SendMessagesDialog* SendMessagesDialog::ui
MessageModel* SendMessagesDialog::model
bool SendMessagesDialog::fNewRecipientAllowed
Mode SendMessagesDialog::mode
Type SendMessagesDialog::type
SendMessagesDialog::SendMessagesDialog(Mode mode, Type type, QWidget *parent=0)
References Encrypted, addEntry, clear, reject, Anonymous, Page.
SendMessagesDialog::~SendMessagesDialog()
void SendMessagesDialog::setModel(MessageModel *model)
References SendMessagesEntry::setModel.
void SendMessagesDialog::loadRow(int row)
References MessageModel::data, MessageModel::index, MessageModel::Type, MessageModel::Received, MessageModel::ToAddress, MessageModel::FromAddress, SendMessagesEntry::loadRow.
bool SendMessagesDialog::checkMode(Mode mode)
bool SendMessagesDialog::validate()
References Encrypted.
QWidget * SendMessagesDialog::setupTabChain(QWidget *prev)
Set up the tab chain manually, as Qt messes up the tab chain by default in some cases (issue https://bugreports.qt-project.org/browse/QTBUG-10907).
References SendMessagesEntry::setupTabChain.
Referenced by updateRemoveEnabled.
void SendMessagesDialog::pasteEntry(const SendMessagesRecipient &rv)
References SendMessagesEntry::isClear, addEntry, SendMessagesEntry::setValue.
void SendMessagesDialog::done(int retval)
References Dialog, clear.
Referenced by reject, accept.
void SendMessagesDialog::clear()
References addEntry, updateRemoveEnabled.
Referenced by SendMessagesDialog, reject, accept, done.
void SendMessagesDialog::reject()
References Dialog, done, clear.
Referenced by SendMessagesDialog.
void SendMessagesDialog::accept()
References Dialog, done, clear.
SendMessagesEntry * SendMessagesDialog::addEntry()
References SendMessagesEntry::setModel, updateRemoveEnabled, SendMessagesEntry::clear, SendMessagesEntry::setFocus.
Referenced by SendMessagesDialog, clear, pasteEntry.
void SendMessagesDialog::updateRemoveEnabled()
References SendMessagesEntry::setRemoveEnabled, setupTabChain.
Referenced by clear, addEntry.
void SendMessagesDialog::on_sendButton_clicked()
void SendMessagesDialog::removeEntry(SendMessagesEntry *entry)
void SendMessagesDialog::on_addressBookButton_clicked()
void SendMessagesDialog::on_pasteButton_clicked()