CDBEnv
VerifyResult
typedef std::pair<std::vector<unsigned char>, std::vector<unsigned char> > CDBEnv::KeyValPair
bool CDBEnv::fDbEnvInit
bool CDBEnv::fMockDb
boost::filesystem::path CDBEnv::pathEnv
std::string CDBEnv::strPath
CCriticalSection CDBEnv::cs_db
Referenced by Verify, Salvage, CDB::CDB, CDB::Close, CloseDb, RemoveDb, CDB::Rewrite, Flush, ThreadFlushWalletDB, BackupWallet.
DbEnv CDBEnv::dbenv
Referenced by Open, MakeMock, Salvage, CheckpointLSN, CDB::CDB, CDB::Flush, RemoveDb, CDB::Rewrite, Flush, CWalletDB::Recover.
std::map<std::string, int> CDBEnv::mapFileUseCount
Referenced by Verify, Salvage, CDB::CDB, CDB::Close, CDB::Rewrite, Flush, ThreadFlushWalletDB, BackupWallet.
std::map<std::string, Db*> CDBEnv::mapDb
Referenced by CDB::CDB, CloseDb.
void CDBEnv::EnvShutdown()
CDBEnv::CDBEnv()
CDBEnv::~CDBEnv()
void CDBEnv::MakeMock()
References dbenv, strprintf.
bool CDBEnv::IsMock()
Referenced by CDB::CDB.
CDBEnv::VerifyResult CDBEnv::Verify(std::string strFile, bool(*recoverFunc)(CDBEnv &dbenv, std::string strFile))
References LOCK, cs_db, mapFileUseCount, VERIFY_OK, RECOVER_FAIL, RECOVER_OK.
Referenced by AppInit2.
bool CDBEnv::Salvage(std::string strFile, bool fAggressive, std::vector< KeyValPair > &vResult)
References LOCK, cs_db, mapFileUseCount, dbenv, LogPrintf, ParseHex.
Referenced by CWalletDB::Recover.
bool CDBEnv::Open(boost::filesystem::path pathEnv_)
References LogPrintf, GetBoolArg, GetArg, dbenv.
Referenced by CDB::CDB, AppInit2.
void CDBEnv::Close()
Referenced by Flush.
void CDBEnv::Flush(bool fShutdown)
References GetTimeMillis, LOCK, cs_db, mapFileUseCount, CloseDb, dbenv, Close.
Referenced by Shutdown.
void CDBEnv::CheckpointLSN(const std::string &strFile)
References dbenv.
Referenced by CDB::Rewrite, ThreadFlushWalletDB, BackupWallet.
void CDBEnv::CloseDb(const std::string &strFile)
References LOCK, cs_db, mapDb.
Referenced by RemoveDb, CDB::Rewrite, Flush, ThreadFlushWalletDB, BackupWallet.
bool CDBEnv::RemoveDb(const std::string &strFile)
References CloseDb, LOCK, cs_db, dbenv.
DbTxn* CDBEnv::TxnBegin(int flags=DB_TXN_WRITE_NOSYNC)
Referenced by CDB::TxnBegin, CWalletDB::Recover.