PeerTablePriv
QList<CNodeCombinedStats> PeerTablePriv::cachedNodeStats
Local cache of peer information
int PeerTablePriv::sortColumn
Column to sort nodes by
Referenced by PeerTableModel::PeerTableModel, PeerTableModel::sort.
Qt::SortOrder PeerTablePriv::sortOrder
Order (ascending or descending) to sort nodes by
Referenced by PeerTableModel::sort.
std::map<NodeId, int> PeerTablePriv::mapNodeRows
Index of rows by node ID
Referenced by PeerTableModel::getRowByNodeId.
void PeerTablePriv::refreshPeers()
Pull a full list of peers from vNodes into our cache
References TRY_LOCK, cs_vNodes, vNodes, stats, CNodeCombinedStats::nodeStateStats, CNodeStateStats::nMisbehavior, CNodeStateStats::nSyncHeight, CNodeCombinedStats::fNodeStateStatsAvailable, CNode::copyStats, CNodeCombinedStats::nodeStats, cs_main, GetNodeStateStats, CNodeStats::nodeid.
Referenced by PeerTableModel::refresh.
int PeerTablePriv::size()
Referenced by PeerTableModel::rowCount.
CNodeCombinedStats* PeerTablePriv::index(int idx)
Referenced by PeerTableModel::index, PeerTableModel::getNodeStats.