leveldb::FilterPolicy
leveldb::FilterPolicy::~FilterPolicy()
virtual const char* leveldb::FilterPolicy::Name() const =0
Referenced by leveldb_filterpolicy_create_bloom, leveldb::InternalFilterPolicy::Name, leveldb::TableBuilder::Finish.
virtual void leveldb::FilterPolicy::CreateFilter(const Slice *keys, int n, std::string *dst) const =0
Referenced by leveldb_filterpolicy_create_bloom, leveldb::InternalFilterPolicy::CreateFilter, leveldb::BloomTest::Build.
virtual bool leveldb::FilterPolicy::KeyMayMatch(const Slice &key, const Slice &filter) const =0
Referenced by leveldb_filterpolicy_create_bloom, leveldb::InternalFilterPolicy::KeyMayMatch, leveldb::FilterBlockReader::KeyMayMatch, leveldb::BloomTest::Matches.