CStormnodeBroadcast
CStormnodeBroadcast::ADD_SERIALIZE_METHODS
CStormnodeBroadcast::CStormnodeBroadcast()
References CStormnode::vin, CStormnode::addr, CStormnode::pubkey, CStormnode::pubkey2, CStormnode::sig, CStormnode::activeState, CStormnode::STORMNODE_ENABLED, CStormnode::sigTime, GetAdjustedTime, CStormnode::lastPing, CStormnode::cacheInputAge, CStormnode::cacheInputAgeBlock, CStormnode::unitTest, CStormnode::allowFreeTx, CStormnode::protocolVersion, CStormnode::nLastSsq, CStormnode::nScanningErrorCount, CStormnode::nLastScanningErrorBlockHeight.
CStormnodeBroadcast::CStormnodeBroadcast(CService newAddr, CTxIn newVin, CPubKey newPubkey, CPubKey newPubkey2, int protocolVersionIn)
References CStormnode::vin, CStormnode::addr, CStormnode::pubkey, CStormnode::pubkey2, CStormnode::sig, CStormnode::activeState, CStormnode::STORMNODE_ENABLED, CStormnode::sigTime, GetAdjustedTime, CStormnode::lastPing, CStormnode::cacheInputAge, CStormnode::cacheInputAgeBlock, CStormnode::unitTest, CStormnode::allowFreeTx, CStormnode::protocolVersion, CStormnode::nLastSsq, CStormnode::nScanningErrorCount, CStormnode::nLastScanningErrorBlockHeight.
CStormnodeBroadcast::CStormnodeBroadcast(const CStormnode &sn)
References CStormnode::vin, CStormnode::addr, CStormnode::pubkey, CStormnode::pubkey2, CStormnode::sig, CStormnode::activeState, CStormnode::sigTime, CStormnode::lastPing, CStormnode::cacheInputAge, CStormnode::cacheInputAgeBlock, CStormnode::unitTest, CStormnode::allowFreeTx, CStormnode::protocolVersion, CStormnode::nLastSsq, CStormnode::nScanningErrorCount, CStormnode::nLastScanningErrorBlockHeight.
bool CStormnodeBroadcast::CheckAndUpdate(int &nDoS)
References CStormnode::sigTime, GetAdjustedTime, LogPrintf, CStormnode::vin, CTxIn::ToString, CStormnode::pubkey, CPubKey::begin, CPubKey::end, CStormnode::pubkey2, CStormnode::addr, CService::ToString, CStormnode::protocolVersion, stormnodePayments, CStormnodePayments::GetMinStormnodePaymentsProto, GetScriptForDestination, CPubKey::GetID, CTxIn::scriptSig, sandStormSigner, CSandStormSigner::VerifyMessage, CStormnode::sig, Params, CChainParams::MAIN, CService::GetPort, snodeman, CStormnodeMan::Find, CStormnode::IsEnabled, CStormnode::IsBroadcastedWithin, CStormnode::UpdateFromNewBroadcast, CStormnode::Check, Relay, stormnodeSync, CStormnodeSync::AddedStormnodeList, GetHash.
bool CStormnodeBroadcast::CheckInputsAndAdd(int &nDos)
References fStormNode, CStormnode::vin, CTxIn::prevout, activeStormnode, CActiveStormnode::vin, CStormnode::pubkey2, CActiveStormnode::pubKeyStormnode, snodeman, CStormnodeMan::Find, CStormnode::IsEnabled, CStormnode::IsPreEnabled, CStormnodeMan::Remove, sandStormPool, CSandstormPool::collateralPubKey, CTransaction::vin, CTransaction::vout, TRY_LOCK, cs_main, CStormnodeMan::mapSeenStormnodeBroadcast, GetHash, stormnodeSync, CStormnodeSync::mapSeenSyncSNB, AcceptableInputs, mempool, CValidationState::IsInvalid, GetInputAge, LogPrintf, GetTransaction, COutPoint::hash, CStormnode::addr, CService::ToString, CTxIn::ToString, CStormnode::sigTime, CStormnodeMan::Add, CStormnode::protocolVersion, CActiveStormnode::EnableHotColdStormNode, CNetAddr::IsRFC1918, CNetAddr::IsLocal, Relay.
bool CStormnodeBroadcast::Sign(CKey &keyCollateralAddress)
References CStormnode::pubkey, CPubKey::begin, CPubKey::end, CStormnode::pubkey2, CStormnode::sigTime, GetAdjustedTime, CStormnode::addr, CService::ToString, CStormnode::protocolVersion, sandStormSigner, CSandStormSigner::SignMessage, CStormnode::sig, LogPrintf, CSandStormSigner::VerifyMessage.
void CStormnodeBroadcast::Relay()
References MSG_STORMNODE_ANNOUNCE, GetHash, RelayInv.
Referenced by CheckAndUpdate, CheckInputsAndAdd.
void CStormnodeBroadcast::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE.
uint256 CStormnodeBroadcast::GetHash()
References SER_GETHASH, CHashWriter::GetHash.
Referenced by CheckAndUpdate, CheckInputsAndAdd, Relay, CStormnodePing::CheckAndUpdate, CStormnodeMan::ProcessMessage.