SendMessagesEntry
Ui::SendMessagesEntry* SendMessagesEntry::ui
MessageModel* SendMessagesEntry::model
SendMessagesEntry::SendMessagesEntry(QWidget *parent=0)
References GUIUtil::setupAddressWidget.
SendMessagesEntry::~SendMessagesEntry()
void SendMessagesEntry::setModel(MessageModel *model)
Referenced by SendMessagesDialog::setModel, SendMessagesDialog::addEntry.
void SendMessagesEntry::loadRow(int row)
References MessageModel::data, MessageModel::index, MessageModel::Type, MessageModel::Received, MessageModel::FromAddress, MessageModel::ToAddress.
Referenced by SendMessagesDialog::loadRow.
bool SendMessagesEntry::validate()
References MessageModel::getWalletModel, WalletModel::validateAddress.
SendMessagesRecipient SendMessagesEntry::getValue()
References SendMessagesRecipient::address, SendMessagesRecipient::label, SendMessagesRecipient::pubkey, SendMessagesRecipient::message.
bool SendMessagesEntry::isClear()
Return whether the entry is still empty and unedited
Referenced by SendMessagesDialog::pasteEntry.
void SendMessagesEntry::setValue(const SendMessagesRecipient &value)
References SendMessagesRecipient::address, SendMessagesRecipient::label, SendMessagesRecipient::pubkey, SendMessagesRecipient::message.
Referenced by SendMessagesDialog::pasteEntry.
QWidget * SendMessagesEntry::setupTabChain(QWidget *prev)
Set up the tab chain manually, as Qt messes up the tab chain by default in some cases (issue https://bugreports.qt-project.org/browse/QTBUG-10907).
Referenced by SendMessagesDialog::setupTabChain.
void SendMessagesEntry::setFocus()
Referenced by SendMessagesDialog::addEntry.
void SendMessagesEntry::setRemoveEnabled(bool enabled)
Referenced by SendMessagesDialog::updateRemoveEnabled.
void SendMessagesEntry::clear()
Referenced by SendMessagesDialog::addEntry.
void SendMessagesEntry::removeEntry(SendMessagesEntry *entry)
void SendMessagesEntry::on_deleteButton_clicked()
void SendMessagesEntry::on_addressBookButton_clicked()
void SendMessagesEntry::on_pasteButton_clicked()
void SendMessagesEntry::on_sendTo_textChanged(const QString &address)