OptionsDialog
Ui::OptionsDialog* OptionsDialog::ui
OptionsModel* OptionsDialog::model
MonitoredDataMapper* OptionsDialog::mapper
bool OptionsDialog::fRestartWarningDisplayed_Proxy
bool OptionsDialog::fRestartWarningDisplayed_Lang
bool OptionsDialog::fProxyIpValid
OptionsDialog::OptionsDialog(QWidget *parent=0)
References proxyIpValid.
OptionsDialog::~OptionsDialog()
void OptionsDialog::setModel(OptionsModel *model)
References setMapper.
void OptionsDialog::setMapper()
References MonitoredDataMapper::addMapping, OptionsModel::Fee, OptionsModel::ReserveBalance, OptionsModel::StartAtStartup, OptionsModel::MapPortUPnP, OptionsModel::ProxyUse, OptionsModel::ProxyIP, OptionsModel::ProxyPort, OptionsModel::MinimizeToTray, OptionsModel::MinimizeOnClose, OptionsModel::Language, OptionsModel::DisplayUnit, OptionsModel::CoinControlFeatures, OptionsModel::SandstormRounds, OptionsModel::AnonymizeDarkSilkAmount.
Referenced by setModel.
bool OptionsDialog::eventFilter(QObject *object, QEvent *event)
References proxyIpValid, LookupNumeric.
void OptionsDialog::enableApplyButton()
void OptionsDialog::disableApplyButton()
void OptionsDialog::enableSaveButtons()
void OptionsDialog::disableSaveButtons()
void OptionsDialog::setSaveButtonState(bool fState)
void OptionsDialog::on_okButton_clicked()
void OptionsDialog::on_cancelButton_clicked()
void OptionsDialog::on_applyButton_clicked()
void OptionsDialog::showRestartWarning_Proxy()
void OptionsDialog::showRestartWarning_Lang()
void OptionsDialog::updateDisplayUnit()
void OptionsDialog::handleProxyIpValid(QValidatedLineEdit *object, bool fState)
void OptionsDialog::proxyIpValid(QValidatedLineEdit *object, bool fValid)
Referenced by OptionsDialog, eventFilter.