leveldb::WritableFile
leveldb::WritableFile::WritableFile()
leveldb::WritableFile::~WritableFile()
virtual Status leveldb::WritableFile::Append(const Slice &data)=0
Referenced by leveldb::SpecialEnv::NewWritableFile, leveldb::log::Writer::AddRecord, leveldb::TEST, leveldb::TableBuilder::Finish.
virtual Status leveldb::WritableFile::Close()=0
Referenced by leveldb::BuildTable, leveldb::SpecialEnv::NewWritableFile.
virtual Status leveldb::WritableFile::Flush()=0
Referenced by leveldb::SpecialEnv::NewWritableFile, leveldb::TableBuilder::Flush.
virtual Status leveldb::WritableFile::Sync()=0
Referenced by leveldb::BuildTable, leveldb::DBImpl::Write, leveldb::SpecialEnv::NewWritableFile, leveldb::VersionSet::LogAndApply.
leveldb::WritableFile::WritableFile(const WritableFile &)
void leveldb::WritableFile::operator=(const WritableFile &)