leveldb::BlockBuilder
const Options* leveldb::BlockBuilder::options_
std::string leveldb::BlockBuilder::buffer_
std::vector<uint32_t> leveldb::BlockBuilder::restarts_
int leveldb::BlockBuilder::counter_
bool leveldb::BlockBuilder::finished_
std::string leveldb::BlockBuilder::last_key_
leveldb::BlockBuilder::BlockBuilder(const Options *options)
References leveldb::Options::block_restart_interval.
void leveldb::BlockBuilder::Reset()
void leveldb::BlockBuilder::Add(const Slice &key, const Slice &value)
References leveldb::Options::comparator, leveldb::Comparator::Compare, shared, leveldb::Slice::size, leveldb::PutVarint32, leveldb::Slice::data.
Referenced by leveldb::TableBuilder::Add, leveldb::TableBuilder::Finish, leveldb::BlockConstructor::FinishImpl.
Slice leveldb::BlockBuilder::Finish()
References leveldb::PutFixed32.
Referenced by leveldb::BlockConstructor::FinishImpl.
size_t leveldb::BlockBuilder::CurrentSizeEstimate() const
Referenced by leveldb::TableBuilder::Add.
bool leveldb::BlockBuilder::empty() const
Referenced by leveldb::TableBuilder::Add, leveldb::TableBuilder::Flush.
leveldb::BlockBuilder::BlockBuilder(const BlockBuilder &)
void leveldb::BlockBuilder::operator=(const BlockBuilder &)