leveldb::DB
Status leveldb::DB::Open(const Options &options, const std::string &name, DB **dbptr)
References leveldb::port::Mutex::Lock, leveldb::Status::ok, leveldb::VersionSet::NewFileNumber, leveldb::Options::env, leveldb::Env::NewWritableFile, leveldb::LogFileName, leveldb::VersionEdit::SetLogNumber, leveldb::VersionSet::LogAndApply, leveldb::port::Mutex::Unlock.
Referenced by leveldb::AutoCompactTest::AutoCompactTest, leveldb::CorruptionTest::TryReopen, leveldb::DBTest::TryReopen, leveldb::TEST, leveldb::BM_LogAndApply, CLevelDBWrapper::CLevelDBWrapper, SecMsgDB::Open.
leveldb::DB::DB()
leveldb::DB::~DB()
Status leveldb::DB::Put(const WriteOptions &options, const Slice &key, const Slice &value)=0
References leveldb::WriteBatch::Put, Write.
Referenced by leveldb::AutoCompactTest::DoReads, leveldb_put, leveldb::DBImpl::Put, leveldb::DBTest::Put, leveldb::ModelDB::Put, leveldb::TEST, SecMsgDB::WritePK, SecMsgDB::WriteSmesg, CTxDB::Write.
Status leveldb::DB::Delete(const WriteOptions &options, const Slice &key)=0
References leveldb::WriteBatch::Delete, Write.
Referenced by leveldb::AutoCompactTest::DoReads, leveldb_delete, leveldb::DBImpl::Delete, leveldb::DBTest::Delete, leveldb::ModelDB::Delete, SecMsgDB::EraseSmesg, CTxDB::Erase.
virtual Status leveldb::DB::Write(const WriteOptions &options, WriteBatch *updates)=0
Referenced by leveldb_write, leveldb::CorruptionTest::Build, Put, Delete, leveldb::DBConstructor::FinishImpl, SecMsgDB::TxnCommit.
virtual Status leveldb::DB::Get(const ReadOptions &options, const Slice &key, std::string *value)=0
Referenced by leveldb_get, leveldb::DBTest::Get, leveldb::TEST, CLevelDBWrapper::Read, CLevelDBWrapper::Exists, SecMsgDB::ReadPK, SecMsgDB::ExistsPK, SecMsgDB::ReadSmesg, SecMsgDB::ExistsSmesg, CTxDB::Read, CTxDB::Exists.
virtual Iterator* leveldb::DB::NewIterator(const ReadOptions &options)=0
Referenced by leveldb::AutoCompactTest::DoReads, leveldb_create_iterator, leveldb::CorruptionTest::Check, leveldb::DBTest::Contents, leveldb::TEST, leveldb::DBConstructor::NewIterator, CLevelDBWrapper::NewIterator, MessageTablePriv::refreshMessageTable, smsginbox, smsgoutbox, ThreadSecureMsgPow.
virtual const Snapshot* leveldb::DB::GetSnapshot()=0
Referenced by leveldb_create_snapshot.
virtual void leveldb::DB::ReleaseSnapshot(const Snapshot *snapshot)=0
Referenced by leveldb_release_snapshot.
virtual bool leveldb::DB::GetProperty(const Slice &property, std::string *value)=0
Referenced by leveldb_property_value, leveldb::CorruptionTest::Property, leveldb::DBTest::NumTableFilesAtLevel, leveldb::DBTest::DumpSSTableList.
virtual void leveldb::DB::GetApproximateSizes(const Range *range, int n, uint64_t *sizes)=0
Referenced by leveldb::AutoCompactTest::Size, leveldb_approximate_sizes, leveldb::DBTest::Size.
virtual void leveldb::DB::CompactRange(const Slice *begin, const Slice *end)=0
Referenced by leveldb_compact_range, leveldb::DBTest::Compact.
leveldb::DB::DB(const DB &)
void leveldb::DB::operator=(const DB &)