leveldb::BloomTest
const FilterPolicy* leveldb::BloomTest::policy_
std::string leveldb::BloomTest::filter_
std::vector<std::string> leveldb::BloomTest::keys_
leveldb::BloomTest::BloomTest()
leveldb::BloomTest::~BloomTest()
void leveldb::BloomTest::Reset()
void leveldb::BloomTest::Add(const Slice &s)
References leveldb::Slice::ToString.
void leveldb::BloomTest::Build()
References leveldb::FilterPolicy::CreateFilter, DumpFilter.
Referenced by Matches.
size_t leveldb::BloomTest::FilterSize() const
void leveldb::BloomTest::DumpFilter()
Referenced by Build.
bool leveldb::BloomTest::Matches(const Slice &s)
References Build, leveldb::FilterPolicy::KeyMayMatch.
Referenced by FalsePositiveRate.
double leveldb::BloomTest::FalsePositiveRate()
References Matches.