CBlock
std::vector<CTransaction> CBlock::vtx
Referenced by AcceptBlock, DisconnectBlock, RebuildAddressIndex, ConnectBlock, Reorganize, CheckBlock, CBlockIndex::CBlockIndex, CMerkleTx::SetMerkleBranch, GetTransaction, PrintBlockTree, IncrementExtraNonce, CheckWork, CheckStake, CheckBlockSignature, ToString, blockToJSON, getworkex, getwork, getblocktemplate, scanforstealthtxns, IsBlockValueValid, CTxDB::LoadBlockIndex, CWallet::ScanForWalletTransactions.
std::vector<unsigned char> CBlock::vchBlockSig
Referenced by CheckBlockSignature, ToString, blockToJSON.
CScript CBlock::payee
Referenced by getblocktemplate.
std::vector<uint256> CBlock::vMerkleTree
Referenced by ToString.
CBlock::ADD_SERIALIZE_METHODS
CBlock::CBlock()
References SetNull.
Referenced by ConnectBlock.
CBlock::CBlock(const CBlockHeader &header)
References SetNull.
void CBlock::SetNull()
References CBlockHeader::nVersion, CBlockHeader::CURRENT_VERSION, CBlockHeader::hashPrevBlock, CBlockHeader::hashMerkleRoot, CBlockHeader::nTime, CBlockHeader::nBits, CBlockHeader::nNonce, CBlockHeader::nDoS.
Referenced by ReadFromDisk, CBlock.
void CBlock::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References SER_GETHASH, SER_BLOCKHEADERONLY, READWRITE.
void CBlock::UpdateTime(const CBlockIndex *pindexPrev)
References CBlockHeader::nTime, CBlockHeader::GetBlockTime, GetAdjustedTime.
Referenced by getwork, getblocktemplate.
unsigned int CBlock::GetStakeEntropyBit() const
References CBlockHeader::GetHash, base_uint< BITS >::Get64, ToString.
bool CBlock::IsProofOfStake() const
Referenced by AcceptBlock, ConnectBlock, CheckBlock, CBlockIndex::CBlockIndex, IsProofOfWork, GetProofOfStake, ProcessBlock, CheckStake, blockToJSON.
bool CBlock::IsProofOfWork() const
References IsProofOfStake.
Referenced by AcceptBlock, ConnectBlock, CheckBlock, ReadFromDisk, CheckWork, CheckBlockSignature.
std::pair<COutPoint, unsigned int> CBlock::GetProofOfStake() const
References IsProofOfStake, CBlockHeader::nTime.
Referenced by ProcessBlock.
int64_t CBlock::GetMaxTransactionTime() const
References CTransaction::nTime.
uint256 CBlock::BuildMerkleTree() const
References CTransaction::GetHash, Hash, BEGIN, END.
Referenced by CheckBlock, AppInit2, GetMerkleBranch, ProcessBlock, IncrementExtraNonce, getworkex, getwork.
std::vector<uint256> CBlock::GetMerkleBranch(int nIndex) const
References BuildMerkleTree.
Referenced by CMerkleTx::SetMerkleBranch, getworkex.
bool CBlock::WriteToDisk(unsigned int &nFileRet, unsigned int &nBlockPosRet)
References AppendBlockFile, SER_DISK, CAutoFile::GetSerializeSize, FLATDATA, Params, IsInitialBlockDownload, nBestHeight, FileCommit.
Referenced by AcceptBlock, LoadBlockIndex.
bool CBlock::ReadFromDisk(unsigned int nFile, unsigned int nBlockPos, bool fReadTransactions=true)
References SetNull, OpenBlockFile, SER_DISK, CAutoFile::nType, SER_BLOCKHEADERONLY, IsProofOfWork, CheckProofOfWork, CBlockHeader::GetPoWHash, CBlockHeader::nBits.
Referenced by Reorganize, ReadFromDisk, AppInit2, CheckProofOfStake, CheckKernel, CMerkleTx::SetMerkleBranch, CTxIndex::GetDepthInMainChain, GetTransaction, PrintBlockTree, SetBestChain, getblock, getblockbynumber, scanforstealthtxns, ScanChainForPublicKeys, CTxDB::LoadBlockIndex, CWallet::ScanForWalletTransactions.
std::string CBlock::ToString() const
References strprintf, CBlockHeader::GetHash, CBlockHeader::nVersion, CBlockHeader::hashPrevBlock, base_uint< BITS >::ToString, CBlockHeader::hashMerkleRoot, CBlockHeader::nTime, CBlockHeader::nBits, CBlockHeader::nNonce, vtx, HexStr, vchBlockSig, vMerkleTree.
Referenced by AppInit2, GetStakeEntropyBit, CheckWork, CheckStake.
bool CBlock::DisconnectBlock(CTxDB &txdb, CBlockIndex *pindex)
References vtx, CTransactionPoS::DisconnectInputs, CBlockIndex::pprev, CDiskBlockIndex::hashNext, CTxDB::WriteBlockIndex, SyncWithWallets.
Referenced by Reorganize.
bool CBlock::ConnectBlock(CTxDB &txdb, CBlockIndex *pindex, bool fJustCheck=false)
References state, CheckBlock, SCRIPT_VERIFY_NOCACHE, SCRIPT_VERIFY_NULLDUMMY, SCRIPT_VERIFY_STRICTENC, SCRIPT_VERIFY_ALLOW_EMPTY_SIG, SCRIPT_VERIFY_FIX_HASHTYPE, SCRIPT_VERIFY_CHECKLOCKTIMEVERIFY, CBlockIndex::nBlockPos, GetSerializeSize, CBlock, SER_DISK, GetSizeOfCompactSize, vtx, GetTimeMicros, CTransaction::GetHash, CTransaction::vin, GetLegacySigOpCount, CBlockHeader::DoS, CBlockIndex::nFile, CTransaction::IsCoinBase, CTransactionPoS::GetValueOut, CTransactionPoS::FetchInputs, GetP2SHSigOpCount, CTransactionPoS::GetValueIn, CTransaction::IsCoinStake, CTransactionPoS::ConnectInputs, CTransaction::vout, fDebug, LogPrintf, IsProofOfWork, GetProofOfWorkReward, IsProofOfStake, CBlockIndex::nMint, CBlockIndex::nMoneySupply, CBlockIndex::pprev, CTxDB::WriteBlockIndex, CTxDB::UpdateTxIndex, CTxOut::scriptPubKey, CTxDB::WriteAddrIndex, base_uint< BITS >::ToString, CDiskBlockIndex::hashNext, CBlockIndex::GetBlockHash, SyncWithWallets.
Referenced by Reorganize.
bool CBlock::ReadFromDisk(const CBlockIndex *pindex, bool fReadTransactions=true)
References ReadFromDisk, CBlockHeader::GetHash.
bool CBlock::SetBestChain(CTxDB &txdb, CBlockIndex *pindexNew)
References CTxDB::TxnBegin, Params, CChainParams::HashGenesisBlock, CTxDB::WriteHashBestChain, CTxDB::TxnCommit, CBlockIndex::pprev, CBlockIndex::nChainTrust, LogPrintf, Reorganize, CTxDB::TxnAbort, InvalidChainFound, ReadFromDisk, IsInitialBlockDownload, CBlockIndex::nHeight, hash, pblockindexFBBHLast, GetTime, base_uint< BITS >::ToString, nBestHeight, CBigNum::ToString, base_uint< BITS >::Get64, DateTimeStrFormat, CBlockIndex::GetBlockTime, pindexBest, CBlockIndex::nVersion, CBlockHeader::CURRENT_VERSION, strMiscWarning, _, GetArg, base_uint< BITS >::GetHex, runCommand.
Referenced by CTxDB::LoadBlockIndex.
bool CBlock::AddToBlockIndex(unsigned int nFile, unsigned int nBlockPos, const uint256 &hashProof)
References AssertLockHeld, base_uint< BITS >::ToString, CBlockIndex::phashBlock, hash, CBlockIndex::pprev, CBlockIndex::nHeight, CBlockIndex::nChainTrust, CBlockIndex::GetBlockTrust, CBlockIndex::SetStakeEntropyBit, CBlockIndex::hashProof, ComputeNextStakeModifier, CBlockIndex::SetStakeModifier, CBlockIndex::bnStakeModifierV2, ComputeStakeModifierV2, CBlockIndex::IsProofOfStake, CBlockIndex::prevoutStake, CBlockIndex::nStakeTime, txdb, CTxDB::TxnBegin, CTxDB::WriteBlockIndex, CTxDB::TxnCommit, uint256::GetHash.
Referenced by AcceptBlock, LoadBlockIndex.
bool CBlock::CheckBlock(CValidationState &state, bool fCheckPOW=true, bool fCheckMerkleRoot=true, bool fCheckSig=true)
References vtx, GetSerializeSize, SER_NETWORK, CBlockHeader::DoS, IsProofOfWork, CheckProofOfWork, CBlockHeader::GetPoWHash, CBlockHeader::nBits, CBlockHeader::GetBlockTime, FutureDrift, GetAdjustedTime, IsProofOfStake, CheckBlockSignature, IsSporkActive, CTransaction::IsCoinBase, CTransaction::vin, mapLockedInputs, CTxIn::prevout, CTransaction::GetHash, fDebug, LogPrintf, base_uint< BITS >::ToString, pindexBest, CTransaction::CheckTransaction, CTransaction::nDoS, CTransaction::nTime, GetLegacySigOpCount, CBlockHeader::hashMerkleRoot, BuildMerkleTree.
Referenced by ConnectBlock, ProcessBlock, CTxDB::LoadBlockIndex.
bool CBlock::AcceptBlock()
References AssertLockHeld, cs_main, CBlockHeader::nVersion, CBlockHeader::CURRENT_VERSION, CBlockHeader::DoS, hash, CBlockHeader::GetHash, mapBlockIndex, CBlockHeader::hashPrevBlock, CBlockIndex::nHeight, IsProofOfStake, Params, CChainParams::FirstPOSBlock, CBlockHeader::GetBlockTime, FutureDrift, vtx, CBlockHeader::nTime, CheckCoinStakeTimestamp, CBlockHeader::nBits, GetNextTargetRequired, IsProofOfWork, LogPrintf, CBlockIndex::GetPastTimeLimit, CBlockIndex::GetBlockTime, IsFinalTx, Checkpoints::CheckHardened, CheckProofOfStake, base_uint< BITS >::ToString, CBlockHeader::GetPoWHash, Checkpoints::CheckSync, expect, CheckDiskSpace, GetSerializeSize, SER_DISK, WriteToDisk, AddToBlockIndex, Checkpoints::GetTotalBlocksEstimate, hashBestChain, LOCK, cs_vNodes, vNodes, nBestHeight, CNode::nStartingHeight, CNode::PushInventory, MSG_BLOCK.
Referenced by ProcessBlock.
bool CBlock::SignBlock(CWallet &keystore, CAmount nFees)
bool CBlock::CheckBlockSignature() const
References IsProofOfWork, vchBlockSig, vtx, Solver, CTxOut::scriptPubKey, TX_PUBKEY, CPubKey::Verify, CBlockHeader::GetHash, CScript::GetOp, OP_RETURN, IsCompressedOrUncompressedPubKey.
Referenced by CheckBlock.
void CBlock::RebuildAddressIndex(CTxDB &txdb)
References vtx, CTransaction::GetHash, CTransaction::IsCoinBase, CTransactionPoS::FetchInputs, CTxOut::scriptPubKey, CTxDB::WriteAddrIndex, LogPrintf, base_uint< BITS >::ToString, CTransaction::vout.
Referenced by AppInit2.
static uint256 CBlock::CheckMerkleBranch(uint256 hash, const std::vector< uint256 > &vMerkleBranch, int nIndex)
References Hash, BEGIN, END, hash.
bool CBlock::SetBestChainInner(CTxDB &txdb, CBlockIndex *pindexNew)