leveldb::log::Writer
WritableFile* leveldb::log::Writer::dest_
int leveldb::log::Writer::block_offset_
uint32_t leveldb::log::Writer::type_crc_[kMaxRecordType+1][kMaxRecordType+1]
leveldb::log::Writer::Writer(WritableFile *dest)
References leveldb::crc32c::Value.
leveldb::log::Writer::~Writer()
Status leveldb::log::Writer::AddRecord(const Slice &slice)
References leveldb::Slice::data, leveldb::Slice::size, leveldb::WritableFile::Append, leveldb::log::kFullType, leveldb::log::kFirstType, leveldb::log::kLastType, leveldb::log::kMiddleType, leveldb::Status::ok.
Referenced by leveldb::DBImpl::Write, leveldb::log::LogTest::Write, leveldb::VersionSet::LogAndApply.
Status leveldb::log::Writer::EmitPhysicalRecord(RecordType type, const char *ptr, size_t length)
leveldb::log::Writer::Writer(const Writer &)
void leveldb::log::Writer::operator=(const Writer &)