MacDockIconHandler
DockIconClickEventHandler* MacDockIconHandler::m_dockIconClickEventHandler
QWidget* MacDockIconHandler::m_dummyWidget
QMenu* MacDockIconHandler::m_dockMenu
QMainWindow* MacDockIconHandler::mainWindow
MacDockIconHandler::~MacDockIconHandler()
References setMainWindow.
QMenu * MacDockIconHandler::dockMenu()
void MacDockIconHandler::setIcon(const QIcon &icon)
Referenced by main, DarkSilkGUI::setClientModel.
void MacDockIconHandler::setMainWindow(QMainWindow *window)
Referenced by DarkSilkGUI::~DarkSilkGUI, ~MacDockIconHandler.
void MacDockIconHandler::handleDockIconClickEvent()
References dockIconClicked.
MacDockIconHandler * MacDockIconHandler::instance()
Referenced by main, DarkSilkGUI::~DarkSilkGUI, DarkSilkGUI::setClientModel.
void MacDockIconHandler::dockIconClicked()
Referenced by handleDockIconClickEvent.
MacDockIconHandler::MacDockIconHandler()