leveldb::Block::Iter
const Comparator* const leveldb::Block::Iter::comparator_
const char* const leveldb::Block::Iter::data_
uint32_t const leveldb::Block::Iter::restarts_
uint32_t const leveldb::Block::Iter::num_restarts_
uint32_t leveldb::Block::Iter::current_
uint32_t leveldb::Block::Iter::restart_index_
std::string leveldb::Block::Iter::key_
Slice leveldb::Block::Iter::value_
Status leveldb::Block::Iter::status_
int leveldb::Block::Iter::Compare(const Slice &a, const Slice &b) const
uint32_t leveldb::Block::Iter::NextEntryOffset() const
uint32_t leveldb::Block::Iter::GetRestartPoint(uint32_t index)
void leveldb::Block::Iter::SeekToRestartPoint(uint32_t index)
void leveldb::Block::Iter::CorruptionError()
bool leveldb::Block::Iter::ParseNextKey()
leveldb::Block::Iter::Iter(const Comparator *comparator, const char *data, uint32_t restarts, uint32_t num_restarts)
virtual bool leveldb::Block::Iter::Valid() const
Referenced by key, value, Next, Prev.
virtual Status leveldb::Block::Iter::status() const
virtual Slice leveldb::Block::Iter::key() const
References Valid.
virtual Slice leveldb::Block::Iter::value() const
References Valid.
virtual void leveldb::Block::Iter::Next()
References Valid.
virtual void leveldb::Block::Iter::Prev()
References Valid.
virtual void leveldb::Block::Iter::Seek(const Slice &target)
References shared.
virtual void leveldb::Block::Iter::SeekToFirst()
virtual void leveldb::Block::Iter::SeekToLast()