CBudgetProposal
CCriticalSection CBudgetProposal::cs
CAmount CBudgetProposal::nAlloted
bool CBudgetProposal::fValid
Referenced by snbudget, CBudgetManager::CheckAndRemove, CBudgetManager::GetBudget, CBudgetManager::ResetSync, CBudgetManager::MarkSynced, CBudgetManager::Sync, CBudgetProposal.
std::string CBudgetProposal::strProposalName
Referenced by CBudgetManager::GetBudget, CBudgetProposal, IsValid, CBudgetProposalBroadcast::swap.
std::string CBudgetProposal::strURL
Referenced by CBudgetProposal, IsValid, CBudgetProposalBroadcast::swap.
int CBudgetProposal::nBlockStart
Referenced by CBudgetManager::GetBudget, CBudgetProposal, IsValid, GetBlockStartCycle, GetRemainingPaymentCount, CBudgetProposalBroadcast::swap.
int CBudgetProposal::nBlockEnd
Referenced by CBudgetManager::GetBudget, CBudgetProposal, IsValid, GetBlockEndCycle, GetRemainingPaymentCount, CBudgetProposalBroadcast::swap.
CAmount CBudgetProposal::nAmount
Referenced by CBudgetProposal, IsValid, CBudgetProposalBroadcast::swap.
CScript CBudgetProposal::address
Referenced by CBudgetProposal, IsValid, CBudgetProposalBroadcast::swap.
int64_t CBudgetProposal::nTime
Referenced by snbudget, CBudgetProposal, IsValid, AddOrUpdateVote, CBudgetProposalBroadcast::swap.
uint256 CBudgetProposal::nFeeTXHash
Referenced by snbudget, CBudgetProposal, IsValid, CBudgetProposalBroadcast::swap.
map<uint256, CBudgetVote> CBudgetProposal::mapVotes
Referenced by snbudget, CBudgetManager::ResetSync, CBudgetManager::MarkSynced, CBudgetManager::Sync, CBudgetProposal, AddOrUpdateVote, CleanAndRemove, GetRatio, GetYesCount, GetNoCount, GetAbstainCount, CBudgetProposalBroadcast::swap.
CBudgetProposal::ADD_SERIALIZE_METHODS
CBudgetProposal::CBudgetProposal()
References strProposalName, nBlockStart, nBlockEnd, nAmount, nTime, fValid.
CBudgetProposal::CBudgetProposal(const CBudgetProposal &other)
References strProposalName, strURL, nBlockStart, nBlockEnd, address, nAmount, nTime, nFeeTXHash, mapVotes, fValid.
CBudgetProposal::CBudgetProposal(std::string strProposalNameIn, std::string strURLIn, int nPaymentCount, CScript addressIn, CAmount nAmountIn, int nBlockStartIn, uint256 nFeeTXHashIn)
References strProposalName, strURL, nBlockStart, GetBudgetPaymentCycleBlocks, nBlockEnd, address, nAmount, nFeeTXHash.
void CBudgetProposal::Calculate()
bool CBudgetProposal::AddOrUpdateVote(CBudgetVote &vote, std::string &strError)
References LOCK, hash, CBudgetVote::vin, CTxIn::prevout, COutPoint::GetHash, mapVotes, nTime, CBudgetVote::nTime, strprintf, CBudgetVote::GetHash, base_uint< BITS >::ToString, GetTime.
bool CBudgetProposal::HasMinimumRequiredSupport()
std::pair<std::string, std::string> CBudgetProposal::GetVotes()
bool CBudgetProposal::IsValid(std::string &strError, bool fCheckCollateral=true)
References GetNoCount, GetYesCount, snodeman, CStormnodeMan::CountEnabled, nBlockStart, pindexBest, GetBudgetPaymentCycleBlocks, CBlockIndex::nHeight, strprintf, nBlockEnd, nAmount, strProposalName, SanitizeString, strURL, address, IsBudgetCollateralValid, nFeeTXHash, GetHash, nTime, CScript::IsPayToScriptHash, GetAbsoluteYesCount, CBudgetManager::GetTotalBudget, GetBlockEnd.
Referenced by snbudget, CBudgetManager::AddProposal, CBudgetManager::CheckAndRemove.
bool CBudgetProposal::IsEstablished()
References Params, CChainParams::MAIN, GetTime.
Referenced by snbudget, CBudgetManager::GetBudget.
std::string CBudgetProposal::GetName()
Referenced by snbudget, CFinalizedBudget::GetProposals.
std::string CBudgetProposal::GetURL()
Referenced by snbudget.
int CBudgetProposal::GetBlockStart()
Referenced by snbudget.
int CBudgetProposal::GetBlockEnd()
Referenced by snbudget, IsValid.
CScript CBudgetProposal::GetPayee()
Referenced by snbudget, CFinalizedBudget::GetStatus.
int CBudgetProposal::GetTotalPaymentCount()
References GetBlockEndCycle, GetBlockStartCycle, GetBudgetPaymentCycleBlocks.
Referenced by snbudget.
int CBudgetProposal::GetRemainingPaymentCount()
References nBlockStart, GetBudgetPaymentCycleBlocks, nBlockEnd.
Referenced by snbudget.
int CBudgetProposal::GetBlockStartCycle()
References nBlockStart, GetBudgetPaymentCycleBlocks.
Referenced by GetTotalPaymentCount.
int CBudgetProposal::GetBlockCurrentCycle()
References pindexBest, CBlockIndex::nHeight, GetBlockEndCycle, GetBudgetPaymentCycleBlocks.
int CBudgetProposal::GetBlockEndCycle()
References nBlockEnd, GetBudgetPaymentCycleBlocks.
Referenced by GetBlockCurrentCycle, GetTotalPaymentCount.
double CBudgetProposal::GetRatio()
References mapVotes.
Referenced by snbudget.
int CBudgetProposal::GetAbsoluteYesCount()
References GetYesCount, GetNoCount.
Referenced by IsValid.
int CBudgetProposal::GetYesCount()
References mapVotes.
Referenced by snbudget, CBudgetManager::FindProposal, CBudgetManager::GetBudget, IsValid, GetAbsoluteYesCount.
int CBudgetProposal::GetNoCount()
References mapVotes.
Referenced by snbudget, CBudgetManager::GetBudget, IsValid, GetAbsoluteYesCount.
int CBudgetProposal::GetAbstainCount()
References mapVotes.
Referenced by snbudget.
CAmount CBudgetProposal::GetAmount()
Referenced by snbudget, CBudgetManager::GetBudget, CFinalizedBudget::GetStatus.
void CBudgetProposal::SetAllotted(CAmount nAllotedIn)
Referenced by CBudgetManager::GetBudget.
CAmount CBudgetProposal::GetAllotted()
Referenced by snbudget.
void CBudgetProposal::CleanAndRemove(bool fSignatureCheck)
References mapVotes.
uint256 CBudgetProposal::GetHash()
References SER_GETHASH, CHashWriter::GetHash.
Referenced by snbudget, CBudgetManager::AddProposal, IsValid, CBudgetProposalBroadcast::Relay.
void CBudgetProposal::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE, LIMITED_STRING.