TransactionRecord
uint256 TransactionRecord::hash
Referenced by decomposeTransaction, getTxID, TxLessThan::operator(), TransactionTablePriv::index, TransactionTablePriv::describe.
qint64 TransactionRecord::time
Referenced by TransactionTableModel::data.
Type TransactionRecord::type
Referenced by decomposeTransaction, updateStatus, TransactionTableModel::data.
std::string TransactionRecord::address
Referenced by TransactionDesc::toHTML, decomposeTransaction, TransactionTableModel::data.
CAmount TransactionRecord::debit
Referenced by decomposeTransaction, TransactionTableModel::data.
CAmount TransactionRecord::credit
Referenced by decomposeTransaction, TransactionTableModel::data.
Type
const int TransactionRecord::RecommendedNumConfirmations
Number of confirmation recommended for accepting a transaction
Referenced by updateStatus.
int TransactionRecord::idx
Subtransaction index, for sort key
Referenced by TransactionDesc::toHTML, decomposeTransaction, updateStatus, getTxID.
TransactionStatus TransactionRecord::status
Status: can change with block chain update
Referenced by updateStatus, statusUpdateNeeded, TransactionTableModel::data.
TransactionRecord::TransactionRecord()
Referenced by decomposeTransaction.
TransactionRecord::TransactionRecord(uint256 hash, int64_t time)
TransactionRecord::TransactionRecord(uint256 hash, int64_t time, Type type, const std::string &address, const CAmount &debit, const CAmount &credit)
QString TransactionRecord::getTxID() const
Return the unique identifier for this transaction (part)
References formatSubTxId, hash, idx.
Referenced by TransactionTableModel::data.
void TransactionRecord::updateStatus(const CWalletTx &wtx)
Update status from core wallet tx.
References AssertLockHeld, cs_main, mapBlockIndex, CMerkleTx::hashBlock, status, TransactionStatus::sortKey, strprintf, CBlockIndex::nHeight, CTransaction::IsCoinBase, CWalletTx::nTimeReceived, idx, TransactionStatus::countsForBalance, CWalletTx::IsTrusted, CMerkleTx::GetBlocksToMaturity, TransactionStatus::depth, CMerkleTx::GetDepthInMainChain, TransactionStatus::cur_num_blocks, nBestHeight, TransactionStatus::cur_num_ix_locks, nCompleteTXLocks, IsFinalTx, CTransaction::nLockTime, TransactionStatus::status, TransactionStatus::OpenUntilBlock, TransactionStatus::open_for, TransactionStatus::OpenUntilDate, type, Generated, TransactionStatus::Immature, CMerkleTx::IsInMainChain, TransactionStatus::matures_in, GetAdjustedTime, CWalletTx::GetRequestCount, TransactionStatus::MaturesWarning, TransactionStatus::NotAccepted, TransactionStatus::Confirmed, TransactionStatus::Conflicted, TransactionStatus::Offline, TransactionStatus::Unconfirmed, RecommendedNumConfirmations, TransactionStatus::Confirming.
Referenced by TransactionTablePriv::index.
bool TransactionRecord::statusUpdateNeeded()
Return whether a status update is needed.
References AssertLockHeld, cs_main, status, TransactionStatus::cur_num_blocks, nBestHeight, TransactionStatus::cur_num_ix_locks, nCompleteTXLocks.
Referenced by TransactionTablePriv::index.
bool TransactionRecord::showTransaction(const CWalletTx &wtx)
Decompose CWallet transaction to model transaction records.
References CTransaction::IsCoinBase, CMerkleTx::IsInMainChain.
Referenced by TransactionTablePriv::refreshWallet, TransactionTablePriv::updateWallet.
QList< TransactionRecord > TransactionRecord::decomposeTransaction(const CWallet *wallet, const CWalletTx &wtx)
References CWalletTx::GetTxTime, CWalletTx::GetCredit, ISMINE_ALL, CWalletTx::GetDebit, hash, CTransaction::GetHash, CWalletTx::mapValue, CTransaction::IsCoinBase, CTransaction::IsCoinStake, CTransaction::vout, CWallet::IsMine, address, idx, credit, CTxOut::nValue, ExtractDestination, CTxOut::scriptPubKey, IsMine, type, RecvWithAddress, CBase58Data::ToString, RecvFromOther, Generated, CTransactionPoS::GetValueOut, CTransaction::vin, CWalletTx::GetChange, TransactionRecord, SendToSelf, SendToAddress, SendToOther, debit, Other.
Referenced by TransactionTablePriv::refreshWallet, TransactionTablePriv::updateWallet.
QString TransactionRecord::formatSubTxId(const uint256 &hash, int vout)
Format subtransaction id
References base_uint< BITS >::ToString, strprintf.
Referenced by TransactionDesc::toHTML, getTxID.