leveldb::IteratorWrapper
Iterator* leveldb::IteratorWrapper::iter_
bool leveldb::IteratorWrapper::valid_
Slice leveldb::IteratorWrapper::key_
leveldb::IteratorWrapper::IteratorWrapper()
leveldb::IteratorWrapper::IteratorWrapper(Iterator *iter)
References Set.
leveldb::IteratorWrapper::~IteratorWrapper()
Iterator* leveldb::IteratorWrapper::iter() const
Referenced by Set.
void leveldb::IteratorWrapper::Set(Iterator *iter)
References iter.
Referenced by IteratorWrapper.
bool leveldb::IteratorWrapper::Valid() const
Referenced by key, value.
Slice leveldb::IteratorWrapper::key() const
References Valid.
Slice leveldb::IteratorWrapper::value() const
References Valid, leveldb::Iterator::value.
Status leveldb::IteratorWrapper::status() const
References leveldb::Iterator::status.
void leveldb::IteratorWrapper::Next()
References leveldb::Iterator::Next.
void leveldb::IteratorWrapper::Prev()
References leveldb::Iterator::Prev.
void leveldb::IteratorWrapper::Seek(const Slice &k)
References leveldb::Iterator::Seek.
void leveldb::IteratorWrapper::SeekToFirst()
References leveldb::Iterator::SeekToFirst.
void leveldb::IteratorWrapper::SeekToLast()
References leveldb::Iterator::SeekToLast.
void leveldb::IteratorWrapper::Update()