leveldb::DBTest
OptionConfig
const FilterPolicy* leveldb::DBTest::filter_policy_
int leveldb::DBTest::option_config_
std::string leveldb::DBTest::dbname_
SpecialEnv* leveldb::DBTest::env_
Referenced by ~DBTest.
DB* leveldb::DBTest::db_
Referenced by ~DBTest, dbfull, Close, DestroyAndReopen, TryReopen.
Options leveldb::DBTest::last_options_
leveldb::DBTest::DBTest()
References leveldb::NewBloomFilterPolicy, leveldb::test::TmpDir, leveldb::DestroyDB, Reopen.
leveldb::DBTest::~DBTest()
References db_, leveldb::DestroyDB, env_.
bool leveldb::DBTest::ChangeOptions()
References DestroyAndReopen.
Options leveldb::DBTest::CurrentOptions()
References leveldb::Options::filter_policy, leveldb::Options::compression, leveldb::kNoCompression.
Referenced by TryReopen.
DBImpl* leveldb::DBTest::dbfull()
References db_.
Referenced by AllEntriesFor, MakeTables, DumpFileCounts.
void leveldb::DBTest::Reopen(Options *options=NULL)
References ASSERT_OK, TryReopen.
Referenced by DBTest.
void leveldb::DBTest::Close()
References db_.
void leveldb::DBTest::DestroyAndReopen(Options *options=NULL)
References db_, leveldb::DestroyDB, ASSERT_OK, TryReopen.
Referenced by ChangeOptions.
Status leveldb::DBTest::TryReopen(Options *options)
References db_, CurrentOptions, leveldb::Options::create_if_missing, leveldb::DB::Open.
Referenced by Reopen, DestroyAndReopen.
Status leveldb::DBTest::Put(const std::string &k, const std::string &v)
References leveldb::DB::Put.
Referenced by MakeTables.
Status leveldb::DBTest::Delete(const std::string &k)
References leveldb::DB::Delete.
std::string leveldb::DBTest::Get(const std::string &k, const Snapshot *snapshot=NULL)
References leveldb::ReadOptions::snapshot, leveldb::DB::Get, leveldb::Status::IsNotFound, leveldb::Status::ok, leveldb::Status::ToString.
std::string leveldb::DBTest::Contents()
References leveldb::DB::NewIterator, leveldb::Iterator::SeekToFirst, leveldb::Iterator::Valid, leveldb::Iterator::Next, IterStatus, leveldb::Iterator::SeekToLast, leveldb::Iterator::Prev, ASSERT_LT, ASSERT_EQ.
std::string leveldb::DBTest::AllEntriesFor(const Slice &user_key)
References dbfull, leveldb::DBImpl::TEST_NewInternalIterator, leveldb::kTypeValue, leveldb::Iterator::Seek, leveldb::InternalKey::Encode, leveldb::Iterator::status, leveldb::Status::ok, leveldb::Status::ToString, leveldb::Iterator::Valid, leveldb::ParseInternalKey, leveldb::Iterator::key, leveldb::Options::comparator, leveldb::Comparator::Compare, leveldb::ParsedInternalKey::user_key, leveldb::ParsedInternalKey::type, leveldb::Iterator::value, leveldb::Slice::ToString, leveldb::kTypeDeletion, leveldb::Iterator::Next.
int leveldb::DBTest::NumTableFilesAtLevel(int level)
References ASSERT_TRUE, leveldb::DB::GetProperty, leveldb::NumberToString, atoi.
Referenced by TotalTableFiles, FilesPerLevel, DumpFileCounts.
int leveldb::DBTest::TotalTableFiles()
References NumTableFilesAtLevel.
std::string leveldb::DBTest::FilesPerLevel()
References NumTableFilesAtLevel.
int leveldb::DBTest::CountFiles()
References leveldb::EnvWrapper::GetChildren.
uint64_t leveldb::DBTest::Size(const Slice &start, const Slice &limit)
References leveldb::DB::GetApproximateSizes.
void leveldb::DBTest::Compact(const Slice &start, const Slice &limit)
References leveldb::DB::CompactRange.
void leveldb::DBTest::MakeTables(int n, const std::string &small, const std::string &large)
References Put, dbfull, leveldb::DBImpl::TEST_CompactMemTable.
Referenced by FillLevels.
void leveldb::DBTest::FillLevels(const std::string &smallest, const std::string &largest)
References MakeTables.
void leveldb::DBTest::DumpFileCounts(const char *label)
References dbfull, NumTableFilesAtLevel.
std::string leveldb::DBTest::DumpSSTableList()
References leveldb::DB::GetProperty.
std::string leveldb::DBTest::IterStatus(Iterator *iter)
References leveldb::Iterator::Valid, leveldb::Iterator::key, leveldb::Slice::ToString, leveldb::Iterator::value.
Referenced by Contents.
bool leveldb::DBTest::DeleteAnSSTFile()
References ASSERT_OK, leveldb::EnvWrapper::GetChildren, leveldb::ParseFileName, leveldb::kTableFile, leveldb::EnvWrapper::DeleteFile, leveldb::TableFileName.
int leveldb::DBTest::RenameLDBToSST()
References ASSERT_OK, leveldb::EnvWrapper::GetChildren, leveldb::ParseFileName, leveldb::kTableFile, leveldb::TableFileName, leveldb::SSTTableFileName, leveldb::EnvWrapper::RenameFile.