CNetMessage
bool CNetMessage::in_data
Referenced by CNode::ReceiveMsgBytes.
CDataStream CNetMessage::hdrbuf
CMessageHeader CNetMessage::hdr
Referenced by ProcessMessages.
unsigned int CNetMessage::nHdrPos
CDataStream CNetMessage::vRecv
Referenced by ProcessMessages, CNode::GetTotalRecvSize.
unsigned int CNetMessage::nDataPos
int64_t CNetMessage::nTime
Referenced by ProcessMessages, CNode::ReceiveMsgBytes.
CNetMessage::CNetMessage(int nTypeIn, int nVersionIn)
References CDataStream::resize.
bool CNetMessage::complete() const
References CMessageHeader::nMessageSize.
Referenced by ProcessMessages, CNode::ReceiveMsgBytes.
void CNetMessage::SetVersion(int nVersionIn)
References CDataStream::SetVersion.
Referenced by CNode::SetRecvVersion.
int CNetMessage::readHeader(const char *pch, unsigned int nBytes)
References MAX_SIZE.
Referenced by CNode::ReceiveMsgBytes.
int CNetMessage::readData(const char *pch, unsigned int nBytes)
Referenced by CNode::ReceiveMsgBytes.