CActiveStormnode
CCriticalSection CActiveStormnode::cs
CPubKey CActiveStormnode::pubKeyStormnode
Referenced by ManageStatus, Register, AppInit2, CStormnodeBroadcast::CheckInputsAndAdd.
CTxIn CActiveStormnode::vin
Referenced by ManageStatus, Register, DoConsensusVote, snbudget, snfinalbudget, stormnode, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::CheckFinalTransaction, CSandstormPool::CheckForCompleteQueue, CSandstormPool::IsCompatibleWithSession, CFinalizedBudget::SubmitVote, CStormnodePayments::ProcessBlock, CStormnodeBroadcast::CheckInputsAndAdd.
CService CActiveStormnode::service
Referenced by ManageStatus, Register, stormnode.
int CActiveStormnode::status
Referenced by ManageStatus, GetStatus, EnableHotColdStormNode, stormnode.
std::string CActiveStormnode::notCapableReason
Referenced by ManageStatus, GetStatus.
bool CActiveStormnode::SendStormnodePing(std::string &errorMessage)
Ping Stormnode.
bool CActiveStormnode::Register(CTxIn vin, CService service, CKey key, CPubKey pubKey, CKey keyStormnode, CPubKey pubKeyStormnode, std::string &retErrorMessage)
Register any Stormnode.
bool CActiveStormnode::GetStormNodeVin(CTxIn &vin, CPubKey &pubkey, CKey &secretKey, std::string strTxHash, std::string strOutputIndex)
Get 10000 DRKSLK input that can be used for the Stormnode.
bool CActiveStormnode::GetVinFromOutput(COutput out, CTxIn &vin, CPubKey &pubkey, CKey &secretKey)
CActiveStormnode::CActiveStormnode()
void CActiveStormnode::ManageStatus()
Manage status of main Stormnode.
References fStormNode, fDebug, LogPrintf, stormnodeSync, CStormnodeSync::IsBlockchainSynced, status, GetStatus, snodeman, CStormnodeMan::Find, pubKeyStormnode, CStormnode::Check, CStormnode::IsEnabled, CStormnode::IsPreEnabled, CStormnode::protocolVersion, EnableHotColdStormNode, CStormnode::vin, CStormnode::addr, notCapableReason, pwalletMain, CCryptoKeyStore::IsLocked, CWallet::GetBalance, strStormNodeAddr, GetLocal, service, CService::ToString, Params, CChainParams::NetworkID, CChainParams::MAIN, CService::GetPort, strprintf, ConnectNode, vin, GetInputAge, LOCK, CWallet::cs_wallet, CWallet::LockCoin, CTxIn::prevout, sandStormSigner, CSandStormSigner::SetKey, strStormNodePrivKey.
Referenced by stormnode, ThreadCheckSandStormPool, CStormnodeSync::Process.
std::string CActiveStormnode::GetStatus()
References status, strprintf, notCapableReason.
Referenced by ManageStatus, Register, stormnode.
bool CActiveStormnode::Register(std::string strService, std::string strKey, std::string strTxHash, std::string strOutputIndex, std::string &errorMessage)
Register remote Stormnode.
References vin, pubKeyStormnode, stormnodeSync, CStormnodeSync::IsBlockchainSynced, GetStatus, LogPrintf, sandStormSigner, CSandStormSigner::SetKey, strprintf, service, Params, CChainParams::MAIN, CService::GetPort, addrman, CAddrMan::Add.
bool CActiveStormnode::GetStormNodeVin(CTxIn &vin, CPubKey &pubkey, CKey &secretKey)
Get 10,000 DRKSLK input that can be used for the Stormnode.
vector< COutput > CActiveStormnode::SelectCoinsStormnode()
References GetBoolArg, stormnodeConfig, CStormnodeConfig::getEntries, base_uint< BITS >::SetHex, CStormnodeConfig::CStormnodeEntry::getTxHash, atoi, CStormnodeConfig::CStormnodeEntry::getOutputIndex, pwalletMain, CWallet::UnlockCoin, CWallet::AvailableCoins, CWallet::LockCoin, COutput::tx, CTransaction::vout, COutput::i.
Referenced by stormnode.
bool CActiveStormnode::EnableHotColdStormNode(CTxIn &vin, CService &addr)
Enable cold wallet mode (run a Stormnode with no funds)
References fStormNode, status, LogPrintf.
Referenced by ManageStatus, CStormnodeBroadcast::CheckInputsAndAdd.