CMedianFilter
std::vector<T> CMedianFilter< T >::vValues
std::vector<T> CMedianFilter< T >::vSorted
unsigned int CMedianFilter< T >::nSize
CMedianFilter< T >::CMedianFilter(unsigned int size, T initial_value)
void CMedianFilter< T >::input(T value)
Referenced by AddTimeData.
T CMedianFilter< T >::median() const
References CMedianFilter< T >::size.
Referenced by AddTimeData.
int CMedianFilter< T >::size() const
Referenced by CMedianFilter< T >::median, AddTimeData.
std::vector<T> CMedianFilter< T >::sorted() const
Referenced by AddTimeData.