CStormnodeConfig::CStormnodeEntry
std::string CStormnodeConfig::CStormnodeEntry::alias
std::string CStormnodeConfig::CStormnodeEntry::ip
std::string CStormnodeConfig::CStormnodeEntry::privKey
std::string CStormnodeConfig::CStormnodeEntry::txHash
std::string CStormnodeConfig::CStormnodeEntry::outputIndex
std::string CStormnodeConfig::CStormnodeEntry::donationAddress
std::string CStormnodeConfig::CStormnodeEntry::donationPercent
CStormnodeConfig::CStormnodeEntry::CStormnodeEntry(std::string alias, std::string ip, std::string privKey, std::string txHash, std::string outputIndex, std::string donationAddress, std::string donationPercent)
const std::string& CStormnodeConfig::CStormnodeEntry::getAlias() const
Referenced by StormnodeManager::on_UpdateButton_clicked, snbudget, snfinalbudget, stormnode.
void CStormnodeConfig::CStormnodeEntry::setAlias(const std::string &alias)
const std::string& CStormnodeConfig::CStormnodeEntry::getOutputIndex() const
Referenced by CActiveStormnode::SelectCoinsStormnode, AppInit2, StormnodeManager::on_UpdateButton_clicked, stormnode.
void CStormnodeConfig::CStormnodeEntry::setOutputIndex(const std::string &outputIndex)
const std::string& CStormnodeConfig::CStormnodeEntry::getPrivKey() const
Referenced by StormnodeManager::on_UpdateButton_clicked, snbudget, snfinalbudget, stormnode.
void CStormnodeConfig::CStormnodeEntry::setPrivKey(const std::string &privKey)
const std::string& CStormnodeConfig::CStormnodeEntry::getTxHash() const
Referenced by CActiveStormnode::SelectCoinsStormnode, AppInit2, StormnodeManager::on_UpdateButton_clicked, stormnode.
void CStormnodeConfig::CStormnodeEntry::setTxHash(const std::string &txHash)
const std::string& CStormnodeConfig::CStormnodeEntry::getIp() const
Referenced by StormnodeManager::on_UpdateButton_clicked, stormnode.
void CStormnodeConfig::CStormnodeEntry::setIp(const std::string &ip)
const std::string& CStormnodeConfig::CStormnodeEntry::getDonationAddress() const
const std::string& CStormnodeConfig::CStormnodeEntry::getDonationPercentage() const