leveldb::CorruptionTest
test::ErrorEnv leveldb::CorruptionTest::env_
Referenced by CorruptionTest.
std::string leveldb::CorruptionTest::dbname_
Cache* leveldb::CorruptionTest::tiny_cache_
Referenced by CorruptionTest, ~CorruptionTest.
Options leveldb::CorruptionTest::options_
DB* leveldb::CorruptionTest::db_
Referenced by ~CorruptionTest, TryReopen, RepairDB.
leveldb::CorruptionTest::CorruptionTest()
References leveldb::NewLRUCache, leveldb::Options::env, env_, leveldb::Options::block_cache, tiny_cache_, leveldb::test::TmpDir, leveldb::DestroyDB, leveldb::Options::create_if_missing, Reopen.
leveldb::CorruptionTest::~CorruptionTest()
References db_, leveldb::DestroyDB, tiny_cache_.
Status leveldb::CorruptionTest::TryReopen()
References db_, leveldb::DB::Open.
Referenced by Reopen.
void leveldb::CorruptionTest::Reopen()
References ASSERT_OK, TryReopen.
Referenced by CorruptionTest.
void leveldb::CorruptionTest::RepairDB()
References db_, ASSERT_OK, leveldb::RepairDB.
void leveldb::CorruptionTest::Build(int n)
References Key, leveldb::WriteBatch::Clear, leveldb::WriteBatch::Put, Value, leveldb::WriteOptions::sync, ASSERT_OK, leveldb::DB::Write.
void leveldb::CorruptionTest::Check(int min_expected, int max_expected)
References leveldb::DB::NewIterator, leveldb::Iterator::SeekToFirst, leveldb::Iterator::Valid, leveldb::Iterator::Next, leveldb::Iterator::key, leveldb::ConsumeDecimalNumber, leveldb::Iterator::value, Value, ASSERT_LE, ASSERT_GE.
void leveldb::CorruptionTest::Corrupt(FileType filetype, int offset, int bytes_to_corrupt)
References ASSERT_OK, leveldb::EnvWrapper::GetChildren, leveldb::ParseFileName, ASSERT_TRUE, leveldb::ReadFileToString, leveldb::Env::Default, leveldb::Status::ok, leveldb::Status::ToString, leveldb::WriteStringToFile.
int leveldb::CorruptionTest::Property(const std::string &name)
References leveldb::DB::GetProperty.
Slice leveldb::CorruptionTest::Key(int i, std::string *storage)
Referenced by Build.
Slice leveldb::CorruptionTest::Value(int k, std::string *storage)
References leveldb::test::RandomString.
Referenced by Build, Check.