CStormnodePaymentWinner
CTxIn CStormnodePaymentWinner::vinStormnode
Referenced by Sign, CStormnodePayments::AddWinningStormnode, IsValid, SignatureValid.
int CStormnodePaymentWinner::nBlockHeight
Referenced by Sign, CStormnodePayments::AddWinningStormnode, CStormnodePayments::CleanPaymentList, IsValid, CStormnodePayments::ProcessBlock, SignatureValid, CStormnodePayments::Sync.
CScript CStormnodePaymentWinner::payee
Referenced by Sign, CStormnodePayments::AddWinningStormnode, SignatureValid.
std::vector<unsigned char> CStormnodePaymentWinner::vchSig
Referenced by Sign, SignatureValid.
CStormnodePaymentWinner::ADD_SERIALIZE_METHODS
CStormnodePaymentWinner::CStormnodePaymentWinner()
CStormnodePaymentWinner::CStormnodePaymentWinner(CTxIn vinIn)
uint256 CStormnodePaymentWinner::GetHash()
References SER_GETHASH, CTxIn::prevout, CHashWriter::GetHash.
Referenced by CStormnodePayments::AddWinningStormnode, Relay, CStormnodePayments::Sync.
bool CStormnodePaymentWinner::Sign(CKey &keyStormnode, CPubKey &pubKeyStormnode)
References vinStormnode, CTxIn::prevout, COutPoint::ToStringShort, nBlockHeight, payee, CScript::ToString, sandStormSigner, CSandStormSigner::SignMessage, vchSig, LogPrintf, CSandStormSigner::VerifyMessage.
Referenced by CStormnodePayments::ProcessBlock.
bool CStormnodePaymentWinner::IsValid(CNode *pnode, std::string &strError)
References IsReferenceNode, vinStormnode, snodeman, CStormnodeMan::Find, strprintf, CTxIn::prevout, COutPoint::ToStringShort, LogPrintf, CStormnodeMan::AskForSN, CStormnode::protocolVersion, CStormnodeMan::GetStormnodeRank, nBlockHeight, SNPAYMENTS_SIGNATURES_TOTAL, stormnodeSync, CStormnodeSync::IsSynced, Misbehaving, CNode::GetId.
bool CStormnodePaymentWinner::SignatureValid()
References snodeman, CStormnodeMan::Find, vinStormnode, CTxIn::prevout, COutPoint::ToStringShort, nBlockHeight, payee, CScript::ToString, sandStormSigner, CSandStormSigner::VerifyMessage, CStormnode::pubkey2, vchSig, CTxIn::ToString.
void CStormnodePaymentWinner::Relay()
References MSG_STORMNODE_WINNER, GetHash, RelayInv.
Referenced by CStormnodePayments::ProcessBlock.
void CStormnodePaymentWinner::AddPayee(CScript payeeIn)
Referenced by CStormnodePayments::ProcessBlock.
void CStormnodePaymentWinner::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE.
std::string CStormnodePaymentWinner::ToString()
References CTxIn::ToString, CScript::ToString.