CStormnodeDB
ReadResult
boost::filesystem::path CStormnodeDB::pathSN
std::string CStormnodeDB::strMagicMessage
CStormnodeDB::CStormnodeDB()
References GetDataDir.
bool CStormnodeDB::Write(const CStormnodeMan &snodemanToSave)
References GetTimeMillis, SER_DISK, FLATDATA, Params, hash, Hash, CDataStream::begin, CDataStream::end, LogPrintf.
Referenced by DumpStormnodes.
CStormnodeDB::ReadResult CStormnodeDB::Read(CStormnodeMan &snodemanToLoad, bool fDryRun=false)
References GetTimeMillis, SER_DISK, FileError, HashReadError, Hash, CDataStream::begin, CDataStream::end, IncorrectHash, IncorrectMagicMessage, FLATDATA, Params, IncorrectMagicNumber, CStormnodeMan::Clear, IncorrectFormat, LogPrintf, CStormnodeMan::ToString, CStormnodeMan::CheckAndRemove, Ok.
Referenced by AppInit2, DumpStormnodes.