CSemaphore
boost::condition_variable CSemaphore::condition
boost::mutex CSemaphore::mutex
int CSemaphore::value
CSemaphore::CSemaphore(int init)
void CSemaphore::wait()
Referenced by CSemaphoreGrant::Acquire.
bool CSemaphore::try_wait()
Referenced by CSemaphoreGrant::TryAcquire.
void CSemaphore::post()
Referenced by StopNode, CSemaphoreGrant::Release.