CReserveKey
CWallet* CReserveKey::pwallet
int64_t CReserveKey::nIndex
CPubKey CReserveKey::vchPubKey
CReserveKey::CReserveKey(CWallet *pwalletIn)
CReserveKey::~CReserveKey()
References ReturnKey.
void CReserveKey::ReturnKey()
Referenced by CSandstormPool::MakeCollateralAmounts, CSandstormPool::CreateDenominated, ~CReserveKey.
bool CReserveKey::GetReservedKey(CPubKey &pubkey)
References CKeyPool::vchPubKey, LogPrintf, CPubKey::IsValid.
Referenced by CreateNewBlock, checkkernel, CSandstormPool::MakeCollateralAmounts, CSandstormPool::CreateDenominated, CWallet::CreateCollateralTransaction, CWallet::PrepareSandstormDenominate.
void CReserveKey::KeepKey()
Referenced by CheckWork, CSandstormPool::MakeCollateralAmounts, CSandstormPool::CreateDenominated, CWallet::CreateCollateralTransaction, CWallet::CommitTransaction, CWallet::PrepareSandstormDenominate.