CKey
bool CKey::fValid
bool CKey::fCompressed
unsigned char CKey::vch[32][32]
bool CKey::Check(const unsigned char *vch)
CKey::CKey()
References LockObject.
CKey::CKey(const CKey &secret)
References LockObject.
CKey::~CKey()
References UnlockObject.
void CKey::Set(const T pbegin, const T pend, bool fCompressedIn)
Referenced by CDarkSilkSecret::GetKey, CCryptoKeyStore::Unlock, CCryptoKeyStore::GetKey, CExtKey::SetMaster, CExtKey::Decode, BOOST_AUTO_TEST_CASE, CWallet::UnlockStealthAddresses, CWallet::FindStealthTransactions.
unsigned int CKey::size() const
Referenced by CDarkSilkSecret::SetKey, CExtKey::Encode, end.
const unsigned char* CKey::begin() const
Referenced by CDarkSilkSecret::SetKey, CCryptoKeyStore::AddKeyPubKey, CCryptoKeyStore::EncryptKeys, SetPrivKey, GetPrivKey, GetPubKey, Sign, SignCompact, Load, Derive, CExtKey::Encode, SecureMsgEncrypt, SecureMsgDecrypt.
const unsigned char* CKey::end() const
References size.
Referenced by CCryptoKeyStore::AddKeyPubKey, CCryptoKeyStore::EncryptKeys, Derive.
bool CKey::IsValid() const
Referenced by CDarkSilkSecret::SetKey, Derive, BOOST_AUTO_TEST_CASE, CWallet::UnlockStealthAddresses, CWallet::FindStealthTransactions.
bool CKey::IsCompressed() const
Referenced by CDarkSilkSecret::SetKey, Derive.
bool CKey::SetPrivKey(const CPrivKey &vchPrivKey, bool fCompressed)
References begin.
Referenced by sendalert.
void CKey::MakeNewKey(bool fCompressed)
References RandAddSeedPerfmon, GetRandBytes.
Referenced by ECC_InitSanityCheck, stormnode, makekeypair, SecureMsgEncrypt, BOOST_AUTO_TEST_CASE, CWallet::GenerateNewKey.
CPrivKey CKey::GetPrivKey() const
References begin, SECP256K1_EC_COMPRESSED, SECP256K1_EC_UNCOMPRESSED.
Referenced by makekeypair, CWallet::AddKeyPubKey.
CPubKey CKey::GetPubKey() const
References secp256k1_ec_pubkey_create, begin, secp256k1_ec_pubkey_serialize, CPubKey::begin, SECP256K1_EC_COMPRESSED, SECP256K1_EC_UNCOMPRESSED, CPubKey::size, CPubKey::IsValid.
Referenced by CCryptoKeyStore::Unlock, CCryptoKeyStore::EncryptKeys, Derive, CExtKey::Derive, CExtKey::Neuter, ECC_InitSanityCheck, CKeyStore::GetPubKey, CKeyStore::AddKey, importprivkey, importwallet, makekeypair, CSandStormSigner::SetKey, SecureMsgEncrypt, BOOST_AUTO_TEST_CASE, CWallet::GenerateNewKey, CWallet::UnlockStealthAddresses, CWallet::FindStealthTransactions, CWallet::CreateCoinStake.
bool CKey::Sign(const uint256 &hash, std::vector< unsigned char > &vchSig, uint32_t test_case=0) const
Create a DER-serialized signature. The test_case parameter tweaks the deterministic nonce.
References secp256k1_ecdsa_sign, base_uint< BITS >::begin, begin, secp256k1_nonce_function_rfc6979, secp256k1_ecdsa_signature_serialize_der.
Referenced by VerifyPubKey, sendalert, Sign1.
bool CKey::SignCompact(const uint256 &hash, std::vector< unsigned char > &vchSig) const
References secp256k1_ecdsa_sign_recoverable, base_uint< BITS >::begin, begin, secp256k1_nonce_function_rfc6979, secp256k1_ecdsa_recoverable_signature_serialize_compact.
Referenced by signmessage, CSandStormSigner::SignMessage, SecureMsgEncrypt.
bool CKey::Derive(CKey &keyChild, unsigned char ccChild[32], unsigned int nChild, const unsigned char cc[32]) const
References IsValid, IsCompressed, LockObject, GetPubKey, CPubKey::begin, CPubKey::end, BIP32Hash, begin, end, secp256k1_ec_privkey_tweak_add, UnlockObject.
Referenced by CExtKey::Derive.
bool CKey::VerifyPubKey(const CPubKey &vchPubKey) const
Verify thoroughly whether a private key and a public key match. This is done using a different mechanism than just regenerating it.
References CPubKey::IsCompressed, GetRandBytes, hash, CHash256::Write, base_uint< BITS >::begin, Sign, CPubKey::Verify.
Referenced by Load, ECC_InitSanityCheck, importprivkey, importwallet, CWallet::GenerateNewKey.
bool CKey::Load(CPrivKey &privkey, CPubKey &vchPubKey, bool fSkipCheck)
References begin, CPubKey::IsCompressed, VerifyPubKey.
Referenced by ReadKeyValue.
bool operator==(const CKey &a, const CKey &b)
static bool CKey::CheckSignatureElement(const unsigned char *vch, int len, bool half)