CBase58Data
typedef std::vector<unsigned char, zero_after_free_allocator<unsigned char> > CBase58Data::vector_uchar
std::vector<unsigned char> CBase58Data::vchVersion
Referenced by CBase58Data, SetData, SetString, ToString, CompareTo, CDarkSilkAddress::IsValid, CDarkSilkAddress::Get, CDarkSilkAddress::GetKeyID, CDarkSilkAddress::IsScript, CDarkSilkSecret::IsValid, CDarkSilkAddress_B::getVersion.
vector_uchar CBase58Data::vchData
Referenced by CBase58Data, SetData, SetString, ToString, CompareTo, CDarkSilkAddress::IsValid, CDarkSilkAddress::Get, CDarkSilkAddress::GetKeyID, CDarkSilkSecret::SetKey, CDarkSilkSecret::GetKey, CDarkSilkSecret::IsValid, CDarkSilkExtKeyBase< K, Size, Type >::GetKey.
CBase58Data::CBase58Data()
References vchVersion, vchData.
void CBase58Data::SetData(const std::vector< unsigned char > &vchVersionIn, const void *pdata, size_t nSize)
References vchVersion, vchData.
Referenced by SetData, CDarkSilkAddress::Set, CDarkSilkSecret::SetKey, CDarkSilkExtKeyBase< K, Size, Type >::SetKey.
void CBase58Data::SetData(const std::vector< unsigned char > &vchVersionIn, const unsigned char *pbegin, const unsigned char *pend)
References SetData.
bool CBase58Data::SetString(const char *psz, unsigned int nVersionBytes=1)
References DecodeBase58Check, vchData, vchVersion, memory_cleanse.
Referenced by SetString, CDarkSilkSecret::SetString, CDarkSilkAddress::CDarkSilkAddress, dumpprivkey, CSandstormPool::SetCollateralAddress, SecureMsgGetLocalPublicKey, SecureMsgEncrypt, SecureMsgSend, SecureMsgDecrypt, BOOST_AUTO_TEST_CASE.
bool CBase58Data::SetString(const std::string &str)
References SetString.
std::string CBase58Data::ToString() const
References vchVersion, vchData, EncodeBase58Check.
Referenced by AddressTablePriv::refreshAddressTable, getOutputs, getInputs, TransactionRecord::decomposeTransaction, WalletModel::sendCoins, WalletModel::listCoins, dumpprivkey, dumpwallet, getblocktemplate, validateaddress, validatepubkey, smsglocalkeys, stormnode, createmultisig, getnewaddress, getaccountaddress, getaddressesbyaccount, addmultisigaddress, addredeemscript, ListReceived, SecureMsgAddWalletAddresses, SecureMsgScanMessage, SecureMsgAddAddress, SecureMsgEncrypt, SecureMsgSend, SecureMsgDecrypt, CBudgetManager::FillBlockPayee, CFinalizedBudget::IsTransactionValid, CStormnodePayments::FillBlockPayee, CStormnodePayments::ProcessMessageStormnodePayments, CStormnodeBlockPayees::IsTransactionValid, CStormnodeBlockPayees::GetRequiredPaymentsString, CStormnodePayments::ProcessBlock, BOOST_AUTO_TEST_CASE, CWallet::UnlockStealthAddresses, CWallet::SendStealthMoneyToDestination, CWallet::FindStealthTransactions.
int CBase58Data::CompareTo(const CBase58Data &b58) const
References vchVersion, vchData.
Referenced by operator==, operator<=, operator>=, operator<, operator>.
bool CBase58Data::operator==(const CBase58Data &b58) const
References CompareTo.
bool CBase58Data::operator<=(const CBase58Data &b58) const
References CompareTo.
bool CBase58Data::operator>=(const CBase58Data &b58) const
References CompareTo.
bool CBase58Data::operator<(const CBase58Data &b58) const
References CompareTo.
bool CBase58Data::operator>(const CBase58Data &b58) const
References CompareTo.