leveldb::Arena
char* leveldb::Arena::alloc_ptr_
size_t leveldb::Arena::alloc_bytes_remaining_
std::vector<char*> leveldb::Arena::blocks_
size_t leveldb::Arena::blocks_memory_
leveldb::Arena::Arena()
leveldb::Arena::~Arena()
char * leveldb::Arena::Allocate(size_t bytes)
Referenced by leveldb::MemTable::Add, leveldb::TEST.
char * leveldb::Arena::AllocateAligned(size_t bytes)
Referenced by leveldb::TEST.
size_t leveldb::Arena::MemoryUsage() const
Referenced by leveldb::MemTable::ApproximateMemoryUsage, leveldb::TEST.
char * leveldb::Arena::AllocateFallback(size_t bytes)
char * leveldb::Arena::AllocateNewBlock(size_t block_bytes)
leveldb::Arena::Arena(const Arena &)
void leveldb::Arena::operator=(const Arena &)