CStormnodePayments
int CStormnodePayments::nSyncedFromPeer
int CStormnodePayments::nLastBlockHeight
std::map<uint256, CStormnodePaymentWinner> CStormnodePayments::mapStormnodePayeeVotes
Referenced by ProcessMessageStormnodePayments, AddWinningStormnode, CleanPaymentList, Sync, ToString, CStormnodeSync::AddedStormnodeWinner.
std::map<int, CStormnodeBlockPayees> CStormnodePayments::mapStormnodeBlocks
Referenced by GetBlockPayee, IsScheduled, AddWinningStormnode, GetRequiredPaymentsString, IsTransactionValid, CleanPaymentList, ToString, GetOldestBlock, GetNewestBlock, CStormnode::GetLastPaid.
std::map<uint256, int> CStormnodePayments::mapStormnodesLastVote
CStormnodePayments::ADD_SERIALIZE_METHODS
CStormnodePayments::CStormnodePayments()
void CStormnodePayments::Clear()
References LOCK2.
Referenced by CStormnodePaymentDB::Read.
bool CStormnodePayments::AddWinningStormnode(CStormnodePaymentWinner &winner)
References GetBlockHash, CStormnodePaymentWinner::nBlockHeight, LOCK2, mapStormnodePayeeVotes, CStormnodePaymentWinner::GetHash, mapStormnodeBlocks, IsReferenceNode, CStormnodePaymentWinner::vinStormnode, CStormnodePaymentWinner::payee.
Referenced by ProcessMessageStormnodePayments, ProcessBlock.
bool CStormnodePayments::ProcessBlock(int nBlockHeight)
References fStormNode, IsReferenceNode, activeStormnode, CActiveStormnode::vin, snodeman, CStormnodeMan::GetStormnodeRank, SNPAYMENTS_SIGNATURES_TOTAL, budget, CBudgetManager::IsBudgetPaymentBlock, LogPrintf, CTxIn::ToString, CStormnodeMan::GetNextStormnodeInQueueForPayment, CStormnodePaymentWinner::nBlockHeight, GetScriptForDestination, CStormnode::pubkey, CPubKey::GetID, CStormnodePaymentWinner::AddPayee, ExtractDestination, CBase58Data::ToString, sandStormSigner, CSandStormSigner::SetKey, strStormNodePrivKey, CStormnodePaymentWinner::Sign, AddWinningStormnode, CStormnodePaymentWinner::Relay.
void CStormnodePayments::Sync(CNode *node, int nCountNeeded)
References LOCK, pindexBest, snodeman, CStormnodeMan::CountEnabled, mapStormnodePayeeVotes, CStormnodePaymentWinner::nBlockHeight, CBlockIndex::nHeight, CNode::PushInventory, MSG_STORMNODE_WINNER, CStormnodePaymentWinner::GetHash, CNode::PushMessage.
Referenced by ProcessMessageStormnodePayments.
void CStormnodePayments::CleanPaymentList()
References LOCK2, pindexBest, snodeman, CStormnodeMan::size, mapStormnodePayeeVotes, CBlockIndex::nHeight, CStormnodePaymentWinner::nBlockHeight, stormnodeSync, CStormnodeSync::mapSeenSyncSNW, mapStormnodeBlocks.
Referenced by ThreadCheckSandStormPool, CStormnodePaymentDB::Read.
int CStormnodePayments::LastPayment(CStormnode &sn)
bool CStormnodePayments::GetBlockPayee(int nBlockHeight, CScript &payee)
References mapStormnodeBlocks.
Referenced by FillBlockPayee, CWallet::CreateCoinStake.
bool CStormnodePayments::IsTransactionValid(const CTransaction &txNew, int nBlockHeight)
References LOCK, mapStormnodeBlocks.
Referenced by IsBlockPayeeValid.
bool CStormnodePayments::IsScheduled(CStormnode &sn, int nNotBlockHeight)
References LOCK, pindexBest, GetScriptForDestination, CStormnode::pubkey, CPubKey::GetID, CBlockIndex::nHeight, mapStormnodeBlocks.
Referenced by CStormnodeMan::GetNextStormnodeInQueueForPayment.
bool CStormnodePayments::CanVote(COutPoint outStormnode, int nBlockHeight)
References LOCK, COutPoint::hash, COutPoint::n.
Referenced by ProcessMessageStormnodePayments.
int CStormnodePayments::GetMinStormnodePaymentsProto()
References IsSporkActive.
Referenced by CStormnodeSync::Process, CStormnodeBroadcast::CheckAndUpdate, CStormnodePing::CheckAndUpdate, CStormnodeMan::CheckAndRemove, CStormnodeMan::CountEnabled, CStormnodeMan::GetNextStormnodeInQueueForPayment, CStormnodeMan::FindRandomNotInVec.
void CStormnodePayments::ProcessMessageStormnodePayments(CNode *pfrom, std::string &strCommand, CDataStream &vRecv)
References stormnodeSync, CStormnodeSync::IsBlockchainSynced, fLiteMode, Params, CChainParams::NetworkID, CChainParams::MAIN, CNode::HasFulfilledRequest, LogPrintf, Misbehaving, CNode::GetId, CNode::FulfilledRequest, Sync, CNode::addr, CService::ToString, CNode::nVersion, pindexBest, mapStormnodePayeeVotes, CBlockIndex::nHeight, CStormnodeSync::AddedStormnodeWinner, snodeman, CStormnodeMan::CountEnabled, CanVote, CStormnodeSync::IsSynced, CStormnodeMan::AskForSN, ExtractDestination, CBase58Data::ToString, AddWinningStormnode.
std::string CStormnodePayments::GetRequiredPaymentsString(int nBlockHeight)
References LOCK, mapStormnodeBlocks.
Referenced by GetRequiredPaymentsString.
void CStormnodePayments::FillBlockPayee(CTransaction &txNew, CAmount nFees)
References pindexBest, GetBlockPayee, CBlockIndex::nHeight, snodeman, CStormnodeMan::GetCurrentStormNode, GetScriptForDestination, CStormnode::pubkey, CPubKey::GetID, LogPrintf, CTransaction::vout, GetBlockValue, CBlockIndex::nBits, GetStormnodePayment, ExtractDestination, CBase58Data::ToString.
Referenced by FillBlockPayee.
std::string CStormnodePayments::ToString() const
References mapStormnodePayeeVotes, mapStormnodeBlocks.
Referenced by CStormnodePaymentDB::Read.
int CStormnodePayments::GetOldestBlock()
References LOCK, mapStormnodeBlocks.
int CStormnodePayments::GetNewestBlock()
References LOCK, mapStormnodeBlocks.
void CStormnodePayments::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE.