CDarkSilkAddress
bool CDarkSilkAddress::Set(const CKeyID &id)
References CBase58Data::SetData, Params, CChainParams::PUBKEY_ADDRESS.
Referenced by CDarkSilkAddress, validatepubkey, SecureMsgDecrypt.
bool CDarkSilkAddress::Set(const CScriptID &id)
References CBase58Data::SetData, Params, CChainParams::SCRIPT_ADDRESS.
bool CDarkSilkAddress::Set(const CTxDestination &dest)
bool CDarkSilkAddress::IsValid() const
References CBase58Data::vchData, CBase58Data::vchVersion, Params, CChainParams::Base58Prefix, CChainParams::PUBKEY_ADDRESS, CChainParams::SCRIPT_ADDRESS.
Referenced by Get, GetKeyID, IsScript, TransactionDesc::toHTML, WalletModel::validateAddress, importaddress, validateaddress, verifymessage, createrawtransaction, searchrawtransactions, smsglocalkeys, snbudget, _createmultisig, setaccount, getaccount, sendtoaddress, signmessage, getreceivedbyaddress, sendfrom, sendmany, addmultisigaddress, SecureMsgAddWalletAddresses, SecureMsgAddAddress, SecureMsgDecrypt, CStormnodeConfig::read, BOOST_AUTO_TEST_CASE.
CDarkSilkAddress::CDarkSilkAddress()
CDarkSilkAddress::CDarkSilkAddress(const CTxDestination &dest)
References Set.
CDarkSilkAddress::CDarkSilkAddress(const std::string &strAddress)
References CBase58Data::SetString.
CDarkSilkAddress::CDarkSilkAddress(const char *pszAddress)
References CBase58Data::SetString.
CTxDestination CDarkSilkAddress::Get() const
References IsValid, id, CBase58Data::vchData, CBase58Data::vchVersion, Params, CChainParams::PUBKEY_ADDRESS, CChainParams::SCRIPT_ADDRESS.
Referenced by AddressTablePriv::refreshAddressTable, AddressTableModel::labelForAddress, MessageModel::sendMessages, TransactionDesc::toHTML, WalletModel::sendCoins, importaddress, validateaddress, validatepubkey, createrawtransaction, searchrawtransactions, snbudget, setaccount, getaccount, sendtoaddress, getreceivedbyaddress, sendfrom, sendmany, CSandstormPool::SetCollateralAddress, BOOST_AUTO_TEST_CASE, CWallet::SendStealthMoneyToDestination, ReadKeyValue.
bool CDarkSilkAddress::GetKeyID(CKeyID &keyID) const
References IsValid, CBase58Data::vchVersion, Params, CChainParams::PUBKEY_ADDRESS, id, CBase58Data::vchData.
Referenced by dumpprivkey, verifymessage, smsglocalkeys, smsggetpubkey, _createmultisig, signmessage, addmultisigaddress, SecureMsgGetLocalPublicKey, SecureMsgAddAddress, SecureMsgEncrypt, SecureMsgDecrypt.
bool CDarkSilkAddress::IsScript() const
References IsValid, CBase58Data::vchVersion, Params, CChainParams::Base58Prefix, CChainParams::SCRIPT_ADDRESS.
Referenced by BOOST_AUTO_TEST_CASE.