CWallet
typedef std::multimap<COutPoint, uint256> CWallet::TxSpends
typedef std::map<unsigned int, CMasterKey> CWallet::MasterKeyMap
typedef std::pair<CWalletTx*, CAccountingEntry*> CWallet::TxPair
typedef std::multimap<int64_t, TxPair > CWallet::TxItems
CWalletDB* CWallet::pwalletdbEncryption
int CWallet::nWalletVersion
int CWallet::nWalletMaxVersion
TxSpends CWallet::mapTxSpends
CCriticalSection CWallet::cs_wallet
Main wallet lock. This lock protects all the fields added by CWallet except for: fFileBacked (immutable after instantiation) strWalletFile (immutable after instantiation)
Referenced by CActiveStormnode::ManageStatus, AppInit2, CheckWork, CheckStake, AddressTablePriv::refreshAddressTable, AddressTableModel::setData, AddressTableModel::addRow, AddressTableModel::removeRows, AddressTableModel::labelForAddress, MessageModel::sendMessages, TransactionDesc::toHTML, TransactionTablePriv::refreshWallet, TransactionTablePriv::updateWallet, TransactionTablePriv::index, TransactionTablePriv::describe, WalletModel::pollBalanceChanged, WalletModel::sendCoins, WalletModel::changePassphrase, WalletModel::getOutputs, WalletModel::listCoins, WalletModel::isLockedCoin, WalletModel::lockCoin, WalletModel::unlockCoin, WalletModel::listLockedCoins, importprivkey, importaddress, CRPCTable::execute, listaddressgroupings, scanforalltxns, CSandstormPool::UnlockCoins, CSandstormPool::CheckFinalTransaction, CWalletDB::ReorderTransactions, CWalletDB::LoadWallet.
bool CWallet::fFileBacked
Referenced by BackupWallet.
bool CWallet::fWalletUnlockAnonymizeOnly
Referenced by WalletModel::getEncryptionStatus, WalletModel::isAnonymizeOnlyUnlocked.
std::string CWallet::strWalletFile
Referenced by AppInit2, GetAccountAddress, GetAccountBalance, movecmd, listaccounts, BOOST_AUTO_TEST_CASE, BackupWallet.
std::set<int64_t> CWallet::setKeyPool
Referenced by AppInit2, ReadKeyValue.
std::map<CKeyID, CKeyMetadata> CWallet::mapKeyMetadata
Referenced by importprivkey, importwallet, ReadKeyValue.
std::set<CStealthAddress> CWallet::stealthAddresses
Referenced by AddressTablePriv::refreshAddressTable, AddressTableModel::addRow, AddressTableModel::labelForAddress, liststealthaddresses, importstealthaddress, ReadKeyValue.
StealthKeyMetaMap CWallet::mapStealthKeyMeta
Referenced by ReadKeyValue.
int CWallet::nLastFilteredHeight
uint32_t CWallet::nStealth
Referenced by scanforstealthtxns.
uint32_t CWallet::nFoundStealth
Referenced by scanforstealthtxns.
MasterKeyMap CWallet::mapMasterKeys
Referenced by ReadKeyValue.
unsigned int CWallet::nMasterKeyMaxID
Referenced by ReadKeyValue.
std::map<uint256, CWalletTx> CWallet::mapWallet
Referenced by AppInit2, TransactionTablePriv::refreshWallet, TransactionTablePriv::updateWallet, TransactionTablePriv::index, TransactionTablePriv::describe, WalletModel::getOutputs, WalletModel::listCoins, GetAccountAddress, getreceivedbyaddress, getreceivedbyaccount, GetAccountBalance, getbalance, ListReceived, listaccounts, listsinceblock, gettransaction, BOOST_AUTO_TEST_CASE, CWalletDB::ReorderTransactions, ReadKeyValue, CWalletDB::LoadWallet.
int64_t CWallet::nOrderPosNext
Referenced by BOOST_AUTO_TEST_CASE, SetNull, CWalletDB::ReorderTransactions, ReadKeyValue.
std::map<uint256, int> CWallet::mapRequestCount
Referenced by ProcessConsensusVote, CheckWork, CheckStake.
std::map<CTxDestination, std::string> CWallet::mapAddressBook
Referenced by AppInit2, AddressTablePriv::refreshAddressTable, AddressTableModel::setData, AddressTableModel::addRow, AddressTableModel::labelForAddress, MessageModel::sendMessages, TransactionDesc::toHTML, WalletModel::sendCoins, dumpwallet, validateaddress, validatepubkey, smsglocalkeys, setaccount, getaccount, getaddressesbyaccount, listaddressgroupings, GetAccountAddresses, ListReceived, ListTransactions, listaccounts, SecureMsgAddWalletAddresses, SecureMsgSend, ReadKeyValue.
CPubKey CWallet::vchDefaultKey
Referenced by AppInit2, ReadKeyValue, CWalletDB::LoadWallet.
std::set<COutPoint> CWallet::setLockedCoins
int64_t CWallet::nTimeFirstKey
Referenced by importprivkey, importwallet, SetNull, ReadKeyValue, CWalletDB::LoadWallet.
boost::signals2::signal<void (CWallet *wallet, const CTxDestination &address, const std::string &label, bool isMine, ChangeType status)> CWallet::NotifyAddressBookChanged
Address book entry changed. called with lock cs_wallet held.
boost::signals2::signal<void (CWallet *wallet, const uint256 &hashTx, ChangeType status)> CWallet::NotifyTransactionChanged
Wallet transaction added, removed or updated. called with lock cs_wallet held.
boost::signals2::signal<void (const std::string &title, int nProgress)> CWallet::ShowProgress
Show progress e.g. for rescan
Referenced by importwallet.
boost::signals2::signal<void (bool fHaveWatchOnly)> CWallet::NotifyWatchonlyChanged
Watch-only address added
bool CWallet::SelectCoinsForStaking(const CAmount &nTargetValue, unsigned int nSpendTime, std::set< std::pair< const CWalletTx *, unsigned int > > &setCoinsRet, CAmount &nValueRet) const
bool CWallet::SelectCoins(const CAmount &nTargetValue, unsigned int nSpendTime, set< pair< const CWalletTx *, unsigned int > > &setCoinsRet, CAmount &nValueRet, const CCoinControl *coinControl, AvailableCoinsType coin_type, bool useIX) const
void CWallet::AddToSpends(const COutPoint &outpoint, const uint256 &wtxid)
void CWallet::AddToSpends(const uint256 &wtxid)
void CWallet::SyncMetaData(std::pair< TxSpends::iterator, TxSpends::iterator >)
int CWallet::GetRealInputSandstormRounds(CTxIn in, int rounds) const
bool CWallet::SelectCoinsDark(CAmount nValueMin, CAmount nValueMax, std::vector< CTxIn > &setCoinsRet, CAmount &nValueRet, int nSandstormRoundsMin, int nSandstormRoundsMax) const
References ONLY_NONDENOMINATED_NOTSN, ONLY_DENOMINATED, COutput::tx, CTransaction::vout, COutput::i, fStormNode, CTransaction::GetHash, CTxIn::prevPubKey.
Referenced by CSandstormPool::DoAutomaticDenominating.
bool CWallet::SelectCoinsByDenominations(int nDenom, CAmount nValueMin, CAmount nValueMax, std::vector< CTxIn > &vCoinsRet, std::vector< COutput > &vCoinsRet2, CAmount &nValueRet, int nSandstormRoundsMin, int nSandstormRoundsMax)
References ONLY_DENOMINATED, COutput::tx, CTransaction::vout, COutput::i, CTransaction::GetHash, rand, CTxIn::prevPubKey.
Referenced by CSandstormPool::DoAutomaticDenominating.
bool CWallet::SelectCoinsDarkDenominated(CAmount nTargetValue, std::vector< CTxIn > &setCoinsRet, CAmount &nValueRet) const
bool CWallet::SelectCoinsStormnode(CTxIn &vin, CAmount &nValueRet, CScript &pubScript) const
bool CWallet::HasCollateralInputs() const
References COutput::tx, CTransaction::vout, COutput::i.
Referenced by CSandstormPool::DoAutomaticDenominating, CSandstormPool::CreateDenominated.
bool CWallet::IsCollateralAmount(CAmount nInputAmount) const
int CWallet::CountInputsWithAmount(CAmount nInputAmount)
References LOCK, CWalletTx::IsTrusted, CMerkleTx::GetDepthInMainChain, CTransaction::vout, IsMine, COutput::tx, CTransaction::GetHash, COutput::i, CWalletTx::IsSpent.
Referenced by CSandstormPool::CreateDenominated.
const CWalletTx * CWallet::GetWalletTx(const uint256 &hash) const
References LOCK.
Referenced by CWalletTx::IsTrusted.
bool CWallet::SelectCoinsCollateral(std::vector< CTxIn > &setCoinsRet, CAmount &nValueRet) const
References COutput::tx, CTransaction::vout, COutput::i, CTransaction::GetHash, CTxIn::prevPubKey.
bool CWallet::SelectCoinsWithoutDenomination(const CAmount &nTargetValue, std::set< std::pair< const CWalletTx *, unsigned int > > &setCoinsRet, CAmount &nValueRet) const
References ONLY_NONDENOMINATED, COutput::tx, CTransaction::vout, COutput::i.
bool CWallet::GetTransaction(const uint256 &hashTx, CWalletTx &wtx)
References LOCK.
int CWallet::GetInputSandstormRounds(CTxIn in) const
References LOCK, nSandstormRounds.
Referenced by CWalletTx::GetAnonymizableCredit.
CWallet::CWallet()
References SetNull.
CWallet::CWallet(std::string strWalletFileIn)
References SetNull.
void CWallet::SetNull()
References FEATURE_BASE, nOrderPosNext, nTimeFirstKey.
Referenced by CWallet.
bool CWallet::CanSupportFeature(enum WalletFeature wf)
References AssertLockHeld.
void CWallet::AvailableCoinsForStaking(std::vector< COutput > &vCoins, unsigned int nSpendTime) const
References LOCK2, cs_main, CMerkleTx::GetDepthInMainChain, nStakeMinConfirmations, CTransaction::nTime, nStakeMinAge, CMerkleTx::GetBlocksToMaturity, CTransaction::vout, CWalletTx::IsSpent, IsMine, nMinimumInputValue.
void CWallet::AvailableCoins(std::vector< COutput > &vCoins, bool fOnlyConfirmed=true, const CCoinControl *coinControl=NULL, AvailableCoinsType coin_type=ALL_COINS, bool useIX=false) const
References LOCK2, cs_main, IsFinalTx, CWalletTx::IsTrusted, CTransaction::IsCoinBase, CMerkleTx::GetBlocksToMaturity, CTransaction::IsCoinStake, CMerkleTx::GetDepthInMainChain, CTransaction::vout, ONLY_DENOMINATED, ONLY_NONDENOMINATED, ONLY_NONDENOMINATED_NOTSN, IsMine, CWalletTx::IsSpent, CCoinControl::HasSelected, CCoinControl::IsSelected, ISMINE_SPENDABLE.
Referenced by CActiveStormnode::SelectCoinsStormnode, WalletModel::getBalance, WalletModel::listCoins.
bool CWallet::SelectCoinsMinConf(const CAmount &nTargetValue, unsigned int nSpendTime, int nConfMine, int nConfTheirs, vector< COutput > vCoins, set< pair< const CWalletTx *, unsigned int > > &setCoinsRet, CAmount &nValueRet) const
References GetRandInt, less_then_denom, fDebug, COutput::fSpendable, COutput::tx, COutput::nDepth, CWalletTx::IsFromMe, ISMINE_ALL, COutput::i, CTransaction::vout, FormatMoney, LogPrintf.
Referenced by BOOST_AUTO_TEST_CASE.
bool CWallet::SelectCoinsMinConfByCoinAge(const CAmount &nTargetValue, unsigned int nSpendTime, int nConfMine, int nConfTheirs, vector< COutput > vCoins, set< pair< const CWalletTx *, unsigned int > > &setCoinsRet, CAmount &nValueRet) const
References COutput::fSpendable, PAIRTYPE, CWalletTx::IsFromMe, ISMINE_ALL, CTransaction::nTime, CTransaction::vout, gcd, fDebug, FormatMoney.
bool CWallet::IsSpent(const uint256 &hash, unsigned int n) const
Referenced by CWalletTx::GetAnonymizableCredit, CWalletTx::GetDenominatedCredit, CWalletTx::GetAvailableWatchOnlyCredit.
bool CWallet::IsLockedCoin(uint256 hash, unsigned int n) const
References AssertLockHeld.
Referenced by WalletModel::isLockedCoin, CWalletTx::GetAnonymizableCredit.
void CWallet::LockCoin(COutPoint &output)
References AssertLockHeld.
Referenced by CActiveStormnode::ManageStatus, CActiveStormnode::SelectCoinsStormnode, AppInit2, WalletModel::lockCoin.
void CWallet::UnlockCoin(COutPoint &output)
References AssertLockHeld.
Referenced by CActiveStormnode::SelectCoinsStormnode, WalletModel::unlockCoin, CSandstormPool::UnlockCoins.
void CWallet::UnlockAllCoins()
References AssertLockHeld.
void CWallet::ListLockedCoins(std::vector< COutPoint > &vOutpts)
References AssertLockHeld.
Referenced by WalletModel::listLockedCoins.
CAmount CWallet::GetTotalValue(std::vector< CTxIn > vCoins)
References CTxIn::prevout, COutPoint::hash, COutPoint::n, CTransaction::vout, LogPrintf.
CPubKey CWallet::GenerateNewKey()
References AssertLockHeld, FEATURE_COMPRPUBKEY, CKey::MakeNewKey, CKey::GetPubKey, CKey::VerifyPubKey, GetTime, CPubKey::GetID.
bool CWallet::AddKeyPubKey(const CKey &key, const CPubKey &pubkey)
References AssertLockHeld, CCryptoKeyStore::AddKeyPubKey, GetScriptForDestination, CPubKey::GetID, CWalletDB::WriteKey, CKey::GetPrivKey.
Referenced by importprivkey.
bool CWallet::LoadKey(const CKey &key, const CPubKey &pubkey)
References CCryptoKeyStore::AddKeyPubKey.
Referenced by ReadKeyValue.
bool CWallet::LoadKeyMetadata(const CPubKey &pubkey, const CKeyMetadata &metadata)
References AssertLockHeld, CKeyMetadata::nCreateTime, CPubKey::GetID, meta.
Referenced by ReadKeyValue.
bool CWallet::LoadMinVersion(int nVersion)
References AssertLockHeld.
Referenced by CWalletDB::LoadWallet.
bool CWallet::AddCryptedKey(const CPubKey &vchPubKey, const std::vector< unsigned char > &vchCryptedSecret)
References CCryptoKeyStore::AddCryptedKey, LOCK, CPubKey::GetID, CWalletDB::WriteCryptedKey.
bool CWallet::LoadCryptedKey(const CPubKey &vchPubKey, const std::vector< unsigned char > &vchCryptedSecret)
References CCryptoKeyStore::AddCryptedKey.
Referenced by ReadKeyValue.
bool CWallet::AddCScript(const CScript &redeemScript)
References CBasicKeyStore::AddCScript, CWalletDB::WriteCScript, Hash160.
Referenced by addmultisigaddress, addredeemscript.
bool CWallet::LoadCScript(const CScript &redeemScript)
References CScript::GetID, LogPrintf, CBasicKeyStore::AddCScript.
Referenced by ReadKeyValue.
bool CWallet::AddWatchOnly(const CScript &dest)
References CBasicKeyStore::AddWatchOnly, CWalletDB::WriteWatchOnly.
Referenced by importaddress.
bool CWallet::RemoveWatchOnly(const CScript &dest)
References AssertLockHeld, CBasicKeyStore::RemoveWatchOnly.
bool CWallet::LoadWatchOnly(const CScript &dest)
References CBasicKeyStore::AddWatchOnly.
Referenced by ReadKeyValue.
bool CWallet::Lock()
References fDebug, LOCK, CStealthAddress::Encoded, CStealthAddress::scan_pubkey, CWalletDB::ReadStealthAddress, CStealthAddress::spend_secret.
Referenced by WalletModel::setWalletLocked, WalletModel::changePassphrase, stormnode, walletlock.
bool CWallet::Unlock(const SecureString &strWalletPassphrase, bool anonimizeOnly=false)
References LOCK, CCrypter::SetKeyFromPassphrase, CCrypter::Decrypt, CCryptoKeyStore::Unlock, SecureMsgWalletUnlocked.
Referenced by WalletModel::setWalletLocked, stormnode, walletpassphrase.
bool CWallet::ChangeWalletPassphrase(const SecureString &strOldWalletPassphrase, const SecureString &strNewWalletPassphrase)
References LOCK, CCrypter::SetKeyFromPassphrase, CCrypter::Decrypt, CCryptoKeyStore::Unlock, GetTimeMillis, LogPrintf, CCrypter::Encrypt, CWalletDB::WriteMasterKey.
Referenced by WalletModel::changePassphrase, walletpassphrasechange.
bool CWallet::EncryptWallet(const SecureString &strWalletPassphrase)
References RandAddSeedPerfmon, WALLET_CRYPTO_KEY_SIZE, GetRandBytes, nDerivationMethodIndex, CMasterKey::vchSalt, WALLET_CRYPTO_SALT_SIZE, GetTimeMillis, CCrypter::SetKeyFromPassphrase, CMasterKey::nDerivationMethod, CMasterKey::nDeriveIterations, LogPrintf, CCrypter::Encrypt, CMasterKey::vchCryptedKey, LOCK, fDebug, CStealthAddress::Encoded, CStealthAddress::spend_secret, Hash, CStealthAddress::spend_pubkey, EncryptSecret, CDB::Rewrite.
Referenced by WalletModel::setWalletEncrypted, encryptwallet.
void CWallet::GetKeyBirthTimes(std::map< CKeyID, int64_t > &mapKeyBirth) const
References AssertLockHeld, FindBlockByHeight, nBestHeight, mapBlockIndex, CMerkleTx::hashBlock, CTransaction::vout, ExtractAffectedKeys, CTxOut::scriptPubKey.
Referenced by dumpwallet.
int64_t CWallet::IncOrderPosNext(CWalletDB *pwalletdb=NULL)
Increment the next transaction order id next transaction order id
References AssertLockHeld, CWalletDB::WriteOrderPosNext.
Referenced by movecmd, BOOST_AUTO_TEST_CASE.
CWallet::TxItems CWallet::OrderedTxItems(std::list< CAccountingEntry > &acentries, std::string strAccount="")
Get the wallet's activity log multimap of ordered transactions and accounting entries Returned pointers are only valid within the scope of passed acentries
References AssertLockHeld, CWalletTx::nOrderPos, CWalletDB::ListAccountCreditDebit, CAccountingEntry::nOrderPos.
Referenced by listtransactions.
void CWallet::MarkDirty()
References LOCK, PAIRTYPE, CWalletTx::MarkDirty.
Referenced by importprivkey, importaddress, importwallet, scanforalltxns.
bool CWallet::AddToWallet(const CWalletTx &wtxIn, bool fFromLoadWallet=false)
References CTransaction::GetHash, hash, CWalletTx::BindWallet, LOCK, CWalletTx::nTimeReceived, GetAdjustedTime, CWalletTx::nOrderPos, CWalletTx::nTimeSmart, CMerkleTx::hashBlock, mapBlockIndex, CAccountingEntry::nTime, LogPrintf, base_uint< BITS >::ToString, CMerkleTx::nIndex, CMerkleTx::vMerkleBranch, CWalletTx::fFromMe, CWalletTx::UpdateSpent, CWalletTx::vfSpent, CWalletTx::WriteToDisk, CWalletTx::MarkDirty, CT_NEW, CT_UPDATED, GetArg, base_uint< BITS >::GetHex, runCommand.
Referenced by BOOST_AUTO_TEST_CASE, ReadKeyValue.
void CWallet::SyncTransaction(const CTransaction &tx, const CBlock *pblock, bool fConnect=true)
References LOCK2, cs_main, CTransaction::vin, CTxIn::prevout, COutPoint::hash, CTransaction::IsCoinStake.
bool CWallet::AddToWalletIfInvolvingMe(const CTransaction &tx, const CBlock *pblock, bool fUpdate)
References AssertLockHeld, CTransaction::GetHash, IsMine, CWalletTx::mapValue, CMerkleTx::SetMerkleBranch.
Referenced by scanforstealthtxns.
void CWallet::EraseFromWallet(const uint256 &hash)
References LOCK, CWalletDB::EraseTx.
int CWallet::ScanForWalletTransactions(CBlockIndex *pindexStart, bool fUpdate=false)
References LOCK2, cs_main, CBlockIndex::nTime, CBlockIndex::pnext, CBlock::ReadFromDisk, CBlock::vtx.
Referenced by AppInit2, importprivkey, importaddress, importwallet, scanforalltxns.
void CWallet::ReacceptWalletTransactions()
References txdb, LOCK2, cs_main, PAIRTYPE, CTransaction::GetHash, CMerkleTx::GetDepthInMainChain, CTransaction::IsCoinBase, LOCK, mempool, CTxMemPool::cs, CMerkleTx::AcceptToMemoryPool, CWalletTx::IsSpent, CTransaction::IsCoinStake, CTxDB::ReadTxIndex, CTxIndex::vSpent, CTransaction::vout, LogPrintf, IsMine, CWalletTx::MarkSpent, FormatMoney, CWalletTx::GetCredit, ISMINE_ALL, base_uint< BITS >::ToString, CWalletTx::MarkDirty, CWalletTx::WriteToDisk, CWalletTx::AcceptWalletTransaction, pindexGenesisBlock.
Referenced by AppInit2, importprivkey, importaddress, importwallet, scanforalltxns.
void CWallet::ResendWalletTransactions(bool fForce=false)
References GetTime, GetRand, nTimeBestReceived, LogPrintf, txdb, LOCK, PAIRTYPE, CWalletTx::nTimeReceived, CWalletTx::RelayWalletTransaction.
CAmount CWallet::GetBalance() const
References LOCK2, cs_main, CWalletTx::IsTrusted, CWalletTx::GetAvailableCredit.
Referenced by CActiveStormnode::ManageStatus, OverviewPage::updateSandstormProgress, WalletModel::getBalance, getinfo, SendMoney, getbalance, sendmany.
CAmount CWallet::GetUnconfirmedBalance() const
References LOCK2, cs_main, IsFinalTx, CWalletTx::IsTrusted, CMerkleTx::GetDepthInMainChain, CWalletTx::GetAvailableCredit.
Referenced by WalletModel::getUnconfirmedBalance.
CAmount CWallet::GetImmatureBalance() const
References LOCK2, cs_main, CWalletTx::GetImmatureCredit.
Referenced by WalletModel::getImmatureBalance.
CAmount CWallet::GetStake() const
References LOCK2, cs_main, CTransaction::IsCoinStake, CMerkleTx::GetBlocksToMaturity, CMerkleTx::GetDepthInMainChain, GetCredit, ISMINE_ALL.
Referenced by WalletModel::getStake, getinfo.
CAmount CWallet::GetNewMint() const
References LOCK2, cs_main, CTransaction::IsCoinBase, CMerkleTx::GetBlocksToMaturity, CMerkleTx::GetDepthInMainChain, GetCredit, ISMINE_ALL.
Referenced by getinfo.
CAmount CWallet::GetAnonymizableBalance(bool includeAlreadyAnonymized=false) const
References fLiteMode, LOCK2, cs_main, CWalletTx::IsTrusted, CTransaction::vout, IsMine, CTransaction::IsCoinBase, CMerkleTx::GetBlocksToMaturity, nSandstormRounds.
Referenced by OverviewPage::updateSandstormProgress, CSandstormPool::DoAutomaticDenominating.
CAmount CWallet::GetAnonymizedBalance() const
References fLiteMode, LOCK, CWalletTx::IsTrusted, CMerkleTx::GetDepthInMainChain, CTransaction::vout, IsMine, COutput::tx, CTransaction::GetHash, COutput::i, CWalletTx::IsSpent, nSandstormRounds.
Referenced by OverviewPage::updateSandstormProgress, WalletModel::getAnonymizedBalance, getinfo, CSandstormPool::DoAutomaticDenominating.
CAmount CWallet::GetWatchOnlyBalance() const
References LOCK2, cs_main, CWalletTx::IsTrusted, CWalletTx::GetAvailableWatchOnlyCredit.
Referenced by WalletModel::getWatchBalance.
CAmount CWallet::GetWatchOnlyStake() const
References LOCK2, cs_main, CTransaction::IsCoinStake, CMerkleTx::GetBlocksToMaturity, CMerkleTx::GetDepthInMainChain, GetCredit, ISMINE_WATCH_ONLY.
Referenced by WalletModel::getWatchStake.
CAmount CWallet::GetUnconfirmedWatchOnlyBalance() const
References LOCK2, cs_main, IsFinalTx, CWalletTx::IsTrusted, CMerkleTx::GetDepthInMainChain, CWalletTx::GetAvailableWatchOnlyCredit.
Referenced by WalletModel::getWatchUnconfirmedBalance.
CAmount CWallet::GetImmatureWatchOnlyBalance() const
References LOCK2, cs_main, CWalletTx::GetImmatureWatchOnlyCredit.
Referenced by WalletModel::getWatchImmatureBalance.
double CWallet::GetAverageAnonymizedRounds() const
References fLiteMode, LOCK, CWalletTx::IsTrusted, CMerkleTx::GetDepthInMainChain, CTransaction::vout, IsMine, COutput::tx, CTransaction::GetHash, COutput::i, CWalletTx::IsSpent.
Referenced by OverviewPage::updateSandstormProgress.
CAmount CWallet::GetNormalizedAnonymizedBalance() const
References fLiteMode, LOCK, CWalletTx::IsTrusted, CMerkleTx::GetDepthInMainChain, CTransaction::vout, IsMine, COutput::tx, CTransaction::GetHash, COutput::i, CWalletTx::IsSpent, nSandstormRounds.
Referenced by OverviewPage::updateSandstormProgress.
CAmount CWallet::GetDenominatedBalance(bool onlyDenom=true, bool onlyUnconfirmed=false, bool includeAlreadyAnonymized=true) const
References fLiteMode, LOCK2, cs_main, CMerkleTx::GetDepthInMainChain, IsFinalTx, CWalletTx::IsTrusted, CTransaction::vout, IsMine, nSandstormRounds.
Referenced by OverviewPage::updateSandstormProgress, CSandstormPool::DoAutomaticDenominating.
bool CWallet::CreateTransaction(const std::vector< std::pair< CScript, CAmount > > &vecSend, CWalletTx &wtxNew, CReserveKey &reservekey, CAmount &nFeeRet, int32_t &nChangePos, std::string &strFailReason, const CCoinControl *coinControl=NULL, AvailableCoinsType coin_type=ALL_COINS, bool useIX=false, CAmount nFeePay=0)
Referenced by WalletModel::sendCoins, SendMoney, sendmany, CSandstormPool::MakeCollateralAmounts, CSandstormPool::CreateDenominated.
bool CWallet::CreateTransaction(CScript scriptPubKey, const CAmount &nValue, std::string &sNarr, CWalletTx &wtxNew, CReserveKey &reservekey, CAmount &nFeeRet, const CCoinControl *coinControl=NULL, AvailableCoinsType coin_type=ALL_COINS, bool useIX=false, CAmount nFeePay=0)
References OP_RETURN, LogPrintf.
bool CWallet::CommitTransaction(CWalletTx &wtxNew, CReserveKey &reservekey, std::string strCommand="tx")
References PAIRTYPE, CWalletTx::mapValue, LOCK2, cs_main, LogPrintf, CTransaction::ToString, CReserveKey::KeepKey, CTransaction::vin, CTxIn::prevout, COutPoint::hash, CWalletTx::BindWallet, CWalletTx::MarkSpent, COutPoint::n, CWalletTx::WriteToDisk, CTransaction::GetHash, CT_UPDATED, CMerkleTx::AcceptToMemoryPool, CWalletTx::RelayWalletTransaction.
Referenced by WalletModel::sendCoins, snbudget, SendMoney, sendmany, CSandstormPool::MakeCollateralAmounts, CSandstormPool::CreateDenominated, CBudgetManager::SubmitFinalBudget.
uint64_t CWallet::GetStakeWeight() const
References nReserveBalance, GetTime, txdb, LOCK2, cs_main, PAIRTYPE, nStakeMinConfirmations.
Referenced by getmininginfo, getstakinginfo.
uint64_t CWallet::GetStakeWeight2() const
bool CWallet::CreateCoinStake(const CKeyStore &keystore, unsigned int nBits, int64_t nSearchInterval, CAmount nFees, CTransaction &txNew, CKey &key)
References pindexBest, CBigNum::SetCompact, CTransaction::vin, CTransaction::vout, CScript::clear, nReserveBalance, CTransaction::nTime, txdb, PAIRTYPE, CheckKernel, Solver, TX_PUBKEY, TX_PUBKEYHASH, CKeyStore::GetKey, CKey::GetPubKey, OP_CHECKSIG, Hash160, GetWeight, nStakeMinAge, Params, CChainParams::TESTNET, CBlockIndex::nHeight, CChainParams::MAIN, stormnodePayments, CStormnodePayments::GetBlockPayee, snodeman, CStormnodeMan::GetCurrentStormNode, GetScriptForDestination, CStormnode::pubkey, CPubKey::GetID, LogPrintf, FillBlockPayee, SignSignature, GetSerializeSize, SER_NETWORK.
string CWallet::SendMoney(CScript scriptPubKey, CAmount nValue, std::string &sNarr, CWalletTx &wtxNew, bool fAskFee=false)
References _, LogPrintf, strprintf, FormatMoney.
string CWallet::SendMoneyToDestination(const CTxDestination &address, CAmount nValue, std::string &sNarr, CWalletTx &wtxNew, bool fAskFee=false)
References _, nTransactionFee, CScript::SetDestination, SendMoney.
Referenced by sendtoaddress, sendfrom.
bool CWallet::NewStealthAddress(std::string &sError, std::string &sLabel, CStealthAddress &sxAddr)
References GenerateRandomSecret, SecretToPublicKey, fDebug, CStealthAddress::label, CStealthAddress::scan_pubkey, CStealthAddress::spend_pubkey, CStealthAddress::scan_secret, ec_secret::e, CStealthAddress::spend_secret.
Referenced by AddressTableModel::addRow, getnewstealthaddress.
bool CWallet::AddStealthAddress(CStealthAddress &sxAddr)
References LOCK, CStealthAddress::scan_secret, ec_secret_size, CStealthAddress::spend_secret, Hash, CStealthAddress::spend_pubkey, EncryptSecret, CStealthAddress::Encoded, CWalletDB::WriteStealthAddress, CStealthAddress::label, CT_NEW.
Referenced by AddressTableModel::addRow, getnewstealthaddress, importstealthaddress.
bool CWallet::UnlockStealthAddresses(const CKeyingMaterial &vMasterKeyIn)
References fDebug, CStealthAddress::Encoded, Hash, CStealthAddress::spend_pubkey, DecryptSecret, CStealthAddress::spend_secret, ec_secret::e, SecretToPublicKey, CPubKey::GetID, CBase58Data::ToString, CStealthAddress::scan_pubkey, CStealthKeyMetadata::pkScan, CPubKey::Raw, ec_secret_size, CStealthKeyMetadata::pkEphem, StealthSecretSpend, CKey::Set, CKey::GetPubKey, CPubKey::IsValid, CKey::IsValid.
bool CWallet::UpdateStealthAddress(std::string &addr, std::string &label, bool addIfNotExist)
References fDebug, CT_UPDATED, CStealthAddress::label, CT_NEW, CStealthAddress::scan_secret, ec_secret_size.
Referenced by AddressTableModel::setData, WalletModel::sendCoins.
bool CWallet::CreateStealthTransaction(CScript scriptPubKey, CAmount nValue, std::vector< uint8_t > &P, std::vector< uint8_t > &narr, std::string &sNarr, CWalletTx &wtxNew, CReserveKey &reservekey, CAmount &nFeeRet, const CCoinControl *coinControl=NULL)
References OP_RETURN, LogPrintf, CTransaction::vout, CWalletTx::mapValue.
string CWallet::SendStealthMoney(CScript scriptPubKey, CAmount nValue, std::vector< uint8_t > &P, std::vector< uint8_t > &narr, std::string &sNarr, CWalletTx &wtxNew, bool fAskFee=false)
References _, LogPrintf, strprintf, FormatMoney, uiInterface, CClientUIInterface::ThreadSafeAskFee.
bool CWallet::SendStealthMoneyToDestination(CStealthAddress &sxAddress, CAmount nValue, std::string &sNarr, CWalletTx &wtxNew, std::string &sError, bool fAskFee=false)
References nTransactionFee, GenerateRandomSecret, StealthSecret, CStealthAddress::scan_pubkey, CStealthAddress::spend_pubkey, CPubKey::IsValid, CPubKey::GetID, SecretToPublicKey, fDebug, LogPrintf, PRIszu, HexStr, CBase58Data::ToString, SecMsgCrypter::SetKey, ec_secret::e, SecMsgCrypter::Encrypt, CScript::SetDestination, CDarkSilkAddress::Get.
Referenced by sendtostealthaddress.
bool CWallet::FindStealthTransactions(const CTransaction &tx, mapValue_t &mapNarr)
References fDebug, LogPrintf, CTransaction::GetHash, base_uint< BITS >::GetHex, LOCK, CTransaction::vout, CTxOut::scriptPubKey, CScript::GetOp, OP_RETURN, ExtractDestination, ec_secret_size, ec_secret::e, StealthSecret, CPubKey::IsValid, CPubKey::GetID, CBase58Data::ToString, StealthSharedToSecretSpend, SecretToPublicKey, CKey::Set, CKey::GetPubKey, CKey::IsValid, SecMsgCrypter::SetKey, SecMsgCrypter::Decrypt.
string CWallet::PrepareSandstormDenominate(int minRounds, int maxRounds)
References _, sandStormPool, CSandstormPool::GetState, POOL_STATUS_ERROR, POOL_STATUS_SUCCESS, CSandstormPool::GetEntriesCount, CSandstormPool::sessionDenom, LogPrintf, LOCK, CTxIn::prevout, GetRandInt, sandStormDenominations, CReserveKey::GetReservedKey, GetScriptForDestination, CPubKey::GetID, CReserveKey::KeepKey, CSandstormPool::GetDenominations, CSandstormPool::SendSandstormDenominate.
Referenced by CSandstormPool::PrepareSandstormDenominate.
int CWallet::GenerateSandstormOutputs(int nTotalValue, std::vector< CTxOut > &vout)
bool CWallet::CreateCollateralTransaction(CMutableTransaction &txCollateral, std::string strReason)
References CMutableTransaction::vin, CMutableTransaction::vout, CReserveKey::GetReservedKey, GetScriptForDestination, CPubKey::GetID, CReserveKey::KeepKey.
Referenced by CSandstormPool::DoAutomaticDenominating.
bool CWallet::GetBudgetSystemCollateralTX(CTransaction &tx, uint256 hash, bool useIX)
Referenced by snbudget, CBudgetManager::SubmitFinalBudget.
bool CWallet::GetBudgetSystemCollateralTX(CWalletTx &tx, uint256 hash, bool useIX)
References pwalletMain, OP_RETURN, ToByteVector, ALL_COINS, LogPrintf.
bool CWallet::ConvertList(std::vector< CTxIn > vCoins, std::vector< CAmount > &vecAmounts)
References CTxIn::prevout, COutPoint::hash, COutPoint::n, CTransaction::vout, LogPrintf.
Referenced by CSandstormPool::DoAutomaticDenominating.
bool CWallet::NewKeyPool()
References LOCK, CWalletDB::ErasePool, GetArg, CWalletDB::WritePool, LogPrintf.
bool CWallet::TopUpKeyPool(unsigned int nSize=0)
References LOCK, GetArg, CWalletDB::WritePool, LogPrintf, strprintf, _, uiInterface, CClientUIInterface::InitMessage.
Referenced by getnewpubkey, getnewaddress, keypoolrefill, walletpassphrase.
int64_t CWallet::AddReserveKey(const CKeyPool &keypool)
References LOCK2, cs_main, CWalletDB::WritePool.
void CWallet::ReserveKeyFromKeyPool(int64_t &nIndex, CKeyPool &keypool)
References CKeyPool::vchPubKey, LOCK, CWalletDB::ReadPool, CPubKey::GetID, CPubKey::IsValid, LogPrintf.
void CWallet::KeepKey(int64_t nIndex)
References CWalletDB::ErasePool, LogPrintf.
void CWallet::ReturnKey(int64_t nIndex)
References LOCK, LogPrintf.
bool CWallet::GetKeyFromPool(CPubKey &key)
References LOCK, CKeyPool::vchPubKey.
Referenced by AppInit2, AddressTableModel::addRow, getnewpubkey, getnewaddress, GetAccountAddress.
int64_t CWallet::GetOldestKeyPoolTime()
References GetTime, CKeyPool::nTime.
Referenced by getinfo.
void CWallet::GetAllReserveKeys(std::set< CKeyID > &setAddress) const
References LOCK2, cs_main, CWalletDB::ReadPool, CKeyPool::vchPubKey, CPubKey::IsValid, CPubKey::GetID.
Referenced by dumpwallet.
set< set< CTxDestination > > CWallet::GetAddressGroupings()
References AssertLockHeld, PAIRTYPE, CTransaction::vin, IsMine, ExtractDestination, CTxIn::prevout, COutPoint::hash, COutPoint::n, CTransaction::vout, CTxOut::scriptPubKey.
Referenced by listaddressgroupings.
std::map< CTxDestination, CAmount > CWallet::GetAddressBalances()
References LOCK, PAIRTYPE, IsFinalTx, CWalletTx::IsTrusted, CTransaction::IsCoinBase, CTransaction::IsCoinStake, CMerkleTx::GetBlocksToMaturity, CMerkleTx::GetDepthInMainChain, CWalletTx::IsFromMe, ISMINE_ALL, CTransaction::vout, IsMine, ExtractDestination, CWalletTx::IsSpent.
Referenced by listaddressgroupings.
bool CWallet::IsDenominated(const CTxIn &txin) const
References LOCK, CTxIn::prevout, COutPoint::hash, prev, COutPoint::n, CTransaction::vout.
Referenced by CWalletTx::IsDenominated.
bool CWallet::IsDenominated(const CTransaction &tx) const
References CTransaction::vin.
bool CWallet::IsDenominatedAmount(CAmount nInputAmount) const
References sandStormDenominations.
Referenced by CWalletTx::GetDenominatedCredit.
isminetype CWallet::IsMine(const CTxIn &txin) const
References LOCK, CTxIn::prevout, COutPoint::hash, prev, COutPoint::n, CTransaction::vout, IsMine, ISMINE_NO.
Referenced by TransactionDesc::toHTML, TransactionRecord::decomposeTransaction, WalletModel::listCoins, IsMine, GetCredit, CWalletTx::IsTrusted.
CAmount CWallet::GetDebit(const CTxIn &txin, const isminefilter &filter) const
References LOCK, CTxIn::prevout, COutPoint::hash, prev, COutPoint::n, CTransaction::vout, IsMine.
Referenced by TransactionDesc::toHTML, IsFromMe, GetDebit, CWalletTx::GetDebit.
isminetype CWallet::IsMine(const CTxOut &txout) const
References IsMine, CTxOut::scriptPubKey.
bool CWallet::IsChange(const CTxOut &txout) const
References IsMine, CTxOut::scriptPubKey, ExtractDestination, LOCK.
Referenced by WalletModel::listCoins, GetChange.
CAmount CWallet::GetChange(const CTxOut &txout) const
References MoneyRange, CTxOut::nValue, IsChange.
Referenced by GetChange, CWalletTx::GetChange.
bool CWallet::IsMine(const CTransaction &tx) const
References CTransaction::vout, IsMine, CTxOut::nValue, nMinimumInputValue.
bool CWallet::IsFromMe(const CTransaction &tx) const
should probably be renamed to IsRelevantToMe
References GetDebit, ISMINE_ALL.
CAmount CWallet::GetDebit(const CTransaction &tx, const isminefilter &filter) const
References CTransaction::vin, GetDebit, MoneyRange.
CAmount CWallet::GetCredit(const CTxOut &txout, const isminefilter &filter) const
References MoneyRange, CTxOut::nValue, IsMine.
Referenced by TransactionDesc::toHTML, GetWatchOnlyStake, GetStake, GetNewMint, GetCredit, CWalletTx::GetCredit, CWalletTx::GetImmatureCredit, CWalletTx::GetAvailableCredit, CWalletTx::GetAnonymizableCredit, CWalletTx::GetDenominatedCredit, CWalletTx::GetImmatureWatchOnlyCredit, CWalletTx::GetAvailableWatchOnlyCredit.
CAmount CWallet::GetCredit(const CTransaction &tx, const isminefilter &filter) const
References CTransaction::vout, GetCredit, MoneyRange.
CAmount CWallet::GetChange(const CTransaction &tx) const
References CTransaction::vout, GetChange, MoneyRange.
void CWallet::SetBestChain(const CBlockLocator &loc)
References CWalletDB::WriteBestBlock.
Referenced by Shutdown, AppInit2.
DBErrors CWallet::LoadWallet(bool &fFirstRunRet)
References DB_LOAD_OK, CWalletDB::LoadWallet, DB_NEED_REWRITE, CDB::Rewrite, LOCK.
Referenced by AppInit2.
bool CWallet::SetAddressBookName(const CTxDestination &address, const std::string &strName)
References LOCK, IsMine, ISMINE_NO, CT_UPDATED, CT_NEW, CWalletDB::WriteName.
Referenced by AppInit2, AddressTableModel::setData, AddressTableModel::addRow, MessageModel::sendMessages, WalletModel::sendCoins, importprivkey, importaddress, importwallet, getnewpubkey, getnewaddress, GetAccountAddress, setaccount, addmultisigaddress, addredeemscript.
bool CWallet::DelAddressBookName(const CTxDestination &address)
References LOCK, IsMine, ISMINE_NO, CT_DELETED, CWalletDB::EraseName.
Referenced by AddressTableModel::setData, AddressTableModel::removeRows.
bool CWallet::UpdatedTransaction(const uint256 &hashTx)
References LOCK, CT_UPDATED.
Referenced by ProcessConsensusVote.
void CWallet::Inventory(const uint256 &hash)
References LOCK.
unsigned int CWallet::GetKeyPoolSize()
References AssertLockHeld.
Referenced by getinfo, keypoolrefill.
bool CWallet::SetDefaultKey(const CPubKey &vchPubKey)
Referenced by AppInit2.
bool CWallet::SetMinVersion(enum WalletFeature, CWalletDB *pwalletdbIn=NULL, bool fExplicit=false)
References LOCK, FEATURE_LATEST, CWalletDB::WriteMinVersion.
Referenced by AppInit2.
bool CWallet::SetMaxVersion(int nVersion)
References LOCK.
Referenced by AppInit2.
int CWallet::GetVersion()
References LOCK.
Referenced by getinfo.
set< uint256 > CWallet::GetConflicts(const uint256 &txid) const
References AssertLockHeld, CTransaction::vin, CTxIn::prevout.
void CWallet::FixSpentCoins(int &nMismatchSpent, CAmount &nBalanceInQuestion, bool fCheckOnly=false)
References LOCK, txdb, CTxDB::ReadTxIndex, CTransaction::GetHash, CTransaction::vout, IsMine, CWalletTx::IsSpent, CTxIndex::vSpent, LogPrintf, FormatMoney, base_uint< BITS >::ToString, CWalletTx::MarkUnspent, CWalletTx::WriteToDisk, CWalletTx::MarkSpent.
Referenced by CheckStake, checkwallet, repairwallet.
void CWallet::DisableTransaction(const CTransaction &tx)
References CTransaction::IsCoinStake, LOCK, CTransaction::vin, CTxIn::prevout, COutPoint::hash, prev, COutPoint::n, CTransaction::vout, IsMine, CWalletTx::MarkUnspent, CWalletTx::WriteToDisk.