CCoinsViewCache
bool CCoinsViewCache::hasModifier
Referenced by ~CCoinsViewCache, ModifyCoins, BatchWrite, CCoinsModifier::~CCoinsModifier.
uint256 CCoinsViewCache::hashBlock
CCoinsView Make mutable so that we can "fill the cache" even from Get-methods declared as "const".
Referenced by GetBestBlock, SetBestBlock, BatchWrite, Flush.
CCoinsMap CCoinsViewCache::cacheCoins
Referenced by GetCoins, ModifyCoins, AccessCoins, HaveCoins, BatchWrite, Flush, GetCacheSize, CCoinsModifier::~CCoinsModifier.
friend class CCoinsModifier
Referenced by ModifyCoins.
CCoinsViewCache::CCoinsViewCache(CCoinsView *baseIn)
CCoinsViewCache::~CCoinsViewCache()
References hasModifier.
bool CCoinsViewCache::GetCoins(const uint256 &txid, CCoins &coins) const
Retrieve the CCoins (unspent transaction outputs) for a given txid.
References cacheCoins.
bool CCoinsViewCache::HaveCoins(const uint256 &txid) const
Just check whether we have data for a given txid. This may (but cannot always) return true for fully spent transactions
References cacheCoins.
uint256 CCoinsViewCache::GetBestBlock() const
Retrieve the block hash whose state this CCoinsView currently represents.
References hashBlock, CCoinsViewBacked::base, CCoinsView::GetBestBlock.
void CCoinsViewCache::SetBestBlock(const uint256 &hashBlock)
References hashBlock.
bool CCoinsViewCache::BatchWrite(CCoinsMap &mapCoins, const uint256 &hashBlock)
Do a bulk modification (multiple CCoins changes + BestBlock change). The passed mapCoins can be modified.
References hasModifier, CCoinsCacheEntry::DIRTY, cacheCoins, CCoinsCacheEntry::FRESH, CCoinsCacheEntry::coins, CCoins::swap, CCoinsCacheEntry::flags, hashBlock.
const CCoins * CCoinsViewCache::AccessCoins(const uint256 &txid) const
Return a pointer to CCoins in the cache, or NULL if not found. This is more efficient than GetCoins. Modifications to other cache entries are allowed while accessing the returned pointer.
References cacheCoins.
Referenced by GetOutputFor, HaveInputs, GetPriority.
CCoinsModifier CCoinsViewCache::ModifyCoins(const uint256 &txid)
Return a modifiable reference to a CCoins. If no entry with the given txid exists, a new one is created. Simultaneous modifications are not allowed.
References hasModifier, cacheCoins, CCoinsViewBacked::base, CCoinsView::GetCoins, CCoinsCacheEntry::FRESH, CCoinsCacheEntry::DIRTY, CCoinsModifier.
bool CCoinsViewCache::Flush()
Push the modifications applied to this cache to its base. Failure to call this method before destruction will cause the changes to be forgotten. If false is returned, the state of this cache (and its backing view) will be undefined.
References CCoinsViewBacked::base, CCoinsView::BatchWrite, cacheCoins, hashBlock.
unsigned int CCoinsViewCache::GetCacheSize() const
Calculate the size of the cache (in number of transactions)
References cacheCoins.
CAmount CCoinsViewCache::GetValueIn(const CTransaction &tx) const
Amount of dash coming in to a transaction Note that lightweight clients may not know anything besides the hash of previous transactions, so may not be able to calculate this. tx transaction for which we are checking input total Sum of value of all inputs (scriptSigs)
References CTransaction::IsCoinBase, CTransaction::vin, GetOutputFor, CTxOut::nValue.
bool CCoinsViewCache::HaveInputs(const CTransaction &tx) const
Check whether all prevouts of the transaction are present in the UTXO set represented by this view.
References CTransaction::IsCoinBase, CTransaction::vin, AccessCoins, COutPoint::hash, CCoins::IsAvailable, COutPoint::n.
double CCoinsViewCache::GetPriority(const CTransaction &tx, int nHeight) const
Return priority of tx at height nHeight.
References CTransaction::IsCoinBase, CTransaction::vin, AccessCoins, CTxIn::prevout, COutPoint::hash, CCoins::IsAvailable, COutPoint::n, CCoins::nHeight, CCoins::vout, CTransaction::ComputePriority.
const CTxOut & CCoinsViewCache::GetOutputFor(const CTxIn &input) const
References AccessCoins, CTxIn::prevout, COutPoint::hash, CCoins::IsAvailable, COutPoint::n, CCoins::vout.
Referenced by GetValueIn.
CCoinsMap::iterator CCoinsViewCache::FetchCoins(const uint256 &txid)
CCoinsMap::const_iterator CCoinsViewCache::FetchCoins(const uint256 &txid) const