CCryptoKeyStore
bool CCryptoKeyStore::fUseCrypto
CryptedKeyMap CCryptoKeyStore::mapCryptedKeys
Referenced by Unlock, AddCryptedKey, GetKey, GetPubKey, EncryptKeys.
CKeyingMaterial CCryptoKeyStore::vMasterKey
Referenced by LockKeyStore, Unlock, AddKeyPubKey, GetKey.
boost::signals2::signal<void (CCryptoKeyStore* wallet)> CCryptoKeyStore::NotifyStatusChanged
Referenced by LockKeyStore, Unlock.
bool CCryptoKeyStore::SetCrypted()
References LOCK, CKeyStore::cs_KeyStore, CBasicKeyStore::mapKeys.
Referenced by LockKeyStore, Unlock, AddCryptedKey.
bool CCryptoKeyStore::EncryptKeys(CKeyingMaterial &vMasterKeyIn)
References LOCK, CKeyStore::cs_KeyStore, mapCryptedKeys, IsCrypted, CBasicKeyStore::mapKeys, CKey::GetPubKey, CKey::begin, CKey::end, EncryptSecret, CPubKey::GetHash, AddCryptedKey.
bool CCryptoKeyStore::Unlock(const CKeyingMaterial &vMasterKeyIn)
References LOCK, CKeyStore::cs_KeyStore, SetCrypted, mapCryptedKeys, DecryptSecret, CPubKey::GetHash, CKey::Set, CPubKey::IsCompressed, CKey::GetPubKey, vMasterKey, NotifyStatusChanged.
Referenced by CWallet::Unlock, CWallet::ChangeWalletPassphrase.
CCryptoKeyStore::CCryptoKeyStore()
bool CCryptoKeyStore::IsCrypted() const
Referenced by AddKeyPubKey, GetKey, GetPubKey, EncryptKeys, IsLocked, HaveKey, GetKeys, WalletModel::getEncryptionStatus, getinfo, HelpRequiringPassphrase, walletpassphrase, walletpassphrasechange, walletlock, encryptwallet.
bool CCryptoKeyStore::IsLocked() const
References IsCrypted, LOCK, CKeyStore::cs_KeyStore.
Referenced by CActiveStormnode::ManageStatus, AddKeyPubKey, ThreadStakeMiner, WalletModel::getEncryptionStatus, smsgscanbuckets, smsginbox, smsgoutbox, sandstorm, stormnode, EnsureWalletIsUnlocked, getnewpubkey, getnewaddress, SendMoney, sendtoaddress, getnewstealthaddress, liststealthaddresses, sendtostealthaddress, CSandstormPool::DoAutomaticDenominating, SecureMsgScanBuckets, SecureMsgWalletUnlocked, SecureMsgScanMessage, SecureMsgSend.
bool CCryptoKeyStore::LockKeyStore()
References SetCrypted, LOCK, CKeyStore::cs_KeyStore, vMasterKey, NotifyStatusChanged.
bool CCryptoKeyStore::AddCryptedKey(const CPubKey &vchPubKey, const std::vector< unsigned char > &vchCryptedSecret)
References LOCK, CKeyStore::cs_KeyStore, SetCrypted, mapCryptedKeys, CPubKey::GetID.
Referenced by AddKeyPubKey, EncryptKeys, CWallet::AddCryptedKey, CWallet::LoadCryptedKey.
bool CCryptoKeyStore::AddKeyPubKey(const CKey &key, const CPubKey &pubkey)
References LOCK, CKeyStore::cs_KeyStore, IsCrypted, CBasicKeyStore::AddKeyPubKey, IsLocked, CKey::begin, CKey::end, EncryptSecret, vMasterKey, CPubKey::GetHash, AddCryptedKey.
Referenced by CWallet::AddKeyPubKey, CWallet::LoadKey.
bool CCryptoKeyStore::HaveKey(const CKeyID &address) const
References LOCK, CKeyStore::cs_KeyStore, IsCrypted, CBasicKeyStore::HaveKey.
Referenced by importprivkey, importwallet.
bool CCryptoKeyStore::GetKey(const CKeyID &address, CKey &keyOut) const
References LOCK, CKeyStore::cs_KeyStore, IsCrypted, CBasicKeyStore::GetKey, mapCryptedKeys, DecryptSecret, vMasterKey, CPubKey::GetHash, CKey::Set, CPubKey::IsCompressed.
Referenced by dumpprivkey, dumpwallet, signmessage, SecureMsgEncrypt, SecureMsgDecrypt.
bool CCryptoKeyStore::GetPubKey(const CKeyID &address, CPubKey &vchPubKeyOut) const
References LOCK, CKeyStore::cs_KeyStore, IsCrypted, CKeyStore::GetPubKey, mapCryptedKeys.
Referenced by WalletModel::getPubKey, smsglocalkeys, _createmultisig, addmultisigaddress, SecureMsgGetLocalKey.
void CCryptoKeyStore::GetKeys(std::set< CKeyID > &setAddress) const
References IsCrypted, CBasicKeyStore::GetKeys.