leveldb::Benchmark
Order
DBState
Order
DBState
Cache* leveldb::Benchmark::cache_
const FilterPolicy* leveldb::Benchmark::filter_policy_
DB* leveldb::Benchmark::db_
int leveldb::Benchmark::num_
int leveldb::Benchmark::value_size_
int leveldb::Benchmark::entries_per_batch_
WriteOptions leveldb::Benchmark::write_options_
int leveldb::Benchmark::reads_
int leveldb::Benchmark::heap_counter_
sqlite3* leveldb::Benchmark::db_
int leveldb::Benchmark::db_num_
double leveldb::Benchmark::start_
double leveldb::Benchmark::last_op_finish_
int64_t leveldb::Benchmark::bytes_
std::string leveldb::Benchmark::message_
Histogram leveldb::Benchmark::hist_
RandomGenerator leveldb::Benchmark::gen_
Random leveldb::Benchmark::rand_
int leveldb::Benchmark::done_
int leveldb::Benchmark::next_report_
kyotocabinet::TreeDB* leveldb::Benchmark::db_
kyotocabinet::LZOCompressor<kyotocabinet::LZO::RAW> leveldb::Benchmark::comp_
void leveldb::Benchmark::PrintHeader()
void leveldb::Benchmark::PrintWarnings()
void leveldb::Benchmark::PrintEnvironment()
void leveldb::Benchmark::RunBenchmark(int n, Slice name, void(Benchmark::*method)(ThreadState *))
void leveldb::Benchmark::Crc32c(ThreadState *thread)
void leveldb::Benchmark::AcquireLoad(ThreadState *thread)
void leveldb::Benchmark::SnappyCompress(ThreadState *thread)
void leveldb::Benchmark::SnappyUncompress(ThreadState *thread)
void leveldb::Benchmark::Open()
void leveldb::Benchmark::WriteSeq(ThreadState *thread)
void leveldb::Benchmark::WriteRandom(ThreadState *thread)
void leveldb::Benchmark::DoWrite(ThreadState *thread, bool seq)
void leveldb::Benchmark::ReadSequential(ThreadState *thread)
void leveldb::Benchmark::ReadReverse(ThreadState *thread)
void leveldb::Benchmark::ReadRandom(ThreadState *thread)
void leveldb::Benchmark::ReadMissing(ThreadState *thread)
void leveldb::Benchmark::ReadHot(ThreadState *thread)
void leveldb::Benchmark::SeekRandom(ThreadState *thread)
void leveldb::Benchmark::DoDelete(ThreadState *thread, bool seq)
void leveldb::Benchmark::DeleteSeq(ThreadState *thread)
void leveldb::Benchmark::DeleteRandom(ThreadState *thread)
void leveldb::Benchmark::ReadWhileWriting(ThreadState *thread)
void leveldb::Benchmark::Compact(ThreadState *thread)
void leveldb::Benchmark::PrintStats(const char *key)
void leveldb::Benchmark::HeapProfile()
void leveldb::Benchmark::PrintHeader()
void leveldb::Benchmark::PrintWarnings()
void leveldb::Benchmark::PrintEnvironment()
void leveldb::Benchmark::Start()
void leveldb::Benchmark::FinishedSingleOp()
void leveldb::Benchmark::Stop(const Slice &name)
void leveldb::Benchmark::PrintHeader()
void leveldb::Benchmark::PrintWarnings()
void leveldb::Benchmark::PrintEnvironment()
void leveldb::Benchmark::Start()
void leveldb::Benchmark::FinishedSingleOp()
void leveldb::Benchmark::Stop(const Slice &name)
void leveldb::Benchmark::Open(bool sync)
void leveldb::Benchmark::Write(bool sync, Order order, DBState state, int num_entries, int value_size, int entries_per_batch)
void leveldb::Benchmark::ReadSequential()
void leveldb::Benchmark::ReadRandom()
leveldb::Benchmark::Benchmark()
References leveldb::Env::Default, leveldb::Env::GetChildren, leveldb::Slice::starts_with, leveldb::Env::DeleteFile, leveldb::DestroyDB.
leveldb::Benchmark::~Benchmark()
void leveldb::Benchmark::Run()
References name, leveldb::WriteOptions::sync, ReadSequential, leveldb::Slice::ToString, leveldb::DestroyDB.
Referenced by main.
leveldb::Benchmark::Benchmark()
References leveldb::Env::Default, leveldb::Env::GetTestDirectory, leveldb::Env::GetChildren, leveldb::Slice::starts_with, leveldb::Env::DeleteFile.
leveldb::Benchmark::~Benchmark()
void leveldb::Benchmark::Run()
References name, Write, SEQUENTIAL, FRESH, RANDOM, EXISTING, ReadSequential, Read, leveldb::Slice::ToString.
void leveldb::Benchmark::Open()
References leveldb::Env::Default, leveldb::Env::GetTestDirectory.
void leveldb::Benchmark::Write(bool write_sync, Order order, DBState state, int num_entries, int value_size, int entries_per_batch)
References FRESH, value, SEQUENTIAL.
Referenced by Run.
void leveldb::Benchmark::Read(Order order, int entries_per_batch)
References SEQUENTIAL.
Referenced by Run.
void leveldb::Benchmark::ReadSequential()
Referenced by Run.
leveldb::Benchmark::Benchmark()
References leveldb::Env::Default, leveldb::Env::GetTestDirectory, leveldb::Env::GetChildren, leveldb::Slice::starts_with, leveldb::Env::DeleteFile.
leveldb::Benchmark::~Benchmark()
void leveldb::Benchmark::Run()
References name, Write, SEQUENTIAL, FRESH, RANDOM, EXISTING, ReadSequential, leveldb::Slice::ToString.
static void leveldb::Benchmark::ThreadBody(void *v)
static void leveldb::Benchmark::WriteToFile(void *arg, const char *buf, int n)