ClientModel
OptionsModel* ClientModel::optionsModel
PeerTableModel* ClientModel::peerTableModel
int ClientModel::cachedNumBlocks
QString ClientModel::cachedStormnodeCountString
int ClientModel::numBlocksAtStartup
QTimer* ClientModel::pollTimer
QTimer* ClientModel::pollSnTimer
ClientModel::ClientModel(OptionsModel *optionsModel, QObject *parent=0)
References updateTimer, updateSnTimer.
ClientModel::~ClientModel()
OptionsModel * ClientModel::getOptionsModel()
Referenced by DarkSilkGUI::changeEvent, DarkSilkGUI::closeEvent, DarkSilkGUI::askFee.
PeerTableModel * ClientModel::getPeerTableModel()
Referenced by DEBUGConsole::setClientModel, DEBUGConsole::peerSelected, DEBUGConsole::peerLayoutChanged.
int ClientModel::getNumConnections() const
References vNodes.
Referenced by DarkSilkGUI::setClientModel, DarkSilkGUI::setNumBlocks, DEBUGConsole::setClientModel, StatisticsPage::updateStatistics.
QString ClientModel::getStormnodeCountString() const
References snodeman, CStormnodeMan::CountEnabled, CStormnodeMan::size.
Referenced by updateSnTimer, DEBUGConsole::setClientModel.
int ClientModel::getNumBlocks() const
References LOCK, cs_main, nBestHeight.
Referenced by getNumBlocksAtStartup, updateTimer, DarkSilkGUI::setClientModel, DEBUGConsole::setClientModel.
int ClientModel::getNumBlocksAtStartup()
References getNumBlocks.
quint64 ClientModel::getTotalBytesRecv() const
References CNode::GetTotalBytesRecv.
Referenced by updateTimer, DEBUGConsole::setClientModel, TrafficGraphWidget::setClientModel, TrafficGraphWidget::updateRates, TrafficGraphWidget::clear.
quint64 ClientModel::getTotalBytesSent() const
References CNode::GetTotalBytesSent.
Referenced by updateTimer, DEBUGConsole::setClientModel, TrafficGraphWidget::setClientModel, TrafficGraphWidget::updateRates, TrafficGraphWidget::clear.
QDateTime ClientModel::getLastBlockDate() const
References LOCK, cs_main, pindexBest, CBlockIndex::GetBlockTime, Params.
Referenced by DarkSilkGUI::setNumBlocks, DEBUGConsole::setNumBlocks, StatisticsPage::updateStatistics.
bool ClientModel::isTestNet() const
Return true if client connected to testnet.
References TestNet.
Referenced by DarkSilkGUI::setClientModel, DEBUGConsole::setClientModel.
bool ClientModel::inInitialBlockDownload() const
Return true if core is doing initial block download.
References IsInitialBlockDownload.
bool ClientModel::isImporting() const
Return true if core is importing blocks.
References fImporting.
Referenced by DarkSilkGUI::setNumBlocks.
QString ClientModel::getStatusBarWarnings() const
Return warnings to be displayed in status bar.
References GetWarnings.
Referenced by updateAlert, OverviewPage::setClientModel.
QString ClientModel::formatFullVersion() const
References FormatFullVersion.
Referenced by AboutDialog::setModel, DEBUGConsole::setClientModel.
QString ClientModel::formatBuildDate() const
References CLIENT_DATE.
Referenced by DEBUGConsole::setClientModel.
bool ClientModel::isReleaseVersion() const
References CLIENT_VERSION_IS_RELEASE.
QString ClientModel::clientName() const
References CLIENT_NAME.
Referenced by DEBUGConsole::setClientModel.
QString ClientModel::formatClientStartupTime() const
Referenced by DEBUGConsole::setClientModel.
void ClientModel::subscribeToCoreSignals()
void ClientModel::unsubscribeFromCoreSignals()
void ClientModel::numConnectionsChanged(int count)
Referenced by updateNumConnections.
void ClientModel::numBlocksChanged(int count)
Referenced by updateTimer.
void ClientModel::strStormnodesChanged(const QString &strStormnodes)
Referenced by updateSnTimer.
void ClientModel::alertsChanged(const QString &warnings)
Referenced by updateAlert.
void ClientModel::bytesChanged(quint64 totalBytesIn, quint64 totalBytesOut)
Referenced by updateTimer.
void ClientModel::message(const QString &title, const QString &message, bool modal, unsigned int style)
Asynchronous message notification.
Referenced by updateAlert.
void ClientModel::showProgress(const QString &title, int nProgress)
void ClientModel::updateTimer()
References TRY_LOCK, cs_main, getNumBlocks, numBlocksChanged, bytesChanged, getTotalBytesRecv, getTotalBytesSent.
Referenced by ClientModel.
void ClientModel::updateSnTimer()
References TRY_LOCK, cs_main, getStormnodeCountString, strStormnodesChanged.
Referenced by ClientModel.
void ClientModel::updateNumConnections(int numConnections)
References numConnectionsChanged.
void ClientModel::updateAlert(const QString &hash, int status)
References CT_NEW, base_uint< BITS >::SetHex, CAlert::getAlertByHash, CAlert::IsNull, message, CUnsignedAlert::strStatusBar, CClientUIInterface::ICON_ERROR, alertsChanged, getStatusBarWarnings.