leveldb::TableBuilder
Rep* leveldb::TableBuilder::rep_
leveldb::TableBuilder::TableBuilder(const Options &options, WritableFile *file)
References leveldb::TableBuilder::Rep::filter_block, leveldb::FilterBlockBuilder::StartBlock.
leveldb::TableBuilder::~TableBuilder()
References leveldb::TableBuilder::Rep::closed, leveldb::TableBuilder::Rep::filter_block.
Status leveldb::TableBuilder::ChangeOptions(const Options &options)
References leveldb::Options::comparator, leveldb::TableBuilder::Rep::options, leveldb::Status::InvalidArgument, leveldb::TableBuilder::Rep::index_block_options, leveldb::Options::block_restart_interval, leveldb::Status::OK.
void leveldb::TableBuilder::Add(const Slice &key, const Slice &value)
References leveldb::TableBuilder::Rep::closed, leveldb::TableBuilder::Rep::num_entries, leveldb::TableBuilder::Rep::options, leveldb::Options::comparator, leveldb::Comparator::Compare, leveldb::TableBuilder::Rep::last_key, leveldb::TableBuilder::Rep::pending_index_entry, leveldb::TableBuilder::Rep::data_block, leveldb::BlockBuilder::empty, leveldb::Comparator::FindShortestSeparator, leveldb::TableBuilder::Rep::pending_handle, leveldb::BlockHandle::EncodeTo, leveldb::TableBuilder::Rep::index_block, leveldb::BlockBuilder::Add, leveldb::TableBuilder::Rep::filter_block, leveldb::FilterBlockBuilder::AddKey, leveldb::Slice::data, leveldb::Slice::size, leveldb::BlockBuilder::CurrentSizeEstimate, leveldb::Options::block_size, Flush.
Referenced by leveldb::BuildTable, leveldb::TableConstructor::FinishImpl.
void leveldb::TableBuilder::Flush()
References leveldb::TableBuilder::Rep::closed, leveldb::TableBuilder::Rep::data_block, leveldb::BlockBuilder::empty, leveldb::TableBuilder::Rep::pending_index_entry, leveldb::TableBuilder::Rep::pending_handle, leveldb::TableBuilder::Rep::status, leveldb::TableBuilder::Rep::file, leveldb::WritableFile::Flush, leveldb::TableBuilder::Rep::filter_block, leveldb::FilterBlockBuilder::StartBlock, leveldb::TableBuilder::Rep::offset.
Referenced by Add, Finish.
Status leveldb::TableBuilder::status() const
References leveldb::TableBuilder::Rep::status.
Referenced by leveldb::TableConstructor::FinishImpl.
Status leveldb::TableBuilder::Finish()
References Flush, leveldb::TableBuilder::Rep::closed, leveldb::TableBuilder::Rep::filter_block, leveldb::FilterBlockBuilder::Finish, leveldb::kNoCompression, leveldb::TableBuilder::Rep::options, leveldb::Options::filter_policy, leveldb::FilterPolicy::Name, leveldb::BlockHandle::EncodeTo, leveldb::BlockBuilder::Add, leveldb::TableBuilder::Rep::pending_index_entry, leveldb::Options::comparator, leveldb::Comparator::FindShortSuccessor, leveldb::TableBuilder::Rep::last_key, leveldb::TableBuilder::Rep::pending_handle, leveldb::TableBuilder::Rep::index_block, leveldb::Footer::set_metaindex_handle, leveldb::Footer::set_index_handle, leveldb::Footer::EncodeTo, leveldb::TableBuilder::Rep::status, leveldb::TableBuilder::Rep::file, leveldb::WritableFile::Append, leveldb::Status::ok, leveldb::TableBuilder::Rep::offset.
Referenced by leveldb::BuildTable, leveldb::TableConstructor::FinishImpl.
void leveldb::TableBuilder::Abandon()
References leveldb::TableBuilder::Rep::closed.
Referenced by leveldb::BuildTable.
uint64_t leveldb::TableBuilder::NumEntries() const
References leveldb::TableBuilder::Rep::num_entries.
uint64_t leveldb::TableBuilder::FileSize() const
References leveldb::TableBuilder::Rep::offset.
Referenced by leveldb::BuildTable, leveldb::TableConstructor::FinishImpl.
bool leveldb::TableBuilder::ok() const
void leveldb::TableBuilder::WriteBlock(BlockBuilder *block, BlockHandle *handle)
void leveldb::TableBuilder::WriteRawBlock(const Slice &data, CompressionType, BlockHandle *handle)
leveldb::TableBuilder::TableBuilder(const TableBuilder &)
void leveldb::TableBuilder::operator=(const TableBuilder &)