leveldb::Footer
@8
BlockHandle leveldb::Footer::metaindex_handle_
BlockHandle leveldb::Footer::index_handle_
leveldb::Footer::Footer()
const BlockHandle& leveldb::Footer::metaindex_handle() const
Referenced by leveldb::Table::Open.
void leveldb::Footer::set_metaindex_handle(const BlockHandle &h)
Referenced by leveldb::TableBuilder::Finish.
const BlockHandle& leveldb::Footer::index_handle() const
Referenced by leveldb::Table::Open.
void leveldb::Footer::set_index_handle(const BlockHandle &h)
Referenced by leveldb::TableBuilder::Finish.
void leveldb::Footer::EncodeTo(std::string *dst) const
References leveldb::BlockHandle::EncodeTo, leveldb::BlockHandle::kMaxEncodedLength, leveldb::PutFixed32, kEncodedLength.
Referenced by leveldb::TableBuilder::Finish.
Status leveldb::Footer::DecodeFrom(Slice *input)
References leveldb::Slice::data, kEncodedLength, leveldb::DecodeFixed32, leveldb::Status::Corruption, leveldb::BlockHandle::DecodeFrom, leveldb::Status::ok, leveldb::Slice::size.
Referenced by leveldb::Table::Open.