CStormnode
state
CCriticalSection CStormnode::cs
int64_t CStormnode::lastTimeChecked
CTxIn CStormnode::vin
Referenced by CActiveStormnode::ManageStatus, snbudget, snfinalbudget, stormnode, stormnodelist, CSandstormPool::DoAutomaticDenominating, CStormnode, CalculateScore, SecondsSincePayment, GetLastPaid, CStormnodeBroadcast::CStormnodeBroadcast, CStormnodeBroadcast::CheckAndUpdate, CStormnodeBroadcast::CheckInputsAndAdd, swap, CStormnodeMan::Add, CStormnodeMan::Find, CStormnodeMan::GetNextStormnodeInQueueForPayment, CStormnodeMan::FindRandomNotInVec, CStormnodeMan::GetStormnodeRank, CStormnodeMan::GetStormnodeByRank, CStormnodeMan::ProcessMessage.
CService CStormnode::addr
Referenced by CActiveStormnode::ManageStatus, ProcessConsensusVote, StormnodeManager::on_UpdateButton_clicked, getpoolinfo, stormnode, stormnodelist, CSandStormRelay::RelayThroughNode, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::DoAutomaticDenominating, CSandstormQueue::GetAddress, CStormnode, UpdateFromNewBroadcast, CStormnodeBroadcast::CStormnodeBroadcast, CStormnodeBroadcast::CheckAndUpdate, CStormnodeBroadcast::CheckInputsAndAdd, CStormnodeBroadcast::Sign, swap, CStormnodeMan::Add, CStormnodeMan::ProcessStormnodeConnections, CStormnodeMan::ProcessMessage.
CPubKey CStormnode::pubkey
Referenced by stormnode, stormnodelist, CStormnodePayments::FillBlockPayee, CStormnodePayments::IsScheduled, CStormnodePayments::ProcessBlock, CStormnode, SecondsSincePayment, GetLastPaid, CStormnodeBroadcast::CStormnodeBroadcast, CStormnodeBroadcast::CheckAndUpdate, CStormnodeBroadcast::Sign, swap, CStormnodeMan::Find, CWallet::CreateCoinStake.
CPubKey CStormnode::pubkey2
Referenced by CSandstormQueue::CheckSignature, CBudgetVote::SignatureValid, CStormnodePaymentWinner::SignatureValid, CStormnode, UpdateFromNewBroadcast, CStormnodeBroadcast::CStormnodeBroadcast, CStormnodeBroadcast::CheckAndUpdate, CStormnodeBroadcast::CheckInputsAndAdd, CStormnodeBroadcast::Sign, swap, CStormnodeMan::Find.
std::vector<unsigned char> CStormnode::sig
Referenced by CStormnode, UpdateFromNewBroadcast, CStormnodeBroadcast::CStormnodeBroadcast, CStormnodeBroadcast::CheckAndUpdate, CStormnodeBroadcast::Sign, swap.
int CStormnode::activeState
Referenced by CStormnode, Check, CStormnodeBroadcast::CStormnodeBroadcast, swap.
int64_t CStormnode::sigTime
Referenced by stormnode, stormnodelist, CStormnode, UpdateFromNewBroadcast, Check, SecondsSincePayment, GetLastPaid, CStormnodeBroadcast::CStormnodeBroadcast, CStormnodeBroadcast::CheckAndUpdate, CStormnodeBroadcast::CheckInputsAndAdd, CStormnodeBroadcast::Sign, swap, CStormnodeMan::GetNextStormnodeInQueueForPayment.
int CStormnode::cacheInputAge
Referenced by CStormnode, CStormnodeBroadcast::CStormnodeBroadcast, swap.
int CStormnode::cacheInputAgeBlock
Referenced by CStormnode, CStormnodeBroadcast::CStormnodeBroadcast, swap.
bool CStormnode::unitTest
Referenced by CStormnode, Check, CStormnodeBroadcast::CStormnodeBroadcast, swap.
bool CStormnode::allowFreeTx
Referenced by CSandstormPool::ProcessMessageSandstorm, CStormnode, CStormnodeBroadcast::CStormnodeBroadcast, swap.
int CStormnode::protocolVersion
Referenced by CActiveStormnode::ManageStatus, stormnode, stormnodelist, CSandstormQueue::GetProtocolVersion, CStormnodePaymentWinner::IsValid, CStormnode, UpdateFromNewBroadcast, CStormnodeBroadcast::CStormnodeBroadcast, CStormnodeBroadcast::CheckAndUpdate, CStormnodeBroadcast::CheckInputsAndAdd, CStormnodeBroadcast::Sign, swap, CStormnodeMan::CountEnabled, CStormnodeMan::GetNextStormnodeInQueueForPayment, CStormnodeMan::FindRandomNotInVec, CStormnodeMan::GetCurrentStormNode, CStormnodeMan::GetStormnodeRank, CStormnodeMan::GetStormnodeRanks, CStormnodeMan::GetStormnodeByRank.
int64_t CStormnode::nLastSsq
Referenced by CSandstormPool::ProcessMessageSandstorm, CSandstormPool::DoAutomaticDenominating, CStormnode, CStormnodeBroadcast::CStormnodeBroadcast, swap.
int CStormnode::nScanningErrorCount
Referenced by CStormnode, CStormnodeBroadcast::CStormnodeBroadcast, swap.
int CStormnode::nLastScanningErrorBlockHeight
Referenced by CStormnode, CStormnodeBroadcast::CStormnodeBroadcast, swap.
CStormnodePing CStormnode::lastPing
Referenced by stormnode, stormnodelist, CStormnode, UpdateFromNewBroadcast, Check, CStormnodeBroadcast::CStormnodeBroadcast, swap.
CStormnode::ADD_SERIALIZE_METHODS
CStormnode::CStormnode()
References LOCK, vin, addr, pubkey, pubkey2, sig, activeState, STORMNODE_ENABLED, sigTime, GetAdjustedTime, lastPing, cacheInputAge, cacheInputAgeBlock, unitTest, allowFreeTx, protocolVersion, nLastSsq, nScanningErrorCount, nLastScanningErrorBlockHeight.
CStormnode::CStormnode(const CStormnode &other)
References LOCK, vin, addr, pubkey, pubkey2, sig, activeState, sigTime, lastPing, cacheInputAge, cacheInputAgeBlock, unitTest, allowFreeTx, protocolVersion, nLastSsq, nScanningErrorCount, nLastScanningErrorBlockHeight.
CStormnode::CStormnode(const CStormnodeBroadcast &snb)
References LOCK, vin, addr, pubkey, pubkey2, sig, activeState, STORMNODE_ENABLED, sigTime, lastPing, cacheInputAge, cacheInputAgeBlock, unitTest, allowFreeTx, protocolVersion, nLastSsq, nScanningErrorCount, nLastScanningErrorBlockHeight.
void CStormnode::swap(CStormnode &first, CStormnode &second)
References vin, addr, pubkey, pubkey2, sig, activeState, sigTime, lastPing, cacheInputAge, cacheInputAgeBlock, unitTest, allowFreeTx, protocolVersion, nLastSsq, nScanningErrorCount, nLastScanningErrorBlockHeight.
CStormnode& CStormnode::operator=(CStormnode from)
uint256 CStormnode::CalculateScore(int mod=1, int64_t nBlockHeight=0)
References pindexBest, hash, vin, CTxIn::prevout, COutPoint::hash, COutPoint::n, GetBlockHash, LogPrintf, SER_GETHASH, CHashWriter::GetHash.
Referenced by stormnode, CStormnodeMan::GetNextStormnodeInQueueForPayment, CStormnodeMan::GetCurrentStormNode, CStormnodeMan::GetStormnodeRank, CStormnodeMan::GetStormnodeRanks, CStormnodeMan::GetStormnodeByRank.
void CStormnode::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References LOCK, READWRITE.
int64_t CStormnode::SecondsSincePayment()
References GetScriptForDestination, pubkey, CPubKey::GetID, GetAdjustedTime, GetLastPaid, SER_GETHASH, vin, sigTime, hash, CHashWriter::GetHash, uint256::GetCompact.
Referenced by CStormnodeMan::GetNextStormnodeInQueueForPayment.
bool CStormnode::UpdateFromNewBroadcast(CStormnodeBroadcast &snb)
References sigTime, pubkey2, sig, protocolVersion, addr, lastPing, CStormnodePing::CheckAndUpdate, snodeman, CStormnodeMan::mapSeenStormnodePing, CStormnodePing::GetHash.
Referenced by CStormnodeBroadcast::CheckAndUpdate.
uint64_t CStormnode::SliceHash(uint256 &hash, int slice)
void CStormnode::Check(bool forceCheck=false)
References ShutdownRequested, GetTime, activeState, STORMNODE_VIN_SPENT, lastPing, CStormnodePing::sigTime, sigTime, STORMNODE_PRE_ENABLED, IsPingedWithin, STORMNODE_REMOVE, STORMNODE_EXPIRED, unitTest, STORMNODE_ENABLED.
Referenced by CActiveStormnode::ManageStatus, CStormnodeBroadcast::CheckAndUpdate, CStormnodeMan::Check, CStormnodeMan::CountEnabled, CStormnodeMan::GetNextStormnodeInQueueForPayment, CStormnodeMan::GetCurrentStormNode, CStormnodeMan::GetStormnodeRank, CStormnodeMan::GetStormnodeRanks, CStormnodeMan::GetStormnodeByRank.
bool CStormnode::IsBroadcastedWithin(int seconds)
References GetAdjustedTime.
Referenced by CStormnodeBroadcast::CheckAndUpdate.
bool CStormnode::IsPingedWithin(int seconds, int64_t now=-1)
References GetAdjustedTime, CStormnodePing::sigTime.
Referenced by Check.
void CStormnode::Disable()
bool CStormnode::IsEnabled()
Referenced by CActiveStormnode::ManageStatus, CStormnodeBroadcast::CheckAndUpdate, CStormnodeBroadcast::CheckInputsAndAdd, CStormnodeMan::Add, CStormnodeMan::CountEnabled, CStormnodeMan::GetNextStormnodeInQueueForPayment, CStormnodeMan::FindRandomNotInVec, CStormnodeMan::GetCurrentStormNode, CStormnodeMan::GetStormnodeRank, CStormnodeMan::GetStormnodeRanks, CStormnodeMan::GetStormnodeByRank, CStormnodeMan::ProcessMessage.
bool CStormnode::IsPreEnabled()
Referenced by CActiveStormnode::ManageStatus, CStormnodeBroadcast::CheckInputsAndAdd, CStormnodeMan::Add.
int CStormnode::GetStormnodeInputAge()
References pindexBest, GetInputAge, CBlockIndex::nHeight.
Referenced by CStormnodeMan::GetNextStormnodeInQueueForPayment.
std::string CStormnode::Status()
References STORMNODE_PRE_ENABLED, STORMNODE_ENABLED, STORMNODE_EXPIRED, STORMNODE_VIN_SPENT, STORMNODE_REMOVE, STORMNODE_POS_ERROR.
Referenced by stormnode, stormnodelist.
int64_t CStormnode::GetLastPaid()
References pindexBest, GetScriptForDestination, pubkey, CPubKey::GetID, SER_GETHASH, vin, sigTime, hash, uint256::GetCompact, snodeman, CStormnodeMan::CountEnabled, CBlockIndex::nHeight, stormnodePayments, CStormnodePayments::mapStormnodeBlocks, CBlockIndex::nTime, CBlockIndex::pprev.
Referenced by stormnodelist, SecondsSincePayment.
bool operator==(const CStormnode &a, const CStormnode &b)
bool operator!=(const CStormnode &a, const CStormnode &b)