TransactionView
DateEnum
WalletModel* TransactionView::model
TransactionFilterProxy* TransactionView::transactionProxyModel
QTableView* TransactionView::transactionView
QComboBox* TransactionView::dateWidget
QComboBox* TransactionView::typeWidget
QLineEdit* TransactionView::addressWidget
QLineEdit* TransactionView::amountWidget
QMenu* TransactionView::contextMenu
QFrame* TransactionView::dateRangeWidget
QDateTimeEdit* TransactionView::dateFrom
QDateTimeEdit* TransactionView::dateTo
TransactionView::TransactionView(QWidget *parent=0)
References All, Today, ThisWeek, ThisMonth, LastMonth, ThisYear, Range, TransactionFilterProxy::ALL_TYPES, TransactionFilterProxy::TYPE, TransactionRecord::RecvWithAddress, TransactionRecord::RecvFromOther, TransactionRecord::SendToAddress, TransactionRecord::SendToOther, TransactionRecord::SendToSelf, TransactionRecord::Generated, TransactionRecord::Other, chooseDate, chooseType, changedPrefix, changedAmount, doubleClicked.
void TransactionView::setModel(WalletModel *model)
References WalletModel::getTransactionTableModel, TransactionTableModel::Date, TransactionTableModel::Status, TransactionTableModel::Type, TransactionTableModel::ToAddress, TransactionTableModel::Amount.
Referenced by DarkSilkGUI::setWalletModel.
QWidget * TransactionView::createDateRangeWidget()
void TransactionView::contextualMenu(const QPoint &)
void TransactionView::dateRangeChanged()
void TransactionView::showDetails()
void TransactionView::copyAddress()
void TransactionView::editLabel()
void TransactionView::copyLabel()
void TransactionView::copyAmount()
void TransactionView::copyTxID()
void TransactionView::doubleClicked(const QModelIndex &)
Referenced by TransactionView.
void TransactionView::chooseDate(int idx)
References All, TransactionFilterProxy::setDateRange, TransactionFilterProxy::MIN_DATE, TransactionFilterProxy::MAX_DATE, Today, ThisWeek, ThisMonth, LastMonth, ThisYear, Range.
Referenced by TransactionView.
void TransactionView::chooseType(int idx)
References TransactionFilterProxy::setTypeFilter.
Referenced by TransactionView.
void TransactionView::changedPrefix(const QString &prefix)
References TransactionFilterProxy::setAddressPrefix.
Referenced by TransactionView.
void TransactionView::changedAmount(const QString &amount)
References DarkSilkUnits::parse, WalletModel::getOptionsModel, OptionsModel::getDisplayUnit, TransactionFilterProxy::setMinAmount.
Referenced by TransactionView.
void TransactionView::exportClicked()
References GUIUtil::getSaveFileName, CSVModelWriter::setModel, CSVModelWriter::addColumn, TransactionTableModel::ConfirmedRole, TransactionTableModel::DateRole, TransactionTableModel::Type, TransactionTableModel::LabelRole, TransactionTableModel::AddressRole, TransactionTableModel::FormattedAmountRole, TransactionTableModel::TxIDRole, CSVModelWriter::write, arg.
void TransactionView::focusTransaction(const QModelIndex &)