CBudgetManager
map<uint256, CTransaction> CBudgetManager::mapCollateral
CCriticalSection CBudgetManager::cs
Referenced by CheckOrphanVotes, SubmitFinalBudget, CBudgetDB::Write, CBudgetDB::Read, AddProposal, FillBlockPayee, FindProposal, IsTransactionValid, GetAllProposals, GetBudget, GetFinalizedBudgets, GetRequiredPaymentsString, NewBlock, ResetSync, MarkSynced, Sync, UpdateProposal, UpdateFinalizedBudget.
map<uint256, CBudgetProposal> CBudgetManager::mapProposals
Referenced by AddProposal, CheckAndRemove, FindProposal, GetAllProposals, GetBudget, NewBlock, PropExists, UpdateProposal, ToString.
map<uint256, CFinalizedBudget> CBudgetManager::mapFinalizedBudgets
Referenced by AddFinalizedBudget, CheckAndRemove, FillBlockPayee, FindFinalizedBudget, IsBudgetPaymentBlock, IsTransactionValid, GetFinalizedBudgets, GetRequiredPaymentsString, NewBlock, UpdateFinalizedBudget, ToString.
std::map<uint256, CBudgetProposalBroadcast> CBudgetManager::mapSeenStormnodeBudgetProposals
Referenced by snbudget, ProcessMessage, ResetSync, MarkSynced, Sync, ToString, CStormnodeSync::AddedBudgetItem.
std::map<uint256, CBudgetVote> CBudgetManager::mapSeenStormnodeBudgetVotes
Referenced by snbudget, snbudgetvoteraw, ProcessMessage, ToString, CStormnodeSync::AddedBudgetItem.
std::map<uint256, CBudgetVote> CBudgetManager::mapOrphanStormnodeBudgetVotes
Referenced by CheckOrphanVotes, UpdateProposal.
std::map<uint256, CFinalizedBudgetBroadcast> CBudgetManager::mapSeenFinalizedBudgets
Referenced by SubmitFinalBudget, ProcessMessage, ResetSync, MarkSynced, Sync, ToString, CStormnodeSync::AddedBudgetItem.
std::map<uint256, CFinalizedBudgetVote> CBudgetManager::mapSeenFinalizedBudgetVotes
Referenced by snfinalbudget, ProcessMessage, CFinalizedBudget::SubmitVote, ToString, CStormnodeSync::AddedBudgetItem.
std::map<uint256, CFinalizedBudgetVote> CBudgetManager::mapOrphanFinalizedBudgetVotes
Referenced by CheckOrphanVotes, UpdateFinalizedBudget.
CBudgetManager::ADD_SERIALIZE_METHODS
CBudgetManager::CBudgetManager()
void CBudgetManager::ClearSeen()
Referenced by AppInit2, NewBlock.
int CBudgetManager::sizeFinalized()
int CBudgetManager::sizeProposals()
void CBudgetManager::ResetSync()
References LOCK, cs, mapSeenStormnodeBudgetProposals, FindProposal, CBudgetProposal::fValid, CBudgetProposal::mapVotes, mapSeenFinalizedBudgets, FindFinalizedBudget, CFinalizedBudget::fValid, CFinalizedBudget::mapVotes.
Referenced by AppInit2, NewBlock.
void CBudgetManager::MarkSynced()
References LOCK, cs, mapSeenStormnodeBudgetProposals, FindProposal, CBudgetProposal::fValid, CBudgetProposal::mapVotes, mapSeenFinalizedBudgets, FindFinalizedBudget, CFinalizedBudget::fValid, CFinalizedBudget::mapVotes.
Referenced by NewBlock.
void CBudgetManager::Sync(CNode *node, uint256 nProp, bool fPartial=false)
References LOCK, cs, mapSeenStormnodeBudgetProposals, FindProposal, CBudgetProposal::fValid, CNode::PushInventory, MSG_BUDGET_PROPOSAL, CBudgetProposal::mapVotes, MSG_BUDGET_VOTE, CNode::PushMessage, LogPrintf, mapSeenFinalizedBudgets, FindFinalizedBudget, CFinalizedBudget::fValid, MSG_BUDGET_FINALIZED, CFinalizedBudget::mapVotes, MSG_BUDGET_FINALIZED_VOTE.
Referenced by NewBlock, ProcessMessage.
void CBudgetManager::ProcessMessage(CNode *pfrom, std::string &strCommand, CDataStream &vRecv)
References fLiteMode, stormnodeSync, CStormnodeSync::IsBlockchainSynced, LOCK, Params, CChainParams::MAIN, CNode::HasFulfilledRequest, LogPrintf, Misbehaving, CNode::GetId, CNode::FulfilledRequest, Sync, CNode::addr, CService::ToString, mapSeenStormnodeBudgetProposals, CStormnodeSync::AddedBudgetItem, IsBudgetCollateralValid, vecImmatureBudgetProposals, AddProposal, CheckOrphanVotes, CBudgetVote::fValid, mapSeenStormnodeBudgetVotes, snodeman, CStormnodeMan::Find, CStormnodeMan::AskForSN, CStormnodeSync::IsSynced, UpdateProposal, mapSeenFinalizedBudgets, vecImmatureFinalizedBudgets, AddFinalizedBudget, CFinalizedBudgetVote::fValid, mapSeenFinalizedBudgetVotes, UpdateFinalizedBudget.
void CBudgetManager::NewBlock()
References TRY_LOCK, cs, stormnodeSync, CStormnodeSync::RequestedStormnodeAssets, strBudgetMode, SubmitFinalBudget, nBestHeight, CStormnodeSync::IsSynced, LogPrintf, rand, ClearSeen, ResetSync, LOCK, cs_vNodes, vNodes, CNode::nVersion, Sync, MarkSynced, CheckAndRemove, askedForSourceProposalOrBudget, GetTime, mapProposals, mapFinalizedBudgets, vecImmatureBudgetProposals, IsBudgetCollateralValid, AddProposal, vecImmatureFinalizedBudgets, AddFinalizedBudget.
CBudgetProposal * CBudgetManager::FindProposal(const std::string &strProposalName)
References mapProposals, CBudgetProposal::GetYesCount.
Referenced by snbudget, ResetSync, MarkSynced, Sync, CFinalizedBudget::GetProposals, CFinalizedBudget::GetStatus.
CBudgetProposal * CBudgetManager::FindProposal(uint256 nHash)
References LOCK, cs, mapProposals.
CFinalizedBudget * CBudgetManager::FindFinalizedBudget(uint256 nHash)
References mapFinalizedBudgets.
Referenced by snfinalbudget, ResetSync, MarkSynced, Sync.
std::pair<std::string, std::string> CBudgetManager::GetVotes(std::string strProposalName)
CAmount CBudgetManager::GetTotalBudget(int nHeight)
References pindexBest.
Referenced by GetBudget, CBudgetProposal::IsValid, CFinalizedBudget::IsValid.
std::vector< CBudgetProposal * > CBudgetManager::GetBudget()
References LOCK, cs, mapProposals, pindexBest, CBlockIndex::nHeight, GetBudgetPaymentCycleBlocks, GetTotalBudget, CBudgetProposal::strProposalName, CBudgetProposal::nBlockStart, CBudgetProposal::nBlockEnd, CBudgetProposal::fValid, CBudgetProposal::GetYesCount, CBudgetProposal::GetNoCount, snodeman, CStormnodeMan::CountEnabled, CBudgetProposal::IsEstablished, CBudgetProposal::GetAmount, CBudgetProposal::SetAllotted.
Referenced by snbudget, SubmitFinalBudget, CFinalizedBudget::AutoCheck.
std::vector< CBudgetProposal * > CBudgetManager::GetAllProposals()
References LOCK, cs, mapProposals.
Referenced by snbudget.
std::vector< CFinalizedBudget * > CBudgetManager::GetFinalizedBudgets()
References LOCK, cs, mapFinalizedBudgets, CFinalizedBudget::GetVoteCount.
Referenced by snfinalbudget.
bool CBudgetManager::IsBudgetPaymentBlock(int nBlockHeight)
References mapFinalizedBudgets, CFinalizedBudget::GetVoteCount, CFinalizedBudget::GetBlockStart, CFinalizedBudget::GetBlockEnd, snodeman, CStormnodeMan::CountEnabled.
Referenced by HasNextFinalizedBudget, IsBlockValueValid, IsBlockPayeeValid, FillBlockPayee, GetRequiredPaymentsString, CStormnodePayments::ProcessBlock.
bool CBudgetManager::AddProposal(CBudgetProposal &budgetProposal)
References LOCK, cs, CBudgetProposal::IsValid, LogPrintf, mapProposals, CBudgetProposal::GetHash.
Referenced by snbudget, NewBlock, ProcessMessage.
bool CBudgetManager::AddFinalizedBudget(CFinalizedBudget &finalizedBudget)
References CFinalizedBudget::IsValid, mapFinalizedBudgets, CFinalizedBudget::GetHash.
Referenced by SubmitFinalBudget, NewBlock, ProcessMessage.
void CBudgetManager::SubmitFinalBudget()
References pindexBest, CBlockIndex::nHeight, GetBudgetPaymentCycleBlocks, nSubmittedFinalBudget, GetBudget, CTxBudgetPayment::nProposalHash, uint256::GetHash, CTxBudgetPayment::payee, CTxBudgetPayment::nAmount, LogPrintf, mapSeenFinalizedBudgets, CFinalizedBudget::GetHash, base_uint< BITS >::ToString, pwalletMain, CWallet::GetBudgetSystemCollateralTX, CWallet::CommitTransaction, CTransaction::GetHash, GetInputAgeIX, LOCK, cs, AddFinalizedBudget.
Referenced by NewBlock.
bool CBudgetManager::HasNextFinalizedBudget()
References pindexBest, stormnodeSync, CStormnodeSync::IsBudgetFinEmpty, CBlockIndex::nHeight, GetBudgetPaymentCycleBlocks, IsBudgetPaymentBlock, LogPrintf.
bool CBudgetManager::UpdateProposal(CBudgetVote &vote, CNode *pfrom, std::string &strError)
References LOCK, cs, mapProposals, CBudgetVote::nProposalHash, stormnodeSync, CStormnodeSync::IsSynced, LogPrintf, base_uint< BITS >::ToString, mapOrphanStormnodeBudgetVotes, askedForSourceProposalOrBudget, CNode::PushMessage, GetTime.
Referenced by snbudget, snbudgetvoteraw, CheckOrphanVotes, ProcessMessage.
bool CBudgetManager::UpdateFinalizedBudget(CFinalizedBudgetVote &vote, CNode *pfrom, std::string &strError)
References LOCK, cs, mapFinalizedBudgets, CFinalizedBudgetVote::nBudgetHash, stormnodeSync, CStormnodeSync::IsSynced, LogPrintf, base_uint< BITS >::ToString, mapOrphanFinalizedBudgetVotes, askedForSourceProposalOrBudget, CNode::PushMessage, GetTime.
Referenced by snfinalbudget, CheckOrphanVotes, ProcessMessage, CFinalizedBudget::SubmitVote.
bool CBudgetManager::PropExists(uint256 nHash)
References mapProposals.
bool CBudgetManager::IsTransactionValid(const CTransaction &txNew, int nBlockHeight)
References LOCK, cs, mapFinalizedBudgets, CFinalizedBudget::GetVoteCount, CFinalizedBudget::GetBlockStart, CFinalizedBudget::GetBlockEnd, snodeman, CStormnodeMan::CountEnabled, CFinalizedBudget::IsTransactionValid.
Referenced by IsBlockPayeeValid.
std::string CBudgetManager::GetRequiredPaymentsString(int nBlockHeight)
References LOCK, cs, mapFinalizedBudgets, CFinalizedBudget::GetBlockStart, CFinalizedBudget::GetBlockEnd, CFinalizedBudget::GetBudgetPaymentByBlock, CTxBudgetPayment::nProposalHash, base_uint< BITS >::ToString, LogPrintf.
Referenced by GetRequiredPaymentsString.
void CBudgetManager::FillBlockPayee(CTransaction &txNew, CAmount nFees)
References LOCK, cs, pindexBest, mapFinalizedBudgets, CFinalizedBudget::GetVoteCount, CBlockIndex::nHeight, CFinalizedBudget::GetBlockStart, CFinalizedBudget::GetBlockEnd, CFinalizedBudget::GetPayeeAndAmount, GetBlockValue, CBlockIndex::nBits, CTransaction::vout, ExtractDestination, LogPrintf, CBase58Data::ToString.
Referenced by FillBlockPayee.
void CBudgetManager::CheckOrphanVotes()
References LOCK, cs, mapOrphanStormnodeBudgetVotes, UpdateProposal, LogPrintf, mapOrphanFinalizedBudgetVotes, UpdateFinalizedBudget.
Referenced by ProcessMessage.
void CBudgetManager::Clear()
References LOCK, LogPrintf.
Referenced by ExecuteSpork, CBudgetDB::Read.
void CBudgetManager::CheckAndRemove()
References LogPrintf, pindexBest, mapFinalizedBudgets, CFinalizedBudget::fValid, CFinalizedBudget::IsValid, CFinalizedBudget::AutoCheck, CFinalizedBudget::nBlockStart, CBlockIndex::nHeight, GetBudgetPaymentCycleBlocks, CFinalizedBudget::GetHash, base_uint< BITS >::ToString, mapProposals, CBudgetProposal::fValid, CBudgetProposal::IsValid.
Referenced by snbudget, CBudgetDB::Read, NewBlock.
std::string CBudgetManager::ToString() const
References mapProposals, mapFinalizedBudgets, mapSeenStormnodeBudgetProposals, mapSeenStormnodeBudgetVotes, mapSeenFinalizedBudgets, mapSeenFinalizedBudgetVotes.
Referenced by CBudgetDB::Read.
void CBudgetManager::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE.