CBasicKeyStore
KeyMap CBasicKeyStore::mapKeys
Referenced by CCryptoKeyStore::SetCrypted, CCryptoKeyStore::EncryptKeys, AddKeyPubKey.
ScriptMap CBasicKeyStore::mapScripts
Referenced by AddCScript, HaveCScript, GetCScript.
WatchOnlySet CBasicKeyStore::setWatchOnly
Referenced by AddWatchOnly, RemoveWatchOnly, HaveWatchOnly.
bool CBasicKeyStore::AddKeyPubKey(const CKey &key, const CPubKey &pubkey)
References LOCK, CKeyStore::cs_KeyStore, mapKeys, CPubKey::GetID.
Referenced by CCryptoKeyStore::AddKeyPubKey.
bool CBasicKeyStore::HaveKey(const CKeyID &address) const
References LOCK, CKeyStore::cs_KeyStore.
Referenced by CCryptoKeyStore::HaveKey.
void CBasicKeyStore::GetKeys(std::set< CKeyID > &setAddress) const
References LOCK, CKeyStore::cs_KeyStore.
Referenced by CCryptoKeyStore::GetKeys.
bool CBasicKeyStore::GetKey(const CKeyID &address, CKey &keyOut) const
References LOCK, CKeyStore::cs_KeyStore.
Referenced by CCryptoKeyStore::GetKey.
bool CBasicKeyStore::AddCScript(const CScript &redeemScript)
References LOCK, CKeyStore::cs_KeyStore, mapScripts, CScript::GetID.
Referenced by signrawtransaction, CWallet::AddCScript, CWallet::LoadCScript.
bool CBasicKeyStore::HaveCScript(const CScriptID &hash) const
References LOCK, CKeyStore::cs_KeyStore, mapScripts.
bool CBasicKeyStore::GetCScript(const CScriptID &hash, CScript &redeemScriptOut) const
References LOCK, CKeyStore::cs_KeyStore, mapScripts.
bool CBasicKeyStore::AddWatchOnly(const CScript &dest)
References LOCK, CKeyStore::cs_KeyStore, setWatchOnly.
Referenced by CWallet::AddWatchOnly, CWallet::LoadWatchOnly.
bool CBasicKeyStore::RemoveWatchOnly(const CScript &dest)
References LOCK, CKeyStore::cs_KeyStore, setWatchOnly.
Referenced by CWallet::RemoveWatchOnly.
bool CBasicKeyStore::HaveWatchOnly(const CScript &dest) const
References LOCK, CKeyStore::cs_KeyStore, setWatchOnly.
Referenced by importaddress.
bool CBasicKeyStore::HaveWatchOnly() const
References LOCK, CKeyStore::cs_KeyStore, setWatchOnly.