CStormnodePaymentDB
ReadResult
boost::filesystem::path CStormnodePaymentDB::pathDB
std::string CStormnodePaymentDB::strMagicMessage
CStormnodePaymentDB::CStormnodePaymentDB()
References GetDataDir.
bool CStormnodePaymentDB::Write(const CStormnodePayments &objToSave)
References GetTimeMillis, SER_DISK, FLATDATA, Params, hash, Hash, CDataStream::begin, CDataStream::end, LogPrintf.
Referenced by DumpStormnodePayments.
CStormnodePaymentDB::ReadResult CStormnodePaymentDB::Read(CStormnodePayments &objToLoad, bool fDryRun=false)
References GetTimeMillis, SER_DISK, FileError, HashReadError, Hash, CDataStream::begin, CDataStream::end, IncorrectHash, IncorrectMagicMessage, FLATDATA, Params, IncorrectMagicNumber, CStormnodePayments::Clear, IncorrectFormat, LogPrintf, CStormnodePayments::ToString, CStormnodePayments::CleanPaymentList, Ok.
Referenced by AppInit2, DumpStormnodePayments.