leveldb::BlockHandle
@7
uint64_t leveldb::BlockHandle::offset_
uint64_t leveldb::BlockHandle::size_
leveldb::BlockHandle::BlockHandle()
uint64_t leveldb::BlockHandle::offset() const
Referenced by leveldb::ReadBlock, set_offset, leveldb::Table::ApproximateOffsetOf.
void leveldb::BlockHandle::set_offset(uint64_t offset)
References offset.
uint64_t leveldb::BlockHandle::size() const
Referenced by leveldb::ReadBlock, set_size.
void leveldb::BlockHandle::set_size(uint64_t size)
References size.
void leveldb::BlockHandle::EncodeTo(std::string *dst) const
References leveldb::PutVarint64.
Referenced by leveldb::Footer::EncodeTo, leveldb::TableBuilder::Add, leveldb::TableBuilder::Finish.
Status leveldb::BlockHandle::DecodeFrom(Slice *input)
References leveldb::GetVarint64, leveldb::Status::OK, leveldb::Status::Corruption.
Referenced by leveldb::Footer::DecodeFrom, leveldb::Table::ApproximateOffsetOf.