SAM::Socket
std::auto_ptr<SocketImpl> SAM::Socket::impl_
SOCKET SAM::Socket::socket_
sockaddr_in SAM::Socket::servAddr_
std::string SAM::Socket::SAMHost_
uint16_t SAM::Socket::SAMPort_
const std::string SAM::Socket::minVer_
const std::string SAM::Socket::maxVer_
std::string SAM::Socket::version_
SAM::Socket::Socket(const std::string &SAMHost, uint16_t SAMPort, const std::string &minVer, const std::string &maxVer)
References isOk.
SAM::Socket::Socket(const sockaddr_in &addr, const std::string &minVer, const std::string &maxVer)
References isOk.
SAM::Socket::Socket(const Socket &rhs)
References isOk.
SAM::Socket::~Socket()
References close.
void SAM::Socket::write(const std::string &msg)
References isOk, SAM_SOCKET_ERROR, close.
std::string SAM::Socket::read()
References isOk, SAM_BUFSIZE, SAM_SOCKET_ERROR, close.
SOCKET SAM::Socket::release()
References SAM_INVALID_SOCKET.
void SAM::Socket::close()
References SAM_INVALID_SOCKET, closesocket.
Referenced by ~Socket, write, read, SAM::StreamSession::StreamSession.
bool SAM::Socket::isOk() const
References SAM_INVALID_SOCKET.
Referenced by Socket, write, read.
const std::string & SAM::Socket::getVersion() const
Referenced by SAM::StreamSession::getSAMVersion.
const std::string & SAM::Socket::getHost() const
Referenced by SAM::StreamSession::getSAMHost.
uint16_t SAM::Socket::getPort() const
Referenced by SAM::StreamSession::getSAMPort.
const std::string & SAM::Socket::getMinVer() const
Referenced by SAM::StreamSession::getSAMMinVer.
const std::string & SAM::Socket::getMaxVer() const
Referenced by SAM::StreamSession::getSAMMaxVer.
const sockaddr_in & SAM::Socket::getAddress() const
Referenced by SAM::StreamSession::getSAMAddress.
void SAM::Socket::handshake()
void SAM::Socket::init()
Socket& SAM::Socket::operator=(const Socket &)