CMessageHeader
@13
CMessageHeader::ADD_SERIALIZE_METHODS
char CMessageHeader::pchMessageStart[MESSAGE_START_SIZE][MESSAGE_START_SIZE]
Referenced by ProcessMessages, CMessageHeader, IsValid, SerializationOp.
char CMessageHeader::pchCommand[COMMAND_SIZE][COMMAND_SIZE]
Referenced by CMessageHeader, GetCommand, IsValid, SerializationOp.
unsigned int CMessageHeader::nMessageSize
Referenced by ProcessMessages, CNetMessage::complete, CMessageHeader, IsValid, SerializationOp.
unsigned int CMessageHeader::nChecksum
Referenced by ProcessMessages, CMessageHeader, SerializationOp.
CMessageHeader::CMessageHeader()
References pchMessageStart, Params, MESSAGE_START_SIZE, pchCommand, nMessageSize, nChecksum.
CMessageHeader::CMessageHeader(const char *pszCommand, unsigned int nMessageSizeIn)
References pchMessageStart, Params, MESSAGE_START_SIZE, pchCommand, COMMAND_SIZE, nMessageSize, nChecksum.
std::string CMessageHeader::GetCommand() const
References pchCommand, COMMAND_SIZE.
Referenced by ProcessMessages, IsValid.
bool CMessageHeader::IsValid() const
References pchMessageStart, Params, MESSAGE_START_SIZE, pchCommand, COMMAND_SIZE, nMessageSize, MAX_SIZE, LogPrintf, GetCommand.
Referenced by ProcessMessages.
void CMessageHeader::SerializationOp(Stream &s, Operation ser_action, int nType, int nVersion)
References READWRITE, FLATDATA, pchMessageStart, pchCommand, nMessageSize, nChecksum.