OverviewPage
QTimer* OverviewPage::timer
Ui::OverviewPage* OverviewPage::ui
ClientModel* OverviewPage::clientModel
WalletModel* OverviewPage::walletModel
CAmount OverviewPage::currentBalance
CAmount OverviewPage::currentStake
CAmount OverviewPage::currentUnconfirmedBalance
CAmount OverviewPage::currentImmatureBalance
CAmount OverviewPage::currentAnonymizedBalance
CAmount OverviewPage::currentWatchOnlyBalance
CAmount OverviewPage::currentWatchUnconfBalance
CAmount OverviewPage::currentWatchImmatureBalance
CAmount OverviewPage::currentWatchOnlyStake
int OverviewPage::nDisplayUnit
qint64 OverviewPage::lastNewBlock
int OverviewPage::showingSandStormMessage
int OverviewPage::sandstormActionCheck
int OverviewPage::cachedNumBlocks
int OverviewPage::cachedTxLocks
TxViewDelegate* OverviewPage::txdelegate
TransactionFilterProxy* OverviewPage::filter
OverviewPage::OverviewPage(QWidget *parent=0)
References DECORATION_SIZE, NUM_ITEMS, fLiteMode, GetBoolArg, fStormNode, fEnableSandstorm, sandStormStatus, showOutOfSyncWarning, fUseBlackTheme.
OverviewPage::~OverviewPage()
References fLiteMode, fStormNode, sandStormStatus.
void OverviewPage::setClientModel(ClientModel *clientModel)
References ClientModel::getStatusBarWarnings.
Referenced by DarkSilkGUI::setClientModel.
void OverviewPage::setWalletModel(WalletModel *walletModel)
References WalletModel::getOptionsModel, WalletModel::getTransactionTableModel, TransactionFilterProxy::setLimit, NUM_ITEMS, TransactionFilterProxy::setShowInactive, TransactionTableModel::Status, TransactionTableModel::ToAddress, setBalance, WalletModel::getBalance, WalletModel::getStake, WalletModel::getUnconfirmedBalance, WalletModel::getImmatureBalance, WalletModel::getAnonymizedBalance, WalletModel::getWatchBalance, WalletModel::getWatchStake, WalletModel::getWatchUnconfirmedBalance, WalletModel::getWatchImmatureBalance.
Referenced by DarkSilkGUI::setWalletModel.
void OverviewPage::showOutOfSyncWarning(bool fShow)
Referenced by DarkSilkGUI::setNumBlocks, OverviewPage.
void OverviewPage::updateSandstormProgress()
References IsInitialBlockDownload, pwalletMain, CWallet::GetBalance, DarkSilkUnits::formatWithUnit, WalletModel::getOptionsModel, OptionsModel::getDisplayUnit, nAnonymizeDarkSilkAmount, nSandstormRounds, CWallet::GetDenominatedBalance, CWallet::GetAnonymizableBalance, CWallet::GetNormalizedAnonymizedBalance, CWallet::GetAnonymizedBalance, CWallet::GetAverageAnonymizedRounds, arg.
Referenced by sandStormStatus.
void OverviewPage::sandStormStatus()
References IsInitialBlockDownload, nBestHeight, pindexBest, CBlockIndex::nHeight, sandStormPool, CSandstormPool::cachedNumBlocks, GetTime, updateSandstormProgress, fEnableSandstorm, state, CSandstormPool::GetState, CSandstormPool::GetEntriesCount, CSandstormPool::GetLastEntryAccepted, CSandstormPool::cachedLastSuccess, CSandstormPool::minBlockSpacing, CSandstormPool::strAutoDenomResult, POOL_STATUS_IDLE, POOL_STATUS_ACCEPTING_ENTRIES, CSandstormPool::lastEntryAccepted, CSandstormPool::GetMaxPoolTransactions, POOL_STATUS_SIGNING, POOL_STATUS_TRANSMISSION, POOL_STATUS_FINALIZE_TRANSACTION, POOL_STATUS_ERROR, CSandstormPool::lastMessage, POOL_STATUS_SUCCESS, POOL_STATUS_QUEUE, CSandstormPool::Check, LogPrintf, CSandstormPool::sessionDenom, CSandstormPool::GetDenominationsToString.
Referenced by OverviewPage, ~OverviewPage.
void OverviewPage::setBalance(const CAmount &balance, const CAmount &stake, const CAmount &unconfirmedBalance, const CAmount &immatureBalance, const CAmount &anonymizedBalance, const CAmount &watchOnlyBalance, const CAmount &watchOnlyStake, const CAmount &watchUnconfBalance, const CAmount &watchImmatureBalance)
References WalletModel::getOptionsModel, OptionsModel::getDisplayUnit, DarkSilkUnits::formatWithUnit, DarkSilkUnits::floorWithUnit, nCompleteTXLocks.
Referenced by setWalletModel.
void OverviewPage::transactionClicked(const QModelIndex &index)
void OverviewPage::toggleSandstorm()
void OverviewPage::sandstormAuto()
void OverviewPage::sandstormReset()
void OverviewPage::updateDisplayUnit()
void OverviewPage::handleTransactionClicked(const QModelIndex &index)
void OverviewPage::updateAlerts(const QString &warnings)