CLevelDBBatch
friend class CLevelDBWrapper
leveldb::WriteBatch CLevelDBBatch::batch
void CLevelDBBatch::Write(const K &key, const V &value)
References SER_DISK, CDataStream::reserve, CDataStream::GetSerializeSize, CDataStream::size, value, leveldb::WriteBatch::Put.
Referenced by CLevelDBWrapper::Write, BatchWriteCoins, BatchWriteHashBestChain, CBlockTreeDB::WriteTxIndex.
void CLevelDBBatch::Erase(const K &key)
References SER_DISK, CDataStream::reserve, CDataStream::GetSerializeSize, CDataStream::size, leveldb::WriteBatch::Delete.
Referenced by CLevelDBWrapper::Erase, BatchWriteCoins.