DarkSilkAmountField
qint64 DarkSilkAmountField::value
QDoubleSpinBox* DarkSilkAmountField::amount
QValueComboBox* DarkSilkAmountField::unit
int DarkSilkAmountField::currentUnit
DarkSilkAmountField::DarkSilkAmountField(QWidget *parent=0)
References textChanged.
CAmount DarkSilkAmountField::value(bool *valid=0) const
References DarkSilkUnits::parse.
void DarkSilkAmountField::setValue(const CAmount &value)
References DarkSilkUnits::format.
void DarkSilkAmountField::setValid(bool valid)
Mark current value as invalid in UI.
References STYLE_INVALID.
Referenced by validate, eventFilter.
bool DarkSilkAmountField::validate()
Perform input validation, mark field as invalid if entered value is not valid.
References DarkSilkUnits::parse, setValid.
void DarkSilkAmountField::setDisplayUnit(int unit)
Change unit used to display amount.
References QValueComboBox::setValue.
void DarkSilkAmountField::clear()
Make field empty and ready for new input.
QWidget * DarkSilkAmountField::setupTabChain(QWidget *prev)
Qt messes up the tab chain by default in some cases (issue https://bugreports.qt-project.org/browse/QTBUG-10907), in these cases we have to set it up manually.
void DarkSilkAmountField::textChanged()
Referenced by DarkSilkAmountField.
bool DarkSilkAmountField::eventFilter(QObject *object, QEvent *event)
Intercept focus-in event and ',' key presses
References setValid.
void DarkSilkAmountField::setText(const QString &text)
QString DarkSilkAmountField::text() const
void DarkSilkAmountField::unitChanged(int idx)