cleanse.cpp
void memory_cleanse(void *ptr, size_t len)
Referenced by UnlockObject, secure_allocator< T >::deallocate, zero_after_free_allocator< T >::deallocate, CBase58Data::SetString, CCrypter::SetKeyFromPassphrase.