core.h
ALIGN
CONST_CAST
Referenced by argon2_hash.
argon2_core_constants
typedef struct block_ block
typedef struct Argon2_instance_t argon2_instance_t
typedef struct Argon2_position_t argon2_position_t
typedef struct Argon2_thread_data argon2_thread_data
void init_block_value(block *b, uint8_t in)
References block_::v.
Referenced by generate_addresses.
void copy_block(block *dst, const block *src)
References block_::v, ARGON2_QWORDS_IN_BLOCK.
Referenced by finalize, fill_block.
void xor_block(block *dst, const block *src)
References ARGON2_QWORDS_IN_BLOCK, block_::v.
Referenced by finalize, fill_block.
int allocate_memory(block **memory, uint32_t m_cost)
References ARGON2_MEMORY_ALLOCATION_ERROR, ARGON2_OK.
Referenced by initialize.
void secure_wipe_memory(void *v, size_t n)
Referenced by clear_memory, finalize, fill_first_blocks, initial_hash, initialize.
void clear_memory(argon2_instance_t *instance, int clear)
References Argon2_instance_t::memory, secure_wipe_memory, Argon2_instance_t::memory_blocks.
Referenced by finalize.
void free_memory(block *memory)
Referenced by finalize.
uint32_t index_alpha(const argon2_instance_t *instance, const argon2_position_t *position, uint32_t pseudo_rand, int same_lane)
References Argon2_position_t::pass, Argon2_position_t::slice, Argon2_position_t::index, Argon2_instance_t::segment_length, Argon2_instance_t::lane_length, ARGON2_SYNC_POINTS.
Referenced by fill_segment.
int validate_inputs(const argon2_context *context)
References ARGON2_INCORRECT_PARAMETER, Argon2_Context::out, ARGON2_OUTPUT_PTR_NULL, ARGON2_MIN_OUTLEN, Argon2_Context::outlen, ARGON2_OUTPUT_TOO_SHORT, ARGON2_OUTPUT_TOO_LONG, Argon2_Context::pwd, Argon2_Context::pwdlen, ARGON2_PWD_PTR_MISMATCH, ARGON2_MIN_PWD_LENGTH, ARGON2_PWD_TOO_SHORT, ARGON2_PWD_TOO_LONG, Argon2_Context::salt, Argon2_Context::saltlen, ARGON2_SALT_PTR_MISMATCH, ARGON2_MIN_SALT_LENGTH, ARGON2_SALT_TOO_SHORT, ARGON2_SALT_TOO_LONG, Argon2_Context::secret, Argon2_Context::secretlen, ARGON2_SECRET_PTR_MISMATCH, ARGON2_MIN_SECRET, ARGON2_SECRET_TOO_SHORT, ARGON2_SECRET_TOO_LONG, Argon2_Context::ad, Argon2_Context::adlen, ARGON2_AD_PTR_MISMATCH, ARGON2_MIN_AD_LENGTH, ARGON2_AD_TOO_SHORT, ARGON2_AD_TOO_LONG, ARGON2_MIN_MEMORY, Argon2_Context::m_cost, ARGON2_MEMORY_TOO_LITTLE, ARGON2_MEMORY_TOO_MUCH, Argon2_Context::lanes, ARGON2_MIN_TIME, Argon2_Context::t_cost, ARGON2_TIME_TOO_SMALL, ARGON2_TIME_TOO_LARGE, ARGON2_MIN_LANES, ARGON2_LANES_TOO_FEW, ARGON2_LANES_TOO_MANY, ARGON2_MIN_THREADS, Argon2_Context::threads, ARGON2_THREADS_TOO_FEW, ARGON2_THREADS_TOO_MANY, Argon2_Context::allocate_cbk, Argon2_Context::free_cbk, ARGON2_FREE_MEMORY_CBK_NULL, ARGON2_ALLOCATE_MEMORY_CBK_NULL, ARGON2_OK.
Referenced by argon2_core.
void initial_hash(uint8_t *blockhash, argon2_context *context, argon2_type type)
References value, blake2b_init, ARGON2_PREHASH_DIGEST_LENGTH, Argon2_Context::lanes, blake2b_update, Argon2_Context::outlen, Argon2_Context::m_cost, Argon2_Context::t_cost, ARGON2_VERSION_NUMBER, Argon2_Context::pwdlen, Argon2_Context::pwd, Argon2_Context::flags, ARGON2_FLAG_CLEAR_PASSWORD, secure_wipe_memory, Argon2_Context::saltlen, Argon2_Context::salt, Argon2_Context::secretlen, Argon2_Context::secret, ARGON2_FLAG_CLEAR_SECRET, Argon2_Context::adlen, Argon2_Context::ad, blake2b_final.
Referenced by initialize.
void fill_first_blocks(uint8_t *blockhash, const argon2_instance_t *instance)
References ARGON2_BLOCK_SIZE, Argon2_instance_t::lanes, ARGON2_PREHASH_DIGEST_LENGTH, blake2b_long, ARGON2_PREHASH_SEED_LENGTH, Argon2_instance_t::memory, Argon2_instance_t::lane_length, secure_wipe_memory.
Referenced by initialize.
int initialize(argon2_instance_t *instance, argon2_context *context)
References ARGON2_PREHASH_SEED_LENGTH, ARGON2_OK, ARGON2_INCORRECT_PARAMETER, Argon2_Context::allocate_cbk, Argon2_instance_t::memory_blocks, ARGON2_BLOCK_SIZE, Argon2_instance_t::memory, allocate_memory, initial_hash, Argon2_instance_t::type, secure_wipe_memory, ARGON2_PREHASH_DIGEST_LENGTH, initial_kat, fill_first_blocks.
Referenced by argon2_core.
void finalize(const argon2_context *context, argon2_instance_t *instance)
References copy_block, Argon2_instance_t::memory, Argon2_instance_t::lane_length, Argon2_instance_t::lanes, xor_block, ARGON2_BLOCK_SIZE, blake2b_long, Argon2_Context::out, Argon2_Context::outlen, secure_wipe_memory, block_::v, print_tag, clear_memory, Argon2_Context::flags, ARGON2_FLAG_CLEAR_PASSWORD, Argon2_Context::free_cbk, Argon2_instance_t::memory_blocks, free_memory.
Referenced by argon2_core.
void fill_segment(const argon2_instance_t *instance, argon2_position_t position)
References state, Argon2_instance_t::type, Argon2_i, Argon2_instance_t::segment_length, generate_addresses, Argon2_position_t::pass, Argon2_position_t::slice, Argon2_position_t::lane, Argon2_instance_t::lane_length, Argon2_instance_t::memory, ARGON2_BLOCK_SIZE, block_::v, Argon2_instance_t::lanes, Argon2_position_t::index, index_alpha, fill_block.
int fill_memory_blocks(argon2_instance_t *instance)
References Argon2_instance_t::lanes, ARGON2_THREAD_FAIL, ARGON2_MEMORY_ALLOCATION_ERROR, Argon2_instance_t::passes, ARGON2_SYNC_POINTS, Argon2_instance_t::threads, argon2_thread_join, Argon2_position_t::pass, Argon2_position_t::lane, Argon2_position_t::slice, Argon2_position_t::index, Argon2_thread_data::instance_ptr, argon2_thread_create, internal_kat, ARGON2_OK.
Referenced by argon2_core.