crypter.h
typedef std::vector<unsigned char, secure_allocator<unsigned char> > CKeyingMaterial
const unsigned int WALLET_CRYPTO_KEY_SIZE
! for SecureString
Referenced by CCrypter::SetKeyFromPassphrase, CCrypter::SetKey, EncryptSecret, DecryptSecret, CWallet::EncryptWallet.
const unsigned int WALLET_CRYPTO_SALT_SIZE
Referenced by CCrypter::SetKeyFromPassphrase, CWallet::EncryptWallet.
bool EncryptSecret(const CKeyingMaterial &vMasterKey, const CKeyingMaterial &vchPlaintext, const uint256 &nIV, std::vector< unsigned char > &vchCiphertext)
References WALLET_CRYPTO_KEY_SIZE, CCrypter::SetKey, CCrypter::Encrypt.
Referenced by CCryptoKeyStore::AddKeyPubKey, CCryptoKeyStore::EncryptKeys, CWallet::EncryptWallet, CWallet::AddStealthAddress.
bool DecryptSecret(const CKeyingMaterial &vMasterKey, const std::vector< unsigned char > &vchCiphertext, const uint256 &nIV, CKeyingMaterial &vchPlaintext)
References WALLET_CRYPTO_KEY_SIZE, CCrypter::SetKey, CCrypter::Decrypt.
Referenced by CCryptoKeyStore::Unlock, CCryptoKeyStore::GetKey, CWallet::UnlockStealthAddresses.
bool EncryptAES256(const SecureString &sKey, const SecureString &sPlaintext, const std::string &sIV, std::string &sCiphertext)
References LogPrintf.
bool DecryptAES256(const SecureString &sKey, const std::string &sCiphertext, const std::string &sIV, SecureString &sPlaintext)
References LogPrintf.