darksilkd.cpp
bool fDaemon
void DetectShutdownThread(boost::thread_group *threadGroup)
References ShutdownRequested, MilliSleep.
Referenced by AppInit.
bool AppInit(int argc, char *argv[])
References ParseParameters, GetDataDir, Shutdown, ReadConfigFile, mapArgs, mapMultiArgs, _, FormatFullVersion, HelpMessage, IsSwitchChar, fCommandLine, SelectParamsFromCommandLine, CommandLineRPC, fDaemon, GetBoolArg, CreatePidFile, GetPidFile, SoftSetBoolArg, DetectShutdownThread, AppInit2, PrintException.
Referenced by main.
void noui_connect()
References uiInterface, CClientUIInterface::ThreadSafeMessageBox, CClientUIInterface::ThreadSafeAskFee, CClientUIInterface::InitMessage.
Referenced by main.
int main(int argc, char *argv[])
References noui_connect, AppInit, fDaemon.