tests_impl.h
void test_ecdh_generator_basepoint(void)
References random_scalar_order, CHECK, secp256k1_ec_pubkey_create, secp256k1_ecdh, secp256k1_ec_pubkey_serialize, SECP256K1_EC_COMPRESSED.
Referenced by run_ecdh_tests.
void test_bad_scalar(void)
References rand, random_scalar_order, CHECK, secp256k1_ec_pubkey_create, secp256k1_ecdh.
Referenced by run_ecdh_tests.
void run_ecdh_tests(void)
References test_ecdh_generator_basepoint, test_bad_scalar.
Referenced by main.