genkat.h
void initial_kat(const uint8_t *blockhash, const argon2_context *context, argon2_type type)
References Argon2_d, Argon2_i, Argon2_Context::m_cost, Argon2_Context::t_cost, Argon2_Context::lanes, Argon2_Context::outlen, Argon2_Context::pwdlen, Argon2_Context::flags, ARGON2_FLAG_CLEAR_PASSWORD, Argon2_Context::pwd, Argon2_Context::saltlen, Argon2_Context::salt, Argon2_Context::secretlen, ARGON2_FLAG_CLEAR_SECRET, Argon2_Context::secret, Argon2_Context::adlen, Argon2_Context::ad, ARGON2_PREHASH_DIGEST_LENGTH.
Referenced by initialize.
void print_tag(const void *out, uint32_t outlen)
Referenced by finalize.
void internal_kat(const argon2_instance_t *instance, uint32_t pass)
References Argon2_instance_t::memory_blocks, ARGON2_QWORDS_IN_BLOCK, Argon2_instance_t::memory, block_::v.
Referenced by fill_memory_blocks.