hash.cpp
int HMAC_SHA512_Init(HMAC_SHA512_CTX *pctx, const void *pkey, size_t len)
References HMAC_SHA512_CTX::ctxOuter, HMAC_SHA512_CTX::ctxInner.
Referenced by BIP32Hash, CExtKey::SetMaster, BOOST_AUTO_TEST_CASE.
int HMAC_SHA512_Update(HMAC_SHA512_CTX *pctx, const void *pdata, size_t len)
References HMAC_SHA512_CTX::ctxInner.
Referenced by BIP32Hash, CExtKey::SetMaster, BOOST_AUTO_TEST_CASE.
int HMAC_SHA512_Final(unsigned char *pmd, HMAC_SHA512_CTX *pctx)
References HMAC_SHA512_CTX::ctxInner, HMAC_SHA512_CTX::ctxOuter.
Referenced by BIP32Hash, CExtKey::SetMaster, BOOST_AUTO_TEST_CASE.
void BIP32Hash(const unsigned char chainCode[32], unsigned int nChild, unsigned char header, const unsigned char data[32], unsigned char output[64])
References HMAC_SHA512_Init, HMAC_SHA512_Update, HMAC_SHA512_Final.
Referenced by CKey::Derive, CPubKey::Derive.