hash.h
const unsigned int OUTPUT_BYTES
uint256 Hash(const T1 pbegin, const T1 pend)
Referenced by CAddrInfo::GetTriedBucket, CAddrInfo::GetNewBucket, CAlert::GetHash, CAlert::CheckSignature, EncodeBase58Check, DecodeBase58Check, ComputeStakeModifierV2, CheckStakeKernelHash, CBlockHeader::GetHash, CBlock::BuildMerkleTree, CBlock::CheckMerkleBranch, ProcessMessages, SendMessages, CAddrDB::Write, CAddrDB::Read, CNode::EndMessage, CNetAddr::GetHash, CPubKey::GetHash, sendalert, EvalScript, SecureMsgEncrypt, SecureMsgDecrypt, CSporkMessage::GetHash, CBudgetDB::Write, CBudgetDB::Read, CStormnodePaymentDB::Write, CStormnodePaymentDB::Read, CStormnodeDB::Write, CStormnodeDB::Read, BOOST_AUTO_TEST_CASE, CWallet::EncryptWallet, CWallet::AddStealthAddress, CWallet::UnlockStealthAddresses, CWalletDB::WriteKey, ReadKeyValue.
uint256 HashBlake2b(const T1 pbegin, const T1 pend)
References blake2b_init, blake2b_update, blake2b_final.
Referenced by hashArgon2d.
int Argon2d_Hash(void *out, size_t outlen, const void *in, size_t inlen, const void *salt, size_t saltlen, unsigned int t_cost, unsigned int m_cost)
Argon2d Parameters Salt and password are the block header. Output length: 32 bytes. Input length (in the case of a block header): 80 bytes. Salt length (same note as input length): 80 bytes. Input: Block header Salt: Block header (SAME AS INPUT) Secret data: None Secret length: 0 Associated data: None Associated data length: 0 Memory cost: 1024 Lanes: 64
References ARGON2_PWD_TOO_LONG, ARGON2_OUTPUT_TOO_LONG, ARGON2_SALT_TOO_LONG, Argon2_Context::out, Argon2_Context::outlen, Argon2_Context::pwd, Argon2_Context::pwdlen, Argon2_Context::salt, Argon2_Context::saltlen, Argon2_Context::secret, Argon2_Context::secretlen, Argon2_Context::ad, Argon2_Context::adlen, Argon2_Context::t_cost, Argon2_Context::m_cost, Argon2_Context::lanes, Argon2_Context::threads, Argon2_Context::allocate_cbk, Argon2_Context::free_cbk, Argon2_Context::flags, ARGON2_DEFAULT_FLAGS, argon2_core, Argon2_d.
Referenced by hashArgon2d.
uint256 hashArgon2d(const T1 pbegin, const T1 pend)
References hash, HashBlake2b, Argon2d_Hash.
Referenced by CBlockHeader::GetPoWArgonHash.
uint256 Hash(const T1 p1begin, const T1 p1end, const T2 p2begin, const T2 p2end)
uint256 Hash(const T1 p1begin, const T1 p1end, const T2 p2begin, const T2 p2end, const T3 p3begin, const T3 p3end)
uint256 SerializeHash(const T &obj, int nType=SER_GETHASH, int nVersion=PROTOCOL_VERSION)
References CHashWriter::GetHash.
Referenced by CMutableTransaction::GetHash, COutPoint::GetHash, CTxOut::GetHash, CTransaction::GetHash.
uint160 Hash160(const T1 pbegin, const T1 pend)
Referenced by Hash160, CPubKey::GetID, EvalScript, CScript::GetID, CWallet::AddCScript, CWallet::CreateCoinStake.
uint160 Hash160(const std::vector< unsigned char > &vch)
References Hash160.
int HMAC_SHA512_Init(HMAC_SHA512_CTX *pctx, const void *pkey, size_t len)
References HMAC_SHA512_CTX::ctxOuter, HMAC_SHA512_CTX::ctxInner.
Referenced by BIP32Hash, CExtKey::SetMaster, BOOST_AUTO_TEST_CASE.
int HMAC_SHA512_Update(HMAC_SHA512_CTX *pctx, const void *pdata, size_t len)
References HMAC_SHA512_CTX::ctxInner.
Referenced by BIP32Hash, CExtKey::SetMaster, BOOST_AUTO_TEST_CASE.
int HMAC_SHA512_Final(unsigned char *pmd, HMAC_SHA512_CTX *pctx)
References HMAC_SHA512_CTX::ctxInner, HMAC_SHA512_CTX::ctxOuter.
Referenced by BIP32Hash, CExtKey::SetMaster, BOOST_AUTO_TEST_CASE.
void BIP32Hash(const unsigned char chainCode[32], unsigned int nChild, unsigned char header, const unsigned char data[32], unsigned char output[64])
References HMAC_SHA512_Init, HMAC_SHA512_Update, HMAC_SHA512_Final.
Referenced by CKey::Derive, CPubKey::Derive.
uint256 Hash(const T1 p1begin, const T1 p1end, const T2 p2begin, const T2 p2end, const T3 p3begin, const T3 p3end, const T4 p4begin, const T4 p4end)
Compute the 256-bit hash of the concatenation of three objects.
References CHash256::Write, CHash256::Finalize.
uint256 Hash(const T1 p1begin, const T1 p1end, const T2 p2begin, const T2 p2end, const T3 p3begin, const T3 p3end, const T4 p4begin, const T4 p4end, const T5 p5begin, const T5 p5end)
Compute the 256-bit hash of the concatenation of three objects.
References CHash256::Write, CHash256::Finalize.
uint256 Hash(const T1 p1begin, const T1 p1end, const T2 p2begin, const T2 p2end, const T3 p3begin, const T3 p3end, const T4 p4begin, const T4 p4end, const T5 p5begin, const T5 p5end, const T6 p6begin, const T6 p6end)
Compute the 256-bit hash of the concatenation of three objects.
References CHash256::Write, CHash256::Finalize.