init.cpp
CClientUIInterface uiInterface
Referenced by CAlert::ProcessAlert, AbortNode, CheckDiskSpace, ThreadSocketHandler, noui_connect, main, WalletModel::sendCoins, StartRPCThreads, AddTimeData, CWallet::SendStealthMoney, CWallet::TopUpKeyPool.
bool fConfChange
Referenced by AppInit2, CWalletTx::IsTrusted.
unsigned int nNodeLifespan
Referenced by AppInit2.
unsigned int nDerivationMethodIndex
Referenced by AppInit2, CWallet::EncryptWallet.
unsigned int nMinerSleep
Referenced by AppInit2, ThreadStakeMiner.
bool fUseFastIndex
Referenced by CDiskBlockIndex::GetBlockHash, AppInit2.
bool fOnlyTor
Referenced by AppInit2, DarkSilkGUI::setClientModel.
bool fMinimizeCoinAge
Referenced by AppInit2.
bool fFeeEstimatesInitialized
Referenced by Shutdown, AppInit2.
const char* FEE_ESTIMATES_FILENAME
volatile bool fRequestShutdown
Referenced by StartShutdown, ShutdownRequested, HandleSIGTERM, AppInit2.
boost::scoped_ptr<ECCVerifyHandle> globalVerifyHandle
CCoinsViewDB* pcoinsdbview
CCoinsViewErrorCatcher* pcoinscatcher
void StartShutdown()
References fRequestShutdown.
Referenced by AbortNode, CheckDiskSpace, stop, StartRPCThreads, encryptwallet.
bool ShutdownRequested()
References fRequestShutdown.
Referenced by DetectShutdownThread, CStormnode::Check.
void Shutdown()
References LogPrintf, TRY_LOCK, RenameThread, mempool, CTxMemPool::AddTransactionsUpdated, StopRPCThreads, SecureMsgShutdown, ShutdownRPCMining, bitdb, CDBEnv::Flush, StopNode, DumpStormnodes, DumpBudgets, DumpStormnodePayments, UnregisterNodeSignals, GetNodeSignals, fFeeEstimatesInitialized, GetDataDir, SER_DISK, CAutoFile::IsNull, CTxMemPool::WriteFeeEstimates, LOCK, cs_main, pcoinsTip, pblocktree, FlushStateToDisk, CWallet::SetBestChain, pindexBest, GetPidFile, UnregisterAllWallets, pwalletMain.
Referenced by AppInit, main.
void HandleSIGTERM(int)
References fRequestShutdown.
Referenced by AppInit2.
void HandleSIGHUP(int)
References fReopenDebugLog.
Referenced by AppInit2.
static bool InitError(const std::string &str)
static bool InitWarning(const std::string &str)
static bool Bind(const CService &addr, bool fError=true)
std::string HelpMessage()
References _, strprintf, fEnableSandstorm, fSandstormMultiSession, nSandstormRounds, nAnonymizeDarkSilkAmount, nLiquidityProvider, nInstantXDepth.
Referenced by AppInit, GUIUtil::HelpMessageBox::HelpMessageBox.
bool InitSanityCheck(void)
Sanity checks Ensure that DarkSilk is running in a usable environment with all necessary library support.
References ECC_InitSanityCheck.
Referenced by AppInit2.
bool AppInit2(boost::thread_group &threadGroup)
Initialize darksilk. Parameters should be parsed and config file should be read.
References strprintf, GetBoolArg, HandleSIGTERM, HandleSIGHUP, I2P_SAM_GENERATE_DESTINATION_PARAM, I2PSession::Instance, SAM::StreamSessionAdapter::destGenerate, SAM::FullDestination::pub, SAM::FullDestination::priv, I2PSession::GenerateB32AddressFromDestination, GetConfigFile, nNodeLifespan, GetArg, fUseFastIndex, nMinerSleep, nDerivationMethodIndex, SelectParamsFromCommandLine, mapArgs, SoftSetBoolArg, LogPrintf, mapMultiArgs, fEnableInstantX, SoftSetArg, fDebug, fDebugSmsg, fNoSmsg, _, fServer, fPrintToConsole, fPrintToDebugLog, fLogTimestamps, nConnectTimeout, ParseMoney, nTransactionFee, MIN_TX_FEE, fConfChange, fMinimizeCoinAge, nMinimumInputValue, ECC_Start, InitSanityCheck, GetDataDir, ShrinkDebugFile, FormatFullVersion, CLIENT_DATE, DateTimeStrFormat, GetTime, GetDefaultDataDir, sporkManager, CSporkManager::SetPrivKey, nStormnodeMinProtocol, SER_DISK, CAutoFile::IsNull, mempool, CTxMemPool::ReadFeeEstimates, fFeeEstimatesInitialized, CClientUIInterface::InitMessage, bitdb, CDBEnv::Open, CWalletDB::Recover, CDBEnv::Verify, CDBEnv::RECOVER_OK, CDBEnv::RECOVER_FAIL, RegisterNodeSignals, GetNodeSignals, ParseNetwork, NET_TOR, fOnlyTor, NET_UNROUTABLE, NET_MAX, SetLimited, CNetAddr::IsValid, IsLimited, NET_IPV4, SetProxy, NET_IPV6, SetNameProxy, SetReachable, fNoListen, fDiscover, fNameLookup, Lookup, GetListenPort, AddLocal, LOCAL_MANUAL, nReserveBalance, AddOneShot, txdb, CTxDB::LoadBlockIndex, PrintBlockTree, nCoinCacheSize, GetTimeMillis, LoadBlockIndex, UnloadBlockIndex, pcoinsTip, pblocktree, fReindex, CBlockTreeDB::WriteReindexing, mapBlockIndex, Params, InitBlockIndex, fTxIndex, fRequestShutdown, hash, base_uint< BITS >::ToString, CBlock::ReadFromDisk, CBlock::BuildMerkleTree, CBlock::ToString, CWallet::LoadWallet, DB_LOAD_OK, DB_CORRUPT, DB_NONCRITICAL_ERROR, DB_TOO_NEW, DB_NEED_REWRITE, FEATURE_LATEST, CWallet::SetMinVersion, CWallet::SetMaxVersion, RandAddSeedPerfmon, CWallet::GetKeyFromPool, CWallet::SetDefaultKey, CWallet::SetAddressBookName, CWallet::vchDefaultKey, CPubKey::GetID, CWallet::SetBestChain, pindexBest, RegisterWallet, pindexGenesisBlock, CWalletDB::ReadBestBlock, CBlockLocator::GetBlockIndex, nBestHeight, CBlockIndex::nHeight, CWallet::ScanForWalletTransactions, nWalletDBUpdated, ThreadImport, MilliSleep, CAddrDB::Read, addrman, snodeman, CStormnodeMan::CheckAndRemove, CStormnodeMan::ToString, SecureMsgStart, CheckDiskSpace, CStormnodeDB::Read, CStormnodeDB::FileError, CStormnodeDB::Ok, CStormnodeDB::IncorrectFormat, CBudgetDB::Read, budget, CBudgetDB::FileError, CBudgetDB::Ok, CBudgetDB::IncorrectFormat, CBudgetManager::ResetSync, CBudgetManager::ClearSeen, CStormnodePaymentDB::Read, stormnodePayments, CStormnodePaymentDB::FileError, CStormnodePaymentDB::Ok, CStormnodePaymentDB::IncorrectFormat, fStormNode, strStormNodeAddr, strStormNodePrivKey, sandStormSigner, CSandStormSigner::SetKey, activeStormnode, CActiveStormnode::pubKeyStormnode, strBudgetMode, LOCK, CWallet::cs_wallet, stormnodeConfig, CStormnodeConfig::getEntries, CStormnodeConfig::CStormnodeEntry::getTxHash, CStormnodeConfig::CStormnodeEntry::getOutputIndex, base_uint< BITS >::SetHex, CWallet::LockCoin, nLiquidityProvider, sandStormPool, CSandstormPool::SetMinBlockSpacing, fEnableSandstorm, fSandstormMultiSession, nSandstormRounds, nAnonymizeDarkSilkAmount, nInstantXDepth, fLiteMode, CSandstormPool::InitDenominations, CSandstormPool::InitCollateralAddress, ThreadCheckSandStormPool, CBlock::RebuildAddressIndex, CBlockIndex::pprev, CWallet::setKeyPool, CWallet::mapWallet, CWallet::mapAddressBook, StartNode, InitRPCMining, StartRPCThreads, ThreadStakeMiner, CWallet::ReacceptWalletTransactions, ThreadFlushWalletDB, CWallet::strWalletFile.
Referenced by AppInit, main.