instantx.h
INSTANTX_SIGNATURES_REQUIRED
Referenced by ProcessMessageInstantX, ProcessConsensusVote, CMerkleTx::GetDepthInMainChain, GetInputAgeIX, GetIXConfirmations.
INSTANTX_SIGNATURES_TOTAL
Referenced by DoConsensusVote, ProcessConsensusVote, CTransactionLock::SignaturesValid.
map<uint256, CTransaction> mapTxLockReq
Referenced by ProcessMessageInstantX, ProcessConsensusVote, CleanTransactionLocksList, CWalletTx::RelayWalletTransaction.
map<uint256, CTransaction> mapTxLockReqRejected
Referenced by ProcessMessageInstantX, ProcessConsensusVote, CleanTransactionLocksList.
map<uint256, CConsensusVote> mapTxLockVote
Referenced by ProcessMessageInstantX, DoConsensusVote, CleanTransactionLocksList.
map<uint256, CTransactionLock> mapTxLocks
Referenced by ProcessMessageInstantX, CreateNewLock, ProcessConsensusVote, CheckForConflictingLocks, CleanTransactionLocksList, CMerkleTx::GetTransactionLockSignatures, CMerkleTx::IsTransactionLockTimedOut, GetInputAgeIX, GetIXConfirmations.
std::map<COutPoint, uint256> mapLockedInputs
Referenced by CBlock::CheckBlock, ProcessMessageInstantX, ProcessConsensusVote, CheckForConflictingLocks, CleanTransactionLocksList, AcceptToMemoryPool, AcceptableInputs.
int nCompleteTXLocks
Referenced by ProcessConsensusVote, OverviewPage::setBalance, TransactionRecord::updateStatus, TransactionRecord::statusUpdateNeeded, WalletModel::pollBalanceChanged.
int64_t CreateNewLock(CTransaction tx)
References CTransaction::vin, GetInputAge, LogPrintf, CTransaction::GetHash, base_uint< BITS >::ToString, pindexBest, CBlockIndex::nHeight, mapTxLocks, CTransactionLock::nBlockHeight, GetTime.
Referenced by ProcessMessageInstantX, CWalletTx::RelayWalletTransaction.
bool IsIXTXValid(const CTransaction &txCollateral)
References CTransaction::vout, CTransaction::nLockTime, CTxOut::nValue, CTransaction::vin, hash, GetTransaction, CTxIn::prevout, COutPoint::hash, COutPoint::n, GetSporkValue, CTransaction::ToString.
Referenced by ProcessMessageInstantX.
bool CheckForConflictingLocks(CTransaction &tx)
References CTransaction::vin, mapLockedInputs, CTxIn::prevout, CTransaction::GetHash, LogPrintf, base_uint< BITS >::ToString, mapTxLocks, GetTime.
Referenced by ProcessMessageInstantX, ProcessConsensusVote.
void ProcessMessageInstantX(CNode *pfrom, std::string &strCommand, CDataStream &vRecv)
References fLiteMode, IsSporkActive, stormnodeSync, CStormnodeSync::IsBlockchainSynced, MSG_TXLOCK_REQUEST, CNode::AddInventoryKnown, mapTxLockReq, mapTxLockReqRejected, IsIXTXValid, CTxOut::scriptPubKey, CScript::IsNormalPaymentScript, CScript::IsUnspendable, LogPrintf, CreateNewLock, state, LOCK, cs_main, AcceptToMemoryPool, mempool, RelayInv, DoConsensusVote, CNode::addr, CService::ToString, CNode::cleanSubVer, mapLockedInputs, CTxIn::prevout, COutPoint::GetHash, mapTxLocks, INSTANTX_SIGNATURES_REQUIRED, CheckForConflictingLocks, ReprocessBlocks, MSG_TXLOCK_VOTE, mapTxLockVote, ProcessConsensusVote, mapUnknownVotes, GetTime, GetAverageVoteTime.
void DoConsensusVote(CTransaction &tx, int64_t nBlockHeight)
References fStormNode, snodeman, CStormnodeMan::GetStormnodeRank, activeStormnode, CActiveStormnode::vin, INSTANTX_SIGNATURES_TOTAL, CConsensusVote::vinStormnode, CConsensusVote::txHash, CTransaction::GetHash, CConsensusVote::nBlockHeight, CConsensusVote::Sign, LogPrintf, CConsensusVote::SignatureValid, mapTxLockVote, CConsensusVote::GetHash, MSG_TXLOCK_VOTE, RelayInv.
Referenced by ProcessMessageInstantX.
bool ProcessConsensusVote(CNode *pnode, CConsensusVote &ctx)
References snodeman, CStormnodeMan::GetStormnodeRank, CConsensusVote::vinStormnode, CConsensusVote::nBlockHeight, CStormnodeMan::Find, CStormnode::addr, CService::ToString, CStormnodeMan::AskForSN, INSTANTX_SIGNATURES_TOTAL, CConsensusVote::GetHash, base_uint< BITS >::ToString, CConsensusVote::SignatureValid, LogPrintf, mapTxLocks, CConsensusVote::txHash, CTransactionLock::nBlockHeight, GetTime, pwalletMain, CWallet::mapRequestCount, INSTANTX_SIGNATURES_REQUIRED, mapTxLockReq, CheckForConflictingLocks, CWallet::UpdatedTransaction, nCompleteTXLocks, mapLockedInputs, CTxIn::prevout, mapTxLockReqRejected, ReprocessBlocks.
Referenced by ProcessMessageInstantX.
void CleanTransactionLocksList()
References pindexBest, mapTxLocks, GetTime, LogPrintf, mapTxLockReq, CTransaction::vin, mapLockedInputs, CTxIn::prevout, mapTxLockReqRejected, mapTxLockVote, CConsensusVote::GetHash.
Referenced by ThreadCheckSandStormPool.
int64_t GetAverageVoteTime()
References mapUnknownVotes, total.
Referenced by ProcessMessageInstantX.