kernel.cpp
int64_t GetWeight(int64_t nIntervalBeginning, int64_t nIntervalEnd)
References nStakeMinAge.
Referenced by CWallet::CreateCoinStake.
static bool GetLastStakeModifier(const CBlockIndex *pindex, uint64_t &nStakeModifier, int64_t &nModifierTime)
static int64_t GetStakeModifierSelectionIntervalSection(int nSection)
static int64_t GetStakeModifierSelectionInterval()
static bool SelectBlockFromCandidates(vector< pair< int64_t, uint256 > > &vSortedByTimestamp, map< uint256, const CBlockIndex * > &mapSelectedBlocks, int64_t nSelectionIntervalStop, uint64_t nStakeModifierPrev, const CBlockIndex **pindexSelected)
bool ComputeNextStakeModifier(const CBlockIndex *pindexPrev, uint64_t &nStakeModifier, bool &fGeneratedStakeModifier)
References DateTimeStrFormat, nModifierInterval, CBlockIndex::GetBlockTime, CBlockIndex::GetBlockHash, CBlockIndex::pprev, CBlockIndex::nHeight, CBlockIndex::GetStakeEntropyBit, LogAcceptCategory, CBlockIndex::IsProofOfStake, PAIRTYPE, LogPrintf.
Referenced by CBlock::AddToBlockIndex.
uint256 ComputeStakeModifierV2(const CBlockIndex *pindexPrev, const uint256 &kernel)
References SER_GETHASH, CBlockIndex::bnStakeModifierV2, Hash, CDataStream::begin, CDataStream::end.
Referenced by CBlock::AddToBlockIndex.
bool CheckStakeKernelHash(CBlockIndex *pindexPrev, unsigned int nBits, unsigned int nTimeBlockFrom, const CTransaction &txPrev, const COutPoint &prevout, unsigned int nTimeTx, uint256 &hashProofOfStake, uint256 &targetProofOfStake, bool fPrintProofOfStake)
References CTransaction::nTime, CBigNum::SetCompact, CTransaction::vout, COutPoint::n, CBigNum::getuint256, CBlockIndex::nStakeModifier, CBlockIndex::bnStakeModifierV2, CBlockIndex::nHeight, CBlockIndex::nTime, SER_GETHASH, COutPoint::hash, Hash, CDataStream::begin, CDataStream::end, LogPrintf, DateTimeStrFormat, base_uint< BITS >::ToString, fDebug.
Referenced by CheckProofOfStake, CheckKernel.
bool CheckProofOfStake(CBlockIndex *pindexPrev, const CTransaction &tx, unsigned int nBits, uint256 &hashProofOfStake, uint256 &targetProofOfStake)
References CTransaction::IsCoinStake, CTransaction::GetHash, base_uint< BITS >::ToString, CTransaction::vin, txdb, CTransactionPoS::ReadFromDisk, CTxIn::prevout, CTransaction::DoS, VerifySignature, SCRIPT_VERIFY_NONE, CBlock::ReadFromDisk, CTxIndex::pos, CDiskTxPos::nFile, CDiskTxPos::nBlockPos, fDebug, IsConfirmedInNPrevBlocks, nStakeMinConfirmations, CheckStakeKernelHash, CBlockHeader::GetBlockTime, CTransaction::nTime.
Referenced by CBlock::AcceptBlock, CheckStake.
bool CheckCoinStakeTimestamp(int nHeight, int64_t nTimeBlock, int64_t nTimeTx)
Referenced by CBlock::AcceptBlock.
bool CheckKernel(CBlockIndex *pindexPrev, unsigned int nBits, int64_t nTime, const COutPoint &prevout, int64_t *pBlockTime)
References txdb, CTransactionPoS::ReadFromDisk, CBlock::ReadFromDisk, CTxIndex::pos, CDiskTxPos::nFile, CDiskTxPos::nBlockPos, IsConfirmedInNPrevBlocks, nStakeMinConfirmations, CBlockHeader::GetBlockTime, CheckStakeKernelHash.
Referenced by checkkernel, CWallet::CreateCoinStake.