leveldbwrapper.h
void HandleError(const leveldb::Status &status)
References LogPrintf.
Referenced by CLevelDBWrapper::CLevelDBWrapper, CLevelDBWrapper::WriteBatch, CLevelDBWrapper::Read, CLevelDBWrapper::Exists.