leveldbwrapper.cpp
void HandleError(const leveldb::Status &status)
References LogPrintf.
Referenced by CLevelDBWrapper::CLevelDBWrapper, CLevelDBWrapper::WriteBatch, CLevelDBWrapper::Read, CLevelDBWrapper::Exists.
static leveldb::Options GetOptions(size_t nCacheSize)