lz4.h
LZ4_VERSION_MAJOR
LZ4_VERSION_MINOR
LZ4_VERSION_RELEASE
LZ4_MAX_INPUT_SIZE
Referenced by LZ4_compress_generic.
LZ4_COMPRESSBOUND
Referenced by LZ4_compressBound.
int LZ4_compress(const char *source, char *dest, int inputSize)
References ALLOCATOR, HASHNBCELLS4, MEMORY_USAGE, LZ4_64KLIMIT, LZ4_compress_generic, source, notLimited, byU16, noPrefix, byU32, byPtr, FREEMEM.
Referenced by SecureMsgEncrypt.
int LZ4_decompress_safe(const char *source, char *dest, int inputSize, int maxOutputSize)
References LZ4_decompress_generic, endOnInputSize, noPrefix, full.
Referenced by LZ4_uncompress_unknownOutputSize, SecureMsgDecrypt.
int LZ4_compressBound(int isize)
References LZ4_COMPRESSBOUND.
Referenced by SecureMsgEncrypt.
int LZ4_compress_limitedOutput(const char *source, char *dest, int inputSize, int maxOutputSize)
References ALLOCATOR, HASHNBCELLS4, MEMORY_USAGE, LZ4_64KLIMIT, LZ4_compress_generic, source, limited, byU16, noPrefix, byU32, byPtr, FREEMEM.
int LZ4_decompress_fast(const char *source, char *dest, int originalSize)
References LZ4_decompress_generic, endOnOutputSize, noPrefix, full, withPrefix.
Referenced by LZ4_uncompress.
int LZ4_decompress_safe_partial(const char *source, char *dest, int inputSize, int targetOutputSize, int maxOutputSize)
References LZ4_decompress_generic, endOnInputSize, noPrefix, partial.
int LZ4_sizeofState(void)
References MEMORY_USAGE.
Referenced by LZ4_compress_withState, LZ4_compress_limitedOutput_withState.
int LZ4_compress_withState(void *state, const char *source, char *dest, int inputSize)
References MEM_INIT, LZ4_sizeofState, LZ4_64KLIMIT, LZ4_compress_generic, notLimited, byU16, noPrefix, byU32, byPtr.
int LZ4_compress_limitedOutput_withState(void *state, const char *source, char *dest, int inputSize, int maxOutputSize)
References MEM_INIT, LZ4_sizeofState, LZ4_64KLIMIT, LZ4_compress_generic, limited, byU16, noPrefix, byU32, byPtr.
void* LZ4_create(const char *inputBuffer)
References ALLOCATOR, LZ4_init.
int LZ4_compress_continue(void *LZ4_Data, const char *source, char *dest, int inputSize)
References LZ4_compress_generic, notLimited, byU32, withPrefix.
int LZ4_compress_limitedOutput_continue(void *LZ4_Data, const char *source, char *dest, int inputSize, int maxOutputSize)
References LZ4_compress_generic, limited, byU32, withPrefix.
char* LZ4_slideInputBuffer(void *LZ4_Data)
References LZ4_Data_Structure::nextBlock, LZ4_Data_Structure::bufferStart, KB, LZ4_Data_Structure::base, HASHNBCELLS4, LZ4_Data_Structure::hashTable.
int LZ4_free(void *LZ4_Data)
References FREEMEM.
int LZ4_sizeofStreamState(void)
int LZ4_resetStreamState(void *state, const char *inputBuffer)
References LZ4_init.
int LZ4_decompress_safe_withPrefix64k(const char *source, char *dest, int inputSize, int maxOutputSize)
References LZ4_decompress_generic, endOnInputSize, withPrefix, full.
int LZ4_decompress_fast_withPrefix64k(const char *source, char *dest, int outputSize)
References LZ4_decompress_generic, endOnOutputSize, withPrefix, full.
int LZ4_uncompress(const char *source, char *dest, int outputSize)
References LZ4_decompress_fast.
int LZ4_uncompress_unknownOutputSize(const char *source, char *dest, int isize, int maxOutputSize)
References LZ4_decompress_safe.