main.h
GetMinFee_mode
typedef std::map<uint256, CBlockIndex*, BlockHasher> BlockMap
typedef std::map<uint256, std::pair<CTxIndex, CTransaction> > MapPrevTx
const double MIN_FEE
Fees smaller than this (in satoshi) are considered zero fee (for transaction creation)
const CAmount STORMNODE_COLLATERAL
const int STORMNODE_PAYMENT_START
const int TESTNET_STORMNODE_PAYMENT_START
const CAmount SANDSTORM_COLLATERAL
const CAmount SANDSTORM_POOL_MAX
const CAmount STATIC_POS_REWARD
const int MAX_BLOCKS_IN_TRANSIT_PER_PEER
Number of blocks that can be requested at any given time from a single peer.
const unsigned int BLOCK_DOWNLOAD_TIMEOUT
Timeout in seconds before considering a block download peer unresponsive.
const unsigned int MAX_BLOCK_SIZE_GEN
The maximum size for mined blocks.
const unsigned int DEFAULT_BLOCK_PRIORITY_SIZE
Default for -blockprioritysize, maximum space for zero/low-fee transactions.
const unsigned int MAX_STANDARD_TX_SIZE
The maximum size for transactions we're willing to relay/mine.
const unsigned int MAX_BLOCK_SIGOPS
The maximum allowed number of signature check operations in a block (network rule)
const unsigned int MAX_P2SH_SIGOPS
Maxiumum number of signature check operations in an IsStandard() P2SH script.
const unsigned int MAX_TX_SIGOPS
The maximum number of sigops we're willing to relay/mine in a single tx.
const unsigned int MAX_ORPHAN_TRANSACTIONS
The maximum number of orphan transactions kept in memory.
const unsigned int DEFAULT_MAX_ORPHAN_BLOCKS
Default for -maxorphanblocksmib, maximum memory used by orphan blocks.
const unsigned int MAX_INV_SZ
The maximum number of entries in an 'inv' protocol message.
const unsigned int MAX_REJECT_MESSAGE_LENGTH
Maximum length of reject messages.
const unsigned int LOCKTIME_THRESHOLD
Threshold for nLockTime: below this value it is interpreted as block number, otherwise as UNIX timestamp.
const unsigned int POW_TARGET_SPACING
const unsigned int POS_TARGET_SPACING
const unsigned int DATABASE_WRITE_INTERVAL
Time to wait (in seconds) between writing blockchain state to disk.
const unsigned char REJECT_MALFORMED
"reject" message codes
const unsigned char REJECT_INVALID
const unsigned char REJECT_OBSOLETE
const unsigned char REJECT_DUPLICATE
const unsigned char REJECT_NONSTANDARD
const unsigned char REJECT_DUST
const unsigned char REJECT_INSUFFICIENTFEE
const unsigned char REJECT_CHECKPOINT
CScript COINBASE_FLAGS
Referenced by CreateNewBlock, IncrementExtraNonce, getblocktemplate.
CCriticalSection cs_main
Referenced by CBlock::AcceptBlock, IsInitialBlockDownload, Shutdown, ProcessMessageInstantX, CreateNewBlock, CheckWork, CheckStake, ClientModel::getNumBlocks, ClientModel::getLastBlockDate, ClientModel::updateTimer, ClientModel::updateSnTimer, PeerTablePriv::refreshPeers, TransactionDesc::toHTML, TransactionRecord::updateStatus, TransactionRecord::statusUpdateNeeded, TransactionTablePriv::refreshWallet, TransactionTablePriv::updateWallet, TransactionTablePriv::index, TransactionTablePriv::describe, WalletModel::pollBalanceChanged, WalletModel::sendCoins, WalletModel::getOutputs, WalletModel::listCoins, WalletModel::isLockedCoin, WalletModel::lockCoin, WalletModel::unlockCoin, WalletModel::listLockedCoins, importprivkey, importaddress, CRPCTable::execute, scanforalltxns, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::CheckFinalTransaction, CSandstormPool::IsCollateralValid, CSandstormPool::SendSandstormDenominate, SecureMsgScanBlockChain, CStormnodeSync::IsBlockchainSynced, CStormnodeBroadcast::CheckInputsAndAdd, CWallet::SyncTransaction, CWallet::ScanForWalletTransactions, CWallet::ReacceptWalletTransactions, CWallet::GetBalance, CWallet::GetAnonymizableBalance, CWallet::GetDenominatedBalance, CWallet::GetUnconfirmedBalance, CWallet::GetImmatureBalance, CWallet::GetWatchOnlyBalance, CWallet::GetWatchOnlyStake, CWallet::GetUnconfirmedWatchOnlyBalance, CWallet::GetImmatureWatchOnlyBalance, CWallet::AvailableCoins, CWallet::AvailableCoinsForStaking, CWallet::GetStake, CWallet::GetNewMint, CWallet::GetStakeWeight, CWallet::CommitTransaction, CWallet::AddReserveKey, CWallet::GetAllReserveKeys.
CTxMemPool mempool
Referenced by Reorganize, Shutdown, AppInit2, ProcessMessageInstantX, CMerkleTx::GetDepthInMainChain, CMerkleTx::AcceptToMemoryPool, CWalletTx::AcceptWalletTransaction, GetTransaction, CreateNewBlock, StopNode, getrawmempool, getmininginfo, getstakinginfo, getworkex, getwork, getblocktemplate, sendrawtransaction, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::SendSandstormDenominate, CStormnodeBroadcast::CheckInputsAndAdd, CWallet::ReacceptWalletTransactions.
std::map<uint256, CBlockIndex*> mapBlockIndex
std::set<std::pair<COutPoint, unsigned int> > setStakeSeen
Referenced by CTxDB::LoadBlockIndex.
CBlockIndex* pindexGenesisBlock
int nStakeMinConfirmations
Referenced by CheckProofOfStake, CheckKernel, CWallet::AvailableCoinsForStaking, CWallet::GetStakeWeight.
unsigned int nStakeMinAge
Referenced by GetWeight, CWallet::AvailableCoinsForStaking, CWallet::CreateCoinStake.
unsigned int nNodeLifespan
Referenced by AppInit2.
int nCoinbaseMaturity
int nBestHeight
uint256 nBestChainTrust
Referenced by CTxDB::LoadBlockIndex.
uint256 nBestInvalidTrust
Referenced by InvalidChainFound, CTxDB::LoadBlockIndex.
uint256 hashBestChain
Referenced by CBlock::AcceptBlock, InvalidChainFound, CCoinsViewDB::GetBestBlock, CheckWork, CheckStake, getBlockHash, getbestblockhash, getblockbynumber, dumpwallet, listsinceblock, scanforalltxns, scanforstealthtxns, CTxDB::LoadBlockIndex.
CBlockIndex* pindexBest
Referenced by CBlock::SetBestChain.
uint64_t nLastBlockTx
Referenced by getmininginfo, getstakinginfo.
uint64_t nLastBlockSize
Referenced by getmininginfo, getstakinginfo.
int64_t nLastCoinStakeSearchInterval
Referenced by getmininginfo, getstakinginfo.
const std::string strMessageMagic
Referenced by verifymessage, signmessage, CSandStormSigner::SignMessage, CSandStormSigner::VerifyMessage.
int64_t nTimeBestReceived
Referenced by CWallet::ResendWalletTransactions.
bool fImporting
Referenced by ClientModel::isImporting, CStormnodeSync::IsBlockchainSynced.
bool fReindex
Referenced by AppInit2, CStormnodeSync::IsBlockchainSynced.
std::map<uint256, COrphanBlock*> mapOrphanBlocks
bool fTxIndex
Referenced by AppInit2.
unsigned int nCoinCacheSize
Referenced by AppInit2.
bool fUseFastIndex
Referenced by AppInit2.
unsigned int nDerivationMethodIndex
Referenced by AppInit2, CWallet::EncryptWallet.
bool fMinimizeCoinAge
Referenced by AppInit2.
bool fLargeWorkForkFound
bool fLargeWorkInvalidChainFound
std::map<uint256, int64_t> mapRejectedBlocks
CFeeRate minRelayTxFee
Fees smaller than this (in satoshis) are considered zero fee (for relaying and mining) We are ~xxx times smaller then bitcoin now (2016-01-11), set minRelayTxFee only 10 times higher so it's still 10 times lower comparing to bitcoin.
Referenced by CoinControlDialog::updateLabels.
const uint64_t nMinDiskSpace
CCoinsViewCache* pcoinsTip
Global variable that points to the active CCoinsView (protected by cs_main)
Referenced by Shutdown, AppInit2.
CBlockTreeDB* pblocktree
Global variable that points to the active block tree (protected by cs_main)
Referenced by Shutdown, AppInit2.
bool GetNodeStateStats(NodeId nodeid, CNodeStateStats &stats)
Get statistics from node state
References LOCK, CNodeStateStats::nMisbehavior, CNodeStateStats::nSyncHeight, CNodeStateStats::nCommonHeight, CNodeStateStats::vHeightInFlight.
Referenced by PeerTablePriv::refreshPeers.
void RegisterWallet(CWalletInterface *pwalletIn)
Register a wallet to receive updates from core
References CWalletInterface::SyncTransaction, CWalletInterface::EraseFromWallet, CWalletInterface::UpdatedTransaction, CWalletInterface::SetBestChain, CWalletInterface::Inventory, CWalletInterface::ResendWalletTransactions.
Referenced by AppInit2.
void UnregisterWallet(CWalletInterface *pwalletIn)
Unregister a wallet from core
References CWalletInterface::ResendWalletTransactions, CWalletInterface::Inventory, CWalletInterface::SetBestChain, CWalletInterface::UpdatedTransaction, CWalletInterface::EraseFromWallet, CWalletInterface::SyncTransaction.
void UnregisterAllWallets()
Unregister all wallets from core
Referenced by Shutdown.
void SyncWithWallets(const CTransaction &tx, const CBlock *pblock=NULL, bool fConnect=true)
Push an updated transaction to all registered wallets
Referenced by CBlock::DisconnectBlock, CBlock::ConnectBlock, AcceptToMemoryPool.
void ResendWalletTransactions(bool fForce=false)
Ask wallets to resend their transactions
Referenced by SendMessages, resendtx.
void RegisterNodeSignals(CNodeSignals &nodeSignals)
Register with a network node to receive its signals
References CNodeSignals::ProcessMessages, ProcessMessages, CNodeSignals::SendMessages, SendMessages, CNodeSignals::InitializeNode, CNodeSignals::FinalizeNode.
Referenced by AppInit2.
void UnregisterNodeSignals(CNodeSignals &nodeSignals)
Unregister a network node
References CNodeSignals::ProcessMessages, ProcessMessages, CNodeSignals::SendMessages, SendMessages, CNodeSignals::InitializeNode, CNodeSignals::FinalizeNode.
Referenced by Shutdown.
void PushGetBlocks(CNode *pnode, CBlockIndex *pindexBegin, uint256 hashEnd)
References CNode::pindexLastGetBlocksBegin, CNode::hashLastGetBlocksEnd, CNode::PushMessage.
Referenced by ProcessBlock, SendMessages.
bool ProcessBlock(CNode *pfrom, CBlock *pblock)
References AssertLockHeld, CBlockHeader::GetHash, base_uint< BITS >::ToString, CBlock::IsProofOfStake, CBlock::GetProofOfStake, CBlockHeader::hashPrevBlock, Checkpoints::AutoSelectSyncCheckpoint, CBlockHeader::GetBlockTime, CBlockIndex::nTime, CNode::Misbehaving, CNode::nVersion, state, CBlock::CheckBlock, LogPrintf, SER_DISK, COrphanBlock::vchBlock, CDataStream::begin, CDataStream::end, COrphanBlock::hashBlock, hash, COrphanBlock::hashPrev, COrphanBlock::stake, PushGetBlocks, IsInitialBlockDownload, CNode::AskFor, MSG_BLOCK, WantedByOrphan, CBlock::AcceptBlock, CBlock::BuildMerkleTree, base_uint< BITS >::size.
Referenced by LoadExternalBlockFile, CheckWork, CheckStake, submitblock.
bool CheckDiskSpace(uint64_t nAdditionalBytes=0)
References GetDataDir, _, strMiscWarning, LogPrintf, uiInterface, CClientUIInterface::ThreadSafeMessageBox, CClientUIInterface::MSG_ERROR, StartShutdown.
Referenced by CBlock::AcceptBlock, AppInit2, CSandstormPool::SendSandstormDenominate.
void UnloadBlockIndex()
Unload database information.
Referenced by AppInit2.
bool LoadBlockIndex(bool fAllowNew=true)
Load the block tree and coins database from disk */.
References LOCK, TestNet, txdb, CTxDB::LoadBlockIndex, Params, CChainParams::GenesisBlock, CBlock::WriteToDisk, CBlock::AddToBlockIndex.
Referenced by AppInit2.
bool InitBlockIndex()
Initialize a new block tree database + block data on disk.
Referenced by AppInit2.
void PrintBlockTree()
References AssertLockHeld, CBlockIndex::pprev, LogPrintf, CBlock::ReadFromDisk, CBlockIndex::nHeight, CBlockIndex::nFile, CBlockIndex::nBlockPos, CBlockHeader::GetHash, base_uint< BITS >::ToString, CBlockHeader::nBits, DateTimeStrFormat, CBlockHeader::GetBlockTime, FormatMoney, CBlockIndex::nMint, CBlock::vtx.
Referenced by AppInit2.
bool ProcessMessages(CNode *pfrom)
References CNode::vRecvGetData, CNode::vRecvMsg, CNode::fDisconnect, CNode::nSendSize, SendBufferSize, CNetMessage::complete, CNetMessage::hdr, CMessageHeader::pchMessageStart, Params, MESSAGE_START_SIZE, LogPrintf, CMessageHeader::IsValid, CMessageHeader::GetCommand, CMessageHeader::nMessageSize, CNetMessage::vRecv, Hash, CDataStream::begin, CMessageHeader::nChecksum, CNetMessage::nTime, PrintExceptionContinue.
Referenced by RegisterNodeSignals, UnregisterNodeSignals.
bool SendMessages(CNode *pto, bool fSendTrickle)
References TRY_LOCK, CNode::nVersion, CNode::fPingQueued, CNode::nPingNonceSent, CNode::nPingUsecStart, GetTimeMicros, GetRandBytes, CNode::PushMessage, CNode::fStartSync, PushGetBlocks, IsInitialBlockDownload, ResendWalletTransactions, GetTime, LOCK, cs_vNodes, vNodes, CNode::setAddrKnown, mruset< T >::clear, fNoListen, GetLocalAddress, CNode::addr, CNetAddr::IsRoutable, CNode::PushAddress, CNode::vAddrToSend, mruset< T >::insert, CNode::cs_inventory, CNode::vInventoryToSend, CNode::setInventoryKnown, mruset< T >::count, CInv::type, MSG_TX, GetRandHash, CInv::hash, Hash, BEGIN, END, CNode::GetId, CNode::fDisconnect, LogPrintf, MSG_BLOCK, hash, base_uint< BITS >::ToString, txdb, CNode::mapAskFor, fDebug, CInv::ToString, mapAlreadyAskedFor, fSecMsgEnabled, SecureMsgSendData.
Referenced by RegisterNodeSignals, UnregisterNodeSignals.
void ThreadImport(std::vector< boost::filesystem::path > vImportFiles)
References RenameThread, LoadExternalBlockFile, GetDataDir, RenameOver.
Referenced by AppInit2.
bool CheckProofOfWork(uint256 hash, unsigned int nBits)
Referenced by CBlock::CheckBlock, CBlock::ReadFromDisk, CBlockTreeDB::LoadBlockIndexGuts.
unsigned int GetNextTargetRequired(const CBlockIndex *pindexLast, bool fProofOfStake)
References CBlockIndex::nHeight, Params, CChainParams::ProofOfWorkLimit, CBigNum::GetCompact, GetLastBlockIndex, CBlockIndex::pprev, CBlockIndex::GetBlockTime, CBigNum::SetCompact, CBlockIndex::nBits.
Referenced by CBlock::AcceptBlock, CreateNewBlock, checkkernel.
CAmount GetProofOfWorkReward(CAmount nFees)
References CBlockIndex::nHeight, FormatMoney.
Referenced by CBlock::ConnectBlock, CreateNewBlock, getsubsidy, getmininginfo.
bool IsConfirmedInNPrevBlocks(const CTxIndex &txindex, const CBlockIndex *pindexFrom, int nMaxDepth, int &nActualDepth)
References CBlockIndex::nHeight, CBlockIndex::pprev, CBlockIndex::nBlockPos, CTxIndex::pos, CDiskTxPos::nBlockPos, CBlockIndex::nFile, CDiskTxPos::nFile.
Referenced by CheckProofOfStake, CheckKernel, CTransactionPoS::ConnectInputs.
std::string GetWarnings(std::string strFor)
bool GetTransaction(const uint256 &hash, CTransaction &tx, uint256 &hashBlock)
Return transaction in tx, and if it was found inside a block, its hash is placed in hashBlock.
References LOCK, mempool, CTxMemPool::lookup, txdb, CTransactionPoS::ReadFromDisk, CBlock::ReadFromDisk, CTxIndex::pos, CDiskTxPos::nFile, CDiskTxPos::nBlockPos, CBlockHeader::GetHash, PAIRTYPE, CBlockIndex::pnext, CBlock::vtx, CTransaction::GetHash, hash.
Referenced by IsIXTXValid, GetInputAge, getTxTotalValue, getOutputs, getInputs, getTxFees, getrawtransaction, sendrawtransaction, searchrawtransactions, gettransaction, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::IsCollateralValid, CSandStormSigner::IsVinAssociatedWithPubkey, IsBudgetCollateralValid, CStormnodeBroadcast::CheckInputsAndAdd.
uint256 WantedByOrphan(const COrphanBlock *pblockOrphan)
References COrphanBlock::hashPrev.
Referenced by ProcessBlock.
const CBlockIndex* GetLastBlockIndex(const CBlockIndex *pindex, bool fProofOfStake)
References CBlockIndex::pprev, CBlockIndex::IsProofOfStake.
Referenced by GetNextTargetRequired, StatisticsPage::updateStatistics, GetDifficulty, getdifficulty, getmininginfo, getstakinginfo, getinfo.
void ThreadStakeMiner(CWallet *pwallet)
References SetThreadPriority, THREAD_PRIORITY_LOWEST, RenameThread, CCryptoKeyStore::IsLocked, nLastCoinStakeSearchInterval, MilliSleep, vNodes, IsInitialBlockDownload, pindexBest, CBlockIndex::GetBlockTime, GetTime, CreateNewBlock, THREAD_PRIORITY_NORMAL, CheckStake, nMinerSleep.
Referenced by AppInit2.
bool AcceptToMemoryPool(CTxMemPool &pool, CValidationState &state, CTransaction &tx, bool fLimitFree, bool *pfMissingInputs, bool ignoreFees=false)
(try to) add transaction to memory pool
References AssertLockHeld, CTransaction::CheckTransaction, CTransaction::IsCoinBase, CTransaction::DoS, CTransaction::IsCoinStake, TestNet, IsStandardTx, CTransaction::GetHash, CTxMemPool::exists, CTransaction::vin, mapLockedInputs, CTxIn::prevout, LOCK, CTxMemPool::cs, CTxMemPool::mapNextTx, txdb, CTxDB::ContainsTx, COutPoint::hash, CTransactionPoS::FetchInputs, base_uint< BITS >::ToString, AreInputsStandard, GetLegacySigOpCount, GetP2SHSigOpCount, CTransactionPoS::GetValueIn, CTransactionPoS::GetValueOut, GetSerializeSize, SER_NETWORK, GetMinFee, GMF_RELAY, MIN_RELAY_TX_FEE, GetTime, GetArg, CTransactionPoS::ConnectInputs, CTxMemPool::addUnchecked, SyncWithWallets, CTxMemPool::mapTx.
Referenced by Reorganize, ProcessMessageInstantX, CMerkleTx::AcceptToMemoryPool, CWalletTx::AcceptWalletTransaction, sendrawtransaction.
bool AcceptableInputs(CTxMemPool &pool, CValidationState &state, CTransaction &tx, bool fLimitFree, bool *pfMissingInputs, bool fRejectInsaneFee=false, bool isSSTX=false)
References AssertLockHeld, CTransaction::CheckTransaction, CTransaction::IsCoinBase, CTransaction::DoS, CTransaction::IsCoinStake, CTransaction::GetHash, CTxMemPool::exists, CTransaction::vin, mapLockedInputs, CTxIn::prevout, CValidationState::DoS, LOCK, CTxMemPool::cs, CTxMemPool::mapNextTx, txdb, CTxDB::ContainsTx, CTransactionPoS::FetchInputs, base_uint< BITS >::ToString, GetLegacySigOpCount, GetP2SHSigOpCount, CTransactionPoS::GetValueIn, CTransactionPoS::GetValueOut, GetSerializeSize, SER_NETWORK, GetMinFee, GMF_RELAY, MIN_RELAY_TX_FEE, GetTime, GetArg, CTransactionPoS::ConnectInputs.
Referenced by CSandstormPool::ProcessMessageSandstorm, CSandstormPool::SendSandstormDenominate, CStormnodeBroadcast::CheckInputsAndAdd.
CAmount GetBlockValue(int nBits, int nHeight, const CAmount &nFees)
Referenced by CreateNewBlock, CBudgetManager::FillBlockPayee, CStormnodePayments::FillBlockPayee.
bool FindTransactionsByDestination(const CTxDestination &dest, std::vector< uint256 > &vtxhash)
References LogPrintf, LOCK, txdb, CTxDB::ReadAddrIndex.
Referenced by searchrawtransactions.
int GetInputAge(CTxIn &vin)
References CTxIn::prevout, COutPoint::hash, GetTransaction, CBlockIndex::nHeight.
Referenced by CActiveStormnode::ManageStatus, CreateNewLock, GetInputAgeIX, CStormnodeBroadcast::CheckInputsAndAdd, CStormnode::GetStormnodeInputAge.
bool AbortNode(const std::string &msg, const std::string &userMessage="")
Abort with a message.
References strMiscWarning, LogPrintf, uiInterface, CClientUIInterface::ThreadSafeMessageBox, _, CClientUIInterface::MSG_ERROR, StartShutdown.
Referenced by CValidationState::Abort.
void Misbehaving(NodeId nodeid, int howmuch)
Increase a node's misbehavior score.
References LOCK, cs_vNodes, vNodes, CNode::GetId, CNode::nMisbehavior, GetArg, LogPrintf, CNode::addrName.
Referenced by ProcessSpork, CBudgetManager::ProcessMessage, CStormnodePayments::ProcessMessageStormnodePayments, CStormnodePaymentWinner::IsValid, CStormnodeMan::ProcessMessage.
CAmount GetStormnodePayment(int nHeight, CAmount blockValue)
Referenced by CreateNewBlock, getblocktemplate, CStormnodePayments::FillBlockPayee, CStormnodeBlockPayees::IsTransactionValid.
int GetInputAgeIX(uint256 nTXHash, CTxIn &vin)
References GetInputAge, mapTxLocks, INSTANTX_SIGNATURES_REQUIRED, nInstantXDepth.
Referenced by CBudgetManager::SubmitFinalBudget.
int GetIXConfirmations(uint256 nTXHash)
References mapTxLocks, INSTANTX_SIGNATURES_REQUIRED, nInstantXDepth.
Referenced by WalletTxToJSON, IsBudgetCollateralValid.
bool DisconnectBlocksAndReprocess(int blocks)
References LogPrintf.
void FlushStateToDisk()
References state, FlushStateToDisk, FLUSH_STATE_ALWAYS.
Referenced by Shutdown, FlushStateToDisk.
boost::filesystem::path GetBlockPosFilename(const CDiskBlockPos &pos, const char *prefix)
References GetDataDir, strprintf, CDiskBlockPos::nFile.
Referenced by OpenDiskFile.
FILE* OpenBlockFile(unsigned int nFile, unsigned int nBlockPos, const char *pszMode)
Referenced by AppendBlockFile, CBlock::ReadFromDisk, CTransactionPoS::ReadFromDisk.
FILE* OpenBlockFile(const CDiskBlockPos &pos, bool fReadOnly=false)
References OpenDiskFile.
FILE* OpenDiskFile(const CDiskBlockPos &pos, const char *prefix, bool fReadOnly=false)
References CDiskBlockPos::IsNull, GetBlockPosFilename, LogPrintf, CDiskBlockPos::nPos.
Referenced by OpenBlockFile, OpenUndoFile.
FILE* AppendBlockFile(unsigned int &nFileRet)
References OpenBlockFile, MAX_SIZE.
Referenced by CBlock::WriteToDisk.
FILE* OpenUndoFile(const CDiskBlockPos &pos, bool fReadOnly=false)
References OpenDiskFile.
CAmount GetMinFee(const CTransaction &tx, unsigned int nBytes, bool fAllowFree, enum GetMinFee_mode mode)
References GMF_RELAY, MIN_RELAY_TX_FEE, MIN_TX_FEE, GMF_SEND, CTransaction::vout, CTxOut::nValue, MoneyRange.
Referenced by AcceptToMemoryPool, AcceptableInputs, CoinControlDialog::updateLabels.
bool AreInputsStandard(const CTransaction &tx, const MapPrevTx &mapInputs)
Check for standard transaction types mapInputs Map of previous transactions that have outputs we're spending True if all inputs (scriptSigs) use only standard transaction forms CTransaction::FetchInputs
References CTransaction::IsCoinBase, CTransaction::vin, prev, CTransactionPoS::GetOutputFor, CTxOut::scriptPubKey, Solver, ScriptSigArgsExpected, EvalScript, SCRIPT_VERIFY_NONE, TX_SCRIPTHASH.
Referenced by AcceptToMemoryPool.
unsigned int GetLegacySigOpCount(const CTransaction &tx)
Count ECDSA signature operations the old-fashioned (pre-0.6) way number of sigops this transaction's outputs will produce when spent CTransaction::FetchInputs
References CTransaction::vin, CTxIn::scriptSig, CScript::GetSigOpCount, CTransaction::vout, CTxOut::scriptPubKey.
Referenced by CBlock::ConnectBlock, CBlock::CheckBlock, AcceptToMemoryPool, AcceptableInputs, CreateNewBlock, getblocktemplate.
unsigned int GetP2SHSigOpCount(const CTransaction &tx, const MapPrevTx &mapInputs)
Count ECDSA signature operations in pay-to-script-hash inputs. mapInputs Map of previous transactions that have outputs we're spending maximum number of sigops required to validate this transaction's inputs CTransaction::FetchInputs
References CTransaction::IsCoinBase, CTransaction::vin, CTransactionPoS::GetOutputFor, CTxOut::scriptPubKey, CScript::IsPayToScriptHash, CScript::GetSigOpCount.
Referenced by CBlock::ConnectBlock, AcceptToMemoryPool, AcceptableInputs, CreateNewBlock, getblocktemplate.
bool IsStandardTx(const CTransaction &tx, std::string &reason)
Check for standard transaction types True if all outputs (scriptPubKeys) use only standard transaction forms
bool IsFinalTx(const CTransaction &tx, int nBlockHeight=0, int64_t nBlockTime=0)
References AssertLockHeld, CTransaction::nLockTime, nBestHeight, GetAdjustedTime, CTransaction::vin, CTxIn::IsFinal.
Referenced by CBlock::AcceptBlock, IsStandardTx, CreateNewBlock, TransactionRecord::updateStatus, getreceivedbyaddress, getreceivedbyaccount, GetAccountBalance, getbalance, ListReceived, CWallet::GetDenominatedBalance, CWallet::GetUnconfirmedBalance, CWallet::GetUnconfirmedWatchOnlyBalance, CWallet::AvailableCoins, CWallet::GetAddressBalances, CWalletTx::GetDenominatedCredit, CWalletTx::IsTrusted.