miner.h
CBlock* CreateNewBlock(CReserveKey &reservekey, bool fProofOfStake=false, CAmount *pFees=0)
References pindexBest, CBlockIndex::nHeight, CMutableTransaction::vin, CMutableTransaction::vout, CReserveKey::GetReservedKey, CPubKey::GetID, COINBASE_FLAGS, GetArg, MIN_TX_FEE, mapArgs, ParseMoney, GetNextTargetRequired, LOCK2, cs_main, mempool, CTxMemPool::cs, txdb, CTxMemPool::mapTx, CTransaction::IsCoinBase, CTransaction::IsCoinStake, IsFinalTx, CTransaction::vin, CTransactionPoS::ReadFromDisk, CTxIn::prevout, COutPoint::hash, LogPrintf, fDebug, COrphan::setDependsOn, COutPoint::n, CTransaction::vout, CTxIndex::GetDepthInMainChain, GetSerializeSize, SER_NETWORK, CTransactionPoS::GetValueOut, COrphan::dPriority, COrphan::dFeePerKb, GetLegacySigOpCount, CTransaction::nTime, GetAdjustedTime, CTransactionPoS::FetchInputs, CTransactionPoS::GetValueIn, GetP2SHSigOpCount, CTransactionPoS::ConnectInputs, CTransaction::GetHash, GetBoolArg, base_uint< BITS >::ToString, hash, COrphan::ptx, GetBlockValue, CBlockIndex::nBits, GetStormnodePayment, GetProofOfWorkReward, CBlockIndex::GetBlockHash, CBlockIndex::GetPastTimeLimit.
Referenced by ThreadStakeMiner, checkkernel, getworkex, getwork, getblocktemplate.
void IncrementExtraNonce(CBlock *pblock, CBlockIndex *pindexPrev, unsigned int &nExtraNonce)
Modify the extranonce in a block
References CBlockHeader::hashPrevBlock, CBlockIndex::nHeight, CBlock::vtx, COINBASE_FLAGS, CBlockHeader::hashMerkleRoot, CBlock::BuildMerkleTree.
Referenced by getworkex, getwork.
void FormatHashBuffers(CBlock *pblock, char *pmidstate, char *pdata, char *phash1)
Do mining precalculation
References CBlockHeader::nVersion, CBlockHeader::hashPrevBlock, CBlockHeader::hashMerkleRoot, CBlockHeader::nTime, CBlockHeader::nBits, CBlockHeader::nNonce, ByteReverse, SHA256Transform.
Referenced by getworkex, getwork.
bool CheckWork(CBlock *pblock, CWallet &wallet, CReserveKey &reservekey)
Check mined proof-of-work block
References CBlockHeader::GetHash, CBlockHeader::GetPoWHash, CBigNum::SetCompact, CBlockHeader::nBits, CBigNum::getuint256, CBlock::IsProofOfWork, base_uint< BITS >::GetHex, LogPrintf, CBlock::ToString, FormatMoney, CBlock::vtx, LOCK, cs_main, CBlockHeader::hashPrevBlock, hashBestChain, CReserveKey::KeepKey, CWallet::cs_wallet, CWallet::mapRequestCount, ProcessBlock.
Referenced by getworkex, getwork.
bool CheckStake(CBlock *pblock, CWallet &wallet)
Check mined proof-of-stake block
References CBlockHeader::GetHash, CBlock::IsProofOfStake, base_uint< BITS >::GetHex, CheckProofOfStake, mapBlockIndex, CBlockHeader::hashPrevBlock, CBlock::vtx, CBlockHeader::nBits, LogPrintf, CBlock::ToString, FormatMoney, CTransactionPoS::GetValueOut, LOCK, cs_main, hashBestChain, CWallet::cs_wallet, CWallet::mapRequestCount, ProcessBlock, CWallet::FixSpentCoins.
Referenced by ThreadStakeMiner.
void SHA256Transform(void *pstate, void *pinput, const void *pinit)
Base sha256 mining transform
References ByteReverse.
Referenced by FormatHashBuffers.