GUIUtil
QString GUIUtil::dateTimeStr(const QDateTime &date)
Referenced by dateTimeStr, TxViewDelegate::paint, TransactionDesc::toHTML.
QString GUIUtil::dateTimeStr(qint64 nTime)
References dateTimeStr.
QFont GUIUtil::darksilkAddressFont()
Referenced by AddressTableModel::data, setupAddressWidget, SendCoinsDialog::SendCoinsDialog, SignVerifyMessageDialog::SignVerifyMessageDialog.
void GUIUtil::setupAddressWidget(QLineEdit *widget, QWidget *parent)
References DarkSilkAddressValidator::MaxAddressLength, darksilkAddressFont.
Referenced by EditAddressDialog::EditAddressDialog, SendCoinsEntry::SendCoinsEntry, SendMessagesEntry::SendMessagesEntry, SignVerifyMessageDialog::SignVerifyMessageDialog.
void GUIUtil::setupAmountWidget(QLineEdit *widget, QWidget *parent)
bool GUIUtil::parseDarkSilkURI(const QUrl &uri, SendCoinsRecipient *out)
References SendCoinsRecipient::address, SendCoinsRecipient::amount, SendCoinsRecipient::label, DarkSilkUnits::parse, DarkSilkUnits::DRKSLK.
Referenced by parseDarkSilkURI, SendCoinsDialog::handleURI.
bool GUIUtil::parseDarkSilkURI(QString uri, SendCoinsRecipient *out)
References parseDarkSilkURI.
QString GUIUtil::HtmlEscape(const QString &str, bool fMultiLine)
Referenced by DEBUGConsole::message, HtmlEscape, GUIUtil::ToolTipToRichTextFilter::eventFilter, TransactionDesc::toHTML.
QString GUIUtil::HtmlEscape(const std::string &str, bool fMultiLine)
References HtmlEscape.
void GUIUtil::copyEntryData(QAbstractItemView *view, int column, int role)
Copy a field of the currently selected entry of a view to the clipboard. Does nothing if nothing is selected. column Data column to extract from the model role Data role to extract from the model TransactionView::copyLabel, TransactionView::copyAmount, TransactionView::copyAddress
QString GUIUtil::getSaveFileName(QWidget *parent, const QString &caption, const QString &dir, const QString &filter, QString *selectedSuffixOut)
Get save filename, mimics QFileDialog::getSaveFileName, except that it appends a default suffix when no suffix is provided by the user. parent Parent window (or 0) caption Window caption (or empty, for default) dir Starting directory (or empty, to default to documents directory) filter Filter specification such as "Comma Separated Files (*.csv)" selectedSuffixOut Pointer to return the suffix (file type) that was selected (or 0). Can be useful when choosing the save file format based on suffix.
Referenced by AddressBookPage::exportClicked, MessagePage::exportClicked, TransactionView::exportClicked.
Qt::ConnectionType GUIUtil::blockingGUIThreadConnection()
Get connection type to call object slot in GUI thread with invokeMethod. The call will be blocking.If called from the GUI thread, return a Qt::DirectConnection. If called from another thread, return a Qt::BlockingQueuedConnection.
bool GUIUtil::checkPoint(const QPoint &p, const QWidget *w)
Referenced by isObscured.
bool GUIUtil::isObscured(QWidget *w)
References checkPoint.
void GUIUtil::openDebugLogfile()
References GetDataDir.
bool GUIUtil::GetStartOnSystemStartup()
Referenced by main, OptionsModel::data.
bool GUIUtil::SetStartOnSystemStartup(bool fAutoStart)
Referenced by main, OptionsModel::setData.
void GUIUtil::SetBlackThemeQSS(QApplication &app)
Referenced by main.
QString GUIUtil::formatPingTime(double dPingTime)
Referenced by PeerTableModel::data.
QString GUIUtil::formatDurationStr(int secs)
References arg.
QString GUIUtil::formatServicesStr(quint64 mask)
References NODE_NETWORK.