leveldb
ValueType
FileType
Tag
CompressionType
TestType
typedef uint64_t leveldb::SequenceNumber
typedef uint64_t leveldb::Key
typedef std::map<std::string, std::string, STLLessThan> leveldb::KVMap
const int leveldb::kValueSize
const int leveldb::kTotalSize
const int leveldb::kCount
const int leveldb::kValueSize
const int leveldb::kNumNonTableCacheFiles
Referenced by leveldb::DBImpl::DBImpl.
const ValueType leveldb::kValueTypeForSeek
const SequenceNumber leveldb::kMaxSequenceNumber
const int leveldb::kTargetFileSize
const int64_t leveldb::kMaxGrandParentOverlapBytes
const int64_t leveldb::kExpandedCompactionByteSizeLimit
const size_t leveldb::kHeader
const int leveldb::kMajorVersion
const int leveldb::kMinorVersion
const size_t leveldb::kFilterBaseLg
const size_t leveldb::kFilterBase
const uint64_t leveldb::kTableMagicNumber
const size_t leveldb::kBlockTrailerSize
ReverseKeyComparator leveldb::reverse_key_comparator
const TestArgs leveldb::kTestArgList[][]
const int leveldb::kNumTestArgs
const int leveldb::kBlockSize
const int leveldb::kVerbose
port::OnceType leveldb::once
const Comparator* leveldb::bytewise
pthread_once_t leveldb::once
Env* leveldb::default_env
const int leveldb::kDelayMicros
leveldb::TEST(AutoCompactTest, ReadAll)
leveldb::TEST(AutoCompactTest, ReadHalf)
Status leveldb::BuildTable(const std::string &dbname, Env *env, const Options &options, TableCache *table_cache, Iterator *iter, FileMetaData *meta)
References leveldb::FileMetaData::file_size, leveldb::Iterator::SeekToFirst, TableFileName, leveldb::FileMetaData::number, leveldb::Iterator::Valid, leveldb::Env::NewWritableFile, leveldb::Status::ok, leveldb::FileMetaData::smallest, leveldb::InternalKey::DecodeFrom, leveldb::Iterator::key, leveldb::Iterator::Next, leveldb::FileMetaData::largest, leveldb::TableBuilder::Add, leveldb::Iterator::value, leveldb::TableBuilder::Finish, leveldb::TableBuilder::FileSize, leveldb::TableBuilder::Abandon, leveldb::WritableFile::Sync, leveldb::WritableFile::Close, leveldb::TableCache::NewIterator, leveldb::Iterator::status, leveldb::Env::DeleteFile.
leveldb::TEST(CorruptionTest, Recovery)
References kLogFile.
leveldb::TEST(CorruptionTest, RecoverWriteError)
References env_, ASSERT_TRUE, leveldb::Status::ok.
leveldb::TEST(CorruptionTest, NewFileErrorDuringWrite)
References env_, leveldb::Options::write_buffer_size, leveldb::Status::ok, leveldb::WriteBatch::Put, db_, leveldb::DBImpl::Write, ASSERT_TRUE, ASSERT_GE.
leveldb::TEST(CorruptionTest, TableFile)
References db_, leveldb::DBImpl::TEST_CompactMemTable, leveldb::DBImpl::TEST_CompactRange, kTableFile.
leveldb::TEST(CorruptionTest, TableFileRepair)
References options_, leveldb::Options::block_size, leveldb::Options::paranoid_checks, db_, leveldb::DBImpl::TEST_CompactMemTable, leveldb::DBImpl::TEST_CompactRange, kTableFile, RepairDB.
leveldb::TEST(CorruptionTest, TableFileIndexData)
References db_, leveldb::DBImpl::TEST_CompactMemTable, kTableFile.
leveldb::TEST(CorruptionTest, MissingDescriptor)
References RepairDB.
leveldb::TEST(CorruptionTest, SequenceNumberRecovery)
References ASSERT_OK, db_, leveldb::DBImpl::Put, RepairDB, leveldb::DBImpl::Get, ASSERT_EQ.
leveldb::TEST(CorruptionTest, CorruptedDescriptor)
References ASSERT_OK, db_, leveldb::DBImpl::Put, leveldb::DBImpl::TEST_CompactMemTable, kDescriptorFile, ASSERT_TRUE, leveldb::Status::ok, RepairDB, leveldb::DBImpl::Get, ASSERT_EQ.
leveldb::TEST(CorruptionTest, CompactionInputError)
References db_, leveldb::DBImpl::TEST_CompactMemTable, ASSERT_EQ, NumberToString, kTableFile.
leveldb::TEST(CorruptionTest, CompactionInputErrorParanoid)
References options_, leveldb::Options::paranoid_checks, leveldb::Options::write_buffer_size, db_, leveldb::DBImpl::TEST_CompactMemTable, kTableFile, env_, leveldb::Env::SleepForMicroseconds, leveldb::DBImpl::CompactRange, leveldb::DBImpl::Put, ASSERT_TRUE, leveldb::Status::ok.
leveldb::TEST(CorruptionTest, UnrelatedKeys)
References db_, leveldb::DBImpl::TEST_CompactMemTable, kTableFile, ASSERT_OK, leveldb::DBImpl::Put, leveldb::DBImpl::Get, ASSERT_EQ.
static void leveldb::ClipToRange(T *ptr, V minvalue, V maxvalue)
Options leveldb::SanitizeOptions(const std::string &dbname, const InternalKeyComparator *icmp, const InternalFilterPolicy *ipolicy, const Options &src)
References leveldb::Options::comparator, leveldb::Options::filter_policy, leveldb::Options::max_open_files, leveldb::Options::write_buffer_size, leveldb::Options::block_size, leveldb::Options::info_log, leveldb::Options::env, leveldb::Env::CreateDir, leveldb::Env::RenameFile, InfoLogFileName, OldInfoLogFileName, leveldb::Env::NewLogger, leveldb::Status::ok, leveldb::Options::block_cache, NewLRUCache.
Status leveldb::DestroyDB(const std::string &dbname, const Options &options)
References leveldb::Options::env, leveldb::Env::GetChildren, leveldb::Status::OK, LockFileName, leveldb::Env::LockFile, leveldb::Status::ok, ParseFileName, kDBLockFile, leveldb::Env::DeleteFile, leveldb::Env::UnlockFile, leveldb::Env::DeleteDir.
Referenced by leveldb::AutoCompactTest::AutoCompactTest, leveldb::AutoCompactTest::~AutoCompactTest, leveldb_destroy_db, leveldb::CorruptionTest::CorruptionTest, leveldb::CorruptionTest::~CorruptionTest, leveldb::Benchmark::Benchmark, leveldb::Benchmark::Run, leveldb::DBTest::DBTest, leveldb::DBTest::~DBTest, leveldb::DBTest::DestroyAndReopen, TEST, BM_LogAndApply, CLevelDBWrapper::CLevelDBWrapper.
Iterator * leveldb::NewDBIterator(DBImpl *db, const Comparator *user_key_comparator, Iterator *internal_iter, SequenceNumber sequence, uint32_t seed)
Referenced by leveldb::DBImpl::NewIterator.
static std::string leveldb::RandomString(Random *rnd, int len)
leveldb::TEST(DBTest, Empty)
References ASSERT_TRUE, db_, ASSERT_EQ.
leveldb::TEST(DBTest, ReadWrite)
References ASSERT_OK, ASSERT_EQ.
leveldb::TEST(DBTest, PutDeleteGet)
References ASSERT_OK, db_, leveldb::DBImpl::Put, ASSERT_EQ, leveldb::DBImpl::Delete.
leveldb::TEST(DBTest, GetFromImmutableLayer)
References leveldb::Options::env, env_, leveldb::Options::write_buffer_size, ASSERT_OK, ASSERT_EQ.
leveldb::TEST(DBTest, GetFromVersions)
References ASSERT_OK, ASSERT_EQ.
leveldb::TEST(DBTest, GetSnapshot)
References ASSERT_OK, db_, leveldb::DBImpl::GetSnapshot, ASSERT_EQ, leveldb::DBImpl::ReleaseSnapshot.
leveldb::TEST(DBTest, GetLevel0Ordering)
References ASSERT_OK, ASSERT_EQ.
leveldb::TEST(DBTest, GetOrderedByLevels)
References ASSERT_OK, ASSERT_EQ.
leveldb::TEST(DBTest, GetPicksCorrectFile)
References ASSERT_OK, ASSERT_EQ.
leveldb::TEST(DBTest, GetEncountersEmptyLevel)
References ASSERT_LE, ASSERT_EQ.
leveldb::TEST(DBTest, IterEmpty)
References db_, leveldb::DBImpl::NewIterator, leveldb::Iterator::SeekToFirst, ASSERT_EQ, leveldb::Iterator::SeekToLast, leveldb::Iterator::Seek.
leveldb::TEST(DBTest, IterSingle)
References ASSERT_OK, db_, leveldb::DBImpl::NewIterator, leveldb::Iterator::SeekToFirst, ASSERT_EQ, leveldb::Iterator::Next, leveldb::Iterator::Prev, leveldb::Iterator::SeekToLast, leveldb::Iterator::Seek.
leveldb::TEST(DBTest, IterMulti)
References ASSERT_OK, db_, leveldb::DBImpl::NewIterator, leveldb::Iterator::SeekToFirst, ASSERT_EQ, leveldb::Iterator::Next, leveldb::Iterator::Prev, leveldb::Iterator::SeekToLast, leveldb::Iterator::Seek.
leveldb::TEST(DBTest, IterSmallAndLargeMix)
References ASSERT_OK, db_, leveldb::DBImpl::NewIterator, leveldb::Iterator::SeekToFirst, ASSERT_EQ, leveldb::Iterator::Next, leveldb::Iterator::SeekToLast, leveldb::Iterator::Prev.
leveldb::TEST(DBTest, IterMultiWithDelete)
References ASSERT_OK, ASSERT_EQ, db_, leveldb::DBImpl::NewIterator, leveldb::Iterator::Seek, leveldb::Iterator::Prev.
leveldb::TEST(DBTest, Recover)
References ASSERT_OK, ASSERT_EQ.
leveldb::TEST(DBTest, RecoveryWithEmptyLog)
References ASSERT_OK, ASSERT_EQ.
leveldb::TEST(DBTest, RecoverDuringMemtableCompaction)
References leveldb::Options::env, env_, leveldb::Options::write_buffer_size, ASSERT_OK, ASSERT_EQ.
static std::string leveldb::Key(int i)
leveldb::TEST(DBTest, MinorCompactionsHappen)
References leveldb::Options::write_buffer_size, ASSERT_OK, ASSERT_GT, ASSERT_EQ.
leveldb::TEST(DBTest, RecoverWithLargeLog)
References ASSERT_OK, ASSERT_EQ, leveldb::Options::write_buffer_size, ASSERT_GT.
leveldb::TEST(DBTest, CompactionsGenerateMultipleFiles)
References leveldb::Options::write_buffer_size, ASSERT_EQ, ASSERT_OK, ASSERT_GT.
leveldb::TEST(DBTest, RepeatedWritesToSameKey)
References leveldb::Options::env, env_, leveldb::Options::write_buffer_size, value, ASSERT_LE.
leveldb::TEST(DBTest, SparseMerge)
References leveldb::Options::compression, kNoCompression, value, ASSERT_LE.
static bool leveldb::Between(uint64_t val, uint64_t low, uint64_t high)
leveldb::TEST(DBTest, ApproximateSizes)
References leveldb::Options::write_buffer_size, leveldb::Options::compression, kNoCompression, ASSERT_TRUE, ASSERT_EQ, ASSERT_OK, ASSERT_GT.
leveldb::TEST(DBTest, ApproximateSizes_MixOfSmallAndLarge)
References leveldb::Options::compression, kNoCompression, ASSERT_OK, ASSERT_TRUE.
leveldb::TEST(DBTest, IteratorPinsRef)
References db_, leveldb::DBImpl::NewIterator, ASSERT_OK, leveldb::Iterator::SeekToFirst, ASSERT_TRUE, leveldb::Iterator::Valid, ASSERT_EQ, leveldb::Iterator::key, leveldb::Slice::ToString, leveldb::Iterator::value, leveldb::Iterator::Next.
leveldb::TEST(DBTest, Snapshot)
References db_, leveldb::DBImpl::GetSnapshot, ASSERT_EQ, leveldb::DBImpl::ReleaseSnapshot.
leveldb::TEST(DBTest, HiddenValuesAreRemoved)
References db_, leveldb::DBImpl::GetSnapshot, ASSERT_OK, ASSERT_GT, ASSERT_EQ, ASSERT_TRUE, leveldb::DBImpl::ReleaseSnapshot, ASSERT_GE.
leveldb::TEST(DBTest, DeletionMarkers1)
References ASSERT_OK, ASSERT_EQ.
leveldb::TEST(DBTest, DeletionMarkers2)
References ASSERT_OK, ASSERT_EQ.
leveldb::TEST(DBTest, OverlapInLevel0)
References ASSERT_EQ, ASSERT_OK.
leveldb::TEST(DBTest, L0_CompactionBug_Issue44_a)
References ASSERT_OK, ASSERT_EQ.
leveldb::TEST(DBTest, L0_CompactionBug_Issue44_b)
References ASSERT_EQ.
leveldb::TEST(DBTest, ComparatorCheck)
References BytewiseComparator, leveldb::Comparator::Compare, leveldb::Comparator::FindShortestSeparator, leveldb::Comparator::FindShortSuccessor, cmp, leveldb::Options::comparator, ASSERT_TRUE, leveldb::Status::ok, leveldb::Status::ToString.
leveldb::TEST(DBTest, CustomComparator)
References ASSERT_TRUE, leveldb::Slice::size, EscapeString, leveldb::Slice::ToString, cmp, leveldb::Options::create_if_missing, leveldb::Options::comparator, leveldb::Options::filter_policy, leveldb::Options::write_buffer_size, ASSERT_OK, ASSERT_EQ.
leveldb::TEST(DBTest, ManualCompaction)
References ASSERT_EQ, db_, leveldb::DBImpl::CompactRange.
leveldb::TEST(DBTest, DBOpen_Options)
References leveldb::test::TmpDir, DestroyDB, leveldb::Options::create_if_missing, leveldb::DB::Open, ASSERT_TRUE, leveldb::Status::ToString, ASSERT_OK, leveldb::Options::error_if_exists.
leveldb::TEST(DBTest, Locking)
References leveldb::DB::Open, dbname_, ASSERT_TRUE, leveldb::Status::ok.
leveldb::TEST(DBTest, NoSpace)
References leveldb::Options::env, env_, ASSERT_OK, ASSERT_EQ, ASSERT_LT.
leveldb::TEST(DBTest, NonWritableFileSystem)
References leveldb::Options::write_buffer_size, leveldb::Options::env, env_, ASSERT_OK, ASSERT_GT.
leveldb::TEST(DBTest, WriteSyncError)
References leveldb::Options::env, env_, ASSERT_OK, db_, leveldb::DBImpl::Put, ASSERT_EQ, leveldb::WriteOptions::sync, ASSERT_TRUE, leveldb::Status::ok.
leveldb::TEST(DBTest, ManifestWriteError)
References env_, leveldb::Options::env, ASSERT_OK, ASSERT_EQ, leveldb::port::AtomicPointer::Release_Store.
leveldb::TEST(DBTest, MissingSSTFile)
References ASSERT_OK, ASSERT_EQ, ASSERT_TRUE, leveldb::Options::paranoid_checks, leveldb::Status::ok, leveldb::Status::ToString.
leveldb::TEST(DBTest, StillReadSST)
References ASSERT_OK, ASSERT_EQ, ASSERT_GT, leveldb::Options::paranoid_checks, ASSERT_TRUE, leveldb::Status::ok.
leveldb::TEST(DBTest, FilesDeletedAfterCompaction)
References ASSERT_OK, ASSERT_EQ.
leveldb::TEST(DBTest, BloomFilter)
References env_, leveldb::Options::env, leveldb::Options::block_cache, NewLRUCache, leveldb::Options::filter_policy, NewBloomFilterPolicy, ASSERT_OK, ASSERT_EQ, ASSERT_GE, ASSERT_LE.
leveldb::TEST(DBTest, MultiThreaded)
References id, env_, leveldb::Env::StartThread.
static std::string leveldb::RandomKey(Random *rnd)
static bool leveldb::CompareIterators(int step, DB *model, DB *db, const Snapshot *model_snap, const Snapshot *db_snap)
leveldb::TEST(DBTest, Randomized)
References leveldb::test::RandomSeed, leveldb::Random::Uniform, leveldb::Random::OneIn, ASSERT_OK, leveldb::ModelDB::Put, db_, leveldb::DBImpl::Put, leveldb::ModelDB::Delete, leveldb::DBImpl::Delete, leveldb::WriteBatch::Put, leveldb::WriteBatch::Delete, leveldb::ModelDB::Write, leveldb::DBImpl::Write, ASSERT_TRUE, leveldb::ModelDB::ReleaseSnapshot, leveldb::DBImpl::ReleaseSnapshot, leveldb::ModelDB::GetSnapshot, leveldb::DBImpl::GetSnapshot.
std::string leveldb::MakeKey(unsigned int num)
Referenced by BM_LogAndApply.
void leveldb::BM_LogAndApply(int iters, int num_base_files)
References leveldb::test::TmpDir, DestroyDB, leveldb::Options::create_if_missing, leveldb::DB::Open, ASSERT_OK, ASSERT_TRUE, leveldb::Env::Default, mu, cmp, BytewiseComparator, leveldb::VersionSet::Recover, start, MakeKey, kTypeValue, kTypeDeletion, leveldb::VersionSet::LogAndApply, leveldb::Env::NowMicros, leveldb::VersionEdit::DeleteFile, leveldb::VersionEdit::AddFile.
Referenced by main.
static uint64_t leveldb::PackSequenceAndType(uint64_t seq, ValueType t)
void leveldb::AppendInternalKey(std::string *result, const ParsedInternalKey &key)
References leveldb::ParsedInternalKey::user_key, leveldb::Slice::data, leveldb::Slice::size, PutFixed64, leveldb::ParsedInternalKey::sequence, leveldb::ParsedInternalKey::type.
Referenced by leveldb::InternalKey::InternalKey, leveldb::InternalKey::SetFrom, leveldb::KeyConvertingIterator::Seek.
size_t leveldb::InternalKeyEncodingLength(const ParsedInternalKey &key)
References leveldb::ParsedInternalKey::user_key, leveldb::Slice::size.
bool leveldb::ParseInternalKey(const Slice &internal_key, ParsedInternalKey *result)
References leveldb::Slice::size, DecodeFixed64, leveldb::Slice::data, leveldb::ParsedInternalKey::sequence, leveldb::ParsedInternalKey::type, leveldb::ParsedInternalKey::user_key, kTypeValue.
Referenced by leveldb::DBTest::AllEntriesFor, leveldb::InternalKey::DebugString, leveldb::Version::RecordReadSample, leveldb::KeyConvertingIterator::key.
Slice leveldb::ExtractUserKey(const Slice &internal_key)
References leveldb::Slice::size, leveldb::Slice::data.
Referenced by leveldb::InternalKeyComparator::Compare, leveldb::InternalKeyComparator::FindShortestSeparator, leveldb::InternalKeyComparator::FindShortSuccessor, leveldb::InternalFilterPolicy::CreateFilter, leveldb::InternalFilterPolicy::KeyMayMatch, leveldb::InternalKey::user_key.
ValueType leveldb::ExtractValueType(const Slice &internal_key)
References leveldb::Slice::size, DecodeFixed64, leveldb::Slice::data.
static std::string leveldb::IKey(const std::string &user_key, uint64_t seq, ValueType vt)
static std::string leveldb::Shorten(const std::string &s, const std::string &l)
static std::string leveldb::ShortSuccessor(const std::string &s)
static void leveldb::TestKey(const std::string &key, uint64_t seq, ValueType vt)
leveldb::TEST(FormatTest, InternalKey_EncodeDecode)
References kTypeValue, kTypeDeletion.
leveldb::TEST(FormatTest, InternalKeyShortSeparator)
References ASSERT_EQ, kTypeValue, kTypeDeletion.
leveldb::TEST(FormatTest, InternalKeyShortestSuccessor)
References ASSERT_EQ, kTypeValue.
Status leveldb::DumpFile(Env *env, const std::string &fname, WritableFile *dst)
References leveldb::Status::InvalidArgument, kLogFile, kDescriptorFile, kTableFile.
Status leveldb::WriteStringToFileSync(Env *env, const Slice &data, const std::string &fname)
Referenced by SetCurrentFile.
static std::string leveldb::MakeFileName(const std::string &name, uint64_t number, const char *suffix)
std::string leveldb::LogFileName(const std::string &name, uint64_t number)
Referenced by leveldb::DB::Open, TEST.
std::string leveldb::TableFileName(const std::string &name, uint64_t number)
Referenced by BuildTable, leveldb::DBTest::DeleteAnSSTFile, leveldb::DBTest::RenameLDBToSST, TEST.
std::string leveldb::SSTTableFileName(const std::string &name, uint64_t number)
Referenced by leveldb::DBTest::RenameLDBToSST.
std::string leveldb::DescriptorFileName(const std::string &dbname, uint64_t number)
Referenced by SetCurrentFile, TEST, leveldb::VersionSet::LogAndApply.
std::string leveldb::CurrentFileName(const std::string &dbname)
Referenced by SetCurrentFile, TEST, leveldb::VersionSet::Recover.
std::string leveldb::LockFileName(const std::string &dbname)
Referenced by DestroyDB, TEST.
std::string leveldb::TempFileName(const std::string &dbname, uint64_t number)
Referenced by SetCurrentFile, TEST.
std::string leveldb::InfoLogFileName(const std::string &dbname)
Referenced by SanitizeOptions.
std::string leveldb::OldInfoLogFileName(const std::string &dbname)
Referenced by SanitizeOptions.
bool leveldb::ParseFileName(const std::string &fname, uint64_t *number, FileType *type)
References kCurrentFile, kDBLockFile, kInfoLogFile, leveldb::Slice::starts_with, leveldb::Slice::remove_prefix, ConsumeDecimalNumber, leveldb::Slice::empty, kDescriptorFile, kLogFile, kTableFile, kTempFile.
Referenced by leveldb::CorruptionTest::Corrupt, DestroyDB, leveldb::DBTest::DeleteAnSSTFile, leveldb::DBTest::RenameLDBToSST, TEST.
Status leveldb::SetCurrentFile(Env *env, const std::string &dbname, uint64_t descriptor_number)
References DescriptorFileName, leveldb::Slice::starts_with, leveldb::Slice::remove_prefix, TempFileName, WriteStringToFileSync, leveldb::Slice::ToString, leveldb::Status::ok, leveldb::Env::RenameFile, CurrentFileName, leveldb::Env::DeleteFile.
Referenced by leveldb::VersionSet::LogAndApply.
leveldb::TEST(FileNameTest, Parse)
References kLogFile, kTableFile, kCurrentFile, kDBLockFile, kDescriptorFile, kInfoLogFile, ASSERT_TRUE, ParseFileName, ASSERT_EQ.
leveldb::TEST(FileNameTest, Construction)
References CurrentFileName, ASSERT_EQ, ASSERT_TRUE, ParseFileName, kCurrentFile, LockFileName, kDBLockFile, LogFileName, kLogFile, TableFileName, kTableFile, DescriptorFileName, kDescriptorFile, TempFileName, kTempFile.
static Slice leveldb::GetLengthPrefixedSlice(const char *data)
static const char* leveldb::EncodeKey(std::string *scratch, const Slice &target)
Status leveldb::RepairDB(const std::string &dbname, const Options &options)
Referenced by leveldb_repair_db, leveldb::CorruptionTest::RepairDB, TEST.
leveldb::TEST(SkipTest, Empty)
References cmp, ASSERT_TRUE, leveldb::SkipList< Key, Comparator >::Contains.
leveldb::TEST(SkipTest, InsertAndLookup)
References R, cmp, leveldb::Random::Next, leveldb::SkipList< Key, Comparator >::Insert, leveldb::SkipList< Key, Comparator >::Contains, ASSERT_EQ, ASSERT_TRUE, leveldb::SkipList< Key, Comparator >::Iterator::Valid, leveldb::SkipList< Key, Comparator >::Iterator::Seek, leveldb::SkipList< Key, Comparator >::Iterator::key, leveldb::SkipList< Key, Comparator >::Iterator::SeekToFirst, leveldb::SkipList< Key, Comparator >::Iterator::SeekToLast, leveldb::SkipList< Key, Comparator >::Iterator::Next, leveldb::SkipList< Key, Comparator >::Iterator::Prev.
leveldb::TEST(SkipTest, ConcurrentWithoutThreads)
References test, leveldb::test::RandomSeed, leveldb::ConcurrentTest::ReadStep, leveldb::ConcurrentTest::WriteStep.
static void leveldb::ConcurrentReader(void *arg)
static void leveldb::RunConcurrent(int run)
leveldb::TEST(SkipTest, Concurrent1)
leveldb::TEST(SkipTest, Concurrent2)
leveldb::TEST(SkipTest, Concurrent3)
leveldb::TEST(SkipTest, Concurrent4)
leveldb::TEST(SkipTest, Concurrent5)
static void leveldb::DeleteEntry(const Slice &key, void *value)
static void leveldb::UnrefEntry(void *arg1, void *arg2)
static bool leveldb::GetInternalKey(Slice *input, InternalKey *dst)
static bool leveldb::GetLevel(Slice *input, int *level)
static void leveldb::TestEncodeDecode(const VersionEdit &edit)
leveldb::TEST(VersionEditTest, EncodeDecode)
References leveldb::VersionEdit::AddFile, kTypeValue, kTypeDeletion, leveldb::VersionEdit::DeleteFile, leveldb::VersionEdit::SetCompactPointer, leveldb::VersionEdit::SetComparatorName, leveldb::VersionEdit::SetLogNumber, leveldb::VersionEdit::SetNextFile, leveldb::VersionEdit::SetLastSequence.
static double leveldb::MaxBytesForLevel(int level)
static uint64_t leveldb::MaxFileSizeForLevel(int level)
static int64_t leveldb::TotalFileSize(const std::vector< FileMetaData * > &files)
int leveldb::FindFile(const InternalKeyComparator &icmp, const std::vector< FileMetaData * > &files, const Slice &key)
References leveldb::FileMetaData::largest, leveldb::InternalKey::Encode.
Referenced by SomeFileOverlapsRange, leveldb::Version::LevelFileNumIterator::Seek, leveldb::Version::Get, leveldb::FindFileTest::Find.
static bool leveldb::AfterFile(const Comparator *ucmp, const Slice *user_key, const FileMetaData *f)
static bool leveldb::BeforeFile(const Comparator *ucmp, const Slice *user_key, const FileMetaData *f)
bool leveldb::SomeFileOverlapsRange(const InternalKeyComparator &icmp, bool disjoint_sorted_files, const std::vector< FileMetaData * > &files, const Slice *smallest_user_key, const Slice *largest_user_key)
References leveldb::InternalKeyComparator::user_comparator, FindFile, leveldb::InternalKey::Encode.
Referenced by leveldb::Version::OverlapInLevel, leveldb::FindFileTest::Overlaps.
static Iterator* leveldb::GetFileIterator(void *arg, const ReadOptions &options, const Slice &file_value)
static void leveldb::SaveValue(void *arg, const Slice &ikey, const Slice &v)
static bool leveldb::NewestFirst(FileMetaData *a, FileMetaData *b)
leveldb::TEST(FindFileTest, Empty)
References ASSERT_EQ, ASSERT_TRUE.
leveldb::TEST(FindFileTest, Single)
References ASSERT_EQ, ASSERT_TRUE.
leveldb::TEST(FindFileTest, Multiple)
References ASSERT_EQ, ASSERT_TRUE.
leveldb::TEST(FindFileTest, MultipleNullBoundaries)
References ASSERT_TRUE.
leveldb::TEST(FindFileTest, OverlapSequenceChecks)
References ASSERT_TRUE.
leveldb::TEST(FindFileTest, OverlappingFiles)
References ASSERT_TRUE.
static std::string leveldb::PrintContents(WriteBatch *b)
leveldb::TEST(WriteBatchTest, Empty)
References ASSERT_EQ, leveldb::WriteBatchInternal::Count.
leveldb::TEST(WriteBatchTest, Multiple)
References leveldb::WriteBatch::Put, leveldb::WriteBatch::Delete, leveldb::WriteBatchInternal::SetSequence, ASSERT_EQ, leveldb::WriteBatchInternal::Sequence, leveldb::WriteBatchInternal::Count.
leveldb::TEST(WriteBatchTest, Corruption)
References leveldb::WriteBatch::Put, leveldb::WriteBatch::Delete, leveldb::WriteBatchInternal::SetSequence, leveldb::WriteBatchInternal::Contents, leveldb::WriteBatchInternal::SetContents, leveldb::Slice::data, leveldb::Slice::size, ASSERT_EQ.
leveldb::TEST(WriteBatchTest, Append)
References leveldb::WriteBatchInternal::SetSequence, leveldb::WriteBatchInternal::Append, ASSERT_EQ, leveldb::WriteBatch::Put, leveldb::WriteBatch::Clear, leveldb::WriteBatch::Delete.
Env * leveldb::NewMemEnv(Env *base_env)
Referenced by CLevelDBWrapper::CLevelDBWrapper.
leveldb::TEST(MemEnvTest, Basics)
References ASSERT_OK, env_, leveldb::Env::CreateDir, ASSERT_TRUE, leveldb::Env::FileExists, leveldb::Env::GetFileSize, leveldb::Status::ok, leveldb::Env::GetChildren, ASSERT_EQ, leveldb::Env::NewWritableFile, leveldb::Env::RenameFile, leveldb::Env::NewSequentialFile, leveldb::Env::NewRandomAccessFile, leveldb::Env::DeleteFile, leveldb::Env::DeleteDir.
leveldb::TEST(MemEnvTest, ReadWrite)
References ASSERT_OK, env_, leveldb::Env::CreateDir, leveldb::Env::NewWritableFile, leveldb::WritableFile::Append, leveldb::Env::NewSequentialFile, leveldb::SequentialFile::Read, ASSERT_EQ, leveldb::Slice::compare, leveldb::SequentialFile::Skip, leveldb::Slice::size, leveldb::Env::NewRandomAccessFile, leveldb::RandomAccessFile::Read, ASSERT_TRUE, leveldb::Status::ok.
leveldb::TEST(MemEnvTest, Locks)
References ASSERT_OK, env_, leveldb::Env::LockFile, leveldb::Env::UnlockFile.
leveldb::TEST(MemEnvTest, Misc)
References ASSERT_OK, env_, leveldb::Env::GetTestDirectory, ASSERT_TRUE, leveldb::Env::NewWritableFile.
leveldb::TEST(MemEnvTest, LargeWrite)
References ASSERT_OK, env_, leveldb::Env::NewWritableFile, leveldb::WritableFile::Append, leveldb::Env::NewSequentialFile, leveldb::SequentialFile::Read, ASSERT_EQ, leveldb::Slice::compare, json_spirit::read, leveldb::Slice::data, leveldb::Slice::size, ASSERT_TRUE.
leveldb::TEST(MemEnvTest, DBTest)
References leveldb::Options::create_if_missing, leveldb::Options::env, env_, ASSERT_OK, leveldb::DB::Open, leveldb::DB::Put, leveldb::DB::Get, ASSERT_TRUE, leveldb::DB::NewIterator, leveldb::Iterator::SeekToFirst, leveldb::Iterator::Valid, leveldb::Iterator::key, leveldb::Iterator::value, leveldb::Iterator::Next, leveldb::DBImpl::TEST_CompactMemTable.
Cache * leveldb::NewLRUCache(size_t capacity)
Referenced by leveldb::AutoCompactTest::AutoCompactTest, leveldb_cache_create_lru, leveldb::CorruptionTest::CorruptionTest, SanitizeOptions, TEST.
const Comparator * leveldb::BytewiseComparator()
References leveldb::port::InitOnce.
Referenced by TEST, BM_LogAndApply, leveldb::FindFileTest::Find, leveldb::FindFileTest::Overlaps.
void leveldb::Log(Logger *info_log, const char *format,...)
References leveldb::Logger::Logv.
Referenced by leveldb::VersionSet::LogAndApply.
Status leveldb::WriteStringToFile(Env *env, const Slice &data, const std::string &fname)
Referenced by leveldb::CorruptionTest::Corrupt.
Status leveldb::ReadFileToString(Env *env, const std::string &fname, std::string *data)
References leveldb::Env::NewSequentialFile, leveldb::Status::ok, leveldb::SequentialFile::Read, leveldb::Slice::data, leveldb::Slice::size, leveldb::Slice::empty.
Referenced by leveldb::CorruptionTest::Corrupt, leveldb::VersionSet::Recover.
const FilterPolicy * leveldb::NewBloomFilterPolicy(int bits_per_key)
Referenced by leveldb_filterpolicy_create_bloom, leveldb::DBTest::DBTest, TEST, CTxDB::CTxDB.
Iterator * leveldb::NewEmptyIterator()
References leveldb::Status::OK.
Referenced by leveldb::Block::NewIterator, NewMergingIterator.
Iterator * leveldb::NewErrorIterator(const Status &status)
Referenced by leveldb::TableCache::NewIterator, leveldb::Block::NewIterator.
bool leveldb::operator==(const Slice &x, const Slice &y)
References leveldb::Slice::size, leveldb::Slice::data.
bool leveldb::operator!=(const Slice &x, const Slice &y)
leveldb::TEST(Issue200, Test)
References leveldb::test::TmpDir, DestroyDB, leveldb::Options::create_if_missing, ASSERT_OK, leveldb::DB::Open, leveldb::DB::Put, leveldb::DB::NewIterator, leveldb::Iterator::Seek, ASSERT_EQ, leveldb::Iterator::key, leveldb::Slice::ToString, leveldb::Iterator::Prev, leveldb::Iterator::Next.
static const char* leveldb::DecodeEntry(const char *p, const char *limit, uint32_t *shared, uint32_t *non_shared, uint32_t *value_length)
leveldb::TEST(FilterBlockTest, EmptyBuilder)
References leveldb::FilterBlockBuilder::Finish, ASSERT_EQ, EscapeString, ASSERT_TRUE, leveldb::FilterBlockReader::KeyMayMatch.
leveldb::TEST(FilterBlockTest, SingleChunk)
References leveldb::FilterBlockBuilder::StartBlock, leveldb::FilterBlockBuilder::AddKey, leveldb::FilterBlockBuilder::Finish, ASSERT_TRUE, leveldb::FilterBlockReader::KeyMayMatch.
leveldb::TEST(FilterBlockTest, MultiChunk)
References leveldb::FilterBlockBuilder::StartBlock, leveldb::FilterBlockBuilder::AddKey, leveldb::FilterBlockBuilder::Finish, ASSERT_TRUE, leveldb::FilterBlockReader::KeyMayMatch.
Status leveldb::ReadBlock(RandomAccessFile *file, const ReadOptions &options, const BlockHandle &handle, BlockContents *result)
References leveldb::BlockContents::data, leveldb::BlockContents::cachable, leveldb::BlockContents::heap_allocated, leveldb::BlockHandle::size, leveldb::RandomAccessFile::Read, leveldb::BlockHandle::offset, leveldb::Status::ok, leveldb::Status::Corruption, leveldb::ReadOptions::verify_checksums, leveldb::crc32c::Unmask, DecodeFixed32, leveldb::crc32c::Value, kNoCompression, kSnappyCompression, leveldb::port::Snappy_GetUncompressedLength, leveldb::port::Snappy_Uncompress, leveldb::Status::OK.
Referenced by leveldb::Table::Open.
Iterator * leveldb::NewMergingIterator(const Comparator *cmp, Iterator **list, int n)
References NewEmptyIterator.
Referenced by leveldb::VersionSet::MakeInputIterator.
static void leveldb::DeleteBlock(void *arg, void *ignored)
static void leveldb::DeleteCachedBlock(const Slice &key, void *value)
static void leveldb::ReleaseBlock(void *arg, void *h)
static std::string leveldb::Reverse(const Slice &key)
static void leveldb::Increment(const Comparator *cmp, std::string *key)
leveldb::TEST(Harness, Empty)
References leveldb::test::RandomSeed.
leveldb::TEST(Harness, ZeroRestartPointsInBlock)
References leveldb::BlockContents::data, leveldb::BlockContents::cachable, leveldb::BlockContents::heap_allocated, leveldb::Block::NewIterator, BytewiseComparator, leveldb::Iterator::SeekToFirst, ASSERT_TRUE, leveldb::Iterator::Valid, leveldb::Iterator::SeekToLast, leveldb::Iterator::Seek.
leveldb::TEST(Harness, SimpleEmptyKey)
References leveldb::test::RandomSeed.
leveldb::TEST(Harness, SimpleSingle)
References leveldb::test::RandomSeed.
leveldb::TEST(Harness, SimpleMulti)
References leveldb::test::RandomSeed.
leveldb::TEST(Harness, SimpleSpecialKey)
References leveldb::test::RandomSeed.
leveldb::TEST(Harness, Randomized)
References leveldb::test::RandomSeed, leveldb::test::RandomKey, leveldb::Random::Skewed, leveldb::test::RandomString.
leveldb::TEST(Harness, RandomizedLongDB)
References leveldb::test::RandomSeed, DB_TEST, leveldb::test::RandomKey, leveldb::Random::Skewed, leveldb::test::RandomString, value, ASSERT_TRUE, atoi, ASSERT_GT.
leveldb::TEST(MemTableTest, Simple)
References cmp, BytewiseComparator, leveldb::MemTable::Ref, leveldb::WriteBatchInternal::SetSequence, leveldb::WriteBatch::Put, ASSERT_TRUE, leveldb::WriteBatchInternal::InsertInto, leveldb::MemTable::NewIterator, leveldb::Iterator::SeekToFirst, leveldb::Iterator::Valid, leveldb::Iterator::key, leveldb::Slice::ToString, leveldb::Iterator::value, leveldb::Iterator::Next, leveldb::MemTable::Unref.
static bool leveldb::Between(uint64_t val, uint64_t low, uint64_t high)
leveldb::TEST(TableTest, ApproximateOffsetOfPlain)
References BytewiseComparator, leveldb::Constructor::Add, leveldb::Options::block_size, leveldb::Options::compression, kNoCompression, leveldb::Constructor::Finish, ASSERT_TRUE, leveldb::TableConstructor::ApproximateOffsetOf.
static bool leveldb::SnappyCompressionSupported()
leveldb::TEST(TableTest, ApproximateOffsetOfCompressed)
References BytewiseComparator, leveldb::Constructor::Add, leveldb::test::CompressibleString, leveldb::Options::block_size, leveldb::Options::compression, kSnappyCompression, leveldb::Constructor::Finish, ASSERT_TRUE, leveldb::TableConstructor::ApproximateOffsetOf.
Iterator* leveldb::NewTwoLevelIterator(Iterator *index_iter, BlockFunction block_function, void *arg, const ReadOptions &options)
Referenced by leveldb::VersionSet::MakeInputIterator, leveldb::Table::NewIterator.
Iterator* leveldb::NewTwoLevelIterator(Iterator *index_iter, Iterator *(*block_function)(void *arg, const ReadOptions &options, const Slice &index_value), void *arg, const ReadOptions &options)
leveldb::TEST(ArenaTest, Empty)
leveldb::TEST(ArenaTest, Simple)
References leveldb::Random::OneIn, leveldb::Random::Uniform, leveldb::Arena::AllocateAligned, leveldb::Arena::Allocate, ASSERT_GE, leveldb::Arena::MemoryUsage, ASSERT_LE, ASSERT_EQ.
static Slice leveldb::Key(int i, char *buffer)
leveldb::TEST(BloomTest, EmptyFilter)
References ASSERT_TRUE.
leveldb::TEST(BloomTest, Small)
References ASSERT_TRUE.
static int leveldb::NextLength(int length)
leveldb::TEST(BloomTest, VaryingLengths)
References ASSERT_LE, ASSERT_TRUE.
static std::string leveldb::EncodeKey(int k)
static int leveldb::DecodeKey(const Slice &k)
static void* leveldb::EncodeValue(uintptr_t v)
static int leveldb::DecodeValue(void *v)
leveldb::TEST(CacheTest, HitAndMiss)
References ASSERT_EQ, Lookup.
leveldb::TEST(CacheTest, Erase)
References ASSERT_EQ, Lookup.
leveldb::TEST(CacheTest, EntriesArePinned)
References ASSERT_EQ, Lookup.
leveldb::TEST(CacheTest, EvictionPolicy)
References ASSERT_EQ, Lookup.
leveldb::TEST(CacheTest, HeavyEntries)
References Lookup, ASSERT_EQ, ASSERT_LE.
leveldb::TEST(CacheTest, NewId)
References ASSERT_NE.
void leveldb::EncodeFixed32(char *buf, uint32_t value)
Referenced by leveldb::log::LogTest::FixChecksum, leveldb::WriteBatchInternal::SetCount, PutFixed32.
void leveldb::EncodeFixed64(char *buf, uint64_t value)
Referenced by leveldb::LookupKey::LookupKey, leveldb::MemTable::Add, leveldb::TableCache::Evict, leveldb::Version::LevelFileNumIterator::value, leveldb::WriteBatchInternal::SetSequence, PutFixed64.
void leveldb::PutFixed32(std::string *dst, uint32_t value)
References value, EncodeFixed32.
Referenced by leveldb::BlockBuilder::Finish, leveldb::FilterBlockBuilder::Finish, leveldb::TestHashFilter::CreateFilter, leveldb::Footer::EncodeTo, TEST.
void leveldb::PutFixed64(std::string *dst, uint64_t value)
References value, EncodeFixed64.
Referenced by AppendInternalKey, leveldb::InternalKeyComparator::FindShortestSeparator, leveldb::InternalKeyComparator::FindShortSuccessor, TEST.
char * leveldb::EncodeVarint32(char *dst, uint32_t v)
Referenced by leveldb::LookupKey::LookupKey, leveldb::MemTable::Add, PutVarint32.
void leveldb::PutVarint32(std::string *dst, uint32_t v)
References EncodeVarint32.
Referenced by leveldb::VersionEdit::EncodeTo, leveldb::BlockBuilder::Add, PutLengthPrefixedSlice, TEST.
char * leveldb::EncodeVarint64(char *dst, uint64_t v)
Referenced by PutVarint64.
void leveldb::PutVarint64(std::string *dst, uint64_t v)
References EncodeVarint64.
Referenced by leveldb::VersionEdit::EncodeTo, leveldb::BlockHandle::EncodeTo, TEST.
void leveldb::PutLengthPrefixedSlice(std::string *dst, const Slice &value)
References PutVarint32, leveldb::Slice::size, leveldb::Slice::data.
Referenced by leveldb::VersionEdit::EncodeTo, leveldb::WriteBatch::Put, leveldb::WriteBatch::Delete, TEST.
int leveldb::VarintLength(uint64_t v)
Referenced by leveldb::MemTable::Add, TEST.
const char * leveldb::GetVarint32PtrFallback(const char *p, const char *limit, uint32_t *value)
Referenced by GetVarint32Ptr.
bool leveldb::GetVarint32(Slice *input, uint32_t *value)
References leveldb::Slice::data, leveldb::Slice::size, GetVarint32Ptr.
Referenced by leveldb::VersionEdit::DecodeFrom, GetLengthPrefixedSlice.
const char * leveldb::GetVarint64Ptr(const char *p, const char *limit, uint64_t *value)
Referenced by GetVarint64, TEST.
bool leveldb::GetVarint64(Slice *input, uint64_t *value)
References leveldb::Slice::data, leveldb::Slice::size, GetVarint64Ptr.
Referenced by leveldb::VersionEdit::DecodeFrom, leveldb::BlockHandle::DecodeFrom.
const char* leveldb::GetLengthPrefixedSlice(const char *p, const char *limit, Slice *result)
References GetLengthPrefixedSlice, GetVarint32Ptr.
Referenced by leveldb::VersionEdit::DecodeFrom, leveldb::WriteBatch::Iterate, GetLengthPrefixedSlice, TEST.
bool leveldb::GetLengthPrefixedSlice(Slice *input, Slice *result)
References GetLengthPrefixedSlice, GetVarint32, leveldb::Slice::size, leveldb::Slice::data, leveldb::Slice::remove_prefix.
const char * leveldb::GetVarint32Ptr(const char *p, const char *limit, uint32_t *v)
References GetVarint32PtrFallback.
Referenced by leveldb::MemTable::Get, GetVarint32, GetLengthPrefixedSlice, TEST.
uint32_t leveldb::DecodeFixed32(const char *ptr)
Referenced by leveldb::WriteBatchInternal::Count, leveldb::FilterBlockReader::FilterBlockReader, leveldb::FilterBlockReader::KeyMayMatch, leveldb::TestHashFilter::KeyMayMatch, leveldb::Footer::DecodeFrom, ReadBlock, DecodeFixed64, TEST, Hash.
uint64_t leveldb::DecodeFixed64(const char *ptr)
References DecodeFixed32.
Referenced by leveldb::InternalKeyComparator::Compare, ExtractValueType, ParseInternalKey, leveldb::MemTable::Get, leveldb::WriteBatchInternal::Sequence, TEST.
leveldb::TEST(Coding, Fixed32)
References PutFixed32, DecodeFixed32, ASSERT_EQ.
leveldb::TEST(Coding, Fixed64)
References PutFixed64, DecodeFixed64, ASSERT_EQ.
leveldb::TEST(Coding, EncodingOutput)
References PutFixed32, ASSERT_EQ, PutFixed64.
leveldb::TEST(Coding, Varint32)
References PutVarint32, start, GetVarint32Ptr, ASSERT_TRUE, ASSERT_EQ, VarintLength.
leveldb::TEST(Coding, Varint64)
References PutVarint64, ASSERT_TRUE, start, GetVarint64Ptr, ASSERT_EQ, VarintLength.
leveldb::TEST(Coding, Varint32Overflow)
References ASSERT_TRUE, GetVarint32Ptr.
leveldb::TEST(Coding, Varint32Truncation)
References PutVarint32, ASSERT_TRUE, GetVarint32Ptr, ASSERT_EQ.
leveldb::TEST(Coding, Varint64Overflow)
References ASSERT_TRUE, GetVarint64Ptr.
leveldb::TEST(Coding, Varint64Truncation)
References PutVarint64, ASSERT_TRUE, GetVarint64Ptr, ASSERT_EQ.
leveldb::TEST(Coding, Strings)
References PutLengthPrefixedSlice, ASSERT_TRUE, GetLengthPrefixedSlice, ASSERT_EQ, leveldb::Slice::ToString.
static void leveldb::InitModule()
static Status leveldb::DoWriteStringToFile(Env *env, const Slice &data, const std::string &fname, bool should_sync)
static void leveldb::InitDefaultEnv()
static void leveldb::SetBool(void *ptr)
leveldb::TEST(EnvPosixTest, RunImmediately)
References env_, leveldb::Env::Schedule, leveldb::Env::Default, leveldb::Env::SleepForMicroseconds, ASSERT_TRUE, leveldb::port::AtomicPointer::NoBarrier_Load.
leveldb::TEST(EnvPosixTest, RunMany)
References id, ASSERT_EQ, env_, leveldb::Env::Schedule, leveldb::Env::Default, leveldb::Env::SleepForMicroseconds, leveldb::port::AtomicPointer::Acquire_Load.
static void leveldb::ThreadBody(void *arg)
leveldb::TEST(EnvPosixTest, StartThread)
References state, leveldb::State::val, leveldb::State::num_running, env_, leveldb::Env::StartThread, leveldb::State::mu, leveldb::port::Mutex::Lock, leveldb::port::Mutex::Unlock, leveldb::Env::Default, leveldb::Env::SleepForMicroseconds, ASSERT_EQ.
uint32_t leveldb::Hash(const char *data, size_t n, uint32_t seed)
References DecodeFixed32, FALLTHROUGH_INTENDED.
Referenced by leveldb::TestHashFilter::CreateFilter, leveldb::TestHashFilter::KeyMayMatch, TEST.
leveldb::TEST(HASH, SignedUnsignedIssue)
References ASSERT_EQ, Hash.
void leveldb::AppendNumberTo(std::string *str, uint64_t num)
Referenced by leveldb::VersionEdit::DebugString, leveldb::Version::DebugString, NumberToString.
void leveldb::AppendEscapedStringTo(std::string *str, const Slice &value)
References leveldb::Slice::size.
Referenced by EscapeString.
std::string leveldb::NumberToString(uint64_t num)
References AppendNumberTo.
Referenced by TEST, leveldb::DBTest::NumTableFilesAtLevel.
std::string leveldb::EscapeString(const Slice &value)
References AppendEscapedStringTo.
Referenced by TEST, leveldb::ParsedInternalKey::DebugString, leveldb::InternalKey::DebugString, leveldb::Harness::TestRandomAccess.
bool leveldb::ConsumeDecimalNumber(Slice *in, uint64_t *val)
References leveldb::Slice::empty, leveldb::Slice::remove_prefix.
Referenced by leveldb::CorruptionTest::Check, leveldb::DBImpl::GetProperty, ParseFileName.