leveldb::test
bool leveldb::test::RegisterTest(const char *base, const char *name, void(*func)())
References base, name, func.
int leveldb::test::RunAllTests()
Referenced by main.
std::string leveldb::test::TmpDir()
References leveldb::Env::Default, leveldb::Env::GetTestDirectory, ASSERT_TRUE, leveldb::Status::ok, leveldb::Status::ToString.
Referenced by leveldb::AutoCompactTest::AutoCompactTest, leveldb::CorruptionTest::CorruptionTest, leveldb::DBTest::DBTest, leveldb::TEST, leveldb::BM_LogAndApply.
int leveldb::test::RandomSeed()
References atoi.
Referenced by leveldb::TEST.
Slice leveldb::test::RandomString(Random *rnd, int len, std::string *dst)
References leveldb::Random::Uniform.
Referenced by leveldb::CorruptionTest::Value, leveldb::TEST, CompressibleString.
std::string leveldb::test::RandomKey(Random *rnd, int len)
References leveldb::Random::Uniform.
Referenced by leveldb::TEST.
Slice leveldb::test::CompressibleString(Random *rnd, double compressed_fraction, size_t len, std::string *dst)
References RandomString.
Referenced by leveldb::TEST.