Checkpoints
typedef std::map<int, uint256> Checkpoints::MapCheckpoints
MapCheckpoints Checkpoints::mapCheckpoints
MapCheckpoints Checkpoints::mapCheckpointsTestnet
bool Checkpoints::CheckHardened(int nHeight, const uint256 &hash)
References TestNet.
Referenced by CBlock::AcceptBlock.
int Checkpoints::GetTotalBlocksEstimate()
References TestNet.
Referenced by CBlock::AcceptBlock, Reorganize, IsInitialBlockDownload, CTransactionPoS::ConnectInputs, BOOST_AUTO_TEST_CASE.
CBlockIndex * Checkpoints::GetLastCheckpoint(const std::map< uint256, CBlockIndex * > &mapBlockIndex)
References TestNet, hash.
const CBlockIndex * Checkpoints::AutoSelectSyncCheckpoint()
References pindexBest, CBlockIndex::pprev, CBlockIndex::nHeight.
Referenced by CheckSync, ProcessBlock, getcheckpoint.
bool Checkpoints::CheckSync(int nHeight)
References AutoSelectSyncCheckpoint.
Referenced by CBlock::AcceptBlock.