leveldb::crc32c
const uint32_t leveldb::crc32c::table0_[256][256]
const uint32_t leveldb::crc32c::table1_[256][256]
const uint32_t leveldb::crc32c::table2_[256][256]
const uint32_t leveldb::crc32c::table3_[256][256]
const uint32_t leveldb::crc32c::kMaskDelta
static uint32_t leveldb::crc32c::LE_LOAD32(const uint8_t *p)
uint32_t leveldb::crc32c::Extend(uint32_t crc, const char *buf, size_t size)
References STEP1, STEP4.
Referenced by Value, TEST.
uint32_t leveldb::crc32c::Value(const char *data, size_t n)
References Extend.
Referenced by leveldb::log::LogTest::FixChecksum, leveldb::log::Writer::Writer, leveldb::ReadBlock, TEST.
uint32_t leveldb::crc32c::Mask(uint32_t crc)
Referenced by leveldb::log::LogTest::FixChecksum, TEST.
uint32_t leveldb::crc32c::Unmask(uint32_t masked_crc)
Referenced by leveldb::ReadBlock, TEST.
leveldb::crc32c::TEST(CRC, StandardResults)
References ASSERT_EQ, Value.
leveldb::crc32c::TEST(CRC, Values)
References ASSERT_NE, Value.
leveldb::crc32c::TEST(CRC, Extend)
References ASSERT_EQ, Value, Extend.
leveldb::crc32c::TEST(CRC, Mask)
References Value, ASSERT_NE, Mask, ASSERT_EQ, Unmask.