net.h
@10
typedef int NodeId
int nBestHeight
Referenced by CBlock::AcceptBlock, InvalidChainFound, IsInitialBlockDownload, CBlock::WriteToDisk, AppInit2, GetHeight, IsFinalTx, CBlock::SetBestChain, CNode::PushVersion, getBlockHash, ClientModel::getNumBlocks, OverviewPage::sandStormStatus, TransactionRecord::updateStatus, TransactionRecord::statusUpdateNeeded, WalletModel::pollBalanceChanged, blockToJSON, getblockcount, getblockhash, getblockbynumber, importwallet, dumpwallet, getmininginfo, getinfo, TxToJSON, listsinceblock, gettransaction, IsBudgetCollateralValid, CBudgetManager::NewBlock, CTxDB::LoadBlockIndex, CWallet::GetKeyBirthTimes.
const int PING_INTERVAL
Time between pings automatically sent out for latency probing and keepalive (in seconds).
const int TIMEOUT_INTERVAL
Time after which to disconnect, after waiting for a ping response (or inactivity).
bool fDiscover
Referenced by AppInit2, IsPeerAddrLocalGood, AddLocal, BindListenPort.
uint64_t nLocalServices
Referenced by GetLocalAddress, CNode::PushVersion, StartNode, getnetworkinfo.
uint64_t nLocalHostNonce
Referenced by CNode::PushVersion.
CAddrMan addrman
Referenced by CActiveStormnode::Register, AppInit2, CStormnodeMan::ProcessMessage.
std::vector<CNode*> vNodes
Referenced by CBlock::AcceptBlock, Misbehaving, SendMessages, ThreadStakeMiner, RelayInv, FindNode, ConnectNode, ThreadSocketHandler, ThreadDNSAddressSeed, ThreadOpenConnections, ThreadOpenAddedConnections, ThreadMessageHandler, ClientModel::getNumConnections, PeerTablePriv::refreshPeers, checkkernel, getworkex, getwork, getblocktemplate, getinfo, getconnectioncount, ping, getaddednodeinfo, sendalert, getnetworkinfo, CSandstormQueue::Relay, CSandstormPool::RelayFinalTransaction, CSandstormPool::RelayStatus, CSandstormPool::RelayCompletedTransaction, ThreadSecureMsg, SecureMsgEnable, SecureMsgDisable, CSporkManager::Relay, CBudgetManager::NewBlock, CStormnodeSync::ClearFulfilledRequest, CStormnodeSync::Process, CStormnodeMan::ProcessStormnodeConnections.
CCriticalSection cs_vNodes
Referenced by CBlock::AcceptBlock, Misbehaving, SendMessages, PeerTablePriv::refreshPeers, getconnectioncount, ping, getaddednodeinfo, sendalert, CSandstormQueue::Relay, CSandstormPool::RelayFinalTransaction, CSandstormPool::RelayStatus, CSandstormPool::RelayCompletedTransaction, ThreadSecureMsg, SecureMsgEnable, SecureMsgDisable, CSporkManager::Relay, CBudgetManager::NewBlock, CStormnodeSync::ClearFulfilledRequest, CStormnodeSync::Process, CStormnodeMan::ProcessStormnodeConnections.
std::map<CInv, CDataStream> mapRelay
Referenced by RelayTransaction.
std::deque<std::pair<int64_t, CInv> > vRelayExpiration
Referenced by RelayTransaction.
CCriticalSection cs_mapRelay
std::map<CInv, int64_t> mapAlreadyAskedFor
Referenced by SendMessages.
std::vector<std::string> vAddedNodes
Referenced by ThreadOpenAddedConnections, addnode, getaddednodeinfo.
CCriticalSection cs_vAddedNodes
Referenced by addnode, getaddednodeinfo.
NodeId nLastNodeId
CCriticalSection cs_nLastNodeId
CCriticalSection cs_mapLocalHost
Referenced by getnetworkinfo.
std::map<CNetAddr, LocalServiceInfo> mapLocalHost
Referenced by GetLocal, GetnScore, AddLocal, SeenLocal, IsLocal, getnetworkinfo.
unsigned int ReceiveFloodSize()
References GetArg.
Referenced by ThreadSocketHandler.
unsigned int SendBufferSize()
References GetArg.
Referenced by ProcessMessages, ThreadMessageHandler, CNode::CNode.
void AddOneShot(std::string strDest)
bool RecvLine(SOCKET hSocket, std::string &strLine)
void AddressCurrentlyConnected(const CService &addr)
References CAddrMan::Connected.
CNode* FindNode(const CNetAddr &ip)
References LOCK, vNodes, CNode::addr.
Referenced by ConnectNode, OpenNetworkConnection, CSandstormPool::RelayIn.
CNode* FindNode(const std::string &addrName)
References LOCK, vNodes, CNode::addrName.
CNode* FindNode(const CService &ip)
References LOCK, vNodes, CNode::addr.
CNode* ConnectNode(CAddress addrConnect, const char *strDest=NULL, bool sandStormnode=false)
References IsLocal, FindNode, CNode::fSandStorm, CNode::AddRef, CService::ToString, GetAdjustedTime, CAddress::nTime, ConnectSocketByName, Params, nConnectTimeout, ConnectSocket, CAddrMan::Attempt, SOCKET_ERROR, LogPrintf, WSAGetLastError, LOCK, vNodes, CNode::nTimeConnected, GetTime.
Referenced by CActiveStormnode::ManageStatus, OpenNetworkConnection, addnode, stormnode, CSandStormRelay::RelayThroughNode, CSandstormPool::DoAutomaticDenominating.
void MapPort(bool fUseUPnP)
Referenced by StartNode, StopNode, OptionsModel::setData.
unsigned short GetListenPort()
References GetArg, Params.
Referenced by AppInit2, GetLocalAddress, AddLocal.
bool BindListenPort(const CService &bindAddr, std::string &strError=REF(std::string()))
void StartNode(boost::thread_group &threadGroup)
References GetArg, nLocalServices, GetBoolArg, LogPrintf, TraceThread, ThreadDNSAddressSeed, MapPort, ThreadSocketHandler, ThreadOpenAddedConnections, ThreadOpenConnections, ThreadMessageHandler, LoopForever, DumpAddresses, DUMP_ADDRESSES_INTERVAL.
Referenced by AppInit2.
bool StopNode()
References LogPrintf, MapPort, mempool, CTxMemPool::AddTransactionsUpdated, CSemaphore::post, DumpAddresses.
Referenced by Shutdown.
void SocketSendData(CNode *pnode)
References CNode::vSendMsg, CNode::nSendOffset, CNode::hSocket, CNode::nLastSend, GetTime, CNode::nSendBytes, CNode::RecordBytesSent, CNode::nSendSize, WSAGetLastError, WSAEWOULDBLOCK, WSAEMSGSIZE, WSAEINTR, WSAEINPROGRESS, LogPrintf, CNode::CloseSocketDisconnect.
Referenced by ThreadSocketHandler, CNode::EndMessage.
void RelayInv(CInv &inv, const int minProtoVersion=MIN_PEER_PROTO_VERSION)
References LOCK, vNodes, CNode::nVersion, CNode::PushInventory.
Referenced by ProcessMessageInstantX, DoConsensusVote, CSandstormPool::CheckFinalTransaction, CBudgetProposalBroadcast::Relay, CBudgetVote::Relay, CFinalizedBudgetBroadcast::Relay, CFinalizedBudgetVote::Relay, CStormnodePaymentWinner::Relay, CStormnodeBroadcast::Relay, CStormnodePing::Relay.
CNodeSignals& GetNodeSignals()
Referenced by Shutdown, AppInit2, CNode::CNode, CNode::~CNode.
bool IsPeerAddrLocalGood(CNode *pnode)
References fDiscover, CNode::addr, CNetAddr::IsRoutable, CNode::addrLocal, IsLimited, CNetAddr::GetNetwork.
void SetLimited(enum Network net, bool fLimited=true)
Make a particular network entirely off-limits (no automatic connects to it)
References NET_UNROUTABLE, LOCK.
Referenced by AppInit2.
bool IsLimited(enum Network net)
References LOCK.
Referenced by AppInit2, IsPeerAddrLocalGood, AddLocal, IsLimited, ThreadOpenConnections, DarkSilkGUI::setClientModel.
bool IsLimited(const CNetAddr &addr)
References IsLimited, CNetAddr::GetNetwork.
bool AddLocal(const CService &addr, int nScore=LOCAL_NONE)
References CNetAddr::IsRoutable, fDiscover, LOCAL_MANUAL, IsLimited, LogPrintf, CService::ToString, LOCK, mapLocalHost, LocalServiceInfo::nScore, LocalServiceInfo::nPort, CService::GetPort, SetReachable, CNetAddr::GetNetwork.
Referenced by AppInit2, AddLocal, BindListenPort.
bool AddLocal(const CNetAddr &addr, int nScore=LOCAL_NONE)
References AddLocal, GetListenPort.
bool SeenLocal(const CService &addr)
vote for a local address
References LOCK, mapLocalHost.
bool IsLocal(const CService &addr)
check whether a given address is potentially local
References LOCK, mapLocalHost.
Referenced by ConnectNode, ThreadOpenConnections, OpenNetworkConnection, CNetAddr::IsRoutable, CNetAddr::GetGroup, BOOST_AUTO_TEST_CASE.
bool GetLocal(CService &addr, const CNetAddr *paddrPeer=NULL)
References fNoListen, LOCK, mapLocalHost.
Referenced by CActiveStormnode::ManageStatus, GetLocalAddress.
bool IsReachable(enum Network net)
check whether a given network is one we can probably connect to
References LOCK.
Referenced by IsReachable.
bool IsReachable(const CNetAddr &addr)
check whether a given address is in a network we can probably connect to
References CNetAddr::GetNetwork, IsReachable.
void SetReachable(enum Network net, bool fFlag=true)
References LOCK, NET_IPV6, NET_IPV4.
Referenced by AppInit2, AddLocal.
CAddress GetLocalAddress(const CNetAddr *paddrPeer=NULL)
References GetListenPort, GetLocal, CAddress::nServices, nLocalServices, CAddress::nTime, GetAdjustedTime.
Referenced by SendMessages, CNode::PushVersion, getinfo.
void RelayInventory(const CInv &inv)
References LOCK, CNode::PushInventory.
Referenced by RelayTransaction.
void RelayTransaction(const CTransaction &tx, const uint256 &hash)
References SER_NETWORK, CDataStream::reserve, RelayTransaction.
Referenced by RelayTransaction, sendrawtransaction, CWalletTx::RelayWalletTransaction.
void RelayTransaction(const CTransaction &tx, const uint256 &hash, const CDataStream &ss)
References MSG_TX, LOCK, vRelayExpiration, GetTime, mapRelay, RelayInventory.
void RelayTransactionLockReq(const CTransaction &tx, const uint256 &hash, bool relayToAll=false)
References MSG_TXLOCK_REQUEST, CTransaction::GetHash, LOCK, CNode::fRelayTxes, CNode::PushMessage.
Referenced by CWalletTx::RelayWalletTransaction.