net.cpp
TOR_NET_STRING
DUMP_ADDRESSES_INTERVAL
Referenced by StartNode.
X
Referenced by CNode::copyStats.
const int MAX_OUTBOUND_CONNECTIONS
bool fDiscover
Referenced by AppInit2, IsPeerAddrLocalGood, AddLocal, BindListenPort.
uint64_t nLocalServices
Referenced by GetLocalAddress, CNode::PushVersion, StartNode, getnetworkinfo.
CCriticalSection cs_mapLocalHost
Referenced by getnetworkinfo.
map<CNetAddr, LocalServiceInfo> mapLocalHost
Referenced by GetLocal, GetnScore, AddLocal, SeenLocal, IsLocal, getnetworkinfo.
bool vfReachable[NET_MAX][NET_MAX]
bool vfLimited[NET_MAX][NET_MAX]
CNode* pnodeLocalHost
CNode* pnodeSync
uint64_t nLocalHostNonce
Referenced by CNode::PushVersion.
std::vector<SOCKET> vhListenSocket
CAddrMan addrman
Referenced by CActiveStormnode::Register, AppInit2, CStormnodeMan::ProcessMessage.
vector<CNode*> vNodes
Referenced by CBlock::AcceptBlock, Misbehaving, SendMessages, ThreadStakeMiner, RelayInv, FindNode, ConnectNode, ThreadSocketHandler, ThreadDNSAddressSeed, ThreadOpenConnections, ThreadOpenAddedConnections, ThreadMessageHandler, ClientModel::getNumConnections, PeerTablePriv::refreshPeers, checkkernel, getworkex, getwork, getblocktemplate, getinfo, getconnectioncount, ping, getaddednodeinfo, sendalert, getnetworkinfo, CSandstormQueue::Relay, CSandstormPool::RelayFinalTransaction, CSandstormPool::RelayStatus, CSandstormPool::RelayCompletedTransaction, ThreadSecureMsg, SecureMsgEnable, SecureMsgDisable, CSporkManager::Relay, CBudgetManager::NewBlock, CStormnodeSync::ClearFulfilledRequest, CStormnodeSync::Process, CStormnodeMan::ProcessStormnodeConnections.
CCriticalSection cs_vNodes
Referenced by CBlock::AcceptBlock, Misbehaving, SendMessages, PeerTablePriv::refreshPeers, getconnectioncount, ping, getaddednodeinfo, sendalert, CSandstormQueue::Relay, CSandstormPool::RelayFinalTransaction, CSandstormPool::RelayStatus, CSandstormPool::RelayCompletedTransaction, ThreadSecureMsg, SecureMsgEnable, SecureMsgDisable, CSporkManager::Relay, CBudgetManager::NewBlock, CStormnodeSync::ClearFulfilledRequest, CStormnodeSync::Process, CStormnodeMan::ProcessStormnodeConnections.
map<CInv, CDataStream> mapRelay
Referenced by RelayTransaction.
deque<pair<int64_t, CInv> > vRelayExpiration
Referenced by RelayTransaction.
CCriticalSection cs_mapRelay
map<CInv, int64_t> mapAlreadyAskedFor
Referenced by SendMessages.
deque<string> vOneShots
CCriticalSection cs_vOneShots
set<CNetAddr> setservAddNodeAddresses
Referenced by ThreadOpenAddedConnections.
CCriticalSection cs_setservAddNodeAddresses
vector<std::string> vAddedNodes
Referenced by ThreadOpenAddedConnections, addnode, getaddednodeinfo.
CCriticalSection cs_vAddedNodes
Referenced by addnode, getaddednodeinfo.
NodeId nLastNodeId
CCriticalSection cs_nLastNodeId
CSemaphore* semOutbound
CNodeSignals n_signals
list<CNode*> vNodesDisconnected
class CNetCleanup instance_of_cnetcleanup
bool OpenNetworkConnection(const CAddress &addrConnect, CSemaphoreGrant *grantOutbound=NULL, const char *strDest=NULL, bool fOneShot=false)
References IsLocal, FindNode, CNode::IsBanned, ConnectNode, CSemaphoreGrant::MoveTo, CNode::grantOutbound, CNode::fNetworkNode, CNode::fOneShot.
Referenced by ThreadOpenConnections, ThreadOpenAddedConnections.
CNodeSignals& GetNodeSignals()
Referenced by Shutdown, AppInit2, CNode::CNode, CNode::~CNode.
void AddOneShot(string strDest)
References LOCK.
Referenced by AppInit2, ThreadDNSAddressSeed.
unsigned short GetListenPort()
References GetArg, Params.
Referenced by AppInit2, GetLocalAddress, AddLocal.
bool GetLocal(CService &addr, const CNetAddr *paddrPeer)
References fNoListen, LOCK, mapLocalHost.
Referenced by CActiveStormnode::ManageStatus, GetLocalAddress.
CAddress GetLocalAddress(const CNetAddr *paddrPeer)
References GetListenPort, GetLocal, CAddress::nServices, nLocalServices, CAddress::nTime, GetAdjustedTime.
Referenced by SendMessages, CNode::PushVersion, getinfo.
bool RecvLine(SOCKET hSocket, string &strLine)
References WSAGetLastError, WSAEMSGSIZE, WSAEWOULDBLOCK, WSAEINTR, WSAEINPROGRESS, MilliSleep.
void RelayInv(CInv &inv, const int minProtoVersion)
References LOCK, vNodes, CNode::nVersion, CNode::PushInventory.
Referenced by ProcessMessageInstantX, DoConsensusVote, CSandstormPool::CheckFinalTransaction, CBudgetProposalBroadcast::Relay, CBudgetVote::Relay, CFinalizedBudgetBroadcast::Relay, CFinalizedBudgetVote::Relay, CStormnodePaymentWinner::Relay, CStormnodeBroadcast::Relay, CStormnodePing::Relay.
int GetnScore(const CService &addr)
References LOCK, mapLocalHost, LOCAL_NONE.
bool IsPeerAddrLocalGood(CNode *pnode)
References fDiscover, CNode::addr, CNetAddr::IsRoutable, CNode::addrLocal, IsLimited, CNetAddr::GetNetwork.
static void AdvertizeLocal()
void SetReachable(enum Network net, bool fFlag)
References LOCK, NET_IPV6, NET_IPV4.
Referenced by AppInit2, AddLocal.
bool AddLocal(const CService &addr, int nScore)
References CNetAddr::IsRoutable, fDiscover, LOCAL_MANUAL, IsLimited, LogPrintf, CService::ToString, LOCK, mapLocalHost, LocalServiceInfo::nScore, LocalServiceInfo::nPort, CService::GetPort, SetReachable, CNetAddr::GetNetwork.
Referenced by AppInit2, AddLocal, BindListenPort.
bool AddLocal(const CNetAddr &addr, int nScore)
References AddLocal, GetListenPort.
void SetLimited(enum Network net, bool fLimited)
Make a particular network entirely off-limits (no automatic connects to it)
References NET_UNROUTABLE, LOCK.
Referenced by AppInit2.
bool IsLimited(enum Network net)
References LOCK.
Referenced by AppInit2, IsPeerAddrLocalGood, AddLocal, IsLimited, ThreadOpenConnections, DarkSilkGUI::setClientModel.
bool IsLimited(const CNetAddr &addr)
References IsLimited, CNetAddr::GetNetwork.
bool SeenLocal(const CService &addr)
vote for a local address
References LOCK, mapLocalHost.
bool IsLocal(const CService &addr)
check whether a given address is potentially local
References LOCK, mapLocalHost.
Referenced by ConnectNode, ThreadOpenConnections, OpenNetworkConnection, CNetAddr::IsRoutable, CNetAddr::GetGroup, BOOST_AUTO_TEST_CASE.
bool IsReachable(enum Network net)
check whether a given network is one we can probably connect to
References LOCK.
Referenced by IsReachable.
bool IsReachable(const CNetAddr &addr)
check whether a given address is in a network we can probably connect to
References CNetAddr::GetNetwork, IsReachable.
void AddressCurrentlyConnected(const CService &addr)
References CAddrMan::Connected.
CNode* FindNode(const CNetAddr &ip)
References LOCK, vNodes, CNode::addr.
Referenced by ConnectNode, OpenNetworkConnection, CSandstormPool::RelayIn.
CNode* FindNode(const std::string &addrName)
References LOCK, vNodes, CNode::addrName.
CNode* FindNode(const CService &addr)
References LOCK, vNodes, CNode::addr.
CNode* ConnectNode(CAddress addrConnect, const char *pszDest, bool sandStormnode)
References IsLocal, FindNode, CNode::fSandStorm, CNode::AddRef, CService::ToString, GetAdjustedTime, CAddress::nTime, ConnectSocketByName, Params, nConnectTimeout, ConnectSocket, CAddrMan::Attempt, SOCKET_ERROR, LogPrintf, WSAGetLastError, LOCK, vNodes, CNode::nTimeConnected, GetTime.
Referenced by CActiveStormnode::ManageStatus, OpenNetworkConnection, addnode, stormnode, CSandStormRelay::RelayThroughNode, CSandstormPool::DoAutomaticDenominating.
void SocketSendData(CNode *pnode)
References CNode::vSendMsg, CNode::nSendOffset, CNode::hSocket, CNode::nLastSend, GetTime, CNode::nSendBytes, CNode::RecordBytesSent, CNode::nSendSize, WSAGetLastError, WSAEWOULDBLOCK, WSAEMSGSIZE, WSAEINTR, WSAEINPROGRESS, LogPrintf, CNode::CloseSocketDisconnect.
Referenced by ThreadSocketHandler, CNode::EndMessage.
void ThreadSocketHandler()
References LOCK, vNodes, CNode::fDisconnect, CNode::GetRefCount, CNode::vRecvMsg, CNode::nSendSize, CNode::ssSend, CDataStream::empty, CNode::grantOutbound, CSemaphoreGrant::Release, CNode::CloseSocketDisconnect, CNode::fNetworkNode, CNode::fInbound, CNode::Release, CNode::addr, TRY_LOCK, CNode::cs_vSend, CNode::cs_vRecvMsg, CNode::cs_inventory, uiInterface, CClientUIInterface::NotifyNumConnectionsChanged, CNode::hSocket, CNode::vSendMsg, SOCKET_ERROR, WSAGetLastError, LogPrintf, MilliSleep, CService::SetSockAddr, WSAEWOULDBLOCK, GetArg, closesocket, CNode::IsBanned, CService::ToString, CNetAddr::SetSpecial, WSAEMSGSIZE, WSAEINTR, WSAEINPROGRESS, INVALID_SOCKET, CNode::AddRef, CNode::GetTotalRecvSize, ReceiveFloodSize, CNode::ReceiveMsgBytes, CNode::nLastRecv, GetTime, CNode::nRecvBytes, CNode::RecordBytesRecv, SocketSendData, CNode::nTimeConnected, CNode::nLastSend, CNode::nPingNonceSent, CNode::nPingUsecStart, GetTimeMicros.
Referenced by StartNode.
void MapPort(bool)
Referenced by StartNode, StopNode, OptionsModel::setData.
void ThreadDNSAddressSeed()
References CAddrMan::size, GetBoolArg, MilliSleep, LOCK, vNodes, LogPrintf, Params, CChainParams::DNSSeeds, HaveNameProxy, AddOneShot, CDNSSeedData::host, LookupHost, CAddress::nTime, GetTime, GetRand, CAddrMan::Add, CDNSSeedData::name.
Referenced by StartNode.
void DumpAddresses()
References GetTimeMillis, CAddrDB::Write, CAddrMan::size.
Referenced by StartNode, StopNode.
static void ProcessOneShot()
void ThreadOpenConnections()
References mapArgs, mapMultiArgs, OpenNetworkConnection, MilliSleep, GetTime, CAddrMan::size, LogPrintf, CAddrMan::Add, Params, LOCK, vNodes, CNode::fInbound, CNode::addr, CNetAddr::GetGroup, GetAdjustedTime, CAddrMan::Select, CNetAddr::IsValid, IsLocal, IsLimited, CAddress::nLastTry, CService::GetPort, CChainParams::GetDefaultPort.
Referenced by StartNode.
void ThreadOpenAddedConnections()
References LOCK, vAddedNodes, mapMultiArgs, HaveNameProxy, OpenNetworkConnection, MilliSleep, Lookup, Params, CChainParams::GetDefaultPort, fNameLookup, setservAddNodeAddresses, vNodes, CNode::addr.
Referenced by StartNode.
static int64_t NodeSyncScore(const CNode *pnode)
static void StartSync(const vector< CNode * > &vNodes)
void ThreadMessageHandler()
References SetThreadPriority, THREAD_PRIORITY_BELOW_NORMAL, LOCK, vNodes, CNode::AddRef, GetRand, CNode::fDisconnect, TRY_LOCK, CNode::cs_vRecvMsg, CNodeSignals::ProcessMessages, CNode::CloseSocketDisconnect, CNode::nSendSize, SendBufferSize, CNode::vRecvGetData, CNode::vRecvMsg, CNode::cs_vSend, CNodeSignals::SendMessages, CNode::Release, MilliSleep.
Referenced by StartNode.
bool BindListenPort(const CService &addrBind, string &strError)
References strprintf, LogPrintf, CService::GetSockAddr, CService::ToString, WSAGetLastError, SOCKET_ERROR, CNetAddr::IsIPv6, WSAEADDRINUSE, _, CNetAddr::IsRoutable, fDiscover, AddLocal, LOCAL_BIND.
static void Discover(boost::thread_group &threadGroup)
void StartNode(boost::thread_group &threadGroup)
References GetArg, nLocalServices, GetBoolArg, LogPrintf, TraceThread, ThreadDNSAddressSeed, MapPort, ThreadSocketHandler, ThreadOpenAddedConnections, ThreadOpenConnections, ThreadMessageHandler, LoopForever, DumpAddresses, DUMP_ADDRESSES_INTERVAL.
Referenced by AppInit2.
bool StopNode()
References LogPrintf, MapPort, mempool, CTxMemPool::AddTransactionsUpdated, CSemaphore::post, DumpAddresses.
Referenced by Shutdown.
void RelayTransaction(const CTransaction &tx, const uint256 &hash)
References SER_NETWORK, CDataStream::reserve, RelayTransaction.
Referenced by RelayTransaction, sendrawtransaction, CWalletTx::RelayWalletTransaction.
void RelayTransaction(const CTransaction &tx, const uint256 &hash, const CDataStream &ss)
References MSG_TX, LOCK, vRelayExpiration, GetTime, mapRelay, RelayInventory.
void RelayTransactionLockReq(const CTransaction &tx, const uint256 &hash, bool relayToAll)
References MSG_TXLOCK_REQUEST, CTransaction::GetHash, LOCK, CNode::fRelayTxes, CNode::PushMessage.
Referenced by CWalletTx::RelayWalletTransaction.