netbase.h
Network
typedef CService proxyType
int nConnectTimeout
Referenced by AppInit2, ConnectNode.
bool fNameLookup
Referenced by AppInit2, ThreadOpenAddedConnections, ConnectSocketByName, getaddednodeinfo.
enum Network ParseNetwork(std::string net)
References NET_IPV4, NET_IPV6, NET_TOR, NET_I2P, NET_UNROUTABLE.
Referenced by AppInit2.
std::string GetNetworkName(enum Network net)
References NET_IPV4, NET_IPV6, NET_TOR, NET_I2P.
void SplitHostPort(std::string in, int &portOut, std::string &hostOut)
Referenced by Lookup, ConnectSocketByName.
bool SetProxy(enum Network net, CService addrProxy)
References NET_MAX, CNetAddr::IsValid, LOCK.
Referenced by AppInit2.
bool GetProxy(enum Network net, proxyType &proxyInfoOut)
References NET_MAX, LOCK.
Referenced by ConnectSocket, OptionsModel::data, OptionsModel::setData, getinfo.
bool IsProxy(const CNetAddr &addr)
References LOCK, NET_MAX.
Referenced by CNode::PushVersion.
bool SetNameProxy(CService addrProxy)
References CNetAddr::IsValid, LOCK.
Referenced by AppInit2.
bool HaveNameProxy()
References LOCK, CNetAddr::IsValid.
Referenced by ThreadDNSAddressSeed, ThreadOpenAddedConnections, ConnectSocketByName.
bool LookupHost(const char *pszName, std::vector< CNetAddr > &vIP, unsigned int nMaxSolutions=0, bool fAllowLookup=true)
Referenced by ThreadDNSAddressSeed, CNetAddr::CNetAddr.
bool Lookup(const char *pszName, CService &addr, int portDefault=0, bool fAllowLookup=true)
References Lookup.
bool Lookup(const char *pszName, std::vector< CService > &vAddr, int portDefault=0, bool fAllowLookup=true, unsigned int nMaxSolutions=0)
References SplitHostPort.
Referenced by AppInit2, leveldb::TEST, ThreadOpenAddedConnections, Lookup, LookupNumeric, CService::CService, getaddednodeinfo.
bool LookupNumeric(const char *pszName, CService &addr, int portDefault=0)
References Lookup.
Referenced by OptionsDialog::eventFilter.
bool ConnectSocket(const CService &addr, SOCKET &hSocketRet, int nTimeout, bool *outProxyConnectionFailed=0)
References I2PSession::Instance, SAM::StreamSessionAdapter::connect, GetProxy, CNetAddr::GetNetwork, INVALID_SOCKET, CNetAddr::ToStringIP, CService::GetPort.
Referenced by ConnectNode, ConnectSocketByName.
bool ConnectSocketByName(CService &addr, SOCKET &hSocketRet, const char *pszDest, int portDefault, int nTimeout, bool *outProxyConnectionFailed=0)
References SplitHostPort, INVALID_SOCKET, GetNameProxy, fNameLookup, HaveNameProxy, CNetAddr::IsValid, ConnectSocket.
Referenced by ConnectNode.