opt.c
void fill_block(__m128i *state, const uint8_t *ref_block, uint8_t *next_block)
References ARGON2_OWORDS_IN_BLOCK, BLAKE2_ROUND.
Referenced by generate_addresses, fill_segment.
void generate_addresses(const argon2_instance_t *instance, const argon2_position_t *position, uint64_t *pseudo_rands)
Referenced by fill_segment.
void fill_segment(const argon2_instance_t *instance, argon2_position_t position)
References state, Argon2_instance_t::type, Argon2_i, Argon2_instance_t::segment_length, generate_addresses, Argon2_position_t::pass, Argon2_position_t::slice, Argon2_position_t::lane, Argon2_instance_t::lane_length, Argon2_instance_t::memory, ARGON2_BLOCK_SIZE, block_::v, Argon2_instance_t::lanes, Argon2_position_t::index, index_alpha, fill_block.