pbkdf2.cpp
static uint32_t be32dec(const void *pp)
static void be32enc(void *pp, uint32_t x)
void HMAC_SHA256_Init(HMAC_SHA256_CTX *ctx, const void *_K, size_t Klen)
References HMAC_SHA256Context::ictx, HMAC_SHA256Context::octx.
Referenced by PBKDF2_SHA256.
void HMAC_SHA256_Update(HMAC_SHA256_CTX *ctx, const void *in, size_t len)
References HMAC_SHA256Context::ictx.
Referenced by PBKDF2_SHA256.
void HMAC_SHA256_Final(unsigned char digest[32], HMAC_SHA256_CTX *ctx)
References HMAC_SHA256Context::ictx, HMAC_SHA256Context::octx.
Referenced by PBKDF2_SHA256.
void PBKDF2_SHA256(const uint8_t *passwd, size_t passwdlen, const uint8_t *salt, size_t saltlen, uint64_t c, uint8_t *buf, size_t dkLen)
PBKDF2_SHA256(passwd, passwdlen, salt, saltlen, c, buf, dkLen): Compute PBKDF2(passwd, salt, c, dkLen) using HMAC-SHA256 as the PRF, and write the output to buf. The value dkLen must be at most 32 * (2^32 - 1).
References HMAC_SHA256_Init, HMAC_SHA256_Update, HMAC_SHA256_Final.
Referenced by scrypt_nosalt, scrypt.