block.h
const int64_t POW_DRIFT
const int64_t POS_DRIFT
bool CheckProofOfWork(uint256 hash, unsigned int nBits)
References CBigNum::SetCompact, Params, CBigNum::getuint256.
int64_t FutureDrift(int64_t nTime, bool fProofOfStake=false)
Referenced by CBlock::AcceptBlock, CBlock::CheckBlock, IsStandardTx.