ref.c
void fill_block(const block *prev_block, const block *ref_block, block *next_block)
References copy_block, xor_block, BLAKE2_ROUND_NOMSG, block_::v.
Referenced by generate_addresses, fill_segment.
void generate_addresses(const argon2_instance_t *instance, const argon2_position_t *position, uint64_t *pseudo_rands)
References init_block_value, block_::v, Argon2_position_t::pass, Argon2_position_t::lane, Argon2_position_t::slice, Argon2_instance_t::memory_blocks, Argon2_instance_t::passes, Argon2_instance_t::type, Argon2_instance_t::segment_length, ARGON2_ADDRESSES_IN_BLOCK, ARGON2_OWORDS_IN_BLOCK, fill_block.
Referenced by fill_segment.
void fill_segment(const argon2_instance_t *instance, argon2_position_t position)
References Argon2_instance_t::type, Argon2_i, Argon2_instance_t::segment_length, generate_addresses, Argon2_position_t::pass, Argon2_position_t::slice, Argon2_position_t::lane, Argon2_instance_t::lane_length, Argon2_instance_t::memory, block_::v, Argon2_instance_t::lanes, Argon2_position_t::index, index_alpha, fill_block.