rpcblockchain.cpp
void TxToJSON(const CTransaction &tx, const uint256 hashBlock, json_spirit::Object &entry)
Referenced by blockToJSON.
double GetDifficulty(const CBlockIndex *blockindex)
References pindexBest, GetLastBlockIndex, CBlockIndex::nBits.
Referenced by StatisticsPage::updateStatistics, GetPoWMHashPS, GetPoSKernelPS, blockToJSON, getdifficulty, getmininginfo, getstakinginfo, getinfo.
double GetPoWMHashPS()
References pindexGenesisBlock, CBlockIndex::IsProofOfWork, CBlockIndex::GetBlockTime, CBlockIndex::pnext, GetDifficulty.
Referenced by StatisticsPage::updateStatistics, getmininginfo.
double GetPoSKernelPS()
References pindexBest, CBlockIndex::IsProofOfStake, GetDifficulty, CBlockIndex::nTime, CBlockIndex::pprev.
Referenced by getmininginfo, getstakinginfo.
Object blockToJSON(const CBlock &block, const CBlockIndex *blockindex, bool fPrintTransactionDetail)
References CBlockHeader::GetHash, base_uint< BITS >::GetHex, CBlockIndex::IsInMainChain, nBestHeight, CBlockIndex::nHeight, GetSerializeSize, SER_NETWORK, CBlockHeader::nVersion, CBlockHeader::hashMerkleRoot, ValueFromAmount, CBlockIndex::nMint, CBlockHeader::GetBlockTime, CBlockHeader::nNonce, strprintf, CBlockHeader::nBits, GetDifficulty, leftTrim, CBlockIndex::GetBlockTrust, CBlockIndex::nChainTrust, CBlockIndex::pprev, CBlockIndex::GetBlockHash, CBlockIndex::pnext, CBlockIndex::IsProofOfStake, CBlockIndex::GeneratedStakeModifier, CBlockIndex::hashProof, CBlockIndex::GetStakeEntropyBit, CBlockIndex::nStakeModifier, CBlockIndex::bnStakeModifierV2, CBlock::vtx, CTransaction::GetHash, TxToJSON, CBlock::IsProofOfStake, HexStr, CBlock::vchBlockSig.
Referenced by getblock, getblockbynumber.
Value getbestblockhash(const Array &params, bool fHelp)
References hashBestChain, base_uint< BITS >::GetHex.
Value getblockcount(const Array &params, bool fHelp)
References nBestHeight.
Value getdifficulty(const Array &params, bool fHelp)
References GetDifficulty, GetLastBlockIndex, pindexBest.
Value getrawmempool(const Array &params, bool fHelp)
References mempool, CTxMemPool::queryHashes, hash, base_uint< BITS >::ToString.
Value getblockhash(const Array &params, bool fHelp)
References json_spirit::Value_impl< Config >::get_int, nBestHeight, FindBlockByHeight, CBlockIndex::phashBlock, base_uint< BITS >::GetHex.
Value getblock(const Array &params, bool fHelp)
References json_spirit::Value_impl< Config >::get_str, hash, mapBlockIndex, JSONRPCError, RPC_INVALID_ADDRESS_OR_KEY, CBlock::ReadFromDisk, blockToJSON.
Value getblockbynumber(const Array &params, bool fHelp)
References json_spirit::Value_impl< Config >::get_int, nBestHeight, mapBlockIndex, hashBestChain, CBlockIndex::nHeight, CBlockIndex::pprev, hash, CBlockIndex::phashBlock, CBlock::ReadFromDisk, blockToJSON.
Value getcheckpoint(const Array &params, bool fHelp)
References Checkpoints::AutoSelectSyncCheckpoint, CBlockIndex::GetBlockHash, base_uint< BITS >::ToString, CBlockIndex::nHeight, DateTimeStrFormat, CBlockIndex::GetBlockTime.