rpcclient.cpp
const CRPCConvertParam vRPCConvertParams[][]
CRPCConvertTable rpcCvtTable
Object CallRPC(const string &strMethod, const Array &params)
References mapArgs, strprintf, _, GetConfigFile, GetBoolArg, SSLIOStreamDevice< Protocol >::connect, GetArg, itostr, Params, MilliSleep, EncodeBase64, JSONRPCRequest, HTTPPost, ReadHTTPStatus, ReadHTTPMessage, MAX_SIZE, HTTP_UNAUTHORIZED, HTTP_BAD_REQUEST, HTTP_NOT_FOUND, HTTP_INTERNAL_SERVER_ERROR, json_spirit::read_string, json_spirit::Value_impl< Config >::get_obj.
Referenced by CommandLineRPC.
Array RPCConvertValues(const std::string &strMethod, const std::vector< std::string > &strParams)
References CRPCConvertTable::convert, json_spirit::read_string.
Referenced by RPCExecutor::request, CommandLineRPC.
int CommandLineRPC(int argc, char *argv[])
References IsSwitchChar, RPCConvertValues, CallRPC, json_spirit::find_value, json_spirit::Value_impl< Config >::type, json_spirit::null_type, json_spirit::write_string, json_spirit::Value_impl< Config >::get_obj, json_spirit::str_type, json_spirit::Value_impl< Config >::get_str, PrintException.
Referenced by AppInit.