rpcclient.h
int CommandLineRPC(int argc, char *argv[])
References IsSwitchChar, RPCConvertValues, CallRPC, json_spirit::find_value, json_spirit::Value_impl< Config >::type, json_spirit::null_type, json_spirit::write_string, json_spirit::Value_impl< Config >::get_obj, json_spirit::str_type, json_spirit::Value_impl< Config >::get_str, PrintException.
Referenced by AppInit.
json_spirit::Array RPCConvertValues(const std::string &strMethod, const std::vector< std::string > &strParams)
References CRPCConvertTable::convert, json_spirit::read_string.
Referenced by RPCExecutor::request, CommandLineRPC.