rpcdump.cpp
const std::locale formats[][]
Referenced by DecodeDumpTime.
const size_t formats_n
Referenced by DecodeDumpTime.
void EnsureWalletIsUnlocked()
Referenced by importwallet, dumpprivkey, dumpwallet, signrawtransaction.
std::time_t pt_to_time_t(const bt::ptime &pt)
Referenced by DecodeDumpTime.
int64_t DecodeDumpTime(const std::string &s)
References formats_n, formats, pt_to_time_t.
Referenced by importwallet.
static std::string EncodeDumpTime(int64_t nTime)
static std::string EncodeDumpString(const std::string &str)
std::string DecodeDumpString(const std::string &str)
Referenced by importwallet.
Value importprivkey(const Array &params, bool fHelp)
References json_spirit::Value_impl< Config >::get_str, json_spirit::get_str, CDarkSilkSecret::SetString, JSONRPCError, RPC_INVALID_ADDRESS_OR_KEY, fWalletUnlockStakingOnly, RPC_WALLET_UNLOCK_NEEDED, CDarkSilkSecret::GetKey, CKey::GetPubKey, CKey::VerifyPubKey, CPubKey::GetID, LOCK2, cs_main, pwalletMain, CWallet::cs_wallet, CWallet::MarkDirty, CWallet::SetAddressBookName, CCryptoKeyStore::HaveKey, json_spirit::Value_impl< Config >::null, CWallet::mapKeyMetadata, CWallet::AddKeyPubKey, RPC_WALLET_ERROR, CWallet::nTimeFirstKey, CWallet::ScanForWalletTransactions, pindexGenesisBlock, CWallet::ReacceptWalletTransactions.
Value importaddress(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, json_spirit::get_str, CDarkSilkAddress::IsValid, GetScriptForDestination, CDarkSilkAddress::Get, IsHex, ParseHex, JSONRPCError, RPC_INVALID_ADDRESS_OR_KEY, LOCK2, cs_main, pwalletMain, CWallet::cs_wallet, IsMine, ISMINE_SPENDABLE, RPC_WALLET_ERROR, CWallet::SetAddressBookName, CBasicKeyStore::HaveWatchOnly, json_spirit::Value_impl< Config >::null, CWallet::MarkDirty, CWallet::AddWatchOnly, CWallet::ScanForWalletTransactions, pindexGenesisBlock, CWallet::ReacceptWalletTransactions.
Value importwallet(const Array &params, bool fHelp)
References EnsureWalletIsUnlocked, json_spirit::get_str, JSONRPCError, RPC_INVALID_PARAMETER, pindexBest, CBlockIndex::nTime, pwalletMain, CWallet::ShowProgress, _, CDarkSilkSecret::SetString, CDarkSilkSecret::GetKey, CKey::GetPubKey, CKey::VerifyPubKey, CPubKey::GetID, CCryptoKeyStore::HaveKey, LogPrintf, DecodeDumpTime, DecodeDumpString, CKeyStore::AddKey, CWallet::mapKeyMetadata, CWallet::SetAddressBookName, CBlockIndex::pprev, CWallet::nTimeFirstKey, nBestHeight, CBlockIndex::nHeight, CWallet::ScanForWalletTransactions, CWallet::ReacceptWalletTransactions, CWallet::MarkDirty, RPC_WALLET_ERROR, json_spirit::Value_impl< Config >::null.
Value dumpprivkey(const Array &params, bool fHelp)
References EnsureWalletIsUnlocked, CBase58Data::SetString, JSONRPCError, RPC_INVALID_ADDRESS_OR_KEY, fWalletUnlockStakingOnly, RPC_WALLET_UNLOCK_NEEDED, CDarkSilkAddress::GetKeyID, RPC_TYPE_ERROR, pwalletMain, CCryptoKeyStore::GetKey, RPC_WALLET_ERROR, CBase58Data::ToString.
Value dumpwallet(const Array &params, bool fHelp)
References EnsureWalletIsUnlocked, json_spirit::get_str, JSONRPCError, RPC_INVALID_PARAMETER, pwalletMain, CWallet::GetKeyBirthTimes, CWallet::GetAllReserveKeys, strprintf, CLIENT_BUILD, CLIENT_DATE, GetTime, nBestHeight, hashBestChain, base_uint< BITS >::ToString, pindexBest, CBlockIndex::nTime, CBase58Data::ToString, CCryptoKeyStore::GetKey, CWallet::mapAddressBook, json_spirit::Value_impl< Config >::null.