rpcprotocol.cpp
const size_t POST_READ_SIZE
Referenced by ReadHTTPMessage.
string HTTPPost(const string &strMsg, const map< string, string > &mapRequestHeaders)
References FormatFullVersion, PAIRTYPE.
Referenced by CallRPC.
static string rfc1123Time()
string HTTPReply(int nStatus, const string &strMsg, bool keepalive)
References HTTP_UNAUTHORIZED, strprintf, FormatFullVersion, HTTP_OK, HTTP_BAD_REQUEST, HTTP_FORBIDDEN, HTTP_NOT_FOUND, HTTP_INTERNAL_SERVER_ERROR.
Referenced by ErrorReply, ServiceConnection.
bool ReadHTTPRequestLine(std::basic_istream< char > &stream, int &proto, string &http_method, string &http_uri)
References atoi.
Referenced by ServiceConnection.
int ReadHTTPStatus(std::basic_istream< char > &stream, int &proto)
References HTTP_INTERNAL_SERVER_ERROR, atoi.
Referenced by CallRPC.
int ReadHTTPHeaders(std::basic_istream< char > &stream, map< string, string > &mapHeadersRet)
References atoi.
Referenced by ReadHTTPMessage.
int ReadHTTPMessage(std::basic_istream< char > &stream, map< string, string > &mapHeadersRet, string &strMessageRet, int nProto, size_t max_size)
References ReadHTTPHeaders, HTTP_INTERNAL_SERVER_ERROR, POST_READ_SIZE, HTTP_OK.
Referenced by CallRPC, ServiceConnection.
string JSONRPCRequest(const string &strMethod, const Array &params, const Value &id)
References json_spirit::write_string.
Referenced by CallRPC.
Object JSONRPCReplyObj(const Value &result, const Value &error, const Value &id)
References json_spirit::Value_impl< Config >::type, json_spirit::null_type.
Referenced by JSONRPCReply.
string JSONRPCReply(const Value &result, const Value &error, const Value &id)
References JSONRPCReplyObj, json_spirit::write_string.
Referenced by ErrorReply, ServiceConnection.
Object JSONRPCError(int code, const string &message)
Referenced by getblock, importprivkey, importaddress, importwallet, dumpprivkey, dumpwallet, getstakesubsidy, checkkernel, getworkex, getwork, getblocktemplate, submitblock, verifymessage, addnode, getaddednodeinfo, getrawtransaction, createrawtransaction, decoderawtransaction, signrawtransaction, sendrawtransaction, searchrawtransactions, RPCTypeCheck, AmountFromValue, ParseHashV, ParseHexV, JSONRequest::parse, ServiceConnection, CRPCTable::execute, snbudget, snbudgetvoteraw, sandstorm, EnsureWalletIsUnlocked, AccountFromValue, getnewpubkey, getnewaddress, GetAccountAddress, setaccount, getaccount, SendMoney, sendtoaddress, signmessage, getreceivedbyaddress, movecmd, sendfrom, sendmany, listtransactions, listsinceblock, gettransaction, backupwallet, keypoolrefill, walletpassphrase, walletpassphrasechange, walletlock, encryptwallet, sendtostealthaddress.