rpcrawtransaction.cpp
void ScriptPubKeyToJSON(const CScript &scriptPubKey, Object &out, bool fIncludeHex)
References CScript::ToString, HexStr, ExtractDestinations, GetTxnOutputType.
Referenced by TxToJSON, decodescript.
void TxToJSON(const CTransaction &tx, const uint256 hashBlock, Object &entry)
References CTransaction::GetHash, base_uint< BITS >::GetHex, CTransaction::nVersion, CTransaction::nTime, CTransaction::nLockTime, CTransaction::vin, CTransaction::IsCoinBase, HexStr, CTxIn::scriptSig, CTxIn::prevout, COutPoint::hash, COutPoint::n, CScript::ToString, CTxIn::nSequence, CTransaction::vout, ValueFromAmount, CTxOut::nValue, ScriptPubKeyToJSON, CTxOut::scriptPubKey, mapBlockIndex, CBlockIndex::IsInMainChain, nBestHeight, CBlockIndex::nHeight, CBlockIndex::nTime.
Referenced by blockToJSON, getrawtransaction, decoderawtransaction, searchrawtransactions, gettransaction.
Value getrawtransaction(const Array &params, bool fHelp)
References hash, base_uint< BITS >::SetHex, json_spirit::get_str, GetTransaction, JSONRPCError, RPC_INVALID_ADDRESS_OR_KEY, SER_NETWORK, HexStr, CDataStream::begin, CDataStream::end, TxToJSON.
Value createrawtransaction(const Array &params, bool fHelp)
References RPCTypeCheck, json_spirit::array_type, json_spirit::obj_type, json_spirit::Value_impl< Config >::get_obj, json_spirit::find_value, json_spirit::Value_impl< Config >::type, json_spirit::str_type, JSONRPCError, RPC_INVALID_PARAMETER, json_spirit::Value_impl< Config >::get_str, IsHex, json_spirit::int_type, json_spirit::Value_impl< Config >::get_int, CMutableTransaction::vin, json_spirit::Pair_impl< Config >::name_, CDarkSilkAddress::IsValid, RPC_INVALID_ADDRESS_OR_KEY, CScript::SetDestination, CDarkSilkAddress::Get, AmountFromValue, json_spirit::Pair_impl< Config >::value_, CMutableTransaction::vout, SER_NETWORK, HexStr, CDataStream::begin, CDataStream::end.
Value decoderawtransaction(const Array &params, bool fHelp)
References RPCTypeCheck, json_spirit::str_type, ParseHex, json_spirit::get_str, SER_NETWORK, JSONRPCError, RPC_DESERIALIZATION_ERROR, TxToJSON.
Value decodescript(const Array &params, bool fHelp)
References RPCTypeCheck, json_spirit::str_type, json_spirit::get_str, ParseHexV, ScriptPubKeyToJSON, CScript::GetID.
Value signrawtransaction(const Array &params, bool fHelp)
References HelpRequiringPassphrase, RPCTypeCheck, json_spirit::str_type, json_spirit::array_type, ParseHex, json_spirit::get_str, SER_NETWORK, CDataStream::empty, JSONRPCError, RPC_DESERIALIZATION_ERROR, CMutableTransaction::vin, txdb, CTransaction::vin, CTransactionPoS::FetchInputs, CTxIn::prevout, COutPoint::hash, COutPoint::n, json_spirit::null_type, CDarkSilkSecret::SetString, json_spirit::Value_impl< Config >::get_str, RPC_INVALID_ADDRESS_OR_KEY, CDarkSilkSecret::GetKey, CKeyStore::AddKey, EnsureWalletIsUnlocked, json_spirit::Value_impl< Config >::type, json_spirit::obj_type, json_spirit::Value_impl< Config >::get_obj, json_spirit::int_type, json_spirit::find_value, IsHex, base_uint< BITS >::SetHex, ParseHexV, CBasicKeyStore::AddCScript, SIGHASH_ALL, SIGHASH_ANYONECANPAY, SIGHASH_NONE, SIGHASH_SINGLE, RPC_INVALID_PARAMETER, CTxIn::scriptSig, CScript::clear, CombineSignatures, VerifyScript, HexStr, CDataStream::begin, CDataStream::end.
Value sendrawtransaction(const Array &params, bool fHelp)
References RPCTypeCheck, json_spirit::str_type, ParseHex, json_spirit::get_str, SER_NETWORK, JSONRPCError, RPC_DESERIALIZATION_ERROR, CTransaction::GetHash, GetTransaction, RPC_INVALID_ADDRESS_OR_KEY, base_uint< BITS >::GetHex, state, AcceptToMemoryPool, mempool, RelayTransaction.
Value searchrawtransactions(const Array &params, bool fHelp)
References json_spirit::get_str, CDarkSilkAddress::IsValid, JSONRPCError, RPC_INVALID_ADDRESS_OR_KEY, CDarkSilkAddress::Get, FindTransactionsByDestination, RPC_DATABASE_ERROR, GetTransaction, SER_NETWORK, HexStr, CDataStream::begin, CDataStream::end, TxToJSON.