rpcserver.cpp
std::string strRPCUserColonPass
asio::io_service* rpc_io_service
map<string, boost::shared_ptr<deadline_timer> > deadlineTimers
ssl::context* rpc_ssl_context
boost::thread_group* rpc_worker_group
const CRPCCommand vRPCCommands[][]
const CRPCTable tableRPC
Referenced by RPCExecutor::request, help, ServiceConnection, CRPCTable::execute.
void RPCTypeCheck(const Array &params, const list< Value_type > &typesExpected, bool fAllowNull)
References json_spirit::Value_impl< Config >::type, json_spirit::null_type, strprintf, JSONRPCError, RPC_TYPE_ERROR.
Referenced by getstakesubsidy, checkkernel, createrawtransaction, decoderawtransaction, decodescript, signrawtransaction, sendrawtransaction.
void RPCTypeCheck(const Object &o, const map< string, Value_type > &typesExpected, bool fAllowNull)
References PAIRTYPE, json_spirit::find_value, json_spirit::Value_impl< Config >::type, json_spirit::null_type, JSONRPCError, RPC_TYPE_ERROR, strprintf.
CAmount AmountFromValue(const Value &value)
References json_spirit::Value_impl< Config >::get_real, JSONRPCError, RPC_TYPE_ERROR, roundint64, MoneyRange.
Referenced by createrawtransaction, snbudget, sendtoaddress, movecmd, sendfrom, sendmany, reservebalance, settxfee, sendtostealthaddress.
Value ValueFromAmount(const CAmount &amount)
Referenced by blockToJSON, getinfo, TxToJSON, snbudget, listaddressgroupings, getreceivedbyaddress, getbalance, ListReceived, ListTransactions, AcentryToJSON, listaccounts, gettransaction, reservebalance, checkwallet, repairwallet.
uint256 ParseHashV(const Value &v, string strName)
References json_spirit::Value_impl< Config >::type, json_spirit::str_type, json_spirit::Value_impl< Config >::get_str, IsHex, JSONRPCError, RPC_INVALID_PARAMETER, base_uint< BITS >::SetHex.
Referenced by ParseHashO, snbudget, snbudgetvoteraw.
uint256 ParseHashO(const Object &o, string strKey)
References ParseHashV, json_spirit::find_value.
vector<unsigned char> ParseHexV(const Value &v, string strName)
References json_spirit::Value_impl< Config >::type, json_spirit::str_type, json_spirit::Value_impl< Config >::get_str, IsHex, JSONRPCError, RPC_INVALID_PARAMETER, ParseHex.
Referenced by decodescript, signrawtransaction, ParseHexO, addredeemscript.
vector<unsigned char> ParseHexO(const Object &o, string strKey)
References ParseHexV, json_spirit::find_value.
Value help(const Array &params, bool fHelp)
References json_spirit::get_str, tableRPC, CRPCTable::help.
Referenced by main.
Value stop(const Array &params, bool fHelp)
References StartShutdown.
bool HTTPAuthorized(map< string, string > &mapHeaders)
References DecodeBase64, TimingResistantEqual.
Referenced by ServiceConnection.
void ErrorReply(std::ostream &stream, const Object &objError, const Value &id)
References HTTP_INTERNAL_SERVER_ERROR, json_spirit::find_value, RPC_INVALID_REQUEST, HTTP_BAD_REQUEST, RPC_METHOD_NOT_FOUND, HTTP_NOT_FOUND, JSONRPCReply, HTTPReply.
Referenced by ServiceConnection.
bool ClientAllowed(const boost::asio::ip::address &address)
References mapMultiArgs, WildcardMatch.
void ServiceConnection(AcceptedConnection *conn)
References ReadHTTPRequestLine, AcceptedConnection::stream, ReadHTTPMessage, MAX_SIZE, HTTPReply, HTTP_NOT_FOUND, HTTP_UNAUTHORIZED, HTTPAuthorized, LogPrintf, AcceptedConnection::peer_address_to_string, mapArgs, MilliSleep, json_spirit::read_string, JSONRPCError, RPC_PARSE_ERROR, json_spirit::Value_impl< Config >::type, json_spirit::obj_type, JSONRequest::parse, tableRPC, CRPCTable::execute, JSONRequest::strMethod, JSONRequest::params, JSONRPCReply, JSONRequest::id, json_spirit::array_type, json_spirit::Value_impl< Config >::get_array, HTTP_OK, ErrorReply.
static void RPCAcceptHandler(boost::shared_ptr< basic_socket_acceptor< Protocol, SocketAcceptorService > > acceptor, ssl::context &context, bool fUseSSL, AcceptedConnection *conn, const boost::system::error_code &error)
Accept and handle incoming connection.
static void RPCListen(boost::shared_ptr< basic_socket_acceptor< Protocol, SocketAcceptorService > > acceptor, ssl::context &context, const bool fUseSSL)
Sets up I/O resources to accept and handle a new connection.
void StartRPCThreads()
References mapArgs, Params, GetRandBytes, strprintf, _, uiInterface, CClientUIInterface::ThreadSafeMessageBox, GetConfigFile, EncodeBase58, CClientUIInterface::MSG_ERROR, StartShutdown, GetBoolArg, GetArg, GetDataDir, LogPrintf.
Referenced by AppInit2.
void StopRPCThreads()
Referenced by Shutdown.
void RPCRunHandler(const boost::system::error_code &err, boost::function< void(void)> func)
References func.
Referenced by RPCRunLater.
void RPCRunLater(const std::string &name, boost::function< void(void)> func, int64_t nSeconds)
References name, RPCRunHandler, func.
Referenced by walletpassphrase.
static Object JSONRPCExecOne(const Value &req)
static string JSONRPCExecBatch(const Array &vReq)
std::string HelpExampleCli(string methodname, string args)
Referenced by importaddress, getnetworkinfo, createmultisig, getnewaddress, getaccountaddress, setaccount, getaccount, getaddressesbyaccount, sendtoaddress, listaddressgroupings, signmessage, getreceivedbyaddress, getreceivedbyaccount, getbalance, movecmd, sendfrom, sendmany, addmultisigaddress, listreceivedbyaddress, listreceivedbyaccount, listtransactions, listaccounts, listsinceblock, gettransaction, backupwallet, keypoolrefill, walletpassphrase, walletpassphrasechange, walletlock, encryptwallet, settxfee.
std::string HelpExampleRpc(string methodname, string args)
Referenced by importaddress, getnetworkinfo, createmultisig, getnewaddress, getaccountaddress, setaccount, getaccount, getaddressesbyaccount, sendtoaddress, listaddressgroupings, signmessage, getreceivedbyaddress, getreceivedbyaccount, getbalance, movecmd, sendfrom, sendmany, addmultisigaddress, listreceivedbyaddress, listreceivedbyaccount, listtransactions, listaccounts, listsinceblock, gettransaction, backupwallet, keypoolrefill, walletpassphrase, walletpassphrasechange, walletlock, encryptwallet, settxfee.