rpcserver.h
typedef json_spirit::Value(* rpcfn_type) (const json_spirit::Array &params, bool fHelp))(const json_spirit::Array &params, bool fHelp)
const CRPCTable tableRPC
Referenced by RPCExecutor::request, help, ServiceConnection, CRPCTable::execute.
int64_t nWalletUnlockTime
Referenced by getinfo, walletpassphrase, walletlock.
void StartRPCThreads()
References mapArgs, Params, GetRandBytes, strprintf, _, uiInterface, CClientUIInterface::ThreadSafeMessageBox, GetConfigFile, EncodeBase58, CClientUIInterface::MSG_ERROR, StartShutdown, GetBoolArg, GetArg, GetDataDir, LogPrintf.
Referenced by AppInit2.
void StopRPCThreads()
Referenced by Shutdown.
void RPCTypeCheck(const json_spirit::Array &params, const std::list< json_spirit::Value_type > &typesExpected, bool fAllowNull=false)
void RPCTypeCheck(const json_spirit::Object &o, const std::map< std::string, json_spirit::Value_type > &typesExpected, bool fAllowNull=false)
void RPCRunLater(const std::string &name, boost::function< void(void)> func, int64_t nSeconds)
References name, RPCRunHandler, func.
Referenced by walletpassphrase.
void InitRPCMining()
References pwalletMain.
Referenced by AppInit2.
void ShutdownRPCMining()
Referenced by Shutdown.
CAmount AmountFromValue(const json_spirit::Value &value)
References json_spirit::Value_impl< Config >::get_real, JSONRPCError, RPC_TYPE_ERROR, roundint64, MoneyRange.
Referenced by createrawtransaction, snbudget, sendtoaddress, movecmd, sendfrom, sendmany, reservebalance, settxfee, sendtostealthaddress.
json_spirit::Value ValueFromAmount(const CAmount &amount)
Referenced by blockToJSON, getinfo, TxToJSON, snbudget, listaddressgroupings, getreceivedbyaddress, getbalance, ListReceived, ListTransactions, AcentryToJSON, listaccounts, gettransaction, reservebalance, checkwallet, repairwallet.
double GetDifficulty(const CBlockIndex *blockindex=NULL)
References pindexBest, GetLastBlockIndex, CBlockIndex::nBits.
Referenced by StatisticsPage::updateStatistics, GetPoWMHashPS, GetPoSKernelPS, blockToJSON, getdifficulty, getmininginfo, getstakinginfo, getinfo.
double GetPoWMHashPS()
References pindexGenesisBlock, CBlockIndex::IsProofOfWork, CBlockIndex::GetBlockTime, CBlockIndex::pnext, GetDifficulty.
Referenced by StatisticsPage::updateStatistics, getmininginfo.
double GetPoSKernelPS()
References pindexBest, CBlockIndex::IsProofOfStake, GetDifficulty, CBlockIndex::nTime, CBlockIndex::pprev.
std::string HelpRequiringPassphrase()
References pwalletMain, CCryptoKeyStore::IsCrypted.
Referenced by spork, signrawtransaction, sandstorm, sendtoaddress, signmessage, sendfrom, sendmany, keypoolrefill, sendtostealthaddress.
std::string HelpExampleCli(std::string methodname, std::string args)
std::string HelpExampleRpc(std::string methodname, std::string args)
void EnsureWalletIsUnlocked()
References pwalletMain, CCryptoKeyStore::IsLocked, JSONRPCError, RPC_WALLET_UNLOCK_NEEDED, fWalletUnlockStakingOnly.
Referenced by sendtoaddress, signmessage, sendfrom, sendmany, keypoolrefill.
uint256 ParseHashV(const json_spirit::Value &v, std::string strName)
uint256 ParseHashO(const json_spirit::Object &o, std::string strKey)
std::vector<unsigned char> ParseHexV(const json_spirit::Value &v, std::string strName)
std::vector<unsigned char> ParseHexO(const json_spirit::Object &o, std::string strKey)
json_spirit::Value getconnectioncount(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getpeerinfo(const json_spirit::Array &params, bool fHelp)
json_spirit::Value ping(const json_spirit::Array &params, bool fHelp)
json_spirit::Value addnode(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getaddednodeinfo(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getnettotals(const json_spirit::Array &params, bool fHelp)
json_spirit::Value dumpwallet(const json_spirit::Array &params, bool fHelp)
json_spirit::Value importwallet(const json_spirit::Array &params, bool fHelp)
json_spirit::Value dumpprivkey(const json_spirit::Array &params, bool fHelp)
json_spirit::Value importprivkey(const json_spirit::Array &params, bool fHelp)
json_spirit::Value importaddress(const json_spirit::Array &params, bool fHelp)
json_spirit::Value sendalert(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getsubsidy(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getstakesubsidy(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getmininginfo(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getstakinginfo(const json_spirit::Array &params, bool fHelp)
json_spirit::Value checkkernel(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getwork(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getworkex(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getblocktemplate(const json_spirit::Array &params, bool fHelp)
json_spirit::Value submitblock(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getnewaddress(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getaccountaddress(const json_spirit::Array &params, bool fHelp)
json_spirit::Value setaccount(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getaccount(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getaddressesbyaccount(const json_spirit::Array &params, bool fHelp)
json_spirit::Value sendtoaddress(const json_spirit::Array &params, bool fHelp)
json_spirit::Value signmessage(const json_spirit::Array &params, bool fHelp)
json_spirit::Value verifymessage(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getreceivedbyaddress(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getreceivedbyaccount(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getbalance(const json_spirit::Array &params, bool fHelp)
json_spirit::Value movecmd(const json_spirit::Array &params, bool fHelp)
json_spirit::Value sendfrom(const json_spirit::Array &params, bool fHelp)
json_spirit::Value sendmany(const json_spirit::Array &params, bool fHelp)
json_spirit::Value addredeemscript(const json_spirit::Array &params, bool fHelp)
json_spirit::Value listreceivedbyaddress(const json_spirit::Array &params, bool fHelp)
json_spirit::Value listreceivedbyaccount(const json_spirit::Array &params, bool fHelp)
json_spirit::Value listtransactions(const json_spirit::Array &params, bool fHelp)
json_spirit::Value listaddressgroupings(const json_spirit::Array &params, bool fHelp)
json_spirit::Value listaccounts(const json_spirit::Array &params, bool fHelp)
json_spirit::Value listsinceblock(const json_spirit::Array &params, bool fHelp)
json_spirit::Value gettransaction(const json_spirit::Array &params, bool fHelp)
json_spirit::Value backupwallet(const json_spirit::Array &params, bool fHelp)
json_spirit::Value keypoolrefill(const json_spirit::Array &params, bool fHelp)
json_spirit::Value walletpassphrase(const json_spirit::Array &params, bool fHelp)
json_spirit::Value walletpassphrasechange(const json_spirit::Array &params, bool fHelp)
json_spirit::Value walletlock(const json_spirit::Array &params, bool fHelp)
json_spirit::Value encryptwallet(const json_spirit::Array &params, bool fHelp)
json_spirit::Value validateaddress(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getinfo(const json_spirit::Array &params, bool fHelp)
json_spirit::Value reservebalance(const json_spirit::Array &params, bool fHelp)
json_spirit::Value addmultisigaddress(const json_spirit::Array &params, bool fHelp)
json_spirit::Value createmultisig(const json_spirit::Array &params, bool fHelp)
json_spirit::Value checkwallet(const json_spirit::Array &params, bool fHelp)
json_spirit::Value repairwallet(const json_spirit::Array &params, bool fHelp)
json_spirit::Value resendtx(const json_spirit::Array &params, bool fHelp)
json_spirit::Value makekeypair(const json_spirit::Array &params, bool fHelp)
json_spirit::Value validatepubkey(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getnewpubkey(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getrawtransaction(const json_spirit::Array &params, bool fHelp)
json_spirit::Value searchrawtransactions(const json_spirit::Array &params, bool fHelp)
json_spirit::Value listunspent(const json_spirit::Array &params, bool fHelp)
json_spirit::Value createrawtransaction(const json_spirit::Array &params, bool fHelp)
json_spirit::Value decoderawtransaction(const json_spirit::Array &params, bool fHelp)
json_spirit::Value decodescript(const json_spirit::Array &params, bool fHelp)
json_spirit::Value signrawtransaction(const json_spirit::Array &params, bool fHelp)
json_spirit::Value sendrawtransaction(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getbestblockhash(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getblockcount(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getdifficulty(const json_spirit::Array &params, bool fHelp)
json_spirit::Value settxfee(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getrawmempool(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getblockhash(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getblock(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getblockbynumber(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getcheckpoint(const json_spirit::Array &params, bool fHelp)
json_spirit::Value getnewstealthaddress(const json_spirit::Array &params, bool fHelp)
json_spirit::Value liststealthaddresses(const json_spirit::Array &params, bool fHelp)
json_spirit::Value importstealthaddress(const json_spirit::Array &params, bool fHelp)
json_spirit::Value sendtostealthaddress(const json_spirit::Array &params, bool fHelp)
json_spirit::Value scanforalltxns(const json_spirit::Array &params, bool fHelp)
json_spirit::Value sandstorm(const json_spirit::Array &params, bool fHelp)
json_spirit::Value spork(const json_spirit::Array &params, bool fHelp)
json_spirit::Value stormnode(const json_spirit::Array &params, bool fHelp)
json_spirit::Value snbudget(const json_spirit::Array &params, bool fHelp)
json_spirit::Value snbudgetvoteraw(const json_spirit::Array &params, bool fHelp)
json_spirit::Value snfinalbudget(const json_spirit::Array &params, bool fHelp)
json_spirit::Value stormnodelist(const json_spirit::Array &params, bool fHelp)
json_spirit::Value smsgenable(const json_spirit::Array &params, bool fHelp)
json_spirit::Value smsgdisable(const json_spirit::Array &params, bool fHelp)
json_spirit::Value smsglocalkeys(const json_spirit::Array &params, bool fHelp)
json_spirit::Value smsgoptions(const json_spirit::Array &params, bool fHelp)
json_spirit::Value smsgscanchain(const json_spirit::Array &params, bool fHelp)
json_spirit::Value smsgscanbuckets(const json_spirit::Array &params, bool fHelp)
json_spirit::Value smsgaddkey(const json_spirit::Array &params, bool fHelp)
json_spirit::Value smsggetpubkey(const json_spirit::Array &params, bool fHelp)
json_spirit::Value smsgsend(const json_spirit::Array &params, bool fHelp)
json_spirit::Value smsgsendanon(const json_spirit::Array &params, bool fHelp)
json_spirit::Value smsginbox(const json_spirit::Array &params, bool fHelp)
json_spirit::Value smsgoutbox(const json_spirit::Array &params, bool fHelp)
json_spirit::Value smsgbuckets(const json_spirit::Array &params, bool fHelp)