rpcwallet.cpp
int64_t nWalletUnlockTime
Referenced by getinfo, walletpassphrase, walletlock.
CCriticalSection cs_nWalletUnlockTime
void TxToJSON(const CTransaction &tx, const uint256 hashBlock, json_spirit::Object &entry)
References CTransaction::GetHash, base_uint< BITS >::GetHex, CTransaction::nVersion, CTransaction::nTime, CTransaction::nLockTime, CTransaction::vin, CTransaction::IsCoinBase, HexStr, CTxIn::scriptSig, CTxIn::prevout, COutPoint::hash, COutPoint::n, CScript::ToString, CTxIn::nSequence, CTransaction::vout, ValueFromAmount, CTxOut::nValue, ScriptPubKeyToJSON, CTxOut::scriptPubKey, mapBlockIndex, CBlockIndex::IsInMainChain, nBestHeight, CBlockIndex::nHeight, CBlockIndex::nTime.
Referenced by getrawtransaction, decoderawtransaction, searchrawtransactions, gettransaction.
static void accountingDeprecationCheck()
std::string HelpRequiringPassphrase()
References pwalletMain, CCryptoKeyStore::IsCrypted.
Referenced by spork, signrawtransaction, sandstorm, sendtoaddress, signmessage, sendfrom, sendmany, keypoolrefill, sendtostealthaddress.
void EnsureWalletIsUnlocked()
References pwalletMain, CCryptoKeyStore::IsLocked, JSONRPCError, RPC_WALLET_UNLOCK_NEEDED, fWalletUnlockStakingOnly.
Referenced by importwallet, dumpprivkey, dumpwallet, signrawtransaction, sendtoaddress, signmessage, sendfrom, sendmany, keypoolrefill.
void WalletTxToJSON(const CWalletTx &wtx, Object &entry)
References CMerkleTx::GetDepthInMainChain, GetIXConfirmations, CTransaction::GetHash, CTransaction::IsCoinBase, CTransaction::IsCoinStake, CMerkleTx::hashBlock, base_uint< BITS >::GetHex, CMerkleTx::nIndex, mapBlockIndex, hash, CWalletTx::GetConflicts, CWalletTx::GetTxTime, CWalletTx::nTimeReceived, PAIRTYPE, CWalletTx::mapValue.
Referenced by ListTransactions, gettransaction.
string AccountFromValue(const Value &value)
References json_spirit::Value_impl< Config >::get_str, JSONRPCError, RPC_WALLET_INVALID_ACCOUNT_NAME.
Referenced by getnewpubkey, getnewaddress, getaccountaddress, setaccount, getaddressesbyaccount, getreceivedbyaccount, getbalance, movecmd, sendfrom, sendmany, addmultisigaddress, addredeemscript.
CScript _createmultisig(const Array &params)
References strprintf, PRIszu, pwalletMain, CDarkSilkAddress::IsValid, CDarkSilkAddress::GetKeyID, CCryptoKeyStore::GetPubKey, CPubKey::IsFullyValid, IsHex, ParseHex, CScript::SetMultisig.
Referenced by createmultisig.
Value createmultisig(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, _createmultisig, CScript::GetID, CBase58Data::ToString, HexStr.
Value getnewpubkey(const Array &params, bool fHelp)
References AccountFromValue, pwalletMain, CCryptoKeyStore::IsLocked, CWallet::TopUpKeyPool, CWallet::GetKeyFromPool, JSONRPCError, RPC_WALLET_KEYPOOL_RAN_OUT, CPubKey::GetID, CWallet::SetAddressBookName, HexStr, CPubKey::begin, CPubKey::end.
Value getnewaddress(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, AccountFromValue, pwalletMain, CCryptoKeyStore::IsLocked, CWallet::TopUpKeyPool, CWallet::GetKeyFromPool, JSONRPCError, RPC_WALLET_KEYPOOL_RAN_OUT, CPubKey::GetID, CWallet::SetAddressBookName, CBase58Data::ToString.
CDarkSilkAddress GetAccountAddress(string strAccount, bool bForceNew=false)
References pwalletMain, CWallet::strWalletFile, CWalletDB::ReadAccount, CAccount::vchPubKey, CPubKey::IsValid, CScript::SetDestination, CPubKey::GetID, CWallet::mapWallet, CTransaction::vout, CTxOut::scriptPubKey, CWallet::GetKeyFromPool, JSONRPCError, RPC_WALLET_KEYPOOL_RAN_OUT, CWallet::SetAddressBookName, CWalletDB::WriteAccount.
Referenced by getaccountaddress, setaccount.
Value getaccountaddress(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, AccountFromValue, GetAccountAddress, CBase58Data::ToString.
Value setaccount(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, json_spirit::get_str, CDarkSilkAddress::IsValid, JSONRPCError, RPC_INVALID_ADDRESS_OR_KEY, AccountFromValue, IsMine, pwalletMain, CDarkSilkAddress::Get, CWallet::mapAddressBook, GetAccountAddress, CWallet::SetAddressBookName, RPC_MISC_ERROR.
Value getaccount(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, json_spirit::get_str, CDarkSilkAddress::IsValid, JSONRPCError, RPC_INVALID_ADDRESS_OR_KEY, pwalletMain, CWallet::mapAddressBook, CDarkSilkAddress::Get.
Value getaddressesbyaccount(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, AccountFromValue, PAIRTYPE, pwalletMain, CWallet::mapAddressBook, CBase58Data::ToString.
void SendMoney(const CTxDestination &address, CAmount nValue, CWalletTx &wtxNew, bool fUseIX=false, bool fUseSS=false)
References JSONRPCError, RPC_INVALID_PARAMETER, pwalletMain, CWallet::GetBalance, RPC_WALLET_INSUFFICIENT_FUNDS, CCryptoKeyStore::IsLocked, LogPrintf, RPC_WALLET_ERROR, GetScriptForDestination, CWallet::CreateTransaction, ONLY_DENOMINATED, ALL_COINS, strprintf, FormatMoney, CWallet::CommitTransaction.
Referenced by sendtoaddress, CWallet::SendMoneyToDestination.
Value sendtoaddress(const Array &params, bool fHelp)
References HelpRequiringPassphrase, HelpExampleCli, HelpExampleRpc, json_spirit::get_str, IsStealthAddress, sendtostealthaddress, CDarkSilkAddress::IsValid, JSONRPCError, RPC_INVALID_ADDRESS_OR_KEY, AmountFromValue, json_spirit::null_type, CWalletTx::mapValue, pwalletMain, CCryptoKeyStore::IsLocked, RPC_WALLET_UNLOCK_NEEDED, CWallet::SendMoneyToDestination, CDarkSilkAddress::Get, RPC_WALLET_ERROR, EnsureWalletIsUnlocked, SendMoney.
Value listaddressgroupings(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, pwalletMain, CWallet::GetAddressBalances, CWallet::GetAddressGroupings, ValueFromAmount, LOCK, CWallet::cs_wallet, CWallet::mapAddressBook.
Value signmessage(const Array &params, bool fHelp)
References HelpRequiringPassphrase, HelpExampleCli, HelpExampleRpc, EnsureWalletIsUnlocked, CDarkSilkAddress::IsValid, JSONRPCError, RPC_TYPE_ERROR, CDarkSilkAddress::GetKeyID, pwalletMain, CCryptoKeyStore::GetKey, RPC_WALLET_ERROR, SER_GETHASH, strMessageMagic, CKey::SignCompact, CHashWriter::GetHash, RPC_INVALID_ADDRESS_OR_KEY, EncodeBase64.
Value getreceivedbyaddress(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, json_spirit::get_str, CDarkSilkAddress::IsValid, JSONRPCError, RPC_INVALID_ADDRESS_OR_KEY, CScript::SetDestination, CDarkSilkAddress::Get, IsMine, pwalletMain, CWallet::mapWallet, CTransaction::IsCoinBase, CTransaction::IsCoinStake, IsFinalTx, CTransaction::vout, CTxOut::scriptPubKey, CMerkleTx::GetDepthInMainChain, CTxOut::nValue, ValueFromAmount.
void GetAccountAddresses(string strAccount, set< CTxDestination > &setAddress)
References PAIRTYPE, pwalletMain, CWallet::mapAddressBook.
Referenced by getreceivedbyaccount.
Value getreceivedbyaccount(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, AccountFromValue, GetAccountAddresses, pwalletMain, CWallet::mapWallet, CTransaction::IsCoinBase, CTransaction::IsCoinStake, IsFinalTx, CTransaction::vout, ExtractDestination, CTxOut::scriptPubKey, IsMine, CMerkleTx::GetDepthInMainChain, CTxOut::nValue.
CAmount GetAccountBalance(CWalletDB &walletdb, const string &strAccount, int nMinDepth, const isminefilter &filter)
References pwalletMain, CWallet::mapWallet, IsFinalTx, CMerkleTx::GetBlocksToMaturity, CMerkleTx::GetDepthInMainChain, CWalletTx::GetAccountAmounts, CWalletDB::GetAccountCreditDebit.
Referenced by GetAccountBalance, getbalance, sendfrom, sendmany.
CAmount GetAccountBalance(const string &strAccount, int nMinDepth, const isminefilter &filter)
References pwalletMain, CWallet::strWalletFile, GetAccountBalance.
Value getbalance(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, ValueFromAmount, pwalletMain, CWallet::GetBalance, ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, json_spirit::get_str, CWallet::mapWallet, IsFinalTx, CMerkleTx::GetBlocksToMaturity, CMerkleTx::GetDepthInMainChain, CWalletTx::GetAmounts, PAIRTYPE, AccountFromValue, GetAccountBalance.
Value movecmd(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, AccountFromValue, AmountFromValue, json_spirit::get_str, pwalletMain, CWallet::strWalletFile, CDB::TxnBegin, JSONRPCError, RPC_DATABASE_ERROR, GetAdjustedTime, CAccountingEntry::nOrderPos, CWallet::IncOrderPosNext, CAccountingEntry::strAccount, CAccountingEntry::nCreditDebit, CAccountingEntry::nTime, CAccountingEntry::strOtherAccount, CAccountingEntry::strComment, CDB::TxnCommit.
Value sendfrom(const Array &params, bool fHelp)
References HelpRequiringPassphrase, HelpExampleCli, HelpExampleRpc, EnsureWalletIsUnlocked, AccountFromValue, json_spirit::get_str, CDarkSilkAddress::IsValid, JSONRPCError, RPC_INVALID_ADDRESS_OR_KEY, AmountFromValue, CWalletTx::strFromAccount, json_spirit::null_type, CWalletTx::mapValue, GetAccountBalance, ISMINE_SPENDABLE, RPC_WALLET_INSUFFICIENT_FUNDS, pwalletMain, CWallet::SendMoneyToDestination, CDarkSilkAddress::Get, RPC_WALLET_ERROR, CTransaction::GetHash, base_uint< BITS >::GetHex.
Value sendmany(const Array &params, bool fHelp)
References HelpRequiringPassphrase, HelpExampleCli, HelpExampleRpc, AccountFromValue, CWalletTx::strFromAccount, json_spirit::null_type, CWalletTx::mapValue, json_spirit::Pair_impl< Config >::name_, CDarkSilkAddress::IsValid, JSONRPCError, RPC_INVALID_ADDRESS_OR_KEY, RPC_INVALID_PARAMETER, CScript::SetDestination, CDarkSilkAddress::Get, AmountFromValue, json_spirit::Pair_impl< Config >::value_, EnsureWalletIsUnlocked, GetAccountBalance, ISMINE_SPENDABLE, RPC_WALLET_INSUFFICIENT_FUNDS, pwalletMain, CWallet::CreateTransaction, ONLY_DENOMINATED, ALL_COINS, CWallet::GetBalance, RPC_WALLET_ERROR, CWallet::CommitTransaction, CTransaction::GetHash, base_uint< BITS >::GetHex.
CScript _createmultisig_redeemScript(const Array &params)
Value addmultisigaddress(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, AccountFromValue, strprintf, pwalletMain, CDarkSilkAddress::IsValid, CDarkSilkAddress::GetKeyID, CCryptoKeyStore::GetPubKey, CPubKey::IsFullyValid, IsHex, ParseHex, CScript::SetMultisig, CScript::GetID, CWallet::AddCScript, CWallet::SetAddressBookName, CBase58Data::ToString.
Value addredeemscript(const Array &params, bool fHelp)
References AccountFromValue, ParseHexV, pwalletMain, CWallet::AddCScript, CWallet::SetAddressBookName, CBase58Data::ToString.
Value ListReceived(const Array &params, bool fByAccounts)
References ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, pwalletMain, CWallet::mapWallet, CTransaction::IsCoinBase, CTransaction::IsCoinStake, IsFinalTx, CMerkleTx::GetDepthInMainChain, CTransaction::vout, ExtractDestination, CTxOut::scriptPubKey, IsMine, tallyitem::nAmount, CTxOut::nValue, tallyitem::nConf, tallyitem::nBCConf, tallyitem::txids, CTransaction::GetHash, tallyitem::fIsWatchonly, PAIRTYPE, CWallet::mapAddressBook, CBase58Data::ToString, ValueFromAmount, base_uint< BITS >::GetHex.
Referenced by listreceivedbyaddress, listreceivedbyaccount.
Value listreceivedbyaddress(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, ListReceived.
Value listreceivedbyaccount(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, ListReceived.
static void MaybePushAddress(Object &entry, const CTxDestination &dest)
void ListTransactions(const CWalletTx &wtx, const string &strAccount, int nMinDepth, bool fLong, Array &ret, const isminefilter &filter)
References CWalletTx::GetAmounts, CWalletTx::IsFromMe, ISMINE_WATCH_ONLY, CTransaction::IsCoinStake, PAIRTYPE, IsMine, pwalletMain, CWalletTx::mapValue, ValueFromAmount, WalletTxToJSON, CMerkleTx::GetDepthInMainChain, stop, CWallet::mapAddressBook, CTransaction::IsCoinBase, CMerkleTx::GetBlocksToMaturity.
Referenced by listtransactions, listsinceblock, gettransaction.
void AcentryToJSON(const CAccountingEntry &acentry, const string &strAccount, Array &ret)
References CAccountingEntry::strAccount, CAccountingEntry::nTime, ValueFromAmount, CAccountingEntry::nCreditDebit, CAccountingEntry::strOtherAccount, CAccountingEntry::strComment.
Referenced by listtransactions.
Value listtransactions(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, json_spirit::get_str, ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, JSONRPCError, RPC_INVALID_PARAMETER, pwalletMain, CWallet::OrderedTxItems, ListTransactions, AcentryToJSON.
Value listaccounts(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, PAIRTYPE, pwalletMain, CWallet::mapAddressBook, IsMine, CWallet::mapWallet, CMerkleTx::GetDepthInMainChain, CWalletTx::GetAmounts, CMerkleTx::GetBlocksToMaturity, CWallet::strWalletFile, CWalletDB::ListAccountCreditDebit, CAccountingEntry::strAccount, CAccountingEntry::nCreditDebit, ValueFromAmount.
Value listsinceblock(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, ISMINE_SPENDABLE, base_uint< BITS >::SetHex, json_spirit::get_str, CBlockLocator::GetBlockIndex, JSONRPCError, RPC_INVALID_PARAMETER, ISMINE_WATCH_ONLY, nBestHeight, CBlockIndex::nHeight, pwalletMain, CWallet::mapWallet, CMerkleTx::GetDepthInMainChain, ListTransactions, hashBestChain, pindexBest, CBlockIndex::pprev, CBlockIndex::GetBlockHash, base_uint< BITS >::GetHex.
Value gettransaction(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, hash, base_uint< BITS >::SetHex, json_spirit::get_str, ISMINE_SPENDABLE, ISMINE_WATCH_ONLY, pwalletMain, CWallet::mapWallet, TxToJSON, CWalletTx::GetCredit, CWalletTx::GetDebit, CWalletTx::IsFromMe, CTransactionPoS::GetValueOut, ValueFromAmount, WalletTxToJSON, ListTransactions, GetTransaction, base_uint< BITS >::GetHex, mapBlockIndex, CBlockIndex::IsInMainChain, nBestHeight, CBlockIndex::nHeight, JSONRPCError, RPC_INVALID_ADDRESS_OR_KEY.
Value backupwallet(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, json_spirit::Value_impl< Config >::get_str, BackupWallet, pwalletMain, JSONRPCError, RPC_WALLET_ERROR.
Value keypoolrefill(const Array &params, bool fHelp)
References HelpRequiringPassphrase, itostr, HelpExampleCli, HelpExampleRpc, GetArg, JSONRPCError, RPC_INVALID_PARAMETER, EnsureWalletIsUnlocked, pwalletMain, CWallet::TopUpKeyPool, CWallet::GetKeyPoolSize, RPC_WALLET_ERROR.
static void LockWallet(CWallet *pWallet)
Value walletpassphrase(const Array &params, bool fHelp)
References pwalletMain, CCryptoKeyStore::IsCrypted, HelpExampleCli, HelpExampleRpc, fServer, JSONRPCError, RPC_SERVER_NOT_STARTED, RPC_WALLET_WRONG_ENC_STATE, CWallet::Unlock, RPC_WALLET_PASSPHRASE_INCORRECT, CWallet::TopUpKeyPool, LOCK, nWalletUnlockTime, GetTime, RPCRunLater, fWalletUnlockStakingOnly.
Value walletpassphrasechange(const Array &params, bool fHelp)
References pwalletMain, CCryptoKeyStore::IsCrypted, HelpExampleCli, HelpExampleRpc, JSONRPCError, RPC_WALLET_WRONG_ENC_STATE, CWallet::ChangeWalletPassphrase, RPC_WALLET_PASSPHRASE_INCORRECT.
Value walletlock(const Array &params, bool fHelp)
References pwalletMain, CCryptoKeyStore::IsCrypted, HelpExampleCli, HelpExampleRpc, JSONRPCError, RPC_WALLET_WRONG_ENC_STATE, LOCK, CWallet::Lock, nWalletUnlockTime.
Value encryptwallet(const Array &params, bool fHelp)
References pwalletMain, CCryptoKeyStore::IsCrypted, HelpExampleCli, HelpExampleRpc, JSONRPCError, RPC_WALLET_WRONG_ENC_STATE, CWallet::EncryptWallet, RPC_WALLET_ENCRYPTION_FAILED, StartShutdown.
Value reservebalance(const Array &params, bool fHelp)
References json_spirit::Value_impl< Config >::get_bool, AmountFromValue, nReserveBalance, ValueFromAmount.
Value checkwallet(const Array &params, bool fHelp)
References pwalletMain, CWallet::FixSpentCoins, ValueFromAmount.
Value repairwallet(const Array &params, bool fHelp)
References pwalletMain, CWallet::FixSpentCoins, ValueFromAmount.
Value resendtx(const Array &params, bool fHelp)
References ResendWalletTransactions.
Value makekeypair(const Array &params, bool fHelp)
References json_spirit::get_str, CKey::MakeNewKey, CKey::GetPrivKey, HexStr, CKey::GetPubKey.
Value settxfee(const Array &params, bool fHelp)
References HelpExampleCli, HelpExampleRpc, nTransactionFee, AmountFromValue.
Value getnewstealthaddress(const Array &params, bool fHelp)
References pwalletMain, CCryptoKeyStore::IsLocked, json_spirit::get_str, CWallet::NewStealthAddress, CWallet::AddStealthAddress, CStealthAddress::Encoded.
Value liststealthaddresses(const Array &params, bool fHelp)
References json_spirit::Value_impl< Config >::get_str, pwalletMain, CCryptoKeyStore::IsLocked, CWallet::stealthAddresses, CStealthAddress::scan_secret, CStealthAddress::label, CStealthAddress::Encoded, HexStr, CStealthAddress::spend_secret.
Value importstealthaddress(const Array &params, bool fHelp)
References json_spirit::Value_impl< Config >::get_str, IsHex, ParseHex, DecodeBase58, ec_secret::e, SecretToPublicKey, CStealthAddress::label, CStealthAddress::scan_pubkey, CStealthAddress::spend_pubkey, CStealthAddress::scan_secret, CStealthAddress::spend_secret, pwalletMain, CWallet::stealthAddresses, CStealthAddress::Encoded, CWallet::AddStealthAddress.
Value sendtostealthaddress(const Array &params, bool fHelp)
References HelpRequiringPassphrase, pwalletMain, CCryptoKeyStore::IsLocked, JSONRPCError, RPC_WALLET_UNLOCK_NEEDED, AmountFromValue, json_spirit::null_type, json_spirit::get_str, CStealthAddress::SetEncoded, CWalletTx::mapValue, CWallet::SendStealthMoneyToDestination, RPC_WALLET_ERROR, CTransaction::GetHash, base_uint< BITS >::GetHex.
Referenced by sendtoaddress.
Value scanforalltxns(const Array &params, bool fHelp)
References pindexGenesisBlock, mapBlockIndex, hashBestChain, CBlockIndex::nHeight, CBlockIndex::pprev, LOCK2, cs_main, pwalletMain, CWallet::cs_wallet, CWallet::MarkDirty, CWallet::ScanForWalletTransactions, CWallet::ReacceptWalletTransactions.
Value scanforstealthtxns(const Array &params, bool fHelp)
References pindexGenesisBlock, mapBlockIndex, hashBestChain, CBlockIndex::nHeight, CBlockIndex::pprev, pwalletMain, CWallet::nStealth, CWallet::nFoundStealth, CBlock::ReadFromDisk, CBlock::vtx, CWallet::AddToWalletIfInvolvingMe, CBlockIndex::pnext.