script.h
SCRIPT_ERR_LAST
ScriptError_t
@16
@17
isminetype
txnouttype
opcodetype
typedef std::vector<unsigned char> valtype
typedef enum ScriptError_t ScriptError
typedef uint8_t isminefilter
used for bitflags of isminetype
typedef boost::variant<CNoDestination, CKeyID, CScriptID, CStealthAddress> CTxDestination
A txout script template with a specific destination. It is either: CNoDestination: no destination setCKeyID: TX_PUBKEYHASH destinationCScriptID: TX_SCRIPTHASH destination A CTxDestination is the internal data type encoded in a CDarkSilkAddress
const unsigned int MAX_SCRIPT_ELEMENT_SIZE
const unsigned int MAX_OP_RETURN_RELAY
const unsigned int MANDATORY_SCRIPT_VERIFY_FLAGS
const unsigned int STANDARD_SCRIPT_VERIFY_FLAGS
const unsigned int STANDARD_NOT_MANDATORY_VERIFY_FLAGS
std::vector<unsigned char> ToByteVector(const T &in)
Referenced by GetScriptForMultisig, IsBudgetCollateralValid, CWallet::GetBudgetSystemCollateralTX.
const char* ScriptErrorString(const ScriptError error)
References SCRIPT_ERR_OK, SCRIPT_ERR_EVAL_FALSE, SCRIPT_ERR_VERIFY, SCRIPT_ERR_EQUALVERIFY, SCRIPT_ERR_CHECKMULTISIGVERIFY, SCRIPT_ERR_CHECKSIGVERIFY, SCRIPT_ERR_NUMEQUALVERIFY, SCRIPT_ERR_SCRIPT_SIZE, SCRIPT_ERR_PUSH_SIZE, SCRIPT_ERR_OP_COUNT, SCRIPT_ERR_STACK_SIZE, SCRIPT_ERR_SIG_COUNT, SCRIPT_ERR_PUBKEY_COUNT, SCRIPT_ERR_BAD_OPCODE, SCRIPT_ERR_DISABLED_OPCODE, SCRIPT_ERR_INVALID_STACK_OPERATION, SCRIPT_ERR_INVALID_ALTSTACK_OPERATION, SCRIPT_ERR_OP_RETURN, SCRIPT_ERR_UNBALANCED_CONDITIONAL, SCRIPT_ERR_SIG_HASHTYPE, SCRIPT_ERR_SIG_DER, SCRIPT_ERR_MINIMALDATA, SCRIPT_ERR_SIG_PUSHONLY, SCRIPT_ERR_SIG_HIGH_S, SCRIPT_ERR_SIG_NULLDUMMY, SCRIPT_ERR_DISCOURAGE_UPGRADABLE_NOPS, SCRIPT_ERR_PUBKEYTYPE, SCRIPT_ERR_UNKNOWN_ERROR, SCRIPT_ERR_ERROR_COUNT.
const char* GetTxnOutputType(txnouttype t)
References TX_NONSTANDARD, TX_PUBKEY, TX_PUBKEYHASH, TX_SCRIPTHASH, TX_MULTISIG, TX_NULL_DATA.
Referenced by ScriptPubKeyToJSON.
const char* GetOpName(opcodetype opcode)
References OP_0, OP_PUSHDATA1, OP_PUSHDATA2, OP_PUSHDATA4, OP_1NEGATE, OP_RESERVED, OP_1, OP_2, OP_3, OP_4, OP_5, OP_6, OP_7, OP_8, OP_9, OP_10, OP_11, OP_12, OP_13, OP_14, OP_15, OP_16, OP_NOP, OP_VER, OP_IF, OP_NOTIF, OP_VERIF, OP_VERNOTIF, OP_ELSE, OP_ENDIF, OP_VERIFY, OP_RETURN, OP_TOALTSTACK, OP_FROMALTSTACK, OP_2DROP, OP_2DUP, OP_3DUP, OP_2OVER, OP_2ROT, OP_2SWAP, OP_IFDUP, OP_DEPTH, OP_DROP, OP_DUP, OP_NIP, OP_OVER, OP_PICK, OP_ROLL, OP_ROT, OP_SWAP, OP_TUCK, OP_CAT, OP_SUBSTR, OP_LEFT, OP_RIGHT, OP_SIZE, OP_INVERT, OP_AND, OP_OR, OP_XOR, OP_EQUAL, OP_EQUALVERIFY, OP_RESERVED1, OP_RESERVED2, OP_1ADD, OP_1SUB, OP_2MUL, OP_2DIV, OP_NEGATE, OP_ABS, OP_NOT, OP_0NOTEQUAL, OP_ADD, OP_SUB, OP_MUL, OP_DIV, OP_MOD, OP_LSHIFT, OP_RSHIFT, OP_BOOLAND, OP_BOOLOR, OP_NUMEQUAL, OP_NUMEQUALVERIFY, OP_NUMNOTEQUAL, OP_LESSTHAN, OP_GREATERTHAN, OP_LESSTHANOREQUAL, OP_GREATERTHANOREQUAL, OP_MIN, OP_MAX, OP_WITHIN, OP_RIPEMD160, OP_SHA1, OP_SHA256, OP_HASH160, OP_HASH256, OP_CODESEPARATOR, OP_CHECKSIG, OP_CHECKSIGVERIFY, OP_CHECKMULTISIG, OP_CHECKMULTISIGVERIFY, OP_NOP1, OP_NOP2, OP_NOP3, OP_NOP4, OP_NOP5, OP_NOP6, OP_CHECKLOCKTIMEVERIFY, OP_NOP8, OP_NOP9, OP_NOP10, OP_INVALIDOPCODE.
Referenced by CScript::ToString.
std::string ValueString(const std::vector< unsigned char > &vch)
References strprintf, CBigNum::getint, HexStr.
Referenced by StackString, CScript::ToString, SecureMsgStore.
std::string StackString(const std::vector< std::vector< unsigned char > > &vStack)
References ValueString.
bool IsDERSignature(const valtype &vchSig, bool haveHashType=true)
References R.
bool IsCompressedOrUncompressedPubKey(const valtype &vchPubKey)
Referenced by CBlock::CheckBlockSignature.
bool EvalScript(std::vector< std::vector< unsigned char > > &stack, const CScript &script, const CTransaction &txTo, unsigned int nIn, unsigned int flags, int nHashType)
References CScript::GetOp, OP_16, OP_CAT, OP_SUBSTR, OP_LEFT, OP_RIGHT, OP_INVERT, OP_AND, OP_OR, OP_XOR, OP_2MUL, OP_2DIV, OP_MUL, OP_DIV, OP_MOD, OP_LSHIFT, OP_RSHIFT, OP_PUSHDATA4, OP_IF, OP_ENDIF, OP_1NEGATE, OP_1, OP_2, OP_3, OP_4, OP_5, OP_6, OP_7, OP_8, OP_9, OP_10, OP_11, OP_12, OP_13, OP_14, OP_15, CBigNum::getvch, OP_NOP, OP_CHECKLOCKTIMEVERIFY, SCRIPT_VERIFY_CHECKLOCKTIMEVERIFY, SCRIPT_VERIFY_DISCOURAGE_UPGRADABLE_NOPS, CastToBigNum, stacktop, OP_NOP1, OP_NOP2, OP_NOP3, OP_NOP4, OP_NOP5, OP_NOP6, OP_NOP8, OP_NOP9, OP_NOP10, OP_NOTIF, CastToBool, OP_ELSE, OP_VERIFY, OP_RETURN, OP_TOALTSTACK, OP_FROMALTSTACK, altstacktop, OP_2DROP, OP_2DUP, OP_3DUP, OP_2OVER, OP_2ROT, OP_2SWAP, OP_IFDUP, OP_DEPTH, OP_DROP, OP_DUP, OP_NIP, OP_OVER, OP_PICK, OP_ROLL, CBigNum::getint, OP_ROT, OP_SWAP, OP_TUCK, OP_SIZE, MakeSameSize, OP_EQUAL, OP_EQUALVERIFY, OP_1ADD, OP_1SUB, OP_NEGATE, OP_ABS, OP_NOT, OP_0NOTEQUAL, OP_ADD, OP_SUB, OP_BOOLAND, OP_BOOLOR, OP_NUMEQUAL, OP_NUMEQUALVERIFY, OP_NUMNOTEQUAL, OP_LESSTHAN, OP_GREATERTHAN, OP_LESSTHANOREQUAL, OP_GREATERTHANOREQUAL, OP_MIN, OP_MAX, CBigNum::getulong, OP_WITHIN, OP_RIPEMD160, OP_SHA1, OP_SHA256, OP_HASH160, OP_HASH256, Hash160, hash, Hash, OP_CODESEPARATOR, OP_CHECKSIG, OP_CHECKSIGVERIFY, CScript::FindAndDelete, SCRIPT_VERIFY_STRICTENC, CheckSig, OP_CHECKMULTISIG, OP_CHECKMULTISIGVERIFY, SCRIPT_VERIFY_NULLDUMMY.
Referenced by AreInputsStandard, VerifyScript, CombineSignatures.
bool EvalScript(std::vector< std::vector< unsigned char > > &stack, const CScript &script, unsigned int flags, const BaseSignatureChecker &checker, ScriptError *error=NULL)
References SCRIPT_ERR_UNKNOWN_ERROR, SCRIPT_ERR_SCRIPT_SIZE, SCRIPT_VERIFY_MINIMALDATA, CScript::GetOp, SCRIPT_ERR_BAD_OPCODE, SCRIPT_ERR_PUSH_SIZE, OP_16, SCRIPT_ERR_OP_COUNT, OP_CAT, OP_SUBSTR, OP_LEFT, OP_RIGHT, OP_INVERT, OP_AND, OP_OR, OP_XOR, OP_2MUL, OP_2DIV, OP_MUL, OP_DIV, OP_MOD, OP_LSHIFT, OP_RSHIFT, SCRIPT_ERR_DISABLED_OPCODE, OP_PUSHDATA4, SCRIPT_ERR_MINIMALDATA, OP_IF, OP_ENDIF, OP_1NEGATE, OP_1, OP_2, OP_3, OP_4, OP_5, OP_6, OP_7, OP_8, OP_9, OP_10, OP_11, OP_12, OP_13, OP_14, OP_15, CScriptNum::getvch, OP_NOP, OP_NOP1, OP_NOP2, OP_NOP3, OP_NOP4, OP_NOP5, OP_NOP6, OP_NOP7, OP_NOP8, OP_NOP9, OP_NOP10, SCRIPT_VERIFY_DISCOURAGE_UPGRADABLE_NOPS, SCRIPT_ERR_DISCOURAGE_UPGRADABLE_NOPS, OP_NOTIF, SCRIPT_ERR_UNBALANCED_CONDITIONAL, stacktop, CastToBool, OP_ELSE, OP_VERIFY, SCRIPT_ERR_INVALID_STACK_OPERATION, SCRIPT_ERR_VERIFY, OP_RETURN, SCRIPT_ERR_OP_RETURN, OP_TOALTSTACK, OP_FROMALTSTACK, SCRIPT_ERR_INVALID_ALTSTACK_OPERATION, altstacktop, OP_2DROP, OP_2DUP, OP_3DUP, OP_2OVER, OP_2ROT, OP_2SWAP, OP_IFDUP, OP_DEPTH, OP_DROP, OP_DUP, OP_NIP, OP_OVER, OP_PICK, OP_ROLL, CScriptNum::getint, OP_ROT, OP_SWAP, OP_TUCK, OP_SIZE, OP_EQUAL, OP_EQUALVERIFY, SCRIPT_ERR_EQUALVERIFY, OP_1ADD, OP_1SUB, OP_NEGATE, OP_ABS, OP_NOT, OP_0NOTEQUAL, OP_ADD, OP_SUB, OP_BOOLAND, OP_BOOLOR, OP_NUMEQUAL, OP_NUMEQUALVERIFY, OP_NUMNOTEQUAL, OP_LESSTHAN, OP_GREATERTHAN, OP_LESSTHANOREQUAL, OP_GREATERTHANOREQUAL, OP_MIN, OP_MAX, SCRIPT_ERR_NUMEQUALVERIFY, OP_WITHIN, OP_RIPEMD160, OP_SHA1, OP_SHA256, OP_HASH160, OP_HASH256, CRIPEMD160::Write, begin_ptr, CSHA1::Write, CSHA256::Write, CHash160::Write, CHash256::Write, OP_CODESEPARATOR, OP_CHECKSIG, OP_CHECKSIGVERIFY, CScript::FindAndDelete, BaseSignatureChecker::CheckSig, SCRIPT_ERR_CHECKSIGVERIFY, OP_CHECKMULTISIG, OP_CHECKMULTISIGVERIFY, SCRIPT_ERR_PUBKEY_COUNT, SCRIPT_ERR_SIG_COUNT, SCRIPT_VERIFY_NULLDUMMY, SCRIPT_ERR_SIG_NULLDUMMY, SCRIPT_ERR_CHECKMULTISIGVERIFY, SCRIPT_ERR_STACK_SIZE.
bool Solver(const CScript &scriptPubKey, txnouttype &typeRet, std::vector< std::vector< unsigned char > > &vSolutionsRet)
References TX_PUBKEY, OP_PUBKEY, OP_CHECKSIG, TX_PUBKEYHASH, OP_DUP, OP_HASH160, OP_PUBKEYHASH, OP_EQUALVERIFY, TX_MULTISIG, OP_SMALLINTEGER, OP_PUBKEYS, OP_CHECKMULTISIG, TX_NULL_DATA, OP_RETURN, OP_SMALLDATA, CScript::IsPayToScriptHash, TX_SCRIPTHASH, PAIRTYPE, CScript::clear, CScript::GetOp, OP_0, OP_1, OP_16, CScript::DecodeOP_N, TX_NONSTANDARD.
Referenced by AreInputsStandard, CBlock::CheckBlockSignature, SignSignature, Solver, IsStandard, IsMine, ExtractDestination, ExtractDestinations, CombineSignatures, CWallet::CreateCoinStake.
int ScriptSigArgsExpected(txnouttype t, const std::vector< std::vector< unsigned char > > &vSolutions)
References TX_NONSTANDARD, TX_NULL_DATA, TX_PUBKEY, TX_PUBKEYHASH, TX_MULTISIG, TX_SCRIPTHASH.
Referenced by AreInputsStandard.
bool IsStandard(const CScript &scriptPubKey, txnouttype &whichType)
References Solver, TX_MULTISIG, TX_NONSTANDARD.
Referenced by IsStandardTx.
isminetype IsMine(const CKeyStore &keystore, const CScript &scriptPubKey)
References Solver, CKeyStore::HaveWatchOnly, ISMINE_WATCH_ONLY, ISMINE_NO, TX_NONSTANDARD, TX_NULL_DATA, TX_PUBKEY, CPubKey::GetID, CKeyStore::HaveKey, ISMINE_SPENDABLE, TX_PUBKEYHASH, TX_SCRIPTHASH, CKeyStore::GetCScript, IsMine, TX_MULTISIG, HaveKeys.
isminetype IsMine(const CKeyStore &keystore, const CTxDestination &dest)
References CScript::SetDestination, IsMine.
Referenced by AddressTablePriv::refreshAddressTable, TransactionRecord::decomposeTransaction, importaddress, validateaddress, validatepubkey, smsglocalkeys, setaccount, getreceivedbyaddress, getreceivedbyaccount, ListReceived, ListTransactions, listaccounts, IsMine, SecureMsgAddWalletAddresses, SecureMsgSend, CWallet::AddToWalletIfInvolvingMe, CWallet::IsMine, CWallet::GetDebit, CWallet::IsChange, CWallet::ReacceptWalletTransactions, CWallet::GetAnonymizableBalance, CWallet::GetAnonymizedBalance, CWallet::GetAverageAnonymizedRounds, CWallet::GetNormalizedAnonymizedBalance, CWallet::GetDenominatedBalance, CWallet::AvailableCoins, CWallet::AvailableCoinsForStaking, CWallet::CountInputsWithAmount, CWallet::SetAddressBookName, CWallet::DelAddressBookName, CWallet::GetAddressBalances, CWallet::GetAddressGroupings, CWallet::FixSpentCoins, CWallet::DisableTransaction.
void ExtractAffectedKeys(const CKeyStore &keystore, const CScript &scriptPubKey, std::vector< CKeyID > &vKeys)
References CAffectedKeysVisitor::Process.
Referenced by CWallet::GetKeyBirthTimes.
bool ExtractDestination(const CScript &scriptPubKey, CTxDestination &addressRet)
References Solver, TX_PUBKEY, CPubKey::GetID, TX_PUBKEYHASH, TX_SCRIPTHASH.
Referenced by getOutputs, getInputs, CoinControlDialog::updateLabels, TransactionDesc::toHTML, TransactionRecord::decomposeTransaction, WalletModel::listCoins, getblocktemplate, snbudget, getreceivedbyaccount, ListReceived, ExtractDestinations, CBudgetManager::FillBlockPayee, CFinalizedBudget::IsTransactionValid, CStormnodePayments::FillBlockPayee, CStormnodePayments::ProcessMessageStormnodePayments, CStormnodeBlockPayees::IsTransactionValid, CStormnodeBlockPayees::GetRequiredPaymentsString, CStormnodePayments::ProcessBlock, CWallet::IsChange, CWalletTx::GetAmounts, CWallet::FindStealthTransactions, CWallet::GetAddressBalances, CWallet::GetAddressGroupings.
bool ExtractDestinations(const CScript &scriptPubKey, txnouttype &typeRet, std::vector< CTxDestination > &addressRet, int &nRequiredRet)
References TX_NONSTANDARD, Solver, TX_NULL_DATA, TX_MULTISIG, CPubKey::GetID, ExtractDestination.
Referenced by ScriptPubKeyToJSON, CAffectedKeysVisitor::Process.
bool SignSignature(const CKeyStore &keystore, const CScript &fromPubKey, CMutableTransaction &txTo, unsigned int nIn, int nHashType=SIGHASH_ALL)
References CMutableTransaction::vin, hash, SignatureHash, Solver, TX_SCRIPTHASH, VerifyScript.
Referenced by CSandstormPool::SignFinalTransaction, SignSignature, CWallet::CreateCoinStake.
bool SignSignature(const CKeyStore &keystore, const CScript &fromPubKey, CTransaction &txTo, unsigned int nIn, int nHashType=SIGHASH_ALL)
References CTransaction::vin, hash, SignatureHash, Solver, TX_SCRIPTHASH, VerifyScript.
bool SignSignature(const CKeyStore &keystore, const CTransaction &txFrom, CTransaction &txTo, unsigned int nIn, int nHashType=SIGHASH_ALL)
References CTransaction::vin, CTransaction::vout, SignSignature.
bool SignSignature(const CKeyStore &keystore, const CMutableTransaction &txFrom, CTransaction &txTo, unsigned int nIn, int nHashType=SIGHASH_ALL)
References CTransaction::vin, CMutableTransaction::vout, SignSignature.
bool VerifyScript(const CScript &scriptSig, const CScript &scriptPubKey, const CTransaction &txTo, unsigned int nIn, unsigned int flags, int nHashType)
References EvalScript, CastToBool, CScript::IsPayToScriptHash, CScript::IsPushOnly.
Referenced by signrawtransaction, CSandstormPool::SignatureValid, SignSignature, VerifySignature.
bool VerifySignature(const CTransaction &txFrom, const CTransaction &txTo, unsigned int nIn, unsigned int flags, int nHashType)
References CTransaction::vin, CTransaction::vout, CTransaction::GetHash, VerifyScript, CTxOut::scriptPubKey.
Referenced by CheckProofOfStake, CTransactionPoS::ConnectInputs, SignatureChecker::CheckSig.
bool VerifyScript(const CScript &scriptSig, const CScript &scriptPubKey, unsigned int flags, const BaseSignatureChecker &checker, ScriptError *error=NULL)
References SCRIPT_ERR_UNKNOWN_ERROR, SCRIPT_VERIFY_SIGPUSHONLY, CScript::IsPushOnly, SCRIPT_ERR_SIG_PUSHONLY, EvalScript, SCRIPT_VERIFY_P2SH, SCRIPT_ERR_EVAL_FALSE, CastToBool, CScript::IsPayToScriptHash.
CScript CombineSignatures(CScript scriptPubKey, const CTransaction &txTo, unsigned int nIn, const CScript &scriptSig1, const CScript &scriptSig2)
References Solver, EvalScript, SCRIPT_VERIFY_NONE, CombineSignatures.
Referenced by signrawtransaction, CombineSignatures.
CScript GetScriptForDestination(const CTxDestination &dest)
Referenced by importaddress, snbudget, SendMoney, CSandstormPool::SetCollateralAddress, CSandstormPool::MakeCollateralAmounts, CSandstormPool::CreateDenominated, CSandStormSigner::IsVinAssociatedWithPubkey, CStormnodePayments::FillBlockPayee, CStormnodePayments::IsScheduled, CStormnodePayments::ProcessBlock, CStormnode::SecondsSincePayment, CStormnode::GetLastPaid, CStormnodeBroadcast::CheckAndUpdate, CStormnodeMan::Find, CWallet::AddKeyPubKey, CWallet::CreateCollateralTransaction, CWallet::CreateCoinStake, CWallet::PrepareSandstormDenominate.
CScript GetScriptForMultisig(int nRequired, const std::vector< CPubKey > &keys)
References CScript::EncodeOP_N, ToByteVector, OP_CHECKMULTISIG.
bool Solver(const CKeyStore &keystore, const CScript &scriptPubKey, uint256 hash, int nHashType, CScript &scriptSigRet, txnouttype &whichTypeRet)
References CScript::clear, Solver, TX_NONSTANDARD, TX_NULL_DATA, TX_PUBKEY, CPubKey::GetID, Sign1, TX_PUBKEYHASH, CKeyStore::GetPubKey, TX_SCRIPTHASH, CKeyStore::GetCScript, TX_MULTISIG, OP_0, SignN.