scrypt.h
uint256 scrypt_salted_multiround_hash(const void *input, size_t inputlen, const void *salt, size_t saltlen, const unsigned int nRounds)
References scrypt_salted_hash.
Referenced by CCrypter::SetKeyFromPassphrase.
uint256 scrypt_salted_hash(const void *input, size_t inputlen, const void *salt, size_t saltlen)
References SCRYPT_BUFFER_SIZE, scrypt.
Referenced by scrypt_salted_multiround_hash.
uint256 scrypt_hash(const void *input, size_t inputlen)
References SCRYPT_BUFFER_SIZE, scrypt_nosalt.
uint256 scrypt_blockhash(const void *input)
References SCRYPT_BUFFER_SIZE, scrypt_nosalt.
Referenced by CBlockHeader::GetPoWHash.