scrypt.cpp
SCRYPT_BUFFER_SIZE
Referenced by scrypt_hash, scrypt_salted_hash, scrypt_blockhash.
R
Referenced by leveldb::TEST, IsDERSignature, StealthSecret.
static void xor_salsa8(unsigned int B[16], const unsigned int Bx[16])
static void scrypt_core(unsigned int *X, unsigned int *V)
uint256 scrypt_nosalt(const void *input, size_t inputlen, void *scratchpad)
References PBKDF2_SHA256.
Referenced by scrypt_hash, scrypt_blockhash.
uint256 scrypt(const void *data, size_t datalen, const void *salt, size_t saltlen, void *scratchpad)
References PBKDF2_SHA256.
Referenced by scrypt_salted_hash.
uint256 scrypt_hash(const void *input, size_t inputlen)
References SCRYPT_BUFFER_SIZE, scrypt_nosalt.
uint256 scrypt_salted_hash(const void *input, size_t inputlen, const void *salt, size_t saltlen)
References SCRYPT_BUFFER_SIZE, scrypt.
Referenced by scrypt_salted_multiround_hash.
uint256 scrypt_salted_multiround_hash(const void *input, size_t inputlen, const void *salt, size_t saltlen, const unsigned int nRounds)
References scrypt_salted_hash.
Referenced by CCrypter::SetKeyFromPassphrase.
uint256 scrypt_blockhash(const void *input)
References SCRYPT_BUFFER_SIZE, scrypt_nosalt.
Referenced by CBlockHeader::GetPoWHash.