serialize.h
READWRITE
Referenced by CAddrInfo::SerializationOp, CUnsignedAlert::SerializationOp, CAlert::SerializationOp, CFeeRate::SerializationOp, CDiskBlockPos::SerializationOp, CDiskBlockIndex::SerializationOp, CBlockLocator::SerializationOp, CTxOutCompressorCoin::SerializationOp, CTxOutCompressor::SerializationOp, CMasterKey::SerializationOp, CConsensusVote::SerializationOp, CBlockHeader::SerializationOp, CBlock::SerializationOp, CDiskTxPos::SerializationOp, CTransactionPoS::SerializationOp, CMerkleTx::SerializationOp, CTxIndex::SerializationOp, CBlockFileInfo::SerializationOp, CNetAddr::SerializationOp, CService::SerializationOp, COutPoint::SerializationOp, CTxIn::SerializationOp, CTxOut::SerializationOp, CTransaction::SerializationOp, CMutableTransaction::SerializationOp, CMessageHeader::SerializationOp, CAddress::SerializationOp, CInv::SerializationOp, CSandStormRelay::SerializationOp, CSandstormQueue::SerializationOp, SecMsgAddress::SerializationOp, SecMsgStored::SerializationOp, CSporkMessage::SerializationOp, CStealthAddress::SerializationOp, CBudgetManager::SerializationOp, CTxBudgetPayment::SerializationOp, CFinalizedBudget::SerializationOp, CFinalizedBudgetBroadcast::SerializationOp, CFinalizedBudgetVote::SerializationOp, CBudgetProposal::SerializationOp, CBudgetProposalBroadcast::SerializationOp, CBudgetVote::SerializationOp, CStormnodePayee::SerializationOp, CStormnodeBlockPayees::SerializationOp, CStormnodePaymentWinner::SerializationOp, CStormnodePayments::SerializationOp, CStormnodePing::SerializationOp, CStormnode::SerializationOp, CStormnodeBroadcast::SerializationOp, CStormnodeMan::SerializationOp, CTxOutCompressorUndo::SerializationOp, CTxUndo::SerializationOp, CKeyPool::SerializationOp, CWalletTx::SerializationOp, CWalletKey::SerializationOp, CAccount::SerializationOp, CAccountingEntry::SerializationOp, CKeyMetadata::SerializationOp, CStealthKeyMetadata::SerializationOp.
ADD_SERIALIZE_METHODS
Implement three methods for serializable objects. These are actually wrappers over "SerializationOp" template, which implements the body of each class' serialization code. Adding "ADD_SERIALIZE_METHODS" in the body of the class causes these wrappers to be added as members.
WRITEDATA
Referenced by Serialize, WriteCompactSize, WriteVarInt.
READDATA
Referenced by Unserialize, ReadCompactSize, ReadVarInt.
FLATDATA
Referenced by CBlock::WriteToDisk, CDiskTxPos::SerializationOp, CAddrDB::Write, CAddrDB::Read, CNetAddr::SerializationOp, CService::SerializationOp, COutPoint::SerializationOp, CMessageHeader::SerializationOp, CBudgetDB::Write, CBudgetDB::Read, CStormnodePaymentDB::Write, CStormnodePaymentDB::Read, CStormnodeDB::Write, CStormnodeDB::Read.
VARINT
Referenced by CDiskBlockPos::SerializationOp, CCoinsViewDB::GetStats, CTxOutCompressorCoin::SerializationOp, CCoins::GetSerializeSize, CCoins::Serialize, CCoins::Unserialize, CScriptCompressor::GetSerializeSize, CScriptCompressor::Serialize, CScriptCompressor::Unserialize, CTxOutCompressor::SerializationOp, CBlockFileInfo::SerializationOp, BOOST_AUTO_TEST_CASE, CTxOutCompressorUndo::SerializationOp, CTxInUndo::GetSerializeSize, CTxInUndo::Serialize, CTxInUndo::Unserialize.
LIMITED_STRING
Referenced by CUnsignedAlert::SerializationOp, CFinalizedBudget::SerializationOp, CFinalizedBudgetBroadcast::SerializationOp, CBudgetProposal::SerializationOp, CBudgetProposalBroadcast::SerializationOp, CWalletKey::SerializationOp, CAccountingEntry::SerializationOp.
@18
typedef std::vector<char, zero_after_free_allocator<char> > CSerializeData
const unsigned int MAX_SIZE
T& REF(const T &val)
Referenced by CTxOutCompressorCoin::SerializationOp, CCoins::GetSerializeSize, CCoins::Serialize, CCoins::Unserialize, CScriptCompressor::Unserialize, CTxOutCompressor::SerializationOp, CTxOutCompressorUndo::SerializationOp, CTxInUndo::GetSerializeSize, CTxInUndo::Serialize, CTxInUndo::Unserialize.
T* NCONST_PTR(const T *val)
Used to acquire a non-const pointer "this" to generate bodies of const serialization operations from a template
T* begin_ptr(std::vector< T, TAl > &v)
Get begin pointer of vector (non-const version). These functions avoid the undefined case of indexing into an empty vector, as well as that of indexing after the end of the vector.
Referenced by CECKey::GetPubKey, EvalScript, CFlatData::CFlatData.
const T* begin_ptr(const std::vector< T, TAl > &v)
Get begin pointer of vector (const version)
T* end_ptr(std::vector< T, TAl > &v)
Get end pointer of vector (non-const version)
Referenced by CFlatData::CFlatData.
const T* end_ptr(const std::vector< T, TAl > &v)
Get end pointer of vector (const version)
unsigned int GetSerializeSize(char a, int, int=0)
Referenced by CBigNum::GetSerializeSize, CBlock::AcceptBlock, CBlock::ConnectBlock, CBlock::CheckBlock, AcceptToMemoryPool, AcceptableInputs, CreateNewBlock, CTransaction::ComputePriority, CTransaction::CheckTransaction, CTxOut::IsDust, blockToJSON, GetSerializeSize_impl, GetSerializeSize, SerReadWrite, CDataStream::GetSerializeSize, CAutoFile::GetSerializeSize, BOOST_AUTO_TEST_CASE, CTxInUndo::GetSerializeSize, CWallet::CreateCoinStake.
unsigned int GetSerializeSize(signed char a, int, int=0)
unsigned int GetSerializeSize(unsigned char a, int, int=0)
unsigned int GetSerializeSize(signed short a, int, int=0)
unsigned int GetSerializeSize(unsigned short a, int, int=0)
unsigned int GetSerializeSize(signed int a, int, int=0)
unsigned int GetSerializeSize(unsigned int a, int, int=0)
unsigned int GetSerializeSize(signed long a, int, int=0)
unsigned int GetSerializeSize(unsigned long a, int, int=0)
unsigned int GetSerializeSize(signed long long a, int, int=0)
unsigned int GetSerializeSize(unsigned long long a, int, int=0)
unsigned int GetSerializeSize(float a, int, int=0)
unsigned int GetSerializeSize(double a, int, int=0)
void Serialize(Stream &s, char a, int, int=0)
References WRITEDATA.
Referenced by CHashWriter::operator<<, Serialize_impl, Serialize, SerReadWrite, CSizeComputer::operator<<, CAutoFile::operator<<, BOOST_AUTO_TEST_CASE.
void Serialize(Stream &s, signed char a, int, int=0)
References WRITEDATA.
void Serialize(Stream &s, unsigned char a, int, int=0)
References WRITEDATA.
void Serialize(Stream &s, signed short a, int, int=0)
References WRITEDATA.
void Serialize(Stream &s, unsigned short a, int, int=0)
References WRITEDATA.
void Serialize(Stream &s, signed int a, int, int=0)
References WRITEDATA.
void Serialize(Stream &s, unsigned int a, int, int=0)
References WRITEDATA.
void Serialize(Stream &s, signed long a, int, int=0)
References WRITEDATA.
void Serialize(Stream &s, unsigned long a, int, int=0)
References WRITEDATA.
void Serialize(Stream &s, signed long long a, int, int=0)
References WRITEDATA.
void Serialize(Stream &s, unsigned long long a, int, int=0)
References WRITEDATA.
void Serialize(Stream &s, float a, int, int=0)
References WRITEDATA.
void Serialize(Stream &s, double a, int, int=0)
References WRITEDATA.
void Unserialize(Stream &s, char &a, int, int=0)
References READDATA.
Referenced by Unserialize_impl, Unserialize, SerReadWrite, CDataStream::operator>>, CAutoFile::operator>>, CBufferedFile::operator>>.
void Unserialize(Stream &s, signed char &a, int, int=0)
References READDATA.
void Unserialize(Stream &s, unsigned char &a, int, int=0)
References READDATA.
void Unserialize(Stream &s, signed short &a, int, int=0)
References READDATA.
void Unserialize(Stream &s, unsigned short &a, int, int=0)
References READDATA.
void Unserialize(Stream &s, signed int &a, int, int=0)
References READDATA.
void Unserialize(Stream &s, unsigned int &a, int, int=0)
References READDATA.
void Unserialize(Stream &s, signed long &a, int, int=0)
References READDATA.
void Unserialize(Stream &s, unsigned long &a, int, int=0)
References READDATA.
void Unserialize(Stream &s, signed long long &a, int, int=0)
References READDATA.
void Unserialize(Stream &s, unsigned long long &a, int, int=0)
References READDATA.
void Unserialize(Stream &s, float &a, int, int=0)
References READDATA.
void Unserialize(Stream &s, double &a, int, int=0)
References READDATA.
unsigned int GetSerializeSize(bool a, int, int=0)
void Serialize(Stream &s, bool a, int, int=0)
References WRITEDATA.
void Unserialize(Stream &s, bool &a, int, int=0)
References READDATA.
unsigned int GetSizeOfCompactSize(uint64_t nSize)
Referenced by CBlock::ConnectBlock, LimitedString< Limit >::GetSerializeSize, GetSerializeSize, GetSerializeSize_impl.
void WriteCompactSize(Stream &os, uint64_t nSize)
References WRITEDATA.
Referenced by CPubKey::Serialize, LimitedString< Limit >::Serialize, Serialize, Serialize_impl.
uint64_t ReadCompactSize(Stream &is)
References READDATA, MAX_SIZE.
Referenced by CPubKey::Unserialize, LimitedString< Limit >::Unserialize, Unserialize, Unserialize_impl.
unsigned int GetSizeOfVarInt(I n)
void WriteVarInt(Stream &os, I n)
References WRITEDATA.
I ReadVarInt(Stream &is)
References READDATA.
CVarInt<I> WrapVarInt(I &n)
unsigned int GetSerializeSize(const std::basic_string< C > &str, int, int=0)
References GetSizeOfCompactSize.
void Serialize(Stream &os, const std::basic_string< C > &str, int, int=0)
References WriteCompactSize.
void Unserialize(Stream &is, std::basic_string< C > &str, int, int=0)
References ReadCompactSize.
unsigned int GetSerializeSize_impl(const std::vector< T, A > &v, int nType, int nVersion, const boost::true_type &)
Referenced by GetSerializeSize.
unsigned int GetSerializeSize_impl(const std::vector< T, A > &v, int nType, int nVersion, const boost::false_type &)
unsigned int GetSerializeSize(const std::vector< T, A > &v, int nType, int nVersion)
References GetSerializeSize_impl.
void Serialize_impl(Stream &os, const std::vector< T, A > &v, int nType, int nVersion, const boost::true_type &)
Referenced by Serialize.
void Serialize_impl(Stream &os, const std::vector< T, A > &v, int nType, int nVersion, const boost::false_type &)
void Serialize(Stream &os, const std::vector< T, A > &v, int nType, int nVersion)
References Serialize_impl.
void Unserialize_impl(Stream &is, std::vector< T, A > &v, int nType, int nVersion, const boost::true_type &)
Referenced by Unserialize.
void Unserialize_impl(Stream &is, std::vector< T, A > &v, int nType, int nVersion, const boost::false_type &)
void Unserialize(Stream &is, std::vector< T, A > &v, int nType, int nVersion)
References Unserialize_impl.
unsigned int GetSerializeSize(const CScript &v, int nType, int nVersion)
References GetSerializeSize.
void Serialize(Stream &os, const CScript &v, int nType, int nVersion)
References Serialize.
void Unserialize(Stream &is, CScript &v, int nType, int nVersion)
References Unserialize.
unsigned int GetSerializeSize(const std::pair< K, T > &item, int nType, int nVersion)
References GetSerializeSize.
void Serialize(Stream &os, const std::pair< K, T > &item, int nType, int nVersion)
References Serialize.
void Unserialize(Stream &is, std::pair< K, T > &item, int nType, int nVersion)
References Unserialize.
unsigned int GetSerializeSize(const boost::tuple< T0, T1, T2 > &item, int nType, int nVersion)
References GetSerializeSize.
void Serialize(Stream &os, const boost::tuple< T0, T1, T2 > &item, int nType, int nVersion)
References Serialize.
void Unserialize(Stream &is, boost::tuple< T0, T1, T2 > &item, int nType, int nVersion)
References Unserialize.
unsigned int GetSerializeSize(const boost::tuple< T0, T1, T2, T3 > &item, int nType, int nVersion)
References GetSerializeSize.
void Serialize(Stream &os, const boost::tuple< T0, T1, T2, T3 > &item, int nType, int nVersion)
References Serialize.
void Unserialize(Stream &is, boost::tuple< T0, T1, T2, T3 > &item, int nType, int nVersion)
References Unserialize.
unsigned int GetSerializeSize(const std::map< K, T, Pred, A > &m, int nType, int nVersion)
References GetSizeOfCompactSize, GetSerializeSize.
void Serialize(Stream &os, const std::map< K, T, Pred, A > &m, int nType, int nVersion)
References WriteCompactSize, Serialize.
void Unserialize(Stream &is, std::map< K, T, Pred, A > &m, int nType, int nVersion)
References ReadCompactSize, Unserialize.
unsigned int GetSerializeSize(const std::set< K, Pred, A > &m, int nType, int nVersion)
References GetSizeOfCompactSize, GetSerializeSize.
void Serialize(Stream &os, const std::set< K, Pred, A > &m, int nType, int nVersion)
References WriteCompactSize, Serialize.
void Unserialize(Stream &is, std::set< K, Pred, A > &m, int nType, int nVersion)
References ReadCompactSize, Unserialize.
unsigned int GetSerializeSize(const T &a, long nType, int nVersion)
void Serialize(Stream &os, const T &a, long nType, int nVersion)
void Unserialize(Stream &is, T &a, long nType, int nVersion)
unsigned int GetSerializeSize_impl(const std::vector< T, A > &v, int nType, int nVersion, const unsigned char &)
vector
References GetSizeOfCompactSize.
unsigned int GetSerializeSize_impl(const std::vector< T, A > &v, int nType, int nVersion, const V &)
References GetSizeOfCompactSize, GetSerializeSize.
void Serialize_impl(Stream &os, const std::vector< T, A > &v, int nType, int nVersion, const unsigned char &)
References WriteCompactSize.
void Serialize_impl(Stream &os, const std::vector< T, A > &v, int nType, int nVersion, const V &)
References WriteCompactSize, Serialize.
void Unserialize_impl(Stream &is, std::vector< T, A > &v, int nType, int nVersion, const unsigned char &)
References ReadCompactSize.
void Unserialize_impl(Stream &is, std::vector< T, A > &v, int nType, int nVersion, const V &)
References ReadCompactSize, Unserialize.
unsigned int SerReadWrite(Stream &s, const T &obj, int nType, int nVersion, CSerActionGetSerializeSize ser_action)
References GetSerializeSize.
unsigned int SerReadWrite(Stream &s, const T &obj, int nType, int nVersion, CSerActionSerialize ser_action)
References Serialize.
unsigned int SerReadWrite(Stream &s, T &obj, int nType, int nVersion, CSerActionUnserialize ser_action)
References Unserialize.