smessage.h
SMSG_MASK_UNREAD
Referenced by smsginbox, SecureMsgScanMessage.
const unsigned int SMSG_HDR_LEN
Referenced by MessageTablePriv::refreshMessageTable, MessageTablePriv::newMessage, MessageTablePriv::newOutboxMessage, smsginbox, smsgoutbox, ThreadSecureMsgPow, SecureMsgBuildBucketSet, SecureMsgScanBuckets, SecureMsgWalletUnlocked, SecureMsgScanMessage, SecureMsgRetrieve, SecureMsgReceive, SecureMsgStoreUnscanned, SecureMsgStore, SecureMsgValidate, SecureMsgSetHash, SecureMsgSend.
const unsigned int SMSG_PL_HDR_LEN
Referenced by SecureMsgEncrypt, SecureMsgDecrypt.
const unsigned int SMSG_BUCKET_LEN
Referenced by SecureMsgReceiveData, SecureMsgRetrieve, SecureMsgStoreUnscanned, SecureMsgStore.
const unsigned int SMSG_RETENTION
Referenced by ThreadSecureMsg, SecureMsgBuildBucketSet, SecureMsgReceiveData, SecureMsgScanBuckets, SecureMsgWalletUnlocked, SecureMsgReceive, SecureMsgStoreUnscanned, SecureMsgStore.
const unsigned int SMSG_SEND_DELAY
Referenced by SecureMsgSendData.
const unsigned int SMSG_THREAD_DELAY
Referenced by ThreadSecureMsg.
const unsigned int SMSG_THREAD_LOG_GAP
Referenced by ThreadSecureMsg.
const unsigned int SMSG_TIME_LEEWAY
Referenced by SecureMsgReceiveData, SecureMsgReceive, SecureMsgStoreUnscanned, SecureMsgStore.
const unsigned int SMSG_TIME_IGNORE
Referenced by ThreadSecureMsg.
const unsigned int SMSG_MAX_MSG_BYTES
Referenced by SecureMsgEncrypt, SecureMsgSend.
const unsigned int SMSG_MAX_MSG_WORST
Referenced by SecureMsgValidate.
bool fSecMsgEnabled
Referenced by SendMessages, smsgenable, smsgdisable, smsglocalkeys, smsgscanchain, smsgscanbuckets, smsgaddkey, smsggetpubkey, smsgsend, smsgsendanon, smsginbox, smsgoutbox, smsgbuckets, ThreadSecureMsg, ThreadSecureMsgPow, SecureMsgReadIni, SecureMsgWriteIni, SecureMsgStart, SecureMsgShutdown, SecureMsgEnable, SecureMsgDisable, SecureMsgScanBuckets, SecureMsgWalletUnlocked, SecureMsgWalletKeyChanged, SecureMsgSetHash.
boost::signals2::signal<void (SecMsgStored& inboxHdr)> NotifySecMsgInboxChanged
Referenced by SecureMsgScanMessage.
boost::signals2::signal<void (SecMsgStored& outboxHdr)> NotifySecMsgOutboxChanged
Referenced by SecureMsgSend.
boost::signals2::signal<void ()> NotifySecMsgWalletUnlocked
Referenced by SecureMsgWalletUnlocked.
std::map<int64_t, SecMsgBucket> smsgBuckets
Referenced by smsgbuckets, ThreadSecureMsg, SecureMsgBuildBucketSet, SecureMsgEnable, SecureMsgDisable, SecureMsgReceiveData, SecureMsgSendData, SecureMsgReceive, SecureMsgStore.
std::vector<SecMsgAddress> smsgAddresses
Referenced by smsglocalkeys, SecureMsgAddWalletAddresses, SecureMsgReadIni, SecureMsgWriteIni, SecureMsgStart, SecureMsgEnable, SecureMsgDisable, SecureMsgWalletKeyChanged, SecureMsgScanMessage.
SecMsgOptions smsgOptions
Referenced by smsgoptions.
CCriticalSection cs_smsg
Referenced by smsgbuckets.
CCriticalSection cs_smsgDB
Referenced by MessageTablePriv::refreshMessageTable, MessageModel::removeRows, smsginbox, smsgoutbox.
int SecureMsgBuildBucketSet()
References fDebugSmsg, LogPrintf, GetTime, GetDataDir, SMSG_RETENTION, LOCK, smsgBuckets, SecMsgToken::offset, SecureMessage::hash, SMSG_HDR_LEN, SecMsgToken::timestamp, SecureMessage::timestamp, SecureMessage::nPayload, SecMsgToken::sample.
Referenced by SecureMsgStart, SecureMsgEnable.
int SecureMsgAddWalletAddresses()
References fDebugSmsg, LogPrintf, PAIRTYPE, pwalletMain, CWallet::mapAddressBook, IsMine, CDarkSilkAddress::IsValid, CBase58Data::ToString, smsgAddresses.
Referenced by SecureMsgStart, SecureMsgEnable.
int SecureMsgReadIni()
References fSecMsgEnabled, fDebugSmsg, LogPrintf, GetDataDir, SecMsgOptions::fNewAddressRecv, SecMsgOptions::fNewAddressAnon, SecMsgOptions::fScanIncoming, smsgAddresses.
Referenced by SecureMsgStart, SecureMsgEnable.
int SecureMsgWriteIni()
References fSecMsgEnabled, fDebugSmsg, LogPrintf, GetDataDir, SecMsgOptions::fNewAddressRecv, SecMsgOptions::fNewAddressAnon, SecMsgOptions::fScanIncoming, smsgAddresses.
Referenced by SecureMsgShutdown, SecureMsgDisable.
bool SecureMsgStart(bool fDontStart, bool fScanChain)
called from AppInit2() in init.cpp
References LogPrintf, fSecMsgEnabled, SecureMsgReadIni, smsgAddresses, SecureMsgAddWalletAddresses, SecureMsgScanBlockChain, SecureMsgBuildBucketSet, threadGroupSmsg, TraceThread, ThreadSecureMsg, ThreadSecureMsgPow.
Referenced by AppInit2.
bool SecureMsgShutdown()
References fSecMsgEnabled, LogPrintf, SecureMsgWriteIni, threadGroupSmsg, LOCK, smsgDB.
Referenced by Shutdown.
bool SecureMsgEnable()
References fSecMsgEnabled, LogPrintf, LOCK, smsgAddresses, SecureMsgReadIni, SecureMsgAddWalletAddresses, smsgBuckets, SecureMsgBuildBucketSet, threadGroupSmsg, TraceThread, ThreadSecureMsg, ThreadSecureMsgPow, cs_vNodes, vNodes, CNode::PushMessage.
Referenced by smsgenable.
bool SecureMsgDisable()
References fSecMsgEnabled, LogPrintf, LOCK, threadGroupSmsg, smsgBuckets, smsgAddresses, cs_vNodes, vNodes, CNode::smsgData, SecMsgNode::fEnabled, LOCK2, CNode::cs_vSend, SecMsgNode::cs_smsg_net, CNode::PushMessage, SecureMsgWriteIni, MilliSleep, smsgDB.
Referenced by smsgdisable.
bool SecureMsgReceiveData(CNode *pfrom, std::string strCommand, CDataStream &vRecv)
References fDebugSmsg, LogPrintf, CNode::addrName, CNode::Misbehaving, GetTime, LOCK, CNode::smsgData, SecMsgNode::cs_smsg_net, CNode::id, SecMsgNode::ignoreUntil, smsgBuckets, SMSG_RETENTION, SMSG_BUCKET_LEN, hash, SMSG_TIME_LEEWAY, CNode::PushMessage, SecMsgToken::timestamp, SecMsgToken::sample, CDataStream::resize, SecMsgToken::offset, SecureMsgRetrieve, SecureMsgReceive, SecMsgNode::lastMatched, SecMsgNode::fEnabled.
bool SecureMsgSendData(CNode *pto, bool fSendTrickle)
References LOCK, CNode::smsgData, SecMsgNode::cs_smsg_net, GetTime, SecMsgNode::lastSeen, fDebugSmsg, LogPrintf, CNode::addrName, CNode::id, CNode::PushMessage, SecMsgNode::fEnabled, SMSG_SEND_DELAY, SecMsgNode::nWakeCounter, SecMsgNode::lastMatched, GetRandInt, smsgBuckets, SecMsgBucket::setTokens, SecMsgBucket::timeChanged, hash, SecMsgBucket::hash.
Referenced by SendMessages.
bool SecureMsgScanBlock(CBlock &block)
References SecMsgOptions::fScanIncoming, fDebugSmsg, LogPrintf, LOCK, txdb, SecMsgDB::Open, SecMsgDB::TxnBegin, SecMsgDB::TxnCommit.
bool ScanChainForPublicKeys(CBlockIndex *pindexStart)
References LogPrintf, GetTimeMillis, fDebugSmsg, CBlockIndex::nHeight, LOCK, txdb, SecMsgDB::Open, SecMsgDB::TxnBegin, CBlock::ReadFromDisk, CBlockIndex::pnext, SecMsgDB::TxnCommit.
Referenced by SecureMsgScanBlockChain.
bool SecureMsgScanBlockChain()
References TRY_LOCK, cs_main, pindexGenesisBlock, LogPrintf, ScanChainForPublicKeys.
Referenced by smsgscanchain, SecureMsgStart.
bool SecureMsgScanBuckets()
References fDebugSmsg, LogPrintf, fSecMsgEnabled, pwalletMain, CCryptoKeyStore::IsLocked, GetTimeMillis, GetTime, GetDataDir, SMSG_RETENTION, LOCK, SecureMessage::hash, SMSG_HDR_LEN, SecureMessage::nPayload, SecureMsgScanMessage.
Referenced by smsgscanbuckets.
int SecureMsgWalletUnlocked()
References fSecMsgEnabled, LogPrintf, pwalletMain, CCryptoKeyStore::IsLocked, GetTime, GetDataDir, fDebugSmsg, SMSG_RETENTION, LOCK, SecureMessage::hash, SMSG_HDR_LEN, SecureMessage::nPayload, SecureMsgScanMessage, NotifySecMsgWalletUnlocked.
Referenced by CWallet::Unlock.
int SecureMsgWalletKeyChanged(std::string sAddress, std::string sLabel, ChangeType mode)
References fSecMsgEnabled, LogPrintf, LOCK, CT_NEW, smsgAddresses, SecMsgOptions::fNewAddressRecv, SecMsgOptions::fNewAddressAnon, CT_DELETED.
int SecureMsgScanMessage(uint8_t *pHeader, uint8_t *pPayload, uint32_t nPayload, bool reportToGui)
References fDebugSmsg, LogPrintf, pwalletMain, CCryptoKeyStore::IsLocked, SecureMsgStoreUnscanned, smsgAddresses, CBase58Data::ToString, SecureMsgDecrypt, MessageData::sFromAddress, SecureMessage::timestamp, SecMsgStored::timeReceived, GetTime, SecMsgStored::status, SMSG_MASK_UNREAD, SecMsgStored::sAddrTo, SecMsgStored::vchMessage, SMSG_HDR_LEN, LOCK, SecMsgDB::Open, SecMsgDB::ExistsSmesg, SecMsgDB::WriteSmesg, NotifySecMsgInboxChanged.
Referenced by ThreadSecureMsgPow, SecureMsgScanBuckets, SecureMsgWalletUnlocked, SecureMsgReceive.
int SecureMsgGetStoredKey(CKeyID &ckid, CPubKey &cpkOut)
References fDebugSmsg, LogPrintf, LOCK, SecMsgDB::Open, SecMsgDB::ReadPK.
Referenced by MessageModel::getAddressOrPubkey, smsggetpubkey, SecureMsgEncrypt.
int SecureMsgGetLocalKey(CKeyID &ckid, CPubKey &cpkOut)
References fDebugSmsg, LogPrintf, pwalletMain, CCryptoKeyStore::GetPubKey, CPubKey::IsValid, CPubKey::IsCompressed, HexStr.
Referenced by MessageModel::getAddressOrPubkey, SecureMsgGetLocalPublicKey, SecureMsgEncrypt.
int SecureMsgGetLocalPublicKey(std::string &strAddress, std::string &strPublicKey)
References CBase58Data::SetString, CDarkSilkAddress::GetKeyID, SecureMsgGetLocalKey, EncodeBase58, CPubKey::begin, CPubKey::end.
Referenced by smsggetpubkey.
int SecureMsgAddAddress(std::string &address, std::string &publicKey)
References CDarkSilkAddress::IsValid, LogPrintf, CDarkSilkAddress::GetKeyID, CBase58Data::ToString, DecodeBase58, CPubKey::IsValid, CPubKey::GetID, SecureMsgInsertAddress.
Referenced by MessageModel::sendMessages, smsgaddkey.
int SecureMsgRetrieve(SecMsgToken &token, std::vector< uint8_t > &vchData)
References fDebugSmsg, LogPrintf, SecMsgToken::timestamp, GetDataDir, SMSG_BUCKET_LEN, SecMsgToken::offset, SecureMessage::hash, SMSG_HDR_LEN, SecureMessage::nPayload.
Referenced by SecureMsgReceiveData.
int SecureMsgReceive(CNode *pfrom, std::vector< uint8_t > &vchData)
References fDebugSmsg, LogPrintf, GetTime, SMSG_TIME_LEEWAY, SMSG_RETENTION, CNode::Misbehaving, LOCK, smsgBuckets, SMSG_HDR_LEN, SecureMsgValidate, SecureMessage::nPayload, SecureMsgStore, SecureMsgScanMessage.
Referenced by SecureMsgReceiveData.
int SecureMsgStoreUnscanned(uint8_t *pHeader, uint8_t *pPayload, uint32_t nPayload)
References fDebugSmsg, LogPrintf, GetDataDir, GetTime, SecureMessage::timestamp, SMSG_TIME_LEEWAY, SMSG_RETENTION, SMSG_BUCKET_LEN, SMSG_HDR_LEN.
Referenced by SecureMsgScanMessage.
int SecureMsgStore(uint8_t *pHeader, uint8_t *pPayload, uint32_t nPayload, bool fUpdateBucket)
References fDebugSmsg, LogPrintf, AssertLockHeld, GetDataDir, GetTime, SecureMessage::timestamp, SMSG_TIME_LEEWAY, SMSG_RETENTION, SMSG_BUCKET_LEN, smsgBuckets, SecMsgToken::timestamp, SecMsgToken::sample, ValueString, SMSG_HDR_LEN, SecMsgToken::offset.
Referenced by ThreadSecureMsgPow, SecureMsgReceive, SecureMsgStore.
int SecureMsgStore(SecureMessage &smsg, bool fUpdateBucket)
References SecureMsgStore, SecureMessage::hash, SecureMessage::pPayload, SecureMessage::nPayload.
int SecureMsgSend(std::string &addressFrom, std::string &addressTo, std::string &message, std::string &sError)
References fDebugSmsg, LogPrintf, pwalletMain, CCryptoKeyStore::IsLocked, SMSG_MAX_MSG_BYTES, SecureMsgEncrypt, SecureMessage::timestamp, SecureMessage::pPayload, SecMsgStored::timeReceived, GetTime, SecMsgStored::sAddrTo, SecMsgStored::vchMessage, SMSG_HDR_LEN, SecureMessage::nPayload, SecureMessage::hash, LOCK, SecMsgDB::Open, SecMsgDB::WriteSmesg, PAIRTYPE, CWallet::mapAddressBook, IsMine, CBase58Data::ToString, CBase58Data::SetString, SecMsgStored::sAddrOutbox, NotifySecMsgOutboxChanged.
Referenced by MessageModel::sendMessages, smsgsend, smsgsendanon.
int SecureMsgValidate(uint8_t *pHeader, uint8_t *pPayload, uint32_t nPayload)
References SecureMessage::version, SMSG_MAX_MSG_WORST, SecureMessage::nonse, fDebugSmsg, LogPrintf, SMSG_HDR_LEN, SecureMessage::hash.
Referenced by SecureMsgReceive.
int SecureMsgSetHash(uint8_t *pHeader, uint8_t *pPayload, uint32_t nPayload)
References GetTimeMillis, fSecMsgEnabled, SecureMessage::nonse, SMSG_HDR_LEN, fDebugSmsg, LogPrintf, SecureMessage::hash.
Referenced by ThreadSecureMsgPow.
int SecureMsgEncrypt(SecureMessage &smsg, const std::string &addressFrom, const std::string &addressTo, const std::string &message)
References fDebugSmsg, LogPrintf, SMSG_MAX_MSG_BYTES, SecureMessage::version, SecureMessage::timestamp, GetTime, CBase58Data::SetString, CDarkSilkAddress::GetKeyID, CBase58Data::ToString, SecureMsgGetStoredKey, SecureMsgGetLocalKey, RandAddSeedPerfmon, SecureMessage::iv, CKey::MakeNewKey, CECKey::SetSecretBytes, CKey::begin, CECKey::SetPubKey, CPubKey::begin, CPubKey::size, HexStr, CECKey::GetECKey, CKey::GetPubKey, CPubKey::IsValid, CPubKey::IsCompressed, SecureMessage::cpkR, LZ4_compressBound, LZ4_compress, SMSG_PL_HDR_LEN, pwalletMain, CCryptoKeyStore::GetKey, CKey::SignCompact, Hash, SecMsgCrypter::SetKey, SecMsgCrypter::Encrypt, SecureMessage::pPayload, SecureMessage::nPayload, SecureMessage::mac.
Referenced by SecureMsgSend.
int SecureMsgDecrypt(bool fTestOnly, std::string &address, uint8_t *pHeader, uint8_t *pPayload, uint32_t nPayload, MessageData &msg)
References fDebugSmsg, LogPrintf, SecureMessage::version, CBase58Data::SetString, CDarkSilkAddress::GetKeyID, CBase58Data::ToString, pwalletMain, CCryptoKeyStore::GetKey, SecureMessage::cpkR, CPubKey::IsValid, CECKey::SetPubKey, CPubKey::begin, CPubKey::size, HexStr, CECKey::SetSecretBytes, CKey::begin, CECKey::GetECKey, SecureMessage::timestamp, SecureMessage::mac, SecMsgCrypter::SetKey, SecureMessage::iv, SecMsgCrypter::Decrypt, MessageData::timestamp, SMSG_PL_HDR_LEN, MessageData::vchMessage, LZ4_decompress_safe, MessageData::sFromAddress, CDarkSilkAddress::Set, CDarkSilkAddress::IsValid, CPubKey::RecoverCompact, Hash, CPubKey::GetID, SecureMsgInsertAddress.
Referenced by MessageTablePriv::refreshMessageTable, MessageTablePriv::newMessage, MessageTablePriv::newOutboxMessage, smsginbox, smsgoutbox, SecureMsgScanMessage, SecureMsgDecrypt.
int SecureMsgDecrypt(bool fTestOnly, std::string &address, SecureMessage &smsg, MessageData &msg)
References SecureMsgDecrypt, SecureMessage::hash, SecureMessage::pPayload, SecureMessage::nPayload.