spork.h
const unsigned int SPORK_1_STORMNODE_PAYMENTS_ENFORCEMENT
const unsigned int SPORK_2_INSTANTX
const unsigned int SPORK_3_INSTANTX_BLOCK_FILTERING
const unsigned int SPORK_5_MAX_VALUE
const unsigned int SPORK_7_STORMNODE_SCANNING
const unsigned int SPORK_8_STORMNODE_PAYMENT_ENFORCEMENT
const unsigned int SPORK_9_STORMNODE_BUDGET_ENFORCEMENT
const unsigned int SPORK_10_STORMNODE_PAY_UPDATED_NODES
const unsigned int SPORK_11_RESET_BUDGET
const unsigned int SPORK_12_RECONSIDER_BLOCKS
const unsigned int SPORK_13_ENABLE_SUPERBLOCKS
const int SPORK_1_STORMNODE_PAYMENTS_ENFORCEMENT_DEFAULT
const int SPORK_2_INSTANTX_DEFAULT
const int SPORK_3_INSTANTX_BLOCK_FILTERING_DEFAULT
const unsigned int SPORK_5_MAX_VALUE_DEFAULT
const int SPORK_7_STORMNODE_SCANNING_DEFAULT
const int SPORK_8_STORMNODE_PAYMENT_ENFORCEMENT_DEFAULT
const int SPORK_9_STORMNODE_BUDGET_ENFORCEMENT_DEFAULT
std::map<uint256, CSporkMessage> mapSporks
Referenced by ProcessSpork, CSporkManager::UpdateSpork.
std::map<int, CSporkMessage> mapSporksActive
Referenced by spork, ProcessSpork, IsSporkActive, GetSporkValue, CSporkManager::UpdateSpork.
CSporkManager sporkManager
Referenced by AppInit2, spork.
void ProcessSpork(CNode *pfrom, std::string &strCommand, CDataStream &vRecv)
References fLiteMode, spork, pindexBest, hash, mapSporksActive, fDebug, LogPrintf, base_uint< BITS >::ToString, CBlockIndex::nHeight, CSporkManager::CheckSignature, Misbehaving, CNode::GetId, mapSporks, CSporkManager::Relay, ExecuteSpork, CNode::PushMessage.
int GetSporkValue(int nSporkID)
References mapSporksActive, LogPrintf.
Referenced by IsIXTXValid.
bool IsSporkActive(int nSporkID)
References mapSporksActive, LogPrintf, GetTime.
Referenced by CBlock::CheckBlock, ProcessMessageInstantX, CMerkleTx::GetTransactionLockSignatures, IsBlockValueValid, IsBlockPayeeValid, FillBlockPayee, GetRequiredPaymentsString, CStormnodePayments::GetMinStormnodePaymentsProto, CStormnodeSync::Process.
void ExecuteSpork(int nSporkID, int nValue)
References budget, CBudgetManager::Clear, LogPrintf, ReprocessBlocks.
Referenced by ProcessSpork.
void ReprocessBlocks(int nBlocks)
References LogPrintf.
Referenced by ProcessMessageInstantX, ProcessConsensusVote, ExecuteSpork.