spork.cpp
std::map<uint256, CSporkMessage> mapSporks
Referenced by ProcessSpork, CSporkManager::UpdateSpork.
std::map<int, CSporkMessage> mapSporksActive
Referenced by spork, ProcessSpork, IsSporkActive, GetSporkValue, CSporkManager::UpdateSpork.
CSporkManager sporkManager
Referenced by AppInit2, spork.
void ProcessSpork(CNode *pfrom, std::string &strCommand, CDataStream &vRecv)
References fLiteMode, spork, pindexBest, hash, mapSporksActive, fDebug, LogPrintf, base_uint< BITS >::ToString, CBlockIndex::nHeight, CSporkManager::CheckSignature, Misbehaving, CNode::GetId, mapSporks, CSporkManager::Relay, ExecuteSpork, CNode::PushMessage.
bool IsSporkActive(int nSporkID)
References mapSporksActive, LogPrintf, GetTime.
Referenced by CBlock::CheckBlock, ProcessMessageInstantX, CMerkleTx::GetTransactionLockSignatures, IsBlockValueValid, IsBlockPayeeValid, FillBlockPayee, GetRequiredPaymentsString, CStormnodePayments::GetMinStormnodePaymentsProto, CStormnodeSync::Process.
int GetSporkValue(int nSporkID)
References mapSporksActive, LogPrintf.
Referenced by IsIXTXValid.
void ReprocessBlocks(int nBlocks)
References LogPrintf.
Referenced by ProcessMessageInstantX, ProcessConsensusVote, ExecuteSpork.
void ExecuteSpork(int nSporkID, int nValue)
References budget, CBudgetManager::Clear, LogPrintf, ReprocessBlocks.
Referenced by ProcessSpork.