stealth.h
typedef std::vector<uint8_t> data_chunk
typedef struct ec_secret ec_secret
typedef data_chunk ec_point
typedef uint32_t stealth_bitfield
const size_t ec_secret_size
Referenced by CKeyStoreIsMineVisitor::operator(), SecretToPublicKey, StealthSecret, StealthSecretSpend, StealthSharedToSecretSpend, CWallet::AddStealthAddress, CWallet::UnlockStealthAddresses, CWallet::UpdateStealthAddress, CWallet::FindStealthTransactions.
const size_t ec_compressed_size
Referenced by SecretToPublicKey, StealthSecret, StealthSecretSpend, CStealthAddress::operator<.
const size_t ec_uncompressed_size
T from_big_endian(Iterator in)
T from_little_endian(Iterator in)
void AppendChecksum(data_chunk &data)
References DarkSilkChecksum.
Referenced by CStealthAddress::Encoded.
bool VerifyChecksum(const data_chunk &data)
References DarkSilkChecksum.
Referenced by CStealthAddress::SetEncoded, IsStealthAddress.
int GenerateRandomSecret(ec_secret &out)
References RandAddSeedPerfmon, test, base_uint< BITS >::begin, ec_secret::e.
Referenced by WalletModel::sendCoins, CWallet::NewStealthAddress, CWallet::SendStealthMoneyToDestination.
int SecretToPublicKey(const ec_secret &secret, ec_point &out)
References ec_secret::e, ec_secret_size, ec_compressed_size.
Referenced by WalletModel::sendCoins, importstealthaddress, CWallet::NewStealthAddress, CWallet::UnlockStealthAddresses, CWallet::SendStealthMoneyToDestination, CWallet::FindStealthTransactions.
int StealthSecret(ec_secret &secret, ec_point &pubkey, const ec_point &pkSpend, ec_secret &sharedSOut, ec_point &pkOut)
References R, ec_secret::e, ec_secret_size, ec_compressed_size.
Referenced by WalletModel::sendCoins, CWallet::SendStealthMoneyToDestination, CWallet::FindStealthTransactions.
int StealthSecretSpend(ec_secret &scanSecret, ec_point &ephemPubkey, ec_secret &spendSecret, ec_secret &secretOut)
References ec_secret::e, ec_secret_size, ec_compressed_size.
Referenced by CWallet::UnlockStealthAddresses.
int StealthSharedToSecretSpend(ec_secret &sharedS, ec_secret &spendSecret, ec_secret &secretOut)
References ec_secret::e, ec_secret_size.
Referenced by CWallet::FindStealthTransactions.
bool IsStealthAddress(const std::string &encodedAddress)
References DecodeBase58, VerifyChecksum, version, stealth_version_byte.
Referenced by AddressTableModel::setData, SendCoinsEntry::getValue, WalletModel::validateAddress, sendtoaddress.