stormnode.h
const int STORMNODE_MIN_CONFIRMATIONS
const int STORMNODE_MIN_SNP_SECONDS
const int STORMNODE_MIN_SNB_SECONDS
const int STORMNODE_PING_SECONDS
const int STORMNODE_EXPIRATION_SECONDS
const int STORMNODE_REMOVAL_SECONDS
const int STORMNODE_CHECK_SECONDS
map<int64_t, uint256> mapCacheBlockHashes
Referenced by GetBlockHash.
bool GetBlockHash(uint256 &hash, int nBlockHeight)
References pindexBest, CBlockIndex::nHeight, mapCacheBlockHashes, CBlockIndex::GetBlockHash, hash, CBlockIndex::pprev.
Referenced by CStormnodePayments::AddWinningStormnode, CStormnode::CalculateScore, CStormnodeMan::GetStormnodeRank, CStormnodeMan::GetStormnodeRanks.