stormnode-payments.cpp
CStormnodePayments stormnodePayments
Object for who's going to get paid on which blocks
Referenced by AppInit2, ThreadCheckSandStormPool, CStormnodeSync::AddedStormnodeWinner, CStormnodeSync::Process, CStormnode::GetLastPaid, CStormnodeBroadcast::CheckAndUpdate, CStormnodePing::CheckAndUpdate, CStormnodeMan::CheckAndRemove, CStormnodeMan::CountEnabled, CStormnodeMan::GetNextStormnodeInQueueForPayment, CStormnodeMan::FindRandomNotInVec, CWallet::CreateCoinStake.
CCriticalSection cs_vecPayments
CCriticalSection cs_mapStormnodeBlocks
CCriticalSection cs_mapStormnodePayeeVotes
void DumpStormnodePayments()
References GetTimeMillis, LogPrintf, CStormnodePaymentDB::Read, CStormnodePaymentDB::FileError, CStormnodePaymentDB::Ok, CStormnodePaymentDB::IncorrectFormat, CStormnodePaymentDB::Write.
Referenced by Shutdown.
bool IsBlockValueValid(const CBlock &block, CAmount nExpectedValue)
References pindexBest, CBlockIndex::GetBlockHash, CBlockHeader::hashPrevBlock, CBlockIndex::nHeight, LogPrintf, stormnodeSync, CStormnodeSync::IsSynced, GetBudgetPaymentCycleBlocks, CBlock::vtx, IsSporkActive, budget, CBudgetManager::IsBudgetPaymentBlock.
bool IsBlockPayeeValid(const CTransaction &txNew, int nBlockHeight)
References stormnodeSync, CStormnodeSync::IsSynced, IsSporkActive, budget, CBudgetManager::IsBudgetPaymentBlock, CBudgetManager::IsTransactionValid, LogPrintf, CTransaction::ToString, CStormnodePayments::IsTransactionValid.
void FillBlockPayee(CTransaction &txNew, CAmount nFees)
References pindexBest, IsSporkActive, budget, CBudgetManager::IsBudgetPaymentBlock, CBlockIndex::nHeight, CBudgetManager::FillBlockPayee, CStormnodePayments::FillBlockPayee.
Referenced by CWallet::CreateCoinStake.
std::string GetRequiredPaymentsString(int nBlockHeight)
References IsSporkActive, budget, CBudgetManager::IsBudgetPaymentBlock, CBudgetManager::GetRequiredPaymentsString, CStormnodePayments::GetRequiredPaymentsString.
Referenced by stormnode.
bool IsReferenceNode(CTxIn &vin)
References CTxIn::prevout, COutPoint::ToStringShort.
Referenced by CStormnodePayments::AddWinningStormnode, CStormnodePaymentWinner::IsValid, CStormnodePayments::ProcessBlock.