stormnode-budget.h
CCriticalSection cs_budget
const int VOTE_ABSTAIN
const int VOTE_YES
const int VOTE_NO
const CAmount BUDGET_FEE_TX
const int64_t BUDGET_FEE_CONFIRMATIONS
const int64_t BUDGET_VOTE_UPDATE_MIN
const uint32_t FIXED_STORMNODE_BUDGET_AMOUNT
const uint32_t FIXED_STORMNODE_BUDGET_FREQUENCY
std::vector<CBudgetProposalBroadcast> vecImmatureBudgetProposals
Referenced by CBudgetManager::NewBlock, CBudgetManager::ProcessMessage.
std::vector<CFinalizedBudgetBroadcast> vecImmatureFinalizedBudgets
Referenced by CBudgetManager::NewBlock, CBudgetManager::ProcessMessage.
CBudgetManager budget
Referenced by AppInit2, snbudget, snbudgetvoteraw, snfinalbudget, ExecuteSpork, IsBlockValueValid, IsBlockPayeeValid, FillBlockPayee, GetRequiredPaymentsString, CStormnodePayments::ProcessBlock, CStormnodeSync::AddedBudgetItem.
void DumpBudgets()
References GetTimeMillis, LogPrintf, CBudgetDB::Read, CBudgetDB::FileError, CBudgetDB::Ok, CBudgetDB::IncorrectFormat, CBudgetDB::Write.
Referenced by Shutdown.
int GetBudgetPaymentCycleBlocks()
References Params, CChainParams::MAIN.
Referenced by snbudget, CBudgetManager::SubmitFinalBudget, CBudgetManager::CheckAndRemove, CBudgetManager::HasNextFinalizedBudget, CBudgetManager::GetBudget, CBudgetProposal::CBudgetProposal, CBudgetProposal::IsValid, CBudgetProposal::GetBlockStartCycle, CBudgetProposal::GetBlockCurrentCycle, CBudgetProposal::GetBlockEndCycle, CBudgetProposal::GetTotalPaymentCount, CBudgetProposal::GetRemainingPaymentCount, CFinalizedBudget::IsValid, IsBlockValueValid.
bool IsBudgetCollateralValid(uint256 nTxCollateralHash, uint256 nExpectedHash, std::string &strError, int64_t &nTime, int &nConf)
References GetTransaction, strprintf, CTransaction::ToString, LogPrintf, CTransaction::vout, CTransaction::nLockTime, OP_RETURN, ToByteVector, CTxOut::scriptPubKey, CScript::IsNormalPaymentScript, CScript::IsUnspendable, CTxOut::nValue, base_uint< BITS >::ToString, GetIXConfirmations, mapBlockIndex, CBlockIndex::IsInMainChain, nBestHeight, CBlockIndex::nHeight, CBlockIndex::nTime.
Referenced by snbudget, CBudgetManager::NewBlock, CBudgetManager::ProcessMessage, CBudgetProposal::IsValid, CFinalizedBudget::IsValid.