ui_interface.h
ChangeType
CClientUIInterface uiInterface
Referenced by CAlert::ProcessAlert, AbortNode, CheckDiskSpace, ThreadSocketHandler, noui_connect, main, WalletModel::sendCoins, StartRPCThreads, AddTimeData, CWallet::SendStealthMoney, CWallet::TopUpKeyPool.
std::string _(const char *psz)
Translation function: Call Translate signal on UI interface, which returns a boost::optional result. If no translation slot is registered, nothing is returned, and simply return the input.
References CClientUIInterface::Translate.
Referenced by AppInit, CCoinsViewErrorCatcher::GetCoins, HelpMessage, AppInit2, AbortNode, CheckDiskSpace, GetWarnings, CBlock::SetBestChain, BindListenPort, CallRPC, importwallet, StartRPCThreads, CSandstormPool::GetStatus, CSandstormPool::CheckTimeout, CSandstormPool::StatusUpdate, CSandstormPool::DoAutomaticDenominating, CSandstormPool::CreateDenominated, CSandstormPool::GetMessageByID, CSandStormSigner::SetKey, CSandStormSigner::SignMessage, CSandStormSigner::VerifyMessage, CStormnodeSync::GetSyncStatus, AddTimeData, CWallet::SendStealthMoney, CWallet::SendMoney, CWallet::SendMoneyToDestination, CWallet::PrepareSandstormDenominate, CWallet::TopUpKeyPool.