uint256.h
const signed char p_util_hexdigit[256][256]
Referenced by HexDigit.
signed char HexDigit(char c)
References p_util_hexdigit.
Referenced by CBigNum::SetHex, base_uint< BITS >::SetHex, IsHex, ParseHex.