utilstrencodings.h
BEGIN
Utilities for converting data from/to strings.
END
UBEGIN
UEND
ARRAYLEN
PAIRTYPE
This is needed because the foreach macro can't get over the comma in pair<t1, t2>
std::vector<unsigned char> DecodeBase64(const char *p, bool *pfInvalid=NULL)
Referenced by I2PSession::GenerateB32AddressFromDestination, verifymessage, HTTPAuthorized, snbudgetvoteraw, BOOST_AUTO_TEST_CASE, DecodeBase64.
std::string DecodeBase64(const std::string &str)
std::string EncodeBase64(const unsigned char *pch, size_t len)
Referenced by CallRPC, signmessage, BOOST_AUTO_TEST_CASE, EncodeBase64.
std::string EncodeBase64(const std::string &str)
SecureString DecodeBase64Secure(const SecureString &input)
References mem.
SecureString EncodeBase64Secure(const SecureString &input)
References mem.
std::vector<unsigned char> DecodeBase32(const char *p, bool *pfInvalid=NULL)
Referenced by CNetAddr::SetSpecial, BOOST_AUTO_TEST_CASE, DecodeBase32.
std::string DecodeBase32(const std::string &str)
std::string EncodeBase32(const unsigned char *pch, size_t len)
Referenced by I2PSession::GenerateB32AddressFromDestination, CNetAddr::ToStringIP, BOOST_AUTO_TEST_CASE, EncodeBase32.
std::string EncodeBase32(const std::string &str)
std::string i64tostr(int64_t n)
References strprintf.
std::string itostr(int n)
References strprintf.
Referenced by CallRPC, keypoolrefill.
int64_t atoi64(const char *psz)
Referenced by ParseMoney, GetArg, CWalletTx::SerializationOp.
int64_t atoi64(const std::string &str)
int atoi(const std::string &str)
References atoi.
Referenced by CActiveStormnode::SelectCoinsStormnode, leveldb::DBTest::NumTableFilesAtLevel, leveldb::TEST, leveldb::test::RandomSeed, CNode::EndMessage, ReadHTTPRequestLine, ReadHTTPStatus, ReadHTTPHeaders, stormnode, atoi, GetBoolArg.
bool ParseInt32(const std::string &str, int32_t *out)
Convert string to signed 32-bit integer with strict parse error feedback. true if the entire string could be parsed as valid integer, false if not the entire string could be parsed or when overflow or underflow occurred.
std::string FormatParagraph(const std::string in, size_t width=79, size_t indent=0)
Format a paragraph of text to a fixed width, adding spaces for indentation to any added line.