util.h
BEGIN
Referenced by CBlockHeader::GetHash, CBlockHeader::GetPoWArgonHash, CBlock::BuildMerkleTree, CBlock::CheckMerkleBranch, SendMessages, getworkex, getwork, CSporkMessage::GetHash.
END
Referenced by CBlockHeader::GetHash, CBlockHeader::GetPoWArgonHash, CBlock::BuildMerkleTree, CBlock::CheckMerkleBranch, SendMessages, getworkex, getwork, CSporkMessage::GetHash.
UBEGIN
UEND
ARRAYLEN
Referenced by CMainParams::CMainParams, CTestNetParams::CTestNetParams, CInv::CInv, CInv::IsKnownType.
UVOIDBEGIN
CVOIDBEGIN
Referenced by CBlockHeader::GetPoWHash.
UINTBEGIN
CUINTBEGIN
PRIszx
PRIszu
Referenced by WalletModel::sendCoins, smsgbuckets, _createmultisig, CWallet::SendStealthMoneyToDestination.
PRIszd
PRIpdx
PRIpdu
PRIpdd
PAIRTYPE
Referenced by CAlert::ProcessAlert, ComputeNextStakeModifier, GetTransaction, GetWarnings, AddressTablePriv::refreshAddressTable, getnetworkinfo, HTTPPost, RPCTypeCheck, smsglocalkeys, stormnodelist, WalletTxToJSON, getaddressesbyaccount, GetAccountAddresses, getbalance, ListReceived, ListTransactions, listaccounts, CSandstormPool::GetDenominations, Solver, SecureMsgAddWalletAddresses, SecureMsgSend, CStormnodeMan::GetNextStormnodeInQueueForPayment, CStormnodeMan::GetStormnodeRank, CStormnodeMan::GetStormnodeRanks, CStormnodeMan::GetStormnodeByRank, CTxDB::LoadBlockIndex, ParseParameters, CWallet::MarkDirty, CWalletTx::GetAccountAmounts, CWallet::ReacceptWalletTransactions, CWallet::ResendWalletTransactions, CWallet::SelectCoinsMinConfByCoinAge, CWallet::GetStakeWeight, CWallet::CreateCoinStake, CWallet::CommitTransaction, CWallet::GetAddressBalances, CWallet::GetAddressGroupings.
MAX_PATH
LogPrintf
Referenced by CActiveStormnode::ManageStatus, CActiveStormnode::Register, CActiveStormnode::EnableHotColdStormNode, CAddrMan::Check, CUnsignedAlert::print, CBlock::AcceptBlock, CBlock::RebuildAddressIndex, CBlock::ConnectBlock, InvalidChainFound, Reorganize, CBlock::CheckBlock, EncryptAES256, DecryptAES256, CDBEnv::Open, CDBEnv::Salvage, CDB::Rewrite, CCoinsViewErrorCatcher::GetCoins, Shutdown, AppInit2, ProcessMessageInstantX, CreateNewLock, DoConsensusVote, ProcessConsensusVote, CheckForConflictingLocks, CleanTransactionLocksList, CConsensusVote::SignatureValid, CConsensusVote::Sign, CTransactionLock::SignaturesValid, ComputeNextStakeModifier, CheckStakeKernelHash, HandleError, CLevelDBWrapper::CLevelDBWrapper, CLevelDBWrapper::Read, CLevelDBWrapper::Exists, AbortNode, CMerkleTx::SetMerkleBranch, Misbehaving, DisconnectBlocksAndReprocess, FindTransactionsByDestination, ProcessBlock, CheckDiskSpace, PrintBlockTree, LoadExternalBlockFile, ProcessMessages, SendMessages, OpenDiskFile, CBlock::SetBestChain, CVerifyDB::VerifyDB, CreateNewBlock, CheckWork, CheckStake, AddLocal, ConnectNode, CNode::Misbehaving, SocketSendData, ThreadSocketHandler, ThreadDNSAddressSeed, ThreadOpenConnections, BindListenPort, StartNode, StopNode, CNetCleanup::~CNetCleanup, CMessageHeader::IsValid, CInv::print, OverviewPage::sandStormStatus, importwallet, StartRPCThreads, ServiceConnection, SendMoney, CSandStormRelay::Sign, CSandStormRelay::VerifyMessage, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::SetCollateralAddress, CSandstormPool::CheckFinalTransaction, CSandstormPool::ChargeFees, CSandstormPool::ChargeRandomFees, CSandstormPool::IsCollateralValid, CSandstormPool::AddScriptSig, CSandstormPool::SendSandstormDenominate, CSandstormPool::StatusUpdate, CSandstormPool::SignFinalTransaction, CSandstormPool::CompletedTransaction, CSandstormPool::DoAutomaticDenominating, CSandstormPool::PrepareSandstormDenominate, CSandstormPool::MakeCollateralAmounts, CSandstormPool::CreateDenominated, CSandstormPool::IsCompatibleWithEntries, CSandstormPool::IsCompatibleWithSession, CSandstormPool::GetDenominationsByAmount, CSandStormSigner::VerifyMessage, CSandstormQueue::Sign, CSandstormPool::RelayIn, CSandstormPool::UpdateState, SignatureHash, LoopForever, TraceThread, SecMsgBucket::hashBucket, SecMsgDB::Open, SecMsgDB::ScanBatch, SecMsgDB::TxnCommit, SecMsgDB::ReadPK, SecMsgDB::WritePK, SecMsgDB::NextSmesg, SecMsgDB::ReadSmesg, SecMsgDB::WriteSmesg, SecMsgDB::EraseSmesg, ThreadSecureMsg, ThreadSecureMsgPow, SecureMsgBuildBucketSet, SecureMsgAddWalletAddresses, SecureMsgReadIni, SecureMsgWriteIni, SecureMsgStart, SecureMsgShutdown, SecureMsgEnable, SecureMsgDisable, SecureMsgReceiveData, SecureMsgSendData, SecureMsgScanBlock, ScanChainForPublicKeys, SecureMsgScanBlockChain, SecureMsgScanBuckets, SecureMsgWalletUnlocked, SecureMsgWalletKeyChanged, SecureMsgScanMessage, SecureMsgGetLocalKey, SecureMsgGetStoredKey, SecureMsgAddAddress, SecureMsgRetrieve, SecureMsgReceive, SecureMsgStoreUnscanned, SecureMsgStore, SecureMsgValidate, SecureMsgSetHash, SecureMsgEncrypt, SecureMsgSend, SecureMsgDecrypt, ProcessSpork, IsSporkActive, GetSporkValue, ReprocessBlocks, ExecuteSpork, CSporkManager::Sign, CSporkManager::SetPrivKey, IsBudgetCollateralValid, CBudgetManager::CheckOrphanVotes, CBudgetManager::SubmitFinalBudget, CBudgetDB::Write, CBudgetDB::Read, DumpBudgets, CBudgetManager::AddProposal, CBudgetManager::CheckAndRemove, CBudgetManager::FillBlockPayee, CBudgetManager::HasNextFinalizedBudget, CBudgetManager::GetRequiredPaymentsString, CBudgetManager::NewBlock, CBudgetManager::ProcessMessage, CBudgetManager::Sync, CBudgetManager::UpdateProposal, CBudgetManager::UpdateFinalizedBudget, CBudgetVote::Sign, CBudgetVote::SignatureValid, CFinalizedBudget::AutoCheck, CFinalizedBudget::GetStatus, CFinalizedBudget::IsTransactionValid, CFinalizedBudget::SubmitVote, CFinalizedBudgetVote::Sign, CFinalizedBudgetVote::SignatureValid, CBudgetManager::Clear, CStormnodePaymentDB::Write, CStormnodePaymentDB::Read, DumpStormnodePayments, IsBlockValueValid, IsBlockPayeeValid, CStormnodePayments::FillBlockPayee, CStormnodePayments::ProcessMessageStormnodePayments, CStormnodePaymentWinner::Sign, CStormnodeBlockPayees::IsTransactionValid, CStormnodePaymentWinner::IsValid, CStormnodePayments::ProcessBlock, CStormnodeSync::GetNextAsset, CStormnodeSync::ProcessMessage, CStormnodeSync::Process, CStormnode::CalculateScore, CStormnodeBroadcast::CheckAndUpdate, CStormnodeBroadcast::CheckInputsAndAdd, CStormnodeBroadcast::Sign, CStormnodePing::Sign, CStormnodePing::CheckAndUpdate, CStormnodeDB::Write, CStormnodeDB::Read, DumpStormnodes, CStormnodeMan::AskForSN, CStormnodeMan::SsegUpdate, CStormnodeMan::FindRandomNotInVec, CStormnodeMan::ProcessStormnodeConnections, CStormnodeMan::ProcessMessage, AddTimeData, CTxDB::CTxDB, CTxDB::TxnCommit, CTxDB::LoadBlockIndex, CTxDB::Read, CTxDB::Write, CTxMemPool::WriteFeeEstimates, CTxMemPool::ReadFeeEstimates, PrintException, PrintExceptionContinue, runCommand, CWallet::LoadCScript, CWallet::ChangeWalletPassphrase, CWallet::EncryptWallet, CWallet::AddToWallet, CWalletTx::GetAmounts, CWalletTx::AddSupportingTransactions, CWallet::ReacceptWalletTransactions, CWalletTx::RelayWalletTransaction, CWallet::ResendWalletTransactions, CWallet::SelectCoinsMinConf, CWallet::GetBudgetSystemCollateralTX, CWallet::ConvertList, CWallet::CreateTransaction, CWallet::CreateStealthTransaction, CWallet::SendStealthMoney, CWallet::SendStealthMoneyToDestination, CWallet::FindStealthTransactions, CWallet::CreateCoinStake, CWallet::CommitTransaction, CWallet::SendMoney, CWallet::GetTotalValue, CWallet::PrepareSandstormDenominate, CWallet::NewKeyPool, CWallet::TopUpKeyPool, CWallet::ReserveKeyFromKeyPool, CWallet::KeepKey, CWallet::ReturnKey, CWallet::FixSpentCoins, CReserveKey::GetReservedKey, COutput::print, CWalletDB::LoadWallet, BackupWallet, CWalletDB::Recover.
MAKE_ERROR_AND_LOG_FUNC
THREAD_PRIORITY_LOWEST
Referenced by ThreadStakeMiner.
THREAD_PRIORITY_BELOW_NORMAL
Referenced by ThreadMessageHandler.
THREAD_PRIORITY_NORMAL
Referenced by ThreadStakeMiner.
THREAD_PRIORITY_ABOVE_NORMAL
const int LISTING_DEFAULT_DURATION
bool fStormNode
Referenced by CActiveStormnode::ManageStatus, CActiveStormnode::EnableHotColdStormNode, AppInit2, DoConsensusVote, OverviewPage::OverviewPage, OverviewPage::~OverviewPage, sandstorm, stormnode, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::Check, CSandstormPool::CheckFinalTransaction, CSandstormPool::ChargeFees, CSandstormPool::ChargeRandomFees, CSandstormPool::CheckTimeout, CSandstormPool::CheckForCompleteQueue, CSandstormPool::AddEntry, CSandstormPool::SendSandstormDenominate, CSandstormPool::StatusUpdate, CSandstormPool::SignFinalTransaction, CSandstormPool::CompletedTransaction, CSandstormPool::DoAutomaticDenominating, CSandstormQueue::Sign, CSandstormPool::UpdateState, CFinalizedBudget::AutoCheck, CStormnodePayments::ProcessBlock, CStormnodeBroadcast::CheckInputsAndAdd, CWallet::SelectCoinsDark, CWalletTx::GetAnonymizableCredit.
bool fLiteMode
Referenced by AppInit2, ProcessMessageInstantX, OverviewPage::OverviewPage, OverviewPage::~OverviewPage, SendCoinsDialog::SendCoinsDialog, getinfo, CSandstormPool::ProcessMessageSandstorm, ThreadCheckSandStormPool, ProcessSpork, CBudgetManager::ProcessMessage, CStormnodePayments::ProcessMessageStormnodePayments, CStormnodeMan::ProcessMessage, CWallet::GetAnonymizableBalance, CWallet::GetAnonymizedBalance, CWallet::GetAverageAnonymizedRounds, CWallet::GetNormalizedAnonymizedBalance, CWallet::GetDenominatedBalance.
bool fEnableInstantX
Referenced by AppInit2, CMerkleTx::GetTransactionLockSignatures, CMerkleTx::IsTransactionLockTimedOut.
int nInstantXDepth
Referenced by HelpMessage, AppInit2, CMerkleTx::GetDepthInMainChain, GetInputAgeIX, GetIXConfirmations.
int nSandstormRounds
Referenced by HelpMessage, AppInit2, OptionsModel::Init, OptionsModel::data, OptionsModel::setData, OverviewPage::updateSandstormProgress, WalletModel::pollBalanceChanged, CSandstormPool::DoAutomaticDenominating, CSandstormPool::PrepareSandstormDenominate, CWallet::GetAnonymizableBalance, CWallet::GetAnonymizedBalance, CWallet::GetInputSandstormRounds, CWallet::GetNormalizedAnonymizedBalance, CWallet::GetDenominatedBalance, CWalletTx::GetAnonymizableCredit.
int nAnonymizeDarkSilkAmount
Referenced by HelpMessage, AppInit2, OptionsModel::Init, OptionsModel::data, OptionsModel::setData, OverviewPage::updateSandstormProgress, CSandstormPool::DoAutomaticDenominating.
int nLiquidityProvider
Referenced by HelpMessage, AppInit2, CSandstormPool::DoAutomaticDenominating.
bool fEnableSandstorm
Referenced by HelpMessage, AppInit2, OverviewPage::OverviewPage, OverviewPage::sandStormStatus, sandstorm, CSandstormPool::CheckTimeout, CSandstormPool::CheckForCompleteQueue, CSandstormPool::SendSandstormDenominate, CSandstormPool::DoAutomaticDenominating.
bool fSandstormMultiSession
Referenced by HelpMessage, AppInit2, CSandstormPool::DoAutomaticDenominating.
int64_t enforceStormnodePaymentsTime
Spork enforcement enabled time
Referenced by stormnode.
std::string strStormNodeAddr
Referenced by CActiveStormnode::ManageStatus, AppInit2.
int nStormnodeMinProtocol
Referenced by AppInit2.
int keysLoaded
bool fSucessfullyLoaded
std::vector<CAmount> sandStormDenominations
All denominations used by sandstorm
Referenced by CSandstormPool::DoAutomaticDenominating, CSandstormPool::CreateDenominated, CSandstormPool::GetDenominations, CSandstormPool::GetDenominationsByAmount, CSandstormPool::InitDenominations, CWallet::IsDenominatedAmount, less_then_denom, CWallet::PrepareSandstormDenominate, CWalletTx::GetAnonymizableCredit, COutput::Priority.
std::string strBudgetMode
Referenced by AppInit2, CBudgetManager::NewBlock, CFinalizedBudget::AutoCheck.
bool fDebug
Referenced by CActiveStormnode::ManageStatus, CBlock::ConnectBlock, CBlock::CheckBlock, AppInit2, CheckStakeKernelHash, CheckProofOfStake, SendMessages, CreateNewBlock, TransactionDesc::toHTML, WalletModel::sendCoins, CSandStormSigner::VerifyMessage, ProcessSpork, CStealthAddress::SetEncoded, CStormnodeSync::Process, AddTimeData, LogAcceptCategory, CWallet::Lock, CWallet::EncryptWallet, CWallet::SelectCoinsMinConfByCoinAge, CWallet::SelectCoinsMinConf, CWallet::NewStealthAddress, CWallet::UnlockStealthAddresses, CWallet::UpdateStealthAddress, CWallet::SendStealthMoneyToDestination, CWallet::FindStealthTransactions, ReadKeyValue.
bool fDebugSmsg
Referenced by AppInit2, SecMsgBucket::hashBucket, ThreadSecureMsg, SecureMsgBuildBucketSet, SecureMsgAddWalletAddresses, SecureMsgReadIni, SecureMsgWriteIni, SecureMsgReceiveData, SecureMsgSendData, SecureMsgScanBlock, ScanChainForPublicKeys, SecureMsgScanBuckets, SecureMsgWalletUnlocked, SecureMsgScanMessage, SecureMsgGetLocalKey, SecureMsgGetStoredKey, SecureMsgRetrieve, SecureMsgReceive, SecureMsgStoreUnscanned, SecureMsgStore, SecureMsgValidate, SecureMsgSetHash, SecureMsgEncrypt, SecureMsgSend, SecureMsgDecrypt.
bool fNoSmsg
Referenced by AppInit2.
bool fPrintToConsole
Referenced by AppInit2, LogPrintStr.
bool fPrintToDebugLog
Referenced by AppInit2, LogPrintStr.
bool fServer
Referenced by AppInit2, walletpassphrase.
bool fCommandLine
Referenced by AppInit.
std::string strMiscWarning
Referenced by AbortNode, CheckDiskSpace, GetWarnings, CBlock::SetBestChain, AddTimeData, PrintException, PrintExceptionContinue.
bool fNoListen
Referenced by AppInit2, SendMessages, GetLocal.
bool fLogTimestamps
Referenced by AppInit2, LogPrintStr.
volatile bool fReopenDebugLog
Referenced by HandleSIGHUP, LogPrintStr.
std::map<std::string, std::string> mapArgs
Referenced by AppInit, AppInit2, CreateNewBlock, ThreadOpenConnections, CNode::EndMessage, main, OptionsModel::Init, OptionsModel::data, CallRPC, StartRPCThreads, ServiceConnection, ParseParameters, GetArg, GetBoolArg, SoftSetArg, GetDataDir.
std::map<std::string, std::vector<std::string> > mapMultiArgs
Referenced by AppInit, AppInit2, ThreadOpenConnections, ThreadOpenAddedConnections, main, OptionsModel::Init, OptionsModel::data, ClientAllowed, LogAcceptCategory, ParseParameters.
const std::string strTimestampFormat
uint32_t insecure_rand_Rz
MWC RNG of George Marsaglia This is intended to be fast. It has a period of 2^59.3, though the least significant 16 bits only have a period of about 2^30.1.random value
uint32_t insecure_rand_Rw
T* alignup(T *p)
boost::filesystem::path GetStormnodeConfigFile()
References GetArg, GetDataDir.
Referenced by CStormnodeConfig::read.
void MilliSleep(int64_t n)
Referenced by DetectShutdownThread, CDB::Rewrite, AppInit2, GetHeight, ThreadStakeMiner, RecvLine, ThreadSocketHandler, ThreadDNSAddressSeed, ThreadOpenConnections, ThreadOpenAddedConnections, ThreadMessageHandler, CallRPC, ServiceConnection, CSandstormPool::UnlockCoins, CSandstormPool::SendSandstormDenominate, ThreadCheckSandStormPool, LoopForever, ThreadSecureMsg, ThreadSecureMsgPow, SecureMsgDisable, ThreadFlushWalletDB, BackupWallet.
bool IsLogOpen()
bool LogAcceptCategory(const char *category)
References fDebug, mapMultiArgs.
Referenced by ComputeNextStakeModifier.
int LogPrintStr(const std::string &str)
References fPrintToConsole, fPrintToDebugLog, fReopenDebugLog, GetDataDir, fLogTimestamps, DateTimeStrFormat, GetTime.
std::string GenerateRandomString(unsigned int len=24)
References rand.
Referenced by WriteConfigFile.
void WriteConfigFile(FILE *configFile)
References GenerateRandomString, RandomIntegerRange.
Referenced by ReadConfigFile.
bool FileExists(const char *fileName)
unsigned int RandomIntegerRange(unsigned int nMin, unsigned int nMax)
References rand.
Referenced by WriteConfigFile.
static int LogPrint(const char *category, const char *format)
static bool error(const char *format)
static int errorN(int n, const char *format)
void RandAddSeed()
References GetPerformanceCounter.
Referenced by CInit::CInit, RandAddSeedPerfmon.
void RandAddSeedPerfmon()
References RandAddSeed, GetTime.
Referenced by AppInit2, CKey::MakeNewKey, SecureMsgEncrypt, GenerateRandomSecret, CWallet::EncryptWallet.
void PrintException(std::exception *pex, const char *pszThread)
References LogPrintf, strMiscWarning.
Referenced by AppInit, CommandLineRPC, LoopForever, TraceThread.
void PrintExceptionContinue(std::exception *pex, const char *pszThread)
References LogPrintf, strMiscWarning.
Referenced by ProcessMessages.
void ParseString(const std::string &str, char c, std::vector< std::string > &v)
std::string FormatMoney(CAmount n, bool fPlus=false)
References strprintf.
Referenced by CBlockIndex::ToString, GetProofOfWorkReward, PrintBlockTree, CheckWork, CheckStake, CTxOut::ToString, SendMoney, CWallet::ReacceptWalletTransactions, CWallet::SelectCoinsMinConfByCoinAge, CWallet::SelectCoinsMinConf, CWallet::SendStealthMoney, CWallet::SendMoney, CWallet::FixSpentCoins, COutput::ToString.
bool ParseMoney(const std::string &str, CAmount &nRet)
bool ParseMoney(const char *pszIn, CAmount &nRet)
References atoi64.
std::string SanitizeString(const std::string &str)
std::vector<unsigned char> ParseHex(const char *psz)
References HexDigit.
Referenced by CMainParams::CMainParams, CTestNetParams::CTestNetParams, CDBEnv::Salvage, importaddress, getstakesubsidy, getworkex, getwork, submitblock, validatepubkey, sendalert, decoderawtransaction, signrawtransaction, sendrawtransaction, ParseHexV, _createmultisig, addmultisigaddress, importstealthaddress, CSporkManager::CheckSignature, BOOST_AUTO_TEST_CASE, ParseHex.
std::vector<unsigned char> ParseHex(const std::string &str)
bool IsHex(const std::string &str)
std::vector<unsigned char> DecodeBase64(const char *p, bool *pfInvalid=NULL)
std::string DecodeBase64(const std::string &str)
std::string EncodeBase64(const unsigned char *pch, size_t len)
std::string EncodeBase64(const std::string &str)
SecureString DecodeBase64Secure(const SecureString &input)
SecureString EncodeBase64Secure(const SecureString &input)
std::vector<unsigned char> DecodeBase32(const char *p, bool *pfInvalid=NULL)
std::string DecodeBase32(const std::string &str)
std::string EncodeBase32(const unsigned char *pch, size_t len)
std::string EncodeBase32(const std::string &str)
void ParseParameters(int argc, const char *const argv[])
References mapArgs, mapMultiArgs, PAIRTYPE.
Referenced by AppInit, main.
bool WildcardMatch(const char *psz, const char *mask)
References WildcardMatch.
Referenced by ClientAllowed, WildcardMatch.
bool WildcardMatch(const std::string &str, const std::string &mask)
bool TryCreateDirectory(const boost::filesystem::path &p)
Ignores exceptions thrown by Boost's create_directory if the requested directory exists. Specifically handles case where path p exists, but it wasn't possible for the user to write to the parent directory.
Referenced by CLevelDBWrapper::CLevelDBWrapper.
void FileCommit(FILE *fileout)
Referenced by CBlock::WriteToDisk, CAddrDB::Write.
bool RenameOver(boost::filesystem::path src, boost::filesystem::path dest)
Referenced by ThreadImport, CAddrDB::Write.
boost::filesystem::path GetDefaultDataDir()
Referenced by AppInit2, GetDataDir.
const boost::filesystem::path& GetDataDir(bool fNetSpecific=true)
References LOCK, CChainParams::MAX_NETWORK_TYPES, Params, CChainParams::NetworkID, mapArgs, GetDefaultDataDir, CChainParams::DataDir.
Referenced by AppInit, CDB::CDB, Shutdown, AppInit2, CheckDiskSpace, ThreadImport, GetBlockPosFilename, CAddrDB::CAddrDB, CAddrDB::Write, main, GUIUtil::openDebugLogfile, StartRPCThreads, smsgbuckets, SecMsgDB::Open, ThreadSecureMsg, SecureMsgBuildBucketSet, SecureMsgReadIni, SecureMsgWriteIni, SecureMsgScanBuckets, SecureMsgWalletUnlocked, SecureMsgRetrieve, SecureMsgStoreUnscanned, SecureMsgStore, CBudgetDB::CBudgetDB, CStormnodePaymentDB::CStormnodePaymentDB, CStormnodeDB::CStormnodeDB, LogPrintStr, GetConfigFile, GetStormnodeConfigFile, GetPidFile, ShrinkDebugFile, BackupWallet.
boost::filesystem::path GetConfigFile()
References GetArg, GetDataDir.
Referenced by AppInit2, CallRPC, StartRPCThreads, ReadConfigFile.
boost::filesystem::path GetPidFile()
References GetArg, GetDataDir.
Referenced by AppInit, Shutdown.
void CreatePidFile(const boost::filesystem::path &path, pid_t pid)
Referenced by AppInit.
void ReadConfigFile(std::map< std::string, std::string > &mapSettingsRet, std::map< std::string, std::vector< std::string > > &mapMultiSettingsRet)
std::string getTimeString(int64_t timestamp, char *buffer, size_t nBuffer)
Referenced by smsginbox, smsgoutbox, smsgbuckets.
std::string bytesReadable(uint64_t nBytes)
References strprintf.
Referenced by smsgbuckets.
void ShrinkDebugFile()
References GetDataDir.
Referenced by AppInit2.
bool GetRandBytes(unsigned char *buf, int num)
Referenced by CAddrMan::CAddrMan, CKey::MakeNewKey, CKey::VerifyPubKey, ECC_Start, SendMessages, CNode::PushVersion, CAddrDB::Write, StartRPCThreads, GetRand, GetRandHash, seed_insecure_rand, CWallet::EncryptWallet.
int GetRandInt(int nMax)
References GetRand.
Referenced by CAddrMan::SelectTried, CAddrMan::ShrinkNew, CAddrMan::Good_, CAddrMan::Add_, CAddrMan::Select_, CAddrMan::GetAddr_, SecureMsgSendData, CStormnodeMan::FindRandomNotInVec, BOOST_AUTO_TEST_CASE, CWallet::SelectCoinsMinConf, CWallet::PrepareSandstormDenominate.
uint64_t GetRand(uint64_t nMax)
References GetRandBytes.
Referenced by ThreadDNSAddressSeed, ThreadMessageHandler, CNode::EndMessage, GetRandInt, CWallet::ResendWalletTransactions.
uint256 GetRandHash()
References hash, GetRandBytes.
Referenced by LimitOrphanTxSize, SendMessages, CSignatureCache::Set.
int64_t GetTime()
Referenced by IsInitialBlockDownload, AppInit2, ProcessMessageInstantX, CreateNewLock, ProcessConsensusVote, CheckForConflictingLocks, CleanTransactionLocksList, AcceptToMemoryPool, AcceptableInputs, CMerkleTx::IsTransactionLockTimedOut, SendMessages, CBlock::SetBestChain, ThreadStakeMiner, ConnectNode, CNode::PushVersion, CNode::IsBanned, CNode::Misbehaving, SocketSendData, ThreadSocketHandler, ThreadDNSAddressSeed, ThreadOpenConnections, RelayTransaction, CNode::CNode, CNode::AskFor, DarkSilkGUI::setNumBlocks, OverviewPage::sandStormStatus, dumpwallet, getworkex, getwork, getblocktemplate, walletpassphrase, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::CheckForCompleteQueue, CSandstormPool::NewBlock, CSandstormPool::IsCompatibleWithSession, CSandStormEntry::Add, CSandStormEntry::IsExpired, CSandstormQueue::IsExpired, SecMsgBucket::hashBucket, ThreadSecureMsg, SecureMsgBuildBucketSet, SecureMsgReceiveData, SecureMsgSendData, SecureMsgScanBuckets, SecureMsgWalletUnlocked, SecureMsgScanMessage, SecureMsgReceive, SecureMsgStoreUnscanned, SecureMsgStore, SecureMsgEncrypt, SecureMsgSend, IsSporkActive, CSporkManager::UpdateSpork, CBudgetManager::NewBlock, CBudgetManager::UpdateProposal, CBudgetManager::UpdateFinalizedBudget, CBudgetProposal::AddOrUpdateVote, CFinalizedBudget::AddOrUpdateVote, CBudgetProposal::IsEstablished, CStormnodeSync::IsBlockchainSynced, CStormnodeSync::Reset, CStormnodeSync::AddedStormnodeList, CStormnodeSync::AddedStormnodeWinner, CStormnodeSync::AddedBudgetItem, CStormnodeSync::GetNextAsset, CStormnodeSync::Process, CStormnode::Check, CStormnodeMan::AskForSN, CStormnodeMan::CheckAndRemove, CStormnodeMan::SsegUpdate, CStormnodeMan::ProcessMessage, GetAdjustedTime, RandAddSeedPerfmon, LogPrintStr, CWallet::GenerateNewKey, CWallet::ResendWalletTransactions, CWallet::GetStakeWeight, CWallet::GetOldestKeyPoolTime, CKeyPool::CKeyPool, CWalletKey::CWalletKey, ThreadFlushWalletDB, CWalletDB::Recover.
void SetMockTime(int64_t nMockTimeIn)
std::string FormatFullVersion()
References CLIENT_BUILD.
Referenced by AppInit, AppInit2, ClientModel::formatFullVersion, GUIUtil::HelpMessageBox::HelpMessageBox, getinfo, HTTPPost, HTTPReply.
std::string FormatSubVersion(const std::string &name, int nClientVersion, const std::vector< std::string > &comments)
References FormatVersion.
Referenced by CAlert::AppliesToMe, CNode::PushVersion, getnetworkinfo.
void runCommand(std::string strCommand)
References LogPrintf.
Referenced by CAlert::ProcessAlert, CBlock::SetBestChain, CWallet::AddToWallet.
bool TruncateFile(FILE *file, unsigned int length)
bool ParseInt32(const std::string &str, int32_t *out)
Convert string to signed 32-bit integer with strict parse error feedback. true if the entire string could be parsed as valid integer, false if not the entire string could be parsed or when overflow or underflow occurred.
std::string FormatParagraph(const std::string in, size_t width=79, size_t indent=0)
Format a paragraph of text to a fixed width, adding spaces for indentation to any added line.
std::string i64tostr(int64_t n)
std::string itostr(int n)
Referenced by CallRPC, keypoolrefill.
int64_t atoi64(const char *psz)
Referenced by ParseMoney, GetArg, CWalletTx::SerializationOp.
int64_t atoi64(const std::string &str)
int atoi(const std::string &str)
Referenced by CActiveStormnode::SelectCoinsStormnode, leveldb::DBTest::NumTableFilesAtLevel, leveldb::TEST, leveldb::test::RandomSeed, CNode::EndMessage, ReadHTTPRequestLine, ReadHTTPStatus, ReadHTTPHeaders, stormnode, atoi, GetBoolArg.
int roundint(double d)
int64_t roundint64(double d)
Referenced by AmountFromValue.
int64_t abs64(int64_t n)
Referenced by AddTimeData.
std::string leftTrim(std::string src, char chr)
Referenced by blockToJSON.
std::string HexStr(const T itbegin, const T itend, bool fSpaces=false)
Referenced by CBlock::ToString, CTxIn::ToString, WalletModel::sendCoins, blockToJSON, checkkernel, getworkex, getwork, getblocktemplate, ScriptPubKeyToJSON, TxToJSON, getrawtransaction, createrawtransaction, signrawtransaction, searchrawtransactions, createmultisig, getnewpubkey, makekeypair, liststealthaddresses, ValueString, HexStr, SecureMsgGetLocalKey, SecureMsgEncrypt, SecureMsgDecrypt, CWallet::SendStealthMoneyToDestination.
std::string HexStr(const T &vch, bool fSpaces=false)
References HexStr.
int64_t GetPerformanceCounter()
Referenced by RandAddSeed.
int64_t GetTimeMillis()
Referenced by CDBEnv::Flush, AppInit2, LoadExternalBlockFile, DumpAddresses, getnettotals, CSandstormPool::SetNull, CSandstormPool::Check, CSandstormPool::CheckTimeout, CSandstormPool::DoAutomaticDenominating, CSandstormPool::IsCompatibleWithSession, CSandstormPool::UpdateState, ScanChainForPublicKeys, SecureMsgScanBuckets, SecureMsgSetHash, CBudgetDB::Write, CBudgetDB::Read, DumpBudgets, CStormnodePaymentDB::Write, CStormnodePaymentDB::Read, DumpStormnodePayments, CStormnodeDB::Write, CStormnodeDB::Read, DumpStormnodes, CWallet::ChangeWalletPassphrase, CWallet::EncryptWallet, ThreadFlushWalletDB.
int64_t GetTimeMicros()
Referenced by CBlock::ConnectBlock, SendMessages, CNode::copyStats, CNode::ReceiveMsgBytes, ThreadSocketHandler.
std::string DateTimeStrFormat(const char *pszFormat, int64_t nTime)
Referenced by InvalidChainFound, AppInit2, ComputeNextStakeModifier, CheckStakeKernelHash, PrintBlockTree, CBlock::SetBestChain, CNode::AskFor, getcheckpoint, DateTimeStrFormat, CTxDB::LoadBlockIndex, LogPrintStr.
std::string DateTimeStrFormat(int64_t nTime)
References DateTimeStrFormat.
void skipspaces(T &it)
bool IsSwitchChar(char c)
Referenced by AppInit, CommandLineRPC.
std::string GetArg(const std::string &strArg, const std::string &strDefault)
Return string argument or default value strArg Argument to get (e.g. "-foo") default (e.g. "1") command-line argument or default value
References mapArgs.
Referenced by CAlert::ProcessAlert, CDBEnv::Open, CDB::Flush, AppInit2, AcceptToMemoryPool, AcceptableInputs, Misbehaving, CBlock::SetBestChain, CreateNewBlock, GetListenPort, CNode::Misbehaving, ThreadSocketHandler, StartNode, ReceiveFloodSize, SendBufferSize, main, OptionsModel::data, CallRPC, StartRPCThreads, keypoolrefill, CSignatureCache::Set, BOOST_AUTO_TEST_CASE, CTxDB::LoadBlockIndex, GetConfigFile, GetStormnodeConfigFile, GetPidFile, CWallet::AddToWallet, CWallet::NewKeyPool, CWallet::TopUpKeyPool.
int64_t GetArg(const std::string &strArg, int64_t nDefault)
Return integer argument or default value strArg Argument to get (e.g. "-foo") default (e.g. 1) command-line argument (0 if invalid number) or default value
References mapArgs, atoi64.
bool GetBoolArg(const std::string &strArg, bool fDefault)
Return boolean argument or default value strArg Argument to get (e.g. "-foo") default (true or false) command-line argument or default value
References mapArgs, atoi.
Referenced by CActiveStormnode::SelectCoinsStormnode, SelectParamsFromCommandLine, AppInit, CDBEnv::Open, AppInit2, GetWarnings, CreateNewBlock, ThreadDNSAddressSeed, StartNode, main, DarkSilkGUI::DarkSilkGUI, OptionsModel::data, OverviewPage::OverviewPage, CallRPC, getstakinginfo, StartRPCThreads, CRPCTable::execute, BOOST_AUTO_TEST_CASE, ThreadFlushWalletDB.
bool SoftSetArg(const std::string &strArg, const std::string &strValue)
Set an argument if it doesn't already have a value strArg Argument to set (e.g. "-foo") strValue Value (e.g. "1") true if argument gets set, false if it already had a value
References mapArgs.
Referenced by AppInit2, OptionsModel::Init, SoftSetBoolArg.
bool SoftSetBoolArg(const std::string &strArg, bool fValue)
Set a boolean argument if it doesn't already have a value strArg Argument to set (e.g. "-foo") fValue Value (e.g. false) true if argument gets set, false if it already had a value
References SoftSetArg.
Referenced by AppInit, AppInit2, OptionsModel::Init, CWalletDB::LoadWallet.
static uint32_t insecure_rand(void)
void seed_insecure_rand(bool fDeterministic=false)
Seed insecure_rand using the random pool. Deterministic Use a determinstic seed
References GetRandBytes.
bool TimingResistantEqual(const T &a, const T &b)
Timing-attack-resistant comparison. Takes time proportional to length of first argument.
Referenced by HTTPAuthorized.
void SetThreadPriority(int nPriority)
Referenced by ThreadStakeMiner, ThreadMessageHandler.
void RenameThread(const char *name)
Referenced by Shutdown, ThreadImport, ThreadStakeMiner, ThreadCheckSandStormPool, LoopForever, TraceThread, ThreadFlushWalletDB.
uint32_t ByteReverse(uint32_t value)
Referenced by SHA256Transform, FormatHashBuffers, getworkex, getwork.
void LoopForever(const char *name, Callable func, int64_t msecs)
References strprintf, RenameThread, LogPrintf, MilliSleep, func, PrintException.
Referenced by StartNode.
void TraceThread(const char *name, Callable func)
References strprintf, RenameThread, LogPrintf, func, PrintException.
Referenced by StartNode, SecureMsgStart, SecureMsgEnable.