utilstrencodings.cpp
string EncodeBase64(const unsigned char *pch, size_t len)
Referenced by EncodeBase64.
string EncodeBase64(const string &str)
References EncodeBase64.
vector<unsigned char> DecodeBase64(const char *p, bool *pfInvalid)
Referenced by DecodeBase64.
string DecodeBase64(const string &str)
References DecodeBase64.
SecureString EncodeBase64Secure(const SecureString &input)
References mem.
SecureString DecodeBase64Secure(const SecureString &input)
References mem.
string EncodeBase32(const unsigned char *pch, size_t len)
Referenced by EncodeBase32.
string EncodeBase32(const string &str)
References EncodeBase32.
vector<unsigned char> DecodeBase32(const char *p, bool *pfInvalid)
Referenced by DecodeBase32.
string DecodeBase32(const string &str)
References DecodeBase32.
bool ParseInt32(const std::string &str, int32_t *out)
Convert string to signed 32-bit integer with strict parse error feedback. true if the entire string could be parsed as valid integer, false if not the entire string could be parsed or when overflow or underflow occurred.
std::string FormatParagraph(const std::string in, size_t width, size_t indent)
Format a paragraph of text to a fixed width, adding spaces for indentation to any added line.
std::string i64tostr(int64_t n)
References strprintf.
std::string itostr(int n)
References strprintf.
int64_t atoi64(const char *psz)
int64_t atoi64(const std::string &str)
int atoi(const std::string &str)
References atoi.