util.cpp
bool fStormNode
Referenced by CActiveStormnode::ManageStatus, CActiveStormnode::EnableHotColdStormNode, AppInit2, DoConsensusVote, OverviewPage::OverviewPage, OverviewPage::~OverviewPage, sandstorm, stormnode, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::Check, CSandstormPool::CheckFinalTransaction, CSandstormPool::ChargeFees, CSandstormPool::ChargeRandomFees, CSandstormPool::CheckTimeout, CSandstormPool::CheckForCompleteQueue, CSandstormPool::AddEntry, CSandstormPool::SendSandstormDenominate, CSandstormPool::StatusUpdate, CSandstormPool::SignFinalTransaction, CSandstormPool::CompletedTransaction, CSandstormPool::DoAutomaticDenominating, CSandstormQueue::Sign, CSandstormPool::UpdateState, CFinalizedBudget::AutoCheck, CStormnodePayments::ProcessBlock, CStormnodeBroadcast::CheckInputsAndAdd, CWallet::SelectCoinsDark, CWalletTx::GetAnonymizableCredit.
string strStormNodePrivKey
Referenced by CActiveStormnode::ManageStatus, AppInit2, CConsensusVote::Sign, snbudget, snfinalbudget, CSandstormPool::CheckFinalTransaction, CSandstormQueue::Sign, CFinalizedBudget::SubmitVote, CStormnodePayments::ProcessBlock.
string strStormNodeAddr
Referenced by CActiveStormnode::ManageStatus, AppInit2.
bool fLiteMode
Referenced by AppInit2, ProcessMessageInstantX, OverviewPage::OverviewPage, OverviewPage::~OverviewPage, SendCoinsDialog::SendCoinsDialog, getinfo, CSandstormPool::ProcessMessageSandstorm, ThreadCheckSandStormPool, ProcessSpork, CBudgetManager::ProcessMessage, CStormnodePayments::ProcessMessageStormnodePayments, CStormnodeMan::ProcessMessage, CWallet::GetAnonymizableBalance, CWallet::GetAnonymizedBalance, CWallet::GetAverageAnonymizedRounds, CWallet::GetNormalizedAnonymizedBalance, CWallet::GetDenominatedBalance.
bool fEnableInstantX
Referenced by AppInit2, CMerkleTx::GetTransactionLockSignatures, CMerkleTx::IsTransactionLockTimedOut.
int nInstantXDepth
Referenced by HelpMessage, AppInit2, CMerkleTx::GetDepthInMainChain, GetInputAgeIX, GetIXConfirmations.
int nSandstormRounds
Referenced by HelpMessage, AppInit2, OptionsModel::Init, OptionsModel::data, OptionsModel::setData, OverviewPage::updateSandstormProgress, WalletModel::pollBalanceChanged, CSandstormPool::DoAutomaticDenominating, CSandstormPool::PrepareSandstormDenominate, CWallet::GetAnonymizableBalance, CWallet::GetAnonymizedBalance, CWallet::GetInputSandstormRounds, CWallet::GetNormalizedAnonymizedBalance, CWallet::GetDenominatedBalance, CWalletTx::GetAnonymizableCredit.
int nAnonymizeDarkSilkAmount
Referenced by HelpMessage, AppInit2, OptionsModel::Init, OptionsModel::data, OptionsModel::setData, OverviewPage::updateSandstormProgress, CSandstormPool::DoAutomaticDenominating.
int nLiquidityProvider
Referenced by HelpMessage, AppInit2, CSandstormPool::DoAutomaticDenominating.
int64_t enforceStormnodePaymentsTime
Spork enforcement enabled time
Referenced by stormnode.
int nStormnodeMinProtocol
Referenced by AppInit2.
bool fSucessfullyLoaded
bool fEnableSandstorm
Referenced by HelpMessage, AppInit2, OverviewPage::OverviewPage, OverviewPage::sandStormStatus, sandstorm, CSandstormPool::CheckTimeout, CSandstormPool::CheckForCompleteQueue, CSandstormPool::SendSandstormDenominate, CSandstormPool::DoAutomaticDenominating.
std::vector<CAmount> sandStormDenominations
All denominations used by sandstorm
Referenced by CSandstormPool::DoAutomaticDenominating, CSandstormPool::CreateDenominated, CSandstormPool::GetDenominations, CSandstormPool::GetDenominationsByAmount, CSandstormPool::InitDenominations, CWallet::IsDenominatedAmount, less_then_denom, CWallet::PrepareSandstormDenominate, CWalletTx::GetAnonymizableCredit, COutput::Priority.
bool fSandstormMultiSession
Referenced by HelpMessage, AppInit2, CSandstormPool::DoAutomaticDenominating.
map<string, string> mapArgs
Referenced by AppInit, AppInit2, CreateNewBlock, ThreadOpenConnections, CNode::EndMessage, main, OptionsModel::Init, OptionsModel::data, CallRPC, StartRPCThreads, ServiceConnection, ParseParameters, GetArg, GetBoolArg, SoftSetArg, GetDataDir.
map<string, vector<string> > mapMultiArgs
Referenced by AppInit, AppInit2, ThreadOpenConnections, ThreadOpenAddedConnections, main, OptionsModel::Init, OptionsModel::data, ClientAllowed, LogAcceptCategory, ParseParameters.
bool fDebug
Referenced by CActiveStormnode::ManageStatus, CBlock::ConnectBlock, CBlock::CheckBlock, AppInit2, CheckStakeKernelHash, CheckProofOfStake, SendMessages, CreateNewBlock, TransactionDesc::toHTML, WalletModel::sendCoins, CSandStormSigner::VerifyMessage, ProcessSpork, CStealthAddress::SetEncoded, CStormnodeSync::Process, AddTimeData, LogAcceptCategory, CWallet::Lock, CWallet::EncryptWallet, CWallet::SelectCoinsMinConfByCoinAge, CWallet::SelectCoinsMinConf, CWallet::NewStealthAddress, CWallet::UnlockStealthAddresses, CWallet::UpdateStealthAddress, CWallet::SendStealthMoneyToDestination, CWallet::FindStealthTransactions, ReadKeyValue.
bool fDebugSmsg
Referenced by AppInit2, SecMsgBucket::hashBucket, ThreadSecureMsg, SecureMsgBuildBucketSet, SecureMsgAddWalletAddresses, SecureMsgReadIni, SecureMsgWriteIni, SecureMsgReceiveData, SecureMsgSendData, SecureMsgScanBlock, ScanChainForPublicKeys, SecureMsgScanBuckets, SecureMsgWalletUnlocked, SecureMsgScanMessage, SecureMsgGetLocalKey, SecureMsgGetStoredKey, SecureMsgRetrieve, SecureMsgReceive, SecureMsgStoreUnscanned, SecureMsgStore, SecureMsgValidate, SecureMsgSetHash, SecureMsgEncrypt, SecureMsgSend, SecureMsgDecrypt.
bool fNoSmsg
Referenced by AppInit2.
bool fPrintToConsole
Referenced by AppInit2, LogPrintStr.
bool fPrintToDebugLog
Referenced by AppInit2, LogPrintStr.
bool fDaemon
Referenced by AppInit, main.
bool fServer
Referenced by AppInit2, walletpassphrase.
bool fCommandLine
Referenced by AppInit.
string strMiscWarning
Referenced by AbortNode, CheckDiskSpace, GetWarnings, CBlock::SetBestChain, AddTimeData, PrintException, PrintExceptionContinue.
bool fNoListen
Referenced by AppInit2, SendMessages, GetLocal.
bool fLogTimestamps
Referenced by AppInit2, LogPrintStr.
volatile bool fReopenDebugLog
Referenced by HandleSIGHUP, LogPrintStr.
string strBudgetMode
Referenced by AppInit2, CBudgetManager::NewBlock, CFinalizedBudget::AutoCheck.
CCriticalSection** ppmutexOpenSSL
class CInit instance_of_cinit
boost::once_flag debugPrintInitFlag
FILE* fileout
boost::mutex* mutexDebugLog
const signed char p_util_hexdigit[256][256]
Referenced by HexDigit.
boost::filesystem::path pathCached[CChainParams::MAX_NETWORK_TYPES+1][CChainParams::MAX_NETWORK_TYPES+1]
CCriticalSection csPathCached
int64_t nMockTime
uint32_t insecure_rand_Rz
MWC RNG of George Marsaglia This is intended to be fast. It has a period of 2^59.3, though the least significant 16 bits only have a period of about 2^30.1.random value
uint32_t insecure_rand_Rw
void locking_callback(int mode, int i, const char *file, int line)
References ENTER_CRITICAL_SECTION, LEAVE_CRITICAL_SECTION.
Referenced by CInit::CInit.
bool GetRandBytes(unsigned char *buf, int num)
Referenced by CAddrMan::CAddrMan, CKey::MakeNewKey, CKey::VerifyPubKey, ECC_Start, SendMessages, CNode::PushVersion, CAddrDB::Write, StartRPCThreads, GetRand, GetRandHash, seed_insecure_rand, CWallet::EncryptWallet.
void RandAddSeed()
References GetPerformanceCounter.
Referenced by CInit::CInit, RandAddSeedPerfmon.
void RandAddSeedPerfmon()
References RandAddSeed, GetTime.
Referenced by AppInit2, CKey::MakeNewKey, SecureMsgEncrypt, GenerateRandomSecret, CWallet::EncryptWallet.
uint64_t GetRand(uint64_t nMax)
References GetRandBytes.
Referenced by ThreadDNSAddressSeed, ThreadMessageHandler, CNode::EndMessage, GetRandInt, CWallet::ResendWalletTransactions.
int GetRandInt(int nMax)
References GetRand.
Referenced by CAddrMan::SelectTried, CAddrMan::ShrinkNew, CAddrMan::Good_, CAddrMan::Add_, CAddrMan::Select_, CAddrMan::GetAddr_, SecureMsgSendData, CStormnodeMan::FindRandomNotInVec, BOOST_AUTO_TEST_CASE, CWallet::SelectCoinsMinConf, CWallet::PrepareSandstormDenominate.
uint256 GetRandHash()
References hash, GetRandBytes.
Referenced by LimitOrphanTxSize, SendMessages, CSignatureCache::Set.
static void DebugPrintInit()
bool LogAcceptCategory(const char *category)
References fDebug, mapMultiArgs.
Referenced by ComputeNextStakeModifier.
int LogPrintStr(const std::string &str)
References fPrintToConsole, fPrintToDebugLog, fReopenDebugLog, GetDataDir, fLogTimestamps, DateTimeStrFormat, GetTime.
void ParseString(const string &str, char c, vector< string > &v)
string FormatMoney(CAmount n, bool fPlus)
References strprintf.
Referenced by CBlockIndex::ToString, GetProofOfWorkReward, PrintBlockTree, CheckWork, CheckStake, CTxOut::ToString, SendMoney, CWallet::ReacceptWalletTransactions, CWallet::SelectCoinsMinConfByCoinAge, CWallet::SelectCoinsMinConf, CWallet::SendStealthMoney, CWallet::SendMoney, CWallet::FixSpentCoins, COutput::ToString.
bool ParseMoney(const string &str, CAmount &nRet)
Referenced by AppInit2, CreateNewBlock.
bool ParseMoney(const char *pszIn, CAmount &nRet)
References atoi64.
static string safeChars("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890 .,;-/:?@")
string SanitizeString(const string &str)
Referenced by CAlert::ProcessAlert, snbudget, snfinalbudget, CBudgetProposal::IsValid.
bool IsHex(const string &str)
References HexDigit.
Referenced by importaddress, checkkernel, createrawtransaction, signrawtransaction, ParseHashV, ParseHexV, _createmultisig, addmultisigaddress, importstealthaddress.
vector<unsigned char> ParseHex(const char *psz)
References HexDigit.
Referenced by CMainParams::CMainParams, CTestNetParams::CTestNetParams, CDBEnv::Salvage, importaddress, getstakesubsidy, getworkex, getwork, submitblock, validatepubkey, sendalert, decoderawtransaction, signrawtransaction, sendrawtransaction, ParseHexV, _createmultisig, addmultisigaddress, importstealthaddress, CSporkManager::CheckSignature, BOOST_AUTO_TEST_CASE, ParseHex.
vector<unsigned char> ParseHex(const string &str)
References ParseHex.
static void InterpretNegativeSetting(string name, map< string, string > &mapSettingsRet)
void ParseParameters(int argc, const char *const argv[])
References mapArgs, mapMultiArgs, PAIRTYPE.
Referenced by AppInit, main.
std::string GetArg(const std::string &strArg, const std::string &strDefault)
Return string argument or default value strArg Argument to get (e.g. "-foo") default (e.g. "1") command-line argument or default value
References mapArgs.
Referenced by CAlert::ProcessAlert, CDBEnv::Open, CDB::Flush, AppInit2, AcceptToMemoryPool, AcceptableInputs, Misbehaving, CBlock::SetBestChain, CreateNewBlock, GetListenPort, CNode::Misbehaving, ThreadSocketHandler, StartNode, ReceiveFloodSize, SendBufferSize, main, OptionsModel::data, CallRPC, StartRPCThreads, keypoolrefill, CSignatureCache::Set, BOOST_AUTO_TEST_CASE, CTxDB::LoadBlockIndex, GetConfigFile, GetStormnodeConfigFile, GetPidFile, CWallet::AddToWallet, CWallet::NewKeyPool, CWallet::TopUpKeyPool.
int64_t GetArg(const std::string &strArg, int64_t nDefault)
Return integer argument or default value strArg Argument to get (e.g. "-foo") default (e.g. 1) command-line argument (0 if invalid number) or default value
References mapArgs, atoi64.
bool GetBoolArg(const std::string &strArg, bool fDefault)
Return boolean argument or default value strArg Argument to get (e.g. "-foo") default (true or false) command-line argument or default value
References mapArgs, atoi.
Referenced by CActiveStormnode::SelectCoinsStormnode, SelectParamsFromCommandLine, AppInit, CDBEnv::Open, AppInit2, GetWarnings, CreateNewBlock, ThreadDNSAddressSeed, StartNode, main, DarkSilkGUI::DarkSilkGUI, OptionsModel::data, OverviewPage::OverviewPage, CallRPC, getstakinginfo, StartRPCThreads, CRPCTable::execute, BOOST_AUTO_TEST_CASE, ThreadFlushWalletDB.
bool SoftSetArg(const std::string &strArg, const std::string &strValue)
Set an argument if it doesn't already have a value strArg Argument to set (e.g. "-foo") strValue Value (e.g. "1") true if argument gets set, false if it already had a value
References mapArgs.
Referenced by AppInit2, OptionsModel::Init, SoftSetBoolArg.
bool SoftSetBoolArg(const std::string &strArg, bool fValue)
Set a boolean argument if it doesn't already have a value strArg Argument to set (e.g. "-foo") fValue Value (e.g. false) true if argument gets set, false if it already had a value
References SoftSetArg.
Referenced by AppInit, AppInit2, OptionsModel::Init, CWalletDB::LoadWallet.
string EncodeBase64(const unsigned char *pch, size_t len)
Referenced by CallRPC, signmessage, BOOST_AUTO_TEST_CASE, EncodeBase64.
string EncodeBase64(const string &str)
References EncodeBase64.
vector<unsigned char> DecodeBase64(const char *p, bool *pfInvalid)
Referenced by I2PSession::GenerateB32AddressFromDestination, verifymessage, HTTPAuthorized, snbudgetvoteraw, BOOST_AUTO_TEST_CASE, DecodeBase64.
string DecodeBase64(const string &str)
References DecodeBase64.
SecureString EncodeBase64Secure(const SecureString &input)
SecureString DecodeBase64Secure(const SecureString &input)
string EncodeBase32(const unsigned char *pch, size_t len)
Referenced by I2PSession::GenerateB32AddressFromDestination, CNetAddr::ToStringIP, BOOST_AUTO_TEST_CASE, EncodeBase32.
string EncodeBase32(const string &str)
References EncodeBase32.
vector<unsigned char> DecodeBase32(const char *p, bool *pfInvalid)
Referenced by CNetAddr::SetSpecial, BOOST_AUTO_TEST_CASE, DecodeBase32.
string DecodeBase32(const string &str)
References DecodeBase32.
bool WildcardMatch(const char *psz, const char *mask)
References WildcardMatch.
Referenced by ClientAllowed, WildcardMatch.
bool WildcardMatch(const string &str, const string &mask)
References WildcardMatch.
bool ParseInt32(const std::string &str, int32_t *out)
Convert string to signed 32-bit integer with strict parse error feedback. true if the entire string could be parsed as valid integer, false if not the entire string could be parsed or when overflow or underflow occurred.
std::string FormatParagraph(const std::string in, size_t width, size_t indent)
Format a paragraph of text to a fixed width, adding spaces for indentation to any added line.
static std::string FormatException(std::exception *pex, const char *pszThread)
void PrintException(std::exception *pex, const char *pszThread)
References LogPrintf, strMiscWarning.
Referenced by AppInit, CommandLineRPC, LoopForever, TraceThread.
void PrintExceptionContinue(std::exception *pex, const char *pszThread)
References LogPrintf, strMiscWarning.
Referenced by ProcessMessages.
boost::filesystem::path GetDefaultDataDir()
Referenced by AppInit2, GetDataDir.
const boost::filesystem::path& GetDataDir(bool fNetSpecific)
References LOCK, CChainParams::MAX_NETWORK_TYPES, Params, CChainParams::NetworkID, mapArgs, GetDefaultDataDir, CChainParams::DataDir.
Referenced by AppInit, CDB::CDB, Shutdown, AppInit2, CheckDiskSpace, ThreadImport, GetBlockPosFilename, CAddrDB::CAddrDB, CAddrDB::Write, main, GUIUtil::openDebugLogfile, StartRPCThreads, smsgbuckets, SecMsgDB::Open, ThreadSecureMsg, SecureMsgBuildBucketSet, SecureMsgReadIni, SecureMsgWriteIni, SecureMsgScanBuckets, SecureMsgWalletUnlocked, SecureMsgRetrieve, SecureMsgStoreUnscanned, SecureMsgStore, CBudgetDB::CBudgetDB, CStormnodePaymentDB::CStormnodePaymentDB, CStormnodeDB::CStormnodeDB, LogPrintStr, GetConfigFile, GetStormnodeConfigFile, GetPidFile, ShrinkDebugFile, BackupWallet.
void ClearDatadirCache()
References CChainParams::MAX_NETWORK_TYPES.
Referenced by ReadConfigFile.
boost::filesystem::path GetConfigFile()
References GetArg, GetDataDir.
Referenced by AppInit2, CallRPC, StartRPCThreads, ReadConfigFile.
boost::filesystem::path GetStormnodeConfigFile()
References GetArg, GetDataDir.
Referenced by CStormnodeConfig::read.
std::string GenerateRandomString(unsigned int len)
References rand.
Referenced by WriteConfigFile.
unsigned int RandomIntegerRange(unsigned int nMin, unsigned int nMax)
References rand.
Referenced by WriteConfigFile.
void WriteConfigFile(FILE *configFile)
References GenerateRandomString, RandomIntegerRange.
Referenced by ReadConfigFile.
bool FileExists(const char *fileName)
void ReadConfigFile(map< string, string > &mapSettingsRet, map< string, vector< string > > &mapMultiSettingsRet)
References GetConfigFile, WriteConfigFile, ClearDatadirCache.
Referenced by AppInit, main.
boost::filesystem::path GetPidFile()
References GetArg, GetDataDir.
Referenced by AppInit, Shutdown.
void CreatePidFile(const boost::filesystem::path &path, pid_t pid)
Referenced by AppInit.
bool RenameOver(boost::filesystem::path src, boost::filesystem::path dest)
Referenced by ThreadImport, CAddrDB::Write.
bool TryCreateDirectory(const boost::filesystem::path &p)
Ignores exceptions thrown by Boost's create_directory if the requested directory exists. Specifically handles case where path p exists, but it wasn't possible for the user to write to the parent directory.
Referenced by CLevelDBWrapper::CLevelDBWrapper.
void FileCommit(FILE *fileout)
Referenced by CBlock::WriteToDisk, CAddrDB::Write.
std::string getTimeString(int64_t timestamp, char *buffer, size_t nBuffer)
Referenced by smsginbox, smsgoutbox, smsgbuckets.
std::string bytesReadable(uint64_t nBytes)
References strprintf.
Referenced by smsgbuckets.
void ShrinkDebugFile()
References GetDataDir.
Referenced by AppInit2.
int64_t GetTime()
Referenced by IsInitialBlockDownload, AppInit2, ProcessMessageInstantX, CreateNewLock, ProcessConsensusVote, CheckForConflictingLocks, CleanTransactionLocksList, AcceptToMemoryPool, AcceptableInputs, CMerkleTx::IsTransactionLockTimedOut, SendMessages, CBlock::SetBestChain, ThreadStakeMiner, ConnectNode, CNode::PushVersion, CNode::IsBanned, CNode::Misbehaving, SocketSendData, ThreadSocketHandler, ThreadDNSAddressSeed, ThreadOpenConnections, RelayTransaction, CNode::CNode, CNode::AskFor, DarkSilkGUI::setNumBlocks, OverviewPage::sandStormStatus, dumpwallet, getworkex, getwork, getblocktemplate, walletpassphrase, CSandstormPool::ProcessMessageSandstorm, CSandstormPool::CheckForCompleteQueue, CSandstormPool::NewBlock, CSandstormPool::IsCompatibleWithSession, CSandStormEntry::Add, CSandStormEntry::IsExpired, CSandstormQueue::IsExpired, SecMsgBucket::hashBucket, ThreadSecureMsg, SecureMsgBuildBucketSet, SecureMsgReceiveData, SecureMsgSendData, SecureMsgScanBuckets, SecureMsgWalletUnlocked, SecureMsgScanMessage, SecureMsgReceive, SecureMsgStoreUnscanned, SecureMsgStore, SecureMsgEncrypt, SecureMsgSend, IsSporkActive, CSporkManager::UpdateSpork, CBudgetManager::NewBlock, CBudgetManager::UpdateProposal, CBudgetManager::UpdateFinalizedBudget, CBudgetProposal::AddOrUpdateVote, CFinalizedBudget::AddOrUpdateVote, CBudgetProposal::IsEstablished, CStormnodeSync::IsBlockchainSynced, CStormnodeSync::Reset, CStormnodeSync::AddedStormnodeList, CStormnodeSync::AddedStormnodeWinner, CStormnodeSync::AddedBudgetItem, CStormnodeSync::GetNextAsset, CStormnodeSync::Process, CStormnode::Check, CStormnodeMan::AskForSN, CStormnodeMan::CheckAndRemove, CStormnodeMan::SsegUpdate, CStormnodeMan::ProcessMessage, GetAdjustedTime, RandAddSeedPerfmon, LogPrintStr, CWallet::GenerateNewKey, CWallet::ResendWalletTransactions, CWallet::GetStakeWeight, CWallet::GetOldestKeyPoolTime, CKeyPool::CKeyPool, CWalletKey::CWalletKey, ThreadFlushWalletDB, CWalletDB::Recover.
void SetMockTime(int64_t nMockTimeIn)
void seed_insecure_rand(bool fDeterministic)
Seed insecure_rand using the random pool. Deterministic Use a determinstic seed
References GetRandBytes.
string FormatVersion(int nVersion)
References strprintf.
Referenced by FormatSubVersion.
string FormatFullVersion()
References CLIENT_BUILD.
Referenced by AppInit, AppInit2, ClientModel::formatFullVersion, GUIUtil::HelpMessageBox::HelpMessageBox, getinfo, HTTPPost, HTTPReply.
std::string FormatSubVersion(const std::string &name, int nClientVersion, const std::vector< std::string > &comments)
References FormatVersion.
Referenced by CAlert::AppliesToMe, CNode::PushVersion, getnetworkinfo.
void runCommand(std::string strCommand)
References LogPrintf.
Referenced by CAlert::ProcessAlert, CBlock::SetBestChain, CWallet::AddToWallet.
void RenameThread(const char *name)
Referenced by Shutdown, ThreadImport, ThreadStakeMiner, ThreadCheckSandStormPool, LoopForever, TraceThread, ThreadFlushWalletDB.
std::string DateTimeStrFormat(const char *pszFormat, int64_t nTime)
Referenced by InvalidChainFound, AppInit2, ComputeNextStakeModifier, CheckStakeKernelHash, PrintBlockTree, CBlock::SetBestChain, CNode::AskFor, getcheckpoint, DateTimeStrFormat, CTxDB::LoadBlockIndex, LogPrintStr.
bool TruncateFile(FILE *file, unsigned int length)