walletdb.cpp
uint64_t nAccountingEntryNumber
bool fWalletUnlockStakingOnly
bool ReadKeyValue(CWallet *pwallet, CDataStream &ssKey, CDataStream &ssValue, CWalletScanState &wss, string &strType, string &strErr)
References CWallet::mapAddressBook, CDarkSilkAddress::Get, hash, CWallet::mapWallet, state, CValidationState::IsValid, CDataStream::empty, strprintf, CWalletScanState::vWalletUpgrade, CWalletScanState::fAnyUnordered, CWallet::AddToWallet, fDebug, CWallet::stealthAddresses, CWallet::LoadWatchOnly, CWallet::nTimeFirstKey, CWalletScanState::nKeys, CWalletKey::vchPrivKey, Hash, CKey::Load, CWallet::LoadKey, CWallet::mapMasterKeys, CWallet::nMasterKeyMaxID, CWalletScanState::nCKeys, CWallet::LoadCryptedKey, CWalletScanState::fIsEncrypted, CWalletScanState::nKeyMeta, CWallet::LoadKeyMetadata, CWallet::mapStealthKeyMeta, CWallet::vchDefaultKey, CWallet::setKeyPool, CWallet::mapKeyMetadata, CWalletScanState::nFileVersion, CWallet::LoadCScript, CWallet::nOrderPosNext.
Referenced by CWalletDB::LoadWallet, CWalletDB::Recover.
static bool IsKeyType(string strType)
void ThreadFlushWalletDB(const string &strFile)
References RenameThread, GetBoolArg, nWalletDBUpdated, GetTime, MilliSleep, TRY_LOCK, bitdb, CDBEnv::cs_db, CDBEnv::mapFileUseCount, GetTimeMillis, CDBEnv::CloseDb, CDBEnv::CheckpointLSN.
bool BackupWallet(const CWallet &wallet, const string &strDest)
References CWallet::fFileBacked, LOCK, bitdb, CDBEnv::cs_db, CDBEnv::mapFileUseCount, CWallet::strWalletFile, CDBEnv::CloseDb, CDBEnv::CheckpointLSN, GetDataDir, LogPrintf, MilliSleep.
Referenced by WalletModel::backupWallet, backupwallet.