xxhash.c
XXH_FORCE_NATIVE_FORMAT
Referenced by XXH32, XXH32_update, XXH32_intermediateDigest.
FORCE_INLINE
_PACKED_XXH
A32_XXH
Referenced by XXH_readLE32_align.
GCC_VERSION
XXH_rotl32
Referenced by XXH32_endian_align, XXH32_update_endian, XXH32_intermediateDigest_endian.
PRIME32_1
Referenced by XXH32_endian_align, XXH32_resetState, XXH32_update_endian, XXH32_intermediateDigest_endian.
PRIME32_2
Referenced by XXH32_endian_align, XXH32_resetState, XXH32_update_endian, XXH32_intermediateDigest_endian.
PRIME32_3
Referenced by XXH32_endian_align, XXH32_intermediateDigest_endian.
PRIME32_4
Referenced by XXH32_endian_align, XXH32_intermediateDigest_endian.
PRIME32_5
Referenced by XXH32_endian_align, XXH32_intermediateDigest_endian.
XXH_CPU_LITTLE_ENDIAN
Referenced by XXH32, XXH32_update, XXH32_intermediateDigest.
XXH_STATIC_ASSERT
Referenced by XXH32_sizeofState.
XXH_endianess
XXH_alignment
typedef unsigned char BYTE
typedef unsigned short U16
typedef unsigned int U32
typedef signed int S32
typedef unsigned long long U64
typedef struct _U32_S U32_S_XXH
const int one
FORCE_INLINE void* XXH_malloc(size_t s)
Referenced by XXH32_init.
FORCE_INLINE void XXH_free(void *p)
Referenced by XXH32_digest.
FORCE_INLINE void* XXH_memcpy(void *dest, const void *src, size_t size)
Referenced by XXH32_update_endian.
static U32 XXH_swap32(U32 x)
FORCE_INLINE U32 XXH_readLE32_align(const U32 *ptr, XXH_endianess endian, XXH_alignment align)
References XXH_unaligned, XXH_littleEndian, A32_XXH.
Referenced by XXH_readLE32, XXH32_endian_align.
FORCE_INLINE U32 XXH_readLE32(const U32 *ptr, XXH_endianess endian)
References XXH_readLE32_align, XXH_unaligned.
Referenced by XXH32_update_endian, XXH32_intermediateDigest_endian.
FORCE_INLINE U32 XXH32_endian_align(const void *input, int len, U32 seed, XXH_endianess endian, XXH_alignment align)
References PRIME32_1, PRIME32_2, XXH_readLE32_align, XXH_rotl32, PRIME32_5, PRIME32_3, PRIME32_4.
Referenced by XXH32.
U32 XXH32(const void *input, int len, U32 seed)
References state, XXH32_init, XXH32_update, XXH32_digest, XXH_CPU_LITTLE_ENDIAN, XXH_littleEndian, XXH_FORCE_NATIVE_FORMAT, XXH32_endian_align, XXH_aligned, XXH_bigEndian, XXH_unaligned.
int XXH32_sizeofState()
References XXH_STATIC_ASSERT, XXH32_SIZEOFSTATE.
XXH_errorcode XXH32_resetState(void *state_in, U32 seed)
References state, XXH_state32_t::seed, XXH_state32_t::v1, PRIME32_1, PRIME32_2, XXH_state32_t::v2, XXH_state32_t::v3, XXH_state32_t::v4, XXH_state32_t::total_len, XXH_state32_t::memsize, XXH_OK.
Referenced by XXH32_init.
void* XXH32_init(U32 seed)
References state, XXH_malloc, XXH32_resetState.
Referenced by SecMsgBucket::hashBucket, XXH32.
FORCE_INLINE XXH_errorcode XXH32_update_endian(void *state_in, const void *input, int len, XXH_endianess endian)
References state, XXH_ERROR, XXH_state32_t::total_len, XXH_state32_t::memsize, XXH_memcpy, XXH_state32_t::memory, XXH_OK, XXH_state32_t::v1, XXH_readLE32, PRIME32_2, XXH_rotl32, PRIME32_1, XXH_state32_t::v2, XXH_state32_t::v3, XXH_state32_t::v4.
Referenced by XXH32_update.
XXH_errorcode XXH32_update(void *state_in, const void *input, int len)
References XXH_CPU_LITTLE_ENDIAN, XXH_littleEndian, XXH_FORCE_NATIVE_FORMAT, XXH32_update_endian, XXH_bigEndian.
Referenced by SecMsgBucket::hashBucket, XXH32.
FORCE_INLINE U32 XXH32_intermediateDigest_endian(void *state_in, XXH_endianess endian)
References state, XXH_state32_t::memory, XXH_state32_t::memsize, XXH_state32_t::total_len, XXH_rotl32, XXH_state32_t::v1, XXH_state32_t::v2, XXH_state32_t::v3, XXH_state32_t::v4, XXH_state32_t::seed, PRIME32_5, XXH_readLE32, PRIME32_3, PRIME32_4, PRIME32_1, PRIME32_2.
Referenced by XXH32_intermediateDigest.
U32 XXH32_intermediateDigest(void *state_in)
References XXH_CPU_LITTLE_ENDIAN, XXH_littleEndian, XXH_FORCE_NATIVE_FORMAT, XXH32_intermediateDigest_endian, XXH_bigEndian.
Referenced by XXH32_digest.
U32 XXH32_digest(void *state_in)
References XXH32_intermediateDigest, XXH_free.
Referenced by SecMsgBucket::hashBucket, XXH32.