.TH "__blake2b_param" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__blake2b_param \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <blake2\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint8_t\fP \fBdigest_length\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBkey_length\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBfanout\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBdepth\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBleaf_length\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBnode_offset\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBnode_depth\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBinner_length\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBreserved\fP [14]"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBsalt\fP [\fBBLAKE2B_SALTBYTES\fP]"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBpersonal\fP [\fBBLAKE2B_PERSONALBYTES\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file blake2\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint8_t\fP __blake2b_param::depth"

.PP
Definition at line 25 of file blake2\&.h\&.
.SS "\fBuint8_t\fP __blake2b_param::digest_length"

.PP
Definition at line 22 of file blake2\&.h\&.
.SS "\fBuint8_t\fP __blake2b_param::fanout"

.PP
Definition at line 24 of file blake2\&.h\&.
.SS "\fBuint8_t\fP __blake2b_param::inner_length"

.PP
Definition at line 29 of file blake2\&.h\&.
.SS "\fBuint8_t\fP __blake2b_param::key_length"

.PP
Definition at line 23 of file blake2\&.h\&.
.SS "\fBuint32_t\fP __blake2b_param::leaf_length"

.PP
Definition at line 26 of file blake2\&.h\&.
.SS "\fBuint8_t\fP __blake2b_param::node_depth"

.PP
Definition at line 28 of file blake2\&.h\&.
.SS "\fBuint64_t\fP __blake2b_param::node_offset"

.PP
Definition at line 27 of file blake2\&.h\&.
.SS "\fBuint8_t\fP __blake2b_param::personal[\fBBLAKE2B_PERSONALBYTES\fP]"

.PP
Definition at line 32 of file blake2\&.h\&.
.SS "\fBuint8_t\fP __blake2b_param::reserved[14]"

.PP
Definition at line 30 of file blake2\&.h\&.
.SS "\fBuint8_t\fP __blake2b_param::salt[\fBBLAKE2B_SALTBYTES\fP]"

.PP
Definition at line 31 of file blake2\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
