.TH "__blake2b_state" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__blake2b_state \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <blake2\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint64_t\fP \fBh\fP [8]"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBt\fP [2]"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBf\fP [2]"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBbuf\fP [\fBBLAKE2B_BLOCKBYTES\fP]"
.br
.ti -1c
.RI "unsigned \fBbuflen\fP"
.br
.ti -1c
.RI "unsigned \fBoutlen\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBlast_node\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file blake2\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint8_t\fP __blake2b_state::buf[\fBBLAKE2B_BLOCKBYTES\fP]"

.PP
Definition at line 40 of file blake2\&.h\&.
.SS "unsigned __blake2b_state::buflen"

.PP
Definition at line 41 of file blake2\&.h\&.
.SS "\fBuint64_t\fP __blake2b_state::f[2]"

.PP
Definition at line 39 of file blake2\&.h\&.
.SS "\fBuint64_t\fP __blake2b_state::h[8]"

.PP
Definition at line 37 of file blake2\&.h\&.
.SS "\fBuint8_t\fP __blake2b_state::last_node"

.PP
Definition at line 43 of file blake2\&.h\&.
.SS "unsigned __blake2b_state::outlen"

.PP
Definition at line 42 of file blake2\&.h\&.
.SS "\fBuint64_t\fP __blake2b_state::t[2]"

.PP
Definition at line 38 of file blake2\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
