.TH "_U32_S" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_U32_S \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBU32\fP \fBv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 128 of file xxhash\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBU32\fP _U32_S::v"

.PP
Definition at line 128 of file xxhash\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
