.TH "AboutDialog" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AboutDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <aboutdialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAboutDialog\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~AboutDialog\fP ()"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBClientModel\fP *model)"
.br
.in -1c
.SH "Detailed Description"
.PP 
'About' dialog box 
.PP
Definition at line 12 of file aboutdialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AboutDialog::AboutDialog (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 7 of file aboutdialog\&.cpp\&.
.SS "AboutDialog::~AboutDialog ()"

.PP
Definition at line 22 of file aboutdialog\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void AboutDialog::setModel (\fBClientModel\fP * model)"

.PP
Definition at line 14 of file aboutdialog\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
