.TH "AcceptedConnection" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AcceptedConnection \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAcceptedConnectionImpl< Protocol >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~AcceptedConnection\fP ()"
.br
.ti -1c
.RI "virtual std::iostream & \fBstream\fP ()=0"
.br
.ti -1c
.RI "virtual std::string \fBpeer_address_to_string\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBclose\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 398 of file rpcserver\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual AcceptedConnection::~AcceptedConnection ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 401 of file rpcserver\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void AcceptedConnection::close ()\fC [pure virtual]\fP"

.PP
Implemented in \fBAcceptedConnectionImpl< Protocol >\fP\&.
.SS "virtual std::string AcceptedConnection::peer_address_to_string () const\fC [pure virtual]\fP"

.PP
Implemented in \fBAcceptedConnectionImpl< Protocol >\fP\&.
.SS "virtual std::iostream& AcceptedConnection::stream ()\fC [pure virtual]\fP"

.PP
Implemented in \fBAcceptedConnectionImpl< Protocol >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
