.TH "AcceptedConnectionImpl< Protocol >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AcceptedConnectionImpl< Protocol > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAcceptedConnection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAcceptedConnectionImpl\fP (asio::io_service &io_service, ssl::context &context, bool fUseSSL)"
.br
.ti -1c
.RI "virtual std::iostream & \fBstream\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBpeer_address_to_string\fP () const "
.br
.ti -1c
.RI "virtual void \fBclose\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Protocol::endpoint \fBpeer\fP"
.br
.ti -1c
.RI "asio::ssl::stream< typename Protocol::socket > \fBsslStream\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Protocol>class AcceptedConnectionImpl< Protocol >"

.PP
Definition at line 409 of file rpcserver\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Protocol> \fBAcceptedConnectionImpl\fP< Protocol >::\fBAcceptedConnectionImpl\fP (asio::io_service & io_service, ssl::context & context, bool fUseSSL)\fC [inline]\fP"

.PP
Definition at line 412 of file rpcserver\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Protocol> virtual void \fBAcceptedConnectionImpl\fP< Protocol >::close ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBAcceptedConnection\fP\&.
.PP
Definition at line 432 of file rpcserver\&.cpp\&.
.SS "template<typename Protocol> virtual std::string \fBAcceptedConnectionImpl\fP< Protocol >::peer_address_to_string () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBAcceptedConnection\fP\&.
.PP
Definition at line 427 of file rpcserver\&.cpp\&.
.SS "template<typename Protocol> virtual std::iostream& \fBAcceptedConnectionImpl\fP< Protocol >::stream ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBAcceptedConnection\fP\&.
.PP
Definition at line 422 of file rpcserver\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename Protocol> Protocol::endpoint \fBAcceptedConnectionImpl\fP< Protocol >::peer"

.PP
Definition at line 437 of file rpcserver\&.cpp\&.
.SS "template<typename Protocol> asio::ssl::stream<typename Protocol::socket> \fBAcceptedConnectionImpl\fP< Protocol >::sslStream"

.PP
Definition at line 438 of file rpcserver\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
