.TH "AddressBookPage" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddressBookPage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <addressbookpage\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBTabs\fP { \fBSendingTab\fP = 0, \fBReceivingTab\fP = 1 }"
.br
.ti -1c
.RI "enum \fBMode\fP { \fBForSending\fP, \fBForEditing\fP }"
.br
.in -1c
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBdone\fP (int retval)"
.br
.ti -1c
.RI "void \fBexportClicked\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBsignMessage\fP (QString addr)"
.br
.ti -1c
.RI "void \fBverifyMessage\fP (QString addr)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddressBookPage\fP (\fBMode\fP mode, \fBTabs\fP tab, QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~AddressBookPage\fP ()"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBAddressTableModel\fP *model)"
.br
.ti -1c
.RI "void \fBsetOptionsModel\fP (\fBOptionsModel\fP *optionsModel)"
.br
.ti -1c
.RI "const QString & \fBgetReturnValue\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Widget that shows a list of sending or receiving addresses\&. 
.PP
Definition at line 22 of file addressbookpage\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBAddressBookPage::Mode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIForSending \fP\fP
Open address book to pick address for sending 
.TP
\fB\fIForEditing \fP\fP
Open address book for editing 
.PP
Definition at line 32 of file addressbookpage\&.h\&.
.SS "enum \fBAddressBookPage::Tabs\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISendingTab \fP\fP
.TP
\fB\fIReceivingTab \fP\fP
.PP
Definition at line 27 of file addressbookpage\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AddressBookPage::AddressBookPage (\fBMode\fP mode, \fBTabs\fP tab, QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 20 of file addressbookpage\&.cpp\&.
.SS "AddressBookPage::~AddressBookPage ()"

.PP
Definition at line 104 of file addressbookpage\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void AddressBookPage::done (int retval)\fC [slot]\fP"

.PP
Definition at line 283 of file addressbookpage\&.cpp\&.
.SS "void AddressBookPage::exportClicked ()\fC [slot]\fP"

.PP
Definition at line 310 of file addressbookpage\&.cpp\&.
.SS "const QString& AddressBookPage::getReturnValue () const\fC [inline]\fP"

.PP
Definition at line 42 of file addressbookpage\&.h\&.
.SS "void AddressBookPage::setModel (\fBAddressTableModel\fP * model)"

.PP
Definition at line 109 of file addressbookpage\&.cpp\&.
.SS "void AddressBookPage::setOptionsModel (\fBOptionsModel\fP * optionsModel)"

.PP
Definition at line 152 of file addressbookpage\&.cpp\&.
.SS "void AddressBookPage::signMessage (QString addr)\fC [signal]\fP"

.SS "void AddressBookPage::verifyMessage (QString addr)\fC [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
