.TH "AddressTablePriv" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddressTablePriv \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddressTablePriv\fP (\fBCWallet\fP *\fBwallet\fP, \fBAddressTableModel\fP *\fBparent\fP)"
.br
.ti -1c
.RI "void \fBrefreshAddressTable\fP ()"
.br
.ti -1c
.RI "void \fBupdateEntry\fP (const QString &address, const QString &label, bool isMine, int status)"
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.ti -1c
.RI "\fBAddressTableEntry\fP * \fBindex\fP (int idx)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCWallet\fP * \fBwallet\fP"
.br
.ti -1c
.RI "QList< \fBAddressTableEntry\fP > \fBcachedAddressTable\fP"
.br
.ti -1c
.RI "\fBAddressTableModel\fP * \fBparent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file addresstablemodel\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AddressTablePriv::AddressTablePriv (\fBCWallet\fP * wallet, \fBAddressTableModel\fP * parent)\fC [inline]\fP"

.PP
Definition at line 56 of file addresstablemodel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAddressTableEntry\fP* AddressTablePriv::index (int idx)\fC [inline]\fP"

.PP
Definition at line 140 of file addresstablemodel\&.cpp\&.
.SS "void AddressTablePriv::refreshAddressTable ()\fC [inline]\fP"

.PP
Definition at line 59 of file addresstablemodel\&.cpp\&.
.SS "int AddressTablePriv::size ()\fC [inline]\fP"

.PP
Definition at line 135 of file addresstablemodel\&.cpp\&.
.SS "void AddressTablePriv::updateEntry (const QString & address, const QString & label, bool isMine, int status)\fC [inline]\fP"

.PP
Definition at line 88 of file addresstablemodel\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QList<\fBAddressTableEntry\fP> AddressTablePriv::cachedAddressTable"

.PP
Definition at line 53 of file addresstablemodel\&.cpp\&.
.SS "\fBAddressTableModel\fP* AddressTablePriv::parent"

.PP
Definition at line 54 of file addresstablemodel\&.cpp\&.
.SS "\fBCWallet\fP* AddressTablePriv::wallet"

.PP
Definition at line 52 of file addresstablemodel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
