.TH "AddressTableEntry" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddressTableEntry \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBSending\fP, \fBReceiving\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddressTableEntry\fP ()"
.br
.ti -1c
.RI "\fBAddressTableEntry\fP (\fBType\fP \fBtype\fP, const QString &\fBlabel\fP, const QString &\fBaddress\fP, const bool &\fBstealth\fP=false)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBType\fP \fBtype\fP"
.br
.ti -1c
.RI "QString \fBlabel\fP"
.br
.ti -1c
.RI "QString \fBaddress\fP"
.br
.ti -1c
.RI "bool \fBstealth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file addresstablemodel\&.cpp\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBAddressTableEntry::Type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISending \fP\fP
.TP
\fB\fIReceiving \fP\fP
.PP
Definition at line 17 of file addresstablemodel\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AddressTableEntry::AddressTableEntry ()\fC [inline]\fP"

.PP
Definition at line 27 of file addresstablemodel\&.cpp\&.
.SS "AddressTableEntry::AddressTableEntry (\fBType\fP type, const QString & label, const QString & address, const bool & stealth = \fCfalse\fP)\fC [inline]\fP"

.PP
Definition at line 28 of file addresstablemodel\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QString AddressTableEntry::address"

.PP
Definition at line 24 of file addresstablemodel\&.cpp\&.
.SS "QString AddressTableEntry::label"

.PP
Definition at line 23 of file addresstablemodel\&.cpp\&.
.SS "bool AddressTableEntry::stealth"

.PP
Definition at line 25 of file addresstablemodel\&.cpp\&.
.SS "\fBType\fP AddressTableEntry::type"

.PP
Definition at line 22 of file addresstablemodel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
