.TH "AddressTableEntryLessThan" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddressTableEntryLessThan \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBAddressTableEntry\fP &a, const \fBAddressTableEntry\fP &b) const "
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBAddressTableEntry\fP &a, const QString &b) const "
.br
.ti -1c
.RI "bool \fBoperator()\fP (const QString &a, const \fBAddressTableEntry\fP &b) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file addresstablemodel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool AddressTableEntryLessThan::operator() (const \fBAddressTableEntry\fP & a, const \fBAddressTableEntry\fP & b) const\fC [inline]\fP"

.PP
Definition at line 34 of file addresstablemodel\&.cpp\&.
.SS "bool AddressTableEntryLessThan::operator() (const \fBAddressTableEntry\fP & a, const QString & b) const\fC [inline]\fP"

.PP
Definition at line 38 of file addresstablemodel\&.cpp\&.
.SS "bool AddressTableEntryLessThan::operator() (const QString & a, const \fBAddressTableEntry\fP & b) const\fC [inline]\fP"

.PP
Definition at line 42 of file addresstablemodel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
