.TH "/home/dev/ds-160209/src/addrman.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/addrman.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'netbase\&.h'\fP
.br
\fC#include 'protocol\&.h'\fP
.br
\fC#include 'sync\&.h'\fP
.br
\fC#include 'timedata\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCAddrInfo\fP"
.br
.ti -1c
.RI "class \fBCAddrMan\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBADDRMAN_TRIED_BUCKET_COUNT\fP   256"
.br
.ti -1c
.RI "#define \fBADDRMAN_TRIED_BUCKET_SIZE\fP   64"
.br
.ti -1c
.RI "#define \fBADDRMAN_NEW_BUCKET_COUNT\fP   1024"
.br
.ti -1c
.RI "#define \fBADDRMAN_NEW_BUCKET_SIZE\fP   64"
.br
.ti -1c
.RI "#define \fBADDRMAN_TRIED_BUCKETS_PER_GROUP\fP   8"
.br
.ti -1c
.RI "#define \fBADDRMAN_NEW_BUCKETS_PER_SOURCE_GROUP\fP   64"
.br
.ti -1c
.RI "#define \fBADDRMAN_NEW_BUCKETS_PER_ADDRESS\fP   8"
.br
.ti -1c
.RI "#define \fBADDRMAN_TRIED_ENTRIES_INSPECT_ON_EVICT\fP   4"
.br
.ti -1c
.RI "#define \fBADDRMAN_HORIZON_DAYS\fP   30"
.br
.ti -1c
.RI "#define \fBADDRMAN_RETRIES\fP   3"
.br
.ti -1c
.RI "#define \fBADDRMAN_MAX_FAILURES\fP   10"
.br
.ti -1c
.RI "#define \fBADDRMAN_MIN_FAIL_DAYS\fP   7"
.br
.ti -1c
.RI "#define \fBADDRMAN_GETADDR_MAX_PCT\fP   23"
.br
.ti -1c
.RI "#define \fBADDRMAN_GETADDR_MAX\fP   2500"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ADDRMAN_GETADDR_MAX   2500"

.PP
Definition at line 162 of file addrman\&.h\&.
.SS "#define ADDRMAN_GETADDR_MAX_PCT   23"

.PP
Definition at line 159 of file addrman\&.h\&.
.SS "#define ADDRMAN_HORIZON_DAYS   30"

.PP
Definition at line 147 of file addrman\&.h\&.
.SS "#define ADDRMAN_MAX_FAILURES   10"

.PP
Definition at line 153 of file addrman\&.h\&.
.SS "#define ADDRMAN_MIN_FAIL_DAYS   7"

.PP
Definition at line 156 of file addrman\&.h\&.
.SS "#define ADDRMAN_NEW_BUCKET_COUNT   1024"

.PP
Definition at line 129 of file addrman\&.h\&.
.SS "#define ADDRMAN_NEW_BUCKET_SIZE   64"

.PP
Definition at line 132 of file addrman\&.h\&.
.SS "#define ADDRMAN_NEW_BUCKETS_PER_ADDRESS   8"

.PP
Definition at line 141 of file addrman\&.h\&.
.SS "#define ADDRMAN_NEW_BUCKETS_PER_SOURCE_GROUP   64"

.PP
Definition at line 138 of file addrman\&.h\&.
.SS "#define ADDRMAN_RETRIES   3"

.PP
Definition at line 150 of file addrman\&.h\&.
.SS "#define ADDRMAN_TRIED_BUCKET_COUNT   256"

.PP
Definition at line 123 of file addrman\&.h\&.
.SS "#define ADDRMAN_TRIED_BUCKET_SIZE   64"

.PP
Definition at line 126 of file addrman\&.h\&.
.SS "#define ADDRMAN_TRIED_BUCKETS_PER_GROUP   8"

.PP
Definition at line 135 of file addrman\&.h\&.
.SS "#define ADDRMAN_TRIED_ENTRIES_INSPECT_ON_EVICT   4"

.PP
Definition at line 144 of file addrman\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
