.TH "AddressTableModel" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddressTableModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <addresstablemodel\&.h>\fP
.PP
Inherits QAbstractTableModel\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBAddressType\fP { \fBAT_Unknown\fP = 0, \fBAT_Normal\fP = 1, \fBAT_Stealth\fP = 2 }"
.br
.ti -1c
.RI "enum \fBColumnIndex\fP { \fBLabel\fP = 0, \fBAddress\fP = 1, \fBType\fP = 2 }"
.br
.ti -1c
.RI "enum \fBRoleIndex\fP { \fBTypeRole\fP = Qt::UserRole }"
.br
.ti -1c
.RI "enum \fBEditStatus\fP { \fBOK\fP, \fBNO_CHANGES\fP, \fBINVALID_ADDRESS\fP, \fBDUPLICATE_ADDRESS\fP, \fBWALLET_UNLOCK_FAILURE\fP, \fBKEY_GENERATION_FAILURE\fP }"
.br
.in -1c
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBupdateEntry\fP (const QString &address, const QString &label, bool isMine, int status)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddressTableModel\fP (\fBCWallet\fP *wallet, \fBWalletModel\fP *parent=0)"
.br
.ti -1c
.RI "\fB~AddressTableModel\fP ()"
.br
.ti -1c
.RI "QString \fBaddRow\fP (const QString &type, const QString &label, const QString &address, int addressType)"
.br
.ti -1c
.RI "QString \fBlabelForAddress\fP (const QString &address) const "
.br
.ti -1c
.RI "int \fBlookupAddress\fP (const QString &address) const "
.br
.ti -1c
.RI "\fBEditStatus\fP \fBgetEditStatus\fP () const "
.br
.in -1c
.PP
.RI "\fBMethods overridden from QAbstractTableModel\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "int \fBrowCount\fP (const QModelIndex &parent) const "
.br
.ti -1c
.RI "int \fBcolumnCount\fP (const QModelIndex &parent) const "
.br
.ti -1c
.RI "QVariant \fBdata\fP (const QModelIndex &\fBindex\fP, int role) const "
.br
.ti -1c
.RI "bool \fBsetData\fP (const QModelIndex &\fBindex\fP, const QVariant &\fBvalue\fP, int role)"
.br
.ti -1c
.RI "QVariant \fBheaderData\fP (int section, Qt::Orientation orientation, int role) const "
.br
.ti -1c
.RI "QModelIndex \fBindex\fP (int row, int column, const QModelIndex &parent) const "
.br
.ti -1c
.RI "bool \fBremoveRows\fP (int row, int count, const QModelIndex &parent=QModelIndex())"
.br
.ti -1c
.RI "Qt::ItemFlags \fBflags\fP (const QModelIndex &\fBindex\fP) const "
.br
.in -1c
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const QString \fBSend\fP = 'S'"
.br
.ti -1c
.RI "static const QString \fBReceive\fP = 'R'"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBAddressTablePriv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Qt model of the address book in the core\&. This allows views to access and modify the address book\&. 
.PP
Definition at line 14 of file addresstablemodel\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBAddressTableModel::AddressType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIAT_Unknown \fP\fP
User specified label 
.TP
\fB\fIAT_Normal \fP\fP
DarkSilk address 
.TP
\fB\fIAT_Stealth \fP\fP
Stealth address 
.PP
Definition at line 22 of file addresstablemodel\&.h\&.
.SS "enum \fBAddressTableModel::ColumnIndex\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILabel \fP\fP
User specified label 
.TP
\fB\fIAddress \fP\fP
DarkSilk address 
.TP
\fB\fIType \fP\fP
Address type 
.PP
Definition at line 28 of file addresstablemodel\&.h\&.
.SS "enum \fBAddressTableModel::EditStatus\fP"
Return status of edit/insert operation 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOK \fP\fP
Everything ok 
.TP
\fB\fINO_CHANGES \fP\fP
No changes were made during edit operation 
.TP
\fB\fIINVALID_ADDRESS \fP\fP
Unparseable address 
.TP
\fB\fIDUPLICATE_ADDRESS \fP\fP
Address already in address book 
.TP
\fB\fIWALLET_UNLOCK_FAILURE \fP\fP
Wallet could not be unlocked to create new receiving address 
.TP
\fB\fIKEY_GENERATION_FAILURE \fP\fP
Generating a new public key for a receiving address failed 
.PP
Definition at line 39 of file addresstablemodel\&.h\&.
.SS "enum \fBAddressTableModel::RoleIndex\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITypeRole \fP\fP
Type of address (\fBSend\fP or \fBReceive\fP) 
.PP
Definition at line 34 of file addresstablemodel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AddressTableModel::AddressTableModel (\fBCWallet\fP * wallet, \fBWalletModel\fP * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 153 of file addresstablemodel\&.cpp\&.
.SS "AddressTableModel::~AddressTableModel ()"

.PP
Definition at line 161 of file addresstablemodel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QString AddressTableModel::addRow (const QString & type, const QString & label, const QString & address, int addressType)"

.PP
Definition at line 349 of file addresstablemodel\&.cpp\&.
.SS "int AddressTableModel::columnCount (const QModelIndex & parent) const"

.PP
Definition at line 172 of file addresstablemodel\&.cpp\&.
.SS "QVariant AddressTableModel::data (const QModelIndex & index, int role) const"

.PP
Definition at line 178 of file addresstablemodel\&.cpp\&.
.SS "Qt::ItemFlags AddressTableModel::flags (const QModelIndex & index) const"

.PP
Definition at line 312 of file addresstablemodel\&.cpp\&.
.SS "\fBEditStatus\fP AddressTableModel::getEditStatus () const\fC [inline]\fP"

.PP
Definition at line 77 of file addresstablemodel\&.h\&.
.SS "QVariant AddressTableModel::headerData (int section, Qt::Orientation orientation, int role) const"

.PP
Definition at line 300 of file addresstablemodel\&.cpp\&.
.SS "QModelIndex AddressTableModel::index (int row, int column, const QModelIndex & parent) const"

.PP
Definition at line 329 of file addresstablemodel\&.cpp\&.
.SS "QString AddressTableModel::labelForAddress (const QString & address) const"

.PP
Definition at line 468 of file addresstablemodel\&.cpp\&.
.SS "int AddressTableModel::lookupAddress (const QString & address) const"

.PP
Definition at line 499 of file addresstablemodel\&.cpp\&.
.SS "bool AddressTableModel::removeRows (int row, int count, const QModelIndex & parent = \fCQModelIndex()\fP)"

.PP
Definition at line 449 of file addresstablemodel\&.cpp\&.
.SS "int AddressTableModel::rowCount (const QModelIndex & parent) const"

.PP
Definition at line 166 of file addresstablemodel\&.cpp\&.
.SS "bool AddressTableModel::setData (const QModelIndex & index, const QVariant & value, int role)"

.PP
Definition at line 225 of file addresstablemodel\&.cpp\&.
.SS "void AddressTableModel::updateEntry (const QString & address, const QString & label, bool isMine, int status)\fC [slot]\fP"

.PP
Definition at line 343 of file addresstablemodel\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBAddressTablePriv\fP\fC [friend]\fP"

.PP
Definition at line 94 of file addresstablemodel\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "const QString AddressTableModel::Receive = 'R'\fC [static]\fP"
Specifies receive address 
.PP
Definition at line 49 of file addresstablemodel\&.h\&.
.SS "const QString AddressTableModel::Send = 'S'\fC [static]\fP"
Specifies send address 
.PP
Definition at line 48 of file addresstablemodel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
