.TH "/home/dev/ds-160209/src/allocators.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/allocators.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'allocators\&.h'\fP
.br
\fC#include <sys/mman\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
