.TH "/home/dev/ds-160209/src/amount.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/amount.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'serialize\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCFeeRate\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBint64_t\fP \fBCAmount\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBMoneyRange\fP (const \fBCAmount\fP &nValue)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBint64_t\fP \fBCAmount\fP"

.PP
Definition at line 14 of file amount\&.h\&.
.SH "Function Documentation"
.PP 
.SS "bool MoneyRange (const \fBCAmount\fP & nValue)\fC [inline]\fP"

.PP
Definition at line 21 of file amount\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
