.TH "AnnotatedMixin< PARENT >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnnotatedMixin< PARENT > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sync\&.h>\fP
.PP
Inherits PARENT\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBlock\fP () \fBEXCLUSIVE_LOCK_FUNCTION\fP()"
.br
.ti -1c
.RI "void \fBunlock\fP () \fBUNLOCK_FUNCTION\fP()"
.br
.ti -1c
.RI "bool \fBtry_lock\fP () \fBEXCLUSIVE_TRYLOCK_FUNCTION\fP(true)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename PARENT>class AnnotatedMixin< PARENT >"

.PP
Definition at line 61 of file sync\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename PARENT> void \fBAnnotatedMixin\fP< PARENT >::lock ()\fC [inline]\fP"

.PP
Definition at line 64 of file sync\&.h\&.
.SS "template<typename PARENT> bool \fBAnnotatedMixin\fP< PARENT >::try_lock ()\fC [inline]\fP"

.PP
Definition at line 74 of file sync\&.h\&.
.SS "template<typename PARENT> void \fBAnnotatedMixin\fP< PARENT >::unlock ()\fC [inline]\fP"

.PP
Definition at line 69 of file sync\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
