.TH "Argon2_thread_data" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Argon2_thread_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBargon2_instance_t\fP * \fBinstance_ptr\fP"
.br
.ti -1c
.RI "\fBargon2_position_t\fP \fBpos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 102 of file core\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBargon2_instance_t\fP* Argon2_thread_data::instance_ptr"

.PP
Definition at line 103 of file core\&.h\&.
.SS "\fBargon2_position_t\fP Argon2_thread_data::pos"

.PP
Definition at line 104 of file core\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
