.TH "Argon2_position_t" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Argon2_position_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP \fBpass\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBlane\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBslice\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBindex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 94 of file core\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint32_t\fP Argon2_position_t::index"

.PP
Definition at line 98 of file core\&.h\&.
.SS "\fBuint32_t\fP Argon2_position_t::lane"

.PP
Definition at line 96 of file core\&.h\&.
.SS "\fBuint32_t\fP Argon2_position_t::pass"

.PP
Definition at line 95 of file core\&.h\&.
.SS "\fBuint8_t\fP Argon2_position_t::slice"

.PP
Definition at line 97 of file core\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
