.TH "Argon2_Context" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Argon2_Context \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <argon2\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint8_t\fP * \fBout\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBoutlen\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBpwd\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBpwdlen\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBsalt\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBsaltlen\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBsecret\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBsecretlen\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBad\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBadlen\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBt_cost\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBm_cost\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBlanes\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBthreads\fP"
.br
.ti -1c
.RI "\fBallocate_fptr\fP \fBallocate_cbk\fP"
.br
.ti -1c
.RI "\fBdeallocate_fptr\fP \fBfree_cbk\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 169 of file argon2\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint8_t\fP* Argon2_Context::ad"

.PP
Definition at line 182 of file argon2\&.h\&.
.SS "\fBuint32_t\fP Argon2_Context::adlen"

.PP
Definition at line 183 of file argon2\&.h\&.
.SS "\fBallocate_fptr\fP Argon2_Context::allocate_cbk"

.PP
Definition at line 190 of file argon2\&.h\&.
.SS "\fBuint32_t\fP Argon2_Context::flags"

.PP
Definition at line 193 of file argon2\&.h\&.
.SS "\fBdeallocate_fptr\fP Argon2_Context::free_cbk"

.PP
Definition at line 191 of file argon2\&.h\&.
.SS "\fBuint32_t\fP Argon2_Context::lanes"

.PP
Definition at line 187 of file argon2\&.h\&.
.SS "\fBuint32_t\fP Argon2_Context::m_cost"

.PP
Definition at line 186 of file argon2\&.h\&.
.SS "\fBuint8_t\fP* Argon2_Context::out"

.PP
Definition at line 170 of file argon2\&.h\&.
.SS "\fBuint32_t\fP Argon2_Context::outlen"

.PP
Definition at line 171 of file argon2\&.h\&.
.SS "\fBuint8_t\fP* Argon2_Context::pwd"

.PP
Definition at line 173 of file argon2\&.h\&.
.SS "\fBuint32_t\fP Argon2_Context::pwdlen"

.PP
Definition at line 174 of file argon2\&.h\&.
.SS "\fBuint8_t\fP* Argon2_Context::salt"

.PP
Definition at line 176 of file argon2\&.h\&.
.SS "\fBuint32_t\fP Argon2_Context::saltlen"

.PP
Definition at line 177 of file argon2\&.h\&.
.SS "\fBuint8_t\fP* Argon2_Context::secret"

.PP
Definition at line 179 of file argon2\&.h\&.
.SS "\fBuint32_t\fP Argon2_Context::secretlen"

.PP
Definition at line 180 of file argon2\&.h\&.
.SS "\fBuint32_t\fP Argon2_Context::t_cost"

.PP
Definition at line 185 of file argon2\&.h\&.
.SS "\fBuint32_t\fP Argon2_Context::threads"

.PP
Definition at line 188 of file argon2\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
