.TH "Argon2_instance_t" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Argon2_instance_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBblock\fP * \fBmemory\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBpasses\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBmemory_blocks\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBsegment_length\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBlane_length\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBlanes\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBthreads\fP"
.br
.ti -1c
.RI "\fBargon2_type\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBprint_internals\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 78 of file core\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint32_t\fP Argon2_instance_t::lane_length"

.PP
Definition at line 83 of file core\&.h\&.
.SS "\fBuint32_t\fP Argon2_instance_t::lanes"

.PP
Definition at line 84 of file core\&.h\&.
.SS "\fBblock\fP* Argon2_instance_t::memory"

.PP
Definition at line 79 of file core\&.h\&.
.SS "\fBuint32_t\fP Argon2_instance_t::memory_blocks"

.PP
Definition at line 81 of file core\&.h\&.
.SS "\fBuint32_t\fP Argon2_instance_t::passes"

.PP
Definition at line 80 of file core\&.h\&.
.SS "int Argon2_instance_t::print_internals"

.PP
Definition at line 87 of file core\&.h\&.
.SS "\fBuint32_t\fP Argon2_instance_t::segment_length"

.PP
Definition at line 82 of file core\&.h\&.
.SS "\fBuint32_t\fP Argon2_instance_t::threads"

.PP
Definition at line 85 of file core\&.h\&.
.SS "\fBargon2_type\fP Argon2_instance_t::type"

.PP
Definition at line 86 of file core\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
