.TH "/home/dev/ds-160209/src/qt/askpassphrasedialog.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/askpassphrasedialog.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'askpassphrasedialog\&.h'\fP
.br
\fC#include 'ui_askpassphrasedialog\&.h'\fP
.br
\fC#include 'guiconstants\&.h'\fP
.br
\fC#include 'walletmodel\&.h'\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QKeyEvent>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBfWalletUnlockStakingOnly\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "bool fWalletUnlockStakingOnly"

.PP
Definition at line 166 of file wallet\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
