.TH "BaseSignatureChecker" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseSignatureChecker \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <script\&.h>\fP
.PP
Inherited by \fBSignatureChecker\fP, and \fBTransactionSignatureChecker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBCheckSig\fP (const std::vector< unsigned char > &scriptSig, const std::vector< unsigned char > &vchPubKey, const \fBCScript\fP &scriptCode) const "
.br
.ti -1c
.RI "virtual \fB~BaseSignatureChecker\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 940 of file script\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual BaseSignatureChecker::~BaseSignatureChecker ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 948 of file script\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual bool BaseSignatureChecker::CheckSig (const std::vector< unsigned char > & scriptSig, const std::vector< unsigned char > & vchPubKey, const \fBCScript\fP & scriptCode) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBSignatureChecker\fP, and \fBTransactionSignatureChecker\fP\&.
.PP
Definition at line 943 of file script\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
