.TH "/home/dev/ds-160209/src/test/base58_tests.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/test/base58_tests.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/test/unit_test\&.hpp>\fP
.br
\fC#include 'json/json_spirit_reader_template\&.h'\fP
.br
\fC#include 'json/json_spirit_writer_template\&.h'\fP
.br
\fC#include 'json/json_spirit_utils\&.h'\fP
.br
\fC#include 'base58\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestAddrTypeVisitor\fP"
.br
.ti -1c
.RI "class \fBTestPayloadVisitor\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBArray\fP \fBread_json\fP (const std::string &filename)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (base58_EncodeBase58)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (base58_DecodeBase58)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (base58_keys_valid_parse)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (base58_keys_valid_gen)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (base58_keys_invalid)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (base58_EncodeBase58)"

.PP
Definition at line 15 of file base58_tests\&.cpp\&.
.SS "BOOST_AUTO_TEST_CASE (base58_DecodeBase58)"

.PP
Definition at line 37 of file base58_tests\&.cpp\&.
.SS "BOOST_AUTO_TEST_CASE (base58_keys_valid_parse)"

.PP
Definition at line 105 of file base58_tests\&.cpp\&.
.SS "BOOST_AUTO_TEST_CASE (base58_keys_valid_gen)"

.PP
Definition at line 164 of file base58_tests\&.cpp\&.
.SS "BOOST_AUTO_TEST_CASE (base58_keys_invalid)"

.PP
Definition at line 232 of file base58_tests\&.cpp\&.
.SS "\fBArray\fP read_json (const std::string & filename)"

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
