.TH "/home/dev/ds-160209/src/base58.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/base58.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'chainparams\&.h'\fP
.br
\fC#include 'pubkey\&.h'\fP
.br
\fC#include 'key\&.h'\fP
.br
\fC#include 'script\&.h'\fP
.br
\fC#include 'allocators\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCBase58Data\fP"
.br
.ti -1c
.RI "class \fBCDarkSilkAddress\fP"
.br
.ti -1c
.RI "class \fBCDarkSilkSecret\fP"
.br
.ti -1c
.RI "class \fBCDarkSilkExtKeyBase< K, Size, Type >\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBCDarkSilkExtKeyBase\fP< \fBCExtKey\fP, 74, \fBCChainParams::EXT_SECRET_KEY\fP > \fBCDarkSilkExtKey\fP"
.br
.ti -1c
.RI "typedef \fBCDarkSilkExtKeyBase\fP< \fBCExtPubKey\fP, 74, \fBCChainParams::EXT_PUBLIC_KEY\fP > \fBCDarkSilkExtPubKey\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBEncodeBase58\fP (const unsigned char *pbegin, const unsigned char *pend)"
.br
.ti -1c
.RI "std::string \fBEncodeBase58\fP (const std::vector< unsigned char > &vch)"
.br
.ti -1c
.RI "bool \fBDecodeBase58\fP (const char *psz, std::vector< unsigned char > &vch)"
.br
.ti -1c
.RI "bool \fBDecodeBase58\fP (const std::string &str, std::vector< unsigned char > &vchRet)"
.br
.ti -1c
.RI "std::string \fBEncodeBase58Check\fP (const std::vector< unsigned char > &vchIn)"
.br
.ti -1c
.RI "bool \fBDecodeBase58Check\fP (const char *psz, std::vector< unsigned char > &vchRet)"
.br
.ti -1c
.RI "bool \fBDecodeBase58Check\fP (const std::string &str, std::vector< unsigned char > &vchRet)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBCDarkSilkExtKeyBase\fP<\fBCExtKey\fP, 74, \fBCChainParams::EXT_SECRET_KEY\fP> \fBCDarkSilkExtKey\fP"

.PP
Definition at line 159 of file base58\&.h\&.
.SS "typedef \fBCDarkSilkExtKeyBase\fP<\fBCExtPubKey\fP, 74, \fBCChainParams::EXT_PUBLIC_KEY\fP> \fBCDarkSilkExtPubKey\fP"

.PP
Definition at line 160 of file base58\&.h\&.
.SH "Function Documentation"
.PP 
.SS "bool DecodeBase58 (const char * psz, std::vector< unsigned char > & vch)"
Decode a base58-encoded string (psz) into a byte vector (vchRet)\&. return true if decoding is successful\&. psz cannot be NULL\&. 
.PP
Definition at line 22 of file base58\&.cpp\&.
.SS "bool DecodeBase58 (const std::string & str, std::vector< unsigned char > & vchRet)"
Decode a base58-encoded string (str) into a byte vector (vchRet)\&. return true if decoding is successful\&. 
.PP
Definition at line 105 of file base58\&.cpp\&.
.SS "bool DecodeBase58Check (const char * psz, std::vector< unsigned char > & vchRet)\fC [inline]\fP"
Decode a base58-encoded string (psz) that includes a checksum into a byte vector (vchRet), return true if decoding is successful 
.PP
Definition at line 117 of file base58\&.cpp\&.
.SS "bool DecodeBase58Check (const std::string & str, std::vector< unsigned char > & vchRet)\fC [inline]\fP"
Decode a base58-encoded string (str) that includes a checksum into a byte vector (vchRet), return true if decoding is successful 
.PP
Definition at line 135 of file base58\&.cpp\&.
.SS "std::string EncodeBase58 (const unsigned char * pbegin, const unsigned char * pend)"
Encode a byte sequence as a base58-encoded string\&. pbegin and pend cannot be NULL, unless both are\&. 
.PP
Definition at line 67 of file base58\&.cpp\&.
.SS "std::string EncodeBase58 (const std::vector< unsigned char > & vch)"
Encode a byte vector as a base58-encoded string 
.PP
Definition at line 101 of file base58\&.cpp\&.
.SS "std::string EncodeBase58Check (const std::vector< unsigned char > & vchIn)"
Encode a byte vector into a base58-encoded string, including checksum 
.PP
Definition at line 109 of file base58\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
