.TH "bench_sign_t" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bench_sign_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsecp256k1_context\fP * \fBctx\fP"
.br
.ti -1c
.RI "unsigned char \fBmsg\fP [32]"
.br
.ti -1c
.RI "unsigned char \fBkey\fP [32]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file bench_sign\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBsecp256k1_context\fP* bench_sign_t::ctx"

.PP
Definition at line 12 of file bench_sign\&.c\&.
.SS "unsigned char bench_sign_t::key[32]"

.PP
Definition at line 14 of file bench_sign\&.c\&.
.SS "unsigned char bench_sign_t::msg[32]"

.PP
Definition at line 13 of file bench_sign\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
