.TH "bench_inv_t" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bench_inv_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsecp256k1_scalar\fP \fBscalar_x\fP"
.br
.ti -1c
.RI "\fBsecp256k1_scalar\fP \fBscalar_y\fP"
.br
.ti -1c
.RI "\fBsecp256k1_fe\fP \fBfe_x\fP"
.br
.ti -1c
.RI "\fBsecp256k1_fe\fP \fBfe_y\fP"
.br
.ti -1c
.RI "\fBsecp256k1_ge\fP \fBge_x\fP"
.br
.ti -1c
.RI "\fBsecp256k1_ge\fP \fBge_y\fP"
.br
.ti -1c
.RI "\fBsecp256k1_gej\fP \fBgej_x\fP"
.br
.ti -1c
.RI "\fBsecp256k1_gej\fP \fBgej_y\fP"
.br
.ti -1c
.RI "unsigned char \fBdata\fP [64]"
.br
.ti -1c
.RI "int \fBwnaf\fP [256]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file bench_internal\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned char bench_inv_t::data[64]"

.PP
Definition at line 26 of file bench_internal\&.c\&.
.SS "\fBsecp256k1_fe\fP bench_inv_t::fe_x"

.PP
Definition at line 23 of file bench_internal\&.c\&.
.SS "\fBsecp256k1_fe\fP bench_inv_t::fe_y"

.PP
Definition at line 23 of file bench_internal\&.c\&.
.SS "\fBsecp256k1_ge\fP bench_inv_t::ge_x"

.PP
Definition at line 24 of file bench_internal\&.c\&.
.SS "\fBsecp256k1_ge\fP bench_inv_t::ge_y"

.PP
Definition at line 24 of file bench_internal\&.c\&.
.SS "\fBsecp256k1_gej\fP bench_inv_t::gej_x"

.PP
Definition at line 25 of file bench_internal\&.c\&.
.SS "\fBsecp256k1_gej\fP bench_inv_t::gej_y"

.PP
Definition at line 25 of file bench_internal\&.c\&.
.SS "\fBsecp256k1_scalar\fP bench_inv_t::scalar_x"

.PP
Definition at line 22 of file bench_internal\&.c\&.
.SS "\fBsecp256k1_scalar\fP bench_inv_t::scalar_y"

.PP
Definition at line 22 of file bench_internal\&.c\&.
.SS "int bench_inv_t::wnaf[256]"

.PP
Definition at line 27 of file bench_internal\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
