.TH "/home/dev/ds-160209/src/secp256k1/src/bench_recover.c" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/secp256k1/src/bench_recover.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'include/secp256k1\&.h'\fP
.br
\fC#include 'include/secp256k1_recovery\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'bench\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBbench_recover_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbench_recover\fP (void *\fBarg\fP)"
.br
.ti -1c
.RI "void \fBbench_recover_setup\fP (void *\fBarg\fP)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void bench_recover (void * arg)"

.PP
Definition at line 18 of file bench_recover\&.c\&.
.SS "void bench_recover_setup (void * arg)"

.PP
Definition at line 39 of file bench_recover\&.c\&.
.SS "int main (void)"

.PP
Definition at line 51 of file bench_recover\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
