.TH "/home/dev/ds-160209/src/crypto/argon2/bench.c" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/crypto/argon2/bench.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include 'argon2\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBENCH_OUTLEN\fP   16"
.br
.ti -1c
.RI "#define \fBBENCH_INLEN\fP   16"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BENCH_INLEN   16"

.SS "#define BENCH_OUTLEN   16"

.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 108 of file bench\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
