.TH "/home/dev/ds-160209/src/secp256k1/src/bench_schnorr_verify.c" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/secp256k1/src/bench_schnorr_verify.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'include/secp256k1\&.h'\fP
.br
\fC#include 'include/secp256k1_schnorr\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'bench\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBbenchmark_schnorr_sig_t\fP"
.br
.ti -1c
.RI "struct \fBbenchmark_schnorr_verify_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 63 of file bench_schnorr_verify\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
