.TH "/home/dev/ds-160209/src/secp256k1/src/bench.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/secp256k1/src/bench.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'sys/time\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_number\fP (double x)"
.br
.ti -1c
.RI "void \fBrun_benchmark\fP (char *\fBname\fP, void(*benchmark)(void *), void(*setup)(void *), void(*teardown)(void *), void *data, int count, int iter)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void print_number (double x)"

.PP
Definition at line 20 of file bench\&.h\&.
.SS "void run_benchmark (char * name, void(*)(void *) benchmark, void(*)(void *) setup, void(*)(void *) teardown, void * data, int count, int iter)"

.PP
Definition at line 33 of file bench\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
