.TH "/home/dev/ds-160209/src/bignum.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/bignum.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'serialize\&.h'\fP
.br
\fC#include 'uint256\&.h'\fP
.br
\fC#include <openssl/bn\&.h>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbignum_error\fP"
.br
.ti -1c
.RI "class \fBCAutoBN_CTX\fP"
.br
.ti -1c
.RI "class \fBCBigNum\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBCBigNum\fP \fBBignum\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBCBigNum\fP \fBoperator+\fP (const \fBCBigNum\fP &a, const \fBCBigNum\fP &b)"
.br
.ti -1c
.RI "const \fBCBigNum\fP \fBoperator-\fP (const \fBCBigNum\fP &a, const \fBCBigNum\fP &b)"
.br
.ti -1c
.RI "const \fBCBigNum\fP \fBoperator-\fP (const \fBCBigNum\fP &a)"
.br
.ti -1c
.RI "const \fBCBigNum\fP \fBoperator*\fP (const \fBCBigNum\fP &a, const \fBCBigNum\fP &b)"
.br
.ti -1c
.RI "const \fBCBigNum\fP \fBoperator/\fP (const \fBCBigNum\fP &a, const \fBCBigNum\fP &b)"
.br
.ti -1c
.RI "const \fBCBigNum\fP \fBoperator%\fP (const \fBCBigNum\fP &a, const \fBCBigNum\fP &b)"
.br
.ti -1c
.RI "const \fBCBigNum\fP \fBoperator<<\fP (const \fBCBigNum\fP &a, unsigned int shift)"
.br
.ti -1c
.RI "const \fBCBigNum\fP \fBoperator>>\fP (const \fBCBigNum\fP &a, unsigned int shift)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCBigNum\fP &a, const \fBCBigNum\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBCBigNum\fP &a, const \fBCBigNum\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBCBigNum\fP &a, const \fBCBigNum\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBCBigNum\fP &a, const \fBCBigNum\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBCBigNum\fP &a, const \fBCBigNum\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBCBigNum\fP &a, const \fBCBigNum\fP &b)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &strm, const \fBCBigNum\fP &b)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBCBigNum\fP \fBBignum\fP"

.PP
Definition at line 724 of file bignum\&.h\&.
.SH "Function Documentation"
.PP 
.SS "bool operator!= (const \fBCBigNum\fP & a, const \fBCBigNum\fP & b)\fC [inline]\fP"

.PP
Definition at line 716 of file bignum\&.h\&.
.SS "const \fBCBigNum\fP operator% (const \fBCBigNum\fP & a, const \fBCBigNum\fP & b)\fC [inline]\fP"

.PP
Definition at line 691 of file bignum\&.h\&.
.SS "const \fBCBigNum\fP operator* (const \fBCBigNum\fP & a, const \fBCBigNum\fP & b)\fC [inline]\fP"

.PP
Definition at line 673 of file bignum\&.h\&.
.SS "const \fBCBigNum\fP operator+ (const \fBCBigNum\fP & a, const \fBCBigNum\fP & b)\fC [inline]\fP"

.PP
Definition at line 650 of file bignum\&.h\&.
.SS "const \fBCBigNum\fP operator- (const \fBCBigNum\fP & a, const \fBCBigNum\fP & b)\fC [inline]\fP"

.PP
Definition at line 658 of file bignum\&.h\&.
.SS "const \fBCBigNum\fP operator- (const \fBCBigNum\fP & a)\fC [inline]\fP"

.PP
Definition at line 666 of file bignum\&.h\&.
.SS "const \fBCBigNum\fP operator/ (const \fBCBigNum\fP & a, const \fBCBigNum\fP & b)\fC [inline]\fP"

.PP
Definition at line 682 of file bignum\&.h\&.
.SS "bool operator< (const \fBCBigNum\fP & a, const \fBCBigNum\fP & b)\fC [inline]\fP"

.PP
Definition at line 719 of file bignum\&.h\&.
.SS "const \fBCBigNum\fP operator<< (const \fBCBigNum\fP & a, unsigned int shift)\fC [inline]\fP"

.PP
Definition at line 700 of file bignum\&.h\&.
.SS "std::ostream& operator<< (std::ostream & strm, const \fBCBigNum\fP & b)\fC [inline]\fP"

.PP
Definition at line 722 of file bignum\&.h\&.
.SS "bool operator<= (const \fBCBigNum\fP & a, const \fBCBigNum\fP & b)\fC [inline]\fP"

.PP
Definition at line 717 of file bignum\&.h\&.
.SS "bool operator== (const \fBCBigNum\fP & a, const \fBCBigNum\fP & b)\fC [inline]\fP"

.PP
Definition at line 715 of file bignum\&.h\&.
.SS "bool operator> (const \fBCBigNum\fP & a, const \fBCBigNum\fP & b)\fC [inline]\fP"

.PP
Definition at line 720 of file bignum\&.h\&.
.SS "bool operator>= (const \fBCBigNum\fP & a, const \fBCBigNum\fP & b)\fC [inline]\fP"

.PP
Definition at line 718 of file bignum\&.h\&.
.SS "const \fBCBigNum\fP operator>> (const \fBCBigNum\fP & a, unsigned int shift)\fC [inline]\fP"

.PP
Definition at line 708 of file bignum\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
