.TH "/home/dev/ds-160209/src/test/bignum_tests.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/test/bignum_tests.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/test/unit_test\&.hpp>\fP
.br
\fC#include <limits>\fP
.br
\fC#include 'bignum\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNOINLINE\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBNOINLINE\fP void \fBmysetint64\fP (\fBCBigNum\fP &num, int64 n)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (bignum_setint64)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (bignum_SetHex)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NOINLINE"

.PP
Definition at line 23 of file bignum_tests\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (bignum_setint64)"

.PP
Definition at line 56 of file bignum_tests\&.cpp\&.
.SS "BOOST_AUTO_TEST_CASE (bignum_SetHex)"

.PP
Definition at line 125 of file bignum_tests\&.cpp\&.
.SS "\fBNOINLINE\fP void mysetint64 (\fBCBigNum\fP & num, int64 n)"

.PP
Definition at line 49 of file bignum_tests\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
