.TH "/home/dev/ds-160209/src/crypto/argon2/blake2/blamka-round-ref.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/crypto/argon2/blake2/blamka-round-ref.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'blake2\&.h'\fP
.br
\fC#include 'blake2-impl\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBG\fP(a,  b,  c,  d)"
.br
.ti -1c
.RI "#define \fBBLAKE2_ROUND_NOMSG\fP(v0,  v1,  v2,  v3,  v4,  v5,  v6,  v7,  v8,  v9,  v10,  v11, v12,  v13,  v14,  v15)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BLAKE2_ROUND_NOMSG(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15)"
\fBValue:\fP
.PP
.nf
do {                                                                       \\
        G(v0, v4, v8, v12);                                                    \\
        G(v1, v5, v9, v13);                                                    \\
        G(v2, v6, v10, v14);                                                   \\
        G(v3, v7, v11, v15);                                                   \\
        G(v0, v5, v10, v15);                                                   \\
        G(v1, v6, v11, v12);                                                   \\
        G(v2, v7, v8, v13);                                                    \\
        G(v3, v4, v9, v14);                                                    \
    } while ((void)0, 0)
.fi
.PP
Definition at line 26 of file blamka-round-ref\&.h\&.
.SS "#define G(a, b, c, d)"
\fBValue:\fP
.PP
.nf
do {                                                                       \
        a = fBlaMka(a, b);                                                     \
        d = rotr64(d ^ a, 32);                                                 \
        c = fBlaMka(c, d);                                                     \
        b = rotr64(b ^ c, 24);                                                 \
        a = fBlaMka(a, b);                                                     \
        d = rotr64(d ^ a, 16);                                                 \
        c = fBlaMka(c, d);                                                     \
        b = rotr64(b ^ c, 63);                                                 \
    } while ((void)0, 0)
.fi
.PP
Definition at line 14 of file blamka-round-ref\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
