.TH "/home/dev/ds-160209/src/crypto/argon2/blake2/blamka-round-opt.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/crypto/argon2/blake2/blamka-round-opt.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'blake2-impl\&.h'\fP
.br
\fC#include <emmintrin\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_mm_roti_epi64\fP(r,  c)   _mm_xor_si128(_mm_srli_epi64((r), -(c)), _mm_slli_epi64((r), 64 - (-(c))))"
.br
.ti -1c
.RI "#define \fBG1\fP(A0,  B0,  C0,  D0,  A1,  B1,  C1,  D1)"
.br
.ti -1c
.RI "#define \fBG2\fP(A0,  B0,  C0,  D0,  A1,  B1,  C1,  D1)"
.br
.ti -1c
.RI "#define \fBDIAGONALIZE\fP(A0,  B0,  C0,  D0,  A1,  B1,  C1,  D1)"
.br
.ti -1c
.RI "#define \fBUNDIAGONALIZE\fP(A0,  B0,  C0,  D0,  A1,  B1,  C1,  D1)"
.br
.ti -1c
.RI "#define \fBBLAKE2_ROUND\fP(A0,  A1,  B0,  B1,  C0,  C1,  D0,  D1)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _mm_roti_epi64(r, c)   _mm_xor_si128(_mm_srli_epi64((r), -(c)), _mm_slli_epi64((r), 64 - (-(c))))"

.PP
Definition at line 34 of file blamka-round-opt\&.h\&.
.SS "#define BLAKE2_ROUND(A0, A1, B0, B1, C0, C1, D0, D1)"
\fBValue:\fP
.PP
.nf
do {                                                                       \\
        G1(A0, B0, C0, D0, A1, B1, C1, D1);                                    \\
        G2(A0, B0, C0, D0, A1, B1, C1, D1);                                    \\
                                                                               \\
        DIAGONALIZE(A0, B0, C0, D0, A1, B1, C1, D1);                           \\
                                                                               \\
        G1(A0, B0, C0, D0, A1, B1, C1, D1);                                    \\
        G2(A0, B0, C0, D0, A1, B1, C1, D1);                                    \\
                                                                               \\
        UNDIAGONALIZE(A0, B0, C0, D0, A1, B1, C1, D1);                         \
    } while ((void)0, 0)
.fi
.PP
Definition at line 150 of file blamka-round-opt\&.h\&.
.SS "#define DIAGONALIZE(A0, B0, C0, D0, A1, B1, C1, D1)"
\fBValue:\fP
.PP
.nf
do {                                                                       \
        __m128i t0 = D0;                                                       \
        __m128i t1 = B0;                                                       \
        D0 = C0;                                                               \
        C0 = C1;                                                               \
        C1 = D0;                                                               \
        D0 = _mm_unpackhi_epi64(D1, _mm_unpacklo_epi64(t0, t0));               \
        D1 = _mm_unpackhi_epi64(t0, _mm_unpacklo_epi64(D1, D1));               \
        B0 = _mm_unpackhi_epi64(B0, _mm_unpacklo_epi64(B1, B1));               \
        B1 = _mm_unpackhi_epi64(B1, _mm_unpacklo_epi64(t1, t1));               \
    } while ((void)0, 0)
.fi
.PP
Definition at line 122 of file blamka-round-opt\&.h\&.
.SS "#define G1(A0, B0, C0, D0, A1, B1, C1, D1)"
\fBValue:\fP
.PP
.nf
do {                                                                       \
        A0 = fBlaMka(A0, B0);                                                  \
        A1 = fBlaMka(A1, B1);                                                  \
                                                                               \
        D0 = _mm_xor_si128(D0, A0);                                            \
        D1 = _mm_xor_si128(D1, A1);                                            \
                                                                               \
        D0 = _mm_roti_epi64(D0, -32);                                          \
        D1 = _mm_roti_epi64(D1, -32);                                          \
                                                                               \
        C0 = fBlaMka(C0, D0);                                                  \
        C1 = fBlaMka(C1, D1);                                                  \
                                                                               \
        B0 = _mm_xor_si128(B0, C0);                                            \
        B1 = _mm_xor_si128(B1, C1);                                            \
                                                                               \
        B0 = _mm_roti_epi64(B0, -24);                                          \
        B1 = _mm_roti_epi64(B1, -24);                                          \
    } while ((void)0, 0)
.fi
.PP
Definition at line 45 of file blamka-round-opt\&.h\&.
.SS "#define G2(A0, B0, C0, D0, A1, B1, C1, D1)"
\fBValue:\fP
.PP
.nf
do {                                                                       \
        A0 = fBlaMka(A0, B0);                                                  \
        A1 = fBlaMka(A1, B1);                                                  \
                                                                               \
        D0 = _mm_xor_si128(D0, A0);                                            \
        D1 = _mm_xor_si128(D1, A1);                                            \
                                                                               \
        D0 = _mm_roti_epi64(D0, -16);                                          \
        D1 = _mm_roti_epi64(D1, -16);                                          \
                                                                               \
        C0 = fBlaMka(C0, D0);                                                  \
        C1 = fBlaMka(C1, D1);                                                  \
                                                                               \
        B0 = _mm_xor_si128(B0, C0);                                            \
        B1 = _mm_xor_si128(B1, C1);                                            \
                                                                               \
        B0 = _mm_roti_epi64(B0, -63);                                          \
        B1 = _mm_roti_epi64(B1, -63);                                          \
    } while ((void)0, 0)
.fi
.PP
Definition at line 66 of file blamka-round-opt\&.h\&.
.SS "#define UNDIAGONALIZE(A0, B0, C0, D0, A1, B1, C1, D1)"
\fBValue:\fP
.PP
.nf
do {                                                                       \
        __m128i t0, t1;                                                        \
        t0 = C0;                                                               \
        C0 = C1;                                                               \
        C1 = t0;                                                               \
        t0 = B0;                                                               \
        t1 = D0;                                                               \
        B0 = _mm_unpackhi_epi64(B1, _mm_unpacklo_epi64(B0, B0));               \
        B1 = _mm_unpackhi_epi64(t0, _mm_unpacklo_epi64(B1, B1));               \
        D0 = _mm_unpackhi_epi64(D0, _mm_unpacklo_epi64(D1, D1));               \
        D1 = _mm_unpackhi_epi64(D1, _mm_unpacklo_epi64(t1, t1));               \
    } while ((void)0, 0)
.fi
.PP
Definition at line 135 of file blamka-round-opt\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
