.TH "/home/dev/ds-160209/src/qt/blockbrowser.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/blockbrowser.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'blockbrowser\&.h'\fP
.br
\fC#include 'ui_blockbrowser\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'wallet\&.h'\fP
.br
\fC#include 'base58\&.h'\fP
.br
\fC#include 'clientmodel\&.h'\fP
.br
\fC#include 'rpcserver\&.h'\fP
.br
\fC#include 'rpcclient\&.h'\fP
.br
\fC#include 'transactionrecord\&.h'\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBgetBlockHardness\fP (int height)"
.br
.ti -1c
.RI "int \fBgetBlockHashrate\fP (int height)"
.br
.ti -1c
.RI "const \fBCBlockIndex\fP * \fBgetBlockIndex\fP (int height)"
.br
.ti -1c
.RI "std::string \fBgetBlockHash\fP (int Height)"
.br
.ti -1c
.RI "int \fBgetBlockTime\fP (int Height)"
.br
.ti -1c
.RI "std::string \fBgetBlockMerkle\fP (int Height)"
.br
.ti -1c
.RI "int \fBgetBlocknBits\fP (int Height)"
.br
.ti -1c
.RI "int \fBgetBlockNonce\fP (int Height)"
.br
.ti -1c
.RI "std::string \fBgetBlockDebug\fP (int Height)"
.br
.ti -1c
.RI "int \fBblocksInPastHours\fP (int hours)"
.br
.ti -1c
.RI "double \fBgetTxTotalValue\fP (std::string txid)"
.br
.ti -1c
.RI "double \fBconvertCoins\fP (\fBCAmount\fP amount)"
.br
.ti -1c
.RI "std::string \fBgetOutputs\fP (std::string txid)"
.br
.ti -1c
.RI "std::string \fBgetInputs\fP (std::string txid)"
.br
.ti -1c
.RI "\fBint64_t\fP \fBgetInputValue\fP (\fBCTransaction\fP tx, \fBCScript\fP target)"
.br
.ti -1c
.RI "double \fBgetTxFees\fP (std::string txid)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int blocksInPastHours (int hours)"

.PP
Definition at line 134 of file blockbrowser\&.cpp\&.
.SS "double convertCoins (\fBCAmount\fP amount)"

.PP
Definition at line 183 of file blockbrowser\&.cpp\&.
.SS "std::string getBlockDebug (int Height)"

.PP
Definition at line 121 of file blockbrowser\&.cpp\&.
.SS "double getBlockHardness (int height)"

.PP
Definition at line 13 of file blockbrowser\&.cpp\&.
.SS "std::string getBlockHash (int Height)"

.PP
Definition at line 53 of file blockbrowser\&.cpp\&.
.SS "int getBlockHashrate (int height)"

.PP
Definition at line 36 of file blockbrowser\&.cpp\&.
.SS "const \fBCBlockIndex\fP* getBlockIndex (int height)"

.PP
Definition at line 46 of file blockbrowser\&.cpp\&.
.SS "std::string getBlockMerkle (int Height)"

.PP
Definition at line 82 of file blockbrowser\&.cpp\&.
.SS "int getBlocknBits (int Height)"

.PP
Definition at line 95 of file blockbrowser\&.cpp\&.
.SS "int getBlockNonce (int Height)"

.PP
Definition at line 108 of file blockbrowser\&.cpp\&.
.SS "int getBlockTime (int Height)"

.PP
Definition at line 69 of file blockbrowser\&.cpp\&.
.SS "std::string getInputs (std::string txid)"

.PP
Definition at line 221 of file blockbrowser\&.cpp\&.
.SS "\fBint64_t\fP getInputValue (\fBCTransaction\fP tx, \fBCScript\fP target)"

.PP
Definition at line 265 of file blockbrowser\&.cpp\&.
.SS "std::string getOutputs (std::string txid)"

.PP
Definition at line 188 of file blockbrowser\&.cpp\&.
.SS "double getTxFees (std::string txid)"

.PP
Definition at line 278 of file blockbrowser\&.cpp\&.
.SS "double getTxTotalValue (std::string txid)"

.PP
Definition at line 157 of file blockbrowser\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
