.TH "/home/dev/ds-160209/src/primitives/block.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/primitives/block.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'primitives/block\&.h'\fP
.br
\fC#include 'chainparams\&.h'\fP
.br
\fC#include <boost/foreach\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBCheckProofOfWork\fP (\fBuint256\fP \fBhash\fP, unsigned int nBits)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool CheckProofOfWork (\fBuint256\fP hash, unsigned int nBits)"

.PP
Definition at line 57 of file block\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
