.TH "/home/dev/ds-160209/src/qt/blockbrowser.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/blockbrowser.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clientmodel\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'wallet\&.h'\fP
.br
\fC#include 'base58\&.h'\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QProcess>\fP
.br
\fC#include <QTime>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <QStringList>\fP
.br
\fC#include <QMap>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QSlider>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBlockBrowser\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBgetBlockHardness\fP (int)"
.br
.ti -1c
.RI "double \fBgetTxTotalValue\fP (std::string)"
.br
.ti -1c
.RI "double \fBconvertCoins\fP (\fBint64_t\fP)"
.br
.ti -1c
.RI "double \fBgetTxFees\fP (std::string)"
.br
.ti -1c
.RI "int \fBgetBlockTime\fP (int)"
.br
.ti -1c
.RI "int \fBgetBlocknBits\fP (int)"
.br
.ti -1c
.RI "int \fBgetBlockNonce\fP (int)"
.br
.ti -1c
.RI "int \fBblocksInPastHours\fP (int)"
.br
.ti -1c
.RI "int \fBgetBlockHashrate\fP (int)"
.br
.ti -1c
.RI "std::string \fBgetInputs\fP (std::string)"
.br
.ti -1c
.RI "std::string \fBgetOutputs\fP (std::string)"
.br
.ti -1c
.RI "std::string \fBgetBlockHash\fP (int)"
.br
.ti -1c
.RI "std::string \fBgetBlockMerkle\fP (int)"
.br
.ti -1c
.RI "bool \fBaddnode\fP (std::string)"
.br
.ti -1c
.RI "const \fBCBlockIndex\fP * \fBgetBlockIndex\fP (int)"
.br
.ti -1c
.RI "\fBint64_t\fP \fBgetInputValue\fP (\fBCTransaction\fP, \fBCScript\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool addnode (std::string)"

.SS "int blocksInPastHours (int)"

.PP
Definition at line 134 of file blockbrowser\&.cpp\&.
.SS "double convertCoins (\fBint64_t\fP)"

.PP
Definition at line 183 of file blockbrowser\&.cpp\&.
.SS "double getBlockHardness (int)"

.PP
Definition at line 13 of file blockbrowser\&.cpp\&.
.SS "std::string getBlockHash (int)"

.PP
Definition at line 53 of file blockbrowser\&.cpp\&.
.SS "int getBlockHashrate (int)"

.PP
Definition at line 36 of file blockbrowser\&.cpp\&.
.SS "const \fBCBlockIndex\fP* getBlockIndex (int)"

.PP
Definition at line 46 of file blockbrowser\&.cpp\&.
.SS "std::string getBlockMerkle (int)"

.PP
Definition at line 82 of file blockbrowser\&.cpp\&.
.SS "int getBlocknBits (int)"

.PP
Definition at line 95 of file blockbrowser\&.cpp\&.
.SS "int getBlockNonce (int)"

.PP
Definition at line 108 of file blockbrowser\&.cpp\&.
.SS "int getBlockTime (int)"

.PP
Definition at line 69 of file blockbrowser\&.cpp\&.
.SS "std::string getInputs (std::string)"

.PP
Definition at line 221 of file blockbrowser\&.cpp\&.
.SS "\fBint64_t\fP getInputValue (\fBCTransaction\fP, \fBCScript\fP)"

.PP
Definition at line 265 of file blockbrowser\&.cpp\&.
.SS "std::string getOutputs (std::string)"

.PP
Definition at line 188 of file blockbrowser\&.cpp\&.
.SS "double getTxFees (std::string)"

.PP
Definition at line 278 of file blockbrowser\&.cpp\&.
.SS "double getTxTotalValue (std::string)"

.PP
Definition at line 157 of file blockbrowser\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
