.TH "block_" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
block_ \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint64_t\fP \fBv\fP [\fBARGON2_QWORDS_IN_BLOCK\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 59 of file core\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint64_t\fP block_::v[\fBARGON2_QWORDS_IN_BLOCK\fP]"

.PP
Definition at line 59 of file core\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
