.TH "/home/dev/ds-160209/src/leveldb/include/leveldb/c.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/include/leveldb/c.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBleveldb_t\fP \fBleveldb_t\fP"
.br
.ti -1c
.RI "typedef struct \fBleveldb_cache_t\fP \fBleveldb_cache_t\fP"
.br
.ti -1c
.RI "typedef struct \fBleveldb_comparator_t\fP \fBleveldb_comparator_t\fP"
.br
.ti -1c
.RI "typedef struct \fBleveldb_env_t\fP \fBleveldb_env_t\fP"
.br
.ti -1c
.RI "typedef struct \fBleveldb_filelock_t\fP \fBleveldb_filelock_t\fP"
.br
.ti -1c
.RI "typedef struct \fBleveldb_filterpolicy_t\fP \fBleveldb_filterpolicy_t\fP"
.br
.ti -1c
.RI "typedef struct \fBleveldb_iterator_t\fP \fBleveldb_iterator_t\fP"
.br
.ti -1c
.RI "typedef struct \fBleveldb_logger_t\fP \fBleveldb_logger_t\fP"
.br
.ti -1c
.RI "typedef struct \fBleveldb_options_t\fP \fBleveldb_options_t\fP"
.br
.ti -1c
.RI "typedef struct \fBleveldb_randomfile_t\fP \fBleveldb_randomfile_t\fP"
.br
.ti -1c
.RI "typedef struct \fBleveldb_readoptions_t\fP \fBleveldb_readoptions_t\fP"
.br
.ti -1c
.RI "typedef struct \fBleveldb_seqfile_t\fP \fBleveldb_seqfile_t\fP"
.br
.ti -1c
.RI "typedef struct \fBleveldb_snapshot_t\fP \fBleveldb_snapshot_t\fP"
.br
.ti -1c
.RI "typedef struct \fBleveldb_writablefile_t\fP \fBleveldb_writablefile_t\fP"
.br
.ti -1c
.RI "typedef struct \fBleveldb_writebatch_t\fP \fBleveldb_writebatch_t\fP"
.br
.ti -1c
.RI "typedef struct \fBleveldb_writeoptions_t\fP \fBleveldb_writeoptions_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBleveldb_no_compression\fP = 0, \fBleveldb_snappy_compression\fP = 1 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBleveldb_t\fP * \fBleveldb_open\fP (const \fBleveldb_options_t\fP *options, const char *\fBname\fP, char **errptr)"
.br
.ti -1c
.RI "void \fBleveldb_close\fP (\fBleveldb_t\fP *db)"
.br
.ti -1c
.RI "void \fBleveldb_put\fP (\fBleveldb_t\fP *db, const \fBleveldb_writeoptions_t\fP *options, const char *key, size_t keylen, const char *val, size_t vallen, char **errptr)"
.br
.ti -1c
.RI "void \fBleveldb_delete\fP (\fBleveldb_t\fP *db, const \fBleveldb_writeoptions_t\fP *options, const char *key, size_t keylen, char **errptr)"
.br
.ti -1c
.RI "void \fBleveldb_write\fP (\fBleveldb_t\fP *db, const \fBleveldb_writeoptions_t\fP *options, \fBleveldb_writebatch_t\fP *batch, char **errptr)"
.br
.ti -1c
.RI "char * \fBleveldb_get\fP (\fBleveldb_t\fP *db, const \fBleveldb_readoptions_t\fP *options, const char *key, size_t keylen, size_t *vallen, char **errptr)"
.br
.ti -1c
.RI "\fBleveldb_iterator_t\fP * \fBleveldb_create_iterator\fP (\fBleveldb_t\fP *db, const \fBleveldb_readoptions_t\fP *options)"
.br
.ti -1c
.RI "const \fBleveldb_snapshot_t\fP * \fBleveldb_create_snapshot\fP (\fBleveldb_t\fP *db)"
.br
.ti -1c
.RI "void \fBleveldb_release_snapshot\fP (\fBleveldb_t\fP *db, const \fBleveldb_snapshot_t\fP *snapshot)"
.br
.ti -1c
.RI "char * \fBleveldb_property_value\fP (\fBleveldb_t\fP *db, const char *propname)"
.br
.ti -1c
.RI "void \fBleveldb_approximate_sizes\fP (\fBleveldb_t\fP *db, int num_ranges, const char *const *range_start_key, const size_t *range_start_key_len, const char *const *range_limit_key, const size_t *range_limit_key_len, \fBuint64_t\fP *sizes)"
.br
.ti -1c
.RI "void \fBleveldb_compact_range\fP (\fBleveldb_t\fP *db, const char *start_key, size_t start_key_len, const char *limit_key, size_t limit_key_len)"
.br
.ti -1c
.RI "void \fBleveldb_destroy_db\fP (const \fBleveldb_options_t\fP *options, const char *\fBname\fP, char **errptr)"
.br
.ti -1c
.RI "void \fBleveldb_repair_db\fP (const \fBleveldb_options_t\fP *options, const char *\fBname\fP, char **errptr)"
.br
.ti -1c
.RI "void \fBleveldb_iter_destroy\fP (\fBleveldb_iterator_t\fP *)"
.br
.ti -1c
.RI "unsigned char \fBleveldb_iter_valid\fP (const \fBleveldb_iterator_t\fP *)"
.br
.ti -1c
.RI "void \fBleveldb_iter_seek_to_first\fP (\fBleveldb_iterator_t\fP *)"
.br
.ti -1c
.RI "void \fBleveldb_iter_seek_to_last\fP (\fBleveldb_iterator_t\fP *)"
.br
.ti -1c
.RI "void \fBleveldb_iter_seek\fP (\fBleveldb_iterator_t\fP *, const char *k, size_t klen)"
.br
.ti -1c
.RI "void \fBleveldb_iter_next\fP (\fBleveldb_iterator_t\fP *)"
.br
.ti -1c
.RI "void \fBleveldb_iter_prev\fP (\fBleveldb_iterator_t\fP *)"
.br
.ti -1c
.RI "const char * \fBleveldb_iter_key\fP (const \fBleveldb_iterator_t\fP *, size_t *klen)"
.br
.ti -1c
.RI "const char * \fBleveldb_iter_value\fP (const \fBleveldb_iterator_t\fP *, size_t *vlen)"
.br
.ti -1c
.RI "void \fBleveldb_iter_get_error\fP (const \fBleveldb_iterator_t\fP *, char **errptr)"
.br
.ti -1c
.RI "\fBleveldb_writebatch_t\fP * \fBleveldb_writebatch_create\fP ()"
.br
.ti -1c
.RI "void \fBleveldb_writebatch_destroy\fP (\fBleveldb_writebatch_t\fP *)"
.br
.ti -1c
.RI "void \fBleveldb_writebatch_clear\fP (\fBleveldb_writebatch_t\fP *)"
.br
.ti -1c
.RI "void \fBleveldb_writebatch_put\fP (\fBleveldb_writebatch_t\fP *, const char *key, size_t klen, const char *val, size_t vlen)"
.br
.ti -1c
.RI "void \fBleveldb_writebatch_delete\fP (\fBleveldb_writebatch_t\fP *, const char *key, size_t klen)"
.br
.ti -1c
.RI "void \fBleveldb_writebatch_iterate\fP (\fBleveldb_writebatch_t\fP *, void *\fBstate\fP, void(*put)(void *, const char *k, size_t klen, const char *v, size_t vlen), void(*deleted)(void *, const char *k, size_t klen))"
.br
.ti -1c
.RI "\fBleveldb_options_t\fP * \fBleveldb_options_create\fP ()"
.br
.ti -1c
.RI "void \fBleveldb_options_destroy\fP (\fBleveldb_options_t\fP *)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_comparator\fP (\fBleveldb_options_t\fP *, \fBleveldb_comparator_t\fP *)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_filter_policy\fP (\fBleveldb_options_t\fP *, \fBleveldb_filterpolicy_t\fP *)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_create_if_missing\fP (\fBleveldb_options_t\fP *, unsigned char)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_error_if_exists\fP (\fBleveldb_options_t\fP *, unsigned char)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_paranoid_checks\fP (\fBleveldb_options_t\fP *, unsigned char)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_env\fP (\fBleveldb_options_t\fP *, \fBleveldb_env_t\fP *)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_info_log\fP (\fBleveldb_options_t\fP *, \fBleveldb_logger_t\fP *)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_write_buffer_size\fP (\fBleveldb_options_t\fP *, size_t)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_max_open_files\fP (\fBleveldb_options_t\fP *, int)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_cache\fP (\fBleveldb_options_t\fP *, \fBleveldb_cache_t\fP *)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_block_size\fP (\fBleveldb_options_t\fP *, size_t)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_block_restart_interval\fP (\fBleveldb_options_t\fP *, int)"
.br
.ti -1c
.RI "void \fBleveldb_options_set_compression\fP (\fBleveldb_options_t\fP *, int)"
.br
.ti -1c
.RI "\fBleveldb_comparator_t\fP * \fBleveldb_comparator_create\fP (void *\fBstate\fP, void(*destructor)(void *), int(*compare)(void *, const char *a, size_t alen, const char *b, size_t blen), const char *(*\fBname\fP)(void *))"
.br
.ti -1c
.RI "void \fBleveldb_comparator_destroy\fP (\fBleveldb_comparator_t\fP *)"
.br
.ti -1c
.RI "\fBleveldb_filterpolicy_t\fP * \fBleveldb_filterpolicy_create\fP (void *\fBstate\fP, void(*destructor)(void *), char *(*create_filter)(void *, const char *const *key_array, const size_t *key_length_array, int num_keys, size_t *filter_length), unsigned char(*key_may_match)(void *, const char *key, size_t length, const char *filter, size_t filter_length), const char *(*\fBname\fP)(void *))"
.br
.ti -1c
.RI "void \fBleveldb_filterpolicy_destroy\fP (\fBleveldb_filterpolicy_t\fP *)"
.br
.ti -1c
.RI "\fBleveldb_filterpolicy_t\fP * \fBleveldb_filterpolicy_create_bloom\fP (int bits_per_key)"
.br
.ti -1c
.RI "\fBleveldb_readoptions_t\fP * \fBleveldb_readoptions_create\fP ()"
.br
.ti -1c
.RI "void \fBleveldb_readoptions_destroy\fP (\fBleveldb_readoptions_t\fP *)"
.br
.ti -1c
.RI "void \fBleveldb_readoptions_set_verify_checksums\fP (\fBleveldb_readoptions_t\fP *, unsigned char)"
.br
.ti -1c
.RI "void \fBleveldb_readoptions_set_fill_cache\fP (\fBleveldb_readoptions_t\fP *, unsigned char)"
.br
.ti -1c
.RI "void \fBleveldb_readoptions_set_snapshot\fP (\fBleveldb_readoptions_t\fP *, const \fBleveldb_snapshot_t\fP *)"
.br
.ti -1c
.RI "\fBleveldb_writeoptions_t\fP * \fBleveldb_writeoptions_create\fP ()"
.br
.ti -1c
.RI "void \fBleveldb_writeoptions_destroy\fP (\fBleveldb_writeoptions_t\fP *)"
.br
.ti -1c
.RI "void \fBleveldb_writeoptions_set_sync\fP (\fBleveldb_writeoptions_t\fP *, unsigned char)"
.br
.ti -1c
.RI "\fBleveldb_cache_t\fP * \fBleveldb_cache_create_lru\fP (size_t capacity)"
.br
.ti -1c
.RI "void \fBleveldb_cache_destroy\fP (\fBleveldb_cache_t\fP *cache)"
.br
.ti -1c
.RI "\fBleveldb_env_t\fP * \fBleveldb_create_default_env\fP ()"
.br
.ti -1c
.RI "void \fBleveldb_env_destroy\fP (\fBleveldb_env_t\fP *)"
.br
.ti -1c
.RI "void \fBleveldb_free\fP (void *ptr)"
.br
.ti -1c
.RI "int \fBleveldb_major_version\fP ()"
.br
.ti -1c
.RI "int \fBleveldb_minor_version\fP ()"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBleveldb_cache_t\fP \fBleveldb_cache_t\fP"

.PP
Definition at line 54 of file c\&.h\&.
.SS "typedef struct \fBleveldb_comparator_t\fP \fBleveldb_comparator_t\fP"

.PP
Definition at line 55 of file c\&.h\&.
.SS "typedef struct \fBleveldb_env_t\fP \fBleveldb_env_t\fP"

.PP
Definition at line 56 of file c\&.h\&.
.SS "typedef struct \fBleveldb_filelock_t\fP \fBleveldb_filelock_t\fP"

.PP
Definition at line 57 of file c\&.h\&.
.SS "typedef struct \fBleveldb_filterpolicy_t\fP \fBleveldb_filterpolicy_t\fP"

.PP
Definition at line 58 of file c\&.h\&.
.SS "typedef struct \fBleveldb_iterator_t\fP \fBleveldb_iterator_t\fP"

.PP
Definition at line 59 of file c\&.h\&.
.SS "typedef struct \fBleveldb_logger_t\fP \fBleveldb_logger_t\fP"

.PP
Definition at line 60 of file c\&.h\&.
.SS "typedef struct \fBleveldb_options_t\fP \fBleveldb_options_t\fP"

.PP
Definition at line 61 of file c\&.h\&.
.SS "typedef struct \fBleveldb_randomfile_t\fP \fBleveldb_randomfile_t\fP"

.PP
Definition at line 62 of file c\&.h\&.
.SS "typedef struct \fBleveldb_readoptions_t\fP \fBleveldb_readoptions_t\fP"

.PP
Definition at line 63 of file c\&.h\&.
.SS "typedef struct \fBleveldb_seqfile_t\fP \fBleveldb_seqfile_t\fP"

.PP
Definition at line 64 of file c\&.h\&.
.SS "typedef struct \fBleveldb_snapshot_t\fP \fBleveldb_snapshot_t\fP"

.PP
Definition at line 65 of file c\&.h\&.
.SS "typedef struct \fBleveldb_t\fP \fBleveldb_t\fP"

.PP
Definition at line 53 of file c\&.h\&.
.SS "typedef struct \fBleveldb_writablefile_t\fP \fBleveldb_writablefile_t\fP"

.PP
Definition at line 66 of file c\&.h\&.
.SS "typedef struct \fBleveldb_writebatch_t\fP \fBleveldb_writebatch_t\fP"

.PP
Definition at line 67 of file c\&.h\&.
.SS "typedef struct \fBleveldb_writeoptions_t\fP \fBleveldb_writeoptions_t\fP"

.PP
Definition at line 68 of file c\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIleveldb_no_compression \fP\fP
.TP
\fB\fIleveldb_snappy_compression \fP\fP
.PP
Definition at line 203 of file c\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void leveldb_approximate_sizes (\fBleveldb_t\fP * db, int num_ranges, const char *const * range_start_key, const size_t * range_start_key_len, const char *const * range_limit_key, const size_t * range_limit_key_len, \fBuint64_t\fP * sizes)"

.PP
Definition at line 252 of file c\&.cc\&.
.SS "\fBleveldb_cache_t\fP* leveldb_cache_create_lru (size_t capacity)"

.PP
Definition at line 560 of file c\&.cc\&.
.SS "void leveldb_cache_destroy (\fBleveldb_cache_t\fP * cache)"

.PP
Definition at line 566 of file c\&.cc\&.
.SS "void leveldb_close (\fBleveldb_t\fP * db)"

.PP
Definition at line 165 of file c\&.cc\&.
.SS "void leveldb_compact_range (\fBleveldb_t\fP * db, const char * start_key, size_t start_key_len, const char * limit_key, size_t limit_key_len)"

.PP
Definition at line 267 of file c\&.cc\&.
.SS "\fBleveldb_comparator_t\fP* leveldb_comparator_create (void * state, void(*)(void *) destructor, int(*)(void *, const char *a, size_t alen, const char *b, size_t blen) compare, const char *(*)(void *) name)"

.PP
Definition at line 453 of file c\&.cc\&.
.SS "void leveldb_comparator_destroy (\fBleveldb_comparator_t\fP *)"

.PP
Definition at line 469 of file c\&.cc\&.
.SS "\fBleveldb_env_t\fP* leveldb_create_default_env ()"

.PP
Definition at line 571 of file c\&.cc\&.
.SS "\fBleveldb_iterator_t\fP* leveldb_create_iterator (\fBleveldb_t\fP * db, const \fBleveldb_readoptions_t\fP * options)"

.PP
Definition at line 218 of file c\&.cc\&.
.SS "const \fBleveldb_snapshot_t\fP* leveldb_create_snapshot (\fBleveldb_t\fP * db)"

.PP
Definition at line 226 of file c\&.cc\&.
.SS "void leveldb_delete (\fBleveldb_t\fP * db, const \fBleveldb_writeoptions_t\fP * options, const char * key, size_t keylen, char ** errptr)"

.PP
Definition at line 180 of file c\&.cc\&.
.SS "void leveldb_destroy_db (const \fBleveldb_options_t\fP * options, const char * name, char ** errptr)"

.PP
Definition at line 278 of file c\&.cc\&.
.SS "void leveldb_env_destroy (\fBleveldb_env_t\fP *)"

.PP
Definition at line 578 of file c\&.cc\&.
.SS "\fBleveldb_filterpolicy_t\fP* leveldb_filterpolicy_create (void * state, void(*)(void *) destructor, char *(*)(void *, const char *const *key_array, const size_t *key_length_array, int num_keys, size_t *filter_length) create_filter, unsigned char(*)(void *, const char *key, size_t length, const char *filter, size_t filter_length) key_may_match, const char *(*)(void *) name)"

.PP
Definition at line 473 of file c\&.cc\&.
.SS "\fBleveldb_filterpolicy_t\fP* leveldb_filterpolicy_create_bloom (int bits_per_key)"

.PP
Definition at line 499 of file c\&.cc\&.
.SS "void leveldb_filterpolicy_destroy (\fBleveldb_filterpolicy_t\fP *)"

.PP
Definition at line 495 of file c\&.cc\&.
.SS "void leveldb_free (void * ptr)"

.PP
Definition at line 583 of file c\&.cc\&.
.SS "char* leveldb_get (\fBleveldb_t\fP * db, const \fBleveldb_readoptions_t\fP * options, const char * key, size_t keylen, size_t * vallen, char ** errptr)"

.PP
Definition at line 197 of file c\&.cc\&.
.SS "void leveldb_iter_destroy (\fBleveldb_iterator_t\fP *)"

.PP
Definition at line 292 of file c\&.cc\&.
.SS "void leveldb_iter_get_error (const \fBleveldb_iterator_t\fP *, char ** errptr)"

.PP
Definition at line 333 of file c\&.cc\&.
.SS "const char* leveldb_iter_key (const \fBleveldb_iterator_t\fP *, size_t * klen)"

.PP
Definition at line 321 of file c\&.cc\&.
.SS "void leveldb_iter_next (\fBleveldb_iterator_t\fP *)"

.PP
Definition at line 313 of file c\&.cc\&.
.SS "void leveldb_iter_prev (\fBleveldb_iterator_t\fP *)"

.PP
Definition at line 317 of file c\&.cc\&.
.SS "void leveldb_iter_seek (\fBleveldb_iterator_t\fP *, const char * k, size_t klen)"

.PP
Definition at line 309 of file c\&.cc\&.
.SS "void leveldb_iter_seek_to_first (\fBleveldb_iterator_t\fP *)"

.PP
Definition at line 301 of file c\&.cc\&.
.SS "void leveldb_iter_seek_to_last (\fBleveldb_iterator_t\fP *)"

.PP
Definition at line 305 of file c\&.cc\&.
.SS "unsigned char leveldb_iter_valid (const \fBleveldb_iterator_t\fP *)"

.PP
Definition at line 297 of file c\&.cc\&.
.SS "const char* leveldb_iter_value (const \fBleveldb_iterator_t\fP *, size_t * vlen)"

.PP
Definition at line 327 of file c\&.cc\&.
.SS "int leveldb_major_version ()"

.PP
Definition at line 587 of file c\&.cc\&.
.SS "int leveldb_minor_version ()"

.PP
Definition at line 591 of file c\&.cc\&.
.SS "\fBleveldb_t\fP* leveldb_open (const \fBleveldb_options_t\fP * options, const char * name, char ** errptr)"

.PP
Definition at line 152 of file c\&.cc\&.
.SS "\fBleveldb_options_t\fP* leveldb_options_create ()"

.PP
Definition at line 386 of file c\&.cc\&.
.SS "void leveldb_options_destroy (\fBleveldb_options_t\fP *)"

.PP
Definition at line 390 of file c\&.cc\&.
.SS "void leveldb_options_set_block_restart_interval (\fBleveldb_options_t\fP *, int)"

.PP
Definition at line 445 of file c\&.cc\&.
.SS "void leveldb_options_set_block_size (\fBleveldb_options_t\fP *, size_t)"

.PP
Definition at line 441 of file c\&.cc\&.
.SS "void leveldb_options_set_cache (\fBleveldb_options_t\fP *, \fBleveldb_cache_t\fP *)"

.PP
Definition at line 437 of file c\&.cc\&.
.SS "void leveldb_options_set_comparator (\fBleveldb_options_t\fP *, \fBleveldb_comparator_t\fP *)"

.PP
Definition at line 394 of file c\&.cc\&.
.SS "void leveldb_options_set_compression (\fBleveldb_options_t\fP *, int)"

.PP
Definition at line 449 of file c\&.cc\&.
.SS "void leveldb_options_set_create_if_missing (\fBleveldb_options_t\fP *, unsigned char)"

.PP
Definition at line 406 of file c\&.cc\&.
.SS "void leveldb_options_set_env (\fBleveldb_options_t\fP *, \fBleveldb_env_t\fP *)"

.PP
Definition at line 421 of file c\&.cc\&.
.SS "void leveldb_options_set_error_if_exists (\fBleveldb_options_t\fP *, unsigned char)"

.PP
Definition at line 411 of file c\&.cc\&.
.SS "void leveldb_options_set_filter_policy (\fBleveldb_options_t\fP *, \fBleveldb_filterpolicy_t\fP *)"

.PP
Definition at line 400 of file c\&.cc\&.
.SS "void leveldb_options_set_info_log (\fBleveldb_options_t\fP *, \fBleveldb_logger_t\fP *)"

.PP
Definition at line 425 of file c\&.cc\&.
.SS "void leveldb_options_set_max_open_files (\fBleveldb_options_t\fP *, int)"

.PP
Definition at line 433 of file c\&.cc\&.
.SS "void leveldb_options_set_paranoid_checks (\fBleveldb_options_t\fP *, unsigned char)"

.PP
Definition at line 416 of file c\&.cc\&.
.SS "void leveldb_options_set_write_buffer_size (\fBleveldb_options_t\fP *, size_t)"

.PP
Definition at line 429 of file c\&.cc\&.
.SS "char* leveldb_property_value (\fBleveldb_t\fP * db, const char * propname)"

.PP
Definition at line 240 of file c\&.cc\&.
.SS "void leveldb_put (\fBleveldb_t\fP * db, const \fBleveldb_writeoptions_t\fP * options, const char * key, size_t keylen, const char * val, size_t vallen, char ** errptr)"

.PP
Definition at line 170 of file c\&.cc\&.
.SS "\fBleveldb_readoptions_t\fP* leveldb_readoptions_create ()"

.PP
Definition at line 522 of file c\&.cc\&.
.SS "void leveldb_readoptions_destroy (\fBleveldb_readoptions_t\fP *)"

.PP
Definition at line 526 of file c\&.cc\&.
.SS "void leveldb_readoptions_set_fill_cache (\fBleveldb_readoptions_t\fP *, unsigned char)"

.PP
Definition at line 536 of file c\&.cc\&.
.SS "void leveldb_readoptions_set_snapshot (\fBleveldb_readoptions_t\fP *, const \fBleveldb_snapshot_t\fP *)"

.PP
Definition at line 541 of file c\&.cc\&.
.SS "void leveldb_readoptions_set_verify_checksums (\fBleveldb_readoptions_t\fP *, unsigned char)"

.PP
Definition at line 530 of file c\&.cc\&.
.SS "void leveldb_release_snapshot (\fBleveldb_t\fP * db, const \fBleveldb_snapshot_t\fP * snapshot)"

.PP
Definition at line 233 of file c\&.cc\&.
.SS "void leveldb_repair_db (const \fBleveldb_options_t\fP * options, const char * name, char ** errptr)"

.PP
Definition at line 285 of file c\&.cc\&.
.SS "void leveldb_write (\fBleveldb_t\fP * db, const \fBleveldb_writeoptions_t\fP * options, \fBleveldb_writebatch_t\fP * batch, char ** errptr)"

.PP
Definition at line 189 of file c\&.cc\&.
.SS "void leveldb_writebatch_clear (\fBleveldb_writebatch_t\fP *)"

.PP
Definition at line 345 of file c\&.cc\&.
.SS "\fBleveldb_writebatch_t\fP* leveldb_writebatch_create ()"

.PP
Definition at line 337 of file c\&.cc\&.
.SS "void leveldb_writebatch_delete (\fBleveldb_writebatch_t\fP *, const char * key, size_t klen)"

.PP
Definition at line 356 of file c\&.cc\&.
.SS "void leveldb_writebatch_destroy (\fBleveldb_writebatch_t\fP *)"

.PP
Definition at line 341 of file c\&.cc\&.
.SS "void leveldb_writebatch_iterate (\fBleveldb_writebatch_t\fP *, void * state, void(*)(void *, const char *k, size_t klen, const char *v, size_t vlen) put, void(*)(void *, const char *k, size_t klen) deleted)"

.PP
Definition at line 362 of file c\&.cc\&.
.SS "void leveldb_writebatch_put (\fBleveldb_writebatch_t\fP *, const char * key, size_t klen, const char * val, size_t vlen)"

.PP
Definition at line 349 of file c\&.cc\&.
.SS "\fBleveldb_writeoptions_t\fP* leveldb_writeoptions_create ()"

.PP
Definition at line 547 of file c\&.cc\&.
.SS "void leveldb_writeoptions_destroy (\fBleveldb_writeoptions_t\fP *)"

.PP
Definition at line 551 of file c\&.cc\&.
.SS "void leveldb_writeoptions_set_sync (\fBleveldb_writeoptions_t\fP *, unsigned char)"

.PP
Definition at line 555 of file c\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
