.TH "/home/dev/ds-160209/src/leveldb/db/c_test.c" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/db/c_test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'leveldb/c\&.h'\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCheckNoError\fP(err)"
.br
.ti -1c
.RI "#define \fBCheckCondition\fP(cond)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned char \fBFilterKeyMatch\fP (void *\fBarg\fP, const char *key, size_t length, const char *filter, size_t filter_length)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char * \fBphase\fP = ''"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CheckCondition(cond)"
\fBValue:\fP
.PP
.nf
if (!(cond)) {                                                        \
    fprintf(stderr, "%s:%d: %s: %s\n", __FILE__, __LINE__, phase, #cond); \
    abort();                                                            \
  }
.fi
.PP
Definition at line 35 of file c_test\&.c\&.
.SS "#define CheckNoError(err)"
\fBValue:\fP
.PP
.nf
if ((err) != NULL) {                                                  \
    fprintf(stderr, "%s:%d: %s: %s\n", __FILE__, __LINE__, phase, (err)); \
    abort();                                                            \
  }
.fi
.PP
Definition at line 29 of file c_test\&.c\&.
.SH "Function Documentation"
.PP 
.SS "unsigned char FilterKeyMatch (void * arg, const char * key, size_t length, const char * filter, size_t filter_length)"

.PP
Definition at line 148 of file c_test\&.c\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 157 of file c_test\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const char* phase = ''"

.PP
Definition at line 14 of file c_test\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
