.TH "CAccountingEntry" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAccountingEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wallet\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCAccountingEntry\fP ()"
.br
.ti -1c
.RI "void \fBSetNull\fP ()"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBstrAccount\fP"
.br
.ti -1c
.RI "\fBCAmount\fP \fBnCreditDebit\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnTime\fP"
.br
.ti -1c
.RI "std::string \fBstrOtherAccount\fP"
.br
.ti -1c
.RI "std::string \fBstrComment\fP"
.br
.ti -1c
.RI "\fBmapValue_t\fP \fBmapValue\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnOrderPos\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBnEntryNo\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal transfers\&. Database key is acentry<account><counter>\&. 
.PP
Definition at line 1178 of file wallet\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CAccountingEntry::CAccountingEntry ()\fC [inline]\fP"

.PP
Definition at line 1190 of file wallet\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream , typename Operation > void CAccountingEntry::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 1208 of file wallet\&.h\&.
.SS "void CAccountingEntry::SetNull ()\fC [inline]\fP"

.PP
Definition at line 1195 of file wallet\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CAccountingEntry::ADD_SERIALIZE_METHODS"

.PP
Definition at line 1205 of file wallet\&.h\&.
.SS "\fBmapValue_t\fP CAccountingEntry::mapValue"

.PP
Definition at line 1186 of file wallet\&.h\&.
.SS "\fBCAmount\fP CAccountingEntry::nCreditDebit"

.PP
Definition at line 1182 of file wallet\&.h\&.
.SS "\fBuint64_t\fP CAccountingEntry::nEntryNo"

.PP
Definition at line 1188 of file wallet\&.h\&.
.SS "\fBint64_t\fP CAccountingEntry::nOrderPos"

.PP
Definition at line 1187 of file wallet\&.h\&.
.SS "\fBint64_t\fP CAccountingEntry::nTime"

.PP
Definition at line 1183 of file wallet\&.h\&.
.SS "std::string CAccountingEntry::strAccount"

.PP
Definition at line 1181 of file wallet\&.h\&.
.SS "std::string CAccountingEntry::strComment"

.PP
Definition at line 1185 of file wallet\&.h\&.
.SS "std::string CAccountingEntry::strOtherAccount"

.PP
Definition at line 1184 of file wallet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
