.TH "CAccount" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAccount \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wallet\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCAccount\fP ()"
.br
.ti -1c
.RI "void \fBSetNull\fP ()"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCPubKey\fP \fBvchPubKey\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Account information\&. Stored in wallet with key 'acc'+string account name\&. 
.PP
Definition at line 1148 of file wallet\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CAccount::CAccount ()\fC [inline]\fP"

.PP
Definition at line 1153 of file wallet\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream , typename Operation > void CAccount::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 1166 of file wallet\&.h\&.
.SS "void CAccount::SetNull ()\fC [inline]\fP"

.PP
Definition at line 1158 of file wallet\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CAccount::ADD_SERIALIZE_METHODS"

.PP
Definition at line 1163 of file wallet\&.h\&.
.SS "\fBCPubKey\fP CAccount::vchPubKey"

.PP
Definition at line 1151 of file wallet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
