.TH "/home/dev/ds-160209/src/leveldb/util/cache.cc" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/util/cache.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'leveldb/cache\&.h'\fP
.br
\fC#include 'port/port\&.h'\fP
.br
\fC#include 'util/hash\&.h'\fP
.br
\fC#include 'util/mutexlock\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Cache * \fBleveldb::NewLRUCache\fP (size_t capacity)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "size_t capacity_"

.PP
Definition at line 157 of file cache\&.cc\&.
.SS "size_t charge"

.PP
Definition at line 31 of file cache\&.cc\&.
.SS "void(* deleter) (const Slice &, void *\fBvalue\fP)"

.PP
Definition at line 27 of file cache\&.cc\&.
.SS "\fBuint32_t\fP elems_"

.PP
Definition at line 92 of file cache\&.cc\&.
.SS "\fBuint32_t\fP hash"

.PP
Definition at line 34 of file cache\&.cc\&.
.SS "port::Mutex id_mutex_"

.PP
Definition at line 273 of file cache\&.cc\&.
.SS "char key_data[1]"

.PP
Definition at line 35 of file cache\&.cc\&.
.SS "size_t key_length"

.PP
Definition at line 32 of file cache\&.cc\&.
.SS "\fBuint64_t\fP last_id_"

.PP
Definition at line 274 of file cache\&.cc\&.
.SS "\fBuint32_t\fP length_"

.PP
Definition at line 91 of file cache\&.cc\&.
.SS "LRUHandle** list_"

.PP
Definition at line 93 of file cache\&.cc\&.
.SS "LRUHandle lru_"

.PP
Definition at line 165 of file cache\&.cc\&.
.SS "port::Mutex mutex_"

.PP
Definition at line 160 of file cache\&.cc\&.
.SS "LRUHandle* next"

.PP
Definition at line 29 of file cache\&.cc\&.
.SS "LRUHandle* next_hash"

.PP
Definition at line 28 of file cache\&.cc\&.
.SS "LRUHandle* prev"

.PP
Definition at line 30 of file cache\&.cc\&.
.SS "\fBuint32_t\fP refs"

.PP
Definition at line 33 of file cache\&.cc\&.
.SS "LRUCache shard_[kNumShards]"

.PP
Definition at line 272 of file cache\&.cc\&.
.SS "HandleTable table_"

.PP
Definition at line 167 of file cache\&.cc\&.
.SS "size_t usage_"

.PP
Definition at line 161 of file cache\&.cc\&.
.SS "void* value"

.PP
Definition at line 26 of file cache\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
