.TH "CActiveStormnode" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CActiveStormnode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <activestormnode\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCActiveStormnode\fP ()"
.br
.ti -1c
.RI "void \fBManageStatus\fP ()"
.br
.RI "\fIManage status of main Stormnode\&. \fP"
.ti -1c
.RI "std::string \fBGetStatus\fP ()"
.br
.ti -1c
.RI "bool \fBRegister\fP (std::string strService, std::string strKey, std::string strTxHash, std::string strOutputIndex, std::string &errorMessage)"
.br
.RI "\fIRegister remote Stormnode\&. \fP"
.ti -1c
.RI "bool \fBGetStormNodeVin\fP (\fBCTxIn\fP &\fBvin\fP, \fBCPubKey\fP &pubkey, \fBCKey\fP &secretKey)"
.br
.RI "\fIGet 10,000 DRKSLK input that can be used for the Stormnode\&. \fP"
.ti -1c
.RI "vector< \fBCOutput\fP > \fBSelectCoinsStormnode\fP ()"
.br
.ti -1c
.RI "bool \fBEnableHotColdStormNode\fP (\fBCTxIn\fP &\fBvin\fP, \fBCService\fP &addr)"
.br
.RI "\fIEnable cold wallet mode (run a Stormnode with no funds) \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCPubKey\fP \fBpubKeyStormnode\fP"
.br
.ti -1c
.RI "\fBCTxIn\fP \fBvin\fP"
.br
.ti -1c
.RI "\fBCService\fP \fBservice\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.ti -1c
.RI "std::string \fBnotCapableReason\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file activestormnode\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CActiveStormnode::CActiveStormnode ()\fC [inline]\fP"

.PP
Definition at line 48 of file activestormnode\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CActiveStormnode::EnableHotColdStormNode (\fBCTxIn\fP & vin, \fBCService\fP & addr)"

.PP
Enable cold wallet mode (run a Stormnode with no funds) 
.PP
Definition at line 402 of file activestormnode\&.cpp\&.
.SS "std::string CActiveStormnode::GetStatus ()"

.PP
Definition at line 142 of file activestormnode\&.cpp\&.
.SS "bool CActiveStormnode::GetStormNodeVin (\fBCTxIn\fP & vin, \fBCPubKey\fP & pubkey, \fBCKey\fP & secretKey)"

.PP
Get 10,000 DRKSLK input that can be used for the Stormnode\&. 
.PP
Definition at line 292 of file activestormnode\&.cpp\&.
.SS "void CActiveStormnode::ManageStatus ()"

.PP
Manage status of main Stormnode\&. 
.PP
Definition at line 17 of file activestormnode\&.cpp\&.
.SS "bool CActiveStormnode::Register (std::string strService, std::string strKey, std::string strTxHash, std::string strOutputIndex, std::string & errorMessage)"

.PP
Register remote Stormnode\&. 
.PP
Definition at line 209 of file activestormnode\&.cpp\&.
.SS "vector< \fBCOutput\fP > CActiveStormnode::SelectCoinsStormnode ()"

.PP
Definition at line 365 of file activestormnode\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string CActiveStormnode::notCapableReason"

.PP
Definition at line 46 of file activestormnode\&.h\&.
.SS "\fBCPubKey\fP CActiveStormnode::pubKeyStormnode"

.PP
Definition at line 39 of file activestormnode\&.h\&.
.SS "\fBCService\fP CActiveStormnode::service"

.PP
Definition at line 43 of file activestormnode\&.h\&.
.SS "int CActiveStormnode::status"

.PP
Definition at line 45 of file activestormnode\&.h\&.
.SS "\fBCTxIn\fP CActiveStormnode::vin"

.PP
Definition at line 42 of file activestormnode\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
