.TH "CAddress" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAddress \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <protocol\&.h>\fP
.PP
Inherits \fBCService\fP\&.
.PP
Inherited by \fBCAddrInfo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCAddress\fP ()"
.br
.ti -1c
.RI "\fBCAddress\fP (\fBCService\fP ipIn, \fBuint64_t\fP nServicesIn=\fBNODE_NETWORK\fP)"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.ti -1c
.RI "void \fBprint\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBnServices\fP"
.br
.ti -1c
.RI "unsigned int \fBnTime\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnLastTry\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBCService\fP with information about it as peer 
.PP
Definition at line 74 of file protocol\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CAddress::CAddress ()"

.PP
Definition at line 95 of file protocol\&.cpp\&.
.SS "CAddress::CAddress (\fBCService\fP ipIn, \fBuint64_t\fP nServicesIn = \fC\fBNODE_NETWORK\fP\fP)\fC [explicit]\fP"

.PP
Definition at line 100 of file protocol\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void CAddress::Init ()"

.PP
Definition at line 106 of file protocol\&.cpp\&.
.SS "void CAddress::print () const"

.SS "template<typename Stream , typename Operation > void CAddress::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 85 of file protocol\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CAddress::ADD_SERIALIZE_METHODS"

.PP
Definition at line 82 of file protocol\&.h\&.
.SS "\fBint64_t\fP CAddress::nLastTry"

.PP
Definition at line 109 of file protocol\&.h\&.
.SS "\fBuint64_t\fP CAddress::nServices"

.PP
Definition at line 103 of file protocol\&.h\&.
.SS "unsigned int CAddress::nTime"

.PP
Definition at line 106 of file protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
