.TH "CAddrMan" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAddrMan \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <addrman\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Stream > void \fBSerialize\fP (Stream &s, int nType, int nVersionDummy) const "
.br
.ti -1c
.RI "template<typename Stream > void \fBUnserialize\fP (Stream &s, int nType, int nVersionDummy)"
.br
.ti -1c
.RI "unsigned int \fBGetSerializeSize\fP (int nType, int nVersion) const "
.br
.ti -1c
.RI "\fBCAddrMan\fP ()"
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.ti -1c
.RI "void \fBCheck\fP ()"
.br
.ti -1c
.RI "bool \fBAdd\fP (const \fBCAddress\fP &addr, const \fBCNetAddr\fP &\fBsource\fP, \fBint64_t\fP nTimePenalty=0)"
.br
.ti -1c
.RI "bool \fBAdd\fP (const std::vector< \fBCAddress\fP > &vAddr, const \fBCNetAddr\fP &\fBsource\fP, \fBint64_t\fP nTimePenalty=0)"
.br
.ti -1c
.RI "void \fBGood\fP (const \fBCService\fP &addr, \fBint64_t\fP nTime=\fBGetAdjustedTime\fP())"
.br
.ti -1c
.RI "void \fBAttempt\fP (const \fBCService\fP &addr, \fBint64_t\fP nTime=\fBGetAdjustedTime\fP())"
.br
.ti -1c
.RI "\fBCAddress\fP \fBSelect\fP (int nUnkBias=50)"
.br
.ti -1c
.RI "std::vector< \fBCAddress\fP > \fBGetAddr\fP ()"
.br
.ti -1c
.RI "void \fBConnected\fP (const \fBCService\fP &addr, \fBint64_t\fP nTime=\fBGetAdjustedTime\fP())"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBCAddrInfo\fP * \fBFind\fP (const \fBCNetAddr\fP &addr, int *pnId=NULL)"
.br
.ti -1c
.RI "\fBCAddrInfo\fP * \fBCreate\fP (const \fBCAddress\fP &addr, const \fBCNetAddr\fP &addrSource, int *pnId=NULL)"
.br
.ti -1c
.RI "void \fBSwapRandom\fP (unsigned int nRandomPos1, unsigned int nRandomPos2)"
.br
.ti -1c
.RI "int \fBSelectTried\fP (int nKBucket)"
.br
.ti -1c
.RI "int \fBShrinkNew\fP (int nUBucket)"
.br
.ti -1c
.RI "void \fBMakeTried\fP (\fBCAddrInfo\fP &info, int nId, int nOrigin)"
.br
.ti -1c
.RI "void \fBGood_\fP (const \fBCService\fP &addr, \fBint64_t\fP nTime)"
.br
.ti -1c
.RI "bool \fBAdd_\fP (const \fBCAddress\fP &addr, const \fBCNetAddr\fP &\fBsource\fP, \fBint64_t\fP nTimePenalty)"
.br
.ti -1c
.RI "void \fBAttempt_\fP (const \fBCService\fP &addr, \fBint64_t\fP nTime)"
.br
.ti -1c
.RI "\fBCAddress\fP \fBSelect_\fP (int nUnkBias)"
.br
.ti -1c
.RI "void \fBGetAddr_\fP (std::vector< \fBCAddress\fP > &vAddr)"
.br
.ti -1c
.RI "void \fBConnected_\fP (const \fBCService\fP &addr, \fBint64_t\fP nTime)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stochastical (IP) address manager 
.PP
Definition at line 165 of file addrman\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CAddrMan::CAddrMan ()\fC [inline]\fP"

.PP
Definition at line 384 of file addrman\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CAddrMan::Add (const \fBCAddress\fP & addr, const \fBCNetAddr\fP & source, \fBint64_t\fP nTimePenalty = \fC0\fP)\fC [inline]\fP"

.PP
Definition at line 414 of file addrman\&.h\&.
.SS "bool CAddrMan::Add (const std::vector< \fBCAddress\fP > & vAddr, const \fBCNetAddr\fP & source, \fBint64_t\fP nTimePenalty = \fC0\fP)\fC [inline]\fP"

.PP
Definition at line 429 of file addrman\&.h\&.
.SS "bool CAddrMan::Add_ (const \fBCAddress\fP & addr, const \fBCNetAddr\fP & source, \fBint64_t\fP nTimePenalty)\fC [protected]\fP"

.PP
Definition at line 311 of file addrman\&.cpp\&.
.SS "void CAddrMan::Attempt (const \fBCService\fP & addr, \fBint64_t\fP nTime = \fC\fBGetAdjustedTime\fP()\fP)\fC [inline]\fP"

.PP
Definition at line 456 of file addrman\&.h\&.
.SS "void CAddrMan::Attempt_ (const \fBCService\fP & addr, \fBint64_t\fP nTime)\fC [protected]\fP"

.PP
Definition at line 368 of file addrman\&.cpp\&.
.SS "void CAddrMan::Check ()\fC [inline]\fP"

.PP
Definition at line 401 of file addrman\&.h\&.
.SS "void CAddrMan::Connected (const \fBCService\fP & addr, \fBint64_t\fP nTime = \fC\fBGetAdjustedTime\fP()\fP)\fC [inline]\fP"

.PP
Definition at line 494 of file addrman\&.h\&.
.SS "void CAddrMan::Connected_ (const \fBCService\fP & addr, \fBint64_t\fP nTime)\fC [protected]\fP"

.PP
Definition at line 513 of file addrman\&.cpp\&.
.SS "\fBCAddrInfo\fP * CAddrMan::Create (const \fBCAddress\fP & addr, const \fBCNetAddr\fP & addrSource, int * pnId = \fCNULL\fP)\fC [protected]\fP"

.PP
Definition at line 94 of file addrman\&.cpp\&.
.SS "\fBCAddrInfo\fP * CAddrMan::Find (const \fBCNetAddr\fP & addr, int * pnId = \fCNULL\fP)\fC [protected]\fP"

.PP
Definition at line 81 of file addrman\&.cpp\&.
.SS "std::vector<\fBCAddress\fP> CAddrMan::GetAddr ()\fC [inline]\fP"

.PP
Definition at line 481 of file addrman\&.h\&.
.SS "void CAddrMan::GetAddr_ (std::vector< \fBCAddress\fP > & vAddr)\fC [protected]\fP"

.PP
Definition at line 491 of file addrman\&.cpp\&.
.SS "unsigned int CAddrMan::GetSerializeSize (int nType, int nVersion) const\fC [inline]\fP"

.PP
Definition at line 379 of file addrman\&.h\&.
.SS "void CAddrMan::Good (const \fBCService\fP & addr, \fBint64_t\fP nTime = \fC\fBGetAdjustedTime\fP()\fP)\fC [inline]\fP"

.PP
Definition at line 445 of file addrman\&.h\&.
.SS "void CAddrMan::Good_ (const \fBCService\fP & addr, \fBint64_t\fP nTime)\fC [protected]\fP"

.PP
Definition at line 262 of file addrman\&.cpp\&.
.SS "void CAddrMan::MakeTried (\fBCAddrInfo\fP & info, int nId, int nOrigin)\fC [protected]\fP"

.PP
Definition at line 204 of file addrman\&.cpp\&.
.SS "\fBCAddress\fP CAddrMan::Select (int nUnkBias = \fC50\fP)\fC [inline]\fP"

.PP
Definition at line 468 of file addrman\&.h\&.
.SS "\fBCAddress\fP CAddrMan::Select_ (int nUnkBias)\fC [protected]\fP"

.PP
Definition at line 387 of file addrman\&.cpp\&.
.SS "int CAddrMan::SelectTried (int nKBucket)\fC [protected]\fP"

.PP
Definition at line 126 of file addrman\&.cpp\&.
.SS "template<typename Stream > void CAddrMan::Serialize (Stream & s, int nType, int nVersionDummy) const\fC [inline]\fP"

.PP
Definition at line 271 of file addrman\&.h\&.
.SS "int CAddrMan::ShrinkNew (int nUBucket)\fC [protected]\fP"

.PP
Definition at line 150 of file addrman\&.cpp\&.
.SS "int CAddrMan::size ()\fC [inline]\fP"

.PP
Definition at line 395 of file addrman\&.h\&.
.SS "void CAddrMan::SwapRandom (unsigned int nRandomPos1, unsigned int nRandomPos2)\fC [protected]\fP"

.PP
Definition at line 106 of file addrman\&.cpp\&.
.SS "template<typename Stream > void CAddrMan::Unserialize (Stream & s, int nType, int nVersionDummy)\fC [inline]\fP"

.PP
Definition at line 315 of file addrman\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
