.TH "CAffectedKeysVisitor" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAffectedKeysVisitor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< void >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCAffectedKeysVisitor\fP (const \fBCKeyStore\fP &keystoreIn, std::vector< \fBCKeyID\fP > &vKeysIn)"
.br
.ti -1c
.RI "void \fBProcess\fP (const \fBCScript\fP &script)"
.br
.ti -1c
.RI "void \fBoperator()\fP (const \fBCKeyID\fP &keyId)"
.br
.ti -1c
.RI "void \fBoperator()\fP (const \fBCScriptID\fP &scriptId)"
.br
.ti -1c
.RI "void \fBoperator()\fP (const \fBCStealthAddress\fP &stxAddr)"
.br
.ti -1c
.RI "void \fBoperator()\fP (const \fBCNoDestination\fP &none)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2696 of file script\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CAffectedKeysVisitor::CAffectedKeysVisitor (const \fBCKeyStore\fP & keystoreIn, std::vector< \fBCKeyID\fP > & vKeysIn)\fC [inline]\fP"

.PP
Definition at line 2702 of file script\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void CAffectedKeysVisitor::operator() (const \fBCKeyID\fP & keyId)\fC [inline]\fP"

.PP
Definition at line 2714 of file script\&.cpp\&.
.SS "void CAffectedKeysVisitor::operator() (const \fBCScriptID\fP & scriptId)\fC [inline]\fP"

.PP
Definition at line 2719 of file script\&.cpp\&.
.SS "void CAffectedKeysVisitor::operator() (const \fBCStealthAddress\fP & stxAddr)\fC [inline]\fP"

.PP
Definition at line 2725 of file script\&.cpp\&.
.SS "void CAffectedKeysVisitor::operator() (const \fBCNoDestination\fP & none)\fC [inline]\fP"

.PP
Definition at line 2730 of file script\&.cpp\&.
.SS "void CAffectedKeysVisitor::Process (const \fBCScript\fP & script)\fC [inline]\fP"

.PP
Definition at line 2704 of file script\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
