.TH "CAlert" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAlert \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <alert\&.h>\fP
.PP
Inherits \fBCUnsignedAlert\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCAlert\fP ()"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int \fBnVersion\fP)"
.br
.ti -1c
.RI "void \fBSetNull\fP ()"
.br
.ti -1c
.RI "bool \fBIsNull\fP () const "
.br
.ti -1c
.RI "\fBuint256\fP \fBGetHash\fP () const "
.br
.ti -1c
.RI "bool \fBIsInEffect\fP () const "
.br
.ti -1c
.RI "bool \fBCancels\fP (const \fBCAlert\fP &alert) const "
.br
.ti -1c
.RI "bool \fBAppliesTo\fP (int \fBnVersion\fP, std::string strSubVerIn) const "
.br
.ti -1c
.RI "bool \fBAppliesToMe\fP () const "
.br
.ti -1c
.RI "bool \fBRelayTo\fP (\fBCNode\fP *pnode) const "
.br
.ti -1c
.RI "bool \fBCheckSignature\fP () const "
.br
.ti -1c
.RI "bool \fBProcessAlert\fP (bool fThread=true)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCAlert\fP \fBgetAlertByHash\fP (const \fBuint256\fP &\fBhash\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< unsigned char > \fBvchMsg\fP"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBvchSig\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An alert is a combination of a serialized \fBCUnsignedAlert\fP and a signature\&. 
.PP
Definition at line 78 of file alert\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CAlert::CAlert ()\fC [inline]\fP"

.PP
Definition at line 84 of file alert\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CAlert::AppliesTo (int nVersion, std::string strSubVerIn) const"

.PP
Definition at line 116 of file alert\&.cpp\&.
.SS "bool CAlert::AppliesToMe () const"

.PP
Definition at line 124 of file alert\&.cpp\&.
.SS "bool CAlert::Cancels (const \fBCAlert\fP & alert) const"

.PP
Definition at line 109 of file alert\&.cpp\&.
.SS "bool CAlert::CheckSignature () const"

.PP
Definition at line 150 of file alert\&.cpp\&.
.SS "\fBCAlert\fP CAlert::getAlertByHash (const \fBuint256\fP & hash)\fC [static]\fP"

.PP
Definition at line 162 of file alert\&.cpp\&.
.SS "\fBuint256\fP CAlert::GetHash () const"

.PP
Definition at line 99 of file alert\&.cpp\&.
.SS "bool CAlert::IsInEffect () const"

.PP
Definition at line 104 of file alert\&.cpp\&.
.SS "bool CAlert::IsNull () const"

.PP
Definition at line 94 of file alert\&.cpp\&.
.SS "bool CAlert::ProcessAlert (bool fThread = \fCtrue\fP)"

.PP
Definition at line 174 of file alert\&.cpp\&.
.SS "bool CAlert::RelayTo (\fBCNode\fP * pnode) const"

.PP
Definition at line 129 of file alert\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CAlert::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 92 of file alert\&.h\&.
.SS "void CAlert::SetNull ()"

.PP
Definition at line 87 of file alert\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "CAlert::ADD_SERIALIZE_METHODS"

.PP
Definition at line 89 of file alert\&.h\&.
.SS "std::vector<unsigned char> CAlert::vchMsg"

.PP
Definition at line 81 of file alert\&.h\&.
.SS "std::vector<unsigned char> CAlert::vchSig"

.PP
Definition at line 82 of file alert\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
