.TH "CAutoBN_CTX" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAutoBN_CTX \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bignum\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCAutoBN_CTX\fP ()"
.br
.ti -1c
.RI "\fB~CAutoBN_CTX\fP ()"
.br
.ti -1c
.RI "\fBoperator BN_CTX *\fP ()"
.br
.ti -1c
.RI "BN_CTX & \fBoperator*\fP ()"
.br
.ti -1c
.RI "BN_CTX ** \fBoperator&\fP ()"
.br
.ti -1c
.RI "bool \fBoperator!\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "BN_CTX * \fBoperator=\fP (BN_CTX *pnew)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "BN_CTX * \fBpctx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
RAII encapsulated BN_CTX (OpenSSL bignum context) 
.PP
Definition at line 29 of file bignum\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CAutoBN_CTX::CAutoBN_CTX ()\fC [inline]\fP"

.PP
Definition at line 36 of file bignum\&.h\&.
.SS "CAutoBN_CTX::~CAutoBN_CTX ()\fC [inline]\fP"

.PP
Definition at line 43 of file bignum\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "CAutoBN_CTX::operator BN_CTX * ()\fC [inline]\fP"

.PP
Definition at line 49 of file bignum\&.h\&.
.SS "bool CAutoBN_CTX::operator! ()\fC [inline]\fP"

.PP
Definition at line 52 of file bignum\&.h\&.
.SS "BN_CTX** CAutoBN_CTX::operator& ()\fC [inline]\fP"

.PP
Definition at line 51 of file bignum\&.h\&.
.SS "BN_CTX& CAutoBN_CTX::operator* ()\fC [inline]\fP"

.PP
Definition at line 50 of file bignum\&.h\&.
.SS "BN_CTX* CAutoBN_CTX::operator= (BN_CTX * pnew)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 33 of file bignum\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "BN_CTX* CAutoBN_CTX::pctx\fC [protected]\fP"

.PP
Definition at line 32 of file bignum\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
