.TH "CBasicKeyStore" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CBasicKeyStore \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <keystore\&.h>\fP
.PP
Inherits \fBCKeyStore\fP\&.
.PP
Inherited by \fBCCryptoKeyStore\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBAddKeyPubKey\fP (const \fBCKey\fP &key, const \fBCPubKey\fP &pubkey)"
.br
.ti -1c
.RI "bool \fBHaveKey\fP (const \fBCKeyID\fP &address) const "
.br
.ti -1c
.RI "void \fBGetKeys\fP (std::set< \fBCKeyID\fP > &setAddress) const "
.br
.ti -1c
.RI "bool \fBGetKey\fP (const \fBCKeyID\fP &address, \fBCKey\fP &keyOut) const "
.br
.ti -1c
.RI "virtual bool \fBAddCScript\fP (const \fBCScript\fP &redeemScript)"
.br
.ti -1c
.RI "virtual bool \fBHaveCScript\fP (const \fBCScriptID\fP &\fBhash\fP) const "
.br
.ti -1c
.RI "virtual bool \fBGetCScript\fP (const \fBCScriptID\fP &\fBhash\fP, \fBCScript\fP &redeemScriptOut) const "
.br
.ti -1c
.RI "virtual bool \fBAddWatchOnly\fP (const \fBCScript\fP &dest)"
.br
.ti -1c
.RI "virtual bool \fBRemoveWatchOnly\fP (const \fBCScript\fP &dest)"
.br
.ti -1c
.RI "virtual bool \fBHaveWatchOnly\fP (const \fBCScript\fP &dest) const "
.br
.ti -1c
.RI "virtual bool \fBHaveWatchOnly\fP () const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBKeyMap\fP \fBmapKeys\fP"
.br
.ti -1c
.RI "\fBScriptMap\fP \fBmapScripts\fP"
.br
.ti -1c
.RI "\fBWatchOnlySet\fP \fBsetWatchOnly\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Basic key store, that keeps keys in an address->secret map 
.PP
Definition at line 60 of file keystore\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CBasicKeyStore::AddCScript (const \fBCScript\fP & redeemScript)\fC [virtual]\fP"

.PP
Implements \fBCKeyStore\fP\&.
.PP
Reimplemented in \fBCWallet\fP\&.
.PP
Definition at line 29 of file keystore\&.cpp\&.
.SS "bool CBasicKeyStore::AddKeyPubKey (const \fBCKey\fP & key, const \fBCPubKey\fP & pubkey)\fC [virtual]\fP"

.PP
Implements \fBCKeyStore\fP\&.
.PP
Reimplemented in \fBCWallet\fP\&.
.PP
Definition at line 22 of file keystore\&.cpp\&.
.SS "bool CBasicKeyStore::AddWatchOnly (const \fBCScript\fP & dest)\fC [virtual]\fP"

.PP
Implements \fBCKeyStore\fP\&.
.PP
Reimplemented in \fBCWallet\fP\&.
.PP
Definition at line 57 of file keystore\&.cpp\&.
.SS "bool CBasicKeyStore::GetCScript (const \fBCScriptID\fP & hash, \fBCScript\fP & redeemScriptOut) const\fC [virtual]\fP"

.PP
Implements \fBCKeyStore\fP\&.
.PP
Definition at line 45 of file keystore\&.cpp\&.
.SS "bool CBasicKeyStore::GetKey (const \fBCKeyID\fP & address, \fBCKey\fP & keyOut) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBCKeyStore\fP\&.
.PP
Definition at line 91 of file keystore\&.h\&.
.SS "void CBasicKeyStore::GetKeys (std::set< \fBCKeyID\fP > & setAddress) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBCKeyStore\fP\&.
.PP
Definition at line 78 of file keystore\&.h\&.
.SS "bool CBasicKeyStore::HaveCScript (const \fBCScriptID\fP & hash) const\fC [virtual]\fP"

.PP
Implements \fBCKeyStore\fP\&.
.PP
Definition at line 39 of file keystore\&.cpp\&.
.SS "bool CBasicKeyStore::HaveKey (const \fBCKeyID\fP & address) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBCKeyStore\fP\&.
.PP
Definition at line 69 of file keystore\&.h\&.
.SS "bool CBasicKeyStore::HaveWatchOnly (const \fBCScript\fP & dest) const\fC [virtual]\fP"

.PP
Implements \fBCKeyStore\fP\&.
.PP
Definition at line 71 of file keystore\&.cpp\&.
.SS "bool CBasicKeyStore::HaveWatchOnly () const\fC [virtual]\fP"

.PP
Implements \fBCKeyStore\fP\&.
.PP
Definition at line 77 of file keystore\&.cpp\&.
.SS "bool CBasicKeyStore::RemoveWatchOnly (const \fBCScript\fP & dest)\fC [virtual]\fP"

.PP
Implements \fBCKeyStore\fP\&.
.PP
Reimplemented in \fBCWallet\fP\&.
.PP
Definition at line 64 of file keystore\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBKeyMap\fP CBasicKeyStore::mapKeys\fC [protected]\fP"

.PP
Definition at line 63 of file keystore\&.h\&.
.SS "\fBScriptMap\fP CBasicKeyStore::mapScripts\fC [protected]\fP"

.PP
Definition at line 64 of file keystore\&.h\&.
.SS "\fBWatchOnlySet\fP CBasicKeyStore::setWatchOnly\fC [protected]\fP"

.PP
Definition at line 65 of file keystore\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
