.TH "CBlock" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CBlock \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <block\&.h>\fP
.PP
Inherits \fBCBlockHeader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCBlock\fP ()"
.br
.ti -1c
.RI "\fBCBlock\fP (const \fBCBlockHeader\fP &header)"
.br
.ti -1c
.RI "void \fBSetNull\fP ()"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int \fBnVersion\fP)"
.br
.ti -1c
.RI "void \fBUpdateTime\fP (const \fBCBlockIndex\fP *pindexPrev)"
.br
.ti -1c
.RI "unsigned int \fBGetStakeEntropyBit\fP () const "
.br
.ti -1c
.RI "bool \fBIsProofOfStake\fP () const "
.br
.ti -1c
.RI "bool \fBIsProofOfWork\fP () const "
.br
.ti -1c
.RI "std::pair< \fBCOutPoint\fP, unsigned int > \fBGetProofOfStake\fP () const "
.br
.ti -1c
.RI "\fBint64_t\fP \fBGetMaxTransactionTime\fP () const "
.br
.ti -1c
.RI "\fBuint256\fP \fBBuildMerkleTree\fP () const "
.br
.ti -1c
.RI "std::vector< \fBuint256\fP > \fBGetMerkleBranch\fP (int nIndex) const "
.br
.ti -1c
.RI "bool \fBWriteToDisk\fP (unsigned int &nFileRet, unsigned int &nBlockPosRet)"
.br
.ti -1c
.RI "bool \fBReadFromDisk\fP (unsigned int nFile, unsigned int nBlockPos, bool fReadTransactions=true)"
.br
.ti -1c
.RI "std::string \fBToString\fP () const "
.br
.ti -1c
.RI "bool \fBDisconnectBlock\fP (\fBCTxDB\fP &\fBtxdb\fP, \fBCBlockIndex\fP *pindex)"
.br
.ti -1c
.RI "bool \fBConnectBlock\fP (\fBCTxDB\fP &\fBtxdb\fP, \fBCBlockIndex\fP *pindex, bool fJustCheck=false)"
.br
.ti -1c
.RI "bool \fBReadFromDisk\fP (const \fBCBlockIndex\fP *pindex, bool fReadTransactions=true)"
.br
.ti -1c
.RI "bool \fBSetBestChain\fP (\fBCTxDB\fP &\fBtxdb\fP, \fBCBlockIndex\fP *pindexNew)"
.br
.ti -1c
.RI "bool \fBAddToBlockIndex\fP (unsigned int nFile, unsigned int nBlockPos, const \fBuint256\fP &hashProof)"
.br
.ti -1c
.RI "bool \fBCheckBlock\fP (\fBCValidationState\fP &\fBstate\fP, bool fCheckPOW=true, bool fCheckMerkleRoot=true, bool fCheckSig=true)"
.br
.ti -1c
.RI "bool \fBAcceptBlock\fP ()"
.br
.ti -1c
.RI "bool \fBSignBlock\fP (\fBCWallet\fP &keystore, \fBCAmount\fP nFees)"
.br
.ti -1c
.RI "bool \fBCheckBlockSignature\fP () const "
.br
.ti -1c
.RI "void \fBRebuildAddressIndex\fP (\fBCTxDB\fP &\fBtxdb\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBuint256\fP \fBCheckMerkleBranch\fP (\fBuint256\fP \fBhash\fP, const std::vector< \fBuint256\fP > &vMerkleBranch, int nIndex)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBCTransaction\fP > \fBvtx\fP"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBvchBlockSig\fP"
.br
.ti -1c
.RI "\fBCScript\fP \fBpayee\fP"
.br
.ti -1c
.RI "std::vector< \fBuint256\fP > \fBvMerkleTree\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 103 of file block\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CBlock::CBlock ()\fC [inline]\fP"

.PP
Definition at line 116 of file block\&.h\&.
.SS "CBlock::CBlock (const \fBCBlockHeader\fP & header)\fC [inline]\fP"

.PP
Definition at line 121 of file block\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CBlock::AcceptBlock ()"

.PP
Definition at line 92 of file chain\&.cpp\&.
.SS "bool CBlock::AddToBlockIndex (unsigned int nFile, unsigned int nBlockPos, const \fBuint256\fP & hashProof)"

.PP
Definition at line 4244 of file main\&.cpp\&.
.SS "\fBuint256\fP CBlock::BuildMerkleTree () const\fC [inline]\fP"

.PP
Definition at line 196 of file block\&.h\&.
.SS "bool CBlock::CheckBlock (\fBCValidationState\fP & state, bool fCheckPOW = \fCtrue\fP, bool fCheckMerkleRoot = \fCtrue\fP, bool fCheckSig = \fCtrue\fP)"

.PP
Definition at line 678 of file chain\&.cpp\&.
.SS "bool CBlock::CheckBlockSignature () const"

.PP
Definition at line 10 of file block\&.cpp\&.
.SS "static \fBuint256\fP CBlock::CheckMerkleBranch (\fBuint256\fP hash, const std::vector< \fBuint256\fP > & vMerkleBranch, int nIndex)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 231 of file block\&.h\&.
.SS "bool CBlock::ConnectBlock (\fBCTxDB\fP & txdb, \fBCBlockIndex\fP * pindex, bool fJustCheck = \fCfalse\fP)"

.PP
Definition at line 299 of file chain\&.cpp\&.
.SS "bool CBlock::DisconnectBlock (\fBCTxDB\fP & txdb, \fBCBlockIndex\fP * pindex)"

.PP
Definition at line 191 of file chain\&.cpp\&.
.SS "\fBint64_t\fP CBlock::GetMaxTransactionTime () const\fC [inline]\fP"

.PP
Definition at line 188 of file block\&.h\&.
.SS "std::vector<\fBuint256\fP> CBlock::GetMerkleBranch (int nIndex) const\fC [inline]\fP"

.PP
Definition at line 215 of file block\&.h\&.
.SS "std::pair<\fBCOutPoint\fP, unsigned int> CBlock::GetProofOfStake () const\fC [inline]\fP"

.PP
Definition at line 182 of file block\&.h\&.
.SS "unsigned int CBlock::GetStakeEntropyBit () const\fC [inline]\fP"

.PP
Definition at line 163 of file block\&.h\&.
.SS "bool CBlock::IsProofOfStake () const\fC [inline]\fP"

.PP
Definition at line 172 of file block\&.h\&.
.SS "bool CBlock::IsProofOfWork () const\fC [inline]\fP"

.PP
Definition at line 177 of file block\&.h\&.
.SS "bool CBlock::ReadFromDisk (unsigned int nFile, unsigned int nBlockPos, bool fReadTransactions = \fCtrue\fP)"

.PP
Definition at line 856 of file chain\&.cpp\&.
.SS "bool CBlock::ReadFromDisk (const \fBCBlockIndex\fP * pindex, bool fReadTransactions = \fCtrue\fP)"

.PP
Definition at line 816 of file chain\&.cpp\&.
.SS "void CBlock::RebuildAddressIndex (\fBCTxDB\fP & txdb)"

.PP
Definition at line 250 of file chain\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CBlock::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 145 of file block\&.h\&.
.SS "bool CBlock::SetBestChain (\fBCTxDB\fP & txdb, \fBCBlockIndex\fP * pindexNew)"

.PP
Definition at line 4125 of file main\&.cpp\&.
.SS "void CBlock::SetNull ()\fC [inline]\fP"

.PP
Definition at line 127 of file block\&.h\&.
.SS "bool CBlock::SignBlock (\fBCWallet\fP & keystore, \fBCAmount\fP nFees)"

.SS "std::string CBlock::ToString () const"

.PP
Definition at line 73 of file block\&.cpp\&.
.SS "void CBlock::UpdateTime (const \fBCBlockIndex\fP * pindexPrev)"

.PP
Definition at line 52 of file block\&.cpp\&.
.SS "bool CBlock::WriteToDisk (unsigned int & nFileRet, unsigned int & nBlockPosRet)"

.PP
Definition at line 830 of file chain\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "CBlock::ADD_SERIALIZE_METHODS"

.PP
Definition at line 142 of file block\&.h\&.
.SS "\fBCScript\fP CBlock::payee\fC [mutable]\fP"

.PP
Definition at line 113 of file block\&.h\&.
.SS "std::vector<unsigned char> CBlock::vchBlockSig"

.PP
Definition at line 110 of file block\&.h\&.
.SS "std::vector<\fBuint256\fP> CBlock::vMerkleTree\fC [mutable]\fP"

.PP
Definition at line 114 of file block\&.h\&.
.SS "std::vector<\fBCTransaction\fP> CBlock::vtx"

.PP
Definition at line 107 of file block\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
