.TH "CBudgetManager" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CBudgetManager \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stormnode-budget\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCBudgetManager\fP ()"
.br
.ti -1c
.RI "void \fBClearSeen\fP ()"
.br
.ti -1c
.RI "int \fBsizeFinalized\fP ()"
.br
.ti -1c
.RI "int \fBsizeProposals\fP ()"
.br
.ti -1c
.RI "void \fBResetSync\fP ()"
.br
.ti -1c
.RI "void \fBMarkSynced\fP ()"
.br
.ti -1c
.RI "void \fBSync\fP (\fBCNode\fP *node, \fBuint256\fP nProp, bool fPartial=false)"
.br
.ti -1c
.RI "void \fBProcessMessage\fP (\fBCNode\fP *pfrom, std::string &strCommand, \fBCDataStream\fP &vRecv)"
.br
.ti -1c
.RI "void \fBNewBlock\fP ()"
.br
.ti -1c
.RI "\fBCBudgetProposal\fP * \fBFindProposal\fP (const std::string &strProposalName)"
.br
.ti -1c
.RI "\fBCBudgetProposal\fP * \fBFindProposal\fP (\fBuint256\fP nHash)"
.br
.ti -1c
.RI "\fBCFinalizedBudget\fP * \fBFindFinalizedBudget\fP (\fBuint256\fP nHash)"
.br
.ti -1c
.RI "std::pair< std::string, std::string > \fBGetVotes\fP (std::string strProposalName)"
.br
.ti -1c
.RI "\fBCAmount\fP \fBGetTotalBudget\fP (int nHeight)"
.br
.ti -1c
.RI "std::vector< \fBCBudgetProposal\fP * > \fBGetBudget\fP ()"
.br
.ti -1c
.RI "std::vector< \fBCBudgetProposal\fP * > \fBGetAllProposals\fP ()"
.br
.ti -1c
.RI "std::vector< \fBCFinalizedBudget\fP * > \fBGetFinalizedBudgets\fP ()"
.br
.ti -1c
.RI "bool \fBIsBudgetPaymentBlock\fP (int nBlockHeight)"
.br
.ti -1c
.RI "bool \fBAddProposal\fP (\fBCBudgetProposal\fP &budgetProposal)"
.br
.ti -1c
.RI "bool \fBAddFinalizedBudget\fP (\fBCFinalizedBudget\fP &finalizedBudget)"
.br
.ti -1c
.RI "void \fBSubmitFinalBudget\fP ()"
.br
.ti -1c
.RI "bool \fBHasNextFinalizedBudget\fP ()"
.br
.ti -1c
.RI "bool \fBUpdateProposal\fP (\fBCBudgetVote\fP &vote, \fBCNode\fP *pfrom, std::string &strError)"
.br
.ti -1c
.RI "bool \fBUpdateFinalizedBudget\fP (\fBCFinalizedBudgetVote\fP &vote, \fBCNode\fP *pfrom, std::string &strError)"
.br
.ti -1c
.RI "bool \fBPropExists\fP (\fBuint256\fP nHash)"
.br
.ti -1c
.RI "bool \fBIsTransactionValid\fP (const \fBCTransaction\fP &txNew, int nBlockHeight)"
.br
.ti -1c
.RI "std::string \fBGetRequiredPaymentsString\fP (int nBlockHeight)"
.br
.ti -1c
.RI "void \fBFillBlockPayee\fP (\fBCTransaction\fP &txNew, \fBCAmount\fP nFees)"
.br
.ti -1c
.RI "void \fBCheckOrphanVotes\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBCheckAndRemove\fP ()"
.br
.ti -1c
.RI "std::string \fBToString\fP () const "
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs\fP"
.br
.ti -1c
.RI "map< \fBuint256\fP, \fBCBudgetProposal\fP > \fBmapProposals\fP"
.br
.ti -1c
.RI "map< \fBuint256\fP, \fBCFinalizedBudget\fP > \fBmapFinalizedBudgets\fP"
.br
.ti -1c
.RI "std::map< \fBuint256\fP, \fBCBudgetProposalBroadcast\fP > \fBmapSeenStormnodeBudgetProposals\fP"
.br
.ti -1c
.RI "std::map< \fBuint256\fP, \fBCBudgetVote\fP > \fBmapSeenStormnodeBudgetVotes\fP"
.br
.ti -1c
.RI "std::map< \fBuint256\fP, \fBCBudgetVote\fP > \fBmapOrphanStormnodeBudgetVotes\fP"
.br
.ti -1c
.RI "std::map< \fBuint256\fP, \fBCFinalizedBudgetBroadcast\fP > \fBmapSeenFinalizedBudgets\fP"
.br
.ti -1c
.RI "std::map< \fBuint256\fP, \fBCFinalizedBudgetVote\fP > \fBmapSeenFinalizedBudgetVotes\fP"
.br
.ti -1c
.RI "std::map< \fBuint256\fP, \fBCFinalizedBudgetVote\fP > \fBmapOrphanFinalizedBudgetVotes\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 78 of file stormnode-budget\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CBudgetManager::CBudgetManager ()\fC [inline]\fP"

.PP
Definition at line 100 of file stormnode-budget\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CBudgetManager::AddFinalizedBudget (\fBCFinalizedBudget\fP & finalizedBudget)"

.PP
Definition at line 364 of file stormnode-budget\&.cpp\&.
.SS "bool CBudgetManager::AddProposal (\fBCBudgetProposal\fP & budgetProposal)"

.PP
Definition at line 377 of file stormnode-budget\&.cpp\&.
.SS "void CBudgetManager::CheckAndRemove ()"

.PP
Definition at line 394 of file stormnode-budget\&.cpp\&.
.SS "void CBudgetManager::CheckOrphanVotes ()"

.PP
Definition at line 92 of file stormnode-budget\&.cpp\&.
.SS "void CBudgetManager::Clear ()\fC [inline]\fP"

.PP
Definition at line 145 of file stormnode-budget\&.h\&.
.SS "void CBudgetManager::ClearSeen ()\fC [inline]\fP"

.PP
Definition at line 105 of file stormnode-budget\&.h\&.
.SS "void CBudgetManager::FillBlockPayee (\fBCTransaction\fP & txNew, \fBCAmount\fP nFees)"

.PP
Definition at line 430 of file stormnode-budget\&.cpp\&.
.SS "\fBCFinalizedBudget\fP * CBudgetManager::FindFinalizedBudget (\fBuint256\fP nHash)"

.PP
Definition at line 493 of file stormnode-budget\&.cpp\&.
.SS "\fBCBudgetProposal\fP * CBudgetManager::FindProposal (const std::string & strProposalName)"

.PP
Definition at line 501 of file stormnode-budget\&.cpp\&.
.SS "\fBCBudgetProposal\fP * CBudgetManager::FindProposal (\fBuint256\fP nHash)"

.PP
Definition at line 522 of file stormnode-budget\&.cpp\&.
.SS "std::vector< \fBCBudgetProposal\fP * > CBudgetManager::GetAllProposals ()"

.PP
Definition at line 623 of file stormnode-budget\&.cpp\&.
.SS "std::vector< \fBCBudgetProposal\fP * > CBudgetManager::GetBudget ()"

.PP
Definition at line 655 of file stormnode-budget\&.cpp\&.
.SS "std::vector< \fBCFinalizedBudget\fP * > CBudgetManager::GetFinalizedBudgets ()"

.PP
Definition at line 731 of file stormnode-budget\&.cpp\&.
.SS "std::string CBudgetManager::GetRequiredPaymentsString (int nBlockHeight)"

.PP
Definition at line 760 of file stormnode-budget\&.cpp\&.
.SS "\fBCAmount\fP CBudgetManager::GetTotalBudget (int nHeight)"

.PP
Definition at line 790 of file stormnode-budget\&.cpp\&.
.SS "std::pair<std::string, std::string> CBudgetManager::GetVotes (std::string strProposalName)"

.SS "bool CBudgetManager::HasNextFinalizedBudget ()"

.PP
Definition at line 557 of file stormnode-budget\&.cpp\&.
.SS "bool CBudgetManager::IsBudgetPaymentBlock (int nBlockHeight)"

.PP
Definition at line 532 of file stormnode-budget\&.cpp\&.
.SS "bool CBudgetManager::IsTransactionValid (const \fBCTransaction\fP & txNew, int nBlockHeight)"

.PP
Definition at line 574 of file stormnode-budget\&.cpp\&.
.SS "void CBudgetManager::MarkSynced ()"

.PP
Definition at line 1117 of file stormnode-budget\&.cpp\&.
.SS "void CBudgetManager::NewBlock ()"

.PP
Definition at line 799 of file stormnode-budget\&.cpp\&.
.SS "void CBudgetManager::ProcessMessage (\fBCNode\fP * pfrom, std::string & strCommand, \fBCDataStream\fP & vRecv)"

.PP
Definition at line 904 of file stormnode-budget\&.cpp\&.
.SS "bool CBudgetManager::PropExists (\fBuint256\fP nHash)"

.PP
Definition at line 1074 of file stormnode-budget\&.cpp\&.
.SS "void CBudgetManager::ResetSync ()"

.PP
Definition at line 1081 of file stormnode-budget\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CBudgetManager::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 165 of file stormnode-budget\&.h\&.
.SS "int CBudgetManager::sizeFinalized ()\fC [inline]\fP"

.PP
Definition at line 112 of file stormnode-budget\&.h\&.
.SS "int CBudgetManager::sizeProposals ()\fC [inline]\fP"

.PP
Definition at line 113 of file stormnode-budget\&.h\&.
.SS "void CBudgetManager::SubmitFinalBudget ()"

.PP
Definition at line 118 of file stormnode-budget\&.cpp\&.
.SS "void CBudgetManager::Sync (\fBCNode\fP * node, \fBuint256\fP nProp, bool fPartial = \fCfalse\fP)"

.PP
Definition at line 1160 of file stormnode-budget\&.cpp\&.
.SS "std::string CBudgetManager::ToString () const"

.PP
Definition at line 2048 of file stormnode-budget\&.cpp\&.
.SS "bool CBudgetManager::UpdateFinalizedBudget (\fBCFinalizedBudgetVote\fP & vote, \fBCNode\fP * pfrom, std::string & strError)"

.PP
Definition at line 1258 of file stormnode-budget\&.cpp\&.
.SS "bool CBudgetManager::UpdateProposal (\fBCBudgetVote\fP & vote, \fBCNode\fP * pfrom, std::string & strError)"

.PP
Definition at line 1231 of file stormnode-budget\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "CBudgetManager::ADD_SERIALIZE_METHODS"

.PP
Definition at line 162 of file stormnode-budget\&.h\&.
.SS "\fBCCriticalSection\fP CBudgetManager::cs\fC [mutable]\fP"

.PP
Definition at line 86 of file stormnode-budget\&.h\&.
.SS "map<\fBuint256\fP, \fBCFinalizedBudget\fP> CBudgetManager::mapFinalizedBudgets"

.PP
Definition at line 90 of file stormnode-budget\&.h\&.
.SS "std::map<\fBuint256\fP, \fBCFinalizedBudgetVote\fP> CBudgetManager::mapOrphanFinalizedBudgetVotes"

.PP
Definition at line 97 of file stormnode-budget\&.h\&.
.SS "std::map<\fBuint256\fP, \fBCBudgetVote\fP> CBudgetManager::mapOrphanStormnodeBudgetVotes"

.PP
Definition at line 94 of file stormnode-budget\&.h\&.
.SS "map<\fBuint256\fP, \fBCBudgetProposal\fP> CBudgetManager::mapProposals"

.PP
Definition at line 89 of file stormnode-budget\&.h\&.
.SS "std::map<\fBuint256\fP, \fBCFinalizedBudgetBroadcast\fP> CBudgetManager::mapSeenFinalizedBudgets"

.PP
Definition at line 95 of file stormnode-budget\&.h\&.
.SS "std::map<\fBuint256\fP, \fBCFinalizedBudgetVote\fP> CBudgetManager::mapSeenFinalizedBudgetVotes"

.PP
Definition at line 96 of file stormnode-budget\&.h\&.
.SS "std::map<\fBuint256\fP, \fBCBudgetProposalBroadcast\fP> CBudgetManager::mapSeenStormnodeBudgetProposals"

.PP
Definition at line 92 of file stormnode-budget\&.h\&.
.SS "std::map<\fBuint256\fP, \fBCBudgetVote\fP> CBudgetManager::mapSeenStormnodeBudgetVotes"

.PP
Definition at line 93 of file stormnode-budget\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
