.TH "CBudgetProposal" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CBudgetProposal \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stormnode-budget\&.h>\fP
.PP
Inherited by \fBCBudgetProposalBroadcast\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCBudgetProposal\fP ()"
.br
.ti -1c
.RI "\fBCBudgetProposal\fP (const \fBCBudgetProposal\fP &other)"
.br
.ti -1c
.RI "\fBCBudgetProposal\fP (std::string strProposalNameIn, std::string strURLIn, int nPaymentCount, \fBCScript\fP addressIn, \fBCAmount\fP nAmountIn, int nBlockStartIn, \fBuint256\fP nFeeTXHashIn)"
.br
.ti -1c
.RI "void \fBCalculate\fP ()"
.br
.ti -1c
.RI "bool \fBAddOrUpdateVote\fP (\fBCBudgetVote\fP &vote, std::string &strError)"
.br
.ti -1c
.RI "bool \fBHasMinimumRequiredSupport\fP ()"
.br
.ti -1c
.RI "std::pair< std::string, std::string > \fBGetVotes\fP ()"
.br
.ti -1c
.RI "bool \fBIsValid\fP (std::string &strError, bool fCheckCollateral=true)"
.br
.ti -1c
.RI "bool \fBIsEstablished\fP ()"
.br
.ti -1c
.RI "std::string \fBGetName\fP ()"
.br
.ti -1c
.RI "std::string \fBGetURL\fP ()"
.br
.ti -1c
.RI "int \fBGetBlockStart\fP ()"
.br
.ti -1c
.RI "int \fBGetBlockEnd\fP ()"
.br
.ti -1c
.RI "\fBCScript\fP \fBGetPayee\fP ()"
.br
.ti -1c
.RI "int \fBGetTotalPaymentCount\fP ()"
.br
.ti -1c
.RI "int \fBGetRemainingPaymentCount\fP ()"
.br
.ti -1c
.RI "int \fBGetBlockStartCycle\fP ()"
.br
.ti -1c
.RI "int \fBGetBlockCurrentCycle\fP ()"
.br
.ti -1c
.RI "int \fBGetBlockEndCycle\fP ()"
.br
.ti -1c
.RI "double \fBGetRatio\fP ()"
.br
.ti -1c
.RI "int \fBGetAbsoluteYesCount\fP ()"
.br
.ti -1c
.RI "int \fBGetYesCount\fP ()"
.br
.ti -1c
.RI "int \fBGetNoCount\fP ()"
.br
.ti -1c
.RI "int \fBGetAbstainCount\fP ()"
.br
.ti -1c
.RI "\fBCAmount\fP \fBGetAmount\fP ()"
.br
.ti -1c
.RI "void \fBSetAllotted\fP (\fBCAmount\fP nAllotedIn)"
.br
.ti -1c
.RI "\fBCAmount\fP \fBGetAllotted\fP ()"
.br
.ti -1c
.RI "void \fBCleanAndRemove\fP (bool fSignatureCheck)"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetHash\fP ()"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBfValid\fP"
.br
.ti -1c
.RI "std::string \fBstrProposalName\fP"
.br
.ti -1c
.RI "std::string \fBstrURL\fP"
.br
.ti -1c
.RI "int \fBnBlockStart\fP"
.br
.ti -1c
.RI "int \fBnBlockEnd\fP"
.br
.ti -1c
.RI "\fBCAmount\fP \fBnAmount\fP"
.br
.ti -1c
.RI "\fBCScript\fP \fBaddress\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnTime\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBnFeeTXHash\fP"
.br
.ti -1c
.RI "map< \fBuint256\fP, \fBCBudgetVote\fP > \fBmapVotes\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 385 of file stormnode-budget\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CBudgetProposal::CBudgetProposal ()"

.PP
Definition at line 1285 of file stormnode-budget\&.cpp\&.
.SS "CBudgetProposal::CBudgetProposal (const \fBCBudgetProposal\fP & other)"

.PP
Definition at line 1295 of file stormnode-budget\&.cpp\&.
.SS "CBudgetProposal::CBudgetProposal (std::string strProposalNameIn, std::string strURLIn, int nPaymentCount, \fBCScript\fP addressIn, \fBCAmount\fP nAmountIn, int nBlockStartIn, \fBuint256\fP nFeeTXHashIn)"

.PP
Definition at line 1309 of file stormnode-budget\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CBudgetProposal::AddOrUpdateVote (\fBCBudgetVote\fP & vote, std::string & strError)"

.PP
Definition at line 1422 of file stormnode-budget\&.cpp\&.
.SS "void CBudgetProposal::Calculate ()"

.SS "void CBudgetProposal::CleanAndRemove (bool fSignatureCheck)"

.PP
Definition at line 1452 of file stormnode-budget\&.cpp\&.
.SS "int CBudgetProposal::GetAbsoluteYesCount ()"

.PP
Definition at line 1480 of file stormnode-budget\&.cpp\&.
.SS "int CBudgetProposal::GetAbstainCount ()"

.PP
Definition at line 1511 of file stormnode-budget\&.cpp\&.
.SS "\fBCAmount\fP CBudgetProposal::GetAllotted ()\fC [inline]\fP"

.PP
Definition at line 449 of file stormnode-budget\&.h\&.
.SS "\fBCAmount\fP CBudgetProposal::GetAmount ()\fC [inline]\fP"

.PP
Definition at line 447 of file stormnode-budget\&.h\&.
.SS "int CBudgetProposal::GetBlockCurrentCycle ()"

.PP
Definition at line 1531 of file stormnode-budget\&.cpp\&.
.SS "int CBudgetProposal::GetBlockEnd ()\fC [inline]\fP"

.PP
Definition at line 435 of file stormnode-budget\&.h\&.
.SS "int CBudgetProposal::GetBlockEndCycle ()"

.PP
Definition at line 1541 of file stormnode-budget\&.cpp\&.
.SS "int CBudgetProposal::GetBlockStart ()\fC [inline]\fP"

.PP
Definition at line 434 of file stormnode-budget\&.h\&.
.SS "int CBudgetProposal::GetBlockStartCycle ()"

.PP
Definition at line 1524 of file stormnode-budget\&.cpp\&.
.SS "\fBuint256\fP CBudgetProposal::GetHash ()\fC [inline]\fP"

.PP
Definition at line 453 of file stormnode-budget\&.h\&.
.SS "std::string CBudgetProposal::GetName ()\fC [inline]\fP"

.PP
Definition at line 432 of file stormnode-budget\&.h\&.
.SS "int CBudgetProposal::GetNoCount ()"

.PP
Definition at line 1498 of file stormnode-budget\&.cpp\&.
.SS "\fBCScript\fP CBudgetProposal::GetPayee ()\fC [inline]\fP"

.PP
Definition at line 436 of file stormnode-budget\&.h\&.
.SS "double CBudgetProposal::GetRatio ()"

.PP
Definition at line 1462 of file stormnode-budget\&.cpp\&.
.SS "int CBudgetProposal::GetRemainingPaymentCount ()"

.PP
Definition at line 1553 of file stormnode-budget\&.cpp\&.
.SS "int CBudgetProposal::GetTotalPaymentCount ()"

.PP
Definition at line 1548 of file stormnode-budget\&.cpp\&.
.SS "std::string CBudgetProposal::GetURL ()\fC [inline]\fP"

.PP
Definition at line 433 of file stormnode-budget\&.h\&.
.SS "std::pair<std::string, std::string> CBudgetProposal::GetVotes ()"

.SS "int CBudgetProposal::GetYesCount ()"

.PP
Definition at line 1485 of file stormnode-budget\&.cpp\&.
.SS "bool CBudgetProposal::HasMinimumRequiredSupport ()"

.SS "bool CBudgetProposal::IsEstablished ()\fC [inline]\fP"

.PP
Definition at line 423 of file stormnode-budget\&.h\&.
.SS "bool CBudgetProposal::IsValid (std::string & strError, bool fCheckCollateral = \fCtrue\fP)"

.PP
Definition at line 1326 of file stormnode-budget\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CBudgetProposal::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 469 of file stormnode-budget\&.h\&.
.SS "void CBudgetProposal::SetAllotted (\fBCAmount\fP nAllotedIn)\fC [inline]\fP"

.PP
Definition at line 448 of file stormnode-budget\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CBudgetProposal::ADD_SERIALIZE_METHODS"

.PP
Definition at line 466 of file stormnode-budget\&.h\&.
.SS "\fBCScript\fP CBudgetProposal::address"

.PP
Definition at line 405 of file stormnode-budget\&.h\&.
.SS "bool CBudgetProposal::fValid"

.PP
Definition at line 394 of file stormnode-budget\&.h\&.
.SS "map<\fBuint256\fP, \fBCBudgetVote\fP> CBudgetProposal::mapVotes"

.PP
Definition at line 409 of file stormnode-budget\&.h\&.
.SS "\fBCAmount\fP CBudgetProposal::nAmount"

.PP
Definition at line 404 of file stormnode-budget\&.h\&.
.SS "int CBudgetProposal::nBlockEnd"

.PP
Definition at line 403 of file stormnode-budget\&.h\&.
.SS "int CBudgetProposal::nBlockStart"

.PP
Definition at line 402 of file stormnode-budget\&.h\&.
.SS "\fBuint256\fP CBudgetProposal::nFeeTXHash"

.PP
Definition at line 407 of file stormnode-budget\&.h\&.
.SS "\fBint64_t\fP CBudgetProposal::nTime"

.PP
Definition at line 406 of file stormnode-budget\&.h\&.
.SS "std::string CBudgetProposal::strProposalName"

.PP
Definition at line 395 of file stormnode-budget\&.h\&.
.SS "std::string CBudgetProposal::strURL"

.PP
Definition at line 401 of file stormnode-budget\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
