.TH "CBudgetProposalBroadcast" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CBudgetProposalBroadcast \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stormnode-budget\&.h>\fP
.PP
Inherits \fBCBudgetProposal\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCBudgetProposalBroadcast\fP ()"
.br
.ti -1c
.RI "\fBCBudgetProposalBroadcast\fP (const \fBCBudgetProposal\fP &other)"
.br
.ti -1c
.RI "\fBCBudgetProposalBroadcast\fP (const \fBCBudgetProposalBroadcast\fP &other)"
.br
.ti -1c
.RI "\fBCBudgetProposalBroadcast\fP (std::string strProposalNameIn, std::string strURLIn, int nPaymentCount, \fBCScript\fP addressIn, \fBCAmount\fP nAmountIn, int nBlockStartIn, \fBuint256\fP nFeeTXHashIn)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBCBudgetProposalBroadcast\fP &first, \fBCBudgetProposalBroadcast\fP &second)"
.br
.ti -1c
.RI "\fBCBudgetProposalBroadcast\fP & \fBoperator=\fP (\fBCBudgetProposalBroadcast\fP from)"
.br
.ti -1c
.RI "void \fBRelay\fP ()"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 487 of file stormnode-budget\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CBudgetProposalBroadcast::CBudgetProposalBroadcast ()\fC [inline]\fP"

.PP
Definition at line 490 of file stormnode-budget\&.h\&.
.SS "CBudgetProposalBroadcast::CBudgetProposalBroadcast (const \fBCBudgetProposal\fP & other)\fC [inline]\fP"

.PP
Definition at line 491 of file stormnode-budget\&.h\&.
.SS "CBudgetProposalBroadcast::CBudgetProposalBroadcast (const \fBCBudgetProposalBroadcast\fP & other)\fC [inline]\fP"

.PP
Definition at line 492 of file stormnode-budget\&.h\&.
.SS "CBudgetProposalBroadcast::CBudgetProposalBroadcast (std::string strProposalNameIn, std::string strURLIn, int nPaymentCount, \fBCScript\fP addressIn, \fBCAmount\fP nAmountIn, int nBlockStartIn, \fBuint256\fP nFeeTXHashIn)\fC [inline]\fP"

.PP
Definition at line 493 of file stormnode-budget\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCBudgetProposalBroadcast\fP& CBudgetProposalBroadcast::operator= (\fBCBudgetProposalBroadcast\fP from)\fC [inline]\fP"

.PP
Definition at line 513 of file stormnode-budget\&.h\&.
.SS "void CBudgetProposalBroadcast::Relay ()"

.PP
Definition at line 1569 of file stormnode-budget\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CBudgetProposalBroadcast::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 524 of file stormnode-budget\&.h\&.
.SS "void CBudgetProposalBroadcast::swap (\fBCBudgetProposalBroadcast\fP & first, \fBCBudgetProposalBroadcast\fP & second)\fC [inline]\fP"

.PP
Definition at line 495 of file stormnode-budget\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CBudgetProposalBroadcast::ADD_SERIALIZE_METHODS"

.PP
Definition at line 521 of file stormnode-budget\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
