.TH "CBudgetDB" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CBudgetDB \- Save Budget Manager (budget\&.dat)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stormnode-budget\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBReadResult\fP { \fBOk\fP, \fBFileError\fP, \fBHashReadError\fP, \fBIncorrectHash\fP, \fBIncorrectMagicMessage\fP, \fBIncorrectMagicNumber\fP, \fBIncorrectFormat\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCBudgetDB\fP ()"
.br
.ti -1c
.RI "bool \fBWrite\fP (const \fBCBudgetManager\fP &objToSave)"
.br
.ti -1c
.RI "\fBReadResult\fP \fBRead\fP (\fBCBudgetManager\fP &objToLoad, bool fDryRun=false)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Save Budget Manager (budget\&.dat) 
.PP
Definition at line 54 of file stormnode-budget\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBCBudgetDB::ReadResult\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOk \fP\fP
.TP
\fB\fIFileError \fP\fP
.TP
\fB\fIHashReadError \fP\fP
.TP
\fB\fIIncorrectHash \fP\fP
.TP
\fB\fIIncorrectMagicMessage \fP\fP
.TP
\fB\fIIncorrectMagicNumber \fP\fP
.TP
\fB\fIIncorrectFormat \fP\fP
.PP
Definition at line 60 of file stormnode-budget\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CBudgetDB::CBudgetDB ()"

.PP
Definition at line 204 of file stormnode-budget\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCBudgetDB::ReadResult\fP CBudgetDB::Read (\fBCBudgetManager\fP & objToLoad, bool fDryRun = \fCfalse\fP)"

.PP
Definition at line 245 of file stormnode-budget\&.cpp\&.
.SS "bool CBudgetDB::Write (const \fBCBudgetManager\fP & objToSave)"

.PP
Definition at line 210 of file stormnode-budget\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
