.TH "CChain" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CChain \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <chain\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCBlockIndex\fP * \fBGenesis\fP () const "
.br
.ti -1c
.RI "\fBCBlockIndex\fP * \fBTip\fP () const "
.br
.ti -1c
.RI "\fBCBlockIndex\fP * \fBoperator[]\fP (int nHeight) const "
.br
.ti -1c
.RI "bool \fBContains\fP (const \fBCBlockIndex\fP *pindex) const "
.br
.ti -1c
.RI "\fBCBlockIndex\fP * \fBNext\fP (const \fBCBlockIndex\fP *pindex) const "
.br
.ti -1c
.RI "int \fBHeight\fP () const "
.br
.ti -1c
.RI "void \fBSetTip\fP (\fBCBlockIndex\fP *pindex)"
.br
.RI "\fI\fBCChain\fP implementation\&. \fP"
.ti -1c
.RI "\fBCBlockLocator\fP \fBGetLocator\fP (const \fBCBlockIndex\fP *pindex=NULL) const "
.br
.ti -1c
.RI "const \fBCBlockIndex\fP * \fBFindFork\fP (const \fBCBlockIndex\fP *pindex) const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCChain\fP &a, const \fBCChain\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
An in-memory indexed chain of blocks\&. 
.PP
Definition at line 550 of file chain\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CChain::Contains (const \fBCBlockIndex\fP * pindex) const\fC [inline]\fP"
Efficiently check whether a block is present in this chain\&. 
.PP
Definition at line 579 of file chain\&.h\&.
.SS "const \fBCBlockIndex\fP* CChain::FindFork (const \fBCBlockIndex\fP * pindex) const"
Find the last common block between this chain and a block index entry\&. 
.SS "\fBCBlockIndex\fP* CChain::Genesis () const\fC [inline]\fP"
Returns the index entry for the genesis block of this chain, or NULL if none\&. 
.PP
Definition at line 556 of file chain\&.h\&.
.SS "\fBCBlockLocator\fP CChain::GetLocator (const \fBCBlockIndex\fP * pindex = \fCNULL\fP) const"
Return a \fBCBlockLocator\fP that refers to a block in this chain (by default the tip)\&. 
.SS "int CChain::Height () const\fC [inline]\fP"
Return the maximal height in the chain\&. Is equal to chain\&.Tip() ? chain\&.Tip()->nHeight : -1\&. 
.PP
Definition at line 592 of file chain\&.h\&.
.SS "\fBCBlockIndex\fP* CChain::Next (const \fBCBlockIndex\fP * pindex) const\fC [inline]\fP"
Find the successor of a block in this chain, or NULL if the given index is not found or is the tip\&. 
.PP
Definition at line 584 of file chain\&.h\&.
.SS "\fBCBlockIndex\fP* CChain::operator[] (int nHeight) const\fC [inline]\fP"
Returns the index entry at a particular height in this chain, or NULL if no such height exists\&. 
.PP
Definition at line 566 of file chain\&.h\&.
.SS "void CChain::SetTip (\fBCBlockIndex\fP * pindex)"

.PP
\fBCChain\fP implementation\&. Set/initialize a chain with a given tip\&. 
.PP
Definition at line 627 of file chain\&.cpp\&.
.SS "\fBCBlockIndex\fP* CChain::Tip () const\fC [inline]\fP"
Returns the index entry for the tip of this chain, or NULL if none\&. 
.PP
Definition at line 561 of file chain\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "bool operator== (const \fBCChain\fP & a, const \fBCChain\fP & b)\fC [friend]\fP"
Compare two chains efficiently\&. 
.PP
Definition at line 573 of file chain\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
