.TH "CCoinsModifier" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCoinsModifier \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <coins\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCCoins\fP * \fBoperator->\fP ()"
.br
.ti -1c
.RI "\fBCCoins\fP & \fBoperator*\fP ()"
.br
.ti -1c
.RI "\fB~CCoinsModifier\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCCoinsViewCache\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A reference to a mutable cache entry\&. Encapsulating it allows us to run cleanup code after the modification is finished, and keeping track of concurrent modifications\&. 
.PP
Definition at line 403 of file coins\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CCoinsModifier::~CCoinsModifier ()"

.PP
Definition at line 254 of file coins\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCCoins\fP& CCoinsModifier::operator* ()\fC [inline]\fP"

.PP
Definition at line 412 of file coins\&.h\&.
.SS "\fBCCoins\fP* CCoinsModifier::operator-> ()\fC [inline]\fP"

.PP
Definition at line 411 of file coins\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBCCoinsViewCache\fP\fC [friend]\fP"

.PP
Definition at line 414 of file coins\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
