.TH "CCoinsStats" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCoinsStats \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <coins\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCCoinsStats\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnHeight\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBhashBlock\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBnTransactions\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBnTransactionOutputs\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBnSerializedSize\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBhashSerialized\fP"
.br
.ti -1c
.RI "\fBCAmount\fP \fBnTotalAmount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 327 of file coins\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CCoinsStats::CCoinsStats ()\fC [inline]\fP"

.PP
Definition at line 337 of file coins\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint256\fP CCoinsStats::hashBlock"

.PP
Definition at line 330 of file coins\&.h\&.
.SS "\fBuint256\fP CCoinsStats::hashSerialized"

.PP
Definition at line 334 of file coins\&.h\&.
.SS "int CCoinsStats::nHeight"

.PP
Definition at line 329 of file coins\&.h\&.
.SS "\fBuint64_t\fP CCoinsStats::nSerializedSize"

.PP
Definition at line 333 of file coins\&.h\&.
.SS "\fBCAmount\fP CCoinsStats::nTotalAmount"

.PP
Definition at line 335 of file coins\&.h\&.
.SS "\fBuint64_t\fP CCoinsStats::nTransactionOutputs"

.PP
Definition at line 332 of file coins\&.h\&.
.SS "\fBuint64_t\fP CCoinsStats::nTransactions"

.PP
Definition at line 331 of file coins\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
