.TH "CCoinsViewErrorCatcher" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCoinsViewErrorCatcher \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCCoinsViewBacked\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCCoinsViewErrorCatcher\fP (\fBCCoinsView\fP *view)"
.br
.ti -1c
.RI "bool \fBGetCoins\fP (const \fBuint256\fP &txid, \fBCCoins\fP &coins) const "
.br
.RI "\fIRetrieve the \fBCCoins\fP (unspent transaction outputs) for a given txid\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 98 of file init\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CCoinsViewErrorCatcher::CCoinsViewErrorCatcher (\fBCCoinsView\fP * view)\fC [inline]\fP"

.PP
Definition at line 101 of file init\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CCoinsViewErrorCatcher::GetCoins (const \fBuint256\fP & txid, \fBCCoins\fP & coins) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Retrieve the \fBCCoins\fP (unspent transaction outputs) for a given txid\&. 
.PP
Reimplemented from \fBCCoinsViewBacked\fP\&.
.PP
Definition at line 102 of file init\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
