.TH "CCoinsCacheEntry" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCoinsCacheEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <coins\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBFlags\fP { \fBDIRTY\fP = (1 << 0), \fBFRESH\fP = (1 << 1) }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCCoinsCacheEntry\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCCoins\fP \fBcoins\fP"
.br
.ti -1c
.RI "unsigned char \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 312 of file coins\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBCCoinsCacheEntry::Flags\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDIRTY \fP\fP
.TP
\fB\fIFRESH \fP\fP
.PP
Definition at line 317 of file coins\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CCoinsCacheEntry::CCoinsCacheEntry ()\fC [inline]\fP"

.PP
Definition at line 322 of file coins\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCCoins\fP CCoinsCacheEntry::coins"

.PP
Definition at line 314 of file coins\&.h\&.
.SS "unsigned char CCoinsCacheEntry::flags"

.PP
Definition at line 315 of file coins\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
