.TH "CCoinControl" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCoinControl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <coincontrol\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCCoinControl\fP ()"
.br
.ti -1c
.RI "void \fBSetNull\fP ()"
.br
.ti -1c
.RI "bool \fBHasSelected\fP () const "
.br
.ti -1c
.RI "bool \fBIsSelected\fP (const \fBuint256\fP &\fBhash\fP, unsigned int n) const "
.br
.ti -1c
.RI "void \fBSelect\fP (\fBCOutPoint\fP &output)"
.br
.ti -1c
.RI "void \fBUnSelect\fP (\fBCOutPoint\fP &output)"
.br
.ti -1c
.RI "void \fBUnSelectAll\fP ()"
.br
.ti -1c
.RI "void \fBListSelected\fP (std::vector< \fBCOutPoint\fP > &vOutpoints)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCTxDestination\fP \fBdestChange\fP"
.br
.ti -1c
.RI "bool \fBuseSandStorm\fP"
.br
.ti -1c
.RI "bool \fBuseInstantX\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Coin Control Features\&. 
.PP
Definition at line 7 of file coincontrol\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CCoinControl::CCoinControl ()\fC [inline]\fP"

.PP
Definition at line 15 of file coincontrol\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CCoinControl::HasSelected () const\fC [inline]\fP"

.PP
Definition at line 28 of file coincontrol\&.h\&.
.SS "bool CCoinControl::IsSelected (const \fBuint256\fP & hash, unsigned int n) const\fC [inline]\fP"

.PP
Definition at line 33 of file coincontrol\&.h\&.
.SS "void CCoinControl::ListSelected (std::vector< \fBCOutPoint\fP > & vOutpoints)\fC [inline]\fP"

.PP
Definition at line 54 of file coincontrol\&.h\&.
.SS "void CCoinControl::Select (\fBCOutPoint\fP & output)\fC [inline]\fP"

.PP
Definition at line 39 of file coincontrol\&.h\&.
.SS "void CCoinControl::SetNull ()\fC [inline]\fP"

.PP
Definition at line 20 of file coincontrol\&.h\&.
.SS "void CCoinControl::UnSelect (\fBCOutPoint\fP & output)\fC [inline]\fP"

.PP
Definition at line 44 of file coincontrol\&.h\&.
.SS "void CCoinControl::UnSelectAll ()\fC [inline]\fP"

.PP
Definition at line 49 of file coincontrol\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCTxDestination\fP CCoinControl::destChange"

.PP
Definition at line 10 of file coincontrol\&.h\&.
.SS "bool CCoinControl::useInstantX"

.PP
Definition at line 13 of file coincontrol\&.h\&.
.SS "bool CCoinControl::useSandStorm"

.PP
Definition at line 12 of file coincontrol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
