.TH "CConsensusVote" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CConsensusVote \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <instantx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBuint256\fP \fBGetHash\fP () const "
.br
.ti -1c
.RI "bool \fBSignatureValid\fP ()"
.br
.ti -1c
.RI "bool \fBSign\fP ()"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCTxIn\fP \fBvinStormnode\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBtxHash\fP"
.br
.ti -1c
.RI "int \fBnBlockHeight\fP"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBvchStormNodeSignature\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 57 of file instantx\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBuint256\fP CConsensusVote::GetHash () const"

.PP
Definition at line 465 of file instantx\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CConsensusVote::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 73 of file instantx\&.h\&.
.SS "bool CConsensusVote::Sign ()"

.PP
Definition at line 493 of file instantx\&.cpp\&.
.SS "bool CConsensusVote::SignatureValid ()"

.PP
Definition at line 471 of file instantx\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "CConsensusVote::ADD_SERIALIZE_METHODS"

.PP
Definition at line 70 of file instantx\&.h\&.
.SS "int CConsensusVote::nBlockHeight"

.PP
Definition at line 62 of file instantx\&.h\&.
.SS "\fBuint256\fP CConsensusVote::txHash"

.PP
Definition at line 61 of file instantx\&.h\&.
.SS "std::vector<unsigned char> CConsensusVote::vchStormNodeSignature"

.PP
Definition at line 63 of file instantx\&.h\&.
.SS "\fBCTxIn\fP CConsensusVote::vinStormnode"

.PP
Definition at line 60 of file instantx\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
