.TH "CCrypter" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCrypter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crypter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBSetKeyFromPassphrase\fP (const \fBSecureString\fP &strKeyData, const std::vector< unsigned char > &chSalt, const unsigned int nRounds, const unsigned int nDerivationMethod)"
.br
.ti -1c
.RI "bool \fBEncrypt\fP (const \fBCKeyingMaterial\fP &vchPlaintext, std::vector< unsigned char > &vchCiphertext)"
.br
.ti -1c
.RI "bool \fBDecrypt\fP (const std::vector< unsigned char > &vchCiphertext, \fBCKeyingMaterial\fP &vchPlaintext)"
.br
.ti -1c
.RI "bool \fBSetKey\fP (const \fBCKeyingMaterial\fP &chNewKey, const std::vector< unsigned char > &chNewIV)"
.br
.ti -1c
.RI "void \fBCleanKey\fP ()"
.br
.ti -1c
.RI "\fBCCrypter\fP ()"
.br
.ti -1c
.RI "\fB~CCrypter\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Encryption/decryption context with key information 
.PP
Definition at line 88 of file crypter\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CCrypter::CCrypter ()\fC [inline]\fP"

.PP
Definition at line 108 of file crypter\&.h\&.
.SS "CCrypter::~CCrypter ()\fC [inline]\fP"

.PP
Definition at line 119 of file crypter\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void CCrypter::CleanKey ()\fC [inline]\fP"

.PP
Definition at line 101 of file crypter\&.h\&.
.SS "bool CCrypter::Decrypt (const std::vector< unsigned char > & vchCiphertext, \fBCKeyingMaterial\fP & vchPlaintext)"

.PP
Definition at line 98 of file crypter\&.cpp\&.
.SS "bool CCrypter::Encrypt (const \fBCKeyingMaterial\fP & vchPlaintext, std::vector< unsigned char > & vchCiphertext)"

.PP
Definition at line 71 of file crypter\&.cpp\&.
.SS "bool CCrypter::SetKey (const \fBCKeyingMaterial\fP & chNewKey, const std::vector< unsigned char > & chNewIV)"

.PP
Definition at line 59 of file crypter\&.cpp\&.
.SS "bool CCrypter::SetKeyFromPassphrase (const \fBSecureString\fP & strKeyData, const std::vector< unsigned char > & chSalt, const unsigned int nRounds, const unsigned int nDerivationMethod)"

.PP
Definition at line 25 of file crypter\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
