.TH "CCryptoKeyStore" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCryptoKeyStore \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crypter\&.h>\fP
.PP
Inherits \fBCBasicKeyStore\fP\&.
.PP
Inherited by \fBCWallet\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCCryptoKeyStore\fP ()"
.br
.ti -1c
.RI "bool \fBIsCrypted\fP () const "
.br
.ti -1c
.RI "bool \fBIsLocked\fP () const "
.br
.ti -1c
.RI "bool \fBLockKeyStore\fP ()"
.br
.ti -1c
.RI "virtual bool \fBAddCryptedKey\fP (const \fBCPubKey\fP &vchPubKey, const std::vector< unsigned char > &vchCryptedSecret)"
.br
.ti -1c
.RI "bool \fBAddKeyPubKey\fP (const \fBCKey\fP &key, const \fBCPubKey\fP &pubkey)"
.br
.ti -1c
.RI "bool \fBHaveKey\fP (const \fBCKeyID\fP &address) const "
.br
.ti -1c
.RI "bool \fBGetKey\fP (const \fBCKeyID\fP &address, \fBCKey\fP &keyOut) const "
.br
.ti -1c
.RI "bool \fBGetPubKey\fP (const \fBCKeyID\fP &address, \fBCPubKey\fP &vchPubKeyOut) const "
.br
.ti -1c
.RI "void \fBGetKeys\fP (std::set< \fBCKeyID\fP > &setAddress) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::signals2::signal< void(\fBCCryptoKeyStore\fP *wallet)> \fBNotifyStatusChanged\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBSetCrypted\fP ()"
.br
.ti -1c
.RI "bool \fBEncryptKeys\fP (\fBCKeyingMaterial\fP &vMasterKeyIn)"
.br
.ti -1c
.RI "bool \fBUnlock\fP (const \fBCKeyingMaterial\fP &vMasterKeyIn)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBCryptedKeyMap\fP \fBmapCryptedKeys\fP"
.br
.ti -1c
.RI "\fBCKeyingMaterial\fP \fBvMasterKey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Keystore which keeps the private keys encrypted\&. It derives from the basic key store, which is used if no encryption is active\&. 
.PP
Definition at line 137 of file crypter\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CCryptoKeyStore::CCryptoKeyStore ()\fC [inline]\fP"

.PP
Definition at line 156 of file crypter\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CCryptoKeyStore::AddCryptedKey (const \fBCPubKey\fP & vchPubKey, const std::vector< unsigned char > & vchCryptedSecret)\fC [virtual]\fP"

.PP
Reimplemented in \fBCWallet\fP\&.
.PP
Definition at line 289 of file crypter\&.cpp\&.
.SS "bool CCryptoKeyStore::AddKeyPubKey (const \fBCKey\fP & key, const \fBCPubKey\fP & pubkey)\fC [virtual]\fP"

.PP
Implements \fBCKeyStore\fP\&.
.PP
Reimplemented in \fBCWallet\fP\&.
.PP
Definition at line 267 of file crypter\&.cpp\&.
.SS "bool CCryptoKeyStore::EncryptKeys (\fBCKeyingMaterial\fP & vMasterKeyIn)\fC [protected]\fP"

.PP
Definition at line 342 of file crypter\&.cpp\&.
.SS "bool CCryptoKeyStore::GetKey (const \fBCKeyID\fP & address, \fBCKey\fP & keyOut) const\fC [virtual]\fP"

.PP
Implements \fBCKeyStore\fP\&.
.PP
Definition at line 301 of file crypter\&.cpp\&.
.SS "void CCryptoKeyStore::GetKeys (std::set< \fBCKeyID\fP > & setAddress) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBCKeyStore\fP\&.
.PP
Definition at line 193 of file crypter\&.h\&.
.SS "bool CCryptoKeyStore::GetPubKey (const \fBCKeyID\fP & address, \fBCPubKey\fP & vchPubKeyOut) const\fC [virtual]\fP"

.PP
Reimplemented from \fBCKeyStore\fP\&.
.PP
Definition at line 325 of file crypter\&.cpp\&.
.SS "bool CCryptoKeyStore::HaveKey (const \fBCKeyID\fP & address) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBCKeyStore\fP\&.
.PP
Definition at line 181 of file crypter\&.h\&.
.SS "bool CCryptoKeyStore::IsCrypted () const\fC [inline]\fP"

.PP
Definition at line 160 of file crypter\&.h\&.
.SS "bool CCryptoKeyStore::IsLocked () const\fC [inline]\fP"

.PP
Definition at line 165 of file crypter\&.h\&.
.SS "bool CCryptoKeyStore::LockKeyStore ()"

.PP
Definition at line 224 of file crypter\&.cpp\&.
.SS "bool CCryptoKeyStore::SetCrypted ()\fC [protected]\fP"

.PP
Definition at line 213 of file crypter\&.cpp\&.
.SS "bool CCryptoKeyStore::Unlock (const \fBCKeyingMaterial\fP & vMasterKeyIn)\fC [protected]\fP"

.PP
Definition at line 238 of file crypter\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCryptedKeyMap\fP CCryptoKeyStore::mapCryptedKeys\fC [protected]\fP"

.PP
Definition at line 145 of file crypter\&.h\&.
.SS "boost::signals2::signal<void (\fBCCryptoKeyStore\fP* wallet)> CCryptoKeyStore::NotifyStatusChanged"

.PP
Definition at line 212 of file crypter\&.h\&.
.SS "\fBCKeyingMaterial\fP CCryptoKeyStore::vMasterKey\fC [protected]\fP"

.PP
Definition at line 146 of file crypter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
