.TH "CDarkSilkAddress_B" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDarkSilkAddress_B \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <smessage\&.h>\fP
.PP
Inherits \fBCDarkSilkAddress\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBuint8_t\fP \fBgetVersion\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 168 of file smessage\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBuint8_t\fP CDarkSilkAddress_B::getVersion ()\fC [inline]\fP"

.PP
Definition at line 171 of file smessage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
