.TH "CDarkSilkExtKeyBase< K, Size, Type >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDarkSilkExtKeyBase< K, Size, Type > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <base58\&.h>\fP
.PP
Inherits \fBCBase58Data\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetKey\fP (const K &key)"
.br
.ti -1c
.RI "K \fBGetKey\fP ()"
.br
.ti -1c
.RI "\fBCDarkSilkExtKeyBase\fP (const K &key)"
.br
.ti -1c
.RI "\fBCDarkSilkExtKeyBase\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename K, int Size, CChainParams::Base58Type Type>class CDarkSilkExtKeyBase< K, Size, Type >"

.PP
Definition at line 137 of file base58\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename K , int Size, CChainParams::Base58Type Type> \fBCDarkSilkExtKeyBase\fP< K, Size, Type >::\fBCDarkSilkExtKeyBase\fP (const K & key)\fC [inline]\fP"

.PP
Definition at line 152 of file base58\&.h\&.
.SS "template<typename K , int Size, CChainParams::Base58Type Type> \fBCDarkSilkExtKeyBase\fP< K, Size, Type >::\fBCDarkSilkExtKeyBase\fP ()\fC [inline]\fP"

.PP
Definition at line 156 of file base58\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename K , int Size, CChainParams::Base58Type Type> K \fBCDarkSilkExtKeyBase\fP< K, Size, Type >::GetKey ()\fC [inline]\fP"

.PP
Definition at line 146 of file base58\&.h\&.
.SS "template<typename K , int Size, CChainParams::Base58Type Type> void \fBCDarkSilkExtKeyBase\fP< K, Size, Type >::SetKey (const K & key)\fC [inline]\fP"

.PP
Definition at line 140 of file base58\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
