.TH "CDarkSilkAddress" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDarkSilkAddress \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <base58\&.h>\fP
.PP
Inherits \fBCBase58Data\fP\&.
.PP
Inherited by \fBCDarkSilkAddress_B\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBSet\fP (const \fBCKeyID\fP &\fBid\fP)"
.br
.ti -1c
.RI "bool \fBSet\fP (const \fBCScriptID\fP &\fBid\fP)"
.br
.ti -1c
.RI "bool \fBSet\fP (const \fBCTxDestination\fP &dest)"
.br
.ti -1c
.RI "bool \fBIsValid\fP () const "
.br
.ti -1c
.RI "\fBCDarkSilkAddress\fP ()"
.br
.ti -1c
.RI "\fBCDarkSilkAddress\fP (const \fBCTxDestination\fP &dest)"
.br
.ti -1c
.RI "\fBCDarkSilkAddress\fP (const std::string &strAddress)"
.br
.ti -1c
.RI "\fBCDarkSilkAddress\fP (const char *pszAddress)"
.br
.ti -1c
.RI "\fBCTxDestination\fP \fBGet\fP () const "
.br
.ti -1c
.RI "bool \fBGetKeyID\fP (\fBCKeyID\fP &keyID) const "
.br
.ti -1c
.RI "bool \fBIsScript\fP () const "
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
base58-encoded DarkSilk addresses\&. Public-key-hash-addresses have version 0 (or 111 testnet)\&. The data vector contains RIPEMD160(SHA256(pubkey)), where pubkey is the serialized public key\&. Script-hash-addresses have version 5 (or 196 testnet)\&. The data vector contains RIPEMD160(SHA256(cscript)), where cscript is the serialized redemption script\&. 
.PP
Definition at line 103 of file base58\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CDarkSilkAddress::CDarkSilkAddress ()\fC [inline]\fP"

.PP
Definition at line 110 of file base58\&.h\&.
.SS "CDarkSilkAddress::CDarkSilkAddress (const \fBCTxDestination\fP & dest)\fC [inline]\fP"

.PP
Definition at line 111 of file base58\&.h\&.
.SS "CDarkSilkAddress::CDarkSilkAddress (const std::string & strAddress)\fC [inline]\fP"

.PP
Definition at line 112 of file base58\&.h\&.
.SS "CDarkSilkAddress::CDarkSilkAddress (const char * pszAddress)\fC [inline]\fP"

.PP
Definition at line 113 of file base58\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCTxDestination\fP CDarkSilkAddress::Get () const"

.PP
Definition at line 225 of file base58\&.cpp\&.
.SS "bool CDarkSilkAddress::GetKeyID (\fBCKeyID\fP & keyID) const"

.PP
Definition at line 238 of file base58\&.cpp\&.
.SS "bool CDarkSilkAddress::IsScript () const"

.PP
Definition at line 247 of file base58\&.cpp\&.
.SS "bool CDarkSilkAddress::IsValid () const"

.PP
Definition at line 218 of file base58\&.cpp\&.
.SS "bool CDarkSilkAddress::Set (const \fBCKeyID\fP & id)"

.PP
Definition at line 204 of file base58\&.cpp\&.
.SS "bool CDarkSilkAddress::Set (const \fBCScriptID\fP & id)"

.PP
Definition at line 209 of file base58\&.cpp\&.
.SS "bool CDarkSilkAddress::Set (const \fBCTxDestination\fP & dest)"

.PP
Definition at line 214 of file base58\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
