.TH "CDarkSilkSecret" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDarkSilkSecret \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <base58\&.h>\fP
.PP
Inherits \fBCBase58Data\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetKey\fP (const \fBCKey\fP &vchSecret)"
.br
.ti -1c
.RI "\fBCKey\fP \fBGetKey\fP ()"
.br
.ti -1c
.RI "bool \fBIsValid\fP () const "
.br
.ti -1c
.RI "bool \fBSetString\fP (const char *pszSecret)"
.br
.ti -1c
.RI "bool \fBSetString\fP (const std::string &strSecret)"
.br
.ti -1c
.RI "\fBCDarkSilkSecret\fP (const \fBCKey\fP &vchSecret)"
.br
.ti -1c
.RI "\fBCDarkSilkSecret\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A base58-encoded secret key 
.PP
Definition at line 124 of file base58\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CDarkSilkSecret::CDarkSilkSecret (const \fBCKey\fP & vchSecret)\fC [inline]\fP"

.PP
Definition at line 133 of file base58\&.h\&.
.SS "CDarkSilkSecret::CDarkSilkSecret ()\fC [inline]\fP"

.PP
Definition at line 134 of file base58\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCKey\fP CDarkSilkSecret::GetKey ()"

.PP
Definition at line 258 of file base58\&.cpp\&.
.SS "bool CDarkSilkSecret::IsValid () const"

.PP
Definition at line 265 of file base58\&.cpp\&.
.SS "void CDarkSilkSecret::SetKey (const \fBCKey\fP & vchSecret)"

.PP
Definition at line 251 of file base58\&.cpp\&.
.SS "bool CDarkSilkSecret::SetString (const char * pszSecret)"

.PP
Definition at line 271 of file base58\&.cpp\&.
.SS "bool CDarkSilkSecret::SetString (const std::string & strSecret)"

.PP
Definition at line 275 of file base58\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
