.TH "CDataStream" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDataStream \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <streams\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef vector_type::allocator_type \fBallocator_type\fP"
.br
.ti -1c
.RI "typedef vector_type::size_type \fBsize_type\fP"
.br
.ti -1c
.RI "typedef vector_type::difference_type \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef vector_type::reference \fBreference\fP"
.br
.ti -1c
.RI "typedef vector_type::const_reference \fBconst_reference\fP"
.br
.ti -1c
.RI "typedef vector_type::value_type \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef vector_type::iterator \fBiterator\fP"
.br
.ti -1c
.RI "typedef vector_type::const_iterator \fBconst_iterator\fP"
.br
.ti -1c
.RI "typedef vector_type::reverse_iterator \fBreverse_iterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCDataStream\fP (int nTypeIn, int nVersionIn)"
.br
.ti -1c
.RI "\fBCDataStream\fP (\fBconst_iterator\fP pbegin, \fBconst_iterator\fP pend, int nTypeIn, int nVersionIn)"
.br
.ti -1c
.RI "\fBCDataStream\fP (const char *pbegin, const char *pend, int nTypeIn, int nVersionIn)"
.br
.ti -1c
.RI "\fBCDataStream\fP (const \fBvector_type\fP &vchIn, int nTypeIn, int nVersionIn)"
.br
.ti -1c
.RI "\fBCDataStream\fP (const std::vector< char > &vchIn, int nTypeIn, int nVersionIn)"
.br
.ti -1c
.RI "\fBCDataStream\fP (const std::vector< unsigned char > &vchIn, int nTypeIn, int nVersionIn)"
.br
.ti -1c
.RI "void \fBInit\fP (int nTypeIn, int nVersionIn)"
.br
.ti -1c
.RI "\fBCDataStream\fP & \fBoperator+=\fP (const \fBCDataStream\fP &b)"
.br
.ti -1c
.RI "std::string \fBstr\fP () const "
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBbegin\fP () const "
.br
.ti -1c
.RI "\fBiterator\fP \fBbegin\fP ()"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBend\fP () const "
.br
.ti -1c
.RI "\fBiterator\fP \fBend\fP ()"
.br
.ti -1c
.RI "\fBsize_type\fP \fBsize\fP () const "
.br
.ti -1c
.RI "bool \fBempty\fP () const "
.br
.ti -1c
.RI "void \fBresize\fP (\fBsize_type\fP n, \fBvalue_type\fP c=0)"
.br
.ti -1c
.RI "void \fBreserve\fP (\fBsize_type\fP n)"
.br
.ti -1c
.RI "\fBconst_reference\fP \fBoperator[]\fP (\fBsize_type\fP pos) const "
.br
.ti -1c
.RI "\fBreference\fP \fBoperator[]\fP (\fBsize_type\fP pos)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP \fBinsert\fP (\fBiterator\fP it, const char &x=char())"
.br
.ti -1c
.RI "void \fBinsert\fP (\fBiterator\fP it, \fBsize_type\fP n, const char &x)"
.br
.ti -1c
.RI "void \fBinsert\fP (\fBiterator\fP it, std::vector< char >::\fBconst_iterator\fP first, std::vector< char >::\fBconst_iterator\fP last)"
.br
.ti -1c
.RI "void \fBinsert\fP (\fBiterator\fP it, const char *first, const char *last)"
.br
.ti -1c
.RI "\fBiterator\fP \fBerase\fP (\fBiterator\fP it)"
.br
.ti -1c
.RI "\fBiterator\fP \fBerase\fP (\fBiterator\fP first, \fBiterator\fP last)"
.br
.ti -1c
.RI "void \fBCompact\fP ()"
.br
.ti -1c
.RI "bool \fBRewind\fP (\fBsize_type\fP n)"
.br
.ti -1c
.RI "void \fBsetstate\fP (short bits, const char *psz)"
.br
.ti -1c
.RI "bool \fBeof\fP () const "
.br
.ti -1c
.RI "bool \fBfail\fP () const "
.br
.ti -1c
.RI "bool \fBgood\fP () const "
.br
.ti -1c
.RI "void \fBclear\fP (short n)"
.br
.ti -1c
.RI "short \fBexceptions\fP ()"
.br
.ti -1c
.RI "short \fBexceptions\fP (short mask)"
.br
.ti -1c
.RI "\fBCDataStream\fP * \fBrdbuf\fP ()"
.br
.ti -1c
.RI "int \fBin_avail\fP ()"
.br
.ti -1c
.RI "void \fBSetType\fP (int n)"
.br
.ti -1c
.RI "int \fBGetType\fP ()"
.br
.ti -1c
.RI "void \fBSetVersion\fP (int n)"
.br
.ti -1c
.RI "int \fBGetVersion\fP ()"
.br
.ti -1c
.RI "void \fBReadVersion\fP ()"
.br
.ti -1c
.RI "void \fBWriteVersion\fP ()"
.br
.ti -1c
.RI "\fBCDataStream\fP & \fBread\fP (char *pch, size_t nSize)"
.br
.ti -1c
.RI "\fBCDataStream\fP & \fBignore\fP (int nSize)"
.br
.ti -1c
.RI "\fBCDataStream\fP & \fBwrite\fP (const char *pch, size_t nSize)"
.br
.ti -1c
.RI "template<typename Stream > void \fBSerialize\fP (Stream &s, int \fBnType\fP, int \fBnVersion\fP) const "
.br
.ti -1c
.RI "template<typename T > unsigned int \fBGetSerializeSize\fP (const T &obj)"
.br
.ti -1c
.RI "template<typename T > \fBCDataStream\fP & \fBoperator<<\fP (const T &obj)"
.br
.ti -1c
.RI "template<typename T > \fBCDataStream\fP & \fBoperator>>\fP (T &obj)"
.br
.ti -1c
.RI "void \fBGetAndClear\fP (\fBCSerializeData\fP &data)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnType\fP"
.br
.ti -1c
.RI "int \fBnVersion\fP"
.br
.in -1c
.SS "Protected Types"

.in +1c
.ti -1c
.RI "typedef \fBCSerializeData\fP \fBvector_type\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBvector_type\fP \fBvch\fP"
.br
.ti -1c
.RI "unsigned int \fBnReadPos\fP"
.br
.ti -1c
.RI "short \fBstate\fP"
.br
.ti -1c
.RI "short \fBexceptmask\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBCDataStream\fP \fBoperator+\fP (const \fBCDataStream\fP &a, const \fBCDataStream\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Double ended buffer combining vector and stream-like interfaces\&. 
.PP
.RS 4

.PP
.RS 4
and << read and write unformatted data using the above serialization templates\&. 
.RE
.PP
.RE
.PP
Fills with data in linear time; some stringstream implementations take N^2 time\&. 
.PP
Definition at line 27 of file streams\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef vector_type::allocator_type \fBCDataStream::allocator_type\fP"

.PP
Definition at line 39 of file streams\&.h\&.
.SS "typedef vector_type::const_iterator \fBCDataStream::const_iterator\fP"

.PP
Definition at line 46 of file streams\&.h\&.
.SS "typedef vector_type::const_reference \fBCDataStream::const_reference\fP"

.PP
Definition at line 43 of file streams\&.h\&.
.SS "typedef vector_type::difference_type \fBCDataStream::difference_type\fP"

.PP
Definition at line 41 of file streams\&.h\&.
.SS "typedef vector_type::iterator \fBCDataStream::iterator\fP"

.PP
Definition at line 45 of file streams\&.h\&.
.SS "typedef vector_type::reference \fBCDataStream::reference\fP"

.PP
Definition at line 42 of file streams\&.h\&.
.SS "typedef vector_type::reverse_iterator \fBCDataStream::reverse_iterator\fP"

.PP
Definition at line 47 of file streams\&.h\&.
.SS "typedef vector_type::size_type \fBCDataStream::size_type\fP"

.PP
Definition at line 40 of file streams\&.h\&.
.SS "typedef vector_type::value_type \fBCDataStream::value_type\fP"

.PP
Definition at line 44 of file streams\&.h\&.
.SS "typedef \fBCSerializeData\fP \fBCDataStream::vector_type\fP\fC [protected]\fP"

.PP
Definition at line 30 of file streams\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CDataStream::CDataStream (int nTypeIn, int nVersionIn)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 49 of file streams\&.h\&.
.SS "CDataStream::CDataStream (\fBconst_iterator\fP pbegin, \fBconst_iterator\fP pend, int nTypeIn, int nVersionIn)\fC [inline]\fP"

.PP
Definition at line 54 of file streams\&.h\&.
.SS "CDataStream::CDataStream (const char * pbegin, const char * pend, int nTypeIn, int nVersionIn)\fC [inline]\fP"

.PP
Definition at line 60 of file streams\&.h\&.
.SS "CDataStream::CDataStream (const \fBvector_type\fP & vchIn, int nTypeIn, int nVersionIn)\fC [inline]\fP"

.PP
Definition at line 66 of file streams\&.h\&.
.SS "CDataStream::CDataStream (const std::vector< char > & vchIn, int nTypeIn, int nVersionIn)\fC [inline]\fP"

.PP
Definition at line 71 of file streams\&.h\&.
.SS "CDataStream::CDataStream (const std::vector< unsigned char > & vchIn, int nTypeIn, int nVersionIn)\fC [inline]\fP"

.PP
Definition at line 76 of file streams\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBconst_iterator\fP CDataStream::begin () const\fC [inline]\fP"

.PP
Definition at line 112 of file streams\&.h\&.
.SS "\fBiterator\fP CDataStream::begin ()\fC [inline]\fP"

.PP
Definition at line 113 of file streams\&.h\&.
.SS "void CDataStream::clear ()\fC [inline]\fP"

.PP
Definition at line 122 of file streams\&.h\&.
.SS "void CDataStream::clear (short n)\fC [inline]\fP"

.PP
Definition at line 220 of file streams\&.h\&.
.SS "void CDataStream::Compact ()\fC [inline]\fP"

.PP
Definition at line 191 of file streams\&.h\&.
.SS "bool CDataStream::empty () const\fC [inline]\fP"

.PP
Definition at line 117 of file streams\&.h\&.
.SS "\fBconst_iterator\fP CDataStream::end () const\fC [inline]\fP"

.PP
Definition at line 114 of file streams\&.h\&.
.SS "\fBiterator\fP CDataStream::end ()\fC [inline]\fP"

.PP
Definition at line 115 of file streams\&.h\&.
.SS "bool CDataStream::eof () const\fC [inline]\fP"

.PP
Definition at line 217 of file streams\&.h\&.
.SS "\fBiterator\fP CDataStream::erase (\fBiterator\fP it)\fC [inline]\fP"

.PP
Definition at line 154 of file streams\&.h\&.
.SS "\fBiterator\fP CDataStream::erase (\fBiterator\fP first, \fBiterator\fP last)\fC [inline]\fP"

.PP
Definition at line 171 of file streams\&.h\&.
.SS "short CDataStream::exceptions ()\fC [inline]\fP"

.PP
Definition at line 221 of file streams\&.h\&.
.SS "short CDataStream::exceptions (short mask)\fC [inline]\fP"

.PP
Definition at line 222 of file streams\&.h\&.
.SS "bool CDataStream::fail () const\fC [inline]\fP"

.PP
Definition at line 218 of file streams\&.h\&.
.SS "void CDataStream::GetAndClear (\fBCSerializeData\fP & data)\fC [inline]\fP"

.PP
Definition at line 310 of file streams\&.h\&.
.SS "template<typename T > unsigned int CDataStream::GetSerializeSize (const T & obj)\fC [inline]\fP"

.PP
Definition at line 288 of file streams\&.h\&.
.SS "int CDataStream::GetType ()\fC [inline]\fP"

.PP
Definition at line 227 of file streams\&.h\&.
.SS "int CDataStream::GetVersion ()\fC [inline]\fP"

.PP
Definition at line 229 of file streams\&.h\&.
.SS "bool CDataStream::good () const\fC [inline]\fP"

.PP
Definition at line 219 of file streams\&.h\&.
.SS "\fBCDataStream\fP& CDataStream::ignore (int nSize)\fC [inline]\fP"

.PP
Definition at line 255 of file streams\&.h\&.
.SS "int CDataStream::in_avail ()\fC [inline]\fP"

.PP
Definition at line 224 of file streams\&.h\&.
.SS "void CDataStream::Init (int nTypeIn, int nVersionIn)\fC [inline]\fP"

.PP
Definition at line 81 of file streams\&.h\&.
.SS "\fBiterator\fP CDataStream::insert (\fBiterator\fP it, const char & x = \fCchar()\fP)\fC [inline]\fP"

.PP
Definition at line 123 of file streams\&.h\&.
.SS "void CDataStream::insert (\fBiterator\fP it, \fBsize_type\fP n, const char & x)\fC [inline]\fP"

.PP
Definition at line 124 of file streams\&.h\&.
.SS "void CDataStream::insert (\fBiterator\fP it, std::vector< char >::\fBconst_iterator\fP first, std::vector< char >::\fBconst_iterator\fP last)\fC [inline]\fP"

.PP
Definition at line 126 of file streams\&.h\&.
.SS "void CDataStream::insert (\fBiterator\fP it, const char * first, const char * last)\fC [inline]\fP"

.PP
Definition at line 140 of file streams\&.h\&.
.SS "\fBCDataStream\fP& CDataStream::operator+= (const \fBCDataStream\fP & b)\fC [inline]\fP"

.PP
Definition at line 90 of file streams\&.h\&.
.SS "template<typename T > \fBCDataStream\fP& CDataStream::operator<< (const T & obj)\fC [inline]\fP"

.PP
Definition at line 295 of file streams\&.h\&.
.SS "template<typename T > \fBCDataStream\fP& CDataStream::operator>> (T & obj)\fC [inline]\fP"

.PP
Definition at line 303 of file streams\&.h\&.
.SS "\fBconst_reference\fP CDataStream::operator[] (\fBsize_type\fP pos) const\fC [inline]\fP"

.PP
Definition at line 120 of file streams\&.h\&.
.SS "\fBreference\fP CDataStream::operator[] (\fBsize_type\fP pos)\fC [inline]\fP"

.PP
Definition at line 121 of file streams\&.h\&.
.SS "\fBCDataStream\fP* CDataStream::rdbuf ()\fC [inline]\fP"

.PP
Definition at line 223 of file streams\&.h\&.
.SS "\fBCDataStream\fP& CDataStream::read (char * pch, size_t nSize)\fC [inline]\fP"

.PP
Definition at line 233 of file streams\&.h\&.
.SS "void CDataStream::ReadVersion ()\fC [inline]\fP"

.PP
Definition at line 230 of file streams\&.h\&.
.SS "void CDataStream::reserve (\fBsize_type\fP n)\fC [inline]\fP"

.PP
Definition at line 119 of file streams\&.h\&.
.SS "void CDataStream::resize (\fBsize_type\fP n, \fBvalue_type\fP c = \fC0\fP)\fC [inline]\fP"

.PP
Definition at line 118 of file streams\&.h\&.
.SS "bool CDataStream::Rewind (\fBsize_type\fP n)\fC [inline]\fP"

.PP
Definition at line 197 of file streams\&.h\&.
.SS "template<typename Stream > void CDataStream::Serialize (Stream & s, int nType, int nVersion) const\fC [inline]\fP"

.PP
Definition at line 280 of file streams\&.h\&.
.SS "void CDataStream::setstate (short bits, const char * psz)\fC [inline]\fP"

.PP
Definition at line 210 of file streams\&.h\&.
.SS "void CDataStream::SetType (int n)\fC [inline]\fP"

.PP
Definition at line 226 of file streams\&.h\&.
.SS "void CDataStream::SetVersion (int n)\fC [inline]\fP"

.PP
Definition at line 228 of file streams\&.h\&.
.SS "\fBsize_type\fP CDataStream::size () const\fC [inline]\fP"

.PP
Definition at line 116 of file streams\&.h\&.
.SS "std::string CDataStream::str () const\fC [inline]\fP"

.PP
Definition at line 103 of file streams\&.h\&.
.SS "\fBCDataStream\fP& CDataStream::write (const char * pch, size_t nSize)\fC [inline]\fP"

.PP
Definition at line 272 of file streams\&.h\&.
.SS "void CDataStream::WriteVersion ()\fC [inline]\fP"

.PP
Definition at line 231 of file streams\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "\fBCDataStream\fP operator+ (const \fBCDataStream\fP & a, const \fBCDataStream\fP & b)\fC [friend]\fP"

.PP
Definition at line 96 of file streams\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "short CDataStream::exceptmask\fC [protected]\fP"

.PP
Definition at line 34 of file streams\&.h\&.
.SS "unsigned int CDataStream::nReadPos\fC [protected]\fP"

.PP
Definition at line 32 of file streams\&.h\&.
.SS "int CDataStream::nType"

.PP
Definition at line 36 of file streams\&.h\&.
.SS "int CDataStream::nVersion"

.PP
Definition at line 37 of file streams\&.h\&.
.SS "short CDataStream::state\fC [protected]\fP"

.PP
Definition at line 33 of file streams\&.h\&.
.SS "\fBvector_type\fP CDataStream::vch\fC [protected]\fP"

.PP
Definition at line 31 of file streams\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
