.TH "CDB" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDB \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <db\&.h>\fP
.PP
Inherited by \fBCWalletDB\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.ti -1c
.RI "bool \fBTxnBegin\fP ()"
.br
.ti -1c
.RI "bool \fBTxnCommit\fP ()"
.br
.ti -1c
.RI "bool \fBTxnAbort\fP ()"
.br
.ti -1c
.RI "bool \fBReadVersion\fP (int &nVersion)"
.br
.ti -1c
.RI "bool \fBWriteVersion\fP (int nVersion)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBRewrite\fP (const std::string &\fBstrFile\fP, const char *pszSkip=NULL)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBCDB\fP (const std::string &strFilename, const char *pszMode='r+')"
.br
.ti -1c
.RI "\fB~CDB\fP ()"
.br
.ti -1c
.RI "template<typename K , typename T > bool \fBRead\fP (const K &key, T &\fBvalue\fP)"
.br
.ti -1c
.RI "template<typename K , typename T > bool \fBWrite\fP (const K &key, const T &\fBvalue\fP, bool fOverwrite=true)"
.br
.ti -1c
.RI "template<typename K > bool \fBErase\fP (const K &key)"
.br
.ti -1c
.RI "template<typename K > bool \fBExists\fP (const K &key)"
.br
.ti -1c
.RI "Dbc * \fBGetCursor\fP ()"
.br
.ti -1c
.RI "int \fBReadAtCursor\fP (Dbc *pcursor, \fBCDataStream\fP &ssKey, \fBCDataStream\fP &ssValue, unsigned int fFlags=DB_NEXT)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Db * \fBpdb\fP"
.br
.ti -1c
.RI "std::string \fBstrFile\fP"
.br
.ti -1c
.RI "DbTxn * \fBactiveTxn\fP"
.br
.ti -1c
.RI "bool \fBfReadOnly\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
RAII class that provides access to a Berkeley database 
.PP
Definition at line 95 of file db\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CDB::CDB (const std::string & strFilename, const char * pszMode = \fC'r+'\fP)\fC [explicit]\fP, \fC [protected]\fP"

.PP
Definition at line 230 of file db\&.cpp\&.
.SS "CDB::~CDB ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 104 of file db\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void CDB::Close ()"

.PP
Definition at line 301 of file db\&.cpp\&.
.SS "template<typename K > bool CDB::Erase (const K & key)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 179 of file db\&.h\&.
.SS "template<typename K > bool CDB::Exists (const K & key)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 201 of file db\&.h\&.
.SS "void CDB::Flush ()"

.PP
Definition at line 288 of file db\&.cpp\&.
.SS "Dbc* CDB::GetCursor ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 220 of file db\&.h\&.
.SS "template<typename K , typename T > bool CDB::Read (const K & key, T & value)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 116 of file db\&.h\&.
.SS "int CDB::ReadAtCursor (Dbc * pcursor, \fBCDataStream\fP & ssKey, \fBCDataStream\fP & ssValue, unsigned int fFlags = \fCDB_NEXT\fP)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 231 of file db\&.h\&.
.SS "bool CDB::ReadVersion (int & nVersion)\fC [inline]\fP"

.PP
Definition at line 298 of file db\&.h\&.
.SS "bool CDB::Rewrite (const std::string & strFile, const char * pszSkip = \fCNULL\fP)\fC [static]\fP"

.PP
Definition at line 343 of file db\&.cpp\&.
.SS "bool CDB::TxnAbort ()\fC [inline]\fP"

.PP
Definition at line 289 of file db\&.h\&.
.SS "bool CDB::TxnBegin ()\fC [inline]\fP"

.PP
Definition at line 269 of file db\&.h\&.
.SS "bool CDB::TxnCommit ()\fC [inline]\fP"

.PP
Definition at line 280 of file db\&.h\&.
.SS "template<typename K , typename T > bool CDB::Write (const K & key, const T & value, bool fOverwrite = \fCtrue\fP)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 150 of file db\&.h\&.
.SS "bool CDB::WriteVersion (int nVersion)\fC [inline]\fP"

.PP
Definition at line 304 of file db\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "DbTxn* CDB::activeTxn\fC [protected]\fP"

.PP
Definition at line 100 of file db\&.h\&.
.SS "bool CDB::fReadOnly\fC [protected]\fP"

.PP
Definition at line 101 of file db\&.h\&.
.SS "Db* CDB::pdb\fC [protected]\fP"

.PP
Definition at line 98 of file db\&.h\&.
.SS "std::string CDB::strFile\fC [protected]\fP"

.PP
Definition at line 99 of file db\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
