.TH "CDBEnv" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDBEnv \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <db\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBVerifyResult\fP { \fBVERIFY_OK\fP, \fBRECOVER_OK\fP, \fBRECOVER_FAIL\fP }"
.br
.ti -1c
.RI "typedef std::pair< std::vector< unsigned char >, std::vector< unsigned char > > \fBKeyValPair\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCDBEnv\fP ()"
.br
.ti -1c
.RI "\fB~CDBEnv\fP ()"
.br
.ti -1c
.RI "void \fBMakeMock\fP ()"
.br
.ti -1c
.RI "bool \fBIsMock\fP ()"
.br
.ti -1c
.RI "\fBVerifyResult\fP \fBVerify\fP (std::string strFile, bool(*recoverFunc)(\fBCDBEnv\fP &\fBdbenv\fP, std::string strFile))"
.br
.ti -1c
.RI "bool \fBSalvage\fP (std::string strFile, bool fAggressive, std::vector< \fBKeyValPair\fP > &vResult)"
.br
.ti -1c
.RI "bool \fBOpen\fP (boost::filesystem::path pathEnv_)"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.ti -1c
.RI "void \fBFlush\fP (bool fShutdown)"
.br
.ti -1c
.RI "void \fBCheckpointLSN\fP (const std::string &strFile)"
.br
.ti -1c
.RI "void \fBCloseDb\fP (const std::string &strFile)"
.br
.ti -1c
.RI "bool \fBRemoveDb\fP (const std::string &strFile)"
.br
.ti -1c
.RI "DbTxn * \fBTxnBegin\fP (int flags=DB_TXN_WRITE_NOSYNC)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_db\fP"
.br
.ti -1c
.RI "DbEnv \fBdbenv\fP"
.br
.ti -1c
.RI "std::map< std::string, int > \fBmapFileUseCount\fP"
.br
.ti -1c
.RI "std::map< std::string, Db * > \fBmapDb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file db\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef std::pair<std::vector<unsigned char>, std::vector<unsigned char> > \fBCDBEnv::KeyValPair\fP"

.PP
Definition at line 70 of file db\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBCDBEnv::VerifyResult\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIVERIFY_OK \fP\fP
.TP
\fB\fIRECOVER_OK \fP\fP
.TP
\fB\fIRECOVER_FAIL \fP\fP
.PP
Definition at line 61 of file db\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CDBEnv::CDBEnv ()"

.PP
Definition at line 47 of file db\&.cpp\&.
.SS "CDBEnv::~CDBEnv ()"

.PP
Definition at line 53 of file db\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void CDBEnv::CheckpointLSN (const std::string & strFile)"

.PP
Definition at line 222 of file db\&.cpp\&.
.SS "void CDBEnv::Close ()"

.PP
Definition at line 58 of file db\&.cpp\&.
.SS "void CDBEnv::CloseDb (const std::string & strFile)"

.PP
Definition at line 319 of file db\&.cpp\&.
.SS "void CDBEnv::Flush (bool fShutdown)"

.PP
Definition at line 428 of file db\&.cpp\&.
.SS "bool CDBEnv::IsMock ()\fC [inline]\fP"

.PP
Definition at line 53 of file db\&.h\&.
.SS "void CDBEnv::MakeMock ()"

.PP
Definition at line 116 of file db\&.cpp\&.
.SS "bool CDBEnv::Open (boost::filesystem::path pathEnv_)"
debug 
.PP
Definition at line 63 of file db\&.cpp\&.
.SS "bool CDBEnv::RemoveDb (const std::string & strFile)"

.PP
Definition at line 334 of file db\&.cpp\&.
.SS "bool CDBEnv::Salvage (std::string strFile, bool fAggressive, std::vector< \fBKeyValPair\fP > & vResult)"

.PP
Definition at line 167 of file db\&.cpp\&.
.SS "DbTxn* CDBEnv::TxnBegin (int flags = \fCDB_TXN_WRITE_NOSYNC\fP)\fC [inline]\fP"

.PP
Definition at line 81 of file db\&.h\&.
.SS "\fBCDBEnv::VerifyResult\fP CDBEnv::Verify (std::string strFile, bool(*)(\fBCDBEnv\fP &\fBdbenv\fP, std::string strFile) recoverFunc)"

.PP
Definition at line 150 of file db\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCCriticalSection\fP CDBEnv::cs_db\fC [mutable]\fP"

.PP
Definition at line 45 of file db\&.h\&.
.SS "DbEnv CDBEnv::dbenv"

.PP
Definition at line 46 of file db\&.h\&.
.SS "std::map<std::string, Db*> CDBEnv::mapDb"

.PP
Definition at line 48 of file db\&.h\&.
.SS "std::map<std::string, int> CDBEnv::mapFileUseCount"

.PP
Definition at line 47 of file db\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
