.TH "CDiskBlockIndex" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDiskBlockIndex \- Used to marshal pointers into hashes for db storage\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <chain\&.h>\fP
.PP
Inherits \fBCBlockIndex\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCDiskBlockIndex\fP ()"
.br
.ti -1c
.RI "\fBCDiskBlockIndex\fP (\fBCBlockIndex\fP *pindex)"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int \fBnVersion\fP)"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetBlockHash\fP () const "
.br
.ti -1c
.RI "std::string \fBToString\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint256\fP \fBhashPrev\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBhashNext\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Used to marshal pointers into hashes for db storage\&. 
.PP
Definition at line 331 of file chain\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CDiskBlockIndex::CDiskBlockIndex ()\fC [inline]\fP"

.PP
Definition at line 340 of file chain\&.h\&.
.SS "CDiskBlockIndex::CDiskBlockIndex (\fBCBlockIndex\fP * pindex)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 347 of file chain\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBuint256\fP CDiskBlockIndex::GetBlockHash () const\fC [inline]\fP"

.PP
Definition at line 391 of file chain\&.h\&.
.SS "template<typename Stream , typename Operation > void CDiskBlockIndex::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 356 of file chain\&.h\&.
.SS "std::string CDiskBlockIndex::ToString () const\fC [inline]\fP"

.PP
Definition at line 409 of file chain\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CDiskBlockIndex::ADD_SERIALIZE_METHODS"

.PP
Definition at line 353 of file chain\&.h\&.
.SS "\fBuint256\fP CDiskBlockIndex::hashNext"

.PP
Definition at line 338 of file chain\&.h\&.
.SS "\fBuint256\fP CDiskBlockIndex::hashPrev"

.PP
Definition at line 337 of file chain\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
