.TH "CDiskBlockPos" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDiskBlockPos \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <chain\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.ti -1c
.RI "\fBCDiskBlockPos\fP ()"
.br
.ti -1c
.RI "\fBCDiskBlockPos\fP (int nFileIn, unsigned int nPosIn)"
.br
.ti -1c
.RI "void \fBSetNull\fP ()"
.br
.ti -1c
.RI "bool \fBIsNull\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnFile\fP"
.br
.ti -1c
.RI "unsigned int \fBnPos\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCDiskBlockPos\fP &a, const \fBCDiskBlockPos\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBCDiskBlockPos\fP &a, const \fBCDiskBlockPos\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file chain\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CDiskBlockPos::CDiskBlockPos ()\fC [inline]\fP"

.PP
Definition at line 41 of file chain\&.h\&.
.SS "CDiskBlockPos::CDiskBlockPos (int nFileIn, unsigned int nPosIn)\fC [inline]\fP"

.PP
Definition at line 45 of file chain\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CDiskBlockPos::IsNull () const\fC [inline]\fP"

.PP
Definition at line 59 of file chain\&.h\&.
.SS "template<typename Stream , typename Operation > void CDiskBlockPos::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 36 of file chain\&.h\&.
.SS "void CDiskBlockPos::SetNull ()\fC [inline]\fP"

.PP
Definition at line 58 of file chain\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "bool operator!= (const \fBCDiskBlockPos\fP & a, const \fBCDiskBlockPos\fP & b)\fC [friend]\fP"

.PP
Definition at line 54 of file chain\&.h\&.
.SS "bool operator== (const \fBCDiskBlockPos\fP & a, const \fBCDiskBlockPos\fP & b)\fC [friend]\fP"

.PP
Definition at line 50 of file chain\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CDiskBlockPos::ADD_SERIALIZE_METHODS"

.PP
Definition at line 33 of file chain\&.h\&.
.SS "int CDiskBlockPos::nFile"

.PP
Definition at line 30 of file chain\&.h\&.
.SS "unsigned int CDiskBlockPos::nPos"

.PP
Definition at line 31 of file chain\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
