.TH "CDNSSeedData" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDNSSeedData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <chainparams\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCDNSSeedData\fP (const string &strName, const string &strHost)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBhost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file chainparams\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CDNSSeedData::CDNSSeedData (const string & strName, const string & strHost)\fC [inline]\fP"

.PP
Definition at line 25 of file chainparams\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "string CDNSSeedData::host"

.PP
Definition at line 24 of file chainparams\&.h\&.
.SS "string CDNSSeedData::name"

.PP
Definition at line 24 of file chainparams\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
