.TH "CExtKey" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CExtKey \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <key\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBEncode\fP (unsigned char code[74]) const "
.br
.ti -1c
.RI "void \fBDecode\fP (const unsigned char code[74])"
.br
.ti -1c
.RI "bool \fBDerive\fP (\fBCExtKey\fP &out, unsigned int \fBnChild\fP) const "
.br
.ti -1c
.RI "\fBCExtPubKey\fP \fBNeuter\fP () const "
.br
.ti -1c
.RI "void \fBSetMaster\fP (const unsigned char *seed, unsigned int nSeedLen)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBnDepth\fP"
.br
.ti -1c
.RI "unsigned char \fBvchFingerprint\fP [4]"
.br
.ti -1c
.RI "unsigned int \fBnChild\fP"
.br
.ti -1c
.RI "unsigned char \fBvchChainCode\fP [32]"
.br
.ti -1c
.RI "\fBCKey\fP \fBkey\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCExtKey\fP &a, const \fBCExtKey\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 136 of file key\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void CExtKey::Decode (const unsigned char code[74])"

.PP
Definition at line 305 of file key\&.cpp\&.
.SS "bool CExtKey::Derive (\fBCExtKey\fP & out, unsigned int nChild) const"

.PP
Definition at line 260 of file key\&.cpp\&.
.SS "void CExtKey::Encode (unsigned char code[74]) const"

.PP
Definition at line 294 of file key\&.cpp\&.
.SS "\fBCExtPubKey\fP CExtKey::Neuter () const"

.PP
Definition at line 284 of file key\&.cpp\&.
.SS "void CExtKey::SetMaster (const unsigned char * seed, unsigned int nSeedLen)"

.PP
Definition at line 268 of file key\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "bool operator== (const \fBCExtKey\fP & a, const \fBCExtKey\fP & b)\fC [friend]\fP"

.PP
Definition at line 143 of file key\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCKey\fP CExtKey::key"

.PP
Definition at line 141 of file key\&.h\&.
.SS "unsigned int CExtKey::nChild"

.PP
Definition at line 139 of file key\&.h\&.
.SS "unsigned char CExtKey::nDepth"

.PP
Definition at line 137 of file key\&.h\&.
.SS "unsigned char CExtKey::vchChainCode[32]"

.PP
Definition at line 140 of file key\&.h\&.
.SS "unsigned char CExtKey::vchFingerprint[4]"

.PP
Definition at line 138 of file key\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
