.TH "CExtPubKey" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CExtPubKey \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pubkey\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBEncode\fP (unsigned char code[74]) const "
.br
.ti -1c
.RI "void \fBDecode\fP (const unsigned char code[74])"
.br
.ti -1c
.RI "bool \fBDerive\fP (\fBCExtPubKey\fP &out, unsigned int \fBnChild\fP) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBnDepth\fP"
.br
.ti -1c
.RI "unsigned char \fBvchFingerprint\fP [4]"
.br
.ti -1c
.RI "unsigned int \fBnChild\fP"
.br
.ti -1c
.RI "unsigned char \fBvchChainCode\fP [32]"
.br
.ti -1c
.RI "\fBCPubKey\fP \fBpubkey\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCExtPubKey\fP &a, const \fBCExtPubKey\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 182 of file pubkey\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void CExtPubKey::Decode (const unsigned char code[74])"

.PP
Definition at line 259 of file pubkey\&.cpp\&.
.SS "bool CExtPubKey::Derive (\fBCExtPubKey\fP & out, unsigned int nChild) const"

.PP
Definition at line 267 of file pubkey\&.cpp\&.
.SS "void CExtPubKey::Encode (unsigned char code[74]) const"

.PP
Definition at line 249 of file pubkey\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "bool operator== (const \fBCExtPubKey\fP & a, const \fBCExtPubKey\fP & b)\fC [friend]\fP"

.PP
Definition at line 189 of file pubkey\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned int CExtPubKey::nChild"

.PP
Definition at line 185 of file pubkey\&.h\&.
.SS "unsigned char CExtPubKey::nDepth"

.PP
Definition at line 183 of file pubkey\&.h\&.
.SS "\fBCPubKey\fP CExtPubKey::pubkey"

.PP
Definition at line 187 of file pubkey\&.h\&.
.SS "unsigned char CExtPubKey::vchChainCode[32]"

.PP
Definition at line 186 of file pubkey\&.h\&.
.SS "unsigned char CExtPubKey::vchFingerprint[4]"

.PP
Definition at line 184 of file pubkey\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
