.TH "CFinalizedBudgetBroadcast" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFinalizedBudgetBroadcast \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stormnode-budget\&.h>\fP
.PP
Inherits \fBCFinalizedBudget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCFinalizedBudgetBroadcast\fP ()"
.br
.ti -1c
.RI "\fBCFinalizedBudgetBroadcast\fP (const \fBCFinalizedBudget\fP &other)"
.br
.ti -1c
.RI "\fBCFinalizedBudgetBroadcast\fP (std::string strBudgetNameIn, int nBlockStartIn, std::vector< \fBCTxBudgetPayment\fP > vecBudgetPaymentsIn, \fBuint256\fP nFeeTXHashIn)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBCFinalizedBudgetBroadcast\fP &first, \fBCFinalizedBudgetBroadcast\fP &second)"
.br
.ti -1c
.RI "\fBCFinalizedBudgetBroadcast\fP & \fBoperator=\fP (\fBCFinalizedBudgetBroadcast\fP from)"
.br
.ti -1c
.RI "void \fBRelay\fP ()"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 296 of file stormnode-budget\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CFinalizedBudgetBroadcast::CFinalizedBudgetBroadcast ()"

.PP
Definition at line 1942 of file stormnode-budget\&.cpp\&.
.SS "CFinalizedBudgetBroadcast::CFinalizedBudgetBroadcast (const \fBCFinalizedBudget\fP & other)"

.PP
Definition at line 1952 of file stormnode-budget\&.cpp\&.
.SS "CFinalizedBudgetBroadcast::CFinalizedBudgetBroadcast (std::string strBudgetNameIn, int nBlockStartIn, std::vector< \fBCTxBudgetPayment\fP > vecBudgetPaymentsIn, \fBuint256\fP nFeeTXHashIn)"

.PP
Definition at line 1961 of file stormnode-budget\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCFinalizedBudgetBroadcast\fP& CFinalizedBudgetBroadcast::operator= (\fBCFinalizedBudgetBroadcast\fP from)\fC [inline]\fP"

.PP
Definition at line 321 of file stormnode-budget\&.h\&.
.SS "void CFinalizedBudgetBroadcast::Relay ()"

.PP
Definition at line 1970 of file stormnode-budget\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CFinalizedBudgetBroadcast::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 332 of file stormnode-budget\&.h\&.
.SS "void CFinalizedBudgetBroadcast::swap (\fBCFinalizedBudgetBroadcast\fP & first, \fBCFinalizedBudgetBroadcast\fP & second)\fC [inline]\fP"

.PP
Definition at line 306 of file stormnode-budget\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CFinalizedBudgetBroadcast::ADD_SERIALIZE_METHODS"

.PP
Definition at line 329 of file stormnode-budget\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
