.TH "CFinalizedBudgetVote" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFinalizedBudgetVote \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stormnode-budget\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCFinalizedBudgetVote\fP ()"
.br
.ti -1c
.RI "\fBCFinalizedBudgetVote\fP (\fBCTxIn\fP vinIn, \fBuint256\fP nBudgetHashIn)"
.br
.ti -1c
.RI "bool \fBSign\fP (\fBCKey\fP &keyStormnode, \fBCPubKey\fP &pubKeyStormnode)"
.br
.ti -1c
.RI "bool \fBSignatureValid\fP (bool fSignatureCheck)"
.br
.ti -1c
.RI "void \fBRelay\fP ()"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetHash\fP ()"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBfValid\fP"
.br
.ti -1c
.RI "bool \fBfSynced\fP"
.br
.ti -1c
.RI "\fBCTxIn\fP \fBvin\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBnBudgetHash\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnTime\fP"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBvchSig\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 345 of file stormnode-budget\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CFinalizedBudgetVote::CFinalizedBudgetVote ()"

.PP
Definition at line 1976 of file stormnode-budget\&.cpp\&.
.SS "CFinalizedBudgetVote::CFinalizedBudgetVote (\fBCTxIn\fP vinIn, \fBuint256\fP nBudgetHashIn)"

.PP
Definition at line 1986 of file stormnode-budget\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBuint256\fP CFinalizedBudgetVote::GetHash ()\fC [inline]\fP"

.PP
Definition at line 362 of file stormnode-budget\&.h\&.
.SS "void CFinalizedBudgetVote::Relay ()"

.PP
Definition at line 1996 of file stormnode-budget\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CFinalizedBudgetVote::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 373 of file stormnode-budget\&.h\&.
.SS "bool CFinalizedBudgetVote::Sign (\fBCKey\fP & keyStormnode, \fBCPubKey\fP & pubKeyStormnode)"

.PP
Definition at line 2002 of file stormnode-budget\&.cpp\&.
.SS "bool CFinalizedBudgetVote::SignatureValid (bool fSignatureCheck)"

.PP
Definition at line 2024 of file stormnode-budget\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "CFinalizedBudgetVote::ADD_SERIALIZE_METHODS"

.PP
Definition at line 370 of file stormnode-budget\&.h\&.
.SS "bool CFinalizedBudgetVote::fSynced"

.PP
Definition at line 349 of file stormnode-budget\&.h\&.
.SS "bool CFinalizedBudgetVote::fValid"

.PP
Definition at line 348 of file stormnode-budget\&.h\&.
.SS "\fBuint256\fP CFinalizedBudgetVote::nBudgetHash"

.PP
Definition at line 351 of file stormnode-budget\&.h\&.
.SS "\fBint64_t\fP CFinalizedBudgetVote::nTime"

.PP
Definition at line 352 of file stormnode-budget\&.h\&.
.SS "std::vector<unsigned char> CFinalizedBudgetVote::vchSig"

.PP
Definition at line 353 of file stormnode-budget\&.h\&.
.SS "\fBCTxIn\fP CFinalizedBudgetVote::vin"

.PP
Definition at line 350 of file stormnode-budget\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
