.TH "CFlatData" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFlatData \- Wrapper for serializing arrays and POD\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <serialize\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCFlatData\fP (void *pbeginIn, void *pendIn)"
.br
.ti -1c
.RI "template<class T , class TAl > \fBCFlatData\fP (std::vector< T, TAl > &v)"
.br
.ti -1c
.RI "char * \fBbegin\fP ()"
.br
.ti -1c
.RI "const char * \fBbegin\fP () const "
.br
.ti -1c
.RI "char * \fBend\fP ()"
.br
.ti -1c
.RI "const char * \fBend\fP () const "
.br
.ti -1c
.RI "unsigned int \fBGetSerializeSize\fP (int, int=0) const "
.br
.ti -1c
.RI "template<typename Stream > void \fBSerialize\fP (Stream &s, int, int=0) const "
.br
.ti -1c
.RI "template<typename Stream > void \fBUnserialize\fP (Stream &s, int, int=0)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "char * \fBpbegin\fP"
.br
.ti -1c
.RI "char * \fBpend\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Wrapper for serializing arrays and POD\&. 
.PP
Definition at line 334 of file serialize\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CFlatData::CFlatData (void * pbeginIn, void * pendIn)\fC [inline]\fP"

.PP
Definition at line 340 of file serialize\&.h\&.
.SS "template<class T , class TAl > CFlatData::CFlatData (std::vector< T, TAl > & v)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 342 of file serialize\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "char* CFlatData::begin ()\fC [inline]\fP"

.PP
Definition at line 347 of file serialize\&.h\&.
.SS "const char* CFlatData::begin () const\fC [inline]\fP"

.PP
Definition at line 348 of file serialize\&.h\&.
.SS "char* CFlatData::end ()\fC [inline]\fP"

.PP
Definition at line 349 of file serialize\&.h\&.
.SS "const char* CFlatData::end () const\fC [inline]\fP"

.PP
Definition at line 350 of file serialize\&.h\&.
.SS "unsigned int CFlatData::GetSerializeSize (int, int = \fC0\fP) const\fC [inline]\fP"

.PP
Definition at line 352 of file serialize\&.h\&.
.SS "template<typename Stream > void CFlatData::Serialize (Stream & s, int, int = \fC0\fP) const\fC [inline]\fP"

.PP
Definition at line 358 of file serialize\&.h\&.
.SS "template<typename Stream > void CFlatData::Unserialize (Stream & s, int, int = \fC0\fP)\fC [inline]\fP"

.PP
Definition at line 364 of file serialize\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "char* CFlatData::pbegin\fC [protected]\fP"

.PP
Definition at line 337 of file serialize\&.h\&.
.SS "char* CFlatData::pend\fC [protected]\fP"

.PP
Definition at line 338 of file serialize\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
