.TH "/home/dev/ds-160209/src/chain.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/chain.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'chain\&.h'\fP
.br
\fC#include 'wallet\&.h'\fP
.br
\fC#include 'checkpoints\&.h'\fP
.br
\fC#include 'spork\&.h'\fP
.br
\fC#include 'kernel\&.h'\fP
.br
\fC#include 'txdb-leveldb\&.h'\fP
.br
\fC#include <boost/algorithm/string/replace\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBInvalidChainFound\fP (\fBCBlockIndex\fP *pindexNew)"
.br
.ti -1c
.RI "bool \fBReorganize\fP (\fBCTxDB\fP &\fBtxdb\fP, \fBCBlockIndex\fP *pindexNew)"
.br
.ti -1c
.RI "FILE * \fBAppendBlockFile\fP (unsigned int &nFileRet)"
.br
.ti -1c
.RI "bool \fBIsInitialBlockDownload\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "FILE* AppendBlockFile (unsigned int & nFileRet)"

.PP
Definition at line 639 of file chain\&.cpp\&.
.SS "void InvalidChainFound (\fBCBlockIndex\fP * pindexNew)"

.PP
Definition at line 492 of file chain\&.cpp\&.
.SS "bool IsInitialBlockDownload ()"

.PP
Definition at line 660 of file chain\&.cpp\&.
.SS "bool Reorganize (\fBCTxDB\fP & txdb, \fBCBlockIndex\fP * pindexNew)"

.PP
Definition at line 514 of file chain\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
