.TH "/home/dev/ds-160209/src/chainparams.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/chainparams.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bignum\&.h'\fP
.br
\fC#include 'uint256\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCDNSSeedData\fP"
.br
.ti -1c
.RI "class \fBCChainParams\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMESSAGE_START_SIZE\fP   4"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBMessageStartChars\fP[\fBMESSAGE_START_SIZE\fP]"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBCChainParams\fP & \fBParams\fP ()"
.br
.ti -1c
.RI "void \fBSelectParams\fP (\fBCChainParams::Network\fP network)"
.br
.ti -1c
.RI "bool \fBSelectParamsFromCommandLine\fP ()"
.br
.ti -1c
.RI "bool \fBTestNet\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MESSAGE_START_SIZE   4"

.PP
Definition at line 17 of file chainparams\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned char MessageStartChars[\fBMESSAGE_START_SIZE\fP]"

.PP
Definition at line 18 of file chainparams\&.h\&.
.SH "Function Documentation"
.PP 
.SS "const \fBCChainParams\fP& Params ()"
Return the currently selected parameters\&. This won't change after app startup outside of the unit tests\&. 
.PP
Definition at line 186 of file chainparams\&.cpp\&.
.SS "void SelectParams (\fBCChainParams::Network\fP network)"
Sets the params returned by \fBParams()\fP to those for the given network\&. 
.PP
Definition at line 190 of file chainparams\&.cpp\&.
.SS "bool SelectParamsFromCommandLine ()"
Looks for -testnet and then calls SelectParams as appropriate\&. Returns false if an invalid combination is given\&. 
.PP
Definition at line 204 of file chainparams\&.cpp\&.
.SS "bool TestNet ()\fC [inline]\fP"

.PP
Definition at line 111 of file chainparams\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
