.TH "/home/dev/ds-160209/src/chain.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/chain.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'primitives/block\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'chainparams\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <boost/foreach\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCDiskBlockPos\fP"
.br
.ti -1c
.RI "class \fBCBlockIndex\fP"
.br
.ti -1c
.RI "class \fBCDiskBlockIndex\fP"
.br
.RI "\fIUsed to marshal pointers into hashes for db storage\&. \fP"
.ti -1c
.RI "class \fBCBlockLocator\fP"
.br
.ti -1c
.RI "class \fBCChain\fP"
.br
.ti -1c
.RI "struct \fBCBlockTemplate\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBlockStatus\fP { \fBBLOCK_VALID_UNKNOWN\fP = 0, \fBBLOCK_VALID_HEADER\fP = 1, \fBBLOCK_VALID_TREE\fP = 2, \fBBLOCK_VALID_TRANSACTIONS\fP = 3, \fBBLOCK_VALID_CHAIN\fP = 4, \fBBLOCK_VALID_SCRIPTS\fP = 5, \fBBLOCK_VALID_MASK\fP, \fBBLOCK_HAVE_DATA\fP = 8, \fBBLOCK_HAVE_UNDO\fP = 16, \fBBLOCK_HAVE_MASK\fP = BLOCK_HAVE_DATA | BLOCK_HAVE_UNDO, \fBBLOCK_FAILED_VALID\fP = 32, \fBBLOCK_FAILED_CHILD\fP = 64, \fBBLOCK_FAILED_MASK\fP = BLOCK_FAILED_VALID | BLOCK_FAILED_CHILD }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBIsInitialBlockDownload\fP ()"
.br
.ti -1c
.RI "\fBCBlockIndex\fP * \fBFindBlockByHeight\fP (int nHeight)"
.br
.ti -1c
.RI "bool \fBReorganize\fP (\fBCTxDB\fP &\fBtxdb\fP, \fBCBlockIndex\fP *pindexNew)"
.br
.ti -1c
.RI "void \fBInvalidChainFound\fP (\fBCBlockIndex\fP *pindexNew)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "std::map< \fBuint256\fP, \fBCBlockIndex\fP * > \fBmapBlockIndex\fP"
.br
.ti -1c
.RI "\fBCBlockIndex\fP * \fBpindexBest\fP"
.br
.ti -1c
.RI "bool \fBfUseFastIndex\fP"
.br
.ti -1c
.RI "\fBCBlockIndex\fP * \fBpindexGenesisBlock\fP"
.br
.ti -1c
.RI "\fBCBlockIndex\fP * \fBpblockindexFBBHLast\fP"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBBlockStatus\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIBLOCK_VALID_UNKNOWN \fP\fP
Unused\&. 
.TP
\fB\fIBLOCK_VALID_HEADER \fP\fP
Parsed, version ok, hash satisfies claimed PoW, 1 <= vtx count <= max, timestamp not in future\&. 
.TP
\fB\fIBLOCK_VALID_TREE \fP\fP
All parent headers found, difficulty matches, timestamp >= median previous, checkpoint\&. Implies all parents are also at least TREE\&. 
.TP
\fB\fIBLOCK_VALID_TRANSACTIONS \fP\fP
Only first tx is coinbase, 2 <= coinbase input script length <= 100, transactions valid, no duplicate txids, sigops, size, merkle root\&. Implies all parents are at least TREE but not necessarily TRANSACTIONS\&. When all parent blocks also have TRANSACTIONS, CBlockIndex::nChainTx will be set\&. 
.TP
\fB\fIBLOCK_VALID_CHAIN \fP\fP
Outputs do not overspend inputs, no double spends, coinbase output ok, immature coinbase spends, BIP30\&. Implies all parents are also at least CHAIN\&. 
.TP
\fB\fIBLOCK_VALID_SCRIPTS \fP\fP
Scripts & signatures ok\&. Implies all parents are also at least SCRIPTS\&. 
.TP
\fB\fIBLOCK_VALID_MASK \fP\fP
All validity bits\&. 
.TP
\fB\fIBLOCK_HAVE_DATA \fP\fP
.TP
\fB\fIBLOCK_HAVE_UNDO \fP\fP
full block available in blk*\&.dat 
.TP
\fB\fIBLOCK_HAVE_MASK \fP\fP
undo data available in rev*\&.dat 
.TP
\fB\fIBLOCK_FAILED_VALID \fP\fP
.TP
\fB\fIBLOCK_FAILED_CHILD \fP\fP
stage after last reached validness failed 
.TP
\fB\fIBLOCK_FAILED_MASK \fP\fP
descends from failed block 
.PP
Definition at line 62 of file chain\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBCBlockIndex\fP* FindBlockByHeight (int nHeight)"

.SS "void InvalidChainFound (\fBCBlockIndex\fP * pindexNew)"

.PP
Definition at line 492 of file chain\&.cpp\&.
.SS "bool IsInitialBlockDownload ()"

.PP
Definition at line 660 of file chain\&.cpp\&.
.SS "bool Reorganize (\fBCTxDB\fP & txdb, \fBCBlockIndex\fP * pindexNew)"

.PP
Definition at line 514 of file chain\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "bool fUseFastIndex"

.PP
Definition at line 57 of file init\&.cpp\&.
.SS "std::map<\fBuint256\fP, \fBCBlockIndex\fP*> mapBlockIndex"

.PP
Definition at line 59 of file main\&.cpp\&.
.SS "\fBCBlockIndex\fP* pblockindexFBBHLast"

.SS "\fBCBlockIndex\fP* pindexBest"

.PP
Definition at line 76 of file main\&.cpp\&.
.SS "\fBCBlockIndex\fP* pindexGenesisBlock"

.PP
Definition at line 69 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
