.TH "/home/dev/ds-160209/src/chainparams.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/chainparams.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'chainparams\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'chainparamsseeds\&.h'\fP
.br
\fC#include 'assert\&.h'\fP
.br
\fC#include <boost/assign/list_of\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSeedSpec6\fP"
.br
.ti -1c
.RI "class \fBCMainParams\fP"
.br
.ti -1c
.RI "class \fBCTestNetParams\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBCChainParams\fP & \fBParams\fP ()"
.br
.ti -1c
.RI "void \fBSelectParams\fP (\fBCChainParams::Network\fP network)"
.br
.ti -1c
.RI "bool \fBSelectParamsFromCommandLine\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const \fBCChainParams\fP& Params ()"
Return the currently selected parameters\&. This won't change after app startup outside of the unit tests\&. 
.PP
Definition at line 186 of file chainparams\&.cpp\&.
.SS "void SelectParams (\fBCChainParams::Network\fP network)"
Sets the params returned by \fBParams()\fP to those for the given network\&. 
.PP
Definition at line 190 of file chainparams\&.cpp\&.
.SS "bool SelectParamsFromCommandLine ()"
Looks for -testnet and then calls SelectParams as appropriate\&. Returns false if an invalid combination is given\&. 
.PP
Definition at line 204 of file chainparams\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
