.TH "CHash256" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CHash256 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hash\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBFinalize\fP (unsigned char \fBhash\fP[\fBOUTPUT_SIZE\fP])"
.br
.ti -1c
.RI "\fBCHash256\fP & \fBWrite\fP (const unsigned char *data, size_t len)"
.br
.ti -1c
.RI "\fBCHash256\fP & \fBReset\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const size_t \fBOUTPUT_SIZE\fP = CSHA256::OUTPUT_SIZE"
.br
.in -1c
.SH "Detailed Description"
.PP 
A hasher class for DarkSilk's 256-bit hash (double SHA-256)\&. 
.PP
Definition at line 29 of file hash\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void CHash256::Finalize (unsigned char hash[OUTPUT_SIZE])\fC [inline]\fP"

.PP
Definition at line 35 of file hash\&.h\&.
.SS "\fBCHash256\fP& CHash256::Reset ()\fC [inline]\fP"

.PP
Definition at line 46 of file hash\&.h\&.
.SS "\fBCHash256\fP& CHash256::Write (const unsigned char * data, size_t len)\fC [inline]\fP"

.PP
Definition at line 41 of file hash\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "const size_t CHash256::OUTPUT_SIZE = CSHA256::OUTPUT_SIZE\fC [static]\fP"

.PP
Definition at line 33 of file hash\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
