.TH "CHashWriter" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CHashWriter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hash\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "\fBCHashWriter\fP (int nTypeIn, int nVersionIn)"
.br
.ti -1c
.RI "\fBCHashWriter\fP & \fBwrite\fP (const char *pch, size_t size)"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetHash\fP ()"
.br
.ti -1c
.RI "template<typename T > \fBCHashWriter\fP & \fBoperator<<\fP (const T &obj)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnType\fP"
.br
.ti -1c
.RI "int \fBnVersion\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 163 of file hash\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CHashWriter::CHashWriter (int nTypeIn, int nVersionIn)\fC [inline]\fP"

.PP
Definition at line 176 of file hash\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBuint256\fP CHashWriter::GetHash ()\fC [inline]\fP"

.PP
Definition at line 186 of file hash\&.h\&.
.SS "void CHashWriter::Init ()\fC [inline]\fP"

.PP
Definition at line 172 of file hash\&.h\&.
.SS "template<typename T > \fBCHashWriter\fP& CHashWriter::operator<< (const T & obj)\fC [inline]\fP"

.PP
Definition at line 195 of file hash\&.h\&.
.SS "\fBCHashWriter\fP& CHashWriter::write (const char * pch, size_t size)\fC [inline]\fP"

.PP
Definition at line 180 of file hash\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int CHashWriter::nType"

.PP
Definition at line 169 of file hash\&.h\&.
.SS "int CHashWriter::nVersion"

.PP
Definition at line 170 of file hash\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
