.TH "Checkpoints" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Checkpoints \- 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::map< int, \fBuint256\fP > \fBMapCheckpoints\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBCheckHardened\fP (int nHeight, const \fBuint256\fP &\fBhash\fP)"
.br
.ti -1c
.RI "int \fBGetTotalBlocksEstimate\fP ()"
.br
.ti -1c
.RI "\fBCBlockIndex\fP * \fBGetLastCheckpoint\fP (const std::map< \fBuint256\fP, \fBCBlockIndex\fP * > &\fBmapBlockIndex\fP)"
.br
.ti -1c
.RI "const \fBCBlockIndex\fP * \fBAutoSelectSyncCheckpoint\fP ()"
.br
.ti -1c
.RI "bool \fBCheckSync\fP (int nHeight)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Block-chain checkpoints are compiled-in sanity checks\&. They are updated every release or three\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef std::map<int, \fBuint256\fP> \fBCheckpoints::MapCheckpoints\fP"

.PP
Definition at line 20 of file checkpoints\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "const \fBCBlockIndex\fP * Checkpoints::AutoSelectSyncCheckpoint ()"

.PP
Definition at line 70 of file checkpoints\&.cpp\&.
.SS "bool Checkpoints::CheckHardened (int nHeight, const \fBuint256\fP & hash)"

.PP
Definition at line 37 of file checkpoints\&.cpp\&.
.SS "bool Checkpoints::CheckSync (int nHeight)"

.PP
Definition at line 80 of file checkpoints\&.cpp\&.
.SS "\fBCBlockIndex\fP * Checkpoints::GetLastCheckpoint (const std::map< \fBuint256\fP, \fBCBlockIndex\fP * > & mapBlockIndex)"

.PP
Definition at line 55 of file checkpoints\&.cpp\&.
.SS "int Checkpoints::GetTotalBlocksEstimate ()"

.PP
Definition at line 46 of file checkpoints\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
