.TH "/home/dev/ds-160209/src/checkpoints.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/checkpoints.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/assign/list_of\&.hpp>\fP
.br
\fC#include <boost/foreach\&.hpp>\fP
.br
\fC#include 'checkpoints\&.h'\fP
.br
\fC#include 'txdb\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'uint256\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCheckpoints\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::map< int, \fBuint256\fP > \fBCheckpoints::MapCheckpoints\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBCheckpoints::CheckHardened\fP (int nHeight, const \fBuint256\fP &\fBhash\fP)"
.br
.ti -1c
.RI "int \fBCheckpoints::GetTotalBlocksEstimate\fP ()"
.br
.ti -1c
.RI "\fBCBlockIndex\fP * \fBCheckpoints::GetLastCheckpoint\fP (const std::map< \fBuint256\fP, \fBCBlockIndex\fP * > &\fBmapBlockIndex\fP)"
.br
.ti -1c
.RI "const \fBCBlockIndex\fP * \fBCheckpoints::AutoSelectSyncCheckpoint\fP ()"
.br
.ti -1c
.RI "bool \fBCheckpoints::CheckSync\fP (int nHeight)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
