.TH "CHMAC_SHA512" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CHMAC_SHA512 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hmac_sha512\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCHMAC_SHA512\fP (const unsigned char *key, size_t keylen)"
.br
.ti -1c
.RI "\fBCHMAC_SHA512\fP & \fBWrite\fP (const unsigned char *data, size_t len)"
.br
.ti -1c
.RI "void \fBFinalize\fP (unsigned char \fBhash\fP[\fBOUTPUT_SIZE\fP])"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const size_t \fBOUTPUT_SIZE\fP = 64"
.br
.in -1c
.SH "Detailed Description"
.PP 
A hasher class for HMAC-SHA-512\&. 
.PP
Definition at line 14 of file hmac_sha512\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CHMAC_SHA512::CHMAC_SHA512 (const unsigned char * key, size_t keylen)"

.PP
Definition at line 9 of file hmac_sha512\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void CHMAC_SHA512::Finalize (unsigned char hash[OUTPUT_SIZE])"

.PP
Definition at line 29 of file hmac_sha512\&.cpp\&.
.SS "\fBCHMAC_SHA512\fP& CHMAC_SHA512::Write (const unsigned char * data, size_t len)\fC [inline]\fP"

.PP
Definition at line 24 of file hmac_sha512\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "const size_t CHMAC_SHA512::OUTPUT_SIZE = 64\fC [static]\fP"

.PP
Definition at line 21 of file hmac_sha512\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
