.TH "CInit" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CInit \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCInit\fP ()"
.br
.ti -1c
.RI "\fB~CInit\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 124 of file util\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CInit::CInit ()\fC [inline]\fP"

.PP
Definition at line 127 of file util\&.cpp\&.
.SS "CInit::~CInit ()\fC [inline]\fP"

.PP
Definition at line 143 of file util\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
