.TH "CInPoint" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CInPoint \- An inpoint - a combination of a transaction and an index n into its vin\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transaction\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCInPoint\fP ()"
.br
.ti -1c
.RI "\fBCInPoint\fP (\fBCTransaction\fP *ptxIn, unsigned int nIn)"
.br
.ti -1c
.RI "void \fBSetNull\fP ()"
.br
.ti -1c
.RI "bool \fBIsNull\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCTransaction\fP * \fBptx\fP"
.br
.ti -1c
.RI "unsigned int \fBn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An inpoint - a combination of a transaction and an index n into its vin\&. 
.PP
Definition at line 79 of file transaction\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CInPoint::CInPoint ()\fC [inline]\fP"

.PP
Definition at line 85 of file transaction\&.h\&.
.SS "CInPoint::CInPoint (\fBCTransaction\fP * ptxIn, unsigned int nIn)\fC [inline]\fP"

.PP
Definition at line 86 of file transaction\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CInPoint::IsNull () const\fC [inline]\fP"

.PP
Definition at line 88 of file transaction\&.h\&.
.SS "void CInPoint::SetNull ()\fC [inline]\fP"

.PP
Definition at line 87 of file transaction\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned int CInPoint::n"

.PP
Definition at line 83 of file transaction\&.h\&.
.SS "\fBCTransaction\fP* CInPoint::ptx"

.PP
Definition at line 82 of file transaction\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
