.TH "CInv" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CInv \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <protocol\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCInv\fP ()"
.br
.ti -1c
.RI "\fBCInv\fP (int typeIn, const \fBuint256\fP &hashIn)"
.br
.ti -1c
.RI "\fBCInv\fP (const std::string &strType, const \fBuint256\fP &hashIn)"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.ti -1c
.RI "bool \fBIsKnownType\fP () const "
.br
.ti -1c
.RI "const char * \fBGetCommand\fP () const "
.br
.ti -1c
.RI "std::string \fBToString\fP () const "
.br
.ti -1c
.RI "void \fBprint\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBhash\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBCInv\fP &a, const \fBCInv\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
inv message data 
.PP
Definition at line 113 of file protocol\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CInv::CInv ()"

.PP
Definition at line 113 of file protocol\&.cpp\&.
.SS "CInv::CInv (int typeIn, const \fBuint256\fP & hashIn)"

.PP
Definition at line 119 of file protocol\&.cpp\&.
.SS "CInv::CInv (const std::string & strType, const \fBuint256\fP & hashIn)"

.PP
Definition at line 125 of file protocol\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "const char * CInv::GetCommand () const"

.PP
Definition at line 151 of file protocol\&.cpp\&.
.SS "bool CInv::IsKnownType () const"

.PP
Definition at line 146 of file protocol\&.cpp\&.
.SS "void CInv::print () const"

.PP
Definition at line 163 of file protocol\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CInv::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 123 of file protocol\&.h\&.
.SS "std::string CInv::ToString () const"

.PP
Definition at line 158 of file protocol\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "bool operator< (const \fBCInv\fP & a, const \fBCInv\fP & b)\fC [friend]\fP"

.PP
Definition at line 141 of file protocol\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "CInv::ADD_SERIALIZE_METHODS"

.PP
Definition at line 120 of file protocol\&.h\&.
.SS "\fBuint256\fP CInv::hash"

.PP
Definition at line 138 of file protocol\&.h\&.
.SS "int CInv::type"

.PP
Definition at line 137 of file protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
