.TH "CKeyStore" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CKeyStore \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <keystore\&.h>\fP
.PP
Inherited by \fBCBasicKeyStore\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~CKeyStore\fP ()"
.br
.ti -1c
.RI "virtual bool \fBAddKeyPubKey\fP (const \fBCKey\fP &key, const \fBCPubKey\fP &pubkey)=0"
.br
.ti -1c
.RI "virtual bool \fBAddKey\fP (const \fBCKey\fP &key)"
.br
.ti -1c
.RI "virtual bool \fBHaveKey\fP (const \fBCKeyID\fP &address) const =0"
.br
.ti -1c
.RI "virtual bool \fBGetKey\fP (const \fBCKeyID\fP &address, \fBCKey\fP &keyOut) const =0"
.br
.ti -1c
.RI "virtual void \fBGetKeys\fP (std::set< \fBCKeyID\fP > &setAddress) const =0"
.br
.ti -1c
.RI "virtual bool \fBGetPubKey\fP (const \fBCKeyID\fP &address, \fBCPubKey\fP &vchPubKeyOut) const "
.br
.ti -1c
.RI "virtual bool \fBAddCScript\fP (const \fBCScript\fP &redeemScript)=0"
.br
.ti -1c
.RI "virtual bool \fBHaveCScript\fP (const \fBCScriptID\fP &\fBhash\fP) const =0"
.br
.ti -1c
.RI "virtual bool \fBGetCScript\fP (const \fBCScriptID\fP &\fBhash\fP, \fBCScript\fP &redeemScriptOut) const =0"
.br
.ti -1c
.RI "virtual bool \fBAddWatchOnly\fP (const \fBCScript\fP &dest)=0"
.br
.ti -1c
.RI "virtual bool \fBRemoveWatchOnly\fP (const \fBCScript\fP &dest)=0"
.br
.ti -1c
.RI "virtual bool \fBHaveWatchOnly\fP (const \fBCScript\fP &dest) const =0"
.br
.ti -1c
.RI "virtual bool \fBHaveWatchOnly\fP () const =0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_KeyStore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A virtual base class for key stores 
.PP
Definition at line 25 of file keystore\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual CKeyStore::~CKeyStore ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 31 of file keystore\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual bool CKeyStore::AddCScript (const \fBCScript\fP & redeemScript)\fC [pure virtual]\fP"

.PP
Implemented in \fBCWallet\fP, and \fBCBasicKeyStore\fP\&.
.SS "bool CKeyStore::AddKey (const \fBCKey\fP & key)\fC [virtual]\fP"

.PP
Definition at line 18 of file keystore\&.cpp\&.
.SS "virtual bool CKeyStore::AddKeyPubKey (const \fBCKey\fP & key, const \fBCPubKey\fP & pubkey)\fC [pure virtual]\fP"

.PP
Implemented in \fBCWallet\fP, \fBCCryptoKeyStore\fP, and \fBCBasicKeyStore\fP\&.
.SS "virtual bool CKeyStore::AddWatchOnly (const \fBCScript\fP & dest)\fC [pure virtual]\fP"

.PP
Implemented in \fBCWallet\fP, and \fBCBasicKeyStore\fP\&.
.SS "virtual bool CKeyStore::GetCScript (const \fBCScriptID\fP & hash, \fBCScript\fP & redeemScriptOut) const\fC [pure virtual]\fP"

.PP
Implemented in \fBCBasicKeyStore\fP\&.
.SS "virtual bool CKeyStore::GetKey (const \fBCKeyID\fP & address, \fBCKey\fP & keyOut) const\fC [pure virtual]\fP"

.PP
Implemented in \fBCCryptoKeyStore\fP, and \fBCBasicKeyStore\fP\&.
.SS "virtual void CKeyStore::GetKeys (std::set< \fBCKeyID\fP > & setAddress) const\fC [pure virtual]\fP"

.PP
Implemented in \fBCCryptoKeyStore\fP, and \fBCBasicKeyStore\fP\&.
.SS "bool CKeyStore::GetPubKey (const \fBCKeyID\fP & address, \fBCPubKey\fP & vchPubKeyOut) const\fC [virtual]\fP"

.PP
Reimplemented in \fBCCryptoKeyStore\fP\&.
.PP
Definition at line 9 of file keystore\&.cpp\&.
.SS "virtual bool CKeyStore::HaveCScript (const \fBCScriptID\fP & hash) const\fC [pure virtual]\fP"

.PP
Implemented in \fBCBasicKeyStore\fP\&.
.SS "virtual bool CKeyStore::HaveKey (const \fBCKeyID\fP & address) const\fC [pure virtual]\fP"

.PP
Implemented in \fBCCryptoKeyStore\fP, and \fBCBasicKeyStore\fP\&.
.SS "virtual bool CKeyStore::HaveWatchOnly (const \fBCScript\fP & dest) const\fC [pure virtual]\fP"

.PP
Implemented in \fBCBasicKeyStore\fP\&.
.SS "virtual bool CKeyStore::HaveWatchOnly () const\fC [pure virtual]\fP"

.PP
Implemented in \fBCBasicKeyStore\fP\&.
.SS "virtual bool CKeyStore::RemoveWatchOnly (const \fBCScript\fP & dest)\fC [pure virtual]\fP"

.PP
Implemented in \fBCWallet\fP, and \fBCBasicKeyStore\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCCriticalSection\fP CKeyStore::cs_KeyStore\fC [mutable]\fP, \fC [protected]\fP"

.PP
Definition at line 28 of file keystore\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
