.TH "CKeyMetadata" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CKeyMetadata \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <walletdb\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCKeyMetadata\fP ()"
.br
.ti -1c
.RI "\fBCKeyMetadata\fP (\fBint64_t\fP nCreateTime_)"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int \fBnVersion\fP)"
.br
.ti -1c
.RI "void \fBSetNull\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnVersion\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnCreateTime\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBCURRENT_VERSION\fP =1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file walletdb\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CKeyMetadata::CKeyMetadata ()\fC [inline]\fP"

.PP
Definition at line 48 of file walletdb\&.h\&.
.SS "CKeyMetadata::CKeyMetadata (\fBint64_t\fP nCreateTime_)\fC [inline]\fP"

.PP
Definition at line 52 of file walletdb\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream , typename Operation > void CKeyMetadata::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 61 of file walletdb\&.h\&.
.SS "void CKeyMetadata::SetNull ()\fC [inline]\fP"

.PP
Definition at line 67 of file walletdb\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CKeyMetadata::ADD_SERIALIZE_METHODS"

.PP
Definition at line 58 of file walletdb\&.h\&.
.SS "const int CKeyMetadata::CURRENT_VERSION =1\fC [static]\fP"

.PP
Definition at line 44 of file walletdb\&.h\&.
.SS "\fBint64_t\fP CKeyMetadata::nCreateTime"

.PP
Definition at line 46 of file walletdb\&.h\&.
.SS "int CKeyMetadata::nVersion"

.PP
Definition at line 45 of file walletdb\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
