.TH "CKey" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CKey \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <key\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCKey\fP ()"
.br
.ti -1c
.RI "\fBCKey\fP (const \fBCKey\fP &secret)"
.br
.ti -1c
.RI "\fB~CKey\fP ()"
.br
.ti -1c
.RI "template<typename T > void \fBSet\fP (const T pbegin, const T pend, bool fCompressedIn)"
.br
.ti -1c
.RI "unsigned int \fBsize\fP () const "
.br
.ti -1c
.RI "const unsigned char * \fBbegin\fP () const "
.br
.ti -1c
.RI "const unsigned char * \fBend\fP () const "
.br
.ti -1c
.RI "bool \fBIsValid\fP () const "
.br
.ti -1c
.RI "bool \fBIsCompressed\fP () const "
.br
.ti -1c
.RI "bool \fBSetPrivKey\fP (const \fBCPrivKey\fP &vchPrivKey, bool fCompressed)"
.br
.ti -1c
.RI "void \fBMakeNewKey\fP (bool fCompressed)"
.br
.ti -1c
.RI "\fBCPrivKey\fP \fBGetPrivKey\fP () const "
.br
.ti -1c
.RI "\fBCPubKey\fP \fBGetPubKey\fP () const "
.br
.ti -1c
.RI "bool \fBSign\fP (const \fBuint256\fP &\fBhash\fP, std::vector< unsigned char > &vchSig, \fBuint32_t\fP test_case=0) const "
.br
.ti -1c
.RI "bool \fBSignCompact\fP (const \fBuint256\fP &\fBhash\fP, std::vector< unsigned char > &vchSig) const "
.br
.ti -1c
.RI "bool \fBDerive\fP (\fBCKey\fP &keyChild, unsigned char ccChild[32], unsigned int nChild, const unsigned char cc[32]) const "
.br
.ti -1c
.RI "bool \fBVerifyPubKey\fP (const \fBCPubKey\fP &vchPubKey) const "
.br
.ti -1c
.RI "bool \fBLoad\fP (\fBCPrivKey\fP &privkey, \fBCPubKey\fP &vchPubKey, bool fSkipCheck)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBCheckSignatureElement\fP (const unsigned char *vch, int len, bool half)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCKey\fP &a, const \fBCKey\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
An encapsulated private key\&. 
.PP
Definition at line 29 of file key\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CKey::CKey ()\fC [inline]\fP"

.PP
Definition at line 46 of file key\&.h\&.
.SS "CKey::CKey (const \fBCKey\fP & secret)\fC [inline]\fP"

.PP
Definition at line 51 of file key\&.h\&.
.SS "CKey::~CKey ()\fC [inline]\fP"

.PP
Definition at line 57 of file key\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "const unsigned char* CKey::begin () const\fC [inline]\fP"

.PP
Definition at line 84 of file key\&.h\&.
.SS "static bool CKey::CheckSignatureElement (const unsigned char * vch, int len, bool half)\fC [static]\fP"

.SS "bool CKey::Derive (\fBCKey\fP & keyChild, unsigned char ccChild[32], unsigned int nChild, const unsigned char cc[32]) const"

.PP
Definition at line 238 of file key\&.cpp\&.
.SS "const unsigned char* CKey::end () const\fC [inline]\fP"

.PP
Definition at line 85 of file key\&.h\&.
.SS "\fBCPrivKey\fP CKey::GetPrivKey () const"

.PP
Definition at line 156 of file key\&.cpp\&.
.SS "\fBCPubKey\fP CKey::GetPubKey () const"

.PP
Definition at line 169 of file key\&.cpp\&.
.SS "bool CKey::IsCompressed () const\fC [inline]\fP"

.PP
Definition at line 91 of file key\&.h\&.
.SS "bool CKey::IsValid () const\fC [inline]\fP"

.PP
Definition at line 88 of file key\&.h\&.
.SS "bool CKey::Load (\fBCPrivKey\fP & privkey, \fBCPubKey\fP & vchPubKey, bool fSkipCheck = \fCfalse\fP)"

.PP
Definition at line 226 of file key\&.cpp\&.
.SS "void CKey::MakeNewKey (bool fCompressed)"

.PP
Definition at line 139 of file key\&.cpp\&.
.SS "template<typename T > void CKey::Set (const T pbegin, const T pend, bool fCompressedIn)\fC [inline]\fP"

.PP
Definition at line 68 of file key\&.h\&.
.SS "bool CKey::SetPrivKey (const \fBCPrivKey\fP & vchPrivKey, bool fCompressed)"

.PP
Definition at line 148 of file key\&.cpp\&.
.SS "bool CKey::Sign (const \fBuint256\fP & hash, std::vector< unsigned char > & vchSig, \fBuint32_t\fP test_case = \fC0\fP) const"
Create a DER-serialized signature\&. The test_case parameter tweaks the deterministic nonce\&. 
.PP
Definition at line 182 of file key\&.cpp\&.
.SS "bool CKey::SignCompact (const \fBuint256\fP & hash, std::vector< unsigned char > & vchSig) const"

.PP
Definition at line 211 of file key\&.cpp\&.
.SS "unsigned int CKey::size () const\fC [inline]\fP"

.PP
Definition at line 83 of file key\&.h\&.
.SS "bool CKey::VerifyPubKey (const \fBCPubKey\fP & vchPubKey) const"
Verify thoroughly whether a private key and a public key match\&. This is done using a different mechanism than just regenerating it\&. 
.PP
Definition at line 197 of file key\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "bool operator== (const \fBCKey\fP & a, const \fBCKey\fP & b)\fC [friend]\fP"

.PP
Definition at line 61 of file key\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
