.TH "CKeyPool" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CKeyPool \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wallet\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCKeyPool\fP ()"
.br
.ti -1c
.RI "\fBCKeyPool\fP (const \fBCPubKey\fP &vchPubKeyIn)"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint64_t\fP \fBnTime\fP"
.br
.ti -1c
.RI "\fBCPubKey\fP \fBvchPubKey\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A key pool entry 
.PP
Definition at line 69 of file wallet\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CKeyPool::CKeyPool ()\fC [inline]\fP"

.PP
Definition at line 75 of file wallet\&.h\&.
.SS "CKeyPool::CKeyPool (const \fBCPubKey\fP & vchPubKeyIn)\fC [inline]\fP"

.PP
Definition at line 80 of file wallet\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream , typename Operation > void CKeyPool::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 89 of file wallet\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CKeyPool::ADD_SERIALIZE_METHODS"

.PP
Definition at line 86 of file wallet\&.h\&.
.SS "\fBint64_t\fP CKeyPool::nTime"

.PP
Definition at line 72 of file wallet\&.h\&.
.SS "\fBCPubKey\fP CKeyPool::vchPubKey"

.PP
Definition at line 73 of file wallet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
