.TH "CKeyID_B" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CKeyID_B \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <smessage\&.h>\fP
.PP
Inherits \fBCKeyID\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP * \fBGetPPN\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 180 of file smessage\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBuint32_t\fP* CKeyID_B::GetPPN ()\fC [inline]\fP"

.PP
Definition at line 183 of file smessage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
