.TH "CKeyID" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CKeyID \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pubkey\&.h>\fP
.PP
Inherits \fBuint160\fP\&.
.PP
Inherited by \fBCKeyID_B\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCKeyID\fP ()"
.br
.ti -1c
.RI "\fBCKeyID\fP (const \fBuint160\fP &in)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
secp256k1: const unsigned int PRIVATE_KEY_SIZE = 279; const unsigned int PUBLIC_KEY_SIZE = 65; const unsigned int SIGNATURE_SIZE = 72;
.PP
see www\&.keylength\&.com script supports up to 75 for single byte pushA reference to a \fBCKey\fP: the Hash160 of its serialized public key 
.PP
Definition at line 27 of file pubkey\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CKeyID::CKeyID ()\fC [inline]\fP"

.PP
Definition at line 30 of file pubkey\&.h\&.
.SS "CKeyID::CKeyID (const \fBuint160\fP & in)\fC [inline]\fP"

.PP
Definition at line 31 of file pubkey\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
