.TH "CKeyStoreIsMineVisitor" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CKeyStoreIsMineVisitor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< bool >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCKeyStoreIsMineVisitor\fP (const \fBCKeyStore\fP *keystoreIn)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCNoDestination\fP &dest) const "
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCKeyID\fP &keyID) const "
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCScriptID\fP &scriptID) const "
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCStealthAddress\fP &stxAddr) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2592 of file script\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CKeyStoreIsMineVisitor::CKeyStoreIsMineVisitor (const \fBCKeyStore\fP * keystoreIn)\fC [inline]\fP"

.PP
Definition at line 2597 of file script\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CKeyStoreIsMineVisitor::operator() (const \fBCNoDestination\fP & dest) const\fC [inline]\fP"

.PP
Definition at line 2598 of file script\&.cpp\&.
.SS "bool CKeyStoreIsMineVisitor::operator() (const \fBCKeyID\fP & keyID) const\fC [inline]\fP"

.PP
Definition at line 2599 of file script\&.cpp\&.
.SS "bool CKeyStoreIsMineVisitor::operator() (const \fBCScriptID\fP & scriptID) const\fC [inline]\fP"

.PP
Definition at line 2600 of file script\&.cpp\&.
.SS "bool CKeyStoreIsMineVisitor::operator() (const \fBCStealthAddress\fP & stxAddr) const\fC [inline]\fP"

.PP
Definition at line 2601 of file script\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
