.TH "/home/dev/ds-160209/src/cleanse.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/cleanse.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmemory_cleanse\fP (void *ptr, size_t len)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void memory_cleanse (void * ptr, size_t len)"

.PP
Definition at line 10 of file cleanse\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
