.TH "CLevelDBWrapper" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CLevelDBWrapper \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <leveldbwrapper\&.h>\fP
.PP
Inherited by \fBCBlockTreeDB\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCLevelDBWrapper\fP (const boost::filesystem::path &path, size_t nCacheSize, bool fMemory=false, bool fWipe=false)"
.br
.ti -1c
.RI "\fB~CLevelDBWrapper\fP ()"
.br
.ti -1c
.RI "template<typename K , typename V > bool \fBRead\fP (const K &key, V &\fBvalue\fP) const   throw (leveldb_error)"
.br
.ti -1c
.RI "template<typename K , typename V > bool \fBWrite\fP (const K &key, const V &\fBvalue\fP, bool fSync=false)  throw (leveldb_error)"
.br
.ti -1c
.RI "template<typename K > bool \fBExists\fP (const K &key) const   throw (leveldb_error)"
.br
.ti -1c
.RI "template<typename K > bool \fBErase\fP (const K &key, bool fSync=false)  throw (leveldb_error)"
.br
.ti -1c
.RI "bool \fBWriteBatch\fP (\fBCLevelDBBatch\fP &batch, bool fSync=false)  throw (leveldb_error)"
.br
.ti -1c
.RI "bool \fBFlush\fP ()"
.br
.ti -1c
.RI "bool \fBSync\fP ()  throw (leveldb_error)"
.br
.ti -1c
.RI "\fBleveldb::Iterator\fP * \fBNewIterator\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file leveldbwrapper\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CLevelDBWrapper::CLevelDBWrapper (const boost::filesystem::path & path, size_t nCacheSize, bool fMemory = \fCfalse\fP, bool fWipe = \fCfalse\fP)"

.PP
Definition at line 44 of file leveldbwrapper\&.cpp\&.
.SS "CLevelDBWrapper::~CLevelDBWrapper ()"

.PP
Definition at line 69 of file leveldbwrapper\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename K > bool CLevelDBWrapper::Erase (const K & key, bool fSync = \fCfalse\fP)\fBleveldb_error\fP\fC [inline]\fP"

.PP
Definition at line 143 of file leveldbwrapper\&.h\&.
.SS "template<typename K > bool CLevelDBWrapper::Exists (const K & key) const\fBleveldb_error\fP\fC [inline]\fP"

.PP
Definition at line 124 of file leveldbwrapper\&.h\&.
.SS "bool CLevelDBWrapper::Flush ()\fC [inline]\fP"

.PP
Definition at line 153 of file leveldbwrapper\&.h\&.
.SS "\fBleveldb::Iterator\fP* CLevelDBWrapper::NewIterator ()\fC [inline]\fP"

.PP
Definition at line 165 of file leveldbwrapper\&.h\&.
.SS "template<typename K , typename V > bool CLevelDBWrapper::Read (const K & key, V & value) const\fBleveldb_error\fP\fC [inline]\fP"

.PP
Definition at line 91 of file leveldbwrapper\&.h\&.
.SS "bool CLevelDBWrapper::Sync ()\fBleveldb_error\fP\fC [inline]\fP"

.PP
Definition at line 158 of file leveldbwrapper\&.h\&.
.SS "template<typename K , typename V > bool CLevelDBWrapper::Write (const K & key, const V & value, bool fSync = \fCfalse\fP)\fBleveldb_error\fP\fC [inline]\fP"

.PP
Definition at line 116 of file leveldbwrapper\&.h\&.
.SS "bool CLevelDBWrapper::WriteBatch (\fBCLevelDBBatch\fP & batch, bool fSync = \fCfalse\fP)\fBleveldb_error\fP"

.PP
Definition at line 81 of file leveldbwrapper\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
