.TH "/home/dev/ds-160209/src/clientversion.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/clientversion.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCLIENT_VERSION_MAJOR\fP   1"
.br
.ti -1c
.RI "#define \fBCLIENT_VERSION_MINOR\fP   0"
.br
.ti -1c
.RI "#define \fBCLIENT_VERSION_REVISION\fP   0"
.br
.ti -1c
.RI "#define \fBCLIENT_VERSION_BUILD\fP   0"
.br
.ti -1c
.RI "#define \fBCLIENT_VERSION_IS_RELEASE\fP   false"
.br
.ti -1c
.RI "#define \fBSTRINGIZE\fP(\fBX\fP)   \fBDO_STRINGIZE\fP(\fBX\fP)"
.br
.ti -1c
.RI "#define \fBDO_STRINGIZE\fP(\fBX\fP)   #\fBX\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CLIENT_VERSION_BUILD   0"

.PP
Definition at line 12 of file clientversion\&.h\&.
.SS "#define CLIENT_VERSION_IS_RELEASE   false"

.PP
Definition at line 15 of file clientversion\&.h\&.
.SS "#define CLIENT_VERSION_MAJOR   1"

.PP
Definition at line 9 of file clientversion\&.h\&.
.SS "#define CLIENT_VERSION_MINOR   0"

.PP
Definition at line 10 of file clientversion\&.h\&.
.SS "#define CLIENT_VERSION_REVISION   0"

.PP
Definition at line 11 of file clientversion\&.h\&.
.SS "#define DO_STRINGIZE(\fBX\fP)   #\fBX\fP"

.PP
Definition at line 20 of file clientversion\&.h\&.
.SS "#define STRINGIZE(\fBX\fP)   \fBDO_STRINGIZE\fP(\fBX\fP)"

.PP
Definition at line 19 of file clientversion\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
