.TH "CMainParams" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMainParams \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCChainParams\fP\&.
.PP
Inherited by \fBCTestNetParams\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCMainParams\fP ()"
.br
.ti -1c
.RI "virtual const \fBCBlock\fP & \fBGenesisBlock\fP () const "
.br
.ti -1c
.RI "virtual \fBNetwork\fP \fBNetworkID\fP () const "
.br
.ti -1c
.RI "virtual const vector< \fBCAddress\fP > & \fBFixedSeeds\fP () const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBCBlock\fP \fBgenesis\fP"
.br
.ti -1c
.RI "vector< \fBCAddress\fP > \fBvFixedSeeds\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 52 of file chainparams\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CMainParams::CMainParams ()\fC [inline]\fP"

.PP
Definition at line 54 of file chainparams\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual const vector<\fBCAddress\fP>& CMainParams::FixedSeeds () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBCChainParams\fP\&.
.PP
Definition at line 122 of file chainparams\&.cpp\&.
.SS "virtual const \fBCBlock\fP& CMainParams::GenesisBlock () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBCChainParams\fP\&.
.PP
Definition at line 119 of file chainparams\&.cpp\&.
.SS "virtual \fBNetwork\fP CMainParams::NetworkID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBCChainParams\fP\&.
.PP
Reimplemented in \fBCTestNetParams\fP\&.
.PP
Definition at line 120 of file chainparams\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCBlock\fP CMainParams::genesis\fC [protected]\fP"

.PP
Definition at line 126 of file chainparams\&.cpp\&.
.SS "vector<\fBCAddress\fP> CMainParams::vFixedSeeds\fC [protected]\fP"

.PP
Definition at line 127 of file chainparams\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
