.TH "CMasterKey" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMasterKey \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crypter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.ti -1c
.RI "\fBCMasterKey\fP ()"
.br
.ti -1c
.RI "\fBCMasterKey\fP (unsigned int \fBnDerivationMethodIndex\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< unsigned char > \fBvchCryptedKey\fP"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBvchSalt\fP"
.br
.ti -1c
.RI "unsigned int \fBnDerivationMethod\fP"
.br
.ti -1c
.RI "unsigned int \fBnDeriveIterations\fP"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBvchOtherDerivationParameters\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Master key for wallet encryption 
.PP
Definition at line 31 of file crypter\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CMasterKey::CMasterKey ()\fC [inline]\fP"

.PP
Definition at line 55 of file crypter\&.h\&.
.SS "CMasterKey::CMasterKey (unsigned int nDerivationMethodIndex)\fC [inline]\fP"

.PP
Definition at line 64 of file crypter\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream , typename Operation > void CMasterKey::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 47 of file crypter\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CMasterKey::ADD_SERIALIZE_METHODS"

.PP
Definition at line 44 of file crypter\&.h\&.
.SS "unsigned int CMasterKey::nDerivationMethod"

.PP
Definition at line 38 of file crypter\&.h\&.
.SS "unsigned int CMasterKey::nDeriveIterations"

.PP
Definition at line 39 of file crypter\&.h\&.
.SS "std::vector<unsigned char> CMasterKey::vchCryptedKey"

.PP
Definition at line 34 of file crypter\&.h\&.
.SS "std::vector<unsigned char> CMasterKey::vchOtherDerivationParameters"

.PP
Definition at line 42 of file crypter\&.h\&.
.SS "std::vector<unsigned char> CMasterKey::vchSalt"

.PP
Definition at line 35 of file crypter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
