.TH "CMedianFilter< T >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMedianFilter< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <util\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCMedianFilter\fP (unsigned int \fBsize\fP, T initial_value)"
.br
.ti -1c
.RI "void \fBinput\fP (T \fBvalue\fP)"
.br
.ti -1c
.RI "T \fBmedian\fP () const "
.br
.ti -1c
.RI "int \fBsize\fP () const "
.br
.ti -1c
.RI "std::vector< T > \fBsorted\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>class CMedianFilter< T >"
Median filter over a stream of values\&. Returns the median of the last N numbers 
.PP
Definition at line 505 of file util\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBCMedianFilter\fP< T >::\fBCMedianFilter\fP (unsigned int size, T initial_value)\fC [inline]\fP"

.PP
Definition at line 512 of file util\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> void \fBCMedianFilter\fP< T >::input (T value)\fC [inline]\fP"

.PP
Definition at line 520 of file util\&.h\&.
.SS "template<typename T> T \fBCMedianFilter\fP< T >::median () const\fC [inline]\fP"

.PP
Definition at line 533 of file util\&.h\&.
.SS "template<typename T> int \fBCMedianFilter\fP< T >::size () const\fC [inline]\fP"

.PP
Definition at line 547 of file util\&.h\&.
.SS "template<typename T> std::vector<T> \fBCMedianFilter\fP< T >::sorted () const\fC [inline]\fP"

.PP
Definition at line 552 of file util\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
