.TH "CMessageHeader" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMessageHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <protocol\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBCOMMAND_SIZE\fP =12, \fBMESSAGE_SIZE_SIZE\fP =sizeof(int), \fBCHECKSUM_SIZE\fP =sizeof(int), \fBMESSAGE_SIZE_OFFSET\fP =MESSAGE_START_SIZE+COMMAND_SIZE, \fBCHECKSUM_OFFSET\fP =MESSAGE_SIZE_OFFSET+MESSAGE_SIZE_SIZE, \fBHEADER_SIZE\fP =MESSAGE_START_SIZE+COMMAND_SIZE+MESSAGE_SIZE_SIZE+CHECKSUM_SIZE }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCMessageHeader\fP ()"
.br
.ti -1c
.RI "\fBCMessageHeader\fP (const char *pszCommand, unsigned int nMessageSizeIn)"
.br
.ti -1c
.RI "std::string \fBGetCommand\fP () const "
.br
.ti -1c
.RI "bool \fBIsValid\fP () const "
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.ti -1c
.RI "char \fBpchMessageStart\fP [\fBMESSAGE_START_SIZE\fP]"
.br
.ti -1c
.RI "char \fBpchCommand\fP [\fBCOMMAND_SIZE\fP]"
.br
.ti -1c
.RI "unsigned int \fBnMessageSize\fP"
.br
.ti -1c
.RI "unsigned int \fBnChecksum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Message header\&. (4) message start\&. (12) command\&. (4) size\&. (4) checksum\&. 
.PP
Definition at line 28 of file protocol\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICOMMAND_SIZE \fP\fP
.TP
\fB\fIMESSAGE_SIZE_SIZE \fP\fP
.TP
\fB\fICHECKSUM_SIZE \fP\fP
.TP
\fB\fIMESSAGE_SIZE_OFFSET \fP\fP
.TP
\fB\fICHECKSUM_OFFSET \fP\fP
.TP
\fB\fIHEADER_SIZE \fP\fP
.PP
Definition at line 49 of file protocol\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CMessageHeader::CMessageHeader ()"

.PP
Definition at line 38 of file protocol\&.cpp\&.
.SS "CMessageHeader::CMessageHeader (const char * pszCommand, unsigned int nMessageSizeIn)"

.PP
Definition at line 47 of file protocol\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string CMessageHeader::GetCommand () const"

.PP
Definition at line 55 of file protocol\&.cpp\&.
.SS "bool CMessageHeader::IsValid () const"

.PP
Definition at line 63 of file protocol\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CMessageHeader::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 40 of file protocol\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CMessageHeader::ADD_SERIALIZE_METHODS"

.PP
Definition at line 37 of file protocol\&.h\&.
.SS "unsigned int CMessageHeader::nChecksum"

.PP
Definition at line 61 of file protocol\&.h\&.
.SS "unsigned int CMessageHeader::nMessageSize"

.PP
Definition at line 60 of file protocol\&.h\&.
.SS "char CMessageHeader::pchCommand[\fBCOMMAND_SIZE\fP]"

.PP
Definition at line 59 of file protocol\&.h\&.
.SS "char CMessageHeader::pchMessageStart[\fBMESSAGE_START_SIZE\fP]"

.PP
Definition at line 58 of file protocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
