.TH "CMutableTransaction" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMutableTransaction \- A mutable version of \fBCTransaction\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transaction\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBDoS\fP (\fBint32_t\fP nDoSIn, bool fIn) const "
.br
.ti -1c
.RI "\fBCMutableTransaction\fP ()"
.br
.ti -1c
.RI "\fBCMutableTransaction\fP (const \fBCTransaction\fP &tx)"
.br
.ti -1c
.RI "\fBCMutableTransaction\fP (\fBint32_t\fP \fBnVersion\fP, \fBuint32_t\fP \fBnTime\fP, const std::vector< \fBCTxIn\fP > &\fBvin\fP, const std::vector< \fBCTxOut\fP > &\fBvout\fP, \fBuint32_t\fP \fBnLockTime\fP)"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int \fBnVersion\fP)"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetHash\fP () const "
.br
.ti -1c
.RI "std::string \fBToString\fP () const "
.br
.ti -1c
.RI "bool \fBIsNull\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint32_t\fP \fBnVersion\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBnTime\fP"
.br
.ti -1c
.RI "std::vector< \fBCTxIn\fP > \fBvin\fP"
.br
.ti -1c
.RI "std::vector< \fBCTxOut\fP > \fBvout\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBnLockTime\fP"
.br
.ti -1c
.RI "\fBint32_t\fP \fBnDoS\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBint32_t\fP \fBCURRENT_VERSION\fP = 1"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCMutableTransaction\fP &a, const \fBCMutableTransaction\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBCMutableTransaction\fP &a, const \fBCMutableTransaction\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A mutable version of \fBCTransaction\fP\&. 
.PP
Definition at line 351 of file transaction\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CMutableTransaction::CMutableTransaction ()"

.PP
Definition at line 112 of file transaction\&.cpp\&.
.SS "CMutableTransaction::CMutableTransaction (const \fBCTransaction\fP & tx)"

.PP
Definition at line 122 of file transaction\&.cpp\&.
.SS "CMutableTransaction::CMutableTransaction (\fBint32_t\fP nVersion, \fBuint32_t\fP nTime, const std::vector< \fBCTxIn\fP > & vin, const std::vector< \fBCTxOut\fP > & vout, \fBuint32_t\fP nLockTime)\fC [inline]\fP"

.PP
Definition at line 367 of file transaction\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CMutableTransaction::DoS (\fBint32_t\fP nDoSIn, bool fIn) const\fC [inline]\fP"

.PP
Definition at line 362 of file transaction\&.h\&.
.SS "\fBuint256\fP CMutableTransaction::GetHash () const"
Compute the hash of this \fBCMutableTransaction\fP\&. This is computed on the fly, as opposed to \fBGetHash()\fP in \fBCTransaction\fP, which uses a cached result\&. 
.PP
Definition at line 125 of file transaction\&.cpp\&.
.SS "bool CMutableTransaction::IsNull () const\fC [inline]\fP"

.PP
Definition at line 390 of file transaction\&.h\&.
.SS "template<typename Stream , typename Operation > void CMutableTransaction::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 375 of file transaction\&.h\&.
.SS "std::string CMutableTransaction::ToString () const"

.PP
Definition at line 130 of file transaction\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "bool operator!= (const \fBCMutableTransaction\fP & a, const \fBCMutableTransaction\fP & b)\fC [friend]\fP"

.PP
Definition at line 404 of file transaction\&.h\&.
.SS "bool operator== (const \fBCMutableTransaction\fP & a, const \fBCMutableTransaction\fP & b)\fC [friend]\fP"

.PP
Definition at line 395 of file transaction\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CMutableTransaction::ADD_SERIALIZE_METHODS"

.PP
Definition at line 372 of file transaction\&.h\&.
.SS "const \fBint32_t\fP CMutableTransaction::CURRENT_VERSION = 1\fC [static]\fP"

.PP
Definition at line 353 of file transaction\&.h\&.
.SS "\fBint32_t\fP CMutableTransaction::nDoS\fC [mutable]\fP"

.PP
Definition at line 361 of file transaction\&.h\&.
.SS "\fBuint32_t\fP CMutableTransaction::nLockTime"

.PP
Definition at line 358 of file transaction\&.h\&.
.SS "\fBuint32_t\fP CMutableTransaction::nTime"

.PP
Definition at line 355 of file transaction\&.h\&.
.SS "\fBint32_t\fP CMutableTransaction::nVersion"

.PP
Definition at line 354 of file transaction\&.h\&.
.SS "std::vector<\fBCTxIn\fP> CMutableTransaction::vin"

.PP
Definition at line 356 of file transaction\&.h\&.
.SS "std::vector<\fBCTxOut\fP> CMutableTransaction::vout"

.PP
Definition at line 357 of file transaction\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
