.TH "CMutexLock< Mutex >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMutexLock< Mutex > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sync\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCMutexLock\fP (Mutex &mutexIn, const char *pszName, const char *pszFile, int nLine, bool fTry=false)"
.br
.ti -1c
.RI "\fB~CMutexLock\fP ()"
.br
.ti -1c
.RI "\fBoperator bool\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Mutex>class CMutexLock< Mutex >"
Wrapper around boost::unique_lock<Mutex> 
.PP
Definition at line 108 of file sync\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Mutex > \fBCMutexLock\fP< Mutex >::\fBCMutexLock\fP (Mutex & mutexIn, const char * pszName, const char * pszFile, int nLine, bool fTry = \fCfalse\fP)\fC [inline]\fP"

.PP
Definition at line 137 of file sync\&.h\&.
.SS "template<typename Mutex > \fBCMutexLock\fP< Mutex >::~\fBCMutexLock\fP ()\fC [inline]\fP"

.PP
Definition at line 145 of file sync\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Mutex > \fBCMutexLock\fP< Mutex >::operator bool ()\fC [inline]\fP"

.PP
Definition at line 151 of file sync\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
