.TH "CNodeStats" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CNodeStats \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <net\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNodeId\fP \fBnodeid\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBnServices\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnLastSend\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnLastRecv\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnTimeConnected\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnTimeOffset\fP"
.br
.ti -1c
.RI "std::string \fBaddrName\fP"
.br
.ti -1c
.RI "int \fBnVersion\fP"
.br
.ti -1c
.RI "std::string \fBcleanSubVer\fP"
.br
.ti -1c
.RI "std::string \fBstrSubVer\fP"
.br
.ti -1c
.RI "bool \fBfInbound\fP"
.br
.ti -1c
.RI "int \fBnStartingHeight\fP"
.br
.ti -1c
.RI "int \fBnMisbehavior\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBnSendBytes\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBnRecvBytes\fP"
.br
.ti -1c
.RI "bool \fBfSyncNode\fP"
.br
.ti -1c
.RI "double \fBdPingTime\fP"
.br
.ti -1c
.RI "double \fBdPingWait\fP"
.br
.ti -1c
.RI "std::string \fBaddrLocal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 131 of file net\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string CNodeStats::addrLocal"

.PP
Definition at line 152 of file net\&.h\&.
.SS "std::string CNodeStats::addrName"

.PP
Definition at line 140 of file net\&.h\&.
.SS "std::string CNodeStats::cleanSubVer"

.PP
Definition at line 142 of file net\&.h\&.
.SS "double CNodeStats::dPingTime"

.PP
Definition at line 150 of file net\&.h\&.
.SS "double CNodeStats::dPingWait"

.PP
Definition at line 151 of file net\&.h\&.
.SS "bool CNodeStats::fInbound"

.PP
Definition at line 144 of file net\&.h\&.
.SS "bool CNodeStats::fSyncNode"

.PP
Definition at line 149 of file net\&.h\&.
.SS "\fBint64_t\fP CNodeStats::nLastRecv"

.PP
Definition at line 137 of file net\&.h\&.
.SS "\fBint64_t\fP CNodeStats::nLastSend"

.PP
Definition at line 136 of file net\&.h\&.
.SS "int CNodeStats::nMisbehavior"

.PP
Definition at line 146 of file net\&.h\&.
.SS "\fBNodeId\fP CNodeStats::nodeid"

.PP
Definition at line 134 of file net\&.h\&.
.SS "\fBuint64_t\fP CNodeStats::nRecvBytes"

.PP
Definition at line 148 of file net\&.h\&.
.SS "\fBuint64_t\fP CNodeStats::nSendBytes"

.PP
Definition at line 147 of file net\&.h\&.
.SS "\fBuint64_t\fP CNodeStats::nServices"

.PP
Definition at line 135 of file net\&.h\&.
.SS "int CNodeStats::nStartingHeight"

.PP
Definition at line 145 of file net\&.h\&.
.SS "\fBint64_t\fP CNodeStats::nTimeConnected"

.PP
Definition at line 138 of file net\&.h\&.
.SS "\fBint64_t\fP CNodeStats::nTimeOffset"

.PP
Definition at line 139 of file net\&.h\&.
.SS "int CNodeStats::nVersion"

.PP
Definition at line 141 of file net\&.h\&.
.SS "std::string CNodeStats::strSubVer"

.PP
Definition at line 143 of file net\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
