.TH "CNode" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CNode \- Information about a peer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <net\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCNode\fP (\fBSOCKET\fP hSocketIn, \fBCAddress\fP addrIn, std::string addrNameIn='', bool fInboundIn=false)"
.br
.ti -1c
.RI "\fB~CNode\fP ()"
.br
.ti -1c
.RI "\fBNodeId\fP \fBGetId\fP () const "
.br
.ti -1c
.RI "int \fBGetRefCount\fP ()"
.br
.ti -1c
.RI "unsigned int \fBGetTotalRecvSize\fP ()"
.br
.ti -1c
.RI "bool \fBReceiveMsgBytes\fP (const char *pch, unsigned int nBytes)"
.br
.ti -1c
.RI "void \fBSetRecvVersion\fP (int nVersionIn)"
.br
.ti -1c
.RI "\fBCNode\fP * \fBAddRef\fP ()"
.br
.ti -1c
.RI "void \fBRelease\fP ()"
.br
.ti -1c
.RI "void \fBAddAddressKnown\fP (const \fBCAddress\fP &\fBaddr\fP)"
.br
.ti -1c
.RI "void \fBPushAddress\fP (const \fBCAddress\fP &\fBaddr\fP)"
.br
.ti -1c
.RI "void \fBAddInventoryKnown\fP (const \fBCInv\fP &inv)"
.br
.ti -1c
.RI "void \fBPushInventory\fP (const \fBCInv\fP &inv)"
.br
.ti -1c
.RI "void \fBAskFor\fP (const \fBCInv\fP &inv)"
.br
.ti -1c
.RI "void \fBBeginMessage\fP (const char *pszCommand) \fBEXCLUSIVE_LOCK_FUNCTION\fP(\fBcs_vSend\fP)"
.br
.ti -1c
.RI "void \fBAbortMessage\fP () \fBUNLOCK_FUNCTION\fP(\fBcs_vSend\fP)"
.br
.ti -1c
.RI "void \fBEndMessage\fP () \fBUNLOCK_FUNCTION\fP(\fBcs_vSend\fP)"
.br
.ti -1c
.RI "void \fBPushVersion\fP ()"
.br
.ti -1c
.RI "void \fBPushMessage\fP (const char *pszCommand)"
.br
.ti -1c
.RI "template<typename T1 > void \fBPushMessage\fP (const char *pszCommand, const T1 &a1)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 > void \fBPushMessage\fP (const char *pszCommand, const T1 &a1, const T2 &a2)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename T3 > void \fBPushMessage\fP (const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename T3 , typename T4 > void \fBPushMessage\fP (const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3, const T4 &a4)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > void \fBPushMessage\fP (const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3, const T4 &a4, const T5 &a5)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > void \fBPushMessage\fP (const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3, const T4 &a4, const T5 &a5, const T6 &a6)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 > void \fBPushMessage\fP (const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3, const T4 &a4, const T5 &a5, const T6 &a6, const T7 &a7)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 > void \fBPushMessage\fP (const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3, const T4 &a4, const T5 &a5, const T6 &a6, const T7 &a7, const T8 &a8)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > void \fBPushMessage\fP (const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3, const T4 &a4, const T5 &a5, const T6 &a6, const T7 &a7, const T8 &a8, const T9 &a9)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 > void \fBPushMessage\fP (const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3, const T4 &a4, const T5 &a5, const T6 &a6, const T7 &a7, const T8 &a8, const T9 &a9, const T10 &a10)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 > void \fBPushMessage\fP (const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3, const T4 &a4, const T5 &a5, const T6 &a6, const T7 &a7, const T8 &a8, const T9 &a9, const T10 &a10, const T11 &a11)"
.br
.ti -1c
.RI "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 > void \fBPushMessage\fP (const char *pszCommand, const T1 &a1, const T2 &a2, const T3 &a3, const T4 &a4, const T5 &a5, const T6 &a6, const T7 &a7, const T8 &a8, const T9 &a9, const T10 &a10, const T11 &a11, const T12 &a12)"
.br
.ti -1c
.RI "void \fBClearFulfilledRequest\fP (std::string strRequest)"
.br
.ti -1c
.RI "bool \fBHasFulfilledRequest\fP (std::string strRequest)"
.br
.ti -1c
.RI "void \fBFulfilledRequest\fP (std::string strRequest)"
.br
.ti -1c
.RI "bool \fBIsSubscribed\fP (unsigned int nChannel)"
.br
.ti -1c
.RI "void \fBSubscribe\fP (unsigned int nChannel, unsigned int nHops=0)"
.br
.ti -1c
.RI "void \fBCancelSubscribe\fP (unsigned int nChannel)"
.br
.ti -1c
.RI "void \fBCloseSocketDisconnect\fP ()"
.br
.ti -1c
.RI "bool \fBMisbehaving\fP (int howmuch)"
.br
.ti -1c
.RI "void \fBcopyStats\fP (\fBCNodeStats\fP &\fBstats\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBClearBanned\fP ()"
.br
.ti -1c
.RI "static bool \fBIsBanned\fP (\fBCNetAddr\fP ip)"
.br
.ti -1c
.RI "static void \fBRecordBytesRecv\fP (\fBuint64_t\fP bytes)"
.br
.ti -1c
.RI "static void \fBRecordBytesSent\fP (\fBuint64_t\fP bytes)"
.br
.ti -1c
.RI "static \fBuint64_t\fP \fBGetTotalBytesRecv\fP ()"
.br
.ti -1c
.RI "static \fBuint64_t\fP \fBGetTotalBytesSent\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint64_t\fP \fBnServices\fP"
.br
.ti -1c
.RI "\fBSOCKET\fP \fBhSocket\fP"
.br
.ti -1c
.RI "\fBCDataStream\fP \fBssSend\fP"
.br
.ti -1c
.RI "size_t \fBnSendSize\fP"
.br
.ti -1c
.RI "size_t \fBnSendOffset\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBnSendBytes\fP"
.br
.ti -1c
.RI "std::deque< \fBCSerializeData\fP > \fBvSendMsg\fP"
.br
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_vSend\fP"
.br
.ti -1c
.RI "std::deque< \fBCInv\fP > \fBvRecvGetData\fP"
.br
.ti -1c
.RI "std::deque< \fBCNetMessage\fP > \fBvRecvMsg\fP"
.br
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_vRecvMsg\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBnRecvBytes\fP"
.br
.ti -1c
.RI "int \fBnRecvVersion\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnLastSend\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnLastRecv\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnTimeConnected\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnTimeOffset\fP"
.br
.ti -1c
.RI "\fBCAddress\fP \fBaddr\fP"
.br
.ti -1c
.RI "std::string \fBaddrName\fP"
.br
.ti -1c
.RI "\fBCService\fP \fBaddrLocal\fP"
.br
.ti -1c
.RI "int \fBnVersion\fP"
.br
.ti -1c
.RI "std::string \fBstrSubVer\fP"
.br
.ti -1c
.RI "std::string \fBcleanSubVer\fP"
.br
.ti -1c
.RI "bool \fBfOneShot\fP"
.br
.ti -1c
.RI "bool \fBfClient\fP"
.br
.ti -1c
.RI "bool \fBfInbound\fP"
.br
.ti -1c
.RI "bool \fBfNetworkNode\fP"
.br
.ti -1c
.RI "bool \fBfSuccessfullyConnected\fP"
.br
.ti -1c
.RI "bool \fBfDisconnect\fP"
.br
.ti -1c
.RI "bool \fBfRelayTxes\fP"
.br
.ti -1c
.RI "bool \fBfSandStorm\fP"
.br
.ti -1c
.RI "\fBCSemaphoreGrant\fP \fBgrantOutbound\fP"
.br
.ti -1c
.RI "int \fBnRefCount\fP"
.br
.ti -1c
.RI "\fBNodeId\fP \fBid\fP"
.br
.ti -1c
.RI "int \fBnMisbehavior\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBhashContinue\fP"
.br
.ti -1c
.RI "\fBCBlockIndex\fP * \fBpindexLastGetBlocksBegin\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBhashLastGetBlocksEnd\fP"
.br
.ti -1c
.RI "int \fBnStartingHeight\fP"
.br
.ti -1c
.RI "bool \fBfStartSync\fP"
.br
.ti -1c
.RI "std::vector< \fBCAddress\fP > \fBvAddrToSend\fP"
.br
.ti -1c
.RI "\fBmruset\fP< \fBCAddress\fP > \fBsetAddrKnown\fP"
.br
.ti -1c
.RI "bool \fBfGetAddr\fP"
.br
.ti -1c
.RI "std::set< \fBuint256\fP > \fBsetKnown\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBhashCheckpointKnown\fP"
.br
.ti -1c
.RI "\fBmruset\fP< \fBCInv\fP > \fBsetInventoryKnown\fP"
.br
.ti -1c
.RI "std::vector< \fBCInv\fP > \fBvInventoryToSend\fP"
.br
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_inventory\fP"
.br
.ti -1c
.RI "std::multimap< \fBint64_t\fP, \fBCInv\fP > \fBmapAskFor\fP"
.br
.ti -1c
.RI "\fBSecMsgNode\fP \fBsmsgData\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBnPingNonceSent\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnPingUsecStart\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnPingUsecTime\fP"
.br
.ti -1c
.RI "bool \fBfPingQueued\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< std::string > \fBvecRequestsFulfilled\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static std::map< \fBCNetAddr\fP, \fBint64_t\fP > \fBsetBanned\fP"
.br
.ti -1c
.RI "static \fBCCriticalSection\fP \fBcs_setBanned\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Information about a peer\&. 
.PP
Definition at line 222 of file net\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CNode::CNode (\fBSOCKET\fP hSocketIn, \fBCAddress\fP addrIn, std::string addrNameIn = \fC''\fP, bool fInboundIn = \fCfalse\fP)\fC [inline]\fP"

.PP
Definition at line 314 of file net\&.h\&.
.SS "CNode::~CNode ()\fC [inline]\fP"

.PP
Definition at line 371 of file net\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void CNode::AbortMessage ()\fC [inline]\fP"

.PP
Definition at line 534 of file net\&.h\&.
.SS "void CNode::AddAddressKnown (const \fBCAddress\fP & addr)\fC [inline]\fP"

.PP
Definition at line 467 of file net\&.h\&.
.SS "void CNode::AddInventoryKnown (const \fBCInv\fP & inv)\fC [inline]\fP"

.PP
Definition at line 486 of file net\&.h\&.
.SS "\fBCNode\fP* CNode::AddRef ()\fC [inline]\fP"

.PP
Definition at line 454 of file net\&.h\&.
.SS "void CNode::AskFor (const \fBCInv\fP & inv)\fC [inline]\fP"

.PP
Definition at line 503 of file net\&.h\&.
.SS "void CNode::BeginMessage (const char * pszCommand)\fC [inline]\fP"

.PP
Definition at line 525 of file net\&.h\&.
.SS "void CNode::CancelSubscribe (unsigned int nChannel)"

.SS "void CNode::ClearBanned ()\fC [static]\fP"

.PP
Definition at line 484 of file net\&.cpp\&.
.SS "void CNode::ClearFulfilledRequest (std::string strRequest)\fC [inline]\fP"

.PP
Definition at line 789 of file net\&.h\&.
.SS "void CNode::CloseSocketDisconnect ()"

.PP
Definition at line 445 of file net\&.cpp\&.
.SS "void CNode::copyStats (\fBCNodeStats\fP & stats)"

.PP
Definition at line 532 of file net\&.cpp\&.
.SS "void CNode::EndMessage ()\fC [inline]\fP"

.PP
Definition at line 544 of file net\&.h\&.
.SS "void CNode::FulfilledRequest (std::string strRequest)\fC [inline]\fP"

.PP
Definition at line 810 of file net\&.h\&.
.SS "\fBNodeId\fP CNode::GetId () const\fC [inline]\fP"

.PP
Definition at line 424 of file net\&.h\&.
.SS "int CNode::GetRefCount ()\fC [inline]\fP"

.PP
Definition at line 428 of file net\&.h\&.
.SS "\fBuint64_t\fP CNode::GetTotalBytesRecv ()\fC [static]\fP"

.PP
Definition at line 2001 of file net\&.cpp\&.
.SS "\fBuint64_t\fP CNode::GetTotalBytesSent ()\fC [static]\fP"

.PP
Definition at line 2007 of file net\&.cpp\&.
.SS "unsigned int CNode::GetTotalRecvSize ()\fC [inline]\fP"

.PP
Definition at line 435 of file net\&.h\&.
.SS "bool CNode::HasFulfilledRequest (std::string strRequest)\fC [inline]\fP"

.PP
Definition at line 801 of file net\&.h\&.
.SS "bool CNode::IsBanned (\fBCNetAddr\fP ip)\fC [static]\fP"

.PP
Definition at line 489 of file net\&.cpp\&.
.SS "bool CNode::IsSubscribed (unsigned int nChannel)"

.SS "bool CNode::Misbehaving (int howmuch)"

.PP
Definition at line 505 of file net\&.cpp\&.
.SS "void CNode::PushAddress (const \fBCAddress\fP & addr)\fC [inline]\fP"

.PP
Definition at line 472 of file net\&.h\&.
.SS "void CNode::PushInventory (const \fBCInv\fP & inv)\fC [inline]\fP"

.PP
Definition at line 494 of file net\&.h\&.
.SS "void CNode::PushMessage (const char * pszCommand)\fC [inline]\fP"

.PP
Definition at line 583 of file net\&.h\&.
.SS "template<typename T1 > void CNode::PushMessage (const char * pszCommand, const T1 & a1)\fC [inline]\fP"

.PP
Definition at line 598 of file net\&.h\&.
.SS "template<typename T1 , typename T2 > void CNode::PushMessage (const char * pszCommand, const T1 & a1, const T2 & a2)\fC [inline]\fP"

.PP
Definition at line 614 of file net\&.h\&.
.SS "template<typename T1 , typename T2 , typename T3 > void CNode::PushMessage (const char * pszCommand, const T1 & a1, const T2 & a2, const T3 & a3)\fC [inline]\fP"

.PP
Definition at line 630 of file net\&.h\&.
.SS "template<typename T1 , typename T2 , typename T3 , typename T4 > void CNode::PushMessage (const char * pszCommand, const T1 & a1, const T2 & a2, const T3 & a3, const T4 & a4)\fC [inline]\fP"

.PP
Definition at line 646 of file net\&.h\&.
.SS "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > void CNode::PushMessage (const char * pszCommand, const T1 & a1, const T2 & a2, const T3 & a3, const T4 & a4, const T5 & a5)\fC [inline]\fP"

.PP
Definition at line 662 of file net\&.h\&.
.SS "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > void CNode::PushMessage (const char * pszCommand, const T1 & a1, const T2 & a2, const T3 & a3, const T4 & a4, const T5 & a5, const T6 & a6)\fC [inline]\fP"

.PP
Definition at line 678 of file net\&.h\&.
.SS "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 > void CNode::PushMessage (const char * pszCommand, const T1 & a1, const T2 & a2, const T3 & a3, const T4 & a4, const T5 & a5, const T6 & a6, const T7 & a7)\fC [inline]\fP"

.PP
Definition at line 694 of file net\&.h\&.
.SS "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 > void CNode::PushMessage (const char * pszCommand, const T1 & a1, const T2 & a2, const T3 & a3, const T4 & a4, const T5 & a5, const T6 & a6, const T7 & a7, const T8 & a8)\fC [inline]\fP"

.PP
Definition at line 710 of file net\&.h\&.
.SS "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > void CNode::PushMessage (const char * pszCommand, const T1 & a1, const T2 & a2, const T3 & a3, const T4 & a4, const T5 & a5, const T6 & a6, const T7 & a7, const T8 & a8, const T9 & a9)\fC [inline]\fP"

.PP
Definition at line 726 of file net\&.h\&.
.SS "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 > void CNode::PushMessage (const char * pszCommand, const T1 & a1, const T2 & a2, const T3 & a3, const T4 & a4, const T5 & a5, const T6 & a6, const T7 & a7, const T8 & a8, const T9 & a9, const T10 & a10)\fC [inline]\fP"

.PP
Definition at line 742 of file net\&.h\&.
.SS "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 > void CNode::PushMessage (const char * pszCommand, const T1 & a1, const T2 & a2, const T3 & a3, const T4 & a4, const T5 & a5, const T6 & a6, const T7 & a7, const T8 & a8, const T9 & a9, const T10 & a10, const T11 & a11)\fC [inline]\fP"

.PP
Definition at line 758 of file net\&.h\&.
.SS "template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 , typename T11 , typename T12 > void CNode::PushMessage (const char * pszCommand, const T1 & a1, const T2 & a2, const T3 & a3, const T4 & a4, const T5 & a5, const T6 & a6, const T7 & a7, const T8 & a8, const T9 & a9, const T10 & a10, const T11 & a11, const T12 & a12)\fC [inline]\fP"

.PP
Definition at line 774 of file net\&.h\&.
.SS "void CNode::PushVersion ()"
when NTP implemented, change to just nTime = \fBGetAdjustedTime()\fP 
.PP
Definition at line 465 of file net\&.cpp\&.
.SS "bool CNode::ReceiveMsgBytes (const char * pch, unsigned int nBytes)"

.PP
Definition at line 572 of file net\&.cpp\&.
.SS "void CNode::RecordBytesRecv (\fBuint64_t\fP bytes)\fC [static]\fP"

.PP
Definition at line 1989 of file net\&.cpp\&.
.SS "void CNode::RecordBytesSent (\fBuint64_t\fP bytes)\fC [static]\fP"

.PP
Definition at line 1995 of file net\&.cpp\&.
.SS "void CNode::Release ()\fC [inline]\fP"

.PP
Definition at line 460 of file net\&.h\&.
.SS "void CNode::SetRecvVersion (int nVersionIn)\fC [inline]\fP"

.PP
Definition at line 447 of file net\&.h\&.
.SS "void CNode::Subscribe (unsigned int nChannel, unsigned int nHops = \fC0\fP)"

.SH "Member Data Documentation"
.PP 
.SS "\fBCAddress\fP CNode::addr"

.PP
Definition at line 245 of file net\&.h\&.
.SS "\fBCService\fP CNode::addrLocal"

.PP
Definition at line 247 of file net\&.h\&.
.SS "std::string CNode::addrName"

.PP
Definition at line 246 of file net\&.h\&.
.SS "std::string CNode::cleanSubVer"

.PP
Definition at line 253 of file net\&.h\&.
.SS "\fBCCriticalSection\fP CNode::cs_inventory"

.PP
Definition at line 297 of file net\&.h\&.
.SS "\fBCCriticalSection\fP CNode::cs_setBanned\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 274 of file net\&.h\&.
.SS "\fBCCriticalSection\fP CNode::cs_vRecvMsg"

.PP
Definition at line 237 of file net\&.h\&.
.SS "\fBCCriticalSection\fP CNode::cs_vSend"

.PP
Definition at line 233 of file net\&.h\&.
.SS "bool CNode::fClient"

.PP
Definition at line 255 of file net\&.h\&.
.SS "bool CNode::fDisconnect"

.PP
Definition at line 259 of file net\&.h\&.
.SS "bool CNode::fGetAddr"

.PP
Definition at line 290 of file net\&.h\&.
.SS "bool CNode::fInbound"

.PP
Definition at line 256 of file net\&.h\&.
.SS "bool CNode::fNetworkNode"

.PP
Definition at line 257 of file net\&.h\&.
.SS "bool CNode::fOneShot"

.PP
Definition at line 254 of file net\&.h\&.
.SS "bool CNode::fPingQueued"

.PP
Definition at line 310 of file net\&.h\&.
.SS "bool CNode::fRelayTxes"

.PP
Definition at line 264 of file net\&.h\&.
.SS "bool CNode::fSandStorm"

.PP
Definition at line 265 of file net\&.h\&.
.SS "bool CNode::fStartSync"

.PP
Definition at line 285 of file net\&.h\&.
.SS "bool CNode::fSuccessfullyConnected"

.PP
Definition at line 258 of file net\&.h\&.
.SS "\fBCSemaphoreGrant\fP CNode::grantOutbound"

.PP
Definition at line 266 of file net\&.h\&.
.SS "\fBuint256\fP CNode::hashCheckpointKnown"

.PP
Definition at line 292 of file net\&.h\&.
.SS "\fBuint256\fP CNode::hashContinue"

.PP
Definition at line 281 of file net\&.h\&.
.SS "\fBuint256\fP CNode::hashLastGetBlocksEnd"

.PP
Definition at line 283 of file net\&.h\&.
.SS "\fBSOCKET\fP CNode::hSocket"

.PP
Definition at line 227 of file net\&.h\&.
.SS "\fBNodeId\fP CNode::id"

.PP
Definition at line 268 of file net\&.h\&.
.SS "std::multimap<\fBint64_t\fP, \fBCInv\fP> CNode::mapAskFor"

.PP
Definition at line 298 of file net\&.h\&.
.SS "\fBint64_t\fP CNode::nLastRecv"

.PP
Definition at line 242 of file net\&.h\&.
.SS "\fBint64_t\fP CNode::nLastSend"

.PP
Definition at line 241 of file net\&.h\&.
.SS "int CNode::nMisbehavior"

.PP
Definition at line 280 of file net\&.h\&.
.SS "\fBuint64_t\fP CNode::nPingNonceSent"

.PP
Definition at line 304 of file net\&.h\&.
.SS "\fBint64_t\fP CNode::nPingUsecStart"

.PP
Definition at line 306 of file net\&.h\&.
.SS "\fBint64_t\fP CNode::nPingUsecTime"

.PP
Definition at line 308 of file net\&.h\&.
.SS "\fBuint64_t\fP CNode::nRecvBytes"

.PP
Definition at line 238 of file net\&.h\&.
.SS "int CNode::nRecvVersion"

.PP
Definition at line 239 of file net\&.h\&.
.SS "int CNode::nRefCount"

.PP
Definition at line 267 of file net\&.h\&.
.SS "\fBuint64_t\fP CNode::nSendBytes"

.PP
Definition at line 231 of file net\&.h\&.
.SS "size_t CNode::nSendOffset"

.PP
Definition at line 230 of file net\&.h\&.
.SS "size_t CNode::nSendSize"

.PP
Definition at line 229 of file net\&.h\&.
.SS "\fBuint64_t\fP CNode::nServices"

.PP
Definition at line 226 of file net\&.h\&.
.SS "int CNode::nStartingHeight"

.PP
Definition at line 284 of file net\&.h\&.
.SS "\fBint64_t\fP CNode::nTimeConnected"

.PP
Definition at line 243 of file net\&.h\&.
.SS "\fBint64_t\fP CNode::nTimeOffset"

.PP
Definition at line 244 of file net\&.h\&.
.SS "int CNode::nVersion"

.PP
Definition at line 248 of file net\&.h\&.
.SS "\fBCBlockIndex\fP* CNode::pindexLastGetBlocksBegin"

.PP
Definition at line 282 of file net\&.h\&.
.SS "\fBmruset\fP<\fBCAddress\fP> CNode::setAddrKnown"

.PP
Definition at line 289 of file net\&.h\&.
.SS "std::map< \fBCNetAddr\fP, \fBint64_t\fP > CNode::setBanned\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 273 of file net\&.h\&.
.SS "\fBmruset\fP<\fBCInv\fP> CNode::setInventoryKnown"

.PP
Definition at line 295 of file net\&.h\&.
.SS "std::set<\fBuint256\fP> CNode::setKnown"

.PP
Definition at line 291 of file net\&.h\&.
.SS "\fBSecMsgNode\fP CNode::smsgData"

.PP
Definition at line 300 of file net\&.h\&.
.SS "\fBCDataStream\fP CNode::ssSend"

.PP
Definition at line 228 of file net\&.h\&.
.SS "std::string CNode::strSubVer"

.PP
Definition at line 253 of file net\&.h\&.
.SS "std::vector<\fBCAddress\fP> CNode::vAddrToSend"

.PP
Definition at line 288 of file net\&.h\&.
.SS "std::vector<std::string> CNode::vecRequestsFulfilled\fC [protected]\fP"

.PP
Definition at line 277 of file net\&.h\&.
.SS "std::vector<\fBCInv\fP> CNode::vInventoryToSend"

.PP
Definition at line 296 of file net\&.h\&.
.SS "std::deque<\fBCInv\fP> CNode::vRecvGetData"

.PP
Definition at line 235 of file net\&.h\&.
.SS "std::deque<\fBCNetMessage\fP> CNode::vRecvMsg"

.PP
Definition at line 236 of file net\&.h\&.
.SS "std::deque<\fBCSerializeData\fP> CNode::vSendMsg"

.PP
Definition at line 232 of file net\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
