.TH "CNodeSignals" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CNodeSignals \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <net\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boost::signals2::signal< int()> \fBGetHeight\fP"
.br
.ti -1c
.RI "boost::signals2::signal< bool(\fBCNode\fP *)> \fBProcessMessages\fP"
.br
.ti -1c
.RI "boost::signals2::signal< bool(\fBCNode\fP *, bool)> \fBSendMessages\fP"
.br
.ti -1c
.RI "boost::signals2::signal< void(\fBNodeId\fP, const \fBCNode\fP *)> \fBInitializeNode\fP"
.br
.ti -1c
.RI "boost::signals2::signal< void(\fBNodeId\fP)> \fBFinalizeNode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 58 of file net\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "boost::signals2::signal<void (\fBNodeId\fP)> CNodeSignals::FinalizeNode"

.PP
Definition at line 64 of file net\&.h\&.
.SS "boost::signals2::signal<int ()> CNodeSignals::GetHeight"

.PP
Definition at line 60 of file net\&.h\&.
.SS "boost::signals2::signal<void (\fBNodeId\fP, const \fBCNode\fP*)> CNodeSignals::InitializeNode"

.PP
Definition at line 63 of file net\&.h\&.
.SS "boost::signals2::signal<bool (\fBCNode\fP*)> CNodeSignals::ProcessMessages"

.PP
Definition at line 61 of file net\&.h\&.
.SS "boost::signals2::signal<bool (\fBCNode\fP*, bool)> CNodeSignals::SendMessages"

.PP
Definition at line 62 of file net\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
