.TH "/home/dev/ds-160209/src/leveldb/util/coding.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/util/coding.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'leveldb/slice\&.h'\fP
.br
\fC#include 'port/port\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBleveldb::PutFixed32\fP (std::string *dst, \fBuint32_t\fP \fBvalue\fP)"
.br
.ti -1c
.RI "void \fBleveldb::PutFixed64\fP (std::string *dst, \fBuint64_t\fP \fBvalue\fP)"
.br
.ti -1c
.RI "void \fBleveldb::PutVarint32\fP (std::string *dst, \fBuint32_t\fP v)"
.br
.ti -1c
.RI "void \fBleveldb::PutVarint64\fP (std::string *dst, \fBuint64_t\fP v)"
.br
.ti -1c
.RI "void \fBleveldb::PutLengthPrefixedSlice\fP (std::string *dst, const Slice &\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBleveldb::GetVarint32\fP (Slice *input, \fBuint32_t\fP *\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBleveldb::GetVarint64\fP (Slice *input, \fBuint64_t\fP *\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBleveldb::GetLengthPrefixedSlice\fP (Slice *input, Slice *result)"
.br
.ti -1c
.RI "const char * \fBleveldb::GetVarint32Ptr\fP (const char *p, const char *limit, \fBuint32_t\fP *v)"
.br
.ti -1c
.RI "const char * \fBleveldb::GetVarint64Ptr\fP (const char *p, const char *limit, \fBuint64_t\fP *\fBvalue\fP)"
.br
.ti -1c
.RI "int \fBleveldb::VarintLength\fP (\fBuint64_t\fP v)"
.br
.ti -1c
.RI "void \fBleveldb::EncodeFixed32\fP (char *buf, \fBuint32_t\fP \fBvalue\fP)"
.br
.ti -1c
.RI "void \fBleveldb::EncodeFixed64\fP (char *buf, \fBuint64_t\fP \fBvalue\fP)"
.br
.ti -1c
.RI "char * \fBleveldb::EncodeVarint32\fP (char *dst, \fBuint32_t\fP v)"
.br
.ti -1c
.RI "char * \fBleveldb::EncodeVarint64\fP (char *dst, \fBuint64_t\fP v)"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBleveldb::DecodeFixed32\fP (const char *ptr)"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBleveldb::DecodeFixed64\fP (const char *ptr)"
.br
.ti -1c
.RI "const char * \fBleveldb::GetVarint32PtrFallback\fP (const char *p, const char *limit, \fBuint32_t\fP *\fBvalue\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
