.TH "CoinControlDialog" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoinControlDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <coincontroldialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCoinControlDialog\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~CoinControlDialog\fP ()"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBWalletModel\fP *model)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBupdateLabels\fP (\fBWalletModel\fP *, QDialog *)"
.br
.ti -1c
.RI "static QString \fBgetPriorityLabel\fP (double)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static QList< \fBCAmount\fP > \fBpayAmounts\fP"
.br
.ti -1c
.RI "static \fBCCoinControl\fP * \fBcoinControl\fP = new \fBCCoinControl\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file coincontroldialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CoinControlDialog::CoinControlDialog (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 38 of file coincontroldialog\&.cpp\&.
.SS "CoinControlDialog::~CoinControlDialog ()"

.PP
Definition at line 138 of file coincontroldialog\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QString CoinControlDialog::getPriorityLabel (double dPriority)\fC [static]\fP"

.PP
Definition at line 421 of file coincontroldialog\&.cpp\&.
.SS "void CoinControlDialog::setModel (\fBWalletModel\fP * model)"

.PP
Definition at line 143 of file coincontroldialog\&.cpp\&.
.SS "void CoinControlDialog::updateLabels (\fBWalletModel\fP * model, QDialog * dialog)\fC [static]\fP"

.PP
Definition at line 451 of file coincontroldialog\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCCoinControl\fP * CoinControlDialog::coinControl = new \fBCCoinControl\fP()\fC [static]\fP"

.PP
Definition at line 38 of file coincontroldialog\&.h\&.
.SS "QList< \fBCAmount\fP > CoinControlDialog::payAmounts\fC [static]\fP"

.PP
Definition at line 37 of file coincontroldialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
