.TH "/home/dev/ds-160209/src/qt/coincontroldialog.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/coincontroldialog.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'amount\&.h'\fP
.br
\fC#include <QAbstractButton>\fP
.br
\fC#include <QAction>\fP
.br
\fC#include <QDialog>\fP
.br
\fC#include <QList>\fP
.br
\fC#include <QMenu>\fP
.br
\fC#include <QPoint>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QTreeWidgetItem>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCoinControlDialog\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
