.TH "/home/dev/ds-160209/src/crypto/argon2/core.c" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/crypto/argon2/core.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <inttypes\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'core\&.h'\fP
.br
\fC#include 'thread\&.h'\fP
.br
\fC#include 'blake2/blake2\&.h'\fP
.br
\fC#include 'blake2/blake2-impl\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBVC_GE_2005\fP(\fBversion\fP)   (\fBversion\fP >= 1400)"
.br
.ti -1c
.RI "#define \fBNOT_OPTIMIZED\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_block_value\fP (\fBblock\fP *b, \fBuint8_t\fP in)"
.br
.ti -1c
.RI "void \fBcopy_block\fP (\fBblock\fP *dst, const \fBblock\fP *src)"
.br
.ti -1c
.RI "void \fBxor_block\fP (\fBblock\fP *dst, const \fBblock\fP *src)"
.br
.ti -1c
.RI "int \fBallocate_memory\fP (\fBblock\fP **memory, \fBuint32_t\fP m_cost)"
.br
.ti -1c
.RI "void \fBNOT_OPTIMIZED\fP \fBsecure_wipe_memory\fP (void *v, size_t n)"
.br
.ti -1c
.RI "void \fBclear_memory\fP (\fBargon2_instance_t\fP *instance, int clear)"
.br
.ti -1c
.RI "void \fBfree_memory\fP (\fBblock\fP *memory)"
.br
.ti -1c
.RI "void \fBfinalize\fP (const \fBargon2_context\fP *context, \fBargon2_instance_t\fP *instance)"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBindex_alpha\fP (const \fBargon2_instance_t\fP *instance, const \fBargon2_position_t\fP *position, \fBuint32_t\fP pseudo_rand, int same_lane)"
.br
.ti -1c
.RI "int \fBfill_memory_blocks\fP (\fBargon2_instance_t\fP *instance)"
.br
.ti -1c
.RI "int \fBvalidate_inputs\fP (const \fBargon2_context\fP *context)"
.br
.ti -1c
.RI "void \fBfill_first_blocks\fP (\fBuint8_t\fP *blockhash, const \fBargon2_instance_t\fP *instance)"
.br
.ti -1c
.RI "void \fBinitial_hash\fP (\fBuint8_t\fP *blockhash, \fBargon2_context\fP *context, \fBargon2_type\fP type)"
.br
.ti -1c
.RI "int \fBinitialize\fP (\fBargon2_instance_t\fP *instance, \fBargon2_context\fP *context)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NOT_OPTIMIZED"

.PP
Definition at line 50 of file core\&.c\&.
.SS "#define VC_GE_2005(\fBversion\fP)   (\fBversion\fP >= 1400)"

.PP
Definition at line 22 of file core\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int allocate_memory (\fBblock\fP ** memory, \fBuint32_t\fP m_cost)"

.PP
Definition at line 82 of file core\&.c\&.
.SS "void clear_memory (\fBargon2_instance_t\fP * instance, int clear)"

.PP
Definition at line 118 of file core\&.c\&.
.SS "void copy_block (\fBblock\fP * dst, const \fBblock\fP * src)"

.PP
Definition at line 56 of file core\&.c\&.
.SS "void fill_first_blocks (\fBuint8_t\fP * blockhash, const \fBargon2_instance_t\fP * instance)"

.PP
Definition at line 462 of file core\&.c\&.
.SS "int fill_memory_blocks (\fBargon2_instance_t\fP * instance)"

.PP
Definition at line 252 of file core\&.c\&.
.SS "void finalize (const \fBargon2_context\fP * context, \fBargon2_instance_t\fP * instance)"

.PP
Definition at line 127 of file core\&.c\&.
.SS "void free_memory (\fBblock\fP * memory)"

.PP
Definition at line 125 of file core\&.c\&.
.SS "\fBuint32_t\fP index_alpha (const \fBargon2_instance_t\fP * instance, const \fBargon2_position_t\fP * position, \fBuint32_t\fP pseudo_rand, int same_lane)"

.PP
Definition at line 170 of file core\&.c\&.
.SS "void init_block_value (\fBblock\fP * b, \fBuint8_t\fP in)"

.PP
Definition at line 54 of file core\&.c\&.
.SS "void initial_hash (\fBuint8_t\fP * blockhash, \fBargon2_context\fP * context, \fBargon2_type\fP type)"

.PP
Definition at line 485 of file core\&.c\&.
.SS "int initialize (\fBargon2_instance_t\fP * instance, \fBargon2_context\fP * context)"

.PP
Definition at line 559 of file core\&.c\&.
.SS "void \fBNOT_OPTIMIZED\fP secure_wipe_memory (void * v, size_t n)"

.PP
Definition at line 103 of file core\&.c\&.
.SS "int validate_inputs (const \fBargon2_context\fP * context)"

.PP
Definition at line 333 of file core\&.c\&.
.SS "void xor_block (\fBblock\fP * dst, const \fBblock\fP * src)"

.PP
Definition at line 60 of file core\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
