.TH "/home/dev/ds-160209/src/leveldb/util/crc32c.cc" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/util/crc32c.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'util/crc32c\&.h'\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include 'util/coding\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.ti -1c
.RI " \fBleveldb::crc32c\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTEP1\fP"
.br
.ti -1c
.RI "#define \fBSTEP4\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP \fBleveldb::crc32c::Extend\fP (\fBuint32_t\fP crc, const char *buf, size_t size)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define STEP1"
\fBValue:\fP
.PP
.nf
do {                              \
    int c = (l & 0xff) ^ *p++;                  \
    l = table0_[c] ^ (l >> 8);                  \
} while (0)
.fi
.SS "#define STEP4"
\fBValue:\fP
.PP
.nf
do {                              \\
    uint32_t c = l ^ LE_LOAD32(p);              \
    p += 4;                                     \
    l = table3_[c & 0xff] ^                     \
        table2_[(c >> 8) & 0xff] ^              \
        table1_[(c >> 16) & 0xff] ^             \
        table0_[c >> 24];                       \
} while (0)
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
