.TH "CReserveKey" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CReserveKey \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wallet\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCReserveKey\fP (\fBCWallet\fP *pwalletIn)"
.br
.ti -1c
.RI "\fB~CReserveKey\fP ()"
.br
.ti -1c
.RI "void \fBReturnKey\fP ()"
.br
.ti -1c
.RI "bool \fBGetReservedKey\fP (\fBCPubKey\fP &pubkey)"
.br
.ti -1c
.RI "void \fBKeepKey\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBCWallet\fP * \fBpwallet\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnIndex\fP"
.br
.ti -1c
.RI "\fBCPubKey\fP \fBvchPubKey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A key allocated from the key pool\&. 
.PP
Definition at line 478 of file wallet\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CReserveKey::CReserveKey (\fBCWallet\fP * pwalletIn)\fC [inline]\fP"

.PP
Definition at line 485 of file wallet\&.h\&.
.SS "CReserveKey::~CReserveKey ()\fC [inline]\fP"

.PP
Definition at line 491 of file wallet\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CReserveKey::GetReservedKey (\fBCPubKey\fP & pubkey)"

.PP
Definition at line 4666 of file wallet\&.cpp\&.
.SS "void CReserveKey::KeepKey ()"

.PP
Definition at line 4687 of file wallet\&.cpp\&.
.SS "void CReserveKey::ReturnKey ()"

.PP
Definition at line 4695 of file wallet\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint64_t\fP CReserveKey::nIndex\fC [protected]\fP"

.PP
Definition at line 482 of file wallet\&.h\&.
.SS "\fBCWallet\fP* CReserveKey::pwallet\fC [protected]\fP"

.PP
Definition at line 481 of file wallet\&.h\&.
.SS "\fBCPubKey\fP CReserveKey::vchPubKey\fC [protected]\fP"

.PP
Definition at line 483 of file wallet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
