.TH "CRPCConvertParam" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CRPCConvertParam \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBmethodName\fP"
.br
.ti -1c
.RI "int \fBparamIdx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 97 of file rpcclient\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string CRPCConvertParam::methodName"

.PP
Definition at line 100 of file rpcclient\&.cpp\&.
.SS "int CRPCConvertParam::paramIdx"

.PP
Definition at line 101 of file rpcclient\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
