.TH "CRPCTable" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CRPCTable \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rpcserver\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCRPCTable\fP ()"
.br
.ti -1c
.RI "const \fBCRPCCommand\fP * \fBoperator[]\fP (std::string \fBname\fP) const "
.br
.ti -1c
.RI "std::string \fBhelp\fP (std::string \fBname\fP) const "
.br
.ti -1c
.RI "\fBjson_spirit::Value\fP \fBexecute\fP (const std::string &method, const \fBjson_spirit::Array\fP &params) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
DarkSilk RPC command dispatcher\&. 
.PP
Definition at line 57 of file rpcserver\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CRPCTable::CRPCTable ()"

.PP
Definition at line 333 of file rpcserver\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBjson_spirit::Value\fP CRPCTable::execute (const std::string & method, const \fBjson_spirit::Array\fP & params) const"
Execute a method\&. 
.PP
\fBParameters:\fP
.RS 4
\fImethod\fP Method to execute 
.br
\fIparams\fP Array of arguments (JSON objects) 
.RE
.PP
\fBReturns:\fP
.RS 4
Result of the call\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIan\fP exception (\fBjson_spirit::Value\fP) when an error happens\&. 
.RE
.PP

.PP
Definition at line 825 of file rpcserver\&.cpp\&.
.SS "string CRPCTable::help (std::string name) const"
Note: This interface may still be subject to change\&. 
.PP
Definition at line 145 of file rpcserver\&.cpp\&.
.SS "const \fBCRPCCommand\fP * CRPCTable::operator[] (std::string name) const"

.PP
Definition at line 345 of file rpcserver\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
