.TH "/home/dev/ds-160209/src/crypter.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/crypter.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'allocators\&.h'\fP
.br
\fC#include 'serialize\&.h'\fP
.br
\fC#include 'keystore\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCMasterKey\fP"
.br
.ti -1c
.RI "class \fBCCrypter\fP"
.br
.ti -1c
.RI "class \fBCCryptoKeyStore\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector< unsigned char, \fBsecure_allocator\fP< unsigned char > > \fBCKeyingMaterial\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBEncryptSecret\fP (const \fBCKeyingMaterial\fP &vMasterKey, const \fBCKeyingMaterial\fP &vchPlaintext, const \fBuint256\fP &nIV, std::vector< unsigned char > &vchCiphertext)"
.br
.ti -1c
.RI "bool \fBDecryptSecret\fP (const \fBCKeyingMaterial\fP &vMasterKey, const std::vector< unsigned char > &vchCiphertext, const \fBuint256\fP &nIV, \fBCKeyingMaterial\fP &vchPlaintext)"
.br
.ti -1c
.RI "bool \fBEncryptAES256\fP (const \fBSecureString\fP &sKey, const \fBSecureString\fP &sPlaintext, const std::string &sIV, std::string &sCiphertext)"
.br
.ti -1c
.RI "bool \fBDecryptAES256\fP (const \fBSecureString\fP &sKey, const std::string &sCiphertext, const std::string &sIV, \fBSecureString\fP &sPlaintext)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned int \fBWALLET_CRYPTO_KEY_SIZE\fP = 32"
.br
.RI "\fI! for SecureString \fP"
.ti -1c
.RI "const unsigned int \fBWALLET_CRYPTO_SALT_SIZE\fP = 8"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::vector<unsigned char, \fBsecure_allocator\fP<unsigned char> > \fBCKeyingMaterial\fP"

.PP
Definition at line 85 of file crypter\&.h\&.
.SH "Function Documentation"
.PP 
.SS "bool DecryptAES256 (const \fBSecureString\fP & sKey, const std::string & sCiphertext, const std::string & sIV, \fBSecureString\fP & sPlaintext)"

.PP
Definition at line 181 of file crypter\&.cpp\&.
.SS "bool DecryptSecret (const \fBCKeyingMaterial\fP & vMasterKey, const std::vector< unsigned char > & vchCiphertext, const \fBuint256\fP & nIV, \fBCKeyingMaterial\fP & vchPlaintext)"

.PP
Definition at line 136 of file crypter\&.cpp\&.
.SS "bool EncryptAES256 (const \fBSecureString\fP & sKey, const \fBSecureString\fP & sPlaintext, const std::string & sIV, std::string & sCiphertext)"

.PP
Definition at line 147 of file crypter\&.cpp\&.
.SS "bool EncryptSecret (const \fBCKeyingMaterial\fP & vMasterKey, const \fBCKeyingMaterial\fP & vchPlaintext, const \fBuint256\fP & nIV, std::vector< unsigned char > & vchCiphertext)"

.PP
Definition at line 126 of file crypter\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const unsigned int WALLET_CRYPTO_KEY_SIZE = 32"

.PP
! for SecureString 
.PP
Definition at line 12 of file crypter\&.h\&.
.SS "const unsigned int WALLET_CRYPTO_SALT_SIZE = 8"

.PP
Definition at line 13 of file crypter\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
