.TH "/home/dev/ds-160209/src/crypter.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/crypter.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'crypter\&.h'\fP
.br
\fC#include 'script\&.h'\fP
.br
\fC#include 'scrypt\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <boost/foreach\&.hpp>\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include <openssl/ec\&.h>\fP
.br
\fC#include <openssl/ecdh\&.h>\fP
.br
\fC#include <openssl/sha\&.h>\fP
.br
\fC#include <openssl/aes\&.h>\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include <openssl/hmac\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBEncryptSecret\fP (const \fBCKeyingMaterial\fP &vMasterKey, const \fBCKeyingMaterial\fP &vchPlaintext, const \fBuint256\fP &nIV, std::vector< unsigned char > &vchCiphertext)"
.br
.ti -1c
.RI "bool \fBDecryptSecret\fP (const \fBCKeyingMaterial\fP &vMasterKey, const std::vector< unsigned char > &vchCiphertext, const \fBuint256\fP &nIV, \fBCKeyingMaterial\fP &vchPlaintext)"
.br
.ti -1c
.RI "bool \fBEncryptAES256\fP (const \fBSecureString\fP &sKey, const \fBSecureString\fP &sPlaintext, const std::string &sIV, std::string &sCiphertext)"
.br
.ti -1c
.RI "bool \fBDecryptAES256\fP (const \fBSecureString\fP &sKey, const std::string &sCiphertext, const std::string &sIV, \fBSecureString\fP &sPlaintext)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool DecryptAES256 (const \fBSecureString\fP & sKey, const std::string & sCiphertext, const std::string & sIV, \fBSecureString\fP & sPlaintext)"

.PP
Definition at line 181 of file crypter\&.cpp\&.
.SS "bool DecryptSecret (const \fBCKeyingMaterial\fP & vMasterKey, const std::vector< unsigned char > & vchCiphertext, const \fBuint256\fP & nIV, \fBCKeyingMaterial\fP & vchPlaintext)"

.PP
Definition at line 136 of file crypter\&.cpp\&.
.SS "bool EncryptAES256 (const \fBSecureString\fP & sKey, const \fBSecureString\fP & sPlaintext, const std::string & sIV, std::string & sCiphertext)"

.PP
Definition at line 147 of file crypter\&.cpp\&.
.SS "bool EncryptSecret (const \fBCKeyingMaterial\fP & vMasterKey, const \fBCKeyingMaterial\fP & vchPlaintext, const \fBuint256\fP & nIV, std::vector< unsigned char > & vchCiphertext)"

.PP
Definition at line 126 of file crypter\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
