.TH "CSandStormEntry" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSandStormEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sandstorm\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCSandStormEntry\fP ()"
.br
.ti -1c
.RI "bool \fBAdd\fP (const std::vector< \fBCTxIn\fP > vinIn, \fBCAmount\fP amountIn, const \fBCTransaction\fP collateralIn, const std::vector< \fBCTxOut\fP > voutIn)"
.br
.RI "\fIAdd entries to use for Sandstorm\&. \fP"
.ti -1c
.RI "bool \fBAddSig\fP (const \fBCTxIn\fP &vin)"
.br
.ti -1c
.RI "bool \fBIsExpired\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisSet\fP"
.br
.ti -1c
.RI "std::vector< \fBCTxSSIn\fP > \fBsev\fP"
.br
.ti -1c
.RI "std::vector< \fBCTxSSOut\fP > \fBvout\fP"
.br
.ti -1c
.RI "\fBCAmount\fP \fBamount\fP"
.br
.ti -1c
.RI "\fBCTransaction\fP \fBcollateral\fP"
.br
.ti -1c
.RI "\fBCTransaction\fP \fBtxSupporting\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBaddedTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 87 of file sandstorm\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CSandStormEntry::CSandStormEntry ()\fC [inline]\fP"

.PP
Definition at line 98 of file sandstorm\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CSandStormEntry::Add (const std::vector< \fBCTxIn\fP > vinIn, \fBCAmount\fP amountIn, const \fBCTransaction\fP collateralIn, const std::vector< \fBCTxOut\fP > voutIn)\fC [inline]\fP"

.PP
Add entries to use for Sandstorm\&. 
.PP
Definition at line 106 of file sandstorm\&.h\&.
.SS "bool CSandStormEntry::AddSig (const \fBCTxIn\fP & vin)\fC [inline]\fP"

.PP
Definition at line 124 of file sandstorm\&.h\&.
.SS "bool CSandStormEntry::IsExpired ()\fC [inline]\fP"

.PP
Definition at line 140 of file sandstorm\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint64_t\fP CSandStormEntry::addedTime"

.PP
Definition at line 96 of file sandstorm\&.h\&.
.SS "\fBCAmount\fP CSandStormEntry::amount"

.PP
Definition at line 93 of file sandstorm\&.h\&.
.SS "\fBCTransaction\fP CSandStormEntry::collateral"

.PP
Definition at line 94 of file sandstorm\&.h\&.
.SS "bool CSandStormEntry::isSet"

.PP
Definition at line 90 of file sandstorm\&.h\&.
.SS "std::vector<\fBCTxSSIn\fP> CSandStormEntry::sev"

.PP
Definition at line 91 of file sandstorm\&.h\&.
.SS "\fBCTransaction\fP CSandStormEntry::txSupporting"

.PP
Definition at line 95 of file sandstorm\&.h\&.
.SS "std::vector<\fBCTxSSOut\fP> CSandStormEntry::vout"

.PP
Definition at line 92 of file sandstorm\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
