.TH "CSandStormSigner" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSandStormSigner \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sandstorm\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsVinAssociatedWithPubkey\fP (\fBCTxIn\fP &vin, \fBCPubKey\fP &pubkey)"
.br
.RI "\fIIs the inputs associated with this public key? (and there is 1000 DASH - checking if valid stormnode) \fP"
.ti -1c
.RI "bool \fBSetKey\fP (std::string strSecret, std::string &errorMessage, \fBCKey\fP &key, \fBCPubKey\fP &pubkey)"
.br
.RI "\fISet the private/public key values, returns true if successful\&. \fP"
.ti -1c
.RI "bool \fBSignMessage\fP (std::string strMessage, std::string &errorMessage, std::vector< unsigned char > &vchSig, \fBCKey\fP key)"
.br
.RI "\fISign the message, returns true if successful\&. \fP"
.ti -1c
.RI "bool \fBVerifyMessage\fP (\fBCPubKey\fP pubkey, std::vector< unsigned char > &vchSig, std::string strMessage, std::string &errorMessage)"
.br
.RI "\fIVerify the message, returns true if succcessful\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Helper object for signing and checking signatures 
.PP
Definition at line 237 of file sandstorm\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CSandStormSigner::IsVinAssociatedWithPubkey (\fBCTxIn\fP & vin, \fBCPubKey\fP & pubkey)"

.PP
Is the inputs associated with this public key? (and there is 1000 DASH - checking if valid stormnode) 
.PP
Definition at line 2027 of file sandstorm\&.cpp\&.
.SS "bool CSandStormSigner::SetKey (std::string strSecret, std::string & errorMessage, \fBCKey\fP & key, \fBCPubKey\fP & pubkey)"

.PP
Set the private/public key values, returns true if successful\&. 
.PP
Definition at line 2044 of file sandstorm\&.cpp\&.
.SS "bool CSandStormSigner::SignMessage (std::string strMessage, std::string & errorMessage, std::vector< unsigned char > & vchSig, \fBCKey\fP key)"

.PP
Sign the message, returns true if successful\&. 
.PP
Definition at line 2059 of file sandstorm\&.cpp\&.
.SS "bool CSandStormSigner::VerifyMessage (\fBCPubKey\fP pubkey, std::vector< unsigned char > & vchSig, std::string strMessage, std::string & errorMessage)"

.PP
Verify the message, returns true if succcessful\&. 
.PP
Definition at line 2073 of file sandstorm\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
