.TH "CSandStormRelay" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSandStormRelay \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sandstorm-relay\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCSandStormRelay\fP ()"
.br
.ti -1c
.RI "\fBCSandStormRelay\fP (\fBCTxIn\fP &vinStormnodeIn, vector< unsigned char > &vchSigIn, int nBlockHeightIn, int nRelayTypeIn, \fBCTxIn\fP &in2, \fBCTxOut\fP &out2)"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.ti -1c
.RI "std::string \fBToString\fP ()"
.br
.ti -1c
.RI "bool \fBSign\fP (std::string strSharedKey)"
.br
.ti -1c
.RI "bool \fBVerifyMessage\fP (std::string strSharedKey)"
.br
.ti -1c
.RI "void \fBRelay\fP ()"
.br
.ti -1c
.RI "void \fBRelayThroughNode\fP (int nRank)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCTxIn\fP \fBvinStormnode\fP"
.br
.ti -1c
.RI "vector< unsigned char > \fBvchSig\fP"
.br
.ti -1c
.RI "vector< unsigned char > \fBvchSig2\fP"
.br
.ti -1c
.RI "int \fBnBlockHeight\fP"
.br
.ti -1c
.RI "int \fBnRelayType\fP"
.br
.ti -1c
.RI "\fBCTxIn\fP \fBin\fP"
.br
.ti -1c
.RI "\fBCTxOut\fP \fBout\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file sandstorm-relay\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CSandStormRelay::CSandStormRelay ()"

.PP
Definition at line 8 of file sandstorm-relay\&.cpp\&.
.SS "CSandStormRelay::CSandStormRelay (\fBCTxIn\fP & vinStormnodeIn, vector< unsigned char > & vchSigIn, int nBlockHeightIn, int nRelayTypeIn, \fBCTxIn\fP & in2, \fBCTxOut\fP & out2)"

.PP
Definition at line 17 of file sandstorm-relay\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void CSandStormRelay::Relay ()"

.PP
Definition at line 89 of file sandstorm-relay\&.cpp\&.
.SS "void CSandStormRelay::RelayThroughNode (int nRank)"

.PP
Definition at line 105 of file sandstorm-relay\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CSandStormRelay::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 27 of file sandstorm-relay\&.h\&.
.SS "bool CSandStormRelay::Sign (std::string strSharedKey)"

.PP
Definition at line 40 of file sandstorm-relay\&.cpp\&.
.SS "std::string CSandStormRelay::ToString ()"

.PP
Definition at line 27 of file sandstorm-relay\&.cpp\&.
.SS "bool CSandStormRelay::VerifyMessage (std::string strSharedKey)"

.PP
Definition at line 67 of file sandstorm-relay\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "CSandStormRelay::ADD_SERIALIZE_METHODS"

.PP
Definition at line 24 of file sandstorm-relay\&.h\&.
.SS "\fBCTxIn\fP CSandStormRelay::in"

.PP
Definition at line 18 of file sandstorm-relay\&.h\&.
.SS "int CSandStormRelay::nBlockHeight"

.PP
Definition at line 16 of file sandstorm-relay\&.h\&.
.SS "int CSandStormRelay::nRelayType"

.PP
Definition at line 17 of file sandstorm-relay\&.h\&.
.SS "\fBCTxOut\fP CSandStormRelay::out"

.PP
Definition at line 19 of file sandstorm-relay\&.h\&.
.SS "vector<unsigned char> CSandStormRelay::vchSig"

.PP
Definition at line 14 of file sandstorm-relay\&.h\&.
.SS "vector<unsigned char> CSandStormRelay::vchSig2"

.PP
Definition at line 15 of file sandstorm-relay\&.h\&.
.SS "\fBCTxIn\fP CSandStormRelay::vinStormnode"

.PP
Definition at line 13 of file sandstorm-relay\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
