.TH "CSandstormBroadcastTx" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSandstormBroadcastTx \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sandstorm\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCTransaction\fP \fBtx\fP"
.br
.ti -1c
.RI "\fBCTxIn\fP \fBvin\fP"
.br
.ti -1c
.RI "vector< unsigned char > \fBvchSig\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBsigTime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Helper class to store Sandstorm transaction (tx) information\&. 
.PP
Definition at line 226 of file sandstorm\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint64_t\fP CSandstormBroadcastTx::sigTime"

.PP
Definition at line 232 of file sandstorm\&.h\&.
.SS "\fBCTransaction\fP CSandstormBroadcastTx::tx"

.PP
Definition at line 229 of file sandstorm\&.h\&.
.SS "vector<unsigned char> CSandstormBroadcastTx::vchSig"

.PP
Definition at line 231 of file sandstorm\&.h\&.
.SS "\fBCTxIn\fP CSandstormBroadcastTx::vin"

.PP
Definition at line 230 of file sandstorm\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
