.TH "CScript" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CScript \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <script\&.h>\fP
.PP
Inherits vector< unsigned char >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCScript\fP ()"
.br
.ti -1c
.RI "\fBCScript\fP (const \fBCScript\fP &b)"
.br
.ti -1c
.RI "\fBCScript\fP (const_iterator pbegin, const_iterator pend)"
.br
.ti -1c
.RI "\fBCScript\fP (const unsigned char *pbegin, const unsigned char *pend)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBoperator+=\fP (const \fBCScript\fP &b)"
.br
.ti -1c
.RI "\fBCScript\fP (signed char b)"
.br
.ti -1c
.RI "\fBCScript\fP (short b)"
.br
.ti -1c
.RI "\fBCScript\fP (int b)"
.br
.ti -1c
.RI "\fBCScript\fP (long b)"
.br
.ti -1c
.RI "\fBCScript\fP (long long b)"
.br
.ti -1c
.RI "\fBCScript\fP (unsigned char b)"
.br
.ti -1c
.RI "\fBCScript\fP (unsigned int b)"
.br
.ti -1c
.RI "\fBCScript\fP (unsigned short b)"
.br
.ti -1c
.RI "\fBCScript\fP (unsigned long b)"
.br
.ti -1c
.RI "\fBCScript\fP (unsigned long long b)"
.br
.ti -1c
.RI "\fBCScript\fP (\fBopcodetype\fP b)"
.br
.ti -1c
.RI "\fBCScript\fP (const \fBuint256\fP &b)"
.br
.ti -1c
.RI "\fBCScript\fP (const \fBCBigNum\fP &b)"
.br
.ti -1c
.RI "\fBCScript\fP (const std::vector< unsigned char > &b)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBoperator<<\fP (signed char b)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBoperator<<\fP (short b)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBoperator<<\fP (int b)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBoperator<<\fP (long b)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBoperator<<\fP (long long b)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBoperator<<\fP (unsigned char b)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBoperator<<\fP (unsigned int b)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBoperator<<\fP (unsigned short b)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBoperator<<\fP (unsigned long b)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBoperator<<\fP (unsigned long long b)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBoperator<<\fP (\fBopcodetype\fP opcode)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBoperator<<\fP (const \fBuint160\fP &b)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBoperator<<\fP (const \fBuint256\fP &b)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBoperator<<\fP (const \fBCPubKey\fP &key)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBoperator<<\fP (const \fBCBigNum\fP &b)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBoperator<<\fP (const std::vector< unsigned char > &b)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBoperator<<\fP (const \fBCScript\fP &b)"
.br
.ti -1c
.RI "bool \fBGetOp\fP (iterator &pc, \fBopcodetype\fP &opcodeRet, std::vector< unsigned char > &vchRet)"
.br
.ti -1c
.RI "bool \fBGetOp\fP (iterator &pc, \fBopcodetype\fP &opcodeRet)"
.br
.ti -1c
.RI "bool \fBGetOp\fP (const_iterator &pc, \fBopcodetype\fP &opcodeRet, std::vector< unsigned char > &vchRet) const "
.br
.ti -1c
.RI "bool \fBGetOp\fP (const_iterator &pc, \fBopcodetype\fP &opcodeRet) const "
.br
.ti -1c
.RI "bool \fBGetOp2\fP (const_iterator &pc, \fBopcodetype\fP &opcodeRet, std::vector< unsigned char > *pvchRet) const "
.br
.ti -1c
.RI "int \fBFindAndDelete\fP (const \fBCScript\fP &b)"
.br
.ti -1c
.RI "int \fBFind\fP (\fBopcodetype\fP op) const "
.br
.ti -1c
.RI "unsigned int \fBGetSigOpCount\fP (bool fAccurate) const "
.br
.ti -1c
.RI "unsigned int \fBGetSigOpCount\fP (const \fBCScript\fP &scriptSig) const "
.br
.ti -1c
.RI "bool \fBIsNormalPaymentScript\fP () const "
.br
.ti -1c
.RI "bool \fBIsPayToScriptHash\fP () const "
.br
.ti -1c
.RI "bool \fBIsPushOnly\fP () const "
.br
.ti -1c
.RI "bool \fBIsUnspendable\fP () const "
.br
.ti -1c
.RI "bool \fBHasCanonicalPushes\fP () const "
.br
.ti -1c
.RI "void \fBSetDestination\fP (const \fBCTxDestination\fP &address)"
.br
.ti -1c
.RI "void \fBSetMultisig\fP (int nRequired, const std::vector< \fBCPubKey\fP > &keys)"
.br
.ti -1c
.RI "std::string \fBToString\fP (bool fShort=false) const "
.br
.ti -1c
.RI "\fBCScriptID\fP \fBGetID\fP () const "
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBDecodeOP_N\fP (\fBopcodetype\fP opcode)"
.br
.ti -1c
.RI "static \fBopcodetype\fP \fBEncodeOP_N\fP (int n)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBCScript\fP & \fBpush_int64\fP (\fBint64_t\fP n)"
.br
.ti -1c
.RI "\fBCScript\fP & \fBpush_uint64\fP (\fBuint64_t\fP n)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBCScript\fP \fBoperator+\fP (const \fBCScript\fP &a, const \fBCScript\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Serialized script, used inside transaction inputs and outputs 
.PP
Definition at line 547 of file script\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CScript::CScript ()\fC [inline]\fP"

.PP
Definition at line 579 of file script\&.h\&.
.SS "CScript::CScript (const \fBCScript\fP & b)\fC [inline]\fP"

.PP
Definition at line 580 of file script\&.h\&.
.SS "CScript::CScript (const_iterator pbegin, const_iterator pend)\fC [inline]\fP"

.PP
Definition at line 581 of file script\&.h\&.
.SS "CScript::CScript (const unsigned char * pbegin, const unsigned char * pend)\fC [inline]\fP"

.PP
Definition at line 583 of file script\&.h\&.
.SS "CScript::CScript (signed char b)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 601 of file script\&.h\&.
.SS "CScript::CScript (short b)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 602 of file script\&.h\&.
.SS "CScript::CScript (int b)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 603 of file script\&.h\&.
.SS "CScript::CScript (long b)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 604 of file script\&.h\&.
.SS "CScript::CScript (long long b)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 605 of file script\&.h\&.
.SS "CScript::CScript (unsigned char b)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 606 of file script\&.h\&.
.SS "CScript::CScript (unsigned int b)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 607 of file script\&.h\&.
.SS "CScript::CScript (unsigned short b)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 608 of file script\&.h\&.
.SS "CScript::CScript (unsigned long b)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 609 of file script\&.h\&.
.SS "CScript::CScript (unsigned long long b)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 610 of file script\&.h\&.
.SS "CScript::CScript (\fBopcodetype\fP b)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 612 of file script\&.h\&.
.SS "CScript::CScript (const \fBuint256\fP & b)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 613 of file script\&.h\&.
.SS "CScript::CScript (const \fBCBigNum\fP & b)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 614 of file script\&.h\&.
.SS "CScript::CScript (const std::vector< unsigned char > & b)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 615 of file script\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void CScript::clear ()\fC [inline]\fP"

.PP
Definition at line 898 of file script\&.h\&.
.SS "static int CScript::DecodeOP_N (\fBopcodetype\fP opcode)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 783 of file script\&.h\&.
.SS "static \fBopcodetype\fP CScript::EncodeOP_N (int n)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 790 of file script\&.h\&.
.SS "int CScript::Find (\fBopcodetype\fP op) const\fC [inline]\fP"

.PP
Definition at line 816 of file script\&.h\&.
.SS "int CScript::FindAndDelete (const \fBCScript\fP & b)\fC [inline]\fP"

.PP
Definition at line 798 of file script\&.h\&.
.SS "\fBCScriptID\fP CScript::GetID () const\fC [inline]\fP"

.PP
Definition at line 893 of file script\&.h\&.
.SS "bool CScript::GetOp (iterator & pc, \fBopcodetype\fP & opcodeRet, std::vector< unsigned char > & vchRet)\fC [inline]\fP"

.PP
Definition at line 702 of file script\&.h\&.
.SS "bool CScript::GetOp (iterator & pc, \fBopcodetype\fP & opcodeRet)\fC [inline]\fP"

.PP
Definition at line 711 of file script\&.h\&.
.SS "bool CScript::GetOp (const_iterator & pc, \fBopcodetype\fP & opcodeRet, std::vector< unsigned char > & vchRet) const\fC [inline]\fP"

.PP
Definition at line 719 of file script\&.h\&.
.SS "bool CScript::GetOp (const_iterator & pc, \fBopcodetype\fP & opcodeRet) const\fC [inline]\fP"

.PP
Definition at line 724 of file script\&.h\&.
.SS "bool CScript::GetOp2 (const_iterator & pc, \fBopcodetype\fP & opcodeRet, std::vector< unsigned char > * pvchRet) const\fC [inline]\fP"

.PP
Definition at line 729 of file script\&.h\&.
.SS "unsigned int CScript::GetSigOpCount (bool fAccurate) const"

.PP
Definition at line 3095 of file script\&.cpp\&.
.SS "unsigned int CScript::GetSigOpCount (const \fBCScript\fP & scriptSig) const"
\&.\&.\&. and return its opcount: 
.PP
Definition at line 3119 of file script\&.cpp\&.
.SS "bool CScript::HasCanonicalPushes () const"

.PP
Definition at line 3152 of file script\&.cpp\&.
.SS "bool CScript::IsNormalPaymentScript () const"

.PP
Definition at line 3245 of file script\&.cpp\&.
.SS "bool CScript::IsPayToScriptHash () const"

.PP
Definition at line 3143 of file script\&.cpp\&.
.SS "bool CScript::IsPushOnly () const\fC [inline]\fP"

.PP
Definition at line 840 of file script\&.h\&.
.SS "bool CScript::IsUnspendable () const\fC [inline]\fP"
Returns whether the script is guaranteed to fail at execution, regardless of the initial stack\&. This allows outputs to be pruned instantly when entering the UTXO set\&. 
.PP
Definition at line 859 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::operator+= (const \fBCScript\fP & b)\fC [inline]\fP"

.PP
Definition at line 586 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::operator<< (signed char b)\fC [inline]\fP"

.PP
Definition at line 619 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::operator<< (short b)\fC [inline]\fP"

.PP
Definition at line 620 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::operator<< (int b)\fC [inline]\fP"

.PP
Definition at line 621 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::operator<< (long b)\fC [inline]\fP"

.PP
Definition at line 622 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::operator<< (long long b)\fC [inline]\fP"

.PP
Definition at line 623 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::operator<< (unsigned char b)\fC [inline]\fP"

.PP
Definition at line 624 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::operator<< (unsigned int b)\fC [inline]\fP"

.PP
Definition at line 625 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::operator<< (unsigned short b)\fC [inline]\fP"

.PP
Definition at line 626 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::operator<< (unsigned long b)\fC [inline]\fP"

.PP
Definition at line 627 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::operator<< (unsigned long long b)\fC [inline]\fP"

.PP
Definition at line 628 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::operator<< (\fBopcodetype\fP opcode)\fC [inline]\fP"

.PP
Definition at line 630 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::operator<< (const \fBuint160\fP & b)\fC [inline]\fP"

.PP
Definition at line 638 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::operator<< (const \fBuint256\fP & b)\fC [inline]\fP"

.PP
Definition at line 645 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::operator<< (const \fBCPubKey\fP & key)\fC [inline]\fP"

.PP
Definition at line 652 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::operator<< (const \fBCBigNum\fP & b)\fC [inline]\fP"

.PP
Definition at line 660 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::operator<< (const std::vector< unsigned char > & b)\fC [inline]\fP"

.PP
Definition at line 666 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::operator<< (const \fBCScript\fP & b)\fC [inline]\fP"

.PP
Definition at line 693 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::push_int64 (\fBint64_t\fP n)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 550 of file script\&.h\&.
.SS "\fBCScript\fP& CScript::push_uint64 (\fBuint64_t\fP n)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 564 of file script\&.h\&.
.SS "void CScript::SetDestination (const \fBCTxDestination\fP & address)"

.PP
Definition at line 3211 of file script\&.cpp\&.
.SS "void CScript::SetMultisig (int nRequired, const std::vector< \fBCPubKey\fP > & keys)"

.PP
Definition at line 3216 of file script\&.cpp\&.
.SS "std::string CScript::ToString (bool fShort = \fCfalse\fP) const\fC [inline]\fP"

.PP
Definition at line 870 of file script\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "\fBCScript\fP operator+ (const \fBCScript\fP & a, const \fBCScript\fP & b)\fC [friend]\fP"

.PP
Definition at line 592 of file script\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
