.TH "CScriptVisitor" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CScriptVisitor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< bool >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCScriptVisitor\fP (\fBCScript\fP *scriptin)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCNoDestination\fP &dest) const "
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCKeyID\fP &keyID) const "
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCScriptID\fP &scriptID) const "
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCStealthAddress\fP &stxAddr) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3179 of file script\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CScriptVisitor::CScriptVisitor (\fBCScript\fP * scriptin)\fC [inline]\fP"

.PP
Definition at line 3184 of file script\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CScriptVisitor::operator() (const \fBCNoDestination\fP & dest) const\fC [inline]\fP"

.PP
Definition at line 3186 of file script\&.cpp\&.
.SS "bool CScriptVisitor::operator() (const \fBCKeyID\fP & keyID) const\fC [inline]\fP"

.PP
Definition at line 3191 of file script\&.cpp\&.
.SS "bool CScriptVisitor::operator() (const \fBCScriptID\fP & scriptID) const\fC [inline]\fP"

.PP
Definition at line 3197 of file script\&.cpp\&.
.SS "bool CScriptVisitor::operator() (const \fBCStealthAddress\fP & stxAddr) const\fC [inline]\fP"

.PP
Definition at line 3203 of file script\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
