.TH "CScriptID" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CScriptID \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pubkey\&.h>\fP
.PP
Inherits \fBuint160\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCScriptID\fP ()"
.br
.ti -1c
.RI "\fBCScriptID\fP (const \fBuint160\fP &in)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A reference to a \fBCScript\fP: the Hash160 of its serialization (see \fBscript\&.h\fP) 
.PP
Definition at line 35 of file pubkey\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CScriptID::CScriptID ()\fC [inline]\fP"

.PP
Definition at line 38 of file pubkey\&.h\&.
.SS "CScriptID::CScriptID (const \fBuint160\fP & in)\fC [inline]\fP"

.PP
Definition at line 39 of file pubkey\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
