.TH "CSemaphoreGrant" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSemaphoreGrant \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sync\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAcquire\fP ()"
.br
.ti -1c
.RI "void \fBRelease\fP ()"
.br
.ti -1c
.RI "bool \fBTryAcquire\fP ()"
.br
.ti -1c
.RI "void \fBMoveTo\fP (\fBCSemaphoreGrant\fP &grant)"
.br
.ti -1c
.RI "\fBCSemaphoreGrant\fP ()"
.br
.ti -1c
.RI "\fBCSemaphoreGrant\fP (\fBCSemaphore\fP &sema, bool fTry=false)"
.br
.ti -1c
.RI "\fB~CSemaphoreGrant\fP ()"
.br
.ti -1c
.RI "\fBoperator bool\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
RAII-style semaphore lock 
.PP
Definition at line 211 of file sync\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CSemaphoreGrant::CSemaphoreGrant ()\fC [inline]\fP"

.PP
Definition at line 246 of file sync\&.h\&.
.SS "CSemaphoreGrant::CSemaphoreGrant (\fBCSemaphore\fP & sema, bool fTry = \fCfalse\fP)\fC [inline]\fP"

.PP
Definition at line 248 of file sync\&.h\&.
.SS "CSemaphoreGrant::~CSemaphoreGrant ()\fC [inline]\fP"

.PP
Definition at line 255 of file sync\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void CSemaphoreGrant::Acquire ()\fC [inline]\fP"

.PP
Definition at line 218 of file sync\&.h\&.
.SS "void CSemaphoreGrant::MoveTo (\fBCSemaphoreGrant\fP & grant)\fC [inline]\fP"

.PP
Definition at line 238 of file sync\&.h\&.
.SS "CSemaphoreGrant::operator bool ()\fC [inline]\fP"

.PP
Definition at line 259 of file sync\&.h\&.
.SS "void CSemaphoreGrant::Release ()\fC [inline]\fP"

.PP
Definition at line 225 of file sync\&.h\&.
.SS "bool CSemaphoreGrant::TryAcquire ()\fC [inline]\fP"

.PP
Definition at line 232 of file sync\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
