.TH "CSerActionGetSerializeSize" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSerActionGetSerializeSize \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <serialize\&.h>\fP
.SH "Detailed Description"
.PP 
Definition at line 793 of file serialize\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
