.TH "CService" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CService \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <netbase\&.h>\fP
.PP
Inherits \fBCNetAddr\fP\&.
.PP
Inherited by \fBCAddress\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCService\fP ()"
.br
.ti -1c
.RI "\fBCService\fP (const \fBCNetAddr\fP &\fBip\fP, unsigned short \fBport\fP)"
.br
.ti -1c
.RI "\fBCService\fP (const struct in_addr &ipv4Addr, unsigned short \fBport\fP)"
.br
.ti -1c
.RI "\fBCService\fP (const struct sockaddr_in &addr)"
.br
.ti -1c
.RI "\fBCService\fP (const char *pszIpPort, int portDefault, bool fAllowLookup=false)"
.br
.ti -1c
.RI "\fBCService\fP (const char *pszIpPort, bool fAllowLookup=false)"
.br
.ti -1c
.RI "\fBCService\fP (const std::string &strIpPort, int portDefault, bool fAllowLookup=false)"
.br
.ti -1c
.RI "\fBCService\fP (const std::string &strIpPort, bool fAllowLookup=false)"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBSetPort\fP (unsigned short portIn)"
.br
.ti -1c
.RI "unsigned short \fBGetPort\fP () const "
.br
.ti -1c
.RI "bool \fBGetSockAddr\fP (struct sockaddr *paddr, socklen_t *addrlen) const "
.br
.ti -1c
.RI "bool \fBSetSockAddr\fP (const struct sockaddr *paddr)"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBGetKey\fP () const "
.br
.ti -1c
.RI "std::string \fBToString\fP () const "
.br
.ti -1c
.RI "std::string \fBToStringPort\fP () const "
.br
.ti -1c
.RI "std::string \fBToStringIPPort\fP () const "
.br
.ti -1c
.RI "\fBCService\fP (const struct in6_addr &ipv6Addr, unsigned short \fBport\fP)"
.br
.ti -1c
.RI "\fBCService\fP (const struct sockaddr_in6 &addr)"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBport\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCService\fP &a, const \fBCService\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBCService\fP &a, const \fBCService\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBCService\fP &a, const \fBCService\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A combination of a network address (\fBCNetAddr\fP) and a (TCP) port 
.PP
Definition at line 114 of file netbase\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CService::CService ()"

.PP
Definition at line 1076 of file netbase\&.cpp\&.
.SS "CService::CService (const \fBCNetAddr\fP & ip, unsigned short port)"

.PP
Definition at line 1081 of file netbase\&.cpp\&.
.SS "CService::CService (const struct in_addr & ipv4Addr, unsigned short port)"

.PP
Definition at line 1085 of file netbase\&.cpp\&.
.SS "CService::CService (const struct sockaddr_in & addr)"

.PP
Definition at line 1093 of file netbase\&.cpp\&.
.SS "CService::CService (const char * pszIpPort, int portDefault, bool fAllowLookup = \fCfalse\fP)\fC [explicit]\fP"

.PP
Definition at line 1125 of file netbase\&.cpp\&.
.SS "CService::CService (const char * pszIpPort, bool fAllowLookup = \fCfalse\fP)\fC [explicit]\fP"

.PP
Definition at line 1117 of file netbase\&.cpp\&.
.SS "CService::CService (const std::string & strIpPort, int portDefault, bool fAllowLookup = \fCfalse\fP)\fC [explicit]\fP"

.PP
Definition at line 1141 of file netbase\&.cpp\&.
.SS "CService::CService (const std::string & strIpPort, bool fAllowLookup = \fCfalse\fP)\fC [explicit]\fP"

.PP
Definition at line 1133 of file netbase\&.cpp\&.
.SS "CService::CService (const struct in6_addr & ipv6Addr, unsigned short port)"

.PP
Definition at line 1089 of file netbase\&.cpp\&.
.SS "CService::CService (const struct sockaddr_in6 & addr)"

.PP
Definition at line 1098 of file netbase\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::vector< unsigned char > CService::GetKey () const"

.PP
Definition at line 1198 of file netbase\&.cpp\&.
.SS "unsigned short CService::GetPort () const"

.PP
Definition at line 1149 of file netbase\&.cpp\&.
.SS "bool CService::GetSockAddr (struct sockaddr * paddr, socklen_t * addrlen) const"

.PP
Definition at line 1169 of file netbase\&.cpp\&.
.SS "void CService::Init ()"

.PP
Definition at line 1071 of file netbase\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CService::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 147 of file netbase\&.h\&.
.SS "void CService::SetPort (unsigned short portIn)"

.PP
Definition at line 1227 of file netbase\&.cpp\&.
.SS "bool CService::SetSockAddr (const struct sockaddr * paddr)"

.PP
Definition at line 1103 of file netbase\&.cpp\&.
.SS "std::string CService::ToString () const"

.PP
Definition at line 1222 of file netbase\&.cpp\&.
.SS "std::string CService::ToStringIPPort () const"

.PP
Definition at line 1213 of file netbase\&.cpp\&.
.SS "std::string CService::ToStringPort () const"

.PP
Definition at line 1208 of file netbase\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "bool operator!= (const \fBCService\fP & a, const \fBCService\fP & b)\fC [friend]\fP"

.PP
Definition at line 1159 of file netbase\&.cpp\&.
.SS "bool operator< (const \fBCService\fP & a, const \fBCService\fP & b)\fC [friend]\fP"

.PP
Definition at line 1164 of file netbase\&.cpp\&.
.SS "bool operator== (const \fBCService\fP & a, const \fBCService\fP & b)\fC [friend]\fP"

.PP
Definition at line 1154 of file netbase\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "CService::ADD_SERIALIZE_METHODS"

.PP
Definition at line 144 of file netbase\&.h\&.
.SS "unsigned short CService::port\fC [protected]\fP"

.PP
Definition at line 117 of file netbase\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
