.TH "CSignatureCache" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSignatureCache \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBGet\fP (const \fBuint256\fP &\fBhash\fP, const std::vector< unsigned char > &vchSig, const \fBCPubKey\fP &pubKey)"
.br
.ti -1c
.RI "void \fBSet\fP (const \fBuint256\fP &\fBhash\fP, const std::vector< unsigned char > &vchSig, const \fBCPubKey\fP &pubKey)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2247 of file script\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CSignatureCache::Get (const \fBuint256\fP & hash, const std::vector< unsigned char > & vchSig, const \fBCPubKey\fP & pubKey)\fC [inline]\fP"

.PP
Definition at line 2257 of file script\&.cpp\&.
.SS "void CSignatureCache::Set (const \fBuint256\fP & hash, const std::vector< unsigned char > & vchSig, const \fBCPubKey\fP & pubKey)\fC [inline]\fP"

.PP
Definition at line 2268 of file script\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
