.TH "CSizeComputer" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSizeComputer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <serialize\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCSizeComputer\fP (int nTypeIn, int nVersionIn)"
.br
.ti -1c
.RI "\fBCSizeComputer\fP & \fBwrite\fP (const char *psz, size_t \fBnSize\fP)"
.br
.ti -1c
.RI "template<typename T > \fBCSizeComputer\fP & \fBoperator<<\fP (const T &obj)"
.br
.ti -1c
.RI "size_t \fBsize\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnType\fP"
.br
.ti -1c
.RI "int \fBnVersion\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "size_t \fBnSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 838 of file serialize\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CSizeComputer::CSizeComputer (int nTypeIn, int nVersionIn)\fC [inline]\fP"

.PP
Definition at line 847 of file serialize\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > \fBCSizeComputer\fP& CSizeComputer::operator<< (const T & obj)\fC [inline]\fP"

.PP
Definition at line 856 of file serialize\&.h\&.
.SS "size_t CSizeComputer::size () const\fC [inline]\fP"

.PP
Definition at line 862 of file serialize\&.h\&.
.SS "\fBCSizeComputer\fP& CSizeComputer::write (const char * psz, size_t nSize)\fC [inline]\fP"

.PP
Definition at line 849 of file serialize\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "size_t CSizeComputer::nSize\fC [protected]\fP"

.PP
Definition at line 841 of file serialize\&.h\&.
.SS "int CSizeComputer::nType"

.PP
Definition at line 844 of file serialize\&.h\&.
.SS "int CSizeComputer::nVersion"

.PP
Definition at line 845 of file serialize\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
