.TH "CSporkMessage" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSporkMessage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spork\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBuint256\fP \fBGetHash\fP ()"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< unsigned char > \fBvchSig\fP"
.br
.ti -1c
.RI "int \fBnSporkID\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnValue\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnTimeSigned\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 71 of file spork\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBuint256\fP CSporkMessage::GetHash ()\fC [inline]\fP"

.PP
Definition at line 79 of file spork\&.h\&.
.SS "template<typename Stream , typename Operation > void CSporkMessage::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 87 of file spork\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CSporkMessage::ADD_SERIALIZE_METHODS"

.PP
Definition at line 84 of file spork\&.h\&.
.SS "int CSporkMessage::nSporkID"

.PP
Definition at line 75 of file spork\&.h\&.
.SS "\fBint64_t\fP CSporkMessage::nTimeSigned"

.PP
Definition at line 77 of file spork\&.h\&.
.SS "\fBint64_t\fP CSporkMessage::nValue"

.PP
Definition at line 76 of file spork\&.h\&.
.SS "std::vector<unsigned char> CSporkMessage::vchSig"

.PP
Definition at line 74 of file spork\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
