.TH "CSporkManager" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSporkManager \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spork\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCSporkManager\fP ()"
.br
.ti -1c
.RI "std::string \fBGetSporkNameByID\fP (int \fBid\fP)"
.br
.ti -1c
.RI "int \fBGetSporkIDByName\fP (std::string strName)"
.br
.ti -1c
.RI "bool \fBUpdateSpork\fP (int nSporkID, \fBint64_t\fP nValue)"
.br
.ti -1c
.RI "bool \fBSetPrivKey\fP (std::string strPrivKey)"
.br
.ti -1c
.RI "bool \fBCheckSignature\fP (\fBCSporkMessage\fP &\fBspork\fP)"
.br
.ti -1c
.RI "bool \fBSign\fP (\fBCSporkMessage\fP &\fBspork\fP)"
.br
.ti -1c
.RI "void \fBRelay\fP (\fBCSporkMessage\fP &msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 97 of file spork\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CSporkManager::CSporkManager ()\fC [inline]\fP"

.PP
Definition at line 107 of file spork\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CSporkManager::CheckSignature (\fBCSporkMessage\fP & spork)"

.PP
Definition at line 175 of file spork\&.cpp\&.
.SS "int CSporkManager::GetSporkIDByName (std::string strName)"

.PP
Definition at line 264 of file spork\&.cpp\&.
.SS "std::string CSporkManager::GetSporkNameByID (int id)"

.PP
Definition at line 277 of file spork\&.cpp\&.
.SS "void CSporkManager::Relay (\fBCSporkMessage\fP & msg)"

.PP
Definition at line 235 of file spork\&.cpp\&.
.SS "bool CSporkManager::SetPrivKey (std::string strPrivKey)"

.PP
Definition at line 247 of file spork\&.cpp\&.
.SS "bool CSporkManager::Sign (\fBCSporkMessage\fP & spork)"

.PP
Definition at line 190 of file spork\&.cpp\&.
.SS "bool CSporkManager::UpdateSpork (int nSporkID, \fBint64_t\fP nValue)"

.PP
Definition at line 217 of file spork\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
