.TH "CStealthKeyMetadata" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CStealthKeyMetadata \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <walletdb\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCStealthKeyMetadata\fP ()"
.br
.ti -1c
.RI "\fBCStealthKeyMetadata\fP (\fBCPubKey\fP pkEphem_, \fBCPubKey\fP pkScan_)"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCPubKey\fP \fBpkEphem\fP"
.br
.ti -1c
.RI "\fBCPubKey\fP \fBpkScan\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 74 of file walletdb\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CStealthKeyMetadata::CStealthKeyMetadata ()\fC [inline]\fP"

.PP
Definition at line 78 of file walletdb\&.h\&.
.SS "CStealthKeyMetadata::CStealthKeyMetadata (\fBCPubKey\fP pkEphem_, \fBCPubKey\fP pkScan_)\fC [inline]\fP"

.PP
Definition at line 80 of file walletdb\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream , typename Operation > void CStealthKeyMetadata::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 92 of file walletdb\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CStealthKeyMetadata::ADD_SERIALIZE_METHODS"

.PP
Definition at line 89 of file walletdb\&.h\&.
.SS "\fBCPubKey\fP CStealthKeyMetadata::pkEphem"

.PP
Definition at line 84 of file walletdb\&.h\&.
.SS "\fBCPubKey\fP CStealthKeyMetadata::pkScan"

.PP
Definition at line 87 of file walletdb\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
