.TH "CStormnodeMan" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CStormnodeMan \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stormnodeman\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.ti -1c
.RI "\fBCStormnodeMan\fP ()"
.br
.ti -1c
.RI "\fBCStormnodeMan\fP (\fBCStormnodeMan\fP &other)"
.br
.ti -1c
.RI "bool \fBAdd\fP (\fBCStormnode\fP &sn)"
.br
.RI "\fIAdd an entry\&. \fP"
.ti -1c
.RI "void \fBAskForSN\fP (\fBCNode\fP *pnode, \fBCTxIn\fP &vin)"
.br
.RI "\fIAsk (source) node for snb\&. \fP"
.ti -1c
.RI "void \fBCheck\fP ()"
.br
.RI "\fICheck all Stormnodes\&. \fP"
.ti -1c
.RI "void \fBCheckAndRemove\fP (bool forceExpiredRemoval=false)"
.br
.RI "\fICheck all Stormnodes and remove inactive\&. \fP"
.ti -1c
.RI "void \fBClear\fP ()"
.br
.RI "\fIClear Stormnode vector\&. \fP"
.ti -1c
.RI "int \fBCountEnabled\fP (int protocolVersion=-1)"
.br
.ti -1c
.RI "void \fBSsegUpdate\fP (\fBCNode\fP *pnode)"
.br
.ti -1c
.RI "\fBCStormnode\fP * \fBFind\fP (const \fBCScript\fP &payee)"
.br
.RI "\fIFind an entry\&. \fP"
.ti -1c
.RI "\fBCStormnode\fP * \fBFind\fP (const \fBCTxIn\fP &vin)"
.br
.ti -1c
.RI "\fBCStormnode\fP * \fBFind\fP (const \fBCPubKey\fP &pubKeyStormnode)"
.br
.ti -1c
.RI "\fBCStormnode\fP * \fBGetNextStormnodeInQueueForPayment\fP (int nBlockHeight, bool fFilterSigTime, int &nCount)"
.br
.RI "\fIFind an entry in the stormnode list that is next to be paid\&. \fP"
.ti -1c
.RI "\fBCStormnode\fP * \fBFindRandomNotInVec\fP (std::vector< \fBCTxIn\fP > &vecToExclude, int protocolVersion=-1)"
.br
.RI "\fIFind a random entry\&. \fP"
.ti -1c
.RI "\fBCStormnode\fP * \fBGetCurrentStormNode\fP (int mod=1, \fBint64_t\fP nBlockHeight=0, int minProtocol=0)"
.br
.RI "\fIGet the current winner for this block\&. \fP"
.ti -1c
.RI "std::vector< \fBCStormnode\fP > \fBGetFullStormnodeVector\fP ()"
.br
.ti -1c
.RI "std::vector< pair< int, \fBCStormnode\fP > > \fBGetStormnodeRanks\fP (\fBint64_t\fP nBlockHeight, int minProtocol=0)"
.br
.ti -1c
.RI "int \fBGetStormnodeRank\fP (const \fBCTxIn\fP &vin, \fBint64_t\fP nBlockHeight, int minProtocol=0, bool fOnlyActive=true)"
.br
.ti -1c
.RI "\fBCStormnode\fP * \fBGetStormnodeByRank\fP (int nRank, \fBint64_t\fP nBlockHeight, int minProtocol=0, bool fOnlyActive=true)"
.br
.ti -1c
.RI "void \fBProcessStormnodeConnections\fP ()"
.br
.ti -1c
.RI "void \fBProcessMessage\fP (\fBCNode\fP *pfrom, std::string &strCommand, \fBCDataStream\fP &vRecv)"
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.RI "\fIReturn the number of (unique) Stormnodes\&. \fP"
.ti -1c
.RI "std::string \fBToString\fP () const "
.br
.ti -1c
.RI "void \fBRemove\fP (\fBCTxIn\fP vin)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "map< \fBuint256\fP, \fBCStormnodeBroadcast\fP > \fBmapSeenStormnodeBroadcast\fP"
.br
.ti -1c
.RI "map< \fBuint256\fP, \fBCStormnodePing\fP > \fBmapSeenStormnodePing\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnSsqCount\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file stormnodeman\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CStormnodeMan::CStormnodeMan ()"

.PP
Definition at line 207 of file stormnodeman\&.cpp\&.
.SS "CStormnodeMan::CStormnodeMan (\fBCStormnodeMan\fP & other)"

.SH "Member Function Documentation"
.PP 
.SS "bool CStormnodeMan::Add (\fBCStormnode\fP & sn)"

.PP
Add an entry\&. 
.PP
Definition at line 211 of file stormnodeman\&.cpp\&.
.SS "void CStormnodeMan::AskForSN (\fBCNode\fP * pnode, \fBCTxIn\fP & vin)"

.PP
Ask (source) node for snb\&. 
.PP
Definition at line 229 of file stormnodeman\&.cpp\&.
.SS "void CStormnodeMan::Check ()"

.PP
Check all Stormnodes\&. 
.PP
Definition at line 246 of file stormnodeman\&.cpp\&.
.SS "void CStormnodeMan::CheckAndRemove (bool forceExpiredRemoval = \fCfalse\fP)"

.PP
Check all Stormnodes and remove inactive\&. 
.PP
Definition at line 255 of file stormnodeman\&.cpp\&.
.SS "void CStormnodeMan::Clear ()"

.PP
Clear Stormnode vector\&. 
.PP
Definition at line 352 of file stormnodeman\&.cpp\&.
.SS "int CStormnodeMan::CountEnabled (int protocolVersion = \fC-1\fP)"

.PP
Definition at line 364 of file stormnodeman\&.cpp\&.
.SS "\fBCStormnode\fP * CStormnodeMan::Find (const \fBCScript\fP & payee)"

.PP
Find an entry\&. 
.PP
Definition at line 400 of file stormnodeman\&.cpp\&.
.SS "\fBCStormnode\fP * CStormnodeMan::Find (const \fBCTxIn\fP & vin)"

.PP
Definition at line 414 of file stormnodeman\&.cpp\&.
.SS "\fBCStormnode\fP * CStormnodeMan::Find (const \fBCPubKey\fP & pubKeyStormnode)"

.PP
Definition at line 427 of file stormnodeman\&.cpp\&.
.SS "\fBCStormnode\fP * CStormnodeMan::FindRandomNotInVec (std::vector< \fBCTxIn\fP > & vecToExclude, int protocolVersion = \fC-1\fP)"

.PP
Find a random entry\&. 
.PP
Definition at line 504 of file stormnodeman\&.cpp\&.
.SS "\fBCStormnode\fP * CStormnodeMan::GetCurrentStormNode (int mod = \fC1\fP, \fBint64_t\fP nBlockHeight = \fC0\fP, int minProtocol = \fC0\fP)"

.PP
Get the current winner for this block\&. 
.PP
Definition at line 536 of file stormnodeman\&.cpp\&.
.SS "std::vector<\fBCStormnode\fP> CStormnodeMan::GetFullStormnodeVector ()\fC [inline]\fP"

.PP
Definition at line 127 of file stormnodeman\&.h\&.
.SS "\fBCStormnode\fP * CStormnodeMan::GetNextStormnodeInQueueForPayment (int nBlockHeight, bool fFilterSigTime, int & nCount)"

.PP
Find an entry in the stormnode list that is next to be paid\&. 
.PP
Definition at line 442 of file stormnodeman\&.cpp\&.
.SS "\fBCStormnode\fP * CStormnodeMan::GetStormnodeByRank (int nRank, \fBint64_t\fP nBlockHeight, int minProtocol = \fC0\fP, bool fOnlyActive = \fCtrue\fP)"

.PP
Definition at line 630 of file stormnodeman\&.cpp\&.
.SS "int CStormnodeMan::GetStormnodeRank (const \fBCTxIn\fP & vin, \fBint64_t\fP nBlockHeight, int minProtocol = \fC0\fP, bool fOnlyActive = \fCtrue\fP)"

.PP
Definition at line 560 of file stormnodeman\&.cpp\&.
.SS "std::vector< pair< int, \fBCStormnode\fP > > CStormnodeMan::GetStormnodeRanks (\fBint64_t\fP nBlockHeight, int minProtocol = \fC0\fP)"

.PP
Definition at line 594 of file stormnodeman\&.cpp\&.
.SS "void CStormnodeMan::ProcessMessage (\fBCNode\fP * pfrom, std::string & strCommand, \fBCDataStream\fP & vRecv)"

.PP
Definition at line 674 of file stormnodeman\&.cpp\&.
.SS "void CStormnodeMan::ProcessStormnodeConnections ()"

.PP
Definition at line 662 of file stormnodeman\&.cpp\&.
.SS "void CStormnodeMan::Remove (\fBCTxIn\fP vin)"

.PP
Definition at line 805 of file stormnodeman\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CStormnodeMan::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 79 of file stormnodeman\&.h\&.
.SS "int CStormnodeMan::size ()\fC [inline]\fP"

.PP
Return the number of (unique) Stormnodes\&. 
.PP
Definition at line 138 of file stormnodeman\&.h\&.
.SS "void CStormnodeMan::SsegUpdate (\fBCNode\fP * pnode)"

.PP
Definition at line 378 of file stormnodeman\&.cpp\&.
.SS "std::string CStormnodeMan::ToString () const"

.PP
Definition at line 820 of file stormnodeman\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "CStormnodeMan::ADD_SERIALIZE_METHODS"

.PP
Definition at line 76 of file stormnodeman\&.h\&.
.SS "map<\fBuint256\fP, \fBCStormnodeBroadcast\fP> CStormnodeMan::mapSeenStormnodeBroadcast"

.PP
Definition at line 69 of file stormnodeman\&.h\&.
.SS "map<\fBuint256\fP, \fBCStormnodePing\fP> CStormnodeMan::mapSeenStormnodePing"

.PP
Definition at line 71 of file stormnodeman\&.h\&.
.SS "\fBint64_t\fP CStormnodeMan::nSsqCount"

.PP
Definition at line 74 of file stormnodeman\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
