.TH "CStormnodeConfig::CStormnodeEntry" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CStormnodeConfig::CStormnodeEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stormnodeconfig\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCStormnodeEntry\fP (std::string alias, std::string ip, std::string privKey, std::string txHash, std::string outputIndex, std::string donationAddress, std::string donationPercent)"
.br
.ti -1c
.RI "const std::string & \fBgetAlias\fP () const "
.br
.ti -1c
.RI "void \fBsetAlias\fP (const std::string &alias)"
.br
.ti -1c
.RI "const std::string & \fBgetOutputIndex\fP () const "
.br
.ti -1c
.RI "void \fBsetOutputIndex\fP (const std::string &outputIndex)"
.br
.ti -1c
.RI "const std::string & \fBgetPrivKey\fP () const "
.br
.ti -1c
.RI "void \fBsetPrivKey\fP (const std::string &privKey)"
.br
.ti -1c
.RI "const std::string & \fBgetTxHash\fP () const "
.br
.ti -1c
.RI "void \fBsetTxHash\fP (const std::string &txHash)"
.br
.ti -1c
.RI "const std::string & \fBgetIp\fP () const "
.br
.ti -1c
.RI "void \fBsetIp\fP (const std::string &ip)"
.br
.ti -1c
.RI "const std::string & \fBgetDonationAddress\fP () const "
.br
.ti -1c
.RI "const std::string & \fBgetDonationPercentage\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file stormnodeconfig\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CStormnodeConfig::CStormnodeEntry::CStormnodeEntry (std::string alias, std::string ip, std::string privKey, std::string txHash, std::string outputIndex, std::string donationAddress, std::string donationPercent)\fC [inline]\fP"

.PP
Definition at line 28 of file stormnodeconfig\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "const std::string& CStormnodeConfig::CStormnodeEntry::getAlias () const\fC [inline]\fP"

.PP
Definition at line 38 of file stormnodeconfig\&.h\&.
.SS "const std::string& CStormnodeConfig::CStormnodeEntry::getDonationAddress () const\fC [inline]\fP"

.PP
Definition at line 78 of file stormnodeconfig\&.h\&.
.SS "const std::string& CStormnodeConfig::CStormnodeEntry::getDonationPercentage () const\fC [inline]\fP"

.PP
Definition at line 82 of file stormnodeconfig\&.h\&.
.SS "const std::string& CStormnodeConfig::CStormnodeEntry::getIp () const\fC [inline]\fP"

.PP
Definition at line 70 of file stormnodeconfig\&.h\&.
.SS "const std::string& CStormnodeConfig::CStormnodeEntry::getOutputIndex () const\fC [inline]\fP"

.PP
Definition at line 46 of file stormnodeconfig\&.h\&.
.SS "const std::string& CStormnodeConfig::CStormnodeEntry::getPrivKey () const\fC [inline]\fP"

.PP
Definition at line 54 of file stormnodeconfig\&.h\&.
.SS "const std::string& CStormnodeConfig::CStormnodeEntry::getTxHash () const\fC [inline]\fP"

.PP
Definition at line 62 of file stormnodeconfig\&.h\&.
.SS "void CStormnodeConfig::CStormnodeEntry::setAlias (const std::string & alias)\fC [inline]\fP"

.PP
Definition at line 42 of file stormnodeconfig\&.h\&.
.SS "void CStormnodeConfig::CStormnodeEntry::setIp (const std::string & ip)\fC [inline]\fP"

.PP
Definition at line 74 of file stormnodeconfig\&.h\&.
.SS "void CStormnodeConfig::CStormnodeEntry::setOutputIndex (const std::string & outputIndex)\fC [inline]\fP"

.PP
Definition at line 50 of file stormnodeconfig\&.h\&.
.SS "void CStormnodeConfig::CStormnodeEntry::setPrivKey (const std::string & privKey)\fC [inline]\fP"

.PP
Definition at line 58 of file stormnodeconfig\&.h\&.
.SS "void CStormnodeConfig::CStormnodeEntry::setTxHash (const std::string & txHash)\fC [inline]\fP"

.PP
Definition at line 66 of file stormnodeconfig\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
