.TH "CStormnodeBlockPayees" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CStormnodeBlockPayees \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stormnode-payments\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCStormnodeBlockPayees\fP ()"
.br
.ti -1c
.RI "\fBCStormnodeBlockPayees\fP (int nBlockHeightIn)"
.br
.ti -1c
.RI "void \fBAddPayee\fP (\fBCScript\fP payeeIn, int nIncrement)"
.br
.ti -1c
.RI "bool \fBGetPayee\fP (\fBCScript\fP &payee)"
.br
.ti -1c
.RI "bool \fBHasPayeeWithVotes\fP (\fBCScript\fP payee, int nVotesReq)"
.br
.ti -1c
.RI "bool \fBIsTransactionValid\fP (const \fBCTransaction\fP &txNew)"
.br
.ti -1c
.RI "std::string \fBGetRequiredPaymentsString\fP ()"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnBlockHeight\fP"
.br
.ti -1c
.RI "std::vector< \fBCStormnodePayee\fP > \fBvecPayments\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 86 of file stormnode-payments\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CStormnodeBlockPayees::CStormnodeBlockPayees ()\fC [inline]\fP"

.PP
Definition at line 92 of file stormnode-payments\&.h\&.
.SS "CStormnodeBlockPayees::CStormnodeBlockPayees (int nBlockHeightIn)\fC [inline]\fP"

.PP
Definition at line 96 of file stormnode-payments\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void CStormnodeBlockPayees::AddPayee (\fBCScript\fP payeeIn, int nIncrement)\fC [inline]\fP"

.PP
Definition at line 101 of file stormnode-payments\&.h\&.
.SS "bool CStormnodeBlockPayees::GetPayee (\fBCScript\fP & payee)\fC [inline]\fP"

.PP
Definition at line 115 of file stormnode-payments\&.h\&.
.SS "std::string CStormnodeBlockPayees::GetRequiredPaymentsString ()"

.PP
Definition at line 566 of file stormnode-payments\&.cpp\&.
.SS "bool CStormnodeBlockPayees::HasPayeeWithVotes (\fBCScript\fP payee, int nVotesReq)\fC [inline]\fP"

.PP
Definition at line 130 of file stormnode-payments\&.h\&.
.SS "bool CStormnodeBlockPayees::IsTransactionValid (const \fBCTransaction\fP & txNew)"

.PP
Definition at line 519 of file stormnode-payments\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CStormnodeBlockPayees::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 147 of file stormnode-payments\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CStormnodeBlockPayees::ADD_SERIALIZE_METHODS"

.PP
Definition at line 144 of file stormnode-payments\&.h\&.
.SS "int CStormnodeBlockPayees::nBlockHeight"

.PP
Definition at line 89 of file stormnode-payments\&.h\&.
.SS "std::vector<\fBCStormnodePayee\fP> CStormnodeBlockPayees::vecPayments"

.PP
Definition at line 90 of file stormnode-payments\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
