.TH "CStormnodePing" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CStormnodePing \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stormnode\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCStormnodePing\fP ()"
.br
.ti -1c
.RI "\fBCStormnodePing\fP (\fBCTxIn\fP &newVin)"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.ti -1c
.RI "bool \fBCheckAndUpdate\fP (int &nDos, bool fRequireEnabled=true)"
.br
.ti -1c
.RI "bool \fBSign\fP (\fBCKey\fP &keyStormnode, \fBCPubKey\fP &pubKeyStormnode)"
.br
.ti -1c
.RI "void \fBRelay\fP ()"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetHash\fP ()"
.br
.ti -1c
.RI "void \fBswap\fP (\fBCStormnodePing\fP &first, \fBCStormnodePing\fP &second)"
.br
.ti -1c
.RI "\fBCStormnodePing\fP & \fBoperator=\fP (\fBCStormnodePing\fP from)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCTxIn\fP \fBvin\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBblockHash\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBsigTime\fP"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBvchSig\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCStormnodePing\fP &a, const \fBCStormnodePing\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBCStormnodePing\fP &a, const \fBCStormnodePing\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file stormnode\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CStormnodePing::CStormnodePing ()"

.PP
Definition at line 539 of file stormnode\&.cpp\&.
.SS "CStormnodePing::CStormnodePing (\fBCTxIn\fP & newVin)"

.PP
Definition at line 547 of file stormnode\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CStormnodePing::CheckAndUpdate (int & nDos, bool fRequireEnabled = \fCtrue\fP)"

.PP
Definition at line 578 of file stormnode\&.cpp\&.
.SS "\fBuint256\fP CStormnodePing::GetHash ()\fC [inline]\fP"

.PP
Definition at line 65 of file stormnode\&.h\&.
.SS "\fBCStormnodePing\fP& CStormnodePing::operator= (\fBCStormnodePing\fP from)\fC [inline]\fP"

.PP
Definition at line 85 of file stormnode\&.h\&.
.SS "void CStormnodePing::Relay ()"

.PP
Definition at line 666 of file stormnode\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CStormnodePing::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 54 of file stormnode\&.h\&.
.SS "bool CStormnodePing::Sign (\fBCKey\fP & keyStormnode, \fBCPubKey\fP & pubKeyStormnode)"

.PP
Definition at line 557 of file stormnode\&.cpp\&.
.SS "void CStormnodePing::swap (\fBCStormnodePing\fP & first, \fBCStormnodePing\fP & second)\fC [inline]\fP"

.PP
Definition at line 72 of file stormnode\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "bool operator!= (const \fBCStormnodePing\fP & a, const \fBCStormnodePing\fP & b)\fC [friend]\fP"

.PP
Definition at line 94 of file stormnode\&.h\&.
.SS "bool operator== (const \fBCStormnodePing\fP & a, const \fBCStormnodePing\fP & b)\fC [friend]\fP"

.PP
Definition at line 90 of file stormnode\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CStormnodePing::ADD_SERIALIZE_METHODS"

.PP
Definition at line 51 of file stormnode\&.h\&.
.SS "\fBuint256\fP CStormnodePing::blockHash"

.PP
Definition at line 43 of file stormnode\&.h\&.
.SS "\fBint64_t\fP CStormnodePing::sigTime"

.PP
Definition at line 44 of file stormnode\&.h\&.
.SS "std::vector<unsigned char> CStormnodePing::vchSig"

.PP
Definition at line 45 of file stormnode\&.h\&.
.SS "\fBCTxIn\fP CStormnodePing::vin"

.PP
Definition at line 42 of file stormnode\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
