.TH "CStormnodePaymentWinner" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CStormnodePaymentWinner \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stormnode-payments\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCStormnodePaymentWinner\fP ()"
.br
.ti -1c
.RI "\fBCStormnodePaymentWinner\fP (\fBCTxIn\fP vinIn)"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetHash\fP ()"
.br
.ti -1c
.RI "bool \fBSign\fP (\fBCKey\fP &keyStormnode, \fBCPubKey\fP &pubKeyStormnode)"
.br
.ti -1c
.RI "bool \fBIsValid\fP (\fBCNode\fP *pnode, std::string &strError)"
.br
.ti -1c
.RI "bool \fBSignatureValid\fP ()"
.br
.ti -1c
.RI "void \fBRelay\fP ()"
.br
.ti -1c
.RI "void \fBAddPayee\fP (\fBCScript\fP payeeIn)"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.ti -1c
.RI "std::string \fBToString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCTxIn\fP \fBvinStormnode\fP"
.br
.ti -1c
.RI "int \fBnBlockHeight\fP"
.br
.ti -1c
.RI "\fBCScript\fP \fBpayee\fP"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBvchSig\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 154 of file stormnode-payments\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CStormnodePaymentWinner::CStormnodePaymentWinner ()\fC [inline]\fP"

.PP
Definition at line 163 of file stormnode-payments\&.h\&.
.SS "CStormnodePaymentWinner::CStormnodePaymentWinner (\fBCTxIn\fP vinIn)\fC [inline]\fP"

.PP
Definition at line 169 of file stormnode-payments\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void CStormnodePaymentWinner::AddPayee (\fBCScript\fP payeeIn)\fC [inline]\fP"

.PP
Definition at line 189 of file stormnode-payments\&.h\&.
.SS "\fBuint256\fP CStormnodePaymentWinner::GetHash ()\fC [inline]\fP"

.PP
Definition at line 175 of file stormnode-payments\&.h\&.
.SS "bool CStormnodePaymentWinner::IsValid (\fBCNode\fP * pnode, std::string & strError)"

.PP
Definition at line 644 of file stormnode-payments\&.cpp\&.
.SS "void CStormnodePaymentWinner::Relay ()"

.PP
Definition at line 764 of file stormnode-payments\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CStormnodePaymentWinner::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 196 of file stormnode-payments\&.h\&.
.SS "bool CStormnodePaymentWinner::Sign (\fBCKey\fP & keyStormnode, \fBCPubKey\fP & pubKeyStormnode)"

.PP
Definition at line 432 of file stormnode-payments\&.cpp\&.
.SS "bool CStormnodePaymentWinner::SignatureValid ()"

.PP
Definition at line 770 of file stormnode-payments\&.cpp\&.
.SS "std::string CStormnodePaymentWinner::ToString ()\fC [inline]\fP"

.PP
Definition at line 203 of file stormnode-payments\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CStormnodePaymentWinner::ADD_SERIALIZE_METHODS"

.PP
Definition at line 193 of file stormnode-payments\&.h\&.
.SS "int CStormnodePaymentWinner::nBlockHeight"

.PP
Definition at line 159 of file stormnode-payments\&.h\&.
.SS "\fBCScript\fP CStormnodePaymentWinner::payee"

.PP
Definition at line 160 of file stormnode-payments\&.h\&.
.SS "std::vector<unsigned char> CStormnodePaymentWinner::vchSig"

.PP
Definition at line 161 of file stormnode-payments\&.h\&.
.SS "\fBCTxIn\fP CStormnodePaymentWinner::vinStormnode"

.PP
Definition at line 157 of file stormnode-payments\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
