.TH "CStormnodeDB" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CStormnodeDB \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stormnodeman\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBReadResult\fP { \fBOk\fP, \fBFileError\fP, \fBHashReadError\fP, \fBIncorrectHash\fP, \fBIncorrectMagicMessage\fP, \fBIncorrectMagicNumber\fP, \fBIncorrectFormat\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCStormnodeDB\fP ()"
.br
.ti -1c
.RI "bool \fBWrite\fP (const \fBCStormnodeMan\fP &snodemanToSave)"
.br
.ti -1c
.RI "\fBReadResult\fP \fBRead\fP (\fBCStormnodeMan\fP &snodemanToLoad, bool fDryRun=false)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Access to the SN database (sncache\&.dat) 
.PP
Definition at line 28 of file stormnodeman\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBCStormnodeDB::ReadResult\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOk \fP\fP
.TP
\fB\fIFileError \fP\fP
.TP
\fB\fIHashReadError \fP\fP
.TP
\fB\fIIncorrectHash \fP\fP
.TP
\fB\fIIncorrectMagicMessage \fP\fP
.TP
\fB\fIIncorrectMagicNumber \fP\fP
.TP
\fB\fIIncorrectFormat \fP\fP
.PP
Definition at line 34 of file stormnodeman\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CStormnodeDB::CStormnodeDB ()"

.PP
Definition at line 51 of file stormnodeman\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCStormnodeDB::ReadResult\fP CStormnodeDB::Read (\fBCStormnodeMan\fP & snodemanToLoad, bool fDryRun = \fCfalse\fP)"

.PP
Definition at line 91 of file stormnodeman\&.cpp\&.
.SS "bool CStormnodeDB::Write (const \fBCStormnodeMan\fP & snodemanToSave)"

.PP
Definition at line 57 of file stormnodeman\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
