.TH "CStormnodeBroadcast" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CStormnodeBroadcast \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stormnode\&.h>\fP
.PP
Inherits \fBCStormnode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCStormnodeBroadcast\fP ()"
.br
.ti -1c
.RI "\fBCStormnodeBroadcast\fP (\fBCService\fP newAddr, \fBCTxIn\fP newVin, \fBCPubKey\fP newPubkey, \fBCPubKey\fP newPubkey2, int protocolVersionIn)"
.br
.ti -1c
.RI "\fBCStormnodeBroadcast\fP (const \fBCStormnode\fP &sn)"
.br
.ti -1c
.RI "bool \fBCheckAndUpdate\fP (int &nDoS)"
.br
.ti -1c
.RI "bool \fBCheckInputsAndAdd\fP (int &nDos)"
.br
.ti -1c
.RI "bool \fBSign\fP (\fBCKey\fP &keyCollateralAddress)"
.br
.ti -1c
.RI "void \fBRelay\fP ()"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetHash\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 286 of file stormnode\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CStormnodeBroadcast::CStormnodeBroadcast ()"

.PP
Definition at line 291 of file stormnode\&.cpp\&.
.SS "CStormnodeBroadcast::CStormnodeBroadcast (\fBCService\fP newAddr, \fBCTxIn\fP newVin, \fBCPubKey\fP newPubkey, \fBCPubKey\fP newPubkey2, int protocolVersionIn)"

.PP
Definition at line 311 of file stormnode\&.cpp\&.
.SS "CStormnodeBroadcast::CStormnodeBroadcast (const \fBCStormnode\fP & sn)"

.PP
Definition at line 331 of file stormnode\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CStormnodeBroadcast::CheckAndUpdate (int & nDoS)"

.PP
Definition at line 351 of file stormnode\&.cpp\&.
.SS "bool CStormnodeBroadcast::CheckInputsAndAdd (int & nDos)"

.PP
Definition at line 424 of file stormnode\&.cpp\&.
.SS "\fBuint256\fP CStormnodeBroadcast::GetHash ()\fC [inline]\fP"

.PP
Definition at line 313 of file stormnode\&.h\&.
.SS "void CStormnodeBroadcast::Relay ()"

.PP
Definition at line 509 of file stormnode\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CStormnodeBroadcast::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 301 of file stormnode\&.h\&.
.SS "bool CStormnodeBroadcast::Sign (\fBCKey\fP & keyCollateralAddress)"

.PP
Definition at line 515 of file stormnode\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "CStormnodeBroadcast::ADD_SERIALIZE_METHODS"

.PP
Definition at line 298 of file stormnode\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
