.TH "CStormnodeConfig" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CStormnodeConfig \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stormnodeconfig\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCStormnodeEntry\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCStormnodeConfig\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "bool \fBread\fP (std::string &strErr)"
.br
.ti -1c
.RI "void \fBadd\fP (std::string alias, std::string ip, std::string privKey, std::string txHash, std::string outputIndex, std::string donationAddress, std::string donationPercent)"
.br
.ti -1c
.RI "std::vector< \fBCStormnodeEntry\fP > & \fBgetEntries\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file stormnodeconfig\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CStormnodeConfig::CStormnodeConfig ()\fC [inline]\fP"

.PP
Definition at line 87 of file stormnodeconfig\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void CStormnodeConfig::add (std::string alias, std::string ip, std::string privKey, std::string txHash, std::string outputIndex, std::string donationAddress, std::string donationPercent)"

.PP
Definition at line 16 of file stormnodeconfig\&.cpp\&.
.SS "void CStormnodeConfig::clear ()"

.SS "std::vector<\fBCStormnodeEntry\fP>& CStormnodeConfig::getEntries ()\fC [inline]\fP"

.PP
Definition at line 95 of file stormnodeconfig\&.h\&.
.SS "bool CStormnodeConfig::read (std::string & strErr)"

.PP
Definition at line 21 of file stormnodeconfig\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
