.TH "CStormnode" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CStormnode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stormnode\&.h>\fP
.PP
Inherited by \fBCStormnodeBroadcast\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBstate\fP { \fBSTORMNODE_PRE_ENABLED\fP, \fBSTORMNODE_ENABLED\fP, \fBSTORMNODE_EXPIRED\fP, \fBSTORMNODE_VIN_SPENT\fP, \fBSTORMNODE_REMOVE\fP, \fBSTORMNODE_POS_ERROR\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCStormnode\fP ()"
.br
.ti -1c
.RI "\fBCStormnode\fP (const \fBCStormnode\fP &other)"
.br
.ti -1c
.RI "\fBCStormnode\fP (const \fBCStormnodeBroadcast\fP &snb)"
.br
.ti -1c
.RI "void \fBswap\fP (\fBCStormnode\fP &first, \fBCStormnode\fP &second)"
.br
.ti -1c
.RI "\fBCStormnode\fP & \fBoperator=\fP (\fBCStormnode\fP from)"
.br
.ti -1c
.RI "\fBuint256\fP \fBCalculateScore\fP (int mod=1, \fBint64_t\fP nBlockHeight=0)"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.ti -1c
.RI "\fBint64_t\fP \fBSecondsSincePayment\fP ()"
.br
.ti -1c
.RI "bool \fBUpdateFromNewBroadcast\fP (\fBCStormnodeBroadcast\fP &snb)"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBSliceHash\fP (\fBuint256\fP &\fBhash\fP, int slice)"
.br
.ti -1c
.RI "void \fBCheck\fP (bool forceCheck=false)"
.br
.ti -1c
.RI "bool \fBIsBroadcastedWithin\fP (int seconds)"
.br
.ti -1c
.RI "bool \fBIsPingedWithin\fP (int seconds, \fBint64_t\fP now=-1)"
.br
.ti -1c
.RI "void \fBDisable\fP ()"
.br
.ti -1c
.RI "bool \fBIsEnabled\fP ()"
.br
.ti -1c
.RI "bool \fBIsPreEnabled\fP ()"
.br
.ti -1c
.RI "int \fBGetStormnodeInputAge\fP ()"
.br
.ti -1c
.RI "std::string \fBStatus\fP ()"
.br
.ti -1c
.RI "\fBint64_t\fP \fBGetLastPaid\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCTxIn\fP \fBvin\fP"
.br
.ti -1c
.RI "\fBCService\fP \fBaddr\fP"
.br
.ti -1c
.RI "\fBCPubKey\fP \fBpubkey\fP"
.br
.ti -1c
.RI "\fBCPubKey\fP \fBpubkey2\fP"
.br
.ti -1c
.RI "std::vector< unsigned char > \fBsig\fP"
.br
.ti -1c
.RI "int \fBactiveState\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBsigTime\fP"
.br
.ti -1c
.RI "int \fBcacheInputAge\fP"
.br
.ti -1c
.RI "int \fBcacheInputAgeBlock\fP"
.br
.ti -1c
.RI "bool \fBunitTest\fP"
.br
.ti -1c
.RI "bool \fBallowFreeTx\fP"
.br
.ti -1c
.RI "int \fBprotocolVersion\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnLastSsq\fP"
.br
.ti -1c
.RI "int \fBnScanningErrorCount\fP"
.br
.ti -1c
.RI "int \fBnLastScanningErrorBlockHeight\fP"
.br
.ti -1c
.RI "\fBCStormnodePing\fP \fBlastPing\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCStormnode\fP &a, const \fBCStormnode\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBCStormnode\fP &a, const \fBCStormnode\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 106 of file stormnode\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBCStormnode::state\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISTORMNODE_PRE_ENABLED \fP\fP
.TP
\fB\fISTORMNODE_ENABLED \fP\fP
.TP
\fB\fISTORMNODE_EXPIRED \fP\fP
.TP
\fB\fISTORMNODE_VIN_SPENT \fP\fP
.TP
\fB\fISTORMNODE_REMOVE \fP\fP
.TP
\fB\fISTORMNODE_POS_ERROR \fP\fP
.PP
Definition at line 113 of file stormnode\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CStormnode::CStormnode ()"

.PP
Definition at line 59 of file stormnode\&.cpp\&.
.SS "CStormnode::CStormnode (const \fBCStormnode\fP & other)"

.PP
Definition at line 81 of file stormnode\&.cpp\&.
.SS "CStormnode::CStormnode (const \fBCStormnodeBroadcast\fP & snb)"

.PP
Definition at line 103 of file stormnode\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBuint256\fP CStormnode::CalculateScore (int mod = \fC1\fP, \fBint64_t\fP nBlockHeight = \fC0\fP)"

.PP
Definition at line 152 of file stormnode\&.cpp\&.
.SS "void CStormnode::Check (bool forceCheck = \fCfalse\fP)"

.PP
Definition at line 178 of file stormnode\&.cpp\&.
.SS "void CStormnode::Disable ()\fC [inline]\fP"

.PP
Definition at line 236 of file stormnode\&.h\&.
.SS "\fBint64_t\fP CStormnode::GetLastPaid ()"

.PP
Definition at line 246 of file stormnode\&.cpp\&.
.SS "int CStormnode::GetStormnodeInputAge ()\fC [inline]\fP"

.PP
Definition at line 252 of file stormnode\&.h\&.
.SS "bool CStormnode::IsBroadcastedWithin (int seconds)\fC [inline]\fP"

.PP
Definition at line 222 of file stormnode\&.h\&.
.SS "bool CStormnode::IsEnabled ()\fC [inline]\fP"

.PP
Definition at line 242 of file stormnode\&.h\&.
.SS "bool CStormnode::IsPingedWithin (int seconds, \fBint64_t\fP now = \fC-1\fP)\fC [inline]\fP"

.PP
Definition at line 227 of file stormnode\&.h\&.
.SS "bool CStormnode::IsPreEnabled ()\fC [inline]\fP"

.PP
Definition at line 247 of file stormnode\&.h\&.
.SS "\fBCStormnode\fP& CStormnode::operator= (\fBCStormnode\fP from)\fC [inline]\fP"

.PP
Definition at line 169 of file stormnode\&.h\&.
.SS "\fBint64_t\fP CStormnode::SecondsSincePayment ()"

.PP
Definition at line 228 of file stormnode\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CStormnode::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 188 of file stormnode\&.h\&.
.SS "\fBuint64_t\fP CStormnode::SliceHash (\fBuint256\fP & hash, int slice)\fC [inline]\fP"

.PP
Definition at line 213 of file stormnode\&.h\&.
.SS "std::string CStormnode::Status ()\fC [inline]\fP"

.PP
Definition at line 264 of file stormnode\&.h\&.
.SS "void CStormnode::swap (\fBCStormnode\fP & first, \fBCStormnode\fP & second)\fC [inline]\fP"

.PP
Definition at line 144 of file stormnode\&.h\&.
.SS "bool CStormnode::UpdateFromNewBroadcast (\fBCStormnodeBroadcast\fP & snb)"

.PP
Definition at line 128 of file stormnode\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "bool operator!= (const \fBCStormnode\fP & a, const \fBCStormnode\fP & b)\fC [friend]\fP"

.PP
Definition at line 178 of file stormnode\&.h\&.
.SS "bool operator== (const \fBCStormnode\fP & a, const \fBCStormnode\fP & b)\fC [friend]\fP"

.PP
Definition at line 174 of file stormnode\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int CStormnode::activeState"

.PP
Definition at line 127 of file stormnode\&.h\&.
.SS "CStormnode::ADD_SERIALIZE_METHODS"

.PP
Definition at line 185 of file stormnode\&.h\&.
.SS "\fBCService\fP CStormnode::addr"

.PP
Definition at line 123 of file stormnode\&.h\&.
.SS "bool CStormnode::allowFreeTx"

.PP
Definition at line 132 of file stormnode\&.h\&.
.SS "int CStormnode::cacheInputAge"

.PP
Definition at line 129 of file stormnode\&.h\&.
.SS "int CStormnode::cacheInputAgeBlock"

.PP
Definition at line 130 of file stormnode\&.h\&.
.SS "\fBCStormnodePing\fP CStormnode::lastPing"

.PP
Definition at line 137 of file stormnode\&.h\&.
.SS "int CStormnode::nLastScanningErrorBlockHeight"

.PP
Definition at line 136 of file stormnode\&.h\&.
.SS "\fBint64_t\fP CStormnode::nLastSsq"

.PP
Definition at line 134 of file stormnode\&.h\&.
.SS "int CStormnode::nScanningErrorCount"

.PP
Definition at line 135 of file stormnode\&.h\&.
.SS "int CStormnode::protocolVersion"

.PP
Definition at line 133 of file stormnode\&.h\&.
.SS "\fBCPubKey\fP CStormnode::pubkey"

.PP
Definition at line 124 of file stormnode\&.h\&.
.SS "\fBCPubKey\fP CStormnode::pubkey2"

.PP
Definition at line 125 of file stormnode\&.h\&.
.SS "std::vector<unsigned char> CStormnode::sig"

.PP
Definition at line 126 of file stormnode\&.h\&.
.SS "\fBint64_t\fP CStormnode::sigTime"

.PP
Definition at line 128 of file stormnode\&.h\&.
.SS "bool CStormnode::unitTest"

.PP
Definition at line 131 of file stormnode\&.h\&.
.SS "\fBCTxIn\fP CStormnode::vin"

.PP
Definition at line 122 of file stormnode\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
