.TH "CStormnodePayee" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CStormnodePayee \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stormnode-payments\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCStormnodePayee\fP ()"
.br
.ti -1c
.RI "\fBCStormnodePayee\fP (\fBCScript\fP payee, int nVotesIn)"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCScript\fP \fBscriptPubKey\fP"
.br
.ti -1c
.RI "int \fBnVotes\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file stormnode-payments\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CStormnodePayee::CStormnodePayee ()\fC [inline]\fP"

.PP
Definition at line 66 of file stormnode-payments\&.h\&.
.SS "CStormnodePayee::CStormnodePayee (\fBCScript\fP payee, int nVotesIn)\fC [inline]\fP"

.PP
Definition at line 71 of file stormnode-payments\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream , typename Operation > void CStormnodePayee::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 79 of file stormnode-payments\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CStormnodePayee::ADD_SERIALIZE_METHODS"

.PP
Definition at line 76 of file stormnode-payments\&.h\&.
.SS "int CStormnodePayee::nVotes"

.PP
Definition at line 64 of file stormnode-payments\&.h\&.
.SS "\fBCScript\fP CStormnodePayee::scriptPubKey"

.PP
Definition at line 63 of file stormnode-payments\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
