.TH "CTestNetParams" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CTestNetParams \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCMainParams\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCTestNetParams\fP ()"
.br
.ti -1c
.RI "virtual \fBNetwork\fP \fBNetworkID\fP () const "
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 136 of file chainparams\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CTestNetParams::CTestNetParams ()\fC [inline]\fP"

.PP
Definition at line 138 of file chainparams\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBNetwork\fP CTestNetParams::NetworkID () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBCMainParams\fP\&.
.PP
Definition at line 180 of file chainparams\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
