.TH "CTransactionLock" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CTransactionLock \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <instantx\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBSignaturesValid\fP ()"
.br
.ti -1c
.RI "int \fBCountSignatures\fP ()"
.br
.ti -1c
.RI "void \fBAddSignature\fP (\fBCConsensusVote\fP &\fBcv\fP)"
.br
.ti -1c
.RI "\fBuint256\fP \fBGetHash\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnBlockHeight\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBtxHash\fP"
.br
.ti -1c
.RI "std::vector< \fBCConsensusVote\fP > \fBvecConsensusVotes\fP"
.br
.ti -1c
.RI "int \fBnExpiration\fP"
.br
.ti -1c
.RI "int \fBnTimeout\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 81 of file instantx\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void CTransactionLock::AddSignature (\fBCConsensusVote\fP & cv)"

.PP
Definition at line 551 of file instantx\&.cpp\&.
.SS "int CTransactionLock::CountSignatures ()"

.PP
Definition at line 556 of file instantx\&.cpp\&.
.SS "\fBuint256\fP CTransactionLock::GetHash ()\fC [inline]\fP"

.PP
Definition at line 94 of file instantx\&.h\&.
.SS "bool CTransactionLock::SignaturesValid ()"

.PP
Definition at line 523 of file instantx\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int CTransactionLock::nBlockHeight"

.PP
Definition at line 84 of file instantx\&.h\&.
.SS "int CTransactionLock::nExpiration"

.PP
Definition at line 87 of file instantx\&.h\&.
.SS "int CTransactionLock::nTimeout"

.PP
Definition at line 88 of file instantx\&.h\&.
.SS "\fBuint256\fP CTransactionLock::txHash"

.PP
Definition at line 85 of file instantx\&.h\&.
.SS "std::vector<\fBCConsensusVote\fP> CTransactionLock::vecConsensusVotes"

.PP
Definition at line 86 of file instantx\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
