.TH "CTxDB" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CTxDB \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <txdb-leveldb\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCTxDB\fP (const char *pszMode='r+')"
.br
.ti -1c
.RI "\fB~CTxDB\fP ()"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.ti -1c
.RI "bool \fBTxnBegin\fP ()"
.br
.ti -1c
.RI "bool \fBTxnCommit\fP ()"
.br
.ti -1c
.RI "bool \fBTxnAbort\fP ()"
.br
.ti -1c
.RI "bool \fBReadVersion\fP (int &nVersion)"
.br
.ti -1c
.RI "bool \fBWriteVersion\fP (int nVersion)"
.br
.ti -1c
.RI "bool \fBReadAddrIndex\fP (\fBuint160\fP addrHash, std::vector< \fBuint256\fP > &txHashes)"
.br
.ti -1c
.RI "bool \fBWriteAddrIndex\fP (\fBuint160\fP addrHash, \fBuint256\fP txHash)"
.br
.ti -1c
.RI "bool \fBReadTxIndex\fP (\fBuint256\fP \fBhash\fP, \fBCTxIndex\fP &txindex)"
.br
.ti -1c
.RI "bool \fBUpdateTxIndex\fP (\fBuint256\fP \fBhash\fP, const \fBCTxIndex\fP &txindex)"
.br
.ti -1c
.RI "bool \fBAddTxIndex\fP (const \fBCTransaction\fP &tx, const \fBCDiskTxPos\fP &pos, int nHeight)"
.br
.ti -1c
.RI "bool \fBEraseTxIndex\fP (const \fBCTransaction\fP &tx)"
.br
.ti -1c
.RI "bool \fBContainsTx\fP (\fBuint256\fP \fBhash\fP)"
.br
.ti -1c
.RI "bool \fBReadDiskTx\fP (\fBuint256\fP \fBhash\fP, \fBCTransaction\fP &tx, \fBCTxIndex\fP &txindex)"
.br
.ti -1c
.RI "bool \fBReadDiskTx\fP (\fBuint256\fP \fBhash\fP, \fBCTransaction\fP &tx)"
.br
.ti -1c
.RI "bool \fBReadDiskTx\fP (\fBCOutPoint\fP outpoint, \fBCTransaction\fP &tx, \fBCTxIndex\fP &txindex)"
.br
.ti -1c
.RI "bool \fBReadDiskTx\fP (\fBCOutPoint\fP outpoint, \fBCTransaction\fP &tx)"
.br
.ti -1c
.RI "bool \fBWriteBlockIndex\fP (const \fBCDiskBlockIndex\fP &blockindex)"
.br
.ti -1c
.RI "bool \fBReadHashBestChain\fP (\fBuint256\fP &\fBhashBestChain\fP)"
.br
.ti -1c
.RI "bool \fBWriteHashBestChain\fP (\fBuint256\fP \fBhashBestChain\fP)"
.br
.ti -1c
.RI "bool \fBReadBestInvalidTrust\fP (\fBCBigNum\fP &bnBestInvalidTrust)"
.br
.ti -1c
.RI "bool \fBWriteBestInvalidTrust\fP (\fBCBigNum\fP bnBestInvalidTrust)"
.br
.ti -1c
.RI "bool \fBLoadBlockIndex\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBScanBatch\fP (const \fBCDataStream\fP &key, std::string *\fBvalue\fP, bool *deleted) const "
.br
.ti -1c
.RI "template<typename K , typename T > bool \fBRead\fP (const K &key, T &\fBvalue\fP)"
.br
.ti -1c
.RI "template<typename K , typename T > bool \fBWrite\fP (const K &key, const T &\fBvalue\fP)"
.br
.ti -1c
.RI "template<typename K > bool \fBErase\fP (const K &key)"
.br
.ti -1c
.RI "template<typename K > bool \fBExists\fP (const K &key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 37 of file txdb-leveldb\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CTxDB::CTxDB (const char * pszMode = \fC'r+'\fP)"

.PP
Definition at line 77 of file txdb-leveldb\&.cpp\&.
.SS "CTxDB::~CTxDB ()\fC [inline]\fP"

.PP
Definition at line 41 of file txdb-leveldb\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CTxDB::AddTxIndex (const \fBCTransaction\fP & tx, const \fBCDiskTxPos\fP & pos, int nHeight)"

.PP
Definition at line 246 of file txdb-leveldb\&.cpp\&.
.SS "void CTxDB::Close ()"

.PP
Definition at line 132 of file txdb-leveldb\&.cpp\&.
.SS "bool CTxDB::ContainsTx (\fBuint256\fP hash)"

.PP
Definition at line 261 of file txdb-leveldb\&.cpp\&.
.SS "template<typename K > bool CTxDB::Erase (const K & key)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 133 of file txdb-leveldb\&.h\&.
.SS "bool CTxDB::EraseTxIndex (const \fBCTransaction\fP & tx)"

.PP
Definition at line 254 of file txdb-leveldb\&.cpp\&.
.SS "template<typename K > bool CTxDB::Exists (const K & key)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 152 of file txdb-leveldb\&.h\&.
.SS "bool CTxDB::LoadBlockIndex ()"

.PP
Definition at line 337 of file txdb-leveldb\&.cpp\&.
.SS "template<typename K , typename T > bool CTxDB::Read (const K & key, T & value)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 67 of file txdb-leveldb\&.h\&.
.SS "bool CTxDB::ReadAddrIndex (\fBuint160\fP addrHash, std::vector< \fBuint256\fP > & txHashes)"

.PP
Definition at line 230 of file txdb-leveldb\&.cpp\&.
.SS "bool CTxDB::ReadBestInvalidTrust (\fBCBigNum\fP & bnBestInvalidTrust)"

.PP
Definition at line 307 of file txdb-leveldb\&.cpp\&.
.SS "bool CTxDB::ReadDiskTx (\fBuint256\fP hash, \fBCTransaction\fP & tx, \fBCTxIndex\fP & txindex)"

.PP
Definition at line 266 of file txdb-leveldb\&.cpp\&.
.SS "bool CTxDB::ReadDiskTx (\fBuint256\fP hash, \fBCTransaction\fP & tx)"

.PP
Definition at line 275 of file txdb-leveldb\&.cpp\&.
.SS "bool CTxDB::ReadDiskTx (\fBCOutPoint\fP outpoint, \fBCTransaction\fP & tx, \fBCTxIndex\fP & txindex)"

.PP
Definition at line 281 of file txdb-leveldb\&.cpp\&.
.SS "bool CTxDB::ReadDiskTx (\fBCOutPoint\fP outpoint, \fBCTransaction\fP & tx)"

.PP
Definition at line 286 of file txdb-leveldb\&.cpp\&.
.SS "bool CTxDB::ReadHashBestChain (\fBuint256\fP & hashBestChain)"

.PP
Definition at line 297 of file txdb-leveldb\&.cpp\&.
.SS "bool CTxDB::ReadTxIndex (\fBuint256\fP hash, \fBCTxIndex\fP & txindex)"

.PP
Definition at line 235 of file txdb-leveldb\&.cpp\&.
.SS "bool CTxDB::ReadVersion (int & nVersion)\fC [inline]\fP"

.PP
Definition at line 182 of file txdb-leveldb\&.h\&.
.SS "bool CTxDB::ScanBatch (const \fBCDataStream\fP & key, std::string * value, bool * deleted) const\fC [protected]\fP"

.PP
Definition at line 194 of file txdb-leveldb\&.cpp\&.
.SS "bool CTxDB::TxnAbort ()\fC [inline]\fP"

.PP
Definition at line 175 of file txdb-leveldb\&.h\&.
.SS "bool CTxDB::TxnBegin ()"

.PP
Definition at line 144 of file txdb-leveldb\&.cpp\&.
.SS "bool CTxDB::TxnCommit ()"

.PP
Definition at line 151 of file txdb-leveldb\&.cpp\&.
.SS "bool CTxDB::UpdateTxIndex (\fBuint256\fP hash, const \fBCTxIndex\fP & txindex)"

.PP
Definition at line 241 of file txdb-leveldb\&.cpp\&.
.SS "template<typename K , typename T > bool CTxDB::Write (const K & key, const T & value)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 108 of file txdb-leveldb\&.h\&.
.SS "bool CTxDB::WriteAddrIndex (\fBuint160\fP addrHash, \fBuint256\fP txHash)"

.PP
Definition at line 208 of file txdb-leveldb\&.cpp\&.
.SS "bool CTxDB::WriteBestInvalidTrust (\fBCBigNum\fP bnBestInvalidTrust)"

.PP
Definition at line 312 of file txdb-leveldb\&.cpp\&.
.SS "bool CTxDB::WriteBlockIndex (const \fBCDiskBlockIndex\fP & blockindex)"

.PP
Definition at line 292 of file txdb-leveldb\&.cpp\&.
.SS "bool CTxDB::WriteHashBestChain (\fBuint256\fP hashBestChain)"

.PP
Definition at line 302 of file txdb-leveldb\&.cpp\&.
.SS "bool CTxDB::WriteVersion (int nVersion)\fC [inline]\fP"

.PP
Definition at line 188 of file txdb-leveldb\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
