.TH "CTxIn" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CTxIn \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transaction\&.h>\fP
.PP
Inherited by \fBCTxSSIn\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCTxIn\fP ()"
.br
.ti -1c
.RI "\fBCTxIn\fP (\fBCOutPoint\fP prevoutIn, \fBCScript\fP scriptSigIn=\fBCScript\fP(), unsigned int nSequenceIn=std::numeric_limits< unsigned int >::max())"
.br
.ti -1c
.RI "\fBCTxIn\fP (\fBuint256\fP hashPrevTx, unsigned int nOut, \fBCScript\fP scriptSigIn=\fBCScript\fP(), unsigned int nSequenceIn=std::numeric_limits< unsigned int >::max())"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.ti -1c
.RI "bool \fBIsFinal\fP () const "
.br
.ti -1c
.RI "std::string \fBToString\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCOutPoint\fP \fBprevout\fP"
.br
.ti -1c
.RI "\fBCScript\fP \fBscriptSig\fP"
.br
.ti -1c
.RI "\fBCScript\fP \fBprevPubKey\fP"
.br
.ti -1c
.RI "unsigned int \fBnSequence\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBCTxIn\fP &a, const \fBCTxIn\fP &b)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBCTxIn\fP &a, const \fBCTxIn\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
An input of a transaction\&. It contains the location of the previous transaction's output that it claims and a signature that matches the output's public key\&. 
.PP
Definition at line 94 of file transaction\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CTxIn::CTxIn ()\fC [inline]\fP"

.PP
Definition at line 102 of file transaction\&.h\&.
.SS "CTxIn::CTxIn (\fBCOutPoint\fP prevoutIn, \fBCScript\fP scriptSigIn = \fC\fBCScript\fP()\fP, unsigned int nSequenceIn = \fCstd::numeric_limits<unsigned int>::max()\fP)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 107 of file transaction\&.h\&.
.SS "CTxIn::CTxIn (\fBuint256\fP hashPrevTx, unsigned int nOut, \fBCScript\fP scriptSigIn = \fC\fBCScript\fP()\fP, unsigned int nSequenceIn = \fCstd::numeric_limits<unsigned int>::max()\fP)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 114 of file transaction\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CTxIn::IsFinal () const\fC [inline]\fP"

.PP
Definition at line 130 of file transaction\&.h\&.
.SS "template<typename Stream , typename Operation > void CTxIn::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 124 of file transaction\&.h\&.
.SS "std::string CTxIn::ToString () const\fC [inline]\fP"

.PP
Definition at line 147 of file transaction\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "bool operator!= (const \fBCTxIn\fP & a, const \fBCTxIn\fP & b)\fC [friend]\fP"

.PP
Definition at line 142 of file transaction\&.h\&.
.SS "bool operator== (const \fBCTxIn\fP & a, const \fBCTxIn\fP & b)\fC [friend]\fP"

.PP
Definition at line 135 of file transaction\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CTxIn::ADD_SERIALIZE_METHODS"

.PP
Definition at line 121 of file transaction\&.h\&.
.SS "unsigned int CTxIn::nSequence"

.PP
Definition at line 100 of file transaction\&.h\&.
.SS "\fBCOutPoint\fP CTxIn::prevout"

.PP
Definition at line 97 of file transaction\&.h\&.
.SS "\fBCScript\fP CTxIn::prevPubKey"

.PP
Definition at line 99 of file transaction\&.h\&.
.SS "\fBCScript\fP CTxIn::scriptSig"

.PP
Definition at line 98 of file transaction\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
