.TH "CTxInUndo" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CTxInUndo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <undo\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCTxInUndo\fP ()"
.br
.ti -1c
.RI "\fBCTxInUndo\fP (const \fBCTxOut\fP &txoutIn, bool fCoinBaseIn=false, unsigned int nHeightIn=0, int nVersionIn=0)"
.br
.ti -1c
.RI "unsigned int \fBGetSerializeSize\fP (int nType, int \fBnVersion\fP) const "
.br
.ti -1c
.RI "template<typename Stream > void \fBSerialize\fP (Stream &s, int nType, int \fBnVersion\fP) const "
.br
.ti -1c
.RI "template<typename Stream > void \fBUnserialize\fP (Stream &s, int nType, int \fBnVersion\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCTxOut\fP \fBtxout\fP"
.br
.ti -1c
.RI "bool \fBfCoinBase\fP"
.br
.ti -1c
.RI "unsigned int \fBnHeight\fP"
.br
.ti -1c
.RI "int \fBnVersion\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file undo\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CTxInUndo::CTxInUndo ()\fC [inline]\fP"

.PP
Definition at line 54 of file undo\&.h\&.
.SS "CTxInUndo::CTxInUndo (const \fBCTxOut\fP & txoutIn, bool fCoinBaseIn = \fCfalse\fP, unsigned int nHeightIn = \fC0\fP, int nVersionIn = \fC0\fP)\fC [inline]\fP"

.PP
Definition at line 55 of file undo\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned int CTxInUndo::GetSerializeSize (int nType, int nVersion) const\fC [inline]\fP"

.PP
Definition at line 57 of file undo\&.h\&.
.SS "template<typename Stream > void CTxInUndo::Serialize (Stream & s, int nType, int nVersion) const\fC [inline]\fP"

.PP
Definition at line 64 of file undo\&.h\&.
.SS "template<typename Stream > void CTxInUndo::Unserialize (Stream & s, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 72 of file undo\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool CTxInUndo::fCoinBase"

.PP
Definition at line 50 of file undo\&.h\&.
.SS "unsigned int CTxInUndo::nHeight"

.PP
Definition at line 51 of file undo\&.h\&.
.SS "int CTxInUndo::nVersion"

.PP
Definition at line 52 of file undo\&.h\&.
.SS "\fBCTxOut\fP CTxInUndo::txout"

.PP
Definition at line 49 of file undo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
