.TH "CTxOutCompressorUndo" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CTxOutCompressorUndo \- wrapper for \fBCTxOut\fP that provides a more compact serialization  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <undo\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCTxOutCompressorUndo\fP (\fBCTxOut\fP &txoutIn)"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBuint64_t\fP \fBCompressAmount\fP (\fBuint64_t\fP nAmount)"
.br
.ti -1c
.RI "static \fBuint64_t\fP \fBDecompressAmount\fP (\fBuint64_t\fP nAmount)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
wrapper for \fBCTxOut\fP that provides a more compact serialization 
.PP
Definition at line 18 of file undo\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CTxOutCompressorUndo::CTxOutCompressorUndo (\fBCTxOut\fP & txoutIn)\fC [inline]\fP"

.PP
Definition at line 27 of file undo\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBuint64_t\fP CTxOutCompressorUndo::CompressAmount (\fBuint64_t\fP nAmount)\fC [static]\fP"

.PP
Definition at line 17 of file undo\&.cpp\&.
.SS "\fBuint64_t\fP CTxOutCompressorUndo::DecompressAmount (\fBuint64_t\fP nAmount)\fC [static]\fP"

.PP
Definition at line 36 of file undo\&.cpp\&.
.SS "template<typename Stream , typename Operation > void CTxOutCompressorUndo::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 32 of file undo\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CTxOutCompressorUndo::ADD_SERIALIZE_METHODS"

.PP
Definition at line 29 of file undo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
