.TH "CTxSSOut" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CTxSSOut \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sandstorm\&.h>\fP
.PP
Inherits \fBCTxOut\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCTxSSOut\fP (const \fBCTxOut\fP &out)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnSentTimes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds an Sandstorm output 
.PP
Definition at line 72 of file sandstorm\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CTxSSOut::CTxSSOut (const \fBCTxOut\fP & out)\fC [inline]\fP"

.PP
Definition at line 77 of file sandstorm\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int CTxSSOut::nSentTimes"

.PP
Definition at line 75 of file sandstorm\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
