.TH "CTxSSIn" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CTxSSIn \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sandstorm\&.h>\fP
.PP
Inherits \fBCTxIn\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCTxSSIn\fP (const \fBCTxIn\fP &in)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBfHasSig\fP"
.br
.ti -1c
.RI "int \fBnSentTimes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds an Sandstorm input 
.PP
Definition at line 53 of file sandstorm\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CTxSSIn::CTxSSIn (const \fBCTxIn\fP & in)\fC [inline]\fP"

.PP
Definition at line 59 of file sandstorm\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool CTxSSIn::fHasSig"

.PP
Definition at line 56 of file sandstorm\&.h\&.
.SS "int CTxSSIn::nSentTimes"

.PP
Definition at line 57 of file sandstorm\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
