.TH "CTxUndo" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CTxUndo \- Undo information for a \fBCTransaction\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <undo\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBCTxInUndo\fP > \fBvprevout\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Undo information for a \fBCTransaction\fP\&. 
.PP
Definition at line 84 of file undo\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream , typename Operation > void CTxUndo::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 93 of file undo\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CTxUndo::ADD_SERIALIZE_METHODS"

.PP
Definition at line 90 of file undo\&.h\&.
.SS "std::vector<\fBCTxInUndo\fP> CTxUndo::vprevout"

.PP
Definition at line 88 of file undo\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
