.TH "CValidationState" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CValidationState \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <main\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCValidationState\fP ()"
.br
.ti -1c
.RI "bool \fBDoS\fP (int level, bool ret=false, unsigned char chRejectCodeIn=0, std::string strRejectReasonIn='', bool corruptionIn=false)"
.br
.ti -1c
.RI "bool \fBInvalid\fP (bool ret=false, unsigned char _chRejectCode=0, std::string _strRejectReason='')"
.br
.ti -1c
.RI "bool \fBError\fP (std::string strRejectReasonIn='')"
.br
.ti -1c
.RI "bool \fBAbort\fP (const std::string &msg)"
.br
.ti -1c
.RI "bool \fBIsValid\fP () const "
.br
.ti -1c
.RI "bool \fBIsInvalid\fP () const "
.br
.ti -1c
.RI "bool \fBIsError\fP () const "
.br
.ti -1c
.RI "bool \fBIsInvalid\fP (int &nDoSOut) const "
.br
.ti -1c
.RI "bool \fBCorruptionPossible\fP () const "
.br
.ti -1c
.RI "unsigned char \fBGetRejectCode\fP () const "
.br
.ti -1c
.RI "std::string \fBGetRejectReason\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Capture information about block/transaction validation 
.PP
Definition at line 496 of file main\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CValidationState::CValidationState ()\fC [inline]\fP"

.PP
Definition at line 508 of file main\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CValidationState::Abort (const std::string & msg)\fC [inline]\fP"

.PP
Definition at line 531 of file main\&.h\&.
.SS "bool CValidationState::CorruptionPossible () const\fC [inline]\fP"

.PP
Definition at line 551 of file main\&.h\&.
.SS "bool CValidationState::DoS (int level, bool ret = \fCfalse\fP, unsigned char chRejectCodeIn = \fC0\fP, std::string strRejectReasonIn = \fC''\fP, bool corruptionIn = \fCfalse\fP)\fC [inline]\fP"

.PP
Definition at line 509 of file main\&.h\&.
.SS "bool CValidationState::Error (std::string strRejectReasonIn = \fC''\fP)\fC [inline]\fP"

.PP
Definition at line 525 of file main\&.h\&.
.SS "unsigned char CValidationState::GetRejectCode () const\fC [inline]\fP"

.PP
Definition at line 554 of file main\&.h\&.
.SS "std::string CValidationState::GetRejectReason () const\fC [inline]\fP"

.PP
Definition at line 555 of file main\&.h\&.
.SS "bool CValidationState::Invalid (bool ret = \fCfalse\fP, unsigned char _chRejectCode = \fC0\fP, std::string _strRejectReason = \fC''\fP)\fC [inline]\fP"

.PP
Definition at line 521 of file main\&.h\&.
.SS "bool CValidationState::IsError () const\fC [inline]\fP"

.PP
Definition at line 541 of file main\&.h\&.
.SS "bool CValidationState::IsInvalid () const\fC [inline]\fP"

.PP
Definition at line 538 of file main\&.h\&.
.SS "bool CValidationState::IsInvalid (int & nDoSOut) const\fC [inline]\fP"

.PP
Definition at line 544 of file main\&.h\&.
.SS "bool CValidationState::IsValid () const\fC [inline]\fP"

.PP
Definition at line 535 of file main\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
