.TH "CVarInt< I >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CVarInt< I > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <serialize\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCVarInt\fP (I &nIn)"
.br
.ti -1c
.RI "unsigned int \fBGetSerializeSize\fP (int, int) const "
.br
.ti -1c
.RI "template<typename Stream > void \fBSerialize\fP (Stream &s, int, int) const "
.br
.ti -1c
.RI "template<typename Stream > void \fBUnserialize\fP (Stream &s, int, int)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "I & \fBn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename I>class CVarInt< I >"

.PP
Definition at line 371 of file serialize\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename I > \fBCVarInt\fP< I >::\fBCVarInt\fP (I & nIn)\fC [inline]\fP"

.PP
Definition at line 376 of file serialize\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename I > unsigned int \fBCVarInt\fP< I >::GetSerializeSize (int, int) const\fC [inline]\fP"

.PP
Definition at line 378 of file serialize\&.h\&.
.SS "template<typename I > template<typename Stream > void \fBCVarInt\fP< I >::Serialize (Stream & s, int, int) const\fC [inline]\fP"

.PP
Definition at line 383 of file serialize\&.h\&.
.SS "template<typename I > template<typename Stream > void \fBCVarInt\fP< I >::Unserialize (Stream & s, int, int)\fC [inline]\fP"

.PP
Definition at line 388 of file serialize\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename I > I& \fBCVarInt\fP< I >::n\fC [protected]\fP"

.PP
Definition at line 374 of file serialize\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
