.TH "CVerifyDB" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CVerifyDB \- RAII wrapper for VerifyDB: Verify consistency of the block and coin databases\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <main\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCVerifyDB\fP ()"
.br
.ti -1c
.RI "\fB~CVerifyDB\fP ()"
.br
.ti -1c
.RI "bool \fBVerifyDB\fP (\fBCCoinsView\fP *coinsview, int nCheckLevel, int nCheckDepth)"
.br
.in -1c
.SH "Detailed Description"
.PP 
RAII wrapper for VerifyDB: Verify consistency of the block and coin databases\&. 
.PP
Definition at line 636 of file main\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CVerifyDB::CVerifyDB ()"

.PP
Definition at line 4313 of file main\&.cpp\&.
.SS "CVerifyDB::~CVerifyDB ()"

.PP
Definition at line 4319 of file main\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CVerifyDB::VerifyDB (\fBCCoinsView\fP * coinsview, int nCheckLevel, int nCheckDepth)"

.PP
Definition at line 4325 of file main\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
