.TH "CWalletKey" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CWalletKey \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wallet\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCWalletKey\fP (\fBint64_t\fP nExpires=0)"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCPrivKey\fP \fBvchPrivKey\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnTimeCreated\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnTimeExpires\fP"
.br
.ti -1c
.RI "std::string \fBstrComment\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Private key that includes an expiration date in case it never gets used\&. 
.PP
Definition at line 1111 of file wallet\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CWalletKey::CWalletKey (\fBint64_t\fP nExpires = \fC0\fP)\fC [inline]\fP"

.PP
Definition at line 1121 of file wallet\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream , typename Operation > void CWalletKey::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 1130 of file wallet\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "CWalletKey::ADD_SERIALIZE_METHODS"

.PP
Definition at line 1127 of file wallet\&.h\&.
.SS "\fBint64_t\fP CWalletKey::nTimeCreated"

.PP
Definition at line 1115 of file wallet\&.h\&.
.SS "\fBint64_t\fP CWalletKey::nTimeExpires"

.PP
Definition at line 1116 of file wallet\&.h\&.
.SS "std::string CWalletKey::strComment"

.PP
Definition at line 1117 of file wallet\&.h\&.
.SS "\fBCPrivKey\fP CWalletKey::vchPrivKey"

.PP
Definition at line 1114 of file wallet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
