.TH "CWalletScanState" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CWalletScanState \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCWalletScanState\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBnKeys\fP"
.br
.ti -1c
.RI "unsigned int \fBnCKeys\fP"
.br
.ti -1c
.RI "unsigned int \fBnKeyMeta\fP"
.br
.ti -1c
.RI "bool \fBfIsEncrypted\fP"
.br
.ti -1c
.RI "bool \fBfAnyUnordered\fP"
.br
.ti -1c
.RI "int \fBnFileVersion\fP"
.br
.ti -1c
.RI "vector< \fBuint256\fP > \fBvWalletUpgrade\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 339 of file walletdb\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CWalletScanState::CWalletScanState ()\fC [inline]\fP"

.PP
Definition at line 349 of file walletdb\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "bool CWalletScanState::fAnyUnordered"

.PP
Definition at line 345 of file walletdb\&.cpp\&.
.SS "bool CWalletScanState::fIsEncrypted"

.PP
Definition at line 344 of file walletdb\&.cpp\&.
.SS "unsigned int CWalletScanState::nCKeys"

.PP
Definition at line 342 of file walletdb\&.cpp\&.
.SS "int CWalletScanState::nFileVersion"

.PP
Definition at line 346 of file walletdb\&.cpp\&.
.SS "unsigned int CWalletScanState::nKeyMeta"

.PP
Definition at line 343 of file walletdb\&.cpp\&.
.SS "unsigned int CWalletScanState::nKeys"

.PP
Definition at line 341 of file walletdb\&.cpp\&.
.SS "vector<\fBuint256\fP> CWalletScanState::vWalletUpgrade"

.PP
Definition at line 347 of file walletdb\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
