.TH "CWalletDB" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CWalletDB \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <walletdb\&.h>\fP
.PP
Inherits \fBCDB\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCWalletDB\fP (const std::string &strFilename, const char *pszMode='r+')"
.br
.ti -1c
.RI "bool \fBWriteName\fP (const std::string &strAddress, const std::string &strName)"
.br
.ti -1c
.RI "bool \fBEraseName\fP (const std::string &strAddress)"
.br
.ti -1c
.RI "bool \fBWriteTx\fP (\fBuint256\fP \fBhash\fP, const \fBCWalletTx\fP &wtx)"
.br
.ti -1c
.RI "bool \fBEraseTx\fP (\fBuint256\fP \fBhash\fP)"
.br
.ti -1c
.RI "bool \fBWriteStealthKeyMeta\fP (const \fBCKeyID\fP &keyId, const \fBCStealthKeyMetadata\fP &sxKeyMeta)"
.br
.ti -1c
.RI "bool \fBEraseStealthKeyMeta\fP (const \fBCKeyID\fP &keyId)"
.br
.ti -1c
.RI "bool \fBWriteStealthAddress\fP (const \fBCStealthAddress\fP &sxAddr)"
.br
.ti -1c
.RI "bool \fBReadStealthAddress\fP (\fBCStealthAddress\fP &sxAddr)"
.br
.ti -1c
.RI "bool \fBWriteKey\fP (const \fBCPubKey\fP &vchPubKey, const \fBCPrivKey\fP &vchPrivKey, const \fBCKeyMetadata\fP &keyMeta)"
.br
.ti -1c
.RI "bool \fBWriteCryptedKey\fP (const \fBCPubKey\fP &vchPubKey, const std::vector< unsigned char > &vchCryptedSecret, const \fBCKeyMetadata\fP &keyMeta)"
.br
.ti -1c
.RI "bool \fBWriteMasterKey\fP (unsigned int nID, const \fBCMasterKey\fP &kMasterKey)"
.br
.ti -1c
.RI "bool \fBWriteCScript\fP (const \fBuint160\fP &\fBhash\fP, const \fBCScript\fP &redeemScript)"
.br
.ti -1c
.RI "bool \fBWriteWatchOnly\fP (const \fBCScript\fP &script)"
.br
.ti -1c
.RI "bool \fBEraseWatchOnly\fP (const \fBCScript\fP &script)"
.br
.ti -1c
.RI "bool \fBWriteBestBlock\fP (const \fBCBlockLocator\fP &locator)"
.br
.ti -1c
.RI "bool \fBReadBestBlock\fP (\fBCBlockLocator\fP &locator)"
.br
.ti -1c
.RI "bool \fBWriteOrderPosNext\fP (\fBint64_t\fP nOrderPosNext)"
.br
.ti -1c
.RI "bool \fBWriteDefaultKey\fP (const \fBCPubKey\fP &vchPubKey)"
.br
.ti -1c
.RI "bool \fBReadPool\fP (\fBint64_t\fP nPool, \fBCKeyPool\fP &keypool)"
.br
.ti -1c
.RI "bool \fBWritePool\fP (\fBint64_t\fP nPool, const \fBCKeyPool\fP &keypool)"
.br
.ti -1c
.RI "bool \fBErasePool\fP (\fBint64_t\fP nPool)"
.br
.ti -1c
.RI "bool \fBWriteMinVersion\fP (int nVersion)"
.br
.ti -1c
.RI "bool \fBReadAccount\fP (const std::string &strAccount, \fBCAccount\fP &account)"
.br
.ti -1c
.RI "bool \fBWriteAccount\fP (const std::string &strAccount, const \fBCAccount\fP &account)"
.br
.ti -1c
.RI "bool \fBWriteAccountingEntry\fP (const \fBCAccountingEntry\fP &acentry)"
.br
.ti -1c
.RI "\fBCAmount\fP \fBGetAccountCreditDebit\fP (const std::string &strAccount)"
.br
.ti -1c
.RI "void \fBListAccountCreditDebit\fP (const std::string &strAccount, std::list< \fBCAccountingEntry\fP > &acentries)"
.br
.ti -1c
.RI "\fBDBErrors\fP \fBReorderTransactions\fP (\fBCWallet\fP *)"
.br
.ti -1c
.RI "\fBDBErrors\fP \fBLoadWallet\fP (\fBCWallet\fP *pwallet)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBRecover\fP (\fBCDBEnv\fP &dbenv, std::string filename, bool fOnlyKeys)"
.br
.ti -1c
.RI "static bool \fBRecover\fP (\fBCDBEnv\fP &dbenv, std::string filename)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Access to the wallet database (wallet\&.dat) 
.PP
Definition at line 99 of file walletdb\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CWalletDB::CWalletDB (const std::string & strFilename, const char * pszMode = \fC'r+'\fP)\fC [inline]\fP"

.PP
Definition at line 102 of file walletdb\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CWalletDB::EraseName (const std::string & strAddress)"

.PP
Definition at line 35 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::ErasePool (\fBint64_t\fP nPool)"

.PP
Definition at line 176 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::EraseStealthKeyMeta (const \fBCKeyID\fP & keyId)"

.PP
Definition at line 61 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::EraseTx (\fBuint256\fP hash)"

.PP
Definition at line 49 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::EraseWatchOnly (const \fBCScript\fP & script)"

.PP
Definition at line 136 of file walletdb\&.cpp\&.
.SS "\fBCAmount\fP CWalletDB::GetAccountCreditDebit (const std::string & strAccount)"

.PP
Definition at line 208 of file walletdb\&.cpp\&.
.SS "void CWalletDB::ListAccountCreditDebit (const std::string & strAccount, std::list< \fBCAccountingEntry\fP > & acentries)"

.PP
Definition at line 220 of file walletdb\&.cpp\&.
.SS "\fBDBErrors\fP CWalletDB::LoadWallet (\fBCWallet\fP * pwallet)"

.PP
Definition at line 630 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::ReadAccount (const std::string & strAccount, \fBCAccount\fP & account)"

.PP
Definition at line 187 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::ReadBestBlock (\fBCBlockLocator\fP & locator)"

.PP
Definition at line 148 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::ReadPool (\fBint64_t\fP nPool, \fBCKeyPool\fP & keypool)"

.PP
Definition at line 165 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::ReadStealthAddress (\fBCStealthAddress\fP & sxAddr)"

.PP
Definition at line 74 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::Recover (\fBCDBEnv\fP & dbenv, std::string filename, bool fOnlyKeys)\fC [static]\fP"

.PP
Definition at line 837 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::Recover (\fBCDBEnv\fP & dbenv, std::string filename)\fC [static]\fP"

.PP
Definition at line 915 of file walletdb\&.cpp\&.
.SS "\fBDBErrors\fP CWalletDB::ReorderTransactions (\fBCWallet\fP * pwallet)"

.PP
Definition at line 263 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::WriteAccount (const std::string & strAccount, const \fBCAccount\fP & account)"

.PP
Definition at line 193 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::WriteAccountingEntry (const \fBCAccountingEntry\fP & acentry)"

.PP
Definition at line 203 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::WriteBestBlock (const \fBCBlockLocator\fP & locator)"

.PP
Definition at line 142 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::WriteCryptedKey (const \fBCPubKey\fP & vchPubKey, const std::vector< unsigned char > & vchCryptedSecret, const \fBCKeyMetadata\fP & keyMeta)"

.PP
Definition at line 97 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::WriteCScript (const \fBuint160\fP & hash, const \fBCScript\fP & redeemScript)"

.PP
Definition at line 124 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::WriteDefaultKey (const \fBCPubKey\fP & vchPubKey)"

.PP
Definition at line 159 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::WriteKey (const \fBCPubKey\fP & vchPubKey, const \fBCPrivKey\fP & vchPrivKey, const \fBCKeyMetadata\fP & keyMeta)"

.PP
Definition at line 80 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::WriteMasterKey (unsigned int nID, const \fBCMasterKey\fP & kMasterKey)"

.PP
Definition at line 118 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::WriteMinVersion (int nVersion)"

.PP
Definition at line 182 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::WriteName (const std::string & strAddress, const std::string & strName)"

.PP
Definition at line 29 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::WriteOrderPosNext (\fBint64_t\fP nOrderPosNext)"

.PP
Definition at line 153 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::WritePool (\fBint64_t\fP nPool, const \fBCKeyPool\fP & keypool)"

.PP
Definition at line 170 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::WriteStealthAddress (const \fBCStealthAddress\fP & sxAddr)"

.PP
Definition at line 67 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::WriteStealthKeyMeta (const \fBCKeyID\fP & keyId, const \fBCStealthKeyMetadata\fP & sxKeyMeta)"

.PP
Definition at line 55 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::WriteTx (\fBuint256\fP hash, const \fBCWalletTx\fP & wtx)"

.PP
Definition at line 43 of file walletdb\&.cpp\&.
.SS "bool CWalletDB::WriteWatchOnly (const \fBCScript\fP & script)"

.PP
Definition at line 130 of file walletdb\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
