.TH "CWalletInterface" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CWalletInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <main\&.h>\fP
.PP
Inherited by \fBCWallet\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBSyncTransaction\fP (const \fBCTransaction\fP &tx, const \fBCBlock\fP *pblock, bool fConnect)=0"
.br
.ti -1c
.RI "virtual void \fBEraseFromWallet\fP (const \fBuint256\fP &\fBhash\fP)=0"
.br
.ti -1c
.RI "virtual void \fBSetBestChain\fP (const \fBCBlockLocator\fP &locator)=0"
.br
.ti -1c
.RI "virtual bool \fBUpdatedTransaction\fP (const \fBuint256\fP &\fBhash\fP)=0"
.br
.ti -1c
.RI "virtual void \fBInventory\fP (const \fBuint256\fP &\fBhash\fP)=0"
.br
.ti -1c
.RI "virtual void \fBResendWalletTransactions\fP (bool fForce)=0"
.br
.ti -1c
.RI "friend \fBvoid::RegisterWallet\fP (\fBCWalletInterface\fP *)"
.br
.ti -1c
.RI "friend \fBvoid::UnregisterWallet\fP (\fBCWalletInterface\fP *)"
.br
.ti -1c
.RI "friend \fBvoid::UnregisterAllWallets\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 558 of file main\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void CWalletInterface::EraseFromWallet (const \fBuint256\fP & hash)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBCWallet\fP\&.
.SS "virtual void CWalletInterface::Inventory (const \fBuint256\fP & hash)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBCWallet\fP\&.
.SS "virtual void CWalletInterface::ResendWalletTransactions (bool fForce)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBCWallet\fP\&.
.SS "virtual void CWalletInterface::SetBestChain (const \fBCBlockLocator\fP & locator)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBCWallet\fP\&.
.SS "virtual void CWalletInterface::SyncTransaction (const \fBCTransaction\fP & tx, const \fBCBlock\fP * pblock, bool fConnect)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBCWallet\fP\&.
.SS "virtual bool CWalletInterface::UpdatedTransaction (const \fBuint256\fP & hash)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBCWallet\fP\&.
.SS "\fBCWalletInterface::void::RegisterWallet\fP (\fBCWalletInterface\fP *)\fC [protected]\fP"

.SS "\fBCWalletInterface::void::UnregisterAllWallets\fP ()\fC [protected]\fP"

.SS "\fBCWalletInterface::void::UnregisterWallet\fP (\fBCWalletInterface\fP *)\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
