.TH "/home/dev/ds-160209/src/darksilkd.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/darksilkd.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'rpcserver\&.h'\fP
.br
\fC#include 'rpcclient\&.h'\fP
.br
\fC#include 'init\&.h'\fP
.br
\fC#include <boost/algorithm/string/predicate\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBDetectShutdownThread\fP (boost::thread_group *threadGroup)"
.br
.ti -1c
.RI "bool \fBAppInit\fP (int argc, char *argv[])"
.br
.ti -1c
.RI "void \fBnoui_connect\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool AppInit (int argc, char * argv[])"

.PP
Definition at line 34 of file darksilkd\&.cpp\&.
.SS "void DetectShutdownThread (boost::thread_group * threadGroup)"

.PP
Definition at line 14 of file darksilkd\&.cpp\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 143 of file darksilkd\&.cpp\&.
.SS "void noui_connect ()"

.PP
Definition at line 45 of file noui\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
