.TH "/home/dev/ds-160209/src/qt/darksilkgui.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/darksilkgui.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QApplication>\fP
.br
\fC#include 'darksilkgui\&.h'\fP
.br
\fC#include 'transactiontablemodel\&.h'\fP
.br
\fC#include 'addressbookpage\&.h'\fP
.br
\fC#include 'sendcoinsdialog\&.h'\fP
.br
\fC#include 'signverifymessagedialog\&.h'\fP
.br
\fC#include 'optionsdialog\&.h'\fP
.br
\fC#include 'aboutdialog\&.h'\fP
.br
\fC#include 'clientmodel\&.h'\fP
.br
\fC#include 'walletmodel\&.h'\fP
.br
\fC#include 'messagemodel\&.h'\fP
.br
\fC#include 'editaddressdialog\&.h'\fP
.br
\fC#include 'optionsmodel\&.h'\fP
.br
\fC#include 'transactiondescdialog\&.h'\fP
.br
\fC#include 'addresstablemodel\&.h'\fP
.br
\fC#include 'transactionview\&.h'\fP
.br
\fC#include 'overviewpage\&.h'\fP
.br
\fC#include 'darksilkunits\&.h'\fP
.br
\fC#include 'guiconstants\&.h'\fP
.br
\fC#include 'askpassphrasedialog\&.h'\fP
.br
\fC#include 'notificator\&.h'\fP
.br
\fC#include 'guiutil\&.h'\fP
.br
\fC#include 'debugconsole\&.h'\fP
.br
\fC#include 'wallet\&.h'\fP
.br
\fC#include 'init\&.h'\fP
.br
\fC#include 'stormnode-sync\&.h'\fP
.br
\fC#include 'stormnodemanager\&.h'\fP
.br
\fC#include 'blockbrowser\&.h'\fP
.br
\fC#include 'statisticspage\&.h'\fP
.br
\fC#include 'messagepage\&.h'\fP
.br
\fC#include <QMenuBar>\fP
.br
\fC#include <QMenu>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QIcon>\fP
.br
\fC#include <QVBoxLayout>\fP
.br
\fC#include <QToolBar>\fP
.br
\fC#include <QStatusBar>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QMimeData>\fP
.br
\fC#include <QProgressBar>\fP
.br
\fC#include <QProgressDialog>\fP
.br
\fC#include <QStackedWidget>\fP
.br
\fC#include <QDateTime>\fP
.br
\fC#include <QMovie>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QDesktopServices>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <QDragEnterEvent>\fP
.br
\fC#include <QUrl>\fP
.br
\fC#include <QStyle>\fP
.br
\fC#include <QToolButton>\fP
.br
\fC#include <QScrollArea>\fP
.br
\fC#include <QScroller>\fP
.br
\fC#include <QTextDocument>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBGetPoSKernelPS\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBfOnlyTor\fP"
.br
.ti -1c
.RI "\fBCWallet\fP * \fBpwalletMain\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnLastCoinStakeSearchInterval\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double GetPoSKernelPS ()"

.PP
Definition at line 73 of file rpcblockchain\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "bool fOnlyTor"

.PP
Definition at line 58 of file init\&.cpp\&.
.SS "\fBint64_t\fP nLastCoinStakeSearchInterval"

.PP
Definition at line 80 of file miner\&.cpp\&.
.SS "\fBCWallet\fP* pwalletMain"

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
