.TH "DarkSilkGUI" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DarkSilkGUI \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <darksilkgui\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetNumConnections\fP (int count)"
.br
.ti -1c
.RI "void \fBsetNumBlocks\fP (int count)"
.br
.ti -1c
.RI "void \fBsetEncryptionStatus\fP (int status)"
.br
.ti -1c
.RI "void \fBmessage\fP (const QString &title, const QString &message, bool modal, unsigned int style=\fBCClientUIInterface::MSG_ERROR\fP, bool *ret=NULL)"
.br
.ti -1c
.RI "void \fBaskFee\fP (\fBCAmount\fP nFeeRequired, bool *payFee)"
.br
.ti -1c
.RI "void \fBhandleURI\fP (QString strURI)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDarkSilkGUI\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~DarkSilkGUI\fP ()"
.br
.ti -1c
.RI "void \fBsetClientModel\fP (\fBClientModel\fP *clientModel)"
.br
.ti -1c
.RI "void \fBsetWalletModel\fP (\fBWalletModel\fP *walletModel)"
.br
.ti -1c
.RI "void \fBsetMessageModel\fP (\fBMessageModel\fP *messageModel)"
.br
.ti -1c
.RI "WId \fBgetMainWinId\fP () const "
.br
.RI "\fIGet window identifier of QMainWindow (\fBDarkSilkGUI\fP) \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBchangeEvent\fP (QEvent *e)"
.br
.ti -1c
.RI "void \fBcloseEvent\fP (QCloseEvent *event)"
.br
.ti -1c
.RI "void \fBdragEnterEvent\fP (QDragEnterEvent *event)"
.br
.ti -1c
.RI "void \fBdropEvent\fP (QDropEvent *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
DarkSilk GUI main class\&. This class represents the main window of the DarkSilk UI\&. It communicates with both the client and wallet models to give the user an up-to-date view of the current core state\&. 
.PP
Definition at line 39 of file darksilkgui\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DarkSilkGUI::DarkSilkGUI (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 83 of file darksilkgui\&.cpp\&.
.SS "DarkSilkGUI::~DarkSilkGUI ()"

.PP
Definition at line 279 of file darksilkgui\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void DarkSilkGUI::askFee (\fBCAmount\fP nFeeRequired, bool * payFee)\fC [slot]\fP"
Asks the user whether to pay the transaction fee or to cancel the transaction\&. It is currently not possible to pass a return value to another thread through BlockingQueuedConnection, so an indirected pointer is used\&. https://bugreports.qt-project.org/browse/QTBUG-10440
.PP
\fBParameters:\fP
.RS 4
\fInFeeRequired\fP the required fee 
.br
\fIpayFee\fP true to pay the fee, false to not pay the fee 
.RE
.PP

.PP
Definition at line 1046 of file darksilkgui\&.cpp\&.
.SS "void DarkSilkGUI::changeEvent (QEvent * e)\fC [protected]\fP"

.PP
Definition at line 1008 of file darksilkgui\&.cpp\&.
.SS "void DarkSilkGUI::closeEvent (QCloseEvent * event)\fC [protected]\fP"

.PP
Definition at line 1030 of file darksilkgui\&.cpp\&.
.SS "void DarkSilkGUI::dragEnterEvent (QDragEnterEvent * event)\fC [protected]\fP"

.PP
Definition at line 1247 of file darksilkgui\&.cpp\&.
.SS "void DarkSilkGUI::dropEvent (QDropEvent * event)\fC [protected]\fP"

.PP
Definition at line 1255 of file darksilkgui\&.cpp\&.
.SS "WId DarkSilkGUI::getMainWinId () const"

.PP
Get window identifier of QMainWindow (\fBDarkSilkGUI\fP) 
.PP
Definition at line 1543 of file darksilkgui\&.cpp\&.
.SS "void DarkSilkGUI::handleURI (QString strURI)\fC [slot]\fP"

.PP
Definition at line 1277 of file darksilkgui\&.cpp\&.
.SS "void DarkSilkGUI::message (const QString & title, const QString & message, bool modal, unsigned int style = \fC\fBCClientUIInterface::MSG_ERROR\fP\fP, bool * ret = \fCNULL\fP)\fC [slot]\fP"
Notify the user of an event from the core network or transaction handling code\&. 
.PP
\fBParameters:\fP
.RS 4
\fItitle\fP the message box / notification title 
.br
\fImessage\fP the displayed text 
.br
\fImodal\fP true to use a message box, false to use a notification 
.br
\fIstyle\fP style definitions (icon and used buttons - buttons only for message boxes) 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBCClientUIInterface::MessageBoxFlags\fP 
.RE
.PP

.PP
Definition at line 946 of file darksilkgui\&.cpp\&.
.SS "void DarkSilkGUI::setClientModel (\fBClientModel\fP * clientModel)"
Set the client model\&. The client model represents the part of the core that communicates with the P2P network, and is wallet-agnostic\&. 
.PP
Definition at line 570 of file darksilkgui\&.cpp\&.
.SS "void DarkSilkGUI::setEncryptionStatus (int status)\fC [slot]\fP"
Set the encryption status as shown in the UI\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstatus\fP current encryption status 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBWalletModel::EncryptionStatus\fP 
.RE
.PP

.PP
Definition at line 1288 of file darksilkgui\&.cpp\&.
.SS "void DarkSilkGUI::setMessageModel (\fBMessageModel\fP * messageModel)"
Set the message model\&. The message model represents encryption message database, and offers access to the list of messages, address book and sending functionality\&. 
.PP
Definition at line 677 of file darksilkgui\&.cpp\&.
.SS "void DarkSilkGUI::setNumBlocks (int count)\fC [slot]\fP"
Set number of blocks shown in the UI 
.PP
Definition at line 860 of file darksilkgui\&.cpp\&.
.SS "void DarkSilkGUI::setNumConnections (int count)\fC [slot]\fP"
Set number of connections shown in the UI 
.PP
Definition at line 844 of file darksilkgui\&.cpp\&.
.SS "void DarkSilkGUI::setWalletModel (\fBWalletModel\fP * walletModel)"
Set the wallet model\&. The wallet model represents a darksilk wallet, and offers access to the list of transactions, address book and sending functionality\&. 
.PP
Definition at line 649 of file darksilkgui\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
