.TH "/home/dev/ds-160209/src/qt/darksilk.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/darksilk.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'darksilkgui\&.h'\fP
.br
\fC#include 'clientmodel\&.h'\fP
.br
\fC#include 'walletmodel\&.h'\fP
.br
\fC#include 'messagemodel\&.h'\fP
.br
\fC#include 'optionsmodel\&.h'\fP
.br
\fC#include 'guiutil\&.h'\fP
.br
\fC#include 'guiconstants\&.h'\fP
.br
\fC#include 'init\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'wallet\&.h'\fP
.br
\fC#include 'ui_interface\&.h'\fP
.br
\fC#include 'paymentserver\&.h'\fP
.br
\fC#include 'winshutdownmonitor\&.h'\fP
.br
\fC#include <QApplication>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QTextStream>\fP
.br
\fC#include <QTextCodec>\fP
.br
\fC#include <QLocale>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <QTranslator>\fP
.br
\fC#include <QSplashScreen>\fP
.br
\fC#include <QLibraryInfo>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBDebugMessageHandler\fP (QtMsgType type, const char *msg)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void DebugMessageHandler (QtMsgType type, const char * msg)"

.PP
Definition at line 114 of file darksilk\&.cpp\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 128 of file darksilk\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
