.TH "/home/dev/ds-160209/src/qt/darksilkunits.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/darksilkunits.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'amount\&.h'\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QAbstractListModel>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDarkSilkUnits\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBREAL_THIN_SP_CP\fP   0x2009"
.br
.ti -1c
.RI "#define \fBREAL_THIN_SP_UTF8\fP   '\\xE2\\x80\\x89'"
.br
.ti -1c
.RI "#define \fBREAL_THIN_SP_HTML\fP   '&thinsp;'"
.br
.ti -1c
.RI "#define \fBHTML_HACK_SP\fP   '<span style='white-space: nowrap; font-size: 6pt'> </span>'"
.br
.ti -1c
.RI "#define \fBTHIN_SP_CP\fP   \fBREAL_THIN_SP_CP\fP"
.br
.ti -1c
.RI "#define \fBTHIN_SP_UTF8\fP   \fBREAL_THIN_SP_UTF8\fP"
.br
.ti -1c
.RI "#define \fBTHIN_SP_HTML\fP   \fBHTML_HACK_SP\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBDarkSilkUnits::Unit\fP \fBDarkSilkUnit\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HTML_HACK_SP   '<span style='white-space: nowrap; font-size: 6pt'> </span>'"

.PP
Definition at line 23 of file darksilkunits\&.h\&.
.SS "#define REAL_THIN_SP_CP   0x2009"

.PP
Definition at line 15 of file darksilkunits\&.h\&.
.SS "#define REAL_THIN_SP_HTML   '&thinsp;'"

.PP
Definition at line 17 of file darksilkunits\&.h\&.
.SS "#define REAL_THIN_SP_UTF8   '\\xE2\\x80\\x89'"

.PP
Definition at line 16 of file darksilkunits\&.h\&.
.SS "#define THIN_SP_CP   \fBREAL_THIN_SP_CP\fP"

.PP
Definition at line 26 of file darksilkunits\&.h\&.
.SS "#define THIN_SP_HTML   \fBHTML_HACK_SP\fP"

.PP
Definition at line 28 of file darksilkunits\&.h\&.
.SS "#define THIN_SP_UTF8   \fBREAL_THIN_SP_UTF8\fP"

.PP
Definition at line 27 of file darksilkunits\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBDarkSilkUnits::Unit\fP \fBDarkSilkUnit\fP"

.PP
Definition at line 105 of file darksilkunits\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
