.TH "/home/dev/ds-160209/src/db.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/db.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'db\&.h'\fP
.br
\fC#include 'addrman\&.h'\fP
.br
\fC#include 'hash\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <boost/filesystem\&.hpp>\fP
.br
\fC#include <boost/version\&.hpp>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "unsigned int \fBnWalletDBUpdated\fP"
.br
.ti -1c
.RI "\fBCDBEnv\fP \fBbitdb\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBCDBEnv\fP bitdb"

.PP
Definition at line 32 of file db\&.cpp\&.
.SS "unsigned int nWalletDBUpdated"

.PP
Definition at line 24 of file db\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
