.TH "/home/dev/ds-160209/src/leveldb/include/leveldb/db.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/include/leveldb/db.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'leveldb/iterator\&.h'\fP
.br
\fC#include 'leveldb/options\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBleveldb::Snapshot\fP"
.br
.ti -1c
.RI "struct \fBleveldb::Range\fP"
.br
.ti -1c
.RI "class \fBleveldb::DB\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Status \fBleveldb::DestroyDB\fP (const std::string &dbname, const Options &options)"
.br
.ti -1c
.RI "Status \fBleveldb::RepairDB\fP (const std::string &dbname, const Options &options)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
