.TH "/home/dev/ds-160209/src/leveldb/db/db_bench.cc" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/db/db_bench.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'db/db_impl\&.h'\fP
.br
\fC#include 'db/version_set\&.h'\fP
.br
\fC#include 'leveldb/cache\&.h'\fP
.br
\fC#include 'leveldb/db\&.h'\fP
.br
\fC#include 'leveldb/env\&.h'\fP
.br
\fC#include 'leveldb/write_batch\&.h'\fP
.br
\fC#include 'port/port\&.h'\fP
.br
\fC#include 'util/crc32c\&.h'\fP
.br
\fC#include 'util/histogram\&.h'\fP
.br
\fC#include 'util/mutexlock\&.h'\fP
.br
\fC#include 'util/random\&.h'\fP
.br
\fC#include 'util/testutil\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBleveldb::Benchmark\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 925 of file db_bench\&.cc\&.
.SH "Variable Documentation"
.PP 
.SS "\fBint64_t\fP bytes_"

.PP
Definition at line 168 of file db_bench\&.cc\&.
.SS "port::CondVar cv"

.PP
Definition at line 271 of file db_bench\&.cc\&.
.SS "std::string data_"

.PP
Definition at line 112 of file db_bench\&.cc\&.
.SS "int done_"

.PP
Definition at line 166 of file db_bench\&.cc\&.
.SS "double finish_"

.PP
Definition at line 164 of file db_bench\&.cc\&.
.SS "Histogram hist_"

.PP
Definition at line 170 of file db_bench\&.cc\&.
.SS "double last_op_finish_"

.PP
Definition at line 169 of file db_bench\&.cc\&.
.SS "std::string message_"

.PP
Definition at line 171 of file db_bench\&.cc\&.
.SS "port::Mutex mu"

.PP
Definition at line 270 of file db_bench\&.cc\&.
.SS "int next_report_"

.PP
Definition at line 167 of file db_bench\&.cc\&.
.SS "int num_done"

.PP
Definition at line 281 of file db_bench\&.cc\&.
.SS "int num_initialized"

.PP
Definition at line 280 of file db_bench\&.cc\&.
.SS "int pos_"

.PP
Definition at line 113 of file db_bench\&.cc\&.
.SS "Random rand"

.PP
Definition at line 290 of file db_bench\&.cc\&.
.SS "double seconds_"

.PP
Definition at line 165 of file db_bench\&.cc\&.
.SS "SharedState* shared"

.PP
Definition at line 292 of file db_bench\&.cc\&.
.SS "bool start"

.PP
Definition at line 282 of file db_bench\&.cc\&.
.SS "double start_"

.PP
Definition at line 163 of file db_bench\&.cc\&.
.SS "Stats stats"

.PP
Definition at line 291 of file db_bench\&.cc\&.
.SS "int tid"

.PP
Definition at line 289 of file db_bench\&.cc\&.
.SS "int total"

.PP
Definition at line 272 of file db_bench\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
