.TH "/home/dev/ds-160209/src/leveldb/db/db_iter.cc" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/db/db_iter.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'db/db_iter\&.h'\fP
.br
\fC#include 'db/filename\&.h'\fP
.br
\fC#include 'db/db_impl\&.h'\fP
.br
\fC#include 'db/dbformat\&.h'\fP
.br
\fC#include 'leveldb/env\&.h'\fP
.br
\fC#include 'leveldb/iterator\&.h'\fP
.br
\fC#include 'port/port\&.h'\fP
.br
\fC#include 'util/logging\&.h'\fP
.br
\fC#include 'util/mutexlock\&.h'\fP
.br
\fC#include 'util/random\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Iterator * \fBleveldb::NewDBIterator\fP (DBImpl *db, const Comparator *user_key_comparator, Iterator *internal_iter, SequenceNumber sequence, \fBuint32_t\fP seed)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "ssize_t bytes_counter_"

.PP
Definition at line 123 of file db_iter\&.cc\&.
.SS "DBImpl* db_"

.PP
Definition at line 111 of file db_iter\&.cc\&.
.SS "Direction direction_"

.PP
Definition at line 119 of file db_iter\&.cc\&.
.SS "Iterator* const iter_"

.PP
Definition at line 113 of file db_iter\&.cc\&.
.SS "Random rnd_"

.PP
Definition at line 122 of file db_iter\&.cc\&.
.SS "std::string saved_key_"

.PP
Definition at line 117 of file db_iter\&.cc\&.
.SS "std::string saved_value_"

.PP
Definition at line 118 of file db_iter\&.cc\&.
.SS "SequenceNumber const sequence_"

.PP
Definition at line 114 of file db_iter\&.cc\&.
.SS "Status status_"

.PP
Definition at line 116 of file db_iter\&.cc\&.
.SS "const Comparator* const user_comparator_"

.PP
Definition at line 112 of file db_iter\&.cc\&.
.SS "bool valid_"

.PP
Definition at line 120 of file db_iter\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
