.TH "/home/dev/ds-160209/src/leveldb/db/db_test.cc" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/db/db_test.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'leveldb/db\&.h'\fP
.br
\fC#include 'leveldb/filter_policy\&.h'\fP
.br
\fC#include 'db/db_impl\&.h'\fP
.br
\fC#include 'db/filename\&.h'\fP
.br
\fC#include 'db/version_set\&.h'\fP
.br
\fC#include 'db/write_batch_internal\&.h'\fP
.br
\fC#include 'leveldb/cache\&.h'\fP
.br
\fC#include 'leveldb/env\&.h'\fP
.br
\fC#include 'leveldb/table\&.h'\fP
.br
\fC#include 'util/hash\&.h'\fP
.br
\fC#include 'util/logging\&.h'\fP
.br
\fC#include 'util/mutexlock\&.h'\fP
.br
\fC#include 'util/testharness\&.h'\fP
.br
\fC#include 'util/testutil\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBleveldb::SpecialEnv\fP"
.br
.ti -1c
.RI "class \fBleveldb::DBTest\fP"
.br
.ti -1c
.RI "class \fBleveldb::ModelDB\fP"
.br
.ti -1c
.RI "class \fBleveldb::ModelDB::ModelSnapshot\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, Empty)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, ReadWrite)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, PutDeleteGet)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, GetFromImmutableLayer)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, GetFromVersions)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, GetSnapshot)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, GetLevel0Ordering)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, GetOrderedByLevels)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, GetPicksCorrectFile)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, GetEncountersEmptyLevel)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, IterEmpty)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, IterSingle)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, IterMulti)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, IterSmallAndLargeMix)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, IterMultiWithDelete)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, Recover)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, RecoveryWithEmptyLog)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, RecoverDuringMemtableCompaction)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, MinorCompactionsHappen)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, RecoverWithLargeLog)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, CompactionsGenerateMultipleFiles)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, RepeatedWritesToSameKey)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, SparseMerge)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, ApproximateSizes)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, ApproximateSizes_MixOfSmallAndLarge)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, IteratorPinsRef)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, Snapshot)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, HiddenValuesAreRemoved)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, DeletionMarkers1)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, DeletionMarkers2)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, OverlapInLevel0)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, L0_CompactionBug_Issue44_a)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, L0_CompactionBug_Issue44_b)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, ComparatorCheck)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, CustomComparator)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, ManualCompaction)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, DBOpen_Options)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, Locking)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, NoSpace)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, NonWritableFileSystem)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, WriteSyncError)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, ManifestWriteError)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, MissingSSTFile)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, StillReadSST)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, FilesDeletedAfterCompaction)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, BloomFilter)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, MultiThreaded)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (DBTest, Randomized)"
.br
.ti -1c
.RI "std::string \fBleveldb::MakeKey\fP (unsigned int num)"
.br
.ti -1c
.RI "void \fBleveldb::BM_LogAndApply\fP (int iters, int num_base_files)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 2118 of file db_test\&.cc\&.
.SH "Variable Documentation"
.PP 
.SS "int count_"

.PP
Definition at line 32 of file db_test\&.cc\&.
.SS "port::AtomicPointer counter[kNumThreads]"

.PP
Definition at line 1739 of file db_test\&.cc\&.
.SS "int id"

.PP
Definition at line 1745 of file db_test\&.cc\&.
.SS "port::Mutex mu_"

.PP
Definition at line 31 of file db_test\&.cc\&.
.SS "MTState* state"

.PP
Definition at line 1744 of file db_test\&.cc\&.
.SS "port::AtomicPointer stop"

.PP
Definition at line 1738 of file db_test\&.cc\&.
.SS "DBTest* test"

.PP
Definition at line 1737 of file db_test\&.cc\&.
.SS "port::AtomicPointer thread_done[kNumThreads]"

.PP
Definition at line 1740 of file db_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
