.TH "/home/dev/ds-160209/src/leveldb/db/dbformat.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/db/dbformat.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'leveldb/comparator\&.h'\fP
.br
\fC#include 'leveldb/db\&.h'\fP
.br
\fC#include 'leveldb/filter_policy\&.h'\fP
.br
\fC#include 'leveldb/slice\&.h'\fP
.br
\fC#include 'leveldb/table_builder\&.h'\fP
.br
\fC#include 'util/coding\&.h'\fP
.br
\fC#include 'util/logging\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBleveldb::ParsedInternalKey\fP"
.br
.ti -1c
.RI "class \fBleveldb::InternalKeyComparator\fP"
.br
.ti -1c
.RI "class \fBleveldb::InternalFilterPolicy\fP"
.br
.ti -1c
.RI "class \fBleveldb::InternalKey\fP"
.br
.ti -1c
.RI "class \fBleveldb::LookupKey\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.ti -1c
.RI " \fBleveldb::config\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBuint64_t\fP \fBleveldb::SequenceNumber\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBleveldb::ValueType\fP { \fBleveldb::kTypeDeletion\fP = 0x0, \fBleveldb::kTypeValue\fP = 0x1 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBleveldb::InternalKeyEncodingLength\fP (const ParsedInternalKey &key)"
.br
.ti -1c
.RI "void \fBleveldb::AppendInternalKey\fP (std::string *result, const ParsedInternalKey &key)"
.br
.ti -1c
.RI "bool \fBleveldb::ParseInternalKey\fP (const Slice &internal_key, ParsedInternalKey *result)"
.br
.ti -1c
.RI "Slice \fBleveldb::ExtractUserKey\fP (const Slice &internal_key)"
.br
.ti -1c
.RI "ValueType \fBleveldb::ExtractValueType\fP (const Slice &internal_key)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
