.TH "DEBUGConsole" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DEBUGConsole \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <debugconsole\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMessageClass\fP { \fBMC_ERROR\fP, \fBMC_DEBUG\fP, \fBCMD_REQUEST\fP, \fBCMD_REPLY\fP, \fBCMD_ERROR\fP }"
.br
.in -1c
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBmessage\fP (int category, const QString &message, bool html=false)"
.br
.ti -1c
.RI "void \fBsetNumConnections\fP (int count)"
.br
.ti -1c
.RI "void \fBsetNumBlocks\fP (int count)"
.br
.ti -1c
.RI "void \fBsetStormnodeCount\fP (const QString &strStormnodes)"
.br
.ti -1c
.RI "void \fBshowPeers\fP ()"
.br
.ti -1c
.RI "void \fBbrowseHistory\fP (int offset)"
.br
.ti -1c
.RI "void \fBscrollToEnd\fP ()"
.br
.ti -1c
.RI "void \fBpeerSelected\fP (const QItemSelection &selected, const QItemSelection &deselected)"
.br
.ti -1c
.RI "void \fBpeerLayoutChanged\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBstopExecutor\fP ()"
.br
.ti -1c
.RI "void \fBcmdRequest\fP (const QString &command)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDEBUGConsole\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~DEBUGConsole\fP ()"
.br
.ti -1c
.RI "void \fBsetClientModel\fP (\fBClientModel\fP *model)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBeventFilter\fP (QObject *obj, QEvent *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Local DarkSilk RPC console\&. 
.PP
Definition at line 20 of file debugconsole\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBDEBUGConsole::MessageClass\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMC_ERROR \fP\fP
.TP
\fB\fIMC_DEBUG \fP\fP
.TP
\fB\fICMD_REQUEST \fP\fP
.TP
\fB\fICMD_REPLY \fP\fP
.TP
\fB\fICMD_ERROR \fP\fP
.PP
Definition at line 30 of file debugconsole\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DEBUGConsole::DEBUGConsole (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 202 of file debugconsole\&.cpp\&.
.SS "DEBUGConsole::~DEBUGConsole ()"

.PP
Definition at line 238 of file debugconsole\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void DEBUGConsole::browseHistory (int offset)\fC [slot]\fP"
Go forward or back in history 
.PP
Definition at line 565 of file debugconsole\&.cpp\&.
.SS "void DEBUGConsole::clear ()\fC [slot]\fP"

.PP
Definition at line 469 of file debugconsole\&.cpp\&.
.SS "void DEBUGConsole::cmdRequest (const QString & command)\fC [signal]\fP"

.SS "bool DEBUGConsole::eventFilter (QObject * obj, QEvent * event)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 244 of file debugconsole\&.cpp\&.
.SS "void DEBUGConsole::message (int category, const QString & message, bool html = \fCfalse\fP)\fC [slot]\fP"

.PP
Definition at line 508 of file debugconsole\&.cpp\&.
.SS "void DEBUGConsole::peerLayoutChanged ()\fC [slot]\fP"
Handle updated peer information 
.PP
Definition at line 375 of file debugconsole\&.cpp\&.
.SS "void DEBUGConsole::peerSelected (const QItemSelection & selected, const QItemSelection & deselected)\fC [slot]\fP"
Handle selection of peer in peers list 
.PP
Definition at line 363 of file debugconsole\&.cpp\&.
.SS "void DEBUGConsole::scrollToEnd ()\fC [slot]\fP"
Scroll console view to end 
.PP
Definition at line 616 of file debugconsole\&.cpp\&.
.SS "void DEBUGConsole::setClientModel (\fBClientModel\fP * model)"

.PP
Definition at line 308 of file debugconsole\&.cpp\&.
.SS "void DEBUGConsole::setNumBlocks (int count)\fC [slot]\fP"
Set number of blocks shown in the UI 
.PP
Definition at line 529 of file debugconsole\&.cpp\&.
.SS "void DEBUGConsole::setNumConnections (int count)\fC [slot]\fP"
Set number of connections shown in the UI 
.PP
Definition at line 524 of file debugconsole\&.cpp\&.
.SS "void DEBUGConsole::setStormnodeCount (const QString & strStormnodes)\fC [slot]\fP"
Set number of stormnodes shown in the UI 
.PP
Definition at line 536 of file debugconsole\&.cpp\&.
.SS "void DEBUGConsole::showPeers ()\fC [slot]\fP"
Switch to peers tab and show 
.PP
Definition at line 502 of file debugconsole\&.cpp\&.
.SS "void DEBUGConsole::stopExecutor ()\fC [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
