.TH "/home/dev/ds-160209/src/qt/debugconsole.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/debugconsole.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'debugconsole\&.h'\fP
.br
\fC#include 'ui_debugconsole\&.h'\fP
.br
\fC#include 'clientmodel\&.h'\fP
.br
\fC#include 'guiutil\&.h'\fP
.br
\fC#include 'rpcserver\&.h'\fP
.br
\fC#include 'rpcclient\&.h'\fP
.br
\fC#include <QTime>\fP
.br
\fC#include <QThread>\fP
.br
\fC#include <QKeyEvent>\fP
.br
\fC#include <QUrl>\fP
.br
\fC#include <QScrollBar>\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include 'debugconsole\&.moc'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRPCExecutor\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const QSize \fBICON_SIZE\fP (24, 24)"
.br
.ti -1c
.RI "bool \fBparseCommandLine\fP (std::vector< std::string > &args, const std::string &strCommand)"
.br
.ti -1c
.RI "QString \fBGetBoostVersion\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBCONSOLE_HISTORY\fP = 50"
.br
.ti -1c
.RI "const int \fBINITIAL_TRAFFIC_GRAPH_MINS\fP = 30"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   const char * \fBurl\fP"
.br
.ti -1c
.RI "   const char * \fBsource\fP"
.br
.ti -1c
.RI "} \fBICON_MAPPING\fP []"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QString GetBoostVersion ()"

.PP
Definition at line 147 of file debugconsole\&.cpp\&.
.SS "const QSize ICON_SIZE (24, 24)"

.SS "bool parseCommandLine (std::vector< std::string > & args, const std::string & strCommand)"
Split shell command line into a list of arguments\&. Aims to emulate \fCbash\fP and friends\&.
.PP
.IP "\(bu" 2
Arguments are delimited with whitespace
.IP "\(bu" 2
Extra whitespace at the beginning and end and between arguments will be ignored
.IP "\(bu" 2
Text can be 'double' or 'single' quoted
.IP "\(bu" 2
The backslash \fC\\\fP is used as escape character
.IP "  \(bu" 4
Outside quotes, any character can be escaped
.IP "  \(bu" 4
Within double quotes, only escape \fC' and backslashes before a \\c '\fP or another backslash
.IP "  \(bu" 4
Within single quotes, no escaping is possible and no special interpretation takes place
.PP

.PP
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP Parsed arguments will be appended to this list 
.br
\fIstrCommand\fP Command line to split 
.RE
.PP

.PP
Definition at line 77 of file debugconsole\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const int CONSOLE_HISTORY = 50"

.PP
Definition at line 25 of file debugconsole\&.cpp\&.
.SS "const { \&.\&.\&. }   ICON_MAPPING[]"
\fBInitial value:\fP
.PP
.nf
= {
    {"cmd-request", ":/icons/tx_input"},
    {"cmd-reply", ":/icons/tx_output"},
    {"cmd-error", ":/icons/tx_output"},
    {"misc", ":/icons/tx_inout"},
    {NULL, NULL}
}
.fi
.SS "const int INITIAL_TRAFFIC_GRAPH_MINS = 30"

.PP
Definition at line 29 of file debugconsole\&.cpp\&.
.SS "const char* source"

.PP
Definition at line 33 of file debugconsole\&.cpp\&.
.SS "const char* url"

.PP
Definition at line 32 of file debugconsole\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
