.TH "/home/dev/ds-160209/src/leveldb/db/dumpfile.cc" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/db/dumpfile.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'db/dbformat\&.h'\fP
.br
\fC#include 'db/filename\&.h'\fP
.br
\fC#include 'db/log_reader\&.h'\fP
.br
\fC#include 'db/version_edit\&.h'\fP
.br
\fC#include 'db/write_batch_internal\&.h'\fP
.br
\fC#include 'leveldb/env\&.h'\fP
.br
\fC#include 'leveldb/iterator\&.h'\fP
.br
\fC#include 'leveldb/options\&.h'\fP
.br
\fC#include 'leveldb/status\&.h'\fP
.br
\fC#include 'leveldb/table\&.h'\fP
.br
\fC#include 'leveldb/write_batch\&.h'\fP
.br
\fC#include 'util/logging\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Status \fBleveldb::DumpFile\fP (Env *env, const std::string &fname, WritableFile *dst)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "WritableFile* dst_"

.PP
Definition at line 38 of file dumpfile\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
