.TH "/home/dev/ds-160209/src/secp256k1/src/ecmult_static_context.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/secp256k1/src/ecmult_static_context.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'group\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSC\fP   \fBSECP256K1_GE_STORAGE_CONST\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SC   \fBSECP256K1_GE_STORAGE_CONST\fP"

.PP
Definition at line 4 of file ecmult_static_context\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
