.TH "EditAddressDialog" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EditAddressDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <editaddressdialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMode\fP { \fBNewReceivingAddress\fP, \fBNewSendingAddress\fP, \fBEditReceivingAddress\fP, \fBEditSendingAddress\fP }"
.br
.in -1c
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBaccept\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditAddressDialog\fP (\fBMode\fP mode, QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~EditAddressDialog\fP ()"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBAddressTableModel\fP *model)"
.br
.ti -1c
.RI "void \fBloadRow\fP (int row)"
.br
.ti -1c
.RI "QString \fBgetAddress\fP () const "
.br
.ti -1c
.RI "void \fBsetAddress\fP (const QString &address)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Dialog for editing an address and associated information\&. 
.PP
Definition at line 17 of file editaddressdialog\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBEditAddressDialog::Mode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINewReceivingAddress \fP\fP
.TP
\fB\fINewSendingAddress \fP\fP
.TP
\fB\fIEditReceivingAddress \fP\fP
.TP
\fB\fIEditSendingAddress \fP\fP
.PP
Definition at line 22 of file editaddressdialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EditAddressDialog::EditAddressDialog (\fBMode\fP mode, QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 10 of file editaddressdialog\&.cpp\&.
.SS "EditAddressDialog::~EditAddressDialog ()"

.PP
Definition at line 48 of file editaddressdialog\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void EditAddressDialog::accept ()\fC [slot]\fP"

.PP
Definition at line 99 of file editaddressdialog\&.cpp\&.
.SS "QString EditAddressDialog::getAddress () const"

.PP
Definition at line 141 of file editaddressdialog\&.cpp\&.
.SS "void EditAddressDialog::loadRow (int row)"

.PP
Definition at line 65 of file editaddressdialog\&.cpp\&.
.SS "void EditAddressDialog::setAddress (const QString & address)"

.PP
Definition at line 146 of file editaddressdialog\&.cpp\&.
.SS "void EditAddressDialog::setModel (\fBAddressTableModel\fP * model)"

.PP
Definition at line 53 of file editaddressdialog\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
