.TH "/home/dev/ds-160209/src/crypto/argon2/encoding.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/crypto/argon2/encoding.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'argon2\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBencode_string\fP (char *dst, size_t dst_len, \fBargon2_context\fP *ctx, \fBargon2_type\fP type)"
.br
.ti -1c
.RI "int \fBdecode_string\fP (\fBargon2_context\fP *ctx, const char *str, \fBargon2_type\fP type)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int decode_string (\fBargon2_context\fP * ctx, const char * str, \fBargon2_type\fP type)"

.PP
Definition at line 249 of file encoding\&.c\&.
.SS "int encode_string (char * dst, size_t dst_len, \fBargon2_context\fP * ctx, \fBargon2_type\fP type)"

.PP
Definition at line 371 of file encoding\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
