.TH "FlowLayout" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlowLayout \- [0]  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <flowlayout\&.h>\fP
.PP
Inherits QLayout\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlowLayout\fP (QWidget *parent, int margin=-1, int hSpacing=-1, int vSpacing=-1)"
.br
.RI "\fI[1] \fP"
.ti -1c
.RI "\fBFlowLayout\fP (int margin=-1, int hSpacing=-1, int vSpacing=-1)"
.br
.ti -1c
.RI "\fB~FlowLayout\fP ()"
.br
.RI "\fI[1] \fP"
.ti -1c
.RI "void \fBaddItem\fP (QLayoutItem *item)"
.br
.RI "\fI[2] \fP"
.ti -1c
.RI "int \fBhorizontalSpacing\fP () const "
.br
.RI "\fI[3] \fP"
.ti -1c
.RI "int \fBverticalSpacing\fP () const "
.br
.ti -1c
.RI "Qt::Orientations \fBexpandingDirections\fP () const "
.br
.RI "\fI[5] \fP"
.ti -1c
.RI "bool \fBhasHeightForWidth\fP () const "
.br
.RI "\fI[6] \fP"
.ti -1c
.RI "int \fBheightForWidth\fP (int) const "
.br
.ti -1c
.RI "int \fBcount\fP () const "
.br
.RI "\fI[4] \fP"
.ti -1c
.RI "QLayoutItem * \fBitemAt\fP (int index) const "
.br
.ti -1c
.RI "QSize \fBminimumSize\fP () const "
.br
.ti -1c
.RI "void \fBsetGeometry\fP (const QRect &rect)"
.br
.RI "\fI[7] \fP"
.ti -1c
.RI "QSize \fBsizeHint\fP () const "
.br
.ti -1c
.RI "QLayoutItem * \fBtakeAt\fP (int index)"
.br
.in -1c
.SH "Detailed Description"
.PP 
[0] 
.PP
Definition at line 48 of file flowlayout\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FlowLayout::FlowLayout (QWidget * parent, int margin = \fC-1\fP, int hSpacing = \fC-1\fP, int vSpacing = \fC-1\fP)"

.PP
[1] 
.PP
Definition at line 47 of file flowlayout\&.cpp\&.
.SS "FlowLayout::FlowLayout (int margin = \fC-1\fP, int hSpacing = \fC-1\fP, int vSpacing = \fC-1\fP)"

.PP
Definition at line 53 of file flowlayout\&.cpp\&.
.SS "FlowLayout::~FlowLayout ()"

.PP
[1] [2] 
.PP
Definition at line 61 of file flowlayout\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void FlowLayout::addItem (QLayoutItem * item)"

.PP
[2] [3] 
.PP
Definition at line 70 of file flowlayout\&.cpp\&.
.SS "int FlowLayout::count () const"

.PP
[4] [5] 
.PP
Definition at line 97 of file flowlayout\&.cpp\&.
.SS "Qt::Orientations FlowLayout::expandingDirections () const"

.PP
[5] [6] 
.PP
Definition at line 117 of file flowlayout\&.cpp\&.
.SS "bool FlowLayout::hasHeightForWidth () const"

.PP
[6] [7] 
.PP
Definition at line 124 of file flowlayout\&.cpp\&.
.SS "int FlowLayout::heightForWidth (int width) const"

.PP
Definition at line 129 of file flowlayout\&.cpp\&.
.SS "int FlowLayout::horizontalSpacing () const"

.PP
[3] [4] 
.PP
Definition at line 77 of file flowlayout\&.cpp\&.
.SS "QLayoutItem * FlowLayout::itemAt (int index) const"

.PP
Definition at line 102 of file flowlayout\&.cpp\&.
.SS "QSize FlowLayout::minimumSize () const"

.PP
Definition at line 148 of file flowlayout\&.cpp\&.
.SS "void FlowLayout::setGeometry (const QRect & rect)"

.PP
[7] [8] 
.PP
Definition at line 137 of file flowlayout\&.cpp\&.
.SS "QSize FlowLayout::sizeHint () const"

.PP
Definition at line 143 of file flowlayout\&.cpp\&.
.SS "QLayoutItem * FlowLayout::takeAt (int index)"

.PP
Definition at line 107 of file flowlayout\&.cpp\&.
.SS "int FlowLayout::verticalSpacing () const"

.PP
Definition at line 86 of file flowlayout\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
