.TH "/home/dev/ds-160209/src/secp256k1/src/gen_context.c" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/secp256k1/src/gen_context.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'basic-config\&.h'\fP
.br
\fC#include 'include/secp256k1\&.h'\fP
.br
\fC#include 'field_impl\&.h'\fP
.br
\fC#include 'scalar_impl\&.h'\fP
.br
\fC#include 'group_impl\&.h'\fP
.br
\fC#include 'ecmult_gen_impl\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSE_BASIC_CONFIG\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define USE_BASIC_CONFIG   1"

.PP
Definition at line 7 of file gen_context\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 27 of file gen_context\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
