.TH "/home/dev/ds-160209/src/test/getarg_tests.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/test/getarg_tests.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/algorithm/string\&.hpp>\fP
.br
\fC#include <boost/foreach\&.hpp>\fP
.br
\fC#include <boost/test/unit_test\&.hpp>\fP
.br
\fC#include 'util\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (boolarg)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (stringarg)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (intarg)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (doubledash)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (boolargno)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (boolarg)"

.PP
Definition at line 25 of file getarg_tests\&.cpp\&.
.SS "BOOST_AUTO_TEST_CASE (stringarg)"

.PP
Definition at line 77 of file getarg_tests\&.cpp\&.
.SS "BOOST_AUTO_TEST_CASE (intarg)"

.PP
Definition at line 101 of file getarg_tests\&.cpp\&.
.SS "BOOST_AUTO_TEST_CASE (doubledash)"

.PP
Definition at line 120 of file getarg_tests\&.cpp\&.
.SS "BOOST_AUTO_TEST_CASE (boolargno)"

.PP
Definition at line 130 of file getarg_tests\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
