.TH "/home/dev/ds-160209/src/secp256k1/src/group.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/secp256k1/src/group.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'num\&.h'\fP
.br
\fC#include 'field\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsecp256k1_ge\fP"
.br
.ti -1c
.RI "struct \fBsecp256k1_gej\fP"
.br
.ti -1c
.RI "struct \fBsecp256k1_ge_storage\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSECP256K1_GE_CONST\fP(a,  b,  c,  d,  e,  f,  g,  h,  i,  j,  k,  l,  m,  n,  o,  p)   {\fBSECP256K1_FE_CONST\fP((a),(b),(c),(d),(e),(f),(g),(h)), \fBSECP256K1_FE_CONST\fP((i),(j),(k),(l),(m),(n),(o),(p)), 0}"
.br
.ti -1c
.RI "#define \fBSECP256K1_GE_CONST_INFINITY\fP   {\fBSECP256K1_FE_CONST\fP(0, 0, 0, 0, 0, 0, 0, 0), \fBSECP256K1_FE_CONST\fP(0, 0, 0, 0, 0, 0, 0, 0), 1}"
.br
.ti -1c
.RI "#define \fBSECP256K1_GEJ_CONST\fP(a,  b,  c,  d,  e,  f,  g,  h,  i,  j,  k,  l,  m,  n,  o,  p)   {\fBSECP256K1_FE_CONST\fP((a),(b),(c),(d),(e),(f),(g),(h)), \fBSECP256K1_FE_CONST\fP((i),(j),(k),(l),(m),(n),(o),(p)), \fBSECP256K1_FE_CONST\fP(0, 0, 0, 0, 0, 0, 0, 1), 0}"
.br
.ti -1c
.RI "#define \fBSECP256K1_GEJ_CONST_INFINITY\fP   {\fBSECP256K1_FE_CONST\fP(0, 0, 0, 0, 0, 0, 0, 0), \fBSECP256K1_FE_CONST\fP(0, 0, 0, 0, 0, 0, 0, 0), \fBSECP256K1_FE_CONST\fP(0, 0, 0, 0, 0, 0, 0, 0), 1}"
.br
.ti -1c
.RI "#define \fBSECP256K1_GE_STORAGE_CONST\fP(a,  b,  c,  d,  e,  f,  g,  h,  i,  j,  k,  l,  m,  n,  o,  p)   {\fBSECP256K1_FE_STORAGE_CONST\fP((a),(b),(c),(d),(e),(f),(g),(h)), \fBSECP256K1_FE_STORAGE_CONST\fP((i),(j),(k),(l),(m),(n),(o),(p))}"
.br
.ti -1c
.RI "#define \fBSECP256K1_GE_STORAGE_CONST_GET\fP(t)   \fBSECP256K1_FE_STORAGE_CONST_GET\fP(t\&.x), \fBSECP256K1_FE_STORAGE_CONST_GET\fP(t\&.y)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SECP256K1_GE_CONST(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p)   {\fBSECP256K1_FE_CONST\fP((a),(b),(c),(d),(e),(f),(g),(h)), \fBSECP256K1_FE_CONST\fP((i),(j),(k),(l),(m),(n),(o),(p)), 0}"

.PP
Definition at line 20 of file group\&.h\&.
.SS "#define SECP256K1_GE_CONST_INFINITY   {\fBSECP256K1_FE_CONST\fP(0, 0, 0, 0, 0, 0, 0, 0), \fBSECP256K1_FE_CONST\fP(0, 0, 0, 0, 0, 0, 0, 0), 1}"

.PP
Definition at line 21 of file group\&.h\&.
.SS "#define SECP256K1_GE_STORAGE_CONST(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p)   {\fBSECP256K1_FE_STORAGE_CONST\fP((a),(b),(c),(d),(e),(f),(g),(h)), \fBSECP256K1_FE_STORAGE_CONST\fP((i),(j),(k),(l),(m),(n),(o),(p))}"

.PP
Definition at line 39 of file group\&.h\&.
.SS "#define SECP256K1_GE_STORAGE_CONST_GET(t)   \fBSECP256K1_FE_STORAGE_CONST_GET\fP(t\&.x), \fBSECP256K1_FE_STORAGE_CONST_GET\fP(t\&.y)"

.PP
Definition at line 41 of file group\&.h\&.
.SS "#define SECP256K1_GEJ_CONST(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p)   {\fBSECP256K1_FE_CONST\fP((a),(b),(c),(d),(e),(f),(g),(h)), \fBSECP256K1_FE_CONST\fP((i),(j),(k),(l),(m),(n),(o),(p)), \fBSECP256K1_FE_CONST\fP(0, 0, 0, 0, 0, 0, 0, 1), 0}"

.PP
Definition at line 31 of file group\&.h\&.
.SS "#define SECP256K1_GEJ_CONST_INFINITY   {\fBSECP256K1_FE_CONST\fP(0, 0, 0, 0, 0, 0, 0, 0), \fBSECP256K1_FE_CONST\fP(0, 0, 0, 0, 0, 0, 0, 0), \fBSECP256K1_FE_CONST\fP(0, 0, 0, 0, 0, 0, 0, 0), 1}"

.PP
Definition at line 32 of file group\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
