.TH "/home/dev/ds-160209/src/qt/guiconstants.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/guiconstants.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTYLE_INVALID\fP   'background:#FF8080'"
.br
.ti -1c
.RI "#define \fBCOLOR_UNCONFIRMED\fP   QColor(128, 128, 128)"
.br
.ti -1c
.RI "#define \fBCOLOR_NEGATIVE\fP   QColor(255, 0, 0)"
.br
.ti -1c
.RI "#define \fBCOLOR_BAREADDRESS\fP   QColor(140, 140, 140)"
.br
.ti -1c
.RI "#define \fBEXPORT_IMAGE_SIZE\fP   256"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COLOR_BAREADDRESS   QColor(140, 140, 140)"

.PP
Definition at line 21 of file guiconstants\&.h\&.
.SS "#define COLOR_NEGATIVE   QColor(255, 0, 0)"

.PP
Definition at line 19 of file guiconstants\&.h\&.
.SS "#define COLOR_UNCONFIRMED   QColor(128, 128, 128)"

.PP
Definition at line 17 of file guiconstants\&.h\&.
.SS "#define EXPORT_IMAGE_SIZE   256"

.PP
Definition at line 32 of file guiconstants\&.h\&.
.SS "#define STYLE_INVALID   'background:#FF8080'"

.PP
Definition at line 14 of file guiconstants\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
