.TH "GUIUtil::ToolTipToRichTextFilter" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUIUtil::ToolTipToRichTextFilter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <guiutil\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBToolTipToRichTextFilter\fP (int size_threshold, QObject *parent=0)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBeventFilter\fP (QObject *obj, QEvent *evt)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Qt event filter that intercepts ToolTipChange events, and replaces the tooltip with a rich text representation if needed\&. This assures that Qt can word-wrap long tooltip messages\&. Tooltips longer than the provided size threshold (in characters) are wrapped\&. 
.PP
Definition at line 89 of file guiutil\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GUIUtil::ToolTipToRichTextFilter::ToolTipToRichTextFilter (int size_threshold, QObject * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 257 of file guiutil\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool GUIUtil::ToolTipToRichTextFilter::eventFilter (QObject * obj, QEvent * evt)\fC [protected]\fP"

.PP
Definition at line 263 of file guiutil\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
