.TH "GUIUtil::ClickableLabel" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUIUtil::ClickableLabel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <guiutil\&.h>\fP
.PP
Inherits QLabel\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBclicked\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClickableLabel\fP (const QString &text='', QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~ClickableLabel\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBmouseReleaseEvent\fP (QMouseEvent *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 128 of file guiutil\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GUIUtil::ClickableLabel::ClickableLabel (const QString & text = \fC''\fP, QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 465 of file guiutil\&.cpp\&.
.SS "GUIUtil::ClickableLabel::~ClickableLabel ()"

.PP
Definition at line 472 of file guiutil\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void GUIUtil::ClickableLabel::clicked ()\fC [signal]\fP"

.SS "void GUIUtil::ClickableLabel::mouseReleaseEvent (QMouseEvent * event)\fC [protected]\fP"

.PP
Definition at line 476 of file guiutil\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
