.TH "/home/dev/ds-160209/src/qt/guiutil.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/guiutil.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QString>\fP
.br
\fC#include <QObject>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QLabel>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGUIUtil::ToolTipToRichTextFilter\fP"
.br
.ti -1c
.RI "class \fBGUIUtil::HelpMessageBox\fP"
.br
.ti -1c
.RI "class \fBGUIUtil::ClickableLabel\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBGUIUtil\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QString \fBGUIUtil::dateTimeStr\fP (const QDateTime &date)"
.br
.ti -1c
.RI "QString \fBGUIUtil::dateTimeStr\fP (qint64 nTime)"
.br
.ti -1c
.RI "QFont \fBGUIUtil::darksilkAddressFont\fP ()"
.br
.ti -1c
.RI "void \fBGUIUtil::setupAddressWidget\fP (QLineEdit *widget, QWidget *parent)"
.br
.ti -1c
.RI "void \fBGUIUtil::setupAmountWidget\fP (QLineEdit *widget, QWidget *parent)"
.br
.ti -1c
.RI "bool \fBGUIUtil::parseDarkSilkURI\fP (const QUrl &uri, \fBSendCoinsRecipient\fP *out)"
.br
.ti -1c
.RI "bool \fBGUIUtil::parseDarkSilkURI\fP (QString uri, \fBSendCoinsRecipient\fP *out)"
.br
.ti -1c
.RI "QString \fBGUIUtil::HtmlEscape\fP (const QString &str, bool fMultiLine)"
.br
.ti -1c
.RI "QString \fBGUIUtil::HtmlEscape\fP (const std::string &str, bool fMultiLine)"
.br
.ti -1c
.RI "QString \fBGUIUtil::formatDurationStr\fP (int secs)"
.br
.ti -1c
.RI "QString \fBGUIUtil::formatPingTime\fP (double dPingTime)"
.br
.ti -1c
.RI "QString \fBGUIUtil::formatServicesStr\fP (quint64 mask)"
.br
.ti -1c
.RI "void \fBGUIUtil::copyEntryData\fP (QAbstractItemView *view, int column, int role)"
.br
.ti -1c
.RI "QString \fBGUIUtil::getSaveFileName\fP (QWidget *parent, const QString &caption, const QString &dir, const QString &filter, QString *selectedSuffixOut)"
.br
.ti -1c
.RI "Qt::ConnectionType \fBGUIUtil::blockingGUIThreadConnection\fP ()"
.br
.ti -1c
.RI "bool \fBGUIUtil::isObscured\fP (QWidget *w)"
.br
.ti -1c
.RI "void \fBGUIUtil::openDebugLogfile\fP ()"
.br
.ti -1c
.RI "bool \fBGUIUtil::GetStartOnSystemStartup\fP ()"
.br
.ti -1c
.RI "bool \fBGUIUtil::SetStartOnSystemStartup\fP (bool fAutoStart)"
.br
.ti -1c
.RI "void \fBGUIUtil::SetBlackThemeQSS\fP (QApplication &app)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
