.TH "/home/dev/ds-160209/src/secp256k1/src/hash_impl.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/secp256k1/src/hash_impl.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'hash\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCh\fP(x,  y,  z)   ((z) ^ ((x) & ((y) ^ (z))))"
.br
.ti -1c
.RI "#define \fBMaj\fP(x,  y,  z)   (((x) & (y)) | ((z) & ((x) | (y))))"
.br
.ti -1c
.RI "#define \fBSigma0\fP(x)   (((x) >> 2 | (x) << 30) ^ ((x) >> 13 | (x) << 19) ^ ((x) >> 22 | (x) << 10))"
.br
.ti -1c
.RI "#define \fBSigma1\fP(x)   (((x) >> 6 | (x) << 26) ^ ((x) >> 11 | (x) << 21) ^ ((x) >> 25 | (x) << 7))"
.br
.ti -1c
.RI "#define \fBsigma0\fP(x)   (((x) >> 7 | (x) << 25) ^ ((x) >> 18 | (x) << 14) ^ ((x) >> 3))"
.br
.ti -1c
.RI "#define \fBsigma1\fP(x)   (((x) >> 17 | (x) << 15) ^ ((x) >> 19 | (x) << 13) ^ ((x) >> 10))"
.br
.ti -1c
.RI "#define \fBRound\fP(a,  b,  c,  d,  e,  f,  g,  h,  k,  w)"
.br
.ti -1c
.RI "#define \fBBE32\fP(p)   ((((p) & 0xFF) << 24) | (((p) & 0xFF00) << 8) | (((p) & 0xFF0000) >> 8) | (((p) & 0xFF000000) >> 24))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BE32(p)   ((((p) & 0xFF) << 24) | (((p) & 0xFF00) << 8) | (((p) & 0xFF0000) >> 8) | (((p) & 0xFF000000) >> 24))"

.PP
Definition at line 33 of file hash_impl\&.h\&.
.SS "#define Ch(x, y, z)   ((z) ^ ((x) & ((y) ^ (z))))"

.PP
Definition at line 16 of file hash_impl\&.h\&.
.SS "#define Maj(x, y, z)   (((x) & (y)) | ((z) & ((x) | (y))))"

.PP
Definition at line 17 of file hash_impl\&.h\&.
.SS "#define Round(a, b, c, d, e, f, g, h, k, w)"
\fBValue:\fP
.PP
.nf
do { \\
    uint32_t t1 = (h) + Sigma1(e) + Ch((e), (f), (g)) + (k) + (w); \\
    uint32_t t2 = Sigma0(a) + Maj((a), (b), (c)); \
    (d) += t1; \
    (h) = t1 + t2; \
} while(0)
.fi
.PP
Definition at line 23 of file hash_impl\&.h\&.
.SS "#define Sigma0(x)   (((x) >> 2 | (x) << 30) ^ ((x) >> 13 | (x) << 19) ^ ((x) >> 22 | (x) << 10))"

.PP
Definition at line 18 of file hash_impl\&.h\&.
.SS "#define sigma0(x)   (((x) >> 7 | (x) << 25) ^ ((x) >> 18 | (x) << 14) ^ ((x) >> 3))"

.PP
Definition at line 20 of file hash_impl\&.h\&.
.SS "#define Sigma1(x)   (((x) >> 6 | (x) << 26) ^ ((x) >> 11 | (x) << 21) ^ ((x) >> 25 | (x) << 7))"

.PP
Definition at line 19 of file hash_impl\&.h\&.
.SS "#define sigma1(x)   (((x) >> 17 | (x) << 15) ^ ((x) >> 19 | (x) << 13) ^ ((x) >> 10))"

.PP
Definition at line 21 of file hash_impl\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
