.TH "/home/dev/ds-160209/src/test/hmac_tests.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/test/hmac_tests.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/test/unit_test\&.hpp>\fP
.br
\fC#include 'hash\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtestvec_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (hmacsha512_testvectors)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (hmacsha512_testvectors)"

.PP
Definition at line 106 of file hmac_tests\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
