.TH "/home/dev/ds-160209/src/i2p.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/i2p.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'i2psam\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSAM::StreamSessionAdapter\fP"
.br
.ti -1c
.RI "class \fBI2PSession\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSAM\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBI2P_SESSION_NAME_PARAM\fP   '-i2psessionname'"
.br
.ti -1c
.RI "#define \fBI2P_SESSION_NAME_DEFAULT\fP   'DarkSilk-client'"
.br
.ti -1c
.RI "#define \fBI2P_SAM_HOST_PARAM\fP   '-samhost'"
.br
.ti -1c
.RI "#define \fBI2P_SAM_HOST_DEFAULT\fP   \fBSAM_DEFAULT_ADDRESS\fP"
.br
.ti -1c
.RI "#define \fBI2P_SAM_PORT_PARAM\fP   '-samport'"
.br
.ti -1c
.RI "#define \fBI2P_SAM_PORT_DEFAULT\fP   \fBSAM_DEFAULT_PORT\fP"
.br
.ti -1c
.RI "#define \fBI2P_SAM_MY_DESTINATION_PARAM\fP   '-mydestination'"
.br
.ti -1c
.RI "#define \fBI2P_SAM_MY_DESTINATION_DEFAULT\fP   \fBSAM_GENERATE_MY_DESTINATION\fP"
.br
.ti -1c
.RI "#define \fBI2P_SAM_I2P_OPTIONS_PARAM\fP   '-i2poptions'"
.br
.ti -1c
.RI "#define \fBI2P_SAM_I2P_OPTIONS_DEFAULT\fP   \fBSAM_DEFAULT_I2P_OPTIONS\fP"
.br
.ti -1c
.RI "#define \fBI2P_SAM_GENERATE_DESTINATION_PARAM\fP   '-generatei2pdestination'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define I2P_SAM_GENERATE_DESTINATION_PARAM   '-generatei2pdestination'"

.PP
Definition at line 25 of file i2p\&.h\&.
.SS "#define I2P_SAM_HOST_DEFAULT   \fBSAM_DEFAULT_ADDRESS\fP"

.PP
Definition at line 14 of file i2p\&.h\&.
.SS "#define I2P_SAM_HOST_PARAM   '-samhost'"

.PP
Definition at line 13 of file i2p\&.h\&.
.SS "#define I2P_SAM_I2P_OPTIONS_DEFAULT   \fBSAM_DEFAULT_I2P_OPTIONS\fP"

.PP
Definition at line 23 of file i2p\&.h\&.
.SS "#define I2P_SAM_I2P_OPTIONS_PARAM   '-i2poptions'"

.PP
Definition at line 22 of file i2p\&.h\&.
.SS "#define I2P_SAM_MY_DESTINATION_DEFAULT   \fBSAM_GENERATE_MY_DESTINATION\fP"

.PP
Definition at line 20 of file i2p\&.h\&.
.SS "#define I2P_SAM_MY_DESTINATION_PARAM   '-mydestination'"

.PP
Definition at line 19 of file i2p\&.h\&.
.SS "#define I2P_SAM_PORT_DEFAULT   \fBSAM_DEFAULT_PORT\fP"

.PP
Definition at line 17 of file i2p\&.h\&.
.SS "#define I2P_SAM_PORT_PARAM   '-samport'"

.PP
Definition at line 16 of file i2p\&.h\&.
.SS "#define I2P_SESSION_NAME_DEFAULT   'DarkSilk-client'"

.PP
Definition at line 11 of file i2p\&.h\&.
.SS "#define I2P_SESSION_NAME_PARAM   '-i2psessionname'"

.PP
Definition at line 10 of file i2p\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
