.TH "/home/dev/ds-160209/src/i2pbuild.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/i2pbuild.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBI2P_NATIVE_VERSION_BUILD\fP   1"
.br
.ti -1c
.RI "#define \fBI2P_NATIVE_VERSION_REVISION\fP   0"
.br
.ti -1c
.RI "#define \fBI2P_NATIVE_REVISION_STR\fP   'unknown'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define I2P_NATIVE_REVISION_STR   'unknown'"

.PP
Definition at line 7 of file i2pbuild\&.h\&.
.SS "#define I2P_NATIVE_VERSION_BUILD   1"

.PP
Definition at line 5 of file i2pbuild\&.h\&.
.SS "#define I2P_NATIVE_VERSION_REVISION   0"

.PP
Definition at line 6 of file i2pbuild\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
