.TH "I2POptionsWidget" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2POptionsWidget \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <i2poptionswidget\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBsettingsChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBI2POptionsWidget\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~I2POptionsWidget\fP ()"
.br
.ti -1c
.RI "void \fBsetMapper\fP (\fBMonitoredDataMapper\fP &mapper)"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBClientModel\fP *model)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file i2poptionswidget\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "I2POptionsWidget::I2POptionsWidget (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 12 of file i2poptionswidget\&.cpp\&.
.SS "I2POptionsWidget::~I2POptionsWidget ()"

.PP
Definition at line 41 of file i2poptionswidget\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void I2POptionsWidget::setMapper (\fBMonitoredDataMapper\fP & mapper)"

.PP
Definition at line 46 of file i2poptionswidget\&.cpp\&.
.SS "void I2POptionsWidget::setModel (\fBClientModel\fP * model)"

.PP
Definition at line 67 of file i2poptionswidget\&.cpp\&.
.SS "void I2POptionsWidget::settingsChanged ()\fC [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
