.TH "I2PSession" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2PSession \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <i2p\&.h>\fP
.PP
Inherits \fBSAM::StreamSessionAdapter\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSAM::StreamSessionAdapter\fP & \fBInstance\fP ()"
.br
.ti -1c
.RI "static std::string \fBGenerateB32AddressFromDestination\fP (const std::string &destination)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 72 of file i2p\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string I2PSession::GenerateB32AddressFromDestination (const std::string & destination)\fC [static]\fP"

.PP
Definition at line 193 of file i2p\&.cpp\&.
.SS "static \fBSAM::StreamSessionAdapter\fP& I2PSession::Instance ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 76 of file i2p\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
