.TH "/home/dev/ds-160209/src/i2psam.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/i2psam.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <list>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSAM::Message\fP"
.br
.ti -1c
.RI "struct \fBSAM::Message::Answer< T >\fP"
.br
.ti -1c
.RI "class \fBSAM::Socket\fP"
.br
.ti -1c
.RI "struct \fBSAM::FullDestination\fP"
.br
.ti -1c
.RI "struct \fBSAM::RequestResult< T >\fP"
.br
.ti -1c
.RI "struct \fBSAM::RequestResult< std::auto_ptr< T > >\fP"
.br
.ti -1c
.RI "struct \fBSAM::RequestResult< std::auto_ptr< T > >::RequestResultRef\fP"
.br
.ti -1c
.RI "struct \fBSAM::RequestResult< void >\fP"
.br
.ti -1c
.RI "class \fBSAM::StreamSession\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSAM\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSAM_INVALID_SOCKET\fP   (-1)"
.br
.ti -1c
.RI "#define \fBSAM_SOCKET_ERROR\fP   (-1)"
.br
.ti -1c
.RI "#define \fBSAM_DEFAULT_ADDRESS\fP   '127\&.0\&.0\&.1'"
.br
.ti -1c
.RI "#define \fBSAM_DEFAULT_PORT\fP   7656"
.br
.ti -1c
.RI "#define \fBSAM_DEFAULT_MIN_VER\fP   '3\&.0'"
.br
.ti -1c
.RI "#define \fBSAM_DEFAULT_MAX_VER\fP   '3\&.0'"
.br
.ti -1c
.RI "#define \fBSAM_GENERATE_MY_DESTINATION\fP   'TRANSIENT'"
.br
.ti -1c
.RI "#define \fBSAM_MY_NAME\fP   'ME'"
.br
.ti -1c
.RI "#define \fBSAM_DEFAULT_I2P_OPTIONS\fP   ''"
.br
.ti -1c
.RI "#define \fBSAM_NAME_INBOUND_QUANTITY\fP   'inbound\&.quantity'"
.br
.ti -1c
.RI "#define \fBSAM_DEFAULT_INBOUND_QUANTITY\fP   2"
.br
.ti -1c
.RI "#define \fBSAM_NAME_INBOUND_LENGTH\fP   'inbound\&.length'"
.br
.ti -1c
.RI "#define \fBSAM_DEFAULT_INBOUND_LENGTH\fP   2"
.br
.ti -1c
.RI "#define \fBSAM_NAME_INBOUND_LENGTHVARIANCE\fP   'inbound\&.lengthVariance'"
.br
.ti -1c
.RI "#define \fBSAM_DEFAULT_INBOUND_LENGTHVARIANCE\fP   0"
.br
.ti -1c
.RI "#define \fBSAM_NAME_INBOUND_BACKUPQUANTITY\fP   'inbound\&.backupquantity'"
.br
.ti -1c
.RI "#define \fBSAM_DEFAULT_INBOUND_BACKUPQUANTITY\fP   0"
.br
.ti -1c
.RI "#define \fBSAM_NAME_INBOUND_ALLOWZEROHOP\fP   'inbound\&.allowzerohop'"
.br
.ti -1c
.RI "#define \fBSAM_DEFAULT_INBOUND_ALLOWZEROHOP\fP   true"
.br
.ti -1c
.RI "#define \fBSAM_NAME_INBOUND_IPRESTRICTION\fP   'inbound\&.iprestriction'"
.br
.ti -1c
.RI "#define \fBSAM_DEFAULT_INBOUND_IPRESTRICTION\fP   2"
.br
.ti -1c
.RI "#define \fBSAM_NAME_OUTBOUND_QUANTITY\fP   'outbound\&.quantity'"
.br
.ti -1c
.RI "#define \fBSAM_DEFAULT_OUTBOUND_QUANTITY\fP   2"
.br
.ti -1c
.RI "#define \fBSAM_NAME_OUTBOUND_LENGTH\fP   'outbound\&.length'"
.br
.ti -1c
.RI "#define \fBSAM_DEFAULT_OUTBOUND_LENGTH\fP   2"
.br
.ti -1c
.RI "#define \fBSAM_NAME_OUTBOUND_LENGTHVARIANCE\fP   'outbound\&.lengthvariance'"
.br
.ti -1c
.RI "#define \fBSAM_DEFAULT_OUTBOUND_LENGTHVARIANCE\fP   0"
.br
.ti -1c
.RI "#define \fBSAM_NAME_OUTBOUND_BACKUPQUANTITY\fP   'outbound\&.backupquantity'"
.br
.ti -1c
.RI "#define \fBSAM_DEFAULT_OUTBOUND_BACKUPQUANTITY\fP   0"
.br
.ti -1c
.RI "#define \fBSAM_NAME_OUTBOUND_ALLOWZEROHOP\fP   'outbound\&.allowzerohop'"
.br
.ti -1c
.RI "#define \fBSAM_DEFAULT_OUTBOUND_ALLOWZEROHOP\fP   true"
.br
.ti -1c
.RI "#define \fBSAM_NAME_OUTBOUND_IPRESTRICTION\fP   'outbound\&.iprestriction'"
.br
.ti -1c
.RI "#define \fBSAM_DEFAULT_OUTBOUND_IPRESTRICTION\fP   2"
.br
.ti -1c
.RI "#define \fBSAM_NAME_OUTBOUND_PRIORITY\fP   'outbound\&.priority'"
.br
.ti -1c
.RI "#define \fBSAM_DEFAULT_OUTBOUND_PRIORITY\fP   0"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBSAM::SOCKET\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SAM_DEFAULT_ADDRESS   '127\&.0\&.0\&.1'"

.PP
Definition at line 34 of file i2psam\&.h\&.
.SS "#define SAM_DEFAULT_I2P_OPTIONS   ''"

.PP
Definition at line 40 of file i2psam\&.h\&.
.SS "#define SAM_DEFAULT_INBOUND_ALLOWZEROHOP   true"

.PP
Definition at line 51 of file i2psam\&.h\&.
.SS "#define SAM_DEFAULT_INBOUND_BACKUPQUANTITY   0"

.PP
Definition at line 49 of file i2psam\&.h\&.
.SS "#define SAM_DEFAULT_INBOUND_IPRESTRICTION   2"

.PP
Definition at line 53 of file i2psam\&.h\&.
.SS "#define SAM_DEFAULT_INBOUND_LENGTH   2"

.PP
Definition at line 45 of file i2psam\&.h\&.
.SS "#define SAM_DEFAULT_INBOUND_LENGTHVARIANCE   0"

.PP
Definition at line 47 of file i2psam\&.h\&.
.SS "#define SAM_DEFAULT_INBOUND_QUANTITY   2"

.PP
Definition at line 43 of file i2psam\&.h\&.
.SS "#define SAM_DEFAULT_MAX_VER   '3\&.0'"

.PP
Definition at line 37 of file i2psam\&.h\&.
.SS "#define SAM_DEFAULT_MIN_VER   '3\&.0'"

.PP
Definition at line 36 of file i2psam\&.h\&.
.SS "#define SAM_DEFAULT_OUTBOUND_ALLOWZEROHOP   true"

.PP
Definition at line 63 of file i2psam\&.h\&.
.SS "#define SAM_DEFAULT_OUTBOUND_BACKUPQUANTITY   0"

.PP
Definition at line 61 of file i2psam\&.h\&.
.SS "#define SAM_DEFAULT_OUTBOUND_IPRESTRICTION   2"

.PP
Definition at line 65 of file i2psam\&.h\&.
.SS "#define SAM_DEFAULT_OUTBOUND_LENGTH   2"

.PP
Definition at line 57 of file i2psam\&.h\&.
.SS "#define SAM_DEFAULT_OUTBOUND_LENGTHVARIANCE   0"

.PP
Definition at line 59 of file i2psam\&.h\&.
.SS "#define SAM_DEFAULT_OUTBOUND_PRIORITY   0"

.PP
Definition at line 67 of file i2psam\&.h\&.
.SS "#define SAM_DEFAULT_OUTBOUND_QUANTITY   2"

.PP
Definition at line 55 of file i2psam\&.h\&.
.SS "#define SAM_DEFAULT_PORT   7656"

.PP
Definition at line 35 of file i2psam\&.h\&.
.SS "#define SAM_GENERATE_MY_DESTINATION   'TRANSIENT'"

.PP
Definition at line 38 of file i2psam\&.h\&.
.SS "#define SAM_INVALID_SOCKET   (-1)"

.PP
Definition at line 31 of file i2psam\&.h\&.
.SS "#define SAM_MY_NAME   'ME'"

.PP
Definition at line 39 of file i2psam\&.h\&.
.SS "#define SAM_NAME_INBOUND_ALLOWZEROHOP   'inbound\&.allowzerohop'"

.PP
Definition at line 50 of file i2psam\&.h\&.
.SS "#define SAM_NAME_INBOUND_BACKUPQUANTITY   'inbound\&.backupquantity'"

.PP
Definition at line 48 of file i2psam\&.h\&.
.SS "#define SAM_NAME_INBOUND_IPRESTRICTION   'inbound\&.iprestriction'"

.PP
Definition at line 52 of file i2psam\&.h\&.
.SS "#define SAM_NAME_INBOUND_LENGTH   'inbound\&.length'"

.PP
Definition at line 44 of file i2psam\&.h\&.
.SS "#define SAM_NAME_INBOUND_LENGTHVARIANCE   'inbound\&.lengthVariance'"

.PP
Definition at line 46 of file i2psam\&.h\&.
.SS "#define SAM_NAME_INBOUND_QUANTITY   'inbound\&.quantity'"

.PP
Definition at line 42 of file i2psam\&.h\&.
.SS "#define SAM_NAME_OUTBOUND_ALLOWZEROHOP   'outbound\&.allowzerohop'"

.PP
Definition at line 62 of file i2psam\&.h\&.
.SS "#define SAM_NAME_OUTBOUND_BACKUPQUANTITY   'outbound\&.backupquantity'"

.PP
Definition at line 60 of file i2psam\&.h\&.
.SS "#define SAM_NAME_OUTBOUND_IPRESTRICTION   'outbound\&.iprestriction'"

.PP
Definition at line 64 of file i2psam\&.h\&.
.SS "#define SAM_NAME_OUTBOUND_LENGTH   'outbound\&.length'"

.PP
Definition at line 56 of file i2psam\&.h\&.
.SS "#define SAM_NAME_OUTBOUND_LENGTHVARIANCE   'outbound\&.lengthvariance'"

.PP
Definition at line 58 of file i2psam\&.h\&.
.SS "#define SAM_NAME_OUTBOUND_PRIORITY   'outbound\&.priority'"

.PP
Definition at line 66 of file i2psam\&.h\&.
.SS "#define SAM_NAME_OUTBOUND_QUANTITY   'outbound\&.quantity'"

.PP
Definition at line 54 of file i2psam\&.h\&.
.SS "#define SAM_SOCKET_ERROR   (-1)"

.PP
Definition at line 32 of file i2psam\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
