.TH "/home/dev/ds-160209/src/i2psam.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/i2psam.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'i2psam\&.h'\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSAM\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBclosesocket\fP   close"
.br
.ti -1c
.RI "#define \fBSAM_BUFSIZE\fP   65536"
.br
.ti -1c
.RI "#define \fBI2P_DESTINATION_SIZE\fP   516"
.br
.ti -1c
.RI "#define \fBSAM_MAKESTRING\fP(\fBX\fP)   \fBSAM_MAKESTRING2\fP(\fBX\fP)"
.br
.ti -1c
.RI "#define \fBSAM_MAKESTRING2\fP(\fBX\fP)   #\fBX\fP"
.br
.ti -1c
.RI "#define \fBSAM_CHECK_RESULT\fP(\fBvalue\fP)   if (result == \fBSAM_MAKESTRING\fP(\fBvalue\fP)) return \fBvalue\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define closesocket   close"

.PP
Definition at line 31 of file i2psam\&.cpp\&.
.SS "#define I2P_DESTINATION_SIZE   516"

.PP
Definition at line 35 of file i2psam\&.cpp\&.
.SS "#define SAM_BUFSIZE   65536"

.PP
Definition at line 34 of file i2psam\&.cpp\&.
.SS "#define SAM_CHECK_RESULT(\fBvalue\fP)   if (result == \fBSAM_MAKESTRING\fP(\fBvalue\fP)) return \fBvalue\fP"

.PP
Definition at line 750 of file i2psam\&.cpp\&.
.SS "#define SAM_MAKESTRING(\fBX\fP)   \fBSAM_MAKESTRING2\fP(\fBX\fP)"

.PP
Definition at line 747 of file i2psam\&.cpp\&.
.SS "#define SAM_MAKESTRING2(\fBX\fP)   #\fBX\fP"

.PP
Definition at line 748 of file i2psam\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
