.TH "/home/dev/ds-160209/src/init.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/init.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'init\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'chainparams\&.h'\fP
.br
\fC#include 'txdb\&.h'\fP
.br
\fC#include 'rpcserver\&.h'\fP
.br
\fC#include 'net\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'key\&.h'\fP
.br
\fC#include 'pubkey\&.h'\fP
.br
\fC#include 'ui_interface\&.h'\fP
.br
\fC#include 'activestormnode\&.h'\fP
.br
\fC#include 'stormnode-budget\&.h'\fP
.br
\fC#include 'stormnode-payments\&.h'\fP
.br
\fC#include 'stormnodeman\&.h'\fP
.br
\fC#include 'spork\&.h'\fP
.br
\fC#include 'stormnodeconfig\&.h'\fP
.br
\fC#include 'smessage\&.h'\fP
.br
\fC#include 'txdb-leveldb\&.h'\fP
.br
\fC#include <boost/algorithm/string/predicate\&.hpp>\fP
.br
\fC#include <boost/algorithm/string/replace\&.hpp>\fP
.br
\fC#include <boost/bind\&.hpp>\fP
.br
\fC#include <boost/filesystem\&.hpp>\fP
.br
\fC#include <boost/interprocess/sync/file_lock\&.hpp>\fP
.br
\fC#include <boost/thread\&.hpp>\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCCoinsViewErrorCatcher\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBStartShutdown\fP ()"
.br
.ti -1c
.RI "bool \fBShutdownRequested\fP ()"
.br
.ti -1c
.RI "void \fBShutdown\fP ()"
.br
.ti -1c
.RI "void \fBHandleSIGTERM\fP (int)"
.br
.ti -1c
.RI "void \fBHandleSIGHUP\fP (int)"
.br
.ti -1c
.RI "std::string \fBHelpMessage\fP ()"
.br
.ti -1c
.RI "bool \fBInitSanityCheck\fP (void)"
.br
.ti -1c
.RI "bool \fBAppInit2\fP (boost::thread_group &threadGroup)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCClientUIInterface\fP \fBuiInterface\fP"
.br
.ti -1c
.RI "bool \fBfConfChange\fP"
.br
.ti -1c
.RI "unsigned int \fBnNodeLifespan\fP"
.br
.ti -1c
.RI "unsigned int \fBnDerivationMethodIndex\fP"
.br
.ti -1c
.RI "unsigned int \fBnMinerSleep\fP"
.br
.ti -1c
.RI "bool \fBfUseFastIndex\fP"
.br
.ti -1c
.RI "bool \fBfOnlyTor\fP = false"
.br
.ti -1c
.RI "bool \fBfMinimizeCoinAge\fP"
.br
.ti -1c
.RI "bool \fBfFeeEstimatesInitialized\fP = false"
.br
.ti -1c
.RI "volatile bool \fBfRequestShutdown\fP = false"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool AppInit2 (boost::thread_group & threadGroup)"
Initialize darksilk\&. 
.PP
\fBPrecondition:\fP
.RS 4
Parameters should be parsed and config file should be read\&. 
.RE
.PP

.PP
Definition at line 375 of file init\&.cpp\&.
.SS "void HandleSIGHUP (int)"

.PP
Definition at line 204 of file init\&.cpp\&.
.SS "void HandleSIGTERM (int)"

.PP
Definition at line 199 of file init\&.cpp\&.
.SS "std::string HelpMessage ()"

.PP
Definition at line 243 of file init\&.cpp\&.
.SS "bool InitSanityCheck (void)"
Sanity checks Ensure that DarkSilk is running in a usable environment with all necessary library support\&. 
.PP
Definition at line 359 of file init\&.cpp\&.
.SS "void Shutdown ()"

.PP
Definition at line 130 of file init\&.cpp\&.
.SS "bool ShutdownRequested ()"

.PP
Definition at line 125 of file init\&.cpp\&.
.SS "void StartShutdown ()"

.PP
Definition at line 121 of file init\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "bool fConfChange"

.PP
Definition at line 53 of file init\&.cpp\&.
.SS "bool fFeeEstimatesInitialized = false"

.PP
Definition at line 61 of file init\&.cpp\&.
.SS "bool fMinimizeCoinAge"

.PP
Definition at line 59 of file init\&.cpp\&.
.SS "bool fOnlyTor = false"

.PP
Definition at line 58 of file init\&.cpp\&.
.SS "volatile bool fRequestShutdown = false"

.PP
Definition at line 95 of file init\&.cpp\&.
.SS "bool fUseFastIndex"

.PP
Definition at line 57 of file init\&.cpp\&.
.SS "unsigned int nDerivationMethodIndex"

.PP
Definition at line 55 of file init\&.cpp\&.
.SS "unsigned int nMinerSleep"

.PP
Definition at line 56 of file init\&.cpp\&.
.SS "unsigned int nNodeLifespan"

.PP
Definition at line 54 of file init\&.cpp\&.
.SS "\fBCClientUIInterface\fP uiInterface"

.PP
Definition at line 52 of file init\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
