.TH "/home/dev/ds-160209/src/init.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/init.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBboost\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBStartShutdown\fP ()"
.br
.ti -1c
.RI "bool \fBShutdownRequested\fP ()"
.br
.ti -1c
.RI "void \fBShutdown\fP ()"
.br
.ti -1c
.RI "bool \fBAppInit2\fP (boost::thread_group &threadGroup)"
.br
.ti -1c
.RI "std::string \fBHelpMessage\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBfOnlyTor\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool AppInit2 (boost::thread_group & threadGroup)"
Initialize darksilk\&. 
.PP
\fBPrecondition:\fP
.RS 4
Parameters should be parsed and config file should be read\&. 
.RE
.PP

.PP
Definition at line 375 of file init\&.cpp\&.
.SS "std::string HelpMessage ()"

.PP
Definition at line 243 of file init\&.cpp\&.
.SS "void Shutdown ()"

.PP
Definition at line 130 of file init\&.cpp\&.
.SS "bool ShutdownRequested ()"

.PP
Definition at line 125 of file init\&.cpp\&.
.SS "void StartShutdown ()"

.PP
Definition at line 121 of file init\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "bool fOnlyTor"

.PP
Definition at line 58 of file init\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
