.TH "/home/dev/ds-160209/src/instantx.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/instantx.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'primitives/transaction\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCConsensusVote\fP"
.br
.ti -1c
.RI "class \fBCTransactionLock\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINSTANTX_SIGNATURES_REQUIRED\fP   10"
.br
.ti -1c
.RI "#define \fBINSTANTX_SIGNATURES_TOTAL\fP   15"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint64_t\fP \fBCreateNewLock\fP (\fBCTransaction\fP tx)"
.br
.ti -1c
.RI "bool \fBIsIXTXValid\fP (const \fBCTransaction\fP &txCollateral)"
.br
.ti -1c
.RI "bool \fBCheckForConflictingLocks\fP (\fBCTransaction\fP &tx)"
.br
.ti -1c
.RI "void \fBProcessMessageInstantX\fP (\fBCNode\fP *pfrom, std::string &strCommand, \fBCDataStream\fP &vRecv)"
.br
.ti -1c
.RI "void \fBDoConsensusVote\fP (\fBCTransaction\fP &tx, \fBint64_t\fP nBlockHeight)"
.br
.ti -1c
.RI "bool \fBProcessConsensusVote\fP (\fBCNode\fP *pnode, \fBCConsensusVote\fP &ctx)"
.br
.ti -1c
.RI "void \fBCleanTransactionLocksList\fP ()"
.br
.ti -1c
.RI "\fBint64_t\fP \fBGetAverageVoteTime\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "map< \fBuint256\fP, \fBCTransaction\fP > \fBmapTxLockReq\fP"
.br
.ti -1c
.RI "map< \fBuint256\fP, \fBCTransaction\fP > \fBmapTxLockReqRejected\fP"
.br
.ti -1c
.RI "map< \fBuint256\fP, \fBCConsensusVote\fP > \fBmapTxLockVote\fP"
.br
.ti -1c
.RI "map< \fBuint256\fP, \fBCTransactionLock\fP > \fBmapTxLocks\fP"
.br
.ti -1c
.RI "std::map< \fBCOutPoint\fP, \fBuint256\fP > \fBmapLockedInputs\fP"
.br
.ti -1c
.RI "int \fBnCompleteTXLocks\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INSTANTX_SIGNATURES_REQUIRED   10"

.PP
Definition at line 19 of file instantx\&.h\&.
.SS "#define INSTANTX_SIGNATURES_TOTAL   15"

.PP
Definition at line 20 of file instantx\&.h\&.
.SH "Function Documentation"
.PP 
.SS "bool CheckForConflictingLocks (\fBCTransaction\fP & tx)"

.PP
Definition at line 396 of file instantx\&.cpp\&.
.SS "void CleanTransactionLocksList ()"

.PP
Definition at line 434 of file instantx\&.cpp\&.
.SS "\fBint64_t\fP CreateNewLock (\fBCTransaction\fP tx)"

.PP
Definition at line 221 of file instantx\&.cpp\&.
.SS "void DoConsensusVote (\fBCTransaction\fP & tx, \fBint64_t\fP nBlockHeight)"

.PP
Definition at line 259 of file instantx\&.cpp\&.
.SS "\fBint64_t\fP GetAverageVoteTime ()"

.PP
Definition at line 419 of file instantx\&.cpp\&.
.SS "bool IsIXTXValid (const \fBCTransaction\fP & txCollateral)"

.PP
Definition at line 175 of file instantx\&.cpp\&.
.SS "bool ProcessConsensusVote (\fBCNode\fP * pnode, \fBCConsensusVote\fP & ctx)"

.PP
Definition at line 302 of file instantx\&.cpp\&.
.SS "void ProcessMessageInstantX (\fBCNode\fP * pfrom, std::string & strCommand, \fBCDataStream\fP & vRecv)"

.PP
Definition at line 38 of file instantx\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "std::map<\fBCOutPoint\fP, \fBuint256\fP> mapLockedInputs"

.PP
Definition at line 27 of file instantx\&.cpp\&.
.SS "map<\fBuint256\fP, \fBCTransaction\fP> mapTxLockReq"

.PP
Definition at line 23 of file instantx\&.cpp\&.
.SS "map<\fBuint256\fP, \fBCTransaction\fP> mapTxLockReqRejected"

.PP
Definition at line 24 of file instantx\&.cpp\&.
.SS "map<\fBuint256\fP, \fBCTransactionLock\fP> mapTxLocks"

.PP
Definition at line 26 of file instantx\&.cpp\&.
.SS "map<\fBuint256\fP, \fBCConsensusVote\fP> mapTxLockVote"

.PP
Definition at line 25 of file instantx\&.cpp\&.
.SS "int nCompleteTXLocks"

.PP
Definition at line 29 of file instantx\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
