.TH "json_spirit::Json_grammer< Value_type, Iter_type >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
json_spirit::Json_grammer< Value_type, Iter_type > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json_spirit_reader_template\&.h>\fP
.PP
Inherits grammar< Json_grammer< Value_type, Iter_type > >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdefinition\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBSemantic_actions\fP< \fBValue_type\fP, Iter_type > \fBSemantic_actions_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJson_grammer\fP (\fBSemantic_actions_t\fP &semantic_actions)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBthrow_not_value\fP (Iter_type begin, Iter_type end)"
.br
.ti -1c
.RI "static void \fBthrow_not_array\fP (Iter_type begin, Iter_type end)"
.br
.ti -1c
.RI "static void \fBthrow_not_object\fP (Iter_type begin, Iter_type end)"
.br
.ti -1c
.RI "static void \fBthrow_not_pair\fP (Iter_type begin, Iter_type end)"
.br
.ti -1c
.RI "static void \fBthrow_not_colon\fP (Iter_type begin, Iter_type end)"
.br
.ti -1c
.RI "static void \fBthrow_not_string\fP (Iter_type begin, Iter_type end)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Value_type, class Iter_type>class json_spirit::Json_grammer< Value_type, Iter_type >"

.PP
Definition at line 370 of file json_spirit_reader_template\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class Value_type , class Iter_type > typedef \fBSemantic_actions\fP< \fBValue_type\fP, Iter_type > \fBjson_spirit::Json_grammer\fP< \fBValue_type\fP, Iter_type >::\fBSemantic_actions_t\fP"

.PP
Definition at line 374 of file json_spirit_reader_template\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class Value_type , class Iter_type > \fBjson_spirit::Json_grammer\fP< \fBValue_type\fP, Iter_type >::\fBJson_grammer\fP (\fBSemantic_actions_t\fP & semantic_actions)\fC [inline]\fP"

.PP
Definition at line 376 of file json_spirit_reader_template\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class Value_type , class Iter_type > static void \fBjson_spirit::Json_grammer\fP< \fBValue_type\fP, Iter_type >::throw_not_array (Iter_type begin, Iter_type end)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 386 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type , class Iter_type > static void \fBjson_spirit::Json_grammer\fP< \fBValue_type\fP, Iter_type >::throw_not_colon (Iter_type begin, Iter_type end)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 401 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type , class Iter_type > static void \fBjson_spirit::Json_grammer\fP< \fBValue_type\fP, Iter_type >::throw_not_object (Iter_type begin, Iter_type end)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 391 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type , class Iter_type > static void \fBjson_spirit::Json_grammer\fP< \fBValue_type\fP, Iter_type >::throw_not_pair (Iter_type begin, Iter_type end)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 396 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type , class Iter_type > static void \fBjson_spirit::Json_grammer\fP< \fBValue_type\fP, Iter_type >::throw_not_string (Iter_type begin, Iter_type end)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 406 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type , class Iter_type > static void \fBjson_spirit::Json_grammer\fP< \fBValue_type\fP, Iter_type >::throw_not_value (Iter_type begin, Iter_type end)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 381 of file json_spirit_reader_template\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
