.TH "json_spirit::Config_vector< String >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
json_spirit::Config_vector< String > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json_spirit_value\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef String \fBString_type\fP"
.br
.ti -1c
.RI "typedef \fBValue_impl\fP< \fBConfig_vector\fP > \fBValue_type\fP"
.br
.ti -1c
.RI "typedef \fBPair_impl\fP< \fBConfig_vector\fP > \fBPair_type\fP"
.br
.ti -1c
.RI "typedef std::vector< \fBValue_type\fP > \fBArray_type\fP"
.br
.ti -1c
.RI "typedef std::vector< \fBPair_type\fP > \fBObject_type\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBValue_type\fP & \fBadd\fP (\fBObject_type\fP &obj, const \fBString_type\fP &\fBname\fP, const \fBValue_type\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "static \fBString_type\fP \fBget_name\fP (const \fBPair_type\fP &pair)"
.br
.ti -1c
.RI "static \fBValue_type\fP \fBget_value\fP (const \fBPair_type\fP &pair)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class String>struct json_spirit::Config_vector< String >"

.PP
Definition at line 110 of file json_spirit_value\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class String > typedef std::vector< \fBValue_type\fP > \fBjson_spirit::Config_vector\fP< String >::\fBArray_type\fP"

.PP
Definition at line 115 of file json_spirit_value\&.h\&.
.SS "template<class String > typedef std::vector< \fBPair_type\fP > \fBjson_spirit::Config_vector\fP< String >::\fBObject_type\fP"

.PP
Definition at line 116 of file json_spirit_value\&.h\&.
.SS "template<class String > typedef \fBPair_impl\fP< \fBConfig_vector\fP > \fBjson_spirit::Config_vector\fP< String >::\fBPair_type\fP"

.PP
Definition at line 114 of file json_spirit_value\&.h\&.
.SS "template<class String > typedef String \fBjson_spirit::Config_vector\fP< String >::\fBString_type\fP"

.PP
Definition at line 112 of file json_spirit_value\&.h\&.
.SS "template<class String > typedef \fBValue_impl\fP< \fBConfig_vector\fP > \fBjson_spirit::Config_vector\fP< String >::\fBValue_type\fP"

.PP
Definition at line 113 of file json_spirit_value\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class String > static \fBValue_type\fP& \fBjson_spirit::Config_vector\fP< String >::add (\fBObject_type\fP & obj, const \fBString_type\fP & name, const \fBValue_type\fP & value)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 118 of file json_spirit_value\&.h\&.
.SS "template<class String > static \fBString_type\fP \fBjson_spirit::Config_vector\fP< String >::get_name (const \fBPair_type\fP & pair)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 125 of file json_spirit_value\&.h\&.
.SS "template<class String > static \fBValue_type\fP \fBjson_spirit::Config_vector\fP< String >::get_value (const \fBPair_type\fP & pair)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 130 of file json_spirit_value\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
