.TH "json_spirit::Value_impl< Config >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
json_spirit::Value_impl< Config > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json_spirit_value\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBConfig\fP \fBConfig_type\fP"
.br
.ti -1c
.RI "typedef \fBConfig::String_type\fP \fBString_type\fP"
.br
.ti -1c
.RI "typedef \fBConfig::Object_type\fP \fBObject\fP"
.br
.ti -1c
.RI "typedef \fBConfig::Array_type\fP \fBArray\fP"
.br
.ti -1c
.RI "typedef String_type::const_pointer \fBConst_str_ptr\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValue_impl\fP ()"
.br
.ti -1c
.RI "\fBValue_impl\fP (\fBConst_str_ptr\fP \fBvalue\fP)"
.br
.ti -1c
.RI "\fBValue_impl\fP (const \fBString_type\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "\fBValue_impl\fP (const \fBObject\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "\fBValue_impl\fP (const \fBArray\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "\fBValue_impl\fP (bool \fBvalue\fP)"
.br
.ti -1c
.RI "\fBValue_impl\fP (int \fBvalue\fP)"
.br
.ti -1c
.RI "\fBValue_impl\fP (\fBint64_t\fP \fBvalue\fP)"
.br
.ti -1c
.RI "\fBValue_impl\fP (\fBuint64_t\fP \fBvalue\fP)"
.br
.ti -1c
.RI "\fBValue_impl\fP (double \fBvalue\fP)"
.br
.ti -1c
.RI "\fBValue_impl\fP (const \fBValue_impl\fP &other)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBValue_impl\fP &lhs) const "
.br
.ti -1c
.RI "\fBValue_impl\fP & \fBoperator=\fP (const \fBValue_impl\fP &lhs)"
.br
.ti -1c
.RI "\fBValue_type\fP \fBtype\fP () const "
.br
.ti -1c
.RI "bool \fBis_uint64\fP () const "
.br
.ti -1c
.RI "bool \fBis_null\fP () const "
.br
.ti -1c
.RI "const \fBString_type\fP & \fBget_str\fP () const "
.br
.ti -1c
.RI "const \fBObject\fP & \fBget_obj\fP () const "
.br
.ti -1c
.RI "const \fBArray\fP & \fBget_array\fP () const "
.br
.ti -1c
.RI "bool \fBget_bool\fP () const "
.br
.ti -1c
.RI "int \fBget_int\fP () const "
.br
.ti -1c
.RI "\fBint64_t\fP \fBget_int64\fP () const "
.br
.ti -1c
.RI "\fBuint64_t\fP \fBget_uint64\fP () const "
.br
.ti -1c
.RI "double \fBget_real\fP () const "
.br
.ti -1c
.RI "\fBObject\fP & \fBget_obj\fP ()"
.br
.ti -1c
.RI "\fBArray\fP & \fBget_array\fP ()"
.br
.ti -1c
.RI "template<typename T > T \fBget_value\fP () const "
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const \fBValue_impl\fP \fBnull\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Config>class json_spirit::Value_impl< Config >"

.PP
Definition at line 31 of file json_spirit_value\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class Config> typedef \fBConfig::Array_type\fP \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::\fBArray\fP"

.PP
Definition at line 38 of file json_spirit_value\&.h\&.
.SS "template<class Config> typedef \fBConfig\fP \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::\fBConfig_type\fP"

.PP
Definition at line 35 of file json_spirit_value\&.h\&.
.SS "template<class Config> typedef String_type::const_pointer \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::\fBConst_str_ptr\fP"

.PP
Definition at line 39 of file json_spirit_value\&.h\&.
.SS "template<class Config> typedef \fBConfig::Object_type\fP \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::\fBObject\fP"

.PP
Definition at line 37 of file json_spirit_value\&.h\&.
.SS "template<class Config> typedef \fBConfig::String_type\fP \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::\fBString_type\fP"

.PP
Definition at line 36 of file json_spirit_value\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class Config > \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::\fBValue_impl\fP ()"

.PP
Definition at line 212 of file json_spirit_value\&.h\&.
.SS "template<class Config > \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::\fBValue_impl\fP (\fBConst_str_ptr\fP value)"

.PP
Definition at line 219 of file json_spirit_value\&.h\&.
.SS "template<class Config > \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::\fBValue_impl\fP (const \fBString_type\fP & value)"

.PP
Definition at line 227 of file json_spirit_value\&.h\&.
.SS "template<class Config > \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::\fBValue_impl\fP (const \fBObject\fP & value)"

.PP
Definition at line 235 of file json_spirit_value\&.h\&.
.SS "template<class Config > \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::\fBValue_impl\fP (const \fBArray\fP & value)"

.PP
Definition at line 243 of file json_spirit_value\&.h\&.
.SS "template<class Config > \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::\fBValue_impl\fP (bool value)"

.PP
Definition at line 251 of file json_spirit_value\&.h\&.
.SS "template<class Config > \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::\fBValue_impl\fP (int value)"

.PP
Definition at line 259 of file json_spirit_value\&.h\&.
.SS "template<class Config > \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::\fBValue_impl\fP (\fBint64_t\fP value)"

.PP
Definition at line 267 of file json_spirit_value\&.h\&.
.SS "template<class Config > \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::\fBValue_impl\fP (\fBuint64_t\fP value)"

.PP
Definition at line 275 of file json_spirit_value\&.h\&.
.SS "template<class Config > \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::\fBValue_impl\fP (double value)"

.PP
Definition at line 283 of file json_spirit_value\&.h\&.
.SS "template<class Config> \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::\fBValue_impl\fP (const \fBValue_impl\fP< \fBConfig\fP > & other)"

.SH "Member Function Documentation"
.PP 
.SS "template<class Config > const \fBValue_impl\fP< \fBConfig\fP >::\fBArray\fP & \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::get_array () const"

.PP
Definition at line 369 of file json_spirit_value\&.h\&.
.SS "template<class Config > \fBValue_impl\fP< \fBConfig\fP >::\fBArray\fP & \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::get_array ()"

.PP
Definition at line 431 of file json_spirit_value\&.h\&.
.SS "template<class Config > bool \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::get_bool () const"

.PP
Definition at line 377 of file json_spirit_value\&.h\&.
.SS "template<class Config > int \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::get_int () const"

.PP
Definition at line 385 of file json_spirit_value\&.h\&.
.SS "template<class Config > \fBint64_t\fP \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::get_int64 () const"

.PP
Definition at line 393 of file json_spirit_value\&.h\&.
.SS "template<class Config > const \fBValue_impl\fP< \fBConfig\fP >::\fBObject\fP & \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::get_obj () const"

.PP
Definition at line 361 of file json_spirit_value\&.h\&.
.SS "template<class Config > \fBValue_impl\fP< \fBConfig\fP >::\fBObject\fP & \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::get_obj ()"

.PP
Definition at line 423 of file json_spirit_value\&.h\&.
.SS "template<class Config > double \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::get_real () const"

.PP
Definition at line 409 of file json_spirit_value\&.h\&.
.SS "template<class Config > const \fBConfig::String_type\fP & \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::get_str () const"

.PP
Definition at line 353 of file json_spirit_value\&.h\&.
.SS "template<class Config > \fBuint64_t\fP \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::get_uint64 () const"

.PP
Definition at line 401 of file json_spirit_value\&.h\&.
.SS "template<class Config > template<typename T > T \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::get_value () const"

.PP
Definition at line 528 of file json_spirit_value\&.h\&.
.SS "template<class Config > bool \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::is_null () const"

.PP
Definition at line 333 of file json_spirit_value\&.h\&.
.SS "template<class Config > bool \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::is_uint64 () const"

.PP
Definition at line 327 of file json_spirit_value\&.h\&.
.SS "template<class Config > \fBValue_impl\fP< \fBConfig\fP > & \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::operator= (const \fBValue_impl\fP< \fBConfig\fP > & lhs)"

.PP
Definition at line 299 of file json_spirit_value\&.h\&.
.SS "template<class Config > bool \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::operator== (const \fBValue_impl\fP< \fBConfig\fP > & lhs) const"

.PP
Definition at line 311 of file json_spirit_value\&.h\&.
.SS "template<class Config > \fBValue_type\fP \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::type () const"

.PP
Definition at line 321 of file json_spirit_value\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class Config> const \fBValue_impl\fP< \fBConfig\fP > \fBjson_spirit::Value_impl\fP< \fBConfig\fP >::null\fC [static]\fP"

.PP
Definition at line 78 of file json_spirit_value\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
