.TH "json_spirit::Multi_pass_iters< Istream_type >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
json_spirit::Multi_pass_iters< Istream_type > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json_spirit_reader_template\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Istream_type::char_type \fBChar_type\fP"
.br
.ti -1c
.RI "typedef std::istream_iterator< \fBChar_type\fP, \fBChar_type\fP > \fBistream_iter\fP"
.br
.ti -1c
.RI "typedef spirit_namespace::multi_pass< \fBistream_iter\fP > \fBMp_iter\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMulti_pass_iters\fP (Istream_type &is)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMp_iter\fP \fBbegin_\fP"
.br
.ti -1c
.RI "\fBMp_iter\fP \fBend_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Istream_type>struct json_spirit::Multi_pass_iters< Istream_type >"

.PP
Definition at line 577 of file json_spirit_reader_template\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class Istream_type> typedef Istream_type::char_type \fBjson_spirit::Multi_pass_iters\fP< Istream_type >::\fBChar_type\fP"

.PP
Definition at line 579 of file json_spirit_reader_template\&.h\&.
.SS "template<class Istream_type> typedef std::istream_iterator< \fBChar_type\fP, \fBChar_type\fP > \fBjson_spirit::Multi_pass_iters\fP< Istream_type >::\fBistream_iter\fP"

.PP
Definition at line 580 of file json_spirit_reader_template\&.h\&.
.SS "template<class Istream_type> typedef spirit_namespace::multi_pass< \fBistream_iter\fP > \fBjson_spirit::Multi_pass_iters\fP< Istream_type >::\fBMp_iter\fP"

.PP
Definition at line 581 of file json_spirit_reader_template\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class Istream_type> \fBjson_spirit::Multi_pass_iters\fP< Istream_type >::\fBMulti_pass_iters\fP (Istream_type & is)\fC [inline]\fP"

.PP
Definition at line 583 of file json_spirit_reader_template\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class Istream_type> \fBMp_iter\fP \fBjson_spirit::Multi_pass_iters\fP< Istream_type >::begin_"

.PP
Definition at line 591 of file json_spirit_reader_template\&.h\&.
.SS "template<class Istream_type> \fBMp_iter\fP \fBjson_spirit::Multi_pass_iters\fP< Istream_type >::end_"

.PP
Definition at line 592 of file json_spirit_reader_template\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
