.TH "JSONRequest" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JSONRequest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJSONRequest\fP ()"
.br
.ti -1c
.RI "void \fBparse\fP (const \fBValue\fP &valRequest)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBValue\fP \fBid\fP"
.br
.ti -1c
.RI "string \fBstrMethod\fP"
.br
.ti -1c
.RI "\fBArray\fP \fBparams\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 668 of file rpcserver\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "JSONRequest::JSONRequest ()\fC [inline]\fP"

.PP
Definition at line 675 of file rpcserver\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void JSONRequest::parse (const \fBValue\fP & valRequest)"

.PP
Definition at line 679 of file rpcserver\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBValue\fP JSONRequest::id"

.PP
Definition at line 671 of file rpcserver\&.cpp\&.
.SS "\fBArray\fP JSONRequest::params"

.PP
Definition at line 673 of file rpcserver\&.cpp\&.
.SS "string JSONRequest::strMethod"

.PP
Definition at line 672 of file rpcserver\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
