.TH "json_spirit::Semantic_actions< Value_type, Iter_type >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
json_spirit::Semantic_actions< Value_type, Iter_type > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json_spirit_reader_template\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Value_type::Config_type \fBConfig_type\fP"
.br
.ti -1c
.RI "typedef Config_type::String_type \fBString_type\fP"
.br
.ti -1c
.RI "typedef Config_type::Object_type \fBObject_type\fP"
.br
.ti -1c
.RI "typedef Config_type::Array_type \fBArray_type\fP"
.br
.ti -1c
.RI "typedef String_type::value_type \fBChar_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSemantic_actions\fP (\fBValue_type\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBbegin_obj\fP (\fBChar_type\fP c)"
.br
.ti -1c
.RI "void \fBend_obj\fP (\fBChar_type\fP c)"
.br
.ti -1c
.RI "void \fBbegin_array\fP (\fBChar_type\fP c)"
.br
.ti -1c
.RI "void \fBend_array\fP (\fBChar_type\fP c)"
.br
.ti -1c
.RI "void \fBnew_name\fP (Iter_type begin, Iter_type end)"
.br
.ti -1c
.RI "void \fBnew_str\fP (Iter_type begin, Iter_type end)"
.br
.ti -1c
.RI "void \fBnew_true\fP (Iter_type begin, Iter_type end)"
.br
.ti -1c
.RI "void \fBnew_false\fP (Iter_type begin, Iter_type end)"
.br
.ti -1c
.RI "void \fBnew_null\fP (Iter_type begin, Iter_type end)"
.br
.ti -1c
.RI "void \fBnew_int\fP (\fBint64_t\fP i)"
.br
.ti -1c
.RI "void \fBnew_uint64\fP (\fBuint64_t\fP ui)"
.br
.ti -1c
.RI "void \fBnew_real\fP (double d)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Value_type, class Iter_type>class json_spirit::Semantic_actions< Value_type, Iter_type >"

.PP
Definition at line 196 of file json_spirit_reader_template\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class Value_type, class Iter_type> typedef Config_type::Array_type \fBjson_spirit::Semantic_actions\fP< \fBValue_type\fP, Iter_type >::\fBArray_type\fP"

.PP
Definition at line 203 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type, class Iter_type> typedef String_type::value_type \fBjson_spirit::Semantic_actions\fP< \fBValue_type\fP, Iter_type >::\fBChar_type\fP"

.PP
Definition at line 204 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type, class Iter_type> typedef Value_type::Config_type \fBjson_spirit::Semantic_actions\fP< \fBValue_type\fP, Iter_type >::\fBConfig_type\fP"

.PP
Definition at line 200 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type, class Iter_type> typedef Config_type::Object_type \fBjson_spirit::Semantic_actions\fP< \fBValue_type\fP, Iter_type >::\fBObject_type\fP"

.PP
Definition at line 202 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type, class Iter_type> typedef Config_type::String_type \fBjson_spirit::Semantic_actions\fP< \fBValue_type\fP, Iter_type >::\fBString_type\fP"

.PP
Definition at line 201 of file json_spirit_reader_template\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class Value_type, class Iter_type> \fBjson_spirit::Semantic_actions\fP< \fBValue_type\fP, Iter_type >::\fBSemantic_actions\fP (\fBValue_type\fP & value)\fC [inline]\fP"

.PP
Definition at line 206 of file json_spirit_reader_template\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class Value_type, class Iter_type> void \fBjson_spirit::Semantic_actions\fP< \fBValue_type\fP, Iter_type >::begin_array (\fBChar_type\fP c)\fC [inline]\fP"

.PP
Definition at line 226 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type, class Iter_type> void \fBjson_spirit::Semantic_actions\fP< \fBValue_type\fP, Iter_type >::begin_obj (\fBChar_type\fP c)\fC [inline]\fP"

.PP
Definition at line 212 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type, class Iter_type> void \fBjson_spirit::Semantic_actions\fP< \fBValue_type\fP, Iter_type >::end_array (\fBChar_type\fP c)\fC [inline]\fP"

.PP
Definition at line 233 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type, class Iter_type> void \fBjson_spirit::Semantic_actions\fP< \fBValue_type\fP, Iter_type >::end_obj (\fBChar_type\fP c)\fC [inline]\fP"

.PP
Definition at line 219 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type, class Iter_type> void \fBjson_spirit::Semantic_actions\fP< \fBValue_type\fP, Iter_type >::new_false (Iter_type begin, Iter_type end)\fC [inline]\fP"

.PP
Definition at line 259 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type, class Iter_type> void \fBjson_spirit::Semantic_actions\fP< \fBValue_type\fP, Iter_type >::new_int (\fBint64_t\fP i)\fC [inline]\fP"

.PP
Definition at line 273 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type, class Iter_type> void \fBjson_spirit::Semantic_actions\fP< \fBValue_type\fP, Iter_type >::new_name (Iter_type begin, Iter_type end)\fC [inline]\fP"

.PP
Definition at line 240 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type, class Iter_type> void \fBjson_spirit::Semantic_actions\fP< \fBValue_type\fP, Iter_type >::new_null (Iter_type begin, Iter_type end)\fC [inline]\fP"

.PP
Definition at line 266 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type, class Iter_type> void \fBjson_spirit::Semantic_actions\fP< \fBValue_type\fP, Iter_type >::new_real (double d)\fC [inline]\fP"

.PP
Definition at line 283 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type, class Iter_type> void \fBjson_spirit::Semantic_actions\fP< \fBValue_type\fP, Iter_type >::new_str (Iter_type begin, Iter_type end)\fC [inline]\fP"

.PP
Definition at line 247 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type, class Iter_type> void \fBjson_spirit::Semantic_actions\fP< \fBValue_type\fP, Iter_type >::new_true (Iter_type begin, Iter_type end)\fC [inline]\fP"

.PP
Definition at line 252 of file json_spirit_reader_template\&.h\&.
.SS "template<class Value_type, class Iter_type> void \fBjson_spirit::Semantic_actions\fP< \fBValue_type\fP, Iter_type >::new_uint64 (\fBuint64_t\fP ui)\fC [inline]\fP"

.PP
Definition at line 278 of file json_spirit_reader_template\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
