.TH "/home/dev/ds-160209/src/json/json_spirit_writer_template.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/json/json_spirit_writer_template.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'json_spirit_value\&.h'\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iomanip>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBjson_spirit::Generator< Value_type, Ostream_type >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBjson_spirit\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char \fBjson_spirit::to_hex_char\fP (unsigned int c)"
.br
.ti -1c
.RI "template<class String_type > String_type \fBjson_spirit::non_printable_to_string\fP (unsigned int c)"
.br
.ti -1c
.RI "template<typename Char_type , class String_type > bool \fBjson_spirit::add_esc_char\fP (Char_type c, String_type &s)"
.br
.ti -1c
.RI "template<class String_type > String_type \fBjson_spirit::add_esc_chars\fP (const String_type &s)"
.br
.ti -1c
.RI "template<class Value_type , class Ostream_type > void \fBjson_spirit::write_stream\fP (const Value_type &\fBvalue\fP, Ostream_type &os, bool pretty)"
.br
.ti -1c
.RI "template<class Value_type > Value_type::String_type \fBjson_spirit::write_string\fP (const Value_type &\fBvalue\fP, bool pretty)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
