.TH "json_spirit::internal_" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
json_spirit::internal_ \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBType_to_type\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class Value > int \fBget_value\fP (const \fBValue\fP &\fBvalue\fP, \fBType_to_type\fP< int >)"
.br
.ti -1c
.RI "template<class Value > \fBint64_t\fP \fBget_value\fP (const \fBValue\fP &\fBvalue\fP, \fBType_to_type\fP< \fBint64_t\fP >)"
.br
.ti -1c
.RI "template<class Value > \fBuint64_t\fP \fBget_value\fP (const \fBValue\fP &\fBvalue\fP, \fBType_to_type\fP< \fBuint64_t\fP >)"
.br
.ti -1c
.RI "template<class Value > double \fBget_value\fP (const \fBValue\fP &\fBvalue\fP, \fBType_to_type\fP< double >)"
.br
.ti -1c
.RI "template<class Value > \fBValue::String_type\fP \fBget_value\fP (const \fBValue\fP &\fBvalue\fP, \fBType_to_type\fP< typename \fBValue::String_type\fP >)"
.br
.ti -1c
.RI "template<class Value > \fBValue::Array\fP \fBget_value\fP (const \fBValue\fP &\fBvalue\fP, \fBType_to_type\fP< typename \fBValue::Array\fP >)"
.br
.ti -1c
.RI "template<class Value > \fBValue::Object\fP \fBget_value\fP (const \fBValue\fP &\fBvalue\fP, \fBType_to_type\fP< typename \fBValue::Object\fP >)"
.br
.ti -1c
.RI "template<class Value > bool \fBget_value\fP (const \fBValue\fP &\fBvalue\fP, \fBType_to_type\fP< bool >)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<class Value > int json_spirit::internal_::get_value (const \fBValue\fP & value, \fBType_to_type\fP< int >)"

.PP
Definition at line 478 of file json_spirit_value\&.h\&.
.SS "template<class Value > \fBint64_t\fP json_spirit::internal_::get_value (const \fBValue\fP & value, \fBType_to_type\fP< \fBint64_t\fP >)"

.PP
Definition at line 484 of file json_spirit_value\&.h\&.
.SS "template<class Value > \fBuint64_t\fP json_spirit::internal_::get_value (const \fBValue\fP & value, \fBType_to_type\fP< \fBuint64_t\fP >)"

.PP
Definition at line 490 of file json_spirit_value\&.h\&.
.SS "template<class Value > double json_spirit::internal_::get_value (const \fBValue\fP & value, \fBType_to_type\fP< double >)"

.PP
Definition at line 496 of file json_spirit_value\&.h\&.
.SS "template<class Value > \fBValue::String_type\fP json_spirit::internal_::get_value (const \fBValue\fP & value, \fBType_to_type\fP< typename \fBValue::String_type\fP >)"

.PP
Definition at line 502 of file json_spirit_value\&.h\&.
.SS "template<class Value > \fBValue::Array\fP json_spirit::internal_::get_value (const \fBValue\fP & value, \fBType_to_type\fP< typename \fBValue::Array\fP >)"

.PP
Definition at line 508 of file json_spirit_value\&.h\&.
.SS "template<class Value > \fBValue::Object\fP json_spirit::internal_::get_value (const \fBValue\fP & value, \fBType_to_type\fP< typename \fBValue::Object\fP >)"

.PP
Definition at line 514 of file json_spirit_value\&.h\&.
.SS "template<class Value > bool json_spirit::internal_::get_value (const \fBValue\fP & value, \fBType_to_type\fP< bool >)"

.PP
Definition at line 520 of file json_spirit_value\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
