.TH "/home/dev/ds-160209/src/json/json_spirit_reader.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/json/json_spirit_reader.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'json_spirit_value\&.h'\fP
.br
\fC#include 'json_spirit_error_position\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBjson_spirit\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBjson_spirit::read\fP (const std::string &s, \fBValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBjson_spirit::read\fP (std::istream &is, \fBValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBjson_spirit::read\fP (std::string::const_iterator &begin, std::string::const_iterator end, \fBValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBjson_spirit::read_or_throw\fP (const std::string &s, \fBValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBjson_spirit::read_or_throw\fP (std::istream &is, \fBValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBjson_spirit::read_or_throw\fP (std::string::const_iterator &begin, std::string::const_iterator end, \fBValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBjson_spirit::read\fP (const std::wstring &s, \fBwValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBjson_spirit::read\fP (std::wistream &is, \fBwValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBjson_spirit::read\fP (std::wstring::const_iterator &begin, std::wstring::const_iterator end, \fBwValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBjson_spirit::read_or_throw\fP (const std::wstring &s, \fBwValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBjson_spirit::read_or_throw\fP (std::wistream &is, \fBwValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBjson_spirit::read_or_throw\fP (std::wstring::const_iterator &begin, std::wstring::const_iterator end, \fBwValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBjson_spirit::read\fP (const std::string &s, \fBmValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBjson_spirit::read\fP (std::istream &is, \fBmValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBjson_spirit::read\fP (std::string::const_iterator &begin, std::string::const_iterator end, \fBmValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBjson_spirit::read_or_throw\fP (const std::string &s, \fBmValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBjson_spirit::read_or_throw\fP (std::istream &is, \fBmValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBjson_spirit::read_or_throw\fP (std::string::const_iterator &begin, std::string::const_iterator end, \fBmValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBjson_spirit::read\fP (const std::wstring &s, \fBwmValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBjson_spirit::read\fP (std::wistream &is, \fBwmValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBjson_spirit::read\fP (std::wstring::const_iterator &begin, std::wstring::const_iterator end, \fBwmValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBjson_spirit::read_or_throw\fP (const std::wstring &s, \fBwmValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBjson_spirit::read_or_throw\fP (std::wistream &is, \fBwmValue\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBjson_spirit::read_or_throw\fP (std::wstring::const_iterator &begin, std::wstring::const_iterator end, \fBwmValue\fP &\fBvalue\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
