.TH "json_spirit::Error_position" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
json_spirit::Error_position \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json_spirit_error_position\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBError_position\fP ()"
.br
.ti -1c
.RI "\fBError_position\fP (unsigned int line, unsigned int column, const std::string &reason)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBError_position\fP &lhs) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBline_\fP"
.br
.ti -1c
.RI "unsigned int \fBcolumn_\fP"
.br
.ti -1c
.RI "std::string \fBreason_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file json_spirit_error_position\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "json_spirit::Error_position::Error_position ()\fC [inline]\fP"

.PP
Definition at line 31 of file json_spirit_error_position\&.h\&.
.SS "json_spirit::Error_position::Error_position (unsigned int line, unsigned int column, const std::string & reason)\fC [inline]\fP"

.PP
Definition at line 37 of file json_spirit_error_position\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool json_spirit::Error_position::operator== (const \fBError_position\fP & lhs) const\fC [inline]\fP"

.PP
Definition at line 44 of file json_spirit_error_position\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned int json_spirit::Error_position::column_"

.PP
Definition at line 27 of file json_spirit_error_position\&.h\&.
.SS "unsigned int json_spirit::Error_position::line_"

.PP
Definition at line 26 of file json_spirit_error_position\&.h\&.
.SS "std::string json_spirit::Error_position::reason_"

.PP
Definition at line 28 of file json_spirit_error_position\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
