.TH "/home/dev/ds-160209/src/json/json_spirit_utils.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/json/json_spirit_utils.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'json_spirit_value\&.h'\fP
.br
\fC#include <map>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBjson_spirit\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::map< std::string, Value > \fBjson_spirit::Mapped_obj\fP"
.br
.ti -1c
.RI "typedef std::map< std::wstring, wValue > \fBjson_spirit::wMapped_obj\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class Obj_t , class Map_t > void \fBjson_spirit::obj_to_map\fP (const Obj_t &obj, Map_t &mp_obj)"
.br
.ti -1c
.RI "template<class Obj_t , class Map_t > void \fBjson_spirit::map_to_obj\fP (const Map_t &mp_obj, Obj_t &obj)"
.br
.ti -1c
.RI "template<class Object_type , class String_type > const Object_type::value_type::Value_type & \fBjson_spirit::find_value\fP (const Object_type &obj, const String_type &\fBname\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
