.TH "json_spirit::Pair_impl< Config >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
json_spirit::Pair_impl< Config > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <json_spirit_value\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBConfig::String_type\fP \fBString_type\fP"
.br
.ti -1c
.RI "typedef \fBConfig::Value_type\fP \fBValue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPair_impl\fP (const \fBString_type\fP &\fBname\fP, const \fBValue_type\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBPair_impl\fP &lhs) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBString_type\fP \fBname_\fP"
.br
.ti -1c
.RI "\fBValue_type\fP \fBvalue_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Config>struct json_spirit::Pair_impl< Config >"

.PP
Definition at line 96 of file json_spirit_value\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class Config> typedef \fBConfig::String_type\fP \fBjson_spirit::Pair_impl\fP< \fBConfig\fP >::\fBString_type\fP"

.PP
Definition at line 98 of file json_spirit_value\&.h\&.
.SS "template<class Config> typedef \fBConfig::Value_type\fP \fBjson_spirit::Pair_impl\fP< \fBConfig\fP >::\fBValue_type\fP"

.PP
Definition at line 99 of file json_spirit_value\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class Config > \fBjson_spirit::Pair_impl\fP< \fBConfig\fP >::\fBPair_impl\fP (const \fBString_type\fP & name, const \fBValue_type\fP & value)"

.PP
Definition at line 439 of file json_spirit_value\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class Config> bool \fBjson_spirit::Pair_impl\fP< \fBConfig\fP >::operator== (const \fBPair_impl\fP< \fBConfig\fP > & lhs) const"

.PP
Definition at line 446 of file json_spirit_value\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class Config> \fBString_type\fP \fBjson_spirit::Pair_impl\fP< \fBConfig\fP >::name_"

.PP
Definition at line 105 of file json_spirit_value\&.h\&.
.SS "template<class Config> \fBValue_type\fP \fBjson_spirit::Pair_impl\fP< \fBConfig\fP >::value_"

.PP
Definition at line 106 of file json_spirit_value\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
