.TH "/home/dev/ds-160209/src/json/json_spirit_writer.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/json/json_spirit_writer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'json_spirit_value\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBjson_spirit\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBjson_spirit::write\fP (const Value &\fBvalue\fP, std::ostream &os)"
.br
.ti -1c
.RI "void \fBjson_spirit::write_formatted\fP (const Value &\fBvalue\fP, std::ostream &os)"
.br
.ti -1c
.RI "std::string \fBjson_spirit::write\fP (const Value &\fBvalue\fP)"
.br
.ti -1c
.RI "std::string \fBjson_spirit::write_formatted\fP (const Value &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBjson_spirit::write\fP (const wValue &\fBvalue\fP, std::wostream &os)"
.br
.ti -1c
.RI "void \fBjson_spirit::write_formatted\fP (const wValue &\fBvalue\fP, std::wostream &os)"
.br
.ti -1c
.RI "void \fBjson_spirit::write\fP (const mValue &\fBvalue\fP, std::ostream &os)"
.br
.ti -1c
.RI "void \fBjson_spirit::write_formatted\fP (const mValue &\fBvalue\fP, std::ostream &os)"
.br
.ti -1c
.RI "std::string \fBjson_spirit::write\fP (const mValue &\fBvalue\fP)"
.br
.ti -1c
.RI "std::string \fBjson_spirit::write_formatted\fP (const mValue &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBjson_spirit::write\fP (const wmValue &\fBvalue\fP, std::wostream &os)"
.br
.ti -1c
.RI "void \fBjson_spirit::write_formatted\fP (const wmValue &\fBvalue\fP, std::wostream &os)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
