.TH "/home/dev/ds-160209/src/kernel.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/kernel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'chain\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBComputeNextStakeModifier\fP (const \fBCBlockIndex\fP *pindexPrev, \fBuint64_t\fP &nStakeModifier, bool &fGeneratedStakeModifier)"
.br
.ti -1c
.RI "\fBuint256\fP \fBComputeStakeModifierV2\fP (const \fBCBlockIndex\fP *pindexPrev, const \fBuint256\fP &kernel)"
.br
.ti -1c
.RI "bool \fBCheckStakeKernelHash\fP (\fBCBlockIndex\fP *pindexPrev, unsigned int nBits, unsigned int nTimeBlockFrom, const \fBCTransaction\fP &txPrev, const \fBCOutPoint\fP &prevout, unsigned int nTimeTx, \fBuint256\fP &hashProofOfStake, \fBuint256\fP &targetProofOfStake, bool fPrintProofOfStake=false)"
.br
.ti -1c
.RI "bool \fBCheckProofOfStake\fP (\fBCBlockIndex\fP *pindexPrev, const \fBCTransaction\fP &tx, unsigned int nBits, \fBuint256\fP &hashProofOfStake, \fBuint256\fP &targetProofOfStake)"
.br
.ti -1c
.RI "bool \fBCheckCoinStakeTimestamp\fP (int nHeight, \fBint64_t\fP nTimeBlock, \fBint64_t\fP nTimeTx)"
.br
.ti -1c
.RI "\fBint64_t\fP \fBGetWeight\fP (\fBint64_t\fP nIntervalBeginning, \fBint64_t\fP nIntervalEnd)"
.br
.ti -1c
.RI "bool \fBCheckKernel\fP (\fBCBlockIndex\fP *pindexPrev, unsigned int nBits, \fBint64_t\fP nTime, const \fBCOutPoint\fP &prevout, \fBint64_t\fP *pBlockTime=NULL)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "unsigned int \fBnModifierInterval\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool CheckCoinStakeTimestamp (int nHeight, \fBint64_t\fP nTimeBlock, \fBint64_t\fP nTimeTx)"

.PP
Definition at line 323 of file kernel\&.cpp\&.
.SS "bool CheckKernel (\fBCBlockIndex\fP * pindexPrev, unsigned int nBits, \fBint64_t\fP nTime, const \fBCOutPoint\fP & prevout, \fBint64_t\fP * pBlockTime = \fCNULL\fP)"

.PP
Definition at line 328 of file kernel\&.cpp\&.
.SS "bool CheckProofOfStake (\fBCBlockIndex\fP * pindexPrev, const \fBCTransaction\fP & tx, unsigned int nBits, \fBuint256\fP & hashProofOfStake, \fBuint256\fP & targetProofOfStake)"

.PP
Definition at line 286 of file kernel\&.cpp\&.
.SS "bool CheckStakeKernelHash (\fBCBlockIndex\fP * pindexPrev, unsigned int nBits, unsigned int nTimeBlockFrom, const \fBCTransaction\fP & txPrev, const \fBCOutPoint\fP & prevout, unsigned int nTimeTx, \fBuint256\fP & hashProofOfStake, \fBuint256\fP & targetProofOfStake, bool fPrintProofOfStake = \fCfalse\fP)"

.PP
Definition at line 227 of file kernel\&.cpp\&.
.SS "bool ComputeNextStakeModifier (const \fBCBlockIndex\fP * pindexPrev, \fBuint64_t\fP & nStakeModifier, bool & fGeneratedStakeModifier)"

.PP
Definition at line 111 of file kernel\&.cpp\&.
.SS "\fBuint256\fP ComputeStakeModifierV2 (const \fBCBlockIndex\fP * pindexPrev, const \fBuint256\fP & kernel)"

.PP
Definition at line 196 of file kernel\&.cpp\&.
.SS "\fBint64_t\fP GetWeight (\fBint64_t\fP nIntervalBeginning, \fBint64_t\fP nIntervalEnd)"

.PP
Definition at line 15 of file kernel\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "unsigned int nModifierInterval"

.PP
Definition at line 64 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
