.TH "/home/dev/ds-160209/src/key.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/key.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'key\&.h'\fP
.br
\fC#include 'crypto/common\&.h'\fP
.br
\fC#include 'crypto/hmac_sha512\&.h'\fP
.br
\fC#include 'pubkey\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include <secp256k1\&.h>\fP
.br
\fC#include <secp256k1_recovery\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBECC_InitSanityCheck\fP ()"
.br
.ti -1c
.RI "void \fBECC_Start\fP ()"
.br
.ti -1c
.RI "void \fBECC_Stop\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool ECC_InitSanityCheck (void)"
Check that required EC support is available at runtime\&. 
.PP
Definition at line 313 of file key\&.cpp\&.
.SS "void ECC_Start (void)"
Initialize the elliptic curve support\&. May not be called twice without calling ECC_Stop first\&. 
.PP
Definition at line 321 of file key\&.cpp\&.
.SS "void ECC_Stop (void)"
Deinitialize the elliptic curve support\&. No-op if ECC_Start wasn't called first\&. 
.PP
Definition at line 340 of file key\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
