.TH "/home/dev/ds-160209/src/keystore.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/keystore.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'key\&.h'\fP
.br
\fC#include 'pubkey\&.h'\fP
.br
\fC#include 'sync\&.h'\fP
.br
\fC#include 'script\&.h'\fP
.br
\fC#include <boost/signals2/signal\&.hpp>\fP
.br
\fC#include <boost/variant\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCKeyStore\fP"
.br
.ti -1c
.RI "class \fBCBasicKeyStore\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef boost::variant< \fBCNoDestination\fP, \fBCKeyID\fP, \fBCScriptID\fP, \fBCStealthAddress\fP > \fBCTxDestination\fP"
.br
.ti -1c
.RI "typedef std::map< \fBCKeyID\fP, \fBCKey\fP > \fBKeyMap\fP"
.br
.ti -1c
.RI "typedef std::map< \fBCScriptID\fP, \fBCScript\fP > \fBScriptMap\fP"
.br
.ti -1c
.RI "typedef std::set< \fBCScript\fP > \fBWatchOnlySet\fP"
.br
.ti -1c
.RI "typedef std::map< \fBCKeyID\fP, std::pair< \fBCPubKey\fP, std::vector< unsigned char > > > \fBCryptedKeyMap\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::map<\fBCKeyID\fP, std::pair<\fBCPubKey\fP, std::vector<unsigned char> > > \fBCryptedKeyMap\fP"

.PP
Definition at line 114 of file keystore\&.h\&.
.SS "typedef boost::variant<\fBCNoDestination\fP, \fBCKeyID\fP, \fBCScriptID\fP, \fBCStealthAddress\fP> \fBCTxDestination\fP"
A txout script template with a specific destination\&. It is either:
.IP "\(bu" 2
\fBCNoDestination\fP: no destination set
.IP "\(bu" 2
\fBCKeyID\fP: TX_PUBKEYHASH destination
.IP "\(bu" 2
\fBCScriptID\fP: TX_SCRIPTHASH destination A CTxDestination is the internal data type encoded in a \fBCDarkSilkAddress\fP 
.PP

.PP
Definition at line 22 of file keystore\&.h\&.
.SS "typedef std::map<\fBCKeyID\fP, \fBCKey\fP> \fBKeyMap\fP"

.PP
Definition at line 55 of file keystore\&.h\&.
.SS "typedef std::map<\fBCScriptID\fP, \fBCScript\fP > \fBScriptMap\fP"

.PP
Definition at line 56 of file keystore\&.h\&.
.SS "typedef std::set<\fBCScript\fP> \fBWatchOnlySet\fP"

.PP
Definition at line 57 of file keystore\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
