.TH "LargerOrEqualThanThreshold" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LargerOrEqualThanThreshold \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLargerOrEqualThanThreshold\fP (\fBCAmount\fP \fBthreshold\fP)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (pair< pair< \fBCAmount\fP, \fBCAmount\fP >, pair< const \fBCWalletTx\fP *, unsigned int > > const &v) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCAmount\fP \fBthreshold\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 70 of file wallet\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LargerOrEqualThanThreshold::LargerOrEqualThanThreshold (\fBCAmount\fP threshold)\fC [inline]\fP"

.PP
Definition at line 73 of file wallet\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool LargerOrEqualThanThreshold::operator() (pair< pair< \fBCAmount\fP, \fBCAmount\fP >, pair< const \fBCWalletTx\fP *, unsigned int > > const & v) const\fC [inline]\fP"

.PP
Definition at line 74 of file wallet\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCAmount\fP LargerOrEqualThanThreshold::threshold"

.PP
Definition at line 72 of file wallet\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
