.TH "leveldb::RandomAccessFile" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::RandomAccessFile \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <env\&.h>\fP
.PP
Inherited by \fBleveldb::StringSource\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandomAccessFile\fP ()"
.br
.ti -1c
.RI "virtual \fB~RandomAccessFile\fP ()"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBRead\fP (\fBuint64_t\fP offset, size_t n, \fBSlice\fP *result, char *scratch) const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 186 of file env\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::RandomAccessFile::RandomAccessFile ()\fC [inline]\fP"

.PP
Definition at line 188 of file env\&.h\&.
.SS "leveldb::RandomAccessFile::~RandomAccessFile ()\fC [virtual]\fP"

.PP
Definition at line 15 of file env\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBStatus\fP leveldb::RandomAccessFile::Read (\fBuint64_t\fP offset, size_t n, \fBSlice\fP * result, char * scratch) const\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::StringSource\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
