.TH "leveldb::LookupKey" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::LookupKey \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dbformat\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLookupKey\fP (const \fBSlice\fP &\fBuser_key\fP, \fBSequenceNumber\fP sequence)"
.br
.ti -1c
.RI "\fB~LookupKey\fP ()"
.br
.ti -1c
.RI "\fBSlice\fP \fBmemtable_key\fP () const "
.br
.ti -1c
.RI "\fBSlice\fP \fBinternal_key\fP () const "
.br
.ti -1c
.RI "\fBSlice\fP \fBuser_key\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 189 of file dbformat\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::LookupKey::LookupKey (const \fBSlice\fP & user_key, \fBSequenceNumber\fP sequence)"

.PP
Definition at line 121 of file dbformat\&.cc\&.
.SS "leveldb::LookupKey::~LookupKey ()\fC [inline]\fP"

.PP
Definition at line 224 of file dbformat\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSlice\fP leveldb::LookupKey::internal_key () const\fC [inline]\fP"

.PP
Definition at line 201 of file dbformat\&.h\&.
.SS "\fBSlice\fP leveldb::LookupKey::memtable_key () const\fC [inline]\fP"

.PP
Definition at line 198 of file dbformat\&.h\&.
.SS "\fBSlice\fP leveldb::LookupKey::user_key () const\fC [inline]\fP"

.PP
Definition at line 204 of file dbformat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
