.TH "leveldb_env_t" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb_env_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEnv\fP * \fBrep\fP"
.br
.ti -1c
.RI "bool \fBis_default\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 127 of file c\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "bool leveldb_env_t::is_default"

.PP
Definition at line 129 of file c\&.cc\&.
.SS "\fBEnv\fP* leveldb_env_t::rep"

.PP
Definition at line 128 of file c\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
