.TH "leveldb::Options" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::Options \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <options\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptions\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBComparator\fP * \fBcomparator\fP"
.br
.ti -1c
.RI "bool \fBcreate_if_missing\fP"
.br
.ti -1c
.RI "bool \fBerror_if_exists\fP"
.br
.ti -1c
.RI "bool \fBparanoid_checks\fP"
.br
.ti -1c
.RI "\fBEnv\fP * \fBenv\fP"
.br
.ti -1c
.RI "\fBLogger\fP * \fBinfo_log\fP"
.br
.ti -1c
.RI "size_t \fBwrite_buffer_size\fP"
.br
.ti -1c
.RI "int \fBmax_open_files\fP"
.br
.ti -1c
.RI "\fBCache\fP * \fBblock_cache\fP"
.br
.ti -1c
.RI "size_t \fBblock_size\fP"
.br
.ti -1c
.RI "int \fBblock_restart_interval\fP"
.br
.ti -1c
.RI "\fBCompressionType\fP \fBcompression\fP"
.br
.ti -1c
.RI "const \fBFilterPolicy\fP * \fBfilter_policy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file options\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::Options::Options ()"

.PP
Definition at line 12 of file options\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCache\fP* leveldb::Options::block_cache"

.PP
Definition at line 98 of file options\&.h\&.
.SS "int leveldb::Options::block_restart_interval"

.PP
Definition at line 113 of file options\&.h\&.
.SS "size_t leveldb::Options::block_size"

.PP
Definition at line 106 of file options\&.h\&.
.SS "const \fBComparator\fP* leveldb::Options::comparator"

.PP
Definition at line 41 of file options\&.h\&.
.SS "\fBCompressionType\fP leveldb::Options::compression"

.PP
Definition at line 129 of file options\&.h\&.
.SS "bool leveldb::Options::create_if_missing"

.PP
Definition at line 45 of file options\&.h\&.
.SS "\fBEnv\fP* leveldb::Options::env"

.PP
Definition at line 62 of file options\&.h\&.
.SS "bool leveldb::Options::error_if_exists"

.PP
Definition at line 49 of file options\&.h\&.
.SS "const \fBFilterPolicy\fP* leveldb::Options::filter_policy"

.PP
Definition at line 136 of file options\&.h\&.
.SS "\fBLogger\fP* leveldb::Options::info_log"

.PP
Definition at line 68 of file options\&.h\&.
.SS "int leveldb::Options::max_open_files"

.PP
Definition at line 90 of file options\&.h\&.
.SS "bool leveldb::Options::paranoid_checks"

.PP
Definition at line 57 of file options\&.h\&.
.SS "size_t leveldb::Options::write_buffer_size"

.PP
Definition at line 83 of file options\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
