.TH "leveldb::WriteBatchInternal" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::WriteBatchInternal \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <write_batch_internal\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBCount\fP (const \fBWriteBatch\fP *batch)"
.br
.ti -1c
.RI "static void \fBSetCount\fP (\fBWriteBatch\fP *batch, int n)"
.br
.ti -1c
.RI "static \fBSequenceNumber\fP \fBSequence\fP (const \fBWriteBatch\fP *batch)"
.br
.ti -1c
.RI "static void \fBSetSequence\fP (\fBWriteBatch\fP *batch, \fBSequenceNumber\fP seq)"
.br
.ti -1c
.RI "static \fBSlice\fP \fBContents\fP (const \fBWriteBatch\fP *batch)"
.br
.ti -1c
.RI "static size_t \fBByteSize\fP (const \fBWriteBatch\fP *batch)"
.br
.ti -1c
.RI "static void \fBSetContents\fP (\fBWriteBatch\fP *batch, const \fBSlice\fP &contents)"
.br
.ti -1c
.RI "static \fBStatus\fP \fBInsertInto\fP (const \fBWriteBatch\fP *batch, \fBMemTable\fP *memtable)"
.br
.ti -1c
.RI "static void \fBAppend\fP (\fBWriteBatch\fP *dst, const \fBWriteBatch\fP *src)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file write_batch_internal\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::WriteBatchInternal::Append (\fBWriteBatch\fP * dst, const \fBWriteBatch\fP * src)\fC [static]\fP"

.PP
Definition at line 141 of file write_batch\&.cc\&.
.SS "static size_t leveldb::WriteBatchInternal::ByteSize (const \fBWriteBatch\fP * batch)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 35 of file write_batch_internal\&.h\&.
.SS "static \fBSlice\fP leveldb::WriteBatchInternal::Contents (const \fBWriteBatch\fP * batch)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 31 of file write_batch_internal\&.h\&.
.SS "int leveldb::WriteBatchInternal::Count (const \fBWriteBatch\fP * batch)\fC [static]\fP"

.PP
Definition at line 82 of file write_batch\&.cc\&.
.SS "\fBStatus\fP leveldb::WriteBatchInternal::InsertInto (const \fBWriteBatch\fP * batch, \fBMemTable\fP * memtable)\fC [static]\fP"

.PP
Definition at line 128 of file write_batch\&.cc\&.
.SS "\fBSequenceNumber\fP leveldb::WriteBatchInternal::Sequence (const \fBWriteBatch\fP * batch)\fC [static]\fP"

.PP
Definition at line 90 of file write_batch\&.cc\&.
.SS "void leveldb::WriteBatchInternal::SetContents (\fBWriteBatch\fP * batch, const \fBSlice\fP & contents)\fC [static]\fP"

.PP
Definition at line 136 of file write_batch\&.cc\&.
.SS "void leveldb::WriteBatchInternal::SetCount (\fBWriteBatch\fP * batch, int n)\fC [static]\fP"

.PP
Definition at line 86 of file write_batch\&.cc\&.
.SS "void leveldb::WriteBatchInternal::SetSequence (\fBWriteBatch\fP * batch, \fBSequenceNumber\fP seq)\fC [static]\fP"

.PP
Definition at line 94 of file write_batch\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
