.TH "leveldb::ParsedInternalKey" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::ParsedInternalKey \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dbformat\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParsedInternalKey\fP ()"
.br
.ti -1c
.RI "\fBParsedInternalKey\fP (const \fBSlice\fP &u, const \fBSequenceNumber\fP &seq, \fBValueType\fP t)"
.br
.ti -1c
.RI "std::string \fBDebugString\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSlice\fP \fBuser_key\fP"
.br
.ti -1c
.RI "\fBSequenceNumber\fP \fBsequence\fP"
.br
.ti -1c
.RI "\fBValueType\fP \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 70 of file dbformat\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::ParsedInternalKey::ParsedInternalKey ()\fC [inline]\fP"

.PP
Definition at line 75 of file dbformat\&.h\&.
.SS "leveldb::ParsedInternalKey::ParsedInternalKey (const \fBSlice\fP & u, const \fBSequenceNumber\fP & seq, \fBValueType\fP t)\fC [inline]\fP"

.PP
Definition at line 76 of file dbformat\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string leveldb::ParsedInternalKey::DebugString () const"

.PP
Definition at line 23 of file dbformat\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSequenceNumber\fP leveldb::ParsedInternalKey::sequence"

.PP
Definition at line 72 of file dbformat\&.h\&.
.SS "\fBValueType\fP leveldb::ParsedInternalKey::type"

.PP
Definition at line 73 of file dbformat\&.h\&.
.SS "\fBSlice\fP leveldb::ParsedInternalKey::user_key"

.PP
Definition at line 71 of file dbformat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
