.TH "leveldb::InternalKey" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::InternalKey \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dbformat\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInternalKey\fP ()"
.br
.ti -1c
.RI "\fBInternalKey\fP (const \fBSlice\fP &\fBuser_key\fP, \fBSequenceNumber\fP s, \fBValueType\fP t)"
.br
.ti -1c
.RI "void \fBDecodeFrom\fP (const \fBSlice\fP &s)"
.br
.ti -1c
.RI "\fBSlice\fP \fBEncode\fP () const "
.br
.ti -1c
.RI "\fBSlice\fP \fBuser_key\fP () const "
.br
.ti -1c
.RI "void \fBSetFrom\fP (const \fBParsedInternalKey\fP &p)"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "std::string \fBDebugString\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 144 of file dbformat\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::InternalKey::InternalKey ()\fC [inline]\fP"

.PP
Definition at line 148 of file dbformat\&.h\&.
.SS "leveldb::InternalKey::InternalKey (const \fBSlice\fP & user_key, \fBSequenceNumber\fP s, \fBValueType\fP t)\fC [inline]\fP"

.PP
Definition at line 149 of file dbformat\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::InternalKey::Clear ()\fC [inline]\fP"

.PP
Definition at line 166 of file dbformat\&.h\&.
.SS "std::string leveldb::InternalKey::DebugString () const"

.PP
Definition at line 34 of file dbformat\&.cc\&.
.SS "void leveldb::InternalKey::DecodeFrom (const \fBSlice\fP & s)\fC [inline]\fP"

.PP
Definition at line 153 of file dbformat\&.h\&.
.SS "\fBSlice\fP leveldb::InternalKey::Encode () const\fC [inline]\fP"

.PP
Definition at line 154 of file dbformat\&.h\&.
.SS "void leveldb::InternalKey::SetFrom (const \fBParsedInternalKey\fP & p)\fC [inline]\fP"

.PP
Definition at line 161 of file dbformat\&.h\&.
.SS "\fBSlice\fP leveldb::InternalKey::user_key () const\fC [inline]\fP"

.PP
Definition at line 159 of file dbformat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
