.TH "leveldb::FindFileTest" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::FindFileTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFindFileTest\fP ()"
.br
.ti -1c
.RI "\fB~FindFileTest\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (const char *smallest, const char *largest, \fBSequenceNumber\fP smallest_seq=100, \fBSequenceNumber\fP largest_seq=100)"
.br
.ti -1c
.RI "int \fBFind\fP (const char *key)"
.br
.ti -1c
.RI "bool \fBOverlaps\fP (const char *smallest, const char *largest)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBFileMetaData\fP * > \fBfiles_\fP"
.br
.ti -1c
.RI "bool \fBdisjoint_sorted_files_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file version_set_test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::FindFileTest::FindFileTest ()\fC [inline]\fP"

.PP
Definition at line 17 of file version_set_test\&.cc\&.
.SS "leveldb::FindFileTest::~FindFileTest ()\fC [inline]\fP"

.PP
Definition at line 19 of file version_set_test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::FindFileTest::Add (const char * smallest, const char * largest, \fBSequenceNumber\fP smallest_seq = \fC100\fP, \fBSequenceNumber\fP largest_seq = \fC100\fP)\fC [inline]\fP"

.PP
Definition at line 25 of file version_set_test\&.cc\&.
.SS "int leveldb::FindFileTest::Find (const char * key)\fC [inline]\fP"

.PP
Definition at line 35 of file version_set_test\&.cc\&.
.SS "bool leveldb::FindFileTest::Overlaps (const char * smallest, const char * largest)\fC [inline]\fP"

.PP
Definition at line 41 of file version_set_test\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "bool leveldb::FindFileTest::disjoint_sorted_files_"

.PP
Definition at line 15 of file version_set_test\&.cc\&.
.SS "std::vector<\fBFileMetaData\fP*> leveldb::FindFileTest::files_"

.PP
Definition at line 14 of file version_set_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
