.TH "leveldb::SkipList< Key, Comparator >::Node" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::SkipList< Key, Comparator >::Node \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <skiplist\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP (const \fBKey\fP &k)"
.br
.ti -1c
.RI "\fBNode\fP * \fBNext\fP (int n)"
.br
.ti -1c
.RI "void \fBSetNext\fP (int n, \fBNode\fP *x)"
.br
.ti -1c
.RI "\fBNode\fP * \fBNoBarrier_Next\fP (int n)"
.br
.ti -1c
.RI "void \fBNoBarrier_SetNext\fP (int n, \fBNode\fP *x)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKey\fP const \fBkey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Key, class Comparator>struct leveldb::SkipList< Key, Comparator >::Node"

.PP
Definition at line 147 of file skiplist\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Key, class Comparator> \fBleveldb::SkipList\fP< \fBKey\fP, \fBComparator\fP >::Node::Node (const \fBKey\fP & k)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 148 of file skiplist\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Key, class Comparator> \fBNode\fP* \fBleveldb::SkipList\fP< \fBKey\fP, \fBComparator\fP >::Node::Next (int n)\fC [inline]\fP"

.PP
Definition at line 154 of file skiplist\&.h\&.
.SS "template<typename Key, class Comparator> \fBNode\fP* \fBleveldb::SkipList\fP< \fBKey\fP, \fBComparator\fP >::Node::NoBarrier_Next (int n)\fC [inline]\fP"

.PP
Definition at line 168 of file skiplist\&.h\&.
.SS "template<typename Key, class Comparator> void \fBleveldb::SkipList\fP< \fBKey\fP, \fBComparator\fP >::Node::NoBarrier_SetNext (int n, \fBNode\fP * x)\fC [inline]\fP"

.PP
Definition at line 172 of file skiplist\&.h\&.
.SS "template<typename Key, class Comparator> void \fBleveldb::SkipList\fP< \fBKey\fP, \fBComparator\fP >::Node::SetNext (int n, \fBNode\fP * x)\fC [inline]\fP"

.PP
Definition at line 160 of file skiplist\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename Key, class Comparator> \fBKey\fP const \fBleveldb::SkipList\fP< \fBKey\fP, \fBComparator\fP >::Node::key"

.PP
Definition at line 150 of file skiplist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
