.TH "leveldb::DBImpl::CompactionState" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::DBImpl::CompactionState \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBOutput\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOutput\fP * \fBcurrent_output\fP ()"
.br
.ti -1c
.RI "\fBCompactionState\fP (\fBCompaction\fP *c)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCompaction\fP *const \fBcompaction\fP"
.br
.ti -1c
.RI "\fBSequenceNumber\fP \fBsmallest_snapshot\fP"
.br
.ti -1c
.RI "std::vector< \fBOutput\fP > \fBoutputs\fP"
.br
.ti -1c
.RI "\fBWritableFile\fP * \fBoutfile\fP"
.br
.ti -1c
.RI "\fBTableBuilder\fP * \fBbuilder\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBtotal_bytes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file db_impl\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::DBImpl::CompactionState::CompactionState (\fBCompaction\fP * c)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 76 of file db_impl\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBOutput\fP* leveldb::DBImpl::CompactionState::current_output ()\fC [inline]\fP"

.PP
Definition at line 74 of file db_impl\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTableBuilder\fP* leveldb::DBImpl::CompactionState::builder"

.PP
Definition at line 70 of file db_impl\&.cc\&.
.SS "\fBCompaction\fP* const leveldb::DBImpl::CompactionState::compaction"

.PP
Definition at line 52 of file db_impl\&.cc\&.
.SS "\fBWritableFile\fP* leveldb::DBImpl::CompactionState::outfile"

.PP
Definition at line 69 of file db_impl\&.cc\&.
.SS "std::vector<\fBOutput\fP> leveldb::DBImpl::CompactionState::outputs"

.PP
Definition at line 66 of file db_impl\&.cc\&.
.SS "\fBSequenceNumber\fP leveldb::DBImpl::CompactionState::smallest_snapshot"

.PP
Definition at line 58 of file db_impl\&.cc\&.
.SS "\fBuint64_t\fP leveldb::DBImpl::CompactionState::total_bytes"

.PP
Definition at line 72 of file db_impl\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
