.TH "leveldb::SequentialFile" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::SequentialFile \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <env\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSequentialFile\fP ()"
.br
.ti -1c
.RI "virtual \fB~SequentialFile\fP ()"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBRead\fP (size_t n, \fBSlice\fP *result, char *scratch)=0"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBSkip\fP (\fBuint64_t\fP n)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 155 of file env\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::SequentialFile::SequentialFile ()\fC [inline]\fP"

.PP
Definition at line 157 of file env\&.h\&.
.SS "leveldb::SequentialFile::~SequentialFile ()\fC [virtual]\fP"

.PP
Definition at line 12 of file env\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBStatus\fP leveldb::SequentialFile::Read (size_t n, \fBSlice\fP * result, char * scratch)\fC [pure virtual]\fP"

.SS "virtual \fBStatus\fP leveldb::SequentialFile::Skip (\fBuint64_t\fP n)\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
