.TH "leveldb::KeyConvertingIterator" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::KeyConvertingIterator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBleveldb::Iterator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyConvertingIterator\fP (\fBIterator\fP *iter)"
.br
.ti -1c
.RI "virtual \fB~KeyConvertingIterator\fP ()"
.br
.ti -1c
.RI "virtual bool \fBValid\fP () const "
.br
.ti -1c
.RI "virtual void \fBSeek\fP (const \fBSlice\fP &target)"
.br
.ti -1c
.RI "virtual void \fBSeekToFirst\fP ()"
.br
.ti -1c
.RI "virtual void \fBSeekToLast\fP ()"
.br
.ti -1c
.RI "virtual void \fBNext\fP ()"
.br
.ti -1c
.RI "virtual void \fBPrev\fP ()"
.br
.ti -1c
.RI "virtual \fBSlice\fP \fBkey\fP () const "
.br
.ti -1c
.RI "virtual \fBSlice\fP \fBvalue\fP () const "
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBstatus\fP () const "
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 276 of file table_test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::KeyConvertingIterator::KeyConvertingIterator (\fBIterator\fP * iter)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 278 of file table_test\&.cc\&.
.SS "virtual leveldb::KeyConvertingIterator::~KeyConvertingIterator ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 279 of file table_test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBSlice\fP leveldb::KeyConvertingIterator::key () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 292 of file table_test\&.cc\&.
.SS "virtual void leveldb::KeyConvertingIterator::Next ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 289 of file table_test\&.cc\&.
.SS "virtual void leveldb::KeyConvertingIterator::Prev ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 290 of file table_test\&.cc\&.
.SS "virtual void leveldb::KeyConvertingIterator::Seek (const \fBSlice\fP & target)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 281 of file table_test\&.cc\&.
.SS "virtual void leveldb::KeyConvertingIterator::SeekToFirst ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 287 of file table_test\&.cc\&.
.SS "virtual void leveldb::KeyConvertingIterator::SeekToLast ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 288 of file table_test\&.cc\&.
.SS "virtual \fBStatus\fP leveldb::KeyConvertingIterator::status () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 303 of file table_test\&.cc\&.
.SS "virtual bool leveldb::KeyConvertingIterator::Valid () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 280 of file table_test\&.cc\&.
.SS "virtual \fBSlice\fP leveldb::KeyConvertingIterator::value () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 302 of file table_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
