.TH "leveldb::InternalFilterPolicy" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::InternalFilterPolicy \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dbformat\&.h>\fP
.PP
Inherits \fBleveldb::FilterPolicy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInternalFilterPolicy\fP (const \fBFilterPolicy\fP *p)"
.br
.ti -1c
.RI "virtual const char * \fBName\fP () const "
.br
.ti -1c
.RI "virtual void \fBCreateFilter\fP (const \fBSlice\fP *keys, int n, std::string *dst) const "
.br
.ti -1c
.RI "virtual bool \fBKeyMayMatch\fP (const \fBSlice\fP &key, const \fBSlice\fP &filter) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 131 of file dbformat\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::InternalFilterPolicy::InternalFilterPolicy (const \fBFilterPolicy\fP * p)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 135 of file dbformat\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::InternalFilterPolicy::CreateFilter (const \fBSlice\fP * keys, int n, std::string * dst) const\fC [virtual]\fP"

.PP
Implements \fBleveldb::FilterPolicy\fP\&.
.PP
Definition at line 105 of file dbformat\&.cc\&.
.SS "bool leveldb::InternalFilterPolicy::KeyMayMatch (const \fBSlice\fP & key, const \fBSlice\fP & filter) const\fC [virtual]\fP"

.PP
Implements \fBleveldb::FilterPolicy\fP\&.
.PP
Definition at line 117 of file dbformat\&.cc\&.
.SS "const char * leveldb::InternalFilterPolicy::Name () const\fC [virtual]\fP"

.PP
Implements \fBleveldb::FilterPolicy\fP\&.
.PP
Definition at line 101 of file dbformat\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
