.TH "leveldb::test" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::test \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBErrorEnv\fP"
.br
.ti -1c
.RI "class \fBTester\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBRegisterTest\fP (const char *\fBbase\fP, const char *\fBname\fP, void(*\fBfunc\fP)())"
.br
.ti -1c
.RI "int \fBRunAllTests\fP ()"
.br
.ti -1c
.RI "std::string \fBTmpDir\fP ()"
.br
.ti -1c
.RI "int \fBRandomSeed\fP ()"
.br
.ti -1c
.RI "\fBSlice\fP \fBRandomString\fP (\fBRandom\fP *rnd, int len, std::string *dst)"
.br
.ti -1c
.RI "std::string \fBRandomKey\fP (\fBRandom\fP *rnd, int len)"
.br
.ti -1c
.RI "\fBSlice\fP \fBCompressibleString\fP (\fBRandom\fP *rnd, double compressed_fraction, size_t len, std::string *dst)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBSlice\fP leveldb::test::CompressibleString (\fBRandom\fP * rnd, double compressed_fraction, size_t len, std::string * dst)"

.PP
Definition at line 34 of file testutil\&.cc\&.
.SS "std::string leveldb::test::RandomKey (\fBRandom\fP * rnd, int len)"

.PP
Definition at line 20 of file testutil\&.cc\&.
.SS "int leveldb::test::RandomSeed ()"

.PP
Definition at line 67 of file testharness\&.cc\&.
.SS "\fBSlice\fP leveldb::test::RandomString (\fBRandom\fP * rnd, int len, std::string * dst)"

.PP
Definition at line 12 of file testutil\&.cc\&.
.SS "bool leveldb::test::RegisterTest (const char * base, const char * name, void(*)() func)"

.PP
Definition at line 24 of file testharness\&.cc\&.
.SS "int leveldb::test::RunAllTests ()"

.PP
Definition at line 36 of file testharness\&.cc\&.
.SS "std::string leveldb::test::TmpDir ()"

.PP
Definition at line 60 of file testharness\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
