.TH "leveldb::Compaction" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::Compaction \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <version_set\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~Compaction\fP ()"
.br
.ti -1c
.RI "int \fBlevel\fP () const "
.br
.ti -1c
.RI "\fBVersionEdit\fP * \fBedit\fP ()"
.br
.ti -1c
.RI "int \fBnum_input_files\fP (int which) const "
.br
.ti -1c
.RI "\fBFileMetaData\fP * \fBinput\fP (int which, int i) const "
.br
.ti -1c
.RI "\fBuint64_t\fP \fBMaxOutputFileSize\fP () const "
.br
.ti -1c
.RI "bool \fBIsTrivialMove\fP () const "
.br
.ti -1c
.RI "void \fBAddInputDeletions\fP (\fBVersionEdit\fP *\fBedit\fP)"
.br
.ti -1c
.RI "bool \fBIsBaseLevelForKey\fP (const \fBSlice\fP &\fBuser_key\fP)"
.br
.ti -1c
.RI "bool \fBShouldStopBefore\fP (const \fBSlice\fP &internal_key)"
.br
.ti -1c
.RI "void \fBReleaseInputs\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBVersion\fP"
.br
.ti -1c
.RI "class \fBVersionSet\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 322 of file version_set\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::Compaction::~Compaction ()"

.PP
Definition at line 1411 of file version_set\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::Compaction::AddInputDeletions (\fBVersionEdit\fP * edit)"

.PP
Definition at line 1426 of file version_set\&.cc\&.
.SS "\fBVersionEdit\fP* leveldb::Compaction::edit ()\fC [inline]\fP"

.PP
Definition at line 332 of file version_set\&.h\&.
.SS "\fBFileMetaData\fP* leveldb::Compaction::input (int which, int i) const\fC [inline]\fP"

.PP
Definition at line 338 of file version_set\&.h\&.
.SS "bool leveldb::Compaction::IsBaseLevelForKey (const \fBSlice\fP & user_key)"

.PP
Definition at line 1434 of file version_set\&.cc\&.
.SS "bool leveldb::Compaction::IsTrivialMove () const"

.PP
Definition at line 1417 of file version_set\&.cc\&.
.SS "int leveldb::Compaction::level () const\fC [inline]\fP"

.PP
Definition at line 328 of file version_set\&.h\&.
.SS "\fBuint64_t\fP leveldb::Compaction::MaxOutputFileSize () const\fC [inline]\fP"

.PP
Definition at line 341 of file version_set\&.h\&.
.SS "int leveldb::Compaction::num_input_files (int which) const\fC [inline]\fP"

.PP
Definition at line 335 of file version_set\&.h\&.
.SS "void leveldb::Compaction::ReleaseInputs ()"

.PP
Definition at line 1477 of file version_set\&.cc\&.
.SS "bool leveldb::Compaction::ShouldStopBefore (const \fBSlice\fP & internal_key)"

.PP
Definition at line 1455 of file version_set\&.cc\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBVersion\fP\fC [friend]\fP"

.PP
Definition at line 364 of file version_set\&.h\&.
.SS "friend class \fBVersionSet\fP\fC [friend]\fP"

.PP
Definition at line 365 of file version_set\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
