.TH "leveldb::Status" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::Status \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <status\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStatus\fP ()"
.br
.ti -1c
.RI "\fB~Status\fP ()"
.br
.ti -1c
.RI "\fBStatus\fP (const \fBStatus\fP &s)"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBStatus\fP &s)"
.br
.ti -1c
.RI "bool \fBok\fP () const "
.br
.ti -1c
.RI "bool \fBIsNotFound\fP () const "
.br
.ti -1c
.RI "bool \fBIsCorruption\fP () const "
.br
.ti -1c
.RI "bool \fBIsIOError\fP () const "
.br
.ti -1c
.RI "std::string \fBToString\fP () const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBStatus\fP \fBOK\fP ()"
.br
.ti -1c
.RI "static \fBStatus\fP \fBNotFound\fP (const \fBSlice\fP &msg, const \fBSlice\fP &msg2=\fBSlice\fP())"
.br
.ti -1c
.RI "static \fBStatus\fP \fBCorruption\fP (const \fBSlice\fP &msg, const \fBSlice\fP &msg2=\fBSlice\fP())"
.br
.ti -1c
.RI "static \fBStatus\fP \fBNotSupported\fP (const \fBSlice\fP &msg, const \fBSlice\fP &msg2=\fBSlice\fP())"
.br
.ti -1c
.RI "static \fBStatus\fP \fBInvalidArgument\fP (const \fBSlice\fP &msg, const \fBSlice\fP &msg2=\fBSlice\fP())"
.br
.ti -1c
.RI "static \fBStatus\fP \fBIOError\fP (const \fBSlice\fP &msg, const \fBSlice\fP &msg2=\fBSlice\fP())"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file status\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::Status::Status ()\fC [inline]\fP"

.PP
Definition at line 24 of file status\&.h\&.
.SS "leveldb::Status::~Status ()\fC [inline]\fP"

.PP
Definition at line 25 of file status\&.h\&.
.SS "leveldb::Status::Status (const \fBStatus\fP & s)\fC [inline]\fP"

.PP
Definition at line 92 of file status\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBStatus\fP leveldb::Status::Corruption (const \fBSlice\fP & msg, const \fBSlice\fP & msg2 = \fC\fBSlice\fP()\fP)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 38 of file status\&.h\&.
.SS "static \fBStatus\fP leveldb::Status::InvalidArgument (const \fBSlice\fP & msg, const \fBSlice\fP & msg2 = \fC\fBSlice\fP()\fP)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 44 of file status\&.h\&.
.SS "static \fBStatus\fP leveldb::Status::IOError (const \fBSlice\fP & msg, const \fBSlice\fP & msg2 = \fC\fBSlice\fP()\fP)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 47 of file status\&.h\&.
.SS "bool leveldb::Status::IsCorruption () const\fC [inline]\fP"

.PP
Definition at line 58 of file status\&.h\&.
.SS "bool leveldb::Status::IsIOError () const\fC [inline]\fP"

.PP
Definition at line 61 of file status\&.h\&.
.SS "bool leveldb::Status::IsNotFound () const\fC [inline]\fP"

.PP
Definition at line 55 of file status\&.h\&.
.SS "static \fBStatus\fP leveldb::Status::NotFound (const \fBSlice\fP & msg, const \fBSlice\fP & msg2 = \fC\fBSlice\fP()\fP)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 35 of file status\&.h\&.
.SS "static \fBStatus\fP leveldb::Status::NotSupported (const \fBSlice\fP & msg, const \fBSlice\fP & msg2 = \fC\fBSlice\fP()\fP)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 41 of file status\&.h\&.
.SS "static \fBStatus\fP leveldb::Status::OK ()\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 32 of file status\&.h\&.
.SS "bool leveldb::Status::ok () const\fC [inline]\fP"

.PP
Definition at line 52 of file status\&.h\&.
.SS "void leveldb::Status::operator= (const \fBStatus\fP & s)\fC [inline]\fP"

.PP
Definition at line 95 of file status\&.h\&.
.SS "std::string leveldb::Status::ToString () const"

.PP
Definition at line 36 of file status\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
