.TH "leveldb::WriteOptions" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::WriteOptions \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <options\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWriteOptions\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBsync\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 169 of file options\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::WriteOptions::WriteOptions ()\fC [inline]\fP"

.PP
Definition at line 188 of file options\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool leveldb::WriteOptions::sync"

.PP
Definition at line 186 of file options\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
