.TH "leveldb::MutexLock" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::MutexLock \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mutexlock\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMutexLock\fP (\fBport::Mutex\fP *\fBmu\fP) \fBEXCLUSIVE_LOCK_FUNCTION\fP(\fBmu\fP)"
.br
.ti -1c
.RI "\fB~MutexLock\fP () \fBUNLOCK_FUNCTION\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file mutexlock\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::MutexLock::MutexLock (\fBport::Mutex\fP * mu)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 25 of file mutexlock\&.h\&.
.SS "leveldb::MutexLock::~MutexLock ()\fC [inline]\fP"

.PP
Definition at line 29 of file mutexlock\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
