.TH "leveldb::State" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::State \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBport::Mutex\fP \fBmu\fP"
.br
.ti -1c
.RI "int \fBval\fP"
.br
.ti -1c
.RI "int \fBnum_running\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 67 of file env_test\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBport::Mutex\fP leveldb::State::mu"

.PP
Definition at line 68 of file env_test\&.cc\&.
.SS "int leveldb::State::num_running"

.PP
Definition at line 70 of file env_test\&.cc\&.
.SS "int leveldb::State::val"

.PP
Definition at line 69 of file env_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
