.TH "leveldb::TestArgs" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::TestArgs \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTestType\fP \fBtype\fP"
.br
.ti -1c
.RI "bool \fBreverse_compare\fP"
.br
.ti -1c
.RI "int \fBrestart_interval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 406 of file table_test\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "int leveldb::TestArgs::restart_interval"

.PP
Definition at line 409 of file table_test\&.cc\&.
.SS "bool leveldb::TestArgs::reverse_compare"

.PP
Definition at line 408 of file table_test\&.cc\&.
.SS "\fBTestType\fP leveldb::TestArgs::type"

.PP
Definition at line 407 of file table_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
