.TH "leveldb::AutoCompactTest" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::AutoCompactTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAutoCompactTest\fP ()"
.br
.ti -1c
.RI "\fB~AutoCompactTest\fP ()"
.br
.ti -1c
.RI "std::string \fBKey\fP (int i)"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBSize\fP (const \fBSlice\fP &\fBstart\fP, const \fBSlice\fP &limit)"
.br
.ti -1c
.RI "void \fBDoReads\fP (int n)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBdbname_\fP"
.br
.ti -1c
.RI "\fBCache\fP * \fBtiny_cache_\fP"
.br
.ti -1c
.RI "\fBOptions\fP \fBoptions_\fP"
.br
.ti -1c
.RI "\fBDB\fP * \fBdb_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file autocompact_test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::AutoCompactTest::AutoCompactTest ()\fC [inline]\fP"

.PP
Definition at line 20 of file autocompact_test\&.cc\&.
.SS "leveldb::AutoCompactTest::~AutoCompactTest ()\fC [inline]\fP"

.PP
Definition at line 30 of file autocompact_test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::AutoCompactTest::DoReads (int n)"

.PP
Definition at line 58 of file autocompact_test\&.cc\&.
.SS "std::string leveldb::AutoCompactTest::Key (int i)\fC [inline]\fP"

.PP
Definition at line 36 of file autocompact_test\&.cc\&.
.SS "\fBuint64_t\fP leveldb::AutoCompactTest::Size (const \fBSlice\fP & start, const \fBSlice\fP & limit)\fC [inline]\fP"

.PP
Definition at line 42 of file autocompact_test\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDB\fP* leveldb::AutoCompactTest::db_"

.PP
Definition at line 18 of file autocompact_test\&.cc\&.
.SS "std::string leveldb::AutoCompactTest::dbname_"

.PP
Definition at line 15 of file autocompact_test\&.cc\&.
.SS "\fBOptions\fP leveldb::AutoCompactTest::options_"

.PP
Definition at line 17 of file autocompact_test\&.cc\&.
.SS "\fBCache\fP* leveldb::AutoCompactTest::tiny_cache_"

.PP
Definition at line 16 of file autocompact_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
