.TH "leveldb::BlockConstructor" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::BlockConstructor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBleveldb::Constructor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockConstructor\fP (const \fBComparator\fP *\fBcmp\fP)"
.br
.ti -1c
.RI "\fB~BlockConstructor\fP ()"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBFinishImpl\fP (const \fBOptions\fP &options, const \fBKVMap\fP &\fBdata\fP)"
.br
.ti -1c
.RI "virtual \fBIterator\fP * \fBNewIterator\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 181 of file table_test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::BlockConstructor::BlockConstructor (const \fBComparator\fP * cmp)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 183 of file table_test\&.cc\&.
.SS "leveldb::BlockConstructor::~BlockConstructor ()\fC [inline]\fP"

.PP
Definition at line 187 of file table_test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBStatus\fP leveldb::BlockConstructor::FinishImpl (const \fBOptions\fP & options, const \fBKVMap\fP & data)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Constructor\fP\&.
.PP
Definition at line 190 of file table_test\&.cc\&.
.SS "virtual \fBIterator\fP* leveldb::BlockConstructor::NewIterator () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Constructor\fP\&.
.PP
Definition at line 209 of file table_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
