.TH "leveldb::CorruptionTest" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::CorruptionTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCorruptionTest\fP ()"
.br
.ti -1c
.RI "\fB~CorruptionTest\fP ()"
.br
.ti -1c
.RI "\fBStatus\fP \fBTryReopen\fP ()"
.br
.ti -1c
.RI "void \fBReopen\fP ()"
.br
.ti -1c
.RI "void \fBRepairDB\fP ()"
.br
.ti -1c
.RI "void \fBBuild\fP (int n)"
.br
.ti -1c
.RI "void \fBCheck\fP (int min_expected, int max_expected)"
.br
.ti -1c
.RI "void \fBCorrupt\fP (\fBFileType\fP filetype, int offset, int bytes_to_corrupt)"
.br
.ti -1c
.RI "int \fBProperty\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "\fBSlice\fP \fBKey\fP (int i, std::string *storage)"
.br
.ti -1c
.RI "\fBSlice\fP \fBValue\fP (int k, std::string *storage)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtest::ErrorEnv\fP \fBenv_\fP"
.br
.ti -1c
.RI "std::string \fBdbname_\fP"
.br
.ti -1c
.RI "\fBCache\fP * \fBtiny_cache_\fP"
.br
.ti -1c
.RI "\fBOptions\fP \fBoptions_\fP"
.br
.ti -1c
.RI "\fBDB\fP * \fBdb_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file corruption_test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::CorruptionTest::CorruptionTest ()\fC [inline]\fP"

.PP
Definition at line 35 of file corruption_test\&.cc\&.
.SS "leveldb::CorruptionTest::~CorruptionTest ()\fC [inline]\fP"

.PP
Definition at line 48 of file corruption_test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::CorruptionTest::Build (int n)\fC [inline]\fP"

.PP
Definition at line 70 of file corruption_test\&.cc\&.
.SS "void leveldb::CorruptionTest::Check (int min_expected, int max_expected)\fC [inline]\fP"

.PP
Definition at line 88 of file corruption_test\&.cc\&.
.SS "void leveldb::CorruptionTest::Corrupt (\fBFileType\fP filetype, int offset, int bytes_to_corrupt)\fC [inline]\fP"

.PP
Definition at line 126 of file corruption_test\&.cc\&.
.SS "\fBSlice\fP leveldb::CorruptionTest::Key (int i, std::string * storage)\fC [inline]\fP"

.PP
Definition at line 188 of file corruption_test\&.cc\&.
.SS "int leveldb::CorruptionTest::Property (const std::string & name)\fC [inline]\fP"

.PP
Definition at line 176 of file corruption_test\&.cc\&.
.SS "void leveldb::CorruptionTest::Reopen ()\fC [inline]\fP"

.PP
Definition at line 60 of file corruption_test\&.cc\&.
.SS "void leveldb::CorruptionTest::RepairDB ()\fC [inline]\fP"

.PP
Definition at line 64 of file corruption_test\&.cc\&.
.SS "\fBStatus\fP leveldb::CorruptionTest::TryReopen ()\fC [inline]\fP"

.PP
Definition at line 54 of file corruption_test\&.cc\&.
.SS "\fBSlice\fP leveldb::CorruptionTest::Value (int k, std::string * storage)\fC [inline]\fP"

.PP
Definition at line 196 of file corruption_test\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDB\fP* leveldb::CorruptionTest::db_"

.PP
Definition at line 33 of file corruption_test\&.cc\&.
.SS "std::string leveldb::CorruptionTest::dbname_"

.PP
Definition at line 30 of file corruption_test\&.cc\&.
.SS "\fBtest::ErrorEnv\fP leveldb::CorruptionTest::env_"

.PP
Definition at line 29 of file corruption_test\&.cc\&.
.SS "\fBOptions\fP leveldb::CorruptionTest::options_"

.PP
Definition at line 32 of file corruption_test\&.cc\&.
.SS "\fBCache\fP* leveldb::CorruptionTest::tiny_cache_"

.PP
Definition at line 31 of file corruption_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
