.TH "leveldb::DB" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::DB \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <db\&.h>\fP
.PP
Inherited by \fBleveldb::DBImpl\fP, and \fBleveldb::ModelDB\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDB\fP ()"
.br
.ti -1c
.RI "virtual \fB~DB\fP ()"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBPut\fP (const \fBWriteOptions\fP &options, const \fBSlice\fP &key, const \fBSlice\fP &\fBvalue\fP)=0"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBDelete\fP (const \fBWriteOptions\fP &options, const \fBSlice\fP &key)=0"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBWrite\fP (const \fBWriteOptions\fP &options, \fBWriteBatch\fP *updates)=0"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBGet\fP (const \fBReadOptions\fP &options, const \fBSlice\fP &key, std::string *\fBvalue\fP)=0"
.br
.ti -1c
.RI "virtual \fBIterator\fP * \fBNewIterator\fP (const \fBReadOptions\fP &options)=0"
.br
.ti -1c
.RI "virtual const \fBSnapshot\fP * \fBGetSnapshot\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBReleaseSnapshot\fP (const \fBSnapshot\fP *snapshot)=0"
.br
.ti -1c
.RI "virtual bool \fBGetProperty\fP (const \fBSlice\fP &property, std::string *\fBvalue\fP)=0"
.br
.ti -1c
.RI "virtual void \fBGetApproximateSizes\fP (const \fBRange\fP *range, int n, \fBuint64_t\fP *sizes)=0"
.br
.ti -1c
.RI "virtual void \fBCompactRange\fP (const \fBSlice\fP *begin, const \fBSlice\fP *end)=0"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBStatus\fP \fBOpen\fP (const \fBOptions\fP &options, const std::string &\fBname\fP, \fBDB\fP **dbptr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file db\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::DB::DB ()\fC [inline]\fP"

.PP
Definition at line 55 of file db\&.h\&.
.SS "leveldb::DB::~DB ()\fC [virtual]\fP"

.PP
Definition at line 1443 of file db_impl\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void leveldb::DB::CompactRange (const \fBSlice\fP * begin, const \fBSlice\fP * end)\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::ModelDB\fP, and \fBleveldb::DBImpl\fP\&.
.SS "\fBStatus\fP leveldb::DB::Delete (const \fBWriteOptions\fP & options, const \fBSlice\fP & key)\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::ModelDB\fP, and \fBleveldb::DBImpl\fP\&.
.PP
Definition at line 1437 of file db_impl\&.cc\&.
.SS "virtual \fBStatus\fP leveldb::DB::Get (const \fBReadOptions\fP & options, const \fBSlice\fP & key, std::string * value)\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::ModelDB\fP, and \fBleveldb::DBImpl\fP\&.
.SS "virtual void leveldb::DB::GetApproximateSizes (const \fBRange\fP * range, int n, \fBuint64_t\fP * sizes)\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::ModelDB\fP, and \fBleveldb::DBImpl\fP\&.
.SS "virtual bool leveldb::DB::GetProperty (const \fBSlice\fP & property, std::string * value)\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::ModelDB\fP, and \fBleveldb::DBImpl\fP\&.
.SS "virtual const \fBSnapshot\fP* leveldb::DB::GetSnapshot ()\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::ModelDB\fP, and \fBleveldb::DBImpl\fP\&.
.SS "virtual \fBIterator\fP* leveldb::DB::NewIterator (const \fBReadOptions\fP & options)\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::ModelDB\fP, and \fBleveldb::DBImpl\fP\&.
.SS "\fBStatus\fP leveldb::DB::Open (const \fBOptions\fP & options, const std::string & name, \fBDB\fP ** dbptr)\fC [static]\fP"

.PP
Definition at line 1445 of file db_impl\&.cc\&.
.SS "\fBStatus\fP leveldb::DB::Put (const \fBWriteOptions\fP & options, const \fBSlice\fP & key, const \fBSlice\fP & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::ModelDB\fP, and \fBleveldb::DBImpl\fP\&.
.PP
Definition at line 1431 of file db_impl\&.cc\&.
.SS "virtual void leveldb::DB::ReleaseSnapshot (const \fBSnapshot\fP * snapshot)\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::ModelDB\fP, and \fBleveldb::DBImpl\fP\&.
.SS "virtual \fBStatus\fP leveldb::DB::Write (const \fBWriteOptions\fP & options, \fBWriteBatch\fP * updates)\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::ModelDB\fP, and \fBleveldb::DBImpl\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
