.TH "leveldb::Slice" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::Slice \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <slice\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSlice\fP ()"
.br
.ti -1c
.RI "\fBSlice\fP (const char *d, size_t n)"
.br
.ti -1c
.RI "\fBSlice\fP (const std::string &s)"
.br
.ti -1c
.RI "\fBSlice\fP (const char *s)"
.br
.ti -1c
.RI "const char * \fBdata\fP () const "
.br
.ti -1c
.RI "size_t \fBsize\fP () const "
.br
.ti -1c
.RI "bool \fBempty\fP () const "
.br
.ti -1c
.RI "char \fBoperator[]\fP (size_t n) const "
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "void \fBremove_prefix\fP (size_t n)"
.br
.ti -1c
.RI "std::string \fBToString\fP () const "
.br
.ti -1c
.RI "int \fBcompare\fP (const \fBSlice\fP &b) const "
.br
.ti -1c
.RI "bool \fBstarts_with\fP (const \fBSlice\fP &x) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file slice\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::Slice::Slice ()\fC [inline]\fP"

.PP
Definition at line 28 of file slice\&.h\&.
.SS "leveldb::Slice::Slice (const char * d, size_t n)\fC [inline]\fP"

.PP
Definition at line 31 of file slice\&.h\&.
.SS "leveldb::Slice::Slice (const std::string & s)\fC [inline]\fP"

.PP
Definition at line 34 of file slice\&.h\&.
.SS "leveldb::Slice::Slice (const char * s)\fC [inline]\fP"

.PP
Definition at line 37 of file slice\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::Slice::clear ()\fC [inline]\fP"

.PP
Definition at line 56 of file slice\&.h\&.
.SS "int leveldb::Slice::compare (const \fBSlice\fP & b) const\fC [inline]\fP"

.PP
Definition at line 96 of file slice\&.h\&.
.SS "const char* leveldb::Slice::data () const\fC [inline]\fP"

.PP
Definition at line 40 of file slice\&.h\&.
.SS "bool leveldb::Slice::empty () const\fC [inline]\fP"

.PP
Definition at line 46 of file slice\&.h\&.
.SS "char leveldb::Slice::operator[] (size_t n) const\fC [inline]\fP"

.PP
Definition at line 50 of file slice\&.h\&.
.SS "void leveldb::Slice::remove_prefix (size_t n)\fC [inline]\fP"

.PP
Definition at line 59 of file slice\&.h\&.
.SS "size_t leveldb::Slice::size () const\fC [inline]\fP"

.PP
Definition at line 43 of file slice\&.h\&.
.SS "bool leveldb::Slice::starts_with (const \fBSlice\fP & x) const\fC [inline]\fP"

.PP
Definition at line 75 of file slice\&.h\&.
.SS "std::string leveldb::Slice::ToString () const\fC [inline]\fP"

.PP
Definition at line 66 of file slice\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
