.TH "leveldb::FileMetaData" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::FileMetaData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <version_edit\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileMetaData\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBrefs\fP"
.br
.ti -1c
.RI "int \fBallowed_seeks\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBnumber\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBfile_size\fP"
.br
.ti -1c
.RI "\fBInternalKey\fP \fBsmallest\fP"
.br
.ti -1c
.RI "\fBInternalKey\fP \fBlargest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file version_edit\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::FileMetaData::FileMetaData ()\fC [inline]\fP"

.PP
Definition at line 25 of file version_edit\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int leveldb::FileMetaData::allowed_seeks"

.PP
Definition at line 19 of file version_edit\&.h\&.
.SS "\fBuint64_t\fP leveldb::FileMetaData::file_size"

.PP
Definition at line 21 of file version_edit\&.h\&.
.SS "\fBInternalKey\fP leveldb::FileMetaData::largest"

.PP
Definition at line 23 of file version_edit\&.h\&.
.SS "\fBuint64_t\fP leveldb::FileMetaData::number"

.PP
Definition at line 20 of file version_edit\&.h\&.
.SS "int leveldb::FileMetaData::refs"

.PP
Definition at line 18 of file version_edit\&.h\&.
.SS "\fBInternalKey\fP leveldb::FileMetaData::smallest"

.PP
Definition at line 22 of file version_edit\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
