.TH "/home/dev/ds-160209/src/leveldbwrapper.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldbwrapper.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'serialize\&.h'\fP
.br
\fC#include 'streams\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include <boost/filesystem/path\&.hpp>\fP
.br
\fC#include <leveldb/db\&.h>\fP
.br
\fC#include <leveldb/write_batch\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBleveldb_error\fP"
.br
.ti -1c
.RI "class \fBCLevelDBBatch\fP"
.br
.ti -1c
.RI "class \fBCLevelDBWrapper\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBHandleError\fP (const \fBleveldb::Status\fP &status)  throw (leveldb_error)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void HandleError (const \fBleveldb::Status\fP & status)\fBleveldb_error\fP"

.PP
Definition at line 14 of file leveldbwrapper\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
