.TH "leveldb::IteratorWrapper" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::IteratorWrapper \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <iterator_wrapper\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIteratorWrapper\fP ()"
.br
.ti -1c
.RI "\fBIteratorWrapper\fP (\fBIterator\fP *\fBiter\fP)"
.br
.ti -1c
.RI "\fB~IteratorWrapper\fP ()"
.br
.ti -1c
.RI "\fBIterator\fP * \fBiter\fP () const "
.br
.ti -1c
.RI "void \fBSet\fP (\fBIterator\fP *\fBiter\fP)"
.br
.ti -1c
.RI "bool \fBValid\fP () const "
.br
.ti -1c
.RI "\fBSlice\fP \fBkey\fP () const "
.br
.ti -1c
.RI "\fBSlice\fP \fBvalue\fP () const "
.br
.ti -1c
.RI "\fBStatus\fP \fBstatus\fP () const "
.br
.ti -1c
.RI "void \fBNext\fP ()"
.br
.ti -1c
.RI "void \fBPrev\fP ()"
.br
.ti -1c
.RI "void \fBSeek\fP (const \fBSlice\fP &k)"
.br
.ti -1c
.RI "void \fBSeekToFirst\fP ()"
.br
.ti -1c
.RI "void \fBSeekToLast\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file iterator_wrapper\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::IteratorWrapper::IteratorWrapper ()\fC [inline]\fP"

.PP
Definition at line 16 of file iterator_wrapper\&.h\&.
.SS "leveldb::IteratorWrapper::IteratorWrapper (\fBIterator\fP * iter)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 17 of file iterator_wrapper\&.h\&.
.SS "leveldb::IteratorWrapper::~IteratorWrapper ()\fC [inline]\fP"

.PP
Definition at line 20 of file iterator_wrapper\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIterator\fP* leveldb::IteratorWrapper::iter () const\fC [inline]\fP"

.PP
Definition at line 21 of file iterator_wrapper\&.h\&.
.SS "\fBSlice\fP leveldb::IteratorWrapper::key () const\fC [inline]\fP"

.PP
Definition at line 38 of file iterator_wrapper\&.h\&.
.SS "void leveldb::IteratorWrapper::Next ()\fC [inline]\fP"

.PP
Definition at line 42 of file iterator_wrapper\&.h\&.
.SS "void leveldb::IteratorWrapper::Prev ()\fC [inline]\fP"

.PP
Definition at line 43 of file iterator_wrapper\&.h\&.
.SS "void leveldb::IteratorWrapper::Seek (const \fBSlice\fP & k)\fC [inline]\fP"

.PP
Definition at line 44 of file iterator_wrapper\&.h\&.
.SS "void leveldb::IteratorWrapper::SeekToFirst ()\fC [inline]\fP"

.PP
Definition at line 45 of file iterator_wrapper\&.h\&.
.SS "void leveldb::IteratorWrapper::SeekToLast ()\fC [inline]\fP"

.PP
Definition at line 46 of file iterator_wrapper\&.h\&.
.SS "void leveldb::IteratorWrapper::Set (\fBIterator\fP * iter)\fC [inline]\fP"

.PP
Definition at line 25 of file iterator_wrapper\&.h\&.
.SS "\fBStatus\fP leveldb::IteratorWrapper::status () const\fC [inline]\fP"

.PP
Definition at line 41 of file iterator_wrapper\&.h\&.
.SS "bool leveldb::IteratorWrapper::Valid () const\fC [inline]\fP"

.PP
Definition at line 37 of file iterator_wrapper\&.h\&.
.SS "\fBSlice\fP leveldb::IteratorWrapper::value () const\fC [inline]\fP"

.PP
Definition at line 39 of file iterator_wrapper\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
