.TH "leveldb::Block" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::Block \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <block\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIter\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlock\fP (const \fBBlockContents\fP &contents)"
.br
.ti -1c
.RI "\fB~Block\fP ()"
.br
.ti -1c
.RI "size_t \fBsize\fP () const "
.br
.ti -1c
.RI "\fBIterator\fP * \fBNewIterator\fP (const \fBComparator\fP *comparator)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file block\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::Block::Block (const \fBBlockContents\fP & contents)\fC [explicit]\fP"

.PP
Definition at line 23 of file block\&.cc\&.
.SS "leveldb::Block::~Block ()"

.PP
Definition at line 40 of file block\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIterator\fP * leveldb::Block::NewIterator (const \fBComparator\fP * comparator)"

.PP
Definition at line 256 of file block\&.cc\&.
.SS "size_t leveldb::Block::size () const\fC [inline]\fP"

.PP
Definition at line 24 of file block\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
