.TH "leveldb::DBImpl::Writer" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::DBImpl::Writer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWriter\fP (\fBport::Mutex\fP *\fBmu\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBStatus\fP \fBstatus\fP"
.br
.ti -1c
.RI "\fBWriteBatch\fP * \fBbatch\fP"
.br
.ti -1c
.RI "bool \fBsync\fP"
.br
.ti -1c
.RI "bool \fBdone\fP"
.br
.ti -1c
.RI "\fBport::CondVar\fP \fBcv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file db_impl\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::DBImpl::Writer::Writer (\fBport::Mutex\fP * mu)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 48 of file db_impl\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBWriteBatch\fP* leveldb::DBImpl::Writer::batch"

.PP
Definition at line 43 of file db_impl\&.cc\&.
.SS "\fBport::CondVar\fP leveldb::DBImpl::Writer::cv"

.PP
Definition at line 46 of file db_impl\&.cc\&.
.SS "bool leveldb::DBImpl::Writer::done"

.PP
Definition at line 45 of file db_impl\&.cc\&.
.SS "\fBStatus\fP leveldb::DBImpl::Writer::status"

.PP
Definition at line 42 of file db_impl\&.cc\&.
.SS "bool leveldb::DBImpl::Writer::sync"

.PP
Definition at line 44 of file db_impl\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
