.TH "leveldb::BlockContents" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::BlockContents \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <format\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSlice\fP \fBdata\fP"
.br
.ti -1c
.RI "bool \fBcachable\fP"
.br
.ti -1c
.RI "bool \fBheap_allocated\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 86 of file format\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool leveldb::BlockContents::cachable"

.PP
Definition at line 88 of file format\&.h\&.
.SS "\fBSlice\fP leveldb::BlockContents::data"

.PP
Definition at line 87 of file format\&.h\&.
.SS "bool leveldb::BlockContents::heap_allocated"

.PP
Definition at line 89 of file format\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
