.TH "leveldb::Harness" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::Harness \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHarness\fP ()"
.br
.ti -1c
.RI "void \fBInit\fP (const \fBTestArgs\fP &args)"
.br
.ti -1c
.RI "\fB~Harness\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (const std::string &key, const std::string &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBTest\fP (\fBRandom\fP *rnd)"
.br
.ti -1c
.RI "void \fBTestForwardScan\fP (const std::vector< std::string > &keys, const \fBKVMap\fP &data)"
.br
.ti -1c
.RI "void \fBTestBackwardScan\fP (const std::vector< std::string > &keys, const \fBKVMap\fP &data)"
.br
.ti -1c
.RI "void \fBTestRandomAccess\fP (\fBRandom\fP *rnd, const std::vector< std::string > &keys, const \fBKVMap\fP &data)"
.br
.ti -1c
.RI "std::string \fBToString\fP (const \fBKVMap\fP &data, const KVMap::const_iterator &it)"
.br
.ti -1c
.RI "std::string \fBToString\fP (const \fBKVMap\fP &data, const KVMap::const_reverse_iterator &it)"
.br
.ti -1c
.RI "std::string \fBToString\fP (const \fBIterator\fP *it)"
.br
.ti -1c
.RI "std::string \fBPickRandomKey\fP (\fBRandom\fP *rnd, const std::vector< std::string > &keys)"
.br
.ti -1c
.RI "\fBDB\fP * \fBdb\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 437 of file table_test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::Harness::Harness ()\fC [inline]\fP"

.PP
Definition at line 439 of file table_test\&.cc\&.
.SS "leveldb::Harness::~Harness ()\fC [inline]\fP"

.PP
Definition at line 469 of file table_test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::Harness::Add (const std::string & key, const std::string & value)\fC [inline]\fP"

.PP
Definition at line 473 of file table_test\&.cc\&.
.SS "\fBDB\fP* leveldb::Harness::db () const\fC [inline]\fP"

.PP
Definition at line 640 of file table_test\&.cc\&.
.SS "void leveldb::Harness::Init (const \fBTestArgs\fP & args)\fC [inline]\fP"

.PP
Definition at line 441 of file table_test\&.cc\&.
.SS "std::string leveldb::Harness::PickRandomKey (\fBRandom\fP * rnd, const std::vector< std::string > & keys)\fC [inline]\fP"

.PP
Definition at line 612 of file table_test\&.cc\&.
.SS "void leveldb::Harness::Test (\fBRandom\fP * rnd)\fC [inline]\fP"

.PP
Definition at line 477 of file table_test\&.cc\&.
.SS "void leveldb::Harness::TestBackwardScan (const std::vector< std::string > & keys, const \fBKVMap\fP & data)\fC [inline]\fP"

.PP
Definition at line 502 of file table_test\&.cc\&.
.SS "void leveldb::Harness::TestForwardScan (const std::vector< std::string > & keys, const \fBKVMap\fP & data)\fC [inline]\fP"

.PP
Definition at line 487 of file table_test\&.cc\&.
.SS "void leveldb::Harness::TestRandomAccess (\fBRandom\fP * rnd, const std::vector< std::string > & keys, const \fBKVMap\fP & data)\fC [inline]\fP"

.PP
Definition at line 517 of file table_test\&.cc\&.
.SS "std::string leveldb::Harness::ToString (const \fBKVMap\fP & data, const KVMap::const_iterator & it)\fC [inline]\fP"

.PP
Definition at line 587 of file table_test\&.cc\&.
.SS "std::string leveldb::Harness::ToString (const \fBKVMap\fP & data, const KVMap::const_reverse_iterator & it)\fC [inline]\fP"

.PP
Definition at line 595 of file table_test\&.cc\&.
.SS "std::string leveldb::Harness::ToString (const \fBIterator\fP * it)\fC [inline]\fP"

.PP
Definition at line 604 of file table_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
