.TH "leveldb::TestHashFilter" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::TestHashFilter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBleveldb::FilterPolicy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual const char * \fBName\fP () const "
.br
.ti -1c
.RI "virtual void \fBCreateFilter\fP (const \fBSlice\fP *keys, int n, std::string *dst) const "
.br
.ti -1c
.RI "virtual bool \fBKeyMayMatch\fP (const \fBSlice\fP &key, const \fBSlice\fP &filter) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file filter_block_test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void leveldb::TestHashFilter::CreateFilter (const \fBSlice\fP * keys, int n, std::string * dst) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::FilterPolicy\fP\&.
.PP
Definition at line 23 of file filter_block_test\&.cc\&.
.SS "virtual bool leveldb::TestHashFilter::KeyMayMatch (const \fBSlice\fP & key, const \fBSlice\fP & filter) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::FilterPolicy\fP\&.
.PP
Definition at line 30 of file filter_block_test\&.cc\&.
.SS "virtual const char* leveldb::TestHashFilter::Name () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::FilterPolicy\fP\&.
.PP
Definition at line 19 of file filter_block_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
