.TH "leveldb::port::OnceType" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::port::OnceType \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <port_win\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOnceType\fP (const \fBOnceType\fP &once)"
.br
.ti -1c
.RI "\fBOnceType\fP (bool f)"
.br
.ti -1c
.RI "void \fBInitOnce\fP (void(*initializer)())"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 98 of file port_win\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::port::OnceType::OnceType (const \fBOnceType\fP & once)\fC [inline]\fP"

.PP
Definition at line 101 of file port_win\&.h\&.
.SS "leveldb::port::OnceType::OnceType (bool f)\fC [inline]\fP"

.PP
Definition at line 102 of file port_win\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::port::OnceType::InitOnce (void(*)() initializer)\fC [inline]\fP"

.PP
Definition at line 103 of file port_win\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
