.TH "leveldb::ReadOptions" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::ReadOptions \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <options\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReadOptions\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBverify_checksums\fP"
.br
.ti -1c
.RI "bool \fBfill_cache\fP"
.br
.ti -1c
.RI "const \fBSnapshot\fP * \fBsnapshot\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 143 of file options\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::ReadOptions::ReadOptions ()\fC [inline]\fP"

.PP
Definition at line 161 of file options\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool leveldb::ReadOptions::fill_cache"

.PP
Definition at line 152 of file options\&.h\&.
.SS "const \fBSnapshot\fP* leveldb::ReadOptions::snapshot"

.PP
Definition at line 159 of file options\&.h\&.
.SS "bool leveldb::ReadOptions::verify_checksums"

.PP
Definition at line 147 of file options\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
