.TH "leveldb::log::LogTest" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::log::LogTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogTest\fP ()"
.br
.ti -1c
.RI "void \fBWrite\fP (const std::string &msg)"
.br
.ti -1c
.RI "size_t \fBWrittenBytes\fP () const "
.br
.ti -1c
.RI "std::string \fBRead\fP ()"
.br
.ti -1c
.RI "void \fBIncrementByte\fP (int offset, int delta)"
.br
.ti -1c
.RI "void \fBSetByte\fP (int offset, char new_byte)"
.br
.ti -1c
.RI "void \fBShrinkSize\fP (int bytes)"
.br
.ti -1c
.RI "void \fBFixChecksum\fP (int header_offset, int len)"
.br
.ti -1c
.RI "void \fBForceError\fP ()"
.br
.ti -1c
.RI "size_t \fBDroppedBytes\fP () const "
.br
.ti -1c
.RI "std::string \fBReportMessage\fP () const "
.br
.ti -1c
.RI "std::string \fBMatchError\fP (const std::string &msg) const "
.br
.ti -1c
.RI "void \fBWriteInitialOffsetLog\fP ()"
.br
.ti -1c
.RI "void \fBCheckOffsetPastEndReturnsNoRecords\fP (\fBuint64_t\fP offset_past_end)"
.br
.ti -1c
.RI "void \fBCheckInitialOffsetRecord\fP (\fBuint64_t\fP initial_offset, int expected_record_offset)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file log_test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::log::LogTest::LogTest ()\fC [inline]\fP"

.PP
Definition at line 115 of file log_test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::log::LogTest::CheckInitialOffsetRecord (\fBuint64_t\fP initial_offset, int expected_record_offset)\fC [inline]\fP"

.PP
Definition at line 204 of file log_test\&.cc\&.
.SS "void leveldb::log::LogTest::CheckOffsetPastEndReturnsNoRecords (\fBuint64_t\fP offset_past_end)\fC [inline]\fP"

.PP
Definition at line 192 of file log_test\&.cc\&.
.SS "size_t leveldb::log::LogTest::DroppedBytes () const\fC [inline]\fP"

.PP
Definition at line 167 of file log_test\&.cc\&.
.SS "void leveldb::log::LogTest::FixChecksum (int header_offset, int len)\fC [inline]\fP"

.PP
Definition at line 156 of file log_test\&.cc\&.
.SS "void leveldb::log::LogTest::ForceError ()\fC [inline]\fP"

.PP
Definition at line 163 of file log_test\&.cc\&.
.SS "void leveldb::log::LogTest::IncrementByte (int offset, int delta)\fC [inline]\fP"

.PP
Definition at line 144 of file log_test\&.cc\&.
.SS "std::string leveldb::log::LogTest::MatchError (const std::string & msg) const\fC [inline]\fP"

.PP
Definition at line 176 of file log_test\&.cc\&.
.SS "std::string leveldb::log::LogTest::Read ()\fC [inline]\fP"

.PP
Definition at line 130 of file log_test\&.cc\&.
.SS "std::string leveldb::log::LogTest::ReportMessage () const\fC [inline]\fP"

.PP
Definition at line 171 of file log_test\&.cc\&.
.SS "void leveldb::log::LogTest::SetByte (int offset, char new_byte)\fC [inline]\fP"

.PP
Definition at line 148 of file log_test\&.cc\&.
.SS "void leveldb::log::LogTest::ShrinkSize (int bytes)\fC [inline]\fP"

.PP
Definition at line 152 of file log_test\&.cc\&.
.SS "void leveldb::log::LogTest::Write (const std::string & msg)\fC [inline]\fP"

.PP
Definition at line 121 of file log_test\&.cc\&.
.SS "void leveldb::log::LogTest::WriteInitialOffsetLog ()\fC [inline]\fP"

.PP
Definition at line 184 of file log_test\&.cc\&.
.SS "size_t leveldb::log::LogTest::WrittenBytes () const\fC [inline]\fP"

.PP
Definition at line 126 of file log_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
