.TH "leveldb::MemTableIterator" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::MemTableIterator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBleveldb::Iterator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemTableIterator\fP (\fBMemTable::Table\fP *table)"
.br
.ti -1c
.RI "virtual bool \fBValid\fP () const "
.br
.ti -1c
.RI "virtual void \fBSeek\fP (const \fBSlice\fP &k)"
.br
.ti -1c
.RI "virtual void \fBSeekToFirst\fP ()"
.br
.ti -1c
.RI "virtual void \fBSeekToLast\fP ()"
.br
.ti -1c
.RI "virtual void \fBNext\fP ()"
.br
.ti -1c
.RI "virtual void \fBPrev\fP ()"
.br
.ti -1c
.RI "virtual \fBSlice\fP \fBkey\fP () const "
.br
.ti -1c
.RI "virtual \fBSlice\fP \fBvalue\fP () const "
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBstatus\fP () const "
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 51 of file memtable\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::MemTableIterator::MemTableIterator (\fBMemTable::Table\fP * table)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 53 of file memtable\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBSlice\fP leveldb::MemTableIterator::key () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 61 of file memtable\&.cc\&.
.SS "virtual void leveldb::MemTableIterator::Next ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 59 of file memtable\&.cc\&.
.SS "virtual void leveldb::MemTableIterator::Prev ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 60 of file memtable\&.cc\&.
.SS "virtual void leveldb::MemTableIterator::Seek (const \fBSlice\fP & k)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 56 of file memtable\&.cc\&.
.SS "virtual void leveldb::MemTableIterator::SeekToFirst ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 57 of file memtable\&.cc\&.
.SS "virtual void leveldb::MemTableIterator::SeekToLast ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 58 of file memtable\&.cc\&.
.SS "virtual \fBStatus\fP leveldb::MemTableIterator::status () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 67 of file memtable\&.cc\&.
.SS "virtual bool leveldb::MemTableIterator::Valid () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 55 of file memtable\&.cc\&.
.SS "virtual \fBSlice\fP leveldb::MemTableIterator::value () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 62 of file memtable\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
