.TH "leveldb::Histogram" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::Histogram \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <histogram\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHistogram\fP ()"
.br
.ti -1c
.RI "\fB~Histogram\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (double \fBvalue\fP)"
.br
.ti -1c
.RI "void \fBMerge\fP (const \fBHistogram\fP &other)"
.br
.ti -1c
.RI "std::string \fBToString\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file histogram\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::Histogram::Histogram ()\fC [inline]\fP"

.PP
Definition at line 14 of file histogram\&.h\&.
.SS "leveldb::Histogram::~Histogram ()\fC [inline]\fP"

.PP
Definition at line 15 of file histogram\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::Histogram::Add (double value)"

.PP
Definition at line 44 of file histogram\&.cc\&.
.SS "void leveldb::Histogram::Clear ()"

.PP
Definition at line 33 of file histogram\&.cc\&.
.SS "void leveldb::Histogram::Merge (const \fBHistogram\fP & other)"

.PP
Definition at line 58 of file histogram\&.cc\&.
.SS "std::string leveldb::Histogram::ToString () const"

.PP
Definition at line 105 of file histogram\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
