.TH "leveldb::SpecialEnv" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::SpecialEnv \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBleveldb::EnvWrapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpecialEnv\fP (\fBEnv\fP *\fBbase\fP)"
.br
.ti -1c
.RI "\fBStatus\fP \fBNewWritableFile\fP (const std::string &f, \fBWritableFile\fP **r)"
.br
.ti -1c
.RI "\fBStatus\fP \fBNewRandomAccessFile\fP (const std::string &f, \fBRandomAccessFile\fP **r)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBport::AtomicPointer\fP \fBdelay_data_sync_\fP"
.br
.ti -1c
.RI "\fBport::AtomicPointer\fP \fBdata_sync_error_\fP"
.br
.ti -1c
.RI "\fBport::AtomicPointer\fP \fBno_space_\fP"
.br
.ti -1c
.RI "\fBport::AtomicPointer\fP \fBnon_writable_\fP"
.br
.ti -1c
.RI "\fBport::AtomicPointer\fP \fBmanifest_sync_error_\fP"
.br
.ti -1c
.RI "\fBport::AtomicPointer\fP \fBmanifest_write_error_\fP"
.br
.ti -1c
.RI "bool \fBcount_random_reads_\fP"
.br
.ti -1c
.RI "AtomicCounter \fBrandom_read_counter_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 58 of file db_test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::SpecialEnv::SpecialEnv (\fBEnv\fP * base)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 81 of file db_test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBStatus\fP leveldb::SpecialEnv::NewRandomAccessFile (const std::string & f, \fBRandomAccessFile\fP ** r)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Env\fP\&.
.PP
Definition at line 164 of file db_test\&.cc\&.
.SS "\fBStatus\fP leveldb::SpecialEnv::NewWritableFile (const std::string & f, \fBWritableFile\fP ** r)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Env\fP\&.
.PP
Definition at line 91 of file db_test\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "bool leveldb::SpecialEnv::count_random_reads_"

.PP
Definition at line 78 of file db_test\&.cc\&.
.SS "\fBport::AtomicPointer\fP leveldb::SpecialEnv::data_sync_error_"

.PP
Definition at line 64 of file db_test\&.cc\&.
.SS "\fBport::AtomicPointer\fP leveldb::SpecialEnv::delay_data_sync_"

.PP
Definition at line 61 of file db_test\&.cc\&.
.SS "\fBport::AtomicPointer\fP leveldb::SpecialEnv::manifest_sync_error_"

.PP
Definition at line 73 of file db_test\&.cc\&.
.SS "\fBport::AtomicPointer\fP leveldb::SpecialEnv::manifest_write_error_"

.PP
Definition at line 76 of file db_test\&.cc\&.
.SS "\fBport::AtomicPointer\fP leveldb::SpecialEnv::no_space_"

.PP
Definition at line 67 of file db_test\&.cc\&.
.SS "\fBport::AtomicPointer\fP leveldb::SpecialEnv::non_writable_"

.PP
Definition at line 70 of file db_test\&.cc\&.
.SS "AtomicCounter leveldb::SpecialEnv::random_read_counter_"

.PP
Definition at line 79 of file db_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
