.TH "leveldb_comparator_t" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb_comparator_t \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBleveldb::Comparator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~leveldb_comparator_t\fP ()"
.br
.ti -1c
.RI "virtual int \fBCompare\fP (const \fBSlice\fP &a, const \fBSlice\fP &b) const "
.br
.ti -1c
.RI "virtual const char * \fBName\fP () const "
.br
.ti -1c
.RI "virtual void \fBFindShortestSeparator\fP (std::string *, const \fBSlice\fP &) const "
.br
.ti -1c
.RI "virtual void \fBFindShortSuccessor\fP (std::string *key) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBstate_\fP"
.br
.ti -1c
.RI "void(* \fBdestructor_\fP )(void *)"
.br
.ti -1c
.RI "int(* \fBcompare_\fP )(void *, const char *a, size_t alen, const char *b, size_t blen)"
.br
.ti -1c
.RI "const char *(* \fBname_\fP )(void *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file c\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual leveldb_comparator_t::~leveldb_comparator_t ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 69 of file c\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual int leveldb_comparator_t::Compare (const \fBSlice\fP & a, const \fBSlice\fP & b) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Comparator\fP\&.
.PP
Definition at line 73 of file c\&.cc\&.
.SS "virtual void leveldb_comparator_t::FindShortestSeparator (std::string *, const \fBSlice\fP &) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Comparator\fP\&.
.PP
Definition at line 82 of file c\&.cc\&.
.SS "virtual void leveldb_comparator_t::FindShortSuccessor (std::string * key) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Comparator\fP\&.
.PP
Definition at line 83 of file c\&.cc\&.
.SS "virtual const char* leveldb_comparator_t::Name () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Comparator\fP\&.
.PP
Definition at line 77 of file c\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "int(* leveldb_comparator_t::compare_) (void *, const char *a, size_t alen, const char *b, size_t blen)"

.PP
Definition at line 63 of file c\&.cc\&.
.SS "void(* leveldb_comparator_t::destructor_) (void *)"

.PP
Definition at line 62 of file c\&.cc\&.
.SS "const char*(* leveldb_comparator_t::name_) (void *)"

.PP
Definition at line 67 of file c\&.cc\&.
.SS "void* leveldb_comparator_t::state_"

.PP
Definition at line 61 of file c\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
