.TH "leveldb::port::AtomicPointer" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::port::AtomicPointer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <port_example\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAtomicPointer\fP ()"
.br
.ti -1c
.RI "\fBAtomicPointer\fP (void *v)"
.br
.ti -1c
.RI "void * \fBAcquire_Load\fP () const "
.br
.ti -1c
.RI "void \fBRelease_Store\fP (void *v)"
.br
.ti -1c
.RI "void * \fBNoBarrier_Load\fP () const "
.br
.ti -1c
.RI "void \fBNoBarrier_Store\fP (void *v)"
.br
.ti -1c
.RI "\fBAtomicPointer\fP ()"
.br
.ti -1c
.RI "\fBAtomicPointer\fP (void *v)"
.br
.ti -1c
.RI "void * \fBAcquire_Load\fP () const "
.br
.ti -1c
.RI "void \fBRelease_Store\fP (void *v)"
.br
.ti -1c
.RI "void * \fBNoBarrier_Load\fP () const "
.br
.ti -1c
.RI "void \fBNoBarrier_Store\fP (void *v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 75 of file port_example\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::port::AtomicPointer::AtomicPointer ()"

.SS "leveldb::port::AtomicPointer::AtomicPointer (void * v)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 83 of file port_example\&.h\&.
.SS "leveldb::port::AtomicPointer::AtomicPointer ()\fC [inline]\fP"

.PP
Definition at line 125 of file port_win\&.h\&.
.SS "leveldb::port::AtomicPointer::AtomicPointer (void * v)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void * leveldb::port::AtomicPointer::Acquire_Load () const"

.PP
Definition at line 128 of file port_win\&.cc\&.
.SS "void* leveldb::port::AtomicPointer::Acquire_Load () const"

.SS "void * leveldb::port::AtomicPointer::NoBarrier_Load () const"

.PP
Definition at line 138 of file port_win\&.cc\&.
.SS "void* leveldb::port::AtomicPointer::NoBarrier_Load () const"

.SS "void leveldb::port::AtomicPointer::NoBarrier_Store (void * v)"

.PP
Definition at line 142 of file port_win\&.cc\&.
.SS "void leveldb::port::AtomicPointer::NoBarrier_Store (void * v)"

.SS "void leveldb::port::AtomicPointer::Release_Store (void * v)"

.PP
Definition at line 134 of file port_win\&.cc\&.
.SS "void leveldb::port::AtomicPointer::Release_Store (void * v)"


.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
