.TH "leveldb::SkipList< Key, Comparator >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::SkipList< Key, Comparator > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <skiplist\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIterator\fP"
.br
.ti -1c
.RI "struct \fBNode\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSkipList\fP (\fBComparator\fP \fBcmp\fP, \fBArena\fP *arena)"
.br
.ti -1c
.RI "void \fBInsert\fP (const \fBKey\fP &key)"
.br
.ti -1c
.RI "bool \fBContains\fP (const \fBKey\fP &key) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Key, class Comparator>class leveldb::SkipList< Key, Comparator >"

.PP
Definition at line 41 of file skiplist\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Key , class Comparator> \fBleveldb::SkipList\fP< \fBKey\fP, \fBComparator\fP >::\fBSkipList\fP (\fBComparator\fP cmp, \fBArena\fP * arena)\fC [explicit]\fP"

.PP
Definition at line 325 of file skiplist\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Key, class Comparator > bool \fBleveldb::SkipList\fP< \fBKey\fP, \fBComparator\fP >::Contains (const \fBKey\fP & key) const"

.PP
Definition at line 373 of file skiplist\&.h\&.
.SS "template<typename Key, class Comparator > void \fBleveldb::SkipList\fP< \fBKey\fP, \fBComparator\fP >::Insert (const \fBKey\fP & key)"

.PP
Definition at line 337 of file skiplist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
