.TH "leveldb::StringSink" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::StringSink \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBleveldb::WritableFile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~StringSink\fP ()"
.br
.ti -1c
.RI "const std::string & \fBcontents\fP () const "
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBClose\fP ()"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBFlush\fP ()"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBSync\fP ()"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBAppend\fP (const \fBSlice\fP &data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 90 of file table_test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::StringSink::~StringSink ()\fC [inline]\fP"

.PP
Definition at line 92 of file table_test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBStatus\fP leveldb::StringSink::Append (const \fBSlice\fP & data)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::WritableFile\fP\&.
.PP
Definition at line 100 of file table_test\&.cc\&.
.SS "virtual \fBStatus\fP leveldb::StringSink::Close ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::WritableFile\fP\&.
.PP
Definition at line 96 of file table_test\&.cc\&.
.SS "const std::string& leveldb::StringSink::contents () const\fC [inline]\fP"

.PP
Definition at line 94 of file table_test\&.cc\&.
.SS "virtual \fBStatus\fP leveldb::StringSink::Flush ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::WritableFile\fP\&.
.PP
Definition at line 97 of file table_test\&.cc\&.
.SS "virtual \fBStatus\fP leveldb::StringSink::Sync ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::WritableFile\fP\&.
.PP
Definition at line 98 of file table_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
