.TH "leveldb::ModelDB::ModelSnapshot" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::ModelDB::ModelSnapshot \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBleveldb::Snapshot\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKVMap\fP \fBmap_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1833 of file db_test\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBKVMap\fP leveldb::ModelDB::ModelSnapshot::map_"

.PP
Definition at line 1835 of file db_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
