.TH "leveldb::WriteBatch::Handler" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::WriteBatch::Handler \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <write_batch\&.h>\fP
.PP
Inherited by \fBCBatchScanner\fP, and \fBSecMsgBatchScanner\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Handler\fP ()"
.br
.ti -1c
.RI "virtual void \fBPut\fP (const \fBSlice\fP &key, const \fBSlice\fP &\fBvalue\fP)=0"
.br
.ti -1c
.RI "virtual void \fBDelete\fP (const \fBSlice\fP &key)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file write_batch\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::WriteBatch::Handler::~Handler ()\fC [virtual]\fP"

.PP
Definition at line 35 of file write_batch\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void leveldb::WriteBatch::Handler::Delete (const \fBSlice\fP & key)\fC [pure virtual]\fP"

.PP
Implemented in \fBSecMsgBatchScanner\fP, and \fBCBatchScanner\fP\&.
.SS "virtual void leveldb::WriteBatch::Handler::Put (const \fBSlice\fP & key, const \fBSlice\fP & value)\fC [pure virtual]\fP"

.PP
Implemented in \fBSecMsgBatchScanner\fP, and \fBCBatchScanner\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
