.TH "leveldb::WritableFile" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::WritableFile \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <env\&.h>\fP
.PP
Inherited by \fBleveldb::StringSink\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWritableFile\fP ()"
.br
.ti -1c
.RI "virtual \fB~WritableFile\fP ()"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBAppend\fP (const \fBSlice\fP &data)=0"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBClose\fP ()=0"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBFlush\fP ()=0"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBSync\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 212 of file env\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::WritableFile::WritableFile ()\fC [inline]\fP"

.PP
Definition at line 214 of file env\&.h\&.
.SS "leveldb::WritableFile::~WritableFile ()\fC [virtual]\fP"

.PP
Definition at line 18 of file env\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBStatus\fP leveldb::WritableFile::Append (const \fBSlice\fP & data)\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::StringSink\fP\&.
.SS "virtual \fBStatus\fP leveldb::WritableFile::Close ()\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::StringSink\fP\&.
.SS "virtual \fBStatus\fP leveldb::WritableFile::Flush ()\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::StringSink\fP\&.
.SS "virtual \fBStatus\fP leveldb::WritableFile::Sync ()\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::StringSink\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
