.TH "leveldb::Version::GetStats" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::Version::GetStats \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <version_set\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFileMetaData\fP * \fBseek_file\fP"
.br
.ti -1c
.RI "int \fBseek_file_level\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 69 of file version_set\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFileMetaData\fP* leveldb::Version::GetStats::seek_file"

.PP
Definition at line 70 of file version_set\&.h\&.
.SS "int leveldb::Version::GetStats::seek_file_level"

.PP
Definition at line 71 of file version_set\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
