.TH "leveldb::WriteBatch" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::WriteBatch \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <write_batch\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHandler\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWriteBatch\fP ()"
.br
.ti -1c
.RI "\fB~WriteBatch\fP ()"
.br
.ti -1c
.RI "void \fBPut\fP (const \fBSlice\fP &key, const \fBSlice\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBDelete\fP (const \fBSlice\fP &key)"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "\fBStatus\fP \fBIterate\fP (\fBHandler\fP *handler) const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBWriteBatchInternal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file write_batch\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::WriteBatch::WriteBatch ()"

.PP
Definition at line 29 of file write_batch\&.cc\&.
.SS "leveldb::WriteBatch::~WriteBatch ()"

.PP
Definition at line 33 of file write_batch\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::WriteBatch::Clear ()"

.PP
Definition at line 37 of file write_batch\&.cc\&.
.SS "void leveldb::WriteBatch::Delete (const \fBSlice\fP & key)"

.PP
Definition at line 105 of file write_batch\&.cc\&.
.SS "\fBStatus\fP leveldb::WriteBatch::Iterate (\fBHandler\fP * handler) const"

.PP
Definition at line 42 of file write_batch\&.cc\&.
.SS "void leveldb::WriteBatch::Put (const \fBSlice\fP & key, const \fBSlice\fP & value)"

.PP
Definition at line 98 of file write_batch\&.cc\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBWriteBatchInternal\fP\fC [friend]\fP"

.PP
Definition at line 55 of file write_batch\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
