.TH "leveldb::FilterPolicy" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::FilterPolicy \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <filter_policy\&.h>\fP
.PP
Inherited by \fBleveldb::InternalFilterPolicy\fP, \fBleveldb::TestHashFilter\fP, and \fBleveldb_filterpolicy_t\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~FilterPolicy\fP ()"
.br
.ti -1c
.RI "virtual const char * \fBName\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBCreateFilter\fP (const \fBSlice\fP *keys, int n, std::string *dst) const =0"
.br
.ti -1c
.RI "virtual bool \fBKeyMayMatch\fP (const \fBSlice\fP &key, const \fBSlice\fP &filter) const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file filter_policy\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::FilterPolicy::~FilterPolicy ()\fC [virtual]\fP"

.PP
Definition at line 9 of file filter_policy\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void leveldb::FilterPolicy::CreateFilter (const \fBSlice\fP * keys, int n, std::string * dst) const\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::InternalFilterPolicy\fP, \fBleveldb_filterpolicy_t\fP, and \fBleveldb::TestHashFilter\fP\&.
.SS "virtual bool leveldb::FilterPolicy::KeyMayMatch (const \fBSlice\fP & key, const \fBSlice\fP & filter) const\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::InternalFilterPolicy\fP, \fBleveldb_filterpolicy_t\fP, and \fBleveldb::TestHashFilter\fP\&.
.SS "virtual const char* leveldb::FilterPolicy::Name () const\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::InternalFilterPolicy\fP, \fBleveldb_filterpolicy_t\fP, and \fBleveldb::TestHashFilter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
