.TH "leveldb::SkipList< Key, Comparator >::Iterator" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::SkipList< Key, Comparator >::Iterator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <skiplist\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIterator\fP (const \fBSkipList\fP *list)"
.br
.ti -1c
.RI "bool \fBValid\fP () const "
.br
.ti -1c
.RI "const \fBKey\fP & \fBkey\fP () const "
.br
.ti -1c
.RI "void \fBNext\fP ()"
.br
.ti -1c
.RI "void \fBPrev\fP ()"
.br
.ti -1c
.RI "void \fBSeek\fP (const \fBKey\fP &target)"
.br
.ti -1c
.RI "void \fBSeekToFirst\fP ()"
.br
.ti -1c
.RI "void \fBSeekToLast\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Key, class Comparator>class leveldb::SkipList< Key, Comparator >::Iterator"

.PP
Definition at line 59 of file skiplist\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Key , class Comparator > \fBleveldb::SkipList\fP< \fBKey\fP, \fBComparator\fP >::Iterator::Iterator (const \fBSkipList\fP * list)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 191 of file skiplist\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Key , class Comparator > const \fBKey\fP & \fBleveldb::SkipList\fP< \fBKey\fP, \fBComparator\fP >::Iterator::key () const\fC [inline]\fP"

.PP
Definition at line 202 of file skiplist\&.h\&.
.SS "template<typename Key , class Comparator > void \fBleveldb::SkipList\fP< \fBKey\fP, \fBComparator\fP >::Iterator::Next ()\fC [inline]\fP"

.PP
Definition at line 208 of file skiplist\&.h\&.
.SS "template<typename Key , class Comparator > void \fBleveldb::SkipList\fP< \fBKey\fP, \fBComparator\fP >::Iterator::Prev ()\fC [inline]\fP"

.PP
Definition at line 214 of file skiplist\&.h\&.
.SS "template<typename Key, class Comparator > void \fBleveldb::SkipList\fP< \fBKey\fP, \fBComparator\fP >::Iterator::Seek (const \fBKey\fP & target)\fC [inline]\fP"

.PP
Definition at line 225 of file skiplist\&.h\&.
.SS "template<typename Key , class Comparator > void \fBleveldb::SkipList\fP< \fBKey\fP, \fBComparator\fP >::Iterator::SeekToFirst ()\fC [inline]\fP"

.PP
Definition at line 230 of file skiplist\&.h\&.
.SS "template<typename Key , class Comparator > void \fBleveldb::SkipList\fP< \fBKey\fP, \fBComparator\fP >::Iterator::SeekToLast ()\fC [inline]\fP"

.PP
Definition at line 235 of file skiplist\&.h\&.
.SS "template<typename Key , class Comparator > bool \fBleveldb::SkipList\fP< \fBKey\fP, \fBComparator\fP >::Iterator::Valid () const\fC [inline]\fP"

.PP
Definition at line 197 of file skiplist\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
