.TH "leveldb::TestState" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::TestState \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBReaderState\fP { \fBSTARTING\fP, \fBRUNNING\fP, \fBDONE\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestState\fP (int s)"
.br
.ti -1c
.RI "void \fBWait\fP (\fBReaderState\fP s)"
.br
.ti -1c
.RI "void \fBChange\fP (\fBReaderState\fP s)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBConcurrentTest\fP \fBt_\fP"
.br
.ti -1c
.RI "int \fBseed_\fP"
.br
.ti -1c
.RI "\fBport::AtomicPointer\fP \fBquit_flag_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 297 of file skiplist_test\&.cc\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBleveldb::TestState::ReaderState\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISTARTING \fP\fP
.TP
\fB\fIRUNNING \fP\fP
.TP
\fB\fIDONE \fP\fP
.PP
Definition at line 303 of file skiplist_test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::TestState::TestState (int s)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 309 of file skiplist_test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::TestState::Change (\fBReaderState\fP s)\fC [inline]\fP"

.PP
Definition at line 323 of file skiplist_test\&.cc\&.
.SS "void leveldb::TestState::Wait (\fBReaderState\fP s)\fC [inline]\fP"

.PP
Definition at line 315 of file skiplist_test\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBport::AtomicPointer\fP leveldb::TestState::quit_flag_"

.PP
Definition at line 301 of file skiplist_test\&.cc\&.
.SS "int leveldb::TestState::seed_"

.PP
Definition at line 300 of file skiplist_test\&.cc\&.
.SS "\fBConcurrentTest\fP leveldb::TestState::t_"

.PP
Definition at line 299 of file skiplist_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
