.TH "leveldb::port::Mutex" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::port::Mutex \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <port_example\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMutex\fP ()"
.br
.ti -1c
.RI "\fB~Mutex\fP ()"
.br
.ti -1c
.RI "void \fBLock\fP ()"
.br
.ti -1c
.RI "void \fBUnlock\fP ()"
.br
.ti -1c
.RI "void \fBAssertHeld\fP ()"
.br
.ti -1c
.RI "\fBMutex\fP ()"
.br
.ti -1c
.RI "\fB~Mutex\fP ()"
.br
.ti -1c
.RI "void \fBLock\fP ()"
.br
.ti -1c
.RI "void \fBUnlock\fP ()"
.br
.ti -1c
.RI "void \fBAssertHeld\fP ()"
.br
.ti -1c
.RI "\fBMutex\fP ()"
.br
.ti -1c
.RI "\fB~Mutex\fP ()"
.br
.ti -1c
.RI "void \fBLock\fP ()"
.br
.ti -1c
.RI "void \fBUnlock\fP ()"
.br
.ti -1c
.RI "void \fBAssertHeld\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCondVar\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file port_example\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::port::Mutex::Mutex ()"

.PP
Definition at line 22 of file port_posix\&.cc\&.
.SS "leveldb::port::Mutex::~Mutex ()"

.PP
Definition at line 24 of file port_posix\&.cc\&.
.SS "leveldb::port::Mutex::Mutex ()"

.SS "leveldb::port::Mutex::~Mutex ()"

.SS "leveldb::port::Mutex::Mutex ()"

.SS "leveldb::port::Mutex::~Mutex ()"

.SH "Member Function Documentation"
.PP 
.SS "void leveldb::port::Mutex::AssertHeld ()"

.PP
Definition at line 65 of file port_win\&.cc\&.
.SS "void leveldb::port::Mutex::AssertHeld ()"

.SS "void leveldb::port::Mutex::AssertHeld ()\fC [inline]\fP"

.PP
Definition at line 89 of file port_posix\&.h\&.
.SS "void leveldb::port::Mutex::Lock ()"

.PP
Definition at line 26 of file port_posix\&.cc\&.
.SS "void leveldb::port::Mutex::Lock ()"

.SS "void leveldb::port::Mutex::Lock ()"

.SS "void leveldb::port::Mutex::Unlock ()"

.PP
Definition at line 28 of file port_posix\&.cc\&.
.SS "void leveldb::port::Mutex::Unlock ()"

.SS "void leveldb::port::Mutex::Unlock ()"

.SH "Friends And Related Function Documentation"
.PP 
.SS "\fBCondVar\fP\fC [friend]\fP"

.PP
Definition at line 92 of file port_posix\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
