.TH "leveldb::Table" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::Table \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <table\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRep\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~Table\fP ()"
.br
.ti -1c
.RI "\fBIterator\fP * \fBNewIterator\fP (const \fBReadOptions\fP &) const "
.br
.ti -1c
.RI "\fBuint64_t\fP \fBApproximateOffsetOf\fP (const \fBSlice\fP &key) const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBStatus\fP \fBOpen\fP (const \fBOptions\fP &options, \fBRandomAccessFile\fP *file, \fBuint64_t\fP file_size, \fBTable\fP **table)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTableCache\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file table\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::Table::~Table ()"

.PP
Definition at line 143 of file table\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBuint64_t\fP leveldb::Table::ApproximateOffsetOf (const \fBSlice\fP & key) const"

.PP
Definition at line 258 of file table\&.cc\&.
.SS "\fBIterator\fP * leveldb::Table::NewIterator (const \fBReadOptions\fP & options) const"

.PP
Definition at line 220 of file table\&.cc\&.
.SS "\fBStatus\fP leveldb::Table::Open (const \fBOptions\fP & options, \fBRandomAccessFile\fP * file, \fBuint64_t\fP file_size, \fBTable\fP ** table)\fC [static]\fP"

.PP
Definition at line 38 of file table\&.cc\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBTableCache\fP\fC [friend]\fP"

.PP
Definition at line 68 of file table\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
