.TH "leveldb::BloomTest" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::BloomTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBloomTest\fP ()"
.br
.ti -1c
.RI "\fB~BloomTest\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (const \fBSlice\fP &s)"
.br
.ti -1c
.RI "void \fBBuild\fP ()"
.br
.ti -1c
.RI "size_t \fBFilterSize\fP () const "
.br
.ti -1c
.RI "void \fBDumpFilter\fP ()"
.br
.ti -1c
.RI "bool \fBMatches\fP (const \fBSlice\fP &s)"
.br
.ti -1c
.RI "double \fBFalsePositiveRate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file bloom_test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::BloomTest::BloomTest ()\fC [inline]\fP"

.PP
Definition at line 28 of file bloom_test\&.cc\&.
.SS "leveldb::BloomTest::~BloomTest ()\fC [inline]\fP"

.PP
Definition at line 30 of file bloom_test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::BloomTest::Add (const \fBSlice\fP & s)\fC [inline]\fP"

.PP
Definition at line 39 of file bloom_test\&.cc\&.
.SS "void leveldb::BloomTest::Build ()\fC [inline]\fP"

.PP
Definition at line 43 of file bloom_test\&.cc\&.
.SS "void leveldb::BloomTest::DumpFilter ()\fC [inline]\fP"

.PP
Definition at line 58 of file bloom_test\&.cc\&.
.SS "double leveldb::BloomTest::FalsePositiveRate ()\fC [inline]\fP"

.PP
Definition at line 76 of file bloom_test\&.cc\&.
.SS "size_t leveldb::BloomTest::FilterSize () const\fC [inline]\fP"

.PP
Definition at line 54 of file bloom_test\&.cc\&.
.SS "bool leveldb::BloomTest::Matches (const \fBSlice\fP & s)\fC [inline]\fP"

.PP
Definition at line 69 of file bloom_test\&.cc\&.
.SS "void leveldb::BloomTest::Reset ()\fC [inline]\fP"

.PP
Definition at line 34 of file bloom_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
