.TH "leveldb::DBImpl::CompactionState::Output" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::DBImpl::CompactionState::Output \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint64_t\fP \fBnumber\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBfile_size\fP"
.br
.ti -1c
.RI "\fBInternalKey\fP \fBsmallest\fP"
.br
.ti -1c
.RI "\fBInternalKey\fP \fBlargest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 61 of file db_impl\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint64_t\fP leveldb::DBImpl::CompactionState::Output::file_size"

.PP
Definition at line 63 of file db_impl\&.cc\&.
.SS "\fBInternalKey\fP leveldb::DBImpl::CompactionState::Output::largest"

.PP
Definition at line 64 of file db_impl\&.cc\&.
.SS "\fBuint64_t\fP leveldb::DBImpl::CompactionState::Output::number"

.PP
Definition at line 62 of file db_impl\&.cc\&.
.SS "\fBInternalKey\fP leveldb::DBImpl::CompactionState::Output::smallest"

.PP
Definition at line 64 of file db_impl\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
