.TH "leveldb::test::ErrorEnv" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::test::ErrorEnv \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <testutil\&.h>\fP
.PP
Inherits \fBleveldb::EnvWrapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBErrorEnv\fP ()"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBNewWritableFile\fP (const std::string &fname, \fBWritableFile\fP **result)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBwritable_file_error_\fP"
.br
.ti -1c
.RI "int \fBnum_writable_file_errors_\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 30 of file testutil\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::test::ErrorEnv::ErrorEnv ()\fC [inline]\fP"

.PP
Definition at line 35 of file testutil\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBStatus\fP leveldb::test::ErrorEnv::NewWritableFile (const std::string & fname, \fBWritableFile\fP ** result)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBleveldb::EnvWrapper\fP\&.
.PP
Definition at line 39 of file testutil\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int leveldb::test::ErrorEnv::num_writable_file_errors_"

.PP
Definition at line 33 of file testutil\&.h\&.
.SS "bool leveldb::test::ErrorEnv::writable_file_error_"

.PP
Definition at line 32 of file testutil\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
