.TH "leveldb::SnapshotList" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::SnapshotList \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <snapshot\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSnapshotList\fP ()"
.br
.ti -1c
.RI "bool \fBempty\fP () const "
.br
.ti -1c
.RI "\fBSnapshotImpl\fP * \fBoldest\fP () const "
.br
.ti -1c
.RI "\fBSnapshotImpl\fP * \fBnewest\fP () const "
.br
.ti -1c
.RI "const \fBSnapshotImpl\fP * \fBNew\fP (\fBSequenceNumber\fP seq)"
.br
.ti -1c
.RI "void \fBDelete\fP (const \fBSnapshotImpl\fP *s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file snapshot\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::SnapshotList::SnapshotList ()\fC [inline]\fP"

.PP
Definition at line 32 of file snapshot\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::SnapshotList::Delete (const \fBSnapshotImpl\fP * s)\fC [inline]\fP"

.PP
Definition at line 52 of file snapshot\&.h\&.
.SS "bool leveldb::SnapshotList::empty () const\fC [inline]\fP"

.PP
Definition at line 37 of file snapshot\&.h\&.
.SS "const \fBSnapshotImpl\fP* leveldb::SnapshotList::New (\fBSequenceNumber\fP seq)\fC [inline]\fP"

.PP
Definition at line 41 of file snapshot\&.h\&.
.SS "\fBSnapshotImpl\fP* leveldb::SnapshotList::newest () const\fC [inline]\fP"

.PP
Definition at line 39 of file snapshot\&.h\&.
.SS "\fBSnapshotImpl\fP* leveldb::SnapshotList::oldest () const\fC [inline]\fP"

.PP
Definition at line 38 of file snapshot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
