.TH "leveldb::log::Reader" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::log::Reader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <log_reader\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBReporter\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReader\fP (\fBSequentialFile\fP *file, \fBReporter\fP *reporter, bool checksum, \fBuint64_t\fP initial_offset)"
.br
.ti -1c
.RI "\fB~Reader\fP ()"
.br
.ti -1c
.RI "bool \fBReadRecord\fP (\fBSlice\fP *record, std::string *scratch)"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBLastRecordOffset\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file log_reader\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::log::Reader::Reader (\fBSequentialFile\fP * file, \fBReporter\fP * reporter, bool checksum, \fBuint64_t\fP initial_offset)"

.PP
Definition at line 18 of file log_reader\&.cc\&.
.SS "leveldb::log::Reader::~Reader ()"

.PP
Definition at line 31 of file log_reader\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBuint64_t\fP leveldb::log::Reader::LastRecordOffset ()"

.PP
Definition at line 166 of file log_reader\&.cc\&.
.SS "bool leveldb::log::Reader::ReadRecord (\fBSlice\fP * record, std::string * scratch)"

.PP
Definition at line 59 of file log_reader\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
