.TH "leveldb::SnapshotImpl" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::SnapshotImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <snapshot\&.h>\fP
.PP
Inherits \fBleveldb::Snapshot\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSequenceNumber\fP \fBnumber_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSnapshotList\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file snapshot\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBSnapshotList\fP\fC [friend]\fP"

.PP
Definition at line 21 of file snapshot\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSequenceNumber\fP leveldb::SnapshotImpl::number_"

.PP
Definition at line 18 of file snapshot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
