.TH "leveldb::Footer" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::Footer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <format\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBkEncodedLength\fP = 2*BlockHandle::kMaxEncodedLength + 8 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFooter\fP ()"
.br
.ti -1c
.RI "const \fBBlockHandle\fP & \fBmetaindex_handle\fP () const "
.br
.ti -1c
.RI "void \fBset_metaindex_handle\fP (const \fBBlockHandle\fP &h)"
.br
.ti -1c
.RI "const \fBBlockHandle\fP & \fBindex_handle\fP () const "
.br
.ti -1c
.RI "void \fBset_index_handle\fP (const \fBBlockHandle\fP &h)"
.br
.ti -1c
.RI "void \fBEncodeTo\fP (std::string *dst) const "
.br
.ti -1c
.RI "\fBStatus\fP \fBDecodeFrom\fP (\fBSlice\fP *input)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file format\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIkEncodedLength \fP\fP
.PP
Definition at line 69 of file format\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::Footer::Footer ()\fC [inline]\fP"

.PP
Definition at line 49 of file format\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBStatus\fP leveldb::Footer::DecodeFrom (\fBSlice\fP * input)"

.PP
Definition at line 44 of file format\&.cc\&.
.SS "void leveldb::Footer::EncodeTo (std::string * dst) const"

.PP
Definition at line 32 of file format\&.cc\&.
.SS "const \fBBlockHandle\fP& leveldb::Footer::index_handle () const\fC [inline]\fP"

.PP
Definition at line 56 of file format\&.h\&.
.SS "const \fBBlockHandle\fP& leveldb::Footer::metaindex_handle () const\fC [inline]\fP"

.PP
Definition at line 52 of file format\&.h\&.
.SS "void leveldb::Footer::set_index_handle (const \fBBlockHandle\fP & h)\fC [inline]\fP"

.PP
Definition at line 59 of file format\&.h\&.
.SS "void leveldb::Footer::set_metaindex_handle (const \fBBlockHandle\fP & h)\fC [inline]\fP"

.PP
Definition at line 53 of file format\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
