.TH "leveldb::DBImpl" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::DBImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <db_impl\&.h>\fP
.PP
Inherits \fBleveldb::DB\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCompactionState\fP"
.br
.ti -1c
.RI "struct \fBWriter\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDBImpl\fP (const \fBOptions\fP &options, const std::string &dbname)"
.br
.ti -1c
.RI "virtual \fB~DBImpl\fP ()"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBPut\fP (const \fBWriteOptions\fP &, const \fBSlice\fP &key, const \fBSlice\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBDelete\fP (const \fBWriteOptions\fP &, const \fBSlice\fP &key)"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBWrite\fP (const \fBWriteOptions\fP &options, \fBWriteBatch\fP *updates)"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBGet\fP (const \fBReadOptions\fP &options, const \fBSlice\fP &key, std::string *\fBvalue\fP)"
.br
.ti -1c
.RI "virtual \fBIterator\fP * \fBNewIterator\fP (const \fBReadOptions\fP &)"
.br
.ti -1c
.RI "virtual const \fBSnapshot\fP * \fBGetSnapshot\fP ()"
.br
.ti -1c
.RI "virtual void \fBReleaseSnapshot\fP (const \fBSnapshot\fP *snapshot)"
.br
.ti -1c
.RI "virtual bool \fBGetProperty\fP (const \fBSlice\fP &property, std::string *\fBvalue\fP)"
.br
.ti -1c
.RI "virtual void \fBGetApproximateSizes\fP (const \fBRange\fP *range, int n, \fBuint64_t\fP *sizes)"
.br
.ti -1c
.RI "virtual void \fBCompactRange\fP (const \fBSlice\fP *begin, const \fBSlice\fP *end)"
.br
.ti -1c
.RI "void \fBTEST_CompactRange\fP (int level, const \fBSlice\fP *begin, const \fBSlice\fP *end)"
.br
.ti -1c
.RI "\fBStatus\fP \fBTEST_CompactMemTable\fP ()"
.br
.ti -1c
.RI "\fBIterator\fP * \fBTEST_NewInternalIterator\fP ()"
.br
.ti -1c
.RI "\fBint64_t\fP \fBTEST_MaxNextLevelOverlappingBytes\fP ()"
.br
.ti -1c
.RI "void \fBRecordReadSample\fP (\fBSlice\fP key)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBDB\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file db_impl\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::DBImpl::DBImpl (const \fBOptions\fP & options, const std::string & dbname)"

.PP
Definition at line 116 of file db_impl\&.cc\&.
.SS "leveldb::DBImpl::~DBImpl ()\fC [virtual]\fP"

.PP
Definition at line 148 of file db_impl\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::DBImpl::CompactRange (const \fBSlice\fP * begin, const \fBSlice\fP * end)\fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 536 of file db_impl\&.cc\&.
.SS "\fBStatus\fP leveldb::DBImpl::Delete (const \fBWriteOptions\fP & options, const \fBSlice\fP & key)\fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1158 of file db_impl\&.cc\&.
.SS "\fBStatus\fP leveldb::DBImpl::Get (const \fBReadOptions\fP & options, const \fBSlice\fP & key, std::string * value)\fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1077 of file db_impl\&.cc\&.
.SS "void leveldb::DBImpl::GetApproximateSizes (const \fBRange\fP * range, int n, \fBuint64_t\fP * sizes)\fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1403 of file db_impl\&.cc\&.
.SS "bool leveldb::DBImpl::GetProperty (const \fBSlice\fP & property, std::string * value)\fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1349 of file db_impl\&.cc\&.
.SS "const \fBSnapshot\fP * leveldb::DBImpl::GetSnapshot ()\fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1143 of file db_impl\&.cc\&.
.SS "\fBIterator\fP * leveldb::DBImpl::NewIterator (const \fBReadOptions\fP & options)\fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1124 of file db_impl\&.cc\&.
.SS "\fBStatus\fP leveldb::DBImpl::Put (const \fBWriteOptions\fP & o, const \fBSlice\fP & key, const \fBSlice\fP & value)\fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1154 of file db_impl\&.cc\&.
.SS "void leveldb::DBImpl::RecordReadSample (\fBSlice\fP key)"

.PP
Definition at line 1136 of file db_impl\&.cc\&.
.SS "void leveldb::DBImpl::ReleaseSnapshot (const \fBSnapshot\fP * snapshot)\fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1148 of file db_impl\&.cc\&.
.SS "\fBStatus\fP leveldb::DBImpl::TEST_CompactMemTable ()"

.PP
Definition at line 590 of file db_impl\&.cc\&.
.SS "void leveldb::DBImpl::TEST_CompactRange (int level, const \fBSlice\fP * begin, const \fBSlice\fP * end)"

.PP
Definition at line 553 of file db_impl\&.cc\&.
.SS "\fBint64_t\fP leveldb::DBImpl::TEST_MaxNextLevelOverlappingBytes ()"

.PP
Definition at line 1072 of file db_impl\&.cc\&.
.SS "\fBIterator\fP * leveldb::DBImpl::TEST_NewInternalIterator ()"

.PP
Definition at line 1066 of file db_impl\&.cc\&.
.SS "\fBStatus\fP leveldb::DBImpl::Write (const \fBWriteOptions\fP & options, \fBWriteBatch\fP * updates)\fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1162 of file db_impl\&.cc\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBDB\fP\fC [friend]\fP"

.PP
Definition at line 68 of file db_impl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
