.TH "leveldb::Version::LevelFileNumIterator" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::Version::LevelFileNumIterator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBleveldb::Iterator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevelFileNumIterator\fP (const \fBInternalKeyComparator\fP &icmp, const std::vector< \fBFileMetaData\fP * > *flist)"
.br
.ti -1c
.RI "virtual bool \fBValid\fP () const "
.br
.ti -1c
.RI "virtual void \fBSeek\fP (const \fBSlice\fP &target)"
.br
.ti -1c
.RI "virtual void \fBSeekToFirst\fP ()"
.br
.ti -1c
.RI "virtual void \fBSeekToLast\fP ()"
.br
.ti -1c
.RI "virtual void \fBNext\fP ()"
.br
.ti -1c
.RI "virtual void \fBPrev\fP ()"
.br
.ti -1c
.RI "\fBSlice\fP \fBkey\fP () const "
.br
.ti -1c
.RI "\fBSlice\fP \fBvalue\fP () const "
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBstatus\fP () const "
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 154 of file version_set\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::Version::LevelFileNumIterator::LevelFileNumIterator (const \fBInternalKeyComparator\fP & icmp, const std::vector< \fBFileMetaData\fP * > * flist)\fC [inline]\fP"

.PP
Definition at line 156 of file version_set\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSlice\fP leveldb::Version::LevelFileNumIterator::key () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 184 of file version_set\&.cc\&.
.SS "virtual void leveldb::Version::LevelFileNumIterator::Next ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 172 of file version_set\&.cc\&.
.SS "virtual void leveldb::Version::LevelFileNumIterator::Prev ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 176 of file version_set\&.cc\&.
.SS "virtual void leveldb::Version::LevelFileNumIterator::Seek (const \fBSlice\fP & target)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 165 of file version_set\&.cc\&.
.SS "virtual void leveldb::Version::LevelFileNumIterator::SeekToFirst ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 168 of file version_set\&.cc\&.
.SS "virtual void leveldb::Version::LevelFileNumIterator::SeekToLast ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 169 of file version_set\&.cc\&.
.SS "virtual \fBStatus\fP leveldb::Version::LevelFileNumIterator::status () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 194 of file version_set\&.cc\&.
.SS "virtual bool leveldb::Version::LevelFileNumIterator::Valid () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 162 of file version_set\&.cc\&.
.SS "\fBSlice\fP leveldb::Version::LevelFileNumIterator::value () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::Iterator\fP\&.
.PP
Definition at line 188 of file version_set\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
