.TH "leveldb::crc32c" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::crc32c \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCRC\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP \fBExtend\fP (\fBuint32_t\fP crc, const char *buf, size_t size)"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBValue\fP (const char *data, size_t n)"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBMask\fP (\fBuint32_t\fP crc)"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBUnmask\fP (\fBuint32_t\fP masked_crc)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCRC\fP, StandardResults)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCRC\fP, Values)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCRC\fP, \fBExtend\fP)"
.br
.ti -1c
.RI "\fBTEST\fP (\fBCRC\fP, \fBMask\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBuint32_t\fP leveldb::crc32c::Extend (\fBuint32_t\fP crc, const char * buf, size_t size)"

.PP
Definition at line 286 of file crc32c\&.cc\&.
.SS "\fBuint32_t\fP leveldb::crc32c::Mask (\fBuint32_t\fP crc)\fC [inline]\fP"

.PP
Definition at line 31 of file crc32c\&.h\&.
.SS "leveldb::crc32c::TEST (\fBCRC\fP, StandardResults)"

.PP
Definition at line 13 of file crc32c_test\&.cc\&.
.SS "leveldb::crc32c::TEST (\fBCRC\fP, Values)"

.PP
Definition at line 50 of file crc32c_test\&.cc\&.
.SS "leveldb::crc32c::TEST (\fBCRC\fP, \fBExtend\fP)"

.PP
Definition at line 54 of file crc32c_test\&.cc\&.
.SS "leveldb::crc32c::TEST (\fBCRC\fP, \fBMask\fP)"

.PP
Definition at line 59 of file crc32c_test\&.cc\&.
.SS "\fBuint32_t\fP leveldb::crc32c::Unmask (\fBuint32_t\fP masked_crc)\fC [inline]\fP"

.PP
Definition at line 37 of file crc32c\&.h\&.
.SS "\fBuint32_t\fP leveldb::crc32c::Value (const char * data, size_t n)\fC [inline]\fP"

.PP
Definition at line 20 of file crc32c\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
