.TH "leveldb::Arena" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::Arena \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arena\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArena\fP ()"
.br
.ti -1c
.RI "\fB~Arena\fP ()"
.br
.ti -1c
.RI "char * \fBAllocate\fP (size_t bytes)"
.br
.ti -1c
.RI "char * \fBAllocateAligned\fP (size_t bytes)"
.br
.ti -1c
.RI "size_t \fBMemoryUsage\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file arena\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::Arena::Arena ()"

.PP
Definition at line 12 of file arena\&.cc\&.
.SS "leveldb::Arena::~Arena ()"

.PP
Definition at line 18 of file arena\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "char * leveldb::Arena::Allocate (size_t bytes)\fC [inline]\fP"

.PP
Definition at line 52 of file arena\&.h\&.
.SS "char * leveldb::Arena::AllocateAligned (size_t bytes)"

.PP
Definition at line 42 of file arena\&.cc\&.
.SS "size_t leveldb::Arena::MemoryUsage () const\fC [inline]\fP"

.PP
Definition at line 29 of file arena\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
