.TH "leveldb::ModelDB" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::ModelDB \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBleveldb::DB\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBModelSnapshot\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModelDB\fP (const \fBOptions\fP &options)"
.br
.ti -1c
.RI "\fB~ModelDB\fP ()"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBPut\fP (const \fBWriteOptions\fP &o, const \fBSlice\fP &k, const \fBSlice\fP &v)"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBDelete\fP (const \fBWriteOptions\fP &o, const \fBSlice\fP &key)"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBGet\fP (const \fBReadOptions\fP &options, const \fBSlice\fP &key, std::string *\fBvalue\fP)"
.br
.ti -1c
.RI "virtual \fBIterator\fP * \fBNewIterator\fP (const \fBReadOptions\fP &options)"
.br
.ti -1c
.RI "virtual const \fBSnapshot\fP * \fBGetSnapshot\fP ()"
.br
.ti -1c
.RI "virtual void \fBReleaseSnapshot\fP (const \fBSnapshot\fP *snapshot)"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBWrite\fP (const \fBWriteOptions\fP &options, \fBWriteBatch\fP *batch)"
.br
.ti -1c
.RI "virtual bool \fBGetProperty\fP (const \fBSlice\fP &property, std::string *\fBvalue\fP)"
.br
.ti -1c
.RI "virtual void \fBGetApproximateSizes\fP (const \fBRange\fP *r, int n, \fBuint64_t\fP *sizes)"
.br
.ti -1c
.RI "virtual void \fBCompactRange\fP (const \fBSlice\fP *\fBstart\fP, const \fBSlice\fP *end)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1831 of file db_test\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::ModelDB::ModelDB (const \fBOptions\fP & options)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 1838 of file db_test\&.cc\&.
.SS "leveldb::ModelDB::~ModelDB ()\fC [inline]\fP"

.PP
Definition at line 1839 of file db_test\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void leveldb::ModelDB::CompactRange (const \fBSlice\fP * start, const \fBSlice\fP * end)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1895 of file db_test\&.cc\&.
.SS "virtual \fBStatus\fP leveldb::ModelDB::Delete (const \fBWriteOptions\fP & o, const \fBSlice\fP & key)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1843 of file db_test\&.cc\&.
.SS "virtual \fBStatus\fP leveldb::ModelDB::Get (const \fBReadOptions\fP & options, const \fBSlice\fP & key, std::string * value)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1846 of file db_test\&.cc\&.
.SS "virtual void leveldb::ModelDB::GetApproximateSizes (const \fBRange\fP * r, int n, \fBuint64_t\fP * sizes)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1890 of file db_test\&.cc\&.
.SS "virtual bool leveldb::ModelDB::GetProperty (const \fBSlice\fP & property, std::string * value)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1887 of file db_test\&.cc\&.
.SS "virtual const \fBSnapshot\fP* leveldb::ModelDB::GetSnapshot ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1862 of file db_test\&.cc\&.
.SS "virtual \fBIterator\fP* leveldb::ModelDB::NewIterator (const \fBReadOptions\fP & options)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1851 of file db_test\&.cc\&.
.SS "virtual \fBStatus\fP leveldb::ModelDB::Put (const \fBWriteOptions\fP & o, const \fBSlice\fP & k, const \fBSlice\fP & v)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1840 of file db_test\&.cc\&.
.SS "virtual void leveldb::ModelDB::ReleaseSnapshot (const \fBSnapshot\fP * snapshot)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1868 of file db_test\&.cc\&.
.SS "virtual \fBStatus\fP leveldb::ModelDB::Write (const \fBWriteOptions\fP & options, \fBWriteBatch\fP * batch)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::DB\fP\&.
.PP
Definition at line 1871 of file db_test\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
