.TH "leveldb::Random" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::Random \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <random\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandom\fP (\fBuint32_t\fP s)"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBNext\fP ()"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBUniform\fP (int n)"
.br
.ti -1c
.RI "bool \fBOneIn\fP (int n)"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBSkewed\fP (int max_log)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file random\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::Random::Random (\fBuint32_t\fP s)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 19 of file random\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBuint32_t\fP leveldb::Random::Next ()\fC [inline]\fP"

.PP
Definition at line 25 of file random\&.h\&.
.SS "bool leveldb::Random::OneIn (int n)\fC [inline]\fP"

.PP
Definition at line 52 of file random\&.h\&.
.SS "\fBuint32_t\fP leveldb::Random::Skewed (int max_log)\fC [inline]\fP"

.PP
Definition at line 57 of file random\&.h\&.
.SS "\fBuint32_t\fP leveldb::Random::Uniform (int n)\fC [inline]\fP"

.PP
Definition at line 48 of file random\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
