.TH "leveldb::test::Tester" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::test::Tester \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <testharness\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTester\fP (const char *f, int l)"
.br
.ti -1c
.RI "\fB~Tester\fP ()"
.br
.ti -1c
.RI "\fBTester\fP & \fBIs\fP (bool b, const char *msg)"
.br
.ti -1c
.RI "\fBTester\fP & \fBIsOk\fP (const \fBStatus\fP &s)"
.br
.ti -1c
.RI "template<class V > \fBTester\fP & \fBoperator<<\fP (const V &\fBvalue\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file testharness\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::test::Tester::Tester (const char * f, int l)\fC [inline]\fP"

.PP
Definition at line 50 of file testharness\&.h\&.
.SS "leveldb::test::Tester::~Tester ()\fC [inline]\fP"

.PP
Definition at line 54 of file testharness\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBTester\fP& leveldb::test::Tester::Is (bool b, const char * msg)\fC [inline]\fP"

.PP
Definition at line 61 of file testharness\&.h\&.
.SS "\fBTester\fP& leveldb::test::Tester::IsOk (const \fBStatus\fP & s)\fC [inline]\fP"

.PP
Definition at line 69 of file testharness\&.h\&.
.SS "template<class V > \fBTester\fP& leveldb::test::Tester::operator<< (const V & value)\fC [inline]\fP"

.PP
Definition at line 97 of file testharness\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
