.TH "leveldb::Iterator" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::Iterator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <iterator\&.h>\fP
.PP
Inherited by \fBleveldb::Block::Iter\fP, \fBleveldb::KeyConvertingIterator\fP, \fBleveldb::MemTableIterator\fP, and \fBleveldb::Version::LevelFileNumIterator\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef void(* \fBCleanupFunction\fP) (void *arg1, void *arg2)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIterator\fP ()"
.br
.ti -1c
.RI "virtual \fB~Iterator\fP ()"
.br
.ti -1c
.RI "virtual bool \fBValid\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBSeekToFirst\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBSeekToLast\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBSeek\fP (const \fBSlice\fP &target)=0"
.br
.ti -1c
.RI "virtual void \fBNext\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBPrev\fP ()=0"
.br
.ti -1c
.RI "virtual \fBSlice\fP \fBkey\fP () const =0"
.br
.ti -1c
.RI "virtual \fBSlice\fP \fBvalue\fP () const =0"
.br
.ti -1c
.RI "virtual \fBStatus\fP \fBstatus\fP () const =0"
.br
.ti -1c
.RI "void \fBRegisterCleanup\fP (\fBCleanupFunction\fP \fBfunction\fP, void *arg1, void *arg2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file iterator\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef void(* leveldb::Iterator::CleanupFunction) (void *arg1, void *arg2)"

.PP
Definition at line 75 of file iterator\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::Iterator::Iterator ()"

.PP
Definition at line 9 of file iterator\&.cc\&.
.SS "leveldb::Iterator::~Iterator ()\fC [virtual]\fP"

.PP
Definition at line 14 of file iterator\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBSlice\fP leveldb::Iterator::key () const\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::KeyConvertingIterator\fP, \fBleveldb::Version::LevelFileNumIterator\fP, \fBleveldb::Block::Iter\fP, and \fBleveldb::MemTableIterator\fP\&.
.SS "virtual void leveldb::Iterator::Next ()\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::KeyConvertingIterator\fP, \fBleveldb::Version::LevelFileNumIterator\fP, \fBleveldb::Block::Iter\fP, and \fBleveldb::MemTableIterator\fP\&.
.SS "virtual void leveldb::Iterator::Prev ()\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::KeyConvertingIterator\fP, \fBleveldb::Version::LevelFileNumIterator\fP, \fBleveldb::Block::Iter\fP, and \fBleveldb::MemTableIterator\fP\&.
.SS "void leveldb::Iterator::RegisterCleanup (\fBCleanupFunction\fP function, void * arg1, void * arg2)"

.PP
Definition at line 26 of file iterator\&.cc\&.
.SS "virtual void leveldb::Iterator::Seek (const \fBSlice\fP & target)\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::KeyConvertingIterator\fP, \fBleveldb::Version::LevelFileNumIterator\fP, \fBleveldb::Block::Iter\fP, and \fBleveldb::MemTableIterator\fP\&.
.SS "virtual void leveldb::Iterator::SeekToFirst ()\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::KeyConvertingIterator\fP, \fBleveldb::Block::Iter\fP, \fBleveldb::Version::LevelFileNumIterator\fP, and \fBleveldb::MemTableIterator\fP\&.
.SS "virtual void leveldb::Iterator::SeekToLast ()\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::KeyConvertingIterator\fP, \fBleveldb::Block::Iter\fP, \fBleveldb::Version::LevelFileNumIterator\fP, and \fBleveldb::MemTableIterator\fP\&.
.SS "virtual \fBStatus\fP leveldb::Iterator::status () const\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::KeyConvertingIterator\fP, \fBleveldb::Version::LevelFileNumIterator\fP, \fBleveldb::Block::Iter\fP, and \fBleveldb::MemTableIterator\fP\&.
.SS "virtual bool leveldb::Iterator::Valid () const\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::KeyConvertingIterator\fP, \fBleveldb::Version::LevelFileNumIterator\fP, \fBleveldb::Block::Iter\fP, and \fBleveldb::MemTableIterator\fP\&.
.SS "virtual \fBSlice\fP leveldb::Iterator::value () const\fC [pure virtual]\fP"

.PP
Implemented in \fBleveldb::KeyConvertingIterator\fP, \fBleveldb::Version::LevelFileNumIterator\fP, \fBleveldb::Block::Iter\fP, and \fBleveldb::MemTableIterator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
