.TH "leveldb::Version" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::Version \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <version_set\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBGetStats\fP"
.br
.ti -1c
.RI "class \fBLevelFileNumIterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddIterators\fP (const \fBReadOptions\fP &, std::vector< \fBIterator\fP * > *iters)"
.br
.ti -1c
.RI "\fBStatus\fP \fBGet\fP (const \fBReadOptions\fP &, const \fBLookupKey\fP &key, std::string *val, \fBGetStats\fP *\fBstats\fP)"
.br
.ti -1c
.RI "bool \fBUpdateStats\fP (const \fBGetStats\fP &\fBstats\fP)"
.br
.ti -1c
.RI "bool \fBRecordReadSample\fP (\fBSlice\fP key)"
.br
.ti -1c
.RI "void \fBRef\fP ()"
.br
.ti -1c
.RI "void \fBUnref\fP ()"
.br
.ti -1c
.RI "void \fBGetOverlappingInputs\fP (int level, const \fBInternalKey\fP *begin, const \fBInternalKey\fP *end, std::vector< \fBFileMetaData\fP * > *inputs)"
.br
.ti -1c
.RI "bool \fBOverlapInLevel\fP (int level, const \fBSlice\fP *smallest_user_key, const \fBSlice\fP *largest_user_key)"
.br
.ti -1c
.RI "int \fBPickLevelForMemTableOutput\fP (const \fBSlice\fP &smallest_user_key, const \fBSlice\fP &largest_user_key)"
.br
.ti -1c
.RI "int \fBNumFiles\fP (int level) const "
.br
.ti -1c
.RI "std::string \fBDebugString\fP () const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCompaction\fP"
.br
.ti -1c
.RI "class \fBVersionSet\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 59 of file version_set\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::Version::AddIterators (const \fBReadOptions\fP & options, std::vector< \fBIterator\fP * > * iters)"

.PP
Definition at line 225 of file version_set\&.cc\&.
.SS "std::string leveldb::Version::DebugString () const"

.PP
Definition at line 565 of file version_set\&.cc\&.
.SS "\fBStatus\fP leveldb::Version::Get (const \fBReadOptions\fP & options, const \fBLookupKey\fP & key, std::string * val, \fBGetStats\fP * stats)"

.PP
Definition at line 323 of file version_set\&.cc\&.
.SS "void leveldb::Version::GetOverlappingInputs (int level, const \fBInternalKey\fP * begin, const \fBInternalKey\fP * end, std::vector< \fBFileMetaData\fP * > * inputs)"

.PP
Definition at line 522 of file version_set\&.cc\&.
.SS "int leveldb::Version::NumFiles (int level) const\fC [inline]\fP"

.PP
Definition at line 111 of file version_set\&.h\&.
.SS "bool leveldb::Version::OverlapInLevel (int level, const \fBSlice\fP * smallest_user_key, const \fBSlice\fP * largest_user_key)"

.PP
Definition at line 486 of file version_set\&.cc\&.
.SS "int leveldb::Version::PickLevelForMemTableOutput (const \fBSlice\fP & smallest_user_key, const \fBSlice\fP & largest_user_key)"

.PP
Definition at line 493 of file version_set\&.cc\&.
.SS "bool leveldb::Version::RecordReadSample (\fBSlice\fP key)"

.PP
Definition at line 435 of file version_set\&.cc\&.
.SS "void leveldb::Version::Ref ()"

.PP
Definition at line 473 of file version_set\&.cc\&.
.SS "void leveldb::Version::Unref ()"

.PP
Definition at line 477 of file version_set\&.cc\&.
.SS "bool leveldb::Version::UpdateStats (const \fBGetStats\fP & stats)"

.PP
Definition at line 422 of file version_set\&.cc\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBCompaction\fP\fC [friend]\fP"

.PP
Definition at line 117 of file version_set\&.h\&.
.SS "friend class \fBVersionSet\fP\fC [friend]\fP"

.PP
Definition at line 118 of file version_set\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
