.TH "leveldb::VersionSet::Builder" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leveldb::VersionSet::Builder \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBuilder\fP (\fBVersionSet\fP *vset, \fBVersion\fP *\fBbase\fP)"
.br
.ti -1c
.RI "\fB~Builder\fP ()"
.br
.ti -1c
.RI "void \fBApply\fP (\fBVersionEdit\fP *edit)"
.br
.ti -1c
.RI "void \fBSaveTo\fP (\fBVersion\fP *v)"
.br
.ti -1c
.RI "void \fBMaybeAddFile\fP (\fBVersion\fP *v, int level, \fBFileMetaData\fP *f)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 594 of file version_set\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leveldb::VersionSet::Builder::Builder (\fBVersionSet\fP * vset, \fBVersion\fP * base)\fC [inline]\fP"

.PP
Definition at line 623 of file version_set\&.cc\&.
.SS "leveldb::VersionSet::Builder::~Builder ()\fC [inline]\fP"

.PP
Definition at line 634 of file version_set\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void leveldb::VersionSet::Builder::Apply (\fBVersionEdit\fP * edit)\fC [inline]\fP"

.PP
Definition at line 656 of file version_set\&.cc\&.
.SS "void leveldb::VersionSet::Builder::MaybeAddFile (\fBVersion\fP * v, int level, \fBFileMetaData\fP * f)\fC [inline]\fP"

.PP
Definition at line 750 of file version_set\&.cc\&.
.SS "void leveldb::VersionSet::Builder::SaveTo (\fBVersion\fP * v)\fC [inline]\fP"

.PP
Definition at line 702 of file version_set\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
