.TH "LimitedString< Limit >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LimitedString< Limit > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <serialize\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLimitedString\fP (std::string &\fBstring\fP)"
.br
.ti -1c
.RI "template<typename Stream > void \fBUnserialize\fP (Stream &s, int, int=0)"
.br
.ti -1c
.RI "template<typename Stream > void \fBSerialize\fP (Stream &s, int, int=0) const "
.br
.ti -1c
.RI "unsigned int \fBGetSerializeSize\fP (int, int=0) const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string & \fBstring\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<size_t Limit>class LimitedString< Limit >"

.PP
Definition at line 394 of file serialize\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<size_t Limit> \fBLimitedString\fP< Limit >::\fBLimitedString\fP (std::string & string)\fC [inline]\fP"

.PP
Definition at line 399 of file serialize\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<size_t Limit> unsigned int \fBLimitedString\fP< Limit >::GetSerializeSize (int, int = \fC0\fP) const\fC [inline]\fP"

.PP
Definition at line 421 of file serialize\&.h\&.
.SS "template<size_t Limit> template<typename Stream > void \fBLimitedString\fP< Limit >::Serialize (Stream & s, int, int = \fC0\fP) const\fC [inline]\fP"

.PP
Definition at line 414 of file serialize\&.h\&.
.SS "template<size_t Limit> template<typename Stream > void \fBLimitedString\fP< Limit >::Unserialize (Stream & s, int, int = \fC0\fP)\fC [inline]\fP"

.PP
Definition at line 402 of file serialize\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<size_t Limit> std::string& \fBLimitedString\fP< Limit >::string\fC [protected]\fP"

.PP
Definition at line 397 of file serialize\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
