.TH "LocalServiceInfo" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LocalServiceInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <net\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnScore\fP"
.br
.ti -1c
.RI "int \fBnPort\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 123 of file net\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int LocalServiceInfo::nPort"

.PP
Definition at line 125 of file net\&.h\&.
.SS "int LocalServiceInfo::nScore"

.PP
Definition at line 124 of file net\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
