.TH "/home/dev/ds-160209/src/leveldb/db/log_test.cc" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/db/log_test.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'db/log_reader\&.h'\fP
.br
\fC#include 'db/log_writer\&.h'\fP
.br
\fC#include 'leveldb/env\&.h'\fP
.br
\fC#include 'util/coding\&.h'\fP
.br
\fC#include 'util/crc32c\&.h'\fP
.br
\fC#include 'util/random\&.h'\fP
.br
\fC#include 'util/testharness\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBleveldb::log::LogTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.ti -1c
.RI " \fBleveldb::log\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, Empty)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ReadWrite)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ManyBlocks)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, Fragmentation)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, MarginalTrailer)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, MarginalTrailer2)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ShortTrailer)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, AlignedEof)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, RandomRead)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ReadError)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, BadRecordType)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, TruncatedTrailingRecordIsIgnored)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, BadLength)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, BadLengthAtEndIsIgnored)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ChecksumMismatch)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, UnexpectedMiddleType)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, UnexpectedLastType)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, UnexpectedFullType)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, UnexpectedFirstType)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, MissingLastIsIgnored)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, PartialLastIsIgnored)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ErrorJoinsRecords)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ReadStart)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ReadSecondOneOff)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ReadSecondTenThousand)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ReadSecondStart)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ReadThirdOneOff)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ReadThirdStart)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ReadFourthOneOff)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ReadFourthFirstBlockTrailer)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ReadFourthMiddleBlock)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ReadFourthLastBlock)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ReadFourthStart)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ReadEnd)"
.br
.ti -1c
.RI "\fBleveldb::log::TEST\fP (LogTest, ReadPastEnd)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 528 of file log_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
