.TH "/home/dev/ds-160209/src/leveldb/util/logging.cc" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/util/logging.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'util/logging\&.h'\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'leveldb/env\&.h'\fP
.br
\fC#include 'leveldb/slice\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBleveldb::AppendNumberTo\fP (std::string *str, \fBuint64_t\fP num)"
.br
.ti -1c
.RI "void \fBleveldb::AppendEscapedStringTo\fP (std::string *str, const Slice &\fBvalue\fP)"
.br
.ti -1c
.RI "std::string \fBleveldb::NumberToString\fP (\fBuint64_t\fP num)"
.br
.ti -1c
.RI "std::string \fBleveldb::EscapeString\fP (const Slice &\fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBleveldb::ConsumeDecimalNumber\fP (Slice *in, \fBuint64_t\fP *val)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
