.TH "LZ4_Data_Structure" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LZ4_Data_Structure \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBU32\fP \fBhashTable\fP [\fBHASHNBCELLS4\fP]"
.br
.ti -1c
.RI "const \fBBYTE\fP * \fBbufferStart\fP"
.br
.ti -1c
.RI "const \fBBYTE\fP * \fBbase\fP"
.br
.ti -1c
.RI "const \fBBYTE\fP * \fBnextBlock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 257 of file lz4\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "const \fBBYTE\fP* LZ4_Data_Structure::base"

.PP
Definition at line 260 of file lz4\&.c\&.
.SS "const \fBBYTE\fP* LZ4_Data_Structure::bufferStart"

.PP
Definition at line 259 of file lz4\&.c\&.
.SS "\fBU32\fP LZ4_Data_Structure::hashTable[\fBHASHNBCELLS4\fP]"

.PP
Definition at line 258 of file lz4\&.c\&.
.SS "const \fBBYTE\fP* LZ4_Data_Structure::nextBlock"

.PP
Definition at line 261 of file lz4\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
