.TH "/home/dev/ds-160209/src/qt/macdockiconhandler.mm" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/macdockiconhandler.mm \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'macdockiconhandler\&.h'\fP
.br
\fC#include <QImageWriter>\fP
.br
\fC#include <QMenu>\fP
.br
\fC#include <QBuffer>\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include <Cocoa/Cocoa\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDockIconClickEventHandler\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBqt_mac_set_dock_menu\fP (QMenu *)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void qt_mac_set_dock_menu (QMenu *)"

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
