.TH "MacDockIconHandler" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MacDockIconHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <macdockiconhandler\&.h>\fP
.PP
Inherits QObject\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBdockIconClicked\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~MacDockIconHandler\fP ()"
.br
.ti -1c
.RI "QMenu * \fBdockMenu\fP ()"
.br
.ti -1c
.RI "void \fBsetIcon\fP (const QIcon &icon)"
.br
.ti -1c
.RI "void \fBsetMainWindow\fP (QMainWindow *window)"
.br
.ti -1c
.RI "void \fBhandleDockIconClickEvent\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBMacDockIconHandler\fP * \fBinstance\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Macintosh-specific dock icon handler\&. 
.PP
Definition at line 21 of file macdockiconhandler\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MacDockIconHandler::~MacDockIconHandler ()"

.PP
Definition at line 69 of file macdockiconhandler\&.mm\&.
.SH "Member Function Documentation"
.PP 
.SS "void MacDockIconHandler::dockIconClicked ()\fC [signal]\fP"

.SS "QMenu * MacDockIconHandler::dockMenu ()"

.PP
Definition at line 76 of file macdockiconhandler\&.mm\&.
.SS "void MacDockIconHandler::handleDockIconClickEvent ()"

.PP
Definition at line 122 of file macdockiconhandler\&.mm\&.
.SS "\fBMacDockIconHandler\fP * MacDockIconHandler::instance ()\fC [static]\fP"

.PP
Definition at line 114 of file macdockiconhandler\&.mm\&.
.SS "void MacDockIconHandler::setIcon (const QIcon & icon)"

.PP
Definition at line 81 of file macdockiconhandler\&.mm\&.
.SS "void MacDockIconHandler::setMainWindow (QMainWindow * window)"

.PP
Definition at line 65 of file macdockiconhandler\&.mm\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
