.TH "/home/dev/ds-160209/src/main.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/main.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'txmempool\&.h'\fP
.br
\fC#include 'net\&.h'\fP
.br
\fC#include 'script\&.h'\fP
.br
\fC#include 'streams\&.h'\fP
.br
\fC#include 'txdb\&.h'\fP
.br
\fC#include 'chain\&.h'\fP
.br
\fC#include <list>\fP
.br
\fC#include <boost/unordered_map\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBlockHasher\fP"
.br
.ti -1c
.RI "struct \fBCNodeStateStats\fP"
.br
.ti -1c
.RI "class \fBCDiskTxPos\fP"
.br
.RI "\fIPosition on disk for a particular transaction\&. \fP"
.ti -1c
.RI "class \fBCTransactionPoS\fP"
.br
.ti -1c
.RI "class \fBCMerkleTx\fP"
.br
.ti -1c
.RI "class \fBCTxIndex\fP"
.br
.ti -1c
.RI "class \fBCValidationState\fP"
.br
.ti -1c
.RI "class \fBCWalletInterface\fP"
.br
.ti -1c
.RI "class \fBCBlockFileInfo\fP"
.br
.ti -1c
.RI "class \fBCVerifyDB\fP"
.br
.RI "\fIRAII wrapper for VerifyDB: Verify consistency of the block and coin databases\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::map< \fBuint256\fP, \fBCBlockIndex\fP *, \fBBlockHasher\fP > \fBBlockMap\fP"
.br
.ti -1c
.RI "typedef std::map< \fBuint256\fP, std::pair< \fBCTxIndex\fP, \fBCTransaction\fP > > \fBMapPrevTx\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBGetMinFee_mode\fP { \fBGMF_BLOCK\fP, \fBGMF_RELAY\fP, \fBGMF_SEND\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBGetNodeStateStats\fP (\fBNodeId\fP nodeid, \fBCNodeStateStats\fP &\fBstats\fP)"
.br
.ti -1c
.RI "void \fBRegisterWallet\fP (\fBCWalletInterface\fP *pwalletIn)"
.br
.ti -1c
.RI "void \fBUnregisterWallet\fP (\fBCWalletInterface\fP *pwalletIn)"
.br
.ti -1c
.RI "void \fBUnregisterAllWallets\fP ()"
.br
.ti -1c
.RI "void \fBSyncWithWallets\fP (const \fBCTransaction\fP &tx, const \fBCBlock\fP *pblock=NULL, bool fConnect=true)"
.br
.ti -1c
.RI "void \fBResendWalletTransactions\fP (bool fForce=false)"
.br
.ti -1c
.RI "void \fBRegisterNodeSignals\fP (\fBCNodeSignals\fP &nodeSignals)"
.br
.ti -1c
.RI "void \fBUnregisterNodeSignals\fP (\fBCNodeSignals\fP &nodeSignals)"
.br
.ti -1c
.RI "void \fBPushGetBlocks\fP (\fBCNode\fP *pnode, \fBCBlockIndex\fP *pindexBegin, \fBuint256\fP hashEnd)"
.br
.ti -1c
.RI "bool \fBProcessBlock\fP (\fBCNode\fP *pfrom, \fBCBlock\fP *pblock)"
.br
.ti -1c
.RI "bool \fBCheckDiskSpace\fP (\fBuint64_t\fP nAdditionalBytes=0)"
.br
.ti -1c
.RI "void \fBUnloadBlockIndex\fP ()"
.br
.RI "\fIUnload database information\&. \fP"
.ti -1c
.RI "bool \fBLoadBlockIndex\fP (bool fAllowNew=true)"
.br
.RI "\fILoad the block tree and coins database from disk */\&. \fP"
.ti -1c
.RI "bool \fBInitBlockIndex\fP ()"
.br
.RI "\fIInitialize a new block tree database + block data on disk\&. \fP"
.ti -1c
.RI "void \fBPrintBlockTree\fP ()"
.br
.ti -1c
.RI "bool \fBProcessMessages\fP (\fBCNode\fP *pfrom)"
.br
.ti -1c
.RI "bool \fBSendMessages\fP (\fBCNode\fP *pto, bool fSendTrickle)"
.br
.ti -1c
.RI "void \fBThreadImport\fP (std::vector< boost::filesystem::path > vImportFiles)"
.br
.ti -1c
.RI "bool \fBCheckProofOfWork\fP (\fBuint256\fP \fBhash\fP, unsigned int nBits)"
.br
.ti -1c
.RI "unsigned int \fBGetNextTargetRequired\fP (const \fBCBlockIndex\fP *pindexLast, bool fProofOfStake)"
.br
.ti -1c
.RI "\fBCAmount\fP \fBGetProofOfWorkReward\fP (\fBCAmount\fP nFees)"
.br
.ti -1c
.RI "bool \fBIsConfirmedInNPrevBlocks\fP (const \fBCTxIndex\fP &txindex, const \fBCBlockIndex\fP *pindexFrom, int nMaxDepth, int &nActualDepth)"
.br
.ti -1c
.RI "std::string \fBGetWarnings\fP (std::string strFor)"
.br
.ti -1c
.RI "bool \fBGetTransaction\fP (const \fBuint256\fP &\fBhash\fP, \fBCTransaction\fP &tx, \fBuint256\fP &hashBlock)"
.br
.RI "\fIReturn transaction in tx, and if it was found inside a block, its hash is placed in hashBlock\&. \fP"
.ti -1c
.RI "\fBuint256\fP \fBWantedByOrphan\fP (const \fBCOrphanBlock\fP *pblockOrphan)"
.br
.ti -1c
.RI "const \fBCBlockIndex\fP * \fBGetLastBlockIndex\fP (const \fBCBlockIndex\fP *pindex, bool fProofOfStake)"
.br
.ti -1c
.RI "void \fBThreadStakeMiner\fP (\fBCWallet\fP *pwallet)"
.br
.ti -1c
.RI "bool \fBAcceptToMemoryPool\fP (\fBCTxMemPool\fP &pool, \fBCValidationState\fP &\fBstate\fP, \fBCTransaction\fP &tx, bool fLimitFree, bool *pfMissingInputs, bool ignoreFees=false)"
.br
.RI "\fI(try to) add transaction to memory pool \fP"
.ti -1c
.RI "bool \fBAcceptableInputs\fP (\fBCTxMemPool\fP &pool, \fBCValidationState\fP &\fBstate\fP, \fBCTransaction\fP &tx, bool fLimitFree, bool *pfMissingInputs, bool fRejectInsaneFee=false, bool isSSTX=false)"
.br
.ti -1c
.RI "\fBCAmount\fP \fBGetBlockValue\fP (int nBits, int nHeight, const \fBCAmount\fP &nFees)"
.br
.ti -1c
.RI "bool \fBFindTransactionsByDestination\fP (const \fBCTxDestination\fP &dest, std::vector< \fBuint256\fP > &vtxhash)"
.br
.ti -1c
.RI "int \fBGetInputAge\fP (\fBCTxIn\fP &vin)"
.br
.ti -1c
.RI "bool \fBAbortNode\fP (const std::string &msg, const std::string &userMessage='')"
.br
.RI "\fIAbort with a message\&. \fP"
.ti -1c
.RI "void \fBMisbehaving\fP (\fBNodeId\fP nodeid, int howmuch)"
.br
.RI "\fIIncrease a node's misbehavior score\&. \fP"
.ti -1c
.RI "\fBCAmount\fP \fBGetStormnodePayment\fP (int nHeight, \fBCAmount\fP blockValue)"
.br
.ti -1c
.RI "int \fBGetInputAgeIX\fP (\fBuint256\fP nTXHash, \fBCTxIn\fP &vin)"
.br
.ti -1c
.RI "int \fBGetIXConfirmations\fP (\fBuint256\fP nTXHash)"
.br
.ti -1c
.RI "bool \fBDisconnectBlocksAndReprocess\fP (int blocks)"
.br
.ti -1c
.RI "void \fBFlushStateToDisk\fP ()"
.br
.ti -1c
.RI "boost::filesystem::path \fBGetBlockPosFilename\fP (const \fBCDiskBlockPos\fP &pos, const char *prefix)"
.br
.ti -1c
.RI "FILE * \fBOpenBlockFile\fP (unsigned int nFile, unsigned int nBlockPos, const char *pszMode)"
.br
.ti -1c
.RI "FILE * \fBOpenBlockFile\fP (const \fBCDiskBlockPos\fP &pos, bool fReadOnly=false)"
.br
.ti -1c
.RI "FILE * \fBOpenDiskFile\fP (const \fBCDiskBlockPos\fP &pos, const char *prefix, bool fReadOnly=false)"
.br
.ti -1c
.RI "FILE * \fBAppendBlockFile\fP (unsigned int &nFileRet)"
.br
.ti -1c
.RI "FILE * \fBOpenUndoFile\fP (const \fBCDiskBlockPos\fP &pos, bool fReadOnly=false)"
.br
.ti -1c
.RI "\fBCAmount\fP \fBGetMinFee\fP (const \fBCTransaction\fP &tx, unsigned int nBytes, bool fAllowFree, enum \fBGetMinFee_mode\fP mode)"
.br
.ti -1c
.RI "bool \fBAreInputsStandard\fP (const \fBCTransaction\fP &tx, const \fBMapPrevTx\fP &mapInputs)"
.br
.ti -1c
.RI "unsigned int \fBGetLegacySigOpCount\fP (const \fBCTransaction\fP &tx)"
.br
.ti -1c
.RI "unsigned int \fBGetP2SHSigOpCount\fP (const \fBCTransaction\fP &tx, const \fBMapPrevTx\fP &mapInputs)"
.br
.ti -1c
.RI "bool \fBIsStandardTx\fP (const \fBCTransaction\fP &tx, std::string &reason)"
.br
.ti -1c
.RI "bool \fBIsFinalTx\fP (const \fBCTransaction\fP &tx, int nBlockHeight=0, \fBint64_t\fP nBlockTime=0)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCScript\fP \fBCOINBASE_FLAGS\fP"
.br
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_main\fP"
.br
.ti -1c
.RI "\fBCTxMemPool\fP \fBmempool\fP"
.br
.ti -1c
.RI "std::map< \fBuint256\fP, \fBCBlockIndex\fP * > \fBmapBlockIndex\fP"
.br
.ti -1c
.RI "std::set< std::pair< \fBCOutPoint\fP, unsigned int > > \fBsetStakeSeen\fP"
.br
.ti -1c
.RI "\fBCBlockIndex\fP * \fBpindexGenesisBlock\fP"
.br
.ti -1c
.RI "int \fBnStakeMinConfirmations\fP"
.br
.ti -1c
.RI "unsigned int \fBnStakeMinAge\fP"
.br
.ti -1c
.RI "unsigned int \fBnNodeLifespan\fP"
.br
.ti -1c
.RI "int \fBnCoinbaseMaturity\fP"
.br
.ti -1c
.RI "int \fBnBestHeight\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBnBestChainTrust\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBnBestInvalidTrust\fP"
.br
.ti -1c
.RI "\fBuint256\fP \fBhashBestChain\fP"
.br
.ti -1c
.RI "\fBCBlockIndex\fP * \fBpindexBest\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBnLastBlockTx\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBnLastBlockSize\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnLastCoinStakeSearchInterval\fP"
.br
.ti -1c
.RI "const std::string \fBstrMessageMagic\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBnTimeBestReceived\fP"
.br
.ti -1c
.RI "bool \fBfImporting\fP"
.br
.ti -1c
.RI "bool \fBfReindex\fP"
.br
.ti -1c
.RI "std::map< \fBuint256\fP, \fBCOrphanBlock\fP * > \fBmapOrphanBlocks\fP"
.br
.ti -1c
.RI "bool \fBfTxIndex\fP"
.br
.ti -1c
.RI "unsigned int \fBnCoinCacheSize\fP"
.br
.ti -1c
.RI "bool \fBfUseFastIndex\fP"
.br
.ti -1c
.RI "unsigned int \fBnDerivationMethodIndex\fP"
.br
.ti -1c
.RI "bool \fBfMinimizeCoinAge\fP"
.br
.ti -1c
.RI "bool \fBfLargeWorkForkFound\fP"
.br
.ti -1c
.RI "bool \fBfLargeWorkInvalidChainFound\fP"
.br
.ti -1c
.RI "std::map< \fBuint256\fP, \fBint64_t\fP > \fBmapRejectedBlocks\fP"
.br
.ti -1c
.RI "\fBCFeeRate\fP \fBminRelayTxFee\fP"
.br
.ti -1c
.RI "\fBCCoinsViewCache\fP * \fBpcoinsTip\fP"
.br
.RI "\fIGlobal variable that points to the active \fBCCoinsView\fP (protected by cs_main) \fP"
.ti -1c
.RI "\fBCBlockTreeDB\fP * \fBpblocktree\fP"
.br
.RI "\fIGlobal variable that points to the active block tree (protected by cs_main) \fP"
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::map<\fBuint256\fP, \fBCBlockIndex\fP*, \fBBlockHasher\fP> \fBBlockMap\fP"

.PP
Definition at line 76 of file main\&.h\&.
.SS "typedef std::map<\fBuint256\fP, std::pair<\fBCTxIndex\fP, \fBCTransaction\fP> > \fBMapPrevTx\fP"

.PP
Definition at line 283 of file main\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBGetMinFee_mode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIGMF_BLOCK \fP\fP
.TP
\fB\fIGMF_RELAY \fP\fP
.TP
\fB\fIGMF_SEND \fP\fP
.PP
Definition at line 276 of file main\&.h\&.
.SH "Function Documentation"
.PP 
.SS "bool AbortNode (const std::string & msg, const std::string & userMessage = \fC''\fP)"

.PP
Abort with a message\&. 
.PP
Definition at line 478 of file main\&.cpp\&.
.SS "bool AcceptableInputs (\fBCTxMemPool\fP & pool, \fBCValidationState\fP & state, \fBCTransaction\fP & tx, bool fLimitFree, bool * pfMissingInputs, bool fRejectInsaneFee = \fCfalse\fP, bool isSSTX = \fCfalse\fP)"

.PP
Definition at line 1230 of file main\&.cpp\&.
.SS "bool AcceptToMemoryPool (\fBCTxMemPool\fP & pool, \fBCValidationState\fP & state, \fBCTransaction\fP & tx, bool fLimitFree, bool * pfMissingInputs, bool ignoreFees = \fCfalse\fP)"

.PP
(try to) add transaction to memory pool 
.PP
Definition at line 865 of file main\&.cpp\&.
.SS "FILE* AppendBlockFile (unsigned int & nFileRet)"

.PP
Definition at line 639 of file chain\&.cpp\&.
.SS "bool AreInputsStandard (const \fBCTransaction\fP & tx, const \fBMapPrevTx\fP & mapInputs)"
Check for standard transaction types 
.PP
\fBParameters:\fP
.RS 4
\fImapInputs\fP Map of previous transactions that have outputs we're spending 
.RE
.PP
\fBReturns:\fP
.RS 4
True if all inputs (scriptSigs) use only standard transaction forms 
.RE
.PP
\fBSee also:\fP
.RS 4
CTransaction::FetchInputs 
.RE
.PP

.PP
Definition at line 692 of file main\&.cpp\&.
.SS "bool CheckDiskSpace (\fBuint64_t\fP nAdditionalBytes = \fC0\fP)"

.PP
Definition at line 2024 of file main\&.cpp\&.
.SS "bool CheckProofOfWork (\fBuint256\fP hash, unsigned int nBits)"

.PP
Definition at line 57 of file block\&.cpp\&.
.SS "bool DisconnectBlocksAndReprocess (int blocks)"

.PP
Definition at line 1779 of file main\&.cpp\&.
.SS "bool FindTransactionsByDestination (const \fBCTxDestination\fP & dest, std::vector< \fBuint256\fP > & vtxhash)"

.PP
Definition at line 1792 of file main\&.cpp\&.
.SS "void FlushStateToDisk ()"

.PP
Definition at line 4120 of file main\&.cpp\&.
.SS "boost::filesystem::path GetBlockPosFilename (const \fBCDiskBlockPos\fP & pos, const char * prefix)"

.PP
Definition at line 4008 of file main\&.cpp\&.
.SS "\fBCAmount\fP GetBlockValue (int nBits, int nHeight, const \fBCAmount\fP & nFees)"

.PP
Definition at line 1725 of file main\&.cpp\&.
.SS "int GetInputAge (\fBCTxIn\fP & vin)"

.PP
Definition at line 1487 of file main\&.cpp\&.
.SS "int GetInputAgeIX (\fBuint256\fP nTXHash, \fBCTxIn\fP & vin)"

.PP
Definition at line 1506 of file main\&.cpp\&.
.SS "int GetIXConfirmations (\fBuint256\fP nTXHash)"

.PP
Definition at line 1525 of file main\&.cpp\&.
.SS "const \fBCBlockIndex\fP* GetLastBlockIndex (const \fBCBlockIndex\fP * pindex, bool fProofOfStake)"

.PP
Definition at line 1678 of file main\&.cpp\&.
.SS "unsigned int GetLegacySigOpCount (const \fBCTransaction\fP & tx)"
Count ECDSA signature operations the old-fashioned (pre-0\&.6) way 
.PP
\fBReturns:\fP
.RS 4
number of sigops this transaction's outputs will produce when spent 
.RE
.PP
\fBSee also:\fP
.RS 4
CTransaction::FetchInputs 
.RE
.PP

.PP
Definition at line 756 of file main\&.cpp\&.
.SS "\fBCAmount\fP GetMinFee (const \fBCTransaction\fP & tx, unsigned int nBytes, bool fAllowFree, enum \fBGetMinFee_mode\fP mode)"

.PP
Definition at line 831 of file main\&.cpp\&.
.SS "unsigned int GetNextTargetRequired (const \fBCBlockIndex\fP * pindexLast, bool fProofOfStake)"

.PP
Definition at line 1685 of file main\&.cpp\&.
.SS "bool GetNodeStateStats (\fBNodeId\fP nodeid, \fBCNodeStateStats\fP & stats)"
Get statistics from node state 
.PP
Definition at line 445 of file main\&.cpp\&.
.SS "unsigned int GetP2SHSigOpCount (const \fBCTransaction\fP & tx, const \fBMapPrevTx\fP & mapInputs)"
Count ECDSA signature operations in pay-to-script-hash inputs\&.
.PP
\fBParameters:\fP
.RS 4
\fImapInputs\fP Map of previous transactions that have outputs we're spending 
.RE
.PP
\fBReturns:\fP
.RS 4
maximum number of sigops required to validate this transaction's inputs 
.RE
.PP
\fBSee also:\fP
.RS 4
CTransaction::FetchInputs 
.RE
.PP

.PP
Definition at line 770 of file main\&.cpp\&.
.SS "\fBCAmount\fP GetProofOfWorkReward (\fBCAmount\fP nFees)"

.PP
Definition at line 1662 of file main\&.cpp\&.
.SS "\fBCAmount\fP GetStormnodePayment (int nHeight, \fBCAmount\fP blockValue)"

.PP
Definition at line 1733 of file main\&.cpp\&.
.SS "bool GetTransaction (const \fBuint256\fP & hash, \fBCTransaction\fP & tx, \fBuint256\fP & hashBlock)"

.PP
Return transaction in tx, and if it was found inside a block, its hash is placed in hashBlock\&. 
.PP
Definition at line 1557 of file main\&.cpp\&.
.SS "std::string GetWarnings (std::string strFor)"

.SS "bool InitBlockIndex ()"

.PP
Initialize a new block tree database + block data on disk\&. 
.PP
Definition at line 2106 of file main\&.cpp\&.
.SS "bool IsConfirmedInNPrevBlocks (const \fBCTxIndex\fP & txindex, const \fBCBlockIndex\fP * pindexFrom, int nMaxDepth, int & nActualDepth)"

.PP
Definition at line 1766 of file main\&.cpp\&.
.SS "bool IsFinalTx (const \fBCTransaction\fP & tx, int nBlockHeight = \fC0\fP, \fBint64_t\fP nBlockTime = \fC0\fP)"

.PP
Definition at line 665 of file main\&.cpp\&.
.SS "bool IsStandardTx (const \fBCTransaction\fP & tx, std::string & reason)"
Check for standard transaction types 
.PP
\fBReturns:\fP
.RS 4
True if all outputs (scriptPubKeys) use only standard transaction forms 
.RE
.PP

.SS "bool LoadBlockIndex (bool fAllowNew = \fCtrue\fP)"

.PP
Load the block tree and coins database from disk */\&. 
.PP
Definition at line 2068 of file main\&.cpp\&.
.SS "void Misbehaving (\fBNodeId\fP nodeid, int howmuch)"

.PP
Increase a node's misbehavior score\&. 
.PP
Definition at line 1741 of file main\&.cpp\&.
.SS "FILE* OpenBlockFile (unsigned int nFile, unsigned int nBlockPos, const char * pszMode)"

.PP
Definition at line 4036 of file main\&.cpp\&.
.SS "FILE* OpenBlockFile (const \fBCDiskBlockPos\fP & pos, bool fReadOnly = \fCfalse\fP)"

.PP
Definition at line 4054 of file main\&.cpp\&.
.SS "FILE* OpenDiskFile (const \fBCDiskBlockPos\fP & pos, const char * prefix, bool fReadOnly = \fCfalse\fP)"

.PP
Definition at line 4013 of file main\&.cpp\&.
.SS "FILE* OpenUndoFile (const \fBCDiskBlockPos\fP & pos, bool fReadOnly = \fCfalse\fP)"

.PP
Definition at line 4058 of file main\&.cpp\&.
.SS "void PrintBlockTree ()"

.PP
Definition at line 2146 of file main\&.cpp\&.
.SS "bool ProcessBlock (\fBCNode\fP * pfrom, \fBCBlock\fP * pblock)"

.PP
Definition at line 1885 of file main\&.cpp\&.
.SS "bool ProcessMessages (\fBCNode\fP * pfrom)"

.PP
Definition at line 3306 of file main\&.cpp\&.
.SS "void PushGetBlocks (\fBCNode\fP * pnode, \fBCBlockIndex\fP * pindexBegin, \fBuint256\fP hashEnd)"

.PP
Definition at line 1865 of file main\&.cpp\&.
.SS "void RegisterNodeSignals (\fBCNodeSignals\fP & nodeSignals)"
Register with a network node to receive its signals 
.PP
Definition at line 460 of file main\&.cpp\&.
.SS "void RegisterWallet (\fBCWalletInterface\fP * pwalletIn)"
Register a wallet to receive updates from core 
.PP
Definition at line 223 of file main\&.cpp\&.
.SS "void ResendWalletTransactions (bool fForce = \fCfalse\fP)"
Ask wallets to resend their transactions 
.PP
Definition at line 254 of file main\&.cpp\&.
.SS "bool SendMessages (\fBCNode\fP * pto, bool fSendTrickle)"

.PP
Definition at line 3426 of file main\&.cpp\&.
.SS "void SyncWithWallets (const \fBCTransaction\fP & tx, const \fBCBlock\fP * pblock = \fCNULL\fP, bool fConnect = \fCtrue\fP)"
Push an updated transaction to all registered wallets 
.PP
Definition at line 250 of file main\&.cpp\&.
.SS "void ThreadImport (std::vector< boost::filesystem::path > vImportFiles)"

.PP
Definition at line 2294 of file main\&.cpp\&.
.SS "void ThreadStakeMiner (\fBCWallet\fP * pwallet)"

.PP
Definition at line 536 of file miner\&.cpp\&.
.SS "void UnloadBlockIndex ()"

.PP
Unload database information\&. 
.PP
Definition at line 2060 of file main\&.cpp\&.
.SS "void UnregisterAllWallets ()"
Unregister all wallets from core 
.PP
Definition at line 241 of file main\&.cpp\&.
.SS "void UnregisterNodeSignals (\fBCNodeSignals\fP & nodeSignals)"
Unregister a network node 
.PP
Definition at line 469 of file main\&.cpp\&.
.SS "void UnregisterWallet (\fBCWalletInterface\fP * pwalletIn)"
Unregister a wallet from core 
.PP
Definition at line 232 of file main\&.cpp\&.
.SS "\fBuint256\fP WantedByOrphan (const \fBCOrphanBlock\fP * pblockOrphan)"

.PP
Definition at line 1620 of file main\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBCScript\fP COINBASE_FLAGS"

.PP
Definition at line 104 of file main\&.cpp\&.
.SS "\fBCCriticalSection\fP cs_main"

.PP
Definition at line 44 of file main\&.cpp\&.
.SS "bool fImporting"

.PP
Definition at line 79 of file main\&.cpp\&.
.SS "bool fLargeWorkForkFound"

.SS "bool fLargeWorkInvalidChainFound"

.SS "bool fMinimizeCoinAge"

.PP
Definition at line 59 of file init\&.cpp\&.
.SS "bool fReindex"

.PP
Definition at line 80 of file main\&.cpp\&.
.SS "bool fTxIndex"

.PP
Definition at line 67 of file main\&.cpp\&.
.SS "bool fUseFastIndex"

.PP
Definition at line 57 of file init\&.cpp\&.
.SS "\fBuint256\fP hashBestChain"

.PP
Definition at line 74 of file main\&.cpp\&.
.SS "std::map<\fBuint256\fP, \fBCBlockIndex\fP*> mapBlockIndex"

.PP
Definition at line 59 of file main\&.cpp\&.
.SS "std::map<\fBuint256\fP, \fBCOrphanBlock\fP*> mapOrphanBlocks"

.PP
Definition at line 89 of file main\&.cpp\&.
.SS "std::map<\fBuint256\fP, \fBint64_t\fP> mapRejectedBlocks"

.PP
Definition at line 93 of file main\&.cpp\&.
.SS "\fBCTxMemPool\fP mempool"

.SS "\fBCFeeRate\fP minRelayTxFee"
Fees smaller than this (in satoshis) are considered zero fee (for relaying and mining) We are ~xxx times smaller then bitcoin now (2016-01-11), set minRelayTxFee only 10 times higher so it's still 10 times lower comparing to bitcoin\&. 
.PP
Definition at line 50 of file main\&.cpp\&.
.SS "\fBuint256\fP nBestChainTrust"

.PP
Definition at line 72 of file main\&.cpp\&.
.SS "int nBestHeight"

.PP
Definition at line 70 of file main\&.cpp\&.
.SS "\fBuint256\fP nBestInvalidTrust"

.PP
Definition at line 73 of file main\&.cpp\&.
.SS "int nCoinbaseMaturity"

.PP
Definition at line 66 of file main\&.cpp\&.
.SS "unsigned int nCoinCacheSize"

.PP
Definition at line 113 of file main\&.cpp\&.
.SS "unsigned int nDerivationMethodIndex"

.PP
Definition at line 55 of file init\&.cpp\&.
.SS "\fBuint64_t\fP nLastBlockSize"

.PP
Definition at line 79 of file miner\&.cpp\&.
.SS "\fBuint64_t\fP nLastBlockTx"

.PP
Definition at line 78 of file miner\&.cpp\&.
.SS "\fBint64_t\fP nLastCoinStakeSearchInterval"

.PP
Definition at line 80 of file miner\&.cpp\&.
.SS "unsigned int nNodeLifespan"

.PP
Definition at line 54 of file init\&.cpp\&.
.SS "unsigned int nStakeMinAge"

.PP
Definition at line 63 of file main\&.cpp\&.
.SS "int nStakeMinConfirmations"

.PP
Definition at line 65 of file main\&.cpp\&.
.SS "\fBint64_t\fP nTimeBestReceived"

.PP
Definition at line 78 of file main\&.cpp\&.
.SS "\fBCBlockTreeDB\fP* pblocktree"

.PP
Global variable that points to the active block tree (protected by cs_main) 
.PP
Definition at line 111 of file main\&.cpp\&.
.SS "\fBCCoinsViewCache\fP* pcoinsTip"

.PP
Global variable that points to the active \fBCCoinsView\fP (protected by cs_main) 
.PP
Definition at line 110 of file main\&.cpp\&.
.SS "\fBCBlockIndex\fP* pindexBest"

.PP
Definition at line 76 of file main\&.cpp\&.
.SS "\fBCBlockIndex\fP* pindexGenesisBlock"

.PP
Definition at line 69 of file main\&.cpp\&.
.SS "std::set<std::pair<\fBCOutPoint\fP, unsigned int> > setStakeSeen"

.PP
Definition at line 60 of file main\&.cpp\&.
.SS "const std::string strMessageMagic"

.PP
Definition at line 106 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
