.TH "md__home_dev_ds-160209_src_qt_plugins_mrichtexteditor__r_e_a_d_m_e" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_dev_ds-160209_src_qt_plugins_mrichtexteditor__r_e_a_d_m_e \- \fBMRichTextEdit\fP 
A simple Qt rich-text editor widget, easy to use in any Qt project\&.
.PP
.PP
The icons used are standard icons from theme as defined by \fCfreedesktop\&.org Icon Naming Specification\fP (which lacks button/ordered list icons)\&.
.PP
The editor automatically converts plain text http(s) links and emails to html links in toHtml()\&.
.PP
Courtesy of \fCHobrasoft\fP\&. 
