.TH "/home/dev/ds-160209/src/leveldb/helpers/memenv/memenv.cc" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/helpers/memenv/memenv.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'helpers/memenv/memenv\&.h'\fP
.br
\fC#include 'leveldb/env\&.h'\fP
.br
\fC#include 'leveldb/status\&.h'\fP
.br
\fC#include 'port/port\&.h'\fP
.br
\fC#include 'util/mutexlock\&.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Env * \fBleveldb::NewMemEnv\fP (Env *base_env)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "std::vector<char*> blocks_"

.PP
Definition at line 143 of file memenv\&.cc\&.
.SS "FileState* file_"

.PP
Definition at line 180 of file memenv\&.cc\&.
.SS "FileSystem file_map_"

.PP
Definition at line 376 of file memenv\&.cc\&.
.SS "port::Mutex mutex_"

.PP
Definition at line 375 of file memenv\&.cc\&.
.SS "\fBuint64_t\fP pos_"

.PP
Definition at line 181 of file memenv\&.cc\&.
.SS "int refs_"

.PP
Definition at line 138 of file memenv\&.cc\&.
.SS "port::Mutex refs_mutex_"

.PP
Definition at line 137 of file memenv\&.cc\&.
.SS "\fBuint64_t\fP size_"

.PP
Definition at line 144 of file memenv\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
