.TH "/home/dev/ds-160209/src/leveldb/table/merger.cc" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/table/merger.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'table/merger\&.h'\fP
.br
\fC#include 'leveldb/comparator\&.h'\fP
.br
\fC#include 'leveldb/iterator\&.h'\fP
.br
\fC#include 'table/iterator_wrapper\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Iterator * \fBleveldb::NewMergingIterator\fP (const Comparator *\fBcmp\fP, Iterator **list, int n)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "IteratorWrapper* children_"

.PP
Definition at line 143 of file merger\&.cc\&.
.SS "const Comparator* comparator_"

.PP
Definition at line 142 of file merger\&.cc\&.
.SS "IteratorWrapper* current_"

.PP
Definition at line 145 of file merger\&.cc\&.
.SS "Direction direction_"

.PP
Definition at line 152 of file merger\&.cc\&.
.SS "int n_"

.PP
Definition at line 144 of file merger\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
