.TH "MessagePage" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MessagePage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <messagepage\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBexportClicked\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessagePage\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~MessagePage\fP ()"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBMessageModel\fP *model)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Widget that shows a list of sending or receiving addresses\&. 
.PP
Definition at line 25 of file messagepage\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MessagePage::MessagePage (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 75 of file messagepage\&.cpp\&.
.SS "MessagePage::~MessagePage ()"

.PP
Definition at line 116 of file messagepage\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void MessagePage::exportClicked ()\fC [slot]\fP"

.PP
Definition at line 391 of file messagepage\&.cpp\&.
.SS "void MessagePage::setModel (\fBMessageModel\fP * model)"

.PP
Definition at line 121 of file messagepage\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
