.TH "MessageTableEntry" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MessageTableEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <messagemodel\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBSent\fP, \fBReceived\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessageTableEntry\fP ()"
.br
.ti -1c
.RI "\fBMessageTableEntry\fP (std::vector< unsigned char > &\fBchKey\fP, \fBType\fP \fBtype\fP, const QString &\fBlabel\fP, const QString &\fBto_address\fP, const QString &\fBfrom_address\fP, const QDateTime &\fBsent_datetime\fP, const QDateTime &\fBreceived_datetime\fP, const QString &\fBmessage\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< unsigned char > \fBchKey\fP"
.br
.ti -1c
.RI "\fBType\fP \fBtype\fP"
.br
.ti -1c
.RI "QString \fBlabel\fP"
.br
.ti -1c
.RI "QString \fBto_address\fP"
.br
.ti -1c
.RI "QString \fBfrom_address\fP"
.br
.ti -1c
.RI "QDateTime \fBsent_datetime\fP"
.br
.ti -1c
.RI "QDateTime \fBreceived_datetime\fP"
.br
.ti -1c
.RI "QString \fBmessage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file messagemodel\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBMessageTableEntry::Type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISent \fP\fP
.TP
\fB\fIReceived \fP\fP
.PP
Definition at line 35 of file messagemodel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MessageTableEntry::MessageTableEntry ()\fC [inline]\fP"

.PP
Definition at line 49 of file messagemodel\&.h\&.
.SS "MessageTableEntry::MessageTableEntry (std::vector< unsigned char > & chKey, \fBType\fP type, const QString & label, const QString & to_address, const QString & from_address, const QDateTime & sent_datetime, const QDateTime & received_datetime, const QString & message)\fC [inline]\fP"

.PP
Definition at line 50 of file messagemodel\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<unsigned char> MessageTableEntry::chKey"

.PP
Definition at line 40 of file messagemodel\&.h\&.
.SS "QString MessageTableEntry::from_address"

.PP
Definition at line 44 of file messagemodel\&.h\&.
.SS "QString MessageTableEntry::label"

.PP
Definition at line 42 of file messagemodel\&.h\&.
.SS "QString MessageTableEntry::message"

.PP
Definition at line 47 of file messagemodel\&.h\&.
.SS "QDateTime MessageTableEntry::received_datetime"

.PP
Definition at line 46 of file messagemodel\&.h\&.
.SS "QDateTime MessageTableEntry::sent_datetime"

.PP
Definition at line 45 of file messagemodel\&.h\&.
.SS "QString MessageTableEntry::to_address"

.PP
Definition at line 43 of file messagemodel\&.h\&.
.SS "\fBType\fP MessageTableEntry::type"

.PP
Definition at line 41 of file messagemodel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
