.TH "MessageTablePriv" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MessageTablePriv \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessageTablePriv\fP (\fBMessageModel\fP *\fBparent\fP)"
.br
.ti -1c
.RI "void \fBrefreshMessageTable\fP ()"
.br
.ti -1c
.RI "void \fBnewMessage\fP (const \fBSecMsgStored\fP &inboxHdr)"
.br
.ti -1c
.RI "void \fBnewOutboxMessage\fP (const \fBSecMsgStored\fP &outboxHdr)"
.br
.ti -1c
.RI "void \fBwalletUnlocked\fP ()"
.br
.ti -1c
.RI "void \fBsetEncryptionStatus\fP (int status)"
.br
.ti -1c
.RI "\fBMessageTableEntry\fP * \fBindex\fP (int idx)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QList< \fBMessageTableEntry\fP > \fBcachedMessageTable\fP"
.br
.ti -1c
.RI "\fBMessageModel\fP * \fBparent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file messagemodel\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MessageTablePriv::MessageTablePriv (\fBMessageModel\fP * parent)\fC [inline]\fP"

.PP
Definition at line 44 of file messagemodel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMessageTableEntry\fP* MessageTablePriv::index (int idx)\fC [inline]\fP"

.PP
Definition at line 239 of file messagemodel\&.cpp\&.
.SS "void MessageTablePriv::newMessage (const \fBSecMsgStored\fP & inboxHdr)\fC [inline]\fP"

.PP
Definition at line 134 of file messagemodel\&.cpp\&.
.SS "void MessageTablePriv::newOutboxMessage (const \fBSecMsgStored\fP & outboxHdr)\fC [inline]\fP"

.PP
Definition at line 172 of file messagemodel\&.cpp\&.
.SS "void MessageTablePriv::refreshMessageTable ()\fC [inline]\fP"

.PP
Definition at line 47 of file messagemodel\&.cpp\&.
.SS "void MessageTablePriv::setEncryptionStatus (int status)\fC [inline]\fP"

.PP
Definition at line 228 of file messagemodel\&.cpp\&.
.SS "void MessageTablePriv::walletUnlocked ()\fC [inline]\fP"

.PP
Definition at line 209 of file messagemodel\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QList<\fBMessageTableEntry\fP> MessageTablePriv::cachedMessageTable"

.PP
Definition at line 41 of file messagemodel\&.cpp\&.
.SS "\fBMessageModel\fP* MessageTablePriv::parent"

.PP
Definition at line 42 of file messagemodel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
