.TH "/home/dev/ds-160209/src/qt/messagemodel.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/messagemodel.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'guiutil\&.h'\fP
.br
\fC#include 'guiconstants\&.h'\fP
.br
\fC#include 'darksilkunits\&.h'\fP
.br
\fC#include 'optionsmodel\&.h'\fP
.br
\fC#include 'walletmodel\&.h'\fP
.br
\fC#include 'messagemodel\&.h'\fP
.br
\fC#include 'addresstablemodel\&.h'\fP
.br
\fC#include 'ui_interface\&.h'\fP
.br
\fC#include 'base58\&.h'\fP
.br
\fC#include 'json_spirit\&.h'\fP
.br
\fC#include <QSet>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <QDateTime>\fP
.br
\fC#include <QSortFilterProxyModel>\fP
.br
\fC#include <QClipboard>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QMenu>\fP
.br
\fC#include <QFont>\fP
.br
\fC#include <QColor>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMessageTableEntryLessThan\fP"
.br
.ti -1c
.RI "class \fBMessageTablePriv\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBQ_DECLARE_METATYPE\fP (std::vector< unsigned char >)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "QList< QString > \fBambiguous\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Q_DECLARE_METATYPE (std::vector< unsigned char >)"

.SH "Variable Documentation"
.PP 
.SS "QList<QString> ambiguous"
Specifies Ambiguous addresses 
.PP
Definition at line 25 of file messagemodel\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
