.TH "MessageData" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MessageData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <smessage\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint64_t\fP \fBtimestamp\fP"
.br
.ti -1c
.RI "std::string \fBsToAddress\fP"
.br
.ti -1c
.RI "std::string \fBsFromAddress\fP"
.br
.ti -1c
.RI "std::vector< \fBuint8_t\fP > \fBvchMessage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 100 of file smessage\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string MessageData::sFromAddress"

.PP
Definition at line 106 of file smessage\&.h\&.
.SS "std::string MessageData::sToAddress"

.PP
Definition at line 105 of file smessage\&.h\&.
.SS "\fBint64_t\fP MessageData::timestamp"

.PP
Definition at line 104 of file smessage\&.h\&.
.SS "std::vector<\fBuint8_t\fP> MessageData::vchMessage"

.PP
Definition at line 107 of file smessage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
