.TH "MessageModel" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MessageModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <messagemodel\&.h>\fP
.PP
Inherits QAbstractTableModel\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBStatusCode\fP { \fBOK\fP, \fBInvalidAddress\fP, \fBInvalidMessage\fP, \fBDuplicateAddress\fP, \fBMessageCreationFailed\fP, \fBMessageCommitFailed\fP, \fBAborted\fP, \fBFailedErrorShown\fP }"
.br
.ti -1c
.RI "enum \fBColumnIndex\fP { \fBType\fP = 0, \fBSentDateTime\fP = 1, \fBReceivedDateTime\fP = 2, \fBLabel\fP = 3, \fBToAddress\fP = 4, \fBFromAddress\fP = 5, \fBMessage\fP = 6, \fBTypeInt\fP = 7, \fBKey\fP = 8, \fBHTML\fP = 9 }"
.br
.ti -1c
.RI "enum \fBRoleIndex\fP { \fBTypeRole\fP = Qt::UserRole, \fBKeyRole\fP, \fBSentDateRole\fP, \fBReceivedDateRole\fP, \fBFromAddressRole\fP, \fBToAddressRole\fP, \fBFilterAddressRole\fP, \fBLabelRole\fP, \fBMessageRole\fP, \fBShortMessageRole\fP, \fBHTMLRole\fP, \fBAmbiguous\fP }"
.br
.in -1c
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBnewMessage\fP (const \fBSecMsgStored\fP &smsg)"
.br
.ti -1c
.RI "void \fBnewOutboxMessage\fP (const \fBSecMsgStored\fP &smsg)"
.br
.ti -1c
.RI "void \fBwalletUnlocked\fP ()"
.br
.ti -1c
.RI "void \fBsetEncryptionStatus\fP (int status)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBerror\fP (const QString &title, const QString &message, bool modal)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessageModel\fP (\fBCWallet\fP *wallet, \fBWalletModel\fP *walletModel, QObject *parent=0)"
.br
.ti -1c
.RI "\fB~MessageModel\fP ()"
.br
.ti -1c
.RI "int \fBlookupMessage\fP (const QString &message) const "
.br
.ti -1c
.RI "\fBWalletModel\fP * \fBgetWalletModel\fP ()"
.br
.ti -1c
.RI "\fBOptionsModel\fP * \fBgetOptionsModel\fP ()"
.br
.ti -1c
.RI "void \fBresetFilter\fP ()"
.br
.ti -1c
.RI "bool \fBgetAddressOrPubkey\fP (QString &Address, QString &Pubkey) const "
.br
.ti -1c
.RI "\fBStatusCode\fP \fBsendMessages\fP (const QList< \fBSendMessagesRecipient\fP > &recipients)"
.br
.ti -1c
.RI "\fBStatusCode\fP \fBsendMessages\fP (const QList< \fBSendMessagesRecipient\fP > &recipients, const QString &addressFrom)"
.br
.in -1c
.PP
.RI "\fBMethods overridden from QAbstractTableModel\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "int \fBrowCount\fP (const QModelIndex &parent) const "
.br
.ti -1c
.RI "int \fBcolumnCount\fP (const QModelIndex &parent) const "
.br
.ti -1c
.RI "QVariant \fBdata\fP (const QModelIndex &\fBindex\fP, int role) const "
.br
.ti -1c
.RI "QVariant \fBheaderData\fP (int section, Qt::Orientation orientation, int role) const "
.br
.ti -1c
.RI "QModelIndex \fBindex\fP (int row, int column, const QModelIndex &parent) const "
.br
.ti -1c
.RI "bool \fBremoveRows\fP (int row, int count, const QModelIndex &parent=QModelIndex())"
.br
.ti -1c
.RI "Qt::ItemFlags \fBflags\fP (const QModelIndex &\fBindex\fP) const "
.br
.in -1c
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QSortFilterProxyModel * \fBproxyModel\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const QString \fBSent\fP = 'Sent'"
.br
.ti -1c
.RI "static const QString \fBReceived\fP = 'Received'"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBMessageTablePriv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface to DarkSilk Secure Messaging from Qt view code\&. 
.PP
Definition at line 71 of file messagemodel\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBMessageModel::ColumnIndex\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIType \fP\fP
Sent/Received 
.TP
\fB\fISentDateTime \fP\fP
Time Sent 
.TP
\fB\fIReceivedDateTime \fP\fP
Time Received 
.TP
\fB\fILabel \fP\fP
User specified label 
.TP
\fB\fIToAddress \fP\fP
To DarkSilk address 
.TP
\fB\fIFromAddress \fP\fP
From DarkSilk address 
.TP
\fB\fIMessage \fP\fP
Plaintext 
.TP
\fB\fITypeInt \fP\fP
Plaintext 
.TP
\fB\fIKey \fP\fP
chKey 
.TP
\fB\fIHTML \fP\fP
HTML Formatted Data 
.PP
Definition at line 91 of file messagemodel\&.h\&.
.SS "enum \fBMessageModel::RoleIndex\fP"
Roles to get specific information from a message row\&. These are independent of column\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITypeRole \fP\fP
Type of message 
.TP
\fB\fIKeyRole \fP\fP
Date and time this message was sent message key 
.TP
\fB\fISentDateRole \fP\fP
.TP
\fB\fIReceivedDateRole \fP\fP
Date and time this message was received 
.TP
\fB\fIFromAddressRole \fP\fP
From Address of message 
.TP
\fB\fIToAddressRole \fP\fP
To Address of message 
.TP
\fB\fIFilterAddressRole \fP\fP
Filter address related to message 
.TP
\fB\fILabelRole \fP\fP
Label of address related to message 
.TP
\fB\fIMessageRole \fP\fP
Full Message 
.TP
\fB\fIShortMessageRole \fP\fP
Short Message 
.TP
\fB\fIHTMLRole \fP\fP
HTML Formatted 
.TP
\fB\fIAmbiguous \fP\fP
Ambiguous bool 
.PP
Definition at line 107 of file messagemodel\&.h\&.
.SS "enum \fBMessageModel::StatusCode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOK \fP\fP
.TP
\fB\fIInvalidAddress \fP\fP
.TP
\fB\fIInvalidMessage \fP\fP
.TP
\fB\fIDuplicateAddress \fP\fP
.TP
\fB\fIMessageCreationFailed \fP\fP
.TP
\fB\fIMessageCommitFailed \fP\fP
.TP
\fB\fIAborted \fP\fP
.TP
\fB\fIFailedErrorShown \fP\fP
.PP
Definition at line 79 of file messagemodel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MessageModel::MessageModel (\fBCWallet\fP * wallet, \fBWalletModel\fP * walletModel, QObject * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 307 of file messagemodel\&.cpp\&.
.SS "MessageModel::~MessageModel ()"

.PP
Definition at line 322 of file messagemodel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int MessageModel::columnCount (const QModelIndex & parent) const"

.PP
Definition at line 433 of file messagemodel\&.cpp\&.
.SS "QVariant MessageModel::data (const QModelIndex & index, int role) const"

.PP
Definition at line 439 of file messagemodel\&.cpp\&.
.SS "void MessageModel::error (const QString & title, const QString & message, bool modal)\fC [signal]\fP"

.SS "Qt::ItemFlags MessageModel::flags (const QModelIndex & index) const"

.PP
Definition at line 512 of file messagemodel\&.cpp\&.
.SS "bool MessageModel::getAddressOrPubkey (QString & Address, QString & Pubkey) const"

.PP
Definition at line 331 of file messagemodel\&.cpp\&.
.SS "\fBOptionsModel\fP * MessageModel::getOptionsModel ()"

.PP
Definition at line 359 of file messagemodel\&.cpp\&.
.SS "\fBWalletModel\fP * MessageModel::getWalletModel ()"

.PP
Definition at line 354 of file messagemodel\&.cpp\&.
.SS "QVariant MessageModel::headerData (int section, Qt::Orientation orientation, int role) const"

.PP
Definition at line 507 of file messagemodel\&.cpp\&.
.SS "QModelIndex MessageModel::index (int row, int column, const QModelIndex & parent) const"

.PP
Definition at line 520 of file messagemodel\&.cpp\&.
.SS "int MessageModel::lookupMessage (const QString & message) const"

.SS "void MessageModel::newMessage (const \fBSecMsgStored\fP & smsg)\fC [slot]\fP"

.PP
Definition at line 558 of file messagemodel\&.cpp\&.
.SS "void MessageModel::newOutboxMessage (const \fBSecMsgStored\fP & smsg)\fC [slot]\fP"

.PP
Definition at line 564 of file messagemodel\&.cpp\&.
.SS "bool MessageModel::removeRows (int row, int count, const QModelIndex & parent = \fCQModelIndex()\fP)"

.PP
Definition at line 527 of file messagemodel\&.cpp\&.
.SS "void MessageModel::resetFilter ()"

.PP
Definition at line 553 of file messagemodel\&.cpp\&.
.SS "int MessageModel::rowCount (const QModelIndex & parent) const"

.PP
Definition at line 427 of file messagemodel\&.cpp\&.
.SS "\fBMessageModel::StatusCode\fP MessageModel::sendMessages (const QList< \fBSendMessagesRecipient\fP > & recipients)"

.PP
Definition at line 422 of file messagemodel\&.cpp\&.
.SS "\fBMessageModel::StatusCode\fP MessageModel::sendMessages (const QList< \fBSendMessagesRecipient\fP > & recipients, const QString & addressFrom)"

.PP
Definition at line 364 of file messagemodel\&.cpp\&.
.SS "void MessageModel::setEncryptionStatus (int status)\fC [slot]\fP"

.PP
Definition at line 575 of file messagemodel\&.cpp\&.
.SS "void MessageModel::walletUnlocked ()\fC [slot]\fP"

.PP
Definition at line 570 of file messagemodel\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBMessageTablePriv\fP\fC [friend]\fP"

.PP
Definition at line 188 of file messagemodel\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "QSortFilterProxyModel* MessageModel::proxyModel"

.PP
Definition at line 166 of file messagemodel\&.h\&.
.SS "const QString MessageModel::Received = 'Received'\fC [static]\fP"
Specifies sent message 
.PP
Definition at line 135 of file messagemodel\&.h\&.
.SS "const QString MessageModel::Sent = 'Sent'\fC [static]\fP"
Specifies sent message 
.PP
Definition at line 134 of file messagemodel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
