.TH "/home/dev/ds-160209/src/qt/messagepage.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/messagepage.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'messagepage\&.h'\fP
.br
\fC#include 'ui_messagepage\&.h'\fP
.br
\fC#include 'sendmessagesdialog\&.h'\fP
.br
\fC#include 'mrichtextedit\&.h'\fP
.br
\fC#include 'messagemodel\&.h'\fP
.br
\fC#include 'darksilkgui\&.h'\fP
.br
\fC#include 'csvmodelwriter\&.h'\fP
.br
\fC#include 'guiutil\&.h'\fP
.br
\fC#include <QSortFilterProxyModel>\fP
.br
\fC#include <QClipboard>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QMenu>\fP
.br
\fC#include <QStyledItemDelegate>\fP
.br
\fC#include <QAbstractTextDocumentLayout>\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QToolBar>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMessageViewDelegate\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDECORATION_SIZE\fP   64"
.br
.ti -1c
.RI "#define \fBNUM_ITEMS\fP   3"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DECORATION_SIZE   64"

.PP
Definition at line 22 of file messagepage\&.cpp\&.
.SS "#define NUM_ITEMS   3"

.PP
Definition at line 23 of file messagepage\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
