.TH "MessageTableEntryLessThan" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MessageTableEntryLessThan \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBMessageTableEntry\fP &a, const \fBMessageTableEntry\fP &b) const "
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBMessageTableEntry\fP &a, const QDateTime &b) const "
.br
.ti -1c
.RI "bool \fBoperator()\fP (const QDateTime &a, const \fBMessageTableEntry\fP &b) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file messagemodel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool MessageTableEntryLessThan::operator() (const \fBMessageTableEntry\fP & a, const \fBMessageTableEntry\fP & b) const\fC [inline]\fP"

.PP
Definition at line 32 of file messagemodel\&.cpp\&.
.SS "bool MessageTableEntryLessThan::operator() (const \fBMessageTableEntry\fP & a, const QDateTime & b) const\fC [inline]\fP"

.PP
Definition at line 33 of file messagemodel\&.cpp\&.
.SS "bool MessageTableEntryLessThan::operator() (const QDateTime & a, const \fBMessageTableEntry\fP & b) const\fC [inline]\fP"

.PP
Definition at line 34 of file messagemodel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
