.TH "MonitoredDataMapper" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MonitoredDataMapper \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <monitoreddatamapper\&.h>\fP
.PP
Inherits QDataWidgetMapper\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBviewModified\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMonitoredDataMapper\fP (QObject *parent=0)"
.br
.ti -1c
.RI "void \fBaddMapping\fP (QWidget *widget, int section)"
.br
.ti -1c
.RI "void \fBaddMapping\fP (QWidget *widget, int section, const QByteArray &propertyName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data to Widget mapper that watches for edits and notifies listeners when a field is edited\&. This can be used, for example, to enable a commit/apply button in a configuration dialog\&. 
.PP
Definition at line 13 of file monitoreddatamapper\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MonitoredDataMapper::MonitoredDataMapper (QObject * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 7 of file monitoreddatamapper\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void MonitoredDataMapper::addMapping (QWidget * widget, int section)"

.PP
Definition at line 12 of file monitoreddatamapper\&.cpp\&.
.SS "void MonitoredDataMapper::addMapping (QWidget * widget, int section, const QByteArray & propertyName)"

.PP
Definition at line 18 of file monitoreddatamapper\&.cpp\&.
.SS "void MonitoredDataMapper::viewModified ()\fC [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
