.TH "MRichTextEdit" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MRichTextEdit \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mrichtextedit\&.h>\fP
.PP
Inherits QWidget, and MRichTextEdit\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetText\fP (const QString &text)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMRichTextEdit\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "QString \fBtoPlainText\fP () const "
.br
.ti -1c
.RI "QString \fBtoHtml\fP () const "
.br
.ti -1c
.RI "QTextDocument * \fBdocument\fP ()"
.br
.ti -1c
.RI "QTextCursor \fBtextCursor\fP () const "
.br
.ti -1c
.RI "void \fBsetTextCursor\fP (const QTextCursor &cursor)"
.br
.in -1c
.SS "Protected Types"

.in +1c
.ti -1c
.RI "enum \fBParagraphItems\fP { \fBParagraphStandard\fP = 0, \fBParagraphHeading1\fP, \fBParagraphHeading2\fP, \fBParagraphHeading3\fP, \fBParagraphHeading4\fP, \fBParagraphMonospace\fP }"
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "void \fBsetPlainText\fP (const QString &text)"
.br
.ti -1c
.RI "void \fBsetHtml\fP (const QString &text)"
.br
.ti -1c
.RI "void \fBtextBold\fP ()"
.br
.ti -1c
.RI "void \fBtextUnderline\fP ()"
.br
.ti -1c
.RI "void \fBtextStrikeout\fP ()"
.br
.ti -1c
.RI "void \fBtextItalic\fP ()"
.br
.ti -1c
.RI "void \fBtextSize\fP (const QString &p)"
.br
.ti -1c
.RI "void \fBtextLink\fP (bool checked)"
.br
.ti -1c
.RI "void \fBtextStyle\fP (int index)"
.br
.ti -1c
.RI "void \fBtextBgColor\fP ()"
.br
.ti -1c
.RI "void \fBlistBullet\fP (bool checked)"
.br
.ti -1c
.RI "void \fBlistOrdered\fP (bool checked)"
.br
.ti -1c
.RI "void \fBslotCurrentCharFormatChanged\fP (const QTextCharFormat &format)"
.br
.ti -1c
.RI "void \fBslotCursorPositionChanged\fP ()"
.br
.ti -1c
.RI "void \fBslotClipboardDataChanged\fP ()"
.br
.ti -1c
.RI "void \fBincreaseIndentation\fP ()"
.br
.ti -1c
.RI "void \fBdecreaseIndentation\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBmergeFormatOnWordOrSelection\fP (const QTextCharFormat &format)"
.br
.ti -1c
.RI "void \fBfontChanged\fP (const QFont &f)"
.br
.ti -1c
.RI "void \fBbgColorChanged\fP (const QColor &c)"
.br
.ti -1c
.RI "void \fBlist\fP (bool checked, QTextListFormat::Style style)"
.br
.ti -1c
.RI "void \fBindent\fP (int delta)"
.br
.ti -1c
.RI "void \fBfocusInEvent\fP (QFocusEvent *event)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QStringList \fBm_paragraphItems\fP"
.br
.ti -1c
.RI "int \fBm_fontsize_h1\fP"
.br
.ti -1c
.RI "int \fBm_fontsize_h2\fP"
.br
.ti -1c
.RI "int \fBm_fontsize_h3\fP"
.br
.ti -1c
.RI "int \fBm_fontsize_h4\fP"
.br
.ti -1c
.RI "QPointer< QTextList > \fBm_lastBlockList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A simple rich-text editor 
.PP
Definition at line 33 of file mrichtextedit\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBMRichTextEdit::ParagraphItems\fP\fC [protected]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIParagraphStandard \fP\fP
.TP
\fB\fIParagraphHeading1 \fP\fP
.TP
\fB\fIParagraphHeading2 \fP\fP
.TP
\fB\fIParagraphHeading3 \fP\fP
.TP
\fB\fIParagraphHeading4 \fP\fP
.TP
\fB\fIParagraphMonospace \fP\fP
.PP
Definition at line 82 of file mrichtextedit\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MRichTextEdit::MRichTextEdit (QWidget * parent = \fC0\fP)"

.PP
Definition at line 39 of file mrichtextedit\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void MRichTextEdit::bgColorChanged (const QColor & c)\fC [protected]\fP"

.PP
Definition at line 399 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::clear ()\fC [slot]\fP"

.PP
Definition at line 464 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::decreaseIndentation ()\fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 436 of file mrichtextedit\&.cpp\&.
.SS "QTextDocument* MRichTextEdit::document ()\fC [inline]\fP"

.PP
Definition at line 40 of file mrichtextedit\&.h\&.
.SS "void MRichTextEdit::focusInEvent (QFocusEvent * event)\fC [protected]\fP"

.PP
Definition at line 169 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::fontChanged (const QFont & f)\fC [protected]\fP"

.PP
Definition at line 360 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::increaseIndentation ()\fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 432 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::indent (int delta)\fC [protected]\fP"

.PP
Definition at line 440 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::list (bool checked, QTextListFormat::Style style)\fC [protected]\fP"

.PP
Definition at line 307 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::listBullet (bool checked)\fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 293 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::listOrdered (bool checked)\fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 300 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::mergeFormatOnWordOrSelection (const QTextCharFormat & format)\fC [protected]\fP"

.PP
Definition at line 326 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::setHtml (const QString & text)\fC [inline]\fP, \fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 51 of file mrichtextedit\&.h\&.
.SS "void MRichTextEdit::setPlainText (const QString & text)\fC [inline]\fP, \fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 50 of file mrichtextedit\&.h\&.
.SS "void MRichTextEdit::setText (const QString & text)\fC [slot]\fP"

.PP
Definition at line 452 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::setTextCursor (const QTextCursor & cursor)\fC [inline]\fP"

.PP
Definition at line 42 of file mrichtextedit\&.h\&.
.SS "void MRichTextEdit::slotClipboardDataChanged ()\fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 415 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::slotCurrentCharFormatChanged (const QTextCharFormat & format)\fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 409 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::slotCursorPositionChanged ()\fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 335 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::textBgColor ()\fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 276 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::textBold ()\fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 162 of file mrichtextedit\&.cpp\&.
.SS "QTextCursor MRichTextEdit::textCursor () const\fC [inline]\fP"

.PP
Definition at line 41 of file mrichtextedit\&.h\&.
.SS "void MRichTextEdit::textItalic ()\fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 180 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::textLink (bool checked)\fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 201 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::textSize (const QString & p)\fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 192 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::textStrikeout ()\fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 186 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::textStyle (int index)\fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 230 of file mrichtextedit\&.cpp\&.
.SS "void MRichTextEdit::textUnderline ()\fC [protected]\fP, \fC [slot]\fP"

.PP
Definition at line 174 of file mrichtextedit\&.cpp\&.
.SS "QString MRichTextEdit::toHtml () const"

.PP
Definition at line 422 of file mrichtextedit\&.cpp\&.
.SS "QString MRichTextEdit::toPlainText () const\fC [inline]\fP"

.PP
Definition at line 38 of file mrichtextedit\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int MRichTextEdit::m_fontsize_h1\fC [protected]\fP"

.PP
Definition at line 77 of file mrichtextedit\&.h\&.
.SS "int MRichTextEdit::m_fontsize_h2\fC [protected]\fP"

.PP
Definition at line 78 of file mrichtextedit\&.h\&.
.SS "int MRichTextEdit::m_fontsize_h3\fC [protected]\fP"

.PP
Definition at line 79 of file mrichtextedit\&.h\&.
.SS "int MRichTextEdit::m_fontsize_h4\fC [protected]\fP"

.PP
Definition at line 80 of file mrichtextedit\&.h\&.
.SS "QPointer<QTextList> MRichTextEdit::m_lastBlockList\fC [protected]\fP"

.PP
Definition at line 89 of file mrichtextedit\&.h\&.
.SS "QStringList MRichTextEdit::m_paragraphItems\fC [protected]\fP"

.PP
Definition at line 76 of file mrichtextedit\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
