.TH "/home/dev/ds-160209/src/test/mruset_tests.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/test/mruset_tests.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/test/unit_test\&.hpp>\fP
.br
\fC#include 'mruset\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmrutester\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNUM_TESTS\fP   16"
.br
.ti -1c
.RI "#define \fBMAX_SIZE\fP   100"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (mruset_like_set)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (mruset_limited_size)"
.br
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (mruset_window)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_SIZE   100"

.PP
Definition at line 9 of file mruset_tests\&.cpp\&.
.SS "#define NUM_TESTS   16"

.PP
Definition at line 8 of file mruset_tests\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (mruset_like_set)"

.PP
Definition at line 32 of file mruset_tests\&.cpp\&.
.SS "BOOST_AUTO_TEST_CASE (mruset_limited_size)"

.PP
Definition at line 45 of file mruset_tests\&.cpp\&.
.SS "BOOST_AUTO_TEST_CASE (mruset_window)"

.PP
Definition at line 75 of file mruset_tests\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
