.TH "mruset< T >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mruset< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mruset\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBkey_type\fP"
.br
.ti -1c
.RI "typedef T \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef std::set< T >::\fBiterator\fP \fBiterator\fP"
.br
.ti -1c
.RI "typedef std::set< T >::\fBconst_iterator\fP \fBconst_iterator\fP"
.br
.ti -1c
.RI "typedef std::set< T >::\fBsize_type\fP \fBsize_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmruset\fP (\fBsize_type\fP nMaxSizeIn=0)"
.br
.ti -1c
.RI "\fBiterator\fP \fBbegin\fP () const "
.br
.ti -1c
.RI "\fBiterator\fP \fBend\fP () const "
.br
.ti -1c
.RI "\fBsize_type\fP \fBsize\fP () const "
.br
.ti -1c
.RI "bool \fBempty\fP () const "
.br
.ti -1c
.RI "\fBiterator\fP \fBfind\fP (const \fBkey_type\fP &k) const "
.br
.ti -1c
.RI "\fBsize_type\fP \fBcount\fP (const \fBkey_type\fP &k) const "
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "bool friend \fBoperator==\fP (const \fBmruset\fP< T > &a, const \fBmruset\fP< T > &b)"
.br
.ti -1c
.RI "bool friend \fBoperator==\fP (const \fBmruset\fP< T > &a, const std::set< T > &b)"
.br
.ti -1c
.RI "bool friend \fBoperator<\fP (const \fBmruset\fP< T > &a, const \fBmruset\fP< T > &b)"
.br
.ti -1c
.RI "std::pair< \fBiterator\fP, bool > \fBinsert\fP (const \fBkey_type\fP &x)"
.br
.ti -1c
.RI "\fBsize_type\fP \fBmax_size\fP () const "
.br
.ti -1c
.RI "\fBsize_type\fP \fBmax_size\fP (\fBsize_type\fP s)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::set< T > \fBset\fP"
.br
.ti -1c
.RI "std::deque< T > \fBqueue\fP"
.br
.ti -1c
.RI "\fBsize_type\fP \fBnMaxSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>class mruset< T >"
STL-like set container that only keeps the most recent N elements\&. 
.PP
Definition at line 11 of file mruset\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T> typedef std::set<T>::\fBconst_iterator\fP \fBmruset\fP< T >::\fBconst_iterator\fP"

.PP
Definition at line 17 of file mruset\&.h\&.
.SS "template<typename T> typedef std::set<T>::\fBiterator\fP \fBmruset\fP< T >::\fBiterator\fP"

.PP
Definition at line 16 of file mruset\&.h\&.
.SS "template<typename T> typedef T \fBmruset\fP< T >::\fBkey_type\fP"

.PP
Definition at line 14 of file mruset\&.h\&.
.SS "template<typename T> typedef std::set<T>::\fBsize_type\fP \fBmruset\fP< T >::\fBsize_type\fP"

.PP
Definition at line 18 of file mruset\&.h\&.
.SS "template<typename T> typedef T \fBmruset\fP< T >::\fBvalue_type\fP"

.PP
Definition at line 15 of file mruset\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBmruset\fP< T >::\fBmruset\fP (\fBsize_type\fP nMaxSizeIn = \fC0\fP)\fC [inline]\fP"

.PP
Definition at line 26 of file mruset\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> \fBiterator\fP \fBmruset\fP< T >::begin () const\fC [inline]\fP"

.PP
Definition at line 27 of file mruset\&.h\&.
.SS "template<typename T> void \fBmruset\fP< T >::clear ()\fC [inline]\fP"

.PP
Definition at line 33 of file mruset\&.h\&.
.SS "template<typename T> \fBsize_type\fP \fBmruset\fP< T >::count (const \fBkey_type\fP & k) const\fC [inline]\fP"

.PP
Definition at line 32 of file mruset\&.h\&.
.SS "template<typename T> bool \fBmruset\fP< T >::empty () const\fC [inline]\fP"

.PP
Definition at line 30 of file mruset\&.h\&.
.SS "template<typename T> \fBiterator\fP \fBmruset\fP< T >::end () const\fC [inline]\fP"

.PP
Definition at line 28 of file mruset\&.h\&.
.SS "template<typename T> \fBiterator\fP \fBmruset\fP< T >::find (const \fBkey_type\fP & k) const\fC [inline]\fP"

.PP
Definition at line 31 of file mruset\&.h\&.
.SS "template<typename T> std::pair<\fBiterator\fP, bool> \fBmruset\fP< T >::insert (const \fBkey_type\fP & x)\fC [inline]\fP"

.PP
Definition at line 37 of file mruset\&.h\&.
.SS "template<typename T> \fBsize_type\fP \fBmruset\fP< T >::max_size () const\fC [inline]\fP"

.PP
Definition at line 51 of file mruset\&.h\&.
.SS "template<typename T> \fBsize_type\fP \fBmruset\fP< T >::max_size (\fBsize_type\fP s)\fC [inline]\fP"

.PP
Definition at line 52 of file mruset\&.h\&.
.SS "template<typename T> bool friend \fBmruset\fP< T >::operator< (const \fBmruset\fP< T > & a, const \fBmruset\fP< T > & b)\fC [inline]\fP"

.PP
Definition at line 36 of file mruset\&.h\&.
.SS "template<typename T> bool friend \fBmruset\fP< T >::operator== (const \fBmruset\fP< T > & a, const \fBmruset\fP< T > & b)\fC [inline]\fP"

.PP
Definition at line 34 of file mruset\&.h\&.
.SS "template<typename T> bool friend \fBmruset\fP< T >::operator== (const \fBmruset\fP< T > & a, const std::set< T > & b)\fC [inline]\fP"

.PP
Definition at line 35 of file mruset\&.h\&.
.SS "template<typename T> \fBsize_type\fP \fBmruset\fP< T >::size () const\fC [inline]\fP"

.PP
Definition at line 29 of file mruset\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T> \fBsize_type\fP \fBmruset\fP< T >::nMaxSize\fC [protected]\fP"

.PP
Definition at line 23 of file mruset\&.h\&.
.SS "template<typename T> std::deque<T> \fBmruset\fP< T >::queue\fC [protected]\fP"

.PP
Definition at line 22 of file mruset\&.h\&.
.SS "template<typename T> std::set<T> \fBmruset\fP< T >::set\fC [protected]\fP"

.PP
Definition at line 21 of file mruset\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
