.TH "MutableTransactionSignatureChecker" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MutableTransactionSignatureChecker \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transaction\&.h>\fP
.PP
Inherits \fBTransactionSignatureChecker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMutableTransactionSignatureChecker\fP (const \fBCMutableTransaction\fP *txToIn, unsigned int nInIn)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 425 of file transaction\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MutableTransactionSignatureChecker::MutableTransactionSignatureChecker (const \fBCMutableTransaction\fP * txToIn, unsigned int nInIn)\fC [inline]\fP"

.PP
Definition at line 431 of file transaction\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
