.TH "/home/dev/ds-160209/src/net.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/net.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'primitives/transaction\&.h'\fP
.br
\fC#include 'init\&.h'\fP
.br
\fC#include 'chainparams\&.h'\fP
.br
\fC#include 'db\&.h'\fP
.br
\fC#include 'net\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'ui_interface\&.h'\fP
.br
\fC#include 'sandstorm\&.h'\fP
.br
\fC#include 'wallet\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCNetCleanup\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTOR_NET_STRING\fP   'tor'"
.br
.ti -1c
.RI "#define \fBDUMP_ADDRESSES_INTERVAL\fP   900"
.br
.ti -1c
.RI "#define \fBX\fP(\fBname\fP)   \fBstats\&.name\fP = \fBname\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBOpenNetworkConnection\fP (const \fBCAddress\fP &addrConnect, \fBCSemaphoreGrant\fP *grantOutbound=NULL, const char *strDest=NULL, bool fOneShot=false)"
.br
.ti -1c
.RI "\fBCNodeSignals\fP & \fBGetNodeSignals\fP ()"
.br
.ti -1c
.RI "void \fBAddOneShot\fP (string strDest)"
.br
.ti -1c
.RI "unsigned short \fBGetListenPort\fP ()"
.br
.ti -1c
.RI "bool \fBGetLocal\fP (\fBCService\fP &addr, const \fBCNetAddr\fP *paddrPeer)"
.br
.ti -1c
.RI "\fBCAddress\fP \fBGetLocalAddress\fP (const \fBCNetAddr\fP *paddrPeer)"
.br
.ti -1c
.RI "bool \fBRecvLine\fP (\fBSOCKET\fP hSocket, string &strLine)"
.br
.ti -1c
.RI "void \fBRelayInv\fP (\fBCInv\fP &inv, const int minProtoVersion)"
.br
.ti -1c
.RI "int \fBGetnScore\fP (const \fBCService\fP &addr)"
.br
.ti -1c
.RI "bool \fBIsPeerAddrLocalGood\fP (\fBCNode\fP *pnode)"
.br
.ti -1c
.RI "void \fBSetReachable\fP (enum \fBNetwork\fP net, bool fFlag)"
.br
.ti -1c
.RI "bool \fBAddLocal\fP (const \fBCService\fP &addr, int nScore)"
.br
.ti -1c
.RI "bool \fBAddLocal\fP (const \fBCNetAddr\fP &addr, int nScore)"
.br
.ti -1c
.RI "void \fBSetLimited\fP (enum \fBNetwork\fP net, bool fLimited)"
.br
.ti -1c
.RI "bool \fBIsLimited\fP (enum \fBNetwork\fP net)"
.br
.ti -1c
.RI "bool \fBIsLimited\fP (const \fBCNetAddr\fP &addr)"
.br
.ti -1c
.RI "bool \fBSeenLocal\fP (const \fBCService\fP &addr)"
.br
.ti -1c
.RI "bool \fBIsLocal\fP (const \fBCService\fP &addr)"
.br
.ti -1c
.RI "bool \fBIsReachable\fP (enum \fBNetwork\fP net)"
.br
.ti -1c
.RI "bool \fBIsReachable\fP (const \fBCNetAddr\fP &addr)"
.br
.ti -1c
.RI "void \fBAddressCurrentlyConnected\fP (const \fBCService\fP &addr)"
.br
.ti -1c
.RI "\fBCNode\fP * \fBFindNode\fP (const \fBCNetAddr\fP &ip)"
.br
.ti -1c
.RI "\fBCNode\fP * \fBFindNode\fP (const std::string &addrName)"
.br
.ti -1c
.RI "\fBCNode\fP * \fBFindNode\fP (const \fBCService\fP &addr)"
.br
.ti -1c
.RI "\fBCNode\fP * \fBConnectNode\fP (\fBCAddress\fP addrConnect, const char *pszDest, bool sandStormnode)"
.br
.ti -1c
.RI "void \fBSocketSendData\fP (\fBCNode\fP *pnode)"
.br
.ti -1c
.RI "void \fBThreadSocketHandler\fP ()"
.br
.ti -1c
.RI "void \fBMapPort\fP (bool)"
.br
.ti -1c
.RI "void \fBThreadDNSAddressSeed\fP ()"
.br
.ti -1c
.RI "void \fBDumpAddresses\fP ()"
.br
.ti -1c
.RI "void \fBThreadOpenConnections\fP ()"
.br
.ti -1c
.RI "void \fBThreadOpenAddedConnections\fP ()"
.br
.ti -1c
.RI "void \fBThreadMessageHandler\fP ()"
.br
.ti -1c
.RI "bool \fBBindListenPort\fP (const \fBCService\fP &addrBind, string &strError)"
.br
.ti -1c
.RI "void \fBStartNode\fP (boost::thread_group &threadGroup)"
.br
.ti -1c
.RI "bool \fBStopNode\fP ()"
.br
.ti -1c
.RI "void \fBRelayTransaction\fP (const \fBCTransaction\fP &tx, const \fBuint256\fP &\fBhash\fP)"
.br
.ti -1c
.RI "void \fBRelayTransaction\fP (const \fBCTransaction\fP &tx, const \fBuint256\fP &\fBhash\fP, const \fBCDataStream\fP &ss)"
.br
.ti -1c
.RI "void \fBRelayTransactionLockReq\fP (const \fBCTransaction\fP &tx, const \fBuint256\fP &\fBhash\fP, bool relayToAll)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBfDiscover\fP = true"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBnLocalServices\fP = \fBNODE_NETWORK\fP"
.br
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_mapLocalHost\fP"
.br
.ti -1c
.RI "map< \fBCNetAddr\fP, \fBLocalServiceInfo\fP > \fBmapLocalHost\fP"
.br
.ti -1c
.RI "\fBuint64_t\fP \fBnLocalHostNonce\fP = 0"
.br
.ti -1c
.RI "\fBCAddrMan\fP \fBaddrman\fP"
.br
.ti -1c
.RI "vector< \fBCNode\fP * > \fBvNodes\fP"
.br
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_vNodes\fP"
.br
.ti -1c
.RI "map< \fBCInv\fP, \fBCDataStream\fP > \fBmapRelay\fP"
.br
.ti -1c
.RI "deque< pair< \fBint64_t\fP, \fBCInv\fP > > \fBvRelayExpiration\fP"
.br
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_mapRelay\fP"
.br
.ti -1c
.RI "map< \fBCInv\fP, \fBint64_t\fP > \fBmapAlreadyAskedFor\fP"
.br
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_vOneShots\fP"
.br
.ti -1c
.RI "set< \fBCNetAddr\fP > \fBsetservAddNodeAddresses\fP"
.br
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_setservAddNodeAddresses\fP"
.br
.ti -1c
.RI "vector< std::string > \fBvAddedNodes\fP"
.br
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_vAddedNodes\fP"
.br
.ti -1c
.RI "\fBNodeId\fP \fBnLastNodeId\fP = 0"
.br
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_nLastNodeId\fP"
.br
.ti -1c
.RI "class \fBCNetCleanup\fP \fBinstance_of_cnetcleanup\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DUMP_ADDRESSES_INTERVAL   900"

.PP
Definition at line 35 of file net\&.cpp\&.
.SS "#define TOR_NET_STRING   'tor'"

.PP
Definition at line 32 of file net\&.cpp\&.
.SS "#define X(\fBname\fP)   \fBstats\&.name\fP = \fBname\fP"

.PP
Definition at line 531 of file net\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "bool AddLocal (const \fBCService\fP & addr, int nScore)"

.PP
Definition at line 247 of file net\&.cpp\&.
.SS "bool AddLocal (const \fBCNetAddr\fP & addr, int nScore)"

.PP
Definition at line 276 of file net\&.cpp\&.
.SS "void AddOneShot (string strDest)"

.PP
Definition at line 93 of file net\&.cpp\&.
.SS "void AddressCurrentlyConnected (const \fBCService\fP & addr)"

.PP
Definition at line 337 of file net\&.cpp\&.
.SS "bool BindListenPort (const \fBCService\fP & addrBind, string & strError)"

.PP
Definition at line 1702 of file net\&.cpp\&.
.SS "\fBCNode\fP* ConnectNode (\fBCAddress\fP addrConnect, const char * pszDest, bool sandStormnode)"
debug print 
.PP
Definition at line 378 of file net\&.cpp\&.
.SS "void DumpAddresses ()"

.PP
Definition at line 1310 of file net\&.cpp\&.
.SS "\fBCNode\fP* FindNode (const \fBCNetAddr\fP & ip)"

.PP
Definition at line 347 of file net\&.cpp\&.
.SS "\fBCNode\fP* FindNode (const std::string & addrName)"

.PP
Definition at line 358 of file net\&.cpp\&.
.SS "\fBCNode\fP* FindNode (const \fBCService\fP & addr)"

.PP
Definition at line 367 of file net\&.cpp\&.
.SS "unsigned short GetListenPort ()"

.PP
Definition at line 99 of file net\&.cpp\&.
.SS "bool GetLocal (\fBCService\fP & addr, const \fBCNetAddr\fP * paddrPeer)"

.PP
Definition at line 105 of file net\&.cpp\&.
.SS "\fBCAddress\fP GetLocalAddress (const \fBCNetAddr\fP * paddrPeer)"

.PP
Definition at line 133 of file net\&.cpp\&.
.SS "\fBCNodeSignals\fP& GetNodeSignals ()"

.PP
Definition at line 91 of file net\&.cpp\&.
.SS "int GetnScore (const \fBCService\fP & addr)"

.PP
Definition at line 204 of file net\&.cpp\&.
.SS "bool IsLimited (enum \fBNetwork\fP net)"

.PP
Definition at line 290 of file net\&.cpp\&.
.SS "bool IsLimited (const \fBCNetAddr\fP & addr)"

.PP
Definition at line 296 of file net\&.cpp\&.
.SS "bool IsLocal (const \fBCService\fP & addr)"
check whether a given address is potentially local 
.PP
Definition at line 317 of file net\&.cpp\&.
.SS "bool IsPeerAddrLocalGood (\fBCNode\fP * pnode)"

.PP
Definition at line 213 of file net\&.cpp\&.
.SS "bool IsReachable (enum \fBNetwork\fP net)"
check whether a given network is one we can probably connect to 
.PP
Definition at line 324 of file net\&.cpp\&.
.SS "bool IsReachable (const \fBCNetAddr\fP & addr)"
check whether a given address is in a network we can probably connect to 
.PP
Definition at line 331 of file net\&.cpp\&.
.SS "void MapPort (bool)"

.PP
Definition at line 1248 of file net\&.cpp\&.
.SS "bool OpenNetworkConnection (const \fBCAddress\fP & addrConnect, \fBCSemaphoreGrant\fP * grantOutbound = \fCNULL\fP, const char * strDest = \fCNULL\fP, bool fOneShot = \fCfalse\fP)"

.PP
Definition at line 1516 of file net\&.cpp\&.
.SS "bool RecvLine (\fBSOCKET\fP hSocket, string & strLine)"

.PP
Definition at line 146 of file net\&.cpp\&.
.SS "void RelayInv (\fBCInv\fP & inv, const int minProtoVersion)"

.PP
Definition at line 196 of file net\&.cpp\&.
.SS "void RelayTransaction (const \fBCTransaction\fP & tx, const \fBuint256\fP & hash)"

.PP
Definition at line 1945 of file net\&.cpp\&.
.SS "void RelayTransaction (const \fBCTransaction\fP & tx, const \fBuint256\fP & hash, const \fBCDataStream\fP & ss)"

.PP
Definition at line 1953 of file net\&.cpp\&.
.SS "void RelayTransactionLockReq (const \fBCTransaction\fP & tx, const \fBuint256\fP & hash, bool relayToAll)"

.PP
Definition at line 1973 of file net\&.cpp\&.
.SS "bool SeenLocal (const \fBCService\fP & addr)"
vote for a local address 
.PP
Definition at line 302 of file net\&.cpp\&.
.SS "void SetLimited (enum \fBNetwork\fP net, bool fLimited)"
Make a particular network entirely off-limits (no automatic connects to it) 
.PP
Definition at line 282 of file net\&.cpp\&.
.SS "void SetReachable (enum \fBNetwork\fP net, bool fFlag)"

.PP
Definition at line 238 of file net\&.cpp\&.
.SS "void SocketSendData (\fBCNode\fP * pnode)"

.PP
Definition at line 709 of file net\&.cpp\&.
.SS "void StartNode (boost::thread_group & threadGroup)"

.PP
Definition at line 1858 of file net\&.cpp\&.
.SS "bool StopNode ()"

.PP
Definition at line 1901 of file net\&.cpp\&.
.SS "void ThreadDNSAddressSeed ()"

.PP
Definition at line 1259 of file net\&.cpp\&.
.SS "void ThreadMessageHandler ()"

.PP
Definition at line 1582 of file net\&.cpp\&.
.SS "void ThreadOpenAddedConnections ()"

.PP
Definition at line 1443 of file net\&.cpp\&.
.SS "void ThreadOpenConnections ()"

.PP
Definition at line 1339 of file net\&.cpp\&.
.SS "void ThreadSocketHandler ()"

.PP
Definition at line 754 of file net\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBCAddrMan\fP addrman"

.PP
Definition at line 61 of file net\&.cpp\&.
.SS "\fBCCriticalSection\fP cs_mapLocalHost"

.PP
Definition at line 53 of file net\&.cpp\&.
.SS "\fBCCriticalSection\fP cs_mapRelay"

.PP
Definition at line 72 of file net\&.cpp\&.
.SS "\fBCCriticalSection\fP cs_nLastNodeId"

.PP
Definition at line 85 of file net\&.cpp\&.
.SS "\fBCCriticalSection\fP cs_setservAddNodeAddresses"

.PP
Definition at line 79 of file net\&.cpp\&.
.SS "\fBCCriticalSection\fP cs_vAddedNodes"

.PP
Definition at line 82 of file net\&.cpp\&.
.SS "\fBCCriticalSection\fP cs_vNodes"

.PP
Definition at line 69 of file net\&.cpp\&.
.SS "\fBCCriticalSection\fP cs_vOneShots"

.PP
Definition at line 76 of file net\&.cpp\&.
.SS "bool fDiscover = true"

.PP
Definition at line 47 of file net\&.cpp\&.
.SS "class \fBCNetCleanup\fP
 instance_of_cnetcleanup"

.SS "map<\fBCInv\fP, \fBint64_t\fP> mapAlreadyAskedFor"

.PP
Definition at line 73 of file net\&.cpp\&.
.SS "map<\fBCNetAddr\fP, \fBLocalServiceInfo\fP> mapLocalHost"

.PP
Definition at line 54 of file net\&.cpp\&.
.SS "map<\fBCInv\fP, \fBCDataStream\fP> mapRelay"

.PP
Definition at line 70 of file net\&.cpp\&.
.SS "\fBNodeId\fP nLastNodeId = 0"

.PP
Definition at line 84 of file net\&.cpp\&.
.SS "\fBuint64_t\fP nLocalHostNonce = 0"

.PP
Definition at line 59 of file net\&.cpp\&.
.SS "\fBuint64_t\fP nLocalServices = \fBNODE_NETWORK\fP"

.PP
Definition at line 51 of file net\&.cpp\&.
.SS "set<\fBCNetAddr\fP> setservAddNodeAddresses"

.PP
Definition at line 78 of file net\&.cpp\&.
.SS "vector<std::string> vAddedNodes"

.PP
Definition at line 81 of file net\&.cpp\&.
.SS "vector<\fBCNode\fP*> vNodes"

.PP
Definition at line 68 of file net\&.cpp\&.
.SS "deque<pair<\fBint64_t\fP, \fBCInv\fP> > vRelayExpiration"

.PP
Definition at line 71 of file net\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
