.TH "Notificator" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Notificator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <notificator\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBClass\fP { \fBInformation\fP, \fBWarning\fP, \fBCritical\fP }"
.br
.in -1c
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBnotify\fP (\fBClass\fP cls, const QString &title, const QString &text, const QIcon &icon=QIcon(), int millisTimeout=10000)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNotificator\fP (const QString &programName=QString(), QSystemTrayIcon *trayIcon=0, QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~Notificator\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Cross-platform desktop notification client\&. 
.PP
Definition at line 15 of file notificator\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBNotificator::Class\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIInformation \fP\fP
Informational message 
.TP
\fB\fIWarning \fP\fP
Notify user of potential problem 
.TP
\fB\fICritical \fP\fP
An error occurred 
.PP
Definition at line 27 of file notificator\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Notificator::Notificator (const QString & programName = \fCQString()\fP, QSystemTrayIcon * trayIcon = \fC0\fP, QWidget * parent = \fC0\fP)"
Create a new notificator\&. 
.PP
\fBNote:\fP
.RS 4
Ownership of trayIcon is not transferred to this object\&. 
.RE
.PP

.PP
Definition at line 27 of file notificator\&.cpp\&.
.SS "Notificator::~Notificator ()"

.PP
Definition at line 57 of file notificator\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Notificator::notify (\fBClass\fP cls, const QString & title, const QString & text, const QIcon & icon = \fCQIcon()\fP, int millisTimeout = \fC10000\fP)\fC [slot]\fP"
Show notification message\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcls\fP general message class 
.br
\fItitle\fP title shown with message 
.br
\fItext\fP message content 
.br
\fIicon\fP optional icon to show with message 
.br
\fImillisTimeout\fP notification timeout in milliseconds (defaults to 10 seconds) 
.RE
.PP
\fBNote:\fP
.RS 4
Platform implementations are free to ignore any of the provided fields except for \fItext\fP\&. 
.RE
.PP

.PP
Definition at line 227 of file notificator\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
