.TH "/home/dev/ds-160209/src/secp256k1/src/num_gmp_impl.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/secp256k1/src/num_gmp_impl.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <gmp\&.h>\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'num\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBsecp256k1_num_sanity\fP(a)   do { } while(0)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define secp256k1_num_sanity(a)   do { } while(0)"

.PP
Definition at line 22 of file num_gmp_impl\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
