.TH "/home/dev/ds-160209/src/secp256k1/src/num_gmp.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/secp256k1/src/num_gmp.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <gmp\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsecp256k1_num\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNUM_LIMBS\fP   ((256+GMP_NUMB_BITS-1)/GMP_NUMB_BITS)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NUM_LIMBS   ((256+GMP_NUMB_BITS-1)/GMP_NUMB_BITS)"

.PP
Definition at line 12 of file num_gmp\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
