.TH "/home/dev/ds-160209/src/crypto/argon2/opt.c" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/crypto/argon2/opt.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'argon2\&.h'\fP
.br
\fC#include 'opt\&.h'\fP
.br
\fC#include 'blake2/blake2\&.h'\fP
.br
\fC#include 'blake2/blamka-round-opt\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfill_block\fP (__m128i *\fBstate\fP, const \fBuint8_t\fP *ref_block, \fBuint8_t\fP *next_block)"
.br
.ti -1c
.RI "void \fBgenerate_addresses\fP (const \fBargon2_instance_t\fP *instance, const \fBargon2_position_t\fP *position, \fBuint64_t\fP *pseudo_rands)"
.br
.ti -1c
.RI "void \fBfill_segment\fP (const \fBargon2_instance_t\fP *instance, \fBargon2_position_t\fP position)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void fill_block (__m128i * state, const \fBuint8_t\fP * ref_block, \fBuint8_t\fP * next_block)"

.PP
Definition at line 24 of file opt\&.c\&.
.SS "void fill_segment (const \fBargon2_instance_t\fP * instance, \fBargon2_position_t\fP position)"

.PP
Definition at line 86 of file opt\&.c\&.
.SS "void generate_addresses (const \fBargon2_instance_t\fP * instance, const \fBargon2_position_t\fP * position, \fBuint64_t\fP * pseudo_rands)"

.PP
Definition at line 51 of file opt\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
