.TH "OptionsModel" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OptionsModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <optionsmodel\&.h>\fP
.PP
Inherits QAbstractListModel\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBOptionID\fP { \fBStartAtStartup\fP, \fBMinimizeToTray\fP, \fBMapPortUPnP\fP, \fBMinimizeOnClose\fP, \fBProxyUse\fP, \fBProxyIP\fP, \fBProxyPort\fP, \fBFee\fP, \fBReserveBalance\fP, \fBDisplayUnit\fP, \fBLanguage\fP, \fBCoinControlFeatures\fP, \fBUseBlackTheme\fP, \fBSandstormRounds\fP, \fBAnonymizeDarkSilkAmount\fP, \fBOptionIDRowCount\fP }"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBdisplayUnitChanged\fP (int unit)"
.br
.ti -1c
.RI "void \fBtransactionFeeChanged\fP (qint64)"
.br
.ti -1c
.RI "void \fBreserveBalanceChanged\fP (qint64)"
.br
.ti -1c
.RI "void \fBcoinControlFeaturesChanged\fP (bool)"
.br
.ti -1c
.RI "void \fBsandstormRoundsChanged\fP (int)"
.br
.ti -1c
.RI "void \fBAnonymizeDarkSilkAmountChanged\fP (int)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptionsModel\fP (QObject *parent=0)"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "int \fBrowCount\fP (const QModelIndex &parent=QModelIndex()) const "
.br
.ti -1c
.RI "QVariant \fBdata\fP (const QModelIndex &index, int role=Qt::DisplayRole) const "
.br
.ti -1c
.RI "bool \fBsetData\fP (const QModelIndex &index, const QVariant &\fBvalue\fP, int role=Qt::EditRole)"
.br
.ti -1c
.RI "qint64 \fBgetTransactionFee\fP ()"
.br
.ti -1c
.RI "qint64 \fBgetReserveBalance\fP ()"
.br
.ti -1c
.RI "bool \fBgetMinimizeToTray\fP ()"
.br
.ti -1c
.RI "bool \fBgetMinimizeOnClose\fP ()"
.br
.ti -1c
.RI "int \fBgetDisplayUnit\fP ()"
.br
.ti -1c
.RI "bool \fBgetCoinControlFeatures\fP ()"
.br
.ti -1c
.RI "QString \fBgetLanguage\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface from Qt to configuration data structure for DarkSilk client\&. To Qt, the options are presented as a list with the different options laid out vertically\&. This can be changed to a tree once the settings become sufficiently complex\&. 
.PP
Definition at line 14 of file optionsmodel\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBOptionsModel::OptionID\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIStartAtStartup \fP\fP
.TP
\fB\fIMinimizeToTray \fP\fP
.TP
\fB\fIMapPortUPnP \fP\fP
.TP
\fB\fIMinimizeOnClose \fP\fP
.TP
\fB\fIProxyUse \fP\fP
.TP
\fB\fIProxyIP \fP\fP
.TP
\fB\fIProxyPort \fP\fP
.TP
\fB\fIFee \fP\fP
.TP
\fB\fIReserveBalance \fP\fP
.TP
\fB\fIDisplayUnit \fP\fP
.TP
\fB\fILanguage \fP\fP
.TP
\fB\fICoinControlFeatures \fP\fP
.TP
\fB\fIUseBlackTheme \fP\fP
.TP
\fB\fISandstormRounds \fP\fP
.TP
\fB\fIAnonymizeDarkSilkAmount \fP\fP
.TP
\fB\fIOptionIDRowCount \fP\fP
.PP
Definition at line 21 of file optionsmodel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OptionsModel::OptionsModel (QObject * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 38 of file optionsmodel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void OptionsModel::AnonymizeDarkSilkAmountChanged (int)\fC [signal]\fP"

.SS "void OptionsModel::coinControlFeaturesChanged (bool)\fC [signal]\fP"

.SS "QVariant OptionsModel::data (const QModelIndex & index, int role = \fCQt::DisplayRole\fP) const"

.PP
Definition at line 206 of file optionsmodel\&.cpp\&.
.SS "void OptionsModel::displayUnitChanged (int unit)\fC [signal]\fP"

.SS "bool OptionsModel::getCoinControlFeatures ()"

.PP
Definition at line 538 of file optionsmodel\&.cpp\&.
.SS "int OptionsModel::getDisplayUnit ()"

.PP
Definition at line 553 of file optionsmodel\&.cpp\&.
.SS "QString OptionsModel::getLanguage ()\fC [inline]\fP"

.PP
Definition at line 74 of file optionsmodel\&.h\&.
.SS "bool OptionsModel::getMinimizeOnClose ()"

.PP
Definition at line 548 of file optionsmodel\&.cpp\&.
.SS "bool OptionsModel::getMinimizeToTray ()"

.PP
Definition at line 543 of file optionsmodel\&.cpp\&.
.SS "qint64 OptionsModel::getReserveBalance ()"

.PP
Definition at line 533 of file optionsmodel\&.cpp\&.
.SS "qint64 OptionsModel::getTransactionFee ()"

.PP
Definition at line 528 of file optionsmodel\&.cpp\&.
.SS "void OptionsModel::Init ()"

.PP
Definition at line 108 of file optionsmodel\&.cpp\&.
.SS "void OptionsModel::reserveBalanceChanged (qint64)\fC [signal]\fP"

.SS "int OptionsModel::rowCount (const QModelIndex & parent = \fCQModelIndex()\fP) const"

.PP
Definition at line 201 of file optionsmodel\&.cpp\&.
.SS "void OptionsModel::sandstormRoundsChanged (int)\fC [signal]\fP"

.SS "bool OptionsModel::setData (const QModelIndex & index, const QVariant & value, int role = \fCQt::EditRole\fP)"

.PP
Definition at line 315 of file optionsmodel\&.cpp\&.
.SS "void OptionsModel::transactionFeeChanged (qint64)\fC [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
