.TH "OptionsDialog" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OptionsDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <optionsdialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBproxyIpValid\fP (\fBQValidatedLineEdit\fP *object, bool fValid)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOptionsDialog\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~OptionsDialog\fP ()"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBOptionsModel\fP *model)"
.br
.ti -1c
.RI "void \fBsetMapper\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBeventFilter\fP (QObject *object, QEvent *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Preferences dialog\&. 
.PP
Definition at line 22 of file optionsdialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OptionsDialog::OptionsDialog (QWidget * parent = \fC0\fP)\fC [explicit]\fP"
check if the locale name consists of 2 parts (language_country)
.PP
display language strings as 'language - country (locale name)', e\&.g\&. 'German - Germany (de)'
.PP
display language strings as 'language (locale name)', e\&.g\&. 'German (de)' 
.PP
Definition at line 18 of file optionsdialog\&.cpp\&.
.SS "OptionsDialog::~OptionsDialog ()"

.PP
Definition at line 101 of file optionsdialog\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool OptionsDialog::eventFilter (QObject * object, QEvent * event)\fC [protected]\fP"

.PP
Definition at line 278 of file optionsdialog\&.cpp\&.
.SS "void OptionsDialog::proxyIpValid (\fBQValidatedLineEdit\fP * object, bool fValid)\fC [signal]\fP"

.SS "void OptionsDialog::setMapper ()"

.PP
Definition at line 142 of file optionsdialog\&.cpp\&.
.SS "void OptionsDialog::setModel (\fBOptionsModel\fP * model)"

.PP
Definition at line 106 of file optionsdialog\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
