.TH "/home/dev/ds-160209/src/leveldb/include/leveldb/options.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/include/leveldb/options.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBleveldb::Options\fP"
.br
.ti -1c
.RI "struct \fBleveldb::ReadOptions\fP"
.br
.ti -1c
.RI "struct \fBleveldb::WriteOptions\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBleveldb::CompressionType\fP { \fBleveldb::kNoCompression\fP = 0x0, \fBleveldb::kSnappyCompression\fP = 0x1 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
