.TH "/home/dev/ds-160209/src/secp256k1/src/java/org_bitcoin_NativeSecp256k1.c" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/secp256k1/src/java/org_bitcoin_NativeSecp256k1.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'org_bitcoin_NativeSecp256k1\&.h'\fP
.br
\fC#include 'include/secp256k1\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "JNIEXPORT jint JNICALL \fBJava_org_bitcoin_NativeSecp256k1_secp256k1_1ecdsa_1verify\fP (JNIEnv *env, jclass classObject, jobject byteBufferObject)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "JNIEXPORT jint JNICALL Java_org_bitcoin_NativeSecp256k1_secp256k1_1ecdsa_1verify (JNIEnv * env, jclass classObject, jobject byteBufferObject)"

.PP
Definition at line 5 of file org_bitcoin_NativeSecp256k1\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
