.TH "OverviewPage" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OverviewPage \- Overview ('home') page widget\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <overviewpage\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsandStormStatus\fP ()"
.br
.ti -1c
.RI "void \fBsetBalance\fP (const \fBCAmount\fP &balance, const \fBCAmount\fP &stake, const \fBCAmount\fP &unconfirmedBalance, const \fBCAmount\fP &immatureBalance, const \fBCAmount\fP &anonymizedBalance, const \fBCAmount\fP &watchOnlyBalance, const \fBCAmount\fP &watchOnlyStake, const \fBCAmount\fP &watchUnconfBalance, const \fBCAmount\fP &watchImmatureBalance)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBtransactionClicked\fP (const QModelIndex &index)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOverviewPage\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~OverviewPage\fP ()"
.br
.ti -1c
.RI "void \fBsetClientModel\fP (\fBClientModel\fP *clientModel)"
.br
.ti -1c
.RI "void \fBsetWalletModel\fP (\fBWalletModel\fP *walletModel)"
.br
.ti -1c
.RI "void \fBshowOutOfSyncWarning\fP (bool fShow)"
.br
.ti -1c
.RI "void \fBupdateSandstormProgress\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Overview ('home') page widget\&. 
.PP
Definition at line 23 of file overviewpage\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OverviewPage::OverviewPage (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 101 of file overviewpage\&.cpp\&.
.SS "OverviewPage::~OverviewPage ()"

.PP
Definition at line 180 of file overviewpage\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void OverviewPage::sandStormStatus ()\fC [slot]\fP"

.PP
Definition at line 396 of file overviewpage\&.cpp\&.
.SS "void OverviewPage::setBalance (const \fBCAmount\fP & balance, const \fBCAmount\fP & stake, const \fBCAmount\fP & unconfirmedBalance, const \fBCAmount\fP & immatureBalance, const \fBCAmount\fP & anonymizedBalance, const \fBCAmount\fP & watchOnlyBalance, const \fBCAmount\fP & watchOnlyStake, const \fBCAmount\fP & watchUnconfBalance, const \fBCAmount\fP & watchImmatureBalance)\fC [slot]\fP"

.PP
Definition at line 186 of file overviewpage\&.cpp\&.
.SS "void OverviewPage::setClientModel (\fBClientModel\fP * clientModel)"

.PP
Definition at line 223 of file overviewpage\&.cpp\&.
.SS "void OverviewPage::setWalletModel (\fBWalletModel\fP * walletModel)"

.PP
Definition at line 234 of file overviewpage\&.cpp\&.
.SS "void OverviewPage::showOutOfSyncWarning (bool fShow)"

.PP
Definition at line 291 of file overviewpage\&.cpp\&.
.SS "void OverviewPage::transactionClicked (const QModelIndex & index)\fC [signal]\fP"

.SS "void OverviewPage::updateSandstormProgress ()"

.PP
Definition at line 299 of file overviewpage\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
