.TH "/home/dev/ds-160209/src/qt/paymentserver.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/paymentserver.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QApplication>\fP
.br
\fC#include 'paymentserver\&.h'\fP
.br
\fC#include 'guiconstants\&.h'\fP
.br
\fC#include 'ui_interface\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include <QByteArray>\fP
.br
\fC#include <QDataStream>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QFileOpenEvent>\fP
.br
\fC#include <QHash>\fP
.br
\fC#include <QLocalServer>\fP
.br
\fC#include <QLocalSocket>\fP
.br
\fC#include <QStringList>\fP
.br
\fC#include <QUrl>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const QString \fBDARKSILK_IPC_PREFIX\fP ('darksilk:')"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBDARKSILK_IPC_CONNECT_TIMEOUT\fP = 1000"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const QString DARKSILK_IPC_PREFIX ('darksilk:')"

.SH "Variable Documentation"
.PP 
.SS "const int DARKSILK_IPC_CONNECT_TIMEOUT = 1000"

.PP
Definition at line 26 of file paymentserver\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
