.TH "PaymentServer" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PaymentServer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <paymentserver\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBuiReady\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBreceivedURI\fP (QString)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPaymentServer\fP (QApplication *parent)"
.br
.ti -1c
.RI "bool \fBeventFilter\fP (QObject *object, QEvent *event)"
.br
.ti -1c
.RI "void \fBsetOptionsModel\fP (\fBOptionsModel\fP *optionsModel)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBipcSendCommandLine\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file paymentserver\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PaymentServer::PaymentServer (QApplication * parent)"

.PP
Definition at line 95 of file paymentserver\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool PaymentServer::eventFilter (QObject * object, QEvent * event)"

.PP
Definition at line 113 of file paymentserver\&.cpp\&.
.SS "bool PaymentServer::ipcSendCommandLine ()\fC [static]\fP"

.PP
Definition at line 60 of file paymentserver\&.cpp\&.
.SS "void PaymentServer::receivedURI (QString)\fC [signal]\fP"

.SS "void PaymentServer::setOptionsModel (\fBOptionsModel\fP * optionsModel)"

.PP
Definition at line 163 of file paymentserver\&.cpp\&.
.SS "void PaymentServer::uiReady ()\fC [slot]\fP"

.PP
Definition at line 131 of file paymentserver\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
