.TH "PeerTablePriv" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PeerTablePriv \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrefreshPeers\fP ()"
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.ti -1c
.RI "\fBCNodeCombinedStats\fP * \fBindex\fP (int idx)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QList< \fBCNodeCombinedStats\fP > \fBcachedNodeStats\fP"
.br
.ti -1c
.RI "int \fBsortColumn\fP"
.br
.ti -1c
.RI "Qt::SortOrder \fBsortOrder\fP"
.br
.ti -1c
.RI "std::map< \fBNodeId\fP, int > \fBmapNodeRows\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file peertablemodel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCNodeCombinedStats\fP* PeerTablePriv::index (int idx)\fC [inline]\fP"

.PP
Definition at line 104 of file peertablemodel\&.cpp\&.
.SS "void PeerTablePriv::refreshPeers ()\fC [inline]\fP"
Pull a full list of peers from vNodes into our cache 
.PP
Definition at line 53 of file peertablemodel\&.cpp\&.
.SS "int PeerTablePriv::size ()\fC [inline]\fP"

.PP
Definition at line 99 of file peertablemodel\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QList<\fBCNodeCombinedStats\fP> PeerTablePriv::cachedNodeStats"
Local cache of peer information 
.PP
Definition at line 44 of file peertablemodel\&.cpp\&.
.SS "std::map<\fBNodeId\fP, int> PeerTablePriv::mapNodeRows"
Index of rows by node ID 
.PP
Definition at line 50 of file peertablemodel\&.cpp\&.
.SS "int PeerTablePriv::sortColumn"
Column to sort nodes by 
.PP
Definition at line 46 of file peertablemodel\&.cpp\&.
.SS "Qt::SortOrder PeerTablePriv::sortOrder"
Order (ascending or descending) to sort nodes by 
.PP
Definition at line 48 of file peertablemodel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
