.TH "PeerTableModel" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PeerTableModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <peertablemodel\&.h>\fP
.PP
Inherits QAbstractTableModel\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBColumnIndex\fP { \fBAddress\fP = 0, \fBSubversion\fP = 1, \fBPing\fP = 2 }"
.br
.in -1c
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBrefresh\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPeerTableModel\fP (\fBClientModel\fP *parent=0)"
.br
.ti -1c
.RI "const \fBCNodeCombinedStats\fP * \fBgetNodeStats\fP (int idx)"
.br
.ti -1c
.RI "int \fBgetRowByNodeId\fP (\fBNodeId\fP nodeid)"
.br
.ti -1c
.RI "void \fBstartAutoRefresh\fP ()"
.br
.ti -1c
.RI "void \fBstopAutoRefresh\fP ()"
.br
.in -1c
.PP
.RI "\fBMethods overridden from QAbstractTableModel\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "int \fBrowCount\fP (const QModelIndex &parent) const "
.br
.ti -1c
.RI "int \fBcolumnCount\fP (const QModelIndex &parent) const "
.br
.ti -1c
.RI "QVariant \fBdata\fP (const QModelIndex &\fBindex\fP, int role) const "
.br
.ti -1c
.RI "QVariant \fBheaderData\fP (int section, Qt::Orientation orientation, int role) const "
.br
.ti -1c
.RI "QModelIndex \fBindex\fP (int row, int column, const QModelIndex &parent) const "
.br
.ti -1c
.RI "Qt::ItemFlags \fBflags\fP (const QModelIndex &\fBindex\fP) const "
.br
.ti -1c
.RI "void \fBsort\fP (int column, Qt::SortOrder order)"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Qt model providing information about connected peers, similar to the 'getpeerinfo' RPC call\&. Used by the rpc console UI\&. 
.PP
Definition at line 43 of file peertablemodel\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBPeerTableModel::ColumnIndex\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIAddress \fP\fP
.TP
\fB\fISubversion \fP\fP
.TP
\fB\fIPing \fP\fP
.PP
Definition at line 54 of file peertablemodel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PeerTableModel::PeerTableModel (\fBClientModel\fP * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 114 of file peertablemodel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int PeerTableModel::columnCount (const QModelIndex & parent) const"

.PP
Definition at line 149 of file peertablemodel\&.cpp\&.
.SS "QVariant PeerTableModel::data (const QModelIndex & index, int role) const"

.PP
Definition at line 155 of file peertablemodel\&.cpp\&.
.SS "Qt::ItemFlags PeerTableModel::flags (const QModelIndex & index) const"

.PP
Definition at line 192 of file peertablemodel\&.cpp\&.
.SS "const \fBCNodeCombinedStats\fP * PeerTableModel::getNodeStats (int idx)"

.PP
Definition at line 216 of file peertablemodel\&.cpp\&.
.SS "int PeerTableModel::getRowByNodeId (\fBNodeId\fP nodeid)"

.PP
Definition at line 228 of file peertablemodel\&.cpp\&.
.SS "QVariant PeerTableModel::headerData (int section, Qt::Orientation orientation, int role) const"

.PP
Definition at line 180 of file peertablemodel\&.cpp\&.
.SS "QModelIndex PeerTableModel::index (int row, int column, const QModelIndex & parent) const"

.PP
Definition at line 201 of file peertablemodel\&.cpp\&.
.SS "void PeerTableModel::refresh ()\fC [slot]\fP"

.PP
Definition at line 221 of file peertablemodel\&.cpp\&.
.SS "int PeerTableModel::rowCount (const QModelIndex & parent) const"

.PP
Definition at line 143 of file peertablemodel\&.cpp\&.
.SS "void PeerTableModel::sort (int column, Qt::SortOrder order)"

.PP
Definition at line 237 of file peertablemodel\&.cpp\&.
.SS "void PeerTableModel::startAutoRefresh ()"

.PP
Definition at line 133 of file peertablemodel\&.cpp\&.
.SS "void PeerTableModel::stopAutoRefresh ()"

.PP
Definition at line 138 of file peertablemodel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
