.TH "/home/dev/ds-160209/src/protocol.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/protocol.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'chainparams\&.h'\fP
.br
\fC#include 'serialize\&.h'\fP
.br
\fC#include 'netbase\&.h'\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCMessageHeader\fP"
.br
.ti -1c
.RI "class \fBCAddress\fP"
.br
.ti -1c
.RI "class \fBCInv\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBNODE_NETWORK\fP = (1 << 0) }"
.br
.ti -1c
.RI "enum { \fBMSG_TX\fP = 1, \fBMSG_BLOCK\fP, \fBMSG_FILTERED_BLOCK\fP, \fBMSG_TXLOCK_REQUEST\fP, \fBMSG_TXLOCK_VOTE\fP, \fBMSG_SPORK\fP, \fBMSG_STORMNODE_WINNER\fP, \fBMSG_BUDGET_VOTE\fP, \fBMSG_BUDGET_PROPOSAL\fP, \fBMSG_BUDGET_FINALIZED\fP, \fBMSG_BUDGET_FINALIZED_VOTE\fP, \fBMSG_STORMNODE_QUORUM\fP, \fBMSG_STORMNODE_ANNOUNCE\fP, \fBMSG_STORMNODE_PING\fP, \fBMSG_SSTX\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"
nServices flags 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINODE_NETWORK \fP\fP
.PP
Definition at line 65 of file protocol\&.h\&.
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMSG_TX \fP\fP
.TP
\fB\fIMSG_BLOCK \fP\fP
.TP
\fB\fIMSG_FILTERED_BLOCK \fP\fP
.TP
\fB\fIMSG_TXLOCK_REQUEST \fP\fP
.TP
\fB\fIMSG_TXLOCK_VOTE \fP\fP
.TP
\fB\fIMSG_SPORK \fP\fP
.TP
\fB\fIMSG_STORMNODE_WINNER \fP\fP
.TP
\fB\fIMSG_BUDGET_VOTE \fP\fP
.TP
\fB\fIMSG_BUDGET_PROPOSAL \fP\fP
.TP
\fB\fIMSG_BUDGET_FINALIZED \fP\fP
.TP
\fB\fIMSG_BUDGET_FINALIZED_VOTE \fP\fP
.TP
\fB\fIMSG_STORMNODE_QUORUM \fP\fP
.TP
\fB\fIMSG_STORMNODE_ANNOUNCE \fP\fP
.TP
\fB\fIMSG_STORMNODE_PING \fP\fP
.TP
\fB\fIMSG_SSTX \fP\fP
.PP
Definition at line 141 of file protocol\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
