.TH "/home/dev/ds-160209/src/protocol.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/protocol.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'protocol\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBCInv\fP &a, const \fBCInv\fP &b)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool operator< (const \fBCInv\fP & a, const \fBCInv\fP & b)"

.PP
Definition at line 141 of file protocol\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
