.TH "qdarkstyle.pyqt_style_rc" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qdarkstyle.pyqt_style_rc \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBqInitResources\fP ()"
.br
.ti -1c
.RI "def \fBqCleanupResources\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBqt_resource_data\fP"
.br
.ti -1c
.RI "string \fBqt_resource_name\fP"
.br
.ti -1c
.RI "string \fBqt_resource_struct\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def qdarkstyle\&.pyqt_style_rc\&.qCleanupResources ()"

.PP
Definition at line 823 of file pyqt_style_rc\&.py\&.
.SS "def qdarkstyle\&.pyqt_style_rc\&.qInitResources ()"

.PP
Definition at line 820 of file pyqt_style_rc\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "string qdarkstyle\&.pyqt_style_rc\&.qt_resource_data"

.PP
Definition at line 12 of file pyqt_style_rc\&.py\&.
.SS "string qdarkstyle\&.pyqt_style_rc\&.qt_resource_name"

.PP
Definition at line 661 of file pyqt_style_rc\&.py\&.
.SS "string qdarkstyle\&.pyqt_style_rc\&.qt_resource_struct"

.PP
Definition at line 788 of file pyqt_style_rc\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
