.TH "qdarkstyle" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qdarkstyle \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBcompile_qrc\fP"
.br
.ti -1c
.RI " \fBpyqt5_style_rc\fP"
.br
.ti -1c
.RI " \fBpyqt_style_rc\fP"
.br
.ti -1c
.RI " \fBpyside_style_rc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBload_stylesheet\fP"
.br
.ti -1c
.RI "def \fBload_stylesheet_pyqt5\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fB__version__\fP = '1\&.12'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def qdarkstyle\&.load_stylesheet ( pyside = \fCTrue\fP)"

.PP
.nf
Loads the stylesheet. Takes care of importing the rc module.

:param pyside: True to load the pyside rc file, False to load the PyQt rc file

:return the stylesheet string

.fi
.PP
 
.PP
Definition at line 42 of file __init__\&.py\&.
.SS "def qdarkstyle\&.load_stylesheet_pyqt5 ()"

.PP
.nf
Loads the stylesheet for use in a pyqt5 application.

:param pyside: True to load the pyside rc file, False to load the PyQt rc file

:return the stylesheet string

.fi
.PP
 
.PP
Definition at line 83 of file __init__\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "string qdarkstyle\&.__version__ = '1\&.12'"

.PP
Definition at line 35 of file __init__\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
