.TH "QRCodeDialog" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QRCodeDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qrcodedialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQRCodeDialog\fP (const QString &addr, const QString &label, bool enableReq, QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~QRCodeDialog\fP ()"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBOptionsModel\fP *model)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file qrcodedialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QRCodeDialog::QRCodeDialog (const QString & addr, const QString & label, bool enableReq, QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 14 of file qrcodedialog\&.cpp\&.
.SS "QRCodeDialog::~QRCodeDialog ()"

.PP
Definition at line 35 of file qrcodedialog\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void QRCodeDialog::setModel (\fBOptionsModel\fP * model)"

.PP
Definition at line 40 of file qrcodedialog\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
