.TH "QValidatedLineEdit" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QValidatedLineEdit \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qvalidatedlineedit\&.h>\fP
.PP
Inherits QLineEdit\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetValid\fP (bool valid)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQValidatedLineEdit\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBfocusInEvent\fP (QFocusEvent *evt)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Line edit that can be marked as 'invalid' to show input validation feedback\&. When marked as invalid, it will get a red background until it is focused\&. 
.PP
Definition at line 9 of file qvalidatedlineedit\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QValidatedLineEdit::QValidatedLineEdit (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 5 of file qvalidatedlineedit\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void QValidatedLineEdit::clear ()"

.PP
Definition at line 41 of file qvalidatedlineedit\&.cpp\&.
.SS "void QValidatedLineEdit::focusInEvent (QFocusEvent * evt)\fC [protected]\fP"

.PP
Definition at line 29 of file qvalidatedlineedit\&.cpp\&.
.SS "void QValidatedLineEdit::setValid (bool valid)\fC [slot]\fP"

.PP
Definition at line 11 of file qvalidatedlineedit\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
