.TH "QValueComboBox" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QValueComboBox \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qvaluecombobox\&.h>\fP
.PP
Inherits QComboBox\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBvalueChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQValueComboBox\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "QVariant \fBvalue\fP () const "
.br
.ti -1c
.RI "void \fBsetValue\fP (const QVariant &\fBvalue\fP)"
.br
.ti -1c
.RI "void \fBsetRole\fP (int role)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QVariant \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file qvaluecombobox\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QValueComboBox::QValueComboBox (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 5 of file qvaluecombobox\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void QValueComboBox::setRole (int role)"
Specify model role to use as ordinal value (defaults to Qt::UserRole) 
.PP
Definition at line 23 of file qvaluecombobox\&.cpp\&.
.SS "void QValueComboBox::setValue (const QVariant & value)"

.PP
Definition at line 18 of file qvaluecombobox\&.cpp\&.
.SS "QVariant QValueComboBox::value () const"

.SS "void QValueComboBox::valueChanged ()\fC [signal]\fP"

.SH "Property Documentation"
.PP 
.SS "QVariant QValueComboBox::value\fC [read]\fP, \fC [write]\fP"

.PP
Definition at line 12 of file qvaluecombobox\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
