.TH "/home/dev/ds-160209/src/crypto/argon2/ref.c" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/crypto/argon2/ref.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'argon2\&.h'\fP
.br
\fC#include 'ref\&.h'\fP
.br
\fC#include 'blake2/blamka-round-ref\&.h'\fP
.br
\fC#include 'blake2/blake2-impl\&.h'\fP
.br
\fC#include 'blake2/blake2\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfill_block\fP (const \fBblock\fP *prev_block, const \fBblock\fP *ref_block, \fBblock\fP *next_block)"
.br
.ti -1c
.RI "void \fBgenerate_addresses\fP (const \fBargon2_instance_t\fP *instance, const \fBargon2_position_t\fP *position, \fBuint64_t\fP *pseudo_rands)"
.br
.ti -1c
.RI "void \fBfill_segment\fP (const \fBargon2_instance_t\fP *instance, \fBargon2_position_t\fP position)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void fill_block (const \fBblock\fP * prev_block, const \fBblock\fP * ref_block, \fBblock\fP * next_block)"

.PP
Definition at line 25 of file ref\&.c\&.
.SS "void fill_segment (const \fBargon2_instance_t\fP * instance, \fBargon2_position_t\fP position)"

.PP
Definition at line 92 of file ref\&.c\&.
.SS "void generate_addresses (const \fBargon2_instance_t\fP * instance, const \fBargon2_position_t\fP * position, \fBuint64_t\fP * pseudo_rands)"

.PP
Definition at line 62 of file ref\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
