.TH "RFC6979_HMAC_SHA256" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RFC6979_HMAC_SHA256 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rfc6979_hmac_sha256\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRFC6979_HMAC_SHA256\fP (const unsigned char *key, size_t keylen, const unsigned char *msg, size_t msglen)"
.br
.ti -1c
.RI "void \fBGenerate\fP (unsigned char *output, size_t outputlen)"
.br
.ti -1c
.RI "\fB~RFC6979_HMAC_SHA256\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The RFC 6979 PRNG using HMAC-SHA256\&. 
.PP
Definition at line 14 of file rfc6979_hmac_sha256\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RFC6979_HMAC_SHA256::RFC6979_HMAC_SHA256 (const unsigned char * key, size_t keylen, const unsigned char * msg, size_t msglen)"
Construct a new RFC6979 PRNG, using the given key and message\&. The message is assumed to be already hashed\&. 
.PP
Definition at line 14 of file rfc6979_hmac_sha256\&.cpp\&.
.SS "RFC6979_HMAC_SHA256::~RFC6979_HMAC_SHA256 ()"

.PP
Definition at line 25 of file rfc6979_hmac_sha256\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void RFC6979_HMAC_SHA256::Generate (unsigned char * output, size_t outputlen)"
Generate a byte array\&. 
.PP
Definition at line 31 of file rfc6979_hmac_sha256\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
