.TH "/home/dev/ds-160209/src/rpcblockchain.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/rpcblockchain.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'rpcserver\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'kernel\&.h'\fP
.br
\fC#include 'checkpoints\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTxToJSON\fP (const \fBCTransaction\fP &tx, const \fBuint256\fP hashBlock, \fBjson_spirit::Object\fP &entry)"
.br
.ti -1c
.RI "double \fBGetDifficulty\fP (const \fBCBlockIndex\fP *blockindex)"
.br
.ti -1c
.RI "double \fBGetPoWMHashPS\fP ()"
.br
.ti -1c
.RI "double \fBGetPoSKernelPS\fP ()"
.br
.ti -1c
.RI "\fBObject\fP \fBblockToJSON\fP (const \fBCBlock\fP &\fBblock\fP, const \fBCBlockIndex\fP *blockindex, bool fPrintTransactionDetail)"
.br
.ti -1c
.RI "\fBValue\fP \fBgetbestblockhash\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBgetblockcount\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBgetdifficulty\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBgetrawmempool\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBgetblockhash\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBgetblock\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBgetblockbynumber\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBgetcheckpoint\fP (const \fBArray\fP &params, bool fHelp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBObject\fP blockToJSON (const \fBCBlock\fP & block, const \fBCBlockIndex\fP * blockindex, bool fPrintTransactionDetail)"

.PP
Definition at line 108 of file rpcblockchain\&.cpp\&.
.SS "\fBValue\fP getbestblockhash (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 162 of file rpcblockchain\&.cpp\&.
.SS "\fBValue\fP getblock (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 229 of file rpcblockchain\&.cpp\&.
.SS "\fBValue\fP getblockbynumber (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 250 of file rpcblockchain\&.cpp\&.
.SS "\fBValue\fP getblockcount (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 172 of file rpcblockchain\&.cpp\&.
.SS "\fBValue\fP getblockhash (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 214 of file rpcblockchain\&.cpp\&.
.SS "\fBValue\fP getcheckpoint (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 276 of file rpcblockchain\&.cpp\&.
.SS "double GetDifficulty (const \fBCBlockIndex\fP * blockindex)"

.PP
Definition at line 17 of file rpcblockchain\&.cpp\&.
.SS "\fBValue\fP getdifficulty (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 183 of file rpcblockchain\&.cpp\&.
.SS "double GetPoSKernelPS ()"

.PP
Definition at line 73 of file rpcblockchain\&.cpp\&.
.SS "double GetPoWMHashPS ()"

.PP
Definition at line 48 of file rpcblockchain\&.cpp\&.
.SS "\fBValue\fP getrawmempool (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 197 of file rpcblockchain\&.cpp\&.
.SS "void TxToJSON (const \fBCTransaction\fP & tx, const \fBuint256\fP hashBlock, \fBjson_spirit::Object\fP & entry)"

.PP
Definition at line 53 of file rpcrawtransaction\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
