.TH "/home/dev/ds-160209/src/rpcclient.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/rpcclient.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <set>\fP
.br
\fC#include 'rpcclient\&.h'\fP
.br
\fC#include 'rpcprotocol\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'ui_interface\&.h'\fP
.br
\fC#include 'chainparams\&.h'\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <boost/algorithm/string\&.hpp>\fP
.br
\fC#include <boost/asio\&.hpp>\fP
.br
\fC#include <boost/asio/ssl\&.hpp>\fP
.br
\fC#include <boost/bind\&.hpp>\fP
.br
\fC#include <boost/filesystem\&.hpp>\fP
.br
\fC#include <boost/foreach\&.hpp>\fP
.br
\fC#include <boost/iostreams/concepts\&.hpp>\fP
.br
\fC#include <boost/iostreams/stream\&.hpp>\fP
.br
\fC#include <boost/lexical_cast\&.hpp>\fP
.br
\fC#include <boost/shared_ptr\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCRPCConvertParam\fP"
.br
.ti -1c
.RI "class \fBCRPCConvertTable\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBObject\fP \fBCallRPC\fP (const string &strMethod, const \fBArray\fP &params)"
.br
.ti -1c
.RI "\fBArray\fP \fBRPCConvertValues\fP (const std::string &strMethod, const std::vector< std::string > &strParams)"
.br
.ti -1c
.RI "int \fBCommandLineRPC\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBObject\fP CallRPC (const string & strMethod, const \fBArray\fP & params)"

.PP
Definition at line 33 of file rpcclient\&.cpp\&.
.SS "int CommandLineRPC (int argc, char * argv[])"

.PP
Definition at line 232 of file rpcclient\&.cpp\&.
.SS "\fBArray\fP RPCConvertValues (const std::string & strMethod, const std::vector< std::string > & strParams)"

.PP
Definition at line 207 of file rpcclient\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
