.TH "/home/dev/ds-160209/src/rpcclient.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/rpcclient.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'json/json_spirit_reader_template\&.h'\fP
.br
\fC#include 'json/json_spirit_utils\&.h'\fP
.br
\fC#include 'json/json_spirit_writer_template\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBCommandLineRPC\fP (int argc, char *argv[])"
.br
.ti -1c
.RI "\fBjson_spirit::Array\fP \fBRPCConvertValues\fP (const std::string &strMethod, const std::vector< std::string > &strParams)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int CommandLineRPC (int argc, char * argv[])"

.PP
Definition at line 232 of file rpcclient\&.cpp\&.
.SS "\fBjson_spirit::Array\fP RPCConvertValues (const std::string & strMethod, const std::vector< std::string > & strParams)"

.PP
Definition at line 207 of file rpcclient\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
