.TH "/home/dev/ds-160209/src/rpcdump.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/rpcdump.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include 'init\&.h'\fP
.br
\fC#include 'rpcserver\&.h'\fP
.br
\fC#include 'ui_interface\&.h'\fP
.br
\fC#include 'base58\&.h'\fP
.br
\fC#include <boost/date_time/posix_time/posix_time\&.hpp>\fP
.br
\fC#include <boost/variant/get\&.hpp>\fP
.br
\fC#include <boost/algorithm/string\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCTxDump\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBEnsureWalletIsUnlocked\fP ()"
.br
.ti -1c
.RI "std::time_t \fBpt_to_time_t\fP (const bt::ptime &pt)"
.br
.ti -1c
.RI "\fBint64_t\fP \fBDecodeDumpTime\fP (const std::string &s)"
.br
.ti -1c
.RI "std::string \fBDecodeDumpString\fP (const std::string &str)"
.br
.ti -1c
.RI "\fBValue\fP \fBimportprivkey\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBimportaddress\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBimportwallet\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBdumpprivkey\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBdumpwallet\fP (const \fBArray\fP &params, bool fHelp)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::locale \fBformats\fP []"
.br
.ti -1c
.RI "const size_t \fBformats_n\fP = sizeof(\fBformats\fP)/sizeof(\fBformats\fP[0])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string DecodeDumpString (const std::string & str)"

.PP
Definition at line 74 of file rpcdump\&.cpp\&.
.SS "\fBint64_t\fP DecodeDumpTime (const std::string & s)"

.PP
Definition at line 43 of file rpcdump\&.cpp\&.
.SS "\fBValue\fP dumpprivkey (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 321 of file rpcdump\&.cpp\&.
.SS "\fBValue\fP dumpwallet (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 345 of file rpcdump\&.cpp\&.
.SS "void EnsureWalletIsUnlocked ()"

.PP
Definition at line 44 of file rpcwallet\&.cpp\&.
.SS "\fBValue\fP importaddress (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 161 of file rpcdump\&.cpp\&.
.SS "\fBValue\fP importprivkey (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 106 of file rpcdump\&.cpp\&.
.SS "\fBValue\fP importwallet (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 232 of file rpcdump\&.cpp\&.
.SS "std::time_t pt_to_time_t (const bt::ptime & pt)"

.PP
Definition at line 36 of file rpcdump\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const std::locale formats[]"
\fBInitial value:\fP
.PP
.nf
= {
    std::locale(std::locale::classic(),new bt::time_input_facet("%Y-%m-%dT%H:%M:%SZ")),
    std::locale(std::locale::classic(),new bt::time_input_facet("%Y-%m-%d %H:%M:%S")),
    std::locale(std::locale::classic(),new bt::time_input_facet("%Y/%m/%d %H:%M:%S")),
    std::locale(std::locale::classic(),new bt::time_input_facet("%d\&.%m\&.%Y %H:%M:%S")),
    std::locale(std::locale::classic(),new bt::time_input_facet("%Y-%m-%d"))
}
.fi
.PP
Definition at line 26 of file rpcdump\&.cpp\&.
.SS "const size_t formats_n = sizeof(\fBformats\fP)/sizeof(\fBformats\fP[0])"

.PP
Definition at line 34 of file rpcdump\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
