.TH "RPCExecutor" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RPCExecutor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBrequest\fP (const QString &command)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBreply\fP (int category, const QString &command)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file debugconsole\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void RPCExecutor::reply (int category, const QString & command)\fC [signal]\fP"

.SS "void RPCExecutor::request (const QString & command)\fC [slot]\fP"

.PP
Definition at line 154 of file debugconsole\&.cpp\&.
.SS "void RPCExecutor::start ()\fC [slot]\fP"

.PP
Definition at line 58 of file debugconsole\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
