.TH "/home/dev/ds-160209/src/rpcmining.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/rpcmining.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'rpcserver\&.h'\fP
.br
\fC#include 'base58\&.h'\fP
.br
\fC#include 'chainparams\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'db\&.h'\fP
.br
\fC#include 'txdb\&.h'\fP
.br
\fC#include 'init\&.h'\fP
.br
\fC#include 'miner\&.h'\fP
.br
\fC#include 'kernel\&.h'\fP
.br
\fC#include 'txdb-leveldb\&.h'\fP
.br
\fC#include 'stormnode-sync\&.h'\fP
.br
\fC#include <boost/assign/list_of\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBInitRPCMining\fP ()"
.br
.ti -1c
.RI "void \fBShutdownRPCMining\fP ()"
.br
.ti -1c
.RI "\fBValue\fP \fBgetsubsidy\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBgetstakesubsidy\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBgetmininginfo\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBgetstakinginfo\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBcheckkernel\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBgetworkex\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBgetwork\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBgetblocktemplate\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBsubmitblock\fP (const \fBArray\fP &params, bool fHelp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBValue\fP checkkernel (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 150 of file rpcmining\&.cpp\&.
.SS "\fBValue\fP getblocktemplate (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 476 of file rpcmining\&.cpp\&.
.SS "\fBValue\fP getmininginfo (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 78 of file rpcmining\&.cpp\&.
.SS "\fBValue\fP getstakesubsidy (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 56 of file rpcmining\&.cpp\&.
.SS "\fBValue\fP getstakinginfo (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 114 of file rpcmining\&.cpp\&.
.SS "\fBValue\fP getsubsidy (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 46 of file rpcmining\&.cpp\&.
.SS "\fBValue\fP getwork (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 363 of file rpcmining\&.cpp\&.
.SS "\fBValue\fP getworkex (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 236 of file rpcmining\&.cpp\&.
.SS "void InitRPCMining ()"

.PP
Definition at line 29 of file rpcmining\&.cpp\&.
.SS "void ShutdownRPCMining ()"

.PP
Definition at line 38 of file rpcmining\&.cpp\&.
.SS "\fBValue\fP submitblock (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 655 of file rpcmining\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
