.TH "/home/dev/ds-160209/src/rpcprotocol.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/rpcprotocol.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'rpcprotocol\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <boost/algorithm/string\&.hpp>\fP
.br
\fC#include <boost/asio\&.hpp>\fP
.br
\fC#include <boost/asio/ssl\&.hpp>\fP
.br
\fC#include <boost/bind\&.hpp>\fP
.br
\fC#include <boost/filesystem\&.hpp>\fP
.br
\fC#include <boost/foreach\&.hpp>\fP
.br
\fC#include <boost/iostreams/concepts\&.hpp>\fP
.br
\fC#include <boost/iostreams/stream\&.hpp>\fP
.br
\fC#include <boost/lexical_cast\&.hpp>\fP
.br
\fC#include <boost/shared_ptr\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "string \fBHTTPPost\fP (const string &strMsg, const map< string, string > &mapRequestHeaders)"
.br
.ti -1c
.RI "string \fBHTTPReply\fP (int nStatus, const string &strMsg, bool keepalive)"
.br
.ti -1c
.RI "bool \fBReadHTTPRequestLine\fP (std::basic_istream< char > &stream, int &proto, string &http_method, string &http_uri)"
.br
.ti -1c
.RI "int \fBReadHTTPStatus\fP (std::basic_istream< char > &stream, int &proto)"
.br
.ti -1c
.RI "int \fBReadHTTPHeaders\fP (std::basic_istream< char > &stream, map< string, string > &mapHeadersRet)"
.br
.ti -1c
.RI "int \fBReadHTTPMessage\fP (std::basic_istream< char > &stream, map< string, string > &mapHeadersRet, string &strMessageRet, int nProto, size_t max_size)"
.br
.ti -1c
.RI "string \fBJSONRPCRequest\fP (const string &strMethod, const \fBArray\fP &params, const \fBValue\fP &\fBid\fP)"
.br
.ti -1c
.RI "\fBObject\fP \fBJSONRPCReplyObj\fP (const \fBValue\fP &result, const \fBValue\fP &error, const \fBValue\fP &\fBid\fP)"
.br
.ti -1c
.RI "string \fBJSONRPCReply\fP (const \fBValue\fP &result, const \fBValue\fP &error, const \fBValue\fP &\fBid\fP)"
.br
.ti -1c
.RI "\fBObject\fP \fBJSONRPCError\fP (int code, const string &message)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const size_t \fBPOST_READ_SIZE\fP = 256 * 1024"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "string HTTPPost (const string & strMsg, const map< string, string > & mapRequestHeaders)"

.PP
Definition at line 39 of file rpcprotocol\&.cpp\&.
.SS "string HTTPReply (int nStatus, const string & strMsg, bool keepalive)"

.PP
Definition at line 61 of file rpcprotocol\&.cpp\&.
.SS "\fBObject\fP JSONRPCError (int code, const string & message)"

.PP
Definition at line 260 of file rpcprotocol\&.cpp\&.
.SS "string JSONRPCReply (const \fBValue\fP & result, const \fBValue\fP & error, const \fBValue\fP & id)"

.PP
Definition at line 254 of file rpcprotocol\&.cpp\&.
.SS "\fBObject\fP JSONRPCReplyObj (const \fBValue\fP & result, const \fBValue\fP & error, const \fBValue\fP & id)"

.PP
Definition at line 242 of file rpcprotocol\&.cpp\&.
.SS "string JSONRPCRequest (const string & strMethod, const \fBArray\fP & params, const \fBValue\fP & id)"

.PP
Definition at line 233 of file rpcprotocol\&.cpp\&.
.SS "int ReadHTTPHeaders (std::basic_istream< char > & stream, map< string, string > & mapHeadersRet)"

.PP
Definition at line 155 of file rpcprotocol\&.cpp\&.
.SS "int ReadHTTPMessage (std::basic_istream< char > & stream, map< string, string > & mapHeadersRet, string & strMessageRet, int nProto, size_t max_size)"

.PP
Definition at line 181 of file rpcprotocol\&.cpp\&.
.SS "bool ReadHTTPRequestLine (std::basic_istream< char > & stream, int & proto, string & http_method, string & http_uri)"

.PP
Definition at line 105 of file rpcprotocol\&.cpp\&.
.SS "int ReadHTTPStatus (std::basic_istream< char > & stream, int & proto)"

.PP
Definition at line 140 of file rpcprotocol\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const size_t POST_READ_SIZE = 256 * 1024"

.PP
Definition at line 30 of file rpcprotocol\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
