.TH "/home/dev/ds-160209/src/rpcsmessage.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/rpcsmessage.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br
\fC#include 'rpcserver\&.h'\fP
.br
\fC#include <boost/lexical_cast\&.hpp>\fP
.br
\fC#include 'smessage\&.h'\fP
.br
\fC#include 'init\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTxToJSON\fP (const \fBCTransaction\fP &tx, const \fBuint256\fP hashBlock, \fBjson_spirit::Object\fP &entry)"
.br
.ti -1c
.RI "\fBValue\fP \fBsmsgenable\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBsmsgdisable\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBsmsgoptions\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBsmsglocalkeys\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBsmsgscanchain\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBsmsgscanbuckets\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBsmsgaddkey\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBsmsggetpubkey\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBsmsgsend\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBsmsgsendanon\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBsmsginbox\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBsmsgoutbox\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBsmsgbuckets\fP (const \fBArray\fP &params, bool fHelp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBValue\fP smsgaddkey (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 393 of file rpcsmessage\&.cpp\&.
.SS "\fBValue\fP smsgbuckets (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 773 of file rpcsmessage\&.cpp\&.
.SS "\fBValue\fP smsgdisable (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 42 of file rpcsmessage\&.cpp\&.
.SS "\fBValue\fP smsgenable (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 21 of file rpcsmessage\&.cpp\&.
.SS "\fBValue\fP smsggetpubkey (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 427 of file rpcsmessage\&.cpp\&.
.SS "\fBValue\fP smsginbox (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 566 of file rpcsmessage\&.cpp\&.
.SS "\fBValue\fP smsglocalkeys (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 140 of file rpcsmessage\&.cpp\&.
.SS "\fBValue\fP smsgoptions (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 62 of file rpcsmessage\&.cpp\&.
.SS "\fBValue\fP smsgoutbox (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 679 of file rpcsmessage\&.cpp\&.
.SS "\fBValue\fP smsgscanbuckets (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 369 of file rpcsmessage\&.cpp\&.
.SS "\fBValue\fP smsgscanchain (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 348 of file rpcsmessage\&.cpp\&.
.SS "\fBValue\fP smsgsend (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 511 of file rpcsmessage\&.cpp\&.
.SS "\fBValue\fP smsgsendanon (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 539 of file rpcsmessage\&.cpp\&.
.SS "void TxToJSON (const \fBCTransaction\fP & tx, const \fBuint256\fP hashBlock, \fBjson_spirit::Object\fP & entry)"

.PP
Definition at line 53 of file rpcrawtransaction\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
