.TH "/home/dev/ds-160209/src/rpcstormnode-budget.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/rpcstormnode-budget.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br
\fC#include 'db\&.h'\fP
.br
\fC#include 'init\&.h'\fP
.br
\fC#include 'activestormnode\&.h'\fP
.br
\fC#include 'stormnode-budget\&.h'\fP
.br
\fC#include 'stormnode-payments\&.h'\fP
.br
\fC#include 'stormnode-sync\&.h'\fP
.br
\fC#include 'stormnodeconfig\&.h'\fP
.br
\fC#include 'stormnodeman\&.h'\fP
.br
\fC#include 'rpcserver\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'sandstorm\&.h'\fP
.br
\fC#include <fstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBValue\fP \fBsnbudget\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBsnbudgetvoteraw\fP (const \fBArray\fP &params, bool fHelp)"
.br
.ti -1c
.RI "\fBValue\fP \fBsnfinalbudget\fP (const \fBArray\fP &params, bool fHelp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBValue\fP snbudget (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 22 of file rpcstormnode-budget\&.cpp\&.
.SS "\fBValue\fP snbudgetvoteraw (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 517 of file rpcstormnode-budget\&.cpp\&.
.SS "\fBValue\fP snfinalbudget (const \fBArray\fP & params, bool fHelp)"

.PP
Definition at line 569 of file rpcstormnode-budget\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
