.TH "/home/dev/ds-160209/src/crypto/argon2/run.c" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/crypto/argon2/run.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <inttypes\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include 'argon2\&.h'\fP
.br
\fC#include 'core\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBT_COST_DEF\fP   3"
.br
.ti -1c
.RI "#define \fBLOG_M_COST_DEF\fP   12 /* 2^12 = 4 MiB */"
.br
.ti -1c
.RI "#define \fBLANES_DEF\fP   1"
.br
.ti -1c
.RI "#define \fBTHREADS_DEF\fP   1"
.br
.ti -1c
.RI "#define \fBOUT_LEN\fP   32"
.br
.ti -1c
.RI "#define \fBSALT_LEN\fP   16"
.br
.ti -1c
.RI "#define \fBENCODED_LEN\fP   108"
.br
.ti -1c
.RI "#define \fBUNUSED_PARAMETER\fP(x)   (void)(x)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ENCODED_LEN   108"

.PP
Definition at line 45 of file run\&.c\&.
.SS "#define LANES_DEF   1"

.PP
Definition at line 26 of file run\&.c\&.
.SS "#define LOG_M_COST_DEF   12 /* 2^12 = 4 MiB */"

.PP
Definition at line 25 of file run\&.c\&.
.SS "#define OUT_LEN   32"

.PP
Definition at line 28 of file run\&.c\&.
.SS "#define SALT_LEN   16"

.PP
Definition at line 29 of file run\&.c\&.
.SS "#define T_COST_DEF   3"

.PP
Definition at line 24 of file run\&.c\&.
.SS "#define THREADS_DEF   1"

.PP
Definition at line 27 of file run\&.c\&.
.SS "#define UNUSED_PARAMETER(x)   (void)(x)"

.PP
Definition at line 47 of file run\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 129 of file run\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
