.TH "SAM" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SAM \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFullDestination\fP"
.br
.ti -1c
.RI "class \fBMessage\fP"
.br
.ti -1c
.RI "struct \fBRequestResult\fP"
.br
.ti -1c
.RI "struct \fBRequestResult< std::auto_ptr< T > >\fP"
.br
.ti -1c
.RI "struct \fBRequestResult< void >\fP"
.br
.ti -1c
.RI "class \fBSocket\fP"
.br
.ti -1c
.RI "class \fBStreamSession\fP"
.br
.ti -1c
.RI "class \fBStreamSessionAdapter\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBSOCKET\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef int \fBSAM::SOCKET\fP"

.PP
Definition at line 72 of file i2psam\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
