.TH "SAM::StreamSession" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SAM::StreamSession \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <i2psam\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStreamSession\fP (const std::string &nickname, const std::string &SAMHost=\fBSAM_DEFAULT_ADDRESS\fP, \fBuint16_t\fP SAMPort=\fBSAM_DEFAULT_PORT\fP, const std::string &destination=\fBSAM_GENERATE_MY_DESTINATION\fP, const std::string &i2pOptions=\fBSAM_DEFAULT_I2P_OPTIONS\fP, const std::string &minVer=\fBSAM_DEFAULT_MIN_VER\fP, const std::string &maxVer=\fBSAM_DEFAULT_MAX_VER\fP)"
.br
.ti -1c
.RI "\fBStreamSession\fP (\fBStreamSession\fP &rhs)"
.br
.ti -1c
.RI "\fB~StreamSession\fP ()"
.br
.ti -1c
.RI "\fBRequestResult\fP< std::auto_ptr< \fBSocket\fP > > \fBaccept\fP (bool silent)"
.br
.ti -1c
.RI "\fBRequestResult\fP< std::auto_ptr< \fBSocket\fP > > \fBconnect\fP (const std::string &destination, bool silent)"
.br
.ti -1c
.RI "\fBRequestResult\fP< void > \fBforward\fP (const std::string &host, \fBuint16_t\fP port, bool silent)"
.br
.ti -1c
.RI "\fBRequestResult\fP< const std::string > \fBnamingLookup\fP (const std::string &\fBname\fP) const "
.br
.ti -1c
.RI "\fBRequestResult\fP< const \fBFullDestination\fP > \fBdestGenerate\fP () const "
.br
.ti -1c
.RI "void \fBstopForwarding\fP (const std::string &host, \fBuint16_t\fP port)"
.br
.ti -1c
.RI "void \fBstopForwardingAll\fP ()"
.br
.ti -1c
.RI "const \fBFullDestination\fP & \fBgetMyDestination\fP () const "
.br
.ti -1c
.RI "const sockaddr_in & \fBgetSAMAddress\fP () const "
.br
.ti -1c
.RI "const std::string & \fBgetSAMHost\fP () const "
.br
.ti -1c
.RI "\fBuint16_t\fP \fBgetSAMPort\fP () const "
.br
.ti -1c
.RI "const std::string & \fBgetNickname\fP () const "
.br
.ti -1c
.RI "const std::string & \fBgetSessionID\fP () const "
.br
.ti -1c
.RI "const std::string & \fBgetSAMMinVer\fP () const "
.br
.ti -1c
.RI "const std::string & \fBgetSAMMaxVer\fP () const "
.br
.ti -1c
.RI "const std::string & \fBgetSAMVersion\fP () const "
.br
.ti -1c
.RI "const std::string & \fBgetOptions\fP () const "
.br
.ti -1c
.RI "bool \fBisSick\fP () const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBgenerateSessionID\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 343 of file i2psam\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SAM::StreamSession::StreamSession (const std::string & nickname, const std::string & SAMHost = \fC\fBSAM_DEFAULT_ADDRESS\fP\fP, \fBuint16_t\fP SAMPort = \fC\fBSAM_DEFAULT_PORT\fP\fP, const std::string & destination = \fC\fBSAM_GENERATE_MY_DESTINATION\fP\fP, const std::string & i2pOptions = \fC\fBSAM_DEFAULT_I2P_OPTIONS\fP\fP, const std::string & minVer = \fC\fBSAM_DEFAULT_MIN_VER\fP\fP, const std::string & maxVer = \fC\fBSAM_DEFAULT_MAX_VER\fP\fP)"

.PP
Definition at line 249 of file i2psam\&.cpp\&.
.SS "SAM::StreamSession::StreamSession (\fBStreamSession\fP & rhs)\fC [explicit]\fP"

.PP
Definition at line 267 of file i2psam\&.cpp\&.
.SS "SAM::StreamSession::~StreamSession ()"

.PP
Definition at line 285 of file i2psam\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBRequestResult\fP< std::auto_ptr< \fBSocket\fP > > SAM::StreamSession::accept (bool silent)"

.PP
Definition at line 311 of file i2psam\&.cpp\&.
.SS "\fBRequestResult\fP< std::auto_ptr< \fBSocket\fP > > SAM::StreamSession::connect (const std::string & destination, bool silent)"

.PP
Definition at line 333 of file i2psam\&.cpp\&.
.SS "\fBRequestResult\fP< const \fBFullDestination\fP > SAM::StreamSession::destGenerate () const"

.PP
Definition at line 400 of file i2psam\&.cpp\&.
.SS "\fBRequestResult\fP< void > SAM::StreamSession::forward (const std::string & host, \fBuint16_t\fP port, bool silent)"

.PP
Definition at line 355 of file i2psam\&.cpp\&.
.SS "std::string SAM::StreamSession::generateSessionID ()\fC [static]\fP"

.PP
Definition at line 292 of file i2psam\&.cpp\&.
.SS "const \fBFullDestination\fP & SAM::StreamSession::getMyDestination () const"

.PP
Definition at line 550 of file i2psam\&.cpp\&.
.SS "const std::string & SAM::StreamSession::getNickname () const"

.PP
Definition at line 535 of file i2psam\&.cpp\&.
.SS "const std::string & SAM::StreamSession::getOptions () const"

.PP
Definition at line 545 of file i2psam\&.cpp\&.
.SS "const sockaddr_in & SAM::StreamSession::getSAMAddress () const"

.PP
Definition at line 560 of file i2psam\&.cpp\&.
.SS "const std::string & SAM::StreamSession::getSAMHost () const"

.PP
Definition at line 565 of file i2psam\&.cpp\&.
.SS "const std::string & SAM::StreamSession::getSAMMaxVer () const"

.PP
Definition at line 580 of file i2psam\&.cpp\&.
.SS "const std::string & SAM::StreamSession::getSAMMinVer () const"

.PP
Definition at line 575 of file i2psam\&.cpp\&.
.SS "\fBuint16_t\fP SAM::StreamSession::getSAMPort () const"

.PP
Definition at line 570 of file i2psam\&.cpp\&.
.SS "const std::string & SAM::StreamSession::getSAMVersion () const"

.PP
Definition at line 585 of file i2psam\&.cpp\&.
.SS "const std::string & SAM::StreamSession::getSessionID () const"

.PP
Definition at line 540 of file i2psam\&.cpp\&.
.SS "bool SAM::StreamSession::isSick () const"

.PP
Definition at line 555 of file i2psam\&.cpp\&.
.SS "\fBRequestResult\fP< const std::string > SAM::StreamSession::namingLookup (const std::string & name) const"

.PP
Definition at line 379 of file i2psam\&.cpp\&.
.SS "void SAM::StreamSession::stopForwarding (const std::string & host, \fBuint16_t\fP port)"

.PP
Definition at line 439 of file i2psam\&.cpp\&.
.SS "void SAM::StreamSession::stopForwardingAll ()"

.PP
Definition at line 453 of file i2psam\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
