.TH "SAM::FullDestination" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SAM::FullDestination \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <i2psam\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFullDestination\fP ()"
.br
.ti -1c
.RI "\fBFullDestination\fP (const std::string &\fBpub\fP, const std::string &\fBpriv\fP, bool \fBisGenerated\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBpub\fP"
.br
.ti -1c
.RI "std::string \fBpriv\fP"
.br
.ti -1c
.RI "bool \fBisGenerated\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 264 of file i2psam\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SAM::FullDestination::FullDestination ()\fC [inline]\fP"

.PP
Definition at line 270 of file i2psam\&.h\&.
.SS "SAM::FullDestination::FullDestination (const std::string & pub, const std::string & priv, bool isGenerated)\fC [inline]\fP"

.PP
Definition at line 271 of file i2psam\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool SAM::FullDestination::isGenerated"

.PP
Definition at line 268 of file i2psam\&.h\&.
.SS "std::string SAM::FullDestination::priv"

.PP
Definition at line 267 of file i2psam\&.h\&.
.SS "std::string SAM::FullDestination::pub"

.PP
Definition at line 266 of file i2psam\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
