.TH "SAM::StreamSessionAdapter::SessionHolder" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SAM::StreamSessionAdapter::SessionHolder \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSessionHolder\fP (std::auto_ptr< \fBSAM::StreamSession\fP > session)"
.br
.ti -1c
.RI "const \fBSAM::StreamSession\fP & \fBgetSession\fP () const "
.br
.ti -1c
.RI "\fBSAM::StreamSession\fP & \fBgetSession\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file i2p\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SAM::StreamSessionAdapter::SessionHolder::SessionHolder (std::auto_ptr< \fBSAM::StreamSession\fP > session)\fC [explicit]\fP"

.PP
Definition at line 29 of file i2p\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "const \fBSAM::StreamSession\fP & SAM::StreamSessionAdapter::SessionHolder::getSession () const"

.PP
Definition at line 33 of file i2p\&.cpp\&.
.SS "\fBSAM::StreamSession\fP & SAM::StreamSessionAdapter::SessionHolder::getSession ()"

.PP
Definition at line 44 of file i2p\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
