.TH "SAM::Socket" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SAM::Socket \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <i2psam\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSocket\fP (const std::string &SAMHost, \fBuint16_t\fP SAMPort, const std::string &minVer, const std::string &maxVer)"
.br
.ti -1c
.RI "\fBSocket\fP (const sockaddr_in &addr, const std::string &minVer, const std::string &maxVer)"
.br
.ti -1c
.RI "\fBSocket\fP (const \fBSocket\fP &rhs)"
.br
.ti -1c
.RI "\fB~Socket\fP ()"
.br
.ti -1c
.RI "void \fBwrite\fP (const std::string &msg)"
.br
.ti -1c
.RI "std::string \fBread\fP ()"
.br
.ti -1c
.RI "\fBSOCKET\fP \fBrelease\fP ()"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.ti -1c
.RI "bool \fBisOk\fP () const "
.br
.ti -1c
.RI "const std::string & \fBgetVersion\fP () const "
.br
.ti -1c
.RI "const std::string & \fBgetHost\fP () const "
.br
.ti -1c
.RI "\fBuint16_t\fP \fBgetPort\fP () const "
.br
.ti -1c
.RI "const std::string & \fBgetMinVer\fP () const "
.br
.ti -1c
.RI "const std::string & \fBgetMaxVer\fP () const "
.br
.ti -1c
.RI "const sockaddr_in & \fBgetAddress\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 216 of file i2psam\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SAM::Socket::Socket (const std::string & SAMHost, \fBuint16_t\fP SAMPort, const std::string & minVer, const std::string & maxVer)"

.PP
Definition at line 66 of file i2psam\&.cpp\&.
.SS "SAM::Socket::Socket (const sockaddr_in & addr, const std::string & minVer, const std::string & maxVer)"

.PP
Definition at line 85 of file i2psam\&.cpp\&.
.SS "SAM::Socket::Socket (const \fBSocket\fP & rhs)\fC [explicit]\fP"

.PP
Definition at line 98 of file i2psam\&.cpp\&.
.SS "SAM::Socket::~Socket ()"

.PP
Definition at line 111 of file i2psam\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void SAM::Socket::close ()"

.PP
Definition at line 204 of file i2psam\&.cpp\&.
.SS "const sockaddr_in & SAM::Socket::getAddress () const"

.PP
Definition at line 241 of file i2psam\&.cpp\&.
.SS "const std::string & SAM::Socket::getHost () const"

.PP
Definition at line 216 of file i2psam\&.cpp\&.
.SS "const std::string & SAM::Socket::getMaxVer () const"

.PP
Definition at line 236 of file i2psam\&.cpp\&.
.SS "const std::string & SAM::Socket::getMinVer () const"

.PP
Definition at line 231 of file i2psam\&.cpp\&.
.SS "\fBuint16_t\fP SAM::Socket::getPort () const"

.PP
Definition at line 221 of file i2psam\&.cpp\&.
.SS "const std::string & SAM::Socket::getVersion () const"

.PP
Definition at line 226 of file i2psam\&.cpp\&.
.SS "bool SAM::Socket::isOk () const"

.PP
Definition at line 211 of file i2psam\&.cpp\&.
.SS "std::string SAM::Socket::read ()"

.PP
Definition at line 179 of file i2psam\&.cpp\&.
.SS "\fBSOCKET\fP SAM::Socket::release ()"

.PP
Definition at line 138 of file i2psam\&.cpp\&.
.SS "void SAM::Socket::write (const std::string & msg)"

.PP
Definition at line 156 of file i2psam\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
