.TH "SAM::Message" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SAM::Message \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <i2psam\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAnswer\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBSessionStyle\fP { \fBsssStream\fP, \fBsssDatagram\fP, \fBsssRaw\fP }"
.br
.ti -1c
.RI "enum \fBeStatus\fP { \fBOK\fP, \fBEMPTY_ANSWER\fP, \fBCLOSED_SOCKET\fP, \fBCANNOT_PARSE_ERROR\fP, \fBDUPLICATED_DEST\fP, \fBDUPLICATED_ID\fP, \fBI2P_ERROR\fP, \fBINVALID_ID\fP, \fBINVALID_KEY\fP, \fBCANT_REACH_PEER\fP, \fBTIMEOUT\fP, \fBNOVERSION\fP, \fBKEY_NOT_FOUND\fP, \fBPEER_NOT_FOUND\fP, \fBALREADY_ACCEPTING\fP, \fBFAILED\fP, \fBCLOSED\fP }"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBhello\fP (const std::string &minVer, const std::string &maxVer)"
.br
.ti -1c
.RI "static std::string \fBsessionCreate\fP (\fBSessionStyle\fP style, const std::string &sessionID, const std::string &nickname, const std::string &destination=\fBSAM_GENERATE_MY_DESTINATION\fP, const std::string &options='')"
.br
.ti -1c
.RI "static std::string \fBstreamAccept\fP (const std::string &sessionID, bool silent=false)"
.br
.ti -1c
.RI "static std::string \fBstreamConnect\fP (const std::string &sessionID, const std::string &destination, bool silent=false)"
.br
.ti -1c
.RI "static std::string \fBstreamForward\fP (const std::string &sessionID, const std::string &host, \fBuint16_t\fP port, bool silent=false)"
.br
.ti -1c
.RI "static std::string \fBnamingLookup\fP (const std::string &\fBname\fP)"
.br
.ti -1c
.RI "static std::string \fBdestGenerate\fP ()"
.br
.ti -1c
.RI "static \fBeStatus\fP \fBcheckAnswer\fP (const std::string &answer)"
.br
.ti -1c
.RI "static std::string \fBgetValue\fP (const std::string &answer, const std::string &key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 74 of file i2psam\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBSAM::Message::eStatus\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOK \fP\fP
.TP
\fB\fIEMPTY_ANSWER \fP\fP
.TP
\fB\fICLOSED_SOCKET \fP\fP
.TP
\fB\fICANNOT_PARSE_ERROR \fP\fP
.TP
\fB\fIDUPLICATED_DEST \fP\fP
.TP
\fB\fIDUPLICATED_ID \fP\fP
.TP
\fB\fII2P_ERROR \fP\fP
.TP
\fB\fIINVALID_ID \fP\fP
.TP
\fB\fIINVALID_KEY \fP\fP
.TP
\fB\fICANT_REACH_PEER \fP\fP
.TP
\fB\fITIMEOUT \fP\fP
.TP
\fB\fINOVERSION \fP\fP
.TP
\fB\fIKEY_NOT_FOUND \fP\fP
.TP
\fB\fIPEER_NOT_FOUND \fP\fP
.TP
\fB\fIALREADY_ACCEPTING \fP\fP
.TP
\fB\fIFAILED \fP\fP
.TP
\fB\fICLOSED \fP\fP
.PP
Definition at line 84 of file i2psam\&.h\&.
.SS "enum \fBSAM::Message::SessionStyle\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIsssStream \fP\fP
.TP
\fB\fIsssDatagram \fP\fP
.TP
\fB\fIsssRaw \fP\fP
.PP
Definition at line 77 of file i2psam\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMessage::eStatus\fP SAM::Message::checkAnswer (const std::string & answer)\fC [static]\fP"

.PP
Definition at line 753 of file i2psam\&.cpp\&.
.SS "std::string SAM::Message::destGenerate ()\fC [static]\fP"

.PP
Definition at line 731 of file i2psam\&.cpp\&.
.SS "std::string SAM::Message::getValue (const std::string & answer, const std::string & key)\fC [static]\fP"

.PP
Definition at line 780 of file i2psam\&.cpp\&.
.SS "std::string SAM::Message::hello (const std::string & minVer, const std::string & maxVer)\fC [static]\fP"

.PP
Definition at line 611 of file i2psam\&.cpp\&.
.SS "std::string SAM::Message::namingLookup (const std::string & name)\fC [static]\fP"

.PP
Definition at line 713 of file i2psam\&.cpp\&.
.SS "std::string SAM::Message::sessionCreate (\fBSessionStyle\fP style, const std::string & sessionID, const std::string & nickname, const std::string & destination = \fC\fBSAM_GENERATE_MY_DESTINATION\fP\fP, const std::string & options = \fC''\fP)\fC [static]\fP"

.PP
Definition at line 629 of file i2psam\&.cpp\&.
.SS "std::string SAM::Message::streamAccept (const std::string & sessionID, bool silent = \fCfalse\fP)\fC [static]\fP"

.PP
Definition at line 657 of file i2psam\&.cpp\&.
.SS "std::string SAM::Message::streamConnect (const std::string & sessionID, const std::string & destination, bool silent = \fCfalse\fP)\fC [static]\fP"

.PP
Definition at line 675 of file i2psam\&.cpp\&.
.SS "std::string SAM::Message::streamForward (const std::string & sessionID, const std::string & host, \fBuint16_t\fP port, bool silent = \fCfalse\fP)\fC [static]\fP"

.PP
Definition at line 694 of file i2psam\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
