.TH "SAM::RequestResult< std::auto_ptr< T > >::RequestResultRef" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SAM::RequestResult< std::auto_ptr< T > >::RequestResultRef \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <i2psam\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRequestResultRef\fP (bool \fBisOk\fP, T *\fBvalue\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisOk\fP"
.br
.ti -1c
.RI "T * \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>struct SAM::RequestResult< std::auto_ptr< T > >::RequestResultRef"

.PP
Definition at line 292 of file i2psam\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBSAM::RequestResult\fP< std::auto_ptr< T > >::RequestResultRef::RequestResultRef (bool isOk, T * value)\fC [inline]\fP"

.PP
Definition at line 297 of file i2psam\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class T > bool \fBSAM::RequestResult\fP< std::auto_ptr< T > >::RequestResultRef::isOk"

.PP
Definition at line 294 of file i2psam\&.h\&.
.SS "template<class T > T* \fBSAM::RequestResult\fP< std::auto_ptr< T > >::RequestResultRef::value"

.PP
Definition at line 295 of file i2psam\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
