.TH "SAM::RequestResult< std::auto_ptr< T > >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SAM::RequestResult< std::auto_ptr< T > > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <i2psam\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBRequestResultRef\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRequestResult\fP ()"
.br
.ti -1c
.RI "\fBRequestResult\fP (std::auto_ptr< T > &\fBvalue\fP)"
.br
.ti -1c
.RI "\fBRequestResult\fP (RequestResultRef ref)"
.br
.ti -1c
.RI "\fBRequestResult\fP & \fBoperator=\fP (RequestResultRef ref)"
.br
.ti -1c
.RI "\fBoperator RequestResultRef\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisOk\fP"
.br
.ti -1c
.RI "std::auto_ptr< T > \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>struct SAM::RequestResult< std::auto_ptr< T > >"

.PP
Definition at line 289 of file i2psam\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBSAM::RequestResult\fP< std::auto_ptr< T > >::\fBRequestResult\fP ()\fC [inline]\fP"

.PP
Definition at line 304 of file i2psam\&.h\&.
.SS "template<class T > \fBSAM::RequestResult\fP< std::auto_ptr< T > >::\fBRequestResult\fP (std::auto_ptr< T > & value)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 307 of file i2psam\&.h\&.
.SS "template<class T > \fBSAM::RequestResult\fP< std::auto_ptr< T > >::\fBRequestResult\fP (RequestResultRef ref)\fC [inline]\fP"

.PP
Definition at line 312 of file i2psam\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<class T > \fBSAM::RequestResult\fP< std::auto_ptr< T > >::operator RequestResultRef ()\fC [inline]\fP"

.PP
Definition at line 325 of file i2psam\&.h\&.
.SS "template<class T > \fBRequestResult\fP& \fBSAM::RequestResult\fP< std::auto_ptr< T > >::operator= (RequestResultRef ref)\fC [inline]\fP"

.PP
Definition at line 315 of file i2psam\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class T > bool \fBSAM::RequestResult\fP< std::auto_ptr< T > >::isOk"

.PP
Definition at line 301 of file i2psam\&.h\&.
.SS "template<class T > std::auto_ptr<T> \fBSAM::RequestResult\fP< std::auto_ptr< T > >::value"

.PP
Definition at line 302 of file i2psam\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
