.TH "SAM::RequestResult< void >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SAM::RequestResult< void > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <i2psam\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRequestResult\fP ()"
.br
.ti -1c
.RI "\fBRequestResult\fP (bool \fBisOk\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisOk\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>struct SAM::RequestResult< void >"

.PP
Definition at line 332 of file i2psam\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSAM::RequestResult\fP< void >::\fBRequestResult\fP ()\fC [inline]\fP"

.PP
Definition at line 336 of file i2psam\&.h\&.
.SS "\fBSAM::RequestResult\fP< void >::\fBRequestResult\fP (bool isOk)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 339 of file i2psam\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool \fBSAM::RequestResult\fP< void >::isOk"

.PP
Definition at line 334 of file i2psam\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
