.TH "SAM::RequestResult< T >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SAM::RequestResult< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <i2psam\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRequestResult\fP ()"
.br
.ti -1c
.RI "\fBRequestResult\fP (const T &\fBvalue\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisOk\fP"
.br
.ti -1c
.RI "T \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>struct SAM::RequestResult< T >"

.PP
Definition at line 276 of file i2psam\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T> \fBSAM::RequestResult\fP< T >::\fBRequestResult\fP ()\fC [inline]\fP"

.PP
Definition at line 281 of file i2psam\&.h\&.
.SS "template<class T> \fBSAM::RequestResult\fP< T >::\fBRequestResult\fP (const T & value)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 284 of file i2psam\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class T> bool \fBSAM::RequestResult\fP< T >::isOk"

.PP
Definition at line 278 of file i2psam\&.h\&.
.SS "template<class T> T \fBSAM::RequestResult\fP< T >::value"

.PP
Definition at line 279 of file i2psam\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
