.TH "/home/dev/ds-160209/src/sandstorm.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/sandstorm.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sandstorm\&.h'\fP
.br
\fC#include 'init\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'stormnode-payments\&.h'\fP
.br
\fC#include 'stormnode-sync\&.h'\fP
.br
\fC#include 'script\&.h'\fP
.br
\fC#include 'instantx\&.h'\fP
.br
\fC#include 'ui_interface\&.h'\fP
.br
\fC#include <boost/algorithm/string/replace\&.hpp>\fP
.br
\fC#include <boost/filesystem\&.hpp>\fP
.br
\fC#include <boost/filesystem/fstream\&.hpp>\fP
.br
\fC#include <boost/lexical_cast\&.hpp>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <boost/assign/list_of\&.hpp>\fP
.br
\fC#include <openssl/rand\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBThreadCheckSandStormPool\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCSandstormPool\fP \fBsandStormPool\fP"
.br
.ti -1c
.RI "\fBCSandStormSigner\fP \fBsandStormSigner\fP"
.br
.ti -1c
.RI "std::vector< \fBCSandstormQueue\fP > \fBvecSandstormQueue\fP"
.br
.ti -1c
.RI "std::vector< \fBCTxIn\fP > \fBvecStormnodesUsed\fP"
.br
.ti -1c
.RI "map< \fBuint256\fP, \fBCSandstormBroadcastTx\fP > \fBmapSandstormBroadcastTxes\fP"
.br
.ti -1c
.RI "\fBCActiveStormnode\fP \fBactiveStormnode\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ThreadCheckSandStormPool ()"

.PP
Definition at line 2196 of file sandstorm\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBCActiveStormnode\fP activeStormnode"

.PP
Definition at line 36 of file sandstorm\&.cpp\&.
.SS "map<\fBuint256\fP, \fBCSandstormBroadcastTx\fP> mapSandstormBroadcastTxes"

.PP
Definition at line 34 of file sandstorm\&.cpp\&.
.SS "\fBCSandstormPool\fP sandStormPool"

.PP
Definition at line 26 of file sandstorm\&.cpp\&.
.SS "\fBCSandStormSigner\fP sandStormSigner"

.PP
Definition at line 28 of file sandstorm\&.cpp\&.
.SS "std::vector<\fBCSandstormQueue\fP> vecSandstormQueue"

.PP
Definition at line 30 of file sandstorm\&.cpp\&.
.SS "std::vector<\fBCTxIn\fP> vecStormnodesUsed"

.PP
Definition at line 32 of file sandstorm\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
