.TH "SandstormConfig" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SandstormConfig \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sandstormconfig\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSandstormConfig\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~SandstormConfig\fP ()"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBWalletModel\fP *model)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Multifunctional dialog to ask for passphrases\&. Used for encryption, unlocking, and changing the passphrase\&. 
.PP
Definition at line 13 of file sandstormconfig\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SandstormConfig::SandstormConfig (QWidget * parent = \fC0\fP)"

.PP
Definition at line 15 of file sandstormconfig\&.cpp\&.
.SS "SandstormConfig::~SandstormConfig ()"

.PP
Definition at line 27 of file sandstormconfig\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void SandstormConfig::setModel (\fBWalletModel\fP * model)"

.PP
Definition at line 32 of file sandstormconfig\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
