.TH "/home/dev/ds-160209/src/secp256k1/src/scalar_4x64.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/secp256k1/src/scalar_4x64.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsecp256k1_scalar\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSECP256K1_SCALAR_CONST\fP(d7,  d6,  d5,  d4,  d3,  d2,  d1,  d0)   {{((\fBuint64_t\fP)(d1)) << 32 | (d0), ((\fBuint64_t\fP)(d3)) << 32 | (d2), ((\fBuint64_t\fP)(d5)) << 32 | (d4), ((\fBuint64_t\fP)(d7)) << 32 | (d6)}}"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SECP256K1_SCALAR_CONST(d7, d6, d5, d4, d3, d2, d1, d0)   {{((\fBuint64_t\fP)(d1)) << 32 | (d0), ((\fBuint64_t\fP)(d3)) << 32 | (d2), ((\fBuint64_t\fP)(d5)) << 32 | (d4), ((\fBuint64_t\fP)(d7)) << 32 | (d6)}}"

.PP
Definition at line 17 of file scalar_4x64\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
