.TH "/home/dev/ds-160209/src/secp256k1/src/modules/schnorr/schnorr.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/secp256k1/src/modules/schnorr/schnorr.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'scalar\&.h'\fP
.br
\fC#include 'group\&.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBsecp256k1_schnorr_msghash\fP) (unsigned char *h32, const unsigned char *r32, const unsigned char *msg32)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* secp256k1_schnorr_msghash) (unsigned char *h32, const unsigned char *r32, const unsigned char *msg32)"

.PP
Definition at line 13 of file schnorr\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
