.TH "/home/dev/ds-160209/src/script.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/script.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/foreach\&.hpp>\fP
.br
\fC#include <boost/tuple/tuple\&.hpp>\fP
.br
\fC#include <boost/tuple/tuple_comparison\&.hpp>\fP
.br
\fC#include 'script\&.h'\fP
.br
\fC#include 'keystore\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'sync\&.h'\fP
.br
\fC#include 'crypto/ripemd160\&.h'\fP
.br
\fC#include 'crypto/sha1\&.h'\fP
.br
\fC#include 'crypto/sha256\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCSignatureCache\fP"
.br
.ti -1c
.RI "class \fBCKeyStoreIsMineVisitor\fP"
.br
.ti -1c
.RI "class \fBCAffectedKeysVisitor\fP"
.br
.ti -1c
.RI "class \fBCScriptVisitor\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBstacktop\fP(i)   (stack\&.at(stack\&.size()+(i)))"
.br
.ti -1c
.RI "#define \fBaltstacktop\fP(i)   (altstack\&.at(altstack\&.size()+(i)))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBScriptErrorString\fP (const \fBScriptError\fP serror)"
.br
.ti -1c
.RI "bool \fBCheckSig\fP (vector< unsigned char > vchSig, const vector< unsigned char > &vchPubKey, const \fBCScript\fP &scriptCode, const \fBCTransaction\fP &txTo, unsigned int nIn, int nHashType, int flags)"
.br
.ti -1c
.RI "\fBCBigNum\fP \fBCastToBigNum\fP (const \fBvaltype\fP &vch, const size_t nMaxNumSize=nDefaultMaxNumSize)"
.br
.ti -1c
.RI "bool \fBCastToBool\fP (const \fBvaltype\fP &vch)"
.br
.ti -1c
.RI "void \fBMakeSameSize\fP (\fBvaltype\fP &vch1, \fBvaltype\fP &vch2)"
.br
.ti -1c
.RI "const char * \fBGetTxnOutputType\fP (\fBtxnouttype\fP t)"
.br
.ti -1c
.RI "const char * \fBGetOpName\fP (\fBopcodetype\fP opcode)"
.br
.ti -1c
.RI "bool \fBIsCompressedOrUncompressedPubKey\fP (const \fBvaltype\fP &vchPubKey)"
.br
.ti -1c
.RI "bool \fBIsDERSignature\fP (const \fBvaltype\fP &vchSig, bool haveHashType)"
.br
.ti -1c
.RI "bool \fBEvalScript\fP (vector< vector< unsigned char > > &stack, const \fBCScript\fP &script, const \fBCTransaction\fP &txTo, unsigned int nIn, unsigned int flags, int nHashType)"
.br
.ti -1c
.RI "bool \fBEvalScript\fP (vector< vector< unsigned char > > &stack, const \fBCScript\fP &script, unsigned int flags, const \fBBaseSignatureChecker\fP &checker, \fBScriptError\fP *serror)"
.br
.ti -1c
.RI "\fBuint256\fP \fBSignatureHash\fP (\fBCScript\fP scriptCode, const \fBCTransaction\fP &txTo, unsigned int nIn, int nHashType)"
.br
.ti -1c
.RI "bool \fBSignSignature\fP (const \fBCKeyStore\fP &keystore, const \fBCScript\fP &fromPubKey, \fBCMutableTransaction\fP &txTo, unsigned int nIn, int nHashType)"
.br
.ti -1c
.RI "bool \fBSignSignature\fP (const \fBCKeyStore\fP &keystore, const \fBCScript\fP &fromPubKey, \fBCTransaction\fP &txTo, unsigned int nIn, int nHashType)"
.br
.ti -1c
.RI "bool \fBSignSignature\fP (const \fBCKeyStore\fP &keystore, const \fBCTransaction\fP &txFrom, \fBCTransaction\fP &txTo, unsigned int nIn, int nHashType)"
.br
.ti -1c
.RI "bool \fBSignSignature\fP (const \fBCKeyStore\fP &keystore, const \fBCMutableTransaction\fP &txFrom, \fBCTransaction\fP &txTo, unsigned int nIn, int nHashType)"
.br
.ti -1c
.RI "bool \fBSolver\fP (const \fBCScript\fP &scriptPubKey, \fBtxnouttype\fP &typeRet, vector< vector< unsigned char > > &vSolutionsRet)"
.br
.ti -1c
.RI "bool \fBSign1\fP (const \fBCKeyID\fP &address, const \fBCKeyStore\fP &keystore, \fBuint256\fP \fBhash\fP, int nHashType, \fBCScript\fP &scriptSigRet)"
.br
.ti -1c
.RI "bool \fBSignN\fP (const vector< \fBvaltype\fP > &multisigdata, const \fBCKeyStore\fP &keystore, \fBuint256\fP \fBhash\fP, int nHashType, \fBCScript\fP &scriptSigRet)"
.br
.ti -1c
.RI "bool \fBSolver\fP (const \fBCKeyStore\fP &keystore, const \fBCScript\fP &scriptPubKey, \fBuint256\fP \fBhash\fP, int nHashType, \fBCScript\fP &scriptSigRet, \fBtxnouttype\fP &whichTypeRet)"
.br
.ti -1c
.RI "int \fBScriptSigArgsExpected\fP (\fBtxnouttype\fP t, const std::vector< std::vector< unsigned char > > &vSolutions)"
.br
.ti -1c
.RI "bool \fBIsStandard\fP (const \fBCScript\fP &scriptPubKey, \fBtxnouttype\fP &whichType)"
.br
.ti -1c
.RI "unsigned int \fBHaveKeys\fP (const vector< \fBvaltype\fP > &pubkeys, const \fBCKeyStore\fP &keystore)"
.br
.ti -1c
.RI "\fBisminetype\fP \fBIsMine\fP (const \fBCKeyStore\fP &keystore, const \fBCTxDestination\fP &dest)"
.br
.ti -1c
.RI "\fBisminetype\fP \fBIsMine\fP (const \fBCKeyStore\fP &keystore, const \fBCScript\fP &scriptPubKey)"
.br
.ti -1c
.RI "bool \fBExtractDestination\fP (const \fBCScript\fP &scriptPubKey, \fBCTxDestination\fP &addressRet)"
.br
.ti -1c
.RI "void \fBExtractAffectedKeys\fP (const \fBCKeyStore\fP &keystore, const \fBCScript\fP &scriptPubKey, std::vector< \fBCKeyID\fP > &vKeys)"
.br
.ti -1c
.RI "bool \fBExtractDestinations\fP (const \fBCScript\fP &scriptPubKey, \fBtxnouttype\fP &typeRet, vector< \fBCTxDestination\fP > &addressRet, int &nRequiredRet)"
.br
.ti -1c
.RI "bool \fBVerifyScript\fP (const \fBCScript\fP &scriptSig, const \fBCScript\fP &scriptPubKey, const \fBCTransaction\fP &txTo, unsigned int nIn, unsigned int flags, int nHashType)"
.br
.ti -1c
.RI "bool \fBVerifyScript\fP (const \fBCScript\fP &scriptSig, const \fBCScript\fP &scriptPubKey, unsigned int flags, const \fBBaseSignatureChecker\fP &checker, \fBScriptError\fP *serror)"
.br
.ti -1c
.RI "bool \fBVerifySignature\fP (const \fBCTransaction\fP &txFrom, const \fBCTransaction\fP &txTo, unsigned int nIn, unsigned int flags, int nHashType)"
.br
.ti -1c
.RI "\fBCScript\fP \fBCombineSignatures\fP (\fBCScript\fP scriptPubKey, const \fBCTransaction\fP &txTo, unsigned int nIn, const \fBCScript\fP &scriptSig1, const \fBCScript\fP &scriptSig2)"
.br
.ti -1c
.RI "\fBCScript\fP \fBGetScriptForDestination\fP (const \fBCTxDestination\fP &dest)"
.br
.ti -1c
.RI "\fBCScript\fP \fBGetScriptForMultisig\fP (int nRequired, const std::vector< \fBCPubKey\fP > &keys)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define altstacktop(i)   (altstack\&.at(altstack\&.size()+(i)))"

.PP
Definition at line 175 of file script\&.cpp\&.
.SS "#define stacktop(i)   (stack\&.at(stack\&.size()+(i)))"

.PP
Definition at line 174 of file script\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "\fBCBigNum\fP CastToBigNum (const \fBvaltype\fP & vch, const size_t nMaxNumSize = \fCnDefaultMaxNumSize\fP)"

.PP
Definition at line 119 of file script\&.cpp\&.
.SS "bool CastToBool (const \fBvaltype\fP & vch)"

.PP
Definition at line 127 of file script\&.cpp\&.
.SS "bool CheckSig (vector< unsigned char > vchSig, const vector< unsigned char > & vchPubKey, const \fBCScript\fP & scriptCode, const \fBCTransaction\fP & txTo, unsigned int nIn, int nHashType, int flags)"

.PP
Definition at line 2299 of file script\&.cpp\&.
.SS "\fBCScript\fP CombineSignatures (\fBCScript\fP scriptPubKey, const \fBCTransaction\fP & txTo, unsigned int nIn, const \fBCScript\fP & scriptSig1, const \fBCScript\fP & scriptSig2)"

.PP
Definition at line 3080 of file script\&.cpp\&.
.SS "bool EvalScript (vector< vector< unsigned char > > & stack, const \fBCScript\fP & script, const \fBCTransaction\fP & txTo, unsigned int nIn, unsigned int flags, int nHashType)"

.PP
Definition at line 475 of file script\&.cpp\&.
.SS "bool EvalScript (vector< vector< unsigned char > > & stack, const \fBCScript\fP & script, unsigned int flags, const \fBBaseSignatureChecker\fP & checker, \fBScriptError\fP * serror)"

.PP
Definition at line 1393 of file script\&.cpp\&.
.SS "void ExtractAffectedKeys (const \fBCKeyStore\fP & keystore, const \fBCScript\fP & scriptPubKey, std::vector< \fBCKeyID\fP > & vKeys)"

.PP
Definition at line 2734 of file script\&.cpp\&.
.SS "bool ExtractDestination (const \fBCScript\fP & scriptPubKey, \fBCTxDestination\fP & addressRet)"

.PP
Definition at line 2670 of file script\&.cpp\&.
.SS "bool ExtractDestinations (const \fBCScript\fP & scriptPubKey, \fBtxnouttype\fP & typeRet, vector< \fBCTxDestination\fP > & addressRet, int & nRequiredRet)"

.PP
Definition at line 2738 of file script\&.cpp\&.
.SS "const char* GetOpName (\fBopcodetype\fP opcode)"

.PP
Definition at line 199 of file script\&.cpp\&.
.SS "\fBCScript\fP GetScriptForDestination (const \fBCTxDestination\fP & dest)"

.PP
Definition at line 3226 of file script\&.cpp\&.
.SS "\fBCScript\fP GetScriptForMultisig (int nRequired, const std::vector< \fBCPubKey\fP > & keys)"

.PP
Definition at line 3234 of file script\&.cpp\&.
.SS "const char* GetTxnOutputType (\fBtxnouttype\fP t)"

.PP
Definition at line 184 of file script\&.cpp\&.
.SS "unsigned int HaveKeys (const vector< \fBvaltype\fP > & pubkeys, const \fBCKeyStore\fP & keystore)"

.PP
Definition at line 2579 of file script\&.cpp\&.
.SS "bool IsCompressedOrUncompressedPubKey (const \fBvaltype\fP & vchPubKey)"

.PP
Definition at line 342 of file script\&.cpp\&.
.SS "bool IsDERSignature (const \fBvaltype\fP & vchSig, bool haveHashType)"

.PP
Definition at line 357 of file script\&.cpp\&.
.SS "\fBisminetype\fP IsMine (const \fBCKeyStore\fP & keystore, const \fBCTxDestination\fP & dest)"

.PP
Definition at line 2607 of file script\&.cpp\&.
.SS "\fBisminetype\fP IsMine (const \fBCKeyStore\fP & keystore, const \fBCScript\fP & scriptPubKey)"

.PP
Definition at line 2614 of file script\&.cpp\&.
.SS "bool IsStandard (const \fBCScript\fP & scriptPubKey, \fBtxnouttype\fP & whichType)"

.PP
Definition at line 2558 of file script\&.cpp\&.
.SS "void MakeSameSize (\fBvaltype\fP & vch1, \fBvaltype\fP & vch2)"

.PP
Definition at line 149 of file script\&.cpp\&.
.SS "const char* ScriptErrorString (const \fBScriptError\fP serror)"

.PP
Definition at line 41 of file script\&.cpp\&.
.SS "int ScriptSigArgsExpected (\fBtxnouttype\fP t, const std::vector< std::vector< unsigned char > > & vSolutions)"

.PP
Definition at line 2537 of file script\&.cpp\&.
.SS "bool Sign1 (const \fBCKeyID\fP & address, const \fBCKeyStore\fP & keystore, \fBuint256\fP hash, int nHashType, \fBCScript\fP & scriptSigRet)"

.PP
Definition at line 2463 of file script\&.cpp\&.
.SS "\fBuint256\fP SignatureHash (\fBCScript\fP scriptCode, const \fBCTransaction\fP & txTo, unsigned int nIn, int nHashType)"

.PP
Definition at line 2092 of file script\&.cpp\&.
.SS "bool SignN (const vector< \fBvaltype\fP > & multisigdata, const \fBCKeyStore\fP & keystore, \fBuint256\fP hash, int nHashType, \fBCScript\fP & scriptSigRet)"

.PP
Definition at line 2478 of file script\&.cpp\&.
.SS "bool SignSignature (const \fBCKeyStore\fP & keystore, const \fBCScript\fP & fromPubKey, \fBCMutableTransaction\fP & txTo, unsigned int nIn, int nHashType)"

.PP
Definition at line 2153 of file script\&.cpp\&.
.SS "bool SignSignature (const \fBCKeyStore\fP & keystore, const \fBCScript\fP & fromPubKey, \fBCTransaction\fP & txTo, unsigned int nIn, int nHashType)"

.PP
Definition at line 2188 of file script\&.cpp\&.
.SS "bool SignSignature (const \fBCKeyStore\fP & keystore, const \fBCTransaction\fP & txFrom, \fBCTransaction\fP & txTo, unsigned int nIn, int nHashType)"

.PP
Definition at line 2223 of file script\&.cpp\&.
.SS "bool SignSignature (const \fBCKeyStore\fP & keystore, const \fBCMutableTransaction\fP & txFrom, \fBCTransaction\fP & txTo, unsigned int nIn, int nHashType)"

.PP
Definition at line 2233 of file script\&.cpp\&.
.SS "bool Solver (const \fBCScript\fP & scriptPubKey, \fBtxnouttype\fP & typeRet, vector< vector< unsigned char > > & vSolutionsRet)"

.PP
Definition at line 2342 of file script\&.cpp\&.
.SS "bool Solver (const \fBCKeyStore\fP & keystore, const \fBCScript\fP & scriptPubKey, \fBuint256\fP hash, int nHashType, \fBCScript\fP & scriptSigRet, \fBtxnouttype\fP & whichTypeRet)"

.PP
Definition at line 2498 of file script\&.cpp\&.
.SS "bool VerifyScript (const \fBCScript\fP & scriptSig, const \fBCScript\fP & scriptPubKey, const \fBCTransaction\fP & txTo, unsigned int nIn, unsigned int flags, int nHashType)"

.PP
Definition at line 2822 of file script\&.cpp\&.
.SS "bool VerifyScript (const \fBCScript\fP & scriptSig, const \fBCScript\fP & scriptPubKey, unsigned int flags, const \fBBaseSignatureChecker\fP & checker, \fBScriptError\fP * serror)"

.PP
Definition at line 2858 of file script\&.cpp\&.
.SS "bool VerifySignature (const \fBCTransaction\fP & txFrom, const \fBCTransaction\fP & txTo, unsigned int nIn, unsigned int flags, int nHashType)"

.PP
Definition at line 2958 of file script\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
