.TH "/home/dev/ds-160209/src/scrypt.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/scrypt.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'net\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBuint256\fP \fBscrypt_salted_multiround_hash\fP (const void *input, size_t inputlen, const void *salt, size_t saltlen, const unsigned int nRounds)"
.br
.ti -1c
.RI "\fBuint256\fP \fBscrypt_salted_hash\fP (const void *input, size_t inputlen, const void *salt, size_t saltlen)"
.br
.ti -1c
.RI "\fBuint256\fP \fBscrypt_hash\fP (const void *input, size_t inputlen)"
.br
.ti -1c
.RI "\fBuint256\fP \fBscrypt_blockhash\fP (const void *input)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBuint256\fP scrypt_blockhash (const void * input)"

.PP
Definition at line 193 of file scrypt\&.cpp\&.
.SS "\fBuint256\fP scrypt_hash (const void * input, size_t inputlen)"

.PP
Definition at line 167 of file scrypt\&.cpp\&.
.SS "\fBuint256\fP scrypt_salted_hash (const void * input, size_t inputlen, const void * salt, size_t saltlen)"

.PP
Definition at line 173 of file scrypt\&.cpp\&.
.SS "\fBuint256\fP scrypt_salted_multiround_hash (const void * input, size_t inputlen, const void * salt, size_t saltlen, const unsigned int nRounds)"

.PP
Definition at line 179 of file scrypt\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
