.TH "SecMsgAddress" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecMsgAddress \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <smessage\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSecMsgAddress\fP ()"
.br
.ti -1c
.RI "\fBSecMsgAddress\fP (std::string sAddr, bool receiveOn, bool receiveAnon)"
.br
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBsAddress\fP"
.br
.ti -1c
.RI "bool \fBfReceiveEnabled\fP"
.br
.ti -1c
.RI "bool \fBfReceiveAnon\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 190 of file smessage\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SecMsgAddress::SecMsgAddress ()\fC [inline]\fP"

.PP
Definition at line 193 of file smessage\&.h\&.
.SS "SecMsgAddress::SecMsgAddress (std::string sAddr, bool receiveOn, bool receiveAnon)\fC [inline]\fP"

.PP
Definition at line 194 of file smessage\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream , typename Operation > void SecMsgAddress::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 208 of file smessage\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "SecMsgAddress::ADD_SERIALIZE_METHODS"

.PP
Definition at line 205 of file smessage\&.h\&.
.SS "bool SecMsgAddress::fReceiveAnon"

.PP
Definition at line 203 of file smessage\&.h\&.
.SS "bool SecMsgAddress::fReceiveEnabled"

.PP
Definition at line 202 of file smessage\&.h\&.
.SS "std::string SecMsgAddress::sAddress"

.PP
Definition at line 199 of file smessage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
