.TH "SecMsgBatchScanner" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecMsgBatchScanner \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBleveldb::WriteBatch::Handler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSecMsgBatchScanner\fP ()"
.br
.ti -1c
.RI "virtual void \fBPut\fP (const \fBleveldb::Slice\fP &key, const \fBleveldb::Slice\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "virtual void \fBDelete\fP (const \fBleveldb::Slice\fP &key)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBneedle\fP"
.br
.ti -1c
.RI "bool * \fBdeleted\fP"
.br
.ti -1c
.RI "std::string * \fBfoundValue\fP"
.br
.ti -1c
.RI "bool \fBfoundEntry\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 224 of file smessage\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SecMsgBatchScanner::SecMsgBatchScanner ()\fC [inline]\fP"

.PP
Definition at line 232 of file smessage\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void SecMsgBatchScanner::Delete (const \fBleveldb::Slice\fP & key)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::WriteBatch::Handler\fP\&.
.PP
Definition at line 244 of file smessage\&.cpp\&.
.SS "virtual void SecMsgBatchScanner::Put (const \fBleveldb::Slice\fP & key, const \fBleveldb::Slice\fP & value)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBleveldb::WriteBatch::Handler\fP\&.
.PP
Definition at line 234 of file smessage\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "bool* SecMsgBatchScanner::deleted"

.PP
Definition at line 228 of file smessage\&.cpp\&.
.SS "bool SecMsgBatchScanner::foundEntry"

.PP
Definition at line 230 of file smessage\&.cpp\&.
.SS "std::string* SecMsgBatchScanner::foundValue"

.PP
Definition at line 229 of file smessage\&.cpp\&.
.SS "std::string SecMsgBatchScanner::needle"

.PP
Definition at line 227 of file smessage\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
