.TH "SecMsgStored" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecMsgStored \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <smessage\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename Stream , typename Operation > void \fBSerializationOp\fP (Stream &s, Operation ser_action, int nType, int nVersion)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint64_t\fP \fBtimeReceived\fP"
.br
.ti -1c
.RI "char \fBstatus\fP"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBfolderId\fP"
.br
.ti -1c
.RI "std::string \fBsAddrTo\fP"
.br
.ti -1c
.RI "std::string \fBsAddrOutbox\fP"
.br
.ti -1c
.RI "std::vector< \fBuint8_t\fP > \fBvchMessage\fP"
.br
.ti -1c
.RI "\fBADD_SERIALIZE_METHODS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 268 of file smessage\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Stream , typename Operation > void SecMsgStored::SerializationOp (Stream & s, Operation ser_action, int nType, int nVersion)\fC [inline]\fP"

.PP
Definition at line 281 of file smessage\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "SecMsgStored::ADD_SERIALIZE_METHODS"

.PP
Definition at line 278 of file smessage\&.h\&.
.SS "\fBuint16_t\fP SecMsgStored::folderId"

.PP
Definition at line 273 of file smessage\&.h\&.
.SS "std::string SecMsgStored::sAddrOutbox"

.PP
Definition at line 275 of file smessage\&.h\&.
.SS "std::string SecMsgStored::sAddrTo"

.PP
Definition at line 274 of file smessage\&.h\&.
.SS "char SecMsgStored::status"

.PP
Definition at line 272 of file smessage\&.h\&.
.SS "\fBint64_t\fP SecMsgStored::timeReceived"

.PP
Definition at line 271 of file smessage\&.h\&.
.SS "std::vector<\fBuint8_t\fP> SecMsgStored::vchMessage"

.PP
Definition at line 276 of file smessage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
