.TH "SecMsgToken" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecMsgToken \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <smessage\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSecMsgToken\fP (\fBint64_t\fP ts, \fBuint8_t\fP *p, int np, long int o)"
.br
.ti -1c
.RI "\fBSecMsgToken\fP ()"
.br
.ti -1c
.RI "\fB~SecMsgToken\fP ()"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBSecMsgToken\fP &y) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint64_t\fP \fBtimestamp\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBsample\fP [8]"
.br
.ti -1c
.RI "\fBint64_t\fP \fBoffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 111 of file smessage\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SecMsgToken::SecMsgToken (\fBint64_t\fP ts, \fBuint8_t\fP * p, int np, long int o)\fC [inline]\fP"

.PP
Definition at line 114 of file smessage\&.h\&.
.SS "SecMsgToken::SecMsgToken ()\fC [inline]\fP"

.PP
Definition at line 125 of file smessage\&.h\&.
.SS "SecMsgToken::~SecMsgToken ()\fC [inline]\fP"

.PP
Definition at line 127 of file smessage\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SecMsgToken::operator< (const \fBSecMsgToken\fP & y) const\fC [inline]\fP"

.PP
Definition at line 129 of file smessage\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBint64_t\fP SecMsgToken::offset"

.PP
Definition at line 139 of file smessage\&.h\&.
.SS "\fBuint8_t\fP SecMsgToken::sample[8]"

.PP
Definition at line 138 of file smessage\&.h\&.
.SS "\fBint64_t\fP SecMsgToken::timestamp"

.PP
Definition at line 137 of file smessage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
