.TH "SecMsgBucket" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecMsgBucket \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <smessage\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSecMsgBucket\fP ()"
.br
.ti -1c
.RI "\fB~SecMsgBucket\fP ()"
.br
.ti -1c
.RI "void \fBhashBucket\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint64_t\fP \fBtimeChanged\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBhash\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBnLockCount\fP"
.br
.ti -1c
.RI "\fBNodeId\fP \fBnLockPeerId\fP"
.br
.ti -1c
.RI "std::set< \fBSecMsgToken\fP > \fBsetTokens\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 144 of file smessage\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SecMsgBucket::SecMsgBucket ()\fC [inline]\fP"

.PP
Definition at line 147 of file smessage\&.h\&.
.SS "SecMsgBucket::~SecMsgBucket ()\fC [inline]\fP"

.PP
Definition at line 154 of file smessage\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void SecMsgBucket::hashBucket ()"

.PP
Definition at line 165 of file smessage\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint32_t\fP SecMsgBucket::hash"

.PP
Definition at line 159 of file smessage\&.h\&.
.SS "\fBuint32_t\fP SecMsgBucket::nLockCount"

.PP
Definition at line 160 of file smessage\&.h\&.
.SS "\fBNodeId\fP SecMsgBucket::nLockPeerId"

.PP
Definition at line 161 of file smessage\&.h\&.
.SS "std::set<\fBSecMsgToken\fP> SecMsgBucket::setTokens"

.PP
Definition at line 162 of file smessage\&.h\&.
.SS "\fBint64_t\fP SecMsgBucket::timeChanged"

.PP
Definition at line 158 of file smessage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
