.TH "SecMsgCrypter" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecMsgCrypter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <smessage\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSecMsgCrypter\fP ()"
.br
.ti -1c
.RI "\fB~SecMsgCrypter\fP ()"
.br
.ti -1c
.RI "bool \fBSetKey\fP (const std::vector< \fBuint8_t\fP > &vchNewKey, \fBuint8_t\fP *chNewIV)"
.br
.ti -1c
.RI "bool \fBSetKey\fP (const \fBuint8_t\fP *chNewKey, \fBuint8_t\fP *chNewIV)"
.br
.ti -1c
.RI "bool \fBEncrypt\fP (\fBuint8_t\fP *chPlaintext, \fBuint32_t\fP nPlain, std::vector< \fBuint8_t\fP > &vchCiphertext)"
.br
.ti -1c
.RI "bool \fBDecrypt\fP (\fBuint8_t\fP *chCiphertext, \fBuint32_t\fP nCipher, std::vector< \fBuint8_t\fP > &vchPlaintext)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 232 of file smessage\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SecMsgCrypter::SecMsgCrypter ()\fC [inline]\fP"

.PP
Definition at line 240 of file smessage\&.h\&.
.SS "SecMsgCrypter::~SecMsgCrypter ()\fC [inline]\fP"

.PP
Definition at line 250 of file smessage\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SecMsgCrypter::Decrypt (\fBuint8_t\fP * chCiphertext, \fBuint32_t\fP nCipher, std::vector< \fBuint8_t\fP > & vchPlaintext)"

.PP
Definition at line 137 of file smessage\&.cpp\&.
.SS "bool SecMsgCrypter::Encrypt (\fBuint8_t\fP * chPlaintext, \fBuint32_t\fP nPlain, std::vector< \fBuint8_t\fP > & vchCiphertext)"

.PP
Definition at line 108 of file smessage\&.cpp\&.
.SS "bool SecMsgCrypter::SetKey (const std::vector< \fBuint8_t\fP > & vchNewKey, \fBuint8_t\fP * chNewIV)"

.PP
Definition at line 90 of file smessage\&.cpp\&.
.SS "bool SecMsgCrypter::SetKey (const \fBuint8_t\fP * chNewKey, \fBuint8_t\fP * chNewIV)"

.PP
Definition at line 98 of file smessage\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
