.TH "SecMsgNode" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecMsgNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <net\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSecMsgNode\fP ()"
.br
.ti -1c
.RI "\fB~SecMsgNode\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_smsg_net\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBlastSeen\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBlastMatched\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBignoreUntil\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBnWakeCounter\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBnPeerId\fP"
.br
.ti -1c
.RI "bool \fBfEnabled\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 196 of file net\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SecMsgNode::SecMsgNode ()\fC [inline]\fP"

.PP
Definition at line 199 of file net\&.h\&.
.SS "SecMsgNode::~SecMsgNode ()\fC [inline]\fP"

.PP
Definition at line 209 of file net\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCCriticalSection\fP SecMsgNode::cs_smsg_net"

.PP
Definition at line 209 of file net\&.h\&.
.SS "bool SecMsgNode::fEnabled"

.PP
Definition at line 217 of file net\&.h\&.
.SS "\fBint64_t\fP SecMsgNode::ignoreUntil"

.PP
Definition at line 214 of file net\&.h\&.
.SS "\fBint64_t\fP SecMsgNode::lastMatched"

.PP
Definition at line 213 of file net\&.h\&.
.SS "\fBint64_t\fP SecMsgNode::lastSeen"

.PP
Definition at line 212 of file net\&.h\&.
.SS "\fBuint32_t\fP SecMsgNode::nPeerId"

.PP
Definition at line 216 of file net\&.h\&.
.SS "\fBuint32_t\fP SecMsgNode::nWakeCounter"

.PP
Definition at line 215 of file net\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
