.TH "secp256k1_pubkey" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_pubkey \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <secp256k1\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBdata\fP [64]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Opaque data structure that holds a parsed and valid public key\&.
.PP
The exact representation of data inside is implementation defined and not guaranteed to be portable between different platforms or versions\&. It is however guaranteed to be 64 bytes in size, and can be safely copied/moved\&. If you need to convert to a format suitable for storage or transmission, use secp256k1_ec_pubkey_serialize and secp256k1_ec_pubkey_parse\&.
.PP
Furthermore, it is guaranteed that identical public keys (ignoring compression) will have identical representation, so they can be memcmp'ed\&. 
.PP
Definition at line 56 of file secp256k1\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned char secp256k1_pubkey::data[64]"

.PP
Definition at line 57 of file secp256k1\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
