.TH "secp256k1_scalar" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_scalar \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <scalar_4x64\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint64_t\fP \fBd\fP [4]"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBd\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
A scalar modulo the group order of the secp256k1 curve\&. 
.PP
Definition at line 13 of file scalar_4x64\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint64_t\fP secp256k1_scalar::d[4]"

.PP
Definition at line 14 of file scalar_4x64\&.h\&.
.SS "\fBuint32_t\fP secp256k1_scalar::d[8]"

.PP
Definition at line 14 of file scalar_8x32\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
