.TH "secp256k1_ecmult_gen_context" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_ecmult_gen_context \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ecmult_gen\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsecp256k1_ge_storage\fP(* \fBprec\fP )[64][16]"
.br
.ti -1c
.RI "\fBsecp256k1_scalar\fP \fBblind\fP"
.br
.ti -1c
.RI "\fBsecp256k1_gej\fP \fBinitial\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file ecmult_gen\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBsecp256k1_scalar\fP secp256k1_ecmult_gen_context::blind"

.PP
Definition at line 27 of file ecmult_gen\&.h\&.
.SS "\fBsecp256k1_gej\fP secp256k1_ecmult_gen_context::initial"

.PP
Definition at line 28 of file ecmult_gen\&.h\&.
.SS "\fBsecp256k1_ge_storage\fP(* secp256k1_ecmult_gen_context::prec)[64][16]"

.PP
Definition at line 26 of file ecmult_gen\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
