.TH "secp256k1_callback" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_callback \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <util\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void(* \fBfn\fP )(const char *text, void *\fBdata\fP)"
.br
.ti -1c
.RI "const void * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file util\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "const void* secp256k1_callback::data"

.PP
Definition at line 20 of file util\&.h\&.
.SS "void(* secp256k1_callback::fn) (const char *text, void *\fBdata\fP)"

.PP
Definition at line 19 of file util\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
