.TH "secp256k1_hmac_sha256_t" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_hmac_sha256_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hash\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsecp256k1_sha256_t\fP \fBinner\fP"
.br
.ti -1c
.RI "\fBsecp256k1_sha256_t\fP \fBouter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file hash\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBsecp256k1_sha256_t\fP secp256k1_hmac_sha256_t::inner"

.PP
Definition at line 24 of file hash\&.h\&.
.SS "\fBsecp256k1_sha256_t\fP secp256k1_hmac_sha256_t::outer"

.PP
Definition at line 24 of file hash\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
