.TH "secp256k1_num" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_num \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <num_gmp\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "mp_limb_t \fBdata\fP [2 *\fBNUM_LIMBS\fP]"
.br
.ti -1c
.RI "int \fBneg\fP"
.br
.ti -1c
.RI "int \fBlimbs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file num_gmp\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "mp_limb_t secp256k1_num::data[2 *\fBNUM_LIMBS\fP]"

.PP
Definition at line 15 of file num_gmp\&.h\&.
.SS "int secp256k1_num::limbs"

.PP
Definition at line 17 of file num_gmp\&.h\&.
.SS "int secp256k1_num::neg"

.PP
Definition at line 16 of file num_gmp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
