.TH "secp256k1_rfc6979_hmac_sha256_t" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_rfc6979_hmac_sha256_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hash\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBv\fP [32]"
.br
.ti -1c
.RI "unsigned char \fBk\fP [32]"
.br
.ti -1c
.RI "int \fBretry\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file hash\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned char secp256k1_rfc6979_hmac_sha256_t::k[32]"

.PP
Definition at line 33 of file hash\&.h\&.
.SS "int secp256k1_rfc6979_hmac_sha256_t::retry"

.PP
Definition at line 34 of file hash\&.h\&.
.SS "unsigned char secp256k1_rfc6979_hmac_sha256_t::v[32]"

.PP
Definition at line 32 of file hash\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
