.TH "secp256k1_gej" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_gej \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <group\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsecp256k1_fe\fP \fBx\fP"
.br
.ti -1c
.RI "\fBsecp256k1_fe\fP \fBy\fP"
.br
.ti -1c
.RI "\fBsecp256k1_fe\fP \fBz\fP"
.br
.ti -1c
.RI "int \fBinfinity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A group element of the secp256k1 curve, in jacobian coordinates\&. 
.PP
Definition at line 24 of file group\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int secp256k1_gej::infinity"

.PP
Definition at line 28 of file group\&.h\&.
.SS "\fBsecp256k1_fe\fP secp256k1_gej::x"

.PP
Definition at line 25 of file group\&.h\&.
.SS "\fBsecp256k1_fe\fP secp256k1_gej::y"

.PP
Definition at line 26 of file group\&.h\&.
.SS "\fBsecp256k1_fe\fP secp256k1_gej::z"

.PP
Definition at line 27 of file group\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
