.TH "secp256k1_ge_storage" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_ge_storage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <group\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsecp256k1_fe_storage\fP \fBx\fP"
.br
.ti -1c
.RI "\fBsecp256k1_fe_storage\fP \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file group\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBsecp256k1_fe_storage\fP secp256k1_ge_storage::x"

.PP
Definition at line 35 of file group\&.h\&.
.SS "\fBsecp256k1_fe_storage\fP secp256k1_ge_storage::y"

.PP
Definition at line 36 of file group\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
