.TH "secp256k1_context_struct" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secp256k1_context_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsecp256k1_ecmult_context\fP \fBecmult_ctx\fP"
.br
.ti -1c
.RI "\fBsecp256k1_ecmult_gen_context\fP \fBecmult_gen_ctx\fP"
.br
.ti -1c
.RI "\fBsecp256k1_callback\fP \fBillegal_callback\fP"
.br
.ti -1c
.RI "\fBsecp256k1_callback\fP \fBerror_callback\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file secp256k1\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBsecp256k1_ecmult_context\fP secp256k1_context_struct::ecmult_ctx"

.PP
Definition at line 54 of file secp256k1\&.c\&.
.SS "\fBsecp256k1_ecmult_gen_context\fP secp256k1_context_struct::ecmult_gen_ctx"

.PP
Definition at line 55 of file secp256k1\&.c\&.
.SS "\fBsecp256k1_callback\fP secp256k1_context_struct::error_callback"

.PP
Definition at line 57 of file secp256k1\&.c\&.
.SS "\fBsecp256k1_callback\fP secp256k1_context_struct::illegal_callback"

.PP
Definition at line 56 of file secp256k1\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
