.TH "secure_allocator< T >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secure_allocator< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <allocators\&.h>\fP
.PP
Inherits allocator< T >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBrebind\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::allocator< T > \fBbase\fP"
.br
.ti -1c
.RI "typedef base::size_type \fBsize_type\fP"
.br
.ti -1c
.RI "typedef base::difference_type \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef base::pointer \fBpointer\fP"
.br
.ti -1c
.RI "typedef base::const_pointer \fBconst_pointer\fP"
.br
.ti -1c
.RI "typedef base::reference \fBreference\fP"
.br
.ti -1c
.RI "typedef base::const_reference \fBconst_reference\fP"
.br
.ti -1c
.RI "typedef base::value_type \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsecure_allocator\fP ()  throw ()"
.br
.ti -1c
.RI "\fBsecure_allocator\fP (const \fBsecure_allocator\fP &a)  throw ()"
.br
.ti -1c
.RI "template<typename U > \fBsecure_allocator\fP (const \fBsecure_allocator\fP< U > &a)  throw ()"
.br
.ti -1c
.RI "\fB~secure_allocator\fP ()  throw ()"
.br
.ti -1c
.RI "T * \fBallocate\fP (std::size_t n, const void *hint=0)"
.br
.ti -1c
.RI "void \fBdeallocate\fP (T *p, std::size_t n)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>struct secure_allocator< T >"

.PP
Definition at line 199 of file allocators\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T> typedef std::allocator<T> \fBsecure_allocator\fP< T >::\fBbase\fP"

.PP
Definition at line 202 of file allocators\&.h\&.
.SS "template<typename T> typedef base::const_pointer \fBsecure_allocator\fP< T >::\fBconst_pointer\fP"

.PP
Definition at line 206 of file allocators\&.h\&.
.SS "template<typename T> typedef base::const_reference \fBsecure_allocator\fP< T >::\fBconst_reference\fP"

.PP
Definition at line 208 of file allocators\&.h\&.
.SS "template<typename T> typedef base::difference_type \fBsecure_allocator\fP< T >::\fBdifference_type\fP"

.PP
Definition at line 204 of file allocators\&.h\&.
.SS "template<typename T> typedef base::pointer \fBsecure_allocator\fP< T >::\fBpointer\fP"

.PP
Definition at line 205 of file allocators\&.h\&.
.SS "template<typename T> typedef base::reference \fBsecure_allocator\fP< T >::\fBreference\fP"

.PP
Definition at line 207 of file allocators\&.h\&.
.SS "template<typename T> typedef base::size_type \fBsecure_allocator\fP< T >::\fBsize_type\fP"

.PP
Definition at line 203 of file allocators\&.h\&.
.SS "template<typename T> typedef base::value_type \fBsecure_allocator\fP< T >::\fBvalue_type\fP"

.PP
Definition at line 209 of file allocators\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBsecure_allocator\fP< T >::\fBsecure_allocator\fP ()\fC [inline]\fP"

.PP
Definition at line 210 of file allocators\&.h\&.
.SS "template<typename T> \fBsecure_allocator\fP< T >::\fBsecure_allocator\fP (const \fBsecure_allocator\fP< T > & a)\fC [inline]\fP"

.PP
Definition at line 211 of file allocators\&.h\&.
.SS "template<typename T> template<typename U > \fBsecure_allocator\fP< T >::\fBsecure_allocator\fP (const \fBsecure_allocator\fP< U > & a)\fC [inline]\fP"

.PP
Definition at line 213 of file allocators\&.h\&.
.SS "template<typename T> \fBsecure_allocator\fP< T >::~\fBsecure_allocator\fP ()\fC [inline]\fP"

.PP
Definition at line 214 of file allocators\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> T* \fBsecure_allocator\fP< T >::allocate (std::size_t n, const void * hint = \fC0\fP)\fC [inline]\fP"

.PP
Definition at line 218 of file allocators\&.h\&.
.SS "template<typename T> void \fBsecure_allocator\fP< T >::deallocate (T * p, std::size_t n)\fC [inline]\fP"

.PP
Definition at line 227 of file allocators\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
