.TH "SecureMessage" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecureMessage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <smessage\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSecureMessage\fP ()"
.br
.ti -1c
.RI "\fB~SecureMessage\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint8_t\fP \fBhash\fP [4]"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBversion\fP [2]"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBint64_t\fP \fBtimestamp\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBiv\fP [16]"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBcpkR\fP [33]"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBmac\fP [32]"
.br
.ti -1c
.RI "\fBuint8_t\fP \fBnonse\fP [4]"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBnPayload\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBpPayload\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 69 of file smessage\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SecureMessage::SecureMessage ()\fC [inline]\fP"

.PP
Definition at line 72 of file smessage\&.h\&.
.SS "SecureMessage::~SecureMessage ()\fC [inline]\fP"

.PP
Definition at line 78 of file smessage\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint8_t\fP SecureMessage::cpkR[33]"

.PP
Definition at line 90 of file smessage\&.h\&.
.SS "\fBuint8_t\fP SecureMessage::flags"

.PP
Definition at line 87 of file smessage\&.h\&.
.SS "\fBuint8_t\fP SecureMessage::hash[4]"

.PP
Definition at line 83 of file smessage\&.h\&.
.SS "\fBuint8_t\fP SecureMessage::iv[16]"

.PP
Definition at line 89 of file smessage\&.h\&.
.SS "\fBuint8_t\fP SecureMessage::mac[32]"

.PP
Definition at line 91 of file smessage\&.h\&.
.SS "\fBuint8_t\fP SecureMessage::nonse[4]"

.PP
Definition at line 92 of file smessage\&.h\&.
.SS "\fBuint32_t\fP SecureMessage::nPayload"

.PP
Definition at line 93 of file smessage\&.h\&.
.SS "\fBuint8_t\fP* SecureMessage::pPayload"

.PP
Definition at line 94 of file smessage\&.h\&.
.SS "\fBint64_t\fP SecureMessage::timestamp"

.PP
Definition at line 88 of file smessage\&.h\&.
.SS "\fBuint8_t\fP SecureMessage::version[2]"

.PP
Definition at line 86 of file smessage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
