.TH "secure_allocator< T >::rebind< _Other >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
secure_allocator< T >::rebind< _Other > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <allocators\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBsecure_allocator\fP< _Other > \fBother\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>template<typename _Other>struct secure_allocator< T >::rebind< _Other >"

.PP
Definition at line 215 of file allocators\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T> template<typename _Other > typedef \fBsecure_allocator\fP<_Other> \fBsecure_allocator\fP< T >::\fBrebind\fP< _Other >::\fBother\fP"

.PP
Definition at line 216 of file allocators\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
