.TH "SeedSpec6" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SeedSpec6 \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint8_t\fP \fBaddr\fP [16]"
.br
.ti -1c
.RI "\fBuint16_t\fP \fBport\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file chainparams\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBuint8_t\fP SeedSpec6::addr[16]"

.PP
Definition at line 17 of file chainparams\&.cpp\&.
.SS "\fBuint16_t\fP SeedSpec6::port"

.PP
Definition at line 18 of file chainparams\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
