.TH "/home/dev/ds-160209/src/qt/sendmessagesdialog.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/sendmessagesdialog.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sendmessagesdialog\&.h'\fP
.br
\fC#include 'ui_sendmessagesdialog\&.h'\fP
.br
\fC#include 'walletmodel\&.h'\fP
.br
\fC#include 'messagemodel\&.h'\fP
.br
\fC#include 'addressbookpage\&.h'\fP
.br
\fC#include 'optionsmodel\&.h'\fP
.br
\fC#include 'sendmessagesentry\&.h'\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QLocale>\fP
.br
\fC#include <QTextDocument>\fP
.br
\fC#include <QScrollBar>\fP
.br
\fC#include <QClipboard>\fP
.br
\fC#include <QDataWidgetMapper>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
