.TH "SendMessagesEntry" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SendMessagesEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sendmessagesentry\&.h>\fP
.PP
Inherits QFrame\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetRemoveEnabled\fP (bool enabled)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBremoveEntry\fP (\fBSendMessagesEntry\fP *entry)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSendMessagesEntry\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~SendMessagesEntry\fP ()"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBMessageModel\fP *model)"
.br
.ti -1c
.RI "void \fBloadRow\fP (int row)"
.br
.ti -1c
.RI "bool \fBvalidate\fP ()"
.br
.ti -1c
.RI "\fBSendMessagesRecipient\fP \fBgetValue\fP ()"
.br
.ti -1c
.RI "bool \fBisClear\fP ()"
.br
.ti -1c
.RI "void \fBsetValue\fP (const \fBSendMessagesRecipient\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "QWidget * \fBsetupTabChain\fP (QWidget *\fBprev\fP)"
.br
.ti -1c
.RI "void \fBsetFocus\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A single entry in the dialog for sending messages\&. 
.PP
Definition at line 13 of file sendmessagesentry\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SendMessagesEntry::SendMessagesEntry (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 15 of file sendmessagesentry\&.cpp\&.
.SS "SendMessagesEntry::~SendMessagesEntry ()"

.PP
Definition at line 38 of file sendmessagesentry\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void SendMessagesEntry::clear ()\fC [slot]\fP"

.PP
Definition at line 117 of file sendmessagesentry\&.cpp\&.
.SS "\fBSendMessagesRecipient\fP SendMessagesEntry::getValue ()"

.PP
Definition at line 161 of file sendmessagesentry\&.cpp\&.
.SS "bool SendMessagesEntry::isClear ()"
Return whether the entry is still empty and unedited 
.PP
Definition at line 196 of file sendmessagesentry\&.cpp\&.
.SS "void SendMessagesEntry::loadRow (int row)"

.PP
Definition at line 104 of file sendmessagesentry\&.cpp\&.
.SS "void SendMessagesEntry::removeEntry (\fBSendMessagesEntry\fP * entry)\fC [signal]\fP"

.SS "void SendMessagesEntry::setFocus ()"

.PP
Definition at line 201 of file sendmessagesentry\&.cpp\&.
.SS "void SendMessagesEntry::setModel (\fBMessageModel\fP * model)"

.PP
Definition at line 96 of file sendmessagesentry\&.cpp\&.
.SS "void SendMessagesEntry::setRemoveEnabled (bool enabled)\fC [slot]\fP"

.PP
Definition at line 112 of file sendmessagesentry\&.cpp\&.
.SS "QWidget * SendMessagesEntry::setupTabChain (QWidget * prev)"
Set up the tab chain manually, as Qt messes up the tab chain by default in some cases (issue https://bugreports.qt-project.org/browse/QTBUG-10907)\&. 
.PP
Definition at line 174 of file sendmessagesentry\&.cpp\&.
.SS "void SendMessagesEntry::setValue (const \fBSendMessagesRecipient\fP & value)"

.PP
Definition at line 188 of file sendmessagesentry\&.cpp\&.
.SS "bool SendMessagesEntry::validate ()"

.PP
Definition at line 131 of file sendmessagesentry\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
