.TH "SendMessagesRecipient" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SendMessagesRecipient \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <messagemodel\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBaddress\fP"
.br
.ti -1c
.RI "QString \fBlabel\fP"
.br
.ti -1c
.RI "QString \fBpubkey\fP"
.br
.ti -1c
.RI "QString \fBmessage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file messagemodel\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "QString SendMessagesRecipient::address"

.PP
Definition at line 27 of file messagemodel\&.h\&.
.SS "QString SendMessagesRecipient::label"

.PP
Definition at line 28 of file messagemodel\&.h\&.
.SS "QString SendMessagesRecipient::message"

.PP
Definition at line 30 of file messagemodel\&.h\&.
.SS "QString SendMessagesRecipient::pubkey"

.PP
Definition at line 29 of file messagemodel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
