.TH "ser_streamplaceholder" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ser_streamplaceholder \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <serialize\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnType\fP"
.br
.ti -1c
.RI "int \fBnVersion\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 830 of file serialize\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int ser_streamplaceholder::nType"

.PP
Definition at line 832 of file serialize\&.h\&.
.SS "int ser_streamplaceholder::nVersion"

.PP
Definition at line 833 of file serialize\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
