.TH "ShowI2PAddresses" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShowI2PAddresses \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <showi2paddresses\&.h>\fP
.PP
Inherits QDialog, and QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShowI2PAddresses\fP (const QString &caption, const QString &pub, const QString &priv, const QString &b32, const QString &configFileName, QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~ShowI2PAddresses\fP ()"
.br
.ti -1c
.RI "\fBShowI2PAddresses\fP (const QString &caption, const QString &pub, const QString &priv, const QString &b32, const QString &configFileName, QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~ShowI2PAddresses\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file showi2paddresses\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ShowI2PAddresses::ShowI2PAddresses (const QString & caption, const QString & pub, const QString & priv, const QString & b32, const QString & configFileName, QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 4 of file showi2paddresses\&.cpp\&.
.SS "ShowI2PAddresses::~ShowI2PAddresses ()"

.PP
Definition at line 31 of file showi2paddresses\&.cpp\&.
.SS "ShowI2PAddresses::ShowI2PAddresses (const QString & caption, const QString & pub, const QString & priv, const QString & b32, const QString & configFileName, QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.SS "ShowI2PAddresses::~ShowI2PAddresses ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
