.TH "/home/dev/ds-160209/src/qt/signverifymessagedialog.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/signverifymessagedialog.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'signverifymessagedialog\&.h'\fP
.br
\fC#include 'ui_signverifymessagedialog\&.h'\fP
.br
\fC#include 'addressbookpage\&.h'\fP
.br
\fC#include 'base58\&.h'\fP
.br
\fC#include 'guiutil\&.h'\fP
.br
\fC#include 'init\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'optionsmodel\&.h'\fP
.br
\fC#include 'walletmodel\&.h'\fP
.br
\fC#include 'wallet\&.h'\fP
.br
\fC#include <QClipboard>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
