.TH "SignatureChecker" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SignatureChecker \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <script\&.h>\fP
.PP
Inherits \fBBaseSignatureChecker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSignatureChecker\fP (const \fBCTransaction\fP &txToIn, unsigned int nInIn)"
.br
.ti -1c
.RI "bool \fBCheckSig\fP (const std::vector< unsigned char > &scriptSig, const std::vector< unsigned char > &vchPubKey, const \fBCScript\fP &scriptCode) const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBVerifySignature\fP (const std::vector< unsigned char > &vchSig, const \fBCPubKey\fP &vchPubKey, const \fBuint256\fP &sighash) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 951 of file script\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SignatureChecker::SignatureChecker (const \fBCTransaction\fP & txToIn, unsigned int nInIn)\fC [inline]\fP"

.PP
Definition at line 961 of file script\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SignatureChecker::CheckSig (const std::vector< unsigned char > & scriptSig, const std::vector< unsigned char > & vchPubKey, const \fBCScript\fP & scriptCode) const\fC [virtual]\fP"

.PP
Reimplemented from \fBBaseSignatureChecker\fP\&.
.PP
Definition at line 2800 of file script\&.cpp\&.
.SS "bool SignatureChecker::VerifySignature (const std::vector< unsigned char > & vchSig, const \fBCPubKey\fP & vchPubKey, const \fBuint256\fP & sighash) const\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 2795 of file script\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
