.TH "SignVerifyMessageDialog" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SignVerifyMessageDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <signverifymessagedialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSignVerifyMessageDialog\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~SignVerifyMessageDialog\fP ()"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBWalletModel\fP *model)"
.br
.ti -1c
.RI "void \fBsetAddress_SM\fP (QString address)"
.br
.ti -1c
.RI "void \fBsetAddress_VM\fP (QString address)"
.br
.ti -1c
.RI "void \fBshowTab_SM\fP (bool fShow)"
.br
.ti -1c
.RI "void \fBshowTab_VM\fP (bool fShow)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBeventFilter\fP (QObject *object, QEvent *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file signverifymessagedialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SignVerifyMessageDialog::SignVerifyMessageDialog (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 18 of file signverifymessagedialog\&.cpp\&.
.SS "SignVerifyMessageDialog::~SignVerifyMessageDialog ()"

.PP
Definition at line 47 of file signverifymessagedialog\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SignVerifyMessageDialog::eventFilter (QObject * object, QEvent * event)\fC [protected]\fP"

.PP
Definition at line 253 of file signverifymessagedialog\&.cpp\&.
.SS "void SignVerifyMessageDialog::setAddress_SM (QString address)"

.PP
Definition at line 57 of file signverifymessagedialog\&.cpp\&.
.SS "void SignVerifyMessageDialog::setAddress_VM (QString address)"

.PP
Definition at line 63 of file signverifymessagedialog\&.cpp\&.
.SS "void SignVerifyMessageDialog::setModel (\fBWalletModel\fP * model)"

.PP
Definition at line 52 of file signverifymessagedialog\&.cpp\&.
.SS "void SignVerifyMessageDialog::showTab_SM (bool fShow)"

.PP
Definition at line 69 of file signverifymessagedialog\&.cpp\&.
.SS "void SignVerifyMessageDialog::showTab_VM (bool fShow)"

.PP
Definition at line 77 of file signverifymessagedialog\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
