.TH "/home/dev/ds-160209/src/smessage.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/smessage.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <leveldb/db\&.h>\fP
.br
\fC#include <leveldb/write_batch\&.h>\fP
.br
\fC#include 'net\&.h'\fP
.br
\fC#include 'db\&.h'\fP
.br
\fC#include 'wallet\&.h'\fP
.br
\fC#include 'base58\&.h'\fP
.br
\fC#include 'lz4/lz4\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSecureMessage\fP"
.br
.ti -1c
.RI "class \fBMessageData\fP"
.br
.ti -1c
.RI "class \fBSecMsgToken\fP"
.br
.ti -1c
.RI "class \fBSecMsgBucket\fP"
.br
.ti -1c
.RI "class \fBCDarkSilkAddress_B\fP"
.br
.ti -1c
.RI "class \fBCKeyID_B\fP"
.br
.ti -1c
.RI "class \fBSecMsgAddress\fP"
.br
.ti -1c
.RI "class \fBSecMsgOptions\fP"
.br
.ti -1c
.RI "class \fBSecMsgCrypter\fP"
.br
.ti -1c
.RI "class \fBSecMsgStored\fP"
.br
.ti -1c
.RI "class \fBSecMsgDB\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSMSG_MASK_UNREAD\fP   (1 << 0)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBSecureMsgBuildBucketSet\fP ()"
.br
.ti -1c
.RI "int \fBSecureMsgAddWalletAddresses\fP ()"
.br
.ti -1c
.RI "int \fBSecureMsgReadIni\fP ()"
.br
.ti -1c
.RI "int \fBSecureMsgWriteIni\fP ()"
.br
.ti -1c
.RI "bool \fBSecureMsgStart\fP (bool fDontStart, bool fScanChain)"
.br
.ti -1c
.RI "bool \fBSecureMsgShutdown\fP ()"
.br
.ti -1c
.RI "bool \fBSecureMsgEnable\fP ()"
.br
.ti -1c
.RI "bool \fBSecureMsgDisable\fP ()"
.br
.ti -1c
.RI "bool \fBSecureMsgReceiveData\fP (\fBCNode\fP *pfrom, std::string strCommand, \fBCDataStream\fP &vRecv)"
.br
.ti -1c
.RI "bool \fBSecureMsgSendData\fP (\fBCNode\fP *pto, bool fSendTrickle)"
.br
.ti -1c
.RI "bool \fBSecureMsgScanBlock\fP (\fBCBlock\fP &\fBblock\fP)"
.br
.ti -1c
.RI "bool \fBScanChainForPublicKeys\fP (\fBCBlockIndex\fP *pindexStart)"
.br
.ti -1c
.RI "bool \fBSecureMsgScanBlockChain\fP ()"
.br
.ti -1c
.RI "bool \fBSecureMsgScanBuckets\fP ()"
.br
.ti -1c
.RI "int \fBSecureMsgWalletUnlocked\fP ()"
.br
.ti -1c
.RI "int \fBSecureMsgWalletKeyChanged\fP (std::string sAddress, std::string sLabel, \fBChangeType\fP mode)"
.br
.ti -1c
.RI "int \fBSecureMsgScanMessage\fP (\fBuint8_t\fP *pHeader, \fBuint8_t\fP *pPayload, \fBuint32_t\fP nPayload, bool reportToGui)"
.br
.ti -1c
.RI "int \fBSecureMsgGetStoredKey\fP (\fBCKeyID\fP &ckid, \fBCPubKey\fP &cpkOut)"
.br
.ti -1c
.RI "int \fBSecureMsgGetLocalKey\fP (\fBCKeyID\fP &ckid, \fBCPubKey\fP &cpkOut)"
.br
.ti -1c
.RI "int \fBSecureMsgGetLocalPublicKey\fP (std::string &strAddress, std::string &strPublicKey)"
.br
.ti -1c
.RI "int \fBSecureMsgAddAddress\fP (std::string &address, std::string &publicKey)"
.br
.ti -1c
.RI "int \fBSecureMsgRetrieve\fP (\fBSecMsgToken\fP &token, std::vector< \fBuint8_t\fP > &vchData)"
.br
.ti -1c
.RI "int \fBSecureMsgReceive\fP (\fBCNode\fP *pfrom, std::vector< \fBuint8_t\fP > &vchData)"
.br
.ti -1c
.RI "int \fBSecureMsgStoreUnscanned\fP (\fBuint8_t\fP *pHeader, \fBuint8_t\fP *pPayload, \fBuint32_t\fP nPayload)"
.br
.ti -1c
.RI "int \fBSecureMsgStore\fP (\fBuint8_t\fP *pHeader, \fBuint8_t\fP *pPayload, \fBuint32_t\fP nPayload, bool fUpdateBucket)"
.br
.ti -1c
.RI "int \fBSecureMsgStore\fP (\fBSecureMessage\fP &smsg, bool fUpdateBucket)"
.br
.ti -1c
.RI "int \fBSecureMsgSend\fP (std::string &addressFrom, std::string &addressTo, std::string &message, std::string &sError)"
.br
.ti -1c
.RI "int \fBSecureMsgValidate\fP (\fBuint8_t\fP *pHeader, \fBuint8_t\fP *pPayload, \fBuint32_t\fP nPayload)"
.br
.ti -1c
.RI "int \fBSecureMsgSetHash\fP (\fBuint8_t\fP *pHeader, \fBuint8_t\fP *pPayload, \fBuint32_t\fP nPayload)"
.br
.ti -1c
.RI "int \fBSecureMsgEncrypt\fP (\fBSecureMessage\fP &smsg, const std::string &addressFrom, const std::string &addressTo, const std::string &message)"
.br
.ti -1c
.RI "int \fBSecureMsgDecrypt\fP (bool fTestOnly, std::string &address, \fBuint8_t\fP *pHeader, \fBuint8_t\fP *pPayload, \fBuint32_t\fP nPayload, \fBMessageData\fP &msg)"
.br
.ti -1c
.RI "int \fBSecureMsgDecrypt\fP (bool fTestOnly, std::string &address, \fBSecureMessage\fP &smsg, \fBMessageData\fP &msg)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned int \fBSMSG_HDR_LEN\fP = 104"
.br
.ti -1c
.RI "const unsigned int \fBSMSG_PL_HDR_LEN\fP = 1+20+65+4"
.br
.ti -1c
.RI "const unsigned int \fBSMSG_BUCKET_LEN\fP = 60 * 10"
.br
.ti -1c
.RI "const unsigned int \fBSMSG_RETENTION\fP = 60 * 60 * 48"
.br
.ti -1c
.RI "const unsigned int \fBSMSG_SEND_DELAY\fP = 2"
.br
.ti -1c
.RI "const unsigned int \fBSMSG_THREAD_DELAY\fP = 30"
.br
.ti -1c
.RI "const unsigned int \fBSMSG_THREAD_LOG_GAP\fP = 6"
.br
.ti -1c
.RI "const unsigned int \fBSMSG_TIME_LEEWAY\fP = 60"
.br
.ti -1c
.RI "const unsigned int \fBSMSG_TIME_IGNORE\fP = 90"
.br
.ti -1c
.RI "const unsigned int \fBSMSG_MAX_MSG_BYTES\fP = 4096"
.br
.ti -1c
.RI "const unsigned int \fBSMSG_MAX_MSG_WORST\fP = \fBLZ4_COMPRESSBOUND\fP(\fBSMSG_MAX_MSG_BYTES\fP+\fBSMSG_PL_HDR_LEN\fP)"
.br
.ti -1c
.RI "bool \fBfSecMsgEnabled\fP"
.br
.ti -1c
.RI "boost::signals2::signal< void(\fBSecMsgStored\fP &inboxHdr)> \fBNotifySecMsgInboxChanged\fP"
.br
.ti -1c
.RI "boost::signals2::signal< void(\fBSecMsgStored\fP &outboxHdr)> \fBNotifySecMsgOutboxChanged\fP"
.br
.ti -1c
.RI "boost::signals2::signal< void()> \fBNotifySecMsgWalletUnlocked\fP"
.br
.ti -1c
.RI "std::map< \fBint64_t\fP, \fBSecMsgBucket\fP > \fBsmsgBuckets\fP"
.br
.ti -1c
.RI "std::vector< \fBSecMsgAddress\fP > \fBsmsgAddresses\fP"
.br
.ti -1c
.RI "\fBSecMsgOptions\fP \fBsmsgOptions\fP"
.br
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_smsg\fP"
.br
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_smsgDB\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SMSG_MASK_UNREAD   (1 << 0)"

.PP
Definition at line 38 of file smessage\&.h\&.
.SH "Function Documentation"
.PP 
.SS "bool ScanChainForPublicKeys (\fBCBlockIndex\fP * pindexStart)"

.PP
Definition at line 2073 of file smessage\&.cpp\&.
.SS "int SecureMsgAddAddress (std::string & address, std::string & publicKey)"

.PP
Definition at line 2676 of file smessage\&.cpp\&.
.SS "int SecureMsgAddWalletAddresses ()"

.PP
Definition at line 911 of file smessage\&.cpp\&.
.SS "int SecureMsgBuildBucketSet ()"

.PP
Definition at line 768 of file smessage\&.cpp\&.
.SS "int SecureMsgDecrypt (bool fTestOnly, std::string & address, \fBuint8_t\fP * pHeader, \fBuint8_t\fP * pPayload, \fBuint32_t\fP nPayload, \fBMessageData\fP & msg)"

.PP
Definition at line 3702 of file smessage\&.cpp\&.
.SS "int SecureMsgDecrypt (bool fTestOnly, std::string & address, \fBSecureMessage\fP & smsg, \fBMessageData\fP & msg)"

.PP
Definition at line 3948 of file smessage\&.cpp\&.
.SS "bool SecureMsgDisable ()"

.PP
Definition at line 1231 of file smessage\&.cpp\&.
.SS "bool SecureMsgEnable ()"

.PP
Definition at line 1170 of file smessage\&.cpp\&.
.SS "int SecureMsgEncrypt (\fBSecureMessage\fP & smsg, const std::string & addressFrom, const std::string & addressTo, const std::string & message)"

.PP
Definition at line 3276 of file smessage\&.cpp\&.
.SS "int SecureMsgGetLocalKey (\fBCKeyID\fP & ckid, \fBCPubKey\fP & cpkOut)"

.PP
Definition at line 2601 of file smessage\&.cpp\&.
.SS "int SecureMsgGetLocalPublicKey (std::string & strAddress, std::string & strPublicKey)"

.PP
Definition at line 2619 of file smessage\&.cpp\&.
.SS "int SecureMsgGetStoredKey (\fBCKeyID\fP & ckid, \fBCPubKey\fP & cpkOut)"

.PP
Definition at line 2649 of file smessage\&.cpp\&.
.SS "int SecureMsgReadIni ()"

.PP
Definition at line 964 of file smessage\&.cpp\&.
.SS "int SecureMsgReceive (\fBCNode\fP * pfrom, std::vector< \fBuint8_t\fP > & vchData)"

.PP
Definition at line 2796 of file smessage\&.cpp\&.
.SS "bool SecureMsgReceiveData (\fBCNode\fP * pfrom, std::string strCommand, \fBCDataStream\fP & vRecv)"

.PP
Definition at line 1292 of file smessage\&.cpp\&.
.SS "int SecureMsgRetrieve (\fBSecMsgToken\fP & token, std::vector< \fBuint8_t\fP > & vchData)"

.PP
Definition at line 2731 of file smessage\&.cpp\&.
.SS "bool SecureMsgScanBlock (\fBCBlock\fP & block)"

.PP
Definition at line 2037 of file smessage\&.cpp\&.
.SS "bool SecureMsgScanBlockChain ()"

.PP
Definition at line 2123 of file smessage\&.cpp\&.
.SS "bool SecureMsgScanBuckets ()"

.PP
Definition at line 2153 of file smessage\&.cpp\&.
.SS "int SecureMsgScanMessage (\fBuint8_t\fP * pHeader, \fBuint8_t\fP * pPayload, \fBuint32_t\fP nPayload, bool reportToGui)"

.PP
Definition at line 2482 of file smessage\&.cpp\&.
.SS "int SecureMsgSend (std::string & addressFrom, std::string & addressTo, std::string & message, std::string & sError)"

.PP
Definition at line 3533 of file smessage\&.cpp\&.
.SS "bool SecureMsgSendData (\fBCNode\fP * pto, bool fSendTrickle)"

.PP
Definition at line 1783 of file smessage\&.cpp\&.
.SS "int SecureMsgSetHash (\fBuint8_t\fP * pHeader, \fBuint8_t\fP * pPayload, \fBuint32_t\fP nPayload)"

.PP
Definition at line 3168 of file smessage\&.cpp\&.
.SS "bool SecureMsgShutdown ()"

.PP
Definition at line 1144 of file smessage\&.cpp\&.
.SS "bool SecureMsgStart (bool fDontStart, bool fScanChain)"
called from \fBAppInit2()\fP in \fBinit\&.cpp\fP 
.PP
Definition at line 1104 of file smessage\&.cpp\&.
.SS "int SecureMsgStore (\fBuint8_t\fP * pHeader, \fBuint8_t\fP * pPayload, \fBuint32_t\fP nPayload, bool fUpdateBucket)"

.PP
Definition at line 2978 of file smessage\&.cpp\&.
.SS "int SecureMsgStore (\fBSecureMessage\fP & smsg, bool fUpdateBucket)"

.PP
Definition at line 3094 of file smessage\&.cpp\&.
.SS "int SecureMsgStoreUnscanned (\fBuint8_t\fP * pHeader, \fBuint8_t\fP * pPayload, \fBuint32_t\fP nPayload)"

.PP
Definition at line 2911 of file smessage\&.cpp\&.
.SS "int SecureMsgValidate (\fBuint8_t\fP * pHeader, \fBuint8_t\fP * pPayload, \fBuint32_t\fP nPayload)"

.PP
Definition at line 3099 of file smessage\&.cpp\&.
.SS "int SecureMsgWalletKeyChanged (std::string sAddress, std::string sLabel, \fBChangeType\fP mode)"

.PP
Definition at line 2446 of file smessage\&.cpp\&.
.SS "int SecureMsgWalletUnlocked ()"

.PP
Definition at line 2301 of file smessage\&.cpp\&.
.SS "int SecureMsgWriteIni ()"

.PP
Definition at line 1038 of file smessage\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBCCriticalSection\fP cs_smsg"

.PP
Definition at line 81 of file smessage\&.cpp\&.
.SS "\fBCCriticalSection\fP cs_smsgDB"

.PP
Definition at line 82 of file smessage\&.cpp\&.
.SS "bool fSecMsgEnabled"

.PP
Definition at line 74 of file smessage\&.cpp\&.
.SS "boost::signals2::signal<void (\fBSecMsgStored\fP& inboxHdr)> NotifySecMsgInboxChanged"

.PP
Definition at line 70 of file smessage\&.cpp\&.
.SS "boost::signals2::signal<void (\fBSecMsgStored\fP& outboxHdr)> NotifySecMsgOutboxChanged"

.PP
Definition at line 71 of file smessage\&.cpp\&.
.SS "boost::signals2::signal<void ()> NotifySecMsgWalletUnlocked"

.PP
Definition at line 72 of file smessage\&.cpp\&.
.SS "const unsigned int SMSG_BUCKET_LEN = 60 * 10"

.PP
Definition at line 21 of file smessage\&.h\&.
.SS "const unsigned int SMSG_HDR_LEN = 104"

.PP
Definition at line 18 of file smessage\&.h\&.
.SS "const unsigned int SMSG_MAX_MSG_BYTES = 4096"

.PP
Definition at line 31 of file smessage\&.h\&.
.SS "const unsigned int SMSG_MAX_MSG_WORST = \fBLZ4_COMPRESSBOUND\fP(\fBSMSG_MAX_MSG_BYTES\fP+\fBSMSG_PL_HDR_LEN\fP)"

.PP
Definition at line 34 of file smessage\&.h\&.
.SS "const unsigned int SMSG_PL_HDR_LEN = 1+20+65+4"

.PP
Definition at line 19 of file smessage\&.h\&.
.SS "const unsigned int SMSG_RETENTION = 60 * 60 * 48"

.PP
Definition at line 22 of file smessage\&.h\&.
.SS "const unsigned int SMSG_SEND_DELAY = 2"

.PP
Definition at line 23 of file smessage\&.h\&.
.SS "const unsigned int SMSG_THREAD_DELAY = 30"

.PP
Definition at line 24 of file smessage\&.h\&.
.SS "const unsigned int SMSG_THREAD_LOG_GAP = 6"

.PP
Definition at line 25 of file smessage\&.h\&.
.SS "const unsigned int SMSG_TIME_IGNORE = 90"

.PP
Definition at line 28 of file smessage\&.h\&.
.SS "const unsigned int SMSG_TIME_LEEWAY = 60"

.PP
Definition at line 27 of file smessage\&.h\&.
.SS "std::vector<\fBSecMsgAddress\fP> smsgAddresses"

.PP
Definition at line 77 of file smessage\&.cpp\&.
.SS "std::map<\fBint64_t\fP, \fBSecMsgBucket\fP> smsgBuckets"

.PP
Definition at line 76 of file smessage\&.cpp\&.
.SS "\fBSecMsgOptions\fP smsgOptions"

.PP
Definition at line 78 of file smessage\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
