.TH "SSLIOStreamDevice< Protocol >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SSLIOStreamDevice< Protocol > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rpcprotocol\&.h>\fP
.PP
Inherits device< boost::iostreams::bidirectional >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSSLIOStreamDevice\fP (boost::asio::ssl::stream< typename Protocol::socket > &streamIn, bool fUseSSLIn)"
.br
.ti -1c
.RI "void \fBhandshake\fP (boost::asio::ssl::stream_base::handshake_type role)"
.br
.ti -1c
.RI "std::streamsize \fBread\fP (char *s, std::streamsize n)"
.br
.ti -1c
.RI "std::streamsize \fBwrite\fP (const char *s, std::streamsize n)"
.br
.ti -1c
.RI "bool \fBconnect\fP (const std::string &server, const std::string &port)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Protocol>class SSLIOStreamDevice< Protocol >"

.PP
Definition at line 79 of file rpcprotocol\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename Protocol> \fBSSLIOStreamDevice\fP< Protocol >::\fBSSLIOStreamDevice\fP (boost::asio::ssl::stream< typename Protocol::socket > & streamIn, bool fUseSSLIn)\fC [inline]\fP"

.PP
Definition at line 81 of file rpcprotocol\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Protocol> bool \fBSSLIOStreamDevice\fP< Protocol >::connect (const std::string & server, const std::string & port)\fC [inline]\fP"

.PP
Definition at line 105 of file rpcprotocol\&.h\&.
.SS "template<typename Protocol> void \fBSSLIOStreamDevice\fP< Protocol >::handshake (boost::asio::ssl::stream_base::handshake_type role)\fC [inline]\fP"

.PP
Definition at line 87 of file rpcprotocol\&.h\&.
.SS "template<typename Protocol> std::streamsize \fBSSLIOStreamDevice\fP< Protocol >::read (char * s, std::streamsize n)\fC [inline]\fP"

.PP
Definition at line 93 of file rpcprotocol\&.h\&.
.SS "template<typename Protocol> std::streamsize \fBSSLIOStreamDevice\fP< Protocol >::write (const char * s, std::streamsize n)\fC [inline]\fP"

.PP
Definition at line 99 of file rpcprotocol\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
