.TH "StatisticsPage" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatisticsPage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <statisticspage\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBupdateStatistics\fP ()"
.br
.ti -1c
.RI "void \fBupdatePrevious\fP (int, QString, double, double, double, double, QString, int, int)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStatisticsPage\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~StatisticsPage\fP ()"
.br
.ti -1c
.RI "void \fBsetModel\fP (\fBClientModel\fP *model)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBheightPrevious\fP"
.br
.ti -1c
.RI "int \fBconnectionPrevious\fP"
.br
.ti -1c
.RI "int \fBvolumePrevious\fP"
.br
.ti -1c
.RI "double \fBrewardPrevious\fP"
.br
.ti -1c
.RI "double \fBnetPawratePrevious\fP"
.br
.ti -1c
.RI "QString \fBpawratePrevious\fP"
.br
.ti -1c
.RI "double \fBhardnessPrevious\fP"
.br
.ti -1c
.RI "double \fBhardnessPrevious2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file statisticspage\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StatisticsPage::StatisticsPage (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 14 of file statisticspage\&.cpp\&.
.SS "StatisticsPage::~StatisticsPage ()"

.PP
Definition at line 129 of file statisticspage\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void StatisticsPage::setModel (\fBClientModel\fP * model)"

.PP
Definition at line 123 of file statisticspage\&.cpp\&.
.SS "void StatisticsPage::updatePrevious (int nHeight, QString phase, double nSubsidy, double pHardness, double pHardness2, double pPawrate2, QString Qlpawrate, int peers, int volume)\fC [slot]\fP"

.PP
Definition at line 111 of file statisticspage\&.cpp\&.
.SS "void StatisticsPage::updateStatistics ()\fC [slot]\fP"

.PP
Definition at line 34 of file statisticspage\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int StatisticsPage::connectionPrevious"

.PP
Definition at line 37 of file statisticspage\&.h\&.
.SS "double StatisticsPage::hardnessPrevious"

.PP
Definition at line 42 of file statisticspage\&.h\&.
.SS "double StatisticsPage::hardnessPrevious2"

.PP
Definition at line 43 of file statisticspage\&.h\&.
.SS "int StatisticsPage::heightPrevious"

.PP
Definition at line 36 of file statisticspage\&.h\&.
.SS "double StatisticsPage::netPawratePrevious"

.PP
Definition at line 40 of file statisticspage\&.h\&.
.SS "QString StatisticsPage::pawratePrevious"

.PP
Definition at line 41 of file statisticspage\&.h\&.
.SS "double StatisticsPage::rewardPrevious"

.PP
Definition at line 39 of file statisticspage\&.h\&.
.SS "int StatisticsPage::volumePrevious"

.PP
Definition at line 38 of file statisticspage\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
