.TH "/home/dev/ds-160209/src/leveldb/port/win/stdint.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/port/win/stdint.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef signed char \fBint8_t\fP"
.br
.ti -1c
.RI "typedef signed short \fBint16_t\fP"
.br
.ti -1c
.RI "typedef signed int \fBint32_t\fP"
.br
.ti -1c
.RI "typedef signed long long \fBint64_t\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBuint8_t\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBuint16_t\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBuint32_t\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBuint64_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef signed short \fBint16_t\fP"

.PP
Definition at line 16 of file stdint\&.h\&.
.SS "typedef signed int \fBint32_t\fP"

.PP
Definition at line 17 of file stdint\&.h\&.
.SS "typedef signed long long \fBint64_t\fP"

.PP
Definition at line 18 of file stdint\&.h\&.
.SS "typedef signed char \fBint8_t\fP"

.PP
Definition at line 15 of file stdint\&.h\&.
.SS "typedef unsigned short \fBuint16_t\fP"

.PP
Definition at line 20 of file stdint\&.h\&.
.SS "typedef unsigned int \fBuint32_t\fP"

.PP
Definition at line 21 of file stdint\&.h\&.
.SS "typedef unsigned long long \fBuint64_t\fP"

.PP
Definition at line 22 of file stdint\&.h\&.
.SS "typedef unsigned char \fBuint8_t\fP"

.PP
Definition at line 19 of file stdint\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
