.TH "StormNodeConfigDialog" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StormNodeConfigDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stormnodeconfigdialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStormNodeConfigDialog\fP (QWidget *parent=0, QString nodeAddress='123\&.456\&.789\&.123:31000', QString privkey='STORMNODEPRIVKEY')"
.br
.ti -1c
.RI "\fB~StormNodeConfigDialog\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Dialog showing transaction details\&. 
.PP
Definition at line 15 of file stormnodeconfigdialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StormNodeConfigDialog::StormNodeConfigDialog (QWidget * parent = \fC0\fP, QString nodeAddress = \fC'123\&.456\&.789\&.123:31000'\fP, QString privkey = \fC'STORMNODEPRIVKEY'\fP)\fC [explicit]\fP"

.PP
Definition at line 6 of file stormnodeconfigdialog\&.cpp\&.
.SS "StormNodeConfigDialog::~StormNodeConfigDialog ()"

.PP
Definition at line 15 of file stormnodeconfigdialog\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
