.TH "/home/dev/ds-160209/src/stormnode-payments.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/stormnode-payments.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'key\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'stormnode\&.h'\fP
.br
\fC#include <boost/lexical_cast\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCStormnodePaymentDB\fP"
.br
.ti -1c
.RI "class \fBCStormnodePayee\fP"
.br
.ti -1c
.RI "class \fBCStormnodeBlockPayees\fP"
.br
.ti -1c
.RI "class \fBCStormnodePaymentWinner\fP"
.br
.ti -1c
.RI "class \fBCStormnodePayments\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSNPAYMENTS_SIGNATURES_REQUIRED\fP   10"
.br
.ti -1c
.RI "#define \fBSNPAYMENTS_SIGNATURES_TOTAL\fP   15"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBProcessMessageStormnodePayments\fP (\fBCNode\fP *pfrom, std::string &strCommand, \fBCDataStream\fP &vRecv)"
.br
.ti -1c
.RI "bool \fBIsReferenceNode\fP (\fBCTxIn\fP &vin)"
.br
.ti -1c
.RI "bool \fBIsBlockPayeeValid\fP (const \fBCTransaction\fP &txNew, int nBlockHeight)"
.br
.ti -1c
.RI "std::string \fBGetRequiredPaymentsString\fP (int nBlockHeight)"
.br
.ti -1c
.RI "bool \fBIsBlockValueValid\fP (const \fBCBlock\fP &\fBblock\fP, \fBCAmount\fP nExpectedValue)"
.br
.ti -1c
.RI "void \fBFillBlockPayee\fP (\fBCTransaction\fP &txNew, \fBCAmount\fP nFees)"
.br
.ti -1c
.RI "void \fBDumpStormnodePayments\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_vecPayments\fP"
.br
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_mapStormnodeBlocks\fP"
.br
.ti -1c
.RI "\fBCCriticalSection\fP \fBcs_mapStormnodePayeeVotes\fP"
.br
.ti -1c
.RI "\fBCStormnodePayments\fP \fBstormnodePayments\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SNPAYMENTS_SIGNATURES_REQUIRED   10"

.PP
Definition at line 25 of file stormnode-payments\&.h\&.
.SS "#define SNPAYMENTS_SIGNATURES_TOTAL   15"

.PP
Definition at line 26 of file stormnode-payments\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void DumpStormnodePayments ()"

.PP
Definition at line 156 of file stormnode-payments\&.cpp\&.
.SS "void FillBlockPayee (\fBCTransaction\fP & txNew, \fBCAmount\fP nFees)"

.PP
Definition at line 272 of file stormnode-payments\&.cpp\&.
.SS "std::string GetRequiredPaymentsString (int nBlockHeight)"

.PP
Definition at line 284 of file stormnode-payments\&.cpp\&.
.SS "bool IsBlockPayeeValid (const \fBCTransaction\fP & txNew, int nBlockHeight)"

.PP
Definition at line 230 of file stormnode-payments\&.cpp\&.
.SS "bool IsBlockValueValid (const \fBCBlock\fP & block, \fBCAmount\fP nExpectedValue)"

.PP
Definition at line 185 of file stormnode-payments\&.cpp\&.
.SS "bool IsReferenceNode (\fBCTxIn\fP & vin)"

.PP
Definition at line 634 of file stormnode-payments\&.cpp\&.
.SS "void ProcessMessageStormnodePayments (\fBCNode\fP * pfrom, std::string & strCommand, \fBCDataStream\fP & vRecv)"

.SH "Variable Documentation"
.PP 
.SS "\fBCCriticalSection\fP cs_mapStormnodeBlocks"

.PP
Definition at line 21 of file stormnode-payments\&.cpp\&.
.SS "\fBCCriticalSection\fP cs_mapStormnodePayeeVotes"

.PP
Definition at line 22 of file stormnode-payments\&.cpp\&.
.SS "\fBCCriticalSection\fP cs_vecPayments"

.PP
Definition at line 20 of file stormnode-payments\&.cpp\&.
.SS "\fBCStormnodePayments\fP stormnodePayments"
Object for who's going to get paid on which blocks 
.PP
Definition at line 18 of file stormnode-payments\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
