.TH "/home/dev/ds-160209/src/stormnodeman.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/stormnodeman.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sync\&.h'\fP
.br
\fC#include 'net\&.h'\fP
.br
\fC#include 'key\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'base58\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'stormnode\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCStormnodeDB\fP"
.br
.ti -1c
.RI "class \fBCStormnodeMan\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBDumpStormnodes\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCStormnodeMan\fP \fBsnodeman\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void DumpStormnodes ()"

.PP
Definition at line 178 of file stormnodeman\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBCStormnodeMan\fP snodeman"
Stormnode manager 
.PP
Definition at line 18 of file stormnodeman\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
