.TH "StormnodeManager" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StormnodeManager \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stormnodemanager\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBupdateNodeList\fP ()"
.br
.ti -1c
.RI "void \fBupdateStormNode\fP (QString alias, QString addr, QString privkey, QString txHash, QString txIndex, QString status)"
.br
.ti -1c
.RI "void \fBon_UpdateButton_clicked\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStormnodeManager\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~StormnodeManager\fP ()"
.br
.ti -1c
.RI "void \fBsetClientModel\fP (\fBClientModel\fP *clientModel)"
.br
.ti -1c
.RI "void \fBsetWalletModel\fP (\fBWalletModel\fP *walletModel)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stormnode Manager page widget 
.PP
Definition at line 22 of file stormnodemanager\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StormnodeManager::StormnodeManager (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 36 of file stormnodemanager\&.cpp\&.
.SS "StormnodeManager::~StormnodeManager ()"

.PP
Definition at line 57 of file stormnodemanager\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void StormnodeManager::on_UpdateButton_clicked ()\fC [slot]\fP"

.PP
Definition at line 247 of file stormnodemanager\&.cpp\&.
.SS "void StormnodeManager::setClientModel (\fBClientModel\fP * clientModel)"

.PP
Definition at line 143 of file stormnodemanager\&.cpp\&.
.SS "void StormnodeManager::setWalletModel (\fBWalletModel\fP * walletModel)"

.PP
Definition at line 151 of file stormnodemanager\&.cpp\&.
.SS "void StormnodeManager::updateNodeList ()\fC [slot]\fP"

.PP
Definition at line 98 of file stormnodemanager\&.cpp\&.
.SS "void StormnodeManager::updateStormNode (QString alias, QString addr, QString privkey, QString txHash, QString txIndex, QString status)\fC [slot]\fP"

.PP
Definition at line 71 of file stormnodemanager\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
