.TH "/home/dev/ds-160209/src/stormnode.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/stormnode.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sync\&.h'\fP
.br
\fC#include 'net\&.h'\fP
.br
\fC#include 'key\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'base58\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'timedata\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCStormnodePing\fP"
.br
.ti -1c
.RI "class \fBCStormnode\fP"
.br
.ti -1c
.RI "class \fBCStormnodeBroadcast\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBGetBlockHash\fP (\fBuint256\fP &\fBhash\fP, int nBlockHeight)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "map< \fBint64_t\fP, \fBuint256\fP > \fBmapCacheBlockHashes\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool GetBlockHash (\fBuint256\fP & hash, int nBlockHeight)"

.PP
Definition at line 22 of file stormnode\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "map<\fBint64_t\fP, \fBuint256\fP> mapCacheBlockHashes"

.PP
Definition at line 19 of file stormnode\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
