.TH "/home/dev/ds-160209/src/stormnodeman.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/stormnodeman.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'stormnodeman\&.h'\fP
.br
\fC#include 'activestormnode\&.h'\fP
.br
\fC#include 'sandstorm\&.h'\fP
.br
\fC#include 'stormnode\&.h'\fP
.br
\fC#include 'stormnode-payments\&.h'\fP
.br
\fC#include 'stormnode-sync\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'addrman\&.h'\fP
.br
\fC#include 'spork\&.h'\fP
.br
\fC#include <boost/lexical_cast\&.hpp>\fP
.br
\fC#include <boost/filesystem\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCompareLastPaid\fP"
.br
.ti -1c
.RI "struct \fBCompareScoreTxIn\fP"
.br
.ti -1c
.RI "struct \fBCompareScoreSN\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBDumpStormnodes\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCStormnodeMan\fP \fBsnodeman\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void DumpStormnodes ()"

.PP
Definition at line 178 of file stormnodeman\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "\fBCStormnodeMan\fP snodeman"
Stormnode manager 
.PP
Definition at line 18 of file stormnodeman\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
