.TH "/home/dev/ds-160209/src/stormnodeconfig.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/stormnodeconfig.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'net\&.h'\fP
.br
\fC#include 'stormnodeconfig\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include <base58\&.h>\fP
.br
\fC#include <boost/filesystem\&.hpp>\fP
.br
\fC#include <boost/filesystem/fstream\&.hpp>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCStormnodeConfig\fP \fBstormnodeConfig\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBCStormnodeConfig\fP stormnodeConfig"

.PP
Definition at line 14 of file stormnodeconfig\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
