.TH "/home/dev/ds-160209/src/strlcpy.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/strlcpy.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBstrlcpy\fP (char *dst, const char *src, size_t siz)"
.br
.ti -1c
.RI "size_t \fBstrlcat\fP (char *dst, const char *src, size_t siz)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "size_t strlcat (char * dst, const char * src, size_t siz)\fC [inline]\fP"

.PP
Definition at line 62 of file strlcpy\&.h\&.
.SS "size_t strlcpy (char * dst, const char * src, size_t siz)\fC [inline]\fP"

.PP
Definition at line 27 of file strlcpy\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
