.TH "tallyitem" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tallyitem \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtallyitem\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCAmount\fP \fBnAmount\fP"
.br
.ti -1c
.RI "int \fBnConf\fP"
.br
.ti -1c
.RI "int \fBnBCConf\fP"
.br
.ti -1c
.RI "vector< \fBuint256\fP > \fBtxids\fP"
.br
.ti -1c
.RI "bool \fBfIsWatchonly\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1207 of file rpcwallet\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tallyitem::tallyitem ()\fC [inline]\fP"

.PP
Definition at line 1214 of file rpcwallet\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "bool tallyitem::fIsWatchonly"

.PP
Definition at line 1213 of file rpcwallet\&.cpp\&.
.SS "\fBCAmount\fP tallyitem::nAmount"

.PP
Definition at line 1209 of file rpcwallet\&.cpp\&.
.SS "int tallyitem::nBCConf"

.PP
Definition at line 1211 of file rpcwallet\&.cpp\&.
.SS "int tallyitem::nConf"

.PP
Definition at line 1210 of file rpcwallet\&.cpp\&.
.SS "vector<\fBuint256\fP> tallyitem::txids"

.PP
Definition at line 1212 of file rpcwallet\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
