.TH "/home/dev/ds-160209/src/qt/test/test_main.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/test/test_main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QTest>\fP
.br
\fC#include <QObject>\fP
.br
\fC#include 'uritests\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 7 of file test_main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
