.TH "/home/dev/ds-160209/src/secp256k1/src/modules/schnorr/tests_impl.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/secp256k1/src/modules/schnorr/tests_impl.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'include/secp256k1_schnorr\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_schnorr_end_to_end\fP (void)"
.br
.ti -1c
.RI "void \fBtest_schnorr_hash\fP (unsigned char *h32, const unsigned char *r32, const unsigned char *msg32)"
.br
.ti -1c
.RI "void \fBtest_schnorr_sign_verify\fP (void)"
.br
.ti -1c
.RI "void \fBtest_schnorr_threshold\fP (void)"
.br
.ti -1c
.RI "void \fBtest_schnorr_recovery\fP (void)"
.br
.ti -1c
.RI "void \fBrun_schnorr_tests\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void run_schnorr_tests (void)"

.PP
Definition at line 159 of file tests_impl\&.h\&.
.SS "void test_schnorr_end_to_end (void)"

.PP
Definition at line 12 of file tests_impl\&.h\&.
.SS "void test_schnorr_hash (unsigned char * h32, const unsigned char * r32, const unsigned char * msg32)"
Horribly broken hash function\&. Do not use for anything but tests\&. 
.PP
Definition at line 43 of file tests_impl\&.h\&.
.SS "void test_schnorr_recovery (void)"

.PP
Definition at line 146 of file tests_impl\&.h\&.
.SS "void test_schnorr_sign_verify (void)"

.PP
Definition at line 50 of file tests_impl\&.h\&.
.SS "void test_schnorr_threshold (void)"

.PP
Definition at line 85 of file tests_impl\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
