.TH "testvec_t" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testvec_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBpszKey\fP"
.br
.ti -1c
.RI "const char * \fBpszData\fP"
.br
.ti -1c
.RI "const char * \fBpszMAC\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file hmac_tests\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "const char* testvec_t::pszData"

.PP
Definition at line 12 of file hmac_tests\&.cpp\&.
.SS "const char* testvec_t::pszKey"

.PP
Definition at line 11 of file hmac_tests\&.cpp\&.
.SS "const char* testvec_t::pszMAC"

.PP
Definition at line 13 of file hmac_tests\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
