.TH "TestAddrTypeVisitor" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestAddrTypeVisitor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< bool >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestAddrTypeVisitor\fP (const std::string &exp_addrType)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCKeyID\fP &\fBid\fP) const "
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCScriptID\fP &\fBid\fP) const "
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCNoDestination\fP &no) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 61 of file base58_tests\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TestAddrTypeVisitor::TestAddrTypeVisitor (const std::string & exp_addrType)\fC [inline]\fP"

.PP
Definition at line 66 of file base58_tests\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool TestAddrTypeVisitor::operator() (const \fBCKeyID\fP & id) const\fC [inline]\fP"

.PP
Definition at line 67 of file base58_tests\&.cpp\&.
.SS "bool TestAddrTypeVisitor::operator() (const \fBCScriptID\fP & id) const\fC [inline]\fP"

.PP
Definition at line 71 of file base58_tests\&.cpp\&.
.SS "bool TestAddrTypeVisitor::operator() (const \fBCNoDestination\fP & no) const\fC [inline]\fP"

.PP
Definition at line 75 of file base58_tests\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
