.TH "TestPayloadVisitor" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestPayloadVisitor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< bool >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestPayloadVisitor\fP (std::vector< unsigned char > &exp_payload)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCKeyID\fP &\fBid\fP) const "
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCScriptID\fP &\fBid\fP) const "
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBCNoDestination\fP &no) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 82 of file base58_tests\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TestPayloadVisitor::TestPayloadVisitor (std::vector< unsigned char > & exp_payload)\fC [inline]\fP"

.PP
Definition at line 87 of file base58_tests\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool TestPayloadVisitor::operator() (const \fBCKeyID\fP & id) const\fC [inline]\fP"

.PP
Definition at line 88 of file base58_tests\&.cpp\&.
.SS "bool TestPayloadVisitor::operator() (const \fBCScriptID\fP & id) const\fC [inline]\fP"

.PP
Definition at line 93 of file base58_tests\&.cpp\&.
.SS "bool TestPayloadVisitor::operator() (const \fBCNoDestination\fP & no) const\fC [inline]\fP"

.PP
Definition at line 98 of file base58_tests\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
