.TH "/home/dev/ds-160209/src/leveldb/util/testharness.cc" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/util/testharness.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'util/testharness\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.ti -1c
.RI " \fBleveldb::test\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBleveldb::test::RegisterTest\fP (const char *\fBbase\fP, const char *\fBname\fP, void(*\fBfunc\fP)())"
.br
.ti -1c
.RI "int \fBleveldb::test::RunAllTests\fP ()"
.br
.ti -1c
.RI "std::string \fBleveldb::test::TmpDir\fP ()"
.br
.ti -1c
.RI "int \fBleveldb::test::RandomSeed\fP ()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char* base"

.PP
Definition at line 17 of file testharness\&.cc\&.
.SS "void(* func) ()"

.PP
Definition at line 19 of file testharness\&.cc\&.
.SS "const char* name"

.PP
Definition at line 18 of file testharness\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
