.TH "/home/dev/ds-160209/src/leveldb/port/thread_annotations.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/port/thread_annotations.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEXCLUSIVE_LOCKS_REQUIRED\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBSHARED_LOCKS_REQUIRED\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBLOCKS_EXCLUDED\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBLOCK_RETURNED\fP(x)"
.br
.ti -1c
.RI "#define \fBLOCKABLE\fP"
.br
.ti -1c
.RI "#define \fBSCOPED_LOCKABLE\fP"
.br
.ti -1c
.RI "#define \fBEXCLUSIVE_LOCK_FUNCTION\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBSHARED_LOCK_FUNCTION\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBEXCLUSIVE_TRYLOCK_FUNCTION\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBSHARED_TRYLOCK_FUNCTION\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBUNLOCK_FUNCTION\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBNO_THREAD_SAFETY_ANALYSIS\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define EXCLUSIVE_LOCK_FUNCTION( \&.\&.\&.)"

.PP
Definition at line 37 of file thread_annotations\&.h\&.
.SS "#define EXCLUSIVE_LOCKS_REQUIRED( \&.\&.\&.)"

.PP
Definition at line 13 of file thread_annotations\&.h\&.
.SS "#define EXCLUSIVE_TRYLOCK_FUNCTION( \&.\&.\&.)"

.PP
Definition at line 45 of file thread_annotations\&.h\&.
.SS "#define LOCK_RETURNED(x)"

.PP
Definition at line 25 of file thread_annotations\&.h\&.
.SS "#define LOCKABLE"

.PP
Definition at line 29 of file thread_annotations\&.h\&.
.SS "#define LOCKS_EXCLUDED( \&.\&.\&.)"

.PP
Definition at line 21 of file thread_annotations\&.h\&.
.SS "#define NO_THREAD_SAFETY_ANALYSIS"

.PP
Definition at line 57 of file thread_annotations\&.h\&.
.SS "#define SCOPED_LOCKABLE"

.PP
Definition at line 33 of file thread_annotations\&.h\&.
.SS "#define SHARED_LOCK_FUNCTION( \&.\&.\&.)"

.PP
Definition at line 41 of file thread_annotations\&.h\&.
.SS "#define SHARED_LOCKS_REQUIRED( \&.\&.\&.)"

.PP
Definition at line 17 of file thread_annotations\&.h\&.
.SS "#define SHARED_TRYLOCK_FUNCTION( \&.\&.\&.)"

.PP
Definition at line 49 of file thread_annotations\&.h\&.
.SS "#define UNLOCK_FUNCTION( \&.\&.\&.)"

.PP
Definition at line 53 of file thread_annotations\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
