.TH "/home/dev/ds-160209/src/crypto/argon2/thread.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/crypto/argon2/thread.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <pthread\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void *(* \fBargon2_thread_func_t\fP) (void *)"
.br
.ti -1c
.RI "typedef pthread_t \fBargon2_thread_handle_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBargon2_thread_create\fP (\fBargon2_thread_handle_t\fP *handle, \fBargon2_thread_func_t\fP \fBfunc\fP, void *args)"
.br
.ti -1c
.RI "int \fBargon2_thread_join\fP (\fBargon2_thread_handle_t\fP handle)"
.br
.ti -1c
.RI "void \fBargon2_thread_exit\fP (void)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void*(* argon2_thread_func_t) (void *)"

.PP
Definition at line 19 of file thread\&.h\&.
.SS "typedef pthread_t \fBargon2_thread_handle_t\fP"

.PP
Definition at line 20 of file thread\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int argon2_thread_create (\fBargon2_thread_handle_t\fP * handle, \fBargon2_thread_func_t\fP func, void * args)"

.PP
Definition at line 6 of file thread\&.c\&.
.SS "void argon2_thread_exit (void)"

.PP
Definition at line 30 of file thread\&.c\&.
.SS "int argon2_thread_join (\fBargon2_thread_handle_t\fP handle)"

.PP
Definition at line 19 of file thread\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
