.TH "/home/dev/ds-160209/src/threadsafety.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/threadsafety.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOCKABLE\fP"
.br
.ti -1c
.RI "#define \fBSCOPED_LOCKABLE\fP"
.br
.ti -1c
.RI "#define \fBGUARDED_BY\fP(x)"
.br
.ti -1c
.RI "#define \fBGUARDED_VAR\fP"
.br
.ti -1c
.RI "#define \fBPT_GUARDED_BY\fP(x)"
.br
.ti -1c
.RI "#define \fBPT_GUARDED_VAR\fP"
.br
.ti -1c
.RI "#define \fBACQUIRED_AFTER\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBACQUIRED_BEFORE\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBEXCLUSIVE_LOCK_FUNCTION\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBSHARED_LOCK_FUNCTION\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBEXCLUSIVE_TRYLOCK_FUNCTION\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBSHARED_TRYLOCK_FUNCTION\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBUNLOCK_FUNCTION\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBLOCK_RETURNED\fP(x)"
.br
.ti -1c
.RI "#define \fBLOCKS_EXCLUDED\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBEXCLUSIVE_LOCKS_REQUIRED\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBSHARED_LOCKS_REQUIRED\fP(\&.\&.\&.)"
.br
.ti -1c
.RI "#define \fBNO_THREAD_SAFETY_ANALYSIS\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ACQUIRED_AFTER( \&.\&.\&.)"

.PP
Definition at line 42 of file threadsafety\&.h\&.
.SS "#define ACQUIRED_BEFORE( \&.\&.\&.)"

.PP
Definition at line 43 of file threadsafety\&.h\&.
.SS "#define EXCLUSIVE_LOCK_FUNCTION( \&.\&.\&.)"

.PP
Definition at line 44 of file threadsafety\&.h\&.
.SS "#define EXCLUSIVE_LOCKS_REQUIRED( \&.\&.\&.)"

.PP
Definition at line 51 of file threadsafety\&.h\&.
.SS "#define EXCLUSIVE_TRYLOCK_FUNCTION( \&.\&.\&.)"

.PP
Definition at line 46 of file threadsafety\&.h\&.
.SS "#define GUARDED_BY(x)"

.PP
Definition at line 38 of file threadsafety\&.h\&.
.SS "#define GUARDED_VAR"

.PP
Definition at line 39 of file threadsafety\&.h\&.
.SS "#define LOCK_RETURNED(x)"

.PP
Definition at line 49 of file threadsafety\&.h\&.
.SS "#define LOCKABLE"

.PP
Definition at line 36 of file threadsafety\&.h\&.
.SS "#define LOCKS_EXCLUDED( \&.\&.\&.)"

.PP
Definition at line 50 of file threadsafety\&.h\&.
.SS "#define NO_THREAD_SAFETY_ANALYSIS"

.PP
Definition at line 53 of file threadsafety\&.h\&.
.SS "#define PT_GUARDED_BY(x)"

.PP
Definition at line 40 of file threadsafety\&.h\&.
.SS "#define PT_GUARDED_VAR"

.PP
Definition at line 41 of file threadsafety\&.h\&.
.SS "#define SCOPED_LOCKABLE"

.PP
Definition at line 37 of file threadsafety\&.h\&.
.SS "#define SHARED_LOCK_FUNCTION( \&.\&.\&.)"

.PP
Definition at line 45 of file threadsafety\&.h\&.
.SS "#define SHARED_LOCKS_REQUIRED( \&.\&.\&.)"

.PP
Definition at line 52 of file threadsafety\&.h\&.
.SS "#define SHARED_TRYLOCK_FUNCTION( \&.\&.\&.)"

.PP
Definition at line 47 of file threadsafety\&.h\&.
.SS "#define UNLOCK_FUNCTION( \&.\&.\&.)"

.PP
Definition at line 48 of file threadsafety\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
