.TH "/home/dev/ds-160209/src/timedata.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/timedata.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint64_t\fP \fBGetTimeOffset\fP ()"
.br
.ti -1c
.RI "\fBint64_t\fP \fBGetAdjustedTime\fP ()"
.br
.ti -1c
.RI "void \fBAddTimeData\fP (const \fBCNetAddr\fP &ip, \fBint64_t\fP nTime)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void AddTimeData (const \fBCNetAddr\fP & ip, \fBint64_t\fP nTime)"

.PP
Definition at line 40 of file timedata\&.cpp\&.
.SS "\fBint64_t\fP GetAdjustedTime ()"

.PP
Definition at line 33 of file timedata\&.cpp\&.
.SS "\fBint64_t\fP GetTimeOffset ()"

.PP
Definition at line 27 of file timedata\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
