.TH "/home/dev/ds-160209/src/timedata.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/timedata.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'timedata\&.h'\fP
.br
\fC#include 'netbase\&.h'\fP
.br
\fC#include 'sync\&.h'\fP
.br
\fC#include 'ui_interface\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include <boost/foreach\&.hpp>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDARKSILK_TIMEDATA_MAX_SAMPLES\fP   200"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint64_t\fP \fBGetTimeOffset\fP ()"
.br
.ti -1c
.RI "\fBint64_t\fP \fBGetAdjustedTime\fP ()"
.br
.ti -1c
.RI "void \fBAddTimeData\fP (const \fBCNetAddr\fP &ip, \fBint64_t\fP nOffsetSample)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DARKSILK_TIMEDATA_MAX_SAMPLES   200"

.PP
Definition at line 38 of file timedata\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "void AddTimeData (const \fBCNetAddr\fP & ip, \fBint64_t\fP nOffsetSample)"

.PP
Definition at line 40 of file timedata\&.cpp\&.
.SS "\fBint64_t\fP GetAdjustedTime ()"

.PP
Definition at line 33 of file timedata\&.cpp\&.
.SS "\fBint64_t\fP GetTimeOffset ()"

.PP
Definition at line 27 of file timedata\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
