.TH "tinyformat::detail::is_wchar< const wchar_t * >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinyformat::detail::is_wchar< const wchar_t * > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tinyformat\&.h>\fP
.SH "Detailed Description"
.PP 

.SS "template<>struct tinyformat::detail::is_wchar< const wchar_t * >"

.PP
Definition at line 189 of file tinyformat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
