.TH "tinyformat::detail::formatValueAsType< T, fmtT, convertible >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinyformat::detail::formatValueAsType< T, fmtT, convertible > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tinyformat\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinvoke\fP (std::ostream &, const T &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename fmtT, bool convertible = is_convertible<T, fmtT>::value>struct tinyformat::detail::formatValueAsType< T, fmtT, convertible >"

.PP
Definition at line 197 of file tinyformat\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T , typename fmtT , bool convertible = is_convertible<T, fmtT>::value> static void \fBtinyformat::detail::formatValueAsType\fP< T, fmtT, convertible >::invoke (std::ostream &, const T &)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 199 of file tinyformat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
