.TH "tinyformat" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinyformat \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdetail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > void \fBformatValue\fP (std::ostream &out, const char *, const char *fmtEnd, const T &\fBvalue\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T > void tinyformat::formatValue (std::ostream & out, const char *, const char * fmtEnd, const T & value)\fC [inline]\fP"

.PP
Definition at line 268 of file tinyformat\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
