.TH "tinyformat::detail::formatValueAsType< T, fmtT, true >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinyformat::detail::formatValueAsType< T, fmtT, true > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tinyformat\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinvoke\fP (std::ostream &out, const T &\fBvalue\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename fmtT>struct tinyformat::detail::formatValueAsType< T, fmtT, true >"

.PP
Definition at line 204 of file tinyformat\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T , typename fmtT > static void \fBtinyformat::detail::formatValueAsType\fP< T, fmtT, true >::invoke (std::ostream & out, const T & value)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 206 of file tinyformat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
