.TH "tinyformat::detail::is_wchar< T >" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinyformat::detail::is_wchar< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tinyformat\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef int \fBtinyformat_wchar_is_not_supported\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>struct tinyformat::detail::is_wchar< T >"

.PP
Definition at line 187 of file tinyformat\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T> typedef int \fBtinyformat::detail::is_wchar\fP< T >::\fBtinyformat_wchar_is_not_supported\fP"

.PP
Definition at line 187 of file tinyformat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
