.TH "tinyformat::detail::is_wchar< wchar_t[n]>" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinyformat::detail::is_wchar< wchar_t[n]> \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tinyformat\&.h>\fP
.SH "Detailed Description"
.PP 

.SS "template<int n>struct tinyformat::detail::is_wchar< wchar_t[n]>"

.PP
Definition at line 191 of file tinyformat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
