.TH "TrafficGraphWidget" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TrafficGraphWidget \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <trafficgraphwidget\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBupdateRates\fP ()"
.br
.ti -1c
.RI "void \fBsetGraphRangeMins\fP (int mins)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTrafficGraphWidget\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetClientModel\fP (\fBClientModel\fP *model)"
.br
.ti -1c
.RI "int \fBgetGraphRangeMins\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file trafficgraphwidget\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TrafficGraphWidget::TrafficGraphWidget (QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 15 of file trafficgraphwidget\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void TrafficGraphWidget::clear ()\fC [slot]\fP"

.PP
Definition at line 156 of file trafficgraphwidget\&.cpp\&.
.SS "int TrafficGraphWidget::getGraphRangeMins () const"

.PP
Definition at line 39 of file trafficgraphwidget\&.cpp\&.
.SS "void TrafficGraphWidget::paintEvent (QPaintEvent *)\fC [protected]\fP"

.PP
Definition at line 59 of file trafficgraphwidget\&.cpp\&.
.SS "void TrafficGraphWidget::setClientModel (\fBClientModel\fP * model)"

.PP
Definition at line 30 of file trafficgraphwidget\&.cpp\&.
.SS "void TrafficGraphWidget::setGraphRangeMins (int mins)\fC [slot]\fP"

.PP
Definition at line 146 of file trafficgraphwidget\&.cpp\&.
.SS "void TrafficGraphWidget::updateRates ()\fC [slot]\fP"

.PP
Definition at line 115 of file trafficgraphwidget\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
