.TH "/home/dev/ds-160209/src/qt/trafficgraphwidget.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/trafficgraphwidget.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'trafficgraphwidget\&.h'\fP
.br
\fC#include 'clientmodel\&.h'\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QColor>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <cmath>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDESIRED_SAMPLES\fP   800"
.br
.ti -1c
.RI "#define \fBXMARGIN\fP   10"
.br
.ti -1c
.RI "#define \fBYMARGIN\fP   10"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DESIRED_SAMPLES   800"

.PP
Definition at line 10 of file trafficgraphwidget\&.cpp\&.
.SS "#define XMARGIN   10"

.PP
Definition at line 12 of file trafficgraphwidget\&.cpp\&.
.SS "#define YMARGIN   10"

.PP
Definition at line 13 of file trafficgraphwidget\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
