.TH "TransactionTablePriv" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransactionTablePriv \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransactionTablePriv\fP (\fBCWallet\fP *\fBwallet\fP, \fBTransactionTableModel\fP *\fBparent\fP)"
.br
.ti -1c
.RI "void \fBrefreshWallet\fP ()"
.br
.ti -1c
.RI "void \fBupdateWallet\fP (const \fBuint256\fP &\fBhash\fP, int status)"
.br
.ti -1c
.RI "int \fBsize\fP ()"
.br
.ti -1c
.RI "\fBTransactionRecord\fP * \fBindex\fP (int idx)"
.br
.ti -1c
.RI "QString \fBdescribe\fP (\fBTransactionRecord\fP *rec, int unit)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCWallet\fP * \fBwallet\fP"
.br
.ti -1c
.RI "\fBTransactionTableModel\fP * \fBparent\fP"
.br
.ti -1c
.RI "QList< \fBTransactionRecord\fP > \fBcachedWallet\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file transactiontablemodel\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TransactionTablePriv::TransactionTablePriv (\fBCWallet\fP * wallet, \fBTransactionTableModel\fP * parent)\fC [inline]\fP"

.PP
Definition at line 51 of file transactiontablemodel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QString TransactionTablePriv::describe (\fBTransactionRecord\fP * rec, int unit)\fC [inline]\fP"

.PP
Definition at line 211 of file transactiontablemodel\&.cpp\&.
.SS "\fBTransactionRecord\fP* TransactionTablePriv::index (int idx)\fC [inline]\fP"

.PP
Definition at line 176 of file transactiontablemodel\&.cpp\&.
.SS "void TransactionTablePriv::refreshWallet ()\fC [inline]\fP"

.PP
Definition at line 68 of file transactiontablemodel\&.cpp\&.
.SS "int TransactionTablePriv::size ()\fC [inline]\fP"

.PP
Definition at line 171 of file transactiontablemodel\&.cpp\&.
.SS "void TransactionTablePriv::updateWallet (const \fBuint256\fP & hash, int status)\fC [inline]\fP"

.PP
Definition at line 87 of file transactiontablemodel\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QList<\fBTransactionRecord\fP> TransactionTablePriv::cachedWallet"

.PP
Definition at line 64 of file transactiontablemodel\&.cpp\&.
.SS "\fBTransactionTableModel\fP* TransactionTablePriv::parent"

.PP
Definition at line 58 of file transactiontablemodel\&.cpp\&.
.SS "\fBCWallet\fP* TransactionTablePriv::wallet"

.PP
Definition at line 57 of file transactiontablemodel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
