.TH "/home/dev/ds-160209/src/primitives/transaction.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/primitives/transaction.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'amount\&.h'\fP
.br
\fC#include 'uint256\&.h'\fP
.br
\fC#include 'serialize\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'script\&.h'\fP
.br
\fC#include 'timedata\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCOutPoint\fP"
.br
.RI "\fIAn outpoint - a combination of a transaction hash and an index n into its vout\&. \fP"
.ti -1c
.RI "class \fBCInPoint\fP"
.br
.RI "\fIAn inpoint - a combination of a transaction and an index n into its vin\&. \fP"
.ti -1c
.RI "class \fBCTxIn\fP"
.br
.ti -1c
.RI "class \fBCTxOut\fP"
.br
.ti -1c
.RI "class \fBCTransaction\fP"
.br
.ti -1c
.RI "struct \fBCMutableTransaction\fP"
.br
.RI "\fIA mutable version of \fBCTransaction\fP\&. \fP"
.ti -1c
.RI "class \fBTransactionSignatureChecker\fP"
.br
.ti -1c
.RI "class \fBMutableTransactionSignatureChecker\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
