.TH "/home/dev/ds-160209/src/qt/transactionview.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/transactionview.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'transactionview\&.h'\fP
.br
\fC#include 'transactionfilterproxy\&.h'\fP
.br
\fC#include 'transactionrecord\&.h'\fP
.br
\fC#include 'walletmodel\&.h'\fP
.br
\fC#include 'addresstablemodel\&.h'\fP
.br
\fC#include 'transactiontablemodel\&.h'\fP
.br
\fC#include 'darksilkunits\&.h'\fP
.br
\fC#include 'csvmodelwriter\&.h'\fP
.br
\fC#include 'transactiondescdialog\&.h'\fP
.br
\fC#include 'editaddressdialog\&.h'\fP
.br
\fC#include 'optionsmodel\&.h'\fP
.br
\fC#include 'guiutil\&.h'\fP
.br
\fC#include <QScrollBar>\fP
.br
\fC#include <QComboBox>\fP
.br
\fC#include <QDoubleValidator>\fP
.br
\fC#include <QHBoxLayout>\fP
.br
\fC#include <QVBoxLayout>\fP
.br
\fC#include <QLineEdit>\fP
.br
\fC#include <QTableView>\fP
.br
\fC#include <QHeaderView>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QPoint>\fP
.br
\fC#include <QMenu>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QDateTimeEdit>\fP
.br
\fC#include <QStyledItemDelegate>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
