.TH "TransactionTableModel" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransactionTableModel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transactiontablemodel\&.h>\fP
.PP
Inherits QAbstractTableModel\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBColumnIndex\fP { \fBStatus\fP = 0, \fBDate\fP = 1, \fBType\fP = 2, \fBToAddress\fP = 3, \fBAmount\fP = 4 }"
.br
.ti -1c
.RI "enum \fBRoleIndex\fP { \fBTypeRole\fP = Qt::UserRole, \fBDateRole\fP, \fBLongDescriptionRole\fP, \fBAddressRole\fP, \fBLabelRole\fP, \fBAmountRole\fP, \fBTxIDRole\fP, \fBConfirmedRole\fP, \fBFormattedAmountRole\fP, \fBStatusRole\fP }"
.br
.in -1c
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBupdateTransaction\fP (const QString &\fBhash\fP, int status)"
.br
.ti -1c
.RI "void \fBupdateConfirmations\fP ()"
.br
.ti -1c
.RI "void \fBupdateDisplayUnit\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransactionTableModel\fP (\fBCWallet\fP *wallet, \fBWalletModel\fP *parent=0)"
.br
.ti -1c
.RI "\fB~TransactionTableModel\fP ()"
.br
.ti -1c
.RI "int \fBrowCount\fP (const QModelIndex &parent) const "
.br
.ti -1c
.RI "int \fBcolumnCount\fP (const QModelIndex &parent) const "
.br
.ti -1c
.RI "QVariant \fBdata\fP (const QModelIndex &\fBindex\fP, int role) const "
.br
.ti -1c
.RI "QVariant \fBheaderData\fP (int section, Qt::Orientation orientation, int role) const "
.br
.ti -1c
.RI "QModelIndex \fBindex\fP (int row, int column, const QModelIndex &parent=QModelIndex()) const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTransactionTablePriv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
UI model for the transaction table of a wallet\&. 
.PP
Definition at line 14 of file transactiontablemodel\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBTransactionTableModel::ColumnIndex\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIStatus \fP\fP
.TP
\fB\fIDate \fP\fP
.TP
\fB\fIType \fP\fP
.TP
\fB\fIToAddress \fP\fP
.TP
\fB\fIAmount \fP\fP
.PP
Definition at line 22 of file transactiontablemodel\&.h\&.
.SS "enum \fBTransactionTableModel::RoleIndex\fP"
Roles to get specific information from a transaction row\&. These are independent of colusn\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITypeRole \fP\fP
Type of transaction 
.TP
\fB\fIDateRole \fP\fP
Date and time this transaction was created 
.TP
\fB\fILongDescriptionRole \fP\fP
Long description (HTML format) 
.TP
\fB\fIAddressRole \fP\fP
Address of transaction 
.TP
\fB\fILabelRole \fP\fP
Label of address related to transaction 
.TP
\fB\fIAmountRole \fP\fP
Net amount of transaction 
.TP
\fB\fITxIDRole \fP\fP
Unique identifier 
.TP
\fB\fIConfirmedRole \fP\fP
Is transaction confirmed? 
.TP
\fB\fIFormattedAmountRole \fP\fP
Formatted amount, without brackets when unconfirmed 
.TP
\fB\fIStatusRole \fP\fP
Transaction status (TransactionRecord::Status) 
.PP
Definition at line 33 of file transactiontablemodel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TransactionTableModel::TransactionTableModel (\fBCWallet\fP * wallet, \fBWalletModel\fP * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 225 of file transactiontablemodel\&.cpp\&.
.SS "TransactionTableModel::~TransactionTableModel ()"

.PP
Definition at line 238 of file transactiontablemodel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int TransactionTableModel::columnCount (const QModelIndex & parent) const"

.PP
Definition at line 267 of file transactiontablemodel\&.cpp\&.
.SS "QVariant TransactionTableModel::data (const QModelIndex & index, int role) const"

.PP
Definition at line 481 of file transactiontablemodel\&.cpp\&.
.SS "QVariant TransactionTableModel::headerData (int section, Qt::Orientation orientation, int role) const"

.PP
Definition at line 574 of file transactiontablemodel\&.cpp\&.
.SS "QModelIndex TransactionTableModel::index (int row, int column, const QModelIndex & parent = \fCQModelIndex()\fP) const"

.PP
Definition at line 605 of file transactiontablemodel\&.cpp\&.
.SS "int TransactionTableModel::rowCount (const QModelIndex & parent) const"

.PP
Definition at line 261 of file transactiontablemodel\&.cpp\&.
.SS "void TransactionTableModel::updateConfirmations ()\fC [slot]\fP"

.PP
Definition at line 251 of file transactiontablemodel\&.cpp\&.
.SS "void TransactionTableModel::updateDisplayUnit ()\fC [slot]\fP"

.PP
Definition at line 619 of file transactiontablemodel\&.cpp\&.
.SS "void TransactionTableModel::updateTransaction (const QString & hash, int status)\fC [slot]\fP"

.PP
Definition at line 243 of file transactiontablemodel\&.cpp\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBTransactionTablePriv\fP\fC [friend]\fP"

.PP
Definition at line 84 of file transactiontablemodel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
