.TH "TransactionDescDialog" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransactionDescDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transactiondescdialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransactionDescDialog\fP (const QModelIndex &idx, QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~TransactionDescDialog\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Dialog showing transaction details\&. 
.PP
Definition at line 15 of file transactiondescdialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TransactionDescDialog::TransactionDescDialog (const QModelIndex & idx, QWidget * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line 8 of file transactiondescdialog\&.cpp\&.
.SS "TransactionDescDialog::~TransactionDescDialog ()"

.PP
Definition at line 17 of file transactiondescdialog\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
