.TH "TransactionDesc" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransactionDesc \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <transactiondesc\&.h>\fP
.PP
Inherits QObject\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static QString \fBtoHTML\fP (\fBCWallet\fP *wallet, \fBCWalletTx\fP &wtx, \fBTransactionRecord\fP *rec, int unit)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provide a human-readable extended HTML description of a transaction\&. 
.PP
Definition at line 13 of file transactiondesc\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "QString TransactionDesc::toHTML (\fBCWallet\fP * wallet, \fBCWalletTx\fP & wtx, \fBTransactionRecord\fP * rec, int unit)\fC [static]\fP"

.PP
Definition at line 41 of file transactiondesc\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
