.TH "/home/dev/ds-160209/src/qt/transactionfilterproxy.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/qt/transactionfilterproxy.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'transactionfilterproxy\&.h'\fP
.br
\fC#include 'transactiontablemodel\&.h'\fP
.br
\fC#include 'transactionrecord\&.h'\fP
.br
\fC#include <QDateTime>\fP
.br
\fC#include <cstdlib>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
