.TH "/home/dev/ds-160209/src/leveldb/table/two_level_iterator.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/table/two_level_iterator.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'leveldb/iterator\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Iterator * \fBleveldb::NewTwoLevelIterator\fP (Iterator *index_iter, Iterator *(*block_function)(void *\fBarg\fP, const ReadOptions &options, const Slice &index_value), void *\fBarg\fP, const ReadOptions &options)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
