.TH "/home/dev/ds-160209/src/leveldb/table/two_level_iterator.cc" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/table/two_level_iterator.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'table/two_level_iterator\&.h'\fP
.br
\fC#include 'leveldb/table\&.h'\fP
.br
\fC#include 'table/block\&.h'\fP
.br
\fC#include 'table/format\&.h'\fP
.br
\fC#include 'table/iterator_wrapper\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Iterator * \fBleveldb::NewTwoLevelIterator\fP (Iterator *index_iter, BlockFunction block_function, void *\fBarg\fP, const ReadOptions &options)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "void* arg_"

.PP
Definition at line 66 of file two_level_iterator\&.cc\&.
.SS "BlockFunction block_function_"

.PP
Definition at line 65 of file two_level_iterator\&.cc\&.
.SS "std::string data_block_handle_"

.PP
Definition at line 73 of file two_level_iterator\&.cc\&.
.SS "IteratorWrapper data_iter_"

.PP
Definition at line 70 of file two_level_iterator\&.cc\&.
.SS "IteratorWrapper index_iter_"

.PP
Definition at line 69 of file two_level_iterator\&.cc\&.
.SS "const ReadOptions options_"

.PP
Definition at line 67 of file two_level_iterator\&.cc\&.
.SS "Status status_"

.PP
Definition at line 68 of file two_level_iterator\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
