.TH "/home/dev/ds-160209/src/txdb-leveldb.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/txdb-leveldb.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <leveldb/db\&.h>\fP
.br
\fC#include <leveldb/write_batch\&.h>\fP
.br
\fC#include 'streams\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCTxDB\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCBlockIndex\fP * \fBInsertBlockIndex\fP (\fBuint256\fP \fBhash\fP)"
.br
.RI "\fICreate a new block index entry for a given block hash\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBCBlockIndex\fP* InsertBlockIndex (\fBuint256\fP hash)"

.PP
Create a new block index entry for a given block hash\&. 
.PP
Definition at line 317 of file txdb-leveldb\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
