.TH "/home/dev/ds-160209/src/txdb.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/txdb.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'txdb\&.h'\fP
.br
\fC#include 'uint256\&.h'\fP
.br
\fC#include 'txdb-leveldb\&.h'\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <boost/thread\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBBatchWriteCoins\fP (\fBCLevelDBBatch\fP &batch, const \fBuint256\fP &\fBhash\fP, const \fBCCoins\fP &coins)"
.br
.ti -1c
.RI "void \fBBatchWriteHashBestChain\fP (\fBCLevelDBBatch\fP &batch, const \fBuint256\fP &\fBhash\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void BatchWriteCoins (\fBCLevelDBBatch\fP & batch, const \fBuint256\fP & hash, const \fBCCoins\fP & coins)"

.PP
Definition at line 16 of file txdb\&.cpp\&.
.SS "void BatchWriteHashBestChain (\fBCLevelDBBatch\fP & batch, const \fBuint256\fP & hash)"

.PP
Definition at line 23 of file txdb\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
