.TH "TxLessThan" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TxLessThan \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBTransactionRecord\fP &a, const \fBTransactionRecord\fP &b) const "
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBTransactionRecord\fP &a, const \fBuint256\fP &b) const "
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBuint256\fP &a, const \fBTransactionRecord\fP &b) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file transactiontablemodel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool TxLessThan::operator() (const \fBTransactionRecord\fP & a, const \fBTransactionRecord\fP & b) const\fC [inline]\fP"

.PP
Definition at line 33 of file transactiontablemodel\&.cpp\&.
.SS "bool TxLessThan::operator() (const \fBTransactionRecord\fP & a, const \fBuint256\fP & b) const\fC [inline]\fP"

.PP
Definition at line 37 of file transactiontablemodel\&.cpp\&.
.SS "bool TxLessThan::operator() (const \fBuint256\fP & a, const \fBTransactionRecord\fP & b) const\fC [inline]\fP"

.PP
Definition at line 41 of file transactiontablemodel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
