.TH "/home/dev/ds-160209/src/txmempool.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/txmempool.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'primitives/transaction\&.h'\fP
.br
\fC#include 'sync\&.h'\fP
.br
\fC#include 'coins\&.h'\fP
.br
\fC#include 'amount\&.h'\fP
.br
\fC#include <boost/circular_buffer\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCTxMemPoolEntry\fP"
.br
.RI "\fI\fBCTxMemPool\fP stores these: \fP"
.ti -1c
.RI "class \fBCBlockAverage\fP"
.br
.ti -1c
.RI "class \fBCMinerPolicyEstimator\fP"
.br
.ti -1c
.RI "class \fBCTxMemPool\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBAllowFreeThreshold\fP ()"
.br
.ti -1c
.RI "bool \fBAllowFree\fP (double dPriority)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool AllowFree (double dPriority)\fC [inline]\fP"

.PP
Definition at line 20 of file txmempool\&.h\&.
.SS "double AllowFreeThreshold ()\fC [inline]\fP"

.PP
Definition at line 15 of file txmempool\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
