.TH "TxPriorityCompare" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TxPriorityCompare \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTxPriorityCompare\fP (bool _byFee)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (const \fBTxPriority\fP &a, const \fBTxPriority\fP &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 84 of file miner\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TxPriorityCompare::TxPriorityCompare (bool _byFee)\fC [inline]\fP"

.PP
Definition at line 88 of file miner\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool TxPriorityCompare::operator() (const \fBTxPriority\fP & a, const \fBTxPriority\fP & b)\fC [inline]\fP"

.PP
Definition at line 89 of file miner\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
