.TH "TxViewDelegate" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TxViewDelegate \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QAbstractItemDelegate\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTxViewDelegate\fP ()"
.br
.ti -1c
.RI "void \fBpaint\fP (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const "
.br
.ti -1c
.RI "QSize \fBsizeHint\fP (const QStyleOptionViewItem &option, const QModelIndex &index) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBunit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file overviewpage\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TxViewDelegate::TxViewDelegate ()\fC [inline]\fP"

.PP
Definition at line 30 of file overviewpage\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void TxViewDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const\fC [inline]\fP"

.PP
Definition at line 35 of file overviewpage\&.cpp\&.
.SS "QSize TxViewDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const\fC [inline]\fP"

.PP
Definition at line 90 of file overviewpage\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int TxViewDelegate::unit"

.PP
Definition at line 95 of file overviewpage\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
