.TH "/home/dev/ds-160209/src/test/uint160_tests.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/test/uint160_tests.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/test/unit_test\&.hpp>\fP
.br
\fC#include 'uint256\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (uint160_equality)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (uint160_equality)"

.PP
Definition at line 7 of file uint160_tests\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
