.TH "uint160" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uint160 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uint256\&.h>\fP
.PP
Inherits \fBbase_uint< 160 >\fP\&.
.PP
Inherited by \fBCKeyID\fP, and \fBCScriptID\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBuint160\fP ()"
.br
.ti -1c
.RI "\fBuint160\fP (const \fBbase_uint\fP< 160 > &b)"
.br
.ti -1c
.RI "\fBuint160\fP (\fBuint64_t\fP b)"
.br
.ti -1c
.RI "\fBuint160\fP (const std::string &str)"
.br
.ti -1c
.RI "\fBuint160\fP (const std::vector< unsigned char > &vch)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
160-bit unsigned big integer\&. 
.PP
Definition at line 305 of file uint256\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "uint160::uint160 ()\fC [inline]\fP"

.PP
Definition at line 307 of file uint256\&.h\&.
.SS "uint160::uint160 (const \fBbase_uint\fP< 160 > & b)\fC [inline]\fP"

.PP
Definition at line 308 of file uint256\&.h\&.
.SS "uint160::uint160 (\fBuint64_t\fP b)\fC [inline]\fP"

.PP
Definition at line 309 of file uint256\&.h\&.
.SS "uint160::uint160 (const std::string & str)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 310 of file uint256\&.h\&.
.SS "uint160::uint160 (const std::vector< unsigned char > & vch)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 311 of file uint256\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
