.TH "uint512" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uint512 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uint256\&.h>\fP
.PP
Inherits \fBbase_uint< 512 >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBuint512\fP ()"
.br
.ti -1c
.RI "\fBuint512\fP (const \fBbase_uint\fP< 512 > &b)"
.br
.ti -1c
.RI "\fBuint512\fP (\fBuint64_t\fP b)"
.br
.ti -1c
.RI "\fBuint512\fP (const std::string &str)"
.br
.ti -1c
.RI "\fBuint512\fP (const std::vector< unsigned char > &vch)"
.br
.ti -1c
.RI "\fBuint256\fP \fBtrim256\fP () const "
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
512-bit unsigned big integer\&. 
.PP
Definition at line 349 of file uint256\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "uint512::uint512 ()\fC [inline]\fP"

.PP
Definition at line 351 of file uint256\&.h\&.
.SS "uint512::uint512 (const \fBbase_uint\fP< 512 > & b)\fC [inline]\fP"

.PP
Definition at line 352 of file uint256\&.h\&.
.SS "uint512::uint512 (\fBuint64_t\fP b)\fC [inline]\fP"

.PP
Definition at line 353 of file uint256\&.h\&.
.SS "uint512::uint512 (const std::string & str)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 354 of file uint256\&.h\&.
.SS "uint512::uint512 (const std::vector< unsigned char > & vch)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 355 of file uint256\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBuint256\fP uint512::trim256 () const\fC [inline]\fP"

.PP
Definition at line 357 of file uint256\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
