.TH "uint_error" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
uint_error \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uint256\&.h>\fP
.PP
Inherits runtime_error\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBuint_error\fP (const std::string &str)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file uint256\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "uint_error::uint_error (const std::string & str)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Definition at line 26 of file uint256\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
