.TH "URITests" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
URITests \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uritests\&.h>\fP
.PP
Inherits QObject\&.
.SH "Detailed Description"
.PP 
Definition at line 7 of file uritests\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
