.TH "/home/dev/ds-160209/src/leveldb/db/version_edit.cc" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/db/version_edit.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'db/version_edit\&.h'\fP
.br
\fC#include 'db/version_set\&.h'\fP
.br
\fC#include 'util/coding\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBleveldb::Tag\fP { \fBleveldb::kComparator\fP = 1, \fBleveldb::kLogNumber\fP = 2, \fBleveldb::kNextFileNumber\fP = 3, \fBleveldb::kLastSequence\fP = 4, \fBleveldb::kCompactPointer\fP = 5, \fBleveldb::kDeletedFile\fP = 6, \fBleveldb::kNewFile\fP = 7, \fBleveldb::kPrevLogNumber\fP = 9 }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
