.TH "/home/dev/ds-160209/src/leveldb/db/version_set.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/db/version_set.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <set>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'db/dbformat\&.h'\fP
.br
\fC#include 'db/version_edit\&.h'\fP
.br
\fC#include 'port/port\&.h'\fP
.br
\fC#include 'port/thread_annotations\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBleveldb::Version\fP"
.br
.ti -1c
.RI "struct \fBleveldb::Version::GetStats\fP"
.br
.ti -1c
.RI "class \fBleveldb::VersionSet\fP"
.br
.ti -1c
.RI "struct \fBleveldb::VersionSet::LevelSummaryStorage\fP"
.br
.ti -1c
.RI "class \fBleveldb::Compaction\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.ti -1c
.RI " \fBleveldb::log\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBleveldb::FindFile\fP (const InternalKeyComparator &icmp, const std::vector< FileMetaData * > &files, const Slice &key)"
.br
.ti -1c
.RI "bool \fBleveldb::SomeFileOverlapsRange\fP (const InternalKeyComparator &icmp, bool disjoint_sorted_files, const std::vector< FileMetaData * > &files, const Slice *smallest_user_key, const Slice *largest_user_key)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
