.TH "/home/dev/ds-160209/src/version.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/version.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'version\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCLIENT_VERSION_SUFFIX\fP   ''"
.br
.ti -1c
.RI "#define \fBGIT_ARCHIVE\fP   1"
.br
.ti -1c
.RI "#define \fBGIT_COMMIT_ID\fP   ''"
.br
.ti -1c
.RI "#define \fBGIT_COMMIT_DATE\fP   ''"
.br
.ti -1c
.RI "#define \fBBUILD_DESC_FROM_COMMIT\fP(maj,  min,  rev,  build,  commit)   'v' DO_STRINGIZE(maj) '\&.' \fBDO_STRINGIZE\fP(min) '\&.' \fBDO_STRINGIZE\fP(rev) '\&.' \fBDO_STRINGIZE\fP(build) '' commit"
.br
.ti -1c
.RI "#define \fBBUILD_DESC_FROM_UNKNOWN\fP(maj,  min,  rev,  build)   'v' DO_STRINGIZE(maj) '\&.' \fBDO_STRINGIZE\fP(min) '\&.' \fBDO_STRINGIZE\fP(rev) '\&.' \fBDO_STRINGIZE\fP(build) ''"
.br
.ti -1c
.RI "#define \fBBUILD_DESC\fP   \fBBUILD_DESC_FROM_COMMIT\fP(\fBCLIENT_VERSION_MAJOR\fP, \fBCLIENT_VERSION_MINOR\fP, \fBCLIENT_VERSION_REVISION\fP, \fBCLIENT_VERSION_BUILD\fP, \fBGIT_COMMIT_ID\fP)"
.br
.ti -1c
.RI "#define \fBBUILD_DATE\fP   \fBGIT_COMMIT_DATE\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const std::string \fBCLIENT_NAME\fP ('DRKSLK')"
.br
.ti -1c
.RI "const std::string \fBCLIENT_BUILD\fP (\fBBUILD_DESC\fP \fBCLIENT_VERSION_SUFFIX\fP)"
.br
.ti -1c
.RI "const std::string \fBCLIENT_DATE\fP (\fBBUILD_DATE\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUILD_DATE   \fBGIT_COMMIT_DATE\fP"

.PP
Definition at line 59 of file version\&.cpp\&.
.SS "#define BUILD_DESC   \fBBUILD_DESC_FROM_COMMIT\fP(\fBCLIENT_VERSION_MAJOR\fP, \fBCLIENT_VERSION_MINOR\fP, \fBCLIENT_VERSION_REVISION\fP, \fBCLIENT_VERSION_BUILD\fP, \fBGIT_COMMIT_ID\fP)"

.PP
Definition at line 51 of file version\&.cpp\&.
.SS "#define BUILD_DESC_FROM_COMMIT(maj, min, rev, build, commit)   'v' DO_STRINGIZE(maj) '\&.' \fBDO_STRINGIZE\fP(min) '\&.' \fBDO_STRINGIZE\fP(rev) '\&.' \fBDO_STRINGIZE\fP(build) '' commit"

.PP
Definition at line 43 of file version\&.cpp\&.
.SS "#define BUILD_DESC_FROM_UNKNOWN(maj, min, rev, build)   'v' DO_STRINGIZE(maj) '\&.' \fBDO_STRINGIZE\fP(min) '\&.' \fBDO_STRINGIZE\fP(rev) '\&.' \fBDO_STRINGIZE\fP(build) ''"

.PP
Definition at line 46 of file version\&.cpp\&.
.SS "#define CLIENT_VERSION_SUFFIX   ''"

.PP
Definition at line 14 of file version\&.cpp\&.
.SS "#define GIT_ARCHIVE   1"

.PP
Definition at line 37 of file version\&.cpp\&.
.SS "#define GIT_COMMIT_DATE   ''"

.PP
Definition at line 40 of file version\&.cpp\&.
.SS "#define GIT_COMMIT_ID   ''"

.PP
Definition at line 39 of file version\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "const std::string CLIENT_BUILD (\fBBUILD_DESC\fP CLIENT_VERSION_SUFFIX)"

.SS "const std::string CLIENT_DATE (\fBBUILD_DATE\fP)"

.SS "const std::string CLIENT_NAME ('DRKSLK')"

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
