.TH "/home/dev/ds-160209/src/version.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/version.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clientversion\&.h'\fP
.br
\fC#include <string>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBCLIENT_NAME\fP"
.br
.ti -1c
.RI "const std::string \fBCLIENT_BUILD\fP"
.br
.ti -1c
.RI "const std::string \fBCLIENT_DATE\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const std::string CLIENT_BUILD"

.SS "const std::string CLIENT_DATE"

.SS "const std::string CLIENT_NAME"

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
