.TH "WalletModel::SendCoinsReturn" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WalletModel::SendCoinsReturn \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <walletmodel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSendCoinsReturn\fP (\fBStatusCode\fP \fBstatus\fP=\fBAborted\fP, \fBCAmount\fP \fBfee\fP=0, QString \fBhex\fP=QString())"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBStatusCode\fP \fBstatus\fP"
.br
.ti -1c
.RI "\fBCAmount\fP \fBfee\fP"
.br
.ti -1c
.RI "QString \fBhex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 92 of file walletmodel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WalletModel::SendCoinsReturn::SendCoinsReturn (\fBStatusCode\fP status = \fC\fBAborted\fP\fP, \fBCAmount\fP fee = \fC0\fP, QString hex = \fCQString()\fP)\fC [inline]\fP"

.PP
Definition at line 94 of file walletmodel\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCAmount\fP WalletModel::SendCoinsReturn::fee"

.PP
Definition at line 99 of file walletmodel\&.h\&.
.SS "QString WalletModel::SendCoinsReturn::hex"

.PP
Definition at line 100 of file walletmodel\&.h\&.
.SS "\fBStatusCode\fP WalletModel::SendCoinsReturn::status"

.PP
Definition at line 98 of file walletmodel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
