.TH "WalletModel::UnlockContext" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WalletModel::UnlockContext \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <walletmodel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnlockContext\fP (\fBWalletModel\fP *wallet, bool valid, bool relock)"
.br
.ti -1c
.RI "\fB~UnlockContext\fP ()"
.br
.ti -1c
.RI "bool \fBisValid\fP () const "
.br
.ti -1c
.RI "\fBUnlockContext\fP (const \fBUnlockContext\fP &obj)"
.br
.ti -1c
.RI "\fBUnlockContext\fP & \fBoperator=\fP (const \fBUnlockContext\fP &rhs)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 117 of file walletmodel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WalletModel::UnlockContext::UnlockContext (\fBWalletModel\fP * wallet, bool valid, bool relock)"

.PP
Definition at line 656 of file walletmodel\&.cpp\&.
.SS "WalletModel::UnlockContext::~UnlockContext ()"

.PP
Definition at line 663 of file walletmodel\&.cpp\&.
.SS "WalletModel::UnlockContext::UnlockContext (const \fBUnlockContext\fP & obj)\fC [inline]\fP"

.PP
Definition at line 126 of file walletmodel\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool WalletModel::UnlockContext::isValid () const\fC [inline]\fP"

.PP
Definition at line 123 of file walletmodel\&.h\&.
.SS "\fBUnlockContext\fP& WalletModel::UnlockContext::operator= (const \fBUnlockContext\fP & rhs)\fC [inline]\fP"

.PP
Definition at line 127 of file walletmodel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
