.TH "/home/dev/ds-160209/src/walletdb.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/walletdb.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'walletdb\&.h'\fP
.br
\fC#include 'base58\&.h'\fP
.br
\fC#include 'protocol\&.h'\fP
.br
\fC#include 'serialize\&.h'\fP
.br
\fC#include 'sync\&.h'\fP
.br
\fC#include 'wallet\&.h'\fP
.br
\fC#include <boost/filesystem\&.hpp>\fP
.br
\fC#include <boost/foreach\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCWalletScanState\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBReadKeyValue\fP (\fBCWallet\fP *pwallet, \fBCDataStream\fP &ssKey, \fBCDataStream\fP &ssValue, \fBCWalletScanState\fP &wss, string &strType, string &strErr)"
.br
.ti -1c
.RI "void \fBThreadFlushWalletDB\fP (const string &strFile)"
.br
.ti -1c
.RI "bool \fBBackupWallet\fP (const \fBCWallet\fP &wallet, const string &strDest)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "bool \fBfWalletUnlockStakingOnly\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool BackupWallet (const \fBCWallet\fP & wallet, const string & strDest)"

.PP
Definition at line 794 of file walletdb\&.cpp\&.
.SS "bool ReadKeyValue (\fBCWallet\fP * pwallet, \fBCDataStream\fP & ssKey, \fBCDataStream\fP & ssValue, \fBCWalletScanState\fP & wss, string & strType, string & strErr)"

.PP
Definition at line 357 of file walletdb\&.cpp\&.
.SS "void ThreadFlushWalletDB (const string & strFile)"

.PP
Definition at line 732 of file walletdb\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "bool fWalletUnlockStakingOnly"

.PP
Definition at line 166 of file wallet\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
