.TH "/home/dev/ds-160209/src/test/wallet_tests.cpp" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/test/wallet_tests.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/test/unit_test\&.hpp>\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'wallet\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRUN_TESTS\fP   100"
.br
.ti -1c
.RI "#define \fBRANDOM_REPEATS\fP   5"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef set< pair< const \fBCWalletTx\fP *, unsigned int > > \fBCoinSet\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBOOST_AUTO_TEST_CASE\fP (coin_selection_tests)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RANDOM_REPEATS   5"

.PP
Definition at line 11 of file wallet_tests\&.cpp\&.
.SS "#define RUN_TESTS   100"

.PP
Definition at line 7 of file wallet_tests\&.cpp\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef set<pair<const \fBCWalletTx\fP*,unsigned int> > \fBCoinSet\fP"

.PP
Definition at line 15 of file wallet_tests\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "BOOST_AUTO_TEST_CASE (coin_selection_tests)"

.PP
Definition at line 56 of file wallet_tests\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
