.TH "/home/dev/ds-160209/src/walletdb.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/walletdb.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'db\&.h'\fP
.br
\fC#include 'keystore\&.h'\fP
.br
\fC#include 'stealth\&.h'\fP
.br
\fC#include 'amount\&.h'\fP
.br
\fC#include <list>\fP
.br
\fC#include <string>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCKeyMetadata\fP"
.br
.ti -1c
.RI "class \fBCStealthKeyMetadata\fP"
.br
.ti -1c
.RI "class \fBCWalletDB\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDBErrors\fP { \fBDB_LOAD_OK\fP, \fBDB_CORRUPT\fP, \fBDB_NONCRITICAL_ERROR\fP, \fBDB_TOO_NEW\fP, \fBDB_LOAD_FAIL\fP, \fBDB_NEED_REWRITE\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBBackupWallet\fP (const \fBCWallet\fP &wallet, const std::string &strDest)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBDBErrors\fP"
Error statuses for the wallet database 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDB_LOAD_OK \fP\fP
.TP
\fB\fIDB_CORRUPT \fP\fP
.TP
\fB\fIDB_NONCRITICAL_ERROR \fP\fP
.TP
\fB\fIDB_TOO_NEW \fP\fP
.TP
\fB\fIDB_LOAD_FAIL \fP\fP
.TP
\fB\fIDB_NEED_REWRITE \fP\fP
.PP
Definition at line 31 of file walletdb\&.h\&.
.SH "Function Documentation"
.PP 
.SS "bool BackupWallet (const \fBCWallet\fP & wallet, const std::string & strDest)"

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
