.TH "/home/dev/ds-160209/src/wallet.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/wallet.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'walletdb\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'primitives/block\&.h'\fP
.br
\fC#include 'primitives/transaction\&.h'\fP
.br
\fC#include 'crypter\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'key\&.h'\fP
.br
\fC#include 'keystore\&.h'\fP
.br
\fC#include 'script\&.h'\fP
.br
\fC#include 'ui_interface\&.h'\fP
.br
\fC#include 'util\&.h'\fP
.br
\fC#include 'stealth\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCKeyPool\fP"
.br
.ti -1c
.RI "class \fBCWallet\fP"
.br
.ti -1c
.RI "class \fBCReserveKey\fP"
.br
.ti -1c
.RI "class \fBCWalletTx\fP"
.br
.ti -1c
.RI "class \fBCOutput\fP"
.br
.ti -1c
.RI "class \fBCWalletKey\fP"
.br
.ti -1c
.RI "class \fBCAccount\fP"
.br
.ti -1c
.RI "class \fBCAccountingEntry\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::map< \fBCKeyID\fP, \fBCStealthKeyMetadata\fP > \fBStealthKeyMetaMap\fP"
.br
.ti -1c
.RI "typedef std::map< std::string, std::string > \fBmapValue_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBWalletFeature\fP { \fBFEATURE_BASE\fP = 10500, \fBFEATURE_WALLETCRYPT\fP = 40000, \fBFEATURE_COMPRPUBKEY\fP = 60141, \fBFEATURE_LATEST\fP = 60141 }"
.br
.ti -1c
.RI "enum \fBAvailableCoinsType\fP { \fBALL_COINS\fP = 1, \fBONLY_DENOMINATED\fP = 2, \fBONLY_NONDENOMINATED\fP = 3, \fBONLY_NONDENOMINATED_NOTSN\fP = 4 }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBCAmount\fP \fBMIN_TX_FEE\fP = 10000"
.br
.ti -1c
.RI "const \fBCAmount\fP \fBMIN_RELAY_TX_FEE\fP = \fBMIN_TX_FEE\fP"
.br
.RI "\fIFees smaller than this (in satoshi) are considered zero fee (for relaying) \fP"
.ti -1c
.RI "\fBCAmount\fP \fBnTransactionFee\fP"
.br
.ti -1c
.RI "\fBCAmount\fP \fBnReserveBalance\fP"
.br
.ti -1c
.RI "\fBCAmount\fP \fBnMinimumInputValue\fP"
.br
.ti -1c
.RI "bool \fBfWalletUnlockStakingOnly\fP"
.br
.ti -1c
.RI "bool \fBfConfChange\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::map< std::string, std::string > \fBmapValue_t\fP"

.PP
Definition at line 47 of file wallet\&.h\&.
.SS "typedef std::map<\fBCKeyID\fP, \fBCStealthKeyMetadata\fP> \fBStealthKeyMetaMap\fP"

.PP
Definition at line 44 of file wallet\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBAvailableCoinsType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIALL_COINS \fP\fP
.TP
\fB\fIONLY_DENOMINATED \fP\fP
.TP
\fB\fIONLY_NONDENOMINATED \fP\fP
.TP
\fB\fIONLY_NONDENOMINATED_NOTSN \fP\fP
.PP
Definition at line 60 of file wallet\&.h\&.
.SS "enum \fBWalletFeature\fP"
(client) version numbers for particular wallet features 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFEATURE_BASE \fP\fP
.TP
\fB\fIFEATURE_WALLETCRYPT \fP\fP
.TP
\fB\fIFEATURE_COMPRPUBKEY \fP\fP
.TP
\fB\fIFEATURE_LATEST \fP\fP
.PP
Definition at line 50 of file wallet\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "bool fConfChange"

.PP
Definition at line 53 of file init\&.cpp\&.
.SS "bool fWalletUnlockStakingOnly"

.PP
Definition at line 166 of file wallet\&.cpp\&.
.SS "const \fBCAmount\fP MIN_RELAY_TX_FEE = \fBMIN_TX_FEE\fP"

.PP
Fees smaller than this (in satoshi) are considered zero fee (for relaying) 
.PP
Definition at line 29 of file wallet\&.h\&.
.SS "const \fBCAmount\fP MIN_TX_FEE = 10000"

.PP
Definition at line 27 of file wallet\&.h\&.
.SS "\fBCAmount\fP nMinimumInputValue"

.PP
Definition at line 42 of file wallet\&.cpp\&.
.SS "\fBCAmount\fP nReserveBalance"

.PP
Definition at line 41 of file wallet\&.cpp\&.
.SS "\fBCAmount\fP nTransactionFee"

.PP
Definition at line 40 of file wallet\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
