.TH "/home/dev/ds-160209/src/leveldb/db/write_batch_test.cc" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/leveldb/db/write_batch_test.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'leveldb/db\&.h'\fP
.br
\fC#include 'db/memtable\&.h'\fP
.br
\fC#include 'db/write_batch_internal\&.h'\fP
.br
\fC#include 'leveldb/env\&.h'\fP
.br
\fC#include 'util/logging\&.h'\fP
.br
\fC#include 'util/testharness\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBleveldb::WriteBatchTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBleveldb\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBleveldb::TEST\fP (WriteBatchTest, Empty)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (WriteBatchTest, Multiple)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (WriteBatchTest, Corruption)"
.br
.ti -1c
.RI "\fBleveldb::TEST\fP (WriteBatchTest, Append)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 118 of file write_batch_test\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
