.TH "XXH32_stateSpace_t" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XXH32_stateSpace_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <xxhash\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long long \fBll\fP [(\fBXXH32_SIZEOFSTATE\fP+(sizeof(long long)-1))/sizeof(long long)]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 128 of file xxhash\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "long long XXH32_stateSpace_t::ll[(\fBXXH32_SIZEOFSTATE\fP+(sizeof(long long)-1))/sizeof(long long)]"

.PP
Definition at line 128 of file xxhash\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
