.TH "XXH_state32_t" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XXH_state32_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBU64\fP \fBtotal_len\fP"
.br
.ti -1c
.RI "\fBU32\fP \fBseed\fP"
.br
.ti -1c
.RI "\fBU32\fP \fBv1\fP"
.br
.ti -1c
.RI "\fBU32\fP \fBv2\fP"
.br
.ti -1c
.RI "\fBU32\fP \fBv3\fP"
.br
.ti -1c
.RI "\fBU32\fP \fBv4\fP"
.br
.ti -1c
.RI "int \fBmemsize\fP"
.br
.ti -1c
.RI "char \fBmemory\fP [16]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 298 of file xxhash\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "char XXH_state32_t::memory[16]"

.PP
Definition at line 307 of file xxhash\&.c\&.
.SS "int XXH_state32_t::memsize"

.PP
Definition at line 306 of file xxhash\&.c\&.
.SS "\fBU32\fP XXH_state32_t::seed"

.PP
Definition at line 301 of file xxhash\&.c\&.
.SS "\fBU64\fP XXH_state32_t::total_len"

.PP
Definition at line 300 of file xxhash\&.c\&.
.SS "\fBU32\fP XXH_state32_t::v1"

.PP
Definition at line 302 of file xxhash\&.c\&.
.SS "\fBU32\fP XXH_state32_t::v2"

.PP
Definition at line 303 of file xxhash\&.c\&.
.SS "\fBU32\fP XXH_state32_t::v3"

.PP
Definition at line 304 of file xxhash\&.c\&.
.SS "\fBU32\fP XXH_state32_t::v4"

.PP
Definition at line 305 of file xxhash\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
