.TH "/home/dev/ds-160209/src/xxhash/xxhash.c" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/xxhash/xxhash.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'xxhash\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB_U32_S\fP"
.br
.ti -1c
.RI "struct \fBXXH_state32_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBXXH_FORCE_NATIVE_FORMAT\fP   0"
.br
.ti -1c
.RI "#define \fBFORCE_INLINE\fP   static inline"
.br
.ti -1c
.RI "#define \fB_PACKED_XXH\fP"
.br
.ti -1c
.RI "#define \fBA32_XXH\fP(x)   (((\fBU32_S_XXH\fP *)(x))->v)"
.br
.ti -1c
.RI "#define \fBGCC_VERSION\fP   (__GNUC__ * 100 + __GNUC_MINOR__)"
.br
.ti -1c
.RI "#define \fBXXH_rotl32\fP(x,  r)   ((x << r) | (x >> (32 - r)))"
.br
.ti -1c
.RI "#define \fBPRIME32_1\fP   2654435761U"
.br
.ti -1c
.RI "#define \fBPRIME32_2\fP   2246822519U"
.br
.ti -1c
.RI "#define \fBPRIME32_3\fP   3266489917U"
.br
.ti -1c
.RI "#define \fBPRIME32_4\fP   668265263U"
.br
.ti -1c
.RI "#define \fBPRIME32_5\fP   374761393U"
.br
.ti -1c
.RI "#define \fBXXH_CPU_LITTLE_ENDIAN\fP   (*(char*)(&one))"
.br
.ti -1c
.RI "#define \fBXXH_STATIC_ASSERT\fP(c)   { enum { XXH_static_assert = 1/(!!(c)) }; }"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBBYTE\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBU16\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBU32\fP"
.br
.ti -1c
.RI "typedef signed int \fBS32\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBU64\fP"
.br
.ti -1c
.RI "typedef struct \fB_U32_S\fP \fBU32_S_XXH\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBXXH_endianess\fP { \fBXXH_bigEndian\fP =0, \fBXXH_littleEndian\fP =1 }"
.br
.ti -1c
.RI "enum \fBXXH_alignment\fP { \fBXXH_aligned\fP, \fBXXH_unaligned\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFORCE_INLINE\fP void * \fBXXH_malloc\fP (size_t s)"
.br
.ti -1c
.RI "\fBFORCE_INLINE\fP void \fBXXH_free\fP (void *p)"
.br
.ti -1c
.RI "\fBFORCE_INLINE\fP void * \fBXXH_memcpy\fP (void *dest, const void *src, size_t size)"
.br
.ti -1c
.RI "\fBFORCE_INLINE\fP \fBU32\fP \fBXXH_readLE32_align\fP (const \fBU32\fP *ptr, \fBXXH_endianess\fP endian, \fBXXH_alignment\fP align)"
.br
.ti -1c
.RI "\fBFORCE_INLINE\fP \fBU32\fP \fBXXH_readLE32\fP (const \fBU32\fP *ptr, \fBXXH_endianess\fP endian)"
.br
.ti -1c
.RI "\fBFORCE_INLINE\fP \fBU32\fP \fBXXH32_endian_align\fP (const void *input, int len, \fBU32\fP seed, \fBXXH_endianess\fP endian, \fBXXH_alignment\fP align)"
.br
.ti -1c
.RI "\fBU32\fP \fBXXH32\fP (const void *input, int len, \fBU32\fP seed)"
.br
.ti -1c
.RI "int \fBXXH32_sizeofState\fP ()"
.br
.ti -1c
.RI "\fBXXH_errorcode\fP \fBXXH32_resetState\fP (void *state_in, \fBU32\fP seed)"
.br
.ti -1c
.RI "void * \fBXXH32_init\fP (\fBU32\fP seed)"
.br
.ti -1c
.RI "\fBFORCE_INLINE\fP \fBXXH_errorcode\fP \fBXXH32_update_endian\fP (void *state_in, const void *input, int len, \fBXXH_endianess\fP endian)"
.br
.ti -1c
.RI "\fBXXH_errorcode\fP \fBXXH32_update\fP (void *state_in, const void *input, int len)"
.br
.ti -1c
.RI "\fBFORCE_INLINE\fP \fBU32\fP \fBXXH32_intermediateDigest_endian\fP (void *state_in, \fBXXH_endianess\fP endian)"
.br
.ti -1c
.RI "\fBU32\fP \fBXXH32_intermediateDigest\fP (void *state_in)"
.br
.ti -1c
.RI "\fBU32\fP \fBXXH32_digest\fP (void *state_in)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _PACKED_XXH"

.PP
Definition at line 116 of file xxhash\&.c\&.
.SS "#define A32_XXH(x)   (((\fBU32_S_XXH\fP *)(x))->v)"

.PP
Definition at line 134 of file xxhash\&.c\&.
.SS "#define FORCE_INLINE   static inline"

.PP
Definition at line 76 of file xxhash\&.c\&.
.SS "#define GCC_VERSION   (__GNUC__ * 100 + __GNUC_MINOR__)"

.PP
Definition at line 140 of file xxhash\&.c\&.
.SS "#define PRIME32_1   2654435761U"

.PP
Definition at line 165 of file xxhash\&.c\&.
.SS "#define PRIME32_2   2246822519U"

.PP
Definition at line 166 of file xxhash\&.c\&.
.SS "#define PRIME32_3   3266489917U"

.PP
Definition at line 167 of file xxhash\&.c\&.
.SS "#define PRIME32_4   668265263U"

.PP
Definition at line 168 of file xxhash\&.c\&.
.SS "#define PRIME32_5   374761393U"

.PP
Definition at line 169 of file xxhash\&.c\&.
.SS "#define XXH_CPU_LITTLE_ENDIAN   (*(char*)(&one))"

.PP
Definition at line 178 of file xxhash\&.c\&.
.SS "#define XXH_FORCE_NATIVE_FORMAT   0"

.PP
Definition at line 59 of file xxhash\&.c\&.
.SS "#define XXH_rotl32(x, r)   ((x << r) | (x >> (32 - r)))"

.PP
Definition at line 146 of file xxhash\&.c\&.
.SS "#define XXH_STATIC_ASSERT(c)   { enum { XXH_static_assert = 1/(!!(c)) }; }"

.PP
Definition at line 185 of file xxhash\&.c\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned char \fBBYTE\fP"

.PP
Definition at line 106 of file xxhash\&.c\&.
.SS "typedef signed int \fBS32\fP"

.PP
Definition at line 109 of file xxhash\&.c\&.
.SS "typedef unsigned short \fBU16\fP"

.PP
Definition at line 107 of file xxhash\&.c\&.
.SS "typedef unsigned int \fBU32\fP"

.PP
Definition at line 108 of file xxhash\&.c\&.
.SS "typedef struct \fB_U32_S\fP \fBU32_S_XXH\fP"

.SS "typedef unsigned long long \fBU64\fP"

.PP
Definition at line 110 of file xxhash\&.c\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBXXH_alignment\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIXXH_aligned \fP\fP
.TP
\fB\fIXXH_unaligned \fP\fP
.PP
Definition at line 191 of file xxhash\&.c\&.
.SS "enum \fBXXH_endianess\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIXXH_bigEndian \fP\fP
.TP
\fB\fIXXH_littleEndian \fP\fP
.PP
Definition at line 175 of file xxhash\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBU32\fP XXH32 (const void * input, int len, \fBU32\fP seed)"

.PP
Definition at line 266 of file xxhash\&.c\&.
.SS "\fBU32\fP XXH32_digest (void * state_in)"

.PP
Definition at line 469 of file xxhash\&.c\&.
.SS "\fBFORCE_INLINE\fP \fBU32\fP XXH32_endian_align (const void * input, int len, \fBU32\fP seed, \fBXXH_endianess\fP endian, \fBXXH_alignment\fP align)"

.PP
Definition at line 207 of file xxhash\&.c\&.
.SS "void* XXH32_init (\fBU32\fP seed)"

.PP
Definition at line 332 of file xxhash\&.c\&.
.SS "\fBU32\fP XXH32_intermediateDigest (void * state_in)"

.PP
Definition at line 458 of file xxhash\&.c\&.
.SS "\fBFORCE_INLINE\fP \fBU32\fP XXH32_intermediateDigest_endian (void * state_in, \fBXXH_endianess\fP endian)"

.PP
Definition at line 416 of file xxhash\&.c\&.
.SS "\fBXXH_errorcode\fP XXH32_resetState (void * state_in, \fBU32\fP seed)"

.PP
Definition at line 318 of file xxhash\&.c\&.
.SS "int XXH32_sizeofState (void)"

.PP
Definition at line 311 of file xxhash\&.c\&.
.SS "\fBXXH_errorcode\fP XXH32_update (void * state_in, const void * input, int len)"

.PP
Definition at line 404 of file xxhash\&.c\&.
.SS "\fBFORCE_INLINE\fP \fBXXH_errorcode\fP XXH32_update_endian (void * state_in, const void * input, int len, \fBXXH_endianess\fP endian)"

.PP
Definition at line 340 of file xxhash\&.c\&.
.SS "\fBFORCE_INLINE\fP void XXH_free (void * p)"

.PP
Definition at line 89 of file xxhash\&.c\&.
.SS "\fBFORCE_INLINE\fP void* XXH_malloc (size_t s)"

.PP
Definition at line 88 of file xxhash\&.c\&.
.SS "\fBFORCE_INLINE\fP void* XXH_memcpy (void * dest, const void * src, size_t size)"

.PP
Definition at line 92 of file xxhash\&.c\&.
.SS "\fBFORCE_INLINE\fP \fBU32\fP XXH_readLE32 (const \fBU32\fP * ptr, \fBXXH_endianess\fP endian)"

.PP
Definition at line 201 of file xxhash\&.c\&.
.SS "\fBFORCE_INLINE\fP \fBU32\fP XXH_readLE32_align (const \fBU32\fP * ptr, \fBXXH_endianess\fP endian, \fBXXH_alignment\fP align)"

.PP
Definition at line 193 of file xxhash\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
