.TH "/home/dev/ds-160209/src/xxhash/xxhash.h" 3 "Wed Feb 10 2016" "Version 1.0.0.0" "darksilk" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dev/ds-160209/src/xxhash/xxhash.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBXXH32_stateSpace_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBXXH32_SIZEOFSTATE\fP   48"
.br
.ti -1c
.RI "#define \fBXXH32_feed\fP   \fBXXH32_update\fP"
.br
.ti -1c
.RI "#define \fBXXH32_result\fP   \fBXXH32_digest\fP"
.br
.ti -1c
.RI "#define \fBXXH32_getIntermediateResult\fP   \fBXXH32_intermediateDigest\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBXXH_errorcode\fP { \fBXXH_OK\fP =0, \fBXXH_ERROR\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBXXH32\fP (const void *input, int len, unsigned int seed)"
.br
.ti -1c
.RI "void * \fBXXH32_init\fP (unsigned int seed)"
.br
.ti -1c
.RI "\fBXXH_errorcode\fP \fBXXH32_update\fP (void *\fBstate\fP, const void *input, int len)"
.br
.ti -1c
.RI "unsigned int \fBXXH32_digest\fP (void *\fBstate\fP)"
.br
.ti -1c
.RI "int \fBXXH32_sizeofState\fP (void)"
.br
.ti -1c
.RI "\fBXXH_errorcode\fP \fBXXH32_resetState\fP (void *\fBstate\fP, unsigned int seed)"
.br
.ti -1c
.RI "unsigned int \fBXXH32_intermediateDigest\fP (void *\fBstate\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define XXH32_feed   \fBXXH32_update\fP"

.PP
Definition at line 156 of file xxhash\&.h\&.
.SS "#define XXH32_getIntermediateResult   \fBXXH32_intermediateDigest\fP"

.PP
Definition at line 158 of file xxhash\&.h\&.
.SS "#define XXH32_result   \fBXXH32_digest\fP"

.PP
Definition at line 157 of file xxhash\&.h\&.
.SS "#define XXH32_SIZEOFSTATE   48"

.PP
Definition at line 127 of file xxhash\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBXXH_errorcode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIXXH_OK \fP\fP
.TP
\fB\fIXXH_ERROR \fP\fP
.PP
Definition at line 70 of file xxhash\&.h\&.
.SH "Function Documentation"
.PP 
.SS "unsigned int XXH32 (const void * input, int len, unsigned int seed)"

.PP
Definition at line 266 of file xxhash\&.c\&.
.SS "unsigned int XXH32_digest (void * state)"

.PP
Definition at line 469 of file xxhash\&.c\&.
.SS "void* XXH32_init (unsigned int seed)"

.PP
Definition at line 332 of file xxhash\&.c\&.
.SS "unsigned int XXH32_intermediateDigest (void * state)"

.PP
Definition at line 458 of file xxhash\&.c\&.
.SS "\fBXXH_errorcode\fP XXH32_resetState (void * state, unsigned int seed)"

.PP
Definition at line 318 of file xxhash\&.c\&.
.SS "int XXH32_sizeofState (void)"

.PP
Definition at line 311 of file xxhash\&.c\&.
.SS "\fBXXH_errorcode\fP XXH32_update (void * state, const void * input, int len)"

.PP
Definition at line 404 of file xxhash\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for darksilk from the source code\&.
